### ISSUE TITLE
TNBC.CMS

### ISSUE THREAD

**Issue by nachoryu** [Bioconductor/Contributions#1035]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nachoryu/TNBC.CMS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your functions should support [SummarizedfExperiment][1] as input data type in addition to plain matrix representations, for more robust management of assay and phenotype data, and for better interoperability with other Bioconductor packages; the vignette should be updated to use SummarizedExperiment.

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by nachoryu** [comment]
Hello @mtmorgan and @hpages,
I have a question about the following time out errors from BiocCheck. 

This is BiocCheck version 1.19.26. BiocCheck is a work in progress.
Output and severity of issues may change. Installing package...
* Checking Package Dependencies...
* Checking if other packages can import this one...
* Checking to see if we understand object initialization...
* Checking for deprecated package usage...
Warning in readLines(file, skipNul = TRUE) :
  InternetOpenUrl failed: 'The operation timed out'
Error in readLines(file, skipNul = TRUE) : cannot open the connection
Calls: <Anonymous> ... checkDeprecatedPackages -> getAllDeprecatedPkgs -> read.dcf -> readLines
Execution halted


This is BiocCheck version 1.19.26. BiocCheck is a work in progress.
Output and severity of issues may change. Installing package...
* Checking Package Dependencies...
* Checking if other packages can import this one...
* Checking to see if we understand object initialization...
* Checking for deprecated package usage...
* Checking for remote package usage...
* Checking version number...
* Checking for version number mismatch...
* Checking new package version number...
* Checking R Version dependency...
    * WARNING: Update R version dependency from 3.4.0 to 3.6.
* Checking package size...
* Checking individual file sizes...
* Checking biocViews...
* Checking that biocViews are present...
* Checking package type based on biocViews...
    Software
* Checking for non-trivial biocViews...
* Checking that biocViews come from the same category...
* Checking biocViews validity...
* Checking for recommended biocViews...
 ERROR
TIMEOUT: R CMD BiocCheck exceeded 10mins

I did not receive this type of timeout error when I ran BiocCheck on my machines (Linux, Windows, and MacOs), and I wonder if this error is related to bioc-issue-bot or my package. 
Thank you.

Best,

Doyeong

**Comment by mtmorgan** [comment]
Internet connections are very fragile, and it looks like this connection simply failed. If you are downloading large files, consider instead making them available as an 'experiment data' package or [ExperimentHub][1] resource (see the vignette 'Creating an ExperimentHub package'), or using [BiocFileCache][2] to reduce the exposure to the internet

[1]: https://bioconductor.org/packages/devel/ExperimentHub
[2]: https://bioconductor.org/packages/devel/BiocFileCache

**Comment by nachoryu** [comment]
Hello, @mtmorgan and @hpages,
sorry to bother you with this question. 
I received the following warning from the R CMD check: 

* checking for future file timestamps ...Warning in file(con, "r") :
  cannot open URL 'http://worldclockapi.com/api/json/utc/now': HTTP status was '403 Forbidden'
 WARNING

I thought it might be due to the time zone difference (as I live in Korea) and changed the time stamps of the files, but I still received this error. I encountered the HTTP status error when I accessed the URL, so I wonder if this warning is due to the problem of the URL. 

Thanks,

Doyeong

**Comment by mtmorgan** [comment]
> I received the following warning from the R CMD check:
> 
> * checking for future file timestamps ...Warning in file(con, "r") :
>   cannot open URL 'http://worldclockapi.com/api/json/utc/now': HTTP status was '403 Forbidden'
>   WARNING

R uses the URL as part of its internal checks, the URL is not available. There is nothing that you can do so please ignore this.

**Comment by nachoryu** [comment]
The package was built without errors and warnings except those from future file timestamps and the check time warning in one platform (5 minutes and 21.91 seconds). If I can ignore those warnings from timestamps, is the package ready for the review? or are there any problems I should address prior to the review? 

Thanks,

Doyeong

**Comment by nachoryu** [comment]
Hello @hpages  and @mtmorgan,

The package built without errors and warnings on all platforms. Since I will be on vacation for a month soon, I wonder whether it is ready for an initial review and when the review will be done. 

Thanks,

Doyeong

**Comment by hpages** [comment]
Hi @nachoryu ,

Thanks for submitting TNBC.CMS . The package is well crafted, well documented, and meets all our guidelines. Congratulations!

H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nachoryu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TNBC.CMS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TNBC.CMS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
