### ISSUE TITLE
uSORT: A self-refining ordering pipeline for gene selection

### ISSUE THREAD

**Issue by haoeric** [Bioconductor/Contributions#104]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JinmiaoChenLab/uSORT

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by haoeric** [comment]
Hi @hpages, the above report shows that there is a warning on linux platform, which is due to "no DISPLAY variable so Tk is not available". Our uSORT package comes together with a GUI, which is built using tcltk package. Could you help me how I can address this warning to pass the bioCheck?

Thanks very much,
Chen Hao

**Comment by haoeric** [comment]
Dear @hpages, can you help us take a look at our **uSORT** package, thanks a lot.

**Comment by hpages** [comment]
Hi Chen Hao,

Thanks for your submission and for your patience. Let's ignore this warning on Linux for now. The package satisfies our guidelines and will be added to our Subversion repository and build system in the next days. You'll also receive an email with further details about this.

Regards,
H.

**Comment by haoeric** [comment]
Dear @hpages, thanks very much.

**Comment by haoeric** [comment]
Dear @hpages, thanks very much.

Sorry that I closed the issue just now by mistake.
