### ISSUE TITLE
clusterSeq

### ISSUE THREAD

**Issue by tjh48** [Bioconductor/Contributions#105]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/tjh48/clusterSeq

Confirm the following by editing each check box to '[x]'
- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [ x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by lshep** [comment]
Thank you for your submission. 

I will review and work through your code and respond back with any suggestions or comments soon. In the meantime, we would appreciate if you could work on fixing some of the WARNINGS and NOTES generated in the build report. 

1. For the compressed data warning, if you run 
`R CMD build --resave-data clusterSeq`
This will create a tarball that has the data files compressed as small as possible. Untar this file and copy the data files in it over the ones in your git working copy and then recommit those. 

2. Please add the suggested importFrom to the NAMESPACE to fix the 'no visible global function' and updated the DESCRIPTION file as necessary 
importFrom("graphics", "lines", "plot")
importFrom("stats", "as.dist", "cutree", "hclust", "kmeans", "median",
             "runif", "sd")
importFrom("utils", "object.size", "read.table")

3. Please try and also correct the 'no visible binding for global variable'  See `?globalVariables`

4. Please consider adding the biocViews GeneExpression and Clustering if appropriate 

5. Add non empty \value section to the man pages cD.ratThymus-data.Rd, ratThymus-data.Rd. 

6. Add baySeq import in the NAMESPACE and remove  "::"  in any R code. 

I will respond with any further comments or suggestions shortly. Thank you.

**Comment by tjh48** [comment]
Fixed these, except for 5, in line with R manual guidance on documenting data sets:

2.1.2 Documenting data sets
The structure of Rd files which document R data sets is slightly different. Sections such as \arguments and \value are not needed but the format and source of the data should be explained.

Thanks

Tom

**Comment by lshep** [comment]
Can you please push these changes and do a version bump in the DESCRIPTION so a new build is started.

**Comment by lshep** [comment]
Thank you for making those changes.  Please see the following: 

General: 
1. From the build report:  please update R dependency from 3.0.0 to 3.3  in Description 
2. It seems like you are using another package you maintain baySeq, mainly the countData object.  You are pulling out data a lot with the @ .  You might consider if this is something not only you as a developer will be accessing but potentially the user may access,  to update the baySeq::countData accessor methods to include these as we don't encourage direct access to an object internal structure. It is not a necessity but just something to keep aware. 

Vignette: 
1. There is a mismatch / extra code after the \end{document}  Please remove or relocate
2. There are missing citations and empty footnotes 
3. Please remove any commented out sections
4. The last statement seems to be an incomplete sentence 
5.  I realize that kCluster can take both a matrix and the baySeq::countData object as an argument.  It would be nice if either countData object is shown as well or at least mentioned as an option. We like to show consistency and interconnectivity of bioconductor packages.  

R code: 
1. I noticed you took out summariseStability in the vignette and it is no longer exported or documented.  can it be removed? 
2. kCluster2.R  seems to hold an internal function as well but it doesn't seem to be utilized anywhere. Can this be removed? 

Man pages: 
1. Please remove any "::"  in the man page examples.  This shouldn't be needed
2. Please remove any lingering comments. See example but there are others: 
(% Add one or more standard keywords, see file 'KEYWORDS' in the
% R documentation directory)


Also, it seemed like the autobuild after the Description version bump didn't happen. This could have been on our end as we were making some updates to the build system earlier in the week but if you could check that your [webhook is set up](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) we would appreciate it.

Thank you
Lori

**Comment by tjh48** [comment]
Hi Lori. Updates made. 

There seems to be a problem with the builder (or my implementation of the webhook). I've pulled the current clusterSeq off github and built it on a new machine, which works perfectly well, but the bioconductor builder fails badly.

Thanks,

Tom

**Comment by tjh48** [comment]
Seems to be fixed now - thanks!

**Comment by lshep** [comment]
Thank you for your recent updates.  A few more minor changes below to address: 

**VIGNETTE** 
Please add a section for installation before the library call 
```
source("http://www.bioconductor.org/biocLite.R")
biocLite("clusterSeq")
```

**MAN** 
ratThymus-data.Rd
Mixed "  '  "  and "  \` "  for  matrix(\`mobData')

kcluster.Rd 
It would be nice to see a demonstration using a countData object in addition to the matrix. 

**R code**
1. use seq_len()/seq_along() rather than 1:n/1:length(x) where appropriate
2. remove .Random.seed from clusterSeq-internal.R as it does not appear to be used anywhere.
3. The output created from makeClusters and makeClusterFF appear to be lists of numeric/integer. Please change the output to use the exisiting S4Vector infastructure NumericList / IntegerList from the IRanges package. This allows the output to be more structured.  This can be accomplished through a simple conversion before returning the object in the functions: i.e  `as(current_list, "NumericList") `

**Comment by lshep** [comment]
Hello, 
It looks like you saved a .Random.seed when you saved your data object in cD.ratThymus.RData . Please   remove this. 

```
> load("cD.ratThymus.RData")
> ls(all.names=TRUE)
[1] "cD.ratThymus" ".Random.seed"
```

This may be causing the new ERROR.

**Comment by tjh48** [comment]
I don't think this has anything to do with the saved object, but appears because a baySeq object is loaded, which causes the required packages (specifically, BiocGenerics) to import into the R session. I can duplicate this behaviour thusly:

> library(BiocGenerics)
> ls(all.names = TRUE)
[1] ".Random.seed"

The errors in the build report seem to be a failure of the parallelisation on the build servers. I will look at disabling this for the vignette/examples.

**Comment by lshep** [comment]
Were you planning on resubmitting before the release deadline?

**Comment by tjh48** [comment]
Sorry - other projects had to take priority. I guess this package will have to wait for the next release.

**Comment by lshep** [comment]
looking into this issue.

**Comment by lshep** [comment]
You can ignore the warning about the version number; this is on our end. I will review and get back to you. 
On a quick glance, it seems like with the recent changes the build and check times have almost doubled. Is this expected?

**Comment by tjh48** [comment]
Not entirely expected, but probably due to changes I've made to the default BiocParallel settings for out-of-the-box running on Windows operating system.

**Comment by lshep** [comment]
The package has to be able to run R CMD check --no-build-vignettes in under 5 minutes.  Is there a way to simplify the examples or vignette, or reduce size of the data object utilized?

**Comment by lshep** [comment]
Some additional points: 

- [ ] reducing the size of the data used in vignettes and examples would be helpful to try and reduce the time for R CMD check --no-build-vignettes

- [ ] In your vignette code chunk 11 takes awhile.  It also asks for 24 cores. It is recommended to use BiocParallel to detect the cores. There should be an internal check that queries the OS for max workers.  If an explicit number of cores is requested, in the documentation the default is 4 cores, it should probably be reduced to <= 4.   Code chunk 9 also requests 24 cores; this should also be changed to <=4.  These are the calls to kCluster. 

- [ ] default BPPARAM should be bpparam() not SnowParam. BiocParallel detects the OS and decides which param is appropriate. Was there a reason SnowParam() was used as the default for the 'BP' arg in associatePosteriors() and kCluster(). The usual approach is to use BP = bpparam() since bpparam() will detect the OS and choose the appropriate back-end and the approprate number of cores.

**Comment by tjh48** [comment]
Testing on build - will check to see time taken for examples. Build is rapid on my test machine so trying to find time on Bioconductor builds.

**Comment by lshep** [comment]
I'm not exactly sure what is causing the latex ERROR.  I went on the system and built and checked the package manually and it seemed to be okay.  I will accept the package but please be advised once the package is moved to the daily build system if this ERROR persists we would expect you attention in a timely manner.  Please keep the issue open until you receive svn instructions via email for upload to Bioconductor. Thank you for your time and effort.
