### ISSUE TITLE
readat

### ISSUE THREAD

**Issue by richierocks** [Bioconductor/Contributions#106]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/graumannlab/readat

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by richierocks** [comment]
See also previous failed attempt at conbtributing

https://github.com/Bioconductor/Contributions/issues/102

**Comment by richierocks** [comment]
I'm getting an error on `mosquato` stating that the dependency `mzR` cannot be found.  There was [some discussion](https://stat.ethz.ch/pipermail/bioc-devel/2016-April/009026.html) on the `bioc-devel` mailing list about the problem of depending upon `mzR`, though I didn't find a resolution. Do I have to remove this dependency?

**Comment by richierocks** [comment]
I made the functionality that depends upon `MSnbase` (and hence `mzR`) Suggested rather than Imported.

**Comment by mtmorgan** [comment]
Thanks for your changes, I'm happy to mark this package as 'accepted'. It will be added to our svn repository and nightly builds, with additional information in the next day or so.
