### ISSUE TITLE
BANDITS

### ISSUE THREAD

**Issue by SimoneTiberi** [Bioconductor/Contributions#1062]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SimoneTiberi/BANDITS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by SimoneTiberi** [comment]
Hi @Kayla-Morrell 
I think the package is ready for review when you have time.

Have a good one,
Simone

**Comment by Kayla-Morrell** [comment]
Hello @SimoneTiberi,

Perfect! I'll comment back here in a week or so with my initial review.

Best,
Kayla

**Comment by SimoneTiberi** [comment]
Hi @Kayla-Morrell,
thanks for the feedback: I'll take care of it and re-submit the package.

A few of questions/clarifications:
1) "_REQUIRED: Avoid for loops, instead vectorize_."
I will try to minimize the presence of for loops, but a few are cumbersome to vectorize, I hope you will be fine with a couple of them being present.

2) "_REQUIRED: As an overall note for all of the man pages, edit the examples so that you are only showcasing the specific function in that man page. Keep the examples simple, just enough information to show the user how they can use the function._"
Some functions require objects to have been pre-computed by other functions to run.
I noticed that also other similar Bioc packages have long examples containing the entire pipeline, otherwise the final test functions cannot run (e.g., see `DRIMSeq::dmTest`).
In our case, for instance, `BANDITS::test_DTU` requires the entire pipeline to have run (or have been loaded) before.
If I only need to showcase `test_DTU`, then I should either I) load all objects needed (but that would make the package size too big) or II) comment out the `test_DTU` function (which you asked not to do: see point 3).
How do you suggest to deal with this?

3) "_REQUIRED: Also, be sure code is not commented out in examples._"
Some functions are computationally intensive and I comment them out (and load the .RData objects instead) in order to fulfil the 5 min time constraint for build time.
e.g. test_DTU takes ~30 seconds to run.
Is that ok? Any suggestions?

We'll get back to you with the updated package in a few days.

Have a good one,
Simone

**Comment by Kayla-Morrell** [comment]
@SimoneTiberi, a couple is not bad to have just as few as possible will help optimize the timing/speed of the functions.

I look forward to seeing the updated package.

Best,
Kayla

**Comment by SimoneTiberi** [comment]
Ok @Kayla-Morrell, thanks for the feedback.

Maybe I exaggerated with just a couple, but I noticed that most of the computationally intensive code is in Rcpp or already vectorized.
Most of the remaining for loops are either necessary or would not benefit (computationally) from a vectorization: 1) in some loops the i-th iteration depends on the previous one; 2) in others, we modify only parts of existing objects; 3) in others we intialize several objects and, if vectorizing, I would still need a loop to allocate the resulting objects.

Btw, I implemented all 'REQUIRED' (still working to reduce some for loops) and some 'SUGGESTION': I will re-submit very soon.

Have a good one,
Simone

**Comment by SimoneTiberi** [comment]
Hi @Kayla-Morrell ,
we submitted an updated version of the package.

We implemented all your ‘REQUIRED’ and some ‘SUGGESTION’.

I briefly summarize the main changes below:
-) DESCRIPTION: we changed the file as required (no examples, BugReports link, packages in Suggests and no LazyData);
-) README and vignette : we fixed issues and typos;
-) inst/extdata: we documented objects in inst/script/extdata.Rmd;
-) man pages: we changed most examples in the help pages to minimize code and focus on the function(s) of the help page;
	Note that some extra code is still present in some cases when a function depends on objects computed by others.
-) R code and Unit tests: we replaced ‘@‘ with accessor methods and vectorized some for loops.
	Note that some for loops are still present (see my explanation in the comment above). I also benchmarked several for loops against their vectorised alternative and noticed no significant difference in computational times, possibly due to the fact that many of the remaining loops loop over very few iterations (often 2 to 5).

Have a good weekend,
Simone

**Comment by SimoneTiberi** [comment]
Hi @Kayla-Morrell,
we submitted an updated version of the package: the latest version of the package is 0.99.22.

You’ll see I did quite a few commits to try and resolve the TIMEOUT problems, before realizing it has to do with CRAN (see Bernat Gel Moreno email to bioc-devel@r-project.org).

We implemented all your ‘REQUIRED’ and some ‘SUGGESTION’.

I briefly summarize the main changes below:
-) DESCRIPTION: we changed the file as required (no examples, BugReports link, packages in Suggests and no LazyData);
-) README and vignette : we fixed issues and typos;
-) inst/extdata: we documented objects in inst/script/extdata.Rmd;
-) man pages: we changed most examples in the help pages to minimize code and focus on the function(s) of the help page;
	Note that some extra code is still present (but was minimized) in cases when a function depends on objects computed by others.
-) R code and Unit tests: we replaced ‘@‘ with accessor methods and vectorized some for loops.
	Note that some for loops are still present (see my explanation in the comment above: https://github.com/Bioconductor/Contributions/issues/1062#issuecomment-482181009). I also benchmarked several for loops against their vectorised alternative and noticed no significant difference in computational times, possibly due to the fact that many of the remaining loops loop over very few iterations (often 2 to 5).

Have a good weekend,
Simone

**Comment by SimoneTiberi** [comment]
Hi @Kayla-Morrell ,
apologies for the pressure, but the deadline for changes is approaching and I just wanted to make sure you saw that we resubmitted our packaged (with the required corrections).

Cheers,
Simone

**Comment by SimoneTiberi** [comment]
Hi @Kayla-Morrell ,
apologies for the pressure, but the deadline for changes is approaching and I just wanted to make sure you saw that we resubmitted our packaged (with the required corrections).

Cheers,
Simone

**Comment by Kayla-Morrell** [comment]
Hello @SimoneTiberi,

Thank you for all the work done on this package. I have looked over the changes made and have just a couple additional requirements before accepting your package. See the secondary review below and comment back here when you are ready for me to look it over again.

# DESCRIPTION #

- [ ] REQUIRED: Thank you for adding the second author. Please format correctly as `Author: Simone Tiberi [aut, cre], Mark D. Robinson [aut]`.

# Unit tests #

- [ ] REQUIRED: Thank you for making changes about the slot access with '@'. There seems to still be some instances of this in 'test_test_DTU'.

Best,
Kayla

**Comment by SimoneTiberi** [comment]
Hi @Kayla-Morrell,
we did the changes you required and re-submitted the package (v. 0.99.23).

P.s. Thanks for spotting the remaining '@', I had missed them!

Simone

**Comment by Kayla-Morrell** [comment]
Hi @SimoneTiberi,

Thank you for making the changes, everything looks good and I'm happy to accept the package!

Best,
Kayla

**Comment by SimoneTiberi** [comment]
Thanks for your helpful comments during the revision process @Kayla-Morrell!

P.s. Just to inform you that we're making a minor change (just a few lines of code) to also allows users to use kallisto quantification (currently only salmon is accepted): we'll re-submit the updated package within a few days.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SimoneTiberi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BANDITS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BANDITS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
