### ISSUE TITLE
crisprseekplus

### ISSUE THREAD

**Issue by nephantes** [Bioconductor/Contributions#107]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/UMMS-Biocore/crisprseekplus

Confirm the following by editing each check box to '[x]'

- [ x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x ] The 'devel' branch for new packages and features.
- [ x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by nephantes** [comment]
What is wrong I couldn't find out? Since, bioc-issue-bot could read Description file without any problem. However, in the report, it couldn't see anything in the repository. Could you please help to fix the problem?

**Comment by vobencha** [comment]
Lori investigated and found that you only have a devel branch in your git repo. The single package builder (SPB) is looking for a master branch. The specific url that is causing the SPB to fail is
'https://raw.githubusercontent.com/UMMS-Biocore/crisprseekplus/master/DESCRIPTION'

Please change this to a master branch and all should be ok.

**Comment by nephantes** [comment]
Changed it master.
How can I trigger the builder? I added a web hook but not sure if that’s working or not.
Thanks,

Alper Kucukural, PhD
Assistant Professor, Program in Molecular Medicine
Bioinformatics Core
University of Massachusetts Medical School
368 Plantation St.Room AS4.2067
Worcester, MA 01605-2324
Phone: 774-312-4493<tel:774-312-4493>
E-mail: Alper.Kucukural@umassmed.edu<mailto:Alper.Kucukural@umassmed.edu>

On Sep 12, 2016, at 12:17 PM, vobencha <notifications@github.com<mailto:notifications@github.com>> wrote:


Lori investigated and found that you only have a devel branch in your git repo. The single package builder (SPB) is looking for a master branch. The specific url that is causing the SPB to fail is
'https://raw.githubusercontent.com/UMMS-Biocore/crisprseekplus/master/DESCRIPTION'

Please change this to a master branch and all should be ok.

**Comment by vobencha** [comment]
A new build is triggered each time you bump the version in DESCRIPTION. Change the version to 0.99.1 and it should rebuild.

**Comment by vobencha** [comment]
Please fix these issues flagged in the single package builder output. Once they are addressed I'll do a full review.

* checking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  'BSgenome.Hsapiens.UCSC.hg19' 'TxDb.Hsapiens.UCSC.hg19.knownGene'
  All declared Imports should be used.

Undefined global functions or variables:
  Celegans Dmelanogaster Hsapiens Mmusculus Rnorvegicus
  TxDb.Celegans.UCSC.ce6.ensGene TxDb.Dmelanogaster.UCSC.dm3.ensGene
  TxDb.Hsapiens.UCSC.hg19.knownGene TxDb.Mmusculus.UCSC.mm10.knownGene
  TxDb.Rnorvegicus.UCSC.rn5.refGene a biocLite fluidRow org.Ce.egSYMBOL
  org.Dm.egSYMBOL org.Mm.egSYMBOL org.Rn.egSYMBOL renderPrint strong

* Checking to see if we understand object initialization....
    * CONSIDER: Clarifying how objects 'Mmusculus,
      TxDb.Mmusculus.UCSC.mm10.knownGene, org.Mm.egSYMBOL' (used in
      cspServer, cspUI, installpack) were initialized. Maybe they are
      part of a data set loaded with data(), or perhaps part of an
      object referenced in with() or within().
* Checking for library/require of crisprseekplus...
    * RECOMMENDED: The following files call library or require on
      crisprseekplus.  This is not necessary. R/server.R
* Checking DESCRIPTION/NAMESPACE consistency...
    * RECOMMENDED: Import BSgenome.Hsapiens.UCSC.hg19,
      TxDb.Hsapiens.UCSC.hg19.knownGene in NAMESPACE as well as
      DESCRIPTION.
* Checking function lengths..................
  The longest function is 743 lines long
  The longest 5 functions are:
      cspServer() (R/server.R, line 40): 743 lines
      cspUI() (R/ui.R, line 14): 557 lines
      getLoadingMsg() (R/getImgs.R, line 9): 27 lines
      installpack() (R/installpack.R, line 14): 18 lines
      startcrisprseekplus() (R/startShiny.R, line 15): 15 lines
* Checking man pages...
    * RECOMMENDED: Add non-empty \value sections to the following man
      pages:
      installpack.Rd

Valerie

**Comment by vobencha** [comment]
Are you planning to submit a new version?

**Comment by nephantes** [comment]
Here we are installing BSgenome.Hsapiens.UCSC.hg19 or TxDb.Mmusculus.UCSC.mm10.knownGene or others, when they are needed. So, we don't want to install those at the beginning since there are many. The REQUIRED counts are 0 in my case.

**Comment by vobencha** [comment]
1) Fix this:
* Checking man pages...
    * WARNING: Add non-empty \value sections to the following man
      pages:
      installpack.Rd

2) Move these to 'depends':
Imports:BSgenome.Hsapiens.UCSC.hg19,
    TxDb.Hsapiens.UCSC.hg19.knownGene,
    org.Hs.eg.db,

3) Add the org.*, BSgenome and TxDb for fly, rat, mouse and worm to 'depends'. 

Bump the version and we'll see where we're at with the warnings.
Valerie

**Comment by vobencha** [comment]
Alternatively you could put the org.*, TxDb and BSgenome packages in imports. In the code, assign them to a variable to avoid the 'no visible binding for global variable' warning:
txdb <- "TxDb.Hsapiens.UCSC.hg19.knownGene"
orgdb <- "org.Hs.eg.db"
etc.
Valerie

**Comment by vobencha** [comment]
Thanks for making the changes. I'm marking as accepted and you should get an email in the next week with svn credentials and next steps.
Valerie
