### ISSUE TITLE
DMRScan

### ISSUE THREAD

**Issue by christpa** [Bioconductor/Contributions#108]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/christpa/DMRScan

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by christpa** [comment]
Dear Bioconductor, 
The package now passes `R CMD BiocCheck` with no errors and the gitHub library have been updated accordingly. 

Summary:
REQUIRED count: 0
RECOMMENDED count: 0
CONSIDERATION count: 3

I'm very sorry for the inconvenience, and would be grateful if you could compile and test the package again.

Sincerely
Christian Page

**Comment by mtmorgan** [comment]
The package version should be 0.99.0, then on the next change 0.99.1, then 0.99.2, etc; commit this change to the DESCRIPTION file on the master branch.

**Comment by christpa** [comment]
Done
- Christian

**Comment by mtmorgan** [comment]
Usually, commits trigger a 'web hook' that re-builds your package. Did you establish a [web hook][1]? If not, do so now and bump your package version again.

[1]: https://github.com/Bioconductor/Contributions#adding-a-web-hook

**Comment by lawremi** [comment]
Vignette does not appropriately introduce the package. It needs to describe the expected format of the data and guide the user through an actual workflow. With better documentation, we would probably see that this package needs to use Bioc data structures. Right now it doesn't depend on Bioc at all, which is obviously suspect. Its dependencies should all be in Imports not Depends. It probably doesn't need RcppRoll, but it's hard to tell since the code uses obfuscated variable names like `L`, `k` and `foo`.

**Comment by LiNk-NY** [comment]
Hi @christpa,
Thank you for considering Bioconductor. 

Michael hits the major points of the review. 
It seems like the package is not making use of the available Bioconductor classes nor does it stick to the conventions of Bioconductor. 

 ---

#### Overall
* We would prefer that you use the S4 object system along with Bioconductor classes. 
* Documentation and vignette should be improved for usability (see points below). 

#### Grammar/Syntax
* We tend not to use any underscores or periods within function names. We use camelCase. 
* Non-robust range creation (`2:L`) syntax can fail/misbehave when a variable is zero. 
* `!TRUE`
* `class(out) <- "scan"` Not sure what the objective for adhoc assignment of a class like that is for. 
* Non descriptive function arguments (i.e., k, p s, L, phi, foo)
* Argument descriptions are incomplete. Provide the class type that the function is expecting. This makes it easier for your users to make use of the function appropriately. 
* Packages in `Depends` should be in `Imports`

Thank you for considering Bioconductor. 

Best regards,
Marcel

**Comment by christpa** [comment]
Hi @LiNk-NY,                                                                    
                                                                                
Thank you for taking the time to review our package for Bioconductor.           
                                                                                
I've cleaned up the implementation of the package to both improve readability and comply with the Bioconductor standards.
                                                                                
### To address the overall points;                                            
* We now uses S4 implementation for both input and output. However, since we want the framework to be as similar as possible as another Bioconductor package ("bumphunter"), which solves the same problem in a different way, we decided to use as similar input and output as possible, and have the object orientation at a simplest possible level.
* I have repeatedly tried to use the BiocParallel package for parallelization in some of the functions, however, it runs into problems with lists crated by do.call(), which is easily solved by the parallel package, so we will prefer to stick with this package. 
* Both the vignette and the documentation have been greatly extended. The vignette now offers a complete pipeline on how to use this package. The documentation have also been updated to better reflect arguments and package usage.
                                                                                                                                              
### Syntax                                                                      
* camelCase is now used throughout the package.                                                      
* All loops and ranges have been implemented with seq_along()                   
* !TRUE should not have occurred in the first place, _removed_                  
* This class assignment is a common hack when using S3, since we have moved to consistently using S4 in the new implementation, this is removed.
* All function argument have be renamed to better reflect their purpose.        
* This should have been resolved with expanding documentation and new argument names.
* All packages in Depends are placed in either Imports or ImportFrom, which should resolve the problem (if I understood it correctly in the first place).
                                                                                
### Package                                                                     
* We have thoroughly tested the vignette this time, to avoid any mistakes like this again.
* The package size have been reduced to 3.2M                                    
                                                                                
I still have some problems to document '[' and '[[' with roxygen2, which gives the compilation error, but working to fix that.
                                                                                
Best                                                                            
Christian

**Comment by LiNk-NY** [comment]
Hi Christian, @christpa
Thank you for your updates. I will review them soon. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Christian, @christpa 
I took a lot at the changes you made. 
Here are a few notes: 

* The `Depends` field needs to only contain packages which you are building on top of. Any other package should be in the `Imports` field. 

### Major 
* Do provide a vignette that has runnable examples. Do **not** use a static vignette. A proper code chunk should start with a triple back tick and a lowercase `r` wrapped in curly brackets (i.e., "   ```{r}   "). 
* Avoid the use of `get`. You can provide a function as an argument to your function and use that instead. 
* Avoid nesting helper functions inside user-facing functions. If they need to be nested, then there is no need to create a function. If you use them repeatedly, they should be outside the function and made available for other functions. Use the naming scheme for unexported functions: `.functionName`. 
* Document datasets with a small description. Don't use `xx` to describe a dataset. 
* Avoid the use of an `initialize` method for your class. You should use a constructor function that handles diverse input and finally constructs the class. See an example in `GenomicRanges`. 
* Your main function should match the case of your package so to keep things consistent (`DMRScan`). 
* You should rename some methods, such as `St` and `Rt`, with descriptive names. 

### Minor 
* Use `anyNA` instead of `any(is.na(vector))`
* Avoid trailing whitespace

**Comment by lawremi** [comment]
It looks like my major points have been addressed. I agree with the comments from Marcel.

**Comment by LiNk-NY** [comment]
Thanks for Michael!

**Comment by christpa** [comment]
Hi Marcel @LiNk-NY  and Michael,

Thanks for taking the time to review my package. I've recompiled the package and addressed the points that you've raised.

* Depends and Imports have been cleaned up.
* All running code in the vignette are now dynamic.
* I've replaced `get` with a decision tree based on input from the functions.
* All nested functions are either moved out from the parent function or recoded.
* Both datasets are now documented.
* The `initializer` is gone now.
* I've change the name of the main function to match the package name.
* `Rt` and `St` have been renamed to have more informative names.
* `anyNA` have replaced `any(is.na(x))`
* Most trailing whitespace should be gone by now.  

Best,
Christian

**Comment by LiNk-NY** [comment]
Hi Christian, @christpa 
Thank you for making those changes!
Your package takes a little over 5 minutes to `check`. 
Please try to reduce this time as you continue development and maintenance.

Your package has been accepted. Thank you for submitting to Bioconductor!

Regards,
Marcel

**Comment by christpa** [comment]
Thank you Marcel, 

I will definitely try to reduce the time check time (I suspect this comes from some of the redundant calculations in the vignette, which I still haven't figured out how to omit). I will for sure keep on developing and maintaining the package. 

Best,
Christian
