### ISSUE TITLE
benchmarkfdrData2019: Data and Benchmarking Results from Korthauer and Kimes et al. (2019) comparing methods to control the false discovery rate

### ISSUE THREAD

**Issue by stephaniehicks** [Bioconductor/Contributions#1086]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/stephaniehicks/benchmarkfdrData2019

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by stephaniehicks** [comment]
Tagging co-authors @pkimes @kdkorthauer

**Comment by stephaniehicks** [comment]
Hi @LiNk-NY -- As part of the Bioconductor instructions (http://bioconductor.org/packages/release/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html), I'm notifying you that we intend to submit this an `ExperimentHub` data package. Please let me know next steps. Thanks!

**Comment by lshep** [comment]
Hey @stephaniehicks   I think the credentials you used to upload data for your last hub package should still work.  You can upload your data at any point and tag me when that's done to have it get in the live database -   
I see you have three metadata files in the inst/extdata directory - Are all three of these being uploaded to the hub?

**Comment by LiNk-NY** [comment]
Hi Stephanie, @stephaniehicks 

Sorry for the late response. I am just catching up on my package reviews. 
Thanks Lori @lshep for staying on top of it. 

Best,
Marcel

**Comment by stephaniehicks** [comment]
Thank you @lshep @LiNk-NY! 

@lshep regarding your question of the "three metadata files in the inst/extdata directory" (https://github.com/stephaniehicks/benchmarkfdrData2019/tree/master/inst/extdata)-- no I wasn't planning on uploading those. If I remember correctly, my understanding was the meta files stay in the `ExperimentHub` R package itself and are not uploaded to the hub?  I'm happy to upload to the hub if recommended though. Thanks! 

@lshep Using my previous credentials, I let the files upload to  `s3://annotation-contributor/benchmarkfdrData2019` overnight, but I think the connection broke at some point unfortunately.  I believe around 30GB out of the 35GB of the data was transferred. Could you confirm? Should I try to upload a second time? Thanks!

**Comment by lshep** [comment]
The metadata files aren't uploaded to the hub but the metadata file is used to add the files to the database.  So I would need to know which file holds the information for the samples you uploaded on S3.

**Comment by stephaniehicks** [comment]
got it. The meta file (https://github.com/stephaniehicks/benchmarkfdrData2019/blob/master/inst/extdata/metadata.csv) holds that information.

**Comment by lshep** [comment]
Its hard for me to tell what has been uploaded and what hasn't - a command line check with 
`aws s3 ls s3://annotation-contributor/benchmarkfdrData2019 --recursive`  will list the files and their sizes if you wanted to check  I could send you the output I see from that command if you are not able to run it.

**Comment by stephaniehicks** [comment]
Thanks @lshep! That `aws s3 ls` command was helpful and makes total sense. I'm back uploading the data. Will ping you when complete.

**Comment by stephaniehicks** [comment]
@lshep -- All of the data has been successfully uploaded.

**Comment by lshep** [comment]
So... fun fact I didn't know about... There is a character limit to the fields of the database and with the four full urls it runs over the limit ...(took me a bit to figure out what was going on). I'm looking now to see if I can find the exact limit. It looks like its max character length of 244. 
Is there any way to shorten the sourceurl field?

**Comment by pkimes** [comment]
Hi @lshep!

We shortened the `SourceURL` by breaking it into 2 columns (`SourceURL` and a new `SourceFile` column) for the rows where the string was over 244 characters (https://github.com/stephaniehicks/benchmarkfdrData2019/commit/0d8e88d8f2e0b7ce0be745695ac5747ec1ff0f4f).

Does this seem reasonable?

Is the 244 character limit specific to the `SourceURL` field or is it for all character fields? I just checked, and it looks like some of our `Description` fields are also pretty long. Let me know and I can shorten them if needed.
```
mdat <- readr::read_csv("../extdata/metadata.csv", col_types = cols())
mdat %>%
    dplyr::summarize_if(is.character, funs(max(nchar(.), na.rm = TRUE))) %>%
    unlist()
##                Title          Description               Series
##                   39                  371                   24
##               Genome           SourceType            SourceUrl
##                   18                    9                  143
##           SourceFile        SourceVersion              Species
##                  192                   73                   24
##         DataProvider        TestStatistic           EffectSize
##                  145                   20                    8
## InformativeCovariate           RDataClass        DispatchClass
##                   23                   19                    3
##           Maintainer            RDataPath
##                   40                   83
```

**Comment by lshep** [comment]
```
> meta = makeExperimentHubMetadata("benchmarkfdrData2019/")
missing values for 'DataProvider set to 'NA''
missing or NA values for 'Coordinate_1_based set to TRUE'
Loading valid species information.
Error in AnnotationHubData:::.checkThatSingleStringOrNAAndNoCommas(SourceVersion) : 
  SourceVersion must not contain commas
```
Can you change these to semi colon or colon or something of the like instead of a comma.  

The description has a longer max -  519 - so those should be okay.

**Comment by pkimes** [comment]
@lshep, sorry about that. 
Fixed in https://github.com/stephaniehicks/benchmarkfdrData2019/commit/e53c7ee2286b56d31edfbf7c5e689fbbb90cf871.

**Comment by lshep** [comment]
Thanks. The data has been added to the hub.  Please let me know if there are any access issues.

**Comment by lshep** [comment]
The data has been added to the hub. Please let me know if there are any access issues
```
> hub = ExperimentHub()
> query(hub, "benchmarkfdrData2019")
ExperimentHub with 171 records
# snapshotDate(): 2019-04-23 
# $dataprovider: NA, Geoffrey J. Barton lab, University of Dundee, Dundee, U...
# $species: Saccharomyces cerevisiae, Homo sapiens, human gut metagenome, Mu...
# $rdataclass: SummarizedBenchmark
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH2267"]]' 

           title                          
  EH2267 | h3k4me3-promoters-benchmark    
  EH2268 | h3k4me3-csaw-benchmark         
  EH2269 | h3k4me3-csaw-uninf-benchmark   
  EH2270 | h3k4me3-csaw-cov-benchmark     
  EH2271 | cbp-csaw-benchmark             
  ...      ...                            
  EH2433 | varyingpi0-benchmark-nullprop70
  EH2434 | varyingpi0-benchmark-nullprop80
  EH2435 | varyingpi0-benchmark-nullprop90
  EH2436 | varyingpi0-benchmark-nullprop95
  EH2437 | varyingpi0-benchmark-nullprop99

```

**Comment by pkimes** [comment]
@lshep everything looks fine with the package builder except the following warning from `R CMD build`:
```
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  'baxter-genus-benchmark' 'baxter-genus-log-ubiquity-benchmark'
  'baxter-genus-mean-abun-benchmark'
...
```
It looks like all of the functions created by the call to `createHubAccessors()` when the package is loaded. Do we need to write manual pages for all of these objects? Any suggestions on how to deal with this? (I guess we could get rid of the `.onLoad` function, but wondering if there are other options or if I'm getting this wrong.)

Thanks for the help!

**Comment by LiNk-NY** [comment]
Hi Patrick, @pkimes @stephaniehicks 
Generally, yes, you should document these functions / objects despite them being generated via the `createHubAccessors()` function. 
For example, `curatedMetagenomicData` also creates the documentation programatically.

Best regards,
Marcel

**Comment by pkimes** [comment]
Thanks, @LiNk-NY!
We shall deliberate...

**Comment by pkimes** [comment]
Hi @LiNk-NY 

I added documentation for all of the data objects and it looks like my push triggered a build, but it's been 9 hours and I don't see the build report. Did something happen?
 
I wrapped the examples in `\dontrun{}` so hopefully that isn't causing the problem. Let me know if I can fix anything!

**Comment by lshep** [comment]
Sorry for the delay -  with the new release the SPB stalled.  I just kicked off a new build and it should post shortly.

**Comment by lshep** [comment]
You should receive a build report shortly.  Version bumps should work as normal now.

**Comment by lshep** [comment]
A report where the git clone failed will post shortly...  that was on our end... I will kick another build off so you have a complete report ... just sit tight...

**Comment by LiNk-NY** [comment]
Hi Stephanie and Patrick, @stephaniehicks @pkimes 

Thank you for your submission. 
The package looks good overall. 
Please see the short review below. 

Best regards,
Marcel 

---

# benchmarkfdrData2019 #1086

## DESCRIPTION

* Include a `BugReports` link in the `DESCRIPTION`

## NAMESPACE

* Looks good

## vignettes

* Include Bioconductor installation instructions
* `BiocManager` should be the default GitHub download example because it uses `remotes`
internally

* Include the alternative way of downloading a resource as `hub[["EH2433"]]`
but encourage the use of the generated functions

## R/

* Data looks well documented

**Comment by LiNk-NY** [comment]
Hi Patrick, @pkimes 

It wouldn't hurt to have them in the vignette as well. 

See instructions on the landing page of any package, such as:
http://bioconductor.org/packages/release/bioc/html/SummarizedBenchmark.html

Best,
Marcel

**Comment by pkimes** [comment]
@LiNk-NY 

I've added a code chunk showing how to install the package in the latest commit. https://github.com/stephaniehicks/benchmarkfdrData2019/commit/8ae68d56acc4c6ea83c4a8d9e08c92a4da73ee65#diff-a045892f53be505fe9013fffa4da8821

Let me know if there's anything else I can change!

**Comment by LiNk-NY** [comment]
Thanks Patrick and Stephanie, @pkimes @stephaniehicks , for your contribution. 
Best regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/stephaniehicks.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("benchmarkfdrData2019")`. The package 'landing page' will be created at

https://bioconductor.org/packages/benchmarkfdrData2019

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
