### ISSUE TITLE
(inactive) harmony

### ISSUE THREAD

**Issue by ilyakorsunsky** [Bioconductor/Contributions#1095]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/immunogenomics/harmony

Confirm the following by editing each check box to '[x]'

- [X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X ] The 'devel' branch for new packages and features.
- [X ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

Please note that BiocCheck() produced 2 NOTES:

(1) "Consider shorter lines; 2 lines (0%) are > 80 characters long."

One of these lines is a URL and cannot be shortened. The other is in RcppExports and was automatically generated by Rcpp::compileAttributes().

(2) "Consider multiples of 4 spaces for line indents, 40 lines(4%) are not."

These lines are generated automatically by Roxygen. All source code and vignettes have 4-space indents.

**Comment by mtmorgan** [comment]
your package must interoperate (accept as inputs / create outputs, as appropriate) [SingleCellExperiment][1] objects.

[1]: https://bioconductor.org/packages/devel/SingleCellExperiment

**Comment by ilyakorsunsky** [comment]
Hi @mtmorgan, I updated the package. The function RunHarmony now has support for SingleCellExperiment.

**Comment by mtmorgan** [comment]
Looks like your package is not building, I guess because patchwork is not a CRAN or Bioconductor package. Will you be updating your package?

**Comment by ilyakorsunsky** [comment]
@mtmorgan good catch, I had removed it from the vignette but not from the DESCRIPTION. It should build now

**Comment by ilyakorsunsky** [comment]
@mtmorgan is there something I can do to trigger a build to test this?

**Comment by mtmorgan** [comment]
increment the version number, to 0.99.1, 0.99.2, ... each time you'd like to trigger a new build.

**Comment by mtmorgan** [comment]
On my Mac, I see
```
-rw-r--r--   1 ma38727  ROSWELL\Domain Users      0 Apr 30 16:15 configure.win
-rw-r--r--   1 ma38727  ROSWELL\Domain Users    697 Apr 30 16:15 configure.ac
-rwxr-xr-x   1 ma38727  ROSWELL\Domain Users  83774 Apr 30 16:15 configure
-rwxr-xr-x   1 ma38727  ROSWELL\Domain Users  23882 Apr 30 16:15 config.status
-rw-r--r--   1 ma38727  ROSWELL\Domain Users      0 Apr 30 16:15 cleanup.win
-rwxr-xr-x   1 ma38727  ROSWELL\Domain Users     46 Apr 30 16:15 cleanup
```
where configure and cleanup have the 'x'ecutable bit set, but configure.win, configure.ac, and cleanup.win do not have this bit set. I think you want to do something like
```
git update-index --chmod=+x configure.ac
```
and commit; I'm not really sure why these are showing up on Windows, or what the underlying issue is with CR / CRLF...

**Comment by ilyakorsunsky** [comment]
I modified the permissions as you suggested. When I clone the repo into my mac, everything seems to have execute permissions: 

-rwxr-xr-x   1 ikorsuns  1594166068     46 Apr 30 16:39 cleanup
-rwxr-xr-x   1 ikorsuns  1594166068      0 Apr 30 16:39 cleanup.win
-rwxr-xr-x   1 ikorsuns  1594166068  23882 Apr 30 16:39 config.status
-rwxr-xr-x   1 ikorsuns  1594166068  83774 Apr 30 16:39 configure
-rwxr-xr-x   1 ikorsuns  1594166068    697 Apr 30 16:39 configure.ac
-rwxr-xr-x   1 ikorsuns  1594166068      0 Apr 30 16:39 configure.win

I still get the same problem in the Windows build though: 

Warning: file 'harmony/cleanup' did not have execute permissions: corrected
Warning: file 'harmony/configure' did not have execute permissions: corrected

**Comment by LTLA** [comment]
You might consider using [_BiocSingular_](https://bioconductor.org/packages/release/bioc/html/BiocSingular.html) in place of a direct _irlba_ call; it provides a wrapper that allows users to easily switch between IRLBA, randomized SVD and exact PCA, increases speed via deferred operations or computation of a cross-product for thin/fat matrices, and supports parallelization via _BiocParallel_.

**Comment by ilyakorsunsky** [comment]
@mtmorgan Does bioconductor require a minimum R version? I would like to avoid requiring R3.6, as I know many users will not upgrade to this version for a while.

**Comment by mtmorgan** [comment]
Your package gets introduced into the 'devel' branch of Bioconductor, and then matures to the 'release' branch at the next release. The devel branch (and future release branch) use R-3.6, and BiocManager::install("yourpkg") will never install a package from the 3.6 branch on a 3.5 or earlier R. Users can more or less readily subvert this, but experience tells us that this only leads to broken installations -- Bioc packages play together much more than packages in other parts of the R ecosystem, so benefit from having more carefully controlled versions.

**Comment by mtmorgan** [comment]
Please increment the version number to trigger a build; I will then review the package.

**Comment by mtmorgan** [comment]
Are you still interested in submitting this package?

**Comment by robertamezquita** [comment]
Bumping this issue - @ilyakorsunsky
