### ISSUE TITLE
compareSingleCell

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#1113]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MarioniLab/compareSingleCell

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LTLA** [comment]
Bumping in the hope that some of the resources got cached after the first `TIMEOUT`, so they don't have to get re-downloaded. Downloading seems to be by far the longest, at least locally.

**Comment by LTLA** [comment]
Incidentally, I can't help but feel @hpages may be more interested in reviewing #1114, while @lshep may be more interested in reviewing this one!

**Comment by LTLA** [comment]
Not quite sure what's going on here... looks like it's not getting detected as a workflow.

**Comment by lshep** [comment]
`Workflow: True`  in the DESCRIPTION

**Comment by LTLA** [comment]
Thanks @lshep. I think this is the third time I've asked this question and you've given this answer! Looks like my strategy of copying a `DESCRIPTION` from a previous workflow was insufficient - _simpleSingleCell_ doesn't even have a `Workflow:` section.

**Comment by lshep** [comment]
Can you check the build time locally for the package?   I kicked off this manually thinking it stalled but there are two triggers that never finished building the package - I'm wondering if I need to check the timeout flag on the build process or if something more is going on...

**Comment by LTLA** [comment]
The downloads are very slow. Took me hours to download them - which doesn't really make sense to me, the files are not particularly big. The servers are in the UK, but still... maybe it's Brexit.

Once cached, the actual computation should be fast - no more than half an hour, but I'd have to go and time it properly. Will get back to you with some more concrete numbers.

**Comment by LTLA** [comment]
I realized I was caching the downloads locally - ostensibly to ensure that they could be re-downloaded at every build - but any locally cached results would be killed when the SPB times out and deletes the working directory of the build-in-progress. So, I've switched to the global cache, assuming that it persists on the SPB. My suspicion is that it will still `TIMEOUT`, though; each download is just **very** slow.

Might be worth considering EHub packages for this data - I'll prod a student on my end.

**Comment by lshep** [comment]
Just wanted to follow up on this -  is there a better solution for downloading the data ? How many different files are we talking about -  I could always download them manually on the builders so they are there but if files are updated that would probably require a manual redownload then -   This also doesnt help the user who may suffer through long download times.   Is it an issue that the files are large or the site they are being downloaded from?  It made it seem like these weren't particularly big but could be a server issue?  If thats the case maybe EH versions  would be the way to go?

**Comment by LTLA** [comment]
The files are somewhat big (500 MB, give or take) and the server is a lab-specific resource that isn't really powered up; I suspect that these two factors combined are probably causing the slow download. I've been nagging someone on the UK end to make an EHub package for this data, but they're taking too long to do this, so I think I will just make one myself over the weekend.

**Comment by lshep** [comment]
Should I close this issue for now or do you think there will be an accompanied data package soon?

**Comment by LTLA** [comment]
We're almost ready to go with the data package, just a few more checks and then we can submit. Can I re-use the credentials you sent me earlier for this new package?

**Comment by lshep** [comment]
Yes those credentials have not expired yet and it should be okay to use.  If there is an issue let me know

**Comment by LTLA** [comment]
I'm going to close this for the time being, as I might absorb the content here into Rob's book instead of having a separate series of workflows.
