### ISSUE TITLE
bigmelon

### ISSUE THREAD

**Issue by TJGorrie** [Bioconductor/Contributions#112]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/TJGorrie/bigmelon

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by TJGorrie** [comment]
This package was previously reviewed back in October 2014 by Kasper Hansen using the old system. Sources tell me it was under 'issue1044'. The notes from that review have been addressed in this version of the package.

**Comment by TJGorrie** [comment]
Hello @vobencha , can you please advise as to how I can fix the check warning reported on moscato1, or can this warning be accepted seeing as neither the Linux nor Mac archs have this error?

Tyler

**Comment by vobencha** [comment]
You can ignore the warning for now. I'll review the package and get comments to you this week.
Valerie

**Comment by vobencha** [comment]
Hi,

Package looks good. Just a few comments.

(1) remove the \dontrun from iadd.Rd

Can you add a small file with barcodes to inst/extdata so this can run?

(2) problems when running R CMD check

Please fix these:

* checking R code for possible problems ... NOTE
app2gds: no visible global function definition for ‘assayData’
app2gds: no visible global function definition for ‘betas’
app2gds: no visible global function definition for ‘pvals’
app2gds: no visible global function definition for ‘methylated’
app2gds: no visible global function definition for ‘unmethylated’
...

Undefined global functions or variables:
  MethylSet QCdata annotatedDataFrameFrom approx assayData
  assayDataElement assayDataNew betas coef data density detectionP
  fData fData<- file_test fivenum getAnnotation getBeta getGreen
  getHistory getMeth getProbeInfo getRed getUnmeth lm median methylated
  methylumiR na.omit object pData pData<- packageVersion preprocessRaw
  pvals sd unmethylated
Consider adding
  importFrom("stats", "approx", "coef", "density", "fivenum", "lm",
             "median", "na.omit", "sd")
  importFrom("utils", "data", "file_test", "packageVersion")
to your NAMESPACE file.

Valerie

**Comment by TJGorrie** [comment]
Hi Valerie, 
I have addressed the two issues that you wanted me to consider.
(1) I decided to opt to use the idats (barcodes) provided in the package 'minfiData' as it would have increased the size of my package considerably to add experimental idats i possess to inst/extdata. Running the example does now take >5 seconds now.
(2) Done.

Anything else I need to do?

Tyler

**Comment by vobencha** [comment]
Everything in 'Depends' should be fully imported in the NAMESPACE, e.g., import(methods), import(gdsfmt), import(minfi) etc. Listing a package in 'Depends' attaches it to the search path and is the same as if the use did library() in their workspace.

If you want to use selective importing, the package should be in 'Imports'. Functions from the packages in 'Imports' are only available to the internal functions in your package - not in the user's workspace. Packages in 'Imports' can be fully or partially imported.

Please modify DESCRIPTION and / or NAMESPACE as necessary.

Valerie

**Comment by vobencha** [comment]
Thanks for making the changes. The warning on windows looks like an anomaly, I'm going to go ahead and approve the package. You should get an email from Martin within the next week with svn credentials and instructions for next steps.
Valerie
