### ISSUE TITLE
TOAST

### ISSUE THREAD

**Issue by ziyili20** [Bioconductor/Contributions#1127]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ziyili20/TOAST

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ziyili20** [comment]
Dear Reviewer,
I took a look at the build report and found there are mainly two warnings from the report:
Warning: inst/doc file
    TOAST.html
  ignored as vignettes have been rebuilt.

  * Checking R Version dependency...
    * WARNING: Update R version dependency from 3.5 to 3.6.
I am not sure if I should increase the R version dependency from 3.5 to 3.6 in order to address the warning. Could you give me some advice?
Ziyi

**Comment by lshep** [comment]
We recommend updating the R version dependency to the current version of R.  This is now R's stable release and we are checking your package vs this version of R as well as all other Bioconductor packages.  There have been a number of significant changes to R (which may or may not affect your package) from R 3.5 to R 3.6.  We can  guarantee the package works with R 3.6 but not necessarily R 3.5 through this tracker.  Bioconductor releases are tied to specific R releases and your package once accepted will be released under Bioc 3.10 which will be associated with R 3.6.

**Comment by ziyili20** [comment]
Dear Ishep,
Thank you very much for the helpful comment! I will increase my package dependency from 3.5 to 3.6 now, recheck the package, commit to my repository and will let you know when I am done.
Ziyi

**Comment by lshep** [comment]
Thank you!  Let me know when you are ready for a review.  Also please remember to set up the [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook)   this will automatically rebuild and check the package on this tracker when there is a version bump in the DESCRIPTION of your package. 
Cheers, 
Looking forward to getting your package accepted on Bioconductor.

**Comment by ziyili20** [comment]
Dear Ishep,
I updated the R dependency from 3.5 to 3.6. Now that warning is removed. The vignette one still persists:
Warning: 'inst/doc' file
    'TOAST.html'
  ignored as vignettes have been rebuilt.
Do I need to delete my inst/doc folder? What I found previously is, if I do not have this folder, I got warning too through BioCheck step on my PC. Could you give me some advice?
Ziyi

**Comment by lshep** [comment]
What warning do you get when you remove this file?

**Comment by ziyili20** [comment]
I got the following warning from R CMD check TOAST:
* checking files in ‘vignettes’ ... WARNING
Files in the 'vignettes' directory but no files in 'inst/doc':
  ‘TOAST.Rmd’

**Comment by lshep** [comment]
Either WARNING is fine to ignore for now.  I'll leave it your choice.  We probably would prefer to have the file removed from the inst/doc as it is better practice to have it rebuild interactively.

**Comment by ziyili20** [comment]
Got it. I will remove the file now and add a version bump. Will get back to you in a minute.

**Comment by lshep** [comment]
Great.  I'll look at your package and should have a review sometime within the next week

**Comment by ziyili20** [comment]
Got it. Thank you very much!

**Comment by lshep** [comment]
**README**

- [ ] Add Bioconductor installation instructions


**vignette**

- [ ] Add Bioconductor installation instructions
- [ ] Seems based on the description of quick start, could there be be capability of analyzing SummarizedExperiment or MultiAssayExperiment
- [ ] ?spelling?  example datset? 
- [X] Thank you for showing the connection to other Bioconductor packages! 
- [ ] You don't have to keep reloading your data in each section.  Once you have loaded once it will persist 


**R/man**

- [ ] In general if a feature by sample matrix, the function should also
  alternatively take in a SummarizedExperiment as this is the standard
  bioconductor object for holding such data. Please also allow this format to be
  passed in either as a wrapper or can simply to an argument check and the
  subset to the matrix. Apply this throughout to functions. We really like to see existing Bioconductor 
  classes and structures reused as much as possible. 
- [ ] Functions could possibly benefit from some initial checking for
  constraints? 

Ex: 
In DEVarSelect (but should be applied throughout)
Does  Y_raw and Prop0  need to be the same dim of N?  This could be
checked? Do all have to be included/matching? 
Other examples: do they have to be a certain class or length?

- [ ] Use message/warning/error over print for status messages to user (apply
  throughout to all files but ex. GetCMatrix_contrast/csDeconv.R)
- [ ] Please remove the paste0 within the stop() (should be applied throughout
  but ex. GetCMatrix_contrast). Stop/message/warning/error uses paste0
  automatically

```
> stop("But is should have ", 12, " columns!") 
Error: But is should have 12 columns!
```

- [ ] Also please check messages, the above "is" seems like a type "it" 
 
- [ ] In general see if you can combined similar code to avoid
  repeated code.  I'm not quite sure if its possible for the GetCMatrix_* files
  but as an example findRefine_cv and findRefinx_var should be one function and
  internally handle the difference.  The condensed code will make it easier to
  manager and if there is ever a need to update avoids having to update in
  multiple places. minimizing the number of repeated calls wherever possible. 

```
findRefinx(rawdata, nmarker=1){

  if(is(rawdata, "matrix")){
     ...
  }else{
     ...
  } 
  
  ix <- sort(value, decreasing=TRUE, index=TRUE)$ix
  return(ix[seq(nmarker)])

}

```

Thank you for your submission. Please work on the above changes.  When ready please ensure a version bump in the description to kick off a new build and comment back here that you are ready for re-review and with a summary of what has been changed. 

I look forward to working with you on getting your package accepted.

**Comment by ziyili20** [comment]
Dear Ishep,

Thank you very much for your detailed and constructive comments! I found your comments very helpful and have revised the TOAST package following your suggestions.

The detailed changes include:
1. Add Bioconductor installation instruction in both README and vignette;
2. Load dataset only once in vignette;
3. Allow all functions that interact with raw data to accept SummarizedExperiment object as input; update vignette and readme by adding information related to using SummarizedExperiment object as input;
4. Add initial checking to functions, including DEVarSelect(), findRefinx(), DEKtissue(), fitModel(), RefFreeCellMix_wrapper().
5. Combine findRefinx_cv() and findRefinx_var() to findRefinx(); I carefully reviewed all GetCMatrix_* functions and found them all have very different structures, so I did not combine them.
6. Remove paste0() within stop(); replace print() by message() across all functions.

The updated package is ready for the second-round review. I really appreciate your time and helpful comments! Look forward to your suggestions!

Ziyi

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ziyili20.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TOAST")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TOAST

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
