### ISSUE TITLE
HelloRanges

### ISSUE THREAD

**Issue by lawremi** [Bioconductor/Contributions#113]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lawremi/HelloRanges

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
There will be some false positive complaints from BiocCheck due to the unconventional nature of the package (essentially written in a DSL using non-standard evaluation). I've done my best to work around them though. There are also some weird variable names, like `F` and `5` that correspond to bedtools argument names, and we need to be consistent. Thanks for your consideration.

**Comment by LiNk-NY** [comment]
Hi @lawremi!
```
Error in library(HelloRangesData) : 
  there is no package called HelloRangesData
```
Were you supposed to submit `HelloRangesData` first (which can be installed without any such dependency issues)?

**Comment by lawremi** [comment]
AdditionalPackage: https://github.com/lawremi/HelloRangesData

**Comment by lawremi** [comment]
It complains about not having a vignette, but it's just a data package. Do I really need a vignette for that? The whole point of the package is to support the HelloRanges vignette.

**Comment by lawremi** [comment]
The HelloRangesData package now has a (trivial) vignette, but it appears to be failing on Windows due to a missing marginfix.sty (loaded by BiocStyle). Any ideas?

**Comment by lawremi** [comment]
Anyone listening? This should be an easy package to push through.

**Comment by LiNk-NY** [comment]
Hi @lawremi, 
I'm on it. 
Thanks, 
Marcel

**Comment by lawremi** [comment]
Looks like Windows just does not like my vignette.

**Comment by lawremi** [comment]
Been almost a week since I've heard anything. @mtmorgan do you have any hints as to why the Windows build machine is not building my straight-forward LaTeX?

**Comment by LiNk-NY** [comment]
Hi @lawremi, 
This is an issue on our end. As far as I know, the build system should handle any LaTeX dependencies automatically. We're looking into it. 
Thanks,
Marcel

**Comment by vobencha** [comment]
Hi Michael,
Marcel just transferred this to me. Asking Lori to kick off another build ... 
Val

**Comment by vobencha** [comment]
I've asked Herve about the error on moscato1.

**Comment by vobencha** [comment]
moscato1 has several of these MikTeK configuration errors that are not reproducible on the new windows builder tokay1.  The SPB will be moving to tokay1 after the release and these issues should go away. Package is approved.

**Comment by lawremi** [comment]
Great, thanks. Sorry for the trouble during this busy time.
