### ISSUE TITLE
Submit new package "fcScan: features cluster Scan"

### ISSUE THREAD

**Issue by pkhoueiry** [Bioconductor/Contributions#1147]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pkhoueiry/fcScan

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by abedkurdi** [comment]
Hi @nturaga 
We are ready for the review and if there is anything we should do please let us know.

Thank you.

**Comment by nturaga** [comment]
# Review fcScan

## R CMD build

ok

## R CMD INSTALL 

ok

## DESCRIPTION

* “LazyData:” field: For packages that include data, we recommend not
  including LazyData: TRUE. This rarely proves to be a good thing. In
  our experience it only slows down the loading of packages with large
  data.

## NAMESPACE

ok

## vignette

* Give the vignette a name, "fcScan_vignette.Rmd".

* in Version Info - Bioconductor Version: Is not printing the actual
  version.

* Vignette seems incomplete, especially the example. Please develop it
  further to make it more approachable to users.
  
* There is no runnable example in the vignette, the example chunk
  option is set to eval=FALSE. Please include a runnable example with
  some details about how the functions work.
  
* Also, your example doesn't work. Without a good vignette, this
  package cannot be accepted.

## R

* Not sure why you need to convert the GRanges object to a data.frame,
  and then again cast it into a GRanges object. What am I missing
  here?

* There are a lot of places where you have used a `for` loop and these
  are not needed.
  
  eg: 
        
		for(i in seq_along(order)){
            if(!order[i] %in% names(c)){
                stop(paste("Site names in order and condition do not match: ",
                            order[i], sep=""))
            }
        }

	vs
	
		bool_index <- all(order %in% in names(c))
		## bool_index gives you a true/false value of order values in names(c)
		if(!bool_index)
			stop("Site names don't match....")

	Take a look at this
	
		>  c = c("s1"=1,"s2"=2)
		>  order = c("s1","s2","s1")
		> c
			s1 s2 
	   		1  2 
		> order
		[1] "s1" "s2" "s1"
		> order %in% names(c)
		[1] TRUE TRUE TRUE
		> all(order %in% names(c))
		[1] TRUE	

* The loops you have used are not efficient at all. Please try to
  optimize your code.

        if(greedy == FALSE){
            ## order has more sites than condition
            for(i in seq_along(unique(order))){
                if(sum(unique(order)[i] == order) >
                    c[which(names(c) == unique(order)[i])]){
                    stop("Greedy is FALSE and order is larger than condition")
                }
            }
			
	- remove operations which don't need to be inside to loop, to the outside
	
	- I'm not convinced you need a for loop at all here.
	
	http://bioconductor.org/developers/how-to/efficient-code/
	
* Another place you don't need the loop, `grepl` is vectorized.

		for(i in seq_along(all_files)){
			if(grepl("\\.bed$", all_files[i])){
				b = import(all_files[i])
			}
			else if(grepl("\\.vcf$|\\.vcf.gz$", all_files[i])){
				b = rowRanges(readVcf(all_files[i]))
			}
			b$site = names(c[i])
			df = rbind(df, as.data.frame(b)[, c("seqnames", "start", "end", "strand", "site")])
		}
			
	vs
	
		> tools::file_ext(c("asdd.bed", "fd.bed"))
		[1] "bed" "bed"
		
		bed_files <- tools::file_ext(c("asdfasfd.bed", "fdsaf.bed"))
		if (all(grepl("bed", bed_files)))
			b = import(bed_files) ## make sure the "import function is vectorized
		else if .... ## do the same for vcf
			b = rowRanges(readVcf....)
		b$site = names(c)
		...
		
	Vectorize you code as needed. This is just an example template	
	
* Make these changes before there is another secondary review.

**Comment by abedkurdi** [comment]
Hello Nitesh,
Do you advise to convert our code from using data frame to GRanges?

Thank you.

**Comment by pkhoueiry** [comment]
> # Review fcScan
> ## R CMD build
> 
> ok
> ## R CMD INSTALL
> 
> ok
> ## DESCRIPTION
> 
>     * “LazyData:” field: For packages that include data, we recommend not
>       including LazyData: TRUE. This rarely proves to be a good thing. In
>       our experience it only slows down the loading of packages with large
>       data.
Response to reviewer:  We now removed the LazyData field
> 
> ## NAMESPACE
> 
> ok
> ## vignette
> 
>     * Give the vignette a name, "fcScan_vignette.Rmd".
Response to reviewer: Vignette name changed to fcScan_vignette.Rmd
>     * in Version Info - Bioconductor Version: Is not printing the actual
>       version.
Response to reviewer: This is corrected
>     * Vignette seems incomplete, especially the example. Please develop it
>       further to make it more approachable to users.
Response to reviewer: We now developed the example section further by adding detailed explanations on each example
>     * There is no runnable example in the vignette, the example chunk
>       option is set to eval=FALSE. Please include a runnable example with
>       some details about how the functions work.
Response to reviewer: We corrected this error and examples are now evaluated
>     * Also, your example doesn't work. Without a good vignette, this
>       package cannot be accepted.
Response to reviewer:  We added an additional example with detailed explanation to clarify it
> 
> ## R
> 
>     * Not sure why you need to convert the GRanges object to a data.frame,
>       and then again cast it into a GRanges object. What am I missing
>       here?
Response to reviewer: Since “getCluster” accepts data in data frame and Granges formats, we opted as default to convert a GRanges to a dataframe and proceed with clustering. We now changed the default and Granges are not converted anymore. However, we are still using dataframe in the clustering function itself but we use GRanges methods to collect the needed information. 
>     * There are a lot of places where you have used a `for` loop and these
>       are not needed.
>       eg:
>       ```
>         for(i in seq_along(order)){
>             if(!order[i] %in% names(c)){
>                 stop(paste("Site names in order and condition do not match: ",
>                             order[i], sep=""))
>             }
>         }
>       ```
>       
>       
>       vs
>       ```
>         bool_index <- all(order %in% in names(c))
>         ## bool_index gives you a true/false value of order values in names(c)
>         if(!bool_index)
>         	stop("Site names don't match....")
>       ```
>       
>       
>       Take a look at this
>       ```
>         >  c = c("s1"=1,"s2"=2)
>         >  order = c("s1","s2","s1")
>         > c
>         	s1 s2 
>        		1  2 
>         > order
>         [1] "s1" "s2" "s1"
>         > order %in% names(c)
>         [1] TRUE TRUE TRUE
>         > all(order %in% names(c))
>         [1] TRUE	
>       ```
Response to reviewer: We updated our code to vectorize for loops whenever possible. As an example, we paste here one case:
Solution:
```
if( !all(names(c) %in% x$site)) {, 
message("Sites in condition do not match sites in data")
return(NULL)
}
```

>     * The loops you have used are not efficient at all. Please try to
>       optimize your code.
>       ```
>         if(greedy == FALSE){
>             ## order has more sites than condition
>             for(i in seq_along(unique(order))){
>                 if(sum(unique(order)[i] == order) >
>                     c[which(names(c) == unique(order)[i])]){
>                     stop("Greedy is FALSE and order is larger than condition")
>                 }
>             }
>       ```
```
Solution:
if(!all(sort(c) == summary(as.factor(order)))){, 
stop("Greedy is FALSE and order is larger than condition")
}
```
>       
>       * remove operations which don't need to be inside to loop, to the outside
>       * I'm not convinced you need a for loop at all here.
Response to reviewer: This is corrected now as mentioned above. We however are still using for loops in a couple of places mainly in cases where the array length is known and small which will not compromise performance. The only large for loop is in “cluster_sites” function where indices are needed, the reason for which we kept the for loop.
   
>       http://bioconductor.org/developers/how-to/efficient-code/
> 
>     * Another place you don't need the loop, `grepl` is vectorized.
>       ```
>         for(i in seq_along(all_files)){
>         	if(grepl("\\.bed$", all_files[i])){
>         		b = import(all_files[i])
>         	}
>         	else if(grepl("\\.vcf$|\\.vcf.gz$", all_files[i])){
>         		b = rowRanges(readVcf(all_files[i]))
>         	}
>         	b$site = names(c[i])
>         	df = rbind(df, as.data.frame(b)[, c("seqnames", "start", "end", "strand", "site")])
>         }
>       ```
>       
>       
>       vs
>       ```
>         > tools::file_ext(c("asdd.bed", "fd.bed"))
>         [1] "bed" "bed"
>         
>         bed_files <- tools::file_ext(c("asdfasfd.bed", "fdsaf.bed"))
>         if (all(grepl("bed", bed_files)))
>         	b = import(bed_files) ## make sure the "import function is vectorized
>         else if .... ## do the same for vcf
>         	b = rowRanges(readVcf....)
>         b$site = names(c)
>         ...
>       ```
>       
>       
>       Vectorize you code as needed. This is just an example template
Response to reviewer: “Load_data” function accepts BED or/and VCF files. That is, users can give as input a mix of both file formats (in addition to input as data frame and GRanges discussed above). In such a case, we cannot use the proposed solution which will be application only if input files are of the same format (i.e BED or VCF). For this reason, we had to keep the for loop to test, at each iteration, the format of the file and call the appropriate loading function (i.e import for BED and readVCF for VCF). 
>     * Make these changes before there is another secondary review.

**Comment by abedkurdi** [comment]
Dear @nturaga,
we have made the requested changes and we are ready for secondary review.

Thank you.

**Comment by nturaga** [comment]
Good job @abedkurdi .

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pkhoueiry.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("fcScan")`. The package 'landing page' will be created at

https://bioconductor.org/packages/fcScan

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
