### ISSUE TITLE
MouseGastrulationData

### ISSUE THREAD

**Issue by jonathangriffiths** [Bioconductor/Contributions#1150]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MarioniLab/MouseGastrulationData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jonathangriffiths** [comment]
A note about the unchecked box: most functions in the package use `dontrun{}`, and the package therefore fails `BiocCheck`.

However, this is because the associated files are not yet available on ExperimentHub, so the examples cannot be run. The files that the package uses are uploaded, however, using information provided by @lshep.

Once the files are available we will update the package to remove these.

**Comment by lshep** [comment]
I see the data on S3.  I unfortunately cannot add the data into the database for the experimenthub until the repository has the inst/extdata/metadata.csv files created.  Could you please run the scripts in inst/scripts to create the three different metadata files. Once they are checked into the repository please tag me in a comment here.

**Comment by jonathangriffiths** [comment]
I have just pushed that now @lshep, thanks!

**Comment by lshep** [comment]
Please make sure to add ExperimentHub to the biocViews list in your DESCRIPTION.  The data has been added to the hub and you should now be able to test and debug with your data.  
```
library(ExperimentHub)
hub = ExperimentHub()
query(hub, "MouseGastrulationData")
ExperimentHub with 65 records
# snapshotDate(): 2019-06-18 
# $dataprovider: Jonathan Griffiths
# $species: Mus musculus
# $rdataclass: character
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH2583"]]' 

           title                            
  EH2583 | Atlas processed counts           
  EH2584 | Atlas rowData                    
  EH2585 | Atlas colData                    
  EH2586 | Atlas size factors               
  EH2587 | Atlas reduced dimensions         
  ...      ...                              
  EH2643 | WT chimera raw counts (sample 6) 
  EH2644 | WT chimera raw counts (sample 7) 
  EH2645 | WT chimera raw counts (sample 8) 
  EH2646 | WT chimera raw counts (sample 9) 
  EH2647 | WT chimera raw counts (sample 10)
```
Let me know if there is any other issues with accessing the data from the hub.

**Comment by jonathangriffiths** [comment]
Okay, I believe this package is now in a ready-to-submit state.

The vignette build fails on the Windows machine due to the restricted amount of memory. Given that this is a package designed to facilitate the download and in-memory use of a large dataset, this does not seem to me to be a severe issue.

I have considered separating the largest objects into smaller files (split according to some sensible scheme like the 10x sample) - these could then be separately downloaded and loaded into R to reduce the memory burden. However, for the moment, I imagine it is better to get this package up and available for use rather than delay to edit the raw data files.

There is also a warning in `R CMD CHECK` asking for an R >= 2.1.0 dependency. Of course, this is implicitly satisfied if the user is able to use a version of Bioconductor version that could contain this package. Do you know what the best thing to do is regarding this?

Thanks!

**Comment by Liubuntu** [comment]
Hi @jonathangriffiths , 

For your last question about R dependency, you can simply add `Depends: R (>= 3.6.0)` in `DESCRIPTION` file, `Depends` field. 

I'll take a look at your other building issues and comment back later. 

Best,
Qian

**Comment by Liubuntu** [comment]
HI @jonathangriffiths , 

Please see below for the review. Fixing warnings and errors from the building report were suggested also. Let me know for any questions. 

Cheers,
Qian

## DESCRIPTION
- Include a depends field for R (>= 3.6.0), this is expected to remove the warnings. 
- The `Date` field is not actually needed.
- Recommended to add `URL` field, to direct users to source code
  repositories, e.g., the GitHub repository.
- Recommended to add `BugReports:` field: It is encouraged to include
  the relevant links to Github for reporting Issues.

## NAMESPACE

- Looks good!

## R/

- General: for those arguments with default values, specify in the
  `@param` documentation.
- To address the windows building error due to memory limit, try to
  load only a small subset of data in examples. e.g., in
  `EmbryoAtlasData.R`, use
  ```
  atlas.data <- EmbryoAtlasData(subsample.frac = 0.1)
  atlas.data <- EmbryoAtlasData(type="processed", subsample.frac = 0.1)
  ```
  Examples and vignette are only used to show functionalities, no need
  to use/load all data.
- data.R: I would usually suggest adding an `@examples
data(embryo_celltype_colours)` field in the documentation.
- It's suggested to prefix `.` for non-exported utility
  functions. e.g., use `.getProcOrRaw` for the function name.

## vignette
- Add a section for `Installation`, to show to users how to install
  the package as if it has been included in Bioconductor using
  `BiocManager`. Include something like this:

```
1. Download the package from Bioconductor.
{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("pkgName")

Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)

2. Load the package into R session.
{r Load, message=FALSE}
library(pkgName)
```

- Add a section for `sessionInfo()` in the end.

## inst/scripts 
- Looks good!

**Comment by jonathangriffiths** [comment]
I have now addressed all of the review points, except for the memory limit one.

I think this is not addressable at the moment due to the wat the data is currently stored on ExperimentHub - raw count matrix, when loaded into R, is 7.4 GB in memory. Therefore, even before the downsampling can happen, the memory threshold should be hit. There is also the point that Aaron has raised above, but I'm uncertain if that is playing a role in the problem here.

The "real" solution is probably to reorganise the files on ExperimentHub into smaller chunks (e.g., by developmental stage) so that we can reduce the amount of data that needs to be loaded at all. Indeed, I do plan to do this at some point, but I think it's probably better to get the package up and running for the much larger community that use high-memory 64-bit machines before doing this restructuring.

**Comment by jonathangriffiths** [comment]
I made a tweak this morning to move a small data file from a data/.rda file to an R/*.R script, to allow easier reading from the code.

**Comment by Liubuntu** [comment]
Hi @jonathangriffiths , 

After inspecting the error a bit further, we see that the data are pretty big in ExperimentHub, and the people who uses win 32 could not download the data successfully and then construct the `SingleCellExperiment` object. Also for documentation examples / vignette examples, we don't expect author to have a very large data set for showcase. 

So I talked with Martin @mtmorgan, and he suggests to add another function like `EmbryoAtlasDataExample()`, which does the same in constructing the SCE, but the data only includes e.g., 2 samples, for showcase only. So in any operating system, this functionality of the real function `EmbryoAtlasData()` could be successfully showed, and the `@examples` doesn't occupy a lot of time given the building time limit. 

Things to do include: 
 1. generate the small data set and submit to ExperimentHub. 
 2. Add a new function e.g., `EmbryoAtlasDataExample()`, and do the EH downloading (small dataset), and SCE constructing, etc. 
3. export this function, and add it into the `@examples` field under `EmbryoAtlasData()`. 
4. Inside the documentation of `EmbryoAtlasData` (or in the `@examples` field, add some comments about the data size, and remind users to be cautious in calling this big function if only for testing purpose.   

Let me know for any question. 

Best,
Qian

**Comment by jonathangriffiths** [comment]
Hi @Liubuntu,

If we're going to add some new data to ExperimentHub, I think it's probably best that I push ahead with a larger restructuring that allows the access of smaller subsets of data in a way that is biologically meaningful. This should be helpful not only for the vignette but also for researchers who want to access only a slice of the data. I'll have a go at this over the weekend.

Thanks,
Jonny

**Comment by jonathangriffiths** [comment]
Hi @lshep,

I've generated the new files for this package now - should I upload them using the same details as for the first file submission?

I think you can safely delete all of the files that had already been uploaded, too.

Thanks for the help,
Jonny.

**Comment by lshep** [comment]
Sorry for the delayed response;  I was away at a conference with limited internet connectivity.  Yes please upload as before.  I will need the updated metadata file to add to the database.


Just to double verify  -  all the original data uploaded can be deleted from S3 and out of the ExperimentHub database?



Cheers,


Lori Shepherd

Bioconductor Core Team

Roswell Park Cancer Institute

Department of Biostatistics & Bioinformatics

Elm & Carlton Streets

Buffalo, New York 14263

________________________________

**Comment by jonathangriffiths** [comment]
No problem!

Yes, everything else can be deleted. I will push the metadata scripts and upload the files tomorrow.

Jonny.

**Comment by jonathangriffiths** [comment]
Hi @lshep,

The files should all be uploaded now.

The metadata files are also updated at https://github.com/MarioniLab/MouseGastrulationData/tree/master/inst/extdata

Thanks for helping me sort this out,

Jonny

**Comment by lshep** [comment]
The new data has been added to the hub.  Please update your package as necessary
```
> eh = ExperimentHub()
  |======================================================================| 100%

snapshotDate(): 2019-08-01
> query(eh, "MouseGas")
ExperimentHub with 324 records
# snapshotDate(): 2019-08-01 
# $dataprovider: Jonathan Griffiths
# $species: Mus musculus
# $rdataclass: character
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH2701"]]' 

           title                            
  EH2701 | Atlas processed counts (sample 1)
  EH2702 | Atlas processed counts (sample 2)
  EH2703 | Atlas processed counts (sample 3)
  EH2704 | Atlas processed counts (sample 4)
  EH2705 | Atlas processed counts (sample 5)
  ...      ...                              
  EH3020 | WT chimera raw counts (sample 6) 
  EH3021 | WT chimera raw counts (sample 7) 
  EH3022 | WT chimera raw counts (sample 8) 
  EH3023 | WT chimera raw counts (sample 9) 
  EH3024 | WT chimera raw counts (sample 10)

```

**Comment by jonathangriffiths** [comment]
I think this package is now ready to go!

I have noticed this morning that I have accidentally duplicated the rowData on ExperimentHub - each sample has its own file, but the contents of the file are actually the same for every sample.

We could clean this up, but given that the files are so small (two columns of ~25k gene names) it might not even be worth the time to do this. I'll leave the decision up to you.

Thanks,
Jonny.

**Comment by Liubuntu** [comment]
Hi @jonathangriffiths , 

It's nice updating the whole data sets on ExperimentHub, so each small data set could be biologically meaningful and apply to all platforms. 

I would say only keep one of the rowData on ExperimentHub, and call the same rowData in R scripts. I'll see what Lori @lshep says about it. 

Other than that, the package looks good!

Best,
Qian

**Comment by jonathangriffiths** [comment]
@lshep - I will generate replacement row data files tomorrow morning - I have already made the code changes, but not pushed them. If we go ahead with deleting the duplicated data, please could you remove any files that contain the string "rowdata"? That should apply only to the files we want removed, and there should be 36 in the atlas folder, 10 in the wild-type chimera folder, and 4 in the Tal1 chimera folder.

If it's easier, we could delete all the files and replace them wholesale - the upload time isn't very long on my end.

Thanks,
Jonny.

**Comment by lshep** [comment]
I will remove these files from the database and S3.  Please let me know when you have the replacement files uploaded to add back in.

**Comment by jonathangriffiths** [comment]
Hi @lshep - these should be uploaded now (just the row data, in the right place in their appropriate file structure)

Jonny

**Comment by lshep** [comment]
So I should be readding three files -  I assume these are corrected in the metadata files as well?




Lori Shepherd

Bioconductor Core Team

Roswell Park Cancer Institute

Department of Biostatistics & Bioinformatics

Elm & Carlton Streets

Buffalo, New York 14263

________________________________

**Comment by lshep** [comment]
The rowData has been added back into the hub. 
```
> library(ExperimentHub)
> eh = ExperimentHub()
> query(eh, c("MouseGast", "rowData"))
ExperimentHub with 3 records
# snapshotDate(): 2019-08-06 
# $dataprovider: Jonathan Griffiths
# $species: Mus musculus
# $rdataclass: character
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH3065"]]' 

           title               
  EH3065 | Atlas rowData       
  EH3066 | Tal1 chimera rowData
  EH3067 | WT chimera rowData  
```

**Comment by jonathangriffiths** [comment]
Thanks for getting these up! However, I'm getting an error when I try to download the new rowData: 

```
> library(ExperimentHub)
> eh = ExperimentHub()
snapshotDate(): 2019-08-06
> head(eh[["EH3065"]])
see ?MouseGastrulationData and browseVignettes('MouseGastrulationData') for documentation
downloading 1 resources
retrieving 1 resource
Downloading: 240 B
Error: failed to load resource
  name: EH3065
  title: Atlas rowData
  reason: 1 resources failed to download
In addition: Warning messages:
1: download failed
  web resource path: ‘https://experimenthub.bioconductor.org/fetch/3081’
  local file path: ‘/Users/griffi01/Library/Caches/ExperimentHub/59211b2f6988_3081’
  reason: Forbidden (HTTP 403).
2: bfcadd() failed; resource removed
  rid: BFC5
  fpath: ‘https://experimenthub.bioconductor.org/fetch/3081’
  reason: download failed
3: download failed
  hub path: ‘https://experimenthub.bioconductor.org/fetch/3081’
  cache resource: ‘EH3065 : 3081’
  reason: bfcadd() failed; see warnings()
```

This seems to apply to all three new files. The old ones work fine, though. Do you know what seems to have upset things, @lshep?

Thanks,
Jonny

**Comment by lshep** [comment]
Apologies I forgot to make the resources public.  They should be accessible now.

**Comment by jonathangriffiths** [comment]
Thanks @lshep!

I think everything is truly ready to go now, @Liubuntu! The only change I have made since your previous review was to add one further exported object, which summarizes some metadata for each 10x sample in the atlas (`AtlasSampleMetadata`).

Thanks,
Jonny

**Comment by Liubuntu** [comment]
HI @jonathangriffiths , 

Seems that you have made some commits and bumped version. It's weird that the building machine didn't catch it correctly. Could  you do the version bump again? As long as the building is clear on all platforms, we are ready to go. 

Best,
Qian

**Comment by jonathangriffiths** [comment]
Hi @Liubuntu,

I think it has done a build already - you can see version 0.99.10 here: http://bioconductor.org/spb_reports/MouseGastrulationData_buildreport_20190807094737.html

Jonny

**Comment by jonathangriffiths** [comment]
I have also made one (final!) formatting change which will trigger a new build now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jonathangriffiths.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MouseGastrulationData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MouseGastrulationData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
