### ISSUE TITLE
NiftiArray Package

### ISSUE THREAD

**Issue by muschellij2** [Bioconductor/Contributions#1173]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/muschellij2/NiftiArray

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
**Covers imaging** - which can be related to **genomic** data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
**BEFORE GOING FURTHER WITH ANY REVIEW**
-  [ ] were you planning on submitting to CRAN? confused at the CRAN badges and
  the `cran-comments.md` file as well as a reference to Neuroconductor.  The
  package should be submitted to CRAN, Bioconductor, or Neuroconductor not all. 

If you plan to continue with Bioconductor: 

**Build report**
- [ ] Fix ERROR for git tracking. do not include the niftiArray.Rproj file.
```
# do this and commit 
git rm niftiArray.Rproj
```
If you want to keep that file your your own reference after you do the above to
the git repository/commit.  Include that file in the `.gitignore` file. 

- [ ] Please fix the package versioning. We use x.y.z versioning.  Please
  increment the next version bump to `0.99.2` as we do not official recognize
  the rest.


**README.md/README.Rmd**

- [ ] should use only one format. You don't need a `.md` and a `.Rmd`

I will do a more thorough review after you comment your intentions for submission.

**Comment by lshep** [comment]
@muschellij2    Any comments on the intentions for this package?  Again it should only be submitted to one location (CRAN/Bioconductor/Neuroconductor).

**Comment by muschellij2** [comment]
I think we're going to go with Neuroconductor.  We'd like it on BioC (and
would like to see the process), but it may make the most sense on
Neuroconductor.
Best,
John

**Comment by lshep** [comment]
I'm going to close the issue for now.  If you change your mind feel free to reopen the issue.
