### ISSUE TITLE
(inactive) prioGene

### ISSUE THREAD

**Issue by huerqiang** [Bioconductor/Contributions#1179]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/huerqiang/prioGene

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
The vignette is not satisfactory; compare to other recent submissions.

Your package should interoperate with other Bioconductor packages as appropriate, e.g., [SummarizedExpermiment][1]

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by huerqiang** [comment]
Thank you for your review. I have updated my vignette.

**Comment by huerqiang** [comment]
Thank you for your review. I have updated my vignette.






At 2019-07-15 21:33:28, "Martin Morgan" <notifications@github.com> wrote:


The vignette is not satisfactory; compare to other recent submissions.

Your package should interoperate with other Bioconductor packages as appropriate, e.g., SummarizedExpermiment

**Comment by mtmorgan** [comment]
To clarify -- my comments were not a review, but rather an indication that without changes your package could not be reviewed. It has now been added to the review queue.

**Comment by Liubuntu** [comment]
Hi @huerqiang , 

Please refer to the [build report](http://bioconductor.org/spb_reports/prioGene_buildreport_20190717063911.html) and fix all errors / warnings / notes before an official review will be given. Let me know for any questions. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @huerqiang , 

Please try to respond to the comments above within 14 days. Responses could be package updates, commits, new building reports, questions, comments, etc. 

We are expecting the package contributor to actively work with the reviewer to smooth the the package submission. Let me know also if you think the above points would require elongated time, so that we can temporarily close this issue. You can comment back here later so that we can reopen the issue when you are finished.  

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @mtmorgan , I just realized that I was unassigned from this issue. So I will leave it to your review. :)

**Comment by huerqiang** [comment]
Dear Qian,
I want to add some functionality to this R package, so it may take some extra time.

Best,
huerqiang

At 2019-07-30 23:19:59, "Qian Liu" <notifications@github.com> wrote:


Hi @huerqiang ,

Please try to respond to the comments above within 14 days. Responses could be package updates, commits, new building reports, questions, comments, etc.

We are expecting the package contributor to actively work with the reviewer to smooth the the package submission. Let me know also if you think the above points would require elongated time, so that we can temporarily close this issue. You can comment back here later so that we can reopen the issue when you are finished.

Best,
Qian

**Comment by huerqiang** [comment]
@mtmorgan, I want to add some functionality to this R package, so it may take some extra time

**Comment by mtmorgan** [comment]
Ok I'll mark this as 'inactive'. Post a comment here when you are ready for the review process to continue.
