### ISSUE TITLE
oppti

### ISSUE THREAD

**Issue by aelmas** [Bioconductor/Contributions#1182]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Huang-lab/oppti

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Hmm, looks like your package doesn't have any help (man) pages; did you forget to add them to the github repository? As a sanity check, you could try and build & check a fresh clone of your package
```
$ cd /tmp
$ git clone https://github.com/Huang-lab/oppti
$ R CMD build oppti
$ R CMD check oppti_0.99.0.tar.gz
```
or similar with `devtools::check("oppti")`.

Respond here with a comment to @mtmorgan when your repository is complete, and we'll start the review process.

**Comment by aelmas** [comment]
Oh, thanks for reminding that! 

I added the man files now, they were indeed missing.

@mtmorgan

**Comment by lshep** [comment]
Bioconductor only allows package dependencies that are on CRAN or Bioconductor.  It appears `cafr` is not on either.  Your package will either have to not utilize this package or you should reach out to have `cafr` submit there package to one of the package repositories.

**Comment by aelmas** [comment]
My package no longer utilizes `cafr`. Could you please continue review process? Thank you!

**Comment by lshep** [comment]
Please follow the instructions for setting up your [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook).   After this is completed, please do a version bump to trigger a rebuild of the package.  When the package can build and check without ERROR @hpages   will provide a more indepth review.  Thank you.

**Comment by aelmas** [comment]
I think I have resolved all issues. Could you please perform a quick evaluation of the package? Thanks!

**Comment by aelmas** [comment]
I have addressed most of the remaining notes. Could you please perform a quick evaluation of the package? Thank you!

**Comment by aelmas** [comment]
I have addressed most of the remaining notes. Could you please perform a quick evaluation of the package? Thank you!

**Comment by aelmas** [comment]
I have addressed most of the remaining notes. Could you please perform a quick evaluation of the package? Thank you!

**Comment by lshep** [comment]
@aelmas  Just checking in if you will be making the above suggested changes?  The release is fast approaching and the deadline for packages to be accepted and included in the Oct 30th release is Oct 23th.  Otherwise the package will remain in the devel branch until the Spring release.

**Comment by aelmas** [comment]
I will do them asap -- thanks for the heads up!

**Comment by aelmas** [comment]
@mtmorgan Thank you for your comments. I addressed them carefully and posted my updates below. 
@lshep Can we submit it in time for the October release?

> NEWS
> - is this file formatted so that it is parsed by utils::news() ?
> 
No, it is manually edited.

> Vignettes
> - no need to include the .md version; this is generated by R CMD build
>
Removed.

> - use library(oppti) rather than devtools::load_all(), since users will generally not be in the package source tree when working through the vignette.
>
Done.

> R
> - Since the data is fundamentally rectangular (protein / gene expression X sample) does it make sense to use SummarizedExperiment for the dat and data arguments to many of your functions? This increases interoperability with other Bioconductor packages and provides a robust framework for structuring data.
>
Restructuring data will not be necessary since the examples contain toy data sets in the basic data frame format which is perhaps more appropriate for reproducibility.

> - use message() instead of print() when providing informational messages, e.g., analyze.R:210
>
Done.

> - please reconsider use of a 'banner' when your package is attached -- if each package did this, then the user would be overwhelmed by promotional material.
>
I avoided the use of banner.

**Comment by lshep** [comment]
@aelmas  It still has a chance to be included.  @mtmorgan  will have to look at the changes and see if there are any other recommendation that need to be done.

**Comment by mtmorgan** [comment]
The NEWS files should be revised so that it can be read by `utils::news()`, since that is what we use to summarize new and updated packages in the release announcement, e.g., http://bioconductor.org/news/bioc_3_9_release/#news-from-new-and-existing-software-packages

**Comment by aelmas** [comment]
@mtmorgan Is there a particular way (template / function) to generate such readable NEWS file?
The "New Package Primer" page on Bioconductor website seems to fall short explaining how to make NEWS files. Thank you!

**Comment by mtmorgan** [comment]
One possibility is to `usethis::use_news_md()`; another is to copy-and-paste from a package with NEWS, e.g., https://github.com/Bioconductor/GenomicRanges/blob/master/NEWS

**Comment by aelmas** [comment]
@mtmorgan I updated the NEWS file according to the template in your link. Thank you!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/aelmas.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("oppti")`. The package 'landing page' will be created at

https://bioconductor.org/packages/oppti

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by aelmas** [comment]
@mtmorgan I have submitted my SSH key to Bioconductor. Do I need to take any further action?
