### ISSUE TITLE
(inactive) TCseq

### ISSUE THREAD

**Issue by Renfang2019** [Bioconductor/Contributions#1185]
Dear developer,

thank you for the package. I have tca in correct but when I run countReads and it showed me could not find the bam files. Any ideas? Thank you very much.
tca
An object of class "TCA"
@design
sampleid timepoint group bamfile
1 1 E16 1 E16WTc_chr.bam
2 2 P0 2 P0H2_chr.bam

@genomicFeature
chr start end id
1 chr1 3116838 3117177 peak1
2 chr1 3117299 3117603 peak2
3 chr1 3361023 3361221 peak3
4 chr1 3372724 3372891 peak4
5 chr1 3395611 3395733 peak5
132621 more rows ...

@clusterRes
An object of class "clust"

tca <- countReads(tca, dir='C:/Users/rsong/Downloads/chromVAR/TCseq')
Error in countReads(tca, dir = "C:/Users/rsong/Downloads/chromVAR/TCseq") :
Can not find 'BAMfile' in design, please check if the correspoinding field is missing or uses a different column name.

**Comment by mtmorgan** [comment]
Seek help on the Bioconductor support site https://support.bioconductor.org or with `maintainer("TCseq")`
