### ISSUE TITLE
GmicR

### ISSUE THREAD

**Issue by Rvirgenslane** [Bioconductor/Contributions#1192]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Rvirgenslane/GmicR

Confirm the following by editing each check box to '[x]'

- [X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ X] The 'devel' branch for new packages and features.
- [ X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Rvirgenslane** [comment]
Checking new package version number...
    * ERROR: New package version starting with 0.99.* (e.g., 0.99.0,
      0.99.1, ...); got '0.2.0'.

I changed the current version to 0.99.3

Namespace dependency not required: data.table
 
I removed this



Checking DESCRIPTION/NAMESPACE consistency...
    * WARNING: Import data.table, grDevices, graphics, stats, utils in
      DESCRIPTION as well as NAMESPACE.

I added these to the DESCRIPTION

**Comment by dvantwisk** [comment]
Can you perform a version bump so that we can remove the "version bump required" tag.

**Comment by Rvirgenslane** [comment]
How goes the review process?

**Comment by Rvirgenslane** [comment]
How goes the review process?  Is there anything I can do to help?

Richard

**Comment by dvantwisk** [comment]
Apologies for the wait! I should have it in today.

**Comment by Rvirgenslane** [comment]
Great! Thanks for the update.

**Comment by dvantwisk** [comment]
Here is a review of your package. The code is very well done and most of my issues stand with the documentation. [REQUIRED] tags describe changes that must be addressed or changed. [CONSIDER] tags describe changes that are advisable but not necessary. Please message me back when you are done making changes.

- [ ] [REQUIRED] `roxygen` notes mention "boolean" values. In R these are
called `logical` and should be changed accordingly. In general, it's best
to explicitly state what type of data is used by a certain results or a
parameter.

vignettes
- [ ] [REQUIRED] Remove the Stangled file `GmicR_vignette.R`. It shouldn't be
needed in the repo.

vignettes/GmicR_vignette.Rmd
- [ ] [REQUIRED] L41-43: `BiocManager::install()` can and should be used to 
download R packages that are on CRAN. Also, the line doesn't seem necessary
to the user as the package should install the packages that are in the `Depends`
and `Imports` section of your `DESCRIPTION` file. This also goes for the extra
packages that you have listed in L31-33. All that needs to be shown to the user
about installing the package should be:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install('GmicR')
```
-[ ] [REQUIRED] L130,183,196, 271, 278: We generally want to see using facing code run on the
build machines, so the `eval=FALSE`s should be removed. There are some cases
when they are okay, such as when the code would open up something interactive.
Do all these code chunks open shiny interfaces? If so, then they can stay.

**Comment by Rvirgenslane** [comment]
Thank you dvantwisk  for this review!

> Here is a review of your package. The code is very well done and most of
my issues stand with the documentation. [REQUIRED] tags describe changes
that must be addressed or changed. [CONSIDER] tags describe changes that
are advisable but not necessary. Please message me back when you are done
making changes.
>
> * [ ]  [REQUIRED] `roxygen` notes mention "boolean" values. In R these are
>   called `logical` and should be changed accordingly. In general, it's
best
>   to explicitly state what type of data is used by a certain results or a
>   parameter.

I have changed all the "boolean" value references to "logical".



> vignettes
>
> * [ ]  [REQUIRED] Remove the Stangled file `GmicR_vignette.R`. It
shouldn't be
>   needed in the repo.

File removed.

> vignettes/GmicR_vignette.Rmd
>
> * [ ]  [REQUIRED] L41-43: `BiocManager::install()` can and should be used
to
>   download R packages that are on CRAN. Also, the line doesn't seem
necessary
>   to the user as the package should install the packages that are in the
`Depends`
>   and `Imports` section of your `DESCRIPTION` file. This also goes for
the extra
>   packages that you have listed in L31-33. All that needs to be shown to
the user
>   about installing the package should be:
>
> ```
> if (!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install('GmicR')
> ```

I removed the lines referencing installation of cran packages and added:

if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install('GmicR')


> -[ ] [REQUIRED] L130,183,196, 271, 278: We generally want to see using
facing code run on the
> build machines, so the `eval=FALSE`s should be removed. There are some
cases
> when they are okay, such as when the code would open up something
interactive.
> Do all these code chunks open shiny interfaces? If so, then they can stay.

I removed all "eval=FALSE' arguments.  This lead to errors during the
vignette build tests. To solve this issue, I add the argument
"results=FALSE" to L128.


Thank you again for you review.  Please let me know if you have any other
concerns.

**Comment by Rvirgenslane** [comment]
Sorry about the formatting issue.  Here is a better version:

Thank you dvantwisk  for this review!  

> Here is a review of your package. The code is very well done and most of my issues stand with the documentation. [REQUIRED] tags describe changes that must be addressed or changed. [CONSIDER] tags describe changes that are advisable but not necessary. Please message me back when you are done making changes.
> 
> * [ ]  [REQUIRED] `roxygen` notes mention "boolean" values. In R these are
>   called `logical` and should be changed accordingly. In general, it's best
>   to explicitly state what type of data is used by a certain results or a
>   parameter.

I have changed all the "boolean" value references to "logical".



> vignettes
> 
> * [ ]  [REQUIRED] Remove the Stangled file `GmicR_vignette.R`. It shouldn't be
>   needed in the repo.

File removed.

> vignettes/GmicR_vignette.Rmd
> 
> * [ ]  [REQUIRED] L41-43: `BiocManager::install()` can and should be used to
>   download R packages that are on CRAN. Also, the line doesn't seem necessary
>   to the user as the package should install the packages that are in the `Depends`
>   and `Imports` section of your `DESCRIPTION` file. This also goes for the extra
>   packages that you have listed in L31-33. All that needs to be shown to the user
>   about installing the package should be:
> 
> ```
> if (!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install('GmicR')
> ```

I removed the lines referencing installation of cran packages and added:

if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install('GmicR')


> -[ ] [REQUIRED] L130,183,196, 271, 278: We generally want to see using facing code run on the
> build machines, so the `eval=FALSE`s should be removed. There are some cases
> when they are okay, such as when the code would open up something interactive.
> Do all these code chunks open shiny interfaces? If so, then they can stay.

I removed all "eval=FALSE' arguments.  This lead to errors during the vignette build tests. To solve this issue, I add the argument "results=FALSE" to L128.


Thank you again for you review.  Please let me know if you have any other concerns.

**Comment by Rvirgenslane** [comment]
Hi dvantwisk, 

Have you had time to see my updates?

**Comment by Rvirgenslane** [comment]
Hi dvantwisk, 

Is there anything else that you require from me?

**Comment by dvantwisk** [comment]
Sorry for the delay! The changes look good. I will move to accept your package.

**Comment by Rvirgenslane** [comment]
AWESOME!  Thanks for your input!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Rvirgenslane.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GmicR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GmicR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
