### ISSUE TITLE
GOpro

### ISSUE THREAD

**Issue by lidiaad** [Bioconductor/Contributions#120]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mi2-warsaw/GOpro

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor. 
Please see the following that need to be addressed: 

**GENERAL:**
 
It seems like your function findGO is really the main function  of your package. It is the simplest for a user to use and condenses down all the intermediate steps you go through in the current vignette; Yet it is not mentioned anywhere. I would focus on this function in the vignette and also reference it in the GOpro.Rd (ie. in  GOpro.Rd  add a \seealso{\link{findGO}} )

The steps of using aovTopTest, groupByTukey/clustering, findAllGOs, findTopGOs, etc... are all run from within findGO.  I would recommend, not exposing the user to these intermediate functions (aovTopTest, groupByTukey/clustering, findAllGOs, findTopGOs, etc..), making them internal, and only focusing on findGO.  It also seems like tukeyHSDTest, isConflict, makeNames, TukeyCore, and ontologyOver are all used internally and never by a user; please also make these internal. 

We like compatibility with other Bioconductor objects.  I would change or at least additionally add the input of findGO to be compatible with a MultiAssayExperiment, which is comparable with your list of data.frames of varying dimension. [See: MultiAssayExperiment](https://bioconductor.org/packages/devel/bioc/html/MultiAssayExperiment.html) 

Your output could be more structured and utilize the exisiting S4Vector infastructure for list of character vectors, etc. It is fine if you would like to define your own class("GO" and "geneclusterplot"), but please base it off of a more structured S4Vectors class like CharacterList, NumericList, etc. [See: IRanges](https://bioconductor.org/packages/3.4/bioc/html/IRanges.html) 

```
library(IRanges)
?CharacterList
```

An example of use of CharacterList including how to subset:
```
libary(IRanges) 
cl = CharacterList(list(letters[1:5], LETTERS, state.name))
cl
il = IntegerList(list(1:5, 1:26, 1:52))
df = DataFrame(char = cl, int = il)
cl[il > 11]
```

(Note: if you really want to keep all the intermediate functions (aovTopTest, groupByTukey/clustering, findAllGOs, findTopGOs, etc) visible and accessable to the user, we would require the output of these structures to be more in line with a CharacterList, NumericList, etc. ) 

**OTHER COMMENTS:**
 
Remove all "::" for R code. You should not need these if the packages are properly specified in the DESCRIPTION and NAMESPACE files. 

I feel like the DESCRIPTION Description should be the consice description in your man page GOpro.Rd and this more detailed description should be in GOpro.Rd. 

Please look over your vignette. There are some typos and phrasing issues.  
Please also change the output to BiocStyle::html_document and add suggest BiocStyle to the DESCRIPTION. Bioconductor likes to have a consistant vignette syle. [vignette sytle](http://www.bioconductor.org/packages/release/bioc/vignettes/BiocStyle/inst/doc/HtmlStyle.html)

Please also include a section for installation and loading by adding sections like the following: 
```
<installation,eval=FALSE>>=
source("http://www.bioconductor.org/biocLite.R")
biocLite("GOpro",dependencies=TRUE)
@
```
After the package is installed, it can be loaded into R workspace typing
```
<<loading,eval=TRUE,results='hide',warning=FALSE,message=FALSE>>=
library(GOpro)
@
```

I think your packages has a lot of potential and with some restructuring and focus will be a nice addition to Bioconductor. I look forward to reviewing your updates.

**Comment by lshep** [comment]
Thank you for your updates.  A few more minor changes that should be addressed: 

**VIGNETTE**
It would be nice if the plots are displayed 

**UNIT TESTS** 
It is a NOTE in the build report but we do strongly encourage adding unit tests to the package.  Some simple suggestions:  test your input data object you provide that it has your restrictions of being >=3  cohorts  and that all the rownames are equivalent.  

**R/CODE**
remove "::"  they shouldn't be needed if declared correctly in DESCRIPTION/NAMESPACE 
findAllGOs.R  there is an AnnotationDbi:: ,  you import(annotationDbi) in NAMESPACE so "::" not necessary
RcppExports.R there  is Rcpp::compileArrtributes ,  please add this as an importFrom in your NAMESPACE and remove "::" 

This is very close to acceptance with these minor changes. 
Thank you 
Lori

**Comment by lshep** [comment]
Thank you for making these changes. The package looks okay now and I will recommend be accepted. You should get svn instructions via email in the next couple of days
