### ISSUE TITLE
pulsedSilac

### ISSUE THREAD

**Issue by marcpaga** [Bioconductor/Contributions#1205]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/marcpaga/pulsedSilac

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by marcpaga** [comment]
Hi @Liubuntu, 
I was wondering if there were any updates on the progress of the review?
Best regards and thanks in advance,
Marc

**Comment by Liubuntu** [comment]
Hi @marcpaga , 

The review is underway and will be posted shortly. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment]
**IMPORTANT:** The `metadata` slot of `SummarizedExperiment` is
designed as a list to store any type of experiment related meta data,
which could be a perfect fit for the current `metaoptions`. The
strategy would be that you can introduce your new S4 class and
directly extend the `SummarizedExperiment` class without adding any
additional slot. To distinguish with the parent `SummarizedExperiment`
class, add validity functions to check the required elements (here
"conditionCol" and "timeCol") in `metadata` slot as you have done for
the `metaoptions`.

Also naming-wise, your data and methods are specifically about the
SILAC experiments, and the validity information required are also
data-specific, so it's better to have the class names align with that,
e.g., `SILACExperiment`?  The current class names of
`ProteinExpeirment`, `PeptideExperiment` and `ProteomicsExperiment`
are too general for this specific purpose and users could not easily
inherit or adapt these class for their different kind of protein
analysis. On the other side, _Bioconductor_ would also like to reserve
these general class names for more comprensive data representations
whenever needed.
@mtmorgan any comments or suggestions?

**Comment by marcpaga** [comment]
Hi @Liubuntu,

Thanks for the detailed comments. I will work on the points that you describe and update the package.

I must mention that I am a bit worried about changing the `ProteomicsExperiment` class since the linked subsetting is something that I would prefer not touching. Nevertheless, I will explore the `MultiAssayExperiment` class and see how easy it would be to extend it and its possible long term benefits.

**Comment by marcpaga** [comment]
Hi @Liubuntu,

### Regarding the `metaoptions` slot:

The reasoning why the additional slot was added was because it stored a "different" kind of data as what I understood the metadata slot was designed for. Nevertheless, I agree that having both is superfluous and having the metaoptions also on the show method is a good thing. The following actions have been taken (https://github.com/marcpaga/pulsedSilac/commit/588c65167985ec51bc171935d92a973bb5374f80, https://github.com/marcpaga/pulsedSilac/commit/4c4a3708c0508dd8a480c8737f306265251112fe):

- The `metaoptions` slot has been removed and now the metaoptions are stored in the `metadata` slot. 
- The validity, unit tests and documentation have been updated accordingly. 
- The metaoptions methods have been updated and kept in order to get access directly into these values.

### Regarding the names of the classes:
I agree that the class names are too generic for the purpose of this package and understand why Bioconductor wants to reserve such names. The following actions have been taken (https://github.com/marcpaga/pulsedSilac/commit/cf354b3a8b28e59812d560fd466977467a8b760d):

- The `ProteinExperiment` class has been renamed to `SilacProteinExperiment`
- The `PeptideExperiment` class has been renamed to `SilacPeptideExperiment`
- The `ProteomicsExperiment` class has been renamed to `SilacProteomicsExperiment`
- The constructor functions and documentation have been updated to their respective class names.

### Regarding extending the `MultiAssayExperiment`: 

As far as I understand, the power of the class comes from the `sampleMap` slot, which relates samples to the different assays/experiments in it. In the `SilacProteomicsExperiment` case, the relationship `data.frame` relates proteins with peptides (rows) and the number of samples is always the same since you measure peptides and the protein data is an aggregation of the peptide data. 

In that case, extending the `MultiAssayExperiment` class would still require to have new methods for the subsetting operations since the linked subsetting acts on columns based on the `sampleMap` but not on rows. And for row subsetting, it relies on `rownames` which would not be possible to in my case since multiple peptides can be assigned to multiple proteins.

For these reasons I would prefer to keep the `SilacProteomicsClass` as it is. 

Thanks again for the review and I will be looking forward to further comments.

**Comment by marcpaga** [comment]
Hi @Liubuntu,

I was wondering if there are any updates on the status of the review? 

Best,
Marc

**Comment by Liubuntu** [comment]
Hi @marcpaga , 

Sorry for the late response. This package is quite big with many generics, methods, and functions defined. I have just gone through all the R scripts, and have the following review. I'll continue with the other parts of the package: vignettes, documentations, unit tests, etc. and post later. Thanks!

Best,
Qian

## DESCRIPTION 
- ok!

## NAMESPACE
- ok!

## R/

- SUGGESTED: For some replace methods, such as
  `assaysPept<-,SilacProteomicsExperiment`, you may call the
  `BiocGenerics:::replaceSlots(, check=TRUE)`, which will
  automatically do the `validObject(x)` check by default, and return
  the updated object. This will generate some note messages in
  checking and loading for using `:::`, but those are fine.

- SUGGESTED: 

  https://github.com/marcpaga/pulsedSilac/blob/master/R/internals.R#L27-L42
  Seems this script could be replaced by?
  ```
  c(hasRowData(x@SilacProteinExperiment), hasRowData(x@SilacPeptideExperiment))
  ```
- SUGGESTED: using `switch` to avoid similar code chunks. e.g.,
  https://github.com/marcpaga/pulsedSilac/blob/master/R/scatterCompareAssay.R#L171-L188
  this could be replaced with:
  ```{r}
  dat <- switch(mode,
                protein = x@SilacProteinExperiment,
                peptide = x@SilacPeptideExperiment)
  scatterCompareAssays(x = dat,
                       conditions = ,
                       ... )
  ```

**Comment by marcpaga** [comment]
Hi @Liubuntu no worries, I just wanted to make sure that we were on the same page with the status of the review. 

Regarding your suggestions:

> SUGGESTED:
> https://github.com/marcpaga/pulsedSilac/blob/master/R/internals.R#L27-L42
> Seems this script could be replaced by?
> `c(hasRowData(x@SilacProteinExperiment), hasRowData(x@SilacPeptideExperiment))`

This is indeed better of what I had before. I have changed it in https://github.com/marcpaga/pulsedSilac/commit/6ce3e2743c7e3d2ed7c198ba7b95a8269d0d5f00.

> SUGGESTED: using switch to avoid similar code chunks.

I did not know that such function existed before, I already have in mind some other places where I want to use it, thanks for the suggestion. I have added it in two functions now https://github.com/marcpaga/pulsedSilac/commit/2b10a52d5b1748a2fd1dd4381dc22ba91da75350. 

> SUGGESTED: For some replace methods, such as `assaysPept<-,SilacProteomicsExperiment`, you may call the `BiocGenerics:::replaceSlots(, check=TRUE)`, which will automatically do the `validObject(x)` check by default, and return the updated object. This will generate some note messages in checking and loading for using `:::`, but those are fine.

To be able to use the `replaceSlots` function I have to import the whole `BiocGenerics` package. Upon doing so I get a warning message: `replacing previous import ‘BiocGenerics::Position’ by ‘ggplot2::Position’ when loading ‘pulsedSilac’`. Since I already have added the `validObject(x)` call in my replace methods, I would rather not have that warning message pop up. 
Using `@importFrom BiocGenerics replaceSlots` does not work since it is a non-exported function, is there any workaround this besides defining the function itself in the package?

**Comment by Liubuntu** [comment]
Hi @marcpaga , 

As a workaround to remove the warning message you had, you can use 
```
@rawNamespace import(ggplot2, except=c(“Position"))
```
 See here https://github.com/klutometis/roxygen/issues/617 for more details.

It's fine though that you keep your current script! 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @marcpaga , 

Please see below for the review of other parts. Please comment back here with any questions or updates. It's in pretty good shape for acceptance. 

## man/ 
- compareAIC: note exactly sure, but please confirm if the formula was
  showing correctly in function help page.

## vignette
- For `Installation` section, we would recommend to add some
  instruction for users if they want to use the development version,
  by pointing to the github repo or using
  `BiocManager::install(gitrepo/pkgname)` to install the development
  version from github using `BiocManager`.

- you can also use `Interoperability` when you mention
  `Transferability`, which is one major feature that Bioconductor
  promotes for the ecosystem as well as for new packages.
  https://www.bioconductor.org/developers/package-submission/#intro

## unit tests 
- good!

Cheers,
Qian

**Comment by marcpaga** [comment]
Hi @Liubuntu,

Thanks for the new comments. I have made some changes to address them.

> compareAIC: note exactly sure, but please confirm if the formula was
showing correctly in function help page.

Indeed the formulas were not correctly rendered. This was also true for the `calculateAIC`, `calculateIsotopeFraction` and `calculateOldIsotopePool` pages. This was something that also annoyed me that the mathematical notation was correctly rendered in the pdf manual but not on the help page. I guess HTML does not play so well with Latex. I have found a fix for it, that keeps the Latex for the pdf and creates an image for the HTML help page. It seems a bit hacky but is the only solution that I found. If you know of a better way I'd be happy to change it. Changed in https://github.com/marcpaga/pulsedSilac/commit/15f4253896ea4171339ea7c7f19dc8b222b679b7

> For Installation section, we would recommend to add some instruction for users if they want to use the development version, by pointing to the github repo or using BiocManager::install(gitrepo/pkgname) to install the development version from github using BiocManager.

I have added the installation through Github in the vignette. Changed in https://github.com/marcpaga/pulsedSilac/commit/43fe0e17ff3e0dff4abc35adb070b927be67e2b1

> you can also use Interoperability when you mention Transferability, which is one major feature that Bioconductor promotes for the ecosystem as well as for new packages. 

That was the word I was looking for! I have changed it in the vignette. Changed in https://github.com/marcpaga/pulsedSilac/commit/7cdc6669296bd21c87570f45c70ec13dcc895757

Cheers,
Marc

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/marcpaga.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pulsedSilac")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pulsedSilac

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
