### ISSUE TITLE
New package: blacksheepr

### ISSUE THREAD

**Issue by mcornwell1957** [Bioconductor/Contributions#1208]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ruggleslab/blacksheepr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mcornwell1957** [comment]
Hi @lshep - thank you very much for your help! First time contributor!
Looks like the issue is a build time timeout (and the R version update - ill do that now) I didn't realize there was a 15 minute build limit. All of that time comes from the vignette construction. My comp has the rest of the build clocked at about 40seconds. Is this a strict rule for vignettes? And therefore should I downsize my example analysis done in the vignette?
Thanks again

**Comment by mcornwell1957** [comment]
Hi - I'm sorry, but we agreed upon a name change here on our end, and that slightly changes the repo. How should I handle this change on this end? Thank you!

**Comment by lshep** [comment]
Sorry for the delay.  What is the name change?   Please comment here with the updated repository link and accurate name and also edit the first comment to reflect the new repository as well: 
 https://github.com/Bioconductor/Contributions/issues/1208#issue-481745400.  Don't forget to set up the webhook as before if it is an entirely new repository.  We will have to change the name in our database which we will take care of when you comment back with the new repository/name

**Comment by mcornwell1957** [comment]
Hi lshep, thanks for getting back to me! We just decided to move away from the camelcase and go all lowercase. I edited the first comment and here it is again below:
https://github.com/ruggleslab/blacksheepr
The webhook should hopefully be working as well. Sorry for the trouble!

**Comment by mcornwell1957** [comment]
I did not move to a new repo - I just changed the name of the one we were working out of, the webhook is still active, but it doesn't look like its syncing the push I just did. Do you have any ideas?
Thank you!

**Comment by lshep** [comment]
Yes I had to make the change in our database as well.  We just made the change.  Could you please try a valid version bump again to see if it works this time.

**Comment by lshep** [comment]
Looks like its working -  also sorry for the delayed review I've been away on vacation.  I'll have a review for you in the next few days.

**Comment by mcornwell1957** [comment]
great! And no problem at all, I hope you had a nice vacation. Looks like it passed - let me know what questions you have. As I mentioned before - I am a first time contributor and am happy to work on whatever you think needs improvement. Thank you very much!

**Comment by lshep** [comment]
Hello.  Sorry for the delay.  Here is an initial review.  I haven't looked in depth on the R code yet until some of the comments/considerations from working through the other parts of the package are addressed.  


**DESCRIPTION**

- [ ] We suggest removing the lazyData: true.  We have found that it rarely is beneficial and can actual slow the installation of a package. 

**NEWS**

- [ ] The NEWS file is formatted incorrectly.  Pleasee see the following link:  http://bioconductor.org/developers/package-guidelines/#news

**data/data man pages**

- [ ] Please give more detail about how the data was generated for both objects and be more detailed in both man pages sample_annotation.Rd/sample_values.Rd. Any source information or references,
etc.  Please be more detailed about the type of data it contains (result of running something? - )  as well as what the columns and rows represent. If a user wanted to mimic this object they should have an idea of how it was created and what data is being held in the object.  

**inst**

- [ ] inst/example_scripts seems to contain the same code that is in your current vignette. 
- [ ] inst/example_data seems like the same data included now in the `data` directory. If this is the case both of these directories should be removed. Do not include multiple copies of the same information in the package. 

**vignettes**
**blacksheepr_rna**

- [ ] 0.3 remove extra `library(blacksheepr)` call. You did it in 0.2
- [ ] Section 1.0.1.  Don't curl files from github.  Any example data needed should be included with your package. If you don't need the full annotation table the table that should be saved should be the subsetted table. 
- [ ] You have `outfilepath = getwd()` .  Output in examples/test/vignette should never write to a users directory. Please use tempdir() and tempfile() when appropriate
- [ ] Section 1.0.1.1 Having users format data manually is never really advisable. It should be avoided if possible. Could a helper function to format be made? It seems like anything with a value is `mutant` while `NA` is `None` this seems like it could easily be made into a helper function. There seems to be an extra column shown from the first version of compcols in 1.0.1 above and the one in this section (additional TP53_Mutation)? When you say to format the data manually, you are making changes directly to the compols object already in R? You don't actually show the object in the print out.  It will be hard for a user to follow this step if you don't show examples of how it is accomplished. 
- [ ] Section 1.0.1.2 So make_comparison_columns makes additional columns based on values in the original table? Does this mean there are required columns of data needed to run this function? 
- [ ] Section 1.0.2 Again do not curl from github. Included necessary files in package. 
- [ ] So you create a SummarizedExperiment Object from the data.  This is good. Can the output of other current bioconductor products or pipelines utilize your package functions if they are SummarizedExperiment Object. This would be ideal to be able to use a precompiled SummarizedExperiment Object too -  or being able to convert an existing if there is some special criteria needed for your functions. This could also be ensured if you had some validation within your functions.  
- [ ] What type of instrumentation provides the raw data files you are utilizing to create the summarized experiment object? 
- [ ] When I run the deva function in 1.0.4 it leaves a device open? 
- [ ] Section 1.0.4.  It seems like the output could have a more standardized structure. Lists of lists are rather hard to navigate and understand what is included as output from running your functions.  Are there any helper functions to parse/find/view different values that may be of particular importance from your structure? 
- [ ] Perhaps the tables should also be SummarizedExperiments or you could looks at GSEABase constructors for GeneSet and GeneSetCollection or their is a new package in review developed by the core team here called [BiocSets (GeneSet replacement class)](https://github.com/Kayla-Morrell/BiocSet)

**blacksheep_phosphoprotein**

- [ ] Besides using the different file how are the two vignettes different?  They seem to have everything the same. 


Thanks for your submission.  I look forward to getting your package into Bioconductor.  Please make any code adjustments and when ready do a version bump with the new version of the package and please comment back here addressing or commenting on the above points. 

Cheers,

**Comment by mcornwell1957** [comment]
Hi - I just wanted to check in and see if there is anything else you would like me to improve upon or correct for submission? Thank you very much for your continued help!

**Comment by lshep** [comment]
Sorry for the delayed response.  I'll re-evaluate the package over the weekend and have a post for you soon.

**Comment by lshep** [comment]
Thanks for those updates. Looking much better.  Please see further comments below: 

**Vignette**

- [ ] Now that there is only one maybe it should be renamed to just `blacksheepr`  . This is completely optional and you can leave as is but I feel a naive user will be more apt to blindly do 
```
vignette("blacksheepr")
# rather than
vignette("blacksheep_phosphoprotein")
```


**R code**
- [ ] Use `<-` instead of `=` for the assignments. Unless using as an assignment in a function call it is the preferred assignment method in R code and in examples/vignette. (ie.  myVar <- myfunction(x = myvalue) 

- [ ] It's fine to default to `getwd()` for an outfile location, but in your examples and vignettes this should be changed to `tempdir()`. 

 - [ ] Please reformat stop/warning/message to not have `paste0`. They do paste0    by default so it is unnecessary:
```
> vl = 12
> stop("something ", vl, " something else")
Error: something 12 something else
```

 - [ ] (More of an FYI and totally stylistic) For What It's Worth, a function will return whatever the last value is so its slightly unnecessary to do for example the following  
```
    output = do.call(cbind, outtablelist)
    return(output)
```

You could just have

```
do.call(cbind, outtablelist)
```

But traditionally returns make it super explicit of what is being returned - so again nothing to do here but just passing along knowledge. 



- [ ] Does group1 values ever influence group2 values in outlier_analysis?  It seems like everything done to group1 is done to group2 - repeated code isn't really desirable - it seems like it would be cleaner to make a function that takes in the group1 data and whatever values that make it different than group2 and then call this function for determining the values? Reducing code in this way makes it cleaner and easier to maintain. 


 - [ ] Where does the code diverge? so line 409/414 the upstatgroup1 and upstatgroup2 are assigned the same exact values and then cbind together? It seems like a mistake to have the same values as it's just a straight duplication and doesn't seem to get updated?  

```
        if ("1" %in% colnames(group1tab)) {
            upstatgroup1 = upstatgroup2 =
                apply(comptab1a, 1, split_and_fish, sidedness = "up")
        } else { upstatgroup1 = upstatgroup2 = NULL }

        if ("-1" %in% colnames(group1tab)) {
            downstatgroup1 = downstatgroup2 =
                apply(comptab1a, 1, split_and_fish, sidedness = "down")
        } else { downstatgroup1 = downstatgroup2 = NULL }

        fishout = cbind(upstatgroup1, upstatgroup2,
                        downstatgroup1, downstatgroup2)
``` 

Please look at the above issues.  Again when ready please do a version bump to trigger a build and comment back here.  Thank you!

**Comment by mcornwell1957** [comment]
Thanks for those updates. Looking much better. Please see further comments below:

Vignette

[X]  Now that there is only one maybe it should be renamed to just blacksheepr . This is completely optional and you can leave as is but I feel a naive user will be more apt to blindly do
```
vignette("blacksheepr")
# rather than
vignette("blacksheep_phosphoprotein")
R code
```

-- Done

[X] Use <- instead of = for the assignments. Unless using as an assignment in a function call it is the preferred assignment method in R code and in examples/vignette. (ie. myVar <- myfunction(x = myvalue)

-- Done ( to the best of my knowledge, probably missed some, but I think I got a lot)

[X] It's fine to default to getwd() for an outfile location, but in your examples and vignettes this should be changed to tempdir().

-- Done. I think I got them all - The only place I think I am still using this function and syntax is a part of the actual outlier_analysis call as a utility parameter. Besides that, I think I got rid of the rest - it seems to be better practice to output function returns as an object, which the user can then decide if they want to save out or not.

[X] Please reformat stop/warning/message to not have paste0. They do paste0 by default so it is unnecessary:

> vl = 12
> stop("something ", vl, " something else")
Error: something 12 something else

--Done

[ ](More of an FYI and totally stylistic) For What It's Worth, a function will return whatever the last value is so its slightly unnecessary to do for example the following
```
    output = do.call(cbind, outtablelist)
    return(output)
You could just have

do.call(cbind, outtablelist)
```
But traditionally returns make it super explicit of what is being returned - so again nothing to do here but just passing along knowledge.

-- Interesting, makes sense and thank you. I think for my own readability and understanding, I will leave as is. If for whatever reason you want me to change this because it is better practice, then let me know.

 Does group1 values ever influence group2 values in outlier_analysis? It seems like everything done to group1 is done to group2 - repeated code isn't really desirable - it seems like it would be cleaner to make a function that takes in the group1 data and whatever values that make it different than group2 and then call this function for determining the values? Reducing code in this way makes it cleaner and easier to maintain.

-- I did a big clean up and functionalizing of the code to make it cleaner. In short - the answer is YES group1 and group2 do interact late when it comes to applying filters. Specifically at #409 when filtering by proportions (which requires group{1|2}/(group1 + group2). This filter is used to exclude genes with no diff in prop, but also later on for FDR correction.

 Where does the code diverge? so line 409/414 the upstatgroup1 and upstatgroup2 are assigned the same exact values and then cbind together? It seems like a mistake to have the same values as it's just a straight duplication and doesn't seem to get updated?

        if ("1" %in% colnames(group1tab)) {
            upstatgroup1 = upstatgroup2 =
                apply(comptab1a, 1, split_and_fish, sidedness = "up")
        } else { upstatgroup1 = upstatgroup2 = NULL }

        if ("-1" %in% colnames(group1tab)) {
            downstatgroup1 = downstatgroup2 =
                apply(comptab1a, 1, split_and_fish, sidedness = "down")
        } else { downstatgroup1 = downstatgroup2 = NULL }

        fishout = cbind(upstatgroup1, upstatgroup2,
                        downstatgroup1, downstatgroup2)

-- Ok, I think I see what happened. This was slightly deprecated code where we used to run both positive AND negative analysis together always by default. Later we realized this was a mistake and in the fix, I left the code to be adoptive to pos AND/OR neg, which is redundant by this point - because it only does one or the other. Good catch - major rewrite done to clean and fix this up. I Also did a big redundancy reduction in the main `deva` call along the same lines.

[ ] QUESTION: In my clean up, I have a number of nested functions now, especially within the outlier_analysis function. Whats best practice for these functions that dont need to be called ever by themselves. Leave nested? Put into some kind of supp_fns.R file? Same file but placed out of the actual usable function?

[ ] QUESTION: I had this one in my last inline comments - but it was buried and not a big deal. But with regards to the data annotation: when documenting the dataset - it throws a warning unless I document every variable in my data structure (which is 76 columns - each one just being a sample. I know in the docs: http://r-pkgs.had.co.nz/data.html#documenting-data Hadley used a "..." to avoid documenting everything, but I can't seem to get that to work. For now to avoid the error I actually went through and threw a descriptive line for each item - but this is pretty redundant for this kind of data table.

Please look at the above issues. Again when ready please do a version bump to trigger a build and comment back here. Thank you!

-- Done! Thank you for your continued help, please let me know what else you would like me to change

**Comment by lshep** [comment]
QUESTION: In my clean up, I have a number of nested functions now, especially within the outlier_analysis function. Whats best practice for these functions that dont need to be called ever by themselves. Leave nested? Put into some kind of supp_fns.R file? Same file but placed out of the actual usable function?
It is up to you.  Having a lot of nested functions tends to make the function hard to read and determine what is being done.  Either option of creating the separate file internal_fns.R  to house these or having in the same file but out of the usable function are acceptable.  Personally, I like a separate file but thats my own opinion. 

QUESTION: I had this one in my last inline comments - but it was buried and not a big deal. But with regards to the data annotation: when documenting the dataset - it throws a warning unless I document every variable in my data structure (which is 76 columns - each one just being a sample. I know in the docs: http://r-pkgs.had.co.nz/data.html#documenting-data Hadley used a "..." to avoid documenting everything, but I can't seem to get that to work. For now to avoid the error I actually went through and threw a descriptive line for each item - but this is pretty redundant for this kind of data table.

Hmm.... this doesn't see quite right but off hand I don't know of a way around it.  Does maybe a tag like @describeIn  seem appropriate that might be useful? 


If you want to reformat the nested functions and version bump once more.  As long as the build report still builds clean I'm ready to accept.

**Comment by mcornwell1957** [comment]
HI @lshep  - I think I am all set - but I am afraid I dont know what this error is! Is this something I can fix? I am happy with it on my end if you are.

**Comment by lshep** [comment]
That's on our end. You're good.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mcornwell1957.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("blacksheepr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/blacksheepr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
