### ISSUE TITLE
RNAseq123

### ISSUE THREAD

**Issue by mritchie** [Bioconductor/Contributions#123]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mritchie/RNAseq123

This workflow package supports our recent F1000Research article http://f1000research.com/articles/5-1408/v1. We hope to have this package available on Bioconductor as part of our revision of this article.

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Hi Matt,
Nice workflow.
(1) Looks like you need to add Mus.musculus to 'Depends'. I would say 'Suggests' if this were a software package but I think it's just a workflow so the vignette is the main event.

(2) This chunk should not be evaluated:

```{r Glimmainstall, message=FALSE}
source("http://www.bioconductor.org/biocLite.R")
biocLite("Glimma", suppressUpdates=TRUE)
```
Specifying the version of Glimma in 'Depends' should be enough.

(3) limma and edgeR are in 'Depends' so they are attached when the package is loaded. You don't need to load them in this chunk:

```{r import2}
library(limma)
library(edgeR)
x <- readDGE(files, columns=c(1,3))
class(x)
dim(x)
```

Valerie

**Comment by mritchie** [comment]
Thanks for the feedback Val. In the updated 0.99.2 that I just pushed to github, I have 

1) added Mus.musculus to Depends 
2) removed this chunk altogether, as it is handled by the Depends in the package 
3) moved 

library(limma) 
library(Glimma) 
library(edgeR) 
library(Mus.musculus) 

to a code chunk in the Set-up section and set eval=FALSE as a reminder that in general you will need to load these packages to be able to the things outlined in this workflow. 

I have a further question that I couldn't get to the bottom of. I want to include a screenshot of one of the Glimma plots in the vignette. 

I tried including the line 

![Interactive mean-difference plot generated using **Glimma**. Summary data (log-FCs versus log-CPM values) are shown in the left panel which is linked to the individual values per sample for a selected gene in the right panel. A table of results is also displayed below these figures, along with a search bar to allow users to look up a particular gene using the annotation information available, e.g. the Gene symbol identifier *Clu*.](vignettes/glMDPlot.png) 

but the build complained that it couldn't find the file glMDPlot.png (from memory I tried a few variations on this like ending the line in (glMDPlot.png) instead, but the same message resulted). Do you know if it is possible to include a figure that hasn't been generated on the fly in R in a vignette? 

Thanks, 

Matt 
----- Original Message -----

**Comment by vobencha** [comment]
A good example of how to include screenshots is the [pRlocGUI vignette](http://www.bioconductor.org/packages/3.4/bioc/vignettes/pRolocGUI/inst/doc/pRolocGUI.html).

An alternative to (3) above is to just load the package, library(RNASeq123); all packages in 'Depends' will be added to the search path. Up to you here, however you'd like to handle this is fine.

Val

**Comment by vobencha** [comment]
I spoke too soon. Currently biocLite() does not look in the workflows/ svn directory so installation is handled differently. The suggested installation approach is  
```
source("http://bioconductor.org/workflows.R")
workflowInstall("RNASeq123")
```
We had a discussion about this today and in general like the idea of future workflows being submitted as light weight packages, as yours is, with no extra R code, no native code etc. For now we need to use the old system so at the top of your vignette I would explicitly load each package instead of biocLite(RNASeq123).
Val

**Comment by mritchie** [comment]
Thanks Val. Have kept the library() parts at the start. 

Have also made the assumption that the package will eventually be online at http://www.bioconductor.org/help/workflows/RNAseq123/ in the availability section at the end of the Rmd. 

I can't seem to get the screenshot to include properly though - I used the same command and directory structure as in the example you sent, but get the following message when I build: 


pandoc: Could not fetch figures/glMDPlot.png 
figures/glMDPlot.png: openBinaryFile: does not exist (No such file or directory) 
Error: processing vignette 'limmaWorkflow.Rmd' failed with diagnostics: 
pandoc document conversion failed with error 67 
so have left it commented out. Ending that particular line of code in (./glMDPlot.png) or (glMDPlot.png) gave similar errors (in the first example I made a new directory 'figures' and copied the image into it, in case it only looked in 'figures' for the files, but it seems this isn't the problem. 

Cheers, 

Matt 
----- Original Message -----

**Comment by vobencha** [comment]
I put the .png in a figures/ directory and added 'self_contained: no' to the vignette header and the package built.

output: 
  BiocStyle::html_document:
    fig_caption: true
    self_contained: no

Not sure why Laurent's vignette runs without this directive ...
Val

**Comment by mritchie** [comment]
Thanks Val - version 0.99.4 includes this extra 'self_contained: no' line. Cheers, Matt 

----- Original Message -----

**Comment by vobencha** [comment]
Did you commit and bump? Not sure why the SPB didn't produce a new report.
Val

**Comment by vobencha** [comment]
Files in the data/ directory need man pages. You can either cut and paste the file description from the vignette into a man page or move the file to inst/extdata/.
Val

**Comment by mritchie** [comment]
Thanks Val. Have moved this file to inst/extdata. Cheers, Matt 

----- Original Message -----

**Comment by vobencha** [comment]
@mritchie please bump the version to trigger a new build. Once that's clean I can approve.

**Comment by vobencha** [comment]
Looks like you did bump to 0.99.5 ... I'll ask Lori to kick off a new build.

**Comment by lshep** [comment]
It looks like the mailing system is still down so until that comes back on line this ERROR will occur

**Comment by vobencha** [comment]
Ah, ok. Thanks for looking into it.

**Comment by vobencha** [comment]
Matt, I'm marking the package as accepted. Going forward, Lori will be managing the workflows so you'll get an email from her (or possibly Martin) when your svn username has been added to the workflow repository. We'll set up a build on Jenkins (workflow manager) and send you the link where you can view build results.

Valerie
