### ISSUE TITLE
(inactive) basejump

### ISSUE THREAD

**Issue by mjsteinbaugh** [Bioconductor/Contributions#1238]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/acidgenomics/basejump

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

The basejump package is a toolkit for bioinformatics. It provides method support for genome annotations, metadata, quality control, and works primarily with `SummarizedExperiment` and `GenomicRanges`.

**Comment by mtmorgan** [comment]
Hi @mjsteinbaugh I'll oversee these group of packages. My preliminary feeling is that, to be most effective

- Some packages might be more suited to CRAN than Bioconductor
- Some functionality in other packages should be incorporated into Bioconductor core packages, especially BiocGenerics
- Some functionality should be implemented to follow achieve specific design goals
- Some functionality is great as-is and in standalone packages

Before launching into a more detailed assessment, I want to make sure you're on board with this general approach

**Comment by mjsteinbaugh** [comment]
@mtmorgan that makes sense to me. In particular, I think goalie and syntactic may be more appropriate on CRAN, but I wanted to check with you guys first to see how those should integrate with Bioconductor. Like @lawremi mentioned, some of the functionality in brio could potentially be moved into rtracklayer, and some of the functions in freerange could be incorporated into GenomicRanges, if that's an option. I tried to split out some of this code into separate packages over the last few years with this in mind.

**Comment by mjsteinbaugh** [comment]
@mtmorgan OK to submit [goalie](https://goalie.acidgenomics.com/] and [syntactic](https://syntactic.acidgenomics.com/) to CRAN? I stripped them down a bit and I'm thinking that makes more sense.

**Comment by mjsteinbaugh** [comment]
Any update on this? Should I start any submissions to CRAN?

**Comment by mtmorgan** [comment]
yes submit to cran and close issues associated with packages that are headed to CRAN. Again my apologies.

**Comment by mjsteinbaugh** [comment]
Will do, thanks @mtmorgan !

**Comment by mtmorgan** [comment]
@mjsteinbaugh sorry that this issue languished without activity for so long. Please open a new issue if there is still material here that you'd like in Bioconductor.
