### ISSUE TITLE
anamiR

### ISSUE THREAD

**Issue by AllenTiTaiWang** [Bioconductor/Contributions#124]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/AllenTiTaiWang/anamiR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
1. `differExp_discrete()` should accept a SummarizedExperiment
2. `differExp_discrete()` seems too limited; only supports one factor in the model, and the factor must be binary.
3. `differExp_discrete()` should use the `match.arg()` for its `method` parameter.
4. Similar stuff pertains to `differExp_continuous()`. Why is it munging the class variable?
5. `correlation()`: could this use `cor()` instead of `cor.test()` to be vectorized? The name of the function seems too generic. Like `differExp_discrete()`, it should should take SummarizedExperiment and use `match.arg()` on `method`.
6. `database_support()` and `enrichment()` talk to some SQL server at a numeric IP. Who maintains it and how long will it stay running? No way to use a hostname?

**Comment by AllenTiTaiWang** [comment]
Hi, @lawremi , thanks for checking my package.

For problem 1, 3, 5, 6, I am working on them.

For 2.  there is another function in package, which is named multi_Differ() , including anova analysis for multiple groups of factor. Also, I am fixing it about using the match.arg() for its post_hoc method parameter.

But for 4. "Why is it munging the class variable?", I don't really know what is that mean ...
Does that mean I should find another way to get the name of factor from my phenotype data?

**Comment by lawremi** [comment]
By munging, I just mean that you are doing some manipulation of the string, i.e., the `sur_time` stuff.

**Comment by AllenTiTaiWang** [comment]
@lawremi , thanks for explaining, I got it now.

The reason is I assume that when people record "Survival time", they may note like "disease free survival time (months): 126.611842105263", so I try to get the string after ":" and turn it to numeric.

**Comment by AllenTiTaiWang** [comment]
** checking loading without being on the library search path ... WARNING
Loading required package: methods
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'httr'
Error: package or namespace load failed for 'anamiR'
Execution halted

I don't know how to deal with this warning message.
My package doesn't  need to import 'httr' ...

**Comment by lshep** [comment]
for now please ignore this warning

**Comment by lawremi** [comment]
The package needs to be based on _SummarizedExperiment_ and should support differential expression detected by other methods, like voom/limma and DEseq.

**Comment by vobencha** [comment]
Hi,
Just a few last comments for you.

1) Please remove \dontrun or explain why you have them in there:
~/proj/git/software/anamiR/man >grep dont *
database_support.Rd:\dontrun{
enrichment.Rd:\dontrun{
miR_converter.Rd:\dontrun{

2) Rename the vignette file to animiR or IntroductionToanimiR. The name is posted on the package landing page and you'll want something more descriptive.

Remember to bump the version before you commit. The deadline to accept packages for the next release is  tomorrow (Oct 12) so hopefully you can't make these changes before then.

Let me know if you have questions.
Valerie

**Comment by AllenTiTaiWang** [comment]
Hi, @vobencha 
Thank you for review, 

1) 
for "dontrun" in function enrichment.Rd and database_support.Rd,

#' ## Species except "hsa" and "mmu"
#' sup <- database_support(cor_data = cor, org = "rno")
#'
#' ## Threshold of total hits greater than 8
#' sup <- database_support(cor_data = cor, , Sum.cutoff = 9)
#' }

#' \dontrun{
#' ## Species except "hsa" and "mmu"
#' pat <- enrichment(data_support = sup, org = "rno")
#' }

these are trying to tell users not to search other species than "hsa" and "mmu", and not to have Sum.cutoff higher than the maximum number of predicted databases.

as for in miR_converter, 

#' \dontrun{
#' ## Choose parameter of latest_version above 21
#' mirna_22 = miR_converter(
#'     data = mirna_d,
#'     original_version = 17,
#'     latest_version = 22
#' )

it is for warning the latest version in miRBase is 21.

If you think these are unnecessary, I can remove them.

2) I will rename it.

for what you said, 
"The deadline to accept packages for the next release is tomorrow (Oct 12) so hopefully you can't make these changes before then."

Did you really mean it, or you just mistyped it ?

**Comment by vobencha** [comment]
It was a typo! I meant "can make the changes", sorry about that.

I think warnings to not search on certain organisms or versions is important but I wouldn't demonstrate the wrong thing to do in \dontrun statements. As long as you have this explained in the \arguments and/or \details sections of the man page (and it looks like you do) that's sufficient.

Valerie

**Comment by vobencha** [comment]
Thanks for making the changes - I'm marking this as accepted. You should get an email in the next week with svn credentials and next steps.
Valerie

**Comment by AllenTiTaiWang** [comment]
@vobencha ,
Thank you very much !

**Comment by LiNk-NY** [comment]
Hi @AllenTiTaiWang, 
Please be aware that you package is marked for `Deprecation`. Please make the necessary changes for your package to pass build and check. Otherwise, you package will be removed from Bioconductor by the next release cycle.
Best regards,
Marcel
