### ISSUE TITLE
SPLINTER

### ISSUE THREAD

**Issue by dianalow** [Bioconductor/Contributions#125]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dianalow/SPLINTER

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
Wins the BED parser of the day award with `extractSpliceSites()`. Please try to use rtracklayer `import()` and its `extraCols` parameter. Is the `filetype` argument ignored? It should return GRanges objects.

**Comment by dianalow** [comment]
>Wins the BED parser of the day award with extractSpliceSites().

Cheers.

> Please try to use rtracklayer import() and its extraCols parameter. Is the filetype argument ignored? It should return GRanges objects.

From what I read and tried, the extraCols option is able to include fields after the initial BED/etc-like columns, and does not seem work here. Nevertheless, I've modified and simplified the function, used `makeGRangesFromDataFrame` and it now returns a `GRanges` object. Thank you for the suggestions.

> Also, it's a bit weird how paths in the author's home directory are used as the defaults for the primer3 stuff.

I included this function as a way to call primer3 from a local install. Yes I know it is now pointing to my directory, but I intend it for users to point it to theirs. I will admit that this does not look the nicest. Is there something more elegant?

**Comment by lawremi** [comment]
Sorry, I guess that format is not BED after all. Using `makeGRangesFromDataFrame()` is an elegant solution. For primer3, I guess you could just assume the binary is on the PATH.

**Comment by mtmorgan** [comment]
DESCRIPTION

- Use the Description: field to describe your approach, including how
  it differs from available alternatives; consider this like a paper
  abstract.

vignette

- looks good

R

- e.g., main_spliter.R:190 The '[copy-and-append][]' pattern is very
  inefficient; it looks like this is a simple vectorized calculation
  anyway and does not require a loop.
- e.g., main_spliter.R:308 is another example of
  copy-and-append. Again it looks as though this can be 'vectorized'
  by a single call to `findOverlaps(ovreg, roi$roi)` and processing
  the returned object.
- review ALL code for copy-and-append approaches, and refactor these
  to use efficient vectorized computations.
- e.g., main_spliter.R:321 `message()` does not usually require nested
  `paste()`.


man

- `extractSpliceEvents()` says that `data` can be a GRanges, object,
  but that does not seem to be the case. 
- e.g., `extractSpliceEvents()` the help page says that it returns a
  `dataframe` but that is not an R class. If the data are based on
  genomic coordinates, then this function should return a `GRanges`
  object.
- `plot_seqlogo()` says that its first argument is a 'character
  vector' but it seems like this could be a file path to a FASTA file
  or a DNAStringSet. There is no description about what the function
  does.
- Provide a reference (See also: section) to where this format (MATS)
  is defined.
- Please carefully review all documentation. Take the time and care to
  provide the user with a complete description of input and return
  values. as an example, `addEnsemblAnnotation` argument talks about
  `dataframe` and `df`, niether of which are R objects; the `data`
  argument has an extra mention of `dataframe`; the `species` argumnt
  should be specified with reference to biomaRt values; the nature of
  the annotations added to the MATS data.frame should be specified.

[copy-and-append]: http://bioconductor.org/developers/how-to/efficient-code/

**Comment by dianalow** [comment]
Dear Martin,

Thank you for the comments and suggestions.

1. Description: field is now more fleshed out, describes more detail about package.
2. Used `apply`,`lapply`,`ldply` where possible. Much neater now!
3. Removed extraneous `paste` from `message()` except those outputting vectors.
4. Fixed all man pages and Rd files are now better documented.

**Comment by dianalow** [comment]
@mtmorgan 
i think the `httr` missing package is a known issue after looking through a couple of other submissions. ok to ignore for now?

**Comment by mtmorgan** [comment]
yes ignore httr for now.
