### ISSUE TITLE
schex

### ISSUE THREAD

**Issue by SaskiaFreytag** [Bioconductor/Contributions#1253]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SaskiaFreytag/schex

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
You will receive a build report shortly.   Please set up your [webhook](https://github.com/Bioconductor/Contributions#adding-a-web-hook) so that future version bumps on the package will trigger an automatic rebuild.

**Comment by lshep** [comment]
Please be advised Bioconductor only allows packages dependencies that are on CRAN or Bioconductor.  SeuratData  does not appear to be on either.  This package will need to be submitted or not be used in your package.

**Comment by lshep** [comment]
Thank you for your submission.  I really enjoyed the plotting aspects of your package.  Please see some comments below: 

**Build reports**

- [ ] Fix notes for global variables/functions
- [ ] Fix coding practice notes

**DESCRIPTION**

- [ ] Packages used in your vignette I believe should be in the Suggest field of
  your DESCRIPTION (which will also clean up the build report note)
- [ ] We would recommend removing `lazyData: true`. We have rarely found it
  useful and have found it can slow installation. 


**README**

- [ ] Are both the .Rmd and .md really necessary?
- [ ] Please include Bioc installation instructions of the package too.

 
**NEWS**

- [ ] Please see group naming convention in `?news`. Headers should be formatted
  `changes in version x.y.z` and not include the package name. 

**vignettes**

- [x] Thank you for having complete and detailed vignettes.  I very much like
  showing the full workflow including data pre-processing. 

_using_schex_

- [ ] For this demo there is no need to download the Github repo SeuratData as
  this is demonstrating SingleCellExperiment
- [ ] Is there a random component somewhere?  When I run through the code when I
  get to `plot_hexbin_density` I get a slightly different plot? Similar but
  different 

_Seurat_schex_

- [x] No additional comments

_shiny_schhex_

- [ ] Is the double h in the name a typo? 
- [ ] If iSEE and shinydashboard are utilized in this vignette, please include as suggest in DESCRIPTION.
- [ ] I don't know if its a limitation in the shiny code or somewhere in your code
but when I run the app to get a shinyApp, if I close the window it doesn't close
the connection on the code terminal (I have to cntr-C to get back to a working R
terminal)
- [ ] It would be nice to show the iSEE plot with some interactive features. The
  plot that shows up seems to be pretty static with no options to switch
- [ ] Same issue where if you close the plot window the connection stays open (this may be out of your control but thought it worth mentioning)

**R / man**

_schex.R_

- [ ] Maybe the package help page could use a little more detail and/or link to
  how to get started using the package?

_utility_functions.R_

- [ ] should this be a scaler || or the vector option used?
- [ ] remove the excess paste0 in the stop function.  

_plot_hexbin_meta.R_

- [ ] The setMethod plot_hexbin_meta for SingleCellExperiment and Seurat object is
essentially the same code except for within the first four lines of code on how
to access the cID, out, and colnames of the two objects.  Please eliminate
duplicate code by have these tow setMethods extract that specific data and pass to
a function to do the rest of the analysis.  Code duplication should always be
avoid to make code easier to read and maintain. We would recommend applying this
to all methods defined for the two objects calling a common function when the
code starts to duplicate. 

_plot_hexbin_interact.R/plot_hexbin_gene.R/plot_hexbin_feature.R/plot_hexbin_density.R/make_hexbin_label.R_

- [ ] See above comment about duplicate code
- [ ] remove unneeded paste0 in stop function

**General comment**
- [ ] Is it worth having a save option for any of these plots or are you intending them to be strictly interactive/investigative?

Please address the above issues and comment back here with a summary of changes or comments to questions.  When ready for a re-review please also do a version bump to trigger a new build of the package.  Cheers!

**Comment by SaskiaFreytag** [comment]
Thank your for your kind review. I have tried to address your points as I will outline below.

**Build reports**

> Fix notes for global variables/functions

I have fixed global variables/functions.

>  Fix coding practice notes

I have fixed most coding practice notes.

**DESCRIPTION**

> Packages used in your vignette I believe should be in the Suggest field of
your DESCRIPTION (which will also clean up the build report note)

I have added all packages required in the vignette to the Suggest field.

> We would recommend removing lazyData: true. We have rarely found it
useful and have found it can slow installation.

Done.

**README**

>  Are both the .Rmd and .md really necessary?

Yes they are both necessary, as I modify the .Rmd file to obtain the .md file. This is the workflow suggested by the `usethis` package.

> Please include Bioc installation instructions of the package too.

Done.

**NEWS**

>  Please see group naming convention in ?news. Headers should be formatted
changes in version x.y.z and not include the package name.

Done

**vignettes**

_using_schex_

>  For this demo there is no need to download the Github repo SeuratData as
this is demonstrating SingleCellExperiment.

I have removed mention of this package. Thank you for pointing out this mistake.

>  Is there a random component somewhere? When I run through the code when I
get to plot_hexbin_density I get a slightly different plot? Similar but
different

Yes there is a random component in the UMAP plotting. I have used `set.seed` to fix this issue.

_shiny_schex_

>  Is the double h in the name a typo?

Yes I have fixed this. Thank you for pointing out this error.

>  If iSEE and shinydashboard are utilized in this vignette, please include as suggest in DESCRIPTION.

Done.

> I don't know if its a limitation in the shiny code or somewhere in your code
but when I run the app to get a shinyApp, if I close the window it doesn't close
the connection on the code terminal (I have to cntr-C to get back to a working R
terminal)

In my experience this is normal shiny behaviour.

> It would be nice to show the iSEE plot with some interactive features. The
plot that shows up seems to be pretty static with no options to switch

I have added explanations to the vignette to explain how the plot can be changed in an interactive manner. However, please note that the interactive feature for iSEE for schex plots is very basic. I have had extensive discussions with the maintainers around this [topic](https://github.com/csoneson/iSEE/issues/308), but for now there is no better way in facilitating interactivity through iSEE in this instance. I still believe that the inclusion of iSEE in the vignette is useful, as iSEE is a widely used tool and schex plots may want to be integrated by users for completion sake. 

**R/man**

_schex.R_

> Maybe the package help page could use a little more detail and/or link to
how to get started using the package?

I have added more detail.

_utility_functions.R_

> should this be a scaler || or the vector option used?

I am not sure what this comment refers to.

> remove the excess paste0 in the stop function.

Done and also taken care of in all other functions.

_further functions_

> The setMethod plot_hexbin_meta for SingleCellExperiment and Seurat object is
essentially the same code except for within the first four lines of code on how
to access the cID, out, and colnames of the two objects. Please eliminate
duplicate code by have these tow setMethods extract that specific data and pass to
a function to do the rest of the analysis. Code duplication should always be
avoid to make code easier to read and maintain. We would recommend applying this
to all methods defined for the two objects calling a common function when the
code starts to duplicate.

I have followed this advice for all functions to the best of my abilities.

**General comment**

>  Is it worth having a save option for any of these plots or are you intending them to be strictly interactive/investigative?


I have added explanations in the vignettes to the connection between schex and ggplot2. Within these explanations I show how the plot can be easily saved using standard ggplot2 grammar.

**Comment by lshep** [comment]
Thank you.  Looks really good and ready to accept.  Could you fix the last two NOTES from the build report

- [ ] coding
```
* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply()
      Found in files:
        utility_functions.R (line 22, column 20)
```

- [ ] just need a newline at the end of file in
`schex/tests/testthat/test-make_hexbin_label.R` and `schex/tests/testthat/test-make_hexbin.R`
```
Warning in readLines(infile) :
  incomplete final line found on '/var/folders/4v/hj3ybtnn2m1cgkmyz3dx0x8h0000gq/T//RtmphAYLU6/file476f885017b/schex/tests/testthat/test-make_hexbin_label.R'
Warning in readLines(infile) :
  incomplete final line found on '/var/folders/4v/hj3ybtnn2m1cgkmyz3dx0x8h0000gq/T//RtmphAYLU6/file476f885017b/schex/tests/testthat/test-make_hexbin.R'

```

Thanks for making all the other changes.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SaskiaFreytag.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("schex")`. The package 'landing page' will be created at

https://bioconductor.org/packages/schex

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
