### ISSUE TITLE
SIMLR (Single-cell Interpretation via Multi-kernel LeaRning)

### ISSUE THREAD

**Issue by danro9685** [Bioconductor/Contributions#127]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BatzoglouLabSU/SIMLR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Hi,

Please see comments and suggestions below.

(1) Problems during R CMD check:

* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer should subscribe to the bioc-devel mailing
      list. Subscribe here:
      https://stat.ethz.ch/mailman/listinfo/bioc-devel

* Checking man pages...
    * WARNING: Add non-empty \value sections to the following man
      pages:
      test.Rd

* Checking native routine registration...
    * WARNING: Register native routines! see
      http://cran.r-project.org/doc/manuals/R-exts.html#Registering-native-routines

(2) Do you need both LICENCE and LICENCE.md?

(3) Please rename the vignette to SIMLR.Rnw.

(4) SIMLR man page

Please add a description of the data type to all of the arguments. For example, what exactly to you expect 'X' to be, a DataFrame, data.frame, list, or matrix? The \description and \value sections don't explain what the function does or what it returns. Please add detail to these - mention the data type, dimensions, col and row names if any. See this man page for an example of a well documented function:

```
library(GenomicAlignments)
?stackStringsFromBam
```

(5) SIMLR() inputs

A goal of Bioconductor is to promote interoperability between packages and we encourage reuse when possible. There are several packages in Bioconductor that analyze single cell data and have developed classes specifically for that purpose. One example is the scran package that has the SCESet class.

https://www.bioconductor.org/help/workflows/simpleSingleCell/

Please look at a few of the other Bioconductor packages that deal with single cell data and support one of those classes as the  'X' argument to SIMLR().

(6) test data

- please rename the data to something more descriptive

Much of this information is in the vignette but should also be in the man page:

- add \details section that describes where the data came from, what they are, how the sample set was created etc.

- add \value section that describes the object; data.frame? matrix?; how many rows / columns and what are they named

Let me know if you have questions.

Valerie

**Comment by danro9685** [comment]
Dear @vobencha, 

here are some preliminary answers to your issues. 

Regarding the ERROR, we updated the maintainer email in the version 0.99.1 of the package to an email we used also for other packages that are currently on Bioconductor. In this way, we have one unique registered email and everything should work. 

Regarding the WARNINGS and other stuff, we are looking into each of them and will be back soon. 

Thanks, 
Daniele Ramazzotti

**Comment by danro9685** [comment]
Dear @vobencha,

I just pushed the latest update of the packages which accounts for most of your suggestions. 

Thanks, 
Daniele Ramazzotti

**Comment by luca-dex** [comment]
Dear @vobencha the error is on:

```
* Checking for bioc-devel mailing list subscription...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer
Calls: <Anonymous> ... request_fetch -> request_fetch.write_memory -> <Anonymous> -> .Call
Execution halted
```
Could you please restart the build?

**Comment by lshep** [comment]
I just put it back on. There should be a new report in a few minutes.

**Comment by vobencha** [comment]
@danro9685, please specify which of my comments you did and did not address as referred to in this comment https://github.com/Bioconductor/Contributions/issues/127#issuecomment-250330746

**Comment by danro9685** [comment]
Dear @vobencha, 

we did not address comment (5), specifically : 

(5) SIMLR() inputs

A goal of Bioconductor is to promote interoperability between packages and we encourage reuse when possible. There are several packages in Bioconductor that analyze single cell data and have developed classes specifically for that purpose. One example is the scran package that has the SCESet class.

https://www.bioconductor.org/help/workflows/simpleSingleCell/

Please look at a few of the other Bioconductor packages that deal with single cell data and support one of those classes as the 'X' argument to SIMLR().

**Comment by vobencha** [comment]
Interoperability is important. Packages added to the Bioconductor repo dealing with the same type of data or analysis should play well together. Another back-end option, fairly new, is the HDF5Array package. This was designed with large data from single cell experiments in mind. In addition to a matrix, please support one of these options (HDF5Array-class, DelayedArray-class or SCESet etc ...) as the 'X' argument.

Valerie

**Comment by danro9685** [comment]
Dear @vobencha, 

as you asked, we supported SCESet class in the last commit. 

Best, 
Daniele

**Comment by vobencha** [comment]
Super. Thanks for making the changes. I'm marking the package as approved and you should get an email from Martin within the next week with svn instructions and next steps.
Valerie

**Comment by danro9685** [comment]
Great! Thanks!
