### ISSUE TITLE
regsplice

### ISSUE THREAD

**Issue by lmweber** [Bioconductor/Contributions#128]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lmweber/regsplice

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
It would be nice if the top-level `regsplice()` accepted a SummarizedExperiment as input, presumably from an upstream call to `summarizeOverlaps()`. I like how regsplice already has a SummarizedExperiment-based class for its internal workflow. Doing the same for the primary entry point would enable interoperability with other pakages.

**Comment by lmweber** [comment]
Thanks for this suggestion @lawremi , yes this is a good idea. I'll get onto it.

**Comment by lmweber** [comment]
Hi @LiNk-NY @lawremi , can we still expect review comments before the Wednesday deadline? I will be on a plane on Tues/Wed so may be unable to respond in time if we get comments at the last minute. It will be disappointing to miss out on this Bioconductor release if we don't have time to respond. I do appreciate the time you are taking to review our package and hope to hear back soon. Best regards, Lukas

**Comment by LiNk-NY** [comment]
Hi @lmweber, 
Sorry for the delay. I'm reviewing your package now. 
Thank you for your patience. 
Marcel

**Comment by LiNk-NY** [comment]
Hi @lmweber, 
Thank you for submitting your package to Bioconductor!
Please see the package review below: 

----
#### Overall 
The documentation of your package looks descriptive and organized. You make use of the `SummarizedExperiment` class and add some changes with your class.  

#### User interface
* No need to provide a message when subsetting (i.e., "subsetting rows by *") . The user is expected to understand what is taking place when subsetting your object. 
* Subsetting by columns? Something like `Y[, 1:2]` doesn't seem to work. You would want to keep the method consistency if your object class is based on a `SummarizedExperiment`. 
* Use of `@` is discouraged. We would prefer that you use accessor functions to avoid the use of `@` symbol (particularly for the `RegspliceResults` object). 
* Your internal functions should start with a period. 
* You could also support `DataFrame` class objects as input for `counts`. 
* Shouldn't `regsplice` use `RegspliceData` as input? Some of the arguments are the same in both and you create that object at the start of the function anyway.
 
#### Grammar
* We try to avoid using the use of underscores in function names. Please use **camelCase** instead. 
* You might want to add a check for condition length to equal sample count in the constructor function. 
* Avoid using `1:number` or `1:length(vector)` try `seq_len(number)` or `seq_along(vector)`
* Please change your `data` argument name to something like `RegspliceData` so that the user knows what is expected (data is also a function in utils). 
* Minor point: I don't think you need multiple `@importFrom` directives as they will resolve to one call in the `NAMESPACE`. 

On the note you have for one of your functions, have you tried contacting the maintainer of `glmnet` for a bug fix? 

Thank you for submitting to Bioconductor. We hope to see the appropriate changes and accepted to Bioconductor. 

Regards,
Marcel

**Comment by lmweber** [comment]
Hi Marcel,

Thank you for your review. These are all helpful comments.

I have added these changes in the updated version just submitted. More details on each point are below.

---

**User interface**

- No need to provide a message when subsetting (i.e., "subsetting rows by *") . The user is expected to understand what is taking place when subsetting your object.

Done. I have removed these messages.

- Subsetting by columns? Something like `Y[, 1:2]` doesn't seem to work. You would want to keep the method consistency if your object class is based on a `SummarizedExperiment`.

This was a bug, which occurred when the argument "i" was missing in a subsetting call. This is now fixed, so subsetting should be consistent with `SummarizedExperiment`.

- Use of `@` is discouraged. We would prefer that you use accessor functions to avoid the use of `@` symbol (particularly for the `RegspliceResults` object).

Done. I have added accessor functions for all the main parts of the `RegspliceResults` objects. The examples in the vignette now all use accessor functions instead of `@`.

- Your internal functions should start with a period.

Done.

- You could also support `DataFrame` class objects as input for counts.

Done.

- Shouldn't `regsplice` use `RegspliceData` as input? Some of the arguments are the same in both and you create that object at the start of the function anyway.

I have re-structured the workflow so that the `RegspliceData` constructor is now always called explicitly. In a typical workflow, the user will now first create a data object using the `RegspliceData()` constructor, and then run the analysis pipeline with the `regsplice()` wrapper function. This is a cleaner separation than I had before. In addition, I have modified the constructor to also accept `SummarizedExperiment` input objects, as per @lawremi 's suggestion.

**Grammar**

- We try to avoid using the use of underscores in function names. Please use **camelCase** instead.

Done. Function names now use camelCase.

- You might want to add a check for condition length to equal sample count in the constructor function.

Done.

- Avoid using `1:number` or `1:length(vector)` try `seq_len(number)` or `seq_along(vector)`

Done.

- Please change your `data` argument name to something like `RegspliceData` so that the user knows what is expected (`data` is also a function in `utils`).

Done. I have changed the data arguments to "rs_data", and the results arguments to "rs_results". This is now consistent throughout the package.

- Minor point: I don't think you need multiple `@importFrom` directives as they will resolve to one call in the `NAMESPACE`.

I started removing some of these `@importFrom` directives, but decided to leave them in for now. I think it helps readability to have all the imports above each function block, and they don't seem to cause any problems. However I'll think about whether there is a good place to collect some of them.

- On the note you have for one of your functions, have you tried contacting the maintainer of `glmnet` for a bug fix?

Yes, we contacted the package maintainer and submitted a bug report. They have added this to their list of updates, and it will be included in a future version. However the version currently on CRAN still has this issue, so I have included the note for now.

---

Thanks again and best regards,
Lukas

**Comment by lmweber** [comment]
Hi @LiNk-NY @lawremi , sorry to keep sending messages. I noticed the release schedule mentions "No new packages added to BioC release roster" from today (Wed 12 Oct). Will we still be considered for inclusion in this release, or is it now too late? Best regards, Lukas

**Comment by LiNk-NY** [comment]
Hi @lmweber, 
It looks like you still have generic and method names with under_score characters.

Regards,
Marcel

**Comment by lmweber** [comment]
Thanks the for the reply. I think these are the accessors for the RegspliceResults objects, i.e. `gene_IDs()`, `p_vals()`, `p_adj()`, `LR_stats()`, and `p_adj()`. I left these since I thought it would be better to keep them consistent with the slot names that they are accessing (the slot names use underscores). However I'll update them now to camelCase now if this is a strict requirement.

**Comment by lmweber** [comment]
Thanks the for the reply. I think these are the accessors for the RegspliceResults objects, i.e. `gene_IDs()`, `p_vals()`, `p_adj()`, `LR_stats()`, and `p_adj()`. I left these since I thought it would be better to keep them consistent with the slot names that they are accessing (the slot names use underscores). However I'll update them now to camelCase now if this is a strict requirement.

**Comment by lmweber** [comment]
Thank you for accepting the package, glad we made it! Thanks again for your time @LiNk-NY .
