### ISSUE TITLE
tartare - biocViews: ExperimentData, MassSpectrometryData

### ISSUE THREAD

**Issue by cpanse** [Bioconductor/Contributions#1286]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cpanse/tartare/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput mass spec data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by cpanse** [comment]
@lshep, I continue once all [metadata](https://github.com/cpanse/tartare/blob/master/inst/extdata/metadata.csv) are available through `ExperimentHub()`. Am I on the right track?

```
R> library(ExperimentHub)
R> eh <- ExperimentHub(); 
snapshotDate(): 2019-09-25
R> query(eh, "tartare")
ExperimentHub with 0 records
# snapshotDate(): 2019-09-25 
R> 
```

**Comment by lshep** [comment]
Yes I will be working on uploading the data later today.  sorry for the dealy

**Comment by lshep** [comment]
Hey a few issues before the data can be added -  could you please make the following changes
**metadata.csv**
- [ ] Please have some distinguishing title rather than 2 of the same
- [ ] Update BiocVersion to 3.10 
- [ ] Please remove empty tags column 

**package description:**
- [ ] Please add ExperimentHub to the biocViews

**Comment by cpanse** [comment]
https://github.com/Bioconductor/Contributions/issues/1286#issuecomment-543235759

@lshep done by commit [7744cae](https://github.com/cpanse/tartare/commit/7744cae640e8f3ad64b2a270d3008a328e51d3fa).

**Comment by lshep** [comment]
When I run the following I get an ERROR (this function is used to add the data to the database) 

```
> meta = makeExperimentHubMetadata("tartare/")
missing or NA values for 'Coordinate_1_based set to TRUE'
Loading valid species information.
Error in .checkThatSourceTypeSoundsReasonable(object@SourceType) : 
  'SourceType' should be one of: BAI, BAM, BED, BigWig, BioPax, BioPaxLevel2, BioPaxLevel3, CEL, Chain, CSV, ensembl, FASTA, FASTQ, FCS, GFF, GRASP, GTF, HDF5, IDAT, Inparanoid, JSON, MTX, MySQL, mzid, mzML, mzTab, mzXML, NCBI/blast2GO, NCBI/ensembl, NCBI/UniProt, RDA, RData, Simulated, tab, tar.gz, TSV, TwoBit, TXT, UCSC track, VCF, XLS/XLSX, Zip.
 Found type: raw
```
Is there a different sourcetype in the list that would be appropriate rather than `raw`?

**Comment by cpanse** [comment]
This is a proprietary file format (consider it as a binary large object (BLOB)). We are going to read the file format by using the [MsBackendRawfileReader](https://github.com/cpanse/MsBackendRawFileReader) and the [Spectra](https://github.com/rformassspectrometry/Spectra) packages in the near future.

**Comment by lshep** [comment]
Ok. I will add BLOB as an acceptable SourceType - could you update your metadata to reflect that please?

**Comment by lshep** [comment]
I updated on my end to be BLOB for the raw files and added the data to the hubs.  It is now accessible using Bioc devel 3.10.    Please update any necessary code and comment back here when you are ready for a review. 
```
eh = ExperimentHub()
  |======================================================================| 100%

snapshotDate(): 2019-10-18
> query(eh, "tartare")
ExperimentHub with 4 records
# snapshotDate(): 2019-10-18 
# $dataprovider: Functional Genomics Center Zurich (FGCZ)
# $species: NA
# $rdataclass: Spectra
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH3219"]]' 

           title                
  EH3219 | Q Exactive HF-X mzXML
  EH3220 | Q Exactive HF-X raw  
  EH3221 | Fusion Lumos mzXML   
  EH3222 | Fusion Lumos raw     
> path = query(eh, "tartare")[[1]]
downloading 1 resources
retrieving 1 resource
  |======================================================================| 100%
> path
                                      EH3219 : 3235 
"/home/lori/.cache/ExperimentHub/5f314cca58e3_3235" 
```

**Comment by cpanse** [comment]
@lshep  so I replace 'raw' by 'BLOB'?
C

**Comment by lshep** [comment]
Yes please.   Then update your code to use the ExperimentHub.  When you are ready for a review just tag me again and I'll have a look at the underlying code of the package.  Cheers

**Comment by cpanse** [comment]
@lshep For whatsoever reason, the file 203c51cb0c6f_3237 seems to be corrupt on the AWS. Maybe my upload got interrupted.

```
cp@fgcz-113:~/__checkouts/R/tartare  (master)> md5 /Users/cp/Library/Caches/ExperimentHub/203c51cb0c6f_3237
MD5 (/Users/cp/Library/Caches/ExperimentHub/203c51cb0c6f_3237) = a4bf6ecb8adcd28ea07a034483aa1d5e
```
also `tail -n 1 /Users/cp/Library/Caches/ExperimentHub/203c51cb0c6f_3237` looks like a incomplete mzXML file. Sorry for the trouble. C

**Comment by lshep** [comment]
I'm not sure how big the files are suppose to be.  The file sizes we currently have 
```
> getInfoOnIds(eh, paste0("EH", c(3219:3222)))
      ah_id fetch_id                 title rdataclass status biocversion
3089 EH3219     3235 Q Exactive HF-X mzXML    Spectra Public        3.10
3090 EH3220     3236   Q Exactive HF-X raw    Spectra Public        3.10
3091 EH3221     3237    Fusion Lumos mzXML    Spectra Public        3.10
3092 EH3222     3238      Fusion Lumos raw    Spectra Public        3.10
     rdatadateadded rdatadateremoved file_size
3089     2019-10-18             <NA>  21295960
3090     2019-10-18             <NA>  34093249
3091     2019-10-18             <NA>  46487407
3092     2019-10-18             <NA> 122609648
```
If you think it was your session that didn't download correctly you can do a `ah("EH3221", force=TRUE) `  which will force redownload the file  or you can reupload the file to S3 and I will replace it if the file seems to be corrupt there. I believe the credentials I sent you still should be active.

**Comment by cpanse** [comment]
@lshep there must be a 2nd session (after that weekend) where I uploaded one mzXML again.
C

**Comment by lshep** [comment]
I don't have any other data in the S3 folder for tartare.  Could you upload again?

**Comment by cpanse** [comment]
@lshep done
```
cp@fgcz-148:~/tartare > aws --profile AnnotationContributor s3 cp 20190716_004_PierceHeLa.mzXML s3://annotation-contributor/tatare/20190716_004_PierceHeLa.mzXML --acl public-read
upload: ./20190716_004_PierceHeLa.mzXML to s3://annotation-contributor/tatare/20190716_004_PierceHeLa.mzXML
cp@fgcz-148:~/tartare > md5sum 20190716_004_PierceHeLa.mzXML 
6f7485fc3b5864bac51a215200a52101  20190716_004_PierceHeLa.mzXML
```

thanks C

**Comment by lshep** [comment]
I updated the file on S3 -  Please try to access again -  The hub should recognize that its a new version of the file and download automatically.  let me know if it doesn't

**Comment by cpanse** [comment]
> Hopefully that fixed that issue - In an effort to try and get this package into this release please see the other comments concerning your package. Hopefully they can be fixed so this package can be added and released with Bioc 3.9

yes it fixed the md5 issue. thanks!

> 
> **README**
> 
>     * [x]  (optional) include Bioconductor installation instructions.
> 
DONE
> 
> **vignette**
> 
>     * [ ]  Perhaps most of this seems like data preparation and should be in the
>       `inst/scripts` desribing how the data was made. Please move this file to
>       `inst/scripts`

most of the things are instrument configurations

>     * [ ]  I recommend still having an official vignette `tartare.Rmd` It is much
>       more intuitive for a user to do `vignette("tartare")` that shows the
>       ExperimentHub commands to download and access data

fully agree the instrument setups are the most important part.


> 
> **R / man**
> 
>     * [x ]  I think you should be very explicit that running the getFilename will
>       download the files associate with the package. So the users are aware there will
>       be a download.


done

>     * [x ]  Please create a different R file to contain package code `zzz.R` file is
>       generally only associated with code for `onLoad/onAttach`.
> 
right; done 

> **general**
> 
> As it could affect vignette and R/man
> 
>     * [ ]  Would there be a usecase to show the file names associated with this
>       without downloading?

the package is meant to be used together with the Spectra and MsBackendRawfilereader.
I added a picture in the README @jorainer presented today on the #SWEMSA conference.

> 
> **exec**
> 
>     * [x]  Please remove and then `.gitignore` this directory. Important for you but
>       not for anyone else.
DONE
> 
> Cheers


Iam going to fix the warnings later today.

best wishes,C

**Comment by lshep** [comment]
Hang tight - we are experiencing some delay with the builder. We are in the process of fixing it.

**Comment by cpanse** [comment]
> Awesome. I'll wait for the final corrections of the warnings but I don't see anything else preventing acceptance.

DONE. no more warnings. thanks.
C

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cpanse.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tartare")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tartare

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
