### ISSUE TITLE
iCAT

### ISSUE THREAD

**Issue by rajeha** [Bioconductor/Contributions#1288]
- Repository: https://github.com/BioHPC/iCAT

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Seems like the ImmunoOncology biocViews term is appropriate...

**Comment by LiNk-NY** [comment]
Hi Ahmad, @rajeha 

Please check the `extdata` folder and make sure that it is not too big. 
Our maximum size requirements are 5 MB tarballs. 

```
* checking installed package size ... NOTE
  installed size is  8.0Mb
  sub-directories of 1Mb or more:
    extdata   5.8Mb
```

I also see this note when running check on the package:

```
* checking R code for possible problems ... NOTE
classMat: no visible global function definition for ‘sd’
classMat: no visible global function definition for ‘dnorm’
plotHist: no visible binding for global variable ‘value’
plotHist: no visible binding for global variable ‘L1’
pred : <anonymous>: no visible binding for global variable ‘freq’
pred: no visible global function definition for ‘sd’
pred: no visible global function definition for ‘dnorm’
train : <anonymous>: no visible global function definition for
  ‘fisher.test’
train : <anonymous>: no visible binding for global variable ‘freq’
Undefined global functions or variables:
  L1 dnorm fisher.test freq sd value
Consider adding
  importFrom("stats", "dnorm", "fisher.test", "sd")
to your NAMESPACE file.
```
Please follow up on these NOTES and the ones from 
`R CMD BiocCheck iCAT_*`. Post your response here
and I will proceed with the package review. Thank you. 

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Ahmad, @rajeha 
Please respond to the comments here. Otherwise, I'd be forced to close the issue
due to inactivity. Thank you.
Best,
Marcel

**Comment by rajeha** [comment]
Hi Marcel, 

Thank you for your time. I have addressed your comments from above.

Thanks,
Ahmad

**Comment by LiNk-NY** [comment]
Hi Ahmad, @rajeha 

Thank you for making further changes. As mentioned in my
previous message, please address some of the `NOTES`
in the `BiocCheck` results. 

```
* Checking for recommended biocViews...
    * NOTE: Consider adding these automatically suggested biocViews:
      Classification
* Checking vignette directory...
    This is a software package
    * NOTE: Potential intermediate files found:
        vignettes/icat.html
* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply()
      Found in files:
        train.R (line 152, column 16)
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        pred.R (line 29, column 15)
        pred.R (line 43, column 13)
        processFiles.R (line 19, column 16)
        processFiles.R (line 22, column 25)
        readTrn.R (line 26, column 13)
        train.R (line 55, column 47)
        train.R (line 111, column 15)
        train.R (line 127, column 15)
        train.R (line 143, column 13)
        train.R (line 157, column 13)
* Checking package NEWS...
    * NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.
* Checking unit tests...
    * NOTE: Consider adding unit tests. We strongly encourage them. See
      http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
```

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Ahmed, @rajeha 

I had a brief look at your package and currently it does not look
like a candidate for Bioconductor.

The main reason for this is that your package does not make use
of the existing Bioconductor infrastructure (packages and classes)
in order to contribute significantly to Bioconductor. 

If you intend to make use of the Bioconductor ecosystem, please
relay that in the issue comments. Otherwise, I'd be inclined to
close the issue. 

Thank you. 

Best regards,
Marcel
