### ISSUE TITLE
SimFFPE

### ISSUE THREAD

**Issue by LanyingWei** [Bioconductor/Contributions#1321]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LanyingWei/SimFFPE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LanyingWei** [comment]
Dear reviewer,

There are errors in compiling vignette on Windows and OS system for my package, I tried my best to solve them but nothing works...therefore I wonder if you have any suggestions for that?

The error on Windows says "Failed to locate 'texi2pdf' output file", it occurs from time to time. As you can see in all those build reports, yesterday for most of the time it was not there, but for all the　attempts today, it appeared, yet I can't find the reason behind it. There is a discussion about this error, however a clear solution is not given: [https://r.789695.n4.nabble.com/quot-Failed-to-locate-the-texi2pdf-output-file-quot-td4664111.html](url).

The error on OS contains messages like "! LaTeX Error: Missing \begin{document}", I googled and tried several ways to solve it but it is always there, I have checked the encoding, it is already UTF-8 without BOM, and I have tried a very simple .Rnw file including only the title page, but still it failed. 

It would be great if you have any former experience with these types of error and are willing to share with me how to solve them, thank you in advance!

Lanying

**Comment by lshep** [comment]
I will investigate these errors and let you know if anything needs to be done on your end or if it is a system wide problem. Thank you for alerting us to this.

**Comment by lshep** [comment]
Thank you for your submission to biooconductor.  Please see the following comments. 

- [ ] See other package's review conversation/comments on data.tables and data.frames vs matrix. Not sure if its relevant but noticing the class structure of the  PhredScoreProfiles it might be (but maybe not as well)? 
https://github.com/Bioconductor/Contributions/issues/1200#issuecomment-535776038

- [ ] targetRegions should also be able to be a GenomicRange object which is how Bioconductor defines chromosome region. 

minor: 
- [ ] Avoid calling message multiple sequentially/should be able to concat into a single message call? and you shouldn't need the paste or paste0 in message

**Comment by LanyingWei** [comment]
@lshep Thanks for your comments! I have modified the package based on your suggestions:

* [x]  See other package's review conversation/comments on data.tables and data.frames vs matrix. Not sure if its relevant but noticing the class structure of the  PhredScoreProfiles it might be (but maybe not as well)?
PhredScoreProfile is a matrix now.

* [x]  targetRegions should also be able to be a GenomicRange object which is how Bioconductor defines chromosome region.
GenomicRanges object supported.

* [x]  Avoid calling message multiple sequentially/should be able to concat into a single message call? and you shouldn't need the paste or paste0 in message
Sequential message calls merged, paste/paste0 removed.

Is there anything else that needs to be changed?

Happy new year!
Lanying

**Comment by LanyingWei** [comment]
Hi @lshep ! Sorry to bother, but may I ask about the progress of my package review?

**Comment by lshep** [comment]
Yes very sorry.   We try to review within two weeks and I am obviously behind.  I will get a review to you today at latest tomorrow morning.

**Comment by LanyingWei** [comment]
@lshep  No worries~ And thank you for your reply :)

**Comment by lshep** [comment]
Again sorry for the delay.  Looks in great shape.  Minor comments/questions: 

**Vignette inspired question:**

- [ ] readSimFFPE doesn't produce any output which seemed rather unintuitive to me. Perhaps it should give the path to the  outFile[s] that was written? 
- [ ] What is different about the two files that get created?  It seems each produces two files as in my temp directory:
```
sim1_1.fq
sim1_2.fq
sim2_1.fq
sim2_2.fq
sim3_1.fq
sim3_2.fq
```
- [ ] Or maybe show how to read the files back in for further analysis in the vignette? I think the ShortRead package has functionality. I suppose I just imagine the what can I do next after utilizing your package or how do I view or analyze the resulting FASTQ files.
```
temp = readFastq(tempdir(), pattern="sim1_1.fq")
id(temp)
sread(temp)
```

**R code**
Looks in great shape.  One thing I noticed in a few of the exported functions but using targetReadSimFFPE as example:
- [ ]  targetReadSimFFPE it seems like there are some arguments that do not have a default value and are not checked for valid input?  This might be helpful.
ie.  `stopifnot` these defined or set a default if `missing()`: 
`reference, PhredScoreProfile, targetRegions, outFile, coverage, readLen, meanInsertLen, sdInsertLen,`
This concept is good practice for any exported function.

The vignette is more suggestion and clarification on my part, totally optional.  The R code argument check is recommended. 
Cheers

**Comment by LanyingWei** [comment]
@lshep Thank you for your feedback! Two output files will be there if pairedEnd is set to TRUE, then the mate pairs will be generated and stored in two separate files. For the first and the third question: the output FASTQ files can be very large if the user run high-coverage simulation on the whole genome (could be larger than 100GB), therefore I think showing examples of loading it back in R might not be a good idea, since the user may not pay attention to the output file size but just follow the examples~ Apart from that, the potential users of this package are those who wants to develop / evaluate their tools / pipelines for FFPE samples,  typically they will not directly deal with large FASTQ files in R. Therefore, I didn't change the vignette. The R code argument check is added. Instead of setting defaults when they are missing, it will just stop and return the error message, because these values are expected from the user's side. Do you think these changes are sufficient?

**Comment by lshep** [comment]
Yes.  Thank you for your efforts and contribution to Bioconductor.

**Comment by LanyingWei** [comment]
Great! :) Thank you too!!

**Comment by lshep** [comment]
The windows ERROR we are seeing in a few other packages as well so I'm looking into this and going to assume its on our end.  Cheers.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LanyingWei.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SimFFPE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SimFFPE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
