### ISSUE TITLE
EnMCB

### ISSUE THREAD

**Issue by whirlsyu** [Bioconductor/Contributions#1327]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/whirlsyu/EnMCB

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
This package does not contain a vignette, which is a required component of Bioconductor packages. It interoperates with Biobase `ExpressionSet`, whereas a more modern container is `SummarizedExperiment` (see [1][])

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by whirlsyu** [comment]
Thank you for review, We will fix that shortly.

**Comment by mtmorgan** [comment]
please note that this is not a review, but checking that your package conforms to Bioconductor specifications prior to the review process.

**Comment by whirlsyu** [comment]
Okay, thanks...

**Comment by whirlsyu** [comment]
> This package does not contain a vignette, which is a required component of Bioconductor packages. It interoperates with Biobase `ExpressionSet`, whereas a more modern container is `SummarizedExperiment` (see [1](https://bioconductor.org/developers/how-to/commonMethodsAndClasses/))

We have updated our vignette and change "ExpressionSet" to "SummarizedExperiment".

**Comment by mtmorgan** [comment]
I'm sorry, the vignette needs to have 'real' code chunks that are computed when the document is processed, rather than `<pre>` code chunks that provide only a 'picture' of the code. See vignettes in other Bioconductor packages for examples, e.g., in the BiocStyle package.

**Comment by whirlsyu** [comment]
> I'm sorry, the vignette needs to have 'real' code chunks that are computed when the document is processed, rather than `<pre>` code chunks that provide only a 'picture' of the code. See vignettes in other Bioconductor packages for examples, e.g., in the BiocStyle package.

Thanks. File "vignette.rmd" has been updated and checked.

**Comment by Kayla-Morrell** [comment]
@whirlsyu - Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] REQUIRED: 'LazyData' should be set to 'FALSE'. When this field is 'TRUE' 
it can slow down the loading of the package, especially those with data.

- [ ] SUGGESTION: Consider adding the automatically suggested biocViews term 
'SupportVectorMachine'.

- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' field with a 
relevant link to Github Issues.

## NAMESPACE

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an 
entire package (as you do with all of the imports). However, if there are many 
functions from a single package then `import()` is okay. Think about limiting 
the number of `import()` used and resort to `importFrom()` if possible, this 
will help speed up the loading of the package.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in the _Bioconductor_ release announcements. See the following link 
for formatting help if you choose to include the NEWS file, 
https://bioconductor.org/developers/package-guidelines/#news.

## Data

- [ ] REQUIRED: The only dataset that was actually used in this package was 
`demo_survival_data`. If the other datasets aren't used (or demonstrated) then 
they shouldn't be included.

## Vignettes

- [ ] REQUIRED: The vignette should be a stand-alone document, so there should 
be an author and last modified date of the vignette included below the title.

- [ ] REQUIRED: There should be a section title 'Introduction' before the text 
starting at line 11.

- [ ] REQUIRED: There should be a section title 'Installation' before the text 
starting at line 17.

- [ ] REQUIRED: There should be a chunk of code before the code at line 25, that 
demonstrates to the user how to download the package from _Bioconductor_. The 
code should look something like the following and should include `eval = FALSE`:

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("EnMCB")
```

- [ ] SUGGESTION: As section titles get added, we highly suggest a table of 
contents.

- [ ] SUGGESTION: At line 23 you might add some information about what this 
function `IdentifyMCB` will actually do.

- [ ] SUGGESTION: Before line 107, I would add `head(em_prediction_results)` and 
then explain a bit what the results actually mean.

- [ ] REQUIRED: Before the `sessionInfo()` code chunk there should be a section 
title 'Session Info'.

- [ ] REQUIRED: Line 114, there should be a space between '##' and 'References'. 
This will create the proper section title.

## Man pages

*IdentifyMCB*

- [ ] REQUIRED: All exported functions need runnable examples. The example code 
in this man page should be commented out.

*demo_MCBinformation*

- [ ] REQUIRED: All variables should be documented under 'Format:', not just 
the first 2.

- [ ] REQUIRED: There needs to be source information for where this data came 
from. This can be a reference, a URL, or additional information in 'Description' 
about how it was created.

*demo_data*

- [ ] REQUIRED: Under 'Format:' if there are other parts of the data they should 
be described and not use '...'.

- [ ] REQUIRED: There needs to be source information provided for this data.

*demo_survival_data*

- [ ] REQUIRED: The format of the data needs to be described.

- [ ] REQUIRED: There needs to be source information provided for this data.


## Unit tests

- [ ] REQUIRED: It is good practice to include unit tests and we highly 
recommend them. However, these tests should be testing functionality from your 
package not just simple mathematics. Please see our documentation for the proper 
use of unit tests,
https://bioconductor.org/developers/package-guidelines/#unittest.

## R code

- [ ] REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` instead. Found 
in the follow files:
        - IdentifyMCB.R - lines 62, 77, and 110
        - metricMCB.R - lines 95, 160, and 222
        - univ_coxph.R - line 21
        - utils.R - lines 51, 92, and 198

- [ ] SUGGESTION: For easier reading (and debugging) of your code, consider 
shorter lines. There are 221 lines that are > 80 characters long.

- [ ] SUGGESTION: For easier reading (and debugging) of your code, consider 
multiples of 4 spaces for line indents. There are 511 lines that are not.

Best,
Kayla

**Comment by whirlsyu** [comment]
> @whirlsyu - Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.
> 
> ## DESCRIPTION
> * [X]  REQUIRED: 'LazyData' should be set to 'FALSE'. When this field is 'TRUE'
>   it can slow down the loading of the package, especially those with data.
> * [X]  SUGGESTION: Consider adding the automatically suggested biocViews term
>   'SupportVectorMachine'.
> * [X]  SUGGESTION: It is encouraged to include the 'BugReports:' field with a
>   relevant link to Github Issues.
> 
> ## NAMESPACE
> * [X]  SUGGESTION: Generally `importFrom()` is encouraged over importing an
>   entire package (as you do with all of the imports). However, if there are many
>   functions from a single package then `import()` is okay. Think about limiting
>   the number of `import()` used and resort to `importFrom()` if possible, this
>   will help speed up the loading of the package.
> 
> ## NEWS
> * [X]  SUGGESTION: Consider adding a NEWS file, so your package news will be
>   included in the _Bioconductor_ release announcements. See the following link
>   for formatting help if you choose to include the NEWS file,
>   https://bioconductor.org/developers/package-guidelines/#news.
> 
> ## Data
> * [X]  REQUIRED: The only dataset that was actually used in this package was
>   `demo_survival_data`. If the other datasets aren't used (or demonstrated) then
>   they shouldn't be included.
> 
> ## Vignettes
> * [X]  REQUIRED: The vignette should be a stand-alone document, so there should
>   be an author and last modified date of the vignette included below the title.
> * [X]  REQUIRED: There should be a section title 'Introduction' before the text
>   starting at line 11.
> * [X]  REQUIRED: There should be a section title 'Installation' before the text
>   starting at line 17.
> * [X]  REQUIRED: There should be a chunk of code before the code at line 25, that
>   demonstrates to the user how to download the package from _Bioconductor_. The
>   code should look something like the following and should include `eval = FALSE`:
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("EnMCB")
> ```
> 
> * [X]  SUGGESTION: As section titles get added, we highly suggest a table of
>   contents.
> * [X]  SUGGESTION: At line 23 you might add some information about what this
>   function `IdentifyMCB` will actually do.
> * [ ]  SUGGESTION: Before line 107, I would add `head(em_prediction_results)` and
>   then explain a bit what the results actually mean.
> * [X]  REQUIRED: Before the `sessionInfo()` code chunk there should be a section
>   title 'Session Info'.X
> * [X]  REQUIRED: Line 114, there should be a space between '##' and 'References'.
>   This will create the proper section title.
> 
> ## Man pages
> _IdentifyMCB_
> 
> * [X]  REQUIRED: All exported functions need runnable examples. The example code
>   in this man page should be commented out.
> 
> _demo_MCBinformation_
> 
> * [X]  REQUIRED: All variables should be documented under 'Format:', not just
>   the first 2.
> * [X]  REQUIRED: There needs to be source information for where this data came
>   from. This can be a reference, a URL, or additional information in 'Description'
>   about how it was created.
> 
> _demo_data_
> 
> * [X]  REQUIRED: Under 'Format:' if there are other parts of the data they should
>   be described and not use '...'.
> * [X]  REQUIRED: There needs to be source information provided for this data.
> 
> _demo_survival_data_
> 
> * [X]  REQUIRED: The format of the data needs to be described.
> * [X]  REQUIRED: There needs to be source information provided for this data.
> 
> ## Unit tests
> * [X]  REQUIRED: It is good practice to include unit tests and we highly
>   recommend them. However, these tests should be testing functionality from your
>   package not just simple mathematics. Please see our documentation for the proper
>   use of unit tests,
>   https://bioconductor.org/developers/package-guidelines/#unittest.
> 
> ## R code
> * [X]  REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` instead. Found
>   in the follow files:
>   - IdentifyMCB.R - lines 62, 77, and 110
>   - metricMCB.R - lines 95, 160, and 222
>   - univ_coxph.R - line 21
>   - utils.R - lines 51, 92, and 198
> * [ ]  SUGGESTION: For easier reading (and debugging) of your code, consider
>   shorter lines. There are 221 lines that are > 80 characters long.
> * [ ]  SUGGESTION: For easier reading (and debugging) of your code, consider
>   multiples of 4 spaces for line indents. There are 511 lines that are not.
> 
> Best,
> Kayla

Hi Kayla,
Thank you for reviewing my package. I really appreciate it! 
Most of the required and suggestion changes have been made accordingly. 
Except:

REQUIRED: The only dataset that was actually used in this package was
   `demo_survival_data`. If the other datasets aren't used (or demonstrated) then
   they shouldn't be included.
Response: dataset 'demo_MCBinformation' was used for demo in metricMCB();
dataset dataset 'demo_set' was used for demo in create_demo();

* [ ]  SUGGESTION: Before line 107, I would add `head(em_prediction_results)` and
>   then explain a bit what the results actually mean.
Response: This function will only return a single vector for predicted risk scores. 
I have updated the description in the Vignettes.

 * [ ]  SUGGESTION: For easier reading (and debugging) of your code, consider
   shorter lines. There are 221 lines that are > 80 characters long.
Response: Those lines mostly are the description lines for 'devtools' package.
 * [ ]  SUGGESTION: For easier reading (and debugging) of your code, consider
   multiples of 4 spaces for line indents. There are 511 lines that are not.
Response: Some of the spaces are not standard 4 spaces for longer lines.

**Comment by whirlsyu** [comment]
@Kayla-Morrell
Hello, Kayla,
All the required changes and most suggested changes have been made accordingly.
Please re-review it to see if I did the right thing.
Thank you for reviewing our packages!
Best,
Xin Yu.

**Comment by Kayla-Morrell** [comment]
@whirlsyu - Thank you for making those changes. I have one final requirement and then I can accept the package. Please see the note below.

- [ ] REQUIRED: Thank you for including the table of content. However, this can
be better done in the metadata of the vignette. Try changing line 3 to this,

```{r}
output: rmarkdown::html_vignette:
  toc:true
```

Then you can remove lines 12-17, the table of content will be created
automatically based on the section headers, and the links should be interactive.

Best,
Kayla

**Comment by whirlsyu** [comment]
> @whirlsyu - Thank you for making those changes. I have one final requirement and then I can accept the package. Please see the note below.
> 
> * [X]  REQUIRED: Thank you for including the table of content. However, this can
>   be better done in the metadata of the vignette. Try changing line 3 to this,
> 
> ```
> output: rmarkdown::html_vignette:
>   toc:true
> ```
> 
> Then you can remove lines 12-17, the table of content will be created
> automatically based on the section headers, and the links should be interactive.
> 
> Best,
> Kayla
@Kayla-Morrell
Hi Kayla,
   The YAML header has been changed accordingly!
   Thank you for reviewing our packages! I really appreciate it!
Best,
Xin

**Comment by Kayla-Morrell** [comment]
@whirlsyu - Everything looks good now and I'm happy to accept the package.

Best,
Kayla

**Comment by whirlsyu** [comment]
> @whirlsyu - Everything looks good now and I'm happy to accept the package.
> 
> Best,
> Kayla

@Kayla-Morrell 
Really thank you! :)
I have one further question... 
what I have to do if I need to upgrade our package and add some new features (eg. 2.0)?
Best,
Xin

**Comment by Kayla-Morrell** [comment]
@whirlsyu - There will be some additional instructions to follow once your package gets added to our Bioconductor git repository. But for the time being there is some information [here](https://bioconductor.org/developers/package-submission/#afteraccept) that will broadly explain it.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/whirlsyu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("EnMCB")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EnMCB

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
