### ISSUE TITLE
gmoviz

### ISSUE THREAD

**Issue by kzeglinski** [Bioconductor/Contributions#1354]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/malhamdoosh/gmoviz

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor.  A few minor comments below but in generally everything looks really good. 

**README**

- [ ] Thank you for include Bioconductor installation instructions.  It seems
  like you also copied those in for your intended installation from Azure
  DevOps? 

**LICENSE**

- [ ] The GPL-3 license is shipped with R so you do not need to inluce the
  LICSENSE file. You could update the DESCRIPTION to just be `License: GPL-3`

**DESCRIPTION**

- [ ] As mentioned above if you remove the LICENSE file than the License field
  would just be `GPL-3`
- [ ] We recommend removing `LazyData: true`; we have rarely found this helpful
  and can actually slow down package installation. 

**inst**

- [ ] Please include an inst/scripts/ directory that includes a file that
  describes how the data in the inst/extdata was generated. It can be R code,
  sudo code, or text description but should include any sort of relevant source
  information.

**vignettes**

_gmoviz\_overview.Rmd_

- [ ] For what its worth, CRAN package can be installed via BiocManager::install
  too.  And maybe its overkill to do the 
```
if (!require("BiocManager"))
  install.packages("BiocManager")
```
  This is simply telling naive users that if BiocManager isn't installed it will
  install it.  Maybe just saying this once at the start of the dependency
  section is good enough?

_gmoviz\_advnaced_

- [X] well written and easy to follow

**R code/man pages**
- [X] Code looks well written.

Please address the minor comments above.  When ready please kick off another build with a version bump and comment back here with what has been updated. 
Cheers,

**Comment by lshep** [comment]
I just wanted to check in about the above recommended changes and if we can expect any updates soon?

**Comment by kzeglinski** [comment]
So sorry for the delay; things have been a bit crazy lately! 
I'll have an update with recommended changes in the next few days

**Comment by kzeglinski** [comment]
Hi, I'm having a bit of trouble getting rid of the last warning from the build report. If I put   R (>= 4.0.0) in my dependencies I get the warning:
WARNING: Unless package includes compressed data, remove R version dependency.

And if I remove this dependency I get another warning
Warning: package needs dependence on R (>= 2.10)

Could you please advise on how to proceed with this? Thanks.
I've also addressed your comments below:

> Thank you for your submission to Bioconductor. A few minor comments below but in generally everything looks really good.
> 
> **README**
> 
> * [x ]  Thank you for include Bioconductor installation instructions.  It seems
>   like you also copied those in for your intended installation from Azure
>   DevOps?

Removed this section from the README!

> **LICENSE**
> 
> * [x ]  The GPL-3 license is shipped with R so you do not need to inluce the
>   LICSENSE file. You could update the DESCRIPTION to just be `License: GPL-3`

Removed license file and updated description to just be gpl-3
> **DESCRIPTION**
> 
> * [ x]  As mentioned above if you remove the LICENSE file than the License field
>   would just be `GPL-3`
as above

> * [ ]  We recommend removing `LazyData: true`; we have rarely found this helpful
>   and can actually slow down package installation.
I had a bit of trouble with this. The only 'data' my package has are some vectors of colours which are used both internally by functions and also externally by users. I found that if I set lazyData to false, I wasn't able to have this work smoothly. Would it be possible to leave lazyData true seeing as the 'data' in this case is very small? Otherwise do you have any advice on how to set up the colours in the package? Thanks.

> **inst**
> 
> * [x ]  Please include an inst/scripts/ directory that includes a file that
>   describes how the data in the inst/extdata was generated. It can be R code,
>   sudo code, or text description but should include any sort of relevant source
>   information.
done! added inst/scripts/extdata_info.txt which explains where inst/extdata comes from

> **vignettes**
> 
> _gmoviz_overview.Rmd_
> 
> * [ x]  For what its worth, CRAN package can be installed via BiocManager::install
>   too.  And maybe its overkill to do the
> 
> ```
> if (!require("BiocManager"))
>   install.packages("BiocManager")
> ```
> 
> This is simply telling naive users that if BiocManager isn't installed it will
> install it. Maybe just saying this once at the start of the dependency
> section is good enough?
Removed this! Also changed to use BiocManager::install to install CRAN packages too.

**Comment by lshep** [comment]
That warning can be ignored.  We tried to update it but seems to be very confusing so we are reverting back to the original check.  Everything else looks good.  Thank you for your submission.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kzeglinski.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gmoviz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gmoviz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
