### ISSUE TITLE
(inactive) IntAssoPlot

### ISSUE THREAD

**Issue by whweve** [Bioconductor/Contributions#1366]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/whweve/IntAssoPlot

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by whweve** [comment]
Dear there, 

I have fixed the warning and error according to the check results. Please recheck the package, and let me know if there is any more error and warning.

(1)  I deleted inst/doc folder.
(2)  I have added my email address to BioConductor.
(3)  I have added bioviews in description file.
(4)  I have formatted the R code, making the line is shorter.
(5)   R CMD BiocCheck says "* WARNING: Update R version dependency from 3.1 to 4.0.". However, no R (version >= 4.0) has been released. What does this mean?
(6)  R CMD BiocCheck says "* WARNING: Use TRUE/FALSE instead of T/F". I have always used TRUE/FALSE. What does this mean?

Thanks a lot!

Hongwei Wang

**Comment by whweve** [comment]
install_github("whweve/IntAssoPlot") can not work when delete the  /inst/doc folder. To make install_github work, I readded /inst/doc folder.

**Comment by whweve** [comment]
I have rechecked the package. But, BioC don't build and check the package, though I have send a webhook.

**Comment by whweve** [comment]
I have one error now. I am not listed in the bioc-developer's list. 
I tried many times to get engaged. However, the registration requires to fill in the captcha. I dont konw why my web page didn't show any captcha at all. 
I tried firefox, edge, IE. All my effort ended in fail. There is no captcha. 
Can you help me to solve this. My emial is whweve@163.com

**Comment by hpages** [comment]
Hi, I think you just need to check the checkbox that says "I'm not a robot".

**Comment by whweve** [comment]
Dear Pages,


Thank you for your time and help.


I am sorry to say that there is no checkbox in my webpage that says "I am not a robot".


Would you please help me to sign my email account in. My email account is "whweve@163.com".




Sorry to trouble you again


Thank you very much!


Hongwei Wang


| |


|
|
On 2/13/2020 16:29，Hervé Pagès<notifications@github.com> wrote：
|

Hi, I think you just need to check the checkbox that says "I'm not a robot".

**Comment by hpages** [comment]
I can't do that for you. Here is the page for subscribing: https://stat.ethz.ch/mailman/listinfo/bioc-devel If you can't access the page or if the page doesn't display properly for you, then it's a problem that needs to be solved on your side. Thanks!

**Comment by vjcitn** [comment]
The visualizations are nicely done.  The documentation needs improvement.  The man page for `association` has
```
GWAS result.

Description:

     A dataset containing the association file. The variables are as
     follows:

Usage:

     association
     
Format:

     :

     Marker molecular marker name

     Locus the chromosome of the marker
```
which is sketchy and does not really tell about any required fields or underlying schema.  The examples are based on maize -- are there examples available for mouse or human data?  The vignette does not describe the inputs well:
```
1. input data format
1.1 association data format
A dataset containing the association file. The variables are as follows: Marker (molecular marker name), Locus (the chromosome of the marker), Site (the position of the marke), p (p value of the marker) Here’s a quick demo of association data format:
```
The dataset does not contain a file.  The "input data" (input to your function) seems to be a data.frame with specific columns available.  Getting that data.frame from a file is often of interest, particularly when the file is of a format commonly produced in genetic research. Unfortunately for GWAS in human genetics, there seems to be no standard -- see for example https://huwenboshi.github.io/data%20management/2017/11/23/tips-for-formatting-gwas-summary-stats.html ...  Whatever convention you need to make your plots should be stated clearly at the outset of the vignette.

Please write your vignette as if you are teaching an interested and technically competent person how to appraise the usefulness of your tools in their work, and how to use them if there is in fact a need.

**Comment by whweve** [comment]
Dear Carey,


Thanks for your review and helpful suggestions.
I am now working on the questions raised, and I am going to make the vignette more detailed.
However, I focused on the genetic research on maize. I don't have genetic data from mouse or human. But, I will keep the package developing, and I think I will put more time and effort to make the package more easily and widely used.


Thanks again for your helpful suggestions.


Hongwei Wang


| |
王宏伟
|
|
whweve@163.com
|


On 2/14/2020 19:19，Vince Carey<notifications@github.com> wrote：

The visualizations are nicely done. The documentation needs improvement. The man page for association has

GWAS result.



Description:



     A dataset containing the association file. The variables are as

     follows:



Usage:



     association

     

Format:



     :



     Marker molecular marker name



     Locus the chromosome of the marker



which is sketchy and does not really tell about any required fields or underlying schema. The examples are based on maize -- are there examples available for mouse or human data? The vignette does not describe the inputs well:

1. input data format

1.1 association data format

A dataset containing the association file. The variables are as follows: Marker (molecular marker name), Locus (the chromosome of the marker), Site (the position of the marke), p (p value of the marker) Here’s a quick demo of association data format:



The dataset does not contain a file. The "input data" (input to your function) seems to be a data.frame with specific columns available. Getting that data.frame from a file is often of interest, particularly when the file is of a format commonly produced in genetic research. Unfortunately for GWAS in human genetics, there seems to be no standard -- see for example https://huwenboshi.github.io/data%20management/2017/11/23/tips-for-formatting-gwas-summary-stats.html ... Whatever convention you need to make your plots should be stated clearly at the outset of the vignette.

Please write your vignette as if you are teaching an interested and technically competent person how to appraise the usefulness of your tools in their work, and how to use them if there is in fact a need.

**Comment by whweve** [comment]
Dear Carey,

I have updated the vignette, please recheck.

Thanks a lot!

Hongwei Wang

**Comment by hpages** [comment]
Thanks @vjcitn for providing feedback.

Thanks for this submission. Here are some additional comments:

1. The words that make the title of your vignette are separated with hyphens (quick-introduction-to-IntAssoPlot). Please use spaces instead. Also capitalize your title (see rules [here](https://capitalizemytitle.com/)).
 
2. The vignette should show the standard way to install a Bioconductor package (i.e. using BiocManager). Installing a Bioconductor package from GitHub is almost never a good idea. This will reduce your long and complicated _Installation_ section to 3 lines of code. It will also eliminate the risk of version mismatches inherent to manually picking/installing the various dependencies of your package from different places. 

3. Subsection _1.4 example_ of the vignette doesn't really belong to the _Installation_ section. Maybe you could replace your _Installation_ section with an _Introduction_ section and make `Installation` and `Examples` subsections of that?

4. Non-evaluated code (e.g. `example(“IntGenicPlot”)` still needs to look like code (by wrapping it in single or triple backquotes). Right now it looks like plain text which makes it hard to distinguish from the rest of the text. Not having it formatted as code in the rendered HTML also has the unfortunate side-effect of replacing the double quotes with fancy double quotes, which then cause an error when the user copy/paste the code in their session:
    ```
    > example(“IntGenicPlot”)
    Error: unexpected input in "example(“"
    ```
    Note that after replacing the fancy quotes with the normal ones, the user will still get an error:
    ```
    > example("IntGenicPlot")
    Warning message:
    In example("IntGenicPlot") : no help found for ‘IntGenicPlot’
    ```
    That's because at this point in the vignette the user still has not been told to load the IntAssoPlot package.

5. Other formatting problems:
    - Subsection 2.1 starts in the middle of a paragraph.
    - Properly capitalize your section and subsection headers (here you can use "Sentence case" instead of "Title Case").

6. The figures in the vignette should be numbered.

7. The man pages of the data sets are still too sketchy and would need to provide more details. See @vjcitn's earlier comment about this.

Thanks!

**Comment by hpages** [comment]
Hi @whweve ,

Are you done with the changes? Should I take a 2nd look?

Thanks,
H.

**Comment by whweve** [comment]
Thanks a lot!
Please take a time to look at the revised package. Also, please let me know if there are any questions. I will fix them as soon as possible.


Hongwei Wang
| |
王宏伟
|
|
whweve@163.com
|


On 4/2/2020 18:27，Hervé Pagès<notifications@github.com> wrote：

Hi @whweve ,

Are you done with the changes? Should I take a 2nd look?

Thanks,
H.

**Comment by hpages** [comment]
Hi @whweve 

Items 2. 3. 4. 7. in my original feedback are still not addressed. Also the section and subsection headers are still not properly capitalized (see item 5.)

Overall the quality and usability of the package remain poor.

Best,
H.

**Comment by lshep** [comment]
Do you plan on making updates to your package soon.  Packages not actively making changes and participating in the review process will be closed for inactivity and you can request it be opened when you have time to work through the submission process?
