### ISSUE TITLE
SegmentedCellExperiment

### ISSUE THREAD

**Issue by ellispatrick** [Bioconductor/Contributions#1370]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ellispatrick/SegmentedCellExperiment

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ X] The 'devel' branch for new packages and features.
- [ X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please remove the build product (.R, .html) from the vignettes directory.

I'm very surprised that this does not extend the SummarizedExperiment or SingleCellExperiment class.

Please provide a more extensive Description: summarizing the unique aspects of your contribution.

I'll provide more extensive comments when these issues (and other issues identified by the automatic checks) are addressed.

**Comment by ellispatrick** [comment]
Thanks Martin.

 I’m sure there have been many long discussion on the best ways to store scRNA-seq data and multi-omic experiments in general. I’ll give you brain dump of my naïve thought process which hopefully provides a little bit of insight into why I wanted a simple data structure for my personal analysis.

For the imaging datasets I have been working with I typically have 100’s of millions of cells. For this reason alone, the statistician in me really wants to use this as a justification to revert to having the observations (cells) as rows and features on the columns. The structure of a flowSet becomes much more appealing and much more natural when arriving to this data structure via imaging mass cytometry. Most of the people in my institute store their data in fcs files and do basic analysis in flowjo anyway. Also, given that I can have 100’s of images, I really wanted the data to be split by image as much as by cell and so again the flowSet or ncdfFlow seemed more appropriate. So the real question becomes less of why not extend SummarizedExperiment or SingleCellExperiment class and more why not extend flowSet or ncdfFlow. There is not a strong reason but it is primarily because I wanted something with a simpler structure that I would be able to extend to eventually be able to store the raw images themselves, masks and polygons. Conceptually I also wanted it to feel “matrix” like and retain the feel of a cellProfiler or ilastik output. Having everything in a big DataFrame with rows being images and columns being modality just made it much easier for me to work with, and think about, my data. However, I’m sure it is not very efficient.

**Comment by vjcitn** [comment]
I built the vignette, which does a good job of illustrating the capabilities.  I am not heavily invested in flow so my comments should carry less weight than an active practitioner.  SegmentedCellExperiment extends DataFrame and defines methods that take advantage of DataFrame nesting to represent elements of cell-based experiments that are commonly encountered.

The show method produces 
```
> cellExp
SegmentedCellExperiment with 2 rows and 6 columns
                                                location
                                    <SplitDataFrameList>
1 1:1:0.367243:...,2:2:0.613818:...,3:3:0.335930:...,...
2 6:1:0.831271:...,7:2:0.130342:...,8:3:0.217023:...,...
                                                       intensity
                                            <SplitDataFrameList>
1 0.1281166:0.10817130,0.1503157:0.17161615,0.0796545:0.00631104
2    0.1707524:0.0975236,0.0697529:0.0892760,0.0890765:0.0190400
                                                   morphology
                                         <SplitDataFrameList>
1    0.489959:1.3913000,3.601540:0.3670445,0.243015:0.0149731
2 0.498723:0.03411949,0.818412:2.25542506,0.932012:0.00920492
             phenotype               images                masks
  <SplitDataFrameList> <SplitDataFrameList> <SplitDataFrameList>
1            1:21:dead                                          
2           2:81:alive                                          
```
which is challenging to read and interpret.  A show method should be
defined to give users a quick sense of content.  This particular instance
involves information on 10 cells derived from two images.  Those basic
facts should be presented in the show method.

A convention seems to be emerging in which classes with name *Experiment
extend SummarizedExperiment, where the basic interpretation is that G
features recorded on N samples are retrievable using  the assay() method, and
R characteristics recorded on N samples are retrievable using the colData()
method.  It seems to me that the data handled by this package could at least
in part be organized in a way that conforms to this scheme, and the parts
that cannot could be provided as extensions to a species of *Experiment, 
probably SingleCellExperiment.  We have found that adoption of these
conventions fosters interoperability and package reuse.  Enhancements to the
underlying infrastructure often provide benefits to packages defining inheriting
classes "for free".

**Comment by ellispatrick** [comment]
Thanks Vince. I'll include this information. The wording of the description sounds great and show method sounds very sensible.

Just to clarify, it sounds like the name of the class is misleading as it is not extending SummarisedExperiment? I'll spend some time thinking of a better name, open to suggestions.

**Comment by ellispatrick** [comment]
Feedback was all great. I am going to change the name and maybe roll into the analysis package which calls it.
