### ISSUE TITLE
fmrs

### ISSUE THREAD

**Issue by shokoohi** [Bioconductor/Contributions#1411]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shokoohi/fmrs

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Given the general statistical nature of this package, does it make more sense to submit this to CRAN, where a wider audience will see it? If you agree, please close this issue.

**Comment by shokoohi** [comment]
It was on CRAN but I many mentioned that it is about survival analysis then you should submit it to Bioconductor. So I decided to remove it from CRAN and submit it to Bioconductor.

**Comment by mtmorgan** [comment]
I'm not sure that I follow -- Bioconductor does not focus on survival analysis, and your package has no dependencies on other Bioconductor packages so does not 'interoperate' with the Bioconductor ecosystem. I strongly suggest that you leave your package on CRAN.

I see from

  https://cran.r-project.org/web/packages/fmrs/index.html

that

> Archived on 2020-03-07 as check problems were not corrected despite reminders.

Are you just trying to avoid maintaining your package to CRAN standards?

**Comment by shokoohi** [comment]
I am trying to add a package to Bioconductor. As far as it is written in Bioconductor policy, packages about survival are accepted.

**Comment by shokoohi** [comment]
I already have two other packages on Bioconductor: DMCHMM and DMCFB

**Comment by shokoohi** [comment]
Hello
Can you tell me what is the next step?
Thank you

**Comment by mtmorgan** [comment]
the reviewer (me) will provide a review; sorry for the delay.

**Comment by mtmorgan** [comment]
Please provide a detailed explanation of the reasons your package was removed from CRAN. What check problems were not corrected? Have they been corrected now? Why were you not responsive as a maintainer, and in particular why will you be more responsive as a Bioconductor maintainer?

DESCRIPTION, NAMESPACE

- ok

vignettes

- please do not include the vignette products (R, html files) in the vignette directory; it is generated with R CMD build.

- Use three back-ticks ``` for 'fences', not four; simply omitting the `{r}` is sufficent to avoid evaluation.

R -- specific comments should be carefully considered for application to other code

- please consider more traditional formatting, e.g., using the formatR package, especially indentation, e.g., 
  ```
  if(missing(y) | !is.numeric(y))
  stop("A numeric response vector must be provided.")
  ```
  as
  ```
  if (missing(y) | !is.numeric(y))
      stop("A numeric response vector must be provided.")
  ```
  so that your code is more easily readable by others.

- because 'survival' is imported, it is not necessary to `require(survival)` in your code.

- review code for basic vectorizion efficiencies, e.g., replacing iteration (`n` R-level function calls)
  ```
  for (k1 in seq_len(Num.Comp)) {
      sumwi[k1] = 0
  }
  ```
  with vectorization (one R-level function call)
  ```
  sumwi[seq_len(Num.Comp)] = 0
  ```

- reconsider the value of a package startup message; generally this is a 'tragedy of the commons', where if each package advertises itself in this way the user is overwhelmed with startup messages and misses truly valuable information.

man

- good

tests

- the single test seems to replicate the 'integeration' tests provided by the vignette and examples. It would be much more satisifying to see a comprehensive set of unit tests evaluating your software.

**Comment by mtmorgan** [comment]
will you revise your package? the deadline for addition to the current release is April 22.

**Comment by shokoohi** [comment]
sorry I just started to work on it. I fix it today.

**Comment by shokoohi** [comment]
All done. In response to your question:
I do not recall why it is removed but I did not care since I wanted to remove it and submit it to bioconductor mainly because this package, although general, but specifically it is used for genomic data and survival analysis. Besides I want to handle all of my packages in one place. Last but not least, handling packages and staying uptodate on bioconductor is more professional and easier. 
All the best, Farhad

**Comment by shokoohi** [comment]
what's next?

**Comment by mtmorgan** [comment]
provide a brief response to the review, describing how you have responded to each item.

**Comment by shokoohi** [comment]
> vignettes
> 
> * please do not include the vignette products (R, html files) in the vignette directory; it is generated with R CMD build.

**Done!**

> * Use three back-ticks ``` for 'fences', not four; simply omitting the `{r}` is sufficent to avoid evaluation.
**Fixed!**
> 
> R -- specific comments should be carefully considered for application to other code
> 
> * please consider more traditional formatting, e.g., using the formatR package, especially indentation, e.g.,
>   ```
>   if(missing(y) | !is.numeric(y))
>   stop("A numeric response vector must be provided.")
>   ```
>   
>   
>   as
>   ```
>   if (missing(y) | !is.numeric(y))
>       stop("A numeric response vector must be provided.")
>   ```
>   
>   
>   so that your code is more easily readable by others.

**Used formatR to format all files and fixed some problem cause by former!**

> * because 'survival' is imported, it is not necessary to `require(survival)` in your code.

**Removed!**

> * review code for basic vectorizion efficiencies, e.g., replacing iteration (`n` R-level function calls)
>   ```
>   for (k1 in seq_len(Num.Comp)) {
>       sumwi[k1] = 0
>   }
>   ```
>   
>   
>   with vectorization (one R-level function call)
>   ```
>   sumwi[seq_len(Num.Comp)] = 0
>   ```

**Done!**

> * reconsider the value of a package startup message; generally this is a 'tragedy of the commons', where if each package advertises itself in this way the user is overwhelmed with startup messages and misses truly valuable information.

**Done!**

> 
> man
> 
> * good
> 
> tests
> 
> * the single test seems to replicate the 'integeration' tests provided by the vignette and examples. It would be much more satisifying to see a comprehensive set of unit tests evaluating your software.

**Updated with a new test!**

**Comment by mtmorgan** [comment]
Please further review your code for inefficiencies, e.g., https://github.com/shokoohi/fmrs/blob/412770737d17f8a027eae4a00c34588736ff5cf3/R/AllMethods.R#L170 is simply 
```
new_pi0 = sumwi / Sample.Size
```
There are many other such examples.

**Comment by shokoohi** [comment]
Hello, I replaced some of the loops with more efficient codes; I will replace double loops later as they are more complex and I have to prepare final exams.

**Comment by shokoohi** [comment]
hello, what's next?

**Comment by mtmorgan** [comment]
you said 'some of the loops' and so I'm waiting for after your final exams for the rest...

**Comment by shokoohi** [comment]
ok, then two weeks at least ....
but if I wouldn't said it, what would happen?

**Comment by mtmorgan** [comment]
I would have looked at your package to see that the review concerns had been addressed. They would not have been and you would have been asked to complete the revisions. When the revisions were complete, I would have accepted your package to the devel branch of Bioconductor. It would be added, within a day or two of acceptance, to the 'devel' build manifest and to the Bioconductor git (not github). It would then build nightly and assuming that it passes, it would propagate to our public 'devel' repository. it would remain in devel only until the next release, in the fall, when it would be included in the release packages.

**Comment by lshep** [comment]
what is the status of implementing the changes @mtmorgan  suggested?  Do you plan on making updates soon to continue the review process?

**Comment by shokoohi** [comment]
Hello, sorry for late response. I was sick. I will work on it this week.

**Comment by shokoohi** [comment]
Hello, there are no issue remained to fix on the fmrs package. I followed all the requirements.

**Comment by mtmorgan** [comment]
I re-opened the issue. Please increment the package version to trigger an automatic build and check.

**Comment by shokoohi** [comment]
I don't understand this error. 
I tried bioconductor guidelines and changed the Description but the following error occurs:

`

Updating fmrs documentation
Loading fmrs
Invalid DESCRIPTION:
Malformed Authors@R field:
  <text>:1:78: unexpected string constant
1: person("Farhad", "Shokoohi", email = "shokoohi@icloud.com", role=c("cre", aut"), comment = c(ORCID = "
                                                                                 ^

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.

Re-compiling fmrs
─  installing *source* package ‘fmrs’ ...
   ** using staged installation
   Error : Invalid DESCRIPTION file
   
   Malformed Authors@R field:
     <text>:1:78: unexpected string constant
   1: person("Farhad", "Shokoohi", email = "shokoohi@icloud.com", role=c("cre", aut"), comment = c(ORCID = "
                                                                                    ^
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
   
   ERROR: installing package DESCRIPTION failed for package ‘fmrs’
─  removing ‘/private/var/folders/9q/88hxnskx4kg30vgg73y4nzl40000gn/T/Rtmpj0XVVD/devtools_install_1af674e4f5b2/fmrs’

Error: System command 'R' failed, exit status: 1, stdout + stderr:
E> * installing *source* package ‘fmrs’ ...
E> ** using staged installation
E> Error : Invalid DESCRIPTION file
E> 
E> Malformed Authors@R field:
E>   <text>:1:78: unexpected string constant
E> 1: person("Farhad", "Shokoohi", email = "shokoohi@icloud.com", role=c("cre", aut"), comment = c(ORCID = "
E>                                                                                  ^
E> 
E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
E> manual.
E> 
E> ERROR: installing package DESCRIPTION failed for package ‘fmrs’
E> * removing ‘/private/var/folders/9q/88hxnskx4kg30vgg73y4nzl40000gn/T/Rtmpj0XVVD/devtools_install_1af674e4f5b2/fmrs’

 Stack trace:

 1. base:::suppressPackageStartupMessages({ ...
 2. base:::withCallingHandlers(expr, packageStartupMessage = function(c) tryInv ...
 3. devtools::document(roclets = c("rd", "collate", "namespace",  ...
 4. withr::with_envvar(r_env_vars(), roxygen2::roxygenise(pkg$path,  ...
 5. base:::force(code)
 6. roxygen2::roxygenise(pkg$path, roclets, load_code = load_code)
 7. roxygen2:::load_code(base_path)
 8. pkgload::load_all(path, helpers = FALSE, attach_testthat = FALSE)
 9. pkgbuild::compile_dll(path, quiet = quiet)
 10. withr::with_makevars(compiler_flags(TRUE), assignment = "+=",  ...
 11. withr:::with_envvar(c(R_MAKEVARS_USER = makevars_file), { ...
 12. base:::force(code)
 13. base:::force(code)
 14. pkgbuild:::install_min(path, dest = install_dir, components = "libs",  ...
 15. pkgbuild:::rcmd_build_tools("INSTALL", c(path, paste("--library=",  ...
 16. pkgbuild:::with_build_tools(callr::rcmd_safe(..., env = env,  ...
 17. callr::rcmd_safe(..., env = env, spinner = FALSE, show = FALSE,  ...
 18. callr:::run_r(options)
 19. base:::with(options, with_envvar(env, do.call(processx::run,  ...
 20. base:::with.default(options, with_envvar(env, do.call(processx::run,  ...
 21. base:::eval(substitute(expr), data, enclos = parent.frame())
 22. base:::eval(substitute(expr), data, enclos = parent.frame())
 23. callr:::with_envvar(env, do.call(processx::run, c(list(bin, args = real_cmd ...
 24. base:::force(code)
 25. base:::do.call(processx::run, c(list(bin, args = real_cmdargs,  ...
 26. (function (command = NULL, args = character(), error_on_status = TRUE,  ...
 27. throw(new_process_error(res, call = sys.call(), echo = echo,  ...

 x System command 'R' failed, exit status: 1, stdout + stderr:
E> * installing *source* package ‘fmrs’ ...
E> ** using staged installation
E> Error : Invalid DESCRIPTION file
E> 
E> Malformed Authors@R field:
E>   <text>:1:78: unexpected string constant
E> 1: person("Farhad", "Shokoohi", email = "shokoohi@icloud.com", role=c("cre", aut"), comment = c(ORCID = "
E>                                                                                  ^
E> 
E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
E> manual.
E> 
E> ERROR: installing package DESCRIPTION failed for package ‘fmrs’
E> * removing ‘/private/var/folders/9q/88hxnskx4kg30vgg73y4nzl40000gn/T/Rtmpj0XVVD/devtools_install_1af674e4f5b2/fmrs’ 

Execution halted

Exited with status 1.
`

**Comment by shokoohi** [comment]
I don't understand this error. It does not make sense. 

* Checking for valid maintainer...
    * ERROR: Use Authors@R field not Author/Maintainer fields. Do not
      use both.

**Comment by shokoohi** [comment]
And this problem:

> ERROR: R installation problem: File /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libgfortran.3.dylib not found!

I don't know how to fix it.

**Comment by mtmorgan** [comment]
You were on the right track with using `Authors@R` instead of the Author / Maintainer fields in the DESCPRIPTION file.
```
Malformed Authors@R field:
:1:78: unexpected string constant
1: person("Farhad", "Shokoohi", email = "shokoohi@icloud.com", role=c("cre", aut"), comment = 
```
is trying to point you to the missing quotation mark `"` before `aut"` (the value of the `Authors@R` field can be cut / pasted into R to test).

The libgfortran problem seems to be a build system configuration issue.

**Comment by mtmorgan** [comment]
In reviewing your changes I noticed that you have
```
setGeneric("show")
show.fmrsfit <- function(object) {
...
```
but `show` is already a generic and you really just want to define a method
```
setMethod("show", "fmrsfit", fucntion(object) {
    ...
})
```
There is a second occurrence of `setGeneric("show")` later in the file that also requires fixing.

If you make this change and remove the Author / Maintainer field from the DESCRIPTION file I will accept it.

**Comment by shokoohi** [comment]
> You use both `Authors@R` and `Author:` / `Maintainer:` notation; remove `Author:` and `Maintainer:` fields.
> 
> The libgfortran problem seems to be a build system configuration issue.

No I didn't. I only use `Authors@R`. Prior to this I was using `Author:` and `Maintainer:` fields. But it gives error.  Below is my Description. 
I made changes regarding show methods. 
On my Mac everything run perfectly fine. 

Package: fmrs
Type: Package
Title: Variable Selection in Finite Mixture of AFT Regression and FMR
Version: 0.99.17
Date: 2020-06-15
Authors@R: c(person("Farhad", "Shokoohi", role = c("aut", "cre"),
                     email = "shokoohi@icloud.com", comment = c(ORCID = "0000-0002-6224-2609"))
              )
Depends:
    R (>= 4.0.0)
Imports:
    methods,
    survival,
    stats
Description: Provides parameter estimation as well as variable selection in
    Finite Mixture of Accelerated Failure Time Regression and Finite
    Mixture of Regression Models.
    Furthermore, this package provides Ridge Regression and Elastic Net.
biocViews: Survival, Regression, DimensionReduction
Suggests: BiocGenerics, testthat, knitr, utils
License: GPL (>= 3)
LazyData: TRUE
VignetteBuilder: knitr
BugReports: https://github.com/shokoohi/fmrs/issues
Packaged: 2017-01-10 21:22:24 UTC; Farhad
RoxygenNote: 7.1.0
Encoding: UTF-8

**Comment by mtmorgan** [comment]
remove these lines https://github.com/shokoohi/fmrs/blob/9091bf75bda6ab433bf220778645e917a490d870/DESCRIPTION#L25-L26 from your DESCRIPTION file

**Comment by shokoohi** [comment]
I AM USING ONLY 'Authors@R'. WHAT THE … IS WRONG WITH YOUR SYSTEM. GETTING TIRED OF THIS PROBLEM.

**Comment by shokoohi** [comment]
THERE IS NOTHING LIKE THIS IN MY DESCRIPTION.

**Comment by mtmorgan** [comment]
You said:
```
I AM USING ONLY 'Authors@R'. WHAT THE … IS WRONG WITH YOUR SYSTEM. GETTING TIRED OF THIS PROBLEM.
```
That was not correct. as indicated by the 'permalink' https://github.com/shokoohi/fmrs/blob/9091bf75bda6ab433bf220778645e917a490d870/DESCRIPTION#L25-L26. If you feel like Bioconductor is not a good fit for you, why don't we close the issue, and you can use other mechanisms to publish your package?

**Comment by shokoohi** [comment]
I did not put those 3 last lines in Description. It turns out that when building using R 'Build Source Package' in RStudio it creates those 3 lines which I could not see in my Description and the build version automatically uploaded to GitHub. So when I said `I AM USING …` I did not lie.

**Comment by shokoohi** [comment]
Thank you.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shokoohi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("fmrs")`. The package 'landing page' will be created at

https://bioconductor.org/packages/fmrs

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
