### ISSUE TITLE
CiteFuse

### ISSUE THREAD

**Issue by YingxinLin** [Bioconductor/Contributions#1415]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SydneyBioX/CiteFuse

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by YingxinLin** [comment]
Hi @Kayla-Morrell ,

I am wondering what should I do with the warning:
```
* Checking R Version dependency...
    * WARNING: Unless package includes compressed data, remove R
      version dependency.
```

If I removed `Depends: R (>= 4.0)`, I will get this error in `R CMD Check`:

`Error in if (dep$op != ">=") next : argument is of length zero`

suggesting adding `Depends: R (>= 3.0.0)` is required based on the answer here: https://stackoverflow.com/questions/53578625/r-cmd-build-fails-argument-is-of-length-zero

Any suggestions to solve this will be greatly appreciated!

Regards,
Yingxin

**Comment by Kayla-Morrell** [comment]
@YingxinLin - This warning can be ignored, it has since been removed. Please let me know if this package is ready for review.

Best,
Kayla

**Comment by YingxinLin** [comment]
Hi Kayla,

Thank you for your reply. Yes, the package is ready for review.

Best wishes,
Yingxin

**Comment by Kayla-Morrell** [comment]
Hello @YingxinLin,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review. Keep in mind that the deadline for accepting new packages into the Bioconductor 3.11 release is 4/22.

## General package development

- [ ] REQUIRED: The 'figures/' directory does not belong in the 'man/' 
directory. It should be in an 'inst/figures/' directory instead. 

- [ ] REQUIRED: What is the purpose of the 'doc/' diretory? This directory seems 
to be taking up the most room in the package.

## DESCRIPTION

- [ ] REQUIRED: The 'Description:' field needs more detail. The description 
should be a relatively short but detailed overview of what the package 
functionality entails. It should be one or more complete sentences.

- [ ] REQUIRED: 'LazyData:' should be set to false. In our experience when this 
is true it slows down the loading of packages, expecially those with large data.

- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' field with the 
relevant link to GitHub for reporting Issues.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements. See the following for formating,
https://bioconductor.org/developers/package-guidelines/#news.

## Vignettes

- [ ] REQUIRED: There should be an installation section that shows the user how 
to install the package from Bioconductor. The code should look something like 
the following and be `eval = FALSE`.

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("CiteFuse")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: Sections 3-7 need some explanatory text to go along with the 
code and plots.  

## Man pages

- [ ] REQUIRED: Add runnable examples to the following man pages which document 
exported objects:
        - eigenMapMatMult.Rd
        - readFrom10X.Rd
        - SNF_fast.Rd

- [ ] REQUIRED: These functions are demonstrated in the vignettes so they don't 
have to have runnable examples, but you should at least include an example in 
the man page either in dontrun{} or donttest{} (if they take too long to 
process).
	- DEcomparisonPlot
	- DEgenesCross

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
https://bioconductor.org/developers/how-to/unitTesting-guidelines/

## R code

- [ ] SUGGESTION: Consider clarifying how 7 object(s) are initialized. Maybe 
they are part of a data set loaded with data(), or perhaps part of an object 
referenced in with() or within().
        function (object)
        DEbubblePlot (leaf)
        visualiseExprs (group)
        visualiseExprs (value)
        visualiseExprs (features)
        visualiseExprsList (group)
        visualiseExprsList (value)
        visualiseExprsList (features)

- [ ] REQUIRED: Avoid sapply(); use vapply() if possible. Found in files:
        - clustering.R, lines 558 and 650
        - ligandReceptor_analysis.R, lines 100, 102, 118, 141, and 165
        - QCfunctions.R, line 508
        - visualise_features.R, line 287

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 115 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 1622 lines that are not.

Best,
Kayla

**Comment by YingxinLin** [comment]
Dear @Kayla-Morrell,

Thanks a lot for all your constructive feedback on the package. They are really helpful. I have addressed most of them in all relevant contexts. Please let me know if there are any further issues I should work on.

Below are the summary of the updates:

**General package development**
- The figures folder now is moved to inst/figures. 
- docs/ folder is generated by pkgdown to create the package website. I have now created a new branch for these files

**Description**
- We have improved our description with more detailed overview of the package. 
- `LazyData` is now set as false
- BugReports is added in the Description

**NEWS**
- NEWS.md is added 

**Vignettes**
- Installation instruction is added on top of the vignettes
- Table of contents is also added
- We have improved the explanatory text in Sections 3-7 in the vignettes, providing more detailed guideline for users to use the package.

**Man pages**
- The `eigenMapMatMult` and `SNF_fast `functions are removed from the package of the latest version due to the computation improvement in R devel.
- Examples for `readFrom10X` are added in both man pages and vignettes. But as this function is reading the data from downloaded files on 10X Genomics website (approximately 30M), I have added `dontrun` and `eval = FALSE` for the examples.
- Runnable examples are added in both `DEcomparisonPlot` and `DEgenesCross`

**R codes**
- All `sapply()` are replaced by `vapply()`
- The 7 objects mentioned are clarified in the codes
- Formatting: the percentages of lines over 80 characters long and lines without multiples of 4 spaces have been reduced. 

Best regards,
Yingxin

**Comment by Kayla-Morrell** [comment]
@YingxinLin - Thank you for making the necessary changes. Everything looks good and I'm more than happy to accept the package.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/YingxinLin.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CiteFuse")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CiteFuse

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
