### ISSUE TITLE
tensorICA

### ISSUE THREAD

**Issue by jinghan1018** [Bioconductor/Contributions#1419]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jinghan1018/tensorICA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi @jinghan1018 
Please fix the errors on the report. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi @jinghan1018 
If you would like to continue the review process, please fix the errors on the report. 
The deadline for the review and changes is **April 22nd**. If you would like to get the package submitted for the release, let me know. Otherwise, the package will go into the devel version of Bioconductor (contingent on follow up and changes). If there is no response, I will be forced to close the issue due to inactivity within the next week. Thank you. 
-Marcel

**Comment by jinghan1018** [comment]
> Hi @jinghan1018
> If you would like to continue the review process, please fix the errors on the report.
> The deadline for the review and changes is **April 22nd**. If you would like to get the package submitted for the release, let me know. Otherwise, the package will go into the devel version of Bioconductor (contingent on follow up and changes). If there is no response, I will be forced to close the issue due to inactivity within the next week. Thank you.
> -Marcel

Hi Marcel,
Thanks for your reply. I would like to fix the errors. But I am not sure what is the error about. Cause I checked my package on both linux server and local windows platforms. It passed all checks and builds. Could you give me a hint?
Thanks again.
Best,
Han

**Comment by LiNk-NY** [comment]
Hi Han, @jinghan1018 

There are a couple of things. 

First, bump the version of the package since it seems to have been a
MiKTeX issue on Windows and the issue may have been intermittent
or fixed.

Second, please fix the error in the examples:
```
> cp13 <- plot_component(tica.o = tica.o, component = 12, nt.idx = c(1,2), tp = seq(501,562));
Error in if (tp != 0) { : the condition has length > 1
```

Thanks.
Marcel

**Comment by LiNk-NY** [comment]
Hi Han Jing, @jinghan1018

Please provide any updates on the package. It looks like the package will likely go in Bioconductor development branch as the deadline to add new packages is tomorrow. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Han Jing, @jinghan1018 
I will close the issue for now. Feel free to reopen it when you are ready. 
Thank you for your contribution. 
Best,
Marcel
