### ISSUE TITLE
bioconductor_docker_cetf

### ISSUE THREAD

**Issue by cbiagii** [Bioconductor/Contributions#1439]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cbiagii/bioconductor_docker_cetf

Confirm the following by editing each check box to '[x]'

- [ X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ X ] The 'devel' branch for new packages and features.
- [ X ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ X ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
We'll process this manually as we develop supporting infrastructure. @nturaga will provide an initial review.

**Comment by nturaga** [comment]
# Docker image review

## Build 

* Local build - ok

* The image should show a successful build on dockerhub. Please
  provide a valid link in your README.md file to the dockerhub
  location.

## FROM

* ok

## LABELS

* ok

* The "description" should be more elaborate. Please think of it as a small abstract.

## Dockerfile 

### Linux Dependencies

* The linux dependencies overlap with what is already installed on
  bioconductor_docker:devel. Please review all the linux dependencies in the Docker file and compare to the Dockerfile in bioconductor/bioconductor_docker:devel . Provide justification for each linux dependency you install in this image,

  For example, there is no need to install,
  
  - libxml2-dev
  
  - libpng-dev
  
  - libcairo2-dev
  
  - build-essentials
  
* Please explain which linux dependencies are needed for the package
  `CeTF` which are not already available on
  bioconductor/bioconductor_docker:devel.

### R packages

* Why are the install scripts using two different installation methods, i.e `install.packages()` and `BiocManager::install()`? 

  The Docker images **should only** use `BiocManager::install()` as the
  way to install packages.

* All the installations should be put in a single RUN
  command. ie. (just an example below, but you should get the gist on
  how to format your Dockerfile)

```
RUN R -e 'BiocManager::install(c( \
    "boot", \
    "class", \
    "cluster", \
    "codetools", \
    "foreign", \
    "kernsmooth", \
    "lattice"))
```

## Dockerfile

* Please try and use a SINGLE RUN command. i.e each RUN command adds a
  layer to the Docker image you create. The fewer layers the better. 
  
* The Dockerfile you provide can bundle the linux dependency
  installation and the R package installation in a single RUN command.
  
## General

* One of the most important things in the review process for a docker
  image is the value it adds. Please justify that this Docker image is
  not simply a single package CeTF installed on top of the base
  bioconductor image. 

I will review your Docker image again once the changes have been made. But I look forward to seeing the justification you provide for the value your image adds beyond simply installing `CeTF`.

**Comment by nturaga** [comment]
Hi @cbiagii ,

Please note that we give authors about 14 days from initial review to respond. 

Best,

Nitesh
