### ISSUE TITLE
scClassify

### ISSUE THREAD

**Issue by YingxinLin** [Bioconductor/Contributions#1446]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SydneyBioX/scClassify

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
One would expect this package to interact with (accept as inputs / return as outputs) SingleCell Experiment.

**Comment by lshep** [comment]
Please do a version bump so that the build report includes all changes to your repository for @Kayla-Morrell  to do a formal review.

**Comment by Kayla-Morrell** [comment]
Hello @YingxinLin,
Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review. Keep in mind that the deadline for accepting new packages into the Bioconductor 3.11 release is 4/22.

## General package development

- [ ] REQUIRED: What is the purpose of the 'doc/' directory?

## DESCRIPTION

- [ ] REQUIRED: The 'Description:' field needs more detail. It should be 
relatively short but detailed overview of what the package functionality entails.

- [ ] REQUIRED: 'LazyData:' should be set to 'false'. We find that when this 
field is set to true it can slow down the loading of the package.

- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' field with the 
relevant link to GitHub for reporting Issues.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements. Please see the following for 
formating help, https://bioconductor.org/developers/package-guidelines/#news.

## Vignette

*pretrainedModel*

- [ ] REQUIRED: There should be more of an 'Introduction' section for this 
vignette. The 'Introduction' should serve as an abstract to introduce the 
objective, models, unique functions, key points, etc that distinguish the 
package from other packages of similar type.

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to 
the user how to download the package from Bioconductor. The code should look 
something like the following and include `eval = FALSE`,

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("scClassify")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: Do not use direct slot access with `@`, instead accessor methods 
should be created and used. Lines 50 and 57. 

*scClassify*

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to 
the user how to download the package from Biocondcutor. The code should look 
something like the code for the previous vignette and include `eval = FALSE`.

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: The `cat()` commands in line 42 and 44 are not needed and are 
redundant.

- [ ] REQUIRED: Do not use direct slot access with `@`, instead accessor methods 
should be created and used. Line 77.

## Man pages

- [ ] REQUIRED: Add runnable examples to the following man pages which document 
exported objects:
        - predict_scClassifyJoint.Rd
        - scClassifyTrainModel.Rd

- [ ] REQUIRED: The data man pages need to include more source information and 
data structure information. See the following for more information, 
http://cran.fhcrc.org/doc/manuals/R-exts.html#Documenting-data-sets.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them.
See http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] REQUIRED: Avoid sapply(); use vapply() if possible. Found in files:
        - ensemble.R, line 90
        - KNNfunctions.R, line 172, 254, 218, and 404
        - predict_scClassify.R, line 537, 696, 707, and 753
        - sampleSizeCal.R, line 78, 176, and 185

- [ ] REQUIRED: Avoid use of direct slot access with `@` or `slot()`. Accessor 
methods should be created and utilized instead.

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 362 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line 
indents. There are 1923 lines that are not.

Best,
Kayla

**Comment by YingxinLin** [comment]
Dear Kayla,

Thanks for all your useful suggestions on the package! I have addressed most of them in all relevant contexts. Please let me know if there are any further issues I should work on.

Summary of the updates:

**General package development**
- docs/ folder is generated by pkgdown to create the package website. It has been moved to a new branch.

**Description**
- We have improved our description with the more detailed overview of the package. 
- LazyData is set as false now
- BugReports is added in the Description

**NEWS**
- NEWS.md is added 

**Vignettes**
- Installation and introduction section are added on top of both of the vignettes
- Table of contents are also added in both of the vignettes
- Several accessors methods for `scClassifyTrainModel` class are created to access the slots.
- `cat()` has been removed from vignettes

**Man pages**
- Examples for `predict_scClassifyJoint` are added, while `scClassifyTrainModel` now has been made as class constructor function that used strictly within the package.
- Data source information are added in the all three data objects.

**R codes**
- All `sapply()` have been replaced by `vapply()`
- Slots are changed to be accessed by either `slot()` or accessor functions.
- Formatting: the percentages of lines over 80 characters long and lines without multiples of 4 spaces have been significantly reduced. 

Best regards,
Yingxin

**Comment by Kayla-Morrell** [comment]
@YingxinLin - Thank you for making the necessary changes. Everything looks good and I'm more than happy to accpet the package.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/YingxinLin.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scClassify")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scClassify

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
