### ISSUE TITLE
LACE

### ISSUE THREAD

**Issue by DavideMaspero** [Bioconductor/Contributions#1450]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BIMIB-DISCo/LACE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
This package should interoperate with (accept as input / return as output) SingleCellExperiment.

**Comment by danro9685** [comment]
Dear @hpages, Dear @mtmorgan, 

we have updated the packages, fixing minor errors and including interface with SingleCellExperiment. 

Best, 
Daniele

**Comment by danro9685** [comment]
Dear @hpages, 

we removed all the errors and most of the warnings. Two warnings remaining only for the R CMD BiocCheck, but are needed. 

So please let us know if there is still anything we need to do. 

Best, 
Daniele

**Comment by hpages** [comment]
Thanks for your submission.

1. Please remove the `LACE/inst/docs` folder. The PDF documents in this folder don't belong to the _package source tree_. The vignette will be automatically created by `R CMD build` and will be placed in the `LACE/inst/doc` folder of the resulting source tarball (note that the folder will be `LACE/inst/doc`, not `LACE/inst/docs`). As for the reference manual, once the package will be in Bioconductor, it will get automatically generated and accessible on the package landing page (see for example https://bioconductor.org/packages/Biobase). These mechanisms guarantee that the PDF vignette and reference manual will always remain in sync with the package (right now, both are _stale_).

2. The ChangeLog has no place in the vignette (the purpose of the vignette is to demonstrate a typical workflow that can be performed with the package). The standard place for keeping track of the changes is the NEWS file, and you already have one, so why the duplication anyway.

3. The vignette is actually kind of minimalist. In particular it lacks an introduction that explains what the package is all about. Yes you have the Description field in the DESCRIPTION file but it's too technical/cryptic so the vignette really needs an introduction that takes the time to explain things in a way that is accessible to the non-specialist.

4. Don't call your data set "data". This is way to generic. Keep in mind that by submitting your package to Bioconductor, you're willing to be part of a vast ecosystem of 1800+ software packages. In a typical session, a Bioconductor user loads dozens of packages. Can you imagine what it would be like if all of the Bioconductor packages had their data set called "data"?

5. Using numeric matrices to store `0`s, `1`s, and `NA`s is not good design. Please use integer or logical matrices for that.

6. The man page for your data set (currently accessible with `?data` but hopefully this will change) needs to provide a lot more details about the nature of the data and how it was obtained (i.e. where it was downloaded from and how it was imported in R). Your package has value if people can use it on their data, not only on the data included in the package, so any details about how to prepare/obtain the input data will help.

7. This sentence:

    > D: Mutation data from multiple experiments for a list of driver
    > genes; it can be either a list with a data matrix per time
    > point or a SingleCellExperiment object with assays field
    > being one unique data matrix pooling all single cells
    > observed at each time point and rowData field being a vector
    > of labels, reporting the time point where each single cell
    > present in the assays field was sequenced (ordering of cells
    > in assays field and rowData field must be the same).

    in the man page for LACE is too long and too convoluted. Please break it down into smaller sentences. Make sure each sentence is clear and concise. Also it will help tremendously if you actually provide an example where `D` is a SingleCellExperiment object.

8. Does `LACE()` rely on functionalities specific to SingleCellExperiment objects or does it just use basic SummarizedExperiment functionalities? If the latter then requiring a SingleCellExperiment object is unnecessarily restrictive and it would make more sense to use a plain SummarizedExperiment object.

Thanks,
H.

**Comment by DavideMaspero** [comment]
Dear @hpages ,

thank you for your review of our package.

Following your instructions we performed the following changes.
 1. We removed the docs directory from the package.
 2. We removed the changelog section from the vignette.
 3. We improved and expanded the description in the vignette.
 4. We renamed "data" in "longitudinal_sc_variants"
 5. Thank you for your suggestion. We modifed data structures to integer.
 6. We improved the description of the data as follows:
	"dataset is a binary matrix that reports presence (1) or absence (0) of somatic single nucleotide variants for each single cell (rows). SNVs are called from SMARTseq2 fastq files of melanoma cancer cells sequencing.
	Please refer to the Methods Section of Ramazzotti, Daniele, et al. "Longitudinal cancer evolution from single cells." bioRxiv (2020)."
 7. We changed the highlighted man paragraph with the following sentece. 
	"D: Mutation data from multiple experiments for a list of driver genes. It can be either a list with a data matrix per time point or a SummarizedExperiment object. 
	In this latter, the object must contain two fields: assays and rowData. Assays stores one unique data matrix pooling all single cells observed at each time point and rowData stores a vector of labels reporting the time point when each single cell was sequenced.
	Ordering of cells in assays field and rowData field must be the same."
 8. Thank you for pointing this out, we now import and use only SummarizedExperiment.

We notice that the review label of the package now changed to ERROR. But looking at the report, it appears that the package correctly passed all checks and that the error is due to a problem of the Windows server that was used as a second build.

So, let us know if we are good with the review process of the packege.

Thanks,
DM

**Comment by hpages** [comment]
Hi,

The vignette error on Windows was on our side and should be fixed now. Sorry for that. I'll take a quick 2nd look at the package ASAP. Thanks for your patience.

H.

**Comment by danro9685** [comment]
Thanks @hpages!

**Comment by hpages** [comment]
Unfortunately we're having other MiKTeX issues with our Windows builder. Let's ignore them for now. Sorry for the inconvenience.

**Comment by hpages** [comment]
Thanks for the improvements.

You're still using numeric matrices (i.e. `storage.mode()` is `"double"`) to store 0s, 1s, and NAs (**item 5**).

There is some progress on **item 6** but you still need to provide a lot more details about this data set. In particular the user still doesn't know how the matrices were obtained. AFAICT the Methods Section of the Ramazzotti, Daniele, et al. paper only gives general considerations about Input data preprocessing but that doesn't say much about where this particular data set is coming from or how it was computed into its current form (i.e the list of matrices). Explain the labels on the rows and columns of the matrices. Also the language needs to be more precise e.g. "dataset is a binary matrix that reports presence (1) or absence (0) of ..." is not accurate (it's a **list** of matrices) and AFAIK they can contain NAs in addition to ones and zeroes, which also something that you need to mention/explain (what's their meaning).

**Item 7**: I still don't see an example of using LACE with a SummarizedExperiment object. The man page claims this is supported but without an actual example, that feature is currently untested. Furthermore, showing the user how to prepare a SummarizedExperiment object suitable for use in LACE would be very useful. Note that, by convention, a SummarizedExperiment object should have 1 column per sample and 1 row per feature, so I think you need to transpose your layout.

How about adding terms `SingleCell` and/or `SomaticMutation` to your biocViews field as suggested by `R CMD BiocCheck`?

Thanks,
H.

**Comment by DavideMaspero** [comment]
Thank @hpages 

We performed all requested changes.

Thanks,
DM.

**Comment by hpages** [comment]
Thanks for the improvements but **Item 5** is still not addressed despite your claim that all requested changes were performed:
```
> sapply(longitudinal_sc_variants, storage.mode)
 T1_before_treatment  T2_4_days_treatment T3_28_days_treatment 
            "double"             "double"             "double" 
T4_57_days_treatment 
            "double" 
```

One more thing: command `library("SummarizedExperiment")` in the vignette produces a full page of output that is not useful for the purpose of the vignette and distracting. Please don't display it.

Thanks,
H.

**Comment by danro9685** [comment]
Dear @hpages, 

just a clarification: longitudinal_sc_variants is an input to the package (inputed by the user) and we provide this dataset as example. We handle storage.mode integer inside the tool, but obviously the user can provide any input (even not integer) with her/his own data. Are you suggesting to change the data that we provide with the package? 

Re: vignette, sounds good. 

Best, 
Daniele

**Comment by hpages** [comment]
> Are you suggesting to change the data that we provide with the package?

Yes.

Of course your users can do all kinds of things. That's why showing good practices to them is important. Thanks!

H.

**Comment by danro9685** [comment]
Thank you for the clarification! We are implementing these changes and updating the package by today. 

Thanks, 
Daniele

**Comment by hpages** [comment]
Please ignore the ERROR, it's on our side (we've just updated R to final R 4.0.0 on the builders, and for some reason the SPB failed to reinstall some of the deps). I checked the package locally on my laptop and everything looks fine. Thanks for all the improvements to the package.

Cheers,
H.

**Comment by DavideMaspero** [comment]
Great! 
Thank you for supporting us.

Best regards,
DM

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/DavideMaspero.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("LACE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/LACE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
