### ISSUE TITLE
matter

### ISSUE THREAD

**Issue by kuwisdelu** [Bioconductor/Contributions#146]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kuwisdelu/matter

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
I guess I'm surprised that e.g. the ff package could not point at arbitrary file offsets and thus interface with custom file formats like the ones mentioned in the vignette. 

Btw, many of the generics are going to conflict with those in e.g. S4Vectors. We should probably push many of those up to BiocGenerics. Right now, they're using the default signature, which is not generally desirable.

**Comment by kuwisdelu** [comment]
Yes, ff and bigmemory are flexible in many ways, but not so much with custom file formats or datasets spanning multiple files, as far as I can tell, without conversion.

I do not currently get any obvious conflicts when loading matter with S4Vectors, but I am happy to switch to relying on whichever existing generics are advisable.

**Comment by lawremi** [comment]
Well, there's at least the `mean()` generic with IRanges.

**Comment by lshep** [comment]
Thank you for your submission. Please address the issues raised in the single package builder output. Once you have a clean (i.e no errors) build and check, a full review will begin.  Please also try and address any warnings that are occurring as many of these will need to be corrected before acceptance. 
Lori

**Comment by lawremi** [comment]
How easy would it be to generalize this, at least the API, to support URLs, not just file paths? I could imagine use cases where the data are stored remotely, through an API that supports random access, like BAM files and HTTP's support for file offsets. Or is your expectation that remote resources would be mounted via e.g. fuse drivers? I'm not suggesting implementation, just abstraction at the API level. An error would be thrown for anything that is not an ordinary path or file scheme.

**Comment by kuwisdelu** [comment]
"How easy would it be to generalize this, at least the API, to support URLs, not just file paths?"

Hi Michael,

It shouldn't be a problem on the API side in R, it would just mean the filepaths can be URLs. Files aren't touched at the R level. The implementation details would be on the C/C++ side in terms of portably opening files over HTTP. It's something I'd like to support in the future, but not right now.

I also want to generalize the API a little bit more to support (in the future) pointing at in-memory R matrices, so it would be possible to, say, cbind() an already-loaded R matrix with a matrix on disk.

**Comment by lshep** [comment]
@lawremi I would appreciate any further comments you had regarding generics and Rcode for this package.

**Comment by lawremi** [comment]
Another thing is that this package should add S3 methods for all external (non-primitive) S3 generics. That way, code that does not see the S4 generics can still use the abstraction. 

For example, for `t()` this would be:

```
t.matter_vec <- function(x) t(x) # we see the "t" S4 generic
```

**Comment by kuwisdelu** [comment]
I am happy to change the generics dependencies whenever BiocGenerics is updated. Just let me know.

**Comment by lawremi** [comment]
Some more things:

1. My point about the URLs was that you might want to rethink the name of the `filepaths()`accessor.
2. `rowSd()` (and others) are singular, while `rowMeans()` is plural. Would be good to make them consistent. But if you make them plural, they will conflict with the functions from the widely used matrixStats package. Ideally, both packages could coexist, but that would require sharing generic definitions. I think @hpages had suggested BiocGenerics depending on matrixStats. That would be one way to go. A lot of matrixStats would be better off in the base package though.
3. It seems that _DelayedArray_ from HDF5Array would want a similar API for setting the chunk size to use for incremental processing. I don't think it has one, but ideally they would end up with the same API.
4. The _matter_ data structure would be useful as a backend for _DelayedArray_. Can it be used as one already?
5. This could probably use the subscript infrastructure from S4Vectors, e.g., `normalizeSingleBracketSubscript()`.
6. Please do not use `.` in function names unless they are S3 methods.
7. There are some `switch()` statements on classes that could be replaced with dispatch.
8. Maybe I am reading this wrong, but it looks like `readMatrixElements()` always returns an ordinary R matrix. For some reason, it's called by `[()`except when `drop=NA`. Is the intent that the matrix is materialized by default by `[()`? I would have thought only `as.matrix()` would do that. You could support `drop=TRUE` with _matter_vec_, right? The behavior should at least be better documented.
9. What does `drop.matrix()` do differently from `drop()`? I guess it has a more generic (R) implementation, but isn't the data always just an R matrix?
10. You should not use `stop()` in validity functions. Rather, all error messages should be concatenated into a returned character vector.

This is not comprehensive. I just stopped arbitrarily at 10 points.

**Comment by lshep** [comment]
Hello, 
Thank you for making the changes recommended thus far. Some additional comments to address: 

**General**
- [ ] The package takes a long time to build   (>5min) . Please try to cut this time down.  One suggestion would be to save the results of the pca analysis in the vignette. You could show the code for this section but not run it and load the presaved results in the background. (essentially saving the 2-4 min as stated) 

- [ ] Functions names should not contain `.`  unless they are S3 methods. Please update the function names accordingly (i.e `all.indicies`, `combined.colnames` etc)

**Vignette** 
- [ ] Add section for downloading from Bioconductor with biocLite() 
```
source("https://bioconductor.org/biocLite.R")
biocLite("matter")
```
- [ ] There is a note in the build report about accessing with the `@`  referring to `x@data` . Since this is your own object, would it not be beneficial to have an accessor method for the data slot? 

**Description** 
 - [ ] Do the suggested biocViews from the build report apply? If so add to description. 



Cheers
Lori

**Comment by kuwisdelu** [comment]
Thank you for the review.

I have addressed the above items in the last commits.

Some notes from my end:

-I have switched to using saved results to cut down build time. If build time is a concern, I suggest adding this to the package guidelines. Requirements for R CMD build do not currently give time constraints, only size constraints, while time constraints are instead given only for R CMD check. I originally wrote the vignette with these specific requirements in mind.

-I have changed internal function names to avoid dots in non-S3 methods, even though none of these functions are exported to the user. If this is an official requirement, I suggest adding it to the package guidelines, and to BiocCheck, which would be helpful in identifying them.

-The suggested biocViews do not apply (in my opinion), so I did not add them. Although matter is designed to be used by Cardinal downstream for MS imaging analysis, the package itself does not provide functionality specific to mass spectrometry or MS imaging analysis.

Thanks,
Kylie

**Comment by lshep** [comment]
Thank you for making these changes.  I will recommend be accepted. You should get svn instructions via email in the next couple of days. 

Thank you also for your notes/input. I will discuss with the rest of the team and update accordingly if applicable.

**Comment by kuwisdelu** [comment]
Thank you!

My svn username is k.bemis.
