### ISSUE TITLE
geneplast.data.string.v110

### ISSUE THREAD

**Issue by leofields** [Bioconductor/Contributions#1474]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/leofields/geneplast.data.string.v110

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
so are the three packages all supporting a (to be submitted) software package?

If so, maybe a better design is to use ExperimentHub or AnnotationHub to serve the various data sets, and a single 'geneplast.data' annotation package to provide an interface to the different versions? See [1][] for an introduction to creating AnnotationHub packages.

[1]: https://bioconductor.org/packages/devel/bioc/vignettes/AnnotationHub/inst/doc/CreateAnAnnotationPackage.html

**Comment by LiNk-NY** [comment]
Hi Leonardo, @leofields 
Please respond to Martin's questions. 
Thank you.

**Comment by leofields** [comment]
Dear Martin, @mtmorgan 

Thank you for your comments and suggestions.

> so are the three packages all supporting a (to be submitted) software package?

Actually, all three packages provide data supporting the Geneplast software package (https://www.bioconductor.org/packages/release/bioc/html/geneplast.html), allowing the user to run Geneplast's analyses with different sources of orthology information.

> 
> If so, maybe a better design is to use ExperimentHub or AnnotationHub to serve the various data sets, and a single 'geneplast.data' annotation package to provide an interface to the different versions? See [1](https://bioconductor.org/packages/devel/bioc/vignettes/AnnotationHub/inst/doc/CreateAnAnnotationPackage.html) for an introduction to creating AnnotationHub packages.

We didn't realize this possibility. We agree with it, and we'll proceed that way. In that case, you can close all three issues.


We look forward to contributing to Bioc and our community.

Sincerely,

Leonardo RS Campos

**Comment by mtmorgan** [comment]
OK We'll close these issues.
