### ISSUE TITLE
MultiBaC

### ISSUE THREAD

**Issue by ManuelUgidos** [Bioconductor/Contributions#1481]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ConesaLab/MultiBaC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ManuelUgidos** [comment]
I have already created an SSH Key. What am I supposed to do with it?

**Comment by ManuelUgidos** [comment]
Dear reviewers,
We would like to include our R package in our next publications. Is there any kind of link for reviewers even thought the package is in devel status?
Thanks

**Comment by lshep** [comment]
I don't know what feedback @hpages  will provide and your willingness to adapt the package to his review.  As far as links, once accepted into Bioconductor the package could be linked with the shorturl link:  https://bioconductor.org/packages/MultiBaC   but it will not be active until officially accepted through the review process.

**Comment by hpages** [comment]
Hi @ManuelUgidos ,

Thanks for submitting MultiBaC. The package is in good shape and has a nice vignette. Only a few minor cosmetic issues:

1. The `doc/` folder should be a subfolder of the `inst/` folder. See section "1.1 Package structure" of the "Writing R Extensions" manual. In your case, the `doc/` folder contains `MultiBaC.html`, `MultiBaC.R`, and `MultiBaC.Rmd`. Note that these files will be automatically generated by `R CMD build` and included in the resulting source tarball so they must not be included in the source tree. Please remove them.
    In other words, you need a `doc/` folder only if you want to include a **static** document in your package (vignettes are **dynamic** documents). Since you don't have any static document (and most packages don't have and don't need one), you don't even need the `inst/doc/` folder.

2. Also please remove `MultiBaC.R` and `MultiBaC.html` from the `vignettes/` folder. Like the files you have in `doc/`, these are not needed and don't belong to the package source tree.

3. The code in the vignette produces a dozen of warnings e.g.
    ```
    ## Warning: 'info.txtC = NULL' argument value is deprecated; use 'info.txtC =
    ## 'none'' instead.
    ```
    Note that these warnings are displayed in the HTML version of the vignette.
    Also some man pages have examples that produce the same warnings e.g.
    ```
    > example(batchCorrection)
    ...
    There were 12 warnings (use warnings() to see them)
    > warnings()
    Warning messages:
    1: 'info.txtC = NULL' argument value is deprecated; use 'info.txtC = 'none'' instead.
    ...
    12: 'fig.pdfC = NULL' argument value is deprecated; use 'fig.pdfC = 'none'' instead.
    ```

4. Why do you have man pages for functions that are not available to the user? For example the code in the man page for `getData` fails with:
    ```
    > omicData <- getData (my_mbac$ListOfBatches)
    Error in getData(my_mbac$ListOfBatches) : 
      could not find function "getData"
    ```
    This will be the most confusing for your users, especially given the fact that this man page will be included in the reference manual of the package (we will display a link to the reference manual of the package on its landing page, see for example https://bioconductor.org/packages/Biobase).
    You basically have 2 options to address this:
    - (1) Don't document non exported functions.
    - (2) Exclude the man page from the reference manual. This is done by adding the `\keyword{internal}` line to the man page, usually at the bottom. Also you'll need to make sure that the code in the Examples section is valid and you shouldn't put it inside a `\dontrun` directive.

Don't hesitate to ask on the bioc-devel mailing list if you have concerns or questions about this.

Thanks

**Comment by ManuelUgidos** [comment]
Hi @hpages,

Thanks for your feedback!. I made the changes and I think I addressed all your points:

1. doc/ folder has been removed.
2. Both files have been removed.
3. All the warnings I could see in the code were because of the function opls and its arguments. That function returns two warnings and, as it is invoked 6 times running the vignette, at the end it returns 12 warnings. This issue has been addressed modifying the arguments. Please, let me know if there are other warnings.
4. man pages for non-exported functions have been removed.

I hope that your requests have been met successfully.

**Comment by ManuelUgidos** [comment]
Hi @hpages,

I have modified one argument in plot functions and I made an error but now is corrected. Please find my previous message bellow.


Thanks for your feedback!. I made the changes and I think I addressed all your points:

doc/ folder has been removed.
Both files have been removed.
All the warnings I could see in the code were because of the function opls and its arguments. That function returns two warnings and, as it is invoked 6 times running the vignette, at the end it returns 12 warnings. This issue has been addressed modifying the arguments. Please, let me know if there are other warnings.
man pages for non-exported functions have been removed.
I hope that your requests have been met successfully.

**Comment by ManuelUgidos** [comment]
Hi,

I already did a new push with corrected issues 28 days ago. Is there anything else I can/must do to finish the submission of the package?

Thanks in advance.

**Comment by hpages** [comment]
Hi @ManuelUgidos ,

Thanks for making the changes. Package is now ready for inclusion in Bioconductor.

Cheers,
H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ManuelUgidos.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MultiBaC")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MultiBaC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
