### ISSUE TITLE
MAST

### ISSUE THREAD

**Issue by amcdavid** [Bioconductor/Contributions#149]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RGLab/MAST

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Hi,
Please clean up these issues on the single package builder:
* Checking man pages...
    * WARNING: Add non-empty \value sections to the following man
      pages:
      combined_residuals_hook.Rd, continuous_residuals_hook.Rd,
      deviance_residuals_hook.Rd, discrete_residuals_hook.Rd,
      filterLowExpressedGenes.Rd, GLMlike-class.Rd, LMERlike-class.Rd,
      LMlike-class.Rd, LRT.Rd, myBiplot.Rd, plotSCAConcordance.Rd,
      print.summaryZlmFit.Rd, rstandard.bayesglm.Rd, score_2_hook.Rd,
      score_hook.Rd, shalek_weights.Rd, stat_ell.Rd,
      summary-ZlmFit-method.Rd, xform.Rd, ZlmFit-class.Rd

* Checking exported objects have runnable examples...
    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples. The following pages do not:
      calcZ.Rd, cData.Rd, coef.Rd, combined_residuals_hook.Rd,
  computeEtFromCt.Rd, condmean.Rd, condSd.Rd,
  continuous_residuals_hook.Rd, deviance_residuals_hook.Rd,
  discrete_residuals_hook.Rd, expavg.Rd, filterLowExpressedGenes.Rd,
  freq.Rd, getConcordance.Rd, getrc.Rd, getwellKey.Rd, hushWarning.Rd,
  impute.Rd, invlogit.Rd, logmean.Rd, LRT.Rd, lrTest.Rd,
  melt.SingleCellAssay.Rd, numexp.Rd, outlierDetection.Rd,
  read.fluidigm.Rd, score_2_hook.Rd, score_hook.Rd, se.coef.Rd,
  shalek_weights.Rd, stat_ell.Rd, subset.Rd, summary.Rd,
  thresholdSCRNACountMatrix.Rd, todt.Rd, vcov.Rd, waldTest.Rd

* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer should subscribe to the bioc-devel mailing
      list. Subscribe here:
      https://stat.ethz.ch/mailman/listinfo/bioc-devel

Valerie

**Comment by amcdavid** [comment]
Hi @vobencha , last night I pushed an updated version to address issues the builder reported, but still haven't gotten a report back.  Is it possible the builder is "stuck" somehow?

**Comment by vobencha** [comment]
I've checked with Lori ... she'll probably start a new build tomorrow.
Valerie

**Comment by lshep** [comment]
Unfortunately we can't get a full build report to post as something is going wrong in the unit tests and it stalls out. I wish I could be more helpful but we can't seem to track it down as it doesn't fail in the normal way.  I've attached the testthat.Rout that is produced. 

[testthat.Rout.txt](https://github.com/Bioconductor/Contributions/files/501211/testthat.Rout.txt)

**Comment by amcdavid** [comment]
I believe it relates to trying to start a PSOCK cluster in a unit test, since it only began when I changed from `fork`ing to `PSOCK` in order to let the the package build on windows.  I found this (fun little nugget)[http://stackoverflow.com/questions/12410694/rbundler-build-error-cannot-open-file-startup-rs-no-such-file-or-directory] which makes me think it could be an upstream bug with either parallel or R CMD check.  I'm just going to only use a single core for the unit test.

**Comment by vobencha** [comment]
Hi,
Please tidy up these issues from the single package builder:

* Checking R Version dependency...
    * WARNING: Update R version dependency from 2.10 to 3.3.

* Checking DESCRIPTION/NAMESPACE consistency...
    * WARNING: Import parallel, reshape2 in NAMESPACE as well as
      DESCRIPTION.

Valerie

**Comment by amcdavid** [comment]
Hi Valerie,
For the second warning, can you explain further?  I access functions in those packages with their fully qualified names (ie, `reshape2::`) per what I understand best practices to be (when feasible).  Is there a downside to using the fully qualified names?  Or am I misunderstanding the warning?

**Comment by vobencha** [comment]
There needs to be consistency between packages listed in DESCRIPTION and NAMESPACE. Both parallel and reshape2 are in 'imports' in DESCRIPTION but they aren't imported in NAMESPACE. Import them (or parts of them) in NAMESPACE and we'll be set.

Valerie

**Comment by amcdavid** [comment]
Ok, I will add an `importFrom` statement for those packages so that we may mark this off the list. I _am_ unclear as to the rationale for this requirement, and it may be worth inquiring on bioc-developers, with your permission.  [Per Hadley](http://r-pkgs.had.co.nz/namespace.html):

> It’s common for packages to be listed in Imports in DESCRIPTION, but not in NAMESPACE. In fact, this is what I recommend: list the package in DESCRIPTION so that it’s installed, then always refer to it explicitly with pkg::fun(). Unless there is a strong reason not to, it’s better to be explicit. It’s a little more work to write, but a lot easier to read when you come back to the code in the future.

Per [R extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Specifying-imports-and-exports):

> If a package only needs a few objects from another package it can use a fully qualified variable reference in the code instead of a formal import. A fully qualified reference to the function f in package foo is of the form foo::f.

**Comment by vobencha** [comment]
Sure, posting on bioc-devel is fine with me. There have been different trains of thought on this and it would be an interesting conversation to have.

**Comment by vobencha** [comment]
Did you mean to bump the version on that last commit? Other than that we are ready to go ...

**Comment by vobencha** [comment]
@amcdavid we need to get this approved and are almost there. Did you mean to bump the version in commit https://github.com/Bioconductor/Contributions/issues/149#issuecomment-251822686? The version bump triggers the builder ... we want the issue have record of the most current build.  As discussed on the mailing list it's fine to leave your package as it was originally and not explicitly import in the NAMESPACE when you use ::.
Valerie

**Comment by vobencha** [comment]
Thanks for making the changes - the package is accepted. You should get an email in the next week with svn info and next steps.

Valerie
