### ISSUE TITLE
GSEAmining

### ISSUE THREAD

**Issue by oriolarques** [Bioconductor/Contributions#1496]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/oriolarques/GSEAmining

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please update your vignette (and Suggests: of the DESCRIPTION file) to indicate how a user of Bioconductor might integrate your software into a typical work flow, e.g., from the results of differential expression analysis using DESeq2 or limma / edgeR.

**Comment by oriolarques** [comment]
I have made modifications to adress the errors from the build report and added Version: 0.99.1 to the last commit. Do I need to do anything else to trigger a new build?

**Comment by lshep** [comment]
Before the version bump you will need to ensure the webhook is activated.  Instructions found [here](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook)

**Comment by oriolarques** [comment]
>  Please update your vignette (and Suggests: of the DESCRIPTION file) to indicate how a user of Bioconductor might integrate your software into a typical work flow, e.g., from the results of differential expression analysis using DESeq2 or limma / edgeR

Related to this point, in the section 3 of the vignette (3. Input data format: gm_filter) it is explained that the natural input of this package is the output of the GSEA function of the Bioconductor package **clusterProfiler**. However, it is also explained that outputs from other programs or functions could be also used if the resulting data frame contains the required variables.  

**This section could be modified if you believe it is not sufficently accurate.** 

Here I enclose the part of the vignette that I mentioned: 

> By default GSEAmining is designed to accept the resuls of the GSEA function
> from the [clusterProfiler](https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html) 
> package. For more information about this function click 
> [here](https://yulab-smu.github.io/clusterProfiler-book/chapter7.html). However,
> it is *not mandatory to use this package*.
> 
> Data should be in a data.frame with, **at least** three columns labelled as 
> follows:
> - **ID**: The name of the gene set.
> - **NES**: Normalized Enrichment Score of the gene set.
> - **core_enrichment**: Genes that appear in the leading edge subset of the gene
> set.
> 
> ```{r}
> # Structure of the data included in the package
> data("genesets_sel", package = 'GSEAmining')
> tibble::glimpse(genesets_sel)
> ```

**Comment by mtmorgan** [comment]
Thanks for your comment. My concern with the _mention_ in the vignette without actually demonstrating the functionality (hence with clusterProfiler in the Suggests: field) is that the functionality is or will become non-functional. By including an explicit demonstration you both help the user by showing them the necessary steps and help yourself to maintain a package that functions as advertised.

**Comment by oriolarques** [comment]
@mtmorgan The vignette has been updated with a demonstration on how to get the input files using clusterProfiler as well as including the package in the Suggests: field. I hope it is complete enough so the users find it easy to link both packages.

**Comment by lshep** [comment]
Thank you for the update.  I will do an in depth review of the package shortly.

**Comment by lshep** [comment]
I'm very sorry in the delayed review. Reviews normally happen within two weeks and I fell behind. I think this looks like a well written package and thank you for clarifying the connection with the ClusterProfile package.  Only a few minor comments 

**build report**

- [ ] We highly suggest unti tests for testing functionality of the package.

**README**

- [ ] Include Bioconductor installation instructions
 
**DESCRIPTION**

- [ ] Use Authors@R not Author/Maintainer field

- [ ] remove `LazyData:true` rarely found useful and can acutally slow
  installation of a package

**vignette**

- [ ] I suggest changing the name from `GSEAmining_vignette` to `GSEAmining`.
  Its much more intuitive for a user to use the name of the package in the
  vignette call than trying to search for the name of the vignette `vignette('GSEAmining')`

- [ ] Include Bioconductor installation instructions. 


When ready please comment back here with what has been updated and to request a re-review. 
 please don't forget to do a version bump to trigger a new build.  

cheers,
L

**Comment by oriolarques** [comment]
Hi @lshep,
Thank you very much for your comments and the positive feedback (I understand that under the current circumstances things are not easy). I have just summited a new version following your advice, so the new version include the changes listed below:

- Unit tests have been included for different functions in the package.
- Bioconductor installation instructions have been included in the README and the Vignette files.
- In the DESCRIPTION the Author information is updated as you suggested.
- The name of the Vignette file has been changed following your suggestion.

The only comment I did not manage to include is the removal of LazyData. The problem is the following, I included it in the DESCRIPTION file so the example data is available to run the examples. I tried to removed it and checked the package but that caused an error when evaluating the examples (failing to load the data). I hope you can give any suggestions regarding this issue if you consider it is necessary to remove it from the package.

Looking forward to your comments.

Bests,

Oriol

**Comment by oriolarques** [comment]
Hi @lshep, 
I don't know if you have had time to review the modifications I included last week. If there is any problem or additional step I have to perform in order for the review to go ahead do not hesitate in writing to me.

Bests,

Oriol

**Comment by lshep** [comment]
I'll review the modifications this week and get back to you soon.

**Comment by lshep** [comment]
I apologize for the delay.  Everything looks good.  Welcome to Bioconductor.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/oriolarques.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GSEAmining")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GSEAmining

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
