### ISSUE TITLE
hummingbird

### ISSUE THREAD

**Issue by eleniadam** [Bioconductor/Contributions#1498]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/eleniadam/hummingbird

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please update your package to interoperate with (produce and consume) [standard Bioconductor classes and methods][1], in particular [GenomicRanges][2].

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/
[2]: https://bioconductor.org/packages/GenomicRanges

**Comment by eleniadam** [comment]
Hello,

@mtmorgan Thank you for your comment, from my understanding, you would like me to use the GenomicRanges for the input/output data format? 
If yes, I would like to leave the flexibility for the users, I think it is better because instead of interoperating with GenomicRanges, the current version can work with any alignment package output. Is that ok?

@nturaga I would like to ask regarding the ERROR "Maintainer must subscribe to the bioc-devel mailing list.". I have tried multiple times to subscribe to the bioc-devel list by filling out the web form but I have never received a confirmation email (I have checked the Spam folder as well). Is there another way of subscribing to the list?

Thank you,
Eleni

**Comment by mtmorgan** [comment]
From looking very briefly at your vignettte, it seems that input to the `hummingbirdEM` function is a group of objects that must be precisely aligned, and that have precise meaning. In addition, it seems that there is important information that is _not_ included, e.g., the chromosome on which the CpG islands have been identified, and the identifiers of the sample names of the assays that have been performed. There are also ambiguities in both the input and the output, for instance whether the start and end coordinates in the output describe 0- or 1-based, 'half-open' or 'closed' intervals.

Avoid these problems by using more structured data. I understand the inputs to be a vector of positions

```
pos <- m_pos[,1]
```

and a list of matrices

```
assays <- list(
    normM = m_normM, 
    normUM = m_normUM,
    abnormM = m_abnormM,
    abnormUM = m_abnormUM
)
```

One can provide this data in a structured and coordinated fashion as a 'ranged' SummarizedExperiment

```
se <- SummarizedExperiment(assays, rowRanges = GPos("chr1", pos))
```

This is a convenient-to-manipulate object with many of the implicit constraints on the inputs (e.g., that the matrices of the assays are all of the same dimension) and other assumptions (e.g., that the positions are on the same chromosome) made explicit

```
> se
class: RangedSummarizedExperiment
dim: 4746 4
metadata(0):
assays(4): normM normUM abnormM abnormUM
rownames: NULL
rowData names(0):
colnames: NULL
colData names(0):
> rowRanges(se)
UnstitchedGPos object with 4746 positions and 0 metadata columns:
         seqnames       pos strand
            <Rle> <integer>  <Rle>
     [1]     chr1       271      *
     [2]     chr1       331      *
     [3]     chr1       363      *
     [4]     chr1       386      *
     [5]     chr1       418      *
     ...      ...       ...    ...
  [4742]     chr1    399795      *
  [4743]     chr1    399802      *
  [4744]     chr1    399833      *
  [4745]     chr1    399864      *
  [4746]     chr1    399987      *
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
> head(assays(se)[["normM"]])
     [,1] [,2] [,3] [,4]
[1,]    8    7   12   10
[2,]    4    4    2    4
[3,]    0    1    0    4
[4,]    2    2    0    2
[5,]    1    1    1    1
[6,]    8    0    0    7
```
The data can be easily manipulated in a coordinated fashion, e.g., selecting only some samples `se[,1:2]`, and can be made more rich, e.g., with annotations on the samples and row ranges. 

It appears the return value from `hummingbirdEM()` should be a `GRanges()` object; I cannot tell in detail what all columns are, but I believe something like

```
> gr <- GRanges("chr1", IRanges(hmmbird1$obs[,3], hmmbird1$obs[,4]), distance = hmmbird1$obs[,1], norm = hmmbird1$normAbnorm[,1], abnorm = hmmbird1$normAbnorm[,2])
> gr
GRanges object with 3296 ranges and 3 metadata columns:
         seqnames        ranges strand |  distance      norm    abnorm
            <Rle>     <IRanges>  <Rle> | <integer> <numeric> <numeric>
     [1]     chr1       271-310      * |         1  0.672414  0.711864
     [2]     chr1       311-350      * |         1  0.258065  0.413793
     [3]     chr1       351-390      * |         0  0.156250  0.104348
     [4]     chr1       391-430      * |         0  0.122449  0.126984
     [5]     chr1       431-470      * |         0  0.333333  0.421875
     ...      ...           ...    ... .       ...       ...       ...
  [3292]     chr1 399671-399710      * |         0  0.250000  0.294118
  [3293]     chr1 399751-399790      * |         0  0.617021  0.555556
  [3294]     chr1 399791-399830      * |         0  0.700000  0.743902
  [3295]     chr1 399831-399870      * |         0  0.448980  0.416667
  [3296]     chr1 399951-399990      * |         0  0.108696  0.268293
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
```
is appropriate. Note that the ranges are closed, i.e., start and end coordinate are _included_ in the range. Again this can be very convenient to manipulate, e.g., select just the ranges with particular values of `distance`, `gr[gr$distance == 1]` or overlapping particular genomic 'regions of interest', `subsetByOverlaps(gr, GRanges("chr1:100000-200000"))`

The robustness and interoperability of these data structures mean that `hummingbirdEM()` should accept as input a SummarizedExperiment, and return as output a GenomicRanges. It would be appropriate to have 'data preparation' and 'data interpretation' sections of your vignette where the steps above are illustrated.

**Comment by nturaga** [comment]
@eleniadam To check if you are subscribed to the mailing list, please check https://stat.ethz.ch/mailman/listinfo/bioc-devel. You should be able to see the subscribers list if you are on it.

I will review your package once you have made the changes Martin described. You'll need to bump the version on your package so you get a build report. The build report will inform you if your package is ready for review. There should be no ERROR messages before the review.

**Comment by eleniadam** [comment]
@mtmorgan , Thank you very much for your detailed explanation. I will try to make the changes in the package.

@nturaga ,
- I checked and I am definitely not in the bioc-devel list. I cannot subscribe through the webpage and I am not sure why that is (I have tried many times). Is there another way to subscribe to the list? 
- Also, in the macOS report it states: "ERROR: R installation problem: File /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libgfortran.3.dylib not found!" 
Is this a  problem in the macOS system or in my package?

**Comment by hpages** [comment]
No problem. Thanks for making that change. Not sure why your last version bump (from more than 3h ago) didn't trigger a new build yet. @lshep ?

**Comment by lshep** [comment]
Not quite sure. All the other issues are building properly and picking up version bumps.  For now I'll kick off one manually.

**Comment by eleniadam** [comment]
@lshep Thank you, a similar issue had occurred some days ago as well. Specifically on May 28th, a valid push was received and the build report was given on June 2nd.

**Comment by lshep** [comment]
I would try deleting and setting up the webhook again.  Also are you doing the version bump directly on the master branch?  We don't recognize version bumps from merged versions.   Please let us know when you do the next version bump so we can better try and monitor the issue.  Sorry for the inconvenience.

**Comment by eleniadam** [comment]
@mtmorgan My code is written in C language and the hummingbirdEM function is a C function. 
I am not sure how to read as input a SummarizedExperiment object. One idea is to create an R function which accepts as input the SummarizedExperiment object, modifies it in simple matrices and then calls the C hummingbirdEM function in it and creates the GRanges output. Would that be acceptable..?

**Comment by mtmorgan** [comment]
The comment above created an object `se`. I would expect `hummingbirdSE(se, <maybe other arguments>)` to work, I guess by, in the package code, checking that `se` contains the necessary components, then extracting those components and invoking the C code that you have implemented. Likewise 'on the way out', translating any simple objects returned by your C code to a corresponding Bioconductor representation. I would not expect that your C code would access the components of a SummarizedExperiment object directly.

I think this is consistent with what you describe, but actually I think that you should not add to the public interface, but rather modify `hummingbirdEM()` to accept a SummarizedExperiment, and implement the current `hummingbirdEM()` as a purely internal function.

**Comment by eleniadam** [comment]
@lshep I am doing the version bump directly on the master branch. I just did another version bump.

**Comment by eleniadam** [comment]
@mtmorgan Thank you very much for the clarification.

**Comment by eleniadam** [comment]
@nturaga I have made the changes that Martin described. There is only one ERROR message and it is related to the mac builder issue.  Is my package ready for review now, given that there are no actual errors?

**Comment by eleniadam** [comment]
@nturaga Hello, I would like to ask if everything is ok with my package? Is it under review? And also, is the Mac builder error fixed..? (which is the only ERROR in the report) Thank you,

**Comment by nturaga** [comment]
# hummingbird review

## DESCRIPTION 

* The **Description** should be similar to the abstract of a paper. Please
  elaborate the section.

## NAMESPACE

* ok

## R

* Take a look at
  http://bioconductor.org/developers/how-to/coding-style/ and format
  your code. Line wrap your code to 80 chars limit.
  
* There is minimal R code in the package to evaluate. I see that the
  input and output have been modified to take in summarized experiment
  objects. This is good.
  
## man

* ok

## vignettes

* Suppress package loading messages.

* Add more details to the vignette.

**Comment by eleniadam** [comment]
@nturaga I have addressed the comments of the review and changed the package according to the review. The only error in the report is the Mac builder error (as before).  Is the package ready now?

**Comment by nturaga** [comment]
Hi, Please issue a new build so that we can see another build report.

**Comment by eleniadam** [comment]
@nturaga Hi, I issued the new build.

**Comment by eleniadam** [comment]
@mtmorgan @nturaga Hello, Is everything ok with the package..? Thank you, Eleni

**Comment by nturaga** [comment]
I'm looking into why your package doesn't build cleanly on both the builders we have....

**Comment by eleniadam** [comment]
Hi @nturaga Thank you, please let me know if I can be of help. Is it just dependency issues?

**Comment by nturaga** [comment]
Your package is fine. The error and warning labels will probably persist until we fix the issue on our build machine.

**Comment by eleniadam** [comment]
@nturaga Thank you! Will the current issue causing the error labels prevent the package from being added to the 'Devel' branch of Bioconductor now and be available for download?

**Comment by lshep** [comment]
No the current issue should not prevent the addition to devel branch.  Once the package is added to the Bioconductor nightly manifest it will build on the nightly builder.  As long as there are no error's there (which we don't anticipate) it will be added and available for download.

**Comment by eleniadam** [comment]
@lshep Ok, thank you!

**Comment by eleniadam** [comment]
Hello, Has the package been added successfully to the Bioconductor nightly build ? Thank you, Eleni

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/eleniadam.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("hummingbird")`. The package 'landing page' will be created at

https://bioconductor.org/packages/hummingbird

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
