### ISSUE TITLE
yamss (metabolomics)

### ISSUE THREAD

**Issue by lmyint** [Bioconductor/Contributions#150]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hansenlab/yamss

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
Looks like all of the functionality is wrapped up in the `bakedpi()` function (what does that name even mean?), while it would be nice to have each step of the pipeline exposed as its own function. That would mean defining a formal data structure for holding the raw data. The xcms package defines some that might be useful.

I noticed that `getFileNames` begins with `get` but the other accessors don't. Probably should drop the `get`.

**Comment by lmyint** [comment]
Hi Michael,
We should have made clear in the man pages that `bakedpi` stands for bivariate approximate kernel density estimation for peak identification." We debated exporting the individual functions to avoid users having to learn too much about internal workings, but we'll revisit this. I think you're right about `getFileNames`. Thanks for the speedy look!

**Comment by kasperdanielhansen** [comment]
This post (partly) addresses @lawremi comments on re-using XCMS as well as exposing each step of the pipeline.

We have looked (again) at the internals of XCMS.  This package (also) has a design where raw data is mixed up with processed data, so it is not so easy to reuse.  For example `xcmsSet`, which is the first class a user instantiates, does peak detection which is a data processing step we don't use at all.

Also, XCMS processes each sample separately which allows them to loop over samples on disk, only accessing one sample at a time.  This allows `xcmsSet` to simply have a pointer to a set of files on disk, which is obviously great from a resource point of view.  Our method processes all samples simultaneously, we do that by reading all the data into a `data.table` which allows us to do fast two-dimensional subsetting, which XCMS doesn't need to do.

Conclusion: the only thing we share with XCMS is having a collection of filenames. So there is not really anything to re-use at the start of the process.

But @lawremi point about `bakedpi()` being a monolithic entities which takes a set of files and returns a heavily processed object, is a point well taken.  Some of the steps inside  `bakedpi()` is uninteresting to the user, but it would be good to chop the process up a little bit. We'll do that, probably by exposing the return object of `readRawDataAsDataTable()` and wrapping it in a function, still designing the details of this.  Hopefully we'll have a redesign tomorrow.

**Comment by lmyint** [comment]
Note that the error on Windows is due to `mzR` being unavailable on Windows. We don't have any compiled code, so we're pretty sure that our code should work on all platforms.

**Comment by kasperdanielhansen** [comment]
Substantial changes:

-  Split the monolithic `bakedpi` function into two parts and defined a class for storing raw data.  We are *not* re-using XCMS classes for reasons outlined in message above.
 - Documentation fixes and code cleanup.
 - Included colData slots into the data classes.

**Comment by kasperdanielhansen** [comment]
In our latest update we have split the analytical pipeline into two: `bakedpi()` and `slicepi()`.  So in total, based on @lawremi we have split our original monolitic pipeline into
  - a reading step
  - a density estimation step
  - a density thresholding step

This completes our revisions based on @lawremi comments. We are not planning on any more revisions, until review.

The package fails on Windows because a dependency - `mzR` - is not available.

**Comment by kasperdanielhansen** [comment]
Well `mzR` now builds (but errors on CHECK) on Windows, but that has not made it available on the single package builder.  Guess we will have to wait longer for this.

**Comment by kasperdanielhansen** [comment]
Ok, so now `mzR` (a package dependency) is fixed, and there are no problems.

**Comment by kasperdanielhansen** [comment]
It would be great to get some movement on this, considering the deadline is the 12th, and we have been waiting for 11d.  Of course I understand there is a lot of packages to look at.

**Comment by lmyint** [comment]
Hi @LiNk-NY 
In your recent reply on Bioc-devel to another package author, you had said that you would get to looking at all packages in good time before the 12th, but we haven't heard from you yet.

**Comment by LiNk-NY** [comment]
Hi @lmyint and @kasperdanielhansen, 
Thank you for submitting to Bioconductor!

My apologies for the delay. There are a few packages ahead of you in the queue. 
I took a brief look at it and here is some feedback. 

---

#### DESCRIPTION
* It seems to me like `limma` should be in the `Imports` field as you only use a few functions from the package.

#### Unit Tests
* Please add some unit tests at least to your main functions. 

#### Methods
* Many functions that you're writing include `stopifnot(myclass)`. Perhaps you intend to write methods that dispatch on your class.

#### Grammar
* Nesting of lapply, sapply - It is not good for readability, and may be avoidable. Perhaps you can pass additional arguments to the first lapply call (i.e., lapply(seq_along(object), function (i, newObj) { ... }, newObj = object))
* Try to avoid call sequences such as rbind > lapply > cbind > rbind > lapply > cbind. 
* Use of `1:length(number)` is not robust when the `number` variable is 0L. Try using seq_len(number) instead. 
* Minor: Avoid using `ifelse` for scalar evaluation, just use if ( ) else ( )
* You shouldn't be using `@` to access slots in your class. Please use accessors and replacers for this. 
* Avoid using argument names that are functions such as `by`. 

#### Vignettes 
* Looking good. 

#### Documentation
* Overall, looks helpful. 
* You include an example with `\dontrun`. It looks runnable. 

Thank you for your patience. 

Regards, 
Marcel

**Comment by lmyint** [comment]
Thank you for taking a look @LiNk-NY. We have addressed the issues regarding the import of `limma` and accessing slots with `@`. We're working on the others as well. Is it ok if we come back with changes by Monday?

**Comment by kasperdanielhansen** [comment]
I looked closer at the release schedule: clearly it has to be done by
Friday at the very latest.

All of the comments involve improving our own code.  None of the issues
affects the user experience nor the interoperability with other packages.
We do agree with most of these suggestions, and will incorporate them.

**Comment by kasperdanielhansen** [comment]
We have now addressed the issues in the review report.  Here is our detailed response

First we quote the review with numbers added for reference.

> DESCRIPTION
> 
> - 1. It seems to me like limma should be in the Imports field as you only use a few functions from the package.
> 
> Unit Tests
> 
> - 2. Please add some unit tests at least to your main functions.
> 
> Methods
> 
> - 3. Many functions that you're writing include stopifnot(myclass). Perhaps you intend to write methods that dispatch on your class.
> 
> Grammar
> 
> - 4. Nesting of lapply, sapply - It is not good for readability, and may be avoidable. Perhaps you can pass additional arguments to the first lapply call (i.e., lapply(seq_along(object), function (i, newObj) { ... }, newObj = object))
> - 5. Try to avoid call sequences such as rbind > lapply > cbind > rbind > lapply > cbind.
> - 6. Use of 1:length(number) is not robust when the number variable is 0L. Try using seq_len(number) instead.
> - 7. Minor: Avoid using ifelse for scalar evaluation, just use if ( ) else ( )
> - 8. You shouldn't be using @ to access slots in your class. Please use accessors and replacers for this.
> - 9. Avoid using argument names that are functions such as by.
> 
> Vignettes
> 
> - 10. Looking good.
> 
> Documentation
> 
> - 11. Overall, looks helpful.
> - 12. You include an example with \dontrun. It looks runnable.

Comments

1. Done (Limma moved to Imports)
2. We now unit tests all main function in the package, specifically `bakedpi()` and `slicepi()`.
3. We have not changed anything here.  We don't believe in creating a new generic when we only would write a single method for the generic. Instead we think of our `stopifnot()` as argument checking.
4. We have improved readability by naming the functions.
5. See 4. 
6. Done (no use of `1:length(x)` anymore in code).
7. Done (no use of `ifelse()` in code outside of `data.table` functions where we need it.
8. Done (no use of `@` in code outside of accessors).
9. Done (by is no longer an argument name).
10. Thanks (no change).
11. Thanks (no change).
12. We now have a small dataset included in the package, so we have removed `\dontrun{}`. Several examples have been reworked.

**Comment by LiNk-NY** [comment]
Hi @kasperdanielhansen and @lmyint, 

Thank you for submitting to Bioconductor!

Regards,
Marcel

**Comment by kasperdanielhansen** [comment]
Any feedback on our response?

**Comment by kasperdanielhansen** [comment]
Guess we're accepted based on the label. Thanks, that's great.

**Comment by LiNk-NY** [comment]
Hi @kasperdanielhansen and @lmyint, 
Thank you addressing the points in the review.
I labeled your package as accepted. 
Thank you for submitting to Bioconductor! 

Regards, 
Marcel
