### ISSUE TITLE
scRepertoire submission

### ISSUE THREAD

**Issue by ncborcherding** [Bioconductor/Contributions#1503]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ncborcherding/scRepertoire

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please make sure the your package can interoperate with (i.e., accept as input and return as output, when appropriate) [standard Bioconductor data representations][1], in particular the [SingleCellExperiment][2] class. Relevant packages should at least appear in the Suggests: field (if the support is optional) or in the Imports: field (preferred).

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/
[2]: https://bioconductor.org/packages/SingleCellExperiment

**Comment by ncborcherding** [comment]
Thanks - packages does interoperate with SingleCellExpression already, but Imports SingleCellExperiment has been added to the DESCRIPTION.

**Comment by lshep** [comment]
Please set up your [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook).  Once this is done please do a version bump in your DESCRIPTION to kick off a new build on the builders.  Bioconductor policy is not to allow dependency on packages that are not on either CRAN or Bioconductor.

**Comment by lshep** [comment]
Startrac  does not appear to be a CRAN or Bioconductor package.  Dependencies can only be packages that are actively on CRAN or Bioconductor.

**Comment by ncborcherding** [comment]
Do I need to remove the function that uses Startrac then? Or how would I allow for the build and keep the function?

Just looked through the startrac code, it looks like I would have to copy all the code into scRepertoire, just for one function to be used in scRepertoire function.

Apologies if that is a dumb question.

**Comment by lshep** [comment]
I would suggest reaching out to the Startrac package and ask about submitting to CRAN or Bioconductor.  But yes, otherwise you will have to remove the Startrac functionality from your package -- either reimplement  in your package or find equivalent functionality in a CRAN/Bioconductor package.

**Comment by ncborcherding** [comment]
New comit to address errors with version change from 1.2.3 to 0.99.0 per error message. Complete changes:

CHANGES IN VERSION 0.99.0
------------------------

-Changed DESCRIPTION version to 0.99.0
-Removed file seurat_example.rda, accidentally committed
-Deleted git attributes
-reduced Seurat object size for alluvialClonotype in vignette
-Changed the alluvialClonotype assessment to account for only 1 condition

**Comment by hpages** [comment]
Thanks @ncborcherding for submitting the scRepertoire package.

There are 2 immediate issues that will likely require significant changes to the package:

1. The vignette and some examples in the man pages use Seurat objects. Bioconductor has a **strong** preference for SingleCellExperiment objects so please use this instead.

2. Also the vignette and some examples in the man pages download datasets from GitHub. This is not the Bioconductor way. Please include the datasets in the package if they don't grow its size beyond the allowed limit, or wrap them in a data experiment package. If you choose the latter, and if the data is more than 50Mb, then the data should preferrably be hosted on ExperimentHub but it should still be associated with a data experiment package. Whether the datasets are included in scRepertoire or in a dedicated data experiment package, they should have man pages giving as much details about the data as possible.

Other issues, mostly cosmetic:

3. Please remove the HTML vignette from the vignettes/ folder. The HTML vignette will be automatically generated by `R CMD build` and included in the resulting source tarball.

4. The vignette has no title, no author name, and no introduction. Please add all of these.

5. Also please add a sessionInfo() section at the end of the vignette.

6. The section/subsection headers are not rendered properly in the HTML vignette.

7. Code snippet `csv1 <- read.csv(“location/of/file.csv”, stringsAsFactors = FALSE)` should be made a real markdown code chunk so it is rendered as such.

8. The man page for `abundanceContig` says "This function takes the output of `combineContig()` or `expression2List()`" but  I don't see any `combineContig()` defined in the package.

Thanks,
H.

**Comment by ncborcherding** [comment]
Seems to be a general issue here with the build:
1. R CMD check is giving an error for the build, I can replicate it on another system with the following log:
* installing *source* package ‘scRepertoire’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
sh: line 1: 47521 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/bt/30h0rxyd2kq_g012_zyq6mjc0000gn/T//RtmparjZoU/fileb99aa5774'
ERROR: lazy loading failed for package ‘scRepertoire’
* removing ‘/Users/nick/scRepertoire.Rcheck/scRepertoire’

2. Statement that Biostrings is not a Bioconductor package
3. I cannot replicate 

Error: package or namespace load failed for scRepertoire in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called Biostrings
Execution halted

**Comment by hpages** [comment]
Hi @ncborcherding ,

Thanks for the improvements and sorry for the delay.

What do you mean by "and subsequently interacts with the popular Seurat R package and _SingleCellExpression data_"? (This is in the `Description` field of your `DESCRIPTION` file.) Is there a package or data structure called "SingleCellExpression" that scRepertoire interacts with, or do you mean "SingleCellExperiment package", or do you just mean "single cell expression data"?

Please add a title and author(s) to the vignette.

Thanks,
H.

**Comment by ncborcherding** [comment]
Hey H.,

No problem at all, thanks for the great suggestions previously. 

> What do you mean by "and subsequently interacts with the popular Seurat R package and SingleCellExpression data"? (This is in the Description field of your DESCRIPTION file.) Is there a package or data structure called "SingleCellExpression" that scRepertoire interacts with, or do you mean "SingleCellExperiment package", or do you just mean "single cell expression data"?

You are correct I meant the SingleCellExperiment package, I have updated the DESCRIPTION file in 0.99.17 (most recent commit) to reflect that.

`Please add a title and author(s) to the vignette.`

I believe this was already there (below). Please let me know if this is not sufficient (I did update the date for today).

<img width="678" alt="Screen Shot 2020-10-16 at 6 58 36 AM" src="https://user-images.githubusercontent.com/22754118/96255787-1ace7a00-0f7d-11eb-8bcb-be3b3840a394.png">

Thanks again and have a great day,

Nick

**Comment by hpages** [comment]
Hi @ncborcherding ,

Thanks for the changes. The Description is much clearer now. As for the title and author(s) of the vignette, I was talking about the _rendered_ vignette, which is the one that the user will typically be looking at. It doesn't have any visible title or author(s):

![Screenshot from 2020-10-22 21-44-48](https://user-images.githubusercontent.com/8810451/96957727-476c1f80-14b0-11eb-9b43-630a546a226a.png)

The rendered vignette is automatically created from the Rmd vignette by `R CMD build scRepertoire` and included to the resulting source package. After you install the source package, start R, and load the package, you can access the vignette with `browseVignettes("scRepertoire")`.

Thanks,
H.

**Comment by ncborcherding** [comment]
Hi @hpages,

Thank you so much for the screen shot - did not realize that was going on. I changed the VignetteEngine and now `R CMD build` is outputing the biocstyle vignette with the author information.

<img width="1042" alt="Screen Shot 2020-10-23 at 7 19 09 AM" src="https://user-images.githubusercontent.com/22754118/97002771-13b8e600-1500-11eb-9481-a69f2680b173.png">

**Comment by hpages** [comment]
Much better! Thanks for the quick fix.  H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ncborcherding.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scRepertoire")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scRepertoire

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
