### ISSUE TITLE
(inactive) MAUDE

### ISSUE THREAD

**Issue by Carldeboer** [Bioconductor/Contributions#1505]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Carldeboer/MAUDE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Before review can be initiated, your package needs to

- follow package submission guidelines with respect to version number
- interoperate (accept as inputs / return as outputs; use in vignettes) [standard Bioconductor data structures][1] such as GRanges and perhaps SummarizedExperiment

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by Carldeboer** [comment]
Whoops. Some changes I had made seem to have been lost (including the DESCRIPTION file). Re-running checks now with recovered versions. Thanks for pointing that out. I will update when checks are complete. 

As far as interoperability, one of the vignettes describes how to integrate MAUDE results with GRanges and other Bioconductor tools: https://carldeboer.github.io/MAUDE/doc/CD69_tutorial.html

**Comment by mtmorgan** [comment]
Depending on what your revisions look like, I don't really think it's enough to have a vignette, if the user with a GRanges object needs cannot directly use your functions...

**Comment by Carldeboer** [comment]
I think the more usual use case would be to go the other way around (end with GRanges), since MAUDE is a primary data analysis tool. I strongly want to avoid a dependence on other packages to make usage easier, reduce overhead, and avoid unnecessary dependencies that will break things down the line. The vast majority of MAUDE functionality is sufficiently abstract that it could have nothing to do with genomic locations. There are, however, two functions that only make sense with respect to genomic coordinates, and could use GRanges. Would you recommend modifying them to accept either data.frames or GRanges?

**Comment by Carldeboer** [comment]
Okay, so I fixed the files and confirmed that it passes R CMD and bioC checks. Please let me know how best to proceed.

**Comment by mtmorgan** [comment]
The package submission guidelines indicate that the version is supposed to be 0.99.0, incremented 0.99.1, 0.99.2, ... etc during the review process.

Yes your package should be modified to accept and return GRanges as appropriate.

**Comment by Carldeboer** [comment]
I fixed the version number (0.99.0 now) in the DESCRIPTION file. Thanks for pointing that out!

I started trying to modify the code so that `getTilingElementwiseStats` (the most "genomic" function in MAUDE) can accept GRanges objects, but immediately ran into the problem that GRanges requires every entity to have genomic coordinates.
Specifically: 
```
Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : 
  In range 1: at least two out of 'start', 'end', and 'width', must
  be supplied.
```
In our case, a common and expected scenario is that some of the entities are not associated with coordinates; namely, the negative controls. Now I could imagine forcing the user to split their data in two, convert half the data into a GRanges, and the other half into a separate data.frame containing the negative controls, but I see no advantage to doing so.

**Comment by mtmorgan** [comment]
I'll initiate the review process and let the reviewer work through this with you.

**Comment by mtmorgan** [comment]
@Carldeboer you'll need to update your package to spend (much) less time building the vignettes, so that it is consistent with Bioconductor guidelines. Be sure that you have the [web hook][1] activated correctly, and remember to increment the version (to 0.99.1, 0.99.2, etc) as you make changes to pass the automated checks.

[1] https://github.com/Bioconductor/Contributions#adding-a-web-hook

**Comment by Carldeboer** [comment]
One of the vignettes is a re-creation of how we evaluated the methods. This one takes awhile and  cannot be sped up. Is there another location where this (`.Rmd`) could be included, but not as a vignette?

**Comment by mtmorgan** [comment]
one possibility is under the inst/ directory, e.g., `inst/rmd/<vignette.Rmd>`. I think you could also include the 'build' product (html) under `inst/doc/vignette.html` though I'm not sure of this

**Comment by Carldeboer** [comment]
Alright, so I made a few updates, including adding the data files for vignettes into `inst/`. I ended up moving the evaluation script to its own folder which is in `.Rbuildignore` so it won't be installed at all. It will exist on github only, which seems appropriate since it's not really designed to help the end user. The version is now 0.99.1. It now takes just under 5 mins on my computer to rebuild the vignettes in `devtools::check()`.

**Comment by mtmorgan** [comment]
good; can you confirm that the web hook is set up correctly, and bump the package version to 0.99.2? It should trigger an automatic build...

**Comment by Carldeboer** [comment]
Great, thanks - forgot to set up the webhook. It should be set up now and I updated the version to 0.99.2.

**Comment by mtmorgan** [comment]
if your package is ready for review, please increment the version number to trigger an automatic build.

**Comment by Carldeboer** [comment]
@mtmorgan Thanks for the heads up. Missed that update.

**Comment by mtmorgan** [comment]
Please update your package in response to the following. When your updates are complete, please add a comment indicating how you have responded to each.

DESCRIPTION, vignettes, NAMESPACE

- good

- in the CD69_tutorial.Rmd, consider using BiocFileCache to increase performance and reduce risk of network timeouts

    ```
    xlsx <- BiocFileCache::bfcrpath(
        rnames="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5675716/bin/NIHMS913084-supplement-supplementary_table_1.xlsx"
    )
    CD69Data = read.xlsx(xlsx)
    ```

- use rtracklayer::import() to read standard file formats such as BED. This is more robust and consistent with Bioconductor interoperability, for instance genome coordinates adopted in Bioconductor are 1-based and closed (so the first record, reported in the bed file as chr12 9885788-9886093 as a zero-based, 1/2 open interval is imported using rtracklayer as chr12 9885789-9886093.

    ```
    bed <- system.file(
        "extdata", "Encode_Jurkat_DHS_both.merged.bed", 
        package = "MAUDE", mustWork = TRUE
    )
  dhsPeakBED = read.table(bed, stringsAsFactors=FALSE, row.names=NULL, sep="\t", header=FALSE)
  ```
  
  note that the 'name' field of your table is just `as.character()` of a GRanges object so the complicated `paste()` statement is not needed.
  
- Please avoid nested function calls, which have to be read 'inside out' and are excessively long, e.g., revise

  ```
  binStats = read.table(system.file("extdata", "CD69_bin_percentiles.txt", package = "MAUDE", mustWork = TRUE), 
  stringsAsFactors=FALSE, row.names=NULL, sep="\t", header=TRUE)
  ```
  
  as
  
  ```
  path <- system.file(
    "extdata", "CD69_bin_percentiles.txt",
    package = "MAUDE", mustWork = TRUE
  )
  binStats = read.table(
    path, stringsAsFactors=FALSE, row.names=NULL, sep="\t", header=TRUE
  )
  ```

R

- Some of these comments might seem like a matter of 'taste', but really I'm trying to standardize your code formatting, hence making it more readable by others. Readability is a prerequisite to more substantive assessment.

- It's very hard to read long lines, please consider breaking these (to a maximum of 80 characters) and implementing a more sequential logic, e.g., replacing

    ```
    curGuides = guides[elements[[elements.start]][xi] <= guides[[guides.pos]] & elements[[elements.end]][xi] >= guides[[guides.pos]] & elements[[elements.chr]][xi]==guides[[guides.chr]],];
    ```

  with

    ```
    curGuides = 
      guides[elements[[elements.start]][xi] <= guides[[guides.pos]] & 
      elements[[elements.end]][xi] >= guides[[guides.pos]] & 
      elements[[elements.chr]][xi] == guides[[guides.chr]],]
    ```

- Use of `sprintf()` is providing very little value in `stop()`, e.g.,

    ```
    stop(sprintf("Cannot find all of %s and %s in guides data.frame!  Did you forget to set guides.pos or guides.chr?", guides.pos, guides.chr))
    ```
    
  is just
  
    ```
    stop(
      "Cannot find all of ", guides.pos, " ",
      "and ", guides.chr, " in guides data.frame! ",
      "Did you forget to set guides.pos or guides.chr?"
    ```
    
- define and use (temporary) variables rather than copy/pasting relatively complicated expressions, e.g., 

    ```
    bin <- LETTERS[6]
    if (sum(curBinBounds$Bin %in% bin) < 2)
      stop("Must have at least two bins.")
    curBinBounds = curBinBounds[c("Bin","fraction")] # only want these two columns;
  
    #add any missing bins (null bins with no area)
    if (!all(bin %in% curBinBounds$Bin)) {
      curBinBounds = rbind(
        curBinBounds, 
        data.frame(Bin = bin[!bin %in% curBinBounds$Bin], 
        fraction=0.00000000001)
      )
    }
    ```

- Consider structuring your code into distinct files with logically related functions. Write 'man' pages that parallel this structure. This makes it easier to navigate your complicated code base.

man pages

- good

**Comment by mtmorgan** [comment]
@Carldeboer will you be responding to the review comments?

**Comment by Carldeboer** [comment]
@mtmorgan Yes!
Sorry - have been busy. 
I agree with most of your recommendations. I will need some time to implement and test. Probably at least a month. 
The only one I am not sure about is splitting into multiple files. Since most of the functions are calling one another (e.g. X(){Y()}; Y(){Z()}; etc.), I think it would make more sense to keep them in one, but will consider this while implementing the other changes.
