### ISSUE TITLE
metavizr

### ISSUE THREAD

**Issue by hcorrada** [Bioconductor/Contributions#154]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/epiviz/metavizr

Confirm the following by editing each check box to '[x]'
- [ X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [ X] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [ X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [ X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [ X] The 'devel' branch for new packages and features.
- [ X] The stable 'release' branch, made available every six
    months, for bug fixes.
- [ X] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by lawremi** [comment]
Hi Hector,

Metaviz looks cool. Maybe the data should be in a separate package? The vignette seems shallow. It does not really motivate or explain the package. There would probably be some overlap with the Metaviz tutorial, but apparently that does not exist yet either. With reference classes, I would prefer making explicit reference to `.self` instead of using `<<-` to assign values to fields. Not sure if that's formal Bioc policy or not (yet).

**Comment by lshep** [comment]
A more detailed review will not begin until ERRORs in the build report are corrected.  

Any package that is imported in the NAMESPACE should be listed as import (or handled appropriately with Depends/suggests) in the DESCRIPTION file.

**Comment by lawremi** [comment]
The error in the build report is surprising, since epivizrStandalone is a Bioc package.

**Comment by lshep** [comment]
This should be resolved if they add epivizrStandalone to the import list in the DESCRIPTION file.

**Comment by hcorrada** [comment]
Hi Mike and Lori,

This push should build without error. There is some documentation issues we need to address but they are listed as warnings and errors. 

Here are some comments on Mike's review comments:

> Metaviz looks cool. 
Thanks!

> Maybe the data should be in a separate package? 
It's gone, we use example data from `metagenomeSeq` for this.

> The vignette seems shallow. It does not really motivate or explain the package. There would probably be some overlap with the Metaviz tutorial, but apparently that does not exist yet either. 
Agreed, we are working on it this week

> With reference classes, I would prefer making explicit reference to .self instead of using <<- to assign values to fields. Not sure if that's formal Bioc policy or not (yet). 
Not addressed yet in this last push, but will address in the next couple of days. We've adopted this style on our other pkgs, but there is some code here we need to fix.

> I also noticed that "stringr" is listed in Imports but NAMESPACE does not import it.
Will fix.

**Comment by hcorrada** [comment]
- [ ] Flesh out vignette
- [ ] Fix .self instead of <<-
- [ ] Fix dependency on stringr

**Comment by lawremi** [comment]
Hi Hector,

I'm going to help out the core crew with this submission. There are a lot of warnings and notes that seem easy to fix, so I will let you do that first before I proceed with a more formal review.

**Comment by hcorrada** [comment]
@lawremi 

Hi Mike,

Thanks for helping out! We've done a few things on this new version

- expanded vignette, there is still more description of UI coming in the next day or so
- all warnings from R CMD check should now be gone, there is one warning from BiocCheck but per Martin's msg to bioc-devel yesterday, that should go away in a new version of BiocCheck

Let us know what you think.

**Comment by lawremi** [comment]
With respet to the warning, why not just `importFrom(Biobase, fData)`? Having dependencies listed in the NAMESPACE file is convenient, at least in my opinion. I can see how qualifying symbols can be helpful when resolving ambiguity, or using an unusal function (where did this come from?). But there's no ambiguity and everyone knows the origin of `fData()`.

I'll start working on the review.

**Comment by hcorrada** [comment]
This takes care of the remaining warning. Thanks!

**Comment by lawremi** [comment]
# Documentation<a id="sec-1" name="sec-1"></a>

## General<a id="sec-1-1" name="sec-1-1"></a>

-   Consider a non-trivial README.md to advertise the software in your
    GH repository. This could just link to the Bioc package landing
    page.

## Vignette<a id="sec-1-2" name="sec-1-2"></a>

-   The vignette could still do a better job of describing the example
    data. While the data are described formally elsewhere, a few
    sentences about the type of object, what it contains, etc, would
    be helpful.
-   What is all the plot type registration in the vignette? Is the
    user expected to copy-paste that?
-   The construction of the `metavizControl` object could use some
    more explanation. It would to tell the reader the goal of the
    analysis, and how the parameters map to it. Are all of those
    parameters needed or can we rely on defaults? Could this first
    example be a bit simpler?
-   Why is the heatmap constructed using several function calls
    instead of the simpler `$plot()`? Does `$plot()` not support a
    subset of a data source?
-   Please demonstrate the high-level plotting functions.

## Man pages<a id="sec-1-3" name="sec-1-3"></a>

-   How do I get an instance of the EpivizMetagenomicsData class? No
    mention in the man page.
-   The method documentation often do not indicate the type of object
    returned. For example, what does `get_measurements()` return?
-   The method documentation does not describe the
    arguments. What does `colLabel` do with `toNEO4JDb()`?
-   The *MetavizTree* class is undocumented; should it be exported?

# Dependencies<a id="sec-2" name="sec-2"></a>

-   Why only import `new()` from the methods package? Surely the
    package uses many more symbols from methods, like `setMethod()`,
    `setClass()`, etc. Best practice is to just
    `import(methods)`. Typically, methods should also be in Depends.
-   Perhaps metagenomeSeq also belongs in Depends for the sake of user
    convenience?

# API<a id="sec-3" name="sec-3"></a>

-   Could the `app$plot()` method get the `datasource_name` by
    deparsing the first argument expression?
-   The `$add_measurements()` method from epivzir should probably be
    called `$create_datasource()`, and a data source should be
    subsettable directly, like the measurements. The existence of both
    `app$plot()` and `app$chart_mgr$visualize()` is a little
    confusing and should be explained.
-   What is the NEO4J dumping for? How is it related to visualization?
    Could move this somewhere else.

# Implementation<a id="sec-4" name="sec-4"></a>

-   It is not at all clear why the tree implementation needs
    *Ptr*. There are many problems:
    1.  The high-level type information is lost, since data structures
        are only storing the generic *Ptr* type.
    2.  Much complexity stems from dereferencing and the potential for
        unexpected side effects.
    
    In any language, mutable state adds complexity and thus should be
    used sparingly and through a write barrier. In R this equates to
    putting fields inside of formal reference classes. It's not clear
    why the tree would not work by having reference objects as nodes
    (as now) without all the /Ptr/s, perhaps also with some sort of
    "context" object that is manipulated during recursion.
-   Lots of `sapply()`, `lapply()` and `for()` calls. Could these be
    vectorized or changed to `vapply()`?  Stuff like
    
        lapply(seq_along(leafInfos), function(i) { "<NA>" })
    
    should be vectorized, like
    
        rep(list("<NA>"), length(leafInfos))
    
    but maybe the subassignment will recycle automatically. 
    
    Also consider *AtomicList* derivatives from IRanges and utilities
    from S4Vectors. This:
    
        sapply(leafAncestors, function(ancestors) { 
              paste(lapply(rev(ancestors), function(node) { node$id() }), collapse=",") 
            })
    
    Could be:

        unstrsplit(lapply(leafAncestors, function(ancestors) {
            vapply(rev(ancestors), function(node) node$id(), character(1L))
        }), ",")

-   Probably should drop the MySQL backend as it appears to be unused
    and broken.

# Misc<a id="sec-5" name="sec-5"></a>

-   Many of the R files have executable permissions, which is weird.

**Comment by hcorrada** [comment]
Thank you for the great review Mike. We will address these after this release round so `metavizr` is added to the devel branch (3.5). I will close the issue for now, and reopen in two weeks or so.

**Comment by hcorrada** [comment]
Hi @lawremi,

We are reopening this issue so metavizr is included in the next release. We have addressed most of the issues listed above, and will comment on them soon. I will first, push the newest version so building checks etc. are done. Once this issue is ready for your review again I will add a comment to let you know.

Thanks for the great initial feedback!
Hector

**Comment by hcorrada** [comment]
This error is addressed by

**Comment by hcorrada** [comment]
This error is addressed by this commit to `metagenomeSeq`:
https://github.com/HCBravoLab/metagenomeSeq/commit/ccee76841cb94fa8f674948ca9146f871309c29b

It should clear when the build system updates `metagenomeSeq`

**Comment by jmwagner** [comment]
Hi @lawremi,

Thank you for the review and comments of the prior submission of metavizr.  Below are the responses to the comments you provided.  Please let us know as you have any additional questions/comments.

>Documentation
>General

>Consider a non-trivial README.md to advertise the software in your
>GH repository. This could just link to the Bioc package landing
>page.

The README.md has been updated with links to metaviz.org and 
tutorials.

>Vignette

>The vignette could still do a better job of describing the example
>data. While the data are described formally elsewhere, a few
>sentences about the type of object, what it contains, etc, would
>be helpful.

The vignette has been updated to include descriptions of all example 
data.

>What is all the plot type registration in the vignette? Is the
>user expected to copy-paste that?

The plot type registration is not visible when building the vignette
and we added a note the user.  The plot type registration is 
required for the registering each chart type so that the vignette 
will build when starting a new Metaviz session using localhost.

>The construction of the metavizControl object could use some
>more explanation. It would to tell the reader the goal of the
>analysis, and how the parameters map to it. Are all of those
>parameters needed or can we rely on defaults? Could this first
>example be a bit simpler?

We added an explanation of the metavizControl object creation and 
now specify one parameter while relying on defaults for the rest.

>Why is the heatmap constructed using several function calls
>instead of the simpler $plot()? Does $plot() not support a
>subset of a data source?

We have updated the epivizr package to include a revisualize 
function. revisualize takes the chart object returned from 
$plot() and uses the measurments to create a new chart.

>Please demonstrate the high-level plotting functions.

We take this to mean explaining what objects can `plot` 
take as input. We add the following sentence in the vignette 
before the `plot` call: "The `plot` function can take as input 
any of the classes registered with epivizrData."

>Man pages

>How do I get an instance of the EpivizMetagenomicsData class? No
>mention in the man page.

The documentation now contains an example for creating an instance 
of EpivizMetagenomicsData.

>The method documentation often do not indicate the type of object
>returned. For example, what does get_measurements() return?

The method documentation for getMeasurements, getHierarchy, getRows,
getValues, getCombined, and the MetavizGraph functions 
now includes description of return.

>The method documentation does not describe the
>arguments. What does colLabel do with toNEO4JDb()?

The method documentation for getMeasurements, getHierarchy, getRows,
getValues, getCombined, and the MetavizGraph functions
now includes description of arguments. Specifically 
for toNEO4JDb(), the NEO4J export is being moved to a new class.

>The MetavizTree class is undocumented; should it be exported?

The MetavizTree class has been removed and replaced by MetavizGraph.
The MetavizGraph class has been documented and is not exported.

>Dependencies

>Why only import new() from the methods package? Surely the
>package uses many more symbols from methods, like setMethod(),
>setClass(), etc. Best practice is to just
>import(methods). Typically, methods should also be in Depends.

methods has been moved to Depends and the best practice of 
import(methods) is now followed.

>Perhaps metagenomeSeq also belongs in Depends for the sake of user
>convenience?

metagenomeSeq has been moved to Depends.

>API

>Could the app$plot() method get the datasource_name by
>deparsing the first argument expression?

datasource_name is now deparsed from the data object.
datasource_name is now an optional argument in case the user wants to 
specify a given name to appear in the Metaviz UI.

>The $add_measurements() method from epivzir should probably be
>called $create_datasource(), and a data source should be
>subsettable directly, like the measurements. The existence of both
>app$plot() and app$chart_mgr$visualize() is a little
>confusing and should be explained.

We believe that both of these are epivizr issues and not specific to 
metavizr.

>What is the NEO4J dumping for? How is it related to visualization?
>Could move this somewhere else.

The NEO4J dumping has been removed and a new class which will handle 
database export of the MRexperiment is being developed.

>Implementation

>It is not at all clear why the tree implementation needs
>Ptr. There are many problems:
  
>1. The high-level type information is lost, since data structures
>are only storing the generic Ptr type.
>2. Much complexity stems from dereferencing and the potential for
>unexpected side effects.

>In any language, mutable state adds complexity and thus should be
>used sparingly and through a write barrier. In R this equates to
>putting fields inside of formal reference classes. It's not clear
>why the tree would not work by having reference objects as nodes
>(as now) without all the /Ptr/s, perhaps also with some sort of
>"context" object that is manipulated during recursion.

The Ptr class has been removed.  The new implementation makes use 
of data.tables to store nodes and edges of the hierarchical 
feature data. The feature count values are also stored in a 
data.table. Aggregation queries for specified features are now 
computed using joins between the nodes, edges, and counts tables.

>Lots of sapply(), lapply() and for() calls. Could these be
>vectorized or changed to vapply()? Stuff like
>lapply(seq_along(leafInfos), function(i) { "<NA>" })
>should be vectorized, like
>rep(list("<NA>"), length(leafInfos))
>but maybe the subassignment will recycle automatically.
>Also consider AtomicList derivatives from IRanges and utilities
>from S4Vectors. This:
>sapply(leafAncestors, function(ancestors) { 
>paste(lapply(rev(ancestors), function(node) { node$id() }), collapse=",") 
>})
>Could be:
>unstrsplit(lapply(leafAncestors, function(ancestors) {
>vapply(rev(ancestors), function(node) node$id(), character(1L))
>}), ",")

We are working to remove for() loops from this implementation and 
replace with vectorized calls.

>Probably should drop the MySQL backend as it appears to be unused
>and broken.

The MySQL backend has been removed.

>Misc

>Many of the R files have executable permissions, which is weird.

The executable permissions on the R files have been removed.

**Comment by lawremi** [comment]
Thanks for addressing my comments. Even with the `revisualize()` convenience, the API does not seem very intuitive compared to grammar-based interfaces like ggplot2. Hopefully something like that could be wrapped around this in the future. I'm OK accepting this.

**Comment by hcorrada** [comment]
Thanks! Once an error-free build is done (should be at some point tomorrow, once metagenomeSeq is on the build system), I'll ping again to change the status of this package.

Thanks again!

- Yes, we are definitely overdue for an epivizr high-level API.

**Comment by mtmorgan** [comment]
I'll mark this as accepted, anticipating that the package will build successfully once metagenomeSeq's update propagates. Thanks for your help!
