### ISSUE TITLE
timecoursedata

### ISSUE THREAD

**Issue by NelleV** [Bioconductor/Contributions#1555]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nellev/timecoursedata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please update your package version to 0.99.0.

Please update your Title and Description to indicate more clearly what the nature of the data is; microarray? bulk RNAseq? scRNASeq?

Please make sure that your data is provided in a format that is consistent with `SummarizedExperiment`, `SingleCellExperiment`, and / or other [standard Bioconductor data representations][1]

Please post a comment here tagging @mtmorgan when you have made these changes.

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by NelleV** [comment]
Hello @mtmorgan

I've made the changes (and pushed to bioconductor, although I did not receive a built notification yet).

Many thanks,
Nelle

**Comment by mtmorgan** [comment]
The version bump to 0.99.0 (instead of starting there...) seems to have confused our code; can you please try a bump to 0.99.1?

**Comment by NelleV** [comment]
The remaining warning is: `WARNING: Description field in the DESCRIPTION file is too concise`
I can make it longer, but it will not necessarily describe more what the package does (considering this is a data package submission).

@LiNk-NY Let me know if I should still provide a longer description (in which case I will add a description of the three datasets included here).

**Comment by LiNk-NY** [comment]
Hi Nelle, @NelleV 

Thank you for your submission.

> Let me know if I should still provide a longer description (in which case I will add a description of the three datasets included here).

Yes, that sounds perfect. 

Please see the review below. 
If you have more questions, feel free to post them here. 

Best regards,
Marcel

---

# timecoursedata #1555

## DESCRIPTION

* Add slightly more detail to the `Description` field
* (optional) Include an ORCID IDs in the `Authors@R` field
* Does `covr` need to be in `Suggests`?

## NAMESPACE

* Looks good

## vignettes

* Consider using `output: BiocStyle::html_vignette` for the Bioconductor look.

## R

* There's an à in line 46 in `R/data.R`.
* Consider creating an empty environment for data extraction to avoid
sending the data to the `.GlobalEnv`:
```
dataEnv <- new.env(parent = emptyenv())
data("varoquaux", envir = dataEnv)
varoquaux <- dataEnv[["varoquaux"]]
```
* Data documentation looks great.
* Minor: `*root` and `*leaf` functions can be combined into one
* You may also consider combining the data into a single `SummarizedExperiment`
representation that shares a single `colData` DataFrame ('varoquaux*$meta')
and contains two assays.

**Comment by NelleV** [comment]
Hello @LiNk-NY 

I've fixed most of the elements you've suggested. The only element I haven't done is merge the leaf and root samples of the sorghum dataset: the samples for the two tissue types were sequenced as two different batches, and while joint analysis of the two samples is possible, it should be done with great care to alleviate batch effects.
I have edited the documentation to reflect this (as well as corrected some errors in the documentation).

If we are to go down the route of merging the two sample types, I will edit the documentation further 

Many thanks,
Nelle

**Comment by NelleV** [comment]
Hi @LiNk-NY 
I was wondering if you had any more comments.
Many thanks,
Nelle

**Comment by LiNk-NY** [comment]
Hi Nelle, @NelleV 
Can you respond to the review line by line? 
Thank you. 
I will have a second look soon. Sorry for the delay. 
Best,
Marcel

**Comment by NelleV** [comment]
Sorry for the delay ! Here are the inline responses

## DESCRIPTION

   - ~Add slightly more detail to the Description field~ Done
   - ~(optional) Include an ORCID IDs in the Authors@R field~ Done
   - ~Does covr need to be in Suggests?~ Yes! Done

## NAMESPACE

  -  ~Looks good~

### vignettes

   - ~Consider using output: BiocStyle::html_vignette for the Bioconductor look.~ Fixed

### R

   - ~There's an à in line 46 in R/data.R.~ Fixed
   - ~Consider creating an empty environment for data extraction to avoid sending the data to the .GlobalEnv:~ Done

    - ~Data documentation looks great.~ Thanks!
    - Minor: *root and *leaf functions can be combined into one

The samples for the two tissue types were sequenced as two different batches, and while joint analysis of the two samples is possible, it should be done with great care to alleviate batch effects. As a result, I did not merge the two sample types. I edited the documentation to be more precise on that point. Let me know if this is ok, or whether to merge the two sample types (in which case I will further edit the documentation)

    - You may also consider combining the data into a single SummarizedExperiment
       representation that shares a single colData DataFrame ('varoquaux*$meta')
       and contains two assays.

Similar as last comment.

**Comment by LiNk-NY** [comment]
Hi Nelle, 
I had a quick look and it looks good. 
A couple of minor issues are: 

Include `BiocStyle` in your `DESCRIPTION` file under `Suggests:`
Resolve this NOTE from `R CMD check` by adding these to the
`.Rbuildignore`:

```
> R CMD check timecourse_*
NOTE Found the following hidden files and directories:
  .travis.yml
  .build_tools
  .scripts
```
Thanks!

**Comment by NelleV** [comment]
Hello @LiNk-NY 
It's all done!
Thanks,
Nelle

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/NelleV.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("timecoursedata")`. The package 'landing page' will be created at

https://bioconductor.org/packages/timecoursedata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
