### ISSUE TITLE
miRDriver

### ISSUE THREAD

**Issue by mmor0728** [Bioconductor/Contributions#1563]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bozdaglab/miRDriver

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Bioconductor package git repositories cannot contain files larger than 5 MB, but

```
remote: Error: file larger than 5 Mb.        
remote: 
remote:     File name: 'supplementary materials/Supplemental_file_1_BRCA_OV_SURVIVAL_CURVES.pdf'        
remote:     File size: 6.2 Mb        
remote: 
remote: Please see Biocondcutor guidelines        
remote: https://bioconductor.org/developers/package-guidelines/    
```
Please remove this (and other) large files that are not part of the package source code from the master branch of your repository. It may be necessary to also [remove large data files][1] from your package history. Post a comment to @mtmorgan when ready to continue the submission process.

[1]: https://bioconductor.org/developers/how-to/git/remove-large-data/

**Comment by mmor0728** [comment]
@mtmorgan I have removed the large files and I believe I have removed it from the history as well, so it should be better! Thanks

**Comment by mmor0728** [comment]
@mtmorgan Is there any update? I have addressed everything and am waiting for bioconductors response.

**Comment by hpages** [comment]
Thanks for the submission.

There are a lot of formatting issues with the HTML version of the vignette that makes it hard to read/navigate. Also the vignette needs a title.

To see the HTML vignette, build the package with `R CMD build`, install the resulting tarball, then start R and do `browseVignettes(package="miRDriver")`.

The Table of Contents is ugly and it seems that it should be clickable but it's not. Also it's hardcoded, which is not a good idea. It should be dynamically generated.
The titles of sections and subsections have the same size and are not preceded with numbers so the document looks flat i.e. its structure is lost, especially on linear reading.
A lot of code is presented as plain text instead of being put in a code chunk.
etc...

Please address.

Thanks,
H.

**Comment by hpages** [comment]
Hi @mmor0728 , are you planning to follow up with this submission? Thanks

**Comment by mmor0728** [comment]
Hi @hpages , I am planning on following up with the submission. When looking at the comment I found other changes that needed to be made, i.e. interoperability with bioconductor classes, running code in the vignette, ect. and have been working on those changes along with the changes that go along with the comment before I resubmit.

**Comment by mmor0728** [comment]
@hpages I have not update you in a while, and want to let you know that I am still working and will have an updated package soon.

**Comment by hpages** [comment]
Hi @mmor0728 , thanks for improving your package and keeping me updated.  H.

**Comment by mmor0728** [comment]
@hpages In this package build, the code in the vignette relies upon the R package bedr. Bedr is avaliable on cran, but requires bedtools, bedops and tabix which are third party software. Is it possible for these to be avaliable on the bioconductor server? I am looking into other ways to accomplish the functionality in the code, but bedr is the prefered method.

**Comment by mmor0728** [comment]
Hi @hpages I have addressed your comments and updated several parts of the package.

**Comment by mmor0728** [comment]
Hi @hpages is there any update or review of the package at this time? If there are any changes that I can begin working on, that would be great, as I would like to be as efficient as possible with the review process.

**Comment by hpages** [comment]
Hi @mmor0728 ,

I'll take a look at the package ASAP. Sorry for the delay.

H.

**Comment by hpages** [comment]
Hi @mmor0728

Thanks for improving the formatting of the vignette but there are still some serious problems with this package.

The major one is that it contains zero running example!!

Another one is this one:
![Screenshot from 2021-01-26 01-46-46](https://user-images.githubusercontent.com/8810451/105828806-6c24d700-5f78-11eb-9791-ef01638e3fee.png)
Where is step 2?

Another one is this one (the warnings are filling more than 1 screen so I'm only showing the beginning of them):
![Screenshot from 2021-01-26 01-48-38](https://user-images.githubusercontent.com/8810451/105829564-611e7680-5f79-11eb-9fbd-f63f309ff83f.png)

Another one is that you've put all your Rda files in `inst/extdata`. Rda files should be placed in the `data` folder. `inst/extdata` is for non Rda files.

Thanks,
H.

**Comment by mmor0728** [comment]
Hi @hpages  thank you for your comments. I have addressed them and resubmitted.

**Comment by mmor0728** [comment]
Hi @hpages I am wondering if you could please give your comments in the latest version of the package as soon as possible, as we are submitting a paper that revolves around the package soon.

**Comment by hpages** [comment]
Thanks for the changes.

Unfortunately I don't think the package is in a usable state at the moment. Some basic things seem broken:

    library(miRDriver)
    lassoParallelForTransGene(numCounter=10, Nfolds=3, nonZeroPercent=20, parallel=FALSE)
    # Error in gzfile(file, "wb") : cannot open the connection
    # In addition: Warning messages:
    # 1: In dir.create(paste0(mirdirectory, "/mirDriverFold/miRDriver_RESULTS/LassoMinCoeff")) :
    #  cannot create dir '/home/hpages//mirDriverFold/miRDriver_RESULTS/LassoMinCoeff', reason 'No such file or directory'
    # 2: In gzfile(file, "wb") :
    #  cannot open compressed file '/home/hpages//mirDriverFold/miRDriver_RESULTS/Final_gene_mirna_network.Rda', probable reason 'No such file or directory'

Also:

1. Why would the user need to specify both `ncores` and `parallel`?

2. Why is the default value for `parallel` a **character** vector of length 2 (`c('TRUE','FALSE')`) when this argument is expected to be a logicial?

3. Internally you do:
    ```
    ...
    if (parallel == TRUE) {
        ...
    }
    if (parallel == FALSE) {
        ...
    }
    ...
    ```
    This is bad programming style. (This is Programming 101 stuff so hopefully I don't need to explain why.)

4. `R CMD check` should not write files or create directories in the user home. This means that all the examples in your man pages and vignettes should write in a _temporary_ location, that is, in a place under `tempdir()`.

5. Don't hardcode paths containing the `/` separator like you do for example here:
    ```
    dir.create(paste0(mirdirectory,"/mirDriverFold/miRDriver_RESULTS/LassoMinCoeff"))
    ```
    This is not portable! Paths should always be assembled with `file.path()` or `system.file()`.

6. Readability matters and something like this could be easier to read if you were indenting the 2nd line and putting a space after each comma:
    ```
    ##The following code is a valid example of how to use the function but is commented as it
    lassoParallelForTransGene(ncores = 2,numCounter = 10,Nfolds = 3,
    nonZeroPercent = 20,parallel = FALSE, mirdirectory = "~/MIR123")
    ```
    Also please note that your comment preceding the code is incomplete.

7. Several man pages actually contain comments and/or commented out code that seem out-of-date or unnecessary. Some cleanup is needed.

8. Always put space before and after the assignment operator (`<-`).

9. The code in the vignette issues a lot of warnings for me:

![Screenshot from 2021-03-04 10-38-08](https://user-images.githubusercontent.com/8810451/110037013-b117f800-7cf2-11eb-9be0-9335c4b02ed7.png)

It's important to keep in mind that the primary reason people submit their package to Bioconductor is because they want to share it with the community so that others can actually _use_ it.

Thanks,
H.

**Comment by hpages** [comment]
Hi @mmor0728 ,

Please let me know if the package is ready for me to take another look at it.

Thanks,
H.

**Comment by mmor0728** [comment]
Hi @mtmorgan @hpages with the most recent builds of the package, I have gotten a warning that says "no function found corresponding to methods exports from 'S4Vectors' for: 'combineRows". Can you please help me to resolve this issue, I tried to reproduce the result in my local, but it seems like a bioconductor server issue?

**Comment by mmor0728** [comment]
Hi @hpages the package is fully updated.

**Comment by hpages** [comment]
Hi @mmor0728,

Yes the `no function found corresponding to methods exports from 'S4Vectors' for: 'combineRows'` warning was on our side, sorry for the late answer. The warning should be gone now.

What happened to the `\usage` sections of your man pages? Any man page that documents a function (or several functions) is expected to have a `\usage` section that shows the usage of the function(s). I've never seen an R package (CRAN or Bioconductor) that doesn't do that.

This still doesn't work:
```
library(miRDriver)
lassoParallelForTransGene(numCounter=10, Nfolds=3, nonZeroPercent=20)
# Error in gzfile(file, "wb") : cannot open the connection
# In addition: Warning messages:
# 1: In dir.create(file.path(mirdirectory, "mirDriverFold", "miRDriver_RESULTS",  :
#   cannot create dir '/home/hpages/mirDriverFold/miRDriver_RESULTS/LassoMinCoeff', reason 'No such file or directory'
# 2: In gzfile(file, "wb") :
#   cannot open compressed file '/home/hpages/mirDriverFold/miRDriver_RESULTS/Final_gene_mirna_network.Rda', probable reason 'No such file or directory'
```

I'm not going to look further at this package, sorry.

Also the commit history of the **miRDriver** repository is shockingly uninformative: 95% of the commit messages are the single letter "c" and another 3% are the word "commit". This makes it impossible to track what's going on with this project. Transparency and trackability are important for an open source project. And when various people contribute commits to it, like this seems to be the case here, seeing a commit history made of empty or meaningless messages suggests poor management of the project.

After 9 months of little progress, it's time to close this review process.

Regards,
H.

**Comment by mmor0728** [comment]
Hi @hpages, I understand that it seems that as a maintainer I was not efficient to reflect my efforts. I worked on the package and made 58 resubmissions so far. Could you please let me know which version you have used that you got this error. I am trying to reproduce the same error and wasn't able to. It will be great if you can tell me the version number as well.

**Comment by mmor0728** [comment]
Hi @hpages  miRDriver is a pipeline package so in order to run the last function one should run the previous functions. I figured that since in manpage I haven't mentioned it and provided the previous functions so this particular function didn't work. However if we include the previous functions, it will increase the run time. Please let me know what should be done to avoid this kind of issue in pipeline packages. I would be highly obliged if you could provide some guidance on it for my future projects.
