### ISSUE TITLE
(inactive) ERROR in read_cisbp

### ISSUE THREAD

**Issue by 2961461560** [Bioconductor/Contributions#1579]
Hi, I want to convert CIS-BP's motif format to meme format.
the first step, I downloaded the pwm data from http://cisbp.ccbr.utoronto.ca/bulk.php.
then I chose one pwm file as input for read_cisbp, just list this, `data <- read_cisbp("M00008_2.00.txt")`, but unfortunately I got an error message,`Error in mapply(function(x, y) raw_lines[x:y], meta_starts, meta_stops, :zero-length inputs cannot be mixed with those of non-zero length`. 
I don't what the reason is. I have tried read_meme() function, where the input file download from jaspar website, and this time it can be loaded successfully. So I think my system and R version and so on are ok.
How can I convert CIS-BP's motif data to meme format?
Thank you very much.

**Comment by mtmorgan** [comment]
If you are asking help with a Bioconductor package, please do so on the support site https://support.bioconductor.org

If you are asking a general bioinformatics question, consider https://biostars.org

**Comment by 2961461560** [comment]
ok, Thank you very much
