### ISSUE TITLE
KOdata

### ISSUE THREAD

**Issue by shanawhite-UC** [Bioconductor/Contributions#158]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shanawhite-UC/KOdata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by shanawhite-UC** [comment]
AdditionalPackage: https://github.com/shanawhite-UC/KEGGlincs

**Comment by shanawhite-UC** [comment]
To the best of my knowledge I have done everything I can on my end to fix the outstanding issues and am at a roadblock due to the following 2 issues:

1) For Windows and Mac OS, I fail to pass CMD CHECK; I get the message "Package suggested but not available: 'RCy3'" and I have no idea why this happens or how else to work around it.
2) My package is designed to work with an open session of Cytoscape; so even though it passes the CMD CHECK for Linux, there is an error for BiocCheck ("ERROR: At least 80% of man pages documenting exported objects must have runnable examples.") that I cannot work around unless the bioconductor.org package builder has an open Cytoscape session. 

I would greatly appreciate any suggestions, thank you.

**Comment by vobencha** [comment]
Hi,

The error in (1) above is because RCy3 and RCytoscape aren't supported on mac and windows:
http://www.bioconductor.org/checkResults/devel/bioc-LATEST/

The RC* authors are working on fixing their packages and we hope that they pass build/check on all platforms for the next release. Supporting an open Cytoscape session on the build machines added a great deal of complexity to the build system and will not be done in the future (>= Bioconductor 3.4). Instead of relying on an open Cytoscape session, your package should check for appropriate pre-conditions to the functions they implement. Another alternative is for you to support and provide access to a docker or web site with a Cytoscape session that the package can access.

Valerie

**Comment by shanawhite-UC** [comment]
Hi Valerie,

Thank you for the valuable feedback!  Since I am using the aforementioned package only for optional formatting I believe I can circumvent the issue (I will just make it clear that users will need to take two additional steps for manually re-formatting the pathways from within Cytoscape [until RCy3 is available on all platforms]).  I will work out a few options taking into consideration your comments about issue 2...thanks again for the advice!

Shana

**Comment by vobencha** [comment]
It looks like there are 2 package repos associated with this issue: KOdata and KEGGlincs. Overall really nice job with these -  just a minor comment on the data package.

KOdata:
- I don't understand the purpose of the files in the R/ directory. There are no functions or defined classes so these can probably be removed. Did you have something else in mind?

Valerie

**Comment by shanawhite-UC** [comment]
Hi Valerie,

Thank you for the positive feedback.  Concerning your comment:
> I don't understand the purpose of the files in the R/ directory. There are no functions or defined classes so these can probably be removed. Did you have something else in mind?

I created the folder/documents in order to generate the documentation files for the package [via roxygen2] - I'll assume that since the documentation is already generated I can go ahead and remove the R/ directory as you suggested.

Shana

**Comment by vobencha** [comment]
Thanks for making the changes - looks good. I'm marking the packages as approved. You should get an email in the next week with svn credentials and next steps.

When they are added to the build system you can monitor the software package here:
http://www.bioconductor.org/checkResults/devel/bioc-LATEST/
and the data package here:
http://www.bioconductor.org/checkResults/3.4/data-experiment-LATEST/

Thanks for contributing your work to Bioconductor.
Valerie
