### ISSUE TITLE
FScanR: an R package to detect Programmed Ribosomal Frameshifting (PRF) events from mRNA/cDNA

### ISSUE THREAD

**Issue by seanchen607** [Bioconductor/Contributions#1593]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/seanchen607/FScanR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
The version number of new packages must be '0.99.0'. If your package has been distributed publicly with version 1.0.0, then use version 1.99.0.

Post a comment here when your package has been revised.

**Comment by seanchen607** [comment]
The version number of the package has been revised to '0.99.0'. Thanks!

**Comment by Kayla-Morrell** [comment]
Hello @tnieuwe,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: The 'docs' should be moved to an 'inst/figures/' directory.

## DESCRIPTION

- [ ] REQUIRED: The 'Description' field in the DESCRIPTION is made up by less 
than 3 sentences. Please expand this field and structure it as a full paragraph.

- [ ] SUGGESTION: We strongly encourage including the 'BugReports:' field with 
the relevant link to Github for reporting Issues.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in the Bioconductor release announcements. See the following for more 
details and formating help:
https://bioconductor.org/developers/package-guidelines/#news.

## Data

- [ ] REQUIRED: Data that is used within the package needs to be properly 
included and not just a sysdata.rda file. Please read our documentation on 
including and documenting data here:
https://bioconductor.org/developers/package-guidelines/#data.

## Vignette

- [ ] REQUIRED: Lines 52-54, the code should be demonstrating to the user how to 
install the package from Bioconductor, not from GitHub. Also, this code should 
be in a proper code chunk with \`\`\` {r} \`\`\` and you should include 
`eval = FALSE`. The code for installing the package from Bioconductor should 
look like the following:

```{r}
iif(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("FScanR")
```

- [ ] SUGGESTION: We strongly encouarge the use of table of contents.

- [ ] REQUIRED: The purpose of the vignette is to demonstrate how to accomplish 
non-trivial tasks utilizing the core functionality of the package. Currently, 
all this vignette does is explain what the package is, what PRF is, and how to 
cite the package. There needs to be reproducable code that demonstrate the use 
of the package. 

- [ ] REQUIRED: The final section of the vignette should be 'Session Info' and 
should include `sessionInfo()`.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them.

## R code

- [ ] SUGGESTION: It's best to use various apply functions over for loops. 

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 32 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider mulitples of 4 spaces for 
line indents. There are 11 lines that are not.

Best,
Kayla

**Comment by seanchen607** [comment]
> Hello @seanchen607,
> 
> Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.
> 
> ## General package development
> * [x]  REQUIRED: The 'docs' should be moved to an 'inst/figures/' directory.
> 
> ## DESCRIPTION
> * [x]  REQUIRED: The 'Description' field in the DESCRIPTION is made up by less
>   than 3 sentences. Please expand this field and structure it as a full paragraph.
> * [x]  SUGGESTION: We strongly encourage including the 'BugReports:' field with
>   the relevant link to Github for reporting Issues.
> 
> ## NEWS
> * [x]  SUGGESTION: Consider adding a NEWS file, so your package news will be
>   included in the Bioconductor release announcements. See the following for more
>   details and formating help:
>   https://bioconductor.org/developers/package-guidelines/#news.
> 
> ## Data
> * [x]  REQUIRED: Data that is used within the package needs to be properly
>   included and not just a sysdata.rda file. Please read our documentation on
>   including and documenting data here:
>   https://bioconductor.org/developers/package-guidelines/#data.
> 
> ## Vignette
> * [x]  REQUIRED: Lines 52-54, the code should be demonstrating to the user how to
>   install the package from Bioconductor, not from GitHub. Also, this code should
>   be in a proper code chunk with ``` {r} ``` and you should include
>   `eval = FALSE`. The code for installing the package from Bioconductor should
>   look like the following:
> 
> ```
> iif(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("FScanR")
> ```
> 
> * [x]  SUGGESTION: We strongly encouarge the use of table of contents.
> * [x]  REQUIRED: The purpose of the vignette is to demonstrate how to accomplish
>   non-trivial tasks utilizing the core functionality of the package. Currently,
>   all this vignette does is explain what the package is, what PRF is, and how to
>   cite the package. There needs to be reproducable code that demonstrate the use
>   of the package.
> * [x]  REQUIRED: The final section of the vignette should be 'Session Info' and
>   should include `sessionInfo()`.
> 
> ## Unit tests
> * [x]  SUGGESTION: Consider adding unit tests. We strongly encourage them.
> 
> ## R code
> * [ ]  SUGGESTION: It's best to use various apply functions over for loops.
> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 32
>   lines that are > 80 characters long.
> * [x]  SUGGESTION: For formatting reasons, consider mulitples of 4 spaces for
>   line indents. There are 11 lines that are not.
> 
> Best,
> Kayla


Hi Kayla,

Thanks for reviewing my package! I've revised my package according to your suggestions above. The changes that have been accomplished are marked as a checked box.

Thanks,
Xiao

**Comment by Kayla-Morrell** [comment]
@seanchen607 - In order for a build report to be produced for these changes, you must bump the version in the DESCRIPTION file.

**Comment by seanchen607** [comment]
@Kayla-Morrell Thanks for the kind reminder! I've bumped the version to 0.99.6 and it has passed the check in the new build report. I've also pushed it to the origin. Thanks!

**Comment by Kayla-Morrell** [comment]
@seanchen607 - Thank you for making the necessary changes. I just have one more requirement before accepting the package.

## R directory

- [ ] REQUIRED: Please remove the sysdata.rda file.

Best,
Kayla

**Comment by seanchen607** [comment]
> @seanchen607 - Thank you for making the necessary changes. I just have one more requirement before accepting the package.
> 
> ## R directory
> * [x]  REQUIRED: Please remove the sysdata.rda file.
> 
> Best,
> Kayla

@Kayla-Morrell - Thanks, Kayla! I've removed the sysdata.rda file and bumped the version to 0.99.7, and also pushed it to the origin.

**Comment by Kayla-Morrell** [comment]
@seanchen607 - Great, thanks for making that change! I'm more than happy to accept the package now.

Best,
Kayla

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/seanchen607.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("FScanR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/FScanR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
