### ISSUE TITLE
(inactive) LRcell

### ISSUE THREAD

**Issue by marvinquiet** [Bioconductor/Contributions#1623]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/marvinquiet/LRcell

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your repository contains files larger than 5Mb
```
files larger than 5Mb:
  /marker_genes_lib/mouse/FCenriched_genes.RDS
  /marker_genes_lib/mouse/GPenriched_genes.RDS
  /marker_genes_lib/mouse/HCenriched_genes.RDS
  /marker_genes_lib/mouse/PCenriched_genes.RDS
```
Please update these to conform with package guidelines; it may be necessary to update your vignette to use a representative sample of data, or to make these data resources available via AnnotationHub or ExperimentHub () (for example http://bioconductor.org/packages/devel/bioc/vignettes/AnnotationHub/inst/doc/CreateAnAnnotationPackage.html).

Please update your package, and run BiocCheck::BiocCheck(). When your package is ready for review, please post a comment here.

**Comment by mtmorgan** [comment]
I'll close this issue now; post a comment here when it is ready to be reviewed.

**Comment by marvinquiet** [comment]
Hi,

Thank you for your suggestion! I am using the /marker_genes_lib/ as an online data resource and when building the package, I included the following lines in `.Rbuildignore`. 

```
# ignore marker genes library
marker_genes_lib/
```
The LRcell package built through `R CMD build LRcell/` could pass both `R CMD BiocCheck` and `R CMD check`. 

Sincerely,
Wenjing

**Comment by mtmorgan** [comment]
remove the large files from the master branch of your git repository; your git repository is cloned to ours as part of the review / dissemination process, and files cannot be that large.

**Comment by marvinquiet** [comment]
Got it, will do soon! Thank you! I will let you know when I finish.

**Comment by marvinquiet** [comment]
Hi, sorry for the long wait. I just uploaded my external data as an ExperimentHub package named LRcellTypeMarkers, which could pass the `R CMD check` and `R CMD BiocCheck`. Do I need to re-submit a repo or can I just do it here?

The Github repo can be found here: https://github.com/marvinquiet/LRcellTypeMarkers.

Because I submitted my software package first, according to the documentation of **Submitting Related Packages**, should I wait until the `review in progress` tag and then inform you of my original software package? Not sure what is the most appropriate thing I would do in my case. Any suggestions or help is appreciated.

**Comment by mtmorgan** [comment]
@lshep can you walk us through the best steps? thanks!

**Comment by marvinquiet** [comment]
Hi @mtmorgan and @lshep,

Thank you for your help!

I have checked both my packages and I think these two are both ready for the review process. Below please find the two packages.

1. Original Software Package: https://github.com/marvinquiet/LRcell
2. Additional ExperimentHub Package: https://github.com/marvinquiet/LRcellTypeMarkers

Could you please let me know what I can do to trigger the review process? 

Sincerely,
Wenjing

**Comment by lshep** [comment]
@marvinquiet  Very sorry for the delayed response.  Could you please open a new issue for the process to continue.  Remember to submit the experiment data hub package first.  Wait for it be in "review in progress" instead of "awaiting moderation" and then you can submit the second software package under the same issue using  `AdditionalPackage: https://github.com/marvinquiet/LRcell`    Cheers!

**Comment by marvinquiet** [comment]
Got you! Thank you so much for your suggestions.
