### ISSUE TITLE
BayesSpace

### ISSUE THREAD

**Issue by msto** [Bioconductor/Contributions#1624]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/edward130603/BayesSpace

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by msto** [comment]
Hi @mtmorgan,

I've removed the `Maintainer:` field and subscribed to bioc-devel to address the BiocCheckGitClone and BiocCheck errors. 

I'm a bit confused about the remaining issues under macOS. 

On the first build, the error was regarding linking to fortran on macOS. I previously encountered a similar issue on my own macbook, and the best solution I was able to find was to install gfortran [directly](https://github.com/fxcoudert/gfortran-for-macOS/releases) rather than through homebrew. I do have a note in the README suggesting this as a fix, but I'm very open to suggestions for a better solution.

However, on the second build, despite only updating the DESCRIPTION, I no longer receive the same error. Instead, for the check I receive errors that the package is not installable, and the binary build fails because the system cannot find edgeR (an indirect dependency via scran). I'm guessing that the failure to install the package in the CHECK is related to this problem, but I'm not able to replicate it locally. Do I need to explicitly add edgeR as an import, or do you have another suggestion to fix?

This package does build without issues and pass check/BiocCheck under macOS on the docker image provided in the (semi?)official [github action](https://github.com/r-lib/actions/issues/84) so these should be surmountable problems; unfortunately I'm not familar with the differences between that image and merida1. 

Thanks!

**Comment by msto** [comment]
Hi @mtmorgan,

The errors appear to have been due to an issue with the Bioconductor build system that Lori Shepherd very helpfully fixed this morning, and the package now builds without error. Please let me know any updates to the package you would suggest when you have time to review.

Thank you!

Matt

**Comment by mtmorgan** [comment]
Sorry for my slow response

DESCRIPTION

- good

vignettes

- IMPORTANT the code chunks in *.Rmd are not evaluated, enclose the `r` in braces `{r}`. Evaluated code chunks are an important part of effective documentation

- do the *bak / *orig and precomile.Rfiles belong in git / at this location?

- From a quick reading, the vignettes would benefit from brief paragraphps _interpretting_ the result of each (or most) code chunks

R (comments on specific lines of code apply throughout)

- Address TODO: in BayesSpace.R

- enhancedFeatures.R:74 use a single `warning()` statement, perhaps with `strwrap()` to format output

- readVisium.R:40 `stop()` calls `paste0()` internally (use of `message(sprintf())` can also often be similarly avoided, so it is usually sufficient to write

    ```
    stop("Matrix directory does not exist: ", matrix_dir)
    ```
    
  Writing the conditional block on the same line as the conditional leads to long an difficult to read code; follwo the standard convention of writing the body of the conditional on a separate line.
  
- utils.R:283 caching of internet downloads are relatively easy using BiocFileCache; see the vignette http://bioconductor.org/packages/devel/bioc/vignettes/BiocFileCache/inst/doc/BiocFileCache.html#local-cache-of-an-internet-resource

**Comment by msto** [comment]
Hi @mtmorgan,

No worries, thanks for the review!

## Description

Thanks!

## Vignettes

I had been pre-building some vignettes that were too computationally expensive to expect the user to build during installation. (The `*.Rmd.orig` files were the raw vignettes, and the `precompile.R` script knit them into Rmarkdown files where the chunks wouldn't be evaluated.) After getting some helpful feedback in the bioc-community slack, I've removed these vignettes from the package and have made them available on the package's website instead. I think they are helpful, as they reproduce the figures in the accompanying manuscript, but are not necessary to include with the package. 

I have updated the remaining vignette so it is evaluated and built upon installation. This vignette demonstrates usage of all exported function in the package.

## R

- [x] ~Address TODO: in BayesSpace.R~
  All TODOs have been addressed, removed as deprecated, or deferred for a later release.
- [x] ~enhancedFeatures.R:74 use a single warning() statement, perhaps with strwrap() to format output~  
  This has been fixed.
- [x] ~readVisium.R:40 stop() calls paste0() internally (use of message(sprintf()) can also often be similarly avoided, so it is usually sufficient to write~  
  All `stop()`, `warning()`, and `message()` statements now avoid use of `paste()` or `paste0()`.
- [x] ~Writing the conditional block on the same line as the conditional leads to long an difficult to read code; follwo the standard convention of writing the body of the conditional on a separate line.~  
  All inline conditionals have been replaced, either by placing the body on a separate line or with `ifelse()`. (The latter is only used to set default values where appropriate).
- [x] ~utils.R:283 caching of internet downloads are relatively easy using BiocFileCache; see the vignette~  
  Thank you very much for this suggestion! This was exactly what I hoped to accomplish and it was very easy to implement.

Please let me know if there are any further updates you'd like us to make to the package prior to acceptance. Thank you!

**Comment by msto** [comment]
The warning on the previous build was due to `R CMD check` exceeding the 10 minute runtime limit. I reduced the number of MCMC iterations used in the documentation examples and it now runs in under the limit.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/msto.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BayesSpace")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BayesSpace

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by msto** [comment]
Great, thank you Martin!
