### ISSUE TITLE
tidySE - brings SummarizedExperiment to tidyverse with no side effects

### ISSUE THREAD

**Issue by stemangiola** [Bioconductor/Contributions#1631]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/stemangiola/tidySummarizedExperiment

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
I believe many of my comments on tidySCE apply here as well; let me know when this package has been updated in line with those comments, and I will review it.

**Comment by stemangiola** [comment]
Hello @mtmorgan , here is the pull request for the compliance https://github.com/stemangiola/tidySE/pull/6

Below the tasks resolved (or commented on) - originally worked in this issue https://github.com/stemangiola/tidySCE/issues/8

**DESCRIPTION**

- [ ] I think the package should be re-named for maximum clarity as TidySingleCellExperiment -- the appreviation SCE could mean anything. The capitalization follows Bioconductor convention.

We are well in-line as I don't like acronyms either. As note, sce is the common name for SingleCellExperiment object e.g. in [this official source](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiw1PGMt6nsAhXIwjgGHZrzAIEQFjADegQIBhAC&url=https%3A%2F%2Fbioconductor.org%2Fpackages%2Frelease%2Fbioc%2Fvignettes%2FSingleCellExperiment%2Finst%2Fdoc%2Fdevel.html&usg=AOvVaw1K6UGxwNbq9KGDY1rDPLYR), is really commonly accepted by the community.

In order to respect both Bioconductor tradition and tidyverse standards (afterall this is a equal-rights marriage) the name `tidySingleCellExperiment` can be a good solution. (I understand the S4 point of view, but this package is dedicated to end-users, so the elegance in design and vocabulary has them as our priority)

Having said that, at the BioC-Asia2020 we will gather the opinion of the community with a pool at our workshop.

- [x] Title: field opening quote not closed; is it necessary

- [x] Description: Not sure what an 'invisible layer' is as a programming concept?

- [x] Imports: not all packages listed here are actually used directly? Remove packages that provide functionality that is not directly referenced.

**TESTS**

- [x] consider organising test files so that they have the same structure as the R/ files -- each tests/testthat/test-* is testing code defined in the corresponding R/* file. This organization makes it easier to navigate the code.

- [x] hmm, I find the coding style here very difficult to read, and wonder why it does not follow tidyverse guidelines? https://style.tidyverse.org/pipes.html#whitespace .

- [x] Likewise with tests, it would seem that nesting pipes within expect_*() is antithetic to readability -- instead, create a temporary variable from a piped expresssion, and use the variable in expect_*() statement?

_I opted for full tydyverse style without the need to create temporary variables_

- [x] test-dplyr.R:16 It is never appropriate to use direct slot access; use accessors instead.

**R (comments are on specfic lines of code, but apply throughout)**

- [x] data.R I was surprised that these data sets were not documented here, where they are defined? The documentation in man/pbmc_small.Rd, for instance, is inadequate -- provide a description of what the object represents, how it was derived, how it is used in the package.

- [ ] dplyr_methods.R:58 Redefining the generic is not appropriate. Instead, define S3 methods that implement functionality for the specific classes you wish to provide methods for, and export the methods. Since you expect the user to use the dplyr generics, place dplyr in the Depends: field of the DESCRIPTION file.

_I worked on it, and I agree. Respecting this standard is on out to-do list for tidySCE, tidySE and tidybulk. However I was not able to make things work under this standard [this branch](https://github.com/stemangiola/tidySCE/tree/drop-generics) (either the export from roxigen disappears, or the method.class does not get exported). I ask to give us a release cycle to fix this. This although is a better approach does not affect negatively when using any package._

- [x] dplyr_methods.R:157 I find the mix of 'base' and tidy functionality confusing; why use cbind() rather than the tidy equivalent? In the next line,

_I used cbind to cbind two SingleCellExperiment objects_ 

- [x] dplyr_methods.R:189 Never use direct slot access @, instead use accessors colData(). It's strange to see as.data.frame() in this line, rather than as_tibble(), and likewise creating the second argument as a DataFrame()???

_tts[[1]] is a SingleCellExperiment; colData(tts[[1]]) is a DataFrame that cannot be converted to tibble directly; DataFrame is used to update colData from SCE_

- [x] dplyr_methods.R:224 This formatting

message("tidySCE says: A data frame is returned for 
        independent data analysis.")
results in quasi-arbitrary formatting for output, where the white space introduced for programmatic convenience is echoed literally to the user

tidySCE says: A data frame is returned for
            independent data analysis.
Rely on message()'s internal use of paste0() or, if precise formatting is important, use strwrap()

message(
    "tidySCE says: A data frame is returned for ",
    "independent data analysis."
)
or (presummable in a helper function for re-use across your code)

txt <- paste(
    "tidySCE says: A data frame is returned for ",
    "independent data analysis."
)
message(paste(strwrap(txt, exdent = 4), collapse = "\n"))

- [x] dplyr_methods.R:622 long lines of piped code and nested conditional tests are unreadable. Reformat, e.g.,

tst <- intersect(
    cols %>% 
        names(), 
    get_special_columns(.data) %>% 
        c(get_needed_columns())) %>% 
        length() %>% 
        gt(0)
    )
if (tst) {

- [x] (why do you write c(get_needed_columns())) instead of get_needed_columns()?)

_this is a concatenation  "a" %>% c("b")_

- [x] In the stop() message immediately after, reconsider use of stop(sprintf()) and instead rely on stop()'s internal use of paste0()

columns <- 
    get_special_columns(.data) %>% 
    c(get_needed_columns()) %>% 
    paste(collapse=", ")
stop(
    "tidySCE says: you are trying to rename a column that is view only ",
    columns,  " ",
    "(it is not present in the colData). If you want to mutate a view-only",
    "column, make a copy and mutate that one.", 
)

- [x] For such long messages adopting a strwrap() discipline as outlined above would seem to be highly desireable.

_For the moment we have adopted the stop paste0 function suggested above. In the future this will be an area of improvement._

- [x] dplyr_methods.R:775 this code is repeated several times. Write a function instead to remove code duplication.

_the code is similar but not identical_

- [x] dplyr_methods.R:1146 it should not be necessary to preface functions with their package names; I don't think this helps readability of the code.

_I understan the concern, however since I am overwriting some tidyverse function this helps some inconsistencies. We plan to improve the code clarity as the pakage matures_

- [ ] methods.R:3 it's strange to see a class definition at the top of a file called 'methods.R'; a more common organization would give the file the name of the class -- tidySCE.R. The Bioconductor / S4 convention (this is an S4 class, after all...) would name this class TidySCE, and perhaps further recognizing the imporance of being clear to the user and that the user will seldom have to type out the word in it's entirety (e.g., because of autocompletion in RStudio) it would be better to name the class explicitly TidySingleCellExperiment.

We agree, we wait to create this file once the package name has been settled (first point in the review list).

- [x] methods.R:106 highly nested calls like this are just too complicated for the user to parse. Adopt a more procedural programming style with less nesting.

**MAN**

- [x] not sure what the figures/ directory is doing here?

_It's used for the figures in the README, as here: https://r-pkgs.org/whole-game.html_

**Comment by stemangiola** [comment]
Hello @mtmorgan 

> Please push your changes to the Bioconductor git repository to trigger a build report.

Done

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/stemangiola.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tidySummarizedExperiment")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tidySummarizedExperiment

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
