### ISSUE TITLE
GRridge

### ISSUE THREAD

**Issue by putriwikie** [Bioconductor/Contributions#164]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/markvdwiel/GRridge

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by vobencha** [comment]
@putriwikie , why so many commits with errors? Are you running R CMD build and R CMD check locally before you commit to git? These vignette errors would be caught if you checked your local copy. 

Valerie

**Comment by putriwikie** [comment]
@vobencha I fixed some points and I have checked locally also. It seems fine. I hope it goes well in this current version.

**Comment by vobencha** [comment]
Hi,

Nice job with the documentation. The man pages and vignette are comprehensive and informative. Please see comments and suggestions below.

(1) Please address these R CMD build / check issues:

* checking S3 generic/method consistency ... WARNING
predict:
  function(object, ...)
predict.grridge:
  function(grr, datanew, printpred, dataunpennew, responsetest,
           recalibrate)

* checking Rd \usage sections ... NOTE
S3 methods shown with full name in documentation object 'predict.grridge':
  'predict.grridge'

The \usage entries for S3 methods should use the \method markup and not
their full name.
See chapter 'Writing R documentation files' in the 'Writing R
Extensions' manual.

* checking data for ASCII and uncompressed saves ... WARNING
 
  Note: significantly better compression could be obtained
        by using R CMD build --resave-data
                    old_size new_size compress
  dataFarkas.rda       3.4Mb    2.5Mb    bzip2
  dataWurdinger.rda    6.8Mb    4.1Mb    bzip2

(2) Package size

The built tarball should occupy < 4MB on disk. See section 'Correctness Space and Time':
http://www.bioconductor.org/developers/package-guidelines/The package is currently 14MB:
~/proj >du -h GRridge_0.99.10.tar.gz
14M    GRridge_0.99.10.tar.gz

(3) Add testthat to Suggests in DESCRIPTION

(4) data man pages

The primary pages for the data sets are well documented. The individual man pages for the objects are not as complete and I don't think you need them. I would suggest one man page per .Rda object. For example, remove these:

CpGannFarkas.Rd, datcenFarkas.Rd, respFarkas.Rd

and add these alias entries to dataFarkas.Rd:

\alias{CpGannFarkas}
\alias{datcenFarkas}
\alias{respFarkas}

On the main page (dataFarkas.Rd) mention if you've done any curation or QC of the data - have they been manipulated in any way, etc.

(5) vignette

i) Remove the undefined \para commands in the .Rnw file. These sectioning commands are AFAIK not necessary and rarely used in regular LaTeX documents.

ii) Please remove all files except GRidge.Rnw and preamble.tex. The vignette is generated automatically when R CMD build is run and we don't want the vignette products checked into svn.

iii) The package should take <= 5min to run R CMD check --no-build-vignettes. GRidge takes substantially longer (30 minutes and still going) Please use a smaller subset of data for the vignette examples or change parameters to a less intensive search etc.

Valerie

**Comment by putriwikie** [comment]
Hi @vobencha 

Thank you for the suggestions. I have updated the package as you suggested. However, I still have one error related to latex. 

"Error: running 'texi2dvi' on 'GRridge.tex' failed"

When I tried to compile " GRridge.RNW" to pdf, it worked fine. But it doesn't pass the R CMD check 
Do you have any suggestion to handle such error?

Thank you in advance.
Putri

**Comment by vobencha** [comment]
There have been so many commits I've lost track of where we are. Have you addressed the issues raised in https://github.com/Bioconductor/Contributions/issues/164#issuecomment-256339512? If yes, please describe the changes made, what points were addressed, which weren't etc.

Valerie

**Comment by putriwikie** [comment]
We have addressed the comments ((1)-(5)). However, we still get a warning related to man file for predict.grridge

* checking S3 generic/method consistency ... WARNING
predict:
  function(object, ...)
predict.grridge:
  function(grr, datanew, printpred, dataunpennew, responsetest,
           recalibrate)

**Comment by vobencha** [comment]
The first argument to the predict() function must be called 'object'. This is defined in the generic and cannot be changed. Modify predict.grridge() such that the first arg is called 'object' and not 'grr'.

Also you need to change this alias in the man page:
\alias{predict.grridge.predict.grridge}

to this:
\alias{predict.grridge}

Valerie

**Comment by putriwikie** [comment]
@vobencha I modified the man and R file for the predict.grridge. 
There is still a warning, which stated that i need to add \alias(grridge) to the man file. However, if I added \alias(grridge), i will get another warning regarding the duplication of the function (i.e. grridge)

**Comment by vobencha** [comment]
The predict.grridge.Rd man page documents predict.grridge yet you have grridge in the \usage section. This belongs on the grridge.Rd man page (which it already is). Remove it from predict.grridge.Rd and the warning should go away.

If a function already exists as an S3 generic it's fine to write an S3 method for it; this is the case with predict(). However, S3 is the old style of method dispatch and has been replaced with S4. We don't encourage creating new S3 generics and methods. I believe grridge.cv ()is a different function from grridge() and not intended to be an S3 method. The use of the '.' in the function name is confusing because this is the traditional method of S3 dispatch. Please rename grridge.cv with camelCase or underscore (e.g., grridgeCV or grridge_cv) to avoid confusion.

Thanks.
Valerie

**Comment by lshep** [comment]
The "abnormal" is an error on our end from updating the single package builder. Once the update is complete I will manually kick off a build of your package

**Comment by putriwikie** [comment]
i updated the package. I followed your suggestion regarding the predict.grridge in the man file. I also changed grridge.cv into grridgeCV. 
However, another error regarding texi2pdf occured. Does this error have some thing to do with the updated single package builder in Bioconductor? 
Moreover, I didnt have this error when I locally checked our package.

Best, Putri

**Comment by lshep** [comment]
We are looking into the tokay2 texi2pdf error.

**Comment by lshep** [comment]
I am rerunning your build the abnormal was my fault.  We are still working on trying to figure out the texi2pdf ERROR that is occurring.

**Comment by vobencha** [comment]
I'm accepting this package. The texi2pdf error on the windows builder is our problem.

You will get an email in the next week with svn credentials and next steps. Thanks for your patience with the review process while we were sorting out problems with the new builders.

Valerie

**Comment by putriwikie** [comment]
Hi @vobencha 

We thank for the acceptance. We also thank for your guidance during the review process. We very much appreciate it. 

Best, Putri
