### ISSUE TITLE
NanoMethViz

### ISSUE THREAD

**Issue by Shians** [Bioconductor/Contributions#1647]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shians/NanoMethViz
Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment]
Hi Shians, @Shians 
Please fix the errors in the package. 

```
** libs
"C:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"C:/Users/BIOCBU~1/BBS-3~1.12-/R/include" -DNDEBUG  -I'C:/Users/biocbuild/bbs-3.12-bioc/R/library/Rcpp/include'   -I"C:/extsoft/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"C:/Users/BIOCBU~1/BBS-3~1.12-/R/include" -DNDEBUG  -I'C:/Users/biocbuild/bbs-3.12-bioc/R/library/Rcpp/include'   -I"C:/extsoft/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c convert_methy_to_dss.cpp -o convert_methy_to_dss.o
In file included from convert_methy_to_dss.cpp:1:
convert_methy_to_dss.hpp:24:5: error: 'uint' does not name a type; did you mean 'uInt'?
     uint total=0;
     ^~~~
     uInt
convert_methy_to_dss.hpp:25:5: error: 'uint' does not name a type; did you mean 'uInt'?
     uint methylated=0;
     ^~~~
     uInt
convert_methy_to_dss.cpp: In function 'void flush_data(const std::unordered_map<std::__cxx11::basic_string<char>, std::map<GenomicPos, MethyCount> >&, const string&)':
convert_methy_to_dss.cpp:69:35: error: 'const struct MethyCount' has no member named 'total'
                 << m_count.second.total << "\t"
                                   ^~~~~
convert_methy_to_dss.cpp:70:35: error: 'const struct MethyCount' has no member named 'methylated'
                 << m_count.second.methylated << "\n";
                                   ^~~~~~~~~~
convert_methy_to_dss.cpp: In function 'std::vector<std::__cxx11::basic_string<char> > convert_methy_to_dss_cpp(std::__cxx11::string, std::__cxx11::string)':
convert_methy_to_dss.cpp:101:37: error: 'std::map<GenomicPos, MethyCount>::mapped_type' {aka 'struct MethyCount'} has no member named 'total'
         sample_data[e.sample][gpos].total++;
                                     ^~~~~
convert_methy_to_dss.cpp:103:41: error: 'std::map<GenomicPos, MethyCount>::mapped_type' {aka 'struct MethyCount'} has no member named 'methylated'
             sample_data[e.sample][gpos].methylated++;
                                         ^~~~~~~~~~
make: *** [C:/Users/BIOCBU~1/BBS-3~1.12-/R/etc/x64/Makeconf:229: convert_methy_to_dss.o] Error 1
ERROR: compilation failed for package 'NanoMethViz'
* removing 'C:/Users/pkgbuild/AppData/Local/Temp/RtmpyYdSy8/Rinst2be07f971996/NanoMethViz'
      -----------------------------------
ERROR: package installation failed
```

Thanks!

**Comment by Shians** [comment]
Ah sorry, I missed the instruction on how to trigger a new build on BioC.

**Comment by LiNk-NY** [comment]
Hi Shian, @Shians 
Push to this location: 

git@git.bioconductor.org:packages/NanoMethViz 

to trigger a new build

Make sure you have an 'upstream' remote. 

git remote add upstream git@git.bioconductor.org:packages/NanoMethViz

**Comment by LiNk-NY** [comment]
Hi Shian, @Shians 

Thank you for your submission. 
Please see the review below. 
If you have any questions, feel free to comment below. 
Be sure to respond to the review line by line.

Best, 
Marcel 

---

# NanoMethViz #1647

* Overall, the coding looks good and neatly written.
* Remove / untrack the `*.Rproj` file
* Add a `NEWS.md` file
* Add a tests folder to enhance robustness.

## DESCRIPTION

* Provide at least a three sentence `Description` in the DESCRIPTION file
(`BiocCheck` Note)
* Do you need to depend on `magrittr` when you have `dplyr` imported?

## NAMESPACE

* Looks good for using the `snake_case` style.
* Perhaps you can combine `get_exons*` and make them differ by arguments (same
with `plot_agg_regions*` and `query_exons_*`)?
* It looks like `load_example_nanomethresult` should be more of a
`data(nanometh)` call.
* It may be better to avoid importing from `glue` and `rlang` if you are only
using one function / object from those packages.

## vignettes

* Include an `Installation` instructions section.
* Try to stick to the 80 character width limit. It's useful for the reviewer
and for maintenance (esp. when you have multiple scripts open on the screen).

## R

* Interesting use of `readr::cols_only`. It's a good way to ensure type.
* If these files are standardized, it makes sense to use a certain combination
of column names in `guess_methy_source`.
* Consider checking the sub directories exist before using `file.create` in
`convert_methy_format`.
* Avoid using `library` inside a function. Try `loadNamespace` or
`requireNamespace`.
* Both `get_exons_*` functions are quite similar. Consider combining these.
* Allow users to opt out of the verbosity from functions such as
`methy_to_bsseq`.
* Why create a generic `plot_gene` and `plot_region` functions? Why not a
plain functions like `plot_grange`?

**Comment by Shians** [comment]
> Hi Shian, @Shians
> 
> Thank you for your submission.
> Please see the review below.
> If you have any questions, feel free to comment below.
> Be sure to respond to the review line by line.
> 
> Best,
> Marcel
> 
> # NanoMethViz #1647
> * Overall, the coding looks good and neatly written.

Thank you!

> * Remove / untrack the `*.Rproj` file

Done

> * Add a `NEWS.md` file

Done

> * Add a tests folder to enhance robustness.

This will be done in the future, but I'm a bit time constrained so at the moment I'm relying on examples the the vignette.

> ## DESCRIPTION
> * Provide at least a three sentence `Description` in the DESCRIPTION file
>   (`BiocCheck` Note)

Done

> * Do you need to depend on `magrittr` when you have `dplyr` imported?

Thanks, the import of `%>%` has been switched to dplyr.


> ## NAMESPACE
> * Looks good for using the `snake_case` style.
> * Perhaps you can combine `get_exons*` and make them differ by arguments (same
>   with `plot_agg_regions*` and `query_exons_*`)?

Keeping them separate was easier for me to keep track of the logic. plot_agg_regions_* would require more serious effort to refactor. But I can put in a query_exons wrapper and some refatoring to use argument. Thanks for the suggestion.

> * It looks like `load_example_nanomethresult` should be more of a
>   `data(nanometh)` call.

One of the components of the object is a path to the internal file, which I don't know if I can store in a saved .RData object since the path will differ for every user. That's why the function constructs it on the spot rather than loads an .RData, which I think would be necessary to make `data()` calls work.

> * It may be better to avoid importing from `glue` and `rlang` if you are only
>   using one function / object from those packages.

`glue` is pretty lightweight and really improves my code readability. .data from `rlang` is necessary for evading checks complaining about the non-standard evaluation in tidyverse functions. If I find a strategy to get around these in the future I would also like to trim down dependencies.


> ## vignettes
> * Include an `Installation` instructions section.

Is this common practice? I am relying on the installation instructions on the BioC page. In my mind the use case would be people finding the package on BioC website or through my Github, both of which have installation instructions already. If I add installation instructions do you think it should be its own vignette or at the top of each of my vignettes?

> * Try to stick to the 80 character width limit. It's useful for the reviewer
>   and for maintenance (esp. when you have multiple scripts open on the screen).

Will do for the future.

> ## R
> * Interesting use of `readr::cols_only`. It's a good way to ensure type.
> * If these files are standardized, it makes sense to use a certain combination
>   of column names in `guess_methy_source`.
> * Consider checking the sub directories exist before using `file.create` in
>   `convert_methy_format`.

Done

> * Avoid using `library` inside a function. Try `loadNamespace` or
>   `requireNamespace`.

This is an issue in the annotation packages where simply grabbing from the namespace doesn't work. Library is the only way I have gotten this to work, it's an annoying situation that I'm trying to resolve.

> * Both `get_exons_*` functions are quite similar. Consider combining these.

Will do soon.

> * Allow users to opt out of the verbosity from functions such as
>   `methy_to_bsseq`.

At the moment because everything is directed through R messages this can be done using suppressMessages. Implementing a verbosity function myself would require threading a new argument through a lot of internal functions and C++ code which is quite a lot of effort, I'll implement this if there is high demand for it in the future.

> * Why create a generic `plot_gene` and `plot_region` functions? Why not a
>   plain functions like `plot_grange`?

I think the design started out with the intention to handle different types of representations of methylation instead of the current centralised object. I could refactor this now that the design is more concrete.

**Comment by LiNk-NY** [comment]
Hi Shian, @Shians 

> > * Include an Installation instructions section.

> Is this common practice? I am relying on the installation instructions on the BioC page. In my mind the use case would be people finding the package on BioC website or through my Github, both of which have installation instructions already. If I add installation instructions do you think it should be its own vignette or at the top of each of my vignettes?

Yes, this is common practice. Sometimes the vignette is linked to from the internet so it's good to have that there. 
It should be a small section at the top of your main vignette. 

> > Avoid using library inside a function. Try loadNamespace or requireNamespace.

> This is an issue in the annotation packages where simply grabbing from the namespace doesn't work. Library is the only way I have gotten this to work, it's an annoying situation that I'm trying to resolve.

Perhaps `require` would work? It almost the same as `library` but meant for using inside a function.

> > * Allow users to opt out of the verbosity from functions such as methy_to_bsseq.

> At the moment because everything is directed through R messages this can be done using suppressMessages. Implementing a verbosity function myself would require threading a new argument through a lot of internal functions and C++ code which is quite a lot of effort, I'll implement this if there is high demand for it in the future.

It would be helpful to have a built-in option and provide users the ability to turn off messages in the top-level function call rather than using an ad hoc solution. 

Best,
Marcel

**Comment by Shians** [comment]
@LiNk-NY Hi Marcel,

I've added the installation instructions, verbose arguments and changed `library()` calls to `require()`. Thanks for your feedback!

Shian

**Comment by LiNk-NY** [comment]
Hi Shian, @Shians 
Thanks for making those changes. Please resolve the error in the build report. 
It looks like there may be a stray `verbose` object in the code.
Best,
Marcel

**Comment by LiNk-NY** [comment]
Thanks for making those changes. It looks like the `ERROR`s occur because of the changes to the support site at the same time the testing was going on. I will accept the package. 
Thank you for your contribution @Shians

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Shians.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("NanoMethViz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NanoMethViz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
