### ISSUE TITLE
TimeScape Contribution

### ISSUE THREAD

**Issue by maiasmith** [Bioconductor/Contributions#167]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/maiasmith/timescape

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by maiasmith** [comment]
I've fixed the error (just a subscription to bioc-devel) - can I re-submit this package now?

**Comment by mtmorgan** [comment]
yes, if you have [set up the web hook][1] then bump the version to trigger a re-build.

[1]: https://github.com/Bioconductor/Contributions#adding-a-web-hook

**Comment by mtmorgan** [comment]
# 23 December, 2016

I'm sorry to be negligent in reviewing these exciting packages.

I agree with Michael that more rigorous data modeling would be
appropriate, but do no wish to hold up processing this package
further. I offer the following suggestions:

DESCRIPTION

- Please provide a more descriptive Description: paragraph, like a
  paper abstract providing the user with a more extensive introduction
  to what this package does, and why they might wish to use it over
  alternatives.
- Consider adding more refined biocViews

NAMESPACE

- OK

R

- `stop(paste(...))` is generally redundant, `stop("foo ", "bar")`
  pastes the result to `"foo bar"`.

man

- Use standard R nomenclature, e.g., `character()` rather than
  `{String}`
- Consider using `@rdname` or `@describeIn` to group functions,
  especially 'internal' functions, onto a single man page clearly
  marked as not meant for end users.

vignettes

- Please update installation instructions to reflect how the package
  will be installed for a _Bioconductor_ user, i.e.,
  `biocLite("timescape")`
- The vignette is minimal; provide the user with insight into how data
  must be structured, and guidance on how to create effective
  visualizations.

misc

- please clean up the repository so that build artifacts (e.g., vignette html & R files) are not included.

**Comment by mtmorgan** [comment]
To elaborate on the vignette comments. The visualization tools provided by the package are really great. To use the tools requires highly structured data. It is therefore essential to provide an unambigous path from the original data source(s) to the inputs used in your functions.

The vignette is a great place to do this -- provide details on how one obtains the inputs `AML_tree_edges.csv`, `AML_clonal_prev.csv`, `AML_mutations.csv`. Preferably, these steps use or highlight _R_ processing and _Bioconductor_ tools.

Well-supported _Bioconductor_ concepts should emphasize _Bioconductor_ tools ad data representations. Typical examples include working with called variants (parsing VCF files with [VariantAnnotation](https://bioconductor.org/packages/VariantAnnotation)) and genomic ranges (`GRanges` objects from the [GenomicRanges](https://bioconductor.org/packages/GenomicRanges) package), and coordinated management of assays and sample phenotypic data (`SummarizedExperiment` from the [SummarizedExperiment](https://bioconductor.org/packages/SummarizedExperiment) package).

**Comment by maiasmith** [comment]
Hi Martin,

Thanks for your enthusiasm. I'm working through these, starting with
TimeScape. I believe I have addressed all your points with regard to this
package. Please let me know if this has passed the test!

Also, I've greatly updated the vignette, but am forgetting how to build it
such that the docs folder appears with the vignette inside...?

Best,

Maia

**Comment by mtmorgan** [comment]
Thanks Maia for your work. The usual protocol is to build then install
```
R CMD build timescape
R CMD INSTALL timescape_0.99.5.tar.gz
```
The `build` command creates the vignette. Your git repository does not need to (should not) have an inst/docs folder. You can also use [devtools](https://cran.r-project.org/package=devtools) and, when `cwd()` is somewhere inside your package source directory, `install(build_vignettes=TRUE)`.

**Comment by maiasmith** [comment]
Thanks Martin.

I believe I have made corrections for the three packages: TimeScape,
MapScape and CellScape. Please keep me posted on the status of these.

Best,
Maia

**Comment by mtmorgan** [comment]
Thank you for the updates. I have the remaining concerns that I hope you can easily address.

## vignette

Please continue to provide more information on the upstream work flow.

- Link to software source code for PyClone and to CITUP.
- Provide explicit instructions for use of this software, e.g., the
  format of the original (raw) data and the exact commands /
  configuration variables used to create the data analyzed in this
  package.
- The exact relationship between the output files of these programs
  and the input files used by your software.

## Other

Please review files in the repository, especially top level, to
include only those that are required for the pacakge. E.g., `3q` and
the `*png` files seem like strays.

## man (Optional)

The man pages are formatted in a fairly ad-hoc way, so that their
presentation is not really optimal. For instance white space is
compressed so this relatively legible specification
  
```
#' @param clonal_prev (Data Frame) Clonal prevalence. Note: timepoints will be alphanumerically sorted in the view.
#'   Format: columns are (1) character() "timepoint" - time point
#'                       (2) character() "clone_id" - clone id
#'                       (3) numeric() "clonal_prev" - clonal prevalence.
```

is displayed as

```
clonal_prev: (Data Frame) Clonal prevalence. Note: timepoints will be
          alphanumerically sorted in the view. Format: columns are (1)
          character() "timepoint" - time point (2) character()
          "clone_id" - clone id (3) numeric() "clonal_prev" - clonal
          prevalence.
```

Improvements would

- use \code{data.frame} (standard R terminology, rather than Data
  Frame), \code{character()} etc. to mark up R code.
- use \describe{} to create a descriptive list of parameters.
- elaborate on details of each column.

For instance

```
#' @param clonal_prev \code{data.frame} Clonal prevalence. Required
#'     columns are:
#'     \describe{
#'
#'       \item{timepoint:}{\code{character()} time point. Time
#'          points will be alphanumerically sorted in the view.}
#' 
#'       \item{clone_id:}{\code{character()} clone id.}
#' 
#'       \item{clonal_prev:}{\code{numeric()} clonal prevalence.}
#'
#'     }
```

Likewise in the Details section.

```
#' Interactive components:
#'   \enumerate{
#' 
#'     \item Mouseover any clone to view its (i) clone ID and (ii) clonal
#'     prevalence at each time point.
#' 
#'     \item Click the view switch button to switch from the traditional
#'     timescape view to the clonal trajectory view, where each clone
#'     changes prevalence on its own track.
#' 
#'     \item Click the download buttons to download a PNG or SVG of the
#'     view.
#' 
#'   }
```
  
Please also consider line width in the man page (suggested maximum: 80
columns), especially the examples. For instance, in a standard 80
column terminal (yes, old-school, but not an uncommon way of using R)
the examples currently wrap in an ugly way

```
     # EXAMPLE 1 - Acute myeloid leukemia patient, Ding et al., 2012
     
     # genotype tree edges
     tree_edges <- read.csv(system.file("extdata", "AML_tree_edges.csv", package
 = "timescape"))
```

They are more readable with

```
#' @examples
#'
#' # EXAMPLE 1 - Acute myeloid leukemia patient, Ding et al., 2012
#'
#' # genotype tree edges
#' tree_edges <- read.csv(system.file("extdata", "AML_tree_edges.csv",
#'     package = "timescape"))
```

**Comment by mtmorgan** [comment]
Also, be sure to remove 'hidden' files like .DS_store in the root and vignettes directory.

**Comment by maiasmith** [comment]
Hi Martin,

Could you please provide clarification as to what kind of description is
necessary for the data preparation? A full description of how to use
PyClone and CITUP is quite intensive, the subject of numerous supplemental
pages in both papers.

I'm CC'ing Andrew McPherson, a developer of CITUP, who will help me develop
an appropriate description of the methods, but is seeking further
clarification on the requirements here.

Best,
Maia

**Comment by mtmorgan** [comment]
Sorry for my slow response. I'm not looknig for anything too elaborate, a 'paragraph' that tells the user what the starting data were, what commands and parameter values were used, and what output file and additional processing were needed to make it appropriate for input into your package.

Please don't forget the version bump when you're ready.

**Comment by mtmorgan** [comment]
@maiasmith I wasn't exactly sure where we stand on this. I do not see revisions to the vignette since you asked for clarification, but I am willing to accept the packages as they now stand. If of course you have revisions that you are about to submit then I will wait for them...

**Comment by maiasmith** [comment]
Hi Martin,

I updated the "Obtaining the data" section for Time/Map/CellScape packages,
as you requested. Can you see it? In TimeScape, it should be a paragraph
that begins as so: "E-scape takes as input a clonal phylogeny and clonal
prevalences per clone per sample."

Please let me know if you see otherwise!

Maia

**Comment by mtmorgan** [comment]
Sorry I some how misinterpreted those commits. I'm accepting these packages; they will be added to the Bioconductor svn repository and nightly builds in the next day or so, with more information forwarded when that is done.

**Comment by mtmorgan** [comment]
And thanks both for your contribution and patience!

**Comment by maiasmith** [comment]
Hi Martin,

Looks like the packages are out now - great!

However, when I try to install them, I am receiving an error - is this
something I'm doing wrong, or something wrong with the packages?


> source("https://bioconductor.org/biocLite.R")
> biocLite("timescape")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.3), R 3.3.2 (2016-10-31).
Installing package(s) ‘timescape’
Warning message:
package ‘timescape’ is not available (for R version 3.3.2)

Best,
Maia

**Comment by maiasmith** [comment]
I've now tried with Bioconductor 3.4 and it still doesn't work:

> source("http://bioconductor.org/biocLite.R")
Bioconductor version 3.4 (BiocInstaller 1.24.0), ?biocLite for help
> biocLite("mapscape")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.4 (BiocInstaller 1.24.0), R 3.3.2 (2016-10-31).
Installing package(s) ‘mapscape’
Warning message:
package ‘mapscape’ is not available (for R version 3.3.2)

**Comment by mtmorgan** [comment]
Packages are added to the 'bioc-devel' branch, which is currently 'Bioc 3.5' and 'R-devel'. Bioc 3.5 will become the next release some time in April, at about the time 'R-devel' is released as R-3.4.0. See [here](http://bioconductor.org/developers/how-to/useDevel/).

**Comment by maiasmith** [comment]
Hi Martin,

Thanks for your previous response, I managed to get the bioc-devel branch
up and running thanks to your help.

One further question - I'm not sure I follow how to update my software. I
made a small change to the vignette in my cellscape repo on github
(maiasmith), however this will not translate to the bioc devel version of
my package because I'm missing which steps? The instructions I received in
my email refer to the svn repo, but I require a username and password for
this, which I'm not sure I have? Also, I would prefer to perform changes
through git, if possible, as I've never used svn before. Can I simply push
changes to the https://github.com/Bioconductor-mirror/cellscape repo?

Best,

Maia

**Comment by mtmorgan** [comment]
No unfortunately you need to arrange for your changes to be in the bioconductor svn repository, perhaps following the instructions at http://bioconductor.org/developers/how-to/git-mirrors/ . The basics of svn are at http://bioconductor.org/developers/how-to/source-control/ . The svn username and password were included in the email you reference above; same username / password for each package. contact me directly martin.morgan at roswellpark.org if you need the user name / password again. Better to ask on the [bioc-devel][] mailing list, so others benefit / can help.

[bioc-devel]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
