### ISSUE TITLE
CellScape Contribution

### ISSUE THREAD

**Issue by maiasmith** [Bioconductor/Contributions#168]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/maiasmith/cellscape

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by lawremi** [comment]
Needs to use Bioconductor data structures for representing these common data types. Then it could just use `aggregate,Vector()` instead of the dplyr stuff.

**Comment by mtmorgan** [comment]
I'm sorry to be negligent in reviewing these exciting packages.

I agree with Michael that more rigorous data modeling would be
appropriate, but do no wish to hold up processing this package
further. I offer the following suggestions:

- Please bump the package version to trigger a build that reflects
  your updated changes.

- Please update this package in line with the comments for timescape,
  with respect to DESCRIPTION and vignette, R, and man pages.

**Comment by mtmorgan** [comment]
Seems like CellScape is waiting for a version bump?

**Comment by maiasmith** [comment]
Thanks, Martin. Done.

**Comment by mtmorgan** [comment]
Thanks for the updates

## vignette

- The vignette installs cellscape from bitbucket, but that step should
  be removed since the package will already be installed on the user
  computer via _Bioconductor_.
- Please provide explicit details about how the user is to prepare
  data for use by your software.

## other

- as with cellscape, please clean up unnecessary files in the
  top-level and vignettes directory.
- please also consider carefully formatting the man page.
