### ISSUE TITLE
MapScape Contribution

### ISSUE THREAD

**Issue by maiasmith** [Bioconductor/Contributions#169]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/maiasmith/mapscape

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by lawremi** [comment]
With data this complex, formal data structures are a must.  Nobody likes `gsub()` anymore.

**Comment by maiasmith** [comment]
I've fixed the error (subscribed to Bioc-devel) - can I re-submit the package now? Where am I using gsub()?

**Comment by mtmorgan** [comment]
One last apology, and as before:

- Please bump the package version to trigger a build that reflects
  your updated changes.

- Please update this package in line with the comments for timescape,
  with respect to DESCRIPTION and vignette, R, and man pages.

**Comment by mtmorgan** [comment]
Thanks for the updates

## vignette

- Please elaborate, as for timescape on the user is to prepare data
  for use by your software.

## other

- as with cellscape, please clean up unnecessary files in the
  top-level and other directories.
- please also consider carefully formatting the man page.
