### ISSUE TITLE
BUMHMM

### ISSUE THREAD

**Issue by alinaselega** [Bioconductor/Contributions#170]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/alinaselega/BUMHMM

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by mtmorgan** [comment]
A formal review will be forthcoming, but I don't understand why this package is submitted to Bioconductor? In particular it makes no use of existing classes, so has no opportunity for integration into existing Bioconductor work flows. Why not just distribute this as a stand-alone package via github or other?

**Comment by alinaselega** [comment]
Hi Martin, 

Thank you for starting the review process! There were two errors identified during the build: one concerning the sign-up to the mailing list, which I have now done, and one about building the vignette. (I did not get either of those when running the checks locally on my machine.) I am currently at a conference but I will address this on Thursday once I am back.

Regarding your comment about the package not using the existing Bioconductor classes: the reason for this is that this computational pipeline refers to the higher modelling level of the structure probing data, which starts with already processed downstream files such as .fastq files etc. Our model takes as input the final output of a structure probing experiment; namely, coverage and drop-off count information. This information is then manipulated within a statistical framework, generating probabilities of modification. The downstream processing, which is, of course, important and challenging in itself, is not, however, the focus of our work, encapsulated in the BUM-HMM package. 

We felt that having our pipeline available as a Bioconductor package would be increasingly beneficial for the bioinformatic community. Firstly, our work was considered highly relevant and will appear in Nature Methods next month. Both us and the editors shared the opinion that the availability of a Bioconductor package accompanying the manuscript would dramatically increase the transparency and reproducibility of our work, given how widely the Bioconductor platform is used by the bioinformatic community. We therefore thought that more researchers would be able to use our model if it was available for downloading from Bioconductor, rather than only accessible from a GitHub repository.

Thank you,
Alina Selega

**Comment by lawremi** [comment]
Bioconductor is not just for hosting packages. It's a platform. For your package to be considered a "Bioconductor" package, it should integrate with Bioconductor. Every package encapsulates one step in a larger workflow, and the data structures are the glue.

**Comment by mtmorgan** [comment]
# 18 October, 2016

Hi -- my comment wasn't so much about the scientific merit -- that's
for the journals to decide -- but the technical merits, particularly
along the lines Michael indicates. To be more specific, the position x
sample data that you have would be represented by the
[SummarizedExperiment][1] package


```r
suppressPackageStartupMessages({
    library(BUMHMM)
    library(Biostrings)
    library(SummarizedExperiment)
})

dna = DNAString(sequence)
se <- SummarizedExperiment(
    list(
        coverage=as.matrix(covFile),
        dropoff_count=as.matrix(docFile),
        dropoff_rate=as.matrix(dorFile)
    ), colData=DataFrame(
        replicate=rep(c("control", "treatment"), each=3)
    ), rowData=DataFrame(
        nucl=Views(dna, successiveIRanges(rep(1, nchar(dna))))
    ))
colnames(se) <- LETTERS[1:6]
se
```

```
## class: SummarizedExperiment 
## dim: 1800 6 
## metadata(0):
## assays(3): coverage dropoff_count dropoff_rate
## rownames: NULL
## rowData names(1): nucl
## colnames(6): A B ... E F
## colData names(1): replicate
```

This representation makes the data very easy to work with, e.g.,


```r
controls <- se[, se$replicate == "control"]   # coordinated subsetting
head(assay(controls, 'coverage'))
```

```
##           A      B      C
## [1,] 382943 276113 135209
## [2,] 399211 280523 137706
## [3,] 403519 284622 140211
## [4,] 404242 287589 144656
## [5,] 404463 288348 147167
## [6,] 404506 288445 147687
```

```r
rowData(controls)[1:5,]
```

```
##   Views on a 1800-letter DNAString subject
## subject: TATCTGGTTGATCCTGCCAGTAGTCATATGCT...TTCCGTAGGTGAACCTGCGGAAGGATCATTA
## views:
##     start end width
## [1]     1   1     1 [T]
## [2]     2   2     1 [A]
## [3]     3   3     1 [T]
## [4]     4   4     1 [C]
## [5]     5   5     1 [T]
```

```r
apply(assay(se, 'dropoff_rate'), 2, median)
```

```
##           A           B           C           D           E           F 
## 0.001005071 0.001025182 0.003684315 0.001608314 0.001302076 0.003380141
```

The changes to your package might be fairly easy, e.g., replacing
function definitions that expect matrices with the more semantically
rich data structures of Bioconductor, e.g.,


```r
selectNuclPos <- function(se, Nc, Nt, t) {
    res <- BUMHMM::selectNuclPos(
        assay(se, "coverage"), assay(se, "dropoff_count"), Nc, Nt, t
    )
    List(res)
}

scaleDOR <- function(se, nuclSelection, Nc, Nt) {
    BUMHMM::scaleDOR(assay(se, "dropoff_rate"), nuclSelection, Nc, Nt)
}
```


```r
Nc <- Nt <- 3
nuclSelection <- selectNuclPos(se, Nc, Nt, 1)
nuclSelection
```

```
## List of length 3
## names(3): analysedC analysedCT computePosteriors
```

```r
assay(se, "scaled_dropoff_rate") <- scaleDOR(se, nuclSelection, Nc, Nt)
se
```

```
## class: SummarizedExperiment 
## dim: 1800 6 
## metadata(0):
## assays(4): coverage dropoff_count dropoff_rate scaled_dropoff_rate
## rownames: NULL
## rowData names(1): nucl
## colnames(6): A B ... E F
## colData names(1): replicate
```

Bioconductor has the notion of IRanges to describe intervals on the
number line, such as those returned by your `computeStretches()`. So
one might write


```r
computeStretches <- function(posteriors) {
    allNucleotides <- Reduce(union, posteriors)
    stretches <- BUMHMM::computeStretches(sort(allNucleotides))
    IRanges(
        start=vapply(stretches, "[[", integer(1), 1),
        end=vapply(stretches, "[[", integer(1), 2)
    )
}
```

with use, perhaps integrating with the SummarizedExperiment


```r
rng <- computeStretches(nuclSelection$computePosteriors)
DNAStringSet(Views(subject(rowData(se)$nucl), rng))
```

```
##   A DNAStringSet instance of length 2
##     width seq
## [1]  1747 TATCTGGTTGATCCTGCCAGTAGTCATATGC...GGAGAATTTGGACAAACTTGGTCATTTAGAG
## [2]    52 AACTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA
```
    
An alternative, fast, implementation of `computeStretches()` is


```r
computeStretches <- function(se, expt_idx) {
    lgl0 <- rowSums(assay(se, "coverage") > 1) == ncol(se)
    lgl1 <- assay(se, "dropoff_count")[, expt_idx, drop=FALSE] > 0
    IRanges(rowSums(lgl0 & lgl1) > 0)
}
computeStretches(se, se$replicate == "treatment")
```

```
## IRanges object with 2 ranges and 0 metadata columns:
##           start       end     width
##       <integer> <integer> <integer>
##   [1]         1      1747      1747
##   [2]      1749      1800        52
```

and similarly for the remainder of the functions in the vignette and
package.

These are the types of changes that are really required for your
package to be considered for Bioconductor. While I'm obviously an
expert, the above is not actually that much work, and I hope you
consider it worth while.

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by alinaselega** [comment]
Hi Martin,

Thank you for providing these very useful suggestions. I completely understand that it is much better for a new package to utilise existing functionality. This is my first Bioconductor package so I apologise for not being better informed. Having your suggestions at hand will be of great help and I will try my best to implement these changes as soon as I can.

Thank you,
Alina

**Comment by alinaselega** [comment]
To clarify this build, I wanted to make sure that the package now builds without errors, before I start implementing technical changes.

**Comment by mtmorgan** [comment]
If your package is ready for review, please bump the version to 0.99.1 to trigger a build that incorporates your changes.

**Comment by alinaselega** [comment]
Hi,

Since the last build half an hour ago, I've pushed again (commit f419fc5) with incrementing the version field to 0.99.3. This commit addresses some notes and warnings from the latest build. However, the new build has not been started automatically yet. I am not sure how long the delay can be?

Thanks,
Alina

**Comment by mtmorgan** [comment]
Hi @alinaselega it seems like github is not recording the commits; is the web hook still intact? If not, restablish and commit a version bump.

**Comment by alinaselega** [comment]
Thanks @mtmorgan, the web hook is fine but for some reason that last commit did not get delivered. I redelivered it and the build started now.

**Comment by alinaselega** [comment]
Hi @mtmorgan, 

Just to let you know that I have implemented the changes we discussed in this current version of the package. I hope that it now provides a more satisfactory level of integration with Bioconductor structures.

Thanks,
Alina

**Comment by mtmorgan** [comment]
Yes thank you for your changes I am marking this package as accepted. You'll here more in a couple of days. Thanks for your contribution!
