### ISSUE TITLE
flowGraph

### ISSUE THREAD

**Issue by aya49** [Bioconductor/Contributions#1703]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/aya49/flowGraph

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please correct the use of `Authors@R` --
```
Authors@R: person("Alice", "Yue", email = "aya43@sfu.ca", role = c("aut", "cre"))
```
There is no need for a `Maintainer:` field.

**Comment by aya49** [comment]
Corrected and committed, thank you :)!

**Comment by aya49** [comment]
[ ]: not sure what I should do about it
[x]: I did something about it
?: Will need to re-build to be sure if it's fixed

I made an attempt at the errors and warnings :D

errors:
- [x] inst/CITATION: removed author brackets
- [x] flowGraph example: future multicore does not work on Windows, changed example so so that it runs on one core.

warnings:
- [x] DESCRIPTION: Update R version dependency from 3.5 to 4.0.
- [x] DESCRIPTION/NAMESPACE consistency: added utils package to DESCRIPTION,  removed plotly from DESCRIPTION.
- [x] ? data compression: fg_data_fca.rda 241Kb (compression: xz); i could only get it down to 243Kb after xz compression ("save(fg_data_fcsa, file="...", compress="xz");")
- [x] data compression: fg_data_pos30.rda 9Kb (compression: bzip2)
- [x] ? Undocumented S4 methods: generic 'show' and siglist 'flowGraph'; I changed the roxygen documentation to have "#' @aliases show,flowGraph-method"... I hope it works...
- [x] ? Functions or methods with usage in documentation object 'show' but not in code: show; I changed the roxygen documentation to have "#' @usage \\method{show}{flowGraph}(x)" instead of just show... again not sure but hope it works.
- [ ] no function found corresponding to methods exports from flowGraph for: show; I exported the function, I swear D:, I'm not sure what's wrong, I'll have to come back to this.
- [ ] unknown macro '\insertRef': I googled this and it seems like it just has always been a warning, not sure if I should remove all my citations.
- [x] Avoid class() == or class() != ; use is() or !is(): fixed.
- [x] Add non-empty \value sections to the following man: done.
- [ ] 'rgl.init' failed, running with 'rgl.useNULL = TRUE'; I don't know what this is... (someone said to ignore: https://stat.ethz.ch/pipermail/bioc-devel/2016-February/008743.html)
- [ ] Package dependency in the DESCRIPTION is 'Deprecated': flowType; huh... I'll come back to this.

**Comment by LiNk-NY** [comment]
Hi Alice, @aya49 
You cannot depend on a deprecated package. Please either have the maintainer un-deprecate it immediately or submit flowTypeFilter first before you submit this package. 
The other option is to remove the flowType code entirely from the package. 
Thanks.

**Comment by aya49** [comment]
Hi Marcel,

Thank you for the comment, I removed the dependency on flowType and committed an updated version of flowGraph.

Alice

**Comment by LiNk-NY** [comment]
Hi Alice, @aya49 

I was reviewing your package but I see that you still mention `flowType` quite a lot in the package.
You haven't completely removed it. Please do so before the review can continue. 

Best regards,
Marcel

---

# flowGraph #1703

## DESCRIPTION

* Keep the `DESCRIPTION` file (and possibly other files) within the 80 column
width limit.
* Update the `Depends` field to have the `R (>= 4.0.0)` dependency.
* Consider reducing the number of imported packages (~23). If there are
packages where you only import one or two functions, consider using alternative
functionality.
* Remove `flowType` from the `Suggests` field.
* Remove any mentions of `flowType` from the package as it will confuse users
when they do not find the `flowType` package.

**Comment by aya49** [comment]
Hi Marcel,

Ok, I will completely remove flowType D:, the places where flowType is still mentioned are the unit tests but they are commented out, so I don't have to rewrite them after flowTypeFilter comes out, Roxygen documentations in flowGraph_constructor which I have commented out so it is not in the manual, also I mention it in the Vignette as a future option for input generation for completeness sake. Does that sound alright?

For the number of imported packages, the list is long, but as long as the user imports effsize, furrr, ggiraph, igraph, visNetwork, and stringr, all the other packages are automatically imported. I re-organized the DESCRIPTION file to reflect this. I got warnings from bioccheck to also import Rdpack, data.table, and gridExtra which I don't explicitly use but I don't mind adding if it's required.

**Comment by LiNk-NY** [comment]
Hi Alice, @aya49 

You can add all of those changes to a branch and merge that branch if and when `flowTypeFilter` is accepted to Bioconductor.
Currently, `flowType` is not an existing package from the build system perspective and should not be mentioned to avoid confusing users. 

> all the other packages are automatically imported.

Are you using functions from those packages? If not, I would remove them from the `Imports` field even if they're
imported lower in the dependency chain. 

Please commit your changes and bump the version so that we can see what warnings the package is getting from
`BiocCheck`.
Thanks!

-Marcel

**Comment by aya49** [comment]
Hi Marcel,

I've removed flowType mentions and commited to the repository.

I do use functions from them, so I kept them. I don't use functions from the data.table, Rdpack, and gridExtra packages though, but it's imported as per the warnings. 

For the version bump, I read the https://bioconductor.org/developers/how-to/version-numbering/ webpage and I bumped the version from 0.99.0 to 0.99.1, I wanted to confirm if that was what you meant?

Thank you,
Alice

P.S. Note the two messages I'm not sure about are:
- unknown macro '\insertRef'
- 'rgl.init' failed, running with 'rgl.useNULL = TRUE';

**Comment by LiNk-NY** [comment]
Hi Alice, @aya49 
I do not see the build report in the comments here. Did you push upstream to `git@git.bioconductor.org`? 
Thanks. 
-Marcel

**Comment by aya49** [comment]
Hi Marcel,

We're doing a conductor test so all our remote machines are turned off and I don't have access to push locally, so I will push hopefully by Thursday if not tomorrow night, fingers crossed.

Thank you for the help, and uber patience :)
Alice

**Comment by aya49** [comment]
hi marcel @LiNk-NY 

i wanted to follow up this issue and confirm the specifics on what i should do to move further with the submission :)

thank you,
alice

**Comment by LiNk-NY** [comment]
Hi Alice, 

As you may have noticed, we have been busy reviewing other packages that
were submitted in time for the release. Sorry for the delay.
I will review your package today. 
Best,
Marcel

**Comment by aya49** [comment]
thank you marcel! hope everything goes well with thise release cycle :)

**Comment by LiNk-NY** [comment]
Hi Alice, @aya49 

Please address these remarks from `R CMD check`: 

```
* checking DESCRIPTION meta-information ... NOTE
Malformed Title field: should not end in a period.
Non-standard license specification:
  Artistic-3.0
Standardizable: FALSE

* checking whether the namespace can be loaded with stated dependencies ... NOTE
Warning: no function found corresponding to methods exports from ‘flowGraph’ for: ‘show’

A namespace must be able to be loaded with just the base namespace
loaded: otherwise if the namespace gets loaded by a saved object, the
session will be unable to start.

Probably some imports need to be declared in the NAMESPACE file.

* checking R code for possible problems ... NOTE
fg_feat_node_exprop_new : <anonymous> : <anonymous>: no visible binding
  for global variable ‘ep_’
fg_plot_box: no visible binding for global variable ‘val’
fg_plot_box: no visible binding for global variable ‘ID’
fg_plot_box_set: no visible binding for global variable ‘val’
fg_plot_box_set: no visible binding for global variable ‘ID’
fg_plot_pVSdiff: no visible binding for global variable ‘log_p_value’
fg_plot_pVSdiff: no visible binding for global variable ‘cohensd_size’
fg_plot_pVSdiff: no visible binding for global variable ‘avg_count’
fg_plot_pVSdiff: no visible binding for global variable ‘phenotype’
fg_plot_pVSdiff: no visible binding for global variable ‘phenogroup’
fg_plot_qq: no visible binding for global variable ‘y’
fg_plot_qq: no visible binding for global variable ‘x’
fg_plot_qq: no visible binding for global variable ‘cohensd_size’
fg_plot_qq: no visible binding for global variable ‘phenotype’
fg_plot_qq: no visible binding for global variable ‘d_size’
fg_plot_qq: no visible binding for global variable ‘phenogroup’
flowGraph: ... may be used in an incorrect context: ‘fg_save_plots(fg,
  plot_path = paste0(path, "/plots"), ...)’
plot_gr: no visible binding for global variable ‘x’
plot_gr: no visible binding for global variable ‘y’
plot_gr: no visible binding for global variable ‘from.x’
plot_gr: no visible binding for global variable ‘to.x’
plot_gr: no visible binding for global variable ‘from.y’
plot_gr: no visible binding for global variable ‘to.y’
plot_gr: no visible binding for global variable ‘colour’
plot_gr: no visible binding for global variable ‘label’
plot_gr: no visible binding for global variable ‘from’
plot_gr: no visible binding for global variable ‘to’
plot_gr: no visible binding for global variable ‘label_long’
plot_gr: no visible binding for global variable ‘phenotype’
plot_gr: no visible binding for global variable ‘phenogroup’
Undefined global functions or variables:
  ID avg_count cohensd_size colour d_size ep_ from from.x from.y label
  label_long log_p_value phenogroup phenotype to to.x to.y val x y

* checking for code/documentation mismatches ... WARNING
Codoc mismatches from documentation object 'fg_save_plots':
fg_save_plots
  Code: function(fg, plot_path, plot_types = "node", interactive =
                 FALSE, adjust_custom = "byLayer", label_max = 10,
                 box_no = 20, paired = FALSE, logged = FALSE,
                 filter_adjust0 = 1, filter_es = 0, filter_btwn_tpthres
                 = 1, filter_btwn_es = 0, overwrite = TRUE, node_labels
                 = "NONE", ...)
  Docs: function(fg, plot_path, plot_types = "node", interactive =
                 FALSE, adjust_custom = "byLayer", label_max = 10,
                 box_no = 20, paired = FALSE, logged = FALSE,
                 filter_adjust0 = 1, filter_es = 0, filter_btwn_tpthres
                 = 1, filter_btwn_es = 0, overwrite = TRUE, ...)
  Argument names in code not in docs:
    node_labels
  Mismatches in argument names:
    Position: 15 Code: node_labels Docs: ...
```

**Comment by LiNk-NY** [comment]
Hi Alice, @aya49 

An important point that I must stress is that contributed packages should provide interoperability with
other Bioconductor packages. Currently, `flowGraph` does not do that. Can you please speak to
this? Thank you. 
See item number 8 here: https://www.bioconductor.org/developers/package-guidelines/#description

Best regards,
Marcel

---

# flowGraph #1703

* One of our major requirements for incoming software contributions is
interoperability with the Bioconductor ecosystem. What efforts have you
made to provide a seamless integration with recognized Bioconductor
data structures?
Please answer this question before the review can continue. Thank you.

## LICENSE

* I am not aware of an Artistic-3.0 License. Perhaps you meant to use
[Artistic-2.0](https://opensource.org/licenses/Artistic-2.0)?

## DESCRIPTION

* Keep the `DESCRIPTION` file (and possibly other files) within the 80 column
width limit.
* Update the `Depends` field to have the `R (>= 4.0.0)` dependency.
* Consider reducing the number of imported packages (~20). If there are
packages where you only import one or two functions, consider using alternative
functionality.

## NAMESPACE

* Do the functions written require an `fg` prefix? If these are methods,
you may not need a prefix.
* Consider renaming some functions with general names (e.g., `*load`, `*merge`)




---
# flowGraph #1703

* One of our major requirements for incoming software contributions is
interoperability with the Bioconductor ecosystem. What efforts have you
made to provide a seamless integration with recognized Bioconductor
data structures?
Please answer this question before the review can continue. Thank you.

## LICENSE

* I am not aware of an Artistic-3.0 License. Perhaps you meant to use
[Artistic-2.0](https://opensource.org/licenses/Artistic-2.0)?

## DESCRIPTION

* Keep the `DESCRIPTION` file (and possibly other files) within the 80 column
width limit.
* Update the `Depends` field to have the `R (>= 4.0.0)` dependency.
* Consider reducing the number of imported packages (~20). If there are
packages where you only import one or two functions, consider using alternative
functionality.

## NAMESPACE

* Do the functions written require an `fg` prefix? If these are methods,
you may not need a prefix.
* Consider renaming some functions with general names (e.g., `*load`, `*merge`)

**Comment by aya49** [comment]
hi marcel,

interoperability: the package conducts downstream analysis for flow cytometry data. input flow cytometry data is stored in an S4 class from the flowCore package which also does all the pre-processing. then taking this S4 object as input, flowType is used as one of the many many cell population phenotype identification tools. flowGraph previously depended on flowType's Phenotypes object as input, but now it takes a generic matrix as input since flowType is going to get replaced with flowTypeFilter which is not available at the moment. so flowGraph is now kind of stand-alone during this time of transition.

Non-standard license specification: Artistic-3.0, I've seen Artistic-2.0, is 3.0 not allowed?

Warning: no function found corresponding to methods exports from ‘flowGraph’ for: ‘show’: i've been trying to trouble shoot this for some time, we'll see how it goes

no visible binding: these are ggplot2 data frame columns, they do come out weird for the checks

WARNING: Update R version dependency from 4.0 to 4.1.: but i guess i should keep it to 4.0 for this issue because when i update it to 4.1 i get an error instead?

I'll edit as i go

thank you!
alice

**Comment by aya49** [comment]
i changed the license from Artistic 3.0 to 2.0

**Comment by LiNk-NY** [comment]
Hi Alice, @aya49 

Thank you for following up. 
Perhaps `flowGraph` should be submitted after the `flowTypeFilter`. 
See the rest of the review below. 

Best,
Marcel 

---


## R

* Remove any commented code in `.R` files.
* Avoid any `.onLoad` hooks for data in `00_data.R`.
* Default arguments to writing files should be `FALSE` or files should
be saved to the `tmp` directory via `tempdir`
* In general, graphics should not be saved to the user's system. Users should
be allowed to choose their own format.
* What is the reasoning for saving data as `.rds`? Wouldn't it suffice to
save the entire object if you will be using R to load the `.rds` files anyway?
(`fg_save` and `fg_load`)
* `base` should be the default package loaded and therefore you do not need
to use references such as `base::sort`. Are there other packages interferring
with using `sort`, `which`, `length`, etc.?
* Avoid direct slot access via `@` in package code. Please include a formal
interface for your class. I see you have `fg_get*` but perhaps the functions
you provide are not enough. See
https://www.bioconductor.org/developers/package-guidelines/#rcode
* The `overwrite` argument should be `FALSE` by default in `fg_add_summary`.

## tests

* It is strongly recommended that you add unit tests for code robustness.

## vignette

* It looks good.
* I would recommend keeping the sample code in the vignette straight forward
and simple for your users.
* This means avoiding the nested `gr$v$label` calls and using `grep` to set a
nested variable. It seems like only package authors would know about these
since they are quite nested which is not good for usability.

**Comment by aya49** [comment]
> 
> 
> Hi Alice, @aya49
> 
> Thank you for following up.
> Perhaps `flowGraph` should be submitted after the `flowTypeFilter`.
> See the rest of the review below.
> 
> Best,
> Marcel
> ## R
> 
>     * Remove any commented code in `.R` files.
Done

>     * Avoid any `.onLoad` hooks for data in `00_data.R`.
This was commented out, and now taken out.

>     * Default arguments to writing files should be `FALSE` or files should
>       be saved to the `tmp` directory via `tempdir`
`path=NULL` sets saving files in the constructor function to false by default. the `save_plots` parameter is only evaluated if `path!=NULL`.
 
>     * In general, graphics should not be saved to the user's system. Users should
>       be allowed to choose their own format.
`path=NULL` for all plotting functions, and it's not mentioned in the vignette. This is for if the user chooses to save everything to file directly from the constructor. Even then it's only for exploratory analysis, the users would most likely want to create their own plots.
 
>     * What is the reasoning for saving data as `.rds`? Wouldn't it suffice to
>       save the entire object if you will be using R to load the `.rds` files anyway?
>       (`fg_save` and `fg_load`)
Initially, I made the package so that I'd save the object as one Rdata file and just explore it in R. But I changed this so that common files user wants to see would be saved as csv and plots in a folder because not many people in our lab use R. This way, we just use the constructor function once and it saves everything to file and people can analyze the csv files in another program.

But you're right, I saved all the separate rds's as a single other.Rdata file :)

>     * `base` should be the default package loaded and therefore you do not need
>       to use references such as `base::sort`. Are there other packages interferring
>       with using `sort`, `which`, `length`, etc.?
YES, I got warnings that I should specify these when packages I import have functions with the same name.

>     * Avoid direct slot access via `@` in package code. Please include a formal
>       interface for your class. I see you have `fg_get*` but perhaps the functions
>       you provide are not enough. See
>       https://www.bioconductor.org/developers/package-guidelines/#rcode
Some @ accessors that users won't need to use that are in the functions:
- in modifiers and accessor functions or adding things into the flowGraph object.
- `fg@etc$save$path`: includes the path the user saved the object to and the save id; users won't need to use these and they are only used to confirm 
- `fg@etc$save$id`: save id, a random string generated during each save.
WILL COME BACK AND EDIT

>     * The `overwrite` argument should be `FALSE` by default in `fg_add_summary`.
Done.

> ## tests
> 
>     * It is strongly recommended that you add unit tests for code robustness.
I have a test script in the test folder, do I need to change it?

> ## vignette
> 
>     * It looks good.
;__;)b

>     * I would recommend keeping the sample code in the vignette straight forward
>       and simple for your users.
> 
>     * This means avoiding the nested `gr$v$label` calls and using `grep` to set a
>       nested variable. It seems like only package authors would know about these
>       since they are quite nested which is not good for usability.
I moved plot customization into the appendix. I think this might be useful for advanced users who don't want to write their plotting functions from scratch which is another option they have.

**Comment by aya49** [comment]
whew

**Comment by LiNk-NY** [comment]
Hi Alice, @aya49 

Thanks for making those changes!

> path=NULL for all plotting functions, and it's not mentioned in the vignette. This is for if the user chooses to save everything to file directly from the constructor. Even then it's only for exploratory analysis, the users would most likely want to create their own plots.

I'm not sure if users will want to save plots from exploratory analyses... But thanks for keeping the `path=NULL`. 

> I got warnings about is.null, name, length, nrow, and apply saying that imported packages also have these functions so I added base:: to them. A lot of them from the Matrix package that I use to make sparse matrices. I can try taking it out... a bit nervous though.

I don't think using `base::` is necessary. Perhaps by only adding `Matrix` to the `Imports` field in the description and using `Matrix::sparseMatrix` etc. in the package code, you can avoid these warnings...

> I have a test script in the test folder, do I need to change it?

I'm not sure it makes a difference but I'd move them to the standard location as promoted by `usethis::use_testthat`.

**Comment by aya49** [comment]
Hi Marcel @LiNk-NY 

Thank you for the suggestions 💯 

> I don't think using `base::` is necessary. Perhaps by only adding `Matrix` to the `Imports` field in the description and using `Matrix::sparseMatrix` etc. in the package code, you can avoid these warnings...
Done

> I'm not sure it makes a difference but I'd move them to the standard location as promoted by `usethis::use_testthat`.
and done!

Alice

**Comment by LiNk-NY** [comment]
Hi Alice, @aya49 

It's looking good! 
I ran build and check on the package and encountered this issue: 

```r
* checking examples ... ERROR
Running examples in 'flowGraph-Ex.R' failed
The error most likely occurred in:

> ### Name: fg_plot_qq
> ### Title: Creates a QQ plot of a summary statistic.
> ### Aliases: fg_plot_qq
> 
> ### ** Examples
> 
> 
>  no_cores <- 1
>  data(fg_data_pos15)
>  fg <- flowGraph(fg_data_pos15$count, class=fg_data_pos15$meta$class,
+                  no_cores=no_cores)
preparing input; 
10:42:33-10:42:33 > 19:00:00
preparing feature(s): mapping out cell population relations
NOTE: markers/measurements should not contain underscores_!
- 8 pops @ layer 1
10:42:33-10:42:33 > 19:00:00
- 24 pops @ layer 2
10:42:33-10:42:34 > 19:00:00
- 32 pops @ layer 3
10:42:34-10:42:34 > 19:00:00
cell population meta data created: 10:42:33-10:42:34 > 19:00:00
preparing feature(s): node proportion 
10:42:34-10:42:34 > 19:00:00
preparing feature(s): proportion on edges 
10:42:34-10:42:34 > 19:00:00
preparing feature(s): SpecEnr 
skipped
10:42:34-10:42:34 > 19:00:00
- claculating summary statistics (for class class: exp & control) t_diminish for node feature SpecEnr
10:42:34-10:42:34 > 19:00:00
total time used: 10:42:33-10:42:34 > 19:00:01
> 
>  fg_plot_qq(fg, type="node", summary_meta=NULL, adjust_custom="byLayer", index=1,
+          interactive=TRUE, logged=FALSE)
Error in DSVG_(file = file, width = width, height = height, bg = bg, pointsize = pointsize,  : 
  Graphics API version mismatch
Calls: fg_plot_qq -> <Anonymous> -> do.call -> <Anonymous> -> DSVG_
Execution halted
``` 
Do you have an idea of what is causing this? Thank you. 


Also, there is a NOTE that should be resolved. 
```r
* checking R code for possible problems ... NOTE
fg_feat_node_exprop_new : <anonymous> : <anonymous>: no visible binding
  for global variable ‘ep_’
fg_load: no visible binding for global variable ‘markers’
fg_load: no visible binding for global variable ‘fg_graph’
fg_load: no visible binding for global variable ‘elist’
fg_load: no visible binding for global variable ‘pl’
fg_load: no visible binding for global variable ‘etc’
fg_plot_box: no visible binding for global variable ‘val’
fg_plot_box: no visible binding for global variable ‘ID’
fg_plot_box_set: no visible binding for global variable ‘val’
fg_plot_box_set: no visible binding for global variable ‘ID’
fg_plot_pVSdiff: no visible binding for global variable ‘log_p_value’
fg_plot_pVSdiff: no visible binding for global variable ‘cohensd_size’
fg_plot_pVSdiff: no visible binding for global variable ‘avg_count’
fg_plot_pVSdiff: no visible binding for global variable ‘phenotype’
fg_plot_pVSdiff: no visible binding for global variable ‘phenogroup’
fg_plot_qq: no visible binding for global variable ‘y’
fg_plot_qq: no visible binding for global variable ‘x’
fg_plot_qq: no visible binding for global variable ‘cohensd_size’
fg_plot_qq: no visible binding for global variable ‘phenotype’
fg_plot_qq: no visible binding for global variable ‘d_size’
fg_plot_qq: no visible binding for global variable ‘phenogroup’
plot_gr: no visible binding for global variable ‘x’
plot_gr: no visible binding for global variable ‘y’
plot_gr: no visible binding for global variable ‘from.x’
plot_gr: no visible binding for global variable ‘to.x’
plot_gr: no visible binding for global variable ‘from.y’
plot_gr: no visible binding for global variable ‘to.y’
plot_gr: no visible binding for global variable ‘colour’
plot_gr: no visible binding for global variable ‘label’
plot_gr: no visible binding for global variable ‘from’
plot_gr: no visible binding for global variable ‘to’
plot_gr: no visible binding for global variable ‘label_long’
plot_gr: no visible binding for global variable ‘phenotype’
plot_gr: no visible binding for global variable ‘phenogroup’
show,flowGraph: no visible binding for global variable ‘fg’
Undefined global functions or variables:
  ID avg_count cohensd_size colour d_size elist ep_ etc fg fg_graph
  from from.x from.y label label_long log_p_value markers phenogroup
  phenotype pl to to.x to.y val x y
```

Thanks!

**Comment by aya49** [comment]
Hi Marcel @LiNk-NY 

For the error, I can't seem to replicate it on my local computer, let me do a version bump and see if it persists. If not, I did a quick search and people have similar Graphics API version mismatch errors in between R version upgrades because of outdated packages. Are there more messages related to this error?

For the notes, most of the variables with no physical bindings are for ggplot2's aes function, I've replaced this with aes_. For the variables loaded, I've used the attach and get functions instead so this should be alright now.

Hopefully, that cleans everything up. Let me know if the first error persists... D:

Thank you,
Alice

**Comment by LiNk-NY** [comment]
Hi Alice, @aya49 
Usually, to avoid the variables loaded message, I would do something like: 

```r
dataenv <- new.env(parent = emptyenv())
load("/file/path/to/data.rda", envir = dataenv)
variable1 <- dataenv[["variable1"]]
```

Thanks for making those changes! It looks good!

Best,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/aya49.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("flowGraph")`. The package 'landing page' will be created at

https://bioconductor.org/packages/flowGraph

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by aya49** [comment]
thank you for the tip @LiNk-NY  duly noted :-D, i will look through the code again to see if i can also apply this.

and oh boy, what a great way to end the semester!
