### ISSUE TITLE
TrajectoryGeometry

### ISSUE THREAD

**Issue by AnnaLaddach** [Bioconductor/Contributions#1728]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/AnnaLaddach/TrajectoryGeometry

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by AnnaLaddach** [comment]
Hi,

I'm very confused, I've subscribed to the bioc-devel mailing list, and yet I keep getting the error "Maintainer must subscribe to the bioc-devel mailing list."  Any advice would be much appreciated.

Thank you!

**Comment by lshep** [comment]
Have you confirmed the subscription and you are sure it is the email used as the maintainer of the package?  There is normally a confirmation email sent that sometimes gets marked as spam?

**Comment by AnnaLaddach** [comment]
Thank you, I have confirmed the subscription. This was initially the problem but even after confirming, I get the error. I am definitely receiving the mailing list email every day.

**Comment by AnnaLaddach** [comment]
Just realised the other maintainer was subscribed with a different email address which may have been causing the problem.

**Comment by hpages** [comment]
Hi @AnnaLaddach ,

Thanks for submitting TrajectoryGeometry. Please address the following warning:
```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'visualiseTrajectoryStats'
  traj2Data
Documented arguments not in \usage in documentation object 'visualiseTrajectoryStats':
  -

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter Writing R documentation files in the Writing R
Extensions manual.
```
and bump the version number in order to trigger a new build by the Single Package Builder.

Thanks,
H.

**Comment by hpages** [comment]
Thanks @AnnaLaddach for submitting TrajectoryGeometry. Here is some preliminary feedback:

1. `R CMD BiocCheck` produces 8 NOTEs which is a lot. Please address as much of them as possible.

2. Please do not document non-exported objects. All these man pages for internal functions that the user cannot access are going to make the reference manual of the package extremely confusing (note that the reference manual will be automatically generated and linked from the package landing page, see for example https://bioconductor.org/packages/SummarizedExperiment).

3. Using the same naming style for datasets and functions can be confusing. I would suggest that you use a different style e.g. camelCaps for functions and maybe lower case with underscores for datasets (e.g. `chol_answers`, `crooked_path`, etc...).

4. Please make sure that all the man pages for datasets provide information about the origin of the dataset. In particular they should provide as many details as possible about how the datasets were obtained (ideally enough details to allow the user to recreate the datasets if they wanted to). For example, no information is provided about how `crookedPath` was generated.

Thanks,
H.

**Comment by AnnaLaddach** [comment]
Many thanks @hpages for your feedback. Also apologies for taking so long to address your comments, Christmas has been a challenging time this year... 

We have attempted to improve the package:

1. R CMD BiocCheck now produces 4 (rather than 8) NOTES.
2. We have removed documentation for non-exported objects.
3. We now use lower case with underscores for naming datasets.
4. We have added GEO accession numbers for single-cell data. We have also created a repository (https://github.com/AnnaLaddach/TrajectoryGeometryData) which contains scripts used for preprocessing of single-cell datasets and generation of simulated datasets. We reference this in the man pages for datasets.

We look forward to hearing more from you.

Anna

**Comment by hpages** [comment]
Hi @AnnaLaddach,

I'll take a look at the package ASAP.

Thanks,
H.

**Comment by hpages** [comment]
Hi @AnnaLaddach 

Thanks for making these improvements. One last thing is that the package source tree contains a `doc/` folder at the top-level withe the following content:
```
doc/
├── SingleCellTrajectoryAnalysis.html
├── SingleCellTrajectoryAnalysis.R
├── SingleCellTrajectoryAnalysis.Rmd
├── TrajectoryGeometry.html
├── TrajectoryGeometry.R
└── TrajectoryGeometry.Rmd
```
This is wrong. Please remove. `R CMD build` will automatically add the `doc/` folder to the resulting source tarball and populate it with the above files, except that the files will be "the real ones" i.e. they will reflect the vignettes that are located in the `vignettes/` folder. Also note that `R CMD build` will place this `doc/` folder inside the `inst/` folder. You can use `tar ztf` on the source tarball to see its content without extracting it. You should never extract the source tarball on top of your package source tree (a.k.a. your git clone).

Thanks,
H.

**Comment by AnnaLaddach** [comment]
Thank you @hpages for looking at our changes. We've removed the top-level /doc folder now.

**Comment by hpages** [comment]
Perfect, thanks. (Let's ignore the warning on Mac builder machv2, it's an issue on our side.)

H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/AnnaLaddach.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TrajectoryGeometry")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TrajectoryGeometry

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
