### ISSUE TITLE
POST: Projection onto Orthogonal Space Testing for High Dimensional Data

### ISSUE THREAD

**Issue by xueyuancao** [Bioconductor/Contributions#173]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/xueyuancao/POST

Confirm the following by editing each check box to '[x]'
- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [ x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by xueyuancao** [comment]
The warning is due the version number being not even: 0.99.1, I make a push to change the version number to 0.98.1. Due to the version number decreased, there will not be a build for this push. Could you check whether it is OK or I need another push to increase version number to 0.98.2

Bests,

Xueyuan

**Comment by xueyuancao** [comment]
I am not sure the reason for 'Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'POST.tex' failed'

We could use this version 'http://bioconductor.org/spb_reports/POST_buildreport_20161020154255.html'

**Comment by LiNk-NY** [comment]
Hi @xueyuancao, 
DESCRIPTION: Please move the packages in the `Depends` field to the `Imports` field and selectively import the functions that you need in the `NAMESPACE`. 
Update the version number to start another build. Thanks.

Marcel

**Comment by LiNk-NY** [comment]
Hi @xueyuancao, 
Thank you for submitting to Bioconductor!
Please find your package review below: 

---

#### DESCRIPTION 
* As mentioned earlier, please move the packages from the `Depends` fields to the `Imports` fields. The `Depends` field should only be used if you are expanding or building on top of another package. 

#### Rd pages
* Please make sure you're describing all arguments in detail. For example, the `lamda` argument description is a bit vague. 

#### Grammar
* Please avoid the use of `1:number`, instead use `seq_len(number)` for more robust coding practice.
* If possible please avoid nested if/else statements.
* Avoid growing an object inside of a loop. Pre-allocate the dimensions of the new object and fill in with data (e.g., `boots <- matrix(NA, ncol = 6, nrow = 4)` and then `boots[j, ] <- letters[1:6]`)
* Please use full argument names, `modd` could be `model`.
* Please use descriptive object names in the code. An object named "this" is not very helpful. 
* Consider using a helper function for parsing models such as: 

```
.getVarList <- function(model) {
   lapply(as.list(
       attr(terms(
       as.formula(model)),
       "variables"))[-1], as.character)
}
```

Looking forward to your changes. If you have any questions, please let me know. 

Regards,
Marcel

**Comment by xueyuancao** [comment]
Dear Marcel:

Thanks you very for taking time to review our package. Your suggestions are very helpful and highly appreciated. I just pushed a revision to gitHub with following modification as suggested:

1)  moved packages from the Depends fields to the Imports fields
2)  made arguments more clear such as lamda: from 'a predefined fraction'  to 'a predefined fraction of 0 to 1: the fraction of variation retained in the selected orthogonal projections'
3)  change all 1:number to seq_len(number)
4)  Pre-allocate the dimensions of the new objects 
5)  modd to model, this to thisIds.
6)  revise the extract variable names from model or similar using character class. I did not use the helper function provided as it will not handle pseudo formula such as 'Group ~ '
7) added more options to POSTcoxph

If you have any questions, please let me know.

Bests,

Xueyuan

**Comment by LiNk-NY** [comment]
Hi Xueyuan, @xueyuancao 
Thank you for making those changes. 
Please change the R version number in the description to `3.4.0`. 

Your package will be accepted after this. 

Regards,
Marcel

**Comment by xueyuancao** [comment]
Dear Marcel:

I have changed the R version to 3.4.0 in DESCRIPTION file. It seems the package cannot be built in tokay2 and oaxaca due to texi2dvi. This error has been seen by other developer too.

Thanks,

Xueyuan

**Comment by xueyuancao** [comment]
Dear Marcel:

It seems the package cannot be built in tokay2 and oaxaca due to texi2dvi. Is there any suggestion to fix this problem.

Thanks,

Xueyuan

**Comment by LiNk-NY** [comment]
Hi XueYuan, @xueyuancao 
This is an issue on our end. We are looking into it. 
Thanks, 
Marcel

**Comment by xueyuancao** [comment]
Thanks a lot.

Xueyuan

**Comment by LiNk-NY** [comment]
@xueyuancao 
Can you bump the version for another build? 
Thanks, 
Marcel

**Comment by LiNk-NY** [comment]
Hi @xueyuancao, 
My apologies for the delay. Your package has been accepted. 
Thank you for submitting to Bioconductor!

Regards,
Marcel

**Comment by xueyuancao** [comment]
Thanks a lot,
