### ISSUE TITLE
RnaSeqGeneEdgeRQL (workflow package)

### ISSUE THREAD

**Issue by yunshun** [Bioconductor/Contributions#179]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/yunshun/RnaSeqGeneEdgeRQL

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by vobencha** [comment]
Hi,
This is a workflow only and not a software package, right?
Valerie

**Comment by yunshun** [comment]
Hi Valerie,

Sorry for the late reply.
Yes, it is a workflow package only.

Cheers,
Yunshun

**Comment by vobencha** [comment]
Hi,
Sorry for the delay in reviewing.

1) The first code chunk in the vignette is entirely commented out:
```{r style, echo=FALSE, results='hide', message=FALSE}
#library(BiocStyle)
#library(knitr)
#opts_chunk$set(error=FALSE, prompt=TRUE, comment=NA)
...

If you don't need this please remove it.

2) edgeRQL package
Several vignette chunks refer to data in package edgeRQL but are commented out (I see you've moved the data to inst/extdata). As far as I can tell the edgeRQL package does not exist in CRAN or Biocondcutor. Are you planning to submit this package or maybe you already have and it's under review?

3) Add GO.db to 'Depends' and Rsubread to 'Suggests'

Valerie

**Comment by vobencha** [comment]
Also, 'workflows' is not a valid biocViews term. Please choose a few terms from the 'software' list here:
http://www.bioconductor.org/packages/release/BiocViews.html#___Software

Valerie

**Comment by vobencha** [comment]
Hi,
Checking in. Looks like we still have an error ... ?
Valerie

**Comment by yunshun** [comment]
Hi Valerie,

I don't know why there is an error. It says the it can't download the data
from the URL link.

It was totally fine before. I've reverted everything back to the older
version which had no error but warnings. But now it still returns an error.

Do you know the cause of it?

Cheers,
Yunshun

**Comment by vobencha** [comment]
Please re-submit your most current changes and bump the version. We're having some problems with the builders - if the SPB output has errors related to the build machiens we'll just waive it. Sorry this has taken so long to get through the review process.
Valerie

**Comment by vobencha** [comment]
Please re-submit your most current changes and bump the version. In your last message you said you reverted back to an older version ...

**Comment by yunshun** [comment]
Hi Valerie,

The same error appears again.
It fails to open the URL, which is clearly available.
It wasn't a problem back in Oct.
Even when I reverted my package to the Oct version, it still fails.

Also, Rsubread is available for Mac and Unix.
It is not actually run in the workflow.
So I should probably remove it from the list of suggested packages.

trying URL 'http://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE60450&format=file&file=GSE60450_Lactation-GenewiseCounts.txt.gz'
Quitting from lines 102-110 (edgeRQL.Rmd)
Error: processing vignette 'edgeRQL.Rmd' failed with diagnostics:
cannot open URL
'http://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE60450&format=file&file=GSE60450_Lactation-GenewiseCounts.txt.gz'
Execution halted


Cheers,
Yunshun

**Comment by vobencha** [comment]
The vignette has a few problems.

1) Please format all code to be a max of 80 characters wide. The wrapping code is very difficult to read.

2) R CMD Stangle produces an R file that you can run with source(). When I run this on your vignette I see this -

~/RnaSeqGeneEdgeRQL/vignettes >R-dev CMD Stangle edgeRQL.Rmd
Warning in grep("\n", x) : input string 419 is invalid in this locale
Warning in grep("^(---|\\.\\.\\.)\\s*$", lines) :
  input string 419 is invalid in this locale
Warning in grepl(chunk.begin, lines) :
  input string 419 is invalid in this locale
Warning in grepl(chunk.end, lines) :
  input string 419 is invalid in this locale
Warning in grepl(chunk.begin, g[1]) :
  input string 1 is invalid in this locale
Output file:  edgeRQL.R

Please fix the format problems in line 419.

3) Add library(RnaSeqGeneEdgeRQL)

Workflows will now be stored and distributed as R packages so you need to library(RnaSeqGeneEdgeRQL) at the top of the vignette.

4) file download

When I go to this page:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE60450

and click on the txt.gz file the address is this:
"https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE60450&format=file&file=GSE60450%5FLactation%2DGenewiseCounts%2Etxt%2Egz"

not this (which is what you have in your vignette):
> FileURL
[1] "http://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE60450&format=file&file=GSE60450_Lactation-GenewiseCounts.txt.gz"


Valerie

**Comment by yunshun** [comment]
Hi Valerie,

Now it is complaining about the new URL you sent to me.
However, both the old and the new URL allow me to download the data on my PC.
I just don't understand why it is causing such a problem.

As I mentioned before, the workflow was absolutely fine with the old URL back in Oct (more precisely on Oct 27).
There wasn't even an error in that version.
See the build report at:
http://bioconductor.org/spb_reports/RnaSeqGeneEdgeRQL_buildreport_20161026192704.html

The warnings were about the package version number and the biocViews, which wasn't anything techincal.
Now even when I revert back to that version (which had no errors), it is still throwing out all the error messages about not being able to download the data.

Could you please explain this to me, or simply do the submission for me?
I really don't think I can figure that out from my end.
If needed, I can send you all the files for building the package.

Cheers,
Yunshun

**Comment by vobencha** [comment]
It looks like you need to specify 'method' as something other than auto in the call to download.file(), e.g.,
method = libcurl
method = curl
method = wget
See ?download.file for details.

httr::GET will work with either url. I would suggest using the httr package instead of download.file:

> httr::GET("http://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE60450&format=file&file=GSE60450_Lactation-GenewiseCounts.txt.gz")
Response [https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE60450&format=file&file=GSE60450_Lactation-GenewiseCounts.txt.gz]
  Date: 2016-12-01 02:48
  Status: 200
  Content-Type: application/octet-stream
  Size: 514 kB
<BINARY BODY>

> httr::GET("https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE60450&format=file&file=GSE60450%5FLactation%2DGenewiseCounts%2Etxt%2Egz")
Response [https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE60450&format=file&file=GSE60450%5FLactation%2DGenewiseCounts%2Etxt%2Egz]
  Date: 2016-12-01 02:49
  Status: 200
  Content-Type: application/octet-stream
  Size: 514 kB
<BINARY BODY>

No, I cannot just fix and submit the package for you. I can help work through problems but the responsibility is yours to create a functioning workflow. Hopefully you understand that once accepted, it is also your responsibility to fix problems that come up as R and dependencies change.

I can reproduce the download error by running R CMD build on your package from github on my machine. Please run R CMD build yourself locally to make sure the download works in the context of the package infrastructure (don't just paste the url in your browser).

Valerie

**Comment by yunshun** [comment]
Hi Valerie,

I used the 'libcurl' method in 'download.file' and the problem seems to be fixed.
Thanks for the suggestion.

There is a warning message that appears on all the three platforms.
It says 'Update R version dependency from 3.3.0 to 3.4.'
However, the workflow was written for R > 3.3.0 and should be able to run in R > 3.3.0.
Do I have to change the dependency from 3.3.0 to 3.4?

There is also an error in oaxaca build report saying 'pdflatex is not available'.
How do I fix this error?

Cheers,
Yunshun

**Comment by vobencha** [comment]
No, you don't have to change the R dependency. The error on Oaxaca is our problem.

It looks like you have not formatted the code to a max of 80 characters wide. 

Valerie

**Comment by yunshun** [comment]
Do I have to set the width of max of 80 characters?
This will affect the formatting of some of the R outputs which were manually added into the workflow.
(since Rsubread doesn't run on windows, we have to run Rsubread on unix and copy and paste the screen output back into the workflow).

Cheers,
Yunshun

**Comment by vobencha** [comment]
The width formatting is not a requirement, just a suggestion. I will approve this and let Lori know we have a new workflow. You should be hearing from her or Martin with svn credentials in the next week.

Valerie

**Comment by yunshun** [comment]
Thanks for the help, Valerie!
