### ISSUE TITLE
ouija

### ISSUE THREAD

**Issue by kieranrcampbell** [Bioconductor/Contributions#181]
- Repository: https://github.com/kieranrcampbell/ouija

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by mtmorgan** [comment]
Marcel will provide the official review, but I notice that you make no use of Bioconductor packages. A major strength of Bioconductor is interoperability, and it seems like many classes can come into play here; without looking at all into your package, perhaps the discussion in this issue https://github.com/Bioconductor/Contributions/issues/170 is relevant?

**Comment by kieranrcampbell** [comment]
Ouija can take an ExpressionSet as input, which would ideally be from
Scater (on bioconductor), hence suggest: scater in DESCRIPTION. I can
change this to an import or suggests of Biobase if that would be better?

**Comment by kieranrcampbell** [comment]
The build reports for these go to page not found...any help?

**Comment by lshep** [comment]
This should be remedied now. Any future reports should be active.

**Comment by LiNk-NY** [comment]
Hi @kieranrcampbell, 
I'm getting this error when trying to install locally: 

```
** testing if installed package can be loaded
Error in .doLoadActions(where, attach) : 
  error in load action .__A__.1 for package ouija: is(module, "character"): object 'm' not found
Error: loading failed
Execution halted
ERROR: loading failed
```

**Comment by LiNk-NY** [comment]
Hi Kieran, @kieranrcampbell 
Thank you for submitting to Bioconductor. 

I recently ran a check on your package and I got the following error:

```
> plot_ouija_fit_diagnostics(oui)
Error in `[.unit`(padding, 4) : index out of bounds ('unit' subsetting)
Calls: plot_ouija_fit_diagnostics ... lapply -> FUN -> guide_gengrob.legend -> [ -> [.unit
Execution halted
```
Please resolve this error in the `ouija-Ex.R` example script. 

Also, your package is taking a long time to check: `real  9m43.787s`. The guidelines state that `R CMD check` must complete within 5 minutes. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @kieranrcampbell, 
Please repond to these comments, otherwise I'd have to close the issue. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Please create another issue if you would like to resubmit.
