### ISSUE TITLE
TCGAbiolinksGUI

### ISSUE THREAD

**Issue by tiagochst** [Bioconductor/Contributions#182]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/BioinformaticsFMRP/TCGAbiolinksGUI

Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by tiagochst** [comment]
Please, could you verify why the server is installing an old version of TGCAbiolinks package?
Thanks!

**Comment by tiagochst** [comment]
Please, could you verify why the  zin1 server is loading an old version of the package? The other ones is it ok.

> namespace TCGAbiolinks 2.2.3 is being loaded, but >= 2.2.4 is required

Thanks

**Comment by tiagochst** [comment]
@hpages I'm sorry to ask, but by any chance do you have a date for this review? Thanks! Best regards,
Tiago

**Comment by hpages** [comment]
Hi Tiago,

Sorry for the delay and thanks for your patience.

 TCGAbiolinksGUI looks good. It passes `R CMD build`, `R CMD check` and `R CMD BiocCheck` on my system. I think the errors we see in the latest SPB report are false positives and can be ignored. I found only a few minor issues:

1. I would suggest that you add the term GUI to your biocViews field.

2. The session info section at the end of the vignette doesn't render properly in the HTML version.

3. A lot of output (many dozens of lines) is generated when I call `TCGAbiolinksGUI()` to start the GUI. This output is a little bit annoying, not very useful, and might confuse the user. I know I can suppress it by wrapping the call in `suppressMessages()`. Maybe that could be mentioned in the man page? Or maybe the `TCGAbiolinksGUI()` function itself could be modified to be more quiet (by using `suppressMessages()` internally). This could also be controlled via an argument e.g. `verbose` that would be `FALSE` by default. Just some suggestions. Maybe you come up with a better idea of how to deal with this.

4. In addition to the many lines of output, calling `TCGAbiolinksGUI()` also generates the following warning:
```
> suppressMessages(TCGAbiolinksGUI())
Warning in body(fun) : argument is not a function
```

5. What's the clean way to quit the GUI? `CTRL+C` at the command line kind of works but leaves the browser window/tab open. Shutting down the browser alone doesn't seem to be enough either: it has to be followed by `CTRL+C` at the command line. I would suggest that the user be able to end the GUI session by clicking somewhere in the GUI. Sorry if there is such feature, couldn't find it.

Thanks,
H.

**Comment by tiagochst** [comment]
Hi Hervé! 
Thank you.

1) I added the GUI to biocViews field.

2) I had some codes to output the vignette in pdf, I just removed them, I'll keep the HTML

3) I added suppressMessages as suggested. I believe the messages are related to this:
https://github.com/thomasp85/shinyFiles/issues/43, I was waiting for the maintainer to update the package, but he hasn't done that yet.

4) I don't have this problem. I'll try to see if I can replicate the problem.
> suppressMessages(TCGAbiolinksGUI())
Warning in body(fun) : argument is not a function

5) If you do  CTRL+C now it will close the client side. I added also a button to close the GUI session (stop the APP). It a small shutdown button in the top right. What do you think ?

<img width="2381" alt="screen shot 2016-12-09 at 2 19 36 pm" src="https://cloud.githubusercontent.com/assets/145529/21066471/9e60455a-be1a-11e6-9b3c-51dc31217d15.png">

**Comment by tiagochst** [comment]
@hpages Just to know, is it possible to change a name of the package? As TCGA migrated to GDC we are thinking if we should call it something more generic like "CancerBiolinks". It is not a big problem if it is not possible. We are still discussing if that would be a good ideia.

**Comment by tiagochst** [comment]
@hpages we decided to keep the name. Please,  ignore my last message.

**Comment by tiagochst** [comment]
@hpages Please, I'm really sorry to ask, I know you might be busy. But when do you believe the package will be accepted? I made the changes from the last review, but I didn't get any updates yet.
Thanks!

**Comment by hpages** [comment]
Hi Tiago,

Sorry again for the delay. Thanks for your work on the package. I like the new shutdown button.

The output of `sessionInfo()` in the vignette still has some formatting issues.

Also I still get 
```
> TCGAbiolinksGUI()
Warning in body(fun) : argument is not a function
```
These are no showstoppers. I'm accepting the package. You'll be contacted by email in the next days for the follow-up on this.

Thanks for your contribution to the project.

H.

**Comment by tiagochst** [comment]
@hpages Thank you very much for doing the review.

**Comment by tiagochst** [comment]
@hpages About the warning problem, I was able to reproduce it. But the warning comes from a Shiny package [issue.](https://groups.google.com/forum/#!topic/shiny-discuss/2kVPa8jDooI)

**Comment by tiagochst** [comment]
@hpages @mtmorgan,
I'm not sure how to deal with this case. But, I need to add some pre-processed data to the TCGAbiolinksGUI.

 AdditionalPackage: https://github.com/BioinformaticsFMRP/TCGAbiolinksGUI.data

Best regards,
Tiago

**Comment by mtmorgan** [comment]
Do you mean you'd like to add another (experiment data) package? I think the best bet is to open a new issue.

**Comment by tiagochst** [comment]
Yes. Thanks! I just open a new issue with the  experiment data package.
