### ISSUE TITLE
AHPathbankDbs

### ISSUE THREAD

**Issue by kozo2** [Bioconductor/Contributions#1825]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/biopackathon/AHPathbankDbs

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by kozo2** [comment]
@nturaga I can't fetch upstream. (So I can't trigger new build report...) What do you think?
```
> cat ~\.ssh\id_ed25519.pub
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFT4ynvtxZT5assytXlFBMqTYy8Jl1Pnkcs0cSbY94Zm
> git remote -v
origin  git@github.com:biopackathon/AHPathbankDbs.git (fetch)
origin  git@github.com:biopackathon/AHPathbankDbs.git (push)
upstream        git@git.bioconductor.org:packages/AHPathbankDbs.git (fetch)
upstream        git@git.bioconductor.org:packages/AHPathbankDbs.git (push)
(base) PS C:\Users\kozon\Projects\AHPathbankDbs> git fetch --all
Fetching origin
Fetching upstream
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch upstream

```

**Comment by kozo2** [comment]
@nturaga I think this is because I changed the contents of https://github.com/kozo2.keys after creating this issue. Could you please check the SSH public key registration again?

**Comment by kozo2** [comment]
@nturaga I'm sorry for upsetting you. I understand the reason.
The reason was that the [Bioconductor Git Credentials](https://git.bioconductor.org/BiocCredentials) and the GitHub Credentials were out of sync.
(and I did not know how the [Bioconductor Git Credentials](https://git.bioconductor.org/BiocCredentials) works ).
Now the `git fech -all` works well.

**Comment by nturaga** [comment]
You did not upset me at all. Please feel free to ask questions.

**Comment by nturaga** [comment]
# Review

## DESCRIPTION

- ok.

- It looks like an Annotationhub package, did you contact @lshep or
  @Kayla-Morrell already? This doesn't look like anything is needed in
  AWS S3, it's pulling from Pathbank.

## NAMESPACE

- ok

## inst

- extdata has metadata.csv

- scripts - ok

## vignettes

ok.

**Comment by lshep** [comment]
The data is already in AnnotationHub and the data is already in Bioconductor S3 bucket.  If it is pulling the data from some other place the code should be updated to use the AnnotationHub front end

**Comment by nturaga** [comment]
I see, ok so it seems he downloads CSV metadata from Pathbank for the databases which are already in AnnotationHub in our S3 bucket. 

Can you confirm @kozo2 ?

**Comment by kozo2** [comment]
> I see, ok so it seems Kozo downloads CSV metadata from Pathbank for the databases which are already in AnnotationHub in our S3 bucket.
> 
> Can you confirm @kozo2 ?

I confirmed it with the code below. (I also added this code to AHPathbankDbs vignette.)

```
> library(AnnotationHub)
> ah <- AnnotationHub()
snapshotDate(): 2021-01-04
> ah
AnnotationHub with 55009 records
# snapshotDate(): 2021-01-04
# $dataprovider: Ensembl, BroadInstitute, UCSC, ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/, Haemcode, FungiDB, Inparanoid8, TriTrypDB, PlasmoDB, MicrosporidiaDB
# $species: Homo sapiens, Mus musculus, Drosophila melanogaster, Bos taurus, Rattus norvegicus, Pan troglodytes, Danio rerio, Gallus gallus, Monodelphis domestica, Felis catus
# $rdataclass: GRanges, TwoBitFile, BigWigFile, EnsDb, Rle, OrgDb, ChainFile, TxDb, Inparanoid8Db, data.frame
# additional mcols(): taxonomyid, genome, description, coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags, rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["AH5012"]]' 

            title                                       
  AH5012  | Chromosome Band                             
  AH5013  | STS Markers                                 
  AH5014  | FISH Clones                                 
  AH5015  | Recomb Rate                                 
  AH5016  | ENCODE Pilot                                
  ...       ...                                         
  AH89321 | Ensembl 102 EnsDb for Xiphophorus couchianus
  AH89322 | Ensembl 102 EnsDb for Xiphophorus maculatus 
  AH89323 | Ensembl 102 EnsDb for Xenopus tropicalis    
  AH89324 | Ensembl 102 EnsDb for Zonotrichia albicollis
  AH89325 | Ensembl 102 EnsDb for Zalophus californianus

> mcols(query(ah, "pathbank"))
```

I paste the image to check the metadata.
(Because it didn't render well in markdown.)

![image](https://user-images.githubusercontent.com/12192/104074961-db01f080-5254-11eb-8f6f-4525190d0e7d.png)

**Comment by kozo2** [comment]
@nturaga 

> Checking package NEWS...
> * NOTE: Consider adding a NEWS file, so your package news will be
> included in Bioconductor release announcements.

Fixed

> ## DESCRIPTION
> * * NOTE: The Description field in the DESCRIPTION is made up by less
>     than 3 sentences. Please consider expanding this field, and
>     structure it as a full paragraph

Fixed

> * It looks like an Annotationhub package, did you contact @lshep or
>   @Kayla-Morrell already? This doesn't look like anything is needed in
>   AWS S3, it's pulling from Pathbank.

Yes. I contacted @lshep and @Kayla-Morrell already.
I uploaded the rda files to S3 last month.
It's pulling data from S3. Not from Pathbank.

> ## inst
> * extdata has metadata.csv

extdata has metadata.csv, but I think the metadata in the above code is not from this extdata but from S3.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kozo2.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("AHPathbankDbs")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AHPathbankDbs

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
