### ISSUE TITLE
(inactive) PeCorA

### ISSUE THREAD

**Issue by demar01** [Bioconductor/Contributions#1836]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/demar01/PeCorA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by demar01** [comment]
Hello 
BiocCheck FAILED because
  * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel


I have subscribed to bioc-devel mailing list.

Do you know why this is failing?

Thanks

**Comment by mtmorgan** [comment]
When you subscribe, the mailing list sends a confirmation email that you need to reply to. This often ends in a spam mail folder. The address you subscribe with has to match the address of the `cre` in the DESCRIPTION file. Increment your package version (to 0.99.1) and push a change to the 'master' branch of your git.bioconductor.org repository.

**Comment by demar01** [comment]
- [X] Email confirmation
- [X]  version 0.99.1

**Comment by mtmorgan** [comment]
...looks like 0.99.1 wasn't pushed to git.bioconductor.org?

**Comment by demar01** [comment]
It should be pushed now. Can you confirm?

**Comment by vjcitn** [comment]
It looks like it was pushed to your github repo.  But you need to push the corrected version to git.bioconductor.org.  If the
documentation is not clear on how to do this please respond to this issue.  Probably you need to do a clone of git@git.bioconductor.org:packages/PeCorA (which will have 0.99.0 at this moment), make corrections, git add/commit/push

**Comment by vjcitn** [comment]
and be sure to change the DESCRIPTION In the git.bioconductor.org:packages/PeCorA repo to have 0.99.x with x > 0 and increasing every time you make a new change.

**Comment by demar01** [comment]
I fixed the gitignore but it is still giving an error because of it apparently. I cannot see what is wrong

**Comment by vjcitn** [comment]
Here's what I see at the current pull of 
```
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/PeCorA/vignettes$ git remote -v
origin	git@git.bioconductor.org:packages/PeCorA (fetch)
origin	git@git.bioconductor.org:packages/PeCorA (push)

```
```stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/PeCorA$ ls -tla
total 72
drwxrwxr-x  9 stvjc stvjc  4096 Jan  7 08:24 .
-rw-rw-r--  1 stvjc stvjc  1406 Jan  7 08:24 DESCRIPTION
drwxrwxr-x  8 stvjc stvjc  4096 Jan  7 08:24 .git
-rw-rw-r--  1 stvjc stvjc   169 Jan  7 08:24 .gitignore
drwxrwxr-x  3 stvjc stvjc  4096 Jan  6 07:23 man
drwxrwxr-x  3 stvjc stvjc  4096 Jan  6 06:53 inst
drwxrwxr-x  3 stvjc stvjc  4096 Jan  6 06:53 tests
drwxrwxr-x  2 stvjc stvjc  4096 Jan  6 06:53 vignettes
drwxrwxr-x  2 stvjc stvjc  4096 Jan  6 06:53 data
-rw-rw-r--  1 stvjc stvjc 10244 Jan  6 06:53 .DS_Store
-rw-rw-r--  1 stvjc stvjc   571 Jan  6 06:53 NAMESPACE
-rw-rw-r--  1 stvjc stvjc   356 Jan  6 06:53 PeCorA.Rproj
drwxrwxr-x  2 stvjc stvjc  4096 Jan  6 06:53 R
-rw-rw-r--  1 stvjc stvjc    48 Jan  6 06:53 .Rbuildignore
-rw-rw-r--  1 stvjc stvjc  2663 Jan  6 06:53 README.md
drwxrwxr-x 10 stvjc stvjc  4096 Jan  6 06:53 ..
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/PeCorA$ cd vig*
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/PeCorA/vignettes$ ls -tla
total 1100
drwxrwxr-x 9 stvjc stvjc    4096 Jan  7 08:24 ..
-rw-rw-r-- 1 stvjc stvjc 1094644 Jan  6 06:53 PeCorA.html
drwxrwxr-x 2 stvjc stvjc    4096 Jan  6 06:53 .
-rw-rw-r-- 1 stvjc stvjc    6148 Jan  6 06:53 .DS_Store
-rw-rw-r-- 1 stvjc stvjc    1225 Jan  6 06:53 PeCorA.bib
-rw-rw-r-- 1 stvjc stvjc    4633 Jan  6 06:53 PeCorA.Rmd
```

Note the .DS_Store files ... you'll have to remove them from your .git repo, along
with any other files noted in messages like the following, seen at
`http://bioconductor.org/spb_reports/PeCorA_buildreport_20210106071755.html`

The error message:
```* Checking valid files...
    * ERROR: System Files found that should not be git tracked:
        PeCorA.Rproj
        man/.Rapp.history
        .DS_Store
        inst/.DS_Store
        R/.DS_Store
        tests/.DS_Store
        tests/testthat/.DS_Store
        vignettes/.DS_Store
```

**Comment by demar01** [comment]
DS are removed and  +1 version is added and pushed to git.bioconductor.org. 

I cannot see changes in the build report?

Thanks

**Comment by mtmorgan** [comment]
I'm not exactly sure what the problem is; perhaps @lshep can help / trigger a new build. It might be that the version bump is only recognized if it is in the 'last' commit. You could test this hypothesis by bumping to 0.99.2...

**Comment by lshep** [comment]
From the looks of it, you committed the DESCRIPTION version bump only to github and not to bioconductor git.bioconductor.org.  You will need to push to upstream remote as well.

**Comment by vjcitn** [comment]
I confirm this.  On my checkout pf PeCorA from git.bioconductor.org
```
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/PeCorA$ git remote -v
origin	git@git.bioconductor.org:packages/PeCorA (fetch)
origin	git@git.bioconductor.org:packages/PeCorA (push)
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/PeCorA$ git pull
Already up to date.
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/PeCorA$ ls -tla
total 72
drwxrwxr-x  8 stvjc stvjc  4096 Jan 11 18:56 .git
drwxrwxr-x  9 stvjc stvjc  4096 Jan 11 18:56 .
-rw-rw-r--  1 stvjc stvjc  1406 Jan  7 08:24 DESCRIPTION
-rw-rw-r--  1 stvjc stvjc   169 Jan  7 08:24 .gitignore
drwxrwxr-x  3 stvjc stvjc  4096 Jan  6 07:23 man
drwxrwxr-x  3 stvjc stvjc  4096 Jan  6 06:53 inst
drwxrwxr-x  3 stvjc stvjc  4096 Jan  6 06:53 tests
drwxrwxr-x  2 stvjc stvjc  4096 Jan  6 06:53 vignettes
drwxrwxr-x  2 stvjc stvjc  4096 Jan  6 06:53 data
-rw-rw-r--  1 stvjc stvjc 10244 Jan  6 06:53 .DS_Store
```
Note the .DS_Store is still present.  An explicit git push 
```
git push git@git.bioconductor.org:packages/PeCorA
```
might work for you and illustrate the task very clearly.

**Comment by demar01** [comment]
git push git@git.bioconductor.org:packages/PeCorA

I get 

git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository

**Comment by lshep** [comment]
Are you using a different computer because you were able to push earlier last week? @nturaga

**Comment by demar01** [comment]
Yes, I am. Would easiest be to create a new issue?

**Comment by vjcitn** [comment]
No, you do not have to create a new issue.   Look at part 8 of https://www.bioconductor.org/developers/how-to/git/faq/

You would use BiocCredentials to provide the key generated on your new computer.

**Comment by mtmorgan** [comment]
Also if you add you new public key to github, so that it appears at https://github.com/demar01.keys, it will be copied to the credentials app; I'm not sure about the frequency of the copy, but it would likely be hourly??

**Comment by demar01** [comment]
Ok, I added a key and updated the Description file now

**Comment by vjcitn** [comment]
Let us know when it looks as if your push to the bioconductor git repo has succeeded.  I see no change in my checkout.

**Comment by lshep** [comment]
I can confirm this too.  There are no changes pushed to the bioconductor git repo. You need to push your change with a valid version bump to git.bioconductor.org  every time you want changes to propagate. If you are on a new computer you may want to set up remotes as originally [documented](https://bioconductor.org/developers/how-to/git/new-package-workflow/) when submitted.

**Comment by demar01** [comment]
Thanks. It should now be pushed

**Comment by lshep** [comment]
It is still not pushed to upstream for git.bioconductor.org.  The last pushed changes were from January 6th 
```
commit e7a2bd084b36c62e29299a9a6173e3f5bbe2ae9a (HEAD -> master, origin/master, origin/HEAD)
Author: Maria <maria.dermit@qmul.ac.uk>
Date:   Wed Jan 6 12:52:34 2021 +0000

    Modifying gitignore

commit 08cd51ed383c35179a2d2a3061121417f71d3628
Author: Maria <maria.dermit@qmul.ac.uk>
Date:   Wed Jan 6 12:04:01 2021 +0000

    Adding version
```
Again please check your remotes and make sure you are pushing to  `git push upstream master`   or doing as @vjcitn  suggested with `git push git@git.bioconductor.org:packages/PeCorA`

**Comment by demar01** [comment]
I cannot see what I am missing. 
Following this:
https://bioconductor.org/developers/how-to/git/new-package-workflow/

- [X] SSH keys are correctly connected. 
https://github.com/demar01.keys
matches cat ~/.ssh/id_rsa.pub 

- [X] Remote is configured
 git remote -v
origin	https://github.com/demar01/PeCorA.git (fetch)
origin	https://github.com/demar01/PeCorA.git (push)
upstream	git@git.bioconductor.org:packages/PeCorA.git (fetch)
upstream	git@git.bioconductor.org:packages/PeCorA.git (push)

However, on git push git@git.bioconductor.org:packages/PeCorA
fatal: Could not read from remote repository.

 git push origin master
 Everything up-to-date

**Comment by mtmorgan** [comment]
You want to push to the remote note the repository, so

```
git push upstream
```

**Comment by mtmorgan** [comment]
The BiocCredentials app knows about the first two keys at https://github.com/demar01.keys. From http://bioconductor.org/developers/how-to/git/faq/ what does
```
ssh -T git@git.bioconductor.org
```
report? If it doesn't include PeCorA, try
```
ssh -Tv git@git.bioconductor.org
```
It should report debugging information, including keys that it is trying to use. Also the key and public key on your system need to have particular permissions; mine is
```
$ ls -al ~/.ssh/*
drwx------  11 ma38727  735121457    352 Dec 21 10:55 .
-rw-------@ 1 ma38727  735121457  951 Dec  1  2019 /Users/ma38727/.ssh/id_rsa
-rw-------@ 1 ma38727  735121457  226 Dec  1  2019 /Users/ma38727/.ssh/id_rsa.pub
```

**Comment by demar01** [comment]
Hi Martin

I added the 3rd key to my Bioconductor Git Credentials more than one hour ago, but 
`ssh -T git@git.bioconductor.org`

still reports
` Permission denied (publickey).`

I replaced the remote to ssh remote with 
`
git remote remove origin
git remote add origin git@github.com:demar01/PeCorA.git
`

Permission denied (publickey).

**Comment by mtmorgan** [comment]
So I guess you now have
```
git remote -v
origin git@github.com:demar01/PeCorA.git (fetch)
origin git@github.com:demar01/PeCorA.git (push)
upstream git@git.bioconductor.org:packages/PeCorA.git (fetch)
upstream git@git.bioconductor.org:packages/PeCorA.git (push)
```
You say that you see `Permission denied`, but do you see it when now pushing to **GitHub** (`git push origin`)? This would indicate that the problem is with your ssh keys.

**Comment by mtmorgan** [comment]
Looks like there was a successful push! Glad that we worked through this.

**Comment by demar01** [comment]
Yes, indeed. There is a problem with the build, but at least I can make and push changes back.

**Comment by mtmorgan** [comment]
11 February, 2021

Thanks for your patience

Warnings on the build report

- bad markup: fix with

    ```
    diff --git a/R/data.R b/R/data.R
    index eb669bc..9b0f385 100644
    --- a/R/data.R
    +++ b/R/data.R
    @@ -15,7 +15,6 @@
     #' @source Overmyer et al 2020.
     #' Large-Scale Multi-omic Analysis of COVID-19 Severity
     #' https://doi.org/10.1016/j.cels.2020.10.003
    -#' \href{https://www.sciencedirect.com/science/article/pii/S2405471220303719}
    -#' {doi: 10.1016/j.cels.2020.10.003}.
    +#' \href{https://www.sciencedirect.com/science/article/pii/S2405471220303719}{doi: 10.1016/j.cels.2020.10.003}.
     #'
     "peptides_data_filtered"
     ```

   and re-running devtools::document()

DESCRIPTION, NAMESPACE

- Good

vignettes

- good, thanks

- Should peptide data be represented more informatively as a data structure such as Biostrings::AAStringSet()?

R (comments on specific lines usually apply throughtout code)

- PeCorA.R:3 @param description should be extensive enough to help users understand expected inputs, e.g., 'a data.frame with columns...'

- PeCorA.R:44 use `message()` rather than `print()` for informative messages; `paste()` (e.g., line 82) is not usually required in `message()`.

- PeCorA.R:50 this 'copy and append style' is inefficient; use, e.g., lapply() (best) or pre-allocate-and-fill (see http://bioconductor.org/developers/how-to/efficient-code/)

- PeCorA_preprocessing.R:71 long lines of highly nested logic are difficult to understand. 'warnings' are usually important and avoidable, avoid using `suppressWarnings()` in your code and instead understand and protect against (e.g., removing NAs?) the root cause of the warngin. `which()` is usually unnecessary when subsetting, and just makes the code more difficult to read. Use whitespace around assignment and other operators. Revise as

    ```
    idx1 <- pecora_format$modpep_z == x
    idx2 <- t_cntrl$modpep_z == x
    ## subtract the ave of control
    ms1adj[idx1] <-  ms1scaled_full[idx1] - mean(ms1scaled_cntrl[idx2]
    ```

- ZZZ.R:3 declaring `globalVariables()` is dangerous, because all references to the variable are silenced even when they really _are_ undefined; this is particularly dangerous with commonly-used names like `x`. Use paradigms that avoid the need for this declaration, e.g., in the tidyverse using quoted arguments or `.data$...`.

- data.R the description here is not really sufficient -- the user would not be 
able to recreate the dataset from the information provided.

tests

- good start; it would be informative to develop fast tests that evaluated the code in the functions, rather than only checking that inputs are valid.

**Comment by demar01** [comment]
Hi Martin 

Thanks so much for your feedback. I will address these changes accordingly.

**Comment by mtmorgan** [comment]
please update your submission

**Comment by vjcitn** [comment]
@demar01 per your email to me of 22 March, this package will be labeled inactive.  Open this issue when you wish to resume development of the Bioconductor contribution.
