### ISSUE TITLE
SparseDOSSA2

### ISSUE THREAD

**Issue by sagun98** [Bioconductor/Contributions#1843]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/biobakery/SparseDOSSA2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by mtmorgan** [comment]
Usually it is more appropriate to update an existing package, perhaps with a 'major' version bump to 1.99.0 (so 2.0.0 in the next release) instead of adding a new package. Even if you add a new package, it should be accompanied by deprecation of the old package. Please clarify why you think it is appropriate to add a new package, and what you intend to do with the old package.

**Comment by mtmorgan** [comment]
Also, when I try and clone your repository on macOS I receive an error

```
$ git clone https://github.com/biobakery/SparseDOSSA2 --single-branch
Cloning into 'SparseDOSSA2'...
remote: Enumerating objects: 651, done.
remote: Counting objects: 100% (651/651), done.
remote: Compressing objects: 100% (395/395), done.
remote: Total 1148 (delta 426), reused 462 (delta 247), pack-reused 497
Receiving objects: 100% (1148/1148), 22.80 MiB | 4.77 MiB/s, done.
Resolving deltas: 100% (735/735), done.
error: unable to create symlink .github/README.md: File name too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

This https://stackoverflow.com/questions/18411200/git-unable-to-create-symlink-file-name-too-long suggests that you have changed a 'symlink' to a real file, without changing the mode of the file.

**Comment by sagun98** [comment]
Hi @mtmorgan, 

Many thanks for your review. 

1. The 'symlink' issue has been fixed.`git clone https://github.com/biobakery/SparseDOSSA2 --single-branch` is working without errors now.  

2. For the versioning of the new package(Why to add a new package):
- The codebase has been re-written from scratch and has barely any overlap with the old package.
- The underlying statistical model has major changes, from independent zero-inflated log-normal distributions of relative abundances to absolute abundances (marginal zero-inflated log normals) connected through a Gaussian copula. This is very much beyond simple model modifications.
- The two packages are designed to serve the same purpose, i.e. simulation of microbial abundance profiles so would it be possible to deprecate the old package but not remove it? An example would be [DESeq](https://bioconductor.org/packages/release/bioc/html/DESeq.html)(deprecated) and [DESeq2](https://bioconductor.org/packages/release/bioc/html/DESeq2.html) which are both still on Bioconductor. DESeq2 is a major update to DESeq, with fundamental method changes, similar to SparseDOSSA.

Please let me know your insights. 

Regards,
Sagun

**Comment by mtmorgan** [comment]
The acceptable route is to mark sparsDOSSA as deprecated in devel, it will be removed from devel in the next cycle (April / May) and consequently deprecated in release 3.13 (April / May) and removed from release 3.14 (October / November, 2021). DESeq is actually deprecated in the current release, and removed from devel; it should have been deprecated several years ago.

Would you like me to proceed with processing SparseDOSSA2, knowing that this means that sparseDOSSA will be deprecated in devel? (sorry for my slow response; I have been on vacation).

**Comment by sagun98** [comment]
Hi @mtmorgan, 

Yes, that sounds good. It is good to proceed with processing SparseDOSSA2, deprecating SparseDOSSA in devel. 

Thank you,
Sagun Maharjan

**Comment by sagun98** [comment]
Hi @nturaga/ @mtmorgan , 
```
FATAL: W any packages/SparseDOSSA2 sma-hsph DENIED by fallthru
```

Currently, my Bioconductor git credentials list email address syma.research@gmail.com, with Github username sagun98 (I changed this to syma-research, my current github user name but it does not fix the issue). The error message seems to suggest a github user sma-hsph, which I used to use but has since switched to syma-research. Which of these mismatches needs to be fixed before new build can be pushed to the upstream `git@git.bioconductor.org:packages/SparseDOSSA2`?

Thanks,
Sagun Maharjan

**Comment by nturaga** [comment]
Hi @sagun98 

If you are a contributor to the package, please add your name in the Authors list on the DESCRIPTION section. 

Use `Authors@R` as the field instead of `Author` and `Maintainer`. Please see the build report to your package and fix all the issues.  http://bioconductor.org/developers/package-guidelines/#description

**Comment by nturaga** [comment]
Hi @sagun98

You'll have to fix the errors on your build report before I review the package. It is easier for the reviewer to take a look at a package and evaluate it once it passes build, check on the builders. 

Best,

Nitesh

**Comment by nturaga** [comment]
Hi @sagun98 Since there hasn't been any movement on the package for the last month, I'm going to close the issue. One you have time you can reopen it.

Best,

Nitesh
