### ISSUE TITLE
flowTime

### ISSUE THREAD

**Issue by wrightrc** [Bioconductor/Contributions#185]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wrightrc/flowTime

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Hi,
Please address these issues raised by the Single Package Builder:

* checking DESCRIPTION meta-information ... NOTE
License components with restrictions not permitted:
  Artistic-2.0 + file LICENSE

* checking dependencies in R code ... NOTE
Package in Depends field not imported from: dplyr
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.

* checking R code for possible problems ... NOTE
addbs: no visible binding for global variable strain
addnorm : estimate_0: no visible global function definition for lm
fl1transform: no visible binding for global variable FL1.A
fl1transform: no visible binding for global variable FSC.A
fl1transform : trans: no visible binding for global variable FL1.A
...
Undefined global functions or variables:
  FL1.A FSC.A dipdoubletGate dipsingletGate hapdoubletGate
  hapsingletGate lm median sd splitFrame strain var yeastGate
Consider adding
  importFrom("stats", "lm", "median", "sd", "var")
to your NAMESPACE file.

* Checking to see if we understand object initialization....
    * NOTE: Consider clarifying how objects strain, lm, FL1.A, FSC.A,
      FL1.A, FSC.A, median, sd, splitFrame, var, yeastGate,
      dipsingletGate, dipdoubletGate, hapsingletGate, hapdoubletGate,
      yeastGate, hapsingletGate, hapdoubletGate, dipsingletGate,
      dipdoubletGate, yeastGate, hapsingletGate, hapdoubletGate,
      dipsingletGate, dipdoubletGate (used in addbs, addnorm,
      fl1transform, fl1transform, flsummary, flsummary, saveGates,
      steadyState, summarizeFlow, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA) were initialized. Maybe they are part
      of a data set loaded with data(), or perhaps part of an object
      referenced in with() or within().

Once these are taken care of I'll do a full review.
Valerie

**Comment by wrightrc** [comment]
Hi Valerie,

I have addressed the issues mentioned above and made a few other updates. The package is ready for review when you get a chance.

Thanks,
Clay

**Comment by vobencha** [comment]
Hi,

Nice job with flowTime. A few comments / suggestions below.

1) move .RData to data/ directory
.RData files are usually stored in the data/ directory; they need man pages and loading them is done with data("C6Gates.RData"). I like that you have a function that lists the gates but loading should be through the standard mechanism. Having the files in data/ makes them visible via a call to data() when the package is loaded.

    I would suggest keeping listGates but have a man page for each data set:
```
> listGates()
[1] "C6Gates.RData"      "defaultGates.RData" "SORPGates.RData"  
> ?C6Gates
No documentation for ‘C6Gates’ in specified packages and libraries:
you could try ‘??C6Gates’
```
Each man page should describe these objects.
```
> load("C6Gates.RData")
> objects()
[1] "dipdoubletGate" "dipsingletGate" "hapdoubletGate" "hapsingletGate"
[5] "yeastGate"    
```
Aren't there any descriptive statistics for the polygonGate? If yes, please include them on the man page.
```
> class(yeastGate)
[1] "polygonGate"
attr(,"package")
[1] "flowCore"
> dim(yeastGate)
Loading required package: flowCore
NULL
> length(yeastGate)
[1] 1
> names(yeastGate)
NULL
```
2) function names
get_time() and qa.gating() are not named consistent with the other functions. It looks like you've gone with camelCase so please change those to match.

```
~/flowTime/man >ls
addbs.Rd             dipdoubletGate.Rd  get_time.Rd        loadGates.Rd  saveGates.Rd      yeastGate.Rd
addnorm.Rd           dipsingletGate.Rd  hapdoubletGate.Rd  ploidy.Rd     setGates.Rd
annotateFlowSet.Rd   flsummary.Rd       hapsingletGate.Rd  polygate.Rd   steadyState.Rd
createAnnotation.Rd  gateEnv.Rd         listGates.Rd       qa.gating.Rd  summarizeFlow.Rd
```
Valerie

**Comment by wrightrc** [comment]
Thank you!

Can the user make changes to the data/ directory? I included these .RData gate sets in extdata/ such that users can also add their own gate sets to this directory using `saveGates`. Also the user should be able to change the `defaultGates` to `C6Gates`, `SORPGates`, or their own gate set. Perhaps, it is best to deal with setting defaults in extdata/ (as is done currently) but pull the included gate sets from data/ as you recommend.

Now, I am also thinking it is best to separate "User" gates from "Included" gates such that package updates will not overwrite "User" gates. Upon saving a gate set (in a user-defined directory), `saveGates` could then prompt the user to add them to a branch of the flowTime github repository for inclusion in the next release, for ease of use and reproducibility. This would also fit the conventions and documentation requirements you mentioned.

What are your thoughts on this approach?

Thanks,
Clay

**Comment by vobencha** [comment]
I would recommend you have non-changeable data in data/. Users should be responsible for managing their own gates and they should not be able to add these gates to the flowTime package (no access to github repo). The functions in flowTime should have a 'gatePath' input argument that by default uses the gates in data/. If the user wants to use their own gate they can provide their own path.

Valerie

**Comment by vobencha** [comment]
Are you planning to submit another version or should I close this issue?

Valerie

**Comment by wrightrc** [comment]
Yes, I will submit another version. Sorry for the delay. I will have an updated version including your suggestions by March 17.

**Comment by vobencha** [comment]
Thanks for making the changes. The man pages for datasets in data/ should show how to load the data with
 ```
data(hapdoubletGate)
```
etc.

The built tarball must be <= 4MB on disk, see http://www.bioconductor.org/developers/package-guidelines/#correctness. You'll need to reduce the size of the datasets and/or use a more efficient compression method. The current size is 24 MB:

~/proj/git/software >du -h flowTime_0.99.6.tar.gz 
24M	flowTime_0.99.6.tar.gz

Valerie

**Comment by wrightrc** [comment]
Ok, I've trimmed down the example data and updated the data/ man pages. The error now is from oaxaca, which I believe is soon to be decommissioned, correct?

**Comment by vobencha** [comment]
OK, looks good. Thanks for making the changes. I'm marking the package as accepted - you should get an email in the next week with svn credentials and instructions for next steps.
Valerie
