### ISSUE TITLE
(inactive) RIC

### ISSUE THREAD

**Issue by demar01** [Bioconductor/Contributions#1851]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/demar01/RIC

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by mtmorgan** [comment]
The empty `ORCID = ""` in ` comment = c(ORCID = "0000-0002-6287-8367",ORCID = "")` is blocking initial processing; can you please remove or update it?

**Comment by demar01** [comment]
Oh, I missed that. It is changed now. However I cannot see RIC package neither on 
`   ssh -T git@git.bioconductor.org
`
nor on BiocCredentials

I can see another package, which is using the same SSH key. 

What I am missing here?

**Comment by mtmorgan** [comment]
It hasn't been been added to git.bioconductor.org because it was not a valid 'package'. Now that the ORCID issue has been updated, it will be processed; wait unitl the '1. awaiting moderation' tag has been replaced by '2. review in process'.

**Comment by mtmorgan** [comment]
Sorry for the delay in responding. The Authors@R field is still not correct; I think it should be something like
```
Authors@R: 
    c(person(given = "Maria",
           family = "Dermit",
           role = c("aut","cre"),
           comment = c(ORCID = "0000-0002-6287-8367"),
           email = "maria.dermit@qmul.ac.uk"),
      person(given = "Ni",
           family = "Shuai",
           role = "aut",
           email = "nishuai@yahoo.com")
    )
```
(a vector of `person()` objects).

**Comment by demar01** [comment]
I changed and I updated the remotes in my repo
` git remote -v`
origin	https://github.com/demar01/RIC.git (fetch)
origin	https://github.com/demar01/RIC.git (push)
upstream	git@git.bioconductor.org:packages/RIC.git (fetch)
upstream	git@git.bioconductor.org:packages/RIC.git (push)

However, I cannot push after adding and commiting. 

`git push git@git.bioconductor.org:packages/RIC`

fatal: Could not read from remote repository.

The package is not listed in

` https://git.bioconductor.org/BiocCredentials/permissions_by_user/`

What may I be missing?

**Comment by mtmorgan** [comment]
To be add to our git the DESCRIPTION file has to be correct. Since the DESCRIPTION file was not correct, the package was not added to our git. The DESCRIPTION file is now correct, so the package has been added to our git; you should be able to push changes now.

**Comment by mtmorgan** [comment]
...but it looks like your package depends on another package, RICdata, and that RICdata should have been submitted first. I think you should follow the instructions for adding an additional package, starting at step 3 of https://github.com/Bioconductor/Contributions#submitting-related-packages. Get the additional package building correctly (it needs to be moderated, so it will not be built until that step has occurred) and then return to RIC.

**Comment by demar01** [comment]
Appreciate your guidance!

**Comment by lshep** [comment]
Do you plan to submit RICdata here as an accompanied package?  If so please remember to submit under this issue [submitting related packages](https://github.com/Bioconductor/Contributions#submitting-related-packages)

**Comment by demar01** [comment]
Hi, 
Thanks for your message. Yes, I am planning to submit RICdata. In fact I tried to submit it (as an ExperimentalData package ) last week but it failed because it was too big. Do I necessarily need to submit it to ExperimentHub?

**Comment by lshep** [comment]
ExperimentHub is the recommend option for large file sizes.

**Comment by demar01** [comment]
In the ExperimentHubData vignette is says I would need assistance from a Bioconductor team member to submit data to ExperimentHub . Could you point me out to instructions to submit these data?
> https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHubData/inst/doc/CreateAnExperimentHubPackage.html
Many thanks

**Comment by lshep** [comment]
@demar01  I think I emailed you credentials.  If you did not receive them please let me know.

**Comment by demar01** [comment]
@lshep, thank you,  I confirm I have received them.

**Comment by lshep** [comment]
Do you plan on moving forward with the submission? We normally expect movement within 2-3 weeks to keep the submission process moving forward.

**Comment by demar01** [comment]
It is my intention to move forward with this submission. However, I would need to submit another package (RICdata) before submitting RIC. RICdata has some dependencies of other packages (RBDmap https://www.huber.embl.de/users/befische/RBDmap/Rpackage/index.html), which is not currently in bioconductor and I need to make sure I follow the dependencies correctly.


Maria Dermit
Postdoctoral Research Assistant | Centre for Molecular Oncology

Barts Cancer Institute - a Cancer Research UK Centre of Excellence
Queen Mary, University of London
John Vane Science Centre, Charterhouse Square, London EC1M 6BQ
Email: ***@***.***
________________________________

**Comment by lshep** [comment]
Okay. Thank you for the clarification.  Cheers

**Comment by lshep** [comment]
I will close this issue for now.  When the other dependencies have been cleared up, please ping on this issue and I will reopen and continue the review.  Cheers
