### ISSUE TITLE
Submitting Package WhistleR

### ISSUE THREAD

**Issue by ZW-xjtlu** [Bioconductor/Contributions#1871]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ZW-xjtlu/WhistleR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by hpages** [comment]
Thanks for the submission. Package looks good.

2 minor things:

(1) The vignette says:
  > WhistleR can be installed from both bioconductor and github.

  Please note that we strongly discourage installing Bioconductor packages from GitHub. Because of Bioconductor 6-month release cycles and because Bioconductor has a notion of release and devel, Bioconductor users should always use `BiocManager::install()` to install packages. This will spare them a lot of headaches with version mismatches. Please instruct your users to install the package with `BiocManager::install()` and do not encourage them to install from GitHub.

(2) You can do:

    X <- makeGRangesFromDataFrame(X_df)

  instead of:

    X <- GRanges(seqnames = X_df[,1],
    ranges = IRanges(start = X_df[,2],
    end = X_df[,3]),
    strand = X_df[,5])

Thanks,
H.

**Comment by ZW-xjtlu** [comment]
> Thanks for the submission. Package looks good.
> 
> 2 minor things:
> 
> (1) The vignette says:
> 
> > WhistleR can be installed from both bioconductor and github.
> 
> Please note that we strongly discourage installing Bioconductor packages from GitHub. Because of Bioconductor 6-month release cycles and because Bioconductor has a notion of release and devel, Bioconductor users should always use `BiocManager::install()` to install packages. This will spare them a lot of headaches with version mismatches. Please instruct your users to install the package with `BiocManager::install()` and do not encourage them to install from GitHub.
> 
> (2) You can do:
> 
> ```
> X <- makeGRangesFromDataFrame(X_df)
> ```
> 
> instead of:
> 
> ```
> X <- GRanges(seqnames = X_df[,1],
> ranges = IRanges(start = X_df[,2],
> end = X_df[,3]),
> strand = X_df[,5])
> ```
> 
> Thanks,
> H.

Dear hpages,

Thank you very much for your review and comments. All of the 2 points are now implemented in the newest version (0.99.5).

With my best wishes,
Zhen

**Comment by hpages** [comment]
Thanks for the changes.

I just realize now that `WhistlerUsersGuide.pdf` is a precompiled vignette and that the _real vignette_ (`Vignette_V_1.0.0.Rmd`) is basically a pointer to the precompiled vignette. This is incompatible with Bioconductor guidelines.

The reason static/precompiled vignettes must be avoided is that there's no way to know when the code in them breaks. And the code in them _will_ break at some point. Also this will happen sooner than you expect given that the package has 100+ dependencies (direct and indirect).

OTOH when the code in a _real vignette_ (i.e. a vignette with code chunks that are evaluated by `R CMD check`) breaks, we will immediately know that, thanks to our daily checks. This is why providing a _real vignette_ is a key feature of Bioconductor.

Thanks,
H.

**Comment by ZW-xjtlu** [comment]
@hpages Thanks very much for your comment and explanations. 

The real vignette will be added soon. However, I have 2 more questions: (1) Since the Machine learning packages (H2O) I need to demonstrate are not installed on the Bioconductor server. So, can I add some key examples in the real vignette but also keep the precompiled `WhistlerUsersGuide.pdf`? (2) Can I at this stage change the name of the package?

Best wishes,
Zhen

**Comment by hpages** [comment]
Hi @ZW-xjtlu ,

If your typical workflow requires CRAN package **h2o**, then this needs to be formally stated by listing **h2o** in your `Suggests` field. This will trigger automatic installation of **h2o** on the build machines.

As for renaming the package at this stage, I'm not sure what's the best way to do it. Maybe resubmit with a different name and explain the situation in the new submission? @lshep @vjcitn @nturaga Would that be ok or maybe there is an easier way? Thanks.

H.

**Comment by nturaga** [comment]
It’s easier to close this completely and open another one in my opinion.

Otherwise, the name change has to be done on the SPB and then the git ecosystem too.

**Comment by vjcitn** [comment]
The name should not be changed unless there is an extremely compelling reason.

**Comment by hpages** [comment]
Thanks Nitesh, Vince.

@nturaga @lshep If they resubmit with a different name, then I guess I'll change the status of this submission to "declined". Will this trigger automatic removal of Whistler from our git server or will this need to be handled manually? Thanks

**Comment by lshep** [comment]
As far as I know there is no auto removal process and it would have to be removed manually by @nturaga

**Comment by hpages** [comment]
Any update on this @ZW-xjtlu ? Thanks

**Comment by ZW-xjtlu** [comment]
Dear Herve,

Sorry for the late reply; my time is mostly occupied by teaching recently. Thanks for your clarification on the situation, so I decide to re-submit the package using another name.

With my best wishes,
Zhen

On Apr 9, 2021, at 5:28 PM, Hervé Pagès ***@***.******@***.***>> wrote:



Any update on this @ZW-xjtlu<https://github.com/ZW-xjtlu> ? Thanks

**Comment by lshep** [comment]
@vjcitn  @nturaga   I believe this means we can delete this out of the git.bioconductor.org repository?

**Comment by nturaga** [comment]
I've removed it from git.bioconductor. Thanks!
