### ISSUE TITLE
PhIPData

### ISSUE THREAD

**Issue by athchen** [Bioconductor/Contributions#1927]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/athchen/PhIPData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by athchen** [comment]
For the build on Windows, there was a warning in `R CMD check` that the documentation files could not be opened (see below). I'm unsure of how to fix it.  Any pointers?

```
* checking whether package 'PhIPData' can be installed ... WARNING
Found the following significant warnings:
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/assays<-,PhIPData,list-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/assays<-,PhIPData,SimpleList-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/assay<-,PhIPData,missing-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/assay<-,PhIPData,numeric-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/assay<-,PhIPData,character-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/counts<-,PhIPData-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/logfc<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/logfc<-,PhIPData-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/prob<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/prob<-,PhIPData-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/peptideInfo<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/peptideInfo<-,PhIPData-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/sampleInfo<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1927/66c27a41aa9f7c44587c80694b6f797404d558a5/PhIPData.buildbin-libdir/00LOCK-PhIPData/00new/PhIPData/help/sampleInfo<-,PhIPData-method.html': Invalid argument
```

**Comment by Kayla-Morrell** [comment]
@athchen - This is a common issue we are seeing on the windows builders and can be ignored for now.

**Comment by athchen** [comment]
Hi Kayla, 

I had a question regarding the data directories. Currently the `data_raw` directory contains code to generate data in `inst/extdata/alias.rda` which should be moved to `inst/scripts` as you had mentioned. With regards to the `inst/libraries` folder, it's meant to serve as a default location to store rds files containing peptide annotations that would frequently be reused when constructing PhIPData objects. Would this be better as a sub-folder in `inst/extdata`?

**Comment by Kayla-Morrell** [comment]
@athchen - Thank you for the explanation. I think it would be fine to keep the structure as is for `inst/libraries`.

**Comment by athchen** [comment]
@Kayla-Morrell Thanks! I've listed the updates below and the package should be ready for re-review. 

## DESCRIPTION
> * [x]  REQUIRED: 'LazyData:' should be set to 'false'. It has been our experience
>   that when this field is set to 'true' is can slow down the loading of the
>   package especially if it contains data.
- 'LazyData' has been set to `false`
> * [x]  SUGGESTION: Consider adding these automatically suggested biocViews:
>   - Sequencing
>   - Coverage
- These have both been added to biocViews.

## Data
> * [x]  REQUIRED: The data needs a bit of cleaning up. Generally we only allow for
>   'inst/extdata/' directories for raw data files, and 'data/' directories for
>   data that is exported and readily available for the users. I'm not sure what the
>   purpose is of the 'data-raw' directory or the 'inst/libraries' directory. Maybe
>   these files belong else where?
- The files in the `data-raw` directory has been moved to `inst/script`, and the `inst/libraries` folder has remained as mentioned above.
> * [x]  REQUIRED: Since you are including 'inst/extdata' in your package, there
>   needs to be corresponding documentation in an 'inst/script' directory. The
>   scripts in this directory can vary. It should be clearly documented how the data
>   was generated. It should include source urls and any important information
>   regarding filtering or processing. It can be executible code, sudo code, or a
>   text description. A user should be able to download and roughly reproduce the
>   file or object that is present as data.
- All files in `inst/extdata` have a corresponding file in `inst/scripts` describing how the data was generated. 

## Man pages
> * [x]  REQUIRED: The 'figures/' directory is not allowed within the 'man/'
>   directory. If you need these figures I would suggest moving them to an
>   'inst/figures/' directory.
- This folder has been removed.
> * [x]  SUGGESTION: If you need to not run an example in a man page we suggest
>   using donttest{} instead of dontrun{} since donttest{} requires vaild R code.
- The code in dontrun{} may change default user settings for the package, so I have left them as dontrun{} instead of donttest{}.

## R code
> * [x]  SUGGESTION: For formatting reasons, consider shorter lines. There are 69
>   lines that are > 80 characters long.
- I tried to fix most of these, but I think some of the lines in the vignette are still too long. 
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>   line indents. There are 430 lines that are not.

**Comment by Kayla-Morrell** [comment]
@athchen - Thank you for making the necessary changes. I have looked everything over and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by athchen** [comment]
@Kayla-Morrell Thank you so much for all of the help and the quick review. I have one (hopefully) last question. If I have a related package I plan on submitting later, should I create a new issue or comment on this one? I know in the README of this repo it says to comment here, but since this one has been accepted would it be more appropriate to open a new issue?

**Comment by Kayla-Morrell** [comment]
@athchen - Since this one is accepted I would say it would be best to just open a new issue when the related package is ready for submission.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/athchen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PhIPData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PhIPData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
