### ISSUE TITLE
MsBackendMgf

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/Contributions#1930]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rformassspectrometry/MsBackendMgf

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LiNk-NY** [comment]
Hi Johannes, @jorainer 

Thank for your submission to Bioconductor. 
Here is the short review. 

Best,
Marcel

---

# MsBackendMgf #1930

## DESCRIPTION

* It looks good.
* Perhaps consider using the BiocIO::import generic to provide an import
method for `mgf` files.

## NAMESPACE

* It looks good.

## vignettes

* The installation should look consistent with the landing page instructions.

## R

* I think it makes sense to have an `import` and `export` method for the file
type. `import` may replace `backendInitialize`.
* You can then choose to pass along the imported file to the `Spectra`
constructor function or immediately represent the file using `Spectra` as the
return of `import()`.
* Default `BPPARAM = bpparam()` configuration should not use all the cores
available. Please use one or two cores and allow users to adjust this.

## tests

* Looks good.

**Comment by jorainer** [comment]
Thanks Marcel @LiNk-NY for the review and comments! Below my replies.


# Description

> - Perhaps consider using the BiocIO::import generic to provide an import
method for mgf files.

Thanks for the suggestion, I do however think we don't need a dedicated `import` method here (sorry, this will be a lengtht explanation :) ). The `MsBackendMgf` backend is not thought to provide generic data import/export functions for MGF files (`MSnbase` has for example such functions). `MsBackendMgf` is thought to add support to read and write MGF files to the `Spectra` package, i.e. this package is thought to be used **exclusively** with the `Spectra` package. We have several such *backend* packages that add support for different file types or ways how to store the data. The idea was to have many small packages with support for certain file types/storage options to be flexible and expandable. See also below for a more detailed description.

# vignettes

> - The installation should look consistent with the landing page instructions.

I've updated/fixed this in the recent commit (https://github.com/rformassspectrometry/MsBackendMgf/commit/bb718c760c915cff03bf34f48bbc013b1fe6543e).

# R

> - I think it makes sense to have an `import` and `export` method for the file type. import may replace `backendInitialize`.

I see your point. But we use a different concept than a simple `import`/`export` in `Spectra`. The `Spectra` object just provides the user functionality to work with spectra data, everything related to data import, export and **data representation and storage** is taken care by `MsBackend` classes. Especially the latter point is key for us: MS data can be very large, so in many instances we don't *import* the data at all. We just know where the data is and the backend retrieves the needed data on demand. Thus, for many backends (`MsBackendMzR`, `MsBackendHdf5Peaks`, `MsBackendMassbankSql`) the data resides in external files and is never imported as a whole. This is also the reason why I would like to keep the `backendInitialize` instead of `import`, because in fact we are just *initializing* the backend (well, in the case of the `MsBackendMgf` we are actually reading the data - but we could also have another backend that only retrieves data from MGF files on demand). I hope I can convince you that we don't have to change that - also because this would change the whole concept.

> - You can then choose to pass along the imported file to the `Spectra` constructor function or immediately represent the file using Spectra as the return of `import()`.

See previous point. For this particular backend implementation that looks like a good idea, but this would be against the whole concept of the `MsBackend` we introduced: the `MsBackend` is not a pure *data importer*, it is rather a *data representator* or *data provider*.

> - Default `BPPARAM = bpparam()` configuration should not use all the cores available. Please use one or two cores and allow users to adjust this.

I thought the default `bpparam()` does not use all cores. Is there a way we could do that? Note that in general (in the `Spectra` package) we suggest people to always register first a parallel processing setup which fits their needs.  


I hope I could convince you that using a dedicated `import` method would not fit into the more general picture of the `Spectra`/`MsBackend` concept.

thanks again!

**Comment by jorainer** [comment]
Hi Marcel,

thanks for the feedback. I agree, might be helpful to provide the MGF file import functionality also outside of the `Spectra` ecosystem. I have now exported the `readMgf` function that allows to import the data from a MGF file (in commit https://github.com/rformassspectrometry/MsBackendMgf/commit/d9bce6d429724dd0922b049bb2db8f9fe7abebfd).

Also, I changed the examples and vignette to use `register(SerialParam())` pointing to the `BiocParallel` package documentation for other options.

Thanks for your suggestions!

cheers, jo

**Comment by jorainer** [comment]
Hm, there seems to be an issue with the package builder - I pushed the updates also to the *upstream* (git@git.bioconductor.org:packages/MsBackendMgf.git) but the *bioc-issue-bot* did not update this info here...

**Comment by LiNk-NY** [comment]
> Hm, there seems to be an issue with the package builder - I pushed the updates also to the _upstream_ ([git@git.bioconductor.org](mailto:git@git.bioconductor.org):packages/MsBackendMgf.git) but the _bioc-issue-bot_ did not update this info here...

Hi Johannes, @jorainer
Did you bump the version of the package? That is usually what triggers it. 

Thanks for making those changes! I will have a quick look and accept.
Best,
Marcel

**Comment by LiNk-NY** [comment]
*Update*: This looks good to me.  Thanks for your contribution! 

Best,
Marcel

**Comment by jorainer** [comment]
Thanks Marcel - of course I forgot to bump the version ...

**Comment by jorainer** [comment]
Build looks good - looking forward for the package being accepted and added to BioC 😊 

Thanks again Marcel @LiNk-NY for the review!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jorainer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MsBackendMgf")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MsBackendMgf

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
