### ISSUE TITLE
Submit FEAST to Bioconductor

### ISSUE THREAD

**Issue by suke18** [Bioconductor/Contributions#1943]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/suke18/FEAST

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by vjcitn** [comment]
Hi -- note that BiocCheck::BiocCheck discovers an error in your submission
Error in .precheck_filesize(wd) : files larger than 5Mb:
  /data/Deng.RData

Please repair and rerun BiocCheck before committing changes, and file a comment here when
that is done.

**Comment by suke18** [comment]
remove the large data. Please check again.

**Comment by vjcitn** [comment]
Please fix the issues identified in R CMD check for the devel branch of R.
```
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS$ Rdev CMD check FEAST_0.99.1.tar.gz
1/9 packages newly attached/loaded, see sessionInfo() for details.
* using log directory '/home/stvjc/SUBMISSIONS/FEAST.Rcheck'
* using R Under development (unstable) (2020-12-08 r79595)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file 'FEAST/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'FEAST' version '0.99.1'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... NOTE
Depends: includes the non-default packages:
  'limma', 'knitr', 'aricode', 'assertthat', 'matrixStats', 'mclust',
  'SingleCellExperiment', 'SummarizedExperiment', 'doParallel', 'irlba'
Adding so many packages to the search path is excessive and importing
selectively is preferable.
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package 'FEAST' can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import 'matrixStats::rowRanges' by 'SummarizedExperiment::rowRanges' when loading 'FEAST'
See '/home/stvjc/SUBMISSIONS/FEAST.Rcheck/00install.out' for details.
* checking installed package size ... OK
* checking package directory ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... NOTE
Packages listed in more than one of Depends, Imports, Suggests, Enhances:
  'limma' 'mclust' 'aricode' 'assertthat' 'SummarizedExperiment' 'SingleCellExperiment' 'doParallel'
A package should be listed in only one of these fields.
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... WARNING
Subdirectory 'data' contains no data sets.
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  ‘Biobase’ ‘SingleCellExperiment’ ‘limma’
  All declared Imports should be used.
Packages in Depends field not imported from:
  ‘SingleCellExperiment’ ‘knitr’ ‘limma’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
Cal_Fisher_PS: no visible global function definition for ‘median’
Cal_Fisher_PS: no visible global function definition for ‘cal_fisher2’
Cal_Fisher_PS: no visible global function definition for
  ‘txtProgressBar’
Cal_Fisher_PS: no visible global function definition for
  ‘setTxtProgressBar’
Cal_Fisher_PS: no visible global function definition for ‘p.adjust’
Consensus: no visible global function definition for ‘median’
Consensus: no visible global function definition for ‘prcomp’
Consensus: no visible global function definition for ‘txtProgressBar’
Consensus: no visible global function definition for
  ‘setTxtProgressBar’
FEAST: no visible global function definition for ‘median’
FEAST: no visible global function definition for ‘detectCores’
FEAST: no visible global function definition for ‘makeCluster’
FEAST: no visible global function definition for ‘prcomp’
FEAST: no visible global function definition for ‘%dopar%’
FEAST: no visible global function definition for ‘foreach’
FEAST: no visible binding for global variable ‘i’
FEAST: no visible global function definition for ‘stopCluster’
FEAST_fast: no visible global function definition for ‘median’
FEAST_fast: no visible global function definition for ‘detectCores’
FEAST_fast: no visible global function definition for ‘makeCluster’
FEAST_fast: no visible global function definition for ‘txtProgressBar’
FEAST_fast : f : <anonymous>: no visible global function definition for
  ‘setTxtProgressBar’
FEAST_fast : f : <anonymous>: no visible global function definition for
  ‘flush.console’
FEAST_fast: no visible global function definition for ‘%dopar%’
FEAST_fast: no visible global function definition for ‘foreach’
FEAST_fast: no visible binding for global variable ‘i’
FEAST_fast: no visible global function definition for ‘kmeans’
FEAST_fast: no visible global function definition for ‘stopCluster’
Norm_Y: no visible global function definition for ‘median’
SC3_Clust: no visible global function definition for
  ‘SingleCellExperiment’
SC3_Clust: no visible global function definition for ‘metadata’
Select_Model_short_SC3: no visible global function definition for
  ‘median’
Select_Model_short_SC3: no visible global function definition for
  ‘txtProgressBar’
Select_Model_short_SC3: no visible global function definition for
  ‘setTxtProgressBar’
Select_Model_short_TSCAN: no visible global function definition for
  ‘median’
Select_Model_short_TSCAN: no visible global function definition for
  ‘txtProgressBar’
Select_Model_short_TSCAN: no visible global function definition for
  ‘setTxtProgressBar’
Seurat_Clust: no visible global function definition for
  ‘CreateSeuratObject’
Seurat_Clust: no visible global function definition for ‘NormalizeData’
Seurat_Clust: no visible global function definition for
  ‘FindVariableFeatures’
Seurat_Clust: no visible global function definition for ‘ScaleData’
Seurat_Clust: no visible global function definition for ‘RunPCA’
Seurat_Clust: no visible global function definition for
  ‘VariableFeatures’
Seurat_Clust: no visible global function definition for ‘FindNeighbors’
Seurat_Clust: no visible global function definition for ‘FindClusters’
Seurat_Clust: no visible global function definition for ‘Idents’
TSCAN_Clust: no visible global function definition for ‘preprocess’
TSCAN_Clust: no visible global function definition for ‘prcomp’
TSCAN_Clust : <anonymous>: no visible global function definition for
  ‘lm’
Visual_Rslt: no visible global function definition for ‘ggbarplot’
Visual_Rslt: no visible global function definition for ‘theme’
Visual_Rslt: no visible global function definition for ‘element_text’
Visual_Rslt: no visible global function definition for ‘ggline’
Visual_Rslt: no visible global function definition for ‘get_palette’
Visual_Rslt: no visible global function definition for
  ‘scale_y_continuous’
Visual_Rslt: no visible global function definition for ‘guides’
Visual_Rslt: no visible global function definition for ‘guide_legend’
Visual_Rslt: no visible global function definition for ‘ggarrange’
cal_F2: no visible global function definition for ‘median’
cal_F2: no visible global function definition for ‘txtProgressBar’
cal_F2: no visible global function definition for ‘setTxtProgressBar’
cal_F2: no visible global function definition for ‘pf’
cal_Fisher2: no visible global function definition for ‘median’
cal_MSE: no visible global function definition for ‘model.matrix’
vector2matrix: no visible global function definition for ‘combn’
Undefined global functions or variables:
  %dopar% CreateSeuratObject FindClusters FindNeighbors
  FindVariableFeatures Idents NormalizeData RunPCA ScaleData
  SingleCellExperiment VariableFeatures cal_fisher2 combn detectCores
  element_text flush.console foreach get_palette ggarrange ggbarplot
  ggline guide_legend guides i kmeans lm makeCluster median metadata
  model.matrix p.adjust pf prcomp preprocess scale_y_continuous
  setTxtProgressBar stopCluster theme txtProgressBar
Consider adding
  importFrom("stats", "kmeans", "lm", "median", "model.matrix",
             "p.adjust", "pf", "prcomp")
  importFrom("utils", "combn", "flush.console", "setTxtProgressBar",
             "txtProgressBar")
to your NAMESPACE file.
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘FEAST_fast’ ‘Select_Model_short_SC3’ ‘Visual_Rslt’
Undocumented data sets:
  ‘Deng’ ‘Zheng’
All user-level objects in a package should have documentation entries.
See chapter 'Writing R documentation files' in the 'Writing R
Extensions' manual.
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'Consensus'
  ‘thred’

Undocumented arguments in documentation object 'FEAST'
  ‘batch_size’

Undocumented arguments in documentation object 'Seurat_Clust'
  ‘Y’ ‘knn’ ‘resolution’ ‘input_markers’

Undocumented arguments in documentation object 'cal_3_metrics'
  ‘randMethod’

Undocumented arguments in documentation object 'cal_F2'
  ‘classes’

Undocumented arguments in documentation object 'cal_Fisher2'
  ‘classes’

Undocumented arguments in documentation object 'cal_MSE'
  ‘return_mses’

Undocumented arguments in documentation object 'process_Y'
  ‘thre’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter 'Writing R documentation files' in the 'Writing R
Extensions' manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ... NONE
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking running R code from vignettes ...
  'FEAST.Rmd' using 'UTF-8'... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 4 WARNINGs, 4 NOTEs
See
  '/home/stvjc/SUBMISSIONS/FEAST.Rcheck/00check.log'
for details.

```
Also ensure that BiocCheck is run and produces no warnings or errors.  Thanks!

**Comment by vjcitn** [comment]
Also please remove .so and .rds files from src folder

**Comment by suke18** [comment]
Hello Vince, 

Thanks for checking. I modified accordingly. Also, I checked with BiocCheck and devtools::check. There is an error however no specific message associated. I paste the part here: 

Summary:
ERROR count: 1
WARNING count: 7
NOTE count: 10
For detailed information about these checks, see the BiocCheck
vignette, available at
https://bioconductor.org/packages/3.12/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#interpreting-bioccheck-output
BiocCheck FAILED.
$error
[1] "At least 80% of man pages documenting exported objects must have runnable examples. The following pages do not:"

$warning
[1] "The following files are over 5MB in size: '.git/objects/2b/0c83db9f093a825c9d0eeba54cbe2afcf8fa64 .git/objects/30/331b35aa8742b3058b8351be2dba865cc9abc8 .git/objects/a6/28e651f15d8ba32d95c143b5236c743251c7dd .git/objects/b6/ff11f38d3c78612226eb4b8232d9582716db35'"
[2] "'scRNA-seq' is an invalid BiocViews term."

I not sure whether there is a real error or not. Could you help figure this out? 

Best, 
Kenong

**Comment by vjcitn** [comment]
Thank you.  Git is very careful to preserve the history of a project.  If a large file is committed, an image
of it is retained.   See https://bioconductor.org/developers/how-to/git/remove-large-data/  to solve this.

With R CMD check of your latest source I see multiple issues that should be easy to fix
```
Packages listed in more than one of Depends, Imports, Suggests, Enhances:
  'limma' 'mclust' 'aricode' 'assertthat' 'SummarizedExperiment' 'SingleCellExperiment' 'doParallel'
A package should be listed in only one of these fields.
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  ‘Biobase’ ‘limma’
  All declared Imports should be used.
Packages in Depends field not imported from:
  ‘knitr’ ‘limma’
  These packages need to be imported from (in the NAMESPACE file)
```
also
```
* checking examples ... ERROR
Running examples in 'FEAST-Ex.R' failed
The error most likely occurred in:

> ### Name: cal_MSE
> ### Title: Standard way to preprocess the count matrix. It is the QC step
> ###   for the genes.
> ### Aliases: cal_MSE
> 
> ### ** Examples
> 
> cal_MSE(Ynorm, cluster)
Error in is.factor(x) : object 'cluster' not found
Calls: cal_MSE ... model.frame.default -> eval -> eval -> as.factor -> is.factor
Execution halted
```
You must read BiocCheck output carefully
```
    * WARNING: Add non-empty \value sections to the following man
      pages: man/Seurat_Clust.Rd, man/vector2matrix.Rd
    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples. The following pages do not:
      cal_F2.Rd, Consensus.Rd, eval_Cluster.Rd, FEAST_fast.Rd,
  FEAST.Rd, SC3_Clust.Rd
```
Try to get the large file out, after which your package can be added to single-package builder and you can
have automated checking.

**Comment by suke18** [comment]
Hello Vince, 

Thanks for checking. It is my first time submitting to Bioconductor. I appreciate your patience. I used BiocCheck and there is no error messages. I also https://bioconductor.org/developers/how-to/git/remove-large-data/ to delete large files. Could you please check again. 

Best, 
Kenong

**Comment by suke18** [comment]
Hello Vince, 

Followed up on the last thread, the assets folder is not for submission to Bioconductor. It is mainly used for demonstration in the readme file in Github. 

Best, 
Kenong

**Comment by vjcitn** [comment]
Thanks for your efforts.  We are managing close to 2000 contributed packages so certain conventions need to be followed.  I checked out the latest version and clearly the git payload has decreased.  But the tarball is still 9MB.  R CMD check reveals many problems with documentation, DESCRIPTION file has packages listed in multiple fields, Yan.RData can have size reduced by saving with compression="xz".  You mention an assets folder ... if you do not want it in Bioconductor please move it (and any other unwanted items) to a branch other than main/master.  Please check out a clean version of your code in an empty folder, use R-devel, run R CMD build and R CMD check on the tarball.  Revise the code until all warnings and errors are gone.  Thanks again!

**Comment by suke18** [comment]
Hello Vince, 

Thank you again for checking. Right now, I used BiocCheck and there are no errors and warnings. From R CMD CHECK, there is no error as well. Could you please check again? I tried to resize the git repository to 9M. Even though I tried "java -jar ~/Downloads/bfg-1.14.0.jar --strip-blobs-bigger-than 1B .", there is still 4.1M for the .git folder. Together, it is 10M. The R package itself is less than 5M. Could you please let me know how to further resize the .git folder? 

Best, 
Kenong

**Comment by suke18** [comment]
Hello Vince, 

I found the error is about the number of cores recruited by makeCluster() function. I update the FEAST package. From BiocCheck and R CMD CHECK, there are no errors or warnings. However, I updated my github ssh keys. I could link to the Bioconductor git.  I am wondering is there a way to connect to the upstream Bioconductor git again? 

Best, 
Kenong

**Comment by suke18** [comment]
Hello,

I updated my SSH Key. I my local folder, I can do "git remote -v": 

origin	https://github.com/suke18/FEAST (fetch)
origin	https://github.com/suke18/FEAST (push)
upstream	git@git.bioconductor.org:packages/FEAST (fetch)
upstream	git@git.bioconductor.org:packages/FEAST (push).

However, I couldn't push to the Bioconductor git upstream: "git push upstream master":

"To git.bioconductor.org:packages/FEAST
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@git.bioconductor.org:packages/FEAST'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details."

Do you have any ideas on how to fix this? 

Best, 
Kenong

**Comment by lshep** [comment]
You can add keys to your account if you updated them by activating your [git Credentials account](https://git.bioconductor.org/BiocCredentials) .   Please also see the hints in the ERROR that suggest doing a `git pull` before pushing.

**Comment by suke18** [comment]
Hi, 

I did activate my Bioconductor git credentials. Now, the upstream master is up-to-date, 

git push upstream master

Everything up-to-date

Could you check the updated FEAST package? From my end, by BiocCheck and R CMD CHECK, there are 0 errors and warnings. 

Best, 
Kenong

**Comment by lshep** [comment]
We will not do a manual check.  It is important to figure out the pushing to git.bioconductor.org procedure for being able to update your package on our system.  Did you push with a valid version bump in the DESCRIPTION?  A build is only triggered with a valid version bump so you would want to bump from 1.99.1  to 1.99.2(or higher)  to trigger the build.

**Comment by suke18** [comment]
Hi, 

I updated the package version and push it to the upstream. Could you please check? 

![Screen Shot 2021-03-19 at 9 58 10 AM](https://user-images.githubusercontent.com/12088548/111791664-ce73c700-8899-11eb-82ba-8cb017412422.png)

**Comment by Kayla-Morrell** [comment]
@suke18 - When I clone the package from git I am getting version 0.99.1 in the DESCRIPTION file. Please be sure to review this documentation for setting up your package correctly https://bioconductor.org/developers/how-to/git/new-package-workflow/. It looks like you have done steps 1 and 2, but there seems to be some confusion between what's on GitHub and what is on git. These should be synced up.

**Comment by suke18** [comment]
@Kayla-Morrell, I am just wondering whether you see an updated DESCRIPTION file now? The version is 0.99.2 now. Thank you.

**Comment by Kayla-Morrell** [comment]
@suke18 - I just did a `git pull` on `git@git.bioconductor.org:packages/FEAST` and the version is still 0.99.1.

**Comment by vjcitn** [comment]
same here -- i see 0.99.1

**Comment by suke18** [comment]
@Kayla-Morrell Thanks Kayla. I see the error is from the 'doParallel' package. I am trying to use some cores for parallel computing, where I only used 2 cores. I am wondering how to fix this error: 
"Error in .check_ncores(length(names)) : 39 simultaneous processes spawned
Calls: FEAST_fast -> makeCluster -> makePSOCKcluster -> .check_ncores". 

Best,
Kenong

**Comment by suke18** [comment]
I see. Maybe I should use BiocParallel, right?

**Comment by Kayla-Morrell** [comment]
@suke18 - Yes, I was going to suggest looking at BiocParallel to see if it would be able to help solve your issue.

**Comment by suke18** [comment]
@Kayla-Morrell, Hi Kayla, I git push the version to git.bioconductor.org:packages/FEAST. But bioc-issue-bot didn't send a message to me. Could you please check? 


> git push upstream master
Enumerating objects: 45, done.
Counting objects: 100% (37/37), done.
Delta compression using up to 16 threads
Compressing objects: 100% (20/20), done.
Writing objects: 100% (20/20), 2.81 KiB | 2.81 MiB/s, done.
Total 20 (delta 15), reused 0 (delta 0)
To git.bioconductor.org:packages/FEAST
   69d5fdd..1e52d3c  master -> master


Best, 
Kenong

**Comment by lshep** [comment]
The builds were delayed, you should have a new report shortly

**Comment by suke18** [comment]
Hi, I tried many times. This FEAST R package can be installed properly on mac and linux platform however it cannot be built on windows platform. The error message is from the biocparallel package (see below): 

Error: processing vignette 'FEAST.Rmd' failed with diagnostics:
BiocParallel errors
  element index: 1, 2, 3, 4, 5, 6, ...
  first error: object 'k' not found
--- failed re-building 'FEAST.Rmd'

I am not sure why it cannot be run on windows. Do you have any ideas on how to fix this? 

Best,
Kenong

**Comment by vjcitn** [comment]
Please read http://bioconductor.org/packages/release/bioc/vignettes/BiocParallel/inst/doc/Introduction_To_BiocParallel.pdf

You'll have to make the variable k available to workers.  If you develop your code locally using SnowParam, you will know that it will succeed on windows.

**Comment by suke18** [comment]
@Kayla-Morrell Hello Kayla, now the packages are built without errors and warnings. I am wondering what is the next step? Will you evaluate the package? Since the paper is already online, I am wondering when this package can show up on Bioconductor. It will be very helpful for us. 

Best,
Kenong

**Comment by Kayla-Morrell** [comment]
@suke18 - Yes, I will do an initial review of the package. The entire review process can take between 2 to 5 weeks. I have a few packages to review before yours but I will try to get to yours within the next few days.

Best,
Kayla

**Comment by suke18** [comment]
@Kayla-Morrell Thank you. That will be very helpful. 

Best,
Kenong

**Comment by suke18** [comment]
@Kayla-Morrell Hello Kayla, thanks for the revision. I have a question regarding the 1st requirement under the R code section.  I am not sure about "REQUIRED: Clarify how 55 object(s) are initialized. Maybe they are part of
a data set loaded with data(), or perhaps part of an object referenced in
with() or within(). Some of these will be cleared up by fixing the NAMESPACE
requirement above.". Could you explain more about that? Which specific part that I need to change? 

Best,
Kenong

**Comment by suke18** [comment]
@Kayla-Morrell , Hello Kayla, 

I've pushed a successful build incorporating all the comments below and are ready for a re-review. Thank you for your time and consideration. Two things I'd like to note for the re-review:

For the for loop, I found sometimes it is impossible to covert to the apply function because I need to some re-calculation inside the for loop. I am not sure how to store this information if adopting apply. The for loop is very light weighted within 10 runs ususally. 

To clarify the objects initiated, they are from the data("Yan") which contains a "Y" matrix and "trueclass" character vector. I put this information inside the man folder with proper annotations. 

## General package development

- [X] REQUIRED: We do not include 'doc/' directories with our packages. It
  should be added to a .Rbuildignore file and/or a .gitignore file.

## DESCRIPTION

- [X] REQUIRED: There are multiple packages listed under both 'Depends:' and
  'Imports:' (limma, knitr, aricode, assertthat, mclust, SingleCellExperiment,
BiocParallel, and irlba). These packages should only be listed once, either in
depends or imports. Packages that provide *essential* functionality for users of
your package should be listed under 'Depends:'. It is unusual for more than
three packages to be listed there. For packages that provide functions, methods,
or classes that are used inside your package namespace should be listed under
'Imports:'. In most cases, packages are listed here.

- [X] REQUIRED: It seems that 'knitr' is only needed for building vignettes. If
  this is the case it should be listed under 'Suggests:' instead of 'Imports:'.
Packages listed under 'Suggests:' is for packages used in vignettes, examples
and in conditional code.

## NAMESPACE

- [X] REQUIRED: Add to your NAMESPACE file (and ensure that your DESCRIPTION 
Imports field contains 'methods').
        importFrom("methods", "is)
        importFrom("stats", "kmeans", "lm", "median", "model.matrix", "pf",
	"prcomp")
        importFrom("utils", "combn", "setTxtProgressBar", "txtProgressBar")

- [X] REQUIRED: Generally `importFrom()` is encouraged over importing an entire
  packages, however if there are many functions from a single package,
`import()` is okay.

## NEWS

- [X] REQUIRED: It's great that you have included a NEWS file, however please
  update the version to '0.99.0' since this is the starting version for
submitting to Bioconductor.

## Data

- [X] REQUIRED: With any data files included in 'data/' require documentation
  concerning its creation and source information. This documentation is most
often taken care of in a man page. More details are provided in the 'Man pages'
section below.

## Vignette

- [X] REQUIRED: Only the vignette file and any necessary static images should be
  in the vignette directory. There are several .png files that are not used
within the vignette and should be removed.

- [X] REQUIRED: There should be an 'Installation' section that demonstrates to
  the user how to install/load the package from Bioconductor. The code should
look like the following and should include `eval = FALSE`.

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("FEAST")
```

- [X] REQUIRED: Under section 1.3 'Quick start', there should be some context
  text explaining what exactly this code chunk is achieving.

- [X] REQUIRED: If you are using the Deng dataset within your vignette the data
  needs to be part of your package. You should not be having the user download
the data themselves.

- [X] REQUIRED: A vignette provides reproducibility: the vignette produces the
  same results as copying the corresponding commands into an R session. This
means that the vignette needs to embed executable R code, therefore do not
include `eval = FALSE` code chunks within your vignette.

## Man pages

- [X] REQUIRED: Data man pages must include source information and data
  structure information.

- [X] REQUIRED: Add runnable examples to the following man pages which document 
exported objects:
        TSCAN_Clust.Rd
        Visual_Rslt.Rd

- [X] REQUIRED: Usage of dontrun{} / donttest{} found in man page examples.
  donttest{} and dontrun{} are discouraged and generally not allowed, exceptions
can be made with proper justification and are the _Bioconductor_ Reviewers
discretion. If this option is used it will be preferrable to use donttest{} 
instead of dontrun{}; donttest{} requires valid R code while dontrun{} does not.
 http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [X] REQUIRED: Clarify how 55 object(s) are initialized. Maybe they are part of
 a data set loaded with data(), or perhaps part of an object referenced in 
with() or within(). Some of these will be cleared up by fixing the NAMESPACE
requirement above.

- [X] REQUIRED: Avoid sapply(); instead use vapply() if possible.

- [X] REQUIRED: Avoid 1:...; instead use seq_len() or seq_along() if possible.

- [ ] REQUIRED: Use various apply functions over for loops if possible.

Best, 
Kenong

**Comment by suke18** [comment]
Hello Kayla @Kayla-Morrell,

Thanks for your comments. I have a question about " REQUIRED: There is still no man page documenting the data".  In the package, I listed one sample data "Yan.RData" which contains a matrix "Y" and a character vector "trueclass". Both Y and trueclass objects are well documented in the Yan.Rd and trueclass.Rd. I am wondering what "man page" are your referring to. Could you please let me know?

Best,
Kenong

**Comment by Kayla-Morrell** [comment]
@suke18 - I'm sorry for the confusion. I was looking for a Yan.Rd file which would document the data. I do see the trueclass.Rd file but I'm not see the Yan.Rd file, I'm assuming the Y.Rd file is the other man page you are talking about? If this is the case then you can disregard that requirement.

Best,
Kayla

**Comment by suke18** [comment]
@Kayla-Morrell Thanks for your reply and clarification. I will prepare the package soon.

**Comment by suke18** [comment]
@lshep @vjcitn 

Hello Kayla and Vince, 

I've pushed a successful build incorporating all the suggestions and comments. The package is now ready for a re-review. Thank you for your time and consideration. The changes have been made: 

DESCRIPTION

- [ ] REQUIRED: There are still packages listed in more than one of Depends, Imports, or Suggests. A package should be listed in only one of these fields. [**no duplicated names**]

Data/Man pages

- [ ] REQUIRED: There is still no man page documenting the data. [**already existed**]

- [ ] REQUIRED: There needs to be a runnable example for SC3_Clust since it is an exported object [**add example**].

Thanks,
Kenong

**Comment by Kayla-Morrell** [comment]
@suke18 - The above points still need to be addressed. Please see my comments below.

## DESCRIPTION

- [ ] REQUIRED: There are now no duplicated packages among Depends, Imports or Suggests but there are too many packages listed as Depends. There should be no more than 3 packages listed under Depends, the rest should go under Imports.

## Man pages

- [ ] REQUIRED: You have added a runnable example for SC3_Clust, but the function itself is not actually run since you commented out that line. We require all exported functions to be run/tested through runnable code. This can be in man page examples, vignettes, or tests. Since you don't use tests or run the function in the vignette, the code function needs to be run/tested in the man page. This insures that the function actually runs and will alert you/us when the function is broken. Please fix this so that the function is actually run.

Best,
Kayla

**Comment by suke18** [comment]
@Kayla-Morrell, 

For the "SC3_Clust" function, I used some internal code of SC3 Bioconductor (https://bioconductor.org/packages/release/bioc/html/SC3.html). But it showed an error when submitting to the WIndow system because of the parallel computing part embedded in the original SC3 function.  I decided not to import this function. 

Best,
Kenong

**Comment by Kayla-Morrell** [comment]
@suke18 - Great, thank you for making those changes. I'm more than happy to accept the package now.

Best,
Kayla

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/suke18.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("FEAST")`. The package 'landing page' will be created at

https://bioconductor.org/packages/FEAST

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
