### ISSUE TITLE
phosphonormalizer

### ISSUE THREAD

**Issue by sohrab-saraei** [Bioconductor/Contributions#198]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sohrab-saraei/phosphonormalizer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@lshep will review this package. 

Normally Bioconductor packages depend or import other Bioconductor packages, using common data representations to ease interoperability. Please update your code so that the standard 'rich' data structures (SummarizedExperiment?) commonly used in your domain.

The vignette needs to more fully describe the type of data relevant for this package, the structure of the data used for input into the function, and the integration of this package with other packages in the Bioconductor ecosystem.

**Comment by sohrab-saraei** [comment]
@mtmorgan Thank you very much for you comment. Although, I am going to keep this package as simple as possible, just enough for it to meet the bioconductor requirements for the time being. I will consider your suggestion for the next releases.

**Comment by mtmorgan** [comment]
@sohrab-saraei remember that your package has not yet been accepted to Bioconductor, and it will be reviewed by someone with similar expectations to mine.

**Comment by sohrab-saraei** [comment]
@mtmorgan Thank you for your comment. I am aware, that submitting a package to bioconductor could be a lengthy process and the package should be modified so it can integrate into bioconductor. My concern was to avoid extra overhead of dependencies. I used limma, which is used in normalization step in MS-based proteomics workflow frequently, as a gold standard. Functions like _normalizeMedianAbsValues_ or _normalizeVSN_ take a numeric matrix and return the normalized values.This makes limma one of the most practical packages in this realm. Regardless of my personal opinion, I am modifying my package so it support "MSnbase-MSnSet" data representation which is used by other packages in MS-based proteomics domain.

**Comment by mtmorgan** [comment]
@sohrab-saraei that is an appropriate modification, thanks.

**Comment by sohrab-saraei** [comment]
@mtmorgan I modified the package according to your instructions. I also subscribed to the bioc devel but still haven't gotten any confirmation. Waiting for further instructions.

**Comment by lshep** [comment]
You have to bump your version number in the DESCRIPTION file for the changes to take effect and kick off a new build of your package with the changes.  Once you do this I will further review your package for other Bioconductor standards and best practices.  Please note: we are in the process of updating our single package builder so you may receive an "abnormal" message once you bump your version number; as soon as the updates are complete I will rerun your package.

**Comment by sohrab-saraei** [comment]
@lshep Thank you.

**Comment by sohrab-saraei** [comment]
@lshep The errors and warnings. Do I need to work on them or it's the build/check problem?

**Comment by lshep** [comment]
Please ignore the ERROR on oaxaca. I will look into the ERROR on tokay2.  Please fix all other WARNINGS. 
Thank you.

**Comment by sohrab-saraei** [comment]
@lshep Warnings are fixed. Thank you.

**Comment by sohrab-saraei** [comment]
@lshep  Please let me know if I need to make changes. Thank you

**Comment by lshep** [comment]
Thank you for your submission.  A few minor points to address: 

- [ ] You have a lot of apply's utilized in your code. Please ensure that it is not appropriate to vectorize with methods like colSums or colMedian from the matrixStats package.  I'm not sure how large your input parameters can get but vectorization is encourage for its efficiency.  I believe for example the code  `ratios.norm <- as.matrix(apply(ratios, 2, function(x) x - col.sub))`  could just be  `ratios -col.subs`.  Please test to make sure.  
- [ ]  We do strongly encourage packages to include unit tests. Testing if any of the above would speed up your program while maintaining expected results would be also be an excellent example of how it can be worked into the development process of a package. 
- [ ] The texipdf ERROR is on our end and we have decided to allow packages to pass without a clean Windows report until we can get this resolved.  Please be advised that if there are any ERROR/WARNINGS that occur when transitioned over onto the daily build system, we would require immediate attention. 
- [ ] There is still an ERROR that needs to be resolved concerning submission to the bioc-devel mailing list.  This mailing list is important as it is a way for the Bioconductor community to report bugs, misunderstandings, or suggestions to developers.  Subscribe [here](https://stat.ethz.ch/mailman/listinfo/bioc-devel)
- [ ] Lastly please add a section in your vignette that involves downloading the package from bioconductor: 
```
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite("phosphonormalizer")
```

Thank you for your submission.  Please respond back when these issues are corrected or justification for current implementation. I believe once these are addressed your package will be very close to or ready for acceptance.  

Lori

**Comment by sohrab-saraei** [comment]
@lshep All the comments are acted upon. I also have subscribed to the bioc Devel long time ago and many times, but still I get that error.

**Comment by mtmorgan** [comment]
@sohrab-saraei I looked for your user name on the bioc-devel mailing list but could not find it; I looked for subscribers from 'utu.fi' and there were three, none who looked like they might have been you under another name. The two most likely problems are (a) you used a different email address from the one in your package or (b) subscription sends a message requiring confirmation that you are subscribing, and a spam or other filter at your institution meant that you did not receive and reply to it.

**Comment by sohrab-saraei** [comment]
Thank you very much @mtmorgan. The confirmation was in the spam folder for some reason. I accepted it and the error is gone.

**Comment by lshep** [comment]
Thank you. As a reminder: The texipdf ERROR is on our end and we have decided to allow packages to pass without a clean Windows report until we can get this resolved. Please be advised that if there are any ERROR/WARNINGS that occur when transitioned over onto the daily build system, we would require immediate attention.  I will mark your package as accepted.  Please leave the issue open until you have received svn instructions for uploading to Bioconductor. You should receive these svn instructions via email within a few days.  Thank you for your time and effort.

**Comment by sohrab-saraei** [comment]
@lshep Thank you very much. I will carry on as instructed and look forward for any further comments.
