### ISSUE TITLE
Please add package mirTarRnaSeq

### ISSUE THREAD

**Issue by Mercedeh66** [Bioconductor/Contributions#1981]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Mercedeh66/mirTarRnaSeq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by Mercedeh66** [comment]
@vjcitn hi I am getting a build error :

```
trying URL 'https://zenodo.org/record/4615670/files/Mouse_miRanda.txt.gz?download=1'
Content type 'application/octet-stream' length 2932105 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

Warning in readBin(inn, what = raw(0L), size = 1L, n = BFR.SIZE) :
  invalid or incomplete compressed data
Quitting from lines 291-293 (mirTarRnaSeq.Rmd) 
Error: processing vignette 'mirTarRnaSeq.Rmd' failed with diagnostics:
error reading from the connection
--- failed re-building 'mirTarRnaSeq.Rmd'
```

It seems like a windows related error as I am not getting it on my computer, I would appreciate the advice.

Thanks a lot,

-M

**Comment by Mercedeh66** [comment]
@vjcitn Hi, I was able to resolve all warnings and errors except for the error on the windows machine. I am saving a tmp file but while reading it, it seems to be gone. Would you kindly check if this could be an issue with the build machine? Thanks a lot!

**Comment by hpages** [comment]
So I wonder what the `?download=1` part is for in the URLs you use in `getInputSpecies()` e.g.

    https://zenodo.org/record/4615670/files/Mouse_miRanda.txt.gz?download=1

This seems to break the downloaded file on Windows (but surprisingly not on Unix).

For example, doing:

    download.file("https://zenodo.org/record/4615670/files/Mouse_miRanda.txt.gz?download=1", "test.gz")

produces a `test.gz` file with size 2943594 (expected size is 2932105). Then trying to read the file with `data.table::fread()` or `utils::read.table()` fails with an "invalid or incomplete compressed data" error.

If I get rid of `?download=1`, the download seems to work as expected on Windows.

**Comment by Mercedeh66** [comment]
@hpages Great point! Thanks for the guidance :).

**Comment by vjcitn** [comment]
I think we are almost done with this.  There are a couple of issues.

First, your git repo is very large, even though the package tarball is small.  Consider using
the BFG to remove large files from git repo.

Second, BiocCheck has some recommendations
```
 [1] "Consider clarifying how 2 object(s) are initialized. Maybe they are part of a data set loaded with data(), or perhaps part of an object referenced in with() or within()."         
 [2] " Avoid sapply(); use vapply()"                                                                                                                                                     
 [3] " Avoid 1:...; use seq_len() or seq_along()"                                                                                                                                        
 [4] "Avoid '<<-' if possible (found in 1 files)"                                                                                                                                        
 [5] "Recommended function length <= 50 lines."                                                                                                                                          
 [6] "Consider adding runnable examples to the following man pages which document exported objects:"                                                                                     
 [7] "Usage of dontrun{} / donttest{} found in man page examples."                                                                                                                       
 [8] "Consider adding unit tests. We strongly encourage them. See\n  http://bioconductor.org/developers/how-to/unitTesting-guidelines/."                                                 
 [9] "Consider shorter lines; 332 lines (8%) are > 80 characters long."                                                                                                                  
[10] "Consider multiples of 4 spaces for line indents, 627 lines(15%) are not." ```

Third, the graphics could be improved by setting par(mar=c(4,3,3,2)) or something like that,
to avoid all the white space in margins

![Screenshot from 2021-03-25 11-06-46](https://user-images.githubusercontent.com/4624066/112495714-86054f00-8d5a-11eb-85c6-b38d08adaa41.png)

**Comment by Mercedeh66** [comment]
Hi, I made the final changes based on the notes provided by @vjcitn. I also shrunk my repository as requested using BFG but when I try to force push to bioc master I get the following error. I would appreciate the help.

```
# git push --force bioc master
Enumerating objects: 654, done.
Counting objects: 100% (654/654), done.
Delta compression using up to 4 threads
Compressing objects: 100% (220/220), done.
Writing objects: 100% (654/654), 9.58 MiB | 832.00 KiB/s, done.
Total 654 (delta 402), reused 642 (delta 395)
remote: Resolving deltas: 100% (402/402), done.
remote: FATAL: + refs/heads/master packages/mirTarRnaSeq Mercedeh66 DENIED by fallthru
remote: error: hook declined to update refs/heads/master
To git.bioconductor.org:packages/mirTarRnaSeq
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/mirTarRnaSeq'
```

**Comment by vjcitn** [comment]
@nturaga is this an ssh key issue?

**Comment by nturaga** [comment]
Hi @Mercedeh66 

You cannot force push to the Bioconductor git server. This is not allowed with the hook we have in place. 

I will have to assist you in making this change.

**Comment by nturaga** [comment]
> @nturaga is this an ssh key issue?

Hi @vjcitn , this is not an SSH key issue. It is happening because the git repository on our server is out of sync and has diverged from the github repo.

**Comment by Mercedeh66** [comment]
@nturaga Thanks so much. Please let me know if you need anything from my side.

**Comment by nturaga** [comment]
@vjcitn This might be an issue on our end, or how we are processing packages. I'm investigating and will let you know.

**Comment by nturaga** [comment]
@Mercedeh66 Please try now and see? 

I would suggest you `git fetch --all` again if it doesn't work. Or maybe just obliterate your local directory and try to clone and setup your git repo locally again.

**Comment by Mercedeh66** [comment]
@nturaga Thanks for the help. It seems to work now.
@vjcitn I tried to address most of the notes, hope it is good enough and thanks for the suggestions.

**Comment by vjcitn** [comment]
Looks good.  Accepting.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Mercedeh66.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("mirTarRnaSeq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mirTarRnaSeq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
