### ISSUE TITLE
methylXprs

### ISSUE THREAD

**Issue by iloveless1** [Bioconductor/Contributions#1995]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/iloveless1/EpiXprS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by vjcitn** [comment]
you were able to clone from git.bioconductor.org and see this for git remote -v?
```
origin	git@git.bioconductor.org:packages/methylXprs (fetch)
origin	git@git.bioconductor.org:packages/methylXprs (push)
```
https://www.bioconductor.org/developers/how-to/git/faq/  -- check item 14 here?

**Comment by iloveless1** [comment]
Thank you for your response. I have checked 14 from the FAQ and get the following. 

$ git remote -v
origin  https://github.com/iloveless1/methylXprs.git (fetch)
origin  https://github.com/iloveless1/methylXprs.git (push)
upstream        git@git.bioconductor.org:packages/methylXprs.git (fetch)
upstream        git@git.bioconductor.org:packages/methylXprs.git (push)

$ ssh -T git@git.bioconductor.org
kex_exchange_identification: read: Connection reset by peer
Connection reset by 34.192.48.227 port 22

**Comment by vjcitn** [comment]
@nturaga ^^    iloveless have you put the proper key at BiocCredentials app?

**Comment by nturaga** [comment]
Hmm...i'm not sure what's happening here, especially because everything seems to be working on our end.

Can you do a `ssh -T git@git.bicoonductor.org -vv` and see if the correct keys are being used in the verbose output?

**Comment by iloveless1** [comment]
I am no expert in git, so I am trying to Google as I go, but I haven't been able to resolve this one. Thank you both for your help with this. When I try the above command, I get:

$ ssh -T git@git.bicoonductor.org -vv
OpenSSH_8.4p1, OpenSSL 1.1.1i  8 Dec 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "git.bicoonductor.org" port 22
ssh: Could not resolve hostname git.bicoonductor.org: Name or service not known

**Comment by vjcitn** [comment]
We'll get there.  If you have registered the right key with BiocCredentials this should be solvable easily but let's wait
for Nitesh @nturaga to have a look.  I am reviewing the package and I can work with it in its current form.

**Comment by nturaga** [comment]
Well, for starters it seems there is a typo in the command written by @iloveless1

`bicoonductor` vs `bioconductor`.

Try

``` ssh -T ***@***.******@***.***> -vv```

From: Vince Carey ***@***.***>
Reply-To: Bioconductor/Contributions ***@***.***>
Date: Tuesday, March 30, 2021 at 10:33 AM
To: Bioconductor/Contributions ***@***.***>
Cc: Nitesh Turaga ***@***.***>, Mention ***@***.***>
Subject: Re: [Bioconductor/Contributions] methylXprs (#1995)


We'll get there. If you have registered the right key with BiocCredentials this should be solvable easily but let's wait
for Nitesh @nturaga<https://github.com/nturaga> to have a look. I am reviewing the package and I can work with it in its current form.

**Comment by iloveless1** [comment]
Oh, how embarrasing. When I run the command correctly, I get the following. I am not sure how to tell from this if the correct keys are being used. 

$ ssh -T git@git.bioconductor.org -vv
OpenSSH_8.4p1, OpenSSL 1.1.1i  8 Dec 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "git.bioconductor.org" port 22
debug2: ssh_connect_direct
debug1: Connecting to git.bioconductor.org [34.192.48.227] port 22.
debug1: Connection established.
debug1: identity file /c/Users/ilovele1/.ssh/id_rsa type 0
debug1: identity file /c/Users/ilovele1/.ssh/id_rsa-cert type -1
debug1: identity file /c/Users/ilovele1/.ssh/id_dsa type -1
debug1: identity file /c/Users/ilovele1/.ssh/id_dsa-cert type -1
debug1: identity file /c/Users/ilovele1/.ssh/id_ecdsa type -1
debug1: identity file /c/Users/ilovele1/.ssh/id_ecdsa-cert type -1
debug1: identity file /c/Users/ilovele1/.ssh/id_ecdsa_sk type -1
debug1: identity file /c/Users/ilovele1/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /c/Users/ilovele1/.ssh/id_ed25519 type 3
debug1: identity file /c/Users/ilovele1/.ssh/id_ed25519-cert type -1
debug1: identity file /c/Users/ilovele1/.ssh/id_ed25519_sk type -1
debug1: identity file /c/Users/ilovele1/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /c/Users/ilovele1/.ssh/id_xmss type -1
debug1: identity file /c/Users/ilovele1/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.4
kex_exchange_identification: read: Connection reset by peer
Connection reset by 34.192.48.227 port 22

**Comment by nturaga** [comment]
Hi,

Another thing you could try is in this help page, it might be that you have a `/etc/hosts.deny` file you are unaware of or something of the likes – “https://phoenixnap.com/kb/fix-connection-reset-by-peer-ssh-error”

**Comment by iloveless1** [comment]
@nturaga and @vjcitn I am not sure what was happening on my PC. I switched to our cluster and was able to push without issue. Thank you both for your help.

**Comment by vjcitn** [comment]
I apologize for the delay in reviewing this package.  One basic concern is the choice of data structure.  I do not see any usage of BIoconductor classes such as SummarizedExperiment.  Have you considered this?  I think it will help, and there are various other issues that should be addressed.  Here's the first:  In the vignette, we see

![Screenshot from 2021-04-16 09-26-56](https://user-images.githubusercontent.com/4624066/115032284-23a1f900-9e97-11eb-839f-2e5ec0c20378.png)

Notice the quotation marks around long numeric data.  This is poor form.  

?BRCA_RNA_Test gives hundreds of uninformative lines.  Please use roxygen properly, with @docType data

To produce a SummarizedExperiment the following would work

```
library(methylXprs)
data("BRCA_Methy_Test", package = "methylXprs")
data("BRCA_Clinical_Test", package = "methylXprs")
data("BRCA_RNA_Test", package = "methylXprs")
library(SummarizedExperiment)
dem = SummarizedExperiment(BRCA_Methy_Test)
colData(dem) = DataFrame(BRCA_Clinical_Test)
dem$tspan6 = as.numeric(BRCA_RNA_Test)  # check
```

Now we have

```
> dem
class: SummarizedExperiment 
dim: 258 468 
metadata(0):
assays(1): ''
rownames(258): cg00029931 cg00040923 ... cg27450971 cg27540791
rowData names(0):
colnames(468): TCGA-YL-A8SI-01A TCGA-V1-A8WW-01A ... TCGA-KK-A8I6-01A
  TCGA-EJ-A65J-01A
colData names(3): age race tspan6
```
we should give a name to the 'assays' element.

Your functions can then operate on this structure, and many software tools in other packages will
be able to work with your structure.

?model_search does not provide clear information as to what is happening.

```
> model_search('cg21837192', Cancer = 'PRAD')
              CpG site Effect on Expression Ensembl Gene ID Chromosome      TSS
56          cg21837192   0.0279619582776842 ENSG00000123388         12 53973126
57          cg21837192   0.0180866096458406 ENSG00000161642         12 54369133
27          cg21837192  0.00300619887556913 ENSG00000172789         12 54032853
37     cg21837192:Race  0.00954630744546145 ENSG00000172789         12 54032853
48     cg21837192:Race  0.00314414224851153 ENSG00000197111         12 53452102
45          cg21837192  0.00571710161144973 ENSG00000197757         12 53990624
31          cg21837192  0.00553483289958806 ENSG00000260597         12 54019910
372823      cg21837192   0.0147345879208595 ENSG00000273046         12 54017110
            TES HGNC Symbol
56     53977643      HOXC11
57     54391298     ZNF385A
27     54035358       HOXC5
37     54035358       HOXC5
48     53481162       PCBP2
45     54030823       HOXC6
31     54022589  AC012531.1
372823 54035361  AC012531.2
```
What is "Effect on Expression" here?  An estimate of FDR?  The man page should explain.

I don't think code should download data from github.
```
   else if (Cancer == "UCEC") {
        load(url("https://github.com/iloveless1/methylXprs-Data/raw/main/UCEC.rda"))
        rt = UCEC
    }
```
Please have a look at the ExperimentHub package vignette and consider contributing these data
structures as ExperimentHub components.

From Interact, 
```
        mat <- as.matrix(cbind(x[, seq(ncol(x) - clin.col)], 
            x[, seq(ncol(x) - clin.col)] * x[, (ncol(x))], x[, 
                (ncol(x) - (clin.col - 1)):ncol(x)]))
        colnames(mat)[(ncol(x) - (clin.col - 1)):(ncol(x) * 2 - 
            (2 * clin.col))] <- paste0(colnames(mat)[(ncol(x) - 
            (clin.col - 1)):(ncol(x) * 2 - (2 * clin.col))], 
            paste0(":", colnames(x)[ncol(x)]))
        colnames(mat)[c((ncol(mat) - (clin.col - 1)):ncol(mat))] <- colnames(x)[c((ncol(x) - 
            (clin.col - 1)):ncol(x))]
```
will be very hard to maintain.  We also see 
```
            xtrain <- mat[!tmp %in% i, ]
            xtest <- mat[tmp %in% i, ]
            ytrain <- y[!tmp %in% i]
            ytest <- y[tmp %in% i]
```
so `tmp %in% i` is being recomputed repeatedly.  Have a look at the code and see if there are
repetitious patterns you could identify to remove.

There are no unit tests.

**Comment by vjcitn** [comment]
Please run BiocCheck::BiocCheck() in your source folder and attend to the errors and warnings.  Thank you

**Comment by iloveless1** [comment]
Thank you for your feedback. I will work on these issues and push an update.

**Comment by iloveless1** [comment]
@vjcitn For contributing the data structures referenced above as ExperimentHub components, I saw that it is recommended to push standalone data packages before the packages that depend on them. Since I have already pushed this package, should I add the data package on here as an AdditionalPackage or push it by itself and link this one to it?

**Comment by vjcitn** [comment]
@Kayla-Morrell will comment on this

**Comment by Kayla-Morrell** [comment]
@iloveless1 - You have a couple options. The first is to submit an AdditionalPackage here which is the most common case. The other option, which is a newer implementation for us, is to have your software package have a file in ExperimentHub which would eliminate the need for an additional package. For this option you would need to include the required metadata.csv file in the inst/extdata directory (which would normally be in an ExperimentHub package) and you would have to include the 'ExperimentHubSoftware' biocViews in the DESCRIPTION file. Let me know if you have any further questions or need clarification.

Best,
Kayla

**Comment by iloveless1** [comment]
@Kayla-Morrell - Thank you for your reply. I have a question about the data I am submitting. Essentially, there are 46 models utilizing DNA methylation to predict gene expression for a variety of cancers from TCGA, with and without inclusion of race/ethnicity. Each cancer type has models ranging from ~15,000 genes to ~25,000 genes. Would it be better to organize all of the models into separate data structures for uploading or a large object that allows end users to call on the cancer/race-ethnicity model they want? As distinct files, it currently takes up ~521 MB, but I have gene-wise annotations that could possibly be removed or combined depending on the ultimate data structure. 

Thanks,
Ian

**Comment by vjcitn** [comment]
checking in here.  @iloveless1 do you want to get this package into 3.13?

**Comment by iloveless1** [comment]
I am not sure if it will be done in time. I had our Sys admin start the transfer process for the AnnotationHub data yesterday, then assuming that is in the correct format, I will need to update the functions accordingly. When would I need to have everything finalized to be included in 3.13?

**Comment by vjcitn** [comment]
Deadline is tomorrow.  I will check tomorrow evening to see where we are.

**Comment by lshep** [comment]
We are trying to do the prechecks for EpiXprSData and it appears the version number is not what Bioconductor expects.  Could you please bump the version from 0.1.0 to Bioconductors standard of 0.99.0.  Thank you.  When this is complete please let us know and we will try the prechecks again.

**Comment by iloveless1** [comment]
Hi, I have updated the version from 0.1.0 to 0.99.0 on the EpiXprSData repository.

**Comment by vjcitn** [comment]
I tried to finish the review today and ran into:
```
> ### Name: methyl_Predict
> ### Title: This function predicts mRNA expression
> ### Aliases: methyl_Predict
> 
> ### ** Examples
> 
> data(BRCA_Methy_Test)
> data(BRCA_Clinical_Test)
> colnames(BRCA_Clinical_Test) <- c('age','race_list')
> BRCA_Clinical_Test <- as.data.frame(BRCA_Clinical_Test)
> methyl_Predict(Cancer = 'BRCA', Methy = BRCA_Methy_Test, clinical = BRCA_Clinical_Test,
+ impute = FALSE, beta = FALSE)
Warning in load(url("https://github.com/iloveless1/methylXprs-Data/raw/main/BRCA.rda")) :
  cannot open URL 'https://github.com/iloveless1/methylXprs-Data/raw/main/BRCA.rda': HTTP status was '404 Not Found'
Error in load(url("https://github.com/iloveless1/methylXprs-Data/raw/main/BRCA.rda")) : 
  cannot open the connection to 'https://github.com/iloveless1/methylXprs-Data/raw/main/BRCA.rda'
Calls: methyl_Predict -> load
Execution halted
```
Why are data being pulled from github?  Is this an aspect of the ExperimentHub contribution?

**Comment by lshep** [comment]
The ExperimentHub would not be pulling for github.  Please update any calls to the data to download from the ExperimentHub data you uploaded in the data package.

**Comment by iloveless1** [comment]
Hi, I am finalizing calling TCGA-BRCA methylation and RNA from another package for the vignette. I will push my updated package after I have completed that.

**Comment by vjcitn** [comment]
I am still seeing https://github.com/iloveless1/methylXprs-Data/raw/main/PRAD.rda in source.  Just checking in.

**Comment by iloveless1** [comment]
@vjcitn  I have updated my functions to incorporate more Bioconductor data structures, which in turn has affected downstream functionality. I am working on that. I have updated the repository name above and I will push the changes I have made shortly, while I finish up everything else.

**Comment by vjcitn** [comment]
ok, just checking in

**Comment by vjcitn** [comment]
As far as I can tell, code still uses github.

**Comment by iloveless1** [comment]
Let me try and push again, I changed it so it takes the ExperimentHub object and thought that I had successfully pushed updated functions, while I finish the Vignette.

**Comment by vjcitn** [comment]
are you changing the name of the submitted package?

**Comment by iloveless1** [comment]
Yes, I am changing the name of the submitted package to 'EpiXprS'

**Comment by vjcitn** [comment]
please close this issue and resubmit the new package from scratch. thanks

**Comment by lshep** [comment]
It doesn't appear that the new package was ever submitted for formal review and inclusion into Bioconductor.  Please note that the resources that are included in ExperimentHub for EpiXprSData require an associated package be submitted and accepted.  If a package is not submitted by next release, we will remove the entries from the ExperimentHub and delete the files from our hosting server.
