### ISSUE TITLE
ReactomeGraph4R

### ISSUE THREAD

**Issue by chilampoon** [Bioconductor/Contributions#1996]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/reactome/ReactomeGraph4R

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by lshep** [comment]
The neo4r package is only available on CRAN for 0.1.1.  0.1.3  is not available.  https://cran.r-project.org/web/packages/neo4r/index.html .  Bioconductor only uses packages available on CRAN / Bioconductor .  Either remove the version requirement or you will not be able to proceed until the newer version of the package is available on CRAN.

**Comment by chilampoon** [comment]
@vjcitn this package needs to connect to a local database first (described here: https://github.com/reactome/ReactomeGraph4R). How can I pass the checks on bioconducotr builders?

**Comment by vjcitn** [comment]
Thank you for this interesting package.  The infrastructure required on your README is significant and
I would suggest using "mocks" to allow your package into the ecosystem.  I don't think we will install neo4j
on our build systems.  But you can have some intermediate objects of modest size that behave like the
graph database records and can be used to test your R code.  I will check with others about the requirements
but I think your best bet is not to require the neo4j deployment.  We are managing 1900 packages and yours
is the first with this requirement.  @hpages ?

**Comment by chilampoon** [comment]
@vjcitn Thanks for your response! Is something like [this](https://github.com/neo4j-rstats/neo4r/blob/master/data-raw/create.cypher) what you mean by "mocks"?

**Comment by vjcitn** [comment]
It seems relevant.  Do you have functions to ingest that text into R and perform graph
operations on it, perhaps with igraph?

**Comment by chilampoon** [comment]
I only have functions to ingest json data returned from neo4j. One way to pass the check is to `\dontrun` all exported query functions... I think that's also what neo4r did. And maybe to store some R objects then test other processing functions?

**Comment by vjcitn** [comment]
Let's not rush into this.  I will spend some time with your package and get back to you.

**Comment by vjcitn** [comment]
I ran through your vignette.  It was easy to do this.  It required 4.7GB for the neo4j data, i guess.  Is that something
you will be updating on a regular basis?  Users must acquire the neo4j infrastructure and connect to it.   It seems much
heavier than anything we have done with reactome or perhaps any other package so far.  We have had a static reactome.db
package for a long time, that gets updated each release.  I see on the reactome github that there is a REST API.  It seems to me that that could be a simple way of providing reactome data to Bioc users.  Can you expose a neo4j instance to of reactome to the web?

**Comment by vjcitn** [comment]
The ReactomeGSA package uses gsa.reactome.org ... so the REST API is being used.  We will discuss what would be involved with introducing this to the build system.

In trying out an example, I found it interesting that you manage the connection as a global option
```
> options()$con
<neo4j connection object>
Connected at http://localhost:7474 
User: neo4j 
Neo4j version: 3.5.19 
> 
```
That's not a good practice.  IMHO the connection object should have local state and be passed explicitly when needed.

What I meant by "mock" is somewhat vague, but let's take 
```
"MATCH p1 = (disease:Disease)<-[:disease]-(dbo:DatabaseObject) WHERE disease.displayName = \"asthma\" RETURN disease,dbo,relationships(p1)"
```
You are creating that in R, are you validating it in R before passing it to neo4j?  If so testing that validation
step would be relevant, and presumably you don't need neo4j running to validate it.  You won't know whether
the disease token is valid so you can't test that without neo4j.  But that string is an example of a mock datum
that is usable for testing package functionality without contacting the server.  Another example would be to
save some of the tables you generate, and carry out the visualizations proposed in the vignette.

I'll get back to you on the idea of hosting the package in the Bioc build system.

**Comment by chilampoon** [comment]
gsa.reactome.org is the Analysis Service API which is different from the data query API (Content Service, https://reactome.org/ContentService/). There's also a wrapper for the ContentService API and it has been submitted (https://github.com/reactome/ReactomeContentService4R)... 
 Data retrieved from the Graph Database are mostly with hierarchical/network structure and contain the node and relationship information, these are what you cannot get from the data from the REST API or that reactome.db (I am not so sure but this package looks like a hub for annotation files)

**Comment by vjcitn** [comment]
Have you considered placing a small slice of reactome in neo4j aura -- you might pay something per month -- for the sake of testing and demonstration?  The bioc package code could use that small instance to do its testing.  Then interested users could follow the instructions to get the full deployment, which is quite convenient for docker users.

**Comment by chilampoon** [comment]
Neo4j aura seems convenient but ummm I have to ask the Reactome team
> Have you considered placing a small slice of reactome in neo4j aura -- you might pay something per month -- for the sake of testing and demonstration? The bioc package code could use that small instance to do its testing. Then interested users could follow the instructions to get the full deployment, which is quite convenient for docker users.

**Comment by chilampoon** [comment]
@vjcitn I think we can just use mocks, and I'll think about what stuff to be tested. 
I actually called the `con` in my query and error checking functions, I am not sure how to store it only in the package environment, do you have any suggestions?

> ```
> > options()$con
> <neo4j connection object>
> Connected at http://localhost:7474 
> User: neo4j 
> Neo4j version: 3.5.19 
> > 
> ```
> 
> That's not a good practice. IMHO the connection object should have local state and be passed explicitly when needed.

**Comment by vjcitn** [comment]
You don't have to store it in the package environment.  You have a constructor that produces an object
that holds the connection.  You could look at bigrquery for an example
```> ?bigquery
>    if (bq_testable()) {
+      con <- DBI::dbConnect(
+        bigquery(),
+        project = "publicdata",
+        dataset = "samples",
+        billing = bq_test_project()
+      )
+      con
+      DBI::dbListTables(con)
+ }
[1] "github_nested"   "github_timeline" "gsod"            "natality"       
[5] "shakespeare"     "trigrams"        "wikipedia"      
```

**Comment by chilampoon** [comment]
Did your example mean generating the object each time I need it?
A reason why I used `option()` is, most of the time `con` is not necessary for users, so I wanted to "hide" it

**Comment by vjcitn** [comment]
It would be generated when needed and discarded when no longer needed.   Go ahead with your
redesign using mock data and we will discuss further later on.  The options() list should not be a place
to hide stuff, but we can reevaluate later.

**Comment by chilampoon** [comment]
Oh there's confusion here, the connection object _has to_ be there for interacting with the database when using this package, so it cannot be discarded all the time. But users don't have to directly get the information using it.

**Comment by vjcitn** [comment]
Just checking in.  Still working on the submission?

**Comment by chilampoon** [comment]
> Just checking in. Still working on the submission?

Yes I'll update the package by next week, sorry for the dalay

**Comment by chilampoon** [comment]
@vjcitn a brief summary:

- Since it's unable to connect to the graph database on the builders, I `dontrun` the examples for all exported functions... and put most of them into a [script](https://github.com/reactome/ReactomeGraph4R/blob/master/tests/manual.query.test/query.tests.R) of manual tests
- I added a [test](https://github.com/reactome/ReactomeGraph4R/commit/045a08789844e5287ae3148f983770490315e478) for constructing a cypher query, just like your mock example, still some functions need a connection
- Saved the [data](https://github.com/reactome/ReactomeGraph4R/tree/master/vignettes/data) for building the vignette so that no need to directly retrieve them from the database

**Comment by chilampoon** [comment]
hi @vjcitn would you review this package? the deadline is coming... thanks

**Comment by chilampoon** [comment]
Hi @lshep, just wonder if the new package review is still ongoing? The deadline is May 13th right? Thanks.

**Comment by lshep** [comment]
Yes.  Package review process is still going on. Please be patient as reviewers are assigned multiple issue and review in additional to other release tasks. You should have a review shortly.

**Comment by chilampoon** [comment]
@vjcitn 
license: `Apache License (>= 2.0) | file LICENSE`, `Apache License (>= 2.0)`, `file LICENSE` are all unknown... how should I specify it?

`donttest{}` would run into an R CMD Check error, so I kept `dontrun`

**Comment by chilampoon** [comment]
There is always a note for the license... @vjcitn what else could be improved? Thanks.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/chilampoon.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ReactomeGraph4R")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ReactomeGraph4R

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
