### ISSUE TITLE
scone

### ISSUE THREAD

**Issue by mbcole** [Bioconductor/Contributions#200]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YosefLab/scone

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
The "abnormal" is an error on our end from updating the single package builder.  Once the update is complete I will manually kick off a build of your package

**Comment by lshep** [comment]
Sorry. The abnormal is still on our end we are working to remedy this asap. I will kick off a new build for you shortly.

**Comment by drisso** [comment]
Thank you @lshep! And hopefully we fixed the errors on our side this time! :)

**Comment by nturaga** [comment]
Hi,

Please check these following `WARNINGS` as well. (use R-devel)

```
* Checking R Version dependency...
     * WARNING: Update R version dependency from 3.3 to 3.4.
```

You can also easily resolve these `NOTE` , if these tags are relevant to your package, users can easily find them using these tags. We encourage having a clean build.

* (Easy to resolve)
```
* Checking for recommended biocViews...
    * NOTE: Consider adding these automatically suggested biocViews:
      Sequencing, SingleCell, Coverage
```

*
```
* Checking exported objects have runnable examples...
    * NOTE: Consider adding runnable examples to the following man
      pages which document exported objects:
      lm_adjust.Rd, make_design.Rd, scone_easybake.Rd, score_matrix.Rd,
  SCRAN_FN.Rd
```

*  (Easy to resolve)
```
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * NOTE: Consider shorter lines; 546 lines (8%) are > 80 characters
      long.
```

*  (Easy to resolve)
```
    First 6 lines:
      man/biplot_color.Rd:5 \title{Function for biplotting with no point labe...
      man/biplot_color.Rd:15 If rank is FALSE, all values must be positive in...
      man/biplot_color.Rd:17 \item{rank}{logical. If TRUE (default) y will be...
      man/biplot_color.Rd:21 \item{choices}{numeric. 2 principal components t...
      man/biplot_interactive.Rd:30 res <- scone(obj, scaling=list(none=identi...
      man/biplot_interactive.Rd:31 evaluate=TRUE, k_ruv=0, k_qc=0, eval_kclus...
    * NOTE: Consider multiples of 4 spaces for line indents, 1722 lines
      (26%) are not.
```

**Comment by drisso** [comment]
Thanks for your comments, @nturaga.

We only have one question re: the R version. Is it required to depend on R 3.4? What is the rationale behind it?

We have tested the package both with the devel and the release version of Bioconductor, and it seems to work in both versions. 

One reason I'm hesitant to change the R version is that our package currently lives as a Github repository, and although we don't have a huge number of users, they will be affected by this change (if they install the package from master). 

We will address all the NOTES.

**Comment by nturaga** [comment]
Hi @drisso 

We expect packages to be developed using the **devel** branch of both `Biocondcutor(3.5)` and `R (3.4.*)` . These packages once approved will be available in the **devel** branch. After the next release (Spring 2017) the package will appear in both **release** and **devel** branches. 

Someone using the **current** **release**, `R 3.3.*`, will have `BiocInstaller 1.24.*` . That version of `BiocInstaller::biocLite()` will never 'find' their package because it will not be in the branch for `Bioconductor 3.4 / R 3.3.*`. 

But users can get the package from your github repository and use it with `R 3.3.*`. I believe that your current set of users are getting it from github, and this change should not be an issue?

**Comment by nturaga** [comment]
Hi, @drisso you have an ERROR now in the build. And you seem to have it covered though, (https://github.com/epurdom/clusterExperiment/issues/141).

**Comment by drisso** [comment]
Thanks @nturaga for pointing that out! There was a small typo in the vignette that was causing the builder not to create it.

We get a different error now:
```
Error: processing vignette 'sconeTutorial.Rmd' failed with diagnostics:
unused arguments (self_contained, lib_dir, output_dir)
Execution halted
```
which I don't get if I revert back to R 3.3. Could it be due to some changes in R CMD build between R 3.3 to 3.4?

**Comment by drisso** [comment]
OK, I actually found out that the problem is related to an issue with BiocStyle, that was just fixed:
https://stat.ethz.ch/pipermail/bioc-devel/2016-November/010157.html

I think this error should go away once the changes to BiocStyle make it through the build?
@vobencha is that correct?

**Comment by vobencha** [comment]
Yes, it should resolve itself. Nitesh and I will do a full review early next week and get you more content-based comments.

Is that a blueberry scone avatar? Fantastic.

**Comment by drisso** [comment]
> Is that a blueberry scone avatar?

It is indeed! :)

**Comment by nturaga** [comment]
Hi, quick comment before I give more detailed feedback. You should remove any `pdf`/`html` files from the vignettes. These are not needed as the package builder will run the `Rmd` file to generate the html.

**Comment by nturaga** [comment]
Hi @drisso,

I went through your package. Most of it seems to follow our package
guidelines pretty well. A few suggestions i'd like to make are:


**1. Check DESCRIPTION / NAMESPACE consistency** (`SconeExperiment` vs `sconeExperiment`, not sure why they are named like that, it can lead to confusion)

**2. getters / setters (helper.R)**

Once these are defined they should be used throughout the code; Example: you define them, but don't use them in `setValidity("SconeExperiment")` and other places as well.

**3. Hard to find all the getters / setters for the class:**

Reason: They are on separate man pages; each man page should have a running example - this is easier to do when all are listed on the class man page; Alternative is to add \seealso and reference small man pages with getters/setters.

**4. Constructor has different name from class** (not required, we suggest same name, refers back to issue#1) 

Class constructors often have the same name of the class they make, e.g.,
`SummarizedExperiment()` makes a `SummarizedExperiment object`
`GRanges()` makes a `GRanges object` etc.

**Comment by drisso** [comment]
Hi @nturaga,
thanks a lot for the review and the comments! I think they all make a lot of sense!

We will address them and submit a revised version.

**Comment by nturaga** [comment]
Hi @drisso 

@mtmorgan will follow up with you with how to add to the devel branch. That will take about a week. please keep the issue open.
