### ISSUE TITLE
GISPA

### ISSUE THREAD

**Issue by BhaktiDwivedi** [Bioconductor/Contributions#202]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BhaktiDwivedi/GISPA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@LiNk-NY will review this package, but it's surprising that it does not present the user with an interface that builds on standard Bioconductor packages, especially ExprssionSet or SummarizedExperiment to represent expression data, and classes from GSEABase for representing and working with gene sets. The package should be modified before review to incorporate these classes as a way to foster interoperability with existing Bioconductor packages.

**Comment by BhaktiDwivedi** [comment]
Hi

I have made the changes and fixed the build results.


Thank you.


Regards,

Bhakti

________________________________

**Comment by lawremi** [comment]
Sorry, but it's not evident how you resolved the lack of integration with Bioconductor. It's still entirely based on data.frame-like objects and exports questionable utilities like `sortData()`. One could use `plyr::arrange()` for that, or S4Vectors (0.13.3) `sort(x, by=~variable)`, where `x` is a DataFrame or any other tabular data structure.

**Comment by BhaktiDwivedi** [comment]
Hi Michael,

Thank you for your comments. If I understand correctly, I should modify the code to include the use of existing bio-conductor packages and classes where-ever applies such as sortData? or is it has to be all data.matrix objects as well? Is their a way I can obtain a list of functions or issues in the code that are problematic. similar to issues report. Thank you

**Comment by lawremi** [comment]
The task is a combination of porting the key contributions of your package to operate on and return Bioconductor objects, and to drop functions like `sortData()` which are redundant with existing R/Bioconductor infrastructure. I also noticed `readDATA()` just munges some data without actually reading anything.

**Comment by BhaktiDwivedi** [comment]
Thank you so much Michael. Let me work on it and I will submit the version with changes. I apologize as the revisions requested were obvious and I didn't understand.

**Comment by BhaktiDwivedi** [comment]
I am getting the below ERROR Bioconductor build msg on Mac OS X 

* installing the package to build vignettes
      -----------------------------------
ERROR: dependency HH is not available for package GISPA
* removing /private/var/folders/_l/1jpyvgt17qzgj1yz7f0z4np80000gr/T/Rtmp939MXS/Rinst16ad7608b810a/GISPA
      -----------------------------------
ERROR: package installation failed


I do not get this ERROR messages when I build on my Mac OS X using
R CMD build GISPA
R CMD check GISPA
R CMD check GISPA_0.99.5.tar.gz
R CMD BiocCheck GISPA.Rcheck/00_pkg_src/GISPA

Appreciate your help in suggesting ways to fix this error.

Thank you.

**Comment by BhaktiDwivedi** [comment]
Additionally, I am getting the below warning message:

WARNING: Update R version dependency from 3.3.2 to 3.4.

will changing the DESCRIPTION file from "Depends: R (>= 3.2.2)" to "Depends: R (>= 3.4)" work?

Thank you.

Regards,
Bhakti

**Comment by BhaktiDwivedi** [comment]
Hi Marcel,

Could you please help me with the below two build error and warnings?

I am getting the below ERROR Bioconductor build msg on Mac OS X

•installing the package to build vignettes
ERROR: dependency HH is not available for package GISPA

•removing /private/var/folders/_l/1jpyvgt17qzgj1yz7f0z4np80000gr/T/Rtmp939MXS/Rinst16ad7608b810a/GISPA
ERROR: package installation failed

I do not get this ERROR messages when I build on my Mac OS X using
 R CMD build GISPA
 R CMD check GISPA
 R CMD check GISPA_0.99.5.tar.gz
 R CMD BiocCheck GISPA.Rcheck/00_pkg_src/GISPA

Additionally, I am getting the below warning message:

WARNING: Update R version dependency from 3.3.2 to 3.4.

Appreciate your help and suggestions to fix them.

Thank you.

Regards,
Bhakti

**Comment by BhaktiDwivedi** [comment]
Hi Marcel @LiNk-NY 

Could you please help me with the below two build error and warnings?

I am getting the below ERROR Bioconductor build msg on Mac OS X

•installing the package to build vignettes
 ERROR: dependency HH is not available for package GISPA

•removing /private/var/folders/_l/1jpyvgt17qzgj1yz7f0z4np80000gr/T/Rtmp939MXS/Rinst16ad7608b810a/GISPA
 ERROR: package installation failed

I do not get this ERROR messages when I build on my Mac OS X using
 R CMD build GISPA
 R CMD check GISPA
 R CMD check GISPA_0.99.5.tar.gz
 R CMD BiocCheck GISPA.Rcheck/00_pkg_src/GISPA

Additionally, I am getting the below warning message:

WARNING: Update R version dependency from 3.3.2 to 3.4.

Appreciate your help and suggestions to fix them.

Thank you.

Regards,
 Bhakti

**Comment by BhaktiDwivedi** [comment]
@bioc-issue-bot 

Could anyone please help me with the below two bioconductor build error and warnings?

I am getting the below ERROR Bioconductor build msg on Mac OS X

•installing the package to build vignettes
ERROR: dependency HH is not available for package GISPA

•removing /private/var/folders/_l/1jpyvgt17qzgj1yz7f0z4np80000gr/T/Rtmp939MXS/Rinst16ad7608b810a/GISPA
ERROR: package installation failed

I do not get this ERROR messages when I build on my Mac OS X using
R CMD build GISPA
R CMD check GISPA
R CMD check GISPA_0.99.5.tar.gz
R CMD BiocCheck GISPA.Rcheck/00_pkg_src/GISPA

Additionally, I am getting the below warning message:

WARNING: Update R version dependency from 3.3.2 to 3.4.

Appreciate your help and any suggestions to fix them.

Thank you.

**Comment by BhaktiDwivedi** [comment]
Hi @bioc-issue-bot @mtmorgan @lawremi @LiNk-NY 

Based on my recent correspondence on bioc-devel@r-project.org, I was suggested to ignore the HH dependency/installation error on oaxaca. Also was referred to this recent post (https://stat.ethz.ch/pipermail/bioc-devel/2016-October/009997.html).

I have tried to make the changes. Please see the updated version. I greatly appreciate all your help with the review, suggestions, and comments. 

Thank you

**Comment by LiNk-NY** [comment]
Hi @BhaktiDwivedi, 
My apologies for the delay. I will get to your package today. 
Best regards,
Marcel

**Comment by BhaktiDwivedi** [comment]
Thank you so much Marcel! Appreciate a lot!

Regards,
Bhakti

**Comment by LiNk-NY** [comment]
HI @BhaktiDwivedi, 
Thank you for submitting to Bioconductor. 
Below you will find feedback on your package `GISPA`. 

Let me know if you have any questions. 
Regards,
Marcel 

---

### GISPA

#### Package & Vignette
* The package currently does not leverage any pre-existing Bioconductor classes. Please see comments from Martin Morgan and Michael Lawrence above. 
* Don't use a `vignette.Rds`. This will prevent a command like `R CMD build --no-build-vignettes` from running because it checks against what is listed in the data. Please just provide a vignette with run-able code.

#### Organization 
* Please organize your scripts into a few files. You don't need to create one file per function. You should be able to group them so to minimize the number of files that you as the maintainer or a reviewer has to open. 
* Data should be included in a data folder with appropriate names ("Dataset1" is not very descriptive). 
* Save your data as an `.Rda` file in the data folder and document it appropriately. 

#### Grammar/Naming conventions
* Don't use argument names that are not descriptive (i.e., `x`, `i`, `g`, `b`)
* Avoid the use of the `get` function, there's no need for it when following programming conventions. 
* `cof` function is not complete. 
* The `computePercentage` function seems to be a helper function and would likely not be of much use to other users. The `compPer` seems to be a simple wrapper to `ecdf` and I don't think this adds much value to the package.
* Functions like `computePS_down` and `computePS_up` can be combined and would only differ by an argument input. 
* The logic for the `n` argument in `cptPlot` looks the same. 
* Avoid the use of `1:length(vector)`, use the more robust `seq_along(vector)`. 
* Please provide informative error messages and avoid using "@param" in these messages. 
* avoid nesting functions inside functions if they are going to be used once. If these are meant to be helper functions, keep them outside the function and use an naming scheme such as: `.functionName`
* Your plotting function `stackedBarplot` looks pretty closed to the user. Your default arguments (i.e., colors, and other arguments)  should be available for the end user. 
* Try to reduce the amount of repetition in the code for `stackedBarplot`. 
* Your main function should be in the same case as the package `GISPA` so to keep things consistent. You shouldn't have to have 3 different functions for the number of plotted dimensions (i.e., `gispa1D`, `gispa2D`, etc.). 


Overall, your package should be exporting around 5-7 functions with the appropriate changes. 
Please make use of the Bioconductor classes available. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @BhaktiDwivedi, 
Your issue will be closed if you don't respond within the next 72 hours. 
Best regards,
Marcel

**Comment by BhaktiDwivedi** [comment]
Hi Marcel,

Please do not close the issue. I am working on implementing the changes/additions requested. I am almost there. I will respond and upload the revised package within 72 hours  or by 21st afternoon 12:20 PM? Hope that is alright?

Thank you!

Regards,
Bhakti

**Comment by LiNk-NY** [comment]
Hi @BhaktiDwivedi, 
Thank you for responding. I can wait for your revisions. 
You can take a bit longer to finish them up, if need be. 

Regards,
Marcel

**Comment by BhaktiDwivedi** [comment]
Hi Marcel,


Thank you! I am still working on the changes, I am trying to finish by tomorrow afternoon, if not it may push to Monday Jan 23rd. Hope its alright. I just want to let you know in advance, so please do not close the issue.


Appreciate your help and support.


Regards,

Bhakti

________________________________

**Comment by LiNk-NY** [comment]
Hi Bhakti, @BhaktiDwivedi  
Thank you for working on making those changes. Looking forward to them. 
Regards,
Marcel

**Comment by BhaktiDwivedi** [comment]
Hi Marcel,


Appreciate your patience. Can I please request an extension till Jan 26th Thursday end of the day to finally submit the revised version? I would greatly appreciate your help. Please let me know.


Thank you.


Regards,

Bhakti

________________________________

**Comment by LiNk-NY** [comment]
Hi @BhaktiDwivedi, 
Yes, you can submit tomorrow. Please have all the changes ready. 

Best regards, 
Marcel

**Comment by BhaktiDwivedi** [comment]
Hi Marcel,

I will be uploading the revised package later tonight, so please bear with me. Thank you for understanding.

Regards,
Bhakti

**Comment by LiNk-NY** [comment]
Hi @BhaktiDwivedi, 
Please provide an update on the status of your package. 
Much appreciated. 
Thank you. 
- Marcel

**Comment by BhaktiDwivedi** [comment]
Hi Marcel,


I have uploaded the revised package on GitHub; however I see a tag stating "version bump required". I did try 0.99.8 and then 0.99.9 but didn't make any change. Please let me know how I can fix this?


Also please see attached by responses to the changes requested.


I hope I have answered all your concerns and changes; however please let me know if there is anything else remaining.


Thank you.


Regards,

Bhakti


________________________________

**Comment by LiNk-NY** [comment]
Hi @BhaktiDwivedi, 
Thank you for making those changes. 
As @mtmorgan mentioned before, you should really make use of the classes
in `GSEABase` to represent gene sets. 

After a quick look at your package, there are still some points to be addressed. 

---

#### Data
* Please document your datasets appropriately (see: http://r-pkgs.had.co.nz/data.html) 
* Combine your data documentation roxygen snippets (roclets?) into one document > `data.R`. 

#### Code
* Try to keep your code tidy. This means not having lines that are over 80 columns wide.
* Set default values in the function definition 
* Make arguments more descriptive and consistent (e.g., `DM` means data matrix and data frame in different functions)
* Some arguments are described as "vector" when you likely mean `list` (such as for `f.sets`)
* You should avoid using underscores (`_`) in arguments. 
* There seems to be a lot of repetitive coding in `stackedBarplot` try to reduce this. 
* Avoid empty else statements `else { #nothing }`
* `return` calls after `stop()` are unnecessary
* Do not use underscores `_` in exported functions (`gispa_method`)
* Separate plotting and calculation in the "gispa_method". The function does too much. 

Best regards,
Marcel

**Comment by BhaktiDwivedi** [comment]
Hi @Marcel,

Thank you for the prompt review.

I will make the changes as per the below outlined points. I will also try to incorporate GSEABase to the existing function.

What’s the time-line to submit revised version with the changes? Please let me know.

Thank you.

Regards,
Bhakti

**Comment by marcel** [comment]
FYI typing @Marcel subscribes the username @marcel on github to the entire thread.

**Comment by LiNk-NY** [comment]
Hi @BhaktiDwivedi, 
Please submit as soon as you can make the changes. 
Best regards,
Marcel

**Comment by BhaktiDwivedi** [comment]
Hi @LiNk-NY,
Please see the new version with changes. Below I have highlighted the responses

"you should really make use of the classes in GSEABase to represent gene sets."
I have used GSEABase class in the code where it can be best used to represent gene sets or subset data by gene sets. As my package involves combining multiple data types by gene symbols, which can be duplicated depending on whether more than one variant or copy change or probe is reported in the input data-set, it's tricky to use the gene sets by each data type or data set separately. The results that are generated in this package are genes grouped by identified change points not necessarily by a phenotype or ontology or biological process or pathway. Although change point 1 profile is the most desirable, user with the help of the diagnostic plots can further access and evaluate the genes by change points that best represent the desired profile for their purposes. Please let me know if you still have concerns.

Data
•	Please document your datasets appropriately (see: http://r-pkgs.had.co.nz/data.html)
•	Combine your data documentation roxygen blocks into one document > data.R.
o	Made the changes

Code
•	Try to keep your code tidy. This means not having lines that are over 80 columns wide.
o	Fixed it

•	Set default values in the function definition
o	Done

•	Make arguments more descriptive and consistent (e.g., DM means data matrix and data frame in different functions)
o	Fixed it

•	Some arguments are described as "vector" when you likely mean list (such as for f.sets)
o	Fixed it

•	You should avoid using underscores (_) in arguments.
o	Fixed it

•	There seems to be a lot of repetitive coding in stackedBarplot try to reduce this.
o	I tried, but given the output I need to generate by one-, two-, and three- feature analysis and the likert function {HH} library limitations I have to repeat them.

•	Avoid empty else statements else { #nothing }
o	Fixed such statements

•	return calls after stop() are unnecessary
o	Fixed it 

•	Do not use underscores _ in exported functions (gispa_method)
o	changed to '.', and Fixed it where-ever applies

•	Separate plotting and calculation in the "gispa_method". The function does too much.
o	Fixed it. please see if this looks better.

**Comment by LiNk-NY** [comment]
Hi Bhakti @BhaktiDwivedi,
Thanks for making the changes.
What is the difference between `GISPA` and `gispaMethod`? It seems to me like the names should be different if they are not doing the same thing. It may confuse your users.

The rest is looking better!

Regards,
Marcel

**Comment by BhaktiDwivedi** [comment]
hi @LiNk-NY 

Thank you so much. Yes, it's the function for the changepoint-based profile characterization model. I can change it to something other than gispaMethod. for example, 'cptModel' 

Thank you.

**Comment by LiNk-NY** [comment]
That would be good! 
Thank you Bhakti!

**Comment by BhaktiDwivedi** [comment]
Done. Please see the submitted revised version. Thank you very much @LiNk-NY !

**Comment by LiNk-NY** [comment]
Hi Bhakti @BhaktiDwivedi, 
You are having some errors with the package, namely due to the version number. The version number of you package should be `0.99.z` where `z` is the number of times you have pushed changes to your package (you can also just make it `0.99.8` to keep it consistent with your commits).  The package has not been published on Bioconductor and therefore it cannot be anything above a `1.0.0` version. 

Best regards,
Marcel

**Comment by BhaktiDwivedi** [comment]
Hi @LiNk-NY,
Sure, I just changed the version to 0.99.8. I kept increasing to 1.0.# asI was getting the version bump required tag and to get a valid push. Hope this helps. Please let me know if there is anything else needed. Thank you.
Bhakti

**Comment by BhaktiDwivedi** [comment]
Hi @LiNk-NY 
Is there anything else that I need to fix or resolve in the final version? Please let me know. Thank you.
Regards,
Bhakti

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 
Can you kick off another build? Thanks.

**Comment by LiNk-NY** [comment]
Hi Bhakti, @BhaktiDwivedi 

Package development is a continual process. We hope that you consider adding unit tests to your package in order to make it more robust and less prone to bugs.

Please see the GitHub repository: `MangoTheCat/goodpractice` for more tips on improving your package's robustness. After installation (`BiocInstaller::biocLite("MangoTheCat/goodpractice")`), you can run `goodpractice::gp(".")` within your package's directory to get additional recommendations for your package. 

Once your package builds on Oaxaca, it will be ready to be accepted. 
Thank you for submitting to Bioconductor!

Best regards,
Marcel

**Comment by BhaktiDwivedi** [comment]
Hi @LiNk-NY ,
Thank you. I will take a look at the unit tests. I thought the reason I am getting a build error on Oaxaca is because of library {HH} prerequisites not being installed on the build system. Am i missing something here?
Regards,
Bhakti

**Comment by LiNk-NY** [comment]
Yes, that's right. We have installed it on `Oaxaca` and it should be ready to go. We are just making sure that your package fully checks out on `Oaxaca`. Thanks. 
Marcel

**Comment by LiNk-NY** [comment]
The package is building as expected! Thanks again.

**Comment by BhaktiDwivedi** [comment]
Thank you @LiNk-NY !! This is good news!

Please let me know when I will be able to obtain the URL.

Also, as I make updates and improvement in the package, I hope I am able to commit those changes on Bioconductor release version.

Thank you.

Regards,
Bhakti

**Comment by LiNk-NY** [comment]
Hi Bhakti, @BhaktiDwivedi 
When the package is added to the devel build system, the following URL should work: 
https://bioconductor.org/packages/GISPA

You will be contacted with SVN credentials for making further changes your package. 

Best regards,
Marcel
