### ISSUE TITLE
funtooNorm

### ISSUE THREAD

**Issue by kkleinoros** [Bioconductor/Contributions#204]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GreenwoodLab/funtooNorm

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Please correct any ERROR/WARNINGS that occur in the build report before a formal review takes place.

**Comment by kkleinoros** [comment]
I am not sure why it is failing, I can build and check on my system with no error.
I do notice that package minfi is not listed when loading in the progress report.
Kathleen

**Comment by lshep** [comment]
minfi is not listed as you used library instead of require. 

I do get this ERROR on my system as well. What version of the packages are you using? Are you using the devel version of R and the required packages? 

I'm not sure how minfi sets the pData object.  To have it accessible with pdata(grs) you can set it after creating the GenomicRatioSet object 
```
grs <- GenomicRatioSet(gr=genomerange,
                       Beta=normBeta,
                       preprocessMethod="funtooNorm")
pData(grs) = phenoData
```
Your current implementation will have pData be used as an argument to SummarizedExperiment. There is no such specification and it would go in the metadata. 
```
grs <- GenomicRatioSet(gr=genomerange,
                        Beta=normBeta,
                        preprocessMethod="funtooNorm",
                        metadata=list(pData=phenoData))
```
I'm not sure which is more appropriate for your data but I hope this helps.

**Comment by kkleinoros** [comment]
Yes thanks for your help.
No I did not use the developers version to debug, my bad.
Kathleen

**Comment by lshep** [comment]
A few comments: 

General: 
- [ ] Please fix all WARNINGS/ERRORS in the build report  (for now you can ignore tokay2; this is an issue on our end - but fix all others in malbec2/oaxaca) 
- [ ] Remove all unnecessary files from the top level directory (*.pdf, .Rproj, _old.Rnw, as well as the hidden git files) 
- [ ] Please be advised we generally accept packages that run R CMD check under 5min. If there is a way to shorten the examples/vignette  or use a smaller subset of data this is advisable. 

Vignette/README: 
 - [ ] Please add a section to the vignette and update the README for installation through Biocondcutor: 
```
source("http://www.bioconductor.org/biocLite.R")
biocLite("funtooNorm")
``` 

Man Files: 
- [ ] In funtooNorm-package.Rd, please remove  Version and Date - These will change with updates and become outdated - it is also already kept track in the DESCRIPTION file
- [ ] In funtooNorm.Rd - typo in force argument  whent 

R code: 
- [ ] we strongly encourage the use of S4 classes over S3 classes.  We would strongly encourage this update or please provide a strong justification for current implementation. 

Thank you for your time and effort and submission to Bioconductor.  Please comment back here when you are finished with any updates providing a summary of changes or justifications.

**Comment by kkleinoros** [comment]
Do I really want to change this?
* Checking R Version dependency...
    * WARNING: Update R version dependency from 3.2 to 3.4.
Kathleen

**Comment by lshep** [comment]
We prefer that the R version be updated to the current version being tested and submitted on. While generally it is okay, we can't guarantee backwards compatibility.

**Comment by lshep** [comment]
As a reminder, when you are finished making updates to the package please respond to the previous list of suggestions for which suggestions you have addressed and if any were not addressed.

**Comment by kkleinoros** [comment]
All suggestions have been addressed, except:
Please be advised we generally accept packages that run R CMD check under 5min. If there is a way to shorten the examples/vignette or use a smaller subset of data this is advisable.
The vignette does use a small subset of only 6 samples, I am not aware of a way to make the run shorter.

**Comment by lshep** [comment]
I'm working through your vignette and I can not get the  plotValidationGraph to work correctly.  It doesn't appear to be saving the file.  I tried running `plotValidationGraph(mySampleSet, type.fits="PCR")` as well as specifying a file path on my system; neither run produced a pdf file. Could you please investigate this?

**Comment by kkleinoros** [comment]
I have corrected the issue with plotValidationGraph, should I increment the version field in DESCRIPTION.

**Comment by lshep** [comment]
Yes please

**Comment by lshep** [comment]
Thank you.  Your package looks good and I will recommend it be accepted. Please leave the issue open. You will receive svn instructions via email (probably not until next week because of the holiday) for inclusion in Bioconductor devel.

**Comment by kkleinoros** [comment]
Thank you Ishep for your help.
Much appreciated.
Kathleen
