### ISSUE TITLE
MungeSumstats

### ISSUE THREAD

**Issue by Al-Murphy** [Bioconductor/Contributions#2043]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/neurogenomics/MungeSumstats

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by Al-Murphy** [comment]
Hi @LiNk-NY, 

My package has build successfully without errors and I don't plan to make further changes. Please let me know if there is anything else I can do in the meantime, I understand time is running out for the deadline for the next Bioconductor release and I want to ensure my package is included.

Thanks!
Alan.

**Comment by LiNk-NY** [comment]
Hi Alan, @Al-Murphy 

Thank you for your submission. Please see the review below. 

Best regards,
Marcel

---

# MungeSumstats #2043

* The package does not make a strong case for Bioconductor approval given
the extensive use of `data.table` and lack of formal integration to the
resources already available in Bioconductor (e.g., `VariantAnnotation` for
.vcf files and `GPos`, `GRanges`, and others for representing the data)

## DESCRIPTION

* Remove `LazyData: TRUE` according to `BiocCheck`.
* If possible, avoid downloading large packages by moving them from the
`Imports` to `Suggests` field.
* Add a `BugReports` field

## NAMESPACE

* Save as above regarding the data packages.

## vignettes

* It is preferrable to add `warning=FALSE` options at the chunk-level rather
than the document-level.
* Remove the GitHub installation section.
* You don't need to include the `BiocManager::install(version="devel")` bit
of code. This is known among developers. Your package will go into release
so this code will not be relevant for the majority of your users (conditional
on acceptance).
* The `ieuAmlVcf` appears to be a bit cryptic, perhaps use a more descriptive
name.
* Include a `sessionInfo` section.

## R

* Ensure that defaults are defaults. `allele_flip_check` has no default
although the documentation says it does.
* Avoid using code that writes to the `.globalEnv`. This is bad practice:
`assign("rsids", rsids, envir = parent.frame())`.
* I'm not sure how you can run names on a file `names(sumstats_file)`. Perhaps
the documentation needs a bit more details (in `check_chr`)?
* Avoid writing files for the user in `chekc_four_step_col`.

## tests

* It looks like you have plenty of tests.

**Comment by LiNk-NY** [comment]
Hi Alan, @Al-Murphy 

Additional commentary from our team: 
* It's not a good idea to have more than 2 dozen man pages for internal helpers. 

Consolidate these helper man pages into a single man page and R file (or groups of files if you'd like) and use the `@keywords internal` tag so that these man pages are not visible to the end user. The current state of the man pages can cause confusion. 

* Dumping all the lines of a tab-delimited file in a character vector and saving it as `.rda` for `ieuAmlVcf` and `eduAttainOkbay` datasets doesn't make sense. Either they save these files as `data.frame`s, or they put them in `inst/extdata`.

* Finally, the stuff in `inst/cit/` is used in the vignette so should be in the `vignettes/` folder.

Thanks!
-Marcel

**Comment by Al-Murphy** [comment]
Hey Marcel, 

I have updated the package to sort all issues you mentioned. Please let me know as soon as you can if there is anything else needed for MungeSumstats to be accepted and I'll be happy to update. See below for my comments on each:

> The package does not make a strong case for Bioconductor approval given
> the extensive use of data.table and lack of formal integration to the
> resources already available in Bioconductor (e.g., VariantAnnotation for
> .vcf files and GPos, GRanges, and others for representing the data)
> Update: Feedback from the group is positive. Your intentions at improving the
> interface to GWAS are good and that it seems that the main exported functions
> do not provide the user with data.table objects. 👍

Am I okay to assume then that the package is okay in it's current state for Bioconductor?

## DESCRIPTION

> Remove LazyData: TRUE according to BiocCheck.

Updated in code.

> If possible, avoid downloading large packages by moving them from the Imports to Suggests field.

This can't be avoided, I think the large packages are the **Bioconductor** packages:
```
    GenomicRanges,
    BSgenome,
    Biostrings,
    SNPlocs.Hsapiens.dbSNP144.GRCh37,
    SNPlocs.Hsapiens.dbSNP144.GRCh38,
    BSgenome.Hsapiens.1000genomes.hs37d5,
    BSgenome.Hsapiens.NCBI.GRCh38
```
All of which are needed for checking the data in the GWAS summary statistics file against valid reference genomes. This is essential to the quality control checks of GWAS outputs.


> Add a BugReports field

Updated in code.

## NAMESPACE

> Save as above regarding the data packages.

Updated in code.

## vignettes

> It is preferrable to add warning=FALSE options at the chunk-level rather
> than the document-level.

Removed in code.

> Remove the GitHub installation section.
> You don't need to include the BiocManager::install(version="devel") bit
> of code. This is known among developers. Your package will go into release
> so this code will not be relevant for the majority of your users (conditional
> on acceptance).

Removed in code.

> The ieuAmlVcf appears to be a bit cryptic, perhaps use a more descriptive
> name.

Based on the other comments from the team, I removed this R data object so no need to rename.

> Include a sessionInfo section.

Updated in code.

## R

> Ensure that defaults are defaults. allele_flip_check has no default
> although the documentation says it does.

Default has been set to `TRUE`. Thanks for pointing this out!

> Avoid using code that writes to the .globalEnv. This is bad practice:
> assign("rsids", rsids, envir = parent.frame()).

Updated in code. I have removed this approach and now return the dataset from the function that creates it.

> I'm not sure how you can run names on a file names(sumstats_file). Perhaps
> the documentation needs a bit more details (in check_chr)?

This was bad naming of variables and has been updated

> Avoid writing files for the user in chekc_four_step_col.

I've removed this which has made the code a lot cleaner and resulted in faster run times.

## tests

> It looks like you have plenty of tests.

## Additional commentary from our team:

> > It's not a good idea to have more than 2 dozen man pages for internal helpers.
> > Consolidate these helper man pages into a single man page and R file (or groups of files if you'd like) and use the @keywords internal tag so that these man pages are not visible to the end user. 
> The current state of the man pages can cause confusion.

Updated in code. I have used `@keywords internal` to clean this up.

> > Dumping all the lines of a tab-delimited file in a character vector and saving it as .rda for ieuAmlVcf and eduAttainOkbay datasets doesn't make sense. 
> Either they save these files as data.frames, or they put them in inst/extdata.

I have moved ieuAmlVcf and eduAttainOkbay to extdata as raw txt/vcf files instead of having them as R data objects.

> Finally, the stuff in inst/cit/ is used in the vignette so should be in the vignettes/ folder.

Updated in code.

**Comment by Al-Murphy** [comment]
Hi @LiNk-NY, 

To note that the last push was just to sort the vignette engine based on a suggestion on the bioc-devel mailing list and does not effect my previous message outlining my admendments to the package. I look forward to hearing back from you on then. 

Thanks,
Alan.

**Comment by LiNk-NY** [comment]
Hi Alan, @Al-Murphy 

>> If possible, avoid downloading large packages by moving them from the Imports to Suggests field.

> This can't be avoided, I think the large packages are the Bioconductor packages:
    GenomicRanges,
    BSgenome,
    Biostrings,
    SNPlocs.Hsapiens.dbSNP144.GRCh37,
    SNPlocs.Hsapiens.dbSNP144.GRCh38,
    BSgenome.Hsapiens.1000genomes.hs37d5,
    BSgenome.Hsapiens.NCBI.GRCh38

After a closer look, this can be avoided. You use one `ref_genome` or the other in the code so requiring the user to have both downloaded is not good practice especially if they are large packages. Please put these packages in the `Suggests` field of the `DESCRIPTION` file.

In your code, you can attempt to `loadNamespace` the package that corresponds to the `ref_genome` input by the user and provide an error if it is not installed. 

Best regards,
Marcel

**Comment by Al-Murphy** [comment]
Hi Marcel @LiNk-NY,

That's no problem, I'll do as you suggested. By any chance, do you know of a package where this type of approach is done? Sorry, but I'm not familiar with loading packages based on user input functions.

Thanks,
Alan.

**Comment by LiNk-NY** [comment]
Hi Alan, @Al-Murphy 

You can do something like: 

```r
if (identical(ref_genome, "GRCh37") && !requireNamespace("SNPlocs.Hsapiens.dbSNP144.GRCh37", quietly = TRUE))
    stop("Install 'SNPlocs.Hsapiens.dbSNP144.GRCh37' to use 'GRCh37' as 'ref_genome'")
```

Best, 
Marcel

**Comment by Al-Murphy** [comment]
Hi Marcel @LiNk-NY,

I have made those changes to move packages to the suggests as you suggested.

Please let me know if any other changes are necessary!

Thanks,
Alan.

**Comment by LiNk-NY** [comment]
Hi Alan, @Al-Murphy 
Can you re-bump the package `z` version (`x.y.z`) to kick off another build?
It seems we were having issues with the SPB. 
Thanks!
Best,
Marcel

**Comment by vjcitn** [comment]
At this moment I am seeing 
```
--- re-building ‘MungeSumstats.Rmd’ using rmarkdown
Quitting from lines 161-165 (MungeSumstats.Rmd) 
Error: processing vignette 'MungeSumstats.Rmd' failed with diagnostics:
Install 'SNPlocs.Hsapiens.dbSNP144.GRCh37' to use 'GRCh37' as 'ref_genome'
--- failed re-building ‘MungeSumstats.Rmd’

SUMMARY: processing the following file failed:
  ‘MungeSumstats.Rmd’

Error: Vignette re-building failed.
Execution halted
```
with
```
> sessionInfo()
R Under development (unstable) (2021-04-15 r80175)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS (fossa-melisa X20)

Matrix products: default
BLAS:   /home/stvjc/R-dev-dist/lib/R/lib/libRblas.so
LAPACK: /home/stvjc/R-dev-dist/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] MungeSumstats_0.99.22 rmarkdown_2.7        

loaded via a namespace (and not attached):
 [1] compiler_4.1.0              restfulr_0.0.13            
 [3] GenomeInfoDb_1.27.11        XVector_0.31.1             
 [5] MatrixGenerics_1.3.1        bitops_1.0-7               
 [7] tools_4.1.0                 zlibbioc_1.37.0            
 [9] digest_0.6.27               lattice_0.20-41            
[11] evaluate_0.14               BSgenome_1.59.2            
[13] rlang_0.4.10                Matrix_1.3-2               
[15] DelayedArray_0.17.10        rstudioapi_0.13            
[17] yaml_2.2.1                  parallel_4.1.0             
[19] xfun_0.22                   GenomeInfoDbData_1.2.4     
[21] rtracklayer_1.51.5          knitr_1.33                 
[23] Biostrings_2.59.2           S4Vectors_0.29.17          
[25] IRanges_2.25.10             grid_4.1.0                 
[27] stats4_4.1.0                data.table_1.14.0          
[29] Biobase_2.51.0              XML_3.99-0.6               
[31] BiocParallel_1.25.5         startup_0.15.0             
[33] Rsamtools_2.7.2             matrixStats_0.58.0         
[35] htmltools_0.5.1.1           BiocGenerics_0.37.4        
[37] GenomicRanges_1.43.4        GenomicAlignments_1.27.2   
[39] SummarizedExperiment_1.21.3 RCurl_1.98-1.3             
[41] crayon_1.4.1                rjson_0.2.20               
[43] BiocIO_1.1.2               
> BiocManager::valid()
Bioconductor version 3.13 (BiocManager 1.30.12), ?BiocManager::install for help
[1] TRUE
```

**Comment by Al-Murphy** [comment]
Hi Vincent @vjcitn,

Thank you for looking into this. I'm not sure why that is happening on your check as  SNPlocs.Hsapiens.dbSNP144.GRCh37 (and the other packages used for the reference genome) have been moved to the suggests as suggested by Marcel @LiNk-NY. This doesn't cause an error for me locally or on three Bioconductor machine R CMD CHECKS. Maybe you need to install the reference genome packages to get it to run?:
 SNPlocs.Hsapiens.dbSNP144.GRCh37,
 SNPlocs.Hsapiens.dbSNP144.GRCh38,
 BSgenome.Hsapiens.1000genomes.hs37d5,
 BSgenome.Hsapiens.NCBI.GRCh38

**Comment by vjcitn** [comment]
Indeed I need to install them.  And that is pretty laborious.  I think what you are trying to accomplish in this package is important, and various groups are tackling it in various ways -- it would be nice to federate.  Your package requires me to install all four of those packages, even to explore/check your package?  That seems excessive, but of course we can support that.  I wonder if you have considered making extracts of these resources for testing purposes -- perhaps a fragment of a chromosome for each, that would allow the package to be installed and checked without so many GB of up-front installation.  I am doing the installations now on a home wireless link -- very tedious.

**Comment by vjcitn** [comment]
One more question: how do you deal with reported rsids (from old GWAS) that have been "merged" and don't have representation in more recent dbSNP?  There is a resource at NCBI that collects the relevant information up to 2018 or so.  After that the SPDI standard is used to collect annotations on genomic coordinates.  I am unaware of much uptake of SPDI among practitioners.

**Comment by vjcitn** [comment]
You are likely familiar with the MRC integrative epidemiology unit's ieugwasr package.  That and gwasglue are of interest where I work, but gwasglue in particular has some dependencies that are challenging to resolve.  To allow more exploration I forked some of the related packages that are only on github and have made https://vjcitn.github.io/gwaslake ...I have had no time to try to dialogue with the MRC folks yet, or to develop these interfaces further, but this is a source of "already munged" summary statistics.

**Comment by Al-Murphy** [comment]
> Indeed I need to install them. And that is pretty laborious. I think what you are trying to accomplish in this package is important, and various groups are tackling it in various ways -- it would be nice to federate. Your package requires me to install all four of those packages, even to explore/check your package? That seems excessive, but of course we can support that. I wonder if you have considered making extracts of these resources for testing purposes -- perhaps a fragment of a chromosome for each, that would allow the package to be installed and checked without so many GB of up-front installation. I am doing the installations now on a home wireless link -- very tedious.

I'm happy to do that is it is necessary? Although I haven't seen something like that done before, do you know of a package where this has been done?

**Comment by Al-Murphy** [comment]
> You are likely familiar with the MRC integrative epidemiology unit's ieugwasr package. That and gwasglue are of interest where I work, but gwasglue in particular has some dependencies that are challenging to resolve. To allow more exploration I forked some of the related packages that are only on github and have made https://vjcitn.github.io/gwaslake ...I have had no time to try to dialogue with the MRC folks yet, or to develop these interfaces further, but this is a source of "already munged" summary statistics.

Yes, I'm familiar with the IEU GWAS project and the related VCF format! This is described in more detail in my related paper which will be up in bioRxiv soon but in short: While GWAS VCF is a standardised format that future GWAS may adopt, there are still many past, publicly available GWAS which are not in VCF format. For example, although their summary statistics are publicly available, the GWAS for Cerebral small vessel disease is not yet available in VCF format via IEU GWAS. Moreover, as VCF is not yet the standard for sharing files, unpublished GWAS shared within consortia or provided by personal genetics companies are still in a multitude of summary statistic formats.

**Comment by vjcitn** [comment]
It isn't necessary to do the "trimmed" resources that I suggested -- but to run CMD check I need all the Suggests packages installed.  Now that I have done that a) I think your issue with combineRows can/should be ignored (be sure BiocManager::valid returns true as you explore, and always report sessionInfo when issuing a report), b) I am pleasantly surprised at performance of snpsById.  I don't know how @hpages has made it work so nicely!  Should be interesting to investigate.  So the final question from me is: how do you deal with obsolete/merged rsids?

**Comment by Al-Murphy** [comment]
> One more question: how do you deal with reported rsids (from old GWAS) that have been "merged" and don't have representation in more recent dbSNP? There is a resource at NCBI that collects the relevant information up to 2018 or so. After that the SPDI standard is used to collect annotations on genomic coordinates. I am unaware of much uptake of SPDI among practitioners.

I haven't heard of this NCBI resource? Is there a related site? As I understand your question, it's what to do with SNPs that are not in current dbSNP version? So MungeSumstats asks the user for the reference genome from the GWAS. There is a check, which is on by default (on_ref_genome), which checks if the SNP is on the inputted reference genome. If it isn't, currently the SNP is removed. So in that sense, MungeSumstats won't handle that situation. 

Is the Base pair position and chromosome of these obsolete SNPs still correct? If so, there is already a function in MungeSumstats to impute SNP RS ID based on the reference genome from the given base pair position and chromosome so, if these are correct for these obsolete SNPs, I can add this function to run on SNPs not found on the reference genome instead of just removing them.

**Comment by vjcitn** [comment]
For completeness, here is a query to NLM:
```
Summary: how current is the SNP ID merge resource

Details:
I found the change stamp for an rsid merge resource at

https://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/database/organism_data/ 

specifically

https://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/database/organism_data/RsMergeArch.bcp.gz

The timestamp is

RsMergeArch.bcp.gz 2018-02-07 12:09 146M

So that table is 3 years old, but notice it is associated with (according to the directory path) b151 (dbSNP) and GRCh38 (hg38) ...so perhaps it is "up to date" even though 3 years old.

Has the merging process ended? If not, is there a more recent resource to use?
```
Here is the reply:
```
Hi,
 
Thanks for writing to us.
 
Those files are from the legacy snp build process, which was decommissioned in 2018.
 
The SNP build has been using SPDI-based asserted location workflow since build 152. That system no longer produces relevant file on this. The new build system only produces json and vcf:
https://ftp.ncbi.nlm.nih.gov/snp/latest_release/
 
 
Regards,
 
....
NCBI User Services
http://bit.ly/ncbi_factsheets
]]>
```

**Comment by LiNk-NY** [comment]
> > Indeed I need to install them. And that is pretty laborious. I think what you are trying to accomplish in this package is important, and various groups are tackling it in various ways -- it would be nice to federate. Your package requires me to install all four of those packages, even to explore/check your package? That seems excessive, but of course we can support that. I wonder if you have considered making extracts of these resources for testing purposes -- perhaps a fragment of a chromosome for each, that would allow the package to be installed and checked without so many GB of up-front installation. I am doing the installations now on a home wireless link -- very tedious.
> 
> I'm happy to do that is it is necessary? Although I haven't seen something like that done before, do you know of a package where this has been done? To note, all examples and tests run on GRCh37 so only BSgenome.Hsapiens.1000genomes.hs37d5 and SNPlocs.Hsapiens.dbSNP144.GRCh37 should need to be installed

Hi Alan, @Al-Murphy 

It seems like you are using `GRCH38` in some of the examples so the other packages would be required for checking the package. Please make sure that you are only using one or the other. 

```r
> SNP_LOC_DATA <- load_snp_loc_data("GRCH38")
Error in loadNamespace(x) : 
  there is no package called ‘SNPlocs.Hsapiens.dbSNP144.GRCh38’
```

Thanks!

**Comment by LiNk-NY** [comment]
@Al-Murphy 

Thanks for making the changes, Alan. This looks good to me. 
You can ignore that error for now. 

Thank you for your contribution. 

Best,
Marcel

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Al-Murphy.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MungeSumstats")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MungeSumstats

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
