### ISSUE TITLE
granulator

### ISSUE THREAD

**Issue by xanibas** [Bioconductor/Contributions#2065]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/xanibas/granulator

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by xanibas** [comment]
hey @LiNk-NY ,

I'm tagging @lshep as I'm having the same issue in the previous submission attempt:
https://github.com/Bioconductor/Contributions/issues/2036

after version bump and succesfull push, no automatic build is triggered:
https://github.com/xanibas/granulator/commit/5ee0c397b2d3ca01542969c8b2f771c8c2801e53

git remote -v                                                           
origin  git@github.com:xanibas/granulator.git (fetch)
origin  git@github.com:xanibas/granulator.git (push)
upstream        git@git.bioconductor.org:packages/granulator.git (fetch)
upstream        git@git.bioconductor.org:packages/granulator.git (push)

git fetch -v --all
Fetching origin
Enter passphrase for key '....':
From github.com:xanibas/granulator
 = [up to date]      master     -> origin/master
Fetching upstream
Enter passphrase for key '....':
From git.bioconductor.org:packages/granulator
 = [up to date]      master     -> upstream/master

**Comment by lshep** [comment]
While we debug we will have to do manual builds of the package.  @nturaga  could you set up the log monitoring we discussed to see if you get an error message from the internal codes so we can trace why its rejecting the call to the API to trigger a build?  @Kayla-Morrell while I'm out next week you may have to trigger some manual builds for this package

**Comment by nturaga** [comment]
I'm hesitant to set up logs, because on looking back at the response I got from it trying the API_ENDPOINT manually, it's not very useful.

```
ln [14] response.content
Out[8]: b'OK not building existing package'

In [15]: response.status_code
Out[15]: 200
```

I also retraced my steps when we did set it up. The logging code is implemented and ready, but we decided to disable it because it wasn't adding any value. 

Also, how did the build go through just now?? (looking above)

**Comment by lshep** [comment]
I manually kicked off a build

**Comment by lshep** [comment]
And the ERROR code is not helpful to you but helpful to me -- it is recognizing granulator as an existing package

**Comment by lshep** [comment]
Ok I think I figured out what the issue was;  There was multiple previous submissions so the code was not able to trace it back to the correct issue.  I believe I have corrected.  @xanibas  Could you try another version bump to see if it is automatically triggered now? Sorry for all this confusion

**Comment by xanibas** [comment]
Thank you @lshep , issue is solved now!

**Comment by LiNk-NY** [comment]
Hi Sabina, @xanibas 

Thank you for your submission and for making the changes to improve your package. 
We appreciate it. 
There are a few points still outstanding from `BiocCheck` that can be easily resolved.
Thank you for your patience and attention. 

Best,
Marcel

---

# granulator #2065

## DESCRIPTION

* Add a `BugReports` field
* Update R version to `>= 4.1`
* `LazyData` should be set to `FALSE`

## NAMESPACE

* Looks good.
* Consider re-exporting the `%>%` if you expect users to use your functions
that way.

## vignettes

* Avoid using `print` for inspecting an object. Simply use `correl$summary`,
for example.

## R

* Remove the redundant `paste0` on line 112 of `R/deconvolute.R` as pointed
out by `BiocCheck`

## tests

* Please add unit tests to ensure that your functionality is robust and less
prone to bugs and errors.

**Comment by xanibas** [comment]
Hey Marcel @LiNk-NY ,

thank you for the quick reply.
I have adressed all issues you have raised (see comments below).

The build fails on Mac, but it seems a Mac font installation issue:
Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  no font could be found for family "Arial"
which causes `GeometryDoesNotContainImage` and fails to build the vigentte.

Best,
Sabina

> Hi Sabina, @xanibas
> 
> Thank you for your submission and for making the changes to improve your package.
> We appreciate it.
> There are a few points still outstanding from `BiocCheck` that can be easily resolved.
> Thank you for your patience and attention.
> 
> Best,
> Marcel
> 
> # granulator #2065
> ## DESCRIPTION
> * Add a `BugReports` field
> * Update R version to `>= 4.1`
> * `LazyData` should be set to `FALSE`

done.

> ## NAMESPACE
> * Looks good.
> * Consider re-exporting the `%>%` if you expect users to use your functions
>   that way.

I made all outputs in the `matrix` or `data.frame` format.
I prefer to leave it to the user to decide how they want to manipulate them in downstream analysis.

> ## vignettes
> * Avoid using `print` for inspecting an object. Simply use `correl$summary`,
>   for example.

done.

> ## R
> * Remove the redundant `paste0` on line 112 of `R/deconvolute.R` as pointed
>   out by `BiocCheck`

done.

> ## tests
> * Please add unit tests to ensure that your functionality is robust and less
>   prone to bugs and errors.

done, added tests for data loading and all processing/plotting functions.

**Comment by xanibas** [comment]
Hey Marcel @LiNk-NY ,

indeed I got rid of quite some big datasets.
I can use BFG, but whouldn't be a simple clean of the git history suffice?
https://gist.github.com/stephenhardy/5470814

(given that it's the first release, I don't really need to keep track of how the package was created)

Let me know which way you prefer...

Best,
Sabina

**Comment by LiNk-NY** [comment]
Hi Sabina, @xanibas 

That is the nuclear option if you don't mind losing your git history. 
We would prefer to preserve the git history but it is entirely up to you.
If you do change the history, we would need someone to do the force push
to the `git.bioconductor.org` repository (which you may not be able to do and
after you force push to GitHub, of course). 

Best,
Marcel

**Comment by xanibas** [comment]
Hey Marcel @LiNk-NY ,

I want throguh with cleaning the history as it was quite messy and force push to the origin.
Will start tracking the commits from this version on.

The force push to the upstream is indeed being blocked:
remote: FATAL: + refs/heads/master packages/granulator xanibas DENIED by fallthru
remote: error: hook declined to update refs/heads/master
To git.bioconductor.org:packages/granulator.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'git.bioconductor.org:packages/granulator.git'

Are you able to do it from your side?

Thanks for the help,
Sabina

**Comment by LiNk-NY** [comment]
Hi Sabina, @xanibas 
Please force push only to your GitHub repository. 
We can take care of the rest. 
Is it ready?
Best,
Marcel

**Comment by xanibas** [comment]
yes, the github repositroy is up to date now

**Comment by LiNk-NY** [comment]
Hi Sabina, @xanibas 
Nitesh updated the BioC git repository. The package is ready to go now. 
Thanks for your submission! 
Best,
Marcel

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/xanibas.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("granulator")`. The package 'landing page' will be created at

https://bioconductor.org/packages/granulator

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
