### ISSUE TITLE
triwise

### ISSUE THREAD

**Issue by Zouter** [Bioconductor/Contributions#207]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/saeyslab/triwise

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@LiNk-NY will review this package, but it seems like it should have an easy interface with SummarizedExperiment, the basic Bioconductor object for representing expression values in designed experiments.

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 
It seems like the SPB is missing a package dependency? `circular`? 
Could you possibly install it manually? 
Thanks, 
Marcel

**Comment by Zouter** [comment]
@LiNk-NY Thank you for your time. I was already registered using the maintainer e-mail address, and this was also what BiocCheck told me..

Thank you
Wouter

**Comment by lshep** [comment]
@LiNk-NY I installed the package manually for the MAC builder

**Comment by LiNk-NY** [comment]
@Zouter, 
Just a note: The error pertains to the Bioc-devel mailing list and is different from the Bioconductor support site. 
Please bump the version for another build. 

Regards,
Marcel

**Comment by Zouter** [comment]
@LiNk-NY 
I now subscribed to this mailing list, thank you. I also bumped the version but no new build has been generated. Do I have to do something else for the bot to start rebuilding?

Kind regards
Wouter

**Comment by lshep** [comment]
Did you set up the webhook as described [here] (https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) ? The builder will not pick up a version bump if the webhook is not set up.

**Comment by LiNk-NY** [comment]
@Zouter,
Please bump your package's version. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @Zouter, 
Thanks for making changes to your package. 
Have you considered using `SummarizedExperiment` for representing expression values? 
I don't see why you wouldn't use it. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @Zouter, 
Any updates on interfacing with `SummarizedExperiment`? 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @Zouter, 
Please respond to this thread or your issue will be closed within 48 hours. 
Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @Zouter, 
Thank you for considering Bioconductor. 
Unfortunately, you response level has been low and it makes it difficult to communicate appropriate changes to your package. If you would like your package to be reconsidered with the appropriate changes, please create another issue submission. 
Best regards,
Marcel
