### ISSUE TITLE
tLOH

### ISSUE THREAD

**Issue by michelgw** [Bioconductor/Contributions#2087]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/USCDTG/tLOH

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by michelgw** [comment]
Hello, I recently updated the git repository to v0.99.1 and attempted to update to bioconductor using the instructions at https://bioconductor.org/developers/how-to/git/new-package-workflow/. However, I am receiving an error when running the command `git push upstream main`. I included the errors below:

> remote: FATAL: W refs/heads/main packages/tLOH michelgw DENIED by fallthru
> remote: error: hook declined to update refs/heads/main
> To git.bioconductor.org:packages/tLOH.git
>  ! [remote rejected] main -> main (hook declined)
> error: failed to push some refs to 'git@git.bioconductor.org:packages/tLOH.git'

Do you have any recommendations on resolving this issue?

Thank you,
Michelle

**Comment by LiNk-NY** [comment]
Hi Michelle, @michelgw 
Please push to the `master` branch. We do not support the `main` branch yet. 
`git push upstream master`
Thank you. 
-Marcel

**Comment by LiNk-NY** [comment]
Hi Michelle, @michelgw 

Thank you for your submission. 
Please see the short review below. 

Best regards,
Marcel

---

# tLOH #2087

* I am not sure what would make this package a Bioconductor one given that there is no integration to existing tools.
* Perhaps this package is best suited for `CRAN`?

## DESCRIPTION

* Include a `BugReports` field.

## NAMESPACE

* It seems that you are not using existing Bioconductor infrastructure.
* There are opportunities to use `GPos`, `VariantAnnotation`, `spatialLIBD`,
etc. for the data representation.

**Comment by michelgw** [comment]
Hello Marcel,

Thank you for your response. I used the command `git push upstream master` and now receive the following output:

> error: src refspec master does not match any.
> error: failed to push some refs to 'git@git.bioconductor.org:packages/tLOH.git'

Have you seen this error before? I have used the fetch and merge commands prior to this. Thank you as well for the short review. I am addressing the issues of infrastructure right now and will provide a detailed response soon.

Best,
Michelle

**Comment by michelgw** [comment]
Hello Marcel,

Solved the git issue, although now I have a question regarding the build report. I see the error:

```
* Checking library calls...
Error in parse(outfile, keep.source = TRUE) : 
  C:\Users\pkgbuild\AppData\Local\Temp\RtmpiuoFVo\file1905e7c4680/parseFile.tmp:11:0: unexpected end of input
9: 
10: 
   ^
Calls: BiocCheck -> parseFiles -> parseFile -> parse
Execution halted
```
I am not certain where this is occurring, do you know what this message is referring to?

Thanks,
Michelle

**Comment by LiNk-NY** [comment]
Hi Michelle, @michelgw 

1)
Can you post what you did to get the git issue resolved? 
Was it `git branch -u upstream/master main`? Thanks!

2)
I am not familiar with the issue. 
I looked at the `tmp` file and it seems to be referring to the example in the `plotLOH.Rd`:
```
plotLOH <- function(inputFile,sample)
```
Further information here: https://github.com/Bioconductor/BiocCheck/issues/51
It seems like you are trying to run code that is not valid?

Are `inputFile` and `sample` real objects or is this meant to be pseudo-code?

**Comment by michelgw** [comment]
Hi Marcel @LiNk-NY, 

1. To resolve, I used `git push upstream main:master`. 
2. I see what you mean - I just updated that .Rd file to see if that code line is the problem. Thank you for looking into it and for sharing the link. The example code there was meant to be pseudo-code, not real objects although I can work on adding.

I am still addressing the issues on tool integration and infrastructure mentioned earlier, will update soon. I am looking into the most recent build report as well.

Thank you,
Michelle

**Comment by michelgw** [comment]
Hello Marcel @LiNk-NY,

Thank you again for your review, those are essential and necessary suggestions. I agree that tLOH should use existing data structures and integrate Bioconductor tools. The library now requires VCF input with implementation of VariantAnnotation readVcf() for data import, and I am working with GenomicRanges GPos. These changes will be updated and documented in the repository within the next couple of days. To address build report concerns, I am separating code into smaller functions, increasing the number of runnable examples in the man/*.Rd files, and registered at the support site yesterday. 

Thanks,
Michelle

**Comment by LiNk-NY** [comment]
This sounds great! 
Thank you Michelle @michelgw

**Comment by LiNk-NY** [comment]
Hi Michelle, @michelgw 

Please remember to include a vignette in the package and 
runnable examples for your exported functions (see the build report). 

Best,
Marcel

**Comment by michelgw** [comment]
Hi Marcel @LiNk-NY,

Thank you for the reminder. I am currently re-writing my vignette and examples to include the new data import info and will update the repository today.

Thank you,
Michelle

**Comment by michelgw** [comment]
Hi Marcel @LiNk-NY,

I see that the most recent build report has the error:
`Error: package or namespace load failed for tLOH in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called DelayedArray`
Would implementation of DelayedArray fix this issue? Also, I documented data/dataExample.rda in my R/data.R file, yet there is an "Undocumented data set" error. Do you have any suggestions on how I can address this issue?

Thank you,
Michelle

**Comment by LiNk-NY** [comment]
Hi Michelle, @michelgw 
Sorry for the late response. I looks like you were able to resolve the issue. 
Could you please provide a more descriptive dataset name? 
`dataExample` is a bit too vague. 
Thank you!
-Marcel

**Comment by michelgw** [comment]
Hi Marcel @LiNk-NY,

Sure, I just updated the dataset name. To fix the earlier issue, I added DelayedArray to the Imports section of the DESCRIPTION file. I will see if the undocumented dataset warning appears again in the new build report.

Best,
Michelle

**Comment by michelgw** [comment]
The undocumented dataset error was fixed by using devtools::document() on my package, which created an .Rd file for the dataset in the man/ directory containing info from the R/data.R file.

Best,
Michelle

**Comment by LiNk-NY** [comment]
Hi Michelle, @michelgw 
 
> Sure, I just updated the dataset name. To fix the earlier issue, I added DelayedArray to the Imports section of the DESCRIPTION file. I will see if the undocumented dataset warning appears again in the new build report.

You do not need to import `DelayedArray`. You need to import the `rowRanges` generic from `MatrixGenerics`
which will then call the appropriate method for the `CollapsedVCF` object. 

```
importFrom("MatrixGenerics", "rowRanges")
```
Update the `DESCRIPTION` file accordingly. 

Best,
Marcel

**Comment by michelgw** [comment]
Hi Marcel @LiNk-NY,

Thank you for letting me know about DelayedArray, I updated the files.

Best,
Michelle

**Comment by LiNk-NY** [comment]
Hi Michelle, @michelgw 

Thank you for making the changes!
We have accepted the package. 
Thank you for your contribution to Bioconductor.

Best regards,
Marcel

**Comment by michelgw** [comment]
Hi Marcel @LiNk-NY,

Wow thank you!! I am very excited to contribute to Bioconductor and look forward to adding more features to this package in the future. I appreciate all of your help during the review process.

Thank you,
Michelle

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/michelgw.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tLOH")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tLOH

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
