### ISSUE TITLE
Dino

### ISSUE THREAD

**Issue by JBrownBiostat** [Bioconductor/Contributions#2093]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JBrownBiostat/Dino

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by JBrownBiostat** [comment]
Hi @nturaga (Nitesh),

Hope I'm not being too much of a squeaky wheel , but it's been a while so I'm hoping I can get an ETA on when you might be able to review my package.

We are under deadline for journal re-submission (and have already extended once), and so if there is anything I can do on my end to accelerate the process, I'd love to help.

Thanks,
-Jared

**Comment by nturaga** [comment]
# Dino review


## R CMD build

ok

## R CMD INSTALL 

ok

## DESCRIPTION

ok

## NAMESPACE 

ok

## NEWS.md

- Make sure it’s parseable by `utils::news()`

## Vignettes

- The vignette looks like it has a block of code just dropped into it https://github.com/JBrownBiostat/Dino/blob/master/vignettes/Dino.Rmd#L179. 

- This is not particularly informative or “teaching” a user much, when they have to parse the code to learn something. Even though ‘echo=FALSE’ on that code chunk, a better way to do it is to document what each line is doing and break it up into bits. 

- It is not easy to read code as a user unless they have intricate knowledge of your package. 

## tests

- https://github.com/JBrownBiostat/Dino/blob/master/tests/testthat/test-SeuratFromDino.R is empty. Doesn’t test anything.

- it is always advisable to write better test cases. 

## R

- Break up the length of your functions. When implementing mathematical processes like the EM, you’ll have a hard time debugging if something breaks inside the code of a 150 line function.	Smaller functions lead to easier time debugging (https://github.com/JBrownBiostat/Dino/blob/master/R/CalcEM.R). Your future self (and I right now) will thank you.

- There are a lot of values that are hard coded into the functions. Please explain them in comments or document the reasoning behind them https://github.com/JBrownBiostat/Dino/blob/master/R/CalcEM.R#L629.

- The helper functions https://github.com/JBrownBiostat/Dino/blob/master/R/CalcEM.R#L433 all take `parList` as an argument. It’s impossible to know what the structure of this parameter list is supposed to be. Please use a standard class structure like S4 (object oriented, where each function can be a method on that type of object), or pass in explicit arguments. Also use argument validation in each of the functions. 

- You don’t actually need to do this, https://github.com/JBrownBiostat/Dino/blob/master/R/Dino.R#L113, R will automatically garbage collect at the end of the process.

- Remove commented out code. 

## General

- As soon as your have a clean build report, please include a detailed response of each point. I’ll get back to your package as soon as I can. 


P.S : Sorry for the delay, but please understand that the core team has multiple commitments, apart from package reviews. We are doing the best we can in the time available to us.

**Comment by JBrownBiostat** [comment]
Hi Nitesh,

Thanks for taking the time, and no worries about the  delay. I have of course noticed the recent release of the latest Bioconductor version, and I'm sure that didn't help an already busy schedule.

I have updated the code, it builds cleanly, an my responses to your specific comments are below:

## NEWS.md

- On my system, NEWS.md is parseable by utils::news(). Please let me know if this is not the case on other systems and I'll look into it further.

## Vignettes

- I have removed much of the code block from the current version of the vignette. This section (of the vignette) in general is a description not of the way in which the package should be used, but rather why it is necessary/useful. In particular, this section is giving a brief overview of the underlying algorithm and the code block you mention is intended to generate useful figures for the viewer, not useful code (hence the 'echo=FALSE' statement). To reduce the potential for confusion, I have separately compiled the needed simulation data and included it as package data, which is now loaded and processed at this stage of the vignette.
- 
## tests

- All tests are active.

## R

- Apologies for any readability problems due to function length. I have trimmed all functions down to below the recommended 50 lines, constructing several new smaller functions to support this functionality.

- I have endeavored to add documentation (comments in the code) surrounding the hardcoded values, particularly including the optimization parameters (defining the Strong Wolfe conditions) which you specifically mentioned. In general, these hard coded values represent optimization parameters which, while algorithmically necessary, do not meaningfully alter the output of the method. As such, I chose not to include them as user adjustable as, in the more likely best case, there would be no noticeable difference, and in the worst case, the method would converge (potentially significantly) more slowly.

- Thanks for the suggestion regarding the formatting of the 'parList' object. I have recoded the variable and its operating functions as an S4 object, documenting the mathematical purpose of each of its slots at the point of definition (see R/EM_Class.R).

- I have removed the 'rm(*)' statements. Thanks for letting me know about this functionality.

- I have removed commented-out code.


Thanks!
-Jared

**Comment by JBrownBiostat** [comment]
Hi @nturaga,

Just pinging this issue to keep it active.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/JBrownBiostat.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Dino")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Dino

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
