### ISSUE TITLE
chromhmmData

### ISSUE THREAD

**Issue by MahShaaban** [Bioconductor/Contributions#2101]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MahShaaban/chromhmmData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by MahShaaban** [comment]
AdditionalPackage: https://github.com/MahShaaban/segmenter

**Comment by MahShaaban** [comment]
@hpages I followed the advice you gave me in the slack channel for a package that was above the size limit. I started by submitting the data package. I tried to link the software package to this issue as an additional package but I couldn't despite closing the original issue first.

**Comment by hpages** [comment]
Hi @MahShaaban,

Would have been simpler to just add **chromhmmData** to the original **segmenter** submission. Now it looks like the bioc-issue-bot is very confused, not sure why. Problem is that if we close this issue, re-open the **segmenter** issue, and add **chromhmmData** to the **segmenter** issue, the bioc-issue-bot might get even more confused. But we're going to try this anyways because really, starting a submission with the central package (normally the software package), and adding the data package to it, is the way to go.

Please re-open the **segmenter** issue and try to add **chromhmmData** there.

I'm closing this.

Best,
H.
