### ISSUE TITLE
BUSseq

### ISSUE THREAD

**Issue by songfd2018** [Bioconductor/Contributions#2106]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/songfd2018/BUSseq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by vjcitn** [comment]
I apologize for the delay in review of this package.  I am glad it is passing check nicely now.  There are in my view a number of improvements that should be considered.  First, there is no use of shared Bioconductor infrastructure in the package.  Thus the inputs are to be a list of matrices, whereas it would be typical to use SummarizedExperiment or SingleCellExperiment to manage the assay data (counts) along with relevant cell-level or experiment-level metadata.  I would strongly encourage adoption of this approach.  When we are using unannotated matrices as in the vignette, a risk arises that rows are shuffled independently of associated identifiers, and data become uninterpretable or misleading.

A second concern is acknowledgment of limitations.  The vignette includes the remark that "BUSseq is able to simultaneously correct batch effects, clusters cell types, and takes care of the count data nature, the overdispersion,
the dropout events, and the cell-specific sequencing depth of scRNA-seq data."  In what sense does it do all these things in a reliable way?  Is there a measure of accuracy of batch effect correction, and has BUSseq been shown to outperform, say, spike-in-based correction, and if so, under what conditions?  These topics may be addressed in your paper, and if so, please pass a few key findings to the user through the vignette.  Thanks for submitting your package and I hope this review is helpful!

**Comment by songfd2018** [comment]
Thanks a lot for your kind comments. I will try to allow the input of our algorithm as a SummarizedExperiment or SingleCellExperiment object and outline the advantages of BUSseq through the vignette.

**Comment by songfd2018** [comment]
Dear Reviewer,

I truly appreciate your precious and constructive comments. Please find our point-to-point response as follows.

>  First, there is no use of shared Bioconductor infrastructure in the package. Thus the inputs are to be a list of matrices, whereas it would be typical to use SummarizedExperiment or SingleCellExperiment to manage the assay data (counts) along with relevant cell-level or experiment-level metadata. I would strongly encourage adoption of this approach. When we are using unannotated matrices as in the vignette, a risk arises that rows are shuffled independently of associated identifiers, and data become uninterpretable or misleading.

For the first point, the revised package has allowed both a `SingleCellExperiment` object or a `list` as the input of the main MCMC algorithm function `BUSseq_MCMC`. Meanwhile, the output of `BUSseq_MCMC` is also a `SingleCellExperiment` object. Based on the input, `BUSseq_MCMC` incorporates a new assay of the imputed count data into the output object and adds the posterior inference as the package-specific metadata `int_metadata(sce)$BUSseq`, where `sce` is the name of the output. Furthermore, all the other functions are based on the `SingleCellExperiment` object generated by the `BUSseq_MCMC` function.

> A second concern is acknowledgment of limitations. The vignette includes the remark that "BUSseq is able to simultaneously correct batch effects, clusters cell types, and takes care of the count data nature, the overdispersion, the dropout events, and the cell-specific sequencing depth of scRNA-seq data." In what sense does it do all these things in a reliable way? 

In the vignette, I add a new section `Methodology` to show that the hierarchal structure of our BUSseq model mimics the data generation mechanism of scRNA-seq data. Meanwhile, diverse model parameters or latent variables can characterize the batch effects, cell type labels, overdispersion levels, and dropout event occurrence as well as cell-specific size factors. Moreover, in our paper, we mathematically prove that our model is identifiable up to the label switching under mild conditions. In other words, model parameters can be correctly recovered by the observed read count data, even if the observed data suffer from dropout events and batch effects. We further conduct simulation studies to verify our theoretical results. As a result, BUSseq can provide a one-stop service to do all these things simultaneously.

> Is there a measure of accuracy of batch effect correction, and has BUSseq been shown to outperform, say, spike-in-based correction, and if so, under what conditions? These topics may be addressed in your paper, and if so, please pass a few key findings to the user through the vignette. 

If we directly cluster all the cells from different scRNA-seq experiments, then cells are often separated by experiment or batch rather than by cell type due to severe batch effects. Therefore, in our paper, we clustered cells based on the corrected data or the learned low-dimension embeddings generated by different batch-effect-correction methods. To benchmark different methods, we compare the consistency between the reference cell-type labels and the estimated labels of each method. As a result, BUSseq outperforms six other state-of-the-art methods in both the mouse hematopoietic study and the human pancreatic study. To present our results, I add a new section `Performance of BUSseq in real data analysis` in the vignette. 

Thanks a lot again! Please kindly let me know if there is any issue in my package.

Best regards,
Fangda

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/songfd2018.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BUSseq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BUSseq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
