### ISSUE TITLE
scDD

### ISSUE THREAD

**Issue by kdkorthauer** [Bioconductor/Contributions#211]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kdkorthauer/scDD

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by kdkorthauer** [comment]
From the automated build, it looks like there is an error generated when ```texi2dvi``` is called.  While ```R CMD build``` completes without any errors or warnings on my system, I was able to verify that the command ```texi2dvi scDD.tex``` throws an error if I try to run it manually.  The first error message begins: 

>/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/hyperref.sty:4319: Package hyperref Error: Wrong driver option `pdftex', (hyperref) because pdfTeX in PDF mode is not detected.

I'm wondering if this could this be related to a known issue with knitr - from page 2 of the BiocStyle vignette (http://www.bioconductor.org/packages/3.3/bioc/vignettes/BiocStyle/inst/doc/LatexStyle.pdf) it says that non-breaking spaces may be converted to tildes, and when I run ```texi2dvi --pdf scDD.tex``` manually instead, the pdf is generated without error. 

Any comments or suggestions on how to remedy this issue would be greatly appreciated.

**Comment by vobencha** [comment]
Hi,
Thanks for the insight - you might be right and we will look into this. In the mean time you can ignore the error and I'll go ahead with the review. I'll have comments for you today or tomorrow.
Valerie

**Comment by vobencha** [comment]
What a nice package. Clean code, thorough documentation and informative vignette. A few suggestions and comments below.

1) R dependency
I'd add Depends: R (>= 3.3) to DESCRIPTION since you are using S4 classes from recent versions of Bioconductor (which is great, thanks!). This 'Depends' just prevents someone with a very old version of R/Bioconductor from trying to use the package and being confused if not all works as expected.

2) output
Instead of having scDD() return a named list have you looked at the SummarizedExperiment class in the SummarizedExperiment package? It has an assays() slot that is a list of matrices, data.frames, whatever you want. Very flexible. Also a colData() slot that is a data.frame that described the samples (columns) in assays() if that is relevant.

3) parallel and BiocParallel
BiocParallel builds on the parallel package so there should be no need to import both. BiocParallel automatically detects the OS and will create a cluster appropriate for windows, or linux-like platforms. Each of MulticoreParam(), SnowParam() etc. have their own function to detect the number of workers, e.g., on ?MulticoreParam man page you can see multicoreWorkers() called in the function signature to set the number of workers.

    Instead of passing 'n.cores' to scDD(), I would recommend passing param=bpparam() where the use can provide their own or one is automatically generated.

    When you've made the changes please bump the version to 0.99.1 and a new build will be triggered. Let me know if you have questions.

Valerie

**Comment by kdkorthauer** [comment]
Hi Valerie,

Thanks so much for the prompt response.  I really appreciate the feedback and suggestions.   I have addressed concerns 2 and 3 in full, but am unsure of how to address 1.  Please see below for details:

1.  R dependency
When I added Depends: R (>= 3.3) to DESCRIPTION, I got a WARNING from BiocCheck that said 
     >* WARNING: Update R version dependency from 3.3 to 3.4.
Is this a concern?  If not, I'll add it back in, bump the version, and push.

2.  output
Thanks for the pointer to the SummarizedExperiment class.  I agree that the format of the output could be better than a named list.  I decided it would also be an improvement if I switched from using the ExpressionSet class to using the SummarizedExperiment class, and housed the results within that object.  I have used the assays() slot to hold the expression counts, the colData() slot to hold the sample metadata information, and the metadata() slot to hold the list of results objects.  I also added handy accessor functions to extract the counts (```normExprs```) and results objects (```results```).  I think this new format is much simpler and easy to manipulate/subset.  I hope that you agree.

3. parallel and BiocParallel
Thanks for pointing out the redundancy of importing ```parallel```.  I have removed this and changed the ```scDD``` function to include a ```param``` argument with default ```bpparam()``` instead of passing in ```n.cores```.  A user can still pass in a ```MulticoreParam``` object that is created using a specified number of workers, so there is no loss of functionality.  Instructions to do so are included in the vignette and in the help file for the main ```scDD``` function.

I look forward to hearing your feedback on these changes.

Keegan

**Comment by vobencha** [comment]
Hi,
1) My mistake, we want Depends: R (>= 3.4). New packages should be developed against R devel which is 3.4.
2) Very nice. I like the new accessors.
3)  parallel
- BiocParallel does not use all cores by default. We found the greedy approach to be a problem and took a step back from that. Both multicoreWorkers() and snowWorkers() use `parallel::detectCores() - 2L`.
- MulticoreParam() only works on linux-like machines. If you force the use of MulticoreParam() windows users will always run in serial. The vignette says the 'param' arg in scDD() is MulticoreParam() by default but I don't see that; I see `param=bpparam()` which is the correct default. When on windows, bpparam() will return a SnowParam() not MulticoreParam(). So I would modify the text in the vignette to say something like "... an OS appropriate back-end using max cores - 2 is chosen automatically or the param and number of workers can be specified by the user .. ".

Valerie

**Comment by kdkorthauer** [comment]
Hi Valerie,

Thank you for the feedback and clarification regarding the parallel backend dependencies on OS.  I have addressed your comments in the latest push with the following changes:

* I added ```Depends: R (>= 3.4)``` to the DESCRIPTION
* In both the vignette and ```scDD``` function man page the following corrections were made: 
  1. I now indicate that BiocParallel uses max cores - 2 by default
  2. I clarify that the object returned by ```bpparam()``` is OS-dependent 

Thanks again for helping me improve the package!

Best,
Keegan

**Comment by vobencha** [comment]
Thanks for making the changes. I'm marking the package as approved. You should get an email in the next week with svn credentials (we have to request them) and instructions for next steps.
Thanks for contributing your work to Bioconductor.
Take care.
Valerie
