### ISSUE TITLE
svaNUMT

### ISSUE THREAD

**Issue by jackieduckie** [Bioconductor/Contributions#2114]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PapenfussLab/svaNUMT

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by jackieduckie** [comment]
Hi there, this is the resubmission of the open issue NUMTDetect. The changes of this submission include a new name for the package as well as comments from @LiNk-NY.

**Comment by lshep** [comment]
Please see initial review: 

**General**

- [ ] Please remove flake.lock and flake.nix from git respository. Only needed
  package files should be included in the git branch that is cloned from
  Bioconductor.

**inst/**

- [ ] Please include an inst/script direcory that describes how the files in
  `inst/extdata` were created. These scripts can be code, sudo-code, or text but
  should minimally contain the source information for the data and any
  preprocessing performed

- [ ] Where is all this data utilized?  In the vignette I see reference to
  `MT.vcf` and `gridss-na12878.vcf` in the tests.  Only provide data that is
  needed for the package vignette or examples.




**vignettes**

- [ ] Please change the name of the vignette to something identifable. We highly
  recommend having the same name of the package.  vignette with generic names
  (ie. vignettes.Rmd, intro.Rmd, etc.)  can often be used by multiple
  packages. Depending on the order of loading, a user may be directed to the
  correct vignette or a different package vignette. This actually occurs with
  your vignette if a user does not specify the package

```
> library(svaNUMT)
> vignette("vignettes")
starting httpd help server ... done
Warning message:
vignette 'vignettes' found more than once,
using the one found in '/home/shepherd/R-Libraries/4.1-Bioc3.14/StructuralVariantAnnotation/doc' 

```

- [ ] It seems like it might be useful to create some helper functions for
  extracting ranges from a given output of numtDecect and providing an overview
  of what is in the output.


Please consider the above review.  When ready please do a version bump to trigger a new build report and comment hear addressing the above concerns.  Thank you

**Comment by lshep** [comment]
We are closing your package do to inactivity.  Please comment back here when you are ready to proceed with the review process.

**Comment by jackieduckie** [comment]
Hi there,

My apologies for haven't been able to update the package. I'll be able to address the review comments by Friday this week. Could we reopen this issue? Thank you for your help.

**Comment by jackieduckie** [comment]
Hi @lshep ,

I've addressed your initial reviews in the lastest push. Regarding the last item, I've added a couple of examples in the vignette to demonstrate the structure and how to subset the function output, instead helper functions. Do you think that's enough?
Thank you and looking forward to hearing back.
 
> Please see initial review:
> 
> **General**
> 
> * [x]  Please remove flake.lock and flake.nix from git respository. Only needed
>   package files should be included in the git branch that is cloned from
>   Bioconductor.
> 
> **Description**
> 
> * [x]  Please add rmarkdown to Suggest field as it is used for your vignette.
> 
> **inst/**
> 
> * [x]  Please include an inst/script direcory that describes how the files in
>   `inst/extdata` were created. These scripts can be code, sudo-code, or text but
>   should minimally contain the source information for the data and any
>   preprocessing performed
> * [x]  Where is all this data utilized?  In the vignette I see reference to
>   `MT.vcf` and `gridss-na12878.vcf` in the tests.  Only provide data that is
>   needed for the package vignette or examples.
> 
> **vignettes**
> 
> * [x]  Please change the name of the vignette to something identifable. We highly
>   recommend having the same name of the package.  vignette with generic names
>   (ie. vignettes.Rmd, intro.Rmd, etc.)  can often be used by multiple
>   packages. Depending on the order of loading, a user may be directed to the
>   correct vignette or a different package vignette. This actually occurs with
>   your vignette if a user does not specify the package
> 
> ```
> > library(svaNUMT)
> > vignette("vignettes")
> starting httpd help server ... done
> Warning message:
> vignette 'vignettes' found more than once,
> using the one found in '/home/shepherd/R-Libraries/4.1-Bioc3.14/StructuralVariantAnnotation/doc' 
> ```
> 
>  * [ ]  It seems like it might be useful to create some helper functions for
>   extracting ranges from a given output of numtDecect and providing an overview
>   of what is in the output.
> 
> Please consider the above review. When ready please do a version bump to trigger a new build report and comment hear addressing the above concerns. Thank you

**Comment by lshep** [comment]
Yes. thank you for making the updates.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jackieduckie.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("svaNUMT")`. The package 'landing page' will be created at

https://bioconductor.org/packages/svaNUMT

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
