### ISSUE TITLE
rqt: utilities for gene-level meta-analysis

### ISSUE THREAD

**Issue by izhbannikov** [Bioconductor/Contributions#212]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/izhbannikov/rqt

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@LiNk-NY will review your package, but I note that the interface exposed by your package does not use the [SummarizedExperiment](https://bioconductor.org/packages/SummarizedExperiment) package / class as input. Please revise your package to do so. This level of standardization allows interoperation between different Bioconductor packages, and facilitates more robust and reproducible work flows by more tightly binding 'assay' data with sample descriptions.

**Comment by izhbannikov** [comment]
Hello,

New version 0.99.1 released. Now the package use an object SummarizedExperiment class as one of the input variables. 

Sincerely,

Ilya

**Comment by LiNk-NY** [comment]
Hi Ilya, @izhbannikov 
Thank you for submitting to Bioconductor. 

Please add the `importFrom` directive to your NAMESPACE file. 
More information below: 
```
Undefined global functions or variables:
  binomial cor glm logit na.exclude na.omit pchisq pgamma prcomp qbeta
  qchisq qgamma resid var vcov
Consider adding
  importFrom("stats", "binomial", "cor", "glm", "na.exclude", "na.omit",
             "pchisq", "pgamma", "prcomp", "qbeta", "qchisq", "qgamma",
             "resid", "var", "vcov")
to your NAMESPACE file.
```

I will be reviewing your package soon. 

Regards, 
Marcel

**Comment by izhbannikov** [comment]
Dear Marcel, @LiNk-NY 

Thank you for your comment. 
I fixed that issue by adding `importFrom` with appropriate arguments  to the NAMESPACE file. Now the message 
```
Undefined global functions or variables:
  binomial cor glm logit na.exclude na.omit pchisq pgamma prcomp qbeta
  qchisq qgamma resid var vcov
Consider adding
  importFrom("stats", "binomial", "cor", "glm", "na.exclude", "na.omit",
             "pchisq", "pgamma", "prcomp", "qbeta", "qchisq", "qgamma",
             "resid", "var", "vcov")
to your NAMESPACE file.
```
is disappeared from the checking process log.

Sincerely,
Ilya

**Comment by LiNk-NY** [comment]
Hi @izhbannikov, 
Thanks for making those changes. If you have made any subsequent changes, please bump the version to kick off another build. I will be reviewing your package shortly. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @izhbannikov,
Thank you for submitting to Bioconductor!
Please see your review below. 

---

Thank you for making the change to use the
`SummarizedExperiment` class as a basis for your
class.
 
### Grammar

* Use default values in the arguments (e.g., in the constructor)
* Not sure why you need to create an object in `baseenv` from `rQTtest.prepare`. It doesn't look like a good idea to me. Perhaps @mtmorgan has some additional input on this, see [R/general.R:24](https://github.com/izhbannikov/rqt/blob/master/R/general.R#L24). 
* No need to define functions within functions such as `ridge_se`
* Avoid repetitive coding (use conditional statement only for code that
changes see `preprocess.*` functions)
* Avoid a long series of `if` / `else` statements, use `switch` or a lookup table
* Use `warning` function instead of `cat`
* Avoid liberal use of the `try` function, your code should be predictable
(not including iterative methods)

### Usability - Readability

* Avoid the use of `@`. Use accessor functions to access elements in your class
* Please use descriptive arguments, single letter arguments are not helpful for
the end user. 
* Use camelCase format for your exported function names (no `_` or `.`)
* Remove any `.DS_Store` files from your repository
(add to .gitignore/.Rbuildignore)
* Your package dependencies should be minimal. Only include packages which you
are building on top of. Most likely all should be moved to the `Imports` field.
* Growing a vector (`c()` then `c(object, object)`) should be avoided,
pre-allocate the space and then fill in the spaces

 
### Minor

* Don't use `if (condition == TRUE)` anything inside the `if` is evaluated to
logical; `if (condition)` should suffice. 
* No need to switch from logical to index evaluation. For example,
`coef[which(coef != 0)]` can just be `coef[coef != 0L]
* Avoid argument names that are also functions (e.g., scale)
* Avoid the use of `1:length(object)`
* Stick to using `res[["fit"]]` rather than the less robust `res$fit`
* Avoid the use of semicolon in the code `;`
* Your classes file should have a proper name. If you need to rearrange the file order,
you can do that with the collage field generated by `roxygen` with `@include filename.R`

**Comment by izhbannikov** [comment]
Hi Marcel, @LiNk-NY ,

Thank you so much for your review! 
I will fix the package asap.

Sincerely,
Ilya

**Comment by izhbannikov** [comment]
Dear Marcel, @LiNk-NY ,

Thank you for your review. 
I made changes following your comments. Please see below:

## Grammar

- Use default values in the arguments (e.g., in the constructor)</span>
@izhbannikov: Done; now using default values of arguments.

- Not sure why you need to create an object in baseenv from rQTtest.prepare. 
It doesn't look like a good idea to me. Perhaps @mtmorgan has some additional input on this, see R/general.R:24.
@izhbannikov: Done; such discrepancy was removed.

- No need to define functions within functions such as ridge_se
@izhbannikov: Done;

- Avoid repetitive coding (use conditional statement only for code that
changes see preprocess.* functions)
@izhbannikov: Done; the code was rewritten.

- Avoid a long series of if / else statements, use switch or a lookup table
@izhbannikov: Fixed; now using 'switch'.

- Use warning function instead of cat
@izhbannikov: Done; now using warning function

- Avoid liberal use of the try function, your code should be predictable
(not including iterative methods)
@izhbannikov: Done; the code was rewritten.


## Usability - Readability

- Avoid the use of @. Use accessor functions to access elements in your class
@izhbannikov: Done; now using accessor functions.

- Please use descriptive arguments, single letter arguments are not helpful for
the end user.
@izhbannikov: Done; (at least for exported functions) the code was rewritten.

- Use camelCase format for your exported function names (no _ or .)
@izhbannikov: Done; now using camelCase format for exported functions.

- Remove any .DS_Store files from your repository (add to .gitignore/.Rbuildignore)
@izhbannikov: Done; .DS_Store, .Rhistory files were removed and added to .gitignore.

- Your package dependencies should be minimal. Only include packages which you
are building on top of. Most likely all should be moved to the Imports field.
@izhbannikov: Done; only SummarizedExperiment and R(>=3.4) are left in dependencies section.

- Growing a vector (c() then c(object, object)) should be avoided,
pre-allocate the space and then fill in the spaces
@izhbannikov: Done; not using a growing vector any more.


## Minor

- Don't use if (condition == TRUE) anything inside the if is evaluated to
logical; if (condition) should suffice.
@izhbannikov: Done; now using only 'if (condition).'

- No need to switch from logical to index evaluation. For example, # my comment: coef fixed but other may exist
coef[which(coef != 0)] can just be `coef[coef != 0L]
@izhbannikov: Done; now using only 'coef[coef != 0L].'

- Avoid argument names that are also functions (e.g., scale) my comment: scale is fixed but perhaps other cases exist
@izhbannikov: Done; not using arguments that look like a function name.

- Avoid the use of 1:length(object)
@izhbannikov: Done; the code was rewritten.

- Stick to using res[["fit"]] rather than the less robust res$fit
@izhbannikov: Done; now using res[["fit"]] - like expressions only.

- Avoid the use of semicolon in the code ;
@izhbannikov: Done; not using semicolon any more.

- Your classes file should have a proper name. If you need to rearrange the file order,
you can do that with the collage field generated by roxygen with @include filename.R
@izhbannikov: Hopefully it is fixed.

- Update: Please add unit tests to your package for robust and bug-free code. Also, please see the goodpractice package for additional minor points at MangoTheCat/goodpractice and running gp("rqt").
@izhbannikov: Done: I added tests and checked the code with gp('rqt').


Please take a look at this and let me know if any changes needs to be made. Thank you!

Sincerely,
Ilya

**Comment by LiNk-NY** [comment]
Hi @izhbannikov, 
Thanks for making those changes. 

* Can you explain why you need `rqt-internal.R`? 
* Please use `setReplaceMethod` instead of `results<-`. It's semantically more meaningful. 
* Do you need both a `show` and a `print` method? It seems to me like just creating a `show` method would suffice. 
* What I meant when I told you to use switch would be only for the functions and not the entire expression (i.e., `sump` vs `sump(pv)$p`) but it's a minor point. 

Regards, 
Marcel

**Comment by izhbannikov** [comment]
Hi Marcel, @LiNk-NY,
Thanks for reviewing my package.

I made some changes according to your comments and released a new version. Please see my comments below.

- Can you explain why you need rqt-internal.R?
@izhbannikov: rqt-internal.R removed now. I just forgot to delete it. Thanks for pointing on this.

- Please use setReplaceMethod instead of results<-. It's semantically more meaningful.
@izhbannikov: Done. Now I use setReplaceMethod for "results<-". Thanks. 

- Do you need both a show and a print method? It seems to me like just creating a show method would suffice.
@izhbannikov: Done, "print" method removed.

- What I meant when I told you to use switch would be only for the functions and not the entire expression (i.e., sump vs sump(pv)$p) but it's a minor point.
@izhbannikov: Oh, I see, thanks. Made some code refactoring and hope it looks alright now.
I am happy to make any further changes that may be required.

Sincerely,
Ilya

**Comment by LiNk-NY** [comment]
Hi Ilya @izhbannikov, 
Thanks for making those changes. The package is looking good!
There are a few things. 

* Please rename the construction function according to the class name. `rqtClass` > `rqt`
* Move the constructor and class functions to the `rqt.R` file. 
* Move method functions to `rqt-methods.R` file. You don't have to have `rqt` in the method name (`rQTest`). You can call it something like `geneTest`. 

Regards,
Marcel

**Comment by izhbannikov** [comment]
Hi Marcel, @LiNk-NY,

Thanks for reviewing my package and useful suggestions! I made some changes, according  to your comments, please see my explanations below:

*Please rename the construction function according to the class name. rqtClass > rqt
*Move the constructor and class functions to the rqt.R file.
@izhbannikov: Done. Actually, I renamed rqt.R to rqt-classes.R. I also moved all generics to rqt-generics.R. Hopefully this will make the code more readable.

*Move method functions to rqt-methods.R file. You don't have to have rqt in the method name (rQTest). You can call it something like geneTest.
@izhbannikov: Done. Functions rQTest and rQTestMeta were renamed to geneTest and geneTestMeta.

I will be happy to make any changes if necessary. Thanks!

Sincerely,
Ilya

**Comment by LiNk-NY** [comment]
Hi @izhbannikov, 
The package is looking better! You may combine `general.R` with `preprocess.R` in order to reduce the number of files but they all look well organized and easier to read! 

Your package has been accepted. 

Thank you for submitting to Bioconductor!

Regards,
Marcel

**Comment by izhbannikov** [comment]
Hi Marcel, @LiNk-NY,

Thank you so much for accepting our package. It was a pleasure to collaborate with you!
I merged general.R and preprocess.R. 

Sincerely,
Ilya

**Comment by sariya** [comment]
hi @izhbannikov sorry to bump this old thread. I'm on R (3.5), when I try to install this tool using bioclite I run into error to install glmnet, which isn't available for R3.5. 
Any clue how to bypass this?
