### ISSUE TITLE
swfdr

### ISSUE THREAD

**Issue by SiminaB** [Bioconductor/Contributions#213]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/leekgroup/swfdr

Confirm the following by editing each check box to '[x]'

- [X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ ]X The 'devel' branch for new packages and features.
- [ X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by SiminaB** [comment]
Hi Herve,
It looks like the ERROR issue with the MAC build on oaxaca is common to other folks as well, for example here http://bioconductor.org/spb_reports/ChIPexoQual_buildreport_20161207193202.html https://github.com/Bioconductor/Contributions/issues/79
I have a Windows machine and I cannot reproduce the error - it looks like pdflatex is just not installed on oaxaca though.

Thanks so much!
Best,
Simina

**Comment by mtmorgan** [comment]
I'm really sorry for the delay in getting this review to you. The package looks in great shape, and I have only one suggestion

- include the script for generating journals_pVals.Rd as a script,
  inst/script/getPvalues.R instead of referencing a github url.

Please respond and if you change your package include a version bump, and I'll be happy to accept the revision.

**Comment by SiminaB** [comment]
Thank you so much @mtmorgan ! I just made the change you suggested.

**Comment by mtmorgan** [comment]
Great, I've marked your package as accepted. It will be added to the Bioconductor SVN repository and additional information forwarded over the next couple of days.
