### ISSUE TITLE
(inactive) FEVV: An R package for Functional Enrichment of Genomic Variants and Variations

### ISSUE THREAD

**Issue by isarnassiri** [Bioconductor/Contributions#2137]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/isarnassiri/FEVV

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by nturaga** [comment]
Hi,

You already have an email, `isar.nassiri@oncology.ox.ac.uk` registered with Bioconductor. Please use the same email in your DESCRIPTION file for this package.

Nitesh

**Comment by isarnassiri** [comment]
Hello Nitesh,

Thank you for your consideration.

Done.

Best,
Isar
________________________________

**Comment by isarnassiri** [comment]
Hello Nitesh,

I Pushed changes to the Bioconductor and GitHub repositories, including a version bump.

I have not received an updated build report. Can you please guide me in this regard?

Best regards,
Isar
________________________________

**Comment by nturaga** [comment]
Hi,

Did you update the version number?

**Comment by isarnassiri** [comment]
Hello Nitesh,

Thank you for your email.

Yes; in the description file, the version number is 0.99.2 (https://github.com/isarnassiri/FEVV/blob/main/DESCRIPTION).

Best,
Isar

________________________________

**Comment by nturaga** [comment]
Please bump it again and try.

**Comment by isarnassiri** [comment]
Hello Nitesh,

Thank you for your email.

Excuse me, I use the following script which works:
cd ~/FEVV_package/
git remote rm origin
git remote add origin ***@***.***:isarnassiri/FEVV
git remote rm upstream
git remote add upstream ***@***.***:packages/FEVV
git remote -v
git fetch --all
git merge upstream/master
git merge origin/main
git add FEVV/DESCRIPTION
git add FEVV/R/FEVV.R
git commit -m "Fixed conflicts in version change"
git push upstream master

but the updated build report is based on the old scripts [the build is not based on updated files]. Can you please guide me?

Best regards,
Isar
________________________________

**Comment by nturaga** [comment]
# FEVV

## build

ok

## install

ok

## DESCRIPTION

- The order of the fields in the DESCRIPTION file is
  non-standard. 
  
## NAMESPACE

ok

## R

- The way helper functions within functions are being used doesn't add
  any additional benefit, especially the way things are right now.
  
  Please just make them explicit (e.g: `zScore()`). Tag them
  `@internal` and rename these internal functions (that are not
  exported as `.zScore()`)
  
- Do not use `1:length()`, please check your build report. Use
  seq_len() instead. Issue a new build report by bumping the branch,
  and please make sure the build report is as clean as possible. I
  will check after you make the revisions.
  
- Use the appropriate end-user messages, 

End-User messages

message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.
warning() communicates unusual situations handled by your code.
stop() indicates an error condition.
cat() or print() are used only when displaying an object to the user, e.g., in a show method.

- Why is this option even given if it's not implemented yet, 

```
      stop("type ", type, " is not yet implemented")
```

- There is a misuse of `which()` across the code base, when you use
  `grepl()` (it gives you a logical) and you are converting it to a
  index with the `which()`. Just use `grep()`instead.
  
  There are other cases where the usage of `which` is not
  required. Please chek them all. You don't need the index in some
  places.
  
- Please try to follow,
  http://bioconductor.org/developers/how-to/coding-style/ as closely
  as possible. Use 4 spaces to indent. 2 spaces is very hard to read
  for the reviewers, it is not the standard practice.
  
- Do not use `sapply()` anywhere. Use `vapply()` instead. Look up
  http://bioconductor.org/developers/how-to/efficient-code/
  
  
- Remove commented out code.


## vignette

- Use `BiocStyle`package

- The vignette needs to be more elaborate

**Comment by nturaga** [comment]
Hi,

Just checking to see if you've received my review. We have a 21-day policy to check in with authors to see if they are still working on the package, or it gets stagnant in our pipeline of package reviews.

Best,

Nitesh
