### ISSUE TITLE
DelayedTensor

### ISSUE THREAD

**Issue by kokitsuyuzaki** [Bioconductor/Contributions#2143]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rikenbit/DelayedTensor

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by kokitsuyuzaki** [comment]
@LiNk-NY  I cannot remove the following error nor reproduce it in my environment.
Isn't it necessary to add `--resave-data` as an option of `R CMD build` of Single Package Builder?

```
* checking data for ASCII and uncompressed saves ... WARNING
  
  Note: significantly better compression could be obtained
        by using R CMD build --resave-data
                      old_size new_size compress
  human_mid_brain.rda    677Kb    440Kb       xz
  mouse_mid_brain.rda    761Kb    510Kb       xz
```

Should I ignore this WARNING, as in the following example?
https://github.com/Bioconductor/Contributions/issues/1453#issuecomment-608586524

**Comment by LiNk-NY** [comment]
Hi Koki, @kokitsuyuzaki 

Thanks for linking to that comment. Yes, you can ignore the warning. 
I am currently reviewing the package and will post the review shortly. 

Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi Koki, @kokitsuyuzaki 

Thank you for the submission. 
Please see the review below.

Best regards,
Marcel

---

# DelayedTensor #2143

## DESCRIPTION

* Please add a `BugReports` field and URL pointing to the GitHub repository.
* (minor) Consider wrapping the text in the `Description` field.
* I'm not sure why you need to import `BiocStyle` and `knitr`?

## NAMESPACE

* Looks good.
* Perhaps you should use a more descriptive name for the `vec` function.
* It seems that `fold` and `unfold` should be methods with an argument input
that will differentiate the ones you have listed in the `NAMESPACE`.

## vignettes

* The `BiocStyle` vignette states that you should add `BiocStyle` and `knitr`
to the `Suggests` field in the `DESCRIPTION`.
* The introductory vignette looks good. Consider using a spellchecker to find
some typos and spelling errors.
* In vignette 2, perhaps consider combining the functionality of `k_*`, `rs_*`,
and `cs_*`.
* The vignettes look comprehensive and easy to follow.

## R

* The code looks good overall.
* It looks like you can combine `k_*`, `rs_*`, and related functions
but it may be more convenient to the user to keep them as-is.
* It looks like `vec` is doing more than just coercing to a `vector`. Consider
using a more descriptive name.

## tests

* Looks good.

**Comment by kokitsuyuzaki** [comment]
Hi, Marcel @LiNk-NY 

Thank you for your comprehensive review.

# DESCRIPTION
> Please add a BugReports field and URL pointing to the GitHub repository.

I added the BugReports field to specify the issue page of rikenbit/DelayedArray repository.

> (minor) Consider wrapping the text in the Description field.

I wrapped the Description field.

> I'm not sure why you need to import BiocStyle and knitr?

I moved BiocStyle and knitr to Suggest field.
`BiocStyle` and `knitr` were removed from NAMESPACE file.

# NAMESPACE
> Perhaps you should use a more descriptive name for the vec function.
> It seems that fold and unfold should be methods with an argument input that will differentiate the ones you have listed in the NAMESPACE.

As described in the vignette 1,
`DelayedTensor` is an re-implementation of `rTensor` package to run it in a out-of-core manner based on `DelayedArray`.
https://cran.r-project.org/web/packages/rTensor/index.html
This is because `rTensor` is based on the R standard array object, which is a on-memory object and not scalable.

Therefore, I would like to set all the function names except `einsum` with those of `rTensor` so that `rTensor` users can immediately switch to `DelayedTensor`.
For the above reason, I would like to keep function names such as `vec`, `fold`, and `unfold`.

# vignettes
> The BiocStyle vignette states that you should add BiocStyle and knitr to the Suggests field in the DESCRIPTION.

I moved `BiocStyle` and `knitr` to Suggest field.

> The introductory vignette looks good. Consider using a spellchecker to find some typos and spelling errors.

Thanks for letting me know.
I have corrected the typos in Grammarly.

>  In vignette 2, perhaps consider combining the functionality of k_*, rs_*,
and cs_*.

For the above reason, I want to use `k_*`, `rs_*`, and `cs_*` as they are because they are all function names of `rTensor`.

# R
> It looks like you can combine k_*, rs_*, and related functions but it may be more convenient to the user to keep them as-is.
> It looks like vec is doing more than just coercing to a vector. Consider
using a more descriptive name.

For the above reason, I want to use `k_*`, `rs_*`, and `vec` as they are because they are all function names of `rTensor`.


Koki

**Comment by LiNk-NY** [comment]
Hi Koki, @kokitsuyuzaki 

Thanks for making those changes and providing the additional information. 

Before acceptance, please remove `.html` files from the `vignettes` directory.
These are superfluous and should not be in the package source code.

Best regards,
Marcel

**Comment by kokitsuyuzaki** [comment]
Thanks, @LiNk-NY 

Now I removed the `*.html` files from the `vignette` directory.

Koki

**Comment by LiNk-NY** [comment]
Hi Koki,
Thank you for removing those files. Your package has been accepted. 
Best regards,
Marcel

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kokitsuyuzaki.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DelayedTensor")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DelayedTensor

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
