### ISSUE TITLE
MetaGSCA

### ISSUE THREAD

**Issue by hui-sheen** [Bioconductor/Contributions#2148]
Dear Bioconductor team,

Our R package MetaGSCA got published lately in PLoS Computational Biology (10.1371/journal.pcbi.1008976). Please note that we used to submit MetaGSCA to Bioconductor in last fall (issue #1568). Now the source code has been fundamentally re-written and thus significantly optimized. It has also been shifted under a different maintainer account. So this is a brand new submission, but I'm referring to the historical submission for your reference.

Thanks,
Hui Yu
#########################################################
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hui-sheen/MetaGSCA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by hui-sheen** [comment]
Dear reviewers, 
I see there are warnings and errors on my build report. However, many (if not all) errors are not relevant to the current version of MetaGSCA. For instance, "merida1 CHECK output" reports "ERROR: System Files found that should not be git tracked: MetaGSCA.Rproj" and "Do not use Author/Maintainer fields. Use Authors@R." The current MetaGSCA package (https://github.com/hui-sheen/MetaGSCA) does not have these problems. This package was submitted in last fall by Haocan223 and these issues might be existent with that version. There have been a major systematic re-writing of the code files, and the package has been owned by me instead of Haocan223. I wish you could delete the old MetaGSCA package from your build system and test the package from scratch.
Meanwhile, I'll read the what to expect and related documents to better communicate with you. Thank you very much!

Hui

**Comment by hui-sheen** [comment]
Dear reviewers,
I made a few minor fixes to the repo MetaGSCA and bumped the version to 0.99.1. I successfully pushed the commit including version bump to github.com, but I couldn't push it to the repo on bioconductor.org. I got the following error. Please advise what I should do. Thanks!
 
git push upstream master --force
...
remote: FATAL: + refs/heads/master packages/MetaGSCA hui-sheen DENIED by fallthru
remote: error: hook declined to update refs/heads/master
To git@git.bioconductor.org:packages/MetaGSCA.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/MetaGSCA.git'

**Comment by lshep** [comment]
We apologize for the delay. We needed to change the remotes and references we had internally to be able to point to the correct version of the package. You should have access now and the builds should pick up on the correct version. You will need to activate your Git Credentials Account and then you should be able to trigger a new build by doing a version bump and pushing to git.bioconductor.org. Cheers

**Comment by lshep** [comment]
@hui-sheen  Could you please activate your credentials account and push the changes/including version bump to the git.bioconductor.org version to initiate a new build report.  Thanks

**Comment by hui-sheen** [comment]
@Ishep Thank you very much for relinking the software to the current correct version. I executed the following command on my local work directory yesterday, and it seemed successful with no obvious warning or error message. When I executed the same command about ten days ago, I did encounter an evident error message (see above). I guess I have passed the step of credentials and pushing the version to Github? Can you confirm with me that a new build report will be soon generated?
# Command I executed with possible success
git push upstream master --force
I did read the tutorial on Bioconductor contributor credentials (SSH key) and I possibly have passed that step. Please let me know which part I am missing if you cannot proceed with the review process. Thanks!

**Comment by lshep** [comment]
Bioconductor does not allow `--force` option.  Please do `git push upstream master` to push changes.  If you still encounter errors please show the command with the full output.

**Comment by hui-sheen** [comment]
@lshep Below is what I got after executing the command without --force. I guess I'm good for now. I'm looking forward to a new build report for MetaGSCA v0.99.1. Thanks!
$ git push upstream master
Enter passphrase for key '/home/huiyu1/.ssh/id_ed25519':
Everything up-to-date

**Comment by lshep** [comment]
The build report did not trigger correctly.  Could you please do a version bump to 0.99.2 and try pushing to git.bioconductor.org to trigger a build.

**Comment by lshep** [comment]
Please fix all error warning and notes in the build report before an indepth review will continue.  thank you

**Comment by hpages** [comment]
Hi @hui-sheen ,

Please address the `R CMD check` error and warnings reported by the SPB (Single Package Builder). Thanks!

Best,
H.

**Comment by hui-sheen** [comment]
@hpages,
I ran R CMD check locally with the following command, and found no error with v0.99.4. I shut PDF/vignettes check, because we did not attempt to build a PDF vignette. Instead, we generated an HTML tutorial (https://hui-sheen.github.io/MetaGSCA/) using an Rmd script independently. The *.Rmd script was not included in the package v0.99.4.

R CMD check MetaGSCA_0.99.4.tar.gz --no-manual

**Comment by hpages** [comment]
@hui-sheen ,

It's a Bioconductor requirement that your package contain a valid vignette and man pages that can be built and checked with the standard `R CMD build` and `R CMD check` commands. Thanks!

H.

**Comment by hpages** [comment]
@hui-sheen `R CMD check` is still reporting an error on the 3 platforms. We don't start the review process until the package passes `R CMD check` cleanly, at least on Linux. Thanks!

**Comment by hui-sheen** [comment]
@hpages I don't have sufficient manpower to settle the R CMD check ERRORs. I have to close the submission issue. Thank you very much!
