### ISSUE TITLE
VariantToolsData

### ISSUE THREAD

**Issue by lawremi** [Bioconductor/Contributions#215]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lawremi/VariantToolsData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Please note: the tokay2 ERROR is on our end and we are working to remedy; you can ignore this ERROR for now. Please fix other WARNINGS/ERROR for the other build nodes (malbec2/oaxaca) and then I will formally review the package for other Bioconductor best practices and guidelines.

**Comment by lawremi** [comment]
I pushed a fix to a couple of the warnings. One of the warnings, about the missing `\value{}` section, is invalid, and I fixed it in BiocCheck yesterday. Data man pages (`\docType{data}`) should not need `\value{}` even though the can have `\usage{}`. 

I disagree about the R >= 3.4 version requirement. The R version requirement is intrinsic to the code in the package. We want to be able to tell which package actually depends on some specific R version. It's fine to require a certain version of R for a certain version of Bioconductor, because all of the testing has happened for that version, and we want consistency in general. But that validation is at a different level than version dependency of any specific package. It's more about the blessing on the build artifact than the codebase itself. What about supporting an R version dependency in Suggests? R would warn if the version is lower. Gabe points out that the same could be done for any package in Suggests, upon call to `requireNamespace()`.

**Comment by lshep** [comment]
Thank you for your comments.  I will suggest the change to BiocCheck regarding the version dependency and for now will ignore.  My only suggestion would be to add BiocStyle to the Suggests of the DESCRIPTION to eliminate the R CMD check NOTE.  I will mark the package as accepted:  @mtmorgan please be advised this is an experimental data package.
