### ISSUE TITLE
denyranges

### ISSUE THREAD

**Issue by mdozmorov** [Bioconductor/Contributions#2152]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mdozmorov/denyranges

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by mdozmorov** [comment]
```
* checking for unstated dependencies in examples ... WARNING
no parsed files found
```
This warning appeared in another data package. I used a workaround to create a dummy function, but it was unacceptable. Not sure is this warning is critical, or how to address it.

**Comment by mdozmorov** [comment]
The vignette and readme have been updated to use the data from AnnotationHub.

**Comment by lshep** [comment]
Sorry for the delay we will have a review for you in the next few days.

**Comment by lshep** [comment]
Please see review: 

**R CMD BUILD**                                                                                       
                                                                                                      
- [ ] The following error message occurs:                                                                                             

```                                                                                                   
The 'markdown' package should be installed and declared as a dependency of the 'denyranges' package (\
e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the\
 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.      
```                                                                                                   
         
**R CMD check**                                                                                       
                                                                                                      
- [ ] When I run locally, I get the following NOTE?                                                   
                                                                                                      
```                                                                                                   
* checking for unstated dependencies in vignettes ... NOTE                                            
'library' or 'require' call not declared from: ‘GenomicRanges’                                        
                                                                                                      
```                                                                                                   

**README**

- [ ] Please change installation instructions to Bioconductor instead of github
  repository


**man**

- [ ] You might consider adding at least a package level man page if someone
  does `?denyranges`

**Vignette**

- [ ] Change installation to just package and not github repo.

- [ ] Your vignette shows downloading from google drive. This is not allowed.
  Please update to only show access to the data through the AnnotationHub. We do
  not allow data to be stored and downloaded from private drives.

Please make changes and push a new version to git.bioconductor.org to trigger a new build report.  When ready please request a re-review

**Comment by lshep** [comment]
Just checking in to see if you were going to submit changes soon?

**Comment by mdozmorov** [comment]
Sorry, meant to follow up. I would withdraw the package as it still raises some concerns. I'm planning to redo it, but it will have a different name and content. It won't be fast with the impending Fall teaching, so best is to close this submission. Not sure what's the process.

**Comment by lshep** [comment]
Thanks for the update.  We can close the issue.   I will also remove the resources from the annotationhub
