### ISSUE TITLE
crisprScoreData

### ISSUE THREAD

**Issue by Jfortin1** [Bioconductor/Contributions#2155]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Jfortin1/crisprScoreData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by Jfortin1** [comment]
@Kayla-Morrell Thank you for reviewing this packages. I have a question re.  `   ERROR: License 'CC BY-NC-ND 4.0 + file LICENSE' restricts use`.

This license was the one decided by our legal team at Genentech; is that license strictly prohibited by Bioconductor?

**Comment by Kayla-Morrell** [comment]
@Jfortin1 - I see that this issue was also raised on your other contribution and I feel I must follow the comment of my colleague. As stated [here](https://github.com/Bioconductor/Contributions/issues/2157#issuecomment-873133456), please use a more permissive (non-restrictive) license. I will keep my eye on the issue and if a resolution is reached it will apply to this package as well.

Best,
Kayla

**Comment by Jfortin1** [comment]
@Kayla-Morrell Thanks Kayla, I'm currently working with our legal team to choose a different license.

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe @Jfortin1 
Any updates on this? We can close the issue until you hear back from the legal team.
Best,
Marcel

**Comment by Jfortin1** [comment]
@LiNk-NY Thank you for your patience; the team agreed for a MIT license (just pushed the latest changes).

**Comment by Jfortin1** [comment]
@LiNk-NY Hi Marcel, the package is now building without errors/warnings. Also, `crisprScore` is having an error because it depends on `crisprScoreData`.

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 

Please see the review below. Feel free to ask any questions.
Please indicate `crisprScore` as an additional package in this issue. See for details
https://github.com/Bioconductor/Contributions#submitting-related-packages

Best,
Marcel

---

# crisprScoreData #2155

## DESCRIPTION

* You don't need to import `ExperimentHubData`.
* Suggest your own `crisprScore` package.
* Add `BugReports` and `URL` fields.

## NAMESPACE

* Remove the `ExperimentHubData` dependency.

# crisprScore #2157

## DESCRIPTION

* Suggest your own `crisprScoreData` package.
* Add `BugReports` and `URL` fields.
* Remove `LazyData` field

## NAMESPACE

* Looks good.

## vignettes/

* Looks good.

## R

* Code looks good.
* Remove stale code `R/basilisk2.R`
* If possible, avoid using numeric indices e.g., `scores[, c(1,4,5,6)]` and
use more robust `colnames`.
* It looks like some functions are not supported on Windows. This should be
noted in the `Description` field.

## tests/

* Looks good.

**Comment by Jfortin1** [comment]
AdditionalPackage: https://github.com/Jfortin1/crisprScore

**Comment by Jfortin1** [comment]
@LiNk-NY Hi Marcel, I'm still getting a dependency error (```* checking package dependencies ... ERROR
Package suggested but not available: crisprScore```) after adding `crisprScore` as an additional package, and bumping the version of `crisprScoreData`.

**Comment by LiNk-NY** [comment]
Hi @Jfortin1 
Can you try bumping the version of `crisprScore`? 
Thanks!
-Marcel

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 
It looks like the package is timing out on some platforms. 
Please reduce the vignette and examples to less than 14 minutes. 
You can take a subset of the data and speed up the vignette. 
Best, 
Marcel

**Comment by Jfortin1** [comment]
Hi Marce @LiNk-NY,

The reason why it takes so much time is that each scoring function requires to build a conda environment (and download all conda packages first) using Aaron's [basilisk](http://www.bioconductor.org/packages/release/bioc/html/basilisk.html) package when it's called for the first time, and that takes a few minutes for each scoring method. 

The only way to circumvent the time limit would be to basically not run any of the scoring methods in the vignette/examples. What are your thoughts?

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 

After internal discussion, the vignette should realistically narrate typical tasks of the package and it should not use significant CPU time to do this. You may have to simplify / remove the scoring method to adhere to the 14 minute time limit. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @Jfortin1 
I am getting a couple of issues testing the functions locally. 

1) When running the example for `getDeepCpf1Scores` :
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Pyth
ython 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More
s about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release
s/#python-2-support
```
2) When running the `getDeepHFScores` example: 
```r
>  results <- getDeepHFScores(input)
see ?crisprScoreData and browseVignettes('crisprScoreData') for documentation
loading from cache
sh: 5: /home/mr148/.cache/R/basilisk/1.5.0/crisprScore/0.99.5/deephf_basilisk/etc/conda/activate.d
/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
```

Should these functions share an environment? It seems like they are separately installing python env with their respective dependencies. I don't really understand how basilisk works. 

Best,
Marcel

**Comment by Jfortin1** [comment]
Hi Marcel @LiNk-NY,

A bit of background: `basilisk` allows to use python packages that require different (and potentially conflicting) environments within the same R session. The 5 scoring methods in our package cannot work in the same python environment for 2 reasons: (1) two of the packages were written in python 2.7 and were not further ported over to python 3 by the original authors; and (2) the three remaining packages written in python 3.6 conflict with each other. For instance, we use some of the deep learning models pre-trained provided by the authors of the scoring methods, and they rely on different versions of tensorflow, therefore the need to isolate the packages from each other. `reticulate` does not allow that: one can only use one python environment during one R session; to use another environment, a user would have to quit the session and restart. `basilisk` is a real tour de force to allow that. 

It comes with the cost that 5 conda environments need to be created for our package, but that happens only when users call the function for the first time. 

This is a bit problematic for the BioC R CMD check time limit. The vignette actually builds fine, the problem comes from the `examples`. To circumvent that, I've changed `\donttest` to `\dontrun` to avoid to download the conda environments. But that means most functions in the package have no runnable examples, and that makes R CMD check fails. 

Any suggestions about how we can work around that?

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 

Hervé was kind enough to test `R CMD check crisprScore_0.99.3.tar.gz` on his laptop and it took 1 hour the first time. The second time around, it took 45 minutes. I don't think this length of time is acceptable. There should be more caching going on, if possible. 

The examples should illustrate realistic use of the function and not take so much time. 
Given that you're building python environments, they will necessarily take a long time. 

Personally, I'm less inclined to support software that is not ported from python 2.7 to 3.x.

cc: @vjcitn 

Best regards,
Marcel

**Comment by Jfortin1** [comment]
Hi Marcel @LiNk-NY, 

(Just got back from a 3 week vacation, sorry for the delay).
 
Thanks to Hervé who helped testing the package.
The R CMD check on the latest version of crisprScore (0.99.7) now took very little time (2m39s on my laptop).

Re. your comment *Personally, I'm less inclined to support software that is not ported from python 2.7 to 3.x*:
Ideally we would also like the original authors for each of the prediction algorithm to have ported their code / trained models to Python 3. The fact that we are using frozen python 2 environments identical to the respective published algorithms (via basilisk) at least ensures that our results are reproducible, and that they agree with the published algorithm.

**Comment by LiNk-NY** [comment]
Can you kick off another build of the package? 
Thank you.
-Marcel

**Comment by Jfortin1** [comment]
Hi Marcel @LiNk-NY, 

Current (expected) error from BiocCheck for `crisprScore=0.99.8`:

`* Checking man page documentation...
    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples. The following pages do not:
      getAzimuthScores.Rd, getDeepCpf1Scores.Rd, getDeepHFScores.Rd,
  getEnPAMGBScores.Rd, getLindelScores.Rd`

Given that adding runnable examples (even the most minimal examples) will necessarily trigger building the conda envs, which will exceed the 12m, how could we circumvent that error?

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 

I don't think there is an easy way to circumvent building the conda environments. 
We want the code to be testable and not running the code can cause a lot of problems
for users if the code is not tested. 
I will get back to you on this. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 

Sorry for the delay. 

Please note that there are still some errors in the build report. 
I am tagging Vince @vjcitn to take over the package review. 

Best regards,
Marcel

**Comment by Jfortin1** [comment]
Hi @LiNk-NY @vjcitn, Yes, it still has an ERROR because of the discussion we had above:
- If we test >=80% functions, we run into timeout issue because of the conda installation via basilisk. 

Looping in co-author Aaron Lun @LTLA as well

**Comment by LTLA** [comment]
To recap: **basilisk** works by installing conda environments on first use. Running the examples triggers installation of each environment (4 in total), each of which takes a few minutes to install. This will kick out the build times and cause a timeout.

I would suggest ignoring this particular error and making sure that all functions are adequately tested in the `longtests/`.

**Comment by vjcitn** [comment]
At this point, it seems that BiocCheck has error 
```
    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples. The following pages do not:
      getAzimuthScores.Rd, getDeepCpf1Scores.Rd, getDeepHFScores.Rd,
  getEnPAMGBScores.Rd, getLindelScores.Rd
    * NOTE: Usage of dontrun{} / donttest{} found in man page examples.
      42% of man pages use one of these cases.
      Found in the following files:
        getAzimuthScores.Rd
        getDeepCpf1Scores.Rd
        getDeepHFScores.Rd
        getEnPAMGBScores.Rd
        getLindelScores.Rd
    * NOTE: Use donttest{} instead of dontrun{}.
      Found in the following files:
        getAzimuthScores.Rd
        getDeepCpf1Scores.Rd
        getDeepHFScores.Rd
        getEnPAMGBScores.Rd
        getLindelScores.Rd
```
Now if the timeout owing to basilisk/conda is the main concern, I wonder whether there is a way forward, foregoing the safety of basilisk, by using reticulate, under the assumption that the appropriate python infrastructure is available.

**Comment by LTLA** [comment]
I doubt it, you would have to manually install all of the Python packages on the build machines. Some of these are very finicky.

**Comment by Jfortin1** [comment]
@vjcitn @LTLA This would be somewhat defeating the purpose of using `basilisk` (interfacing with multiple Python environments in one R session). Would it be productive to arrange a meeting to discuss this?

**Comment by vjcitn** [comment]
I am sorry to have missed this comment.  I will spend some time reviewing the situation.  It would be
really outstanding if you could figure out a way to test adequately -- maybe with the longtests feature -- but
pass check with meaningful examples that don't time out.

**Comment by vjcitn** [comment]
I did not realize that the different get*Scores required such incompatible python environments.  Is there no further development going on with these scoring tools to bring them to a more current and compatible state?  Anyway, @LiNk-NY -- would BiocCheck pass this package if >80% of the examples were wrapped in if (interactive())?  I think that is OK for users, gives them a good sense of what is going on, and https://www.bioconductor.org/developers/how-to/long-tests/ should be followed to get proper testing on a regular basis.  Unless there are major concerns from @lshep or @hpages about this strategy, I think we might be done here.

**Comment by LiNk-NY** [comment]
Yes, I think using `if (interactive())` would make the examples pass BiocCheck.

Jean-Philippe, can you work on these two notes from `BiocCheck`? 

```r
[2] "Usage of dontrun{} / donttest{} found in man page examples."
[3] "Use donttest{} instead of dontrun{}."
```
You could either remove them or replace with `if (interactive())` where appropriate. 
Perhaps some of that code can be added to the long tests. 
Thanks!

**Comment by Jfortin1** [comment]
Thank you Marcel @LiNk-NY and Vince @vjcitn, adding `interactive()` did the trick.
I've now made the following changes and pushed a new version:

- Changed `dontrun{}` to `if (interactive(){}` in the man examples
- Added the tests that were timing out to a `longtests` folder and added `RunLongTests: TRUE` to the `.BBSoptions` file

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jfortin1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("crisprScoreData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/crisprScoreData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jfortin1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("crisprScore")`. The package 'landing page' will be created at

https://bioconductor.org/packages/crisprScore

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by Jfortin1** [comment]
Hi Marcel @LiNk-NY,

Both `crisprScore` and `crisprScoreData` are now added to BioC 3.15, but they both have an error in the nightly build because of their mutual dependencies (crisprScore depends on crisprScoreData, and crisprScoreData has crisprScore as a Suggests package).

**Comment by LiNk-NY** [comment]
Thanks for pointing this out Jean-Philippe @Jfortin1 . We are currently investigating. It looks like there are some configuration issues with the builders to be sorted out. We will update soon.

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe @Jfortin1 
It looks like `crisprScoreData` does not need to suggest `crisprScore`.
Perhaps you could remove it from the `Suggests` field to move things forward more quickly? 
Best, 
Marcel

**Comment by Jfortin1** [comment]
Thanks Marcel @LiNk-NY, the `Suggests` is indeed unnecessary, oversight on my part. I removed it and pushed the commit.
