### ISSUE TITLE
crisprScore

### ISSUE THREAD

**Issue by Jfortin1** [Bioconductor/Contributions#2157]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository:https://github.com/Jfortin1/crisprScore

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 

Thank you for your submission. 
Please see the note below.

Best,
Marcel

---


# crisprScore #2157

## DESCRIPTION

* The data package is usually in the `Suggests` field.

## LICENSE

* I will confirm with the rest of the core team but you cannot restrict the
use with the current (albeit version `2.0`) license.

* We have this check in place for version 4.0:

```r
> BiocCheck:::.checkLicenseForRestrictiveUse("CC BY-NC-ND 4.0")
* Checking License: for restrictive use...
    * ERROR: License 'CC BY-NC-ND 4.0' restricts use
```

* If you do decide to continue with the submission, the license will have to
be suitable for redistribution according to our policies.

**Comment by Jfortin1** [comment]
Hi Marcel @LiNk-NY,

Thank you for reviewing our package. The license was decided by our legal team here at Genentech. I will discuss with them if we can change the license or not. If not, is there an exception that can be made?

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 
Unfortunately, we can't make exceptions. Please refer to this table and use a more permissive license:

```r
> read.dcf(R.home("share/licenses/license.db")) |> tibble::as_tibble()
# A tibble: 39 x 12
   Name    Abbrev Version SSS    OSI      FSF      File  URL    FOSS  Extensible
   <chr>   <chr>  <chr>   <chr>  <chr>    <chr>    <chr> <chr>  <chr> <chr>     
 1 GNU Ge… GPL    2       GPL-2  open (h… free_an… shar… https… yes   NA        
 2 GNU Ge… GPL    3       GPL-3  open (h… free_an… shar… https… yes   yes       
 3 GNU Li… LGPL   2       LGPL-2 open     free_an… shar… https… yes   NA        
 4 GNU Le… LGPL   2.1     LGPL-… open (h… free_an… shar… https… yes   NA        
 5 GNU Le… LGPL   3       LGPL-3 open (h… free_an… shar… https… yes   yes       
 6 GNU Af… AGPL   3       AGPL-3 open (h… free_an… shar… https… yes   yes       
 7 Apache… NA     1.1     NA     open bu… free_an… NA    https… yes   NA        
 8 Apache… NA     2.0     NA     open (h… free_an… NA    https… yes   NA        
 9 Artist… NA     1.0     Artis… open bu… non_fre… NA    https… no    NA        
10 Artist… NA     2.0     Artis… open (h… free_an… shar… https… yes   NA        
# … with 29 more rows, and 2 more variables: Restricts_use <chr>, Note <chr>
```
Best regards,
Marcel

**Comment by Jfortin1** [comment]
Thanks @LiNk-NY, I'm currently working with our legal team to choose a different license.

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe @Jfortin1
Any updates on this? We can close the issue until you hear back from the legal team.
Best,
Marcel

**Comment by Jfortin1** [comment]
@LiNk-NY Thank you for your patience; the team agreed for a MIT license (just pushed the latest changes).

**Comment by Jfortin1** [comment]
@LiNk-NY Hi Marcel, I'm trying to push my changes to the Bioc package, and I've set up an upstream correctly:
```
origin	git@github.com:Jfortin1/crisprScore.git (fetch)
origin	git@github.com:Jfortin1/crisprScore.git (push)
upstream	git@git.bioconductor.org:packages/crisprScore (fetch)
upstream	git@git.bioconductor.org:packages/crisprScore (push)
```
but get permission denied when trying to fetch:
```
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.
```

I've tried to specified a few of my public keys on my personal laptop by changing my `.ssh/config` file
(e.g. 
```
host git.bioconductor.org
HostName git.bioconductor.org
IdentityFile ~/.ssh/id_rsa
User git
```
but I've been unsuccessful.  I'm trying to see what ssh-key was added to the BioC crisprScore package by looking at my credentials at https://git.bioconductor.org/BiocCredentials/login/?next=/BiocCredentials/ but when trying to create an account with my email address used for the package (fortin946@gmail.com), it tells me that I don't have a package associated with my account. 

Would you be able to help?

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 

Nitesh would have a better idea of what's going on. It may be that you are authenticating with the wrong key or email. 
Can you please help @nturaga ? 

Best,
Marcel

**Comment by Jfortin1** [comment]
Thanks @nturaga for helping, I confirm that I'm using the same email to authenticate than the one on my Github

**Comment by nturaga** [comment]
Hi @Jfortin1 

It seems you were registered with your JHSPH email. I fixed the issue on our end, so you'll be able to activate your account with  https://git.bioconductor.org/BiocCredentials/account_activation.

Add your SSH keys, and you'll be good to go.

Best regards,

Nitesh

**Comment by Jfortin1** [comment]
@nturaga Thanks Nitesh, everything works well now! I have no idea where the JHSPH email was coming from (it's not in any of my settings on Github?)

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 
Please see the review below. Feel free to ask any questions.
Best,
Marcel

---

# crisprScoreData #2157

## DESCRIPTION

* You don't need to import `ExperimentHubData`.
* Suggest your own `crisprScore` package.
* Add `BugReports` and `URL` fields.

## NAMESPACE

* Remove the `ExperimentHubData` dependency.

# crisprScore #2157

## DESCRIPTION

* Suggest your own `crisprScoreData` package.
* Add `BugReports` and `URL` fields.
* Remove `LazyData` field

## NAMESPACE

* Looks good.

## vignettes/

* Looks good.

## R

* Code looks good.
* Remove stale code `R/basilisk2.R`
* If possible, avoid using numeric indices e.g., `scores[, c(1,4,5,6)]` and
use more robust `colnames`.
* It looks like some functions are not supported on Windows. This should be
noted in the `Description` field.

## tests/

* Looks good.

****

**Comment by Jfortin1** [comment]
@LiNk-NY Hi Marcel, thank you for your review! We've made all of your suggested changes and pushed a new version for both `crisprScore` and `crisprScoreData`.

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 
Please make `crisprScore` and additional package with the comment instructions above in the `crisprScoreData` issue. 
I will move the review over. 
Best,
Marcel
