### ISSUE TITLE
iPath

### ISSUE THREAD

**Issue by suke18** [Bioconductor/Contributions#2162]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/suke18/iPath

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by suke18** [comment]
Hello @Kayla-Morrell, 

I found one build error on the Windows platform. I wonder how to solve the "Rcpp.h" issue.. 

CppFunctions.cpp:1:10: fatal error: Rcpp.h: No such file or directory
 #include <Rcpp.h>
          ^~~~~~~~
Could you explain how should I do? I am using Macbook Pro and this is not an error on Mac OS. 

Best,
Kenong

**Comment by suke18** [comment]
Hello @lshep and @vjcitn, 

I am not sure why my package cannot be built on the Windows platform.  It seems other people having the same experience right now. https://github.com/Bioconductor/Contributions/issues/2049#issuecomment-866474638. 

```
Warning in file(con, "r") :
  cannot open file 'D:/biocbuild/bbs-3.14-bioc/R/etc/x64/Makeconf': Permission denied
Error in file(con, "r") : cannot open the connection
* removing 'C:/Users/pkgbuild/AppData/Local/Temp/RtmpAVmUJQ/Rinst32ec72241ffa/FLAMES'
```

**Comment by vjcitn** [comment]
We're looking at it.

**Comment by hpages** [comment]
There was a file permission issue on our Windows builder. It should be addressed now. Please bump the version of the package to trigger a new build by the SPB. Thanks!

**Comment by suke18** [comment]
@hpages @vjcitn @Kayla-Morrell , I uploaded a new build. However, there is still an checking error from Windows platform (see below): 

```
See 'Writing portable packages' in the 'Writing R Extensions' manual.
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... [10s] ERROR
Running examples in 'iPath-Ex.R' failed
Warning in file(con, "r") :
  cannot open file '../iPath-Ex_i386.Rout': Permission denied
Error in file(con, "r") : cannot open the connection
Execution halted
```
It seems that there is still a permission issue on the Windows platform. Could you help me to figure it out?

Best,
Kenong

**Comment by lshep** [comment]
We will look into this as soon as we can.  In the meantime @Kayla-Morrell  review the package on the other two platforms while we find time to investigate.

**Comment by suke18** [comment]
@Kayla-Morrell, I wonder if there are some updates for reviewing the package? @lshep @hpages, could you please let me know how to deal with the check error from the Windows platform. To me, it is still a permission problem. Thank you.

**Comment by Kayla-Morrell** [comment]
@suke18 - Typically reviews are posted within two weeks of a clean build. Since Lori only cleared the review 5 days ago, I will attempt to get a review posted by the end of the week but it might not happen until next week.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@suke18 - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] REQUIRED: The Title field is malformed, it should not end in a period.

- [ ] REQUIRED: 'LazyData:' in the 'DESCRIPTION' should be set to false or
removed.

- [ ] REQUIRED: It's unusual for more than three packages to be listed under
  'Depends'. If the package doesn't provide essential functionality to the
package I would suggest moving it to 'Imports'.

- [ ] REQUIRED: Update R version dependency from 4.0.0 to 4.1.

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        GeneExpression, Survival

## NAMESPACE

- [ ] REQUIRED: Be sure to add importFrom("stats", "na.omit", "sd") to your
NAMESPACE file, as well as 'stats' to 'Imports:' in the DESCRIPTION file.

- [ ] REQUIRED: Use importFrom() over importing an entire package. If there are
  many functions from a single package, than import() is okay but should be used
sparingly.

## Man pages

- [ ] SUGGESTION: For any unexported function that is already documented I would
  suggest adding the `@keywords internal` tag to the documentation. This will
remove the function from the package's documentation index.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] REQUIRED: Clarify how 4 object(s) are initialized. Maybe they are part of
a data set loaded with data(), or perhaps part of an object referenced in with()
or within().
        function (object)
        iES_cal2 (na.omit)
        rem_data (sd)
        water_fall (value)
        water_fall (type)

- [ ] REQUIRED: Avoid sapply(); use vapply(). Found in files:
        iES_cal.R, lines 64 and 70
        iES_surv.R, line 33

- [ ] REQUIRED: Avoid 1:...; use seq_len() or seq_along(). Found in files:
        iES_cal.R, lines 64 and 70
        iES_plots.R, lines 33 and 40
        iES_surv.R, line 33

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 44
lines that are > 80 characters long.

- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
indents. There are 34 lines that are not.

Best,
Kayla

**Comment by suke18** [comment]
@Kayla-Morrell , Hello Kayla, thanks for the review. I have modified all the required fields. Could you please check? The new version has been successfully built across 3 platforms but there is still a permission error which results in a check error. For the 1st concern listed in the R code section, here are some clarifications: 

- iES_cal2 (na.omit): **na.omit** is not an object. It is the function for ignoring non-matching positions from the `match` function. 
- rem_data (sd): **sd** is not an object. It calculates the standard deviation.  
- water_fall (value): **value** is the column name in the `data.frame`.
- water_fall (type): **type** is the column name in the `data.frame`. 

Please let me know if you have further concerns. 

Best,
Kenong

**Comment by Kayla-Morrell** [comment]
@suke18 - Thank you for making the necessary changes. I have reviewed them and everything looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by suke18** [comment]
@Kayla-Morrell, Thanks for your review.

**Comment by suke18** [comment]
@Kayla-Morrell and @vjcitn, I still didn't see this iPath package on http://www.bioconductor.org/dashboard/. I am wondering when it can be displayed on this platform? 

Best,
Kenong

**Comment by lshep** [comment]
The accepted packages have not been processed yet.  It should be on within the next few days.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/suke18.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("iPath")`. The package 'landing page' will be created at

https://bioconductor.org/packages/iPath

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
