### ISSUE TITLE
BindingSiteFinder

### ISSUE THREAD

**Issue by MirkoBr** [Bioconductor/Contributions#2174]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ZarnackGroup/BindingSiteFinder

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by MirkoBr** [comment]
Hi @Kayla-Morrell,

I've addressed most issues and errors. But I'll keep getting an ERORR on the windows server only. It seems to be related to the import function from the rtracklayer package. Running the check on a local windows machine could not reproduce the error. 

Could you help me following this up?

Thanks, 
Mirko

**Comment by grimbough** [comment]
@MirkoBr there was a very similar error report to this a few days ago in the Bioconductor Slack (https://community-bioc.slack.com/archives/C0207H5QC3X/p1625060073036200)

**Comment by shangguandong1996** [comment]
> 
> 
> Hi @Kayla-Morrell,
> 
> I've addressed most issues and errors. But I'll keep getting an ERORR on the windows server only. It seems to be related to the import function from the rtracklayer package. Running the check on a local windows machine could not reproduce the error.
> 
> Could you help me following this up?
> 
> Thanks,
> Mirko

Hi, I am the one post the error in the Bioconductor Slack. I use the 
```{r}
if (.Platform$OS.type != "windows" & require(TxDb.Athaliana.BioMart.plantsmart28)) {
XXX
}
```

to skip windows check on bioconductor check :) I help it can help you.

Best wishes
Guandong Shang

**Comment by Kayla-Morrell** [comment]
@MirkoBr - I can do an initial review based on the other 2 builders but I would suggest trying to reproduce the error and the work around as suggested above. I should have the review posted in a few days.

Best,
Kayla

**Comment by MirkoBr** [comment]
Hi,
@grimbough and @shangguandong1996 - thanks for the help on the error and the code snippet. I saw these type of exclude statements also in some other bioconductor submissions, but I did not feel comfortable to do this right away. 

@Kayla-Morrell - thanks for starting the review already. Can I still push changes while you are doing it?

Best,
Mirko

**Comment by Kayla-Morrell** [comment]
@MirkoBr - It would be easier to do the review when you have finished working on the package. Feel free to push changes and let me know when it's good to start my review.

Best,
Kayla

**Comment by MirkoBr** [comment]
@Kayla-Morrell - I've resolved the error with the build on windows. I won't make any changes anymore the repository until you finished the review.

Thanks again.

Best,
Mirko

**Comment by Kayla-Morrell** [comment]
@MirkoBr - Perfect, I will continue working on the review. It should be posted in the next couple of days.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@MirkoBr - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] SUGGESTION: The Description field in the DESCRIPTION is made up by less
than 3 sentences. Please consider expanding this field, and structure it as a
full paragraph.

- [ ] SUGGESTION: We strongly encourage using the 'BugReports:' field which
  includes the relevant link to GitHub for reporting Issues.

## NAMESPACE

- [ ] SUGGESTION: Generally importFrom() is encouraged over importing an entire
  package, however if there are many functions from a single package, than
import() is okay.

## Vignette

- [ ] REQUIRED: There should be an 'Installation' section that shows to the user
  how to download and load the package from Bioconductor. The code should look
like the following and include `eval = FALSE`.


```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("BindingSiteFinder")
```

- [ ] REQUIRED: We require code chunks to be evaluated (minus the installation
  code). Please be sure each code chunk is evaluated unless there is good reason
for it not to, which you should justify.

## Man pages

- [ ] REQUIRED: Add runnable examples to the following man pages which document
exported objects:
        show.Rd

## R code

- [ ] REQUIRED: Avoid sapply(); use vapply(). Found in files:
        AllClasses.R, lines 121 and 124
        Functions.R, line 119
        helper.R, lines 41 and 67
        PlotFunction.R, lines 101, 125, 266, 395, 455, and 494

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 222
lines that are > 80 characters long.

- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
indents. There are 137 lines that are not.

Best,
Kayla

**Comment by MirkoBr** [comment]
@Kayla-Morrell - Thank you for reviewing the package. I've addressed all issues and suggestions: 


DESCRIPTION
---
- [x] SUGGESTION: The Description field in the DESCRIPTION is made up by less than 3 sentences. Please consider expanding this field, and structure it as a
full paragraph.
- _Extended_
- [x] SUGGESTION: We strongly encourage using the 'BugReports:' field which includes the relevant link to GitHub for reporting Issues.
- _Added_

NAMESPACE
---
- [x] SUGGESTION: Generally importFrom() is encouraged over importing an entire package, however if there are many functions from a single package, than import() is okay.
- _I mainly use importFrom(), but for packages like GenomicRanges where I require multiple functions, I stayed with import()_

Vignette
---
- [x] REQUIRED: There should be an 'Installation' section that shows to the user how to download and load the package from Bioconductor. 
- _Included_
- [x] REQUIRED: We require code chunks to be evaluated (minus the installation code). Please be sure each code chunk is evaluated unless there is good reason for it not to, which you should justify.
- _At the moment I have two code chunks with eval=FaLSE (besides the installation code). Both deal with the import of example data to showcase the package functionalities. Here for example, I show how the initial object can be constructed from the data (`bds = BSFDataSet(ranges = csFilter, meta = meta)`). But since that call would require large files to be used, I load a precompiled .rds file instead. I could in principal remove this code chunk, but I thought it would be helpful to see where the object is coming from._

Man pages
---
- [x] REQUIRED: Add runnable examples to the following man pages which document exported objects:
show.Rd 
- _Added_

R code
---
- [x] REQUIRED: Avoid sapply(); use vapply(). Found in files: AllClasses.R, lines 121 and 124
Functions.R, line 119
helper.R, lines 41 and 67
PlotFunction.R, lines 101, 125, 266, 395, 455, and 494 
- _Changed all_
- [x] SUGGESTION: For formating reasons, consider shorter lines. There are 222 lines that are > 80 characters long.
- _Fixed most, some lines are still flagged, although I don't know why. To me they appear to be in the correct format._
- [x] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line indents. There are 137 lines that are not.
- _Fixed most, some lines are still flagged, although I don't know why. To me they appear to be in the correct format._

I think with that I've addressed all issues and the package should be ready for a re-evaluation.

Best, 
Mirko

**Comment by Kayla-Morrell** [comment]
@MirkoBr - Thank you for making the necessary changes. I have reviewed them and everything looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by MirkoBr** [comment]
@Kayla-Morrell - That is fantastic new! Thanks for taking the time reviewing the package.

Best,
Mirko

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MirkoBr.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BindingSiteFinder")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BindingSiteFinder

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
