### ISSUE TITLE
rmspc

### ISSUE THREAD

**Issue by MeriemBahda** [Bioconductor/Contributions#2178]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Genometric/rmspc

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by MeriemBahda** [comment]
Hi @nturaga and @bioc-issue-bot, 

Thank you for reviewing the package. 

The error mentioned occurs because a prerequisite for the rmspc package is .NET 5.0. 
Before installing the rmspc package, the program .NET 5.0. should already be installed on the user's computer. 

Best, 
Meriem

**Comment by lshep** [comment]
specific system requirements versions should be specified in a SystemRequirements field of the DESCRIPTION file. You should also include an INSTALL file for how to install any external system requirements.

**Comment by MeriemBahda** [comment]
Alright, thank you!
For the INSTALL file, can it simply be a text file that contains the link to the download web page of the external system requirement?

**Comment by lshep** [comment]
Yes and if there are any other tips or quirks for the installation.

**Comment by MeriemBahda** [comment]
Alright, thank you!

**Comment by MeriemBahda** [comment]
I have added the system requirements in a SystemRequirements field in the DESCRIPTION file, and I have included an INSTALL file in the package, but the same error still occurs.

**Comment by vjcitn** [comment]
Hi @MeriemBahda I have installed your package on a linux machine and it looks interesting.  On an M1 mac with .NET 5.0 I got 
```* checking for file 'rmspc/DESCRIPTION' ... OK
* preparing 'rmspc':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘rmpsc.Rmd’ using rmarkdown
Quitting from lines 158-165 (rmpsc.Rmd) 
Error: processing vignette 'rmpsc.Rmd' failed with diagnostics:
cannot start processx process 'dotnet' (system error 2, No such file or directory) @unix/processx.c:610 (processx_exec)
--- failed re-building ‘rmpsc.Rmd’```

it looks like M1 mac is not supported by .Net, unless I install rosetta.  I will try an intel mac.

I would point out that we have not supported .Net for bioconductor packages thus far, but we will consider it for your package.  We need some further discussion about supporting this infrastructure.  I will continue the review on my linux machine.

**Comment by MeriemBahda** [comment]
Alright, thank you very much @vjcitn !

**Comment by lshep** [comment]
We are testing installing .NET on one of the builders (depending on the outcome we will explore adding to the other builders). I am going to kick off a manual build to see if it recognizes.  I just wanted to make you aware if you see another report posted here.

**Comment by MeriemBahda** [comment]
Thank you for the heads-up!

**Comment by MeriemBahda** [comment]
Hi @lshep, 
I was wondering if there are any updates regarding installing .NET on one of your builders? 
Thank you!

**Comment by vjcitn** [comment]
Hi @MeriemBahda ... I will start working on this package again.  Have you dealt with
```
* Checking for support site registration...
    Maintainer is registered at support site.
    * ERROR: Maintainer must add package name to Watched Tags on the
      support site; Edit your Support Site User Profile to add Watched
      Tags.
```

**Comment by vjcitn** [comment]
If you have, please bump your Version value in DESCRIPTION and push so you get a new build.

**Comment by MeriemBahda** [comment]
It's done, thank you @vjcitn!

**Comment by vjcitn** [comment]
I think we are ready to test this on Mac.  Please bump version in DESCRIPTION and push to generate
a new build.

**Comment by hpages** [comment]
I just installed the .NET 5.0 Runtime on our Windows builder (riesling1) so **rmspc** should also be ready to test on that machine. However, please note that I installed it for 64-bit Windows only so you will need to mark your package as unsupported on 32-bit Windows. This is done by adding the `.BBSoptions` file to the top-level folder of your package with the following line in it:

    UnsupportedPlatforms: win32

You will also need to bump the package version to trigger a new build.  Thanks!

**Comment by MeriemBahda** [comment]
@hpages and @vjcitn, it's done, thank you!

**Comment by hpages** [comment]
@MeriemBahda The file should be named `.BBSoptions`, not `.BBSoptions.txt`. For some reason **rmspc** was still able to pass a bi-arch `R CMD check` on riesling1 (the command for this is `R CMD check --force-multiarch ...`), despite the fact that  `.BBSoptions.txt` got ignored. One possible explanation is that maybe  .NET is only needed to build the vignette (the vignette only gets built for the default arch, which is x64 on Windows), I don't know. Anyways, please rename `.BBSoptions.txt` -> `.BBSoptions`. Also make sure that the line in the file has a trailing EOL character. Thanks.

The error on merida1 (macOS builder) is being investigated by @jwokaty.

@lshep Any idea why the last build doesn't include the results for nebbiolo2 (Linux builder)? Thanks.

**Comment by lshep** [comment]
@hpages It looks like both linux and windows builders stopped responding for the SPB scripts yesterday afternoon. They are both running now and should have a report for linux on the next run

**Comment by MeriemBahda** [comment]
@hpages I have renamed the file .BBSoptions.txt to BBSoptions and added a trailing EOL character to the line of the file. 
Thank you!

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MeriemBahda.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("rmspc")`. The package 'landing page' will be created at

https://bioconductor.org/packages/rmspc

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
