### ISSUE TITLE
rGenomeTracks

### ISSUE THREAD

**Issue by OmarAshkar** [Bioconductor/Contributions#2193]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/OmarAshkar/rGenomeTracks/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Thank you for your package submission. Please see initial review below: 


**inst**

- [ ] Please have an inst/scripts that describes how the data in inst/extdata was created. It can be code, sudo-code, or text but should contain source information and any processing


**vignette**

- [ ] We do not allow data to be downloaded from github. The data should be on a stable server. If unable to host, please look into the Bioconductor provided ExpeirmentHub to store data/large files.

- [ ] I get an ERROR when trying to run:

```
Error: could not find a Python environment for /home/shepherd/miniconda3/envs/r-reticulate/bin/python
```


I followed the instructions for installing pyGenomeTracks
```
conda create -n pygenometracks -c bioconda -c conda-forge pygenometracks python=3.7

```
And if I try again, it seems like it is installed
```
(base) shepherd@jbcj433:~/PkgReviews/rGenomeTracks(master)$ conda create -n pygenometracks -c bioconda -c conda-forge pygenometracks python=3.7WARNING: A conda environment already exists at '/home/shepherd/miniconda3/envs/pygenometracks'
Remove existing environment (y/[n])? n


CondaSystemExit: Exiting.
```

If there are additional setup instructions, or needs to run in a certain directory with environment activated,  these should be documented. 


**DESCRIPTION**
- [ ] external system requirments should be specified in the description with a  `SystemRequirements` field. And it is recommended for any non-trivial installation to also include a top-level `INSTALL` file


When ready please provide feedback on the above concerns.  Kick off a new build by pushing a version bump to git.bioconductor.org  and comment back here that you are ready for a re-review. 

Cheers

**Comment by OmarAshkar** [comment]
Thank you,
My main concerns are that pyGenomeTracks installation I tested was either by using 
```
library(reticulate)
py_install("pyGenomeTracks")
```
or pip install the the same loading environment of R. I will try to find a way to include the official installation environment. However though, you should have been prompted to install via reticulate with the first call of plot_gtracks(), don't you?!

Thank you,

**Comment by lshep** [comment]
No I did not

**Comment by OmarAshkar** [comment]
@lshep I've actually found I don't need to upload the data to bioc cloud as they are not intended to be imported into R. I upload it directly to another package here. 
https://github.com/OmarAshkar/rGenomeTracksData

What should I do now?

**Comment by lshep** [comment]
Please submit the data package here for review as described in [submitting related packages](https://github.com/Bioconductor/Contributions#submitting-related-packages)

**Comment by OmarAshkar** [comment]
I am closing this to upload AnnotationHub package first
