### ISSUE TITLE
atena

### ISSUE THREAD

**Issue by beacalvo** [Bioconductor/Contributions#2213]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/functionalgenomics/atena

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Please see the following review: 

**Build Report**

- [ ] Please address `coding practice` NOTES.

**DESCRIPTION**

- [ ] (Optional) A package URL and BugReports field is encouraged

**Unit tests**

- [ ] We highly suggest adding unit tests

**NEWS**

- [ ] Please have `(start date: August 1, 2021)` removed or as a list
  element. The news file will not be properly formatted with this free form text
  piece.

**README**

- [ ] encouraged to now also include Bioconductor installation instructions

**inst**

- [ ] Please also have an `inst/script` directory with information on how the
  data in `inst/extdata` was generated and minimally source/licenses
  information.

**man**

- [ ] (optional) we highly recommend a package help page for users that naively
  do `?atena` that would point to main documentation or functions.


**vignette**

OK

**R**

- [ ] Seems like features setGeneric in AllClasses should be moved to AllGenerics

- [ ] We would prefer `message` over `cat` for printing as users can optionally
  suppress. The exception obviously for the show method as cat is appropriate
  there.

- [ ] Please remove any non used code such as ovIntersectionNonEmpty

- [ ] Seems like AllUtilies.R function could be moved to utils.R


- [ ] Functional programming: no code repetition. It seems like
  .buildOvValuesMatrix and .buildOvValuesMatrixTS are the same function? Only
  have one version of the functions and do not repeat code. All occurances like
  this should be cleaned up.
  
- [ ] In good practice you should close files opened with `on.exit` to ensure
proper close out eg Telescope.R line 211-222.

- [ ] Is there a reason for the double function assignement In utils.R line 262


Please address the following issues.  When ready be sure to do a version bump to trigger a new build report and comment back here on how the above have been addressed or any clarification comments and request a re-review. 
Cheers,

**Comment by beacalvo** [comment]
Dear @lshep 

Thank you very much for your review and useful suggestions. We have addressed your comments in the following way:



 
> **Build Report**
> 
> * [X]  Please address `coding practice` NOTES.

We have solved most notes. Only one function has a length > 50 lines (70 lines) and the percentage of lines longer than 80 characters has been reduced to 2% (long messages/warnings/error), as well as the percentage of lines without an indent multiple of 4 (2%).


> **DESCRIPTION**
> 
> * [X]  (Optional) A package URL and BugReports field is encouraged

An URL and BugReports field have been added to the DESCRIPTION file.

> **Unit tests**
> 
> * [ ]  We highly suggest adding unit tests

We have included unit tests with a test coverage of 57%.

> **NEWS**
> 
> * [X]  Please have `(start date: August 1, 2021)` removed or as a list
>   element. The news file will not be properly formatted with this free form text
>   piece.

We have removed the free form text.

> **README**
> 
> * [X]  encouraged to now also include Bioconductor installation instructions

We have added instructions for the installation of the development version (once available) through BiocManager. We were unsure about whether to include the release version installation instructions, but we have finally also included these instructions.

> **inst**
> 
> * [X]  Please also have an `inst/script` directory with information on how the
>   data in `inst/extdata` was generated and minimally source/licenses
>   information.

We have created the directory with the file “create-data_OhtaniSaito13.Rmd” with the code used to obtain the data files included in inst/extdata.

> **man**
> 
> * [X]  (optional) we highly recommend a package help page for users that naively
>   do `?atena` that would point to main documentation or functions.

The help page has been created.

> **vignette**
> 
> OK
> 
> **R**
> 
> * [X]  Seems like features setGeneric in AllClasses should be moved to AllGenerics

We agree, it has been changed.

> * [X]  We would prefer `message` over `cat` for printing as users can optionally
>   suppress. The exception obviously for the show method as cat is appropriate
>   there.

Ok, it has been modified.

> * [X]  Please remove any non used code such as ovIntersectionNonEmpty

We have removed all non used code.

> * [X]  Seems like AllUtilies.R function could be moved to utils.R

We agree, we have moved the code in AllUtilies.R to utils.R and deleted the AllUtilies.R file.

> * [X]  Functional programming: no code repetition. It seems like
>   .buildOvValuesMatrix and .buildOvValuesMatrixTS are the same function? Only
>   have one version of the functions and do not repeat code. All occurances like
>   this should be cleaned up.

These two functions differed on just one line. The .buildOvValuesMatrix function has been modified so that it can now be used by all methods. This way, the .buildOvValuesMatrixTS function is not used anymore and has been deleted.

> * [X]  In good practice you should close files opened with `on.exit` to ensure
>   proper close out eg Telescope.R line 211-222.

We have added on.exit to close files.

> * [X]  Is there a reason for the double function assignement In utils.R line 262

No, it was a mistake, thank you for pointing it out. We have fixed it.

> Please address the following issues. When ready be sure to do a version bump to trigger a new build report and comment back here on how the above have been addressed or any clarification comments and request a re-review.
> Cheers,



Best regards,
Bea

**Comment by rcastelo** [comment]
Hi @lshep a week ago we received the notification above on the acceptance of the package, but so far it doesn't seem to part of the nightly builds yet. I guess this will happen at some point, but one question, can we push changes to git.bioconductor.org:packages/atena ? if yes, could i be added to have permissions to push changes as well?

thank you!!
robert.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/beacalvo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("atena")`. The package 'landing page' will be created at

https://bioconductor.org/packages/atena

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
