### ISSUE TITLE
pathprintGEOData

### ISSUE THREAD

**Issue by BioSok** [Bioconductor/Contributions#222]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hidelab/pathprintGEOData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by BioSok** [comment]
Dear @hpages , I am getting an error (from the .Rd files) which states that certain functions cannot be found. I put these functions in the R folder but the error persists. How can I refer to the location of these functions? Also, this is a data package, maybe I have to declare this somewhere? Thank you for your time.

**Comment by mtmorgan** [comment]
Generally, experiment data packages should _not_ have R functions; these should be in the package (pathprint) that this package supports. Add the function to pathprint, add pathprint to the Suggests: field of this package. Make sure to library(pathprint) in the example.

**Comment by mtmorgan** [comment]
I'm closing this issue, in hopes that we can get this associated with it's software package.

**Comment by BioSok** [comment]
Dear @mtmorgan ,
when I added check(force_suggests = FALSE) in the description file (because pathprint is not accepte yet) the build resulted in ABNORMAL. What causes that? Thanks for your time!

**Comment by mtmorgan** [comment]
I removed @hpages from this package and assigned @vobencha, as @vobencha is handling the review of the the sister pathprint package.

**Comment by mtmorgan** [comment]
ABNORMAL usually indicates that the DESCRIPTION file is incorrectly formatted. All entries in the description file must have format

```
Key: value
    continutation
```

I'm sorry I let the ball drop on getting this to build. I'll return to this today.

**Comment by mtmorgan** [comment]
I think the package is now associated with issue https://github.com/Bioconductor/Contributions/issues/183. Please do not post any further comments on this issue.

**Comment by mtmorgan** [comment]
@BioSok don't worry about the error above; the package will be processed to the svn repository later tonight.
