### ISSUE TITLE
mimager

### ISSUE THREAD

**Issue by aaronwolen** [Bioconductor/Contributions#223]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/aaronwolen/mimager

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor.  The package looks very close to acceptance. A few minor comments: 

General: 

- [ ] Please remove the .Rproj from the top level directory along with any unnecessary hidden files
- [ ] Consider adding the installation/download instructions from bioconductor; perhaps in the readme or a section in the vignette: 
```
source("http://www.bioconductor.org/biocLite.R")
biocLite("mimager")
```

Vignette: 
- [ ] Please include the library call for affydata in the Basic visualization section to ensure the package is loaded and data available. 
```
library(mimager)
library(affydata)
data("Dilution", package = "affydata")
```

Man Pages: 
-  [ ] marray.Rd  which method uses the argument `...` ? It doesn't appear to be implemented. Can this be removed? 

General: 
- [ ]  There is a well known package entitled [marray](https://www.bioconductor.org/packages/release/bioc/html/marray.html) that is in existence.  We would highly recommend renaming your S4 method of the same name to a different name to avoid confusion.

Thank you.  When you are finished pushing updates to the packages, please respond back here for which of the above issues were addressed and/or justification if any of the issues were not addressed.

**Comment by aaronwolen** [comment]
Thanks for the feedback! I've addressed all but one of the issues you raised (more below):

--- 

General:

> - [x] Please remove the .Rproj from the top level directory along with any unnecessary hidden files

* Fixed in [2d77efc](https://github.com/aaronwolen/mimager/commit/2d77efc0e04d9765f9a134fd4e84e0aea17f7701)

> - [x] Consider adding the installation/download instructions from bioconductor; perhaps in the readme or a section in the vignette:

* Fixed in [d9a8fb1](https://github.com/aaronwolen/mimager/commit/d9a8fb1f31b5e6724c3880e3613886d5de4f89b8)

Vignette:

> - [x] Please include the library call for affydata in the Basic visualization section to ensure the package is loaded and data available.

* Fixed in [7f24fc8](https://github.com/aaronwolen/mimager/commit/7f24fc801b9c01d6d9fab1a992fa19300b23ffd4)

Man pages:

> - [x] marray.Rd which method uses the argument ... ? It doesn't appear to be implemented. Can this be removed?

* Fixed in [af4368b](https://github.com/aaronwolen/mimager/commit/af4368b9c26e5c31151da069c679f485d3b57eca)

General:

> - [ ] There is a well known package entitled marray that is in existence. We would highly recommend renaming your S4 method of the same name to a different name to avoid confusion.

* This is a good point, and I was aware of the *marray* package (it's actually one of the first bioc packages I ever used), but I didn't think `mimager::marray()` would be an issue since it doesn't actually conflict with any of *marray*'s exported methods/classes. I also liked the consistency of prefixing *mimager*'s functions with *m*: `mimage()` for microarray images, `marray()` for creating microarray arrays and `mindex()` for creating microarray indices (currently not exported). 

    I'm totally willing to rename `marray()` to avoid confusion but haven't yet thought of a suitable replacement. Any suggestions?

**Comment by lshep** [comment]
If you would like the consistency it is your choice as a developer.  Just something to keep in mind and be aware of.  Thank you for making the current fixes.  I will mark your package as accepted.  Please keep the issue open and you will receive svn instructions for inclusion in Bioconductor devel (probably within the next week).

**Comment by aaronwolen** [comment]
Great! Thanks for the help.
