### ISSUE TITLE
(inactive) RTNmotifs package submission

### ISSUE THREAD

**Issue by chagasVinicius** [Bioconductor/Contributions#226]
Dear Bioc Reviewers,

Please, see below the GitHub repository URL for our new software called "RTNmotifs". The software presented here is an original contribution that offers a bioinformatics approach to infer possible co-regulation between regulon pairs (which we call 'dual regulons'). The tool represents the 1st level of our analysis pipeline dedicated to assess the complexity of co-regulation between different types of regulatory elements, and possible effects on regulatory network.

Sincerely,
Vinicius, Clarice and Mauro

- Repository: https://github.com/chagasVinicius/RTNmotifs

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Hi,
I've done a first review. Please see comments/suggestions below.

1) R CMD check output:
Please update the R version. We ask this because the package will only be available in Bioconductor >=3.5 (devel) which corresponds to R version >=3.4.

* Checking R Version dependency...
    * WARNING: Update R version dependency from 3.3 to 3.4.

2) NAMESPACE
Everything in 'Depends' in DESCRIPTION should be fully imported in NAMESPACE. This is what we've got in DESCRIPTION:

    Depends: R (>= 3.3), methods, RTN, graphics

    There is no need (or point) in selectively importing from RTN in NAMESPACE, you just need import(RTN). If you want to selectively import, RTN should only be in 'Imports'.

3) DESCRIPTION
Why the '...'?
Author: Vinicius S. Chagas, Clarice S. Groeneveld, ..., Gordon Robertson, Mauro A. A. Castro

4) function names
Your getters and setters have a dot '.' in the name. This format is used in S3 method dispatch. Since these are not S3 methods, please change the function names to use underscore or camelCase, e.g.,

    mbrGet or mbr_get

5) initialize method
We don't reccomend using an initialize method. The MBR class should have a constructor and validity, see GAlignments-class.R for an example.

6) getter and setters
Instead of defining mbr.get that uses many if statements to retrieve s slots why not have clean getters and setters for each slot? You can build on these to make more complicated functions but the essential slot accessors should be in place. Please create a getter and setter for the slots - see GAlignments-class.R file in the GenomicAlignments package as an example. These don't have to be generics and methods - they can be simple functions. Let me know if you have questions about this.

    The getters and setters should use '@' to access slots. Once these are defined you should not be using '@' through out the code. Please remove slot access with '@' and use a getter/setter instead. For example, tni2mbr.preprocess accesses just about every slot with '@':

```
##Combine two TNIs produced separately
setMethod("tni2mbr.preprocess",
          "TNI",
          function (tni1,  tni2,  verbose=TRUE)
          {
           mbr.checks (name='tni', para=tni1)
           mbr.checks (name='tni', para=tni2)
           .combineTNIs (tni1=tni1, tni2=tni2, verbose=verbose)
           ##---- creates MBR object
           object <- new("MBR", gexp=tni1@gexp,
                         regulatoryElements1=tni1@transcriptionFactors,
                         regulatoryElements2=tni2@transcriptionFactors)
           object@TNI1 <- tni1
           object@TNI2 <- tni2
           status <- names(object@TNI1@status[object@TNI1@status=="[x]"])
           object@status[status] <- "[x]"
           ##---permutation
           object@para$TNIs$perm <- tni1@summary$para$perm
...
```
For some justification as to why we ask this please see this post https://stat.ethz.ch/pipermail/bioc-devel/2016-December/010297.html.

7) man pages
Most man pages look good and have thorough examples, thank you. The class man page is a bit lacking. Please see ?GAlignments for all the details that should be on a class man page. Also add an \alias{} at the top for MBR so it can be found with ?MBR. The class constructor should also be documented on this page.

Valerie

**Comment by vobencha** [comment]
Have you addressed the comments in https://github.com/Bioconductor/Contributions/issues/226#issuecomment-269642276 and are ready for another review? If yes, please itemize what changes were made.

**Comment by chagasVinicius** [comment]
Dear Valerie,

Thank you for your review, all suggestions were very helpful for the development of our package. We revised the package following your suggestions, which are described below in more details.

Sincerely,

Vinicius


(1) R CMD check output:
Please update the R version. We ask this because the package will only be available in Bioconductor >=3.5 (devel) which corresponds to R version >=3.4.
Checking R Version dependency...
WARNING: Update R version dependency from 3.3 to 3.4.

Authors: OK!


(2) NAMESPACE
Everything in 'Depends' in DESCRIPTION should be fully imported in NAMESPACE. This is what we've got in DESCRIPTION:
Depends: R (>= 3.3), methods, RTN, graphics
There is no need (or point) in selectively importing from RTN in NAMESPACE, you just need import(RTN). If you want to selectively import, RTN should only be in 'Imports'.

Authors: OK! thank you.


(3) DESCRIPTION
Why the '...'?
Author: Vinicius S. Chagas, Clarice S. Groeneveld, ..., Gordon Robertson, Mauro A. A. Castro

Authors: Author's contribution is updated.


(4) function names

Your getters and setters have a dot '.' in the name. This format is used in S3 method dispatch. Since these are not S3 methods, please change the function names to use underscore or camelCase, e.g.,

Authors: OK!


(5) initialize method
We don't reccomend using an initialize method. The MBR class should have a constructor and validity, see GAlignments-class.R for an example.

Authors: We have created a constructor as described in the Galignments-class.R; this constructor is internal. We described the constructors in the MBR class man page. The validity of our constructor is now evaluated by the function “mbr.checks”.


(6) getter and setters
Instead of defining mbr.get that uses many if statements to retrieve s slots why not have clean getters and setters for each slot? You can build on these to make more complicated functions but the essential slot accessors should be in place. Please create a getter and setter for the slots - see GAlignments-class.R file in the GenomicAlignments package as an example. These don't have to be generics and methods - they can be simple functions. Let me know if you have questions about this. The getters and setters should use '@' to access slots. Once these are defined you should not be using '@' through out the code. Please remove slot access with '@' and use a getter/setter instead. For example, tni2mbr.preprocess accesses just about every slot with '@':

Authors: Thank you for the suggestion. We have now created the ".mbr.set" function that sets all slots in the MBR class objects. No direct slot is being accessed anymore in the MBR methods. In terms of the getters and setters complexity, we understand that these functions have many statements, but we think it betters accommodates the package evolution at this stage. Also, we are starting to create a toolset around  our RTN package and the RTNmotifs is the first package of this family of tools. So, it is important that all collaborators have the same fealing while using the toolset, and the current methos follows the workflow structure.


(7) man pages
Most man pages look good and have thorough examples, thank you. The class man page is a bit lacking. Please see ?GAlignments for all the details that should be on a class man page. Also add an \alias{} at the top for MBR so it can be found with ?MBR. The class constructor should also be documented on this page.

Authors: Thank you. We have improved the class man page.

**Comment by chagasVinicius** [comment]
Dear Valerie,

We are just contacting you to say that we have made a minor adjust on the documentation of the "MBR-class" object. If you have any suggestion please let us know. 

Sincerely,
Vinicius

**Comment by vobencha** [comment]
Please bump the 'z' portion of the version so we get a new build. This is an important practice you should start doing each time you commit a change. More information on version bumping here:
http://www.bioconductor.org/developers/how-to/version-numbering/

Valerie

**Comment by vobencha** [comment]
Thanks for making the changes. The package is looking good.

It looks like (4) in my original comments was not addressed. We still have exported functions with dot '.' in the name:

export(mbr.plot.duals)
exportMethods(mbr.association)
exportMethods(mbr.bootstrap)
exportMethods(mbr.dpi.filter)
exportMethods(mbr.duals)
exportMethods(mbr.permutation)
exportMethods(mbr.preprocess)
exportMethods(tni2mbr.preprocess)

Valerie

**Comment by chagasVinicius** [comment]
Dear Valerie,

Thank you. I would like to bring you a concern that just arised from the group. We are discussing the possibility of improving the name of the package (from RTNmotifs to RTNduals?), but we haven't decided yet whether it will be necessary. It is a matter of semantics in order to clarify the concepts presented in the package. 

Could I ask you to continue the revision process as it is, but before the eventual acceptance we make the final decision?

In the mean while the group should agree on the final name.

Thank you,

Vinicius

**Comment by vobencha** [comment]
Changing the package name once approved is a pain. You'll definitely want to change it now if at all. If you decide to that we'll close/reject this issue and you'll open another under the new name.

Valerie

**Comment by chagasVinicius** [comment]
Dear Valerie,

Thank you for the quick reply. Please I want to continue with the current issue until the group agree on the final name. We will probably keep the current name, I just would like to bring you this possibility.

Vinicius

**Comment by chagasVinicius** [comment]
Dear Valerie,

We have made the changes you suggested. Sorry for the number of
updates in such a short time, but I have lost some changes in the
documentation. The version number "0.99.4" is the correct for the next
review step.

Sincerely,

Vinícius

**Comment by vobencha** [comment]
Thanks for making the changes. Do you want to change the name or should I mark the package as approved?

Valerie

**Comment by chagasVinicius** [comment]
Dear Valerie,

Thank you for the precious reviews. The group decided to change the package name to "RTNduals", how can I proceed to make this change and how will work the process to upload the package to Bioconductor?

Sincerely,
Vinicius

**Comment by vobencha** [comment]
Hi @chagasVinicius ,

To change the package name we need to 
- we (Bioconductor) close this issue
- you create a new repo on github under the new name and submit as a new packge to the tracker
- the package gets approved under the new name

Adding Martin for confirmation. @mtmorgan , I'm not sure we have a standard procedure for re-naming a package prior to acceptance. I'm marking this issue as 'declined' and suggested the above steps. We may also want to link this issue to the new one ... let me know how you want to proceed.

Valerie

**Comment by mtmorgan** [comment]
Yes I recommend following @vobencha's work flow.
