### ISSUE TITLE
MetCleaning

### ISSUE THREAD

**Issue by jaspershen** [Bioconductor/Contributions#227]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jaspershen/MetCleaning

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by jaspershen** [comment]
Hi LiNk-NY, thank you for reviewing my package. I have revised the most of the errors and warnings in the package. However, in my local computer (win10), I can't run BiocCheck. So I don't know whether the errors and warnings have been removed. Thanks.

**Comment by lawremi** [comment]
The diagram in your vignette shows data potentially coming from xcms, but through a CSV file. Since xcms is a Bioconductor package, why not accept xcms data structures, and perhaps data structures from other packages, as there is a mature ecosystem?

**Comment by jaspershen** [comment]
Hi lawremi, metabolomics data analysis can be divided into several steps, first step is data processing (XCMS or mzMind), which transform MS raw data into dataset (matrix) which can be used for sequence statistical analysis. However, before statistical analysis, the data need to accept data pre-processing (or data preparation, data cleaning) to remove the system variations. So the package MetCleaning is used to do the data pre-processing. I don't integrate XCMS into MetCleaning because there are a lot of parameters should be optimized in the XCMS based on experiment. 
Thanks

**Comment by lawremi** [comment]
All I am suggesting is that the user can pass the output of XCMS to your functions directly, without going through any external files. I wasn't suggesting that your package wrap XCMS.

**Comment by jaspershen** [comment]
Hi, lawremi. I am very sorry to understand your suggestion. Another external file named "sample.information" is used to offer sample information such as injection order, batch and group information, which are necessary for QC based normalization, data integration and statistical analysis. So this file should be offered because those information can't be directly offered by XCMS. 
Thank you.

**Comment by jaspershen** [comment]
Hi, lawremi. I am very sorry to wrongly understand your suggestion. Another external file named "sample.information" is used to offer sample information such as injection order, batch and group information, which are necessary for QC based normalization, data integration and statistical analysis. So this file should be offered because those information can't be directly offered by XCMS.
Thank you.

**Comment by lawremi** [comment]
Why can't you use the `phenoData` component of xcmsSet for that?

**Comment by jaspershen** [comment]
Hi, lawremi. You know that some users don't use XCMS to do processing of MS raw data, they may use mzMine, MS-DIAL or other commercial software (for example, Agilent's Profinder). In MetCleaning, we only need a metabolomics dataset which contains mz(mass to charge) and rt (retention time) information and we don't care which software they use. I just use the dataset from XCMS as a example, because in my lab we mainly use XCMS. However, MetCleaning can process dataset from any software. This is why I don't want to use so much functions in XCMS.
Thanks

**Comment by lawremi** [comment]
The goal would be to make getting data into your software as easy as possible. You could support xcms directly, and also support other types of input from other software.

**Comment by jaspershen** [comment]
Hi, lawremi, offer the sample.information.csv file is also easy for most of users.

**Comment by lawremi** [comment]
Again, I didn't suggest to remove any functionality. Just to support a bridge from xcms, which provides standardized infrastructure for this type of data.

**Comment by jaspershen** [comment]
Hi, lawremi, I don't understand which type of data should be supported in MetCleaning? mzXML? Now, MetCleaning only need a metabolomics dataset which contains mz and rt information from xcms, mzMine or any other software, which is easy enough for most of the users who want to do data preparation and statistical  analysis. You can see the help document in the MetCleaning. Thanks

**Comment by lawremi** [comment]
I was proposing to support the in-memory xcmsSet data structure as input.

**Comment by jaspershen** [comment]
Thank you for your suggestion. In the next version, I will consider to support xcmsSet data structure as input. In this version, because the input mode is easy enough for most of users (my teammates and friends have used it for about three months), so I don't want to change its input mode. Do you think is that OK?
Thanks

**Comment by lawremi** [comment]
No, I don't, because then you'll probably never change it, since users will just go along with it, busy with their work and not thinking about how things could be easier. Sorry, that might sound cynical but it's motivated by idealism.

**Comment by jaspershen** [comment]
OK, I think it will take me a lot of time to learn to how to use xcms.......In fact, I don't think it is easier by using the xcmsSet.
Thanks again.

**Comment by jaspershen** [comment]
Hi, how can I close this issue and submit it again?
Thanks

**Comment by jaspershen** [comment]
Hello, I have change the package. So can you review it again?
Thank you very much.

**Comment by LiNk-NY** [comment]
Hi @jaspershen 
Can you bump the version for the package to be rebuilt?

**Comment by jaspershen** [comment]
Hi, thank your for your reply. And the version of package has been changed to 0.99.1.
Thank you very much

**Comment by jaspershen** [comment]
Hi. Can you review my new version package? I have changed it to version 0.99.1.
Thank you very much!
Xiaotao

**Comment by LiNk-NY** [comment]
Hi Xiaotao @jaspershen,
I don't see any SPB build history for a recent version of the package.
It may be possible that you have to create a webhook again for the build system to pick it up.
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Xiaotao @jaspershen, 
Please re-establish the webhook for your package. 
See this [webhook link](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) for more details. 

Regards,
Marcel

**Comment by jaspershen** [comment]
Hi Marcel, @LiNk-NY 
Thank you very much for your reply and guide. I have re-established the webhook for my package-MetCleaning according to the user guide. 
Best regards
Xiaotao

**Comment by LiNk-NY** [comment]
Hi @jaspershen, 
There are a few issues with the `check` on your package: 

- [ ]  Undefined global variables/functions 
```
Undefined global functions or variables:
  qc qcorder sampleorder
```
- [ ] The package size should not exceed 15 Mb. 
- [ ] The package vignette doesn't seem to be building. 
- [ ] The documentation should have more examples. 
- [ ] Maintainer must subscribe to the bioc-devel mailing list. [Subscribe here](https://stat.ethz.ch/mailman/listinfo/bioc-devel)

Regards,
Marcel

**Comment by jaspershen** [comment]
Hi @LiNk-NY 
Thank you for your reversion. I am fixing those bugs now. It may take me several days, because I don't understand why some issues  appear. Fot the errores which apper, I have some questions
(1) The vignette is built using devtools package, so I don't know why this is an error?
(2) The package is more than 15M because the demo data is very large, because this package is used to process large-scale metabolomics data. So I don't know shouled I remove this demo data?
(3) I am writing examples for documentation to make sure that more than 80% functions have examples.
(4) I have registered in the bioc-devel  and added my e-mail address in the mailing list.
I will fix all those error this week and re-submit it again. 
Thanks again for you reversion and guide.
Best regards,
XIaotao

**Comment by LiNk-NY** [comment]
Hi Xiaotao @jaspershen, 

I hope to see the changes soon. To answer your questions: 

1. I checked your package locally and I didn't get that error. Perhaps it's a build system hiccup. We will see once you make changes to your package and bump the version. Ignore that error for now. 
2. You can run your examples on a smaller dataset. Your data does not have to be so big for the examples.
3. Good.
4. Good. 

Please keep in mind that you should have runnable code in your vignette. Please don't create a vignette with all code chunks set to `eval = FALSE`. Set them to `eval = TRUE` for most chunks unless you have a good reason for why they should not be evaluated. Thanks.

Regards,
Marcel

**Comment by jaspershen** [comment]
HI @LiNk-NY 
Thank you very much. All of the error will be fixed and I will be resubmit it today.
Thanks again.
Regards
Xiaotao

**Comment by jaspershen** [comment]
Hi @LiNk-NY 
I have fixed all the errors and warnings which I got from BiocCheck in local. 
(1) More than 80% of exported functions have runable examples.
(2) The demo data is less than 1 M now.
(3) All  code chunks have been set to eval = TRUE.
(4) My email address-shenxt@sioc.ac.cn has been added in the bioc-devel mailing list.
I have changed the version to 0.99.3 and pushed it to github.
Thank you very much.
Best regards
Xiaotao

**Comment by LiNk-NY** [comment]
Hi Jasper @jaspershen, 
Thank you for submitting `MetCleaning` to Biconductor. 
Please see the review below. 

----

## MetCleaning #227

`MetCleaning` provides several tools for working with metabolomics data
including pre-processing steps and analysis.

### Major

#### Functionality & Integration

* Your package doesn't seem to work well with Bioconductor infrastructure
already in place. There are at least a couple of packages that work with the
same data type as mentioned by @lawremi. Please strongly consider making it
easier for your package to work well with the existing Bioconductor software.

* It seems like you don't use any of the S4 classes and methods [see here]()
for your package. You could make use of this system in order to create a more
robust class with a formal definition and validity checks. 

* Without a formal class definition, it is harder to extend your class.

[see here]: http://www.bioconductor.org/developers/package-guidelines/#classes

#### Grammar 

* Avoid `1:n` style iterations [more info]()
* Avoid the creation of files without the user's explicit consent
* Related to above: Add argument for the file location of the created files  
* Argument names should be short and to the point `ordered.qc` instead of
`qc.has.order`.
* Please add a default path argument (i.e., `"."`) rather than NULL to avoid
doing `path <- getwd()`
* Please be descriptive and informative when documenting your functions
* Avoid using `donttest` flags in your examples. Your examples should be runnable


[more info]: (http://www.bioconductor.org/developers/how-to/efficient-code/#vectorize)

#### Structure

* `MetFlowData` should be a formal S4 class with a constructor function and
accessors - your operations rely to much on data at a specific index rather
than an imposed structure that the S4 system provides
* Avoid the repetition in code (e.g., in `ExportData` function: `hasQC`
should just save `qc.info`)
* Validity checks for the `MetFlowData` class not available


#### Vignettes

* Please add more runnable examples in the vignette
* Avoid using static images in the vignette
* With the amount of functionality you provide, you should have several vignettes
showcasing what your functions do to pre-process and analyze data
* Pick one output type in the vignette, preferably `html_document` 

#### Unit Tests

* Please add unit tests in order to ensure robust code

### Minor

#### Grammar 

* Remove excitement in error messages (`!!!`)

#### Formatting 

* Your code should not go over 80 columns, it should be easy to ready and
come back to when bugs come up
* Function lengths should be minimal
* Functions should only acheive one objective and not try to do too much

Regards,
Marcel

**Comment by jaspershen** [comment]
Dear Marcel,
Thank your very much for your review of my package. According to your advices, I have re-write the package today. The detailed information is listed below:
**Major**
**Functionality & Integration**
(1) My package is used to do pre-processing of larege-scale metabolomics data. 
(2) I have changed MetFlowData to S4 class.
(3) The MetFlowData has been changed to S4 class.
**Grammar**
(1) The 1:n style iteration have been rmoved.
(2,3) MetCleaning do several processing and output results for each process, so the folders shouled be created to save results. It make the results more clear.
(4) According to your suggestion, I have changed the argument names which are not clear.
(5) All the path <- NULL have been changed according to your suggestion. Thanks.
(6) I have re-written some uncaler documents of functions.
(7) When running MetCleaning and MetStat, some processings should be type the selection, for example, when doing PLS-DA, the best component number should be selected by users. So, when I remove the "donttest" from the examples of MetCleaning and MetStat, there is a error when using Build Check. I find a lot of solutions for it in goodle, but I didn't find the solution methods. I am sorry about it. But the examples of MetCleaning and MetStat can be runable when I paste them manually.
**Structure**
(1) The MetFlowData has been changed to S4 class.
(2) This has been changed.
(3) MetFlowData has been changed to S4 calss, so I think this may be solved.
**Size**
(1) All the R scripts are in the "R" folder. and I am sure the packge was built following the gudelines.
**Vignettes**
(1) The most important functions in MetCleaning are MetCleaning and MetStat, the runable examples of them have been provided in the vignette. Other exported functions such as SXTpate are not useful for users, so their examples are not provided.
(2) The workflow and data organization are significant for user to understant this package and usage. So they are remained, other 6 figures are removed from the vignette.
(3) Only MetCleaning and MetStat are useful for users who want to do data processing and statistical analysis. So one vignette is enough to provide the usage of them.
(4) I am sorry about it , but I don't understand how to pick htm_document of vignette? I will be grateful if I can get help. Thanks.
**Unit Tests**
(1) The unit tests has been added into the package.

**Minor**
**Grammar**
(1) The excitement in error messages (!!!) have been removed.
**Formatting**
(1) Most of code which go over 80 column have been changed.
(2) I checked the longest functions and removed the space line from it. And all the functions only do one project.

The version has been changed to 0.99.4 and the package has been pushed to github.
Thanks again for you review and advicements！
Regards
Xiaotao

**Comment by LiNk-NY** [comment]
Hi Xiaotao, @jaspershen 

A few of the points I mentioned in the review were not addressed. 

The major point about integration with Bioconductor is still lacking and there seems to be no effort on your part to bridge your software with Bioconductor. You may wish to not make any changes in that front but keep in mind you are submitting your software to Bioconductor so it is expected in every submission to inter-operate with, enhance, or use existing Bioconductor software. This is a major factor in the review process. 

It's good that you're using S4 but you need to make sure that your `MetFlowData` class has a constructor function that does some checks before creating the class. You may also want to include some validity checks to make sure that data inside the class are in order needed. 
You would have to create accessor method functions so to avoid the use of `@` throughout your functions. Usually these functions have the same name as the slot in the object. 

Reminder: Avoid the use of `.` in function names. 

Refer to: http://bioconductor.org/developers/package-guidelines/#classes

Some points were not entirely addressed: 

* `1:n` style iterations
* `path = NULL` arguments
* Documentation for some arguments is not descriptive (e.g., `@param MetFlowData`)
* `write.csv` is used extensively, please don't create files unless the user asks to create files. Create some argument for ensuring this. 
* All your exported functions should be testable. You can select defaults for the examples and still run them. 

* Don't export functions that users will not be using. Keep those un-exported and available only to you as the developer. 

For the vignette: Select `html_document` as the only value for `output:`. 
Please make the `vignette:` value as

```
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
```

If find it difficult to see how a user would want to use a function with more than 20+ arguments as in `MetFlowData`.  

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Jasper @jaspershen,

Do you have any updates on making your package compatible with the Bioconductor ecosystem?
Otherwise, I'd be forced to close the issue.

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Your issue has been closed due to inactivity. To submit your **revised** package to Bioconductor, please create another issue. Thank you.
-Marcel
