### ISSUE TITLE
biodbChebi (an extension package of biodb package)

### ISSUE THREAD

**Issue by pkrog** [Bioconductor/Contributions#2283]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pkrog/biodbChebi

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Pierrick, @pkrog 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# biodbChebi #2283

* Perhaps the package can benefit from an API layer that avoids using
`chebi$X`?

## DESCRIPTION

* Please keep the `Description` field at maximum 80 character width.
* Looks good.

## NAMESPACE

* Looks good.

## vignettes

* Please update the vignette to use the proper database name rather than `Foo`.
* Use a more descriptive contructor class name (instead of `newInst`).
* If possible, avoid using `vapply` and provide a helper function to facilitate
extraction of entry fields.
* Vignette looks good and comprehensive with examples.

## R

* Indent functions so that the code is easier to read inside the reference
class.
* The `concatenate` argument is not used in `doGetEntryContentRequest`.
* Consider abstracting functions and using a single function that combines
functions in lines 340-370 in `R/ChebiConn.R`.

## /

* Consider moving `yml`, `R_front`, and `Makefile` to another folder.
* Update the `README.md` file.

**Comment by pkrog** [comment]
Hi @LiNk-NY ,

Please find my answers below.

> Hi Pierrick, @pkrog
> 
> Thank you for your submission.
> Please see the review below.
> 
> Best regards,
> Marcel
> # biodbChebi #2283
> 
>     * Perhaps the package can benefit from an API layer that avoids using
>       `chebi$X`?
> 
The R6 OOP model, is the one used inside Bioconductor *biodb* package, so this is the same inside *biodbChebi*, which is just a *biodb* extension.
So, no, there will not be an flat API for *biodbChebi*.

> 
> ## DESCRIPTION
> 
>     * Please keep the `Description` field at maximum 80 character width.
>
Have the rules changed ? My *biodb* package has a description field of 470 characters and gave no issues. I remember on the contrary that BiocCheck complains if the description field is too short.

>     * Looks good.
> 
> 
> ## NAMESPACE
> 
>     * Looks good.
> 
> 
> ## vignettes
> 
>     * Please update the vignette to use the proper database name rather than `Foo`.
> 
Corrected, thanks.

>     * Use a more descriptive contructor class name (instead of `newInst`).
> 
`newInst()` is an helper function for instantiating the main class of the *biodb* package. It simplifies the process of using the *biodb* package.

>     * If possible, avoid using `vapply` and provide a helper function to facilitate
>       extraction of entry fields.
>
Changed example.
 
>     * Vignette looks good and comprehensive with examples.
> 
> 
> ## R
> 
>     * Indent functions so that the code is easier to read inside the reference
>       class.
> 
Due to the width limit of 80 characters, it would be a huge waste of place, and make functions less readable.
As for the separation between public and private methods, I think this is quite clear in R6.

>     * The `concatenate` argument is not used in `doGetEntryContentRequest`.
>
It is not used inside *biodbChebi*, but this is a abstract method declared inside the *BiodbConn* abstract class of the *biodb* package from which inherits *ChebiConn*.
I know there is no such thing as abstract classes or methods in R6, but I try to respect the paradigm nonetheless.
 
>     * Consider abstracting functions and using a single function that combines
>       functions in lines 340-370 in `R/ChebiConn.R`.
> 
Sorry, I do not see your point. Combining different features together is not abstracting.
Those `do*()` methods are realizations of abstract methods from the `BiodbConn` abstract class from *biodb* package anyway, and fulfill a specific goal of implementing a connector for the *biodb* framework.

> 
> ## /
> 
>     * Consider moving `yml`, `R_front`, and `Makefile` to another folder.
>
Those files have to be there for the *biodb* framework. This is the same for all *boidb* extension packages (*biodbUniprot*, *biodbKegg*, *biodbHmdb*, etc).
Those files are ignored during the build anyway (see `.Rbuildignore`).
 
>     * Update the `README.md` file.
Done, thanks.

**Comment by LiNk-NY** [comment]
Hi Perrick, @pkrog 

Please see the responses below. 

Best,
Marcel

---

> > ## DESCRIPTION
> > ```
> > * Please keep the `Description` field at maximum 80 character width.
> > ```
> 
> Have the rules changed ? My _biodb_ package has a description field of 470 characters and gave no issues. I remember on the contrary that BiocCheck complains if the description field is too short.
> 

I am referring to the width limit rather than the character limit.

> >   
> > ## R
> > ```
> > * Indent functions so that the code is easier to read inside the reference
> >   class.
> > ```
> 
> Due to the width limit of 80 characters, it would be a huge waste of place, and make functions less readable. As for the separation between public and private methods, I think this is quite clear in R6.
>

I disagree. I did not realize that those elements were part of the R6 class because they were not indented.
Ultimately, you will maintain your code but from a reviewer's perspective, the indentation could
use improvement. 
 
> > ```
> > * Consider abstracting functions and using a single function that combines
> >   functions in lines 340-370 in `R/ChebiConn.R`.
> > ```
> 
> Sorry, I do not see your point. Combining different features together is not abstracting. Those `do*()` methods are realizations of abstract methods from the `BiodbConn` abstract class from _biodb_ package anyway, and fulfill a specific goal of implementing a connector for the _biodb_ framework.
> 

The procedures in those functions are the same. Take a character vector and send them to `BiodbUrl`.
This can be generalized but I realize it may be difficult.

**Comment by pkrog** [comment]
> > > ## DESCRIPTION
> > > ```
> > > * Please keep the `Description` field at maximum 80 character width.
> > > ```
> > 
> > 
> > Have the rules changed ? My _biodb_ package has a description field of 470 characters and gave no issues. I remember on the contrary that BiocCheck complains if the description field is too short.
> 
> I am referring to the width limit rather than the character limit.
>
I still do not understand what you want. Do you want me to write the description field on multiple lines, each with a maximum width of 80 chars?
 
> > > ## R
> > > ```
> > > * Indent functions so that the code is easier to read inside the reference
> > >   class.
> > > ```
> > 
> > 
> > Due to the width limit of 80 characters, it would be a huge waste of place, and make functions less readable. As for the separation between public and private methods, I think this is quite clear in R6.
> 
> I disagree. I did not realize that those elements were part of the R6 class because they were not indented. Ultimately, you will maintain your code but from a reviewer's perspective, the indentation could use improvement.
>
Sorry, but I'm not going to indent this code. This is my style of coding, I really think it is clearer. What I can do is emphasize the public and private parts of the R6 Class with comment lines like if that can help you :
```
################################################################
# PUBLIC MEMBERS AND METHODS
################################################################
...

################################################################
# PRIVATE MEMBERS AND METHODS
################################################################
...
```
 
> > > ```
> > > * Consider abstracting functions and using a single function that combines
> > >   functions in lines 340-370 in `R/ChebiConn.R`.
> > > ```
> > 
> > 
> > Sorry, I do not see your point. Combining different features together is not abstracting. Those `do*()` methods are realizations of abstract methods from the `BiodbConn` abstract class from _biodb_ package anyway, and fulfill a specific goal of implementing a connector for the _biodb_ framework.
> 
> The procedures in those functions are the same. Take a character vector and send them to `BiodbUrl`. This can be generalized but I realize it may be difficult.
This is not difficult. It just does not make sense. The two functions are different. They just happen to use both BiodbUrl. It is like if you had two methods a() and b() that both used file.path(). The fact that they both use file.path() is not sufficient to factorize their code.
Both functions doGetEntryContentRequest() and doGetEntryPageUrl() are overriding abstract methods of a mother abstract class, they both need to exist and it happens that they both do similar calls to BiodbUrl(). This is classic OOP.

**Comment by LiNk-NY** [comment]
Hi Pierrick, 

Please see the responses below. 

Best regards,
Marcel

---

> > 
> > I am referring to the width limit rather than the character limit.
> 
> I still do not understand what you want. Do you want me to write the description field on multiple lines, each with a maximum width of 80 chars?
> 

Sorry if that wasn't clear but yes, that is right. The Description field can span multiple lines to improve readability. 

> > > > ## R
> > > > ```
> > > > * Indent functions so that the code is easier to read inside the reference
> > > >   class.
> > > > ```
> > > 
> > > 
> > > Due to the width limit of 80 characters, it would be a huge waste of place, and make functions less readable. As for the separation between public and private methods, I think this is quite clear in R6.
> > 
> > 
> > I disagree. I did not realize that those elements were part of the R6 class because they were not indented. Ultimately, you will maintain your code but from a reviewer's perspective, the indentation could use improvement.
> 
> Sorry, but I'm not going to indent this code. This is my style of coding, I really think it is clearer. What I can do is emphasize the public and private parts of the R6 Class with comment lines like if that can help you :
> 
> ```
> ################################################################
> # PUBLIC MEMBERS AND METHODS
> ################################################################
> ...
> 
> ################################################################
> # PRIVATE MEMBERS AND METHODS
> ################################################################
> ...
> ```
> 

Yes, that would be helpful. 

> > > > ```
> > > > * Consider abstracting functions and using a single function that combines
> > > >   functions in lines 340-370 in `R/ChebiConn.R`.
> > > > ```
> > > 
> > > 
> > > Sorry, I do not see your point. Combining different features together is not abstracting. Those `do*()` methods are realizations of abstract methods from the `BiodbConn` abstract class from _biodb_ package anyway, and fulfill a specific goal of implementing a connector for the _biodb_ framework.
> > 
> > 
> > The procedures in those functions are the same. Take a character vector and send them to `BiodbUrl`. This can be generalized but I realize it may be difficult.
> > This is not difficult. It just does not make sense. The two functions are different. They just happen to use both BiodbUrl. It is like if you had two methods a() and b() that both used file.path(). The fact that they both use file.path() is not sufficient to factorize their code.
> > Both functions doGetEntryContentRequest() and doGetEntryPageUrl() are overriding abstract methods of a mother abstract class, they both need to exist and it happens that they both do similar calls to BiodbUrl(). This is classic OOP.

I'm referring to the bodies of the functions and not the functions themselves. It makes sense to create a helper function for a procedure that is repeated in many functions. For time's sake, the functions can be left as is. 

* Note that `filterIdsOnMassRange` is using the copy and append method in a `for` loop which can impact performance. Consider using the allocate and fill method. 

Thank you for your contribution.

**Comment by pkrog** [comment]
I've done the corrections, at the exception of the helper functions since it should be written inside the biodb package. I will add an issue about that.

**Comment by LiNk-NY** [comment]
Hi Pierrick, @pkrog 
Thanks for making those changes. 
Please keep in mind the above bullet point as you continue to improve your package. 
Thank you for your contribution. 
Best regards,
Marcel

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pkrog.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("biodbChebi")`. The package 'landing page' will be created at

https://bioconductor.org/packages/biodbChebi

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
