### ISSUE TITLE
biodbUniprot (biodb extension package)

### ISSUE THREAD

**Issue by pkrog** [Bioconductor/Contributions#2285]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pkrog/biodbUniprot

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
Please fix the errors and warnings to meet the requirement of review process. If you need any help, please let me known or ask help in develop mailing list.

**Comment by pkrog** [comment]
Hi @jianhong ,
Yes, thanks, I'm on it. Just met a strange connection error to the Uniprot database that happens only on Windows.

**Comment by jianhong** [comment]
Try to write an error handler for that part and cross your finger for a good luck for next build.

**Comment by pkrog** [comment]
The error has been solved inside package `biodb` 1.1.9 which should be built this evening (Paris time). Then I will run check on `biodbUniprot` locally and push a new version.

**Comment by vjcitn** [comment]
This package is in good shape as software.  As a tool for users, I think there are some basic improvements
that should be considered.

Here's a snippet from the vignette:
```
conn <- mybiodb$getFactory()$createConn('uniprot')
## Loading required package: biodbUniprot
4Using the query web service
The method wsQuery() implements the request to the query web service, and the parsing of its output.

To get the raw results returned by the UniProt server, run the following code:

conn$wsQuery('reviewed:yes AND organism:9606', columns=c('id', 'entry name'),
             limit=2, retfmt='plain')
...
```
It is uncommon for user code to involve multiple `$`.  Of course it can be done, but it is clumsy.

A different approach is to wrap the object/method operations in functions that
can be documented.  Here's an example:

```
#' wrapper for entryIdsToDataframe for uniprot, working from gene symbols
#' syms character() vector of gene symbols
#' fields character() vector of fields to return; [tell how to determine valid entries]
#' ignore.nonalphanum logical(1) [describe purpose]
#' partial.match logical(1) [describe purpose]
#' @examples
#' bdb_syms2uniprot(c("GCSF", "GCSF")) # runs quickly, tests vector input; BRCA2 does not run quickly
#' @export
bdb_syms2uniprot = function(syms, fields=c('accession', 'gene.symbol'), ignore.nonalphanum=TRUE,
    partial.match=TRUE) {
  mybiodb <- biodb::newInst()                         # setup
  con = mybiodb$getFactory()$createConn('uniprot')    # get connection
  on.exit(mybiodb$terminate())                        # tear down when done
  d = unique(unlist(lapply(syms, function(x) con$geneSymbolToUniprotIds(x,   # do I need Sys.sleep(1) in loop?
         ignore.nonalphanum=ignore.nonalphanum, partial.match=partial.match)))) # issue queries
  mybiodb$entryIdsToDataframe(d, 'uniprot', fields=fields)
}
```
This example shows a variety of ways in which the suite of packages might be improved, and
ways in which the design might be queried.  

- It is typical for R functions to be vectorized.  If we make the user work with `$geneSymbolToUniprotIds` the user has to handle the iteration -- **OK, this is wrong.  the method could be called geneSymbolsToUniprotIds and could process a vector of IDs, if I understand correctly.  I was tricked by the singular aspect of method name.**. However, there really should be some attention paid to input validation.  As I note below the service seems to hang with BRCA2 as an input.  Is it invalid, or is the system hanging?  If a vector of many symbols is provided, can you provide some information on progress of resolution?
- the R6-based design conveys substantial functionality but most is not documented in a meaningful way.  From `help(BiodbMain)`:

```
Methods:

  Public methods:

         • 'BiodbMain$new()'

         • 'BiodbMain$terminate()'

         • 'BiodbMain$loadDefinitions()'

         • 'BiodbMain$getConfig()'

         • 'BiodbMain$getPersistentCache()'
...
```
Did you use an R6 class generator to produce this package?  If so, which one?  It should include tooling to improve method documentation.

- My last comment for now is that the example above (specifically `con = mybiodb$getFactory()$createConn('uniprot')`) shows that there are opportunities for parameterizing activities that will take place among the various biodb* contributions.  Would maintainability be enhanced by concentrating some code for some common tasks in the base biodb package, and reusing it?  Maybe you don't even need provider-specific packages.

**Comment by vjcitn** [comment]
Why does the converter seem to hang with this input?
```
> myb = biodb::newInst()
INFO  [11:38:15.750] Loading definitions from package biodb version 1.1.11. 
INFO  [11:38:15.969] Loading definitions from package biodbChebi version 0.99.4. 
INFO  [11:38:15.982] Loading definitions from package biodbHmdb version 0.99.0. 
INFO  [11:38:15.994] Loading definitions from package biodbKegg version 0.99.1. 
INFO  [11:38:16.013] Loading definitions from package biodbUniprot version 0.99.2. 
> conn = myb$getFactory()$createConn('uniprot')
> ids <- conn$geneSymbolToUniprotIds('BRCA2', ignore.nonalphanum=TRUE)
^C

Enter a frame number, or 0 to exit   

 1: conn$geneSymbolToUniprotIds("BRCA2", ignore.nonalphanum = TRUE)
 2: private$filterResults(x, gene = gene, ignore.nonalphanum = ignore.nonalphan
 3: Filter(gene_matches, x)
 4: unlist(lapply(x, f))
 5: lapply(x, f)
 6: FUN(X[[i]], ...)
 7: self$getEntry(id)
 8: private$bdb$getFactory()$getEntry(self$getId(), id = id, drop = drop)
 9: private$loadEntries(conn$getId(), missing.ids, drop = FALSE)
10: self$createEntryFromContent(conn$getId(), content = content, drop = drop)
11: entry$parseContent(single.content)
12: private$doParseFieldsStep2(parsed.content)
13: self$setFieldValue("aa.seq", gsub("\\n", "", self$getFieldValue("aa.seq")))
14: field.def$correctValue(value)
15: self$isVector()
16: lifecycle::deprecate_soft("1.0.0", "isVector()", "isAtomic()")
17: signal_stage("deprecated", what)
18: spec(what, env = env)
19: spec_fn(what$call)
20: expr_deparse(fn)
21: new_quo_deparser(width = width)
22: new_lines(width = width, deparser = quo_deparse)
23: stopifnot(is_integerish(width, n = 1))

Selection: 0
> myb$terminate()
INFO  [11:39:57.786] Closing BiodbMain instance... 
INFO  [11:39:57.791] Connector "uniprot" deleted. 
```

**Comment by vjcitn** [comment]
While biodbChebi was accepted, we can see that at this time it is in an error state on the build system.  Please attend to this.  @lshep

**Comment by pkrog** [comment]
Hi @vjcitn , thanks for your reviews and the fact that you've be assigned to my different biodb* packages.

About the `$` operator and the wrapping of the object/method operations into functions:
 * The use of R6 throughout the main biodb package impose the use of this operator. I know it is not natural for most R language users, since my colleagues, who are the main users of my libraries, had to learn it.
 * The choice of R6 is due to the necessity to get single instances of connectors and the singleton `biodb::BiodbRequestScheduler` in biodb, which is responsible for handling the sending of all requests. This class ensures, for instance, that the maximum request frequency for each database server is respected (as long as you use only one instance of `biodb::BiodbMain` in your package).
 * I will consider helper functions that hide the use of R6, when it is possible and desirable. I've already wrote one (`biodb::newInst()`) for creating a new instance of `biodb::BiodbMain`.

**Comment by pkrog** [comment]
About the call to `biodbUniprot::UniprotConn::geneSymbolToUniprotIds()`:
 * The method is slow when it has to download many entries from UniProt, each entry having to be downloaded using a single request. The limit of request to UniProt is 3 per second.
 * I have added a progress bar to this method, so the user is no more in the dark when running it.
 * When running the method a second time with the exact same parameters, the cache will be used and it will run faster.
 * Also you can use the parameter `max.results` and set it to a low value like 3, to get a fast result and check the output.
 * I have tried to explain all that in the vignette.

**Comment by pkrog** [comment]
About the documentation, this is way R6 classes are documented with roxygen2. I do not think I can improve it. There is a list of the methods at the start of the help page, then each method is detailed separately.

**Comment by pkrog** [comment]
About your last point ("parameterizing activities"), I am not sure to understand.
If you are talking about factorizing code, this is the whole point of this architecture, but not only.
The main biodb package is more like a development framework. It factorizes many different aspects, but also helps to write a new extension package for implementing a connector to a database (it can generate the skeleton of the new package, for instance).
One goal of biodb, maybe the main goal, is to facilitate the writing of new connectors, and interactions between those connectors. So, yes, I need to have a package for each database.
Also, the modular aspect is an advantage for maintainability.

**Comment by vjcitn** [comment]
OK, thanks for your comments.  Don't forget to push changes to git.bioconductor.org

**Comment by vjcitn** [comment]
Concerning the R6 class/method documentation see https://www.tidyverse.org/blog/2019/11/roxygen2-7-0-0/ ... I think you can introduce some helpful guidance for users following these steps.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pkrog.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("biodbUniprot")`. The package 'landing page' will be created at

https://bioconductor.org/packages/biodbUniprot

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
