### ISSUE TITLE
epimutacions

### ISSUE THREAD

**Issue by LeireAbarrategui** [Bioconductor/Contributions#2294]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/isglobal-brge/epimutacions

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LeireAbarrategui** [comment]
AdditionalPackage: https://github.com/LeireAbarrategui/epimutacionsData

**Comment by vjcitn** [comment]
epimutacions has very large files in inst/extdata.  They have to come out before processing can proceed

**Comment by jianhong** [comment]
Please subscribe the develop mailing list and bump the version. Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

**Comment by LeireAbarrategui** [comment]
Hello, my package Imports some packages that are only available on GitHub.  Is there any possibility of adding them? 

Thank you 

Leire

**Comment by jianhong** [comment]
Currently remote package are not allowed. 
See: https://contributions.bioconductor.org/description.html?q=Remotes#depends-imports-suggests-enhances
Please try to submit the remote package also. If they are not essential,  you may want to put them as download if needed.

**Comment by LeireAbarrategui** [comment]
AdditionalPackage: https://github.com/LeireAbarrategui/epimutacionsData

**Comment by LeireAbarrategui** [comment]
Hello, 

I am subscribed to bio-devel mailing list but I still have the error saying that I am not subscribed. How can I solve it?

**Comment by jianhong** [comment]
# Package epimutations Review

The package is in good shape but there are lots of issues need to be fixed.

## General package development
- [ ] Package can not passes `BiocCheck::BiocCheck()`, `BiocCheck::BiocCheckGitClone()`.
- [ ] README file.
Please include Bioconductor installation instructions using BiocManager.

## The DESCRIPTION file

- [ ] The `Description` field in the DESCRIPTION is made up
      by less than 3 sentences. Please consider expanding this
      field, and structure it as a full paragraph

- [ ] `IlluminaHumanMethylation450kanno.ilmn12.hg19` is missing from Suggests

## The NEWS file

- [ ] The News file is a template, not real.

## Package data

- [ ] Raw data in `data/` need documentation of data source if available.

## Documentation

- [ ] Multiple disabled code blocks present in vignette.
- [ ] Error when run epimutations.Rmd line 292, line 317-320,
- [ ] Try to provide estimate running time for line 207, line 329, line 429. 
- [ ] Please include Bioconductor installation instructions using BiocManager.
- [ ] The `vignettes/` directory contains only vignette file(s) and necessary static images.
epimutations.html is not required for vignettes. Please move it.
- [ ] Error or Typos in vignetters:
    * Contain non-ASCII at epimutations.Rmd line 263.
    * Missing ")" at epimutations.Rmd line 292
    * Missing newline at epimutations.Rmd line 437 before "```"

- [ ] Package name and the main function name are same. The help page does not contain the help information for the package.
- [ ] Packages unavailable to check Rd xrefs: ‘CompQuadForm’, ‘car’
- [ ] Usage of dontrun{} / donttest{} found in man page examples in the following files:
    * epi_preprocess.Rd      

## Unit tests

- [ ] Consider adding unit tests. We strongly encourage them. See
 http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ]  Avoid sapply(); use vapply()
Found in files:
       * R/annotate_cpg.R (line 62, column 30)
       * R/epimutations.R (line 326, column 21)
       * R/mlmtst.R (line 111, column 40)  
- [ ] Avoid 1:...; use seq_len() or seq_along()
Found in files:
      *  epimutations.R (line 328, column 31)
      *  mlm.R (line 228, column 39)
      *  mlmtst.R (line 58, column 15)
      *  mlmtst.R (line 111, column 25)
- [ ] Avoid the use of 'paste' in condition signals
Found in files:
      *  R/annotate_cpg.R (line 36, column 17)
      *  R/annotate_cpg.R (line 48, column 17)
      *  R/annotate_cpg.R (line 53, column 17)
      *  R/epimutations.R (line 176, column 25)
      *  R/epimutations.R (line 200, column 31)   
- [ ] Consider to use `message()`, `warning`, `stop` instead of `cat` in print.MLM
- [ ] Consider clarifying how 1 object(s) are initialized.
    *  epi_quantile  (chr, pos, line 83) , please add them to globalVariables
- [ ] Please try to keep to an 80 character limit as the code will otherwise be
difficult to read when displayed online. 
- [ ] `::` is not suggestted in R code. Please import the functions.
- [ ] Function contain code repetition.
    * `res_mahdistmcd`, `res_isoforest`, `res_manova`, and `res_mlm`
    * `filter_manova`, and  `filter_mlm`
- [ ] Function arguments should be tested for validity, eg 
    *  `N` in `epi_quantile`, if N is smaller than 2, line 117 will be broken. 
    * nrow of tab in `merge_records`.
    * gr class in `betas_sd_mean`,
    * and so on.

**Comment by lshep** [comment]
@LeireAbarrategui  may we expect updates soon?  We like to see progress and response to reviews within a 3-4 week time frame.

**Comment by jianhong** [comment]
# Package 'epimutacions' Review
The package passed check and build. It is in pretty good shape. However there are several things need to be fixed.

## The NAMESPACE file
- [ ] packages imported in DESCRIPTION but not in NAMESPACE.
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 11 import(CompQuadForm)
	* in line 16 import(stats)
- [ ] Try to remove `suggest` packages from import list.
    * in line 12 import(ExperimentHubData)
    * in line 13 import(IlluminaHumanMethylationEPICanno.ilm10b2.hg19)
    * in line 14 import(car)
    * in line 15 import(epimutacionsData)

## R code
- [ ] `::` is not suggested in source code unless you can make sure all the packages are imported.
	* In file R/add_ensemble_regulatory.R:
		+ at line 37 found '  mart <- biomaRt::useEnsembl(biomart = "regulation",'
		+ at line 39 found '  ensembl <- biomaRt::useDataset(dataset = "hsapiens_regulatory_feature", '
		+ at line 68 found '	bm <- biomaRt::getBM('
	* In file R/annotate_cpg.R:
		+ at line 38 found '	anno <- minfi::getAnnotation(db)'
		+ at line 83 found '	gene_mart <- biomaRt::useEnsembl(biomart = "ENSEMBL_MART_ENSEMBL", '
		+ at line 94 found '		omims <- biomaRt::getBM(mart = gene_mart,'
	* In file R/epi_beta.R:
		+ at line 45 found '  pvals <- purrr::pmap_dbl(list(betas_case, beta_params[, 1], '
		+ at line 48 found '                                    stats::pbeta(x, shape1, shape2))'
		+ at line 87 found '  s2 <- matrixStats::colVars(x, na.rm = TRUE)'
		+ at line 102 found '  cl <- bumphunter::clusterMaker(GenomeInfoDb::seqnames(regGR), '
		+ at line 103 found '                                 BiocGenerics::start(regGR), '
		+ at line 108 found '    data.frame(chromosome = as.character(GenomeInfoDb::seqnames(rang)), '
		+ at line 109 found '               start = BiocGenerics::start(rang), '
		+ at line 110 found '               end = BiocGenerics::end(rang),'
		+ at line 111 found '               sz = BiocGenerics::width(rang), cpg_n = length(cpgGR),'
	* In file R/epi_isoforest.R:
		+ at line 18 found '	iso <- isotree::isolation.forest(train, ntrees = ntrees)'
		+ at line 21 found '	score <- stats::predict(iso, test)'
	* In file R/epi_mahdistmcd.R:
		+ at line 29 found '	mcd <- robustbase::covMcd(mixture, nsamp = nsamp)'
	* In file R/epi_manova.R:
		+ at line 14 found '	mod <- stats::manova(mixture ~ model)'
		+ at line 64 found '  bump_out$adj_pvalue <- stats::p.adjust(bump_out$pvalue, '
	* In file R/epi_plot.R:
		+ at line 18 found '    betas <- minfi::getBeta(methy)'
		+ at line 19 found '    fd <- as.data.frame(SummarizedExperiment::rowRanges(methy))'
		+ at line 34 found '  gr <- GenomicRanges::makeGRangesFromDataFrame(fd)'
		+ at line 35 found '  S4Vectors::values(gr) <- betas'
		+ at line 150 found '                    colnames(GenomicRanges::elementMetadata(gr)))'
		+ at line 155 found '  betas <- as.data.frame(S4Vectors::values(gr))'
		+ at line 175 found '  beta_values <- reshape2::melt(df, id = c("seqnames", '
		+ at line 180 found '  mean <- reshape2::melt(mean, id = c("seqnames", '
		+ at line 186 found '  sd <- reshape2::melt(sd, id = c("seqnames", '
		+ at line 216 found '      TxDb.Hsapiens.UCSC.hg19.knownGene::TxDb.Hsapiens.UCSC.hg19.knownGene'
		+ at line 220 found '      TxDb.Hsapiens.UCSC.hg38.knownGene::TxDb.Hsapiens.UCSC.hg38.knownGene'
		+ at line 224 found '      TxDb.Hsapiens.UCSC.hg18.knownGene::TxDb.Hsapiens.UCSC.hg18.knownGene'
		+ at line 232 found '    all_genes <- GenomicFeatures::genes(txdb)'
		+ at line 233 found '    all_genes$symbol <- AnnotationDbi::mapIds(Homo.sapiens::Homo.sapiens, '
		+ at line 260 found '  cpgIslands <- Gviz::UcscTrack(genome = genome, '
		+ at line 276 found '  mySession <-  rtracklayer::browserSession("UCSC")'
		+ at line 277 found '  rtracklayer::genome(mySession) <- "hg19"'
		+ at line 278 found '  granges <- GenomicRanges::GRanges(chr, '
		+ at line 279 found '                                    IRanges::IRanges(from, to))'
		+ at line 282 found '  H3K27Ac <- rtracklayer::getTable('
		+ at line 283 found '                                    rtracklayer::ucscTableQuery(mySession, '
		+ at line 288 found '  H3K27Ac <- GenomicRanges::makeGRangesFromDataFrame(H3K27Ac)'
		+ at line 289 found '  S4Vectors::values(H3K27Ac) <- value '
		+ at line 290 found '  H3K27Ac <- Gviz::DataTrack(H3K27Ac, '
		+ at line 299 found '  H3K4Me3 <- rtracklayer::getTable('
		+ at line 300 found '                  rtracklayer::ucscTableQuery(mySession, '
		+ at line 305 found '  H3K4Me3 <- GenomicRanges::makeGRangesFromDataFrame(H3K4Me3)'
		+ at line 306 found '  S4Vectors::values(H3K4Me3) <- value '
		+ at line 307 found '  H3K4Me3 <- Gviz::DataTrack(H3K4Me3, '
		+ at line 317 found '    ah <- AnnotationHub::AnnotationHub()'
		+ at line 318 found '    H3K27Me3 <- AnnotationHub::query(ah , c("UCSC", "H3K27me3", "hg19"))'
		+ at line 319 found '    H3K27Me3 <- Gviz::DataTrack(H3K27Me3[["AH23260"]], '
	* In file R/epi_preprocess.R:
		+ at line 80 found '  targets <- minfi::read.metharray.sheet(base = cases_dir, '
		+ at line 84 found '    RGset_cases <- minfi::read.metharray.exp(base = cases_dir)'
		+ at line 86 found '    RGset_cases <- minfi::read.metharray.exp(targets = targets)'
		+ at line 97 found ' RGset <- minfi::combineArrays(reference_panel, RGset_cases,'
		+ at line 105 found '   Mset <- minfi::preprocessRaw(RGset)'
		+ at line 107 found '   Mset <-minfi::preprocessIllumina(RGset, '
		+ at line 115 found '   Mset <- minfi::preprocessSWAN(RGset, '
		+ at line 118 found '   GRset <- minfi::preprocessQuantile('
		+ at line 137 found '   Mset <- minfi::preprocessNoob(RGset, '
		+ at line 143 found '   GRset <- minfi::preprocessFunnorm(RGset, '
		+ at line 158 found '   GMset <- minfi::mapToGenome(Mset, '
		+ at line 160 found '   GRset <- minfi::ratioConvert(GMset, '
	* In file R/epimutations_one_leave_out.R:
		+ at line 86 found '                                       BPPARAM = BiocParallel::SerialParam(),'
		+ at line 97 found '                 BiocParallel::bplapply(colnames(methy), '
		+ at line 101 found '    epimutacions::epimutations(case_samples, '
	* In file R/epimutations.R:
		+ at line 135 found '  if(minfi::annotation(case_samples)[1] !='
		+ at line 136 found '     minfi::annotation(control_panel)[1] &'
		+ at line 137 found '     minfi::annotation(case_samples)[2] != '
		+ at line 138 found '     minfi::annotation(control_panel)[2]){'
		+ at line 178 found '  fd <- as.data.frame(GenomicRanges::granges(case_samples))'
		+ at line 181 found '  betas_case <- minfi::getBeta(case_samples)'
		+ at line 183 found '  betas_control <- minfi::getBeta(control_panel)'
		+ at line 229 found '      model <- stats::model.matrix(~status, status)'
		+ at line 233 found '        bumps <- bumphunter::bumphunter(object = betas, design = model,'
		+ at line 266 found '                threshold <- sqrt(stats::qchisq(p = 0.999975, '
		+ at line 376 found '                    GenomicRanges::makeGRangesFromDataFrame(fd_sub),'
		+ at line 413 found '        rstGR <- GenomicRanges::makeGRangesFromDataFrame(rst)'
		+ at line 415 found '        ensembldb::seqlevelsStyle(rstGR) <- "UCSC" '
		+ at line 418 found '        over <- GenomicRanges::findOverlaps(rstGR, candRegsGR)'
		+ at line 420 found '        ids <- names(candRegsGR[S4Vectors::to(over)])'
		+ at line 421 found '        cre <- candRegsGR[S4Vectors::to(over)]$CRE'
		+ at line 422 found '        cre_type <- candRegsGR[S4Vectors::to(over)]$CRE_type'
		+ at line 424 found '        rst$epi_region_id[S4Vectors::from(over)] <- ids'
		+ at line 425 found '        rst$CRE[S4Vectors::from(over)] <- cre'
		+ at line 426 found '        rst$CRE_type[S4Vectors::from(over)] <- cre_type'
		+ at line 432 found '      rst <- tibble::as_tibble(rst_c)'
	* In file R/get_candRegsGR.R:
		+ at line 11 found '  eh <- ExperimentHub::ExperimentHub()'
		+ at line 12 found '  AnnotationHub::query(eh, c("epimutacionsData"))'
	* In file R/globals.R:
		+ at line 1 found 'utils::globalVariables(c("chr", "pos", "cpg_n", "quantile", "start", '
	* In file R/mlm.R:
		+ at line 98 found '  mf[[1L]] <- quote(stats::model.frame)'
	* In file R/mlmtst.R:
		+ at line 104 found '    # In contrast to car::Anova, intercept '
	* In file R/plot_epimutations.R:
		+ at line 158 found '  plot_betas <- ggplot2::ggplot() + '
		+ at line 159 found '    ggplot2::geom_line(data = betas_sd_mean$beta_values, '
		+ at line 160 found '                       ggplot2::aes(x = start, '
		+ at line 165 found '    ggplot2::geom_point(data = betas_sd_mean$beta_values, '
		+ at line 166 found '                        ggplot2::aes(x = start, '
		+ at line 171 found '    ggplot2::geom_ribbon(data = betas_sd_mean$sd, '
		+ at line 172 found '                         ggplot2::aes(x = start,'
		+ at line 176 found '    ggplot2::geom_ribbon(data = betas_sd_mean$sd, '
		+ at line 177 found '                         ggplot2::aes(x = start,'
		+ at line 181 found '    ggplot2::geom_ribbon(data = betas_sd_mean$sd,'
		+ at line 182 found '                         ggplot2::aes(x = start,'
		+ at line 188 found '    ggplot2::geom_line(data = betas_sd_mean$mean, '
		+ at line 189 found '                       ggplot2::aes(x = start, '
		+ at line 192 found '    ggplot2::geom_point(data = betas_sd_mean$mean, '
		+ at line 193 found '                        ggplot2::aes(x = start, y = mean), '
		+ at line 197 found '    ggrepel::geom_text_repel() + '
		+ at line 198 found '    ggplot2::annotate(geom = "text", '
		+ at line 205 found '    ggplot2::lims(y = c(0,1)) +  '
		+ at line 206 found '    ggplot2::scale_colour_manual(name = "Status", values = colors) +'
		+ at line 207 found '    ggplot2::theme_bw() + '
		+ at line 208 found '    ggplot2::ggtitle(paste0(dmr$sample,": ", '
		+ at line 212 found '    ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5)) +'
		+ at line 213 found '    ggplot2::labs(x = "Coordinates") + '
		+ at line 214 found '    ggplot2::labs(y = "DNA methylation level")'
		+ at line 219 found '  ideo_track <- Gviz::IdeogramTrack(genome = genome, '
		+ at line 221 found '  genome_track <- Gviz::GenomeAxisTrack()'
		+ at line 223 found '  gene_track <- Gviz::GeneRegionTrack(genes, '
		+ at line 231 found '  tracks_Highlight <- Gviz::HighlightTrack(trackList = list(genome_track,'
		+ at line 254 found '      tracks_Highlight <- Gviz::HighlightTrack(trackList = '
		+ at line 270 found '      tracks_Highlight <- Gviz::HighlightTrack(trackList = '
		+ at line 292 found '  p2 <- grid::grid.grabExpr(Gviz::plotTracks(list(ideo_track, '
		+ at line 296 found '  gridExtra::grid.arrange(grobs = list(p1,p2), row=2)'
- [ ] Vectorize: no unnecessary `for` loops present.
	* In file R/epi_quantile.R:
		+ at line 123 found '      for(ii in seq(2, nrow(red_df))) {'
	* In file R/epimutations.R:
		+ at line 151 found '    for(i in seq_along(start)){'
		+ at line 191 found '      for(i in seq_along(chr)){'
	* In file R/mlm.R:
		+ at line 185 found '  for(i in seq(along = stats.l)) {'
		+ at line 186 found '    for(j in names(stats.l[[i]])){'
		+ at line 311 found '  for (i in zap.ind) xm[, i] <- zapsmall(xm[, i], digits)'
		+ at line 331 found '    for (i in which(r.ind)) Cf[, i] <- format(xm[, i], '
	* In file R/mlmtst.R:
		+ at line 85 found '    for (i in iterms) {'
		+ at line 110 found '      for (i in iterms){'
		+ at line 124 found '      for (i in iterms){'
		+ at line 138 found '        for (relative in relatives){'
- [ ] Remove unused code.
	* In file R/epimutations.R:
		+ at line 331 found '    #case <- betas[ , cas_sam[1], drop=FALSE]'
		+ at line 435 found '  #})'
	* In file R/mlm.R:
		+ at line 225 found '  #cat("\nCall:\n", paste(deparse(x$call), sep = "\n", collapse = "\n"), '
		+ at line 226 found '      #"\n\n", sep = "")'
		+ at line 227 found '  #cat("Type", x$type, "Sum of Squares\n\n")'
		+ at line 232 found '    #cat(heading, sep = "\n")'
		+ at line 253 found '    #cat(sprintf("%s observation%s deleted due to missingness\n", '
		+ at line 254 found '                #length(na), ifelse(length(na) > 1, "s", "")))'
	* In file R/mlmtst.R:
		+ at line 53 found '  df.e <- fit$df.residual # df.e <- (n-1) - sum(df)'
		+ at line 100 found '    V <- solve(crossprod(X))  # V = (X'X)^{-1}'
		+ at line 168 found '  # R2adj <- 1-( (1-R2)*(n-1) / df.e ) '
		+ at line 170 found '  # r2adj <- 1-( (1-r2)*(n-1) / df.e )'
	* In file R/plot_epimutations.R:
		+ at line 290 found '  #dev.new(width = 1080, height = 1350, unit = "px")'
## C and Fortran code
- [] `Makevars` and `Makefile` not within a package

**Comment by jianhong** [comment]
# Package 'epimutacions' Review
The package passed check and build.  It is almost there. However there are several things need to be fixed.

## R code
- [ ] `vapply` instead of `sapply`.
	* In file R/epi_quantile.R:
		+ at line 124 found '      red_df$cum2 <- c(red_df$cum[1], sapply(seq(2, nrow(red_df)), function(ii) {'
- [ ] `::` is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development.
- [ ] Functional programming: code repetition.
	* repetition in `epimutations` and `epimutations_one_leave_out`
		+ in epimutations
			- line 43:            "'")
			- line 44:    if (!requireNamespace("methods")) 
			- line 45:        stop("'methods' package not available")
			- line 46:    if (!requireNamespace("ensembldb")) 
			- line 47:        stop("'ensembldb' package not available")
		+ in epimutations_one_leave_out
			- line 7:        }
			- line 8:        if (!requireNamespace("methods")) 
			- line 9:            stop("'methods' package not available")
			- line 10:        if (!requireNamespace("BiocParallel")) 
			- line 11:            stop("'BiocParallel' package not available")
	* repetition in `plot_epimutations` and `UCSC_regulation`
		+ in plot_epimutations
			- line 27:    }
			- line 28:    if (!requireNamespace("grid")) 
			- line 29:        stop("'grid' package not available")
			- line 30:    if (!requireNamespace("gridExtra")) 
			- line 31:        stop("'gridExtra' package not available")
			- line 34:    if (!requireNamespace("Gviz")) 
			- line 35:        stop("'Gviz' package not available")
			- line 36:    if (!requireNamespace("grDevices")) 
			- line 37:        stop("'grDevices' package not available")
		+ in UCSC_regulation
			- line 2:{
			- line 3:    if (!requireNamespace("Gviz")) 
			- line 4:        stop("'Gviz' package not available")
			- line 5:    if (!requireNamespace("rtracklayer")) 
			- line 6:        stop("'rtracklayer' package not available")
            
- [ ]   NOTE: Avoid using '=' for assignment and use '<-' instead
Found in files:
  R/mlm.R (line 83, column 16)
- [ ] NOTE: Avoid 'suppressWarnings'/'*Messages' if possible (found
              2 times)
                suppressWarnings() in R/epimutations.R (line 321, column
              17)
                suppressMessages() in R/epimutations.R (line 231, column 7)
                
## Documentation
- [ ] NOTE: Usage of dontrun{} / donttest{} found in man page
examples.
11% of man pages use one of these cases.
Found in the following files:
  annotate_epimutations.Rd
  epi_preprocess.Rd
  epimutations_one_leave_out.Rd
  plot_epimutations.Rd

**Comment by LeireAbarrategui** [comment]
Hello, 

I need to load multiple namespaces at the same time to fix the code repetition. The solution is to use lapply. However,  in the comments before they have suggested using vapply instead of lapply. In this case, did not find the way to use vapply as the FUN results are NULL and the FUN.VALUE cannot be set as NULL. Would be possible to use lapply? Or is there any other solution to load multiple namespaces avoiding code repetition. Thank you.

**Comment by jianhong** [comment]
If it’s difficult to remove the repetition, you can keep it.

Jianhong

**Comment by LeireAbarrategui** [comment]
Hello, 

Would be possible to keep dontrun{} / donttest{} in some of the examples? As some of the examples may take too long to run. 

Thank you 

Leire

**Comment by jianhong** [comment]
Yes, but not too many.

Jianhong

**Comment by lshep** [comment]
Our windows builder was newly added and did not have the data package yet. I'm going to kick off a manual build of the data package so it can find it.

**Comment by LeireAbarrategui** [comment]
Hello, I would like to add some comments about some notes.

- Avoid 'suppressWarnings'/'*Messages' if possible (found 1times)
   suppressMessages() in R/epi_plot.R (line 240, column 5)
**Was suggested by devtools::check().**
-Usage of dontrun{} / donttest{} found in man page examples.
   3% of man pages use one of these cases.
   Found in the following files:
    epi_preprocess.Rd
**The example takes too long to run. That is the reason I used donttest{}**

**Comment by jianhong** [comment]
# Package 'epimutacionsData' Review
The package passed check and build. There are several small things need to be fixed.
## The DESCRIPTION file
- [ ] `Depends` field is not found in DESCRIPTION.
- [ ] R version is not clear in DESCRIPTION.
## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 2 import(ExperimentHub)
## General package development
- [ ] NOTE: Potential intermediate files found:
        vignettes/epimutacionsdata.html
## Documentation
- [ ] Vignette should have an *Introduction* section..
	* rmd file vignettes/epimutacionsData.Rmd

**Comment by jianhong** [comment]
# Package 'epimutacions' Review
The package passed check and build. It is almost there. 
## R development
- [ ] update NEWS.md to current version.
## C and Fortran code
- [ ] `Makevars` and `Makefile` not within a package when CPP version is lower than 0.11.0. It looks like you are using C only. If possible, rename .cpp to .c.

**Comment by LeireAbarrategui** [comment]
Hello, it is necessary to include the Makevars or Makefile file? or only optional?

**Comment by jianhong** [comment]
optional

**Comment by LeireAbarrategui** [comment]
Regarding your package review, I have changed the news file in the epimutacions package.  However, was not possible to make the other changes. I hope that is not a problem, as they are optional. 

Thank you 

Leire

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LeireAbarrategui.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("epimutacions")`. The package 'landing page' will be created at

https://bioconductor.org/packages/epimutacions

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LeireAbarrategui.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("epimutacionsData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/epimutacionsData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
