### ISSUE TITLE
MicrobiomeProfiler

### ISSUE THREAD

**Issue by mjchen1996** [Bioconductor/Contributions#2320]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YuLab-SMU/MicrobiomeProfiler

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by mjchen1996** [comment]
Hi, @lazappi , thank you for your assistance. I was just wondering if my package had under review queue?

**Comment by lazappi** [comment]
Hi @mjchen1996. As I'm sure you know it's super busy at the moment with everyone trying to get packages accepted for the upcoming release. I think yours is at the top of my list so hopefully not too long.

**Comment by mjchen1996** [comment]
Thank you for your reply.

**Comment by lazappi** [comment]
Hi @mjchen1996

Thanks for submitting **MicrobiomeProfiler** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional

## General package development

- [ ] :rotating_light: There are some notes in the build report from `BiocCheck::BiocCheck()`. Please check these and address as many as you can.

## DESCRIPTION file

- [ ] :green_circle: It is recommended to add ORCiDs to the `Authors@R` field

## NAMESPACE file

- [ ] :warning: Is it necessary to re-export the pipe operators (`%>%`, `%<>%`)? As far as I can see they are only used externally and don't need to be available to the user.

## Package data

- [ ] :rotating_light: The documentation for data included in the package is very minimal. Please expand this so it is clear what the data is, where it can from and what structure it has.
- [ ] :rotating_light: There is an additional `R/sysdata.rda` data file. This should either be removed or moved to the `data/` or `inst/data` directories.

### README

- [ ] :warning: The `README.Rmd` file does not include any executed code. If you do not plan to add any you can just have the simpler `README.md` file.
- [ ] :rotating_light: Please add Bioconductor installation instructions to the `README`

### Vignette

- [ ] :rotating_light: Please use the `BiocStyle` package vignette template for formatting
- [ ] :rotating_light: Please add a table of contents
- [ ] :rotating_light: Please add a more detailed *Introduction* section
- [ ] :rotating_light: Please add an *Installation* section with Bioconductor installation instructions. This code chunk should NOT be evaluated.
- [ ] :rotating_light: The vignette is very minimal, please add more detail. It is harder to document a shiny app but you can still explain the functionality and demonstrate any other functions. Screenshots would be very helpful. Please have a look at other the vignettes for other Bioconductor packages with shiny apps.
- [ ] :rotating_light: Please add a `sessionInfo()` chunk at section to the end of the vignette.

### Man pages

- [ ] :warning: It is recommended to add a package man page

## Unit tests

- [ ] :warning: The unit tests are quite minimal. It is hard to test the shiny app but you could write more tests for the exported functions.

## Code

### R

- [ ] :rotating_light: In the `enrichX()` functions slots are accessed directly using `@`. Please use a getter/setter function if possible.
- [ ] :rotating_light: `message()`, `warning()` and `stop()` join input so there is no need to use `paste0` inside them (see `bitr_smpdb()`)
- [ ] :rotating_light: For some functions (especially the shiny components) the documented arguments do not match the function. Please check that these are correct.
- [ ] :warning: It is recommended to add validity checks to arguments for exported functions. These can reduce a lot of errors for users.
- [ ] :green_circle: All the `enrichX()` functions are very similar. It might make sense to put them in one file or even combine them into fewer functions.
- [ ] :green_circle: `run_app()` is a fairly generic function name that could be used by many packages. It might make sense to rename it to something more specific like `run_MicrobiomeProfiler()` to avoid conflicts.

## Additional files

- [ ] :rotating_light: There are non-standard `myapp/` and `dev/` directories. These should be removed unless they are necessary for the package.

**Comment by mjchen1996** [comment]
Hi  @lazappi 

Thank you for your assistance. Here is a summary of the changes. 

 ## General package development

* [x] 🚨 There are some notes in the build report from `BiocCheck::BiocCheck()`. Please check these and address as many as you can.

  I have tried to remove some notes. Unfortunately, there are still 4 notes.

## DESCRIPTION file

 * [x] 🟢 It is recommended to add ORCiDs to the `Authors@R` field

   Thank you. I have added my ORCiDs to the `Authors@R` field.

 ## NAMESPACE file

 * [x] ⚠️ Is it necessary to re-export the pipe operators (`%>%`, `%<>%`)? As far as I can see they are only used externally and don't need to be available to the user.

   I have check it and remove the exported  operators (`%>%`, `%<>%`).

## Package data

 * [x] 🚨 The documentation for data included in the package is very minimal. Please expand this so it is clear what the data is, where it can from and what structure it has.

   Thank you. I have expanded the description of data and added reference url.

 * [x] 🚨 There is an additional `R/sysdata.rda` data file. This should either be removed or moved to the `data/` or `inst/data` directories.

   Sorry. The `sydata.rda` is required for the shiny app and `enrichX()` functions. I think it can not be removed or moved to the `data/` directory.

 ### README

 * [x] ⚠️ The `README.Rmd` file does not include any executed code. If you do not plan to add any you can just have the simpler `README.md` file.

   I have removed the `README.Rmd`.

 * [x] 🚨 Please add Bioconductor installation instructions to the `README`

   I have added the instructions.

### Vignette

* [x] 🚨 Please use the `BiocStyle` package vignette template for formatting

 * [x] 🚨 Please add a table of contents

 * [x] 🚨 Please add a more detailed _Introduction_ section

 * [x] 🚨 Please add an _Installation_ section with Bioconductor installation instructions. This code chunk should NOT be evaluated.

 * [x] 🚨 The vignette is very minimal, please add more detail. It is harder to document a shiny app but you can still explain the functionality and demonstrate any other functions. Screenshots would be very helpful. Please have a look at other the vignettes for other Bioconductor packages with shiny apps.

 * [x] 🚨 Please add a `sessionInfo()` chunk at section to the end of the vignette.

   I have tried my best to check and fix these issues. I have added  _Introduction_ and  _Installation_ sections in the vignette. Also, I added an example of KEGG enrichment analysis demo in the vignette.

 ### Man pages

* [x] ⚠️ It is recommended to add a package man page

  Yes, I have added it in my package.

 ## Unit tests

 * [x] ⚠️ The unit tests are quite minimal. It is hard to test the shiny app but you could write more tests for the exported functions.

 ## Code

 ### R

 * [x] 🚨 In the `enrichX()` functions slots are accessed directly using `@`. Please use a getter/setter function if possible.

   I used `slot()` instead of `@`.

 * [x] 🚨 `message()`, `warning()` and `stop()` join input so there is no need to use `paste0` inside them (see `bitr_smpdb()`)

   OK, I removed the `paste0()` from `bitr_smpdb()`.

 * [x] 🚨 For some functions (especially the shiny components) the documented arguments do not match the function. Please check that these are correct.

   Thank you. I have check the para list and try to make them matched.

* [x] ⚠️ It is recommended to add validity checks to arguments for exported functions. These can reduce a lot of errors for users.

  Most exported functions like `enrichKO()` were implemented from `clusterProfiler` which already included validity checks. Others like `bitr_smpdb()` also has validity check for arguments.

 * [x] 🟢 All the `enrichX()` functions are very similar. It might make sense to put them in one file or even combine them into fewer functions.

   Thank you for your advice. Currently, I haven't found a better way to make all the `enrichX()` much more concise.

 * [x] 🟢 `run_app()` is a fairly generic function name that could be used by many packages. It might make sense to rename it to something more specific like `run_MicrobiomeProfiler()` to avoid conflicts.

   Thank you for this tip. I have use `run_MicrobiomeProfiler()` instead of `run_app()` .

 ## Additional files

 * [x] 🚨 There are non-standard `myapp/` and `dev/` directories. These should be removed unless they are necessary for the package.

   Thank you. I have removed these directories.

  Thanks again for your support. Please let me know if there is anything necessary to be modified.

   Meijun

**Comment by lazappi** [comment]
> ## Package data
> * [x]  🚨 The documentation for data included in the package is very minimal. Please expand this so it is clear what the data is, where it can from and what structure it has.
>   Thank you. I have expanded the description of data and added reference URL.

I think you can probably still had some detail to this. The main thing is to add something about the data structure (is is a `data.frame`, a `matrix`, something else?).

> * [x]  🚨 There is an additional `R/sysdata.rda` data file. This should either be removed or moved to the `data/` or `inst/data` directories.
>   Sorry. The `sydata.rda` is required for the shiny app and `enrichX()` functions. I think it can not be removed or moved to the `data/` directory.

I think it might be possible to do this another way but it seems like `R/sysdata.rda` is a standard file I wasn't aware of so it should be fine.

>   I have tried my best to check and fix these issues. I have added  _Introduction_ and  _Installation_ sections in the vignette. Also, I added an example of KEGG enrichment analysis demo in the vignette.

This looks much better. There are a few typos and some formatting things you might want to look at but I'm happy with this.

> ## Unit tests
> * [x]  ⚠️ The unit tests are quite minimal. It is hard to test the shiny app but you could write more tests for the exported functions.

Did you have a look at adding some more tests?

> ## Code
> ### R
> * [x]  🚨 In the `enrichX()` functions slots are accessed directly using `@`. Please use a getter/setter function if possible.
>   I used `slot()` instead of `@`.

I had a bit of a look at it seems like there aren't proper getters for this class so `slot()` should be ok.

Thanks for your responses. I'm happy with most things now, they only things I think are left is whether you can add a few more tests and adding some information about the data structures for the included data.

**Comment by mjchen1996** [comment]
Hi, Luke @lazappi  

Thank you for your reply.

I have added some new tests in my package. Also, I have added data structure description as all example data are vector. Moreover. I had a bit of a look at vignette file and made some changes.

Meijun

**Comment by mjchen1996** [comment]
Hi, @lazappi 

Thank you for your reply.

I have added some new tests in my package. I think it is enough for exported functions since I have checked the S4 class results. As your known,  it is hard to test the shiny app. Also, I have added data structure description as all example data are vectors.
For `R/sysdata.rda`, this file included several data frame of annotation data collected from public databases like KEGG. Moreover. I had a bit of a look at vignette file and made some changes.

Meijun

**Comment by lazappi** [comment]
Hi @mjchen1996.

Thank you for adding information about the data structure but I think it would be clear to use the `@format` tag, please see the examples in this guide https://r-pkgs.org/data.html. Sorry, I should have been more specific about this earlier. The testing is ok now but I think you could continue to expand it, particularly for things like incorrect inputs.

I will approve this once you have adjusted the data documentation.

**Comment by mjchen1996** [comment]
Hi, @lazappi 

Thank you again. I have adjusted the data documentation and added more test for incorrect inputs.

Meijun

**Comment by lazappi** [comment]
Thanks! I will approve this now 🎉. It can take a few days for the package to be picked up by the build system but it should be on Bioconductor soon.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mjchen1996.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MicrobiomeProfiler")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MicrobiomeProfiler

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
