### ISSUE TITLE
AHCytoBands

### ISSUE THREAD

**Issue by lawremi** [Bioconductor/Contributions#234]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lawremi/AHCytoBands

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Data are now in the hub:
```
> hub = AnnotationHub()
updating metadata: retrieving 1 resource
  |======================================================================| 100%
snapshotDate(): 2017-01-05
> sub = query(hub, "AHCytoBand")
> sub
AnnotationHub with 9 records
# snapshotDate(): 2017-01-05 
# $dataprovider: UCSC
# $species: Homo sapiens, Mus musculus, Rattus norvegicus, Danio rerio, Dros...
# $rdataclass: GRanges
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["AH53176"]]' 

            title                           
  AH53176 | UCSC cytoBand track for hg18    
  AH53177 | UCSC cytoBand track for hg19    
  AH53178 | UCSC cytoBand track for hg38    
  AH53179 | UCSC cytoBand track for mm9     
  AH53180 | UCSC cytoBand track for mm10    
  AH53181 | UCSC cytoBand track for rn5     
  AH53182 | UCSC cytoBand track for rn6     
  AH53183 | UCSC cytoBand track for danRer10
  AH53184 | UCSC cytoBand track for dm6     
> sub[[1]]
downloading from ‘https://annotationhub.bioconductor.org/fetch/59914’
retrieving 1 resource
  |======================================================================| 100%
...
```

For the sake of consistency, I'll probably add the package to the annotation repo. It may seem like overkill here but most authors of AH data want man pages, vignettes and a few extra functions so availability via biocLite() makes sense. You said you might add to these resources in the future so at some point you might have something to load.

Package approved. No more to do from your end.

Val

**Comment by lawremi** [comment]
What do you mean by the annotation repo? Is AnnotationHub autogenerating a package that people can install? That would be great, because we could make biovizBase depend on it.

**Comment by vobencha** [comment]
By the annotation repo I mean packages listed here:
http://www.bioconductor.org/packages/release/BiocViews.html#___AnnotationData

There is no auto-generation of packages but because AHCytoBands will be in the repo people can load it with biocLite(). So you could make biovizBase depend on AHCytoBands and have a few man pages that explained the data if you wanted. The user would still need to create a 'Hub' and load the data with hub[[AH123]].

With ExperimentHub we've taken a different approach - the parent package is loaded when a resource is downloaded with '[['. The parent package documents data discovery / access via the usual '[[' on a 'Hub' object or through functions they've created, helpers, etc.

**Comment by mtmorgan** [comment]
Closing issue for manual processing.
