### ISSUE TITLE
distSTRING

### ISSUE THREAD

**Issue by kullrich** [Bioconductor/Contributions#2385]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kullrich/distSTRING

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by nturaga** [comment]
Hi,

I will review your package post-release i.e after Oct 27th. http://bioconductor.org/developers/release-schedule/

Best,

Nitesh

**Comment by kullrich** [comment]
@nturaga Hi, I am looking forward to the review process. Is it still possible to add some new functions by taking care of increasing the version number? There are still some statistics based on the calculated distances that I would like to contribute and add to my package?

**Comment by nturaga** [comment]
Yes, go for it.


Nitesh Turaga
Scientist II, Department of Data Science,
Bioconductor Core Team Member
Dana Farber Cancer Institute

**Comment by nturaga** [comment]
# Review

The package name `distSTRING` is very close to the CRAN package name
`stringdist`. It would be worth renaming the package to distinguish it
a little bit more to avoid confusion.

## DESCRIPTION

ok

## NAMESPACE 

ok

## NEWS

ok

## R 

- Using direct slot access with `@` should not be done. please check
  your build report.

	http://contributions.bioconductor.org/robust-and-efficient-code.html?#essential-s4-interface

    Found @ in man/addmask2string.Rd
    Found @ in man/addpop2string.Rd
    Found @ in man/addpos2string.Rd
    Found @ in man/addregion2string.Rd
    Found @ in man/string2region.Rd
 

## data

ok

## man

ok 

## tests 

Good! 

## vignettes 

ok

**Comment by kullrich** [comment]
Dear @nturaga,
if I rename the package, do I need to resubmit the whole package from scratch?

**Comment by nturaga** [comment]
I think the easiest would be to resubmit from scratch, but the review I gave you should hold. 

I will take over the review of the package under the new name and make sure it gets through. (of course, the build report should be as clean as possible).

Please tag me in a comment when you submit new.

**Comment by nturaga** [comment]
Please close this issue when you are ready with a new name.

**Comment by kullrich** [comment]
Dear @nturaga,

regarding the slot access, the '@' are only used in the example section, since many users use them in their code for quick access. And even these lines are only given as comments '#'.

The question would be if I really need to remove them in the example sections, which should help the users to execute the functions?

e.g. addmask2string

```
Examples
data(iupac, package="distSTRING")
iupac.aa <- iupac |> cds2aa(shorten = TRUE)
## create mask
mask1 <- IRanges::IRanges(start=c(1,41), end=c(20,50))
## add mask
iupac.aa <- iupac.aa |> addmask2string(mask=mask1)
#iupac.aa@metadata$mask
(iupac.aa |> slot("metadata"))$mask
## append mask
mask2 <- IRanges::IRanges(start=c(21), end=c(30))
iupac.aa <- iupac.aa |> addmask2string(mask=mask2)
(iupac.aa |> slot("metadata"))$mask
## overwrite mask
iupac.aa <- iupac.aa |> addmask2string(mask=mask2, append=FALSE)
(iupac.aa |> slot("metadata"))$mask
## reduce by mask
#iupac.aa.region <- iupac.aa |> string2region(mask=iupac.aa@metadata$mask)
iupac.aa.region <- iupac.aa |> string2region(mask=
    (iupac.aa |> slot("metadata"))$mask)
iupac.aa.region |> slot("metadata")
```

**Comment by kullrich** [comment]
Dear @nturaga,
would be `MSA2dist` fine for a name 'MultipleSequenceAlignment >>> distance', or still too close to `stringdist`?
Thank you in anticipation
Best regards
Kristian

**Comment by nturaga** [comment]
`MSA2dist` sounds fine to me.  Please check the names on Bioconductor and CRAN as well http://contributions.bioconductor.org/package-name.html.

Regarding slot access as an example, if you are not doing it in your code, it's not something your users should be doing either IMO. Accessing a slot is easy if you write accessor functions with good function names. 

Example, `rse1` is a RangedSummarizedExperiment, but to access the slot, we tell users to use `assay(rse1)` instead of `rse1@assays`.

```
> rse1
class: RangedSummarizedExperiment
dim: 200 6
metadata(0):
assays(1): counts
rownames: NULL
rowData names(1): feature_id
colnames(6): A B ... E F
colData names(1): Treatment
```

**Comment by kullrich** [comment]
Dear @nturaga,
since the slot access is on a `Biostrings::DNAStringSet`or an `Biostrings::AAStringSet`I guess I would need to care about original methods for these classes, right?

**Comment by kullrich** [comment]
Or even on a `XStringSet`as given in the description:

```
Description:

     The BStringSet class is a container for storing a set of ‘BString’
     objects and for making its manipulation easy and efficient.

     Similarly, the DNAStringSet (or RNAStringSet, or AAStringSet)
     class is a container for storing a set of ‘DNAString’ (or
     ‘RNAString’, or ‘AAString’) objects.

     All those containers derive directly (and with no additional
     slots) from the XStringSet virtual class
```

**Comment by nturaga** [comment]
I'm not sure I understand your question here.

Even within Biostrings, there are accessor functions to access data within the object. You do not need to alter the original methods in any way.

**Comment by kullrich** [comment]
Actual, I was just confused by this sentence:

**A Collates: field in the DESCRIPTION file may be necessary to order class and method definitions appropriately during package installation.**

**Comment by nturaga** [comment]
Closing this in favor of the other package.
