### ISSUE TITLE
(inactive) best.friends

### ISSUE THREAD

**Issue by favorov** [Bioconductor/Contributions#2387]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/favorov/best.friends

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Package is in good shape.  Reading vignette, note some language issues:

---

**Lets’s** try to translate it to **staistical** inferences.

Suppose we have set of elements E and a set of communities C of this elements with some fuzzy membership, e.g. there is a numeric measure of how an element is represented in a community A(e,c) for each pair (e,c):e∈E,c∈C. The **higher is A(e,c) value is**

---

Please read the vignette carefully and correct errors of this nature.

**Comment by vjcitn** [comment]
"U-statistics allows us to estimate the p-value for the value of t. The uncorrected p-value is (1−t)|C|."

You are referring to Hoeffding's U-statistic framework?  This is incredibly compressed reasoning.  Please elaborate.  Do you expect the reader of the vignette to have been through some other document to obtain definitions of technical terms?  If so please be specific about pre-requisites.

**Comment by favorov** [comment]
Hi, I am not sure was my previous message saved here, at least, I do not see it. 
Thank you for reviewing! I am working on the text and I hope to fix it soon. As for the U-statistics, you are right, the reference is too brave, and actually, it is not completely valid, I use this framework to think about the distribution, but I calculate the probability by integration of the uniform over some shape rather than use the dispersion estimate by Hoeffding's theorem. I will try to finish my preprint explaining the kitchen and refer to it in the vignette. Thank you again!
Cheers,
Sasha (AKA Alexander)

**Comment by vjcitn** [comment]
Just checking in.  Do you have an anticipated date for revision?

**Comment by favorov** [comment]
The language improvement is kind of a week. The arxive preprint preparation is a month.

**Comment by vjcitn** [comment]
How are we doing with language improvement?

**Comment by favorov** [comment]
Thank you for asking. Hope to submit it this weekend.

**Comment by favorov** [comment]
> How are we doing with language improvement?

Hi  Vince,
0.99.5 with the improved vignette is released. Thank you for the comments!

**Comment by vjcitn** [comment]
Thanks.  Spelling error early on: transctironal correlations

Also some spelling and syntax at `There is some week signal for gene E is for {TF1,TF9,TF7,TF10} (uncorrected p-value=0.006).`

Reading some of the R code, `best.friends.r` starts with

```
 A package that describe wheteher a community is a best
friend (or one of the best friends) for its member.
```
The URL in DESCRIPTION `https://github.com/favorov/best-friends/R/best-friends/` does not resolve.  In the README.md of the best-friends repo we have `This is an implementation of the gest.briends test.`  Is this also a spelling error?  I would like to understand the rationale of the algorithm better.  You write
```
The idea is: we have N elements and M communities and relations described as NxM matrix.
The stronger is the relation, the higher is the number. For each element,
we wnat to know the most friendly community.
```
Let E denote the set of cardinality N of the "elements".  Is a community a defined subset of E?  M communities are then M possibly overlapping subsets of E, but the identities of the communities are defined only through the membership weights in the N x M matrix.  It would be really useful to understand the genesis of this model.  Suppose we have N* elements in a network and apply the Girvan-Newman algorithm (https://www.pnas.org/content/pnas/99/12/7821.full.pdf) to define M communities.  Some of the original N* may be isolated, so perhaps N < N*.  How do you define the i,j element of your N x M matrix?  A clear shortcoming of the model achieved by Girvan-Newman is the insistence that communities partition the set of individuals.  But element membership in multiple communities is very realistic.  Perhaps your formulation hopes to overcome this.  But I feel much more explanation of the scientific origin and motivation for your algorithm is needed.  You do not seem to use any Bioconductor resources on gene sets or transcription factors to illustrate the substantive gains provided by your method.  Do you plan to do this?

**Comment by favorov** [comment]
Thank you so much!
I am sorry for the bad spelling, these errors are difficult to see
when the text is well-known,
Happy New Year!

**Comment by vjcitn** [comment]
Has there been any more progress on a publication on this algorithm?  I wonder about its relationship to http://www.scielo.org.co/scielo.php?script=sci_arttext&pid=S0120-56092015000200013 .  The vignette has a number of `noquote(all.friends)` to dump a list of arrays ... a print method for S3 or a show method for S4 object-oriented methodology would make this more readable and understandable.

Here's an example.  Take the `all.friends` element at the end of your vignette.  Use the S3 class assignment
```
class(all.friends) = c("best.fr.test", "list") # arbitrary class name
```
Now define
```
print.best.fr.test = function (x, ...) 
{
    cat("best.friends test results\n")
    cat(sprintf(" %d elements in network\n", nrow(x$pvals)))
    cat(sprintf("  %d connections had p < .01\n", sum(x$pvals < 
        0.01)))
}
```
and we have
```
> all.friends
best.friends test results
 10 elements in network
  4 connections had p < .01
```
instead of a somewhat challenging-to-parse dump of a list.  You can define additional methods to pick out elements of the outcome that are likely to be of interest to users.

**Comment by vjcitn** [comment]
The "p < .01" feature of the print method is just an example.  You can elaborate this in various ways.

**Comment by favorov** [comment]
I eventually returned from Moscow and started to read the correspondence more thoroughly. Thank you for the advice; I will try to use the TF regulation examples from the Bioconductor for the publication. Can you recommend a reliable one?
I will read more about the Girvan-Newman algorithm, maybe it has a clue how to connect the best.friends to the network reality. My original intuition was about coexpression and looking for specific TFs, and then I realised that the matrix is not to be symmetric, so it is related to e.g. PatternMarkers (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5860188/) story. If an element is not in a community, we just assign zero (or any other minimal value) to their pair. My main gain, as far as I can understand, is the p-value for the rank-ordering result rather than the ordering of ranks itself. The best.friends is not based on pagerank, and it is more local than ["An algorithm for identifying the best current friend in a social network"](http://www.scielo.org.co/scielo.php?script=sci_arttext&pid=S0120-56092015000200013) -- the latter, you calculate the pageranks with and without putative friends, and the difference is the measure of friendship. My best.friends, you just calculate how the putative friend score you and compare all the putative friends. Much simpler, and a p-value is provided.

I have doubts about the URL field in the DESCRIPTION. Currently, I have a github for the project (with R and maybe later C or python subfolders) and the bioconductor URL. May I keep the original one in DESCRIPTION (after fixing it)?

**Comment by vjcitn** [comment]
thanks for this  i will answer more in depth next week   the URL should be your github repo URL

**Comment by favorov** [comment]
Thank you for the Girvan-Newman reference! Very inspiring reading. I eventually understood that my element-community terminology is very misleading for network and graph people. The community has intuition to be something isolated from others. The previous was "entity-feature": 

Let’s make a generalisation. We have entities and features and a matrix
that show how strong is a feature ascribed to an entity. We want to identify
those features that reliably and uniquely identify an entity. Let’s call the feature
the entity’s marker and let’s call the entity the feature’s best friend. Here, we
describe a rank test identifying significant pairs of marker feature and its best
friend entity. --

it is a cite from the 1-year ago version of the manuscript. 
It was very psychedelic and actually, it was about substances and accidents in Thomistic sense.

I decided that it is too much and switched to entity (substance) -> element and feature (accident) -> community.
Now, it seems to me it was a bad choice, still, my English is not enough to think out something better than to return to the entity / feature terms. Entity is a gene, its feature is to be regulated by a TF of to be in a pattern. If we speak about the symmetric case (a graph), an entity is a vertex and its features are connections to other vertices. 

Sounds more reasonable than the community term and not so scholastic as substances and accidents. 
What do you think? Here is the link to the paper draft abstract is switched to communities terminology already, all the body remains entity-feature.
https://www.overleaf.com/read/gfzxcyyrmjdc

It all is a little chaotic, I would appreciate any response. Thank you!

Cheers,
Sasha.

**Comment by vjcitn** [comment]
Thanks for the overleaf link.  That will be helpful to reviewers, so please add a link to it to your package vignette, or place a compiled draft in inst/pdfs in your package.  I see that you are supported by an NIH P30 to Johns Hopkins.  It would be nice to explain how this algorithm can be or has been used in that work.  Let me know when you have finalized the sources/terminology in best.friends for Bioconductor review and we can start that process.

**Comment by lshep** [comment]
@favorov  could you please respond and update accordingly to @vjcitn  comments above. We like to see progress within 3-4 weeks of comments and feedback.

**Comment by favorov** [comment]
@lshep thank you for your note. I did not know the timing. The critical issue is that one of the necessary points is to prepare the arxive text, and it now takes much more time than I could even suppose.  Trying to do my best.

**Comment by vjcitn** [comment]
checking in again
