### ISSUE TITLE
RIVER

### ISSUE THREAD

**Issue by ipw012** [Bioconductor/Contributions#239]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ipw012/RIVER

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by LiNk-NY** [comment]
Hi @ipw012, 
I see that you are not using any Bioconductor resources. We want our packages to be inter-operable. 
You should be able to support the use of either an `ExpressionSet` or `SummarizedExperiment` as input for your functions.

**Comment by ipw012** [comment]
Hi @LiNk-NY,
I just updated my R package in several points:
1. `ExpressionSet` was incorporated as an input object of functions in my package.
2. Evaluation approach was changed so that related functions were revised accordingly.
3. A package version was changed from 0.99.0 to 0.99.1.

Could you please take a look at my package and see if it fits Bioconductor requirements?
I also have one question. What does "Update R version dependency from 3.3.1 to 3.4." mean? I am not sure how to fix that issue since the current version of R is 3.3.2 I believe. I had the same WARNING MESSAGES from all three OS environments.

**Comment by LiNk-NY** [comment]
Hi @ipw012, 
Thanks for making that change. I will look at your package in the coming days. 
"Updating your R version dependency" entails changing the `Depends` field to `R (>= 3.3.2)` in the `DESCRIPTION`. Ideally, you would have `R (>= 3.4.0)` since the Bioconductor 3.5 (devel) works R devel. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @ipw012, 
Can you bump the version? 
Thanks. 
-Marcel

**Comment by lcolladotor** [comment]
Hi @LiNk-NY,

You can see that @ipw012 bumped the version to 0.99.1 at https://github.com/ipw012/RIVERpkg/commit/416f40b604c1a45546b5c304dfbb47acc7c220a8#diff-35ba4a2677442e210c23a00a5601aba3R13.

@ipw012, I think that @LiNk-NY wants you to change https://github.com/ipw012/RIVERpkg/blob/416f40b604c1a45546b5c304dfbb47acc7c220a8/DESCRIPTION#L21 to read `R (>= 3.3.2)` and bump the version to 0.99.2. That would solve the warning I see at http://bioconductor.org/spb_reports/RIVERpkg_buildreport_20170128184322.html and the 3 remaining notes can be ignored. You are almost done!

Best,
Leo

**Comment by ipw012** [comment]
Hi Leo,

Thanks for looking over this! I will change it soon and report it.

Sincerely,
Yungil

**Comment by LiNk-NY** [comment]
Hi Leo @lcolladotor,
Thanks for chiming in on the issue. 

Yungil @ipw012,
The `Version Bump Required` tag is attached when the maintainer pushes a commit without bumping the package version. 

Best,
Marcel

**Comment by ipw012** [comment]
Hi Marcel,

I have already bumped up my package version in the last commit. Should I rebump it or current one is OK? Thanks.

Sincerely,
Yungil

**Comment by lcolladotor** [comment]
@ipw012 I understand the issue now. In https://github.com/ipw012/RIVERpkg/commit/416f40b604c1a45546b5c304dfbb47acc7c220a8 you did bump the version.  However, you have made several new commits since then:

<img width="1038" alt="screen shot 2017-02-17 at 5 33 11 pm" src="https://cloud.githubusercontent.com/assets/2288213/23085719/334716f0-f537-11e6-8267-2b71574bcdac.png">

and you haven't bumped the version in them. Bioconductor, via the single package builder (SBP) wants to make sure that the latest version of your package works, and the tests don't start unless you bump the version. Version numbers are cheap, so just bump them every time you change something.

If you accept this pull request, everything should work and `RIVERpkg` will pass the tests unless some of your commits after https://github.com/ipw012/RIVERpkg/commit/416f40b604c1a45546b5c304dfbb47acc7c220a8 broke something.

Best,
Leo

**Comment by ipw012** [comment]
Hi Marcel @LiNk-NY,

I updated my package, committed it, and now I have warnings like "Update R version dependency from 3.3.2 to 3.4.", which I am not sure how to handle it. I tried to update it but couldn't built my package in my current R (3.3.2). I couldn't find any concrete solution for this by googling it. Could you please tell me how to resolve that issue? Thanks.

Sincerely,
Yungil

**Comment by LiNk-NY** [comment]
Hi Yungil @ipw012,
Thank you for submitting to Bioconductor.
Please find your package review below.
If you have any questions, please feel free
to contact me. 

Regards,
Marcel 

---

### Package

* Does your package really have to be named RIVERpkg? 
It seems like it would be better to omit the "pkg" part
of the name and leave it at RIVER.
* As it pertains to the version bump, although it is not necessary, we recommend that all packages in the development branch require an R version of `3.4.0` or greater. If for some reason, you are using the package in a cluster (for example) that does not support that R version, you may leave it unchanged. If you do want to bump the R version and develop your package with `R >= 3.4.0`, you would have to install R-devel.

### Grammar

* Perhaps you want to use `aes_` with a ggplot function
since it should allow character arguments and you'll avoid "undefined global
variables" from `R CMD check`
* Avoid the use of `while` loops especially if they have
`TRUE` as input

### Usability - Readability

* Please use descriptive argument names so that it is easier
for the user to figure out what the input should be.
* Your documentation should minimize the number of symbols. Explain what the
function is returning rather than using probability notation. That can be
included in the `@details` section
* Perhaps you don't want to have a plot ROC method
in your package. There are plenty of packages
that already plot ROCs.
* As far as I know, the NEWS file should be in simple text format and not as
an `Rd` file. 

### Minor

* Try not to use `_` or `.` in object, function names, or arguments
* Assignment should be done via `<-`
* The lines in the vignette should be wrapped at a maximum of 80 columns

**Comment by ipw012** [comment]
Hi Marcel @LiNk-NY,

Thank you for reviewing my package in detail. I will incorporate your comments/suggestions sometime early next week. In the meantime, I have some follow questions/responses regarding your comments in line below.

**Package**

Does your package really have to be named RIVERpkg?
It seems like it would be better to omit the "pkg" part
of the name and leave it at RIVER.
_I currently have a github repository named as RIVER which have all the initial codes of RIVER I provided when we submitted our paper. I will replace the old one with updated codes of RIVER and change the name as RIVER._

As it pertains to the version bump, although it is not necessary, we recommend that all packages in the development branch require an R version of 3.4.0 or greater. If for some reason, you are using the package in a cluster (for example) that does not support that R version, you may leave it unchanged. If you do want to bump the R version and develop your package with R >= 3.4.0, you would have to install R-devel.
_Thanks for your suggestions. I will try to use R-devel, build my package, and evaluate with travis. If it does not work, I will leave as it is._

**Grammar**

Perhaps you want to use aes_ with a ggplot function
since it should allow character arguments and you'll avoid "undefined global
variables" from R CMD check
Avoid the use of while loops especially if they have
TRUE as input
Avoid the use of arguments that are not descriptive. (Example: E, FR, G, etc.)
_I will revise our codes in this way. Thanks_

**Usability - Readability**

Please use descriptive argument names so that it is easier
for the user to figure out what the input should be.
Your documentation should minimize the number of symbols. Explain what the
function is returning rather than using probability notation. That can be
included in the @details section
Perhaps you don't want to have a plot ROC method
in your package. There are plenty of packages
that already plot ROCs.
As far as I know, the NEWS file should be in simple text format and not as
an Rd file.
_I will probably remove plotROCs from my package as you suggested and change all of these points accordingly._

Minor

Try not to use _ or . in object, function names, or arguments
Assignment should be done via <-
The lines in the vignette should be wrapped at a maximum of 80 columns
_Thanks for providing these comments. I will change them accordingly_

**Comment by LiNk-NY** [comment]
Hi Yungil, @ipw012 
Any updates on the status of this? 

Thank you.

Marcel

**Comment by ipw012** [comment]
Hi Marcel @LiNk-NY,

I finally update my package based on your comments/suggestions and current package works fine based on travis-CI. I explained what I changed in lines with your comments below. If there is anything I need to do additionally, please let me know. Thanks.

**Package**

Does your package really have to be named RIVERpkg?
It seems like it would be better to omit the "pkg" part
of the name and leave it at RIVER.
_The name of my package is now RIVER instead of RIVERpkg._

As it pertains to the version bump, although it is not necessary, we recommend that all packages in the development branch require an R version of 3.4.0 or greater. If for some reason, you are using the package in a cluster (for example) that does not support that R version, you may leave it unchanged. If you do want to bump the R version and develop your package with R >= 3.4.0, you would have to install R-devel.
_I tried this but it did not work. Thus, I left it as it was as you suggested._ 

**Grammar**

Perhaps you want to use aes_ with a ggplot function
since it should allow character arguments and you'll avoid "undefined global
variables" from R CMD check
_I changed aes into aes_string_
Avoid the use of while loops especially if they have TRUE as input
_I replaced while loop with for loop_
Avoid the use of arguments that are not descriptive. (Example: E, FR, G, etc.)
_Names of arguments having mathematical symbols with descriptive terms were changed in descriptive ways. (i.e. E --> Out (Outlier), FR --> FuncRv (Functional regulatory variant), G --> Feat (Genomic features)). I also add full descriptions of these names with the symbols I used previously in @section. Since I used those mathematical symbols for equations in our paper, it would be clearer to have them along with the descriptive terms._

**Usability - Readability**

Please use descriptive argument names so that it is easier
for the user to figure out what the input should be.
Your documentation should minimize the number of symbols. Explain what the
function is returning rather than using probability notation. That can be
included in the @details section
_I tried my best to avoid mathematical symbols and probability notations for arguments, objects, and functions. However, if dependent packages use mathematical notations, I left them as they were to avoid confusion._
Perhaps you don't want to have a plot ROC method in your package. There are plenty of packages
that already plot ROCs. 
_I removed a plotAUC function_
As far as I know, the NEWS file should be in simple text format and not as an Rd file.
_My NEWS file is now a simple text format_

**Minor**

Try not to use _ or . in object, function names, or arguments
Assignment should be done via <-
The lines in the vignette should be wrapped at a maximum of 80 columns
_I changed all of these into what you suggested as many as possible._

**Comment by LiNk-NY** [comment]
Hi Yungil, @ipw012 
Thanks for making those changes. The package is looking better now. 

There is still an exported function with an underscore ("_") in the name called `getFuncRv_Feat`. Please use camel case for function names. 

If you're loading `devtools` in the vignette, the package should be added to the `Suggests:` field. 

For more see this [link](http://www.bioconductor.org/developers/package-guidelines/).
If possible, try to follow the guidelines suggested in this GitHub package: [`MangoTheCat/goodpractice`](https://github.com/mangothecat/goodpractice). 

Regards,
Marcel

**Comment by ipw012** [comment]
Hi Marcel @LiNk-NY,

I updated my package in the way you suggested as follows:

1. There is still an exported function with an underscore ("_") in the name called getFuncRv_Feat. Please use camel case for function names.
**The function name, "getFuncRv_Feat", was changed into "getFuncRvFeat".**
2. If you're loading devtools in the vignette, the package should be added to the Suggests: DESCRIPTION field.
**I added devtools into the Suggests: DESCRIPTION field.**
3.  For more see this link.
If possible, try to follow the guidelines suggested in this GitHub package: MangoTheCat/goodpractice.
**I doublechecked the bioconductor package guidelines, ran gp("RIVER") to follow guidelines suggested by the GitHub package you mentioned, and incorporated all the reported and necessary comments into my package.**

If there is any other suggestion/comment, please let me know. Thank you for your suggestion.

Sincerely,
Yungil

**Comment by LiNk-NY** [comment]
Hi Yungil, @ipw012 
Thank you for making those changes. Your package has been accepted. 

Regards,
Marcel

**Comment by ipw012** [comment]
Hi Marcel @LiNk-NY,

Thank you for the update! I did bump the version and started another build. However,  the build was created but did not start yet for a long time (> 30 mins, https://travis-ci.org/ipw012/RIVER). I am not sure what is wrong here. Do you have any clue/suggestion? Thanks.

Sincerely,
Yungil

**Comment by ipw012** [comment]
Hi Marcel @LiNk-NY,

It seemed that I built most recent one successfully. I also asked you that it is possible for my package to be released in this spring (Apr). If there is anything I need to do for my package, please let me know. Thanks.

Sincerely,
Yungil

**Comment by LiNk-NY** [comment]
Hi Yungil, @ipw012 
Please re-establish the webhook so that the SPB can build and test your package. It's good that you use travis but the SPB also tests the package in other platforms. 

See: https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook

Regards,
Marcel

**Comment by ipw012** [comment]
Hi Marcel @LiNk-NY,

I have already established the webhook previously but updated the webhook one more time to make sure that I am following you. Can SPB test my package now? If not, please let me know what to do next. Thanks!

Sincerely,
Yungil

**Comment by LiNk-NY** [comment]
Hi Yungil, @ipw012 
It might have changed due to renaming the repository. 
I have asked @lshep to start a build for your package. 
Thanks!
Regards,
Marcel

**Comment by ipw012** [comment]
Hi Marcel @LiNk-NY,

Based on what I saw in the above build report, I have two WARNINGS and 1 ERROR messages. 2 WARNINGS are "Update R version dependency from 3.3.2 to 3.4." which I left as it was since it was not working from my side. More importantly, I received one ERROR message saying "Error in loadVignetteBuilder(pkgdir, TRUE) : 
  vignette builder 'knitr' not found" on window machine. I was trying to figure this out by searching google but couldn't find any solution. Do you have any suggestion to resolve this? 
In DESCRIPTION file, I added 
"VignetteBuilder: knitr
Suggests: BiocStyle, knitr, rmarkdown, testthat, devtools".
Thus, I did not expect to receive this message. Thanks.

Sincerely,
Yungil

**Comment by LiNk-NY** [comment]
Hi Yungil,  @ipw012 
That is package builder issue. You can ignore that for now. 
Thanks,
Marcel

**Comment by ipw012** [comment]
Hi Marcel @LiNk-NY,

Thank you for your quick response. Then, is my package good to go? Should I simply wait for any further notice from bioconductor? If not, please let me know what to do next. Thanks!

Sincerely,
Yungil

**Comment by LiNk-NY** [comment]
Hi Yungil, @ipw012 
The package is good to go. Thank you for submitting to Bioconductor!

Regards,
Marcel
