### ISSUE TITLE
PPInfer

### ISSUE THREAD

**Issue by dongminjung** [Bioconductor/Contributions#241]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dongminjung/PPInfer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by dongminjung** [comment]
I updated them. Thanks.

**Comment by hpages** [comment]
Hi Dongmin,

Thanks for your submission. Please find below a list of issues with the PPInfer package. Please address them at your earliest convenience.

Cheers,
H.

1. The build/ folder doesn't belong to PPInfer source tree. Please remove it. Also please remove the 'Packaged:...' line from the DESCRIPTION file. This line doesn't belong to the package source tree either.

2. Use `<-` instead of `=` for assignment. Make sure to put a space before and after the `<-`, like in
```
    fblog <- upgrade_graph(fblog)
```

3. Please don't use `\doublespacing` in the vignette.

4. Indent your code properly. For example, in the \usage section of `net.infer()` man page:
```
     net.infer(list.proteins, kernel, top = NULL, cross = 0,
               C1 = 1, nu = 0.2, epsilon = 0.1, cache1 = 40, tol1 = 0.001, 
               shrinking1 = TRUE, C2 = 1, cache2 = 40, tol2 = 0.001,
               shrinking2 = TRUE)
```
  instead of:
```
     net.infer(list.proteins, kernel, top = NULL, cross = 0,
     C1 = 1, nu = 0.2, epsilon = 0.1, cache1 = 40, tol1 = 0.001, 
     shrinking1 = TRUE, C2 = 1, cache2 = 40, tol2 = 0.001,
     shrinking2 = TRUE)
```
  Or, in the `\examples` section:
```
     string.db.9606 <- STRINGdb$new(version='10',species=9606,
                                    score_threshold = 999)
```
  instead of:
```
     string.db.9606 = STRINGdb$new(version='10',species=9606,
     score_threshold = 999)
```

5. It doesn't make sense to return scores in a character vector like your `net.infer()` or `ppi.infer.human()` functions do.

6. It is also a very bad idea to prefix Ensembl protein ideas with a taxonomy id:
```
  > infer$top
   [1] "9606.ENSP00000348762" "9606.ENSP00000381768" "9606.ENSP00000351059"
   [4] "9606.ENSP00000259154" "9606.ENSP00000337255" "9606.ENSP00000323856"
   [7] "9606.ENSP00000374399" "9606.ENSP00000361548" "9606.ENSP00000336702"
  [10] "9606.ENSP00000310623"
```
  This hurts the usability of your package.

7. I'm not convinced it's pertinent/relevant to dedicate 3 pages of an 8-page vignette to illustrate the functionality of your package with an example based on the 'fblog' dataset (French political blogs). Furthermore, you also have these fblog-based examples in the man pages. Please treat use cases and provide examples that are relevant to the Bioinformatics community.

**Comment by dongminjung** [comment]
Hi. hpages

I appreciate your comments. I corrected all issues. Please see below.

Thanks,
Dongmin


****
1. The build/ folder doesn't belong to PPInfer source tree. Please remove it. Also please remove the 'Packaged:...' line from the DESCRIPTION file. This line doesn't belong to the package source tree either.

**Correction** : I removed the file in the build folder and the line in the DESCRIPTION file.


****  
2. Use `<-` instead of `=` for assignment. Make sure to put a space before and after the `<-`, like in

`fblog <- upgrade_graph(fblog)` 

**Correction** : I changed from `=` to `<-`. For example, `infer <- net.infer(list.proteins,K.9606,10)`.


****  
3. Please don't use `\doublespacing` in the vignette.

**Correction** : I use `\linespread{1.5}` instead of `\doublespacing`.


****  
4. Indent your code properly.

**Correction** : I did it.


****  
5. It doesn't make sense to return scores in a character vector like your `net.infer()` or `ppi.infer.human()` functions do.

**Correction** : I changed from
`pred.svm$score <- as.vector(new.sort.pred2[1:top,2])`
`ppi.pred.9606$score <- as.vector(na.omit.new.protein_score[1:top,2])`
`ppi.pred.10090$score <- as.vector(na.omit.new.protein_score[1:top,2])`
to 
`pred.svm$score <- as.numeric(new.sort.pred2[1:top,2])`
`ppi.pred.9606$score <- as.numeric(na.omit.new.protein_score[1:top,2])`
`ppi.pred.10090$score <- as.numeric(na.omit.new.protein_score[1:top,2])`
for each function, respectively.


****  
6. It is also a very bad idea to prefix Ensembl protein ideas with a taxonomy id:

 `> infer$top`
  `[1] "9606.ENSP00000348762" "9606.ENSP00000381768" "9606.ENSP00000351059"`
  `[4] "9606.ENSP00000259154" "9606.ENSP00000337255" "9606.ENSP00000323856"`
  `[7] "9606.ENSP00000374399" "9606.ENSP00000361548" "9606.ENSP00000336702"`
  `[10] "9606.ENSP00000310623"`
This hurts the usability of your package.

**Correction** : I removed the prefix before taking the input. This problem comes from the name of columns and rows of a kernel matrix. So I used
`rownames(K.9606) <- sub('.*\\.','',rownames(K.9606))`
`colnames(K.9606) <- sub('.*\\.','',colnames(K.9606))`.
So such corrections are not necessary for `getBM()` in `ppi.infer.human()` and `ppi.infer.mouse()`.
We have
`> infer$top`
 `[1] "ENSP00000348762" "ENSP00000381768" "ENSP00000351059"`
 `[4] "ENSP00000259154" "ENSP00000337255" "ENSP00000323856"`
 `[7] "ENSP00000374399" "ENSP00000361548" "ENSP00000336702"`
`[10] "ENSP00000310623"`


****  
7. I'm not convinced it's pertinent/relevant to dedicate 3 pages of an 8-page vignette to illustrate the functionality of your package with an example based on the 'fblog' dataset (French political blogs). Furthermore, you also have these fblog-based examples in the man pages. Please treat use cases and provide examples that are relevant to the Bioinformatics community.

**Correction** : The data `litG` of the package `yeastExpData` is used in the vignette. So the package containing 'fblog' is not necessary anymore.

**Comment by hpages** [comment]
Hi Dongmin,

Thanks for addressing the issues. I'm marking the package as accepted. We will add it to our Subversion repo and build system in the next days. You'll receive an email with more information about this.

Thanks for contributing to the Bioconductor project!

Regards,
H.

**Comment by dongminjung** [comment]
Thank you for taking the time to review the package.

Dongmin
