### ISSUE TITLE
DEPTH

### ISSUE THREAD

**Issue by WangX-Lab** [Bioconductor/Contributions#2424]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/WangX-Lab/DEPTH

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
heterogeneity is not a valid biocViews term.  Please remove it from the list.

**Comment by lshep** [comment]
The DEPTH package must be the root of the git clone.  Please update the package repository and move everything under the DEPTH/DEPTH directory up to the main directory.  Please also correct BiocCheck errors that could already be found.

**Comment by WangX-Lab** [comment]
Dear 

> The DEPTH package must be the root of the git clone. Please update the package repository and move everything under the DEPTH/DEPTH directory up to the main directory. Please also correct BiocCheck errors that could already be found.

Thank you for your precious comments. We have made changes now.

**Comment by WangX-Lab** [comment]
> The DEPTH package must be the root of the git clone. Please update the package repository and move everything under the DEPTH/DEPTH directory up to the main directory. Please also correct BiocCheck errors that could already be found.

Thank you for your precious comments. We have made changes now.

**Comment by WangX-Lab** [comment]
> heterogeneity is not a valid biocViews term. Please remove it from the list.

Thank you for your precious comments. We have removed it now.

**Comment by WangX-Lab** [comment]
> Dear Package contributor,
> 
> This is the automated single package builder at bioconductor.org.
> 
> Your package has been built on Linux, Mac, and Windows.
> 
> On one or more platforms, the build results were: "ERROR". This may mean there is a problem with the package that you need to fix. Or it may mean that there is a problem with the build system itself.
> 
> Please see the [build report](http://bioconductor.org/spb_reports/DEPTH_buildreport_20211116093020.html) for more details. This link will be active for 21 days.
> 
> ** Remember: **if you submitted your package after July 7th, 2020, when making changes to your repository push to `git@git.bioconductor.org:packages/DEPTH` to trigger a new build. A quick tutorial for setting up remotes and pushing to upstream can be found [here](https://bioconductor.org/developers/how-to/git/new-package-workflow/).

@lshep  I can't fetch the upstream. (So I can't trigger new build report...) What do you think?
(I fixed the "ERROR" on the origin. But I can't push the update to upstream.)

$ git clone git@git.bioconductor.org:packages/DEPTH
Cloning into 'DEPTH'...
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by lshep** [comment]
Did you activate your BiocCredentials account?  You might have to add a new ssh-key for access which you can do after you activate your account. https://git.bioconductor.org/BiocCredentials

**Comment by lshep** [comment]
Please activate your account and push changes before a review will proceed.  If you do not proceed we will close the issue for inactivity and you can request to reopen when you can participate in the review process

**Comment by lshep** [comment]
@WangX-Lab  do you plan to continue with the submission? Please activate your git credentials and push changes to git.bioconductor.org.

**Comment by WangX-Lab** [comment]
@lshep I've made some changes on github, how do I recommit to bioconductor?

**Comment by WangX-Lab** [comment]
@bioc-issue-bot @lshep  I would like this repository to be linked to issue number: 2474

**Comment by lshep** [comment]
@WangX-Lab  I was away for the holiday. Do not close this issue and try to open a new one.  You should continue on this issue. You need to figure out how to push to Bioconductor as it is an important part of maintaining a Bioconductor package on our system.

**Comment by lshep** [comment]
I mentioned in  previous comments, you need to activate your BiocCredentials account and add ssh-keys in order to push to git.bioconductor.org.  Please do this and update your package on our system with a valid version bump to trigger a new build.  then we will continue with the review.

**Comment by lshep** [comment]
Follow the links for https://bioconductor.org/developers/how-to/git/new-package-workflow/  for pushing to bioconductor

**Comment by WangX-Lab** [comment]
@bioc-issue-bot @lshep  Hi, I am trying to activate my account to add SSH keys. I think I have already added email address in the DESCRIPTION file of the package I maintain. You can find it here: https://github.com/WangX-Lab/DEPTH/blob/master/DESCRIPTION. But the BiocCredentials website shows that my email address "is not associated with a maintainer of a Bioconductor package. Please check the spelling or contact bioc-devel@r-project.org for help." Could you help me to activate my account?

**Comment by lshep** [comment]
The package was originally associated with mengyuanli@stu.cpu.edu.cn as that was the first listed maintainer and following best R practices encourages only one maintainer for a package.  Now that the description has been updated I also updated the BiocCredentials app and it should recognize xiaosheng.wang@cpu.edu.cn.  Remember to activate your account first.

**Comment by WangX-Lab** [comment]
@lshep Thank you, I have activated my BiocCredentials account and added ssh-keys. But when I run 'git push upstream master'  in order to push to git.bioconductor.org, the git shows that "FATAL: W any WangX-Lab/DEPTH WangX-Lab DENIED by fallthru (or you mis-spelled the reponame) fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists." So, how can I solve this problem?

**Comment by lshep** [comment]
please show the results of running `git remote -v`  and then the full output when running `git push upstream master` so we can better assist

**Comment by WangX-Lab** [comment]
@bioc-issue-bot @lshep Hi, I opened the new issue#2473 because I solved the dependency problem with the last version of the package and re-uploaded it to github.

**Comment by WangX-Lab** [comment]
@lshep Thank you very much. Here are the results:

$ git remote -v
origin  git@github.com:WangX-Lab/DEPTH.git (fetch)
origin  git@github.com:WangX-Lab/DEPTH.git (push)
upstream        git@git.bioconductor.org:WangX-Lab/DEPTH.git (fetch)
upstream        git@git.bioconductor.org:WangX-Lab/DEPTH.git (push)

$ git push upstream master
FATAL: W any WangX-Lab/DEPTH WangX-Lab DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by lshep** [comment]
what do you mean by dependency problem?

**Comment by WangX-Lab** [comment]
@lshep  The package DEPTH is an algorithm developed in our lab to calculate intratumor heterogeneity (ITH) level of each tumor sample based on gene expression profiles. DOI: https://doi.org/10.1038/s42003-020-01230-7. The formula inside this algorithm involves a standard deviation (sd) that depends on the R package stats. In the changed version, we have resolved this dependency and can seen here: https://github.com/WangX-Lab/DEPTH/blob/master/NAMESPACE.

**Comment by nturaga** [comment]
Hi @WangX-Lab 

There could be multiple reasons why you cannot push to the git server.

https://bioconductor.org/developers/how-to/git/faq/ 

Please check to ensure FAQ numbers 14, 15, 16 are correctly addressed on your local machine, especially 16, where you might have to set the permissions. 

Best,

Nitesh

**Comment by WangX-Lab** [comment]
@nturaga @lshep  Thank you very much. I will check these issues you mentioned in the near future.

**Comment by lshep** [comment]
> @bioc-issue-bot @lshep Hi, I opened the new issue#2473 because I solved the dependency problem with the last version of the package and re-uploaded it to github.


You should not open new issues for changes.  The point of the review process and assigning an issue is to understand and learn how to maintain a Bioconductor package as well as pass the review process for Bioconductor package standards.  Figuring out how to push to git.bioconductor.org to upload your changes is important to that.  Also worth looking at is  http://contributions.bioconductor.org/  which will have package standards for Bioconductor packages. At quick glance at your repository it does not seem like you have run  Bioconductor BiocCheck before submission as it will produce many ERROR and Warnings.  Please consider running `BiocCheck("DEPTH", 'new-package'=TRUE)` from the [Bioconductor BiocCheck package](https://bioconductor.org/packages/devel/bioc/html/BiocCheck.html)

**Comment by WangX-Lab** [comment]
@lshep  Thank you very much. It does generate a lot of errors and warnings. Here are the results:

> library(BiocCheck)
> BiocCheck("DEPTH", 'new-package'=TRUE)
This is BiocCheck version 1.28.0. BiocCheck is a work in progress. Output and severity of issues
may change. Installing package...
* Checking Package Dependencies...
* Checking if other packages can import this one...
* Checking to see if we understand object initialization...
* Checking for deprecated package usage...
* Checking for remote package usage...
* Checking for 'LazyData: true' usage...
* Checking version number...
* Checking new package version number...
* Checking R Version dependency...
* Checking package size...
        Skipped... only checked on source tarball
* Checking individual file sizes...
* Checking biocViews...
* Checking that biocViews are present...
* Checking package type based on biocViews...
    Software
* Checking for non-trivial biocViews...
* Checking that biocViews come from the same category...
* Checking biocViews validity...
    * WARNING: 'heterogeneity' is an invalid BiocViews term.
* Checking for recommended biocViews...
    * NOTE: Consider adding these automatically suggested biocViews: Microarray
See http://bioconductor.org/developers/how-to/biocViews/
* Checking build system compatibility...
* Checking for blank lines in DESCRIPTION...
* Checking if DESCRIPTION is well formatted...
* Checking for proper Description: field...
    * NOTE: The Description field in the DESCRIPTION is made up by less than 3 sentences. Please
      consider expanding this field, and structure it as a full paragraph
* Checking for whitespace in DESCRIPTION field names...
* Checking that Package field matches directory/tarball name...
* Checking for Version field...
* Checking for valid maintainer...
    * ERROR: Do not use Author/Maintainer fields. Use Authors@R.
    * ERROR: Remove Maintainer field. Use Authors@R [cre] designation.
* Checking License: for restrictive use...
* Checking DESCRIPTION/NAMESPACE consistency...
    * WARNING: Import stats in DESCRIPTION as well as NAMESPACE.
* Checking .Rbuildignore...
* Checking vignette directory...
    * ERROR: No 'vignettes' directory.
* Checking library calls...
* Checking for library/require of DEPTH...
* Checking coding practice...
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        DEPTH.R (line 40, column 14)
        DEPTH.R (line 44, column 14)
        DEPTH.R (line 45, column 16)
        DEPTH.R (line 50, column 14)
        DEPTH.R (line 51, column 16)
        DEPTH.R (line 58, column 12)
* Checking parsed R code in R directory, examples, vignettes...
* Checking function lengths.
* Checking man page documentation...
    * ERROR: At least 80% of man pages documenting exported objects must have runnable examples.
      The following pages do not:
      DEPTH.Rd
* Checking package NEWS...
    * NOTE: Consider adding a NEWS file, so your package news will be included in Bioconductor
      release announcements.
* Checking unit tests...
    * NOTE: Consider adding unit tests. We strongly encourage them. See
      http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
* Checking skip_on_bioc() in tests...
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source, and vignette source...
    * NOTE: Consider shorter lines; 11 lines (11%) are > 80 characters long.
    First 6 lines:
      R/DEPTH.R:5 #' \code{DEPTH} DEPTH evaluates the tumor heterogeneity level of each tumor sample based ...
      R/DEPTH.R:8 #' DEPTH evaluates the tumor heterogeneity level of each tumor sample based on gene expre...
      R/DEPTH.R:10 #' @param exp gene expression profiles in both tumor and normal samples (microarray or R...
      R/DEPTH.R:12 #' 1) if the "exp" dataset has normal samples and tumor samples, we can caculate the het...
      R/DEPTH.R:13 #' 2) else if the "exp" dataset only has tumor samples, we can caculate the heterogeneit...
      R/DEPTH.R:52         score[s, u] <- (as.numeric(exp_tum[s, u]) - mean(as.numeric(exp_tum[s, ])))^2
    * NOTE: Consider multiples of 4 spaces for line indents, 30 lines(30%) are not.
    First 6 lines:
      R/DEPTH.R:24   exp <- as.matrix(exp);
      R/DEPTH.R:25   gene <- exp[-1, 1];
      R/DEPTH.R:26   samp <- exp[1, -1];
      R/DEPTH.R:27   exp <- as.matrix(exp[-1, -1]);
      R/DEPTH.R:28   colnames(exp) <- samp;
      R/DEPTH.R:29   rownames(exp) <- gene;
    See http://bioconductor.org/developers/how-to/coding-style/
    See styler package: https://cran.r-project.org/package=styler as described in the BiocCheck
      vignette.
* Checking if package already exists in CRAN...
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

    * ERROR: Package must be removed from CRAN.
* Checking if new package already exists in Bioconductor...
* Checking for bioc-devel mailing list subscription...
    * NOTE: Cannot determine whether maintainer is subscribed to the bioc-devel mailing list
      (requires admin credentials).  Subscribe here:
      https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
    * ERROR: Maintainer must register at the support site; visit
      https://support.bioconductor.org/accounts/signup/ .


Summary:
ERROR count: 6
WARNING count: 2
NOTE count: 8
For detailed information about these checks, see the BiocCheck vignette, available at
https://bioconductor.org/packages/3.13/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#interpreting-bioccheck-output
BiocCheck FAILED.
$error
[1] "Do not use Author/Maintainer fields. Use Authors@R."                                                            
[2] "Remove Maintainer field. Use Authors@R [cre] designation."                                                      
[3] "No 'vignettes' directory."                                                                                      
[4] "At least 80% of man pages documenting exported objects must have runnable examples. The following pages do not:"
[5] "Package must be removed from CRAN."                                                                             
[6] "Maintainer must register at the support site; visit https://support.bioconductor.org/accounts/signup/ ."        

$warning
[1] "'heterogeneity' is an invalid BiocViews term."     "Import stats in DESCRIPTION as well as NAMESPACE."

$note
[1] "Consider adding these automatically suggested biocViews: Microarray"                                                                                                              
[2] "The Description field in the DESCRIPTION is made up by less than 3 sentences. Please consider\nexpanding this field, and structure it as a full paragraph"                        
[3] " Avoid 1:...; use seq_len() or seq_along()"                                                                                                                                       
[4] "Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements."                                                                        
[5] "Consider adding unit tests. We strongly encourage them. See\n  http://bioconductor.org/developers/how-to/unitTesting-guidelines/."                                                
[6] "Consider shorter lines; 11 lines (11%) are > 80 characters long."                                                                                                                 
[7] "Consider multiples of 4 spaces for line indents, 30 lines(30%) are not."                                                                                                          
[8] "Cannot determine whether maintainer is subscribed to the bioc-devel mailing list (requires admin\ncredentials).  Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel"

**Comment by lshep** [comment]
The biggest concern is that the package already exists on CRAN.  Is this the same package or were you unaware a package already existed with that name?

**Comment by WangX-Lab** [comment]
@lshep Yes, the package on CRAN has the same name as my package, and I didn't know when I first named the package that the 
 package with this name already existed on the CRAN platform.

**Comment by lshep** [comment]
You can not name your package the same as an existing.  To try and make things easier, we will close this issue and please submit a new issue when you have renamed your package.  
@nturaga We can remove DEPTH from git.bioconductor.org as the name is already taken on CRAN and will not be used.

**Comment by WangX-Lab** [comment]
@lshep @bioc-issue-bot  Thank you very much.

**Comment by WangX-Lab** [comment]
@lshep Is it possible to change the DEPTH to DEPTH1?

**Comment by lshep** [comment]
it should be uniquely different than the existing CRAN depth.  Using a numeric indicator typically indicates the next version of the existing package.

**Comment by WangX-Lab** [comment]
@lshep OK, thank you, I'll think about it.
