### ISSUE TITLE
(inactive) Rhisat

### ISSUE THREAD

**Issue by qxdu** [Bioconductor/Contributions#2426]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Carla-Radames/Rhisat

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by nturaga** [comment]
Hi @Carla-Radames 

I cannot seem to build and install your package locally on my Mac (Intel x86)

```
R CMD build Rhisat 
```

I've truncated the error, but it looks like this...

```
   In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/string:511:
   In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/string_view:179:
   In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__string:57:
   In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:649:
   In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/initializer_list:46:
   In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:37:
   ./version:1:1: error: expected unqualified-id
   0.1.6-beta
   ^
   ...
      0.1.6-beta
   ^
   In file included from tinythread.cpp:25:
   In file included from ./tinythread.h:87:
   In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/ostream:139:
   In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/locale:199:
   ./version:1:1: error: expected unqualified-id
   0.1.6-beta
   ^
   In file included from tinythread.cpp:25:
   In file included from ./tinythread.h:87:
   In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/ostream:142:
   ./version:1:1: error: expected unqualified-id
   0.1.6-beta
   ^
   fatal error: too many errors emitted, stopping now [-ferror-limit=]
   20 errors generated.
   make[1]: *** [hisat-inspect-s] Error 1
   make: *** [all] Error 2
   ERROR: compilation failed for package ‘Rhisat’
─  removing ‘/private/var/folders/1w/xf7rrsr1483d4rg7vwbkdy780000gp/T/Rtmpgvgqrm/Rinst105d92834588a/Rhisat’
         -----------------------------------
   ERROR: package installation failed
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  :
  System command 'R' failed, exit status: 1, stdout & stderr were printed
Type .Last.error.trace to see where the error occurred
```

I run into this issue and I'm unable to figure out the issue. It seems it's only happening with your `Rhisat` package on my machine and not other packages which have Rcpp code in them.

Any suggestions?

**Comment by nturaga** [comment]
I'm also not sure why you are adding this to your Makefile. 

https://github.com/Carla-Radames/Rhisat/blob/master/src/Makefile#L4

**Comment by qxdu** [comment]
Thank you sir. I have made some corrections for the package,  I would be grateful if you could check it again. 
For the first error, it may because I named a file "VERSION", maybe it cause some conflicts , now I have renamed it as "HISAT_VERSION".
For https://github.com/Carla-Radames/Rhisat/blob/master/src/Makefile#L4 , This line I wrote is to refer to the format of other R packages. I found that maybe it could be commented. 
Sorry for not being able to reply you in time, I have submitted another edition.

**Comment by qxdu** [comment]
@nturaga I forgot to @ you in time. Sir can you see my new submission?

**Comment by nturaga** [comment]
# Review

## DESCRIPTION

- Elaborate the Description to be more like a paper abstract.

- Is the email of the maintainer correct? The details of the
  maintainer in the vignette are different from that in the
  DESCRIPTION file.
  
	  contact:{wei-z14,w-zhang16}(at)mails.tsinghua.edu.cn

- No usage of Bioconductor infrastructure at all. 

## NAMESPACE 

ok

## NEWS

- include news file

## R 

- use `system2` instead of `system` in your call to the hisat library.

- I've noticed that not every functionality of hisat is captured in
  this package. I've got some reservations about that. 
  
  hisat is very extensive and very little of the functionality is
  encapsulated in the package.

- Overall, the package just allows the building of the index, adapter
  removal, and alignment.

## inst

- The CITATION in the inst directory, what paper does that point to? What
  does that have to do with the Rhisat package?

## man

ok

## tests 

- please add test cases

## vignettes 

ok

**Comment by nturaga** [comment]
We are also not sure the licensing is handled properly for AdapterRemoval (something would need to be in the package root folder); likely the same for `hisat` itself. 

The way the vignette does a replication of the help text for the binaries is not very useful.  The vignette is mostly consumed by replication of help text from the utilities, it makes one wonder exactly what is being added by wrapping in R and submitting to Bioconductor? 

Please explain to the reviewers the logic behind the design. It would also be helpful to do this in the vignette.  

Take a look at `Rsubread` package as an example of a package solving a related problem.

**Comment by qxdu** [comment]
> We are also not sure the licensing is handled properly for AdapterRemoval (something would need to be in the package root folder); likely the same for `hisat` itself.
> 
> The way the vignette does a replication of the help text for the binaries is not very useful. The vignette is mostly consumed by replication of help text from the utilities, it makes one wonder exactly what is being added by wrapping in R and submitting to Bioconductor?
> 
> Please explain to the reviewers the logic behind the design. It would also be helpful to do this in the vignette.
> 
> Take a look at `Rsubread` package as an example of a package solving a related problem.

dear Nitesh,
thanks for your kind reminder.
I am fixing it now and modifying it with reference to your suggestion. And It will be resubmitted in the next or two week.

**Comment by nturaga** [comment]
Hi,

It’s not just the vignette. There are other issues with this package as well. 

The other big issue is you don’t have “any” usage of existing Bioconductor packages to make it interoperable with the larger package ecosystem we provide. Please address this concern as pointed out in the documentation here - http://contributions.bioconductor.org/description.html#depends-imports-suggests-enhances. 

I’m trying to understand if you’ve contacted the `hisat` authors and had any input from them regarding your package? If I were you, I’d contact them and see if they have any valuable suggestions on the package and it’s functionality.

Best,

Nitesh

**Comment by nturaga** [comment]
There is also a `Rhisat2` package in Bioconductor. https://bioconductor.org/packages/release/bioc/html/Rhisat2.html 

Please note the differences as well between what you are submitting and `Rhisat2`.

**Comment by csoneson** [comment]
👋🏻 `Rhisat2` developer here. I don't think this is a duplicate (since the underlying `hisat` and `hisat2` are different software packages), but note that the developers of `hisat` explicitly [recommend](http://ccb.jhu.edu/software/hisat/index.shtml) that users switch to `hisat2`. 

The other thing I was wondering about is the inclusion of `adapterremoval`. This seems to be already wrapped in the `Rbowtie2` package, and the collection of files (as well as the version) look the same. Does it need to be included here as well? Btw, it looks like the `version_info.cpp` file was accidentally copied from `Rbowtie2` (it refers to the version of `bowtie2`, but not of `hisat`).

**Comment by nturaga** [comment]
Thank you @csoneson for your valuable comments on this contribution. 

I would appreciate it if @Carla-Radames would answer the questions posed here.

**Comment by lshep** [comment]
@Carla-Radames  please respond to the previously posted questions/concerns.

**Comment by qxdu** [comment]
> Thank you @csoneson for your valuable comments on this contribution.
> 
> I would appreciate it if @Carla-Radames would answer the questions posed here.

Thank you sir. Sorry for not being able to answer you in time. I have been busy with my graduation thesis, and also not able to get the advice from the author of Hisat. I have fixed major problems, including your advice on tests file, functionality and so on. But I haven't added the User-guide file. 
I have check the Rbowtie2 and sure that I should remove AdapterRemoval. But I could only fix the last 2 bugs only in this weekend.  All the other bugs have been fixed.

**Comment by qxdu** [comment]
@nturaga I forgot to @ you before. I have fixed the problem you said. But about vignettes, I'm little bit not sure because I only wrap the Hisat package as a R format, without new functions added.  I've emailed the author of hisat asking for suggestions, but still haven't gotten any response so far. Therefore I did not extend new functionality. 
Thanks for your kindness.

**Comment by nturaga** [comment]
Thanks for your reply. I'm specifically looking for answers to the questions posted by @csoneson, and it seems like they have not been answered to the degree I would like. 

Good luck with your thesis. We can wait till you have more time to respond.

**Comment by nturaga** [comment]
Hi @Carla-Radames ,

I'm guessing your package will be inactive for a while? Please confirm and I'll close the issue. You can always reopen later. 

There is no point leaving it open.

**Comment by qxdu** [comment]
@nturaga  Thank you sir. this issue could be closed. My senior said that in the case of already having Rhisat2, it does not make much sense to continue the modification of Rhisat. According to the paper, it is difficult for me to explain the advantages and application scenarios of Rhisat compared to Rhisat2. Therefore, at the moment I can't make more critical changes.

Thank you for your kindness. If I have further findings, I will submit it again. You can close this issue.

**Comment by nturaga** [comment]
Thanks for your comment. I'm closing the issue now, but feel free to open it again. 

Best wishes.
