### ISSUE TITLE
(inactive) Ribostan

### ISSUE THREAD

**Issue by zslastman** [Bioconductor/Contributions#2448]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zslastman/Ribostan

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
see https://github.com/zslastman/RiboStan/issues/2 -- can't even build with current R/Bioc

**Comment by zslastman** [comment]
Hi, sorry about that! I will be able to give this my focus again tuesday
next week, will fix the licence issues and confirm it builds on my own
machine, with the most recent bioc docker image.

**Comment by vjcitn** [comment]
Hi any updates here?

**Comment by zslastman** [comment]
Hi! Sorry for the long delay. Changing jobs and address during the pandemic has taken up my time this past month. I'll be able to push again within two weeks.

**Comment by lshep** [comment]
@zslastman  if you do not have time to work on the submission we can close the issue for inactivity and you can request it be opened again once your time allows.

**Comment by zslastman** [comment]
Sorry for the delay guys, I'm available to work on the package again now.

https://github.com/zslastman/RiboStan/issues/2 is fixed

Can you let me know how to go about setting up a build environment that's identical to the one used by Bioconductor? My current understanding is that I want to load the most recent docker image and then run R CMD build, but I notice this doesn't work on e.g. the DESeq2 source code, (it fails because the vignette dependency rmarkdown isn't installed). So I must not have it right.

**Comment by vjcitn** [comment]
How to "set[...] up a build environment that's identical to the one used by Bioconductor" is pretty much an open question at this time.  We are working on github action templates that should eventually accomplish this.  You are welcome to discuss the issue further on bioc-devel mailing list, detailing your expectations and efforts.  I am working on pre-checks for your package now.

**Comment by vjcitn** [comment]
Did you run R CMD check on your package source tarball before pushing?  Do so with version bumps for every source code change.  With 
```
commit 8d233ee11231f88ef069693ba1cbc18c3c3446f3
Author: Dermot Harnett <zslastman@gmail.com>
Date:   Thu Feb 17 14:47:25 2022 -0500

    GRlists not imported

```
I am getting
```
--- re-building ‘Ribostan.rmd’ using rmarkdown
Quitting from lines 71-76 (Ribostan.rmd) 
Error: processing vignette 'Ribostan.rmd' failed with diagnostics:
length(tokeep) > 0 is not TRUE
--- failed re-building ‘Ribostan.rmd’
```

**Comment by vjcitn** [comment]
Even INSTALL is noisy
```
PC002284:SUBMISSIONS vincentcarey$ R CMD INSTALL Ribostan
1/11 packages newly attached/loaded, see sessionInfo() for details.
* installing to library '/Users/vincentcarey/R-dev-dist/lib/R/library'
* installing *source* package 'Ribostan' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
1/11 packages newly attached/loaded, see sessionInfo() for details.
Note: wrong number of arguments to 'sqrt' 
Note: wrong number of arguments to '==' 
Note: wrong number of arguments to '>' 
Note: wrong number of arguments to '>' 
Note: wrong number of arguments to '==' 
Note: wrong number of arguments to '==' 
Note: wrong number of arguments to '>' 
Note: wrong number of arguments to '/' 
** help
*** installing help indices
** building package indices
1/11 packages newly attached/loaded, see sessionInfo() for details.
** installing vignettes
** testing if installed package can be loaded from temporary location
1/11 packages newly attached/loaded, see sessionInfo() for details.
** testing if installed package can be loaded from final location
1/11 packages newly attached/loaded, see sessionInfo() for details.
** testing if installed package keeps a record of temporary installation path
* DONE (Ribostan)
```

**Comment by vjcitn** [comment]
I am going to let it go into the build/check process for review.

**Comment by zslastman** [comment]
Okay, thanks Vincent, and sorry no I wasn't running check on the tarball. I'd been using devtools::check, but will switch to tarball + R CLI.

What is the correct method of specifying dependencies and then building such that all dependencies are installed? Again I had been using devtools but I guess this isn't bioconductor koshure. Should I simply assume that all dependencies, including e.g. BiocStyle for the vignettes, are present on the system I"m building on?

**Comment by vjcitn** [comment]
Good questions.  We endeavor to answer these on the developer guidelines so if those are not sufficiently clear please pose questions at bioc-devel.  We have automated the derivation of dependencies on R packages so you can assume all packages from CRAN or Bioconductor that are imported or suggested or depended upon or enhancing are available.  Packages outside these two regulated environments cannot be used at all.  As for system dependencies like runtime libraries the SystemRequirements field in DESCRIPTION should be used.  I don't think there's a standard syntax/vocabulary for those requirements yet.  @lshep @jwokaty

**Comment by ococrook** [comment]
@zslastman, Could you remove the ERRORs in the build report, I can start reviewing the package once that's complete

**Comment by zslastman** [comment]
Yes, apologies, only get them myself when I installed on a fresh system.

Also removing the non-standard evaluation from the dplyr functions to clean up the build report.

**Comment by lshep** [comment]
@zslastman  may we expect updates soon?  We like to see progress within a 3-4 week time frame of leaving comments and feedback? If you  have an updated version to clean up the ERRORs please remember to activate your GitCredentials account https://git.bioconductor.org/BiocCredentials  and push the update to git.bioconductor.org with a valid version bump to trigger a new build as described http://contributions.bioconductor.org/git-version-control.html#new-package-workflow

**Comment by zslastman** [comment]
Hi Ishep. Yes, sorry for the delay. I'll update by next weekend at the latest.

**Comment by ggvillamil** [comment]
Hi! Ownership of the repository for this package has been transferred to https://github.com/ohlerlab/RiboStan. We would like to resume the submission process. Is it possible to re-open this issue?

**Comment by lshep** [comment]
Should maintainer access still be @zslastman  or does this need to be updated ?  FWIW there is not Maintainer@R official field;  Specifying "Cre" in Authors@R designates the maintainer.

**Comment by zslastman** [comment]
You should update the maintainer, Gabe will take over.

**Comment by ggvillamil** [comment]
As @zslastman said, I will take over as maintainer. I am Gabe. :)

**Comment by lshep** [comment]
@ggvillamil do you have a BiocCredentials account; it doesn't look like it?  If not I can set one up for you. what would be the best email to use?

**Comment by ggvillamil** [comment]
Hi @lshep. Thanks for the assistance! I don't have an account yet. My email address is gabriel.villamil@mdc-berlin.de.

**Comment by lshep** [comment]
We have updated the credentials on our side. I will be sending you an email for how to activate your BiocCredentials account to add ssh keys for access

**Comment by lshep** [comment]
@ggvillamil this should have been taken care of. You should push to git.bioconductor.org to trigger a build report to proceed.

**Comment by LiNk-NY** [comment]
Is Oliver @ococrook still taking a look at this? Thanks!

**Comment by lshep** [comment]
@LiNk-NY sorry about that; I'll check the code that should prevent a reassignment if a reviewer is already assigned if reopened.

**Comment by ggvillamil** [comment]
Hi @lshep. I added an ssh key to my profile and was prompted that it was successfully added. However, my profile does not show any ssh keys and the list of packages I have access to is empty.

**Comment by lshep** [comment]
I see your account is active but also see no ssky keys added.  Did you save the profile at the bottom once you added the key?

**Comment by ggvillamil** [comment]
Yes, I click the submit button and get the message: "New SSH Key for 'gabriel.villamil@mdc-berlin.de' was successfully added. An email confirmation of the change will not be sent. The updated information will be displayed in your User Profile."

But there are no ssh keys when I check my profile.

**Comment by lshep** [comment]
Can you please try again?  This is rather odd as it is not occurring with anyone else.  Another work around would be to add the ssh key to your github account as keys are also automatically pulled from there.

**Comment by ococrook** [comment]
Ill review this once a build is triggered. Thanks

**Comment by ggvillamil** [comment]
It is still happening unfortunately. Does it matter what kind of SSH key I am submitting? Right now I am submitting an ED25519 key.

I also noticed that the SSH key I have in my Github account is not being automatically pulled. I have had it from before I activated my BiocCredentials account as I generally use SSH to push to Github.

**Comment by ggvillamil** [comment]
Would it make sense to try re-making the BiocCredentials acount?

**Comment by lshep** [comment]
Since no one else seems to be having issues, yes that is probably the best option.  I can try that now.  Give me a few minutes to reset. I'll email you with a password to activate the new account.

**Comment by lshep** [comment]
Do you plan on submitting more change to fix the ERROR's, Warnings, and Notes that were occurring?

**Comment by ggvillamil** [comment]
Apologies for the delay. Will push some changes tomorrow.

**Comment by lshep** [comment]
It also has been brought to our attention you have an invalid field in your DESCRIPTION.  Please remove `Maintainers@R` as there is no such field.  Authors@R is sufficient; using "cre" in Authors@R designates the maintainer.

**Comment by ococrook** [comment]
Hi!

Thanks for the submission, I had a quick look through the build report. The main blockers to getting a comprehensive review performed are the build ERROR, Warnings and Notes.

Currently, there are quite a few issues: your unit tests are failing, the package documentation is not sufficient (runnable examples), the package is too large and there are number of small issues highlighted by the notes. Once you've addressed these issues a more comprehensive review can take place.

Thanks,
Olly

**Comment by lshep** [comment]
Please make sure the package can build without ERROR before a review would take place.

**Comment by ococrook** [comment]
Can we archive this? Its been 5 months building with ERROR?
