### ISSUE TITLE
CBEA Submission

### ISSUE THREAD

**Issue by qpmnguyen** [Bioconductor/Contributions#2449]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/qpmnguyen/CBEA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
# Package `CBEA` Review

This package is in good shape but there are some issues need to be fixed.

## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 12 import(TreeSummarizedExperiment)

## Documentation
- [ ] Vignette should have an *Introduction* section..
    * rmd file vignettes/basic_usage.Rmd

## R code
- [ ] `is()` or inherits() instead of `class()`.
	* In file R/cbea_methods.R:
		+ at line 133 found '        check_numeric <- vapply(tab, class)'
- [ ] `message()`, `warning`, `stop` instead of `cat`.
	* In file R/cbea_internals.R:
		+ at line 236 found '            cat("There are NA values here")'
	* In file R/utils.R:
		+ at line 31 found '        cat(paste(n_components, "components!", "\n"))'
		+ at line 46 found '        cat(paste(n_components, "components!", "\n"))'
- [ ] Vectorize: no unnecessary `for` loops present.
	* In file R/set_construction.R:
		+ at line 124 found '    for (i in seq_along(set_names)) {'
	* In file R/utils.R:
		+ at line 34 found '    for (i in seq_len(n_components)) {'
		+ at line 49 found '    for (i in seq_len(n_components)) {'
- [ ] `::` is not suggested in source code unless you can make sure all the packages are imported.
	* In file R/cbea_internals.R:
		+ at line 34 found '    R <- purrr::map_dfc(set_list, ~ {'
		+ at line 68 found '    R <- tibble::add_column(R, sample_id = rownames(ab_tab), .before = 1)'
		+ at line 150 found '        data <- stats::na.omit(data)'
		+ at line 152 found '            rlang::abort("More than 50% of the data is NA,'
		+ at line 183 found '                params <- rlist::list.append(params, start = init,'
		+ at line 185 found '                fit <- do.call(fitdistrplus::fitdist, params)'
		+ at line 188 found '                params <- rlist::list.append(params, x = data)'
		+ at line 217 found '            rlang::abort("Normal requires both mean and standard deviation")'
		+ at line 222 found '            rlang::abort("Mixture normal requires mu,'
		+ at line 227 found '            rlang::abort("Each named parameter much have values for'
		+ at line 233 found '        param <- rlist::list.append(q = as.vector(scores), param)'
		+ at line 279 found '        rlang::abort("The two distributions to combine'
		+ at line 284 found '            rlang::abort("Normal requires both mean and standard deviation")'
		+ at line 289 found '            rlang::abort("Mixture normal requires mu,'
		+ at line 295 found '              rlang::abort("Each named parameter much have values for'
		+ at line 340 found '    opt <- stats::optim('
	* In file R/cbea_methods.R:
		+ at line 61 found '    tab <- phyloseq::otu_table(obj)'
		+ at line 64 found '    if (phyloseq::taxa_are_rows(obj) == TRUE) {'
		+ at line 97 found '    tab <- SummarizedExperiment::assays(obj)[[1]]'
	* In file R/set_construction.R:
		+ at line 31 found '    table <- phyloseq::tax_table(obj)'
		+ at line 33 found '        rlang::abort("Rank name not part of taxonomy table")'
		+ at line 50 found '    table <- SummarizedExperiment::rowData(obj)'
		+ at line 93 found '    sets <- BiocSet::BiocSet(set_list)'
		+ at line 119 found '        dplyr::pull(member) %>%'
		+ at line 122 found '    member <- rlang::sym(member)'
		+ at line 126 found '        dplyr::filter({{ member }} == set_names[i]) %>%'
		+ at line 127 found '        dplyr::pull(id)'
		+ at line 130 found '    sets <- BiocSet::BiocSet(set_list)'
		+ at line 159 found '    unq_names <- stats::na.omit(unique(all_names))'
		+ at line 160 found '    unq_names <- unq_names[!stringr::str_ends(unq_names, "NA")]'
		+ at line 162 found '    sets <- purrr::map(unq_names, ~ {'
		+ at line 167 found '    sets <- BiocSet::BiocSet(sets)'
		+ at line 168 found '    set_sizes <- BiocSet::es_elementset(sets) %>%'
		+ at line 169 found '        dplyr::count(set, name = "size")'
		+ at line 171 found '    sets <- BiocSet::left_join_set(sets, set_sizes)'
		+ at line 172 found '    if (lobstr::obj_size(sets) / 1e6 > 100) {'
		+ at line 173 found '        rlang::warn("Object size is larger than 100MB")'
		+ at line 217 found '    n_set <- BiocSet::filter_elementset(set, element %in% ref_names)'
		+ at line 228 found '    ref_names <- phyloseq::taxa_names(obj)'
		+ at line 229 found '    n_set <- BiocSet::filter_elementset(set, element %in% ref_names)'
		+ at line 251 found '            tax_ids <- rlang::sym(tax_ids)'
		+ at line 252 found '            ref_names <- obj %>% dplyr::pull({{ tax_ids }})'
		+ at line 257 found '    n_set <- BiocSet::filter_elementset(set, element %in% ref_names)'
		+ at line 272 found '    n_set <- BiocSet::filter_elementset(set, element %in% ref_names)'
	* In file R/utils.R:
		+ at line 35 found '        comp[[i]] <- lambda[i] * stats::pnorm(q, mu[i], sigma[i], log.p = log)'
		+ at line 50 found '        comp[[i]] <- lambda[i] * stats::dnorm(x, mu[i], sigma[i], log = log)'

- [ ] Functional programming: no code repetition.
	* repetition in `scale_scores` and `estimate_distr`
	* repetition in `const_set` and `unify_sets`
	* repetition in `dmnorm` and `pmnorm`

- [ ] Function arguments are tested for validity.
	* length of `distr` should be checked in `scale_scores`, `combine_distr`

## C and Fortran code
- [] `Makevars` and `Makefile` not within a package.

**Comment by qpmnguyen** [comment]
Thank you so much for the code review! These are really useful suggestions to make the package better. I have a couple of clarifying questions with regards to some of the comments: 

In the comment

> :: is not suggested in source code unless you can make sure all the packages are imported

I am assuming that this means Bioconductor prefers direct imports (using `importFrom`) instead of specifying namespaces (`::`) and that I should just remove all namespace mentions. Is this what you're looking for?

In the comment
>  Makevars and Makefile not within a package.    

Does this mean that there are `Makevars/Makefile` in the package that should be removed? I can't really seem to find it anywhere. I was wondering if you can point me to the file? 

Thank you so much once again!

**Comment by jianhong** [comment]
> > :: is not suggested in source code unless you can make sure all the packages are imported
> 
> I am assuming that this means Bioconductor prefers direct imports (using `importFrom`) instead of specifying namespaces (`::`) and that I should just remove all namespace mentions. Is this what you're looking for?

I mean `::` is easy for read but there is a potential issue during development if you happed to removed the dependence of the package in the DESCRIPTION and it will not throw an error if you manually set the searching path.

> In the comment
> 
> > Makevars and Makefile not within a package.
> 
> Does this mean that there are `Makevars/Makefile` in the package that should be removed? I can't really seem to find it anywhere. I was wondering if you can point me to the file?
> 
It means I did not see any Makevars or Makefile in the `src` folder. If you put it somewhere, please let me know.

**Comment by qpmnguyen** [comment]
Thank you very much for your responses! That makes sense for the `::` issue. 

I do not have any `Makevars`/`Makefile` in the package. I am not really sure what to add since the latest [Rcpp documentation](https://dirk.eddelbuettel.com/code/rcpp/Rcpp-package.pdf) seems to indicate that I don't need to add `Makevars`\\`Makevars.win` files anymore. I can still a `Makevars` file anyways according to the documentation with the following code: 

```
## Use the R_HOME indirection to support installations of multiple R version
PKG_LIBS = `$(R_HOME)/bin/Rscript -e "Rcpp:::LdFlags()"`
```

Please let me know if I'm missing anything!

**Comment by jianhong** [comment]
Good to know that. I see you are asking `Rcpp >= 1.0.7`, then this is my mistake. Just forget this comment.

**Comment by qpmnguyen** [comment]
Hi @jianhong, 

I apologize for the late response. I want to let you know that the manuscript underlying this package is undergoing some major revisions, which would impact this implementation (and likely change a lot of it). This would delay fixing the issues mentioned above while also introducing new code that needs to be reviewed. The timeline at the moment would be around the first week of February. 

What is the best course of action here? Should I leave this issue open and push a new version of the code for re-review or should I close the issue and open a new one once I'm ready for submission? 

Thank you so much for all your advice.

**Comment by lshep** [comment]
Let's close the issue for now.  When you are ready to make updates please request that this issue be reopened to push all the changes too.

**Comment by qpmnguyen** [comment]
@jianhong @lshep Hi! I have finished revisions to the package and I am ready to re-do the submission process. Please let me know if I can re-open this issue to push new changes.

**Comment by qpmnguyen** [comment]
Hi! Just wondering if there is anything else I can do! I would love to make it into the coming Bioconductor release.

**Comment by jianhong** [comment]
# Package 'CBEA' Review
The package passed check and build. It is almost there. However there are several things need to be fixed.

## The DESCRIPTION file
- [ ] R version should be no less than 4.2
- [ ] NOTE: Consider adding these automatically suggested
      biocViews: DataImport
      
## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 17 import(BiocSet)
	* in line 18 import(TreeSummarizedExperiment)

## R code

- [ ] Remove unused code.
	* In file R/cbea_internals.R:
		+ at line 40 found '    #bpstopOnError(parallel_backend) <- TRUE'
		+ at line 46 found '    # check_res <- bpok(R)'
		+ at line 47 found '    # if (sum(check_res) != length(R)){'
		+ at line 48 found '    #     print(R)'
		+ at line 49 found '    #     idx <- which(check_res == FALSE)'
		+ at line 50 found '    #     for (i in seq_along(idx)){'
		+ at line 51 found '    #         print(names(R)[idx[i]])'
		+ at line 52 found '    #         print(noquote(attr(R[[idx[i]]], "traceback")))'
		+ at line 53 found '    #     }'
		+ at line 54 found '    #     stop("Errors were returned. Check the traceback for more details")'
		+ at line 55 found '    # }'
        
- [ ] Functional programming: code repetition.
	* repetition in `combine_distr` and `scale_scores`
		+ in combine_distr
			- line 11:    }
			- line 12:    if (distr == "norm") {
			- line 13:        if (length(intersect(names(perm), c("mean", "sd"))) != 
			- line 14:            2) {
			- line 15:            stop("Normal requires both mean and standard deviation")
			- line 16:        }
			- line 18:    }
			- line 19:    else if (distr == "mnorm") {
			- line 20:        if (length(intersect(names(perm), c("mu", "lambda", "sigma"))) != 
			- line 21:            3) {
			- line 22:            stop("Mixture normal requires mu,\n                         lambda and sigma arguments")
			- line 23:        }
			- line 24:        check_perm <- all(vapply(perm, FUN = length, FUN.VALUE = 1) == 
			- line 25:            2)
			- line 26:        check_unperm <- all(vapply(unperm, FUN = length, FUN.VALUE = 1) == 
			- line 27:            2)
			- line 28:        if (check_perm == FALSE | check_unperm == FALSE) {
			- line 29:            stop("Each named parameter much have values for\n                           each of the two components.\n                           Number of components restricted to 2")
			- line 30:        }
			- line 33:    }
			- line 34:    else if (distr == "lst") {
			- line 35:        if (length(intersect(names(perm), c("df", "mu", "sigma"))) != 
			- line 36:            3) {
			- line 37:            stop("Location-scale t-distribution requires mu, df and sigma arguments")
			- line 38:        }
		+ in scale_scores
			- line 5:    if (distr == "norm") {
			- line 6:        f <- "pnorm"
			- line 7:        if (length(intersect(names(param), c("mean", "sd"))) != 
			- line 8:            2) {
			- line 9:            stop("Normal requires both mean and standard deviation")
			- line 10:        }
			- line 12:    else if (distr == "mnorm") {
			- line 13:        f <- "pmnorm"
			- line 14:        if (length(intersect(names(param), c("mu", "lambda", 
			- line 15:            "sigma"))) != 3) {
			- line 16:            stop("Mixture normal requires mu,\n                         lambda and sigma arguments")
			- line 17:        }
			- line 18:        check_param <- all(vapply(param, FUN = length, FUN.VALUE = 1) == 
			- line 19:            2)
			- line 20:        if (check_param == FALSE) {
			- line 21:            stop("Each named parameter much have values for\n                       each of the two components.\n                       Number of components restricted to 2")
			- line 22:        }
			- line 23:    }
			- line 24:    else if (distr == "lst") {
			- line 25:        f <- "plst"
			- line 26:        if (length(intersect(names(param), c("mu", "df", "sigma"))) != 
			- line 27:            3) {
			- line 28:            stop("Location-scale t-distribution requires mu, sigma, and df arguments")
			- line 29:        }
            
## Documentation
- [ ] NOTE: Consider adding runnable examples to the
  following man pages which document exported objects:
  reexports.Rd
  
- [ ] In line 132:432 of basic_usage.Rmd, "``" is used. Should that be "`"?

**Comment by qpmnguyen** [comment]
Hi @jianhong! Thank you very much for the prompt review! I've addressed your comments below. Let me know if there are any issues!

 ## The DESCRIPTION file
 * [x]  R version should be no less than 4.2
 * [x]  NOTE: Consider adding these automatically suggested
   biocViews: DataImport
        I added the BiocView but my package isn't really an infrastructure package 

## The NAMESPACE file
* [x]  Selective imports using `importFrom` instead of _import all_ with `import`.

## R code
* [x]  Remove unused code.
* [x]  Functional programming: code repetition.
## Documentation
* [ ]  NOTE: Consider adding runnable examples to the
   following man pages which document exported objects:
   reexports.Rd
        I'm a bit confused about this one. The `reexports.Rd` file exports `tidy`/`glance` generics from the `generics` package so I can use `broom` verbs with my output. It doesn't seem like I need (or can) include examples according to instructions from the [package developers](https://generics.r-lib.org/), and an [example implementation](https://github.com/tidymodels/recipes/blob/main/R/reexports.R). I have documented all methods associated with this generic including providing examples to run. I think this is enough for `reexports.Rd` however let me know if this is wrong! 
* [x]  In line 132:432 of basic_usage.Rmd, "``" is used. Should that be "`"?

**Comment by jianhong** [comment]
It is almost there. If following issue is addressed, then it is ready to go.

-[ ] NOTE: Cannot determine whether maintainer is
      subscribed to the bioc-devel mailing list
      (requires admin credentials). Subscribe here:
      https://stat.ethz.ch/mailman/listinfo/bioc-devel

**Comment by lshep** [comment]
@jianhong  it looks like that is resolved it the last build report that was posted to the issue.  Trust the SPB auto builds for the report of mailing list since it requires confidential credentials to get access it will print that note when anyone runs it locally without those credentials being present.

**Comment by jianhong** [comment]
> @jianhong it looks like that is resolved it the last build report that was posted to the issue. Trust the SPB auto builds for the report of mailing list since it requires confidential credentials to get access it will print that note when anyone runs it locally without those credentials being present.

Great! I will label it as accepted.

**Comment by qpmnguyen** [comment]
Thank you so much @jianhong and @lshep for all your help and support!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/qpmnguyen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CBEA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CBEA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
