### ISSUE TITLE
CompoundDb

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/Contributions#2466]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/EuracBiomedicalResearch/CompoundDb/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
# Package 'CompoundDb' Review

The package passed check and build. It is in pretty good shape. However there are several things need to be fixed.

## The DESCRIPTION file
- [ ] Update R version dependency from 3.4 to 4.2.0.

## R code
- [ ] No `paste` in `message()`, `message`, `stop`. Please move the `paste` outside of the functions.
	* In file R/AnnotationFilters.R:
		+ at line 451 found '        stop("Filter(s) ", paste(have_flts[!got_it], collapse = ","),'
	* In file R/createCompDbPackage.R:
		+ at line 834 found '            stop(paste(txt, collapse = "\n"))'
		+ at line 872 found '            stop(paste(txt, collapse = "\n"))'
	* In file R/IonDb.R:
		+ at line 249 found '            stop(paste(txt, collapse = "\n"))'
	* In file R/query-engine.R:
		+ at line 34 found '        stop("Columns ", paste0(columns[!col_ok], collapse = ", "),'
		+ at line 127 found '        else stop("Tables ", paste(tbls_used, collapse = ", ") ,'
- [ ] `message()`, `warning()`, `stop()` instead of `cat`.
	* In file R/CompDb-methods.R:
		+ at line 16 found '    cat("class:", class(object), "\n")'
		+ at line 19 found '        cat(" data source:", .metadata_value(con, "source"), "\n")'
		+ at line 20 found '        cat(" version:", .metadata_value(con, "source_version"), "\n")'
		+ at line 21 found '        cat(" organism:", .metadata_value(con, "organism"), "\n")'
		+ at line 24 found '        cat(" compound count:", cmp_nr[1, 1], "\n")'
		+ at line 28 found '            cat(" MS/MS spectra count:", spctra[1, 1], "\n")'
		+ at line 30 found '    } else cat(" no database connection available\n")'
	* In file R/IonDb-methods.R:
		+ at line 12 found '        cat(" ion count:", ion_nr[1, 1], "\n")'
	* In file R/MsBackendCompDb.R:
		+ at line 150 found '        cat(" data source:", .metadata_value(object@dbcon, "source"), "\n")'
		+ at line 151 found '        cat(" version:", .metadata_value(object@dbcon, "source_version"), "\n")'
		+ at line 152 found '        cat(" organism:", .metadata_value(object@dbcon, "organism"), "\n")'
- [ ] `::` and `:::` is not suggested in source code unless you can make sure all the packages are imported.
	* In file R/CompDb-methods.R:
		+ at line 50 found '             "with 'Biobase::install(\"RforMassSpectrometry/Spectra\")'")'
	* In file R/CompDb.R:
		+ at line 309 found 'CompDb <- function(x, flags = RSQLite::SQLITE_RO) {'
	* In file R/MsBackendCompDb.R:
		+ at line 229 found '                  miss_res <- lapply(miss_cols, Spectra:::.get_column,'
- [ ] Vectorize: no unnecessary `for` loops present.
	* In file R/createCompDbPackage.R:
		+ at line 730 found '    for (col in cols) {'
	* In file R/query-engine.R:
		+ at line 245 found '    for (i in seq_along(columns_tbl)) {'
- [ ] Use `file.path` to replace `paste`
	* In file R/createCompDbPackage.R:
		+ at line 563 found '    db_file <- paste0(path, "/", .db_file_from_metadata(metadata), ".sqlite")'
- [ ] Remove unused code.
	* In file R/CompDb.R:
		+ at line 357 found '    ## all(c("msms_spectrum_peak", "msms_spectrum_metadata") %in%'
		+ at line 358 found '    ##     names(.tables(x)))'
	* In file R/createCompDbPackage.R:
		+ at line 336 found '        ## get the name(s) -> name + aliases'
		+ at line 862 found '    ## if (db) {'
		+ at line 864 found '    ##     is_ok <- colnames(x) %in% .req_cols'
		+ at line 865 found '    ##     if (any(!is_ok)) {'
		+ at line 866 found '    ##         txt <- c(txt, paste0("Column(s) ", paste(colnames(x)[!is_ok]),'
		+ at line 867 found '    ##                              " are not expected"))'
		+ at line 868 found '    ##     }'
		+ at line 869 found '    ## }'
	* In file R/query-engine.R:
		+ at line 151 found '    ## if (any(x == "msms_spectrum_peak") & length(x) > 1)'
		+ at line 152 found '    ##     x <- c(x, "msms_spectrum_metadata")'
- [ ] Functional programming: code repetition.
	* repetition in `.append_msms_spectra` and `.insert_msms_spectra`
		+ in .append_msms_spectra
			- line 1:    x) 
			- line 2:{
			- line 3:    x <- .msms_spectrum_add_missing_columns(x)
			- line 4:    x$collision_energy <- as.character(x$collision_energy)
			- line 10:    .valid_msms_spectrum(x, blob = is.list(x$mz))
			- line 11:    x <- .add_mz_range_column(x)
			- line 12:    msms_spectrum_peak <- x[, c("spectrum_id", "mz", "intensity")]
			- line 13:    if (is.list(msms_spectrum_peak$mz)) 
			- line 14:        msms_spectrum_peak <- .expand_spectrum_df(msms_spectrum_peak)
			- line 15:    if (!is.numeric(msms_spectrum_peak$mz) || !is.numeric(msms_spectrum_peak$intensity)) 
			- line 16:        stop("Columns 'mz' and 'intensity' should only contain numeric values")
			- line 17:    msms_spectrum_peak <- msms_spectrum_peak[order(msms_spectrum_peak$spectrum_id, 
			- line 18:        msms_spectrum_peak$mz), ]
		+ in .insert_msms_spectra
			- line 1:    x) 
			- line 2:{
			- line 3:    x <- .msms_spectrum_add_missing_columns(x)
			- line 4:    x$collision_energy <- as.character(x$collision_energy)
			- line 5:    .valid_msms_spectrum(x, blob = is.list(x$mz))
			- line 6:    x <- .add_mz_range_column(x)
			- line 7:    msms_spectrum_peak <- x[, c("spectrum_id", "mz", "intensity")]
			- line 8:    if (is.list(msms_spectrum_peak$mz)) 
			- line 9:        msms_spectrum_peak <- .expand_spectrum_df(msms_spectrum_peak)
			- line 10:    if (!is.numeric(msms_spectrum_peak$mz) || !is.numeric(msms_spectrum_peak$intensity)) 
			- line 11:        stop("Columns 'mz' and 'intensity' should only contain numeric values")
			- line 12:    msms_spectrum_peak <- msms_spectrum_peak[order(msms_spectrum_peak$spectrum_id, 
			- line 13:        msms_spectrum_peak$mz), ]
	* repetition in `.valid_compound` and `.valid_ion`
		+ in .valid_compound
			- line 2:{
			- line 3:    txt <- character()
			- line 4:    if (!is.data.frame(x)) 
			- line 5:        txt <- c(txt, "'x' is supposed to be a data.frame")
			- line 9:    got_it <- .req_cols %in% colnames(x)
			- line 10:    if (!all(got_it)) {
			- line 11:        txt <- c(txt, paste0("Miss required columns: ", paste0(.required_compound_columns[!got_it], 
			- line 12:            collapse = ", ")))
			- line 13:    }
			- line 14:    else {
			- line 17:    }
			- line 18:    if (length(txt)) 
			- line 19:        if (error) 
			- line 20:            stop(paste(txt, collapse = "\n"))
			- line 21:        else txt
			- line 22:    else TRUE
		+ in .valid_ion
			- line 2:{
			- line 3:    txt <- character()
			- line 4:    if (!is.data.frame(ions)) 
			- line 5:        txt <- c(txt, "'ions' is supposed to be a data.frame")
			- line 6:    got_it <- .required_ion_columns %in% colnames(ions)
			- line 7:    if (!all(got_it)) {
			- line 8:        txt <- c(txt, paste0("Miss required columns: ", paste0(.required_ion_columns[!got_it], 
			- line 9:            collapse = ", ")))
			- line 10:    }
			- line 11:    else {
			- line 23:    }
			- line 24:    if (length(txt)) {
			- line 25:        if (error) 
			- line 26:            stop(paste(txt, collapse = "\n"))
			- line 27:        else txt
			- line 28:    }
	* repetition in `.valid_compound` and `.valid_metadata`
		+ in .valid_compound
			- line 17:    }
			- line 18:    if (length(txt)) 
			- line 19:        if (error) 
			- line 20:            stop(paste(txt, collapse = "\n"))
			- line 21:        else txt
			- line 22:    else TRUE
		+ in .valid_metadata
			- line 18:    }
			- line 19:    if (length(txt)) 
			- line 20:        if (error) 
			- line 21:            stop(paste(txt, collapse = "\n"))
			- line 22:        else txt
			- line 23:    else TRUE
	* repetition in `.valid_ion` and `.valid_metadata`
		+ in .valid_ion
			- line 1:    error = TRUE) 
			- line 2:{
			- line 3:    txt <- character()
			- line 4:    if (!is.data.frame(ions)) 
			- line 23:    }
			- line 24:    if (length(txt)) {
			- line 25:        if (error) 
			- line 26:            stop(paste(txt, collapse = "\n"))
			- line 27:        else txt
			- line 28:    }
		+ in .valid_metadata
			- line 1:    error = TRUE) 
			- line 2:{
			- line 3:    txt <- character()
			- line 4:    if (!is.data.frame(metadata)) 
			- line 18:    }
			- line 19:    if (length(txt)) 
			- line 20:        if (error) 
			- line 21:            stop(paste(txt, collapse = "\n"))
			- line 22:        else txt
			- line 23:    else TRUE
	* repetition in `.validCompDb` and `.validIonDb`
		+ in .validCompDb
			- line 9:    comps <- dbGetQuery(x, "select * from ms_compound limit 3")
			- line 10:    res <- .valid_compound(comps, error = FALSE)
			- line 11:    if (is.character(res)) 
			- line 12:        txt <- c(txt, res)
			- line 46:    }
			- line 47:    if (length(txt)) 
			- line 48:        txt
			- line 49:    else TRUE
		+ in .validIonDb
			- line 6:        ions <- dbGetQuery(x, "select * from ms_ion limit 3")
			- line 7:        res <- .valid_ion(ions, error = FALSE)
			- line 8:        if (is.character(res)) 
			- line 9:            txt <- c(txt, res)
			- line 10:    }
			- line 11:    if (length(txt)) 
			- line 12:        txt
			- line 13:    else TRUE
	* repetition in `compound_tbl_lipidblast` and `compound_tbl_sdf`
		+ in compound_tbl_lipidblast
			- line 2:    {
			- line 3:        if (missing(file)) 
			- line 4:            stop("Please provide the file name using 'file'")
			- line 5:        if (!file.exists(file)) 
			- line 6:            stop("Can not fine file ", file)
			- line 8:        if (!missing(collapse)) {
			- line 9:            res$synonyms <- vapply(res$synonyms, paste0, collapse = collapse, 
			- line 10:                FUN.VALUE = "character")
			- line 11:        }
			- line 12:        res
		+ in compound_tbl_sdf
			- line 2:{
			- line 3:    if (missing(file)) 
			- line 4:        stop("Please provide the file name using 'file'")
			- line 5:    if (!file.exists(file)) 
			- line 6:        stop("Can not fine file ", file)
			- line 16:    if (!missing(collapse)) {
			- line 17:        res$synonyms <- vapply(res$synonyms, paste0, collapse = collapse, 
			- line 18:            FUN.VALUE = "character")
			- line 19:    }
			- line 20:    res
	* repetition in `import_mona_sdf` and `msms_spectra_mona`
		+ in import_mona_sdf
			- line 1:    nonStop = TRUE) 
			- line 2:{
			- line 3:    message("Reading SDF file ... ", appendLF = FALSE)
			- line 4:    sdfs <- datablock2ma(datablock(read.SDFset(x, skipErrors = nonStop)))
			- line 11:    message("OK")
			- line 12:    message("Extracting spectrum information ... ", appendLF = FALSE)
			- line 13:    spctra <- .extract_spectra_mona_sdf(sdfs)
			- line 14:    message("OK")
		+ in msms_spectra_mona
			- line 1:    collapsed = TRUE) 
			- line 2:{
			- line 3:    message("Reading SDF file ... ", appendLF = FALSE)
			- line 4:    sdf <- datablock2ma(datablock(read.SDFset(x, skipErrors = TRUE)))
			- line 5:    message("OK")
			- line 6:    message("Extracting ", nrow(sdf), " spectra ... ", appendLF = FALSE)
			- line 7:    spctra <- .extract_spectra_mona_sdf(sdf)
			- line 8:    message("OK")

## Documentation
- [ ] Consider adding runnable examples to the following man pages
      which document exported objects:
      MsBackendCompDb.Rd

**Comment by jorainer** [comment]
Dear @jianhong , thanks for your comprehensive review and the detailed assessment! I've addressed most of your points. Some things I would however like to discuss:

## R code

> [ ] No `paste` in `message`, `stop` etc: 

in all instances the `paste` calls I'm using are to format the error message in a more user-friendly way that AFAIK can not be done omitting these *within-stop* `paste` calls. `stop("Filter(s) ", paste(have_flts[!got_it], collapse = ",")` without `paste` would create e.g. an error message `Error: Filter(s) gene_nametx_namesymbol`, i.e. the elements would be concatenate without any separator while the same error message with `paste` results in a more user-friendly error: `Error: Filter(s) gene_name,tx_name,symbol`, i.e. the fields are now properly separated. It is similar for all other instances for which you requested changes.

I'm fully aware that `paste` should not be used within `message`, `stop` or `warning` but IMHO sometimes it is needed (and justified). I would still change it if you insist but I hope that you accept these exceptions.

> [ ] `message()`, `warning()`, `stop()` instead of `cat`.

I'm generally only using `cat` for `show` methods, and for these I thought it is standard to use `cat`. This is also done in [GenomicFeatures](https://github.com/Bioconductor/GenomicFeatures/blob/master/R/TxDb-class.R#L676-L686) and [S4Vectors](https://github.com/Bioconductor/S4Vectors/blob/master/R/DataFrame-class.R#L960-L989). All the instances that you listed are within `show` methods, thus I would like to keep it that way if OK for you?

> `::` and `:::` is not suggested...

I've removed all `::` except the `Spectra:::.get_column` - the `Spectra` package is loaded once related code is used for the first time (R/CompDb-methods.R line 48). Thus, this code will not break.

> Vectorize: no unnecessary `for` loops present:

For R/query-engine.R line 245 I don't see a way to vectorize the operation as I need to access two different variables within this loop. Also, there will not be any gain of using `lapply` or similar instead.


I've addressed all other raised issues. See [this PR](https://github.com/rformassspectrometry/CompoundDb/pull/94) for all changes/fixes.

I hope you are happy with my updates and am happy to discuss if there is anything unclear.

Thanks again for your time and the comprehensive code review!

cheers, jo

**Comment by jorainer** [comment]
@jianhong , I believe the errors and warnings are due some issues in `BiocCheck` - I do import methods from `ProtGenerics` as well as from `Spectra` in the `NAMESPACE` and both packages are listed in `Imports` in the DESCRIPTION, thus I do not understand where this warning comes from. And the error on Windows seems to be related to some problems of the builder on Windows (@lshep ?)

**Comment by jorainer** [comment]
Also, locally (with BiocCheck version 1.31.24, which is the latest which I can install through `BiocManager`) I don't get any of these warnings.

**Comment by jianhong** [comment]
> Dear @jianhong , thanks for your comprehensive review and the detailed assessment! I've addressed most of your points. Some things I would however like to discuss:
> 
> ## R code
> > [ ] No `paste` in `message`, `stop` etc:
> 
> in all instances the `paste` calls I'm using are to format the error message in a more user-friendly way that AFAIK can not be done omitting these _within-stop_ `paste` calls. `stop("Filter(s) ", paste(have_flts[!got_it], collapse = ",")` without `paste` would create e.g. an error message `Error: Filter(s) gene_nametx_namesymbol`, i.e. the elements would be concatenate without any separator while the same error message with `paste` results in a more user-friendly error: `Error: Filter(s) gene_name,tx_name,symbol`, i.e. the fields are now properly separated. It is similar for all other instances for which you requested changes.
> 
> I'm fully aware that `paste` should not be used within `message`, `stop` or `warning` but IMHO sometimes it is needed (and justified). I would still change it if you insist but I hope that you accept these exceptions.
> 
> > [ ] `message()`, `warning()`, `stop()` instead of `cat`.
> 
> I'm generally only using `cat` for `show` methods, and for these I thought it is standard to use `cat`. This is also done in [GenomicFeatures](https://github.com/Bioconductor/GenomicFeatures/blob/master/R/TxDb-class.R#L676-L686) and [S4Vectors](https://github.com/Bioconductor/S4Vectors/blob/master/R/DataFrame-class.R#L960-L989). All the instances that you listed are within `show` methods, thus I would like to keep it that way if OK for you?
> 
> > `::` and `:::` is not suggested...
> 
> I've removed all `::` except the `Spectra:::.get_column` - the `Spectra` package is loaded once related code is used for the first time (R/CompDb-methods.R line 48). Thus, this code will not break.
> 
> > Vectorize: no unnecessary `for` loops present:
> 
> For R/query-engine.R line 245 I don't see a way to vectorize the operation as I need to access two different variables within this loop. Also, there will not be any gain of using `lapply` or similar instead.
> 
> I've addressed all other raised issues. See [this PR](https://github.com/rformassspectrometry/CompoundDb/pull/94) for all changes/fixes.
> 
> I hope you are happy with my updates and am happy to discuss if there is anything unclear.
> 
> Thanks again for your time and the comprehensive code review!
> 
> cheers, jo

HaHa, jo is my name initial.

About the `paste` in `message` or `stop`, I mean you can move it out of the message, for example:
`a = paste(v, collapse=', '); message('blabla', a)`

For `cat` in `show` or `print` function. I agree with that many people using `cat` to print the message. You can keep current code. FYI: https://stackoverflow.com/questions/36699272/why-is-message-a-better-choice-than-print-in-r-for-writing-a-package/36700294

If `for` loop is the best choice for you, please consider arrange memory before hand. If you have trouble in that, you can leave it. It is not a big issue.

**Comment by jorainer** [comment]
Thanks @jianhong for the quick check. I've addressed now the additional points in commit https://github.com/rformassspectrometry/CompoundDb/commit/4fc03c2327369920d6a2793ccddff1ac141c1189 . I did not find a good way to avoid the `for` loop and left it as-is.

**Comment by jorainer** [comment]
And again, I don't know where the WARNINGS and ERRORS on the single package builder come from - locally and using the github actions on main [repo](https://github.com/rformassspectrometry/CompoundDb/actions/runs/1724134677) (only problem there is that `ChemmineR` is not available for macOS, which I guess is some issue with my GHA definition).

**Comment by jorainer** [comment]
The WARNING seems to be indeed a bug in `BiocCheck`: https://github.com/Bioconductor/Contributions/issues/2443#issuecomment-1022511205

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jorainer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CompoundDb")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CompoundDb

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
