### ISSUE TITLE
AllSorts

### ISSUE THREAD

**Issue by Quarkins** [Bioconductor/Contributions#247]
- Repository: https://github.com/Oshlack/AllSorts

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by Quarkins** [comment]
Hi there,
I just wanted to check how the review is going and if there is anything to do to help it along, but i do not know how long the review process takes, but it has now been 20 days since the package was built without errors.
Cheers,
Anthony

**Comment by LiNk-NY** [comment]
Hi Anthony @Quarkins,
We've been a bit busy here. I will get to your package as soon as possible. 
I apologize for the delay. 

Regards,
Marcel

**Comment by lshep** [comment]
Thank you for your interest in submitting to Bioconductor.  Please see the following comments: 

BUILD REPORT:
- [ ] Please fix the no visible binding for global variables and no visible global function definition for.  There are some suggested imports in the build report and also see `?globalVariables` 
- [ ] Please add unit tests
- [ ] Please add a NEWS file

README: 
 - [ ] Please add an installation from Bioconductor, release version of package for when it gets added
```
source("https://bioconductor.org/biocLite.R")
biocLite("AllSorts")
```

VIGNETTE:
 - [ ] We recommend adding the above installation code also in the vignette

R CODE:
 - [ ] Please remove the commented out hello<- function at the top of the file 
 
Please address these issues and comment back here with what/how the above issues have been addressed.  Thank you.

**Comment by lshep** [comment]
Just wanted to check in and see if there were any questions about the changes suggested.  We are nearing a new release and would love to get your package accepted before then.

**Comment by breons** [comment]
Hi there,

I'm taking over as the maintainer of the project. We will be skipping this release but will certainly make sure that these changes are implemented before the following one.

Thanks.

**Comment by lshep** [comment]
Hello @breons.  I was wondering if there would be any updates to the package soon? There were really minimal changes recommended.

**Comment by lshep** [comment]
Hello @breons,  could you please respond with some sort of update.  If you do not have time to work on the package at this time / if we do not here from you we will close the issue and you can reopen when you have time to make the necessary changes.

**Comment by breons** [comment]
Hi, sorry about that, I must have missed your previous comment.

Unfortunately we do not have the time at present. Close the issue and I will reopen it when we do make the required changes. Thank you for following up.
