### ISSUE TITLE
Macarron

### ISSUE THREAD

**Issue by sagun98** [Bioconductor/Contributions#2483]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/biobakery/MACARRoN

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for your submission.  This package is not ready for review.
```
VignetteBuilder: knitr
Depends:
    R (>= 4.1.0), SummarizedExperiment (>= 1.10.0)
Description: MACARRoN is a workflow for the prioritization of interesting bioactive small molecules from metabolomics experiments. Prioritization integrates strengths of evidences of bioactivity such as covariation with a standard/known metabolite, abundance relative to a known metabolite and association with an environmental or phenotypic indicator of bioactivity. Broadly, the workflow consists of stratified clustering of metabolic spectral features which co-vary in abundance in a condition, transfer of functional annotations, estimation of relative abundance and differential abundance analysis to identify associations between features and phenotype/condition.
VignetteBuilder: knitr
```
Note the two occurrencess of VignetteBuilder.  The package must be developed under R-devel (see the developer guidelines) for this period of the Bioc release cycle.   R CMD check output includes
```
* checking whether the namespace can be loaded with stated dependencies ... WARNING
Error in globalVariables("naresid.omit") : 
  could not find function "globalVariables"
Error: unable to load R code in package ‘Hmisc’
Execution halted

A namespace must be able to be loaded with just the base namespace
loaded: otherwise if the namespace gets loaded by a saved object, the
session will be unable to start.

Probably some imports need to be declared in the NAMESPACE file.
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... WARNING
'::' or ':::' imports not declared from:
  ‘RCurl’ ‘logging’
'library' or 'require' call not declared from: ‘psych’
'library' or 'require' call to ‘SummarizedExperiment’ which was already attached by Depends.
  Please remove these calls from your code.
'library' or 'require' call to ‘psych’ in package code.
  Please use :: or requireNamespace() instead.
  See section 'Suggested packages' in the 'Writing R Extensions' manual.
```
Please attend to these and reply when your repo is updated.  Thanks again!

**Comment by sagun98** [comment]
Hi @vjcitn, 

Thank you for the review. 
The repository has now been updated with the changes and passing R CMD check with R devel version.  

Regards,
Sagun

**Comment by vjcitn** [comment]
Sorry for delay.  This
```
### From the command line ###
1. Install the Bioconductor dependencies: SummarizedExperiment, BiocParallel, DelayedArray, Maaslin2
and ComplexHeatmap.
2. Install the CRAN dependencies:
    * ``$ R -q -e "install.packages(c('optparse','logging','data.table','WGCNA','ff','ffbase',
    'dynamicTreeCut','plyr','psych','ggplot2','circlize','grDevices','xml2','RCurl','RJSONIO'), repos='http://cran.r-project.org')"``

```
should not be in the Bioconductor vignette, as BiocManager will take care of these matters.

I will clear the package for review.

**Comment by LiNk-NY** [comment]
Hi @sagun98 

It looks like you've renamed the package from `MACARRoN` to `Macarron`.
While it works on your side, we would have to do extra work on our side.
The easiest way forward is to create a new issue with the updated package
GitHub location and name.

Best regards,
Marcel

**Comment by sagun98** [comment]
Hi @LiNk-NY , 

Thank you so much for your feedback. 

I created a new issue with the updated github name to the repo however the new issue was auto-closed by a bot (duplicate name error message). 
Please advise. 

https://github.com/Bioconductor/Contributions/issues/2544

**Comment by LiNk-NY** [comment]
Hi @sagun98 
Lori knows the inner workings of the @bioc-issue-bot and can remedy the situation. 
@lshep Should we close this issue and re-open the other? Thanks!

**Comment by lshep** [comment]
some systems are not case sensitive so we initial block duplicate submits regardless of case-- but as @LiNk-NY  has pointed out changing case will cause issues with git.   I have removed the entries on our system and you should be able to resubmit as a new issue now

**Comment by sagun98** [comment]
Hi @LiNk-NY and @lshep,

Thank you so much for letting me resubmit the new issue. 
New issue link: https://github.com/Bioconductor/Contributions/issues/2546  

Regards,
Sagun
