### ISSUE TITLE
rifi

### ISSUE THREAD

**Issue by lyoussar** [Bioconductor/Contributions#2492]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CyanolabFreiburg/rifi

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x]_Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission.  Please read your vignette.  It should not start out with sessionInfo().  Also take steps to avoid 
```
nls2_fit(inp=preprocess_minimal$input_df, probe=preprocess_minimal$probe_df,
         cores=1, decay=seq(.08, 0.11, by=.02), delay=seq(0, 10, by=.1),
         k=seq(0.1, 1, 0.2), intyf = 0.2)
## Warning in (function (formula, data = parent.frame(), start, control =
## nls.control(), : Convergence failure: initial par violates constraints
## Warning in (function (formula, data = parent.frame(), start, control =
## nls.control(), : Convergence failure: initial par violates constraints
## Error in nlsModel(formula, mf, start, wts, upper, scaleOffset = scOff,  : 
##   singular gradient matrix at initial parameter estimates
## Error in nlsModel(formula, mf, start, wts, upper, scaleOffset = scOff,  : 
##   singular gradient matrix at initial parameter estimates
## Warning in (function (formula, data = parent.frame(), start, control =
## nls.control(), : Convergence failure: initial par violates constraints
## Warning in (function (formula, data = parent.frame(), start, control =
## nls.control(), : Convergence failure: initial par violates constraints
## Error in nlsModel(formula, mf, start, wts, upper, scaleOffset = scOff,  : 
##   singular gradient matrix at initial parameter estimates
## Error in nlsModel(formula, mf, start, wts, upper, scaleOffset = scOff,  : 
##   singular gradient matrix at initial parameter estimates
```
filing pages of vignette output.

Is there any use/reuse of Bioconductor software or data structures in this package.  You
are using data.frame to organize data from microarrays, which would be served by
SummarizedExperiment.  If you feel using Bioconductor infrastructure is an impediment to
your work, please provide commentary in this issue.

**Comment by WaljaWanney** [comment]
Hi vjcitn,

we gladly made the changes to the vignette.

We don't use SummarizedExperiments as we do not require the full functionality of the data structure, instead a plane data.frame structure is sufficient. The required structure of the input data.frame is described in the vignette. Also, the output of the clustering done by rifi is not compatible with the structure of SummarizedExperiment.

**Comment by vjcitn** [comment]
Thank you for your note.  "Needs interop" means what it says.  Your vignette has IV. rifi_stats with a long dump of a data.frame that should not be happening in a vignette.  A compact print or show method should be used to present this information.  

Apropos SummarizedExperiment, you may not require the full functionality of the data structure, but Bioconductor users are accustomed to its employment for relevant data structures.  I like your package and I would like to see it enter the Bioconductor ecosystem.  But if you do not want to use the approaches that have guided package design and management for 20 years, you should distribute your package by other means.  If you do not plan to use the customary data structures for multiple sample genomic assays, please close this issue.  If you would like assistance in adopting these structures, we have a mentoring program to which you can apply.

With sincere best wishes.

**Comment by lyoussar** [comment]
Dear Vince,

thank you for your comments. We adjusted the vignette as required. All data.frames are now shortened to an adequate size.
We are adjusting our data to SummarizedExperiment according to your suggestion. The updated package will be pushed as soon as possible.

**Comment by lshep** [comment]
is there any update on the incorporation of SummarizedExperiment and what the expected time frame for the modification is?  The review process will not begin until the changes have been pushed

**Comment by lyoussar** [comment]
We are currently working on that. We will let you know once its finished.
Thank you for your comprehension.

**Comment by vjcitn** [comment]
```
-- re-building ‘vignette.Rmd’ using rmarkdown
Loading required package: rifi
Quitting from lines 211-213 (vignette.Rmd) 
Error: processing vignette 'vignette.Rmd' failed with diagnostics:
unable to find an inherited method for function 'colData' for signature '"data.frame"'
--- failed re-building ‘vignette.Rmd’

SUMMARY: processing the following file failed:
  ‘vignette.Rmd’
```
please use a more descriptive name for your vignette.  and try to beat the error by ensuring that the colData method can be found.  use imports, library etc. as necessary.

**Comment by vjcitn** [comment]
of course colData should not be used with data.frame.

**Comment by lyoussar** [comment]
We are still working on SummarizedExperiment. We are not yet done.

**Comment by vjcitn** [comment]
Just checking in.  Any sense on when revisions will be available?

**Comment by lyoussar** [comment]
We are on test mode. I hope will be finished by next week. Once pushed,  I will let you know.

**Comment by vjcitn** [comment]
Checking in again.

**Comment by lyoussar** [comment]
The update version with SummarizedExperiment as wished is now available.

**Comment by lyoussar** [comment]
Dear reviewer,

The package is only available for Unix systems and is mentioned on "Installation" section on the vignette, line 37. I added a sentence on README as well.

**Comment by lshep** [comment]
Please add a top level file `.BBSoptions` that has the line `UnsupportedPlatforms: win`  this will flag it on our build system as unsupported on windows.

**Comment by lyoussar** [comment]
The file was added.

**Comment by vjcitn** [comment]
I will accept but please change Depends: R (>=4.1) to Depends: R (>= 4.2)

**Comment by vjcitn** [comment]
The BiocCheck errors are false positives at this time.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lyoussar.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("rifi")`. The package 'landing page' will be created at

https://bioconductor.org/packages/rifi

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lyoussar** [comment]
I am not sure if this issue link is still working. I will send this sentence as test ...

**Comment by lyoussar** [comment]
OK, looks like it works!
My issue is related to SSH key. The package is hosted on "CyanolabFreiburg" organization and we can not set a key. Is there anyway to branch my account "lyoussar" and use my authenticity? Thanks!

**Comment by lshep** [comment]
Further questions should be directed to the bioc-devel@r-project.org mailing list. 

You can manage keys on the GitCredentials account.  Please activate your account https://git.bioconductor.org/BiocCredentials/account_activation/  The account was set up with lyoussar as the username/github name to use keys and the listed maintainer email for login jens.georg@biologie.uni-freiburg.de

You'll be able to add as many keys as you like there.

**Comment by lyoussar** [comment]
We are on test mode.  I hope by next week and once the last version is
pushed, I will let u know.

في السبت، 19 مارس 2022 08:16 Vince Carey ***@***.***> كتب:

**Comment by lshep** [comment]
@lyoussar @WaljaWanney  The rifi package is at risk for deprecation as the currently listed maintainer of the package has an invalid email address.  Jens Georg <jens.georg@biologie.uni-freiburg.de>  cannot be found when we try to email.   Please remove that maintainer email and either update with a valid or change the maintainer to a valid recipient
