### ISSUE TITLE
UCSCRepeatMasker

### ISSUE THREAD

**Issue by rcastelo** [Bioconductor/Contributions#2517]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/functionalgenomics/UCSCRepeatMasker

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
I realize this is an exception because of how we do annotation packages

**Comment by lshep** [comment]
@rcastelo   When I am trying to build and check on my local computer I am having trouble with the download concerning the SSL certificate of where you are hosting the data.  

```
> ah[["AH99003"]]
downloading 1 resources
retrieving 1 resource
Error: failed to load resource
  name: AH99003
  title: UCSC RepeatMasker annotations (Sep2021) for Human (hg38)
  reason: 1 resources failed to download
In addition: Warning messages:
1: download failed
  web resource path: 'https://annotationhub.bioconductor.org/fetch/105749'
  local file path: '/home/shepherd/.cache/R/AnnotationHub/2b7e1709f0a1_105749'
  reason: SSL certificate problem: unable to get local issuer certificate 
2: bfcadd() failed; resource removed
  rid: BFC23
  fpath: 'https://annotationhub.bioconductor.org/fetch/105749'
  reason: download failed 
3: download failed
  hub path: 'https://annotationhub.bioconductor.org/fetch/105749'
  cache resource: 'AH99003 : 105749'
  reason: bfcadd() failed; see warnings() 
```

I tested several other resources hosted on the Bioconductor Azure server, direct access from ensembl,  as well as others and don't run into this error so I can only assume it is an issue with https://functionalgenomics.upf.edu/annotationhub/repeatmasker/   please investigate

**Comment by rcastelo** [comment]
You're right, this was working smoothly on my Linux workstation, where the package and the vignette (which includes an actual example of downloading one such resources) build without errors and warning, but I can get also that error from my laptop (macOS 10.15.7) connected to the same network as my workstation. It seems that our IT department renewed the HTTPS certificate of our server on January and since this was working fine before with other AnnotationHub resources, my guess is that something changed after that renewal. I've already contacted them and hope that they can fix it soon. I'll keep you posted on this channel.

**Comment by rcastelo** [comment]
Hi @lshep the problem has been sorted out. Our IT department changed the certificate authority in the last renewal of our server's SSL certificate on January, and while in principle we had updated it, the intermediate CA in our server was still pointing out to the old authority. Now you should be able to build and check in your local computer without any issue, or at least, without that specific issue.

**Comment by lshep** [comment]
Manually Added.  This had to be processed differently because it was an annotation package.  It was added to manifest and on git and should propagate by the end of the week.  If it does not please let us know and we will look into the issue.
