### ISSUE TITLE
sampleClassifierData

### ISSUE THREAD

**Issue by khadija-a** [Bioconductor/Contributions#253]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/khadija-a/sampleClassifierData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by khadija-a** [comment]
AdditionalPackage: https://github.com/khadija-a/sampleClassifier

**Comment by khadija-a** [comment]
AdditionalPackage: https://github.com/khadija-a/sampleClassifier

**Comment by lshep** [comment]
Thank you for your submission.  A few minor comments: 

**sampleClassifierData**
Please fix the warnings that are occurring in the build report.  
1.  Remove the files duplicated in inst/doc
2. Compress the data files: 
R CMD build --resave-data sampleClassifierData
This will create a tarball that has the data files compressed as small as possible. Untar this file and copy the data files in it over the ones in your git working copy, then recommit those, with a version bump.
3. Update the required version of R in the Description to R 3.4 
4.  Please remove the random file external_data_store.txt in the top directory 


**sampleClassifier**
Again Please address the warnings in the build report 
1.  Remove the files duplicated in inst/doc
2. Update the required version of R in the Description to R 3.4 
3. We really encourage packages to have unit test. Please try and add a few. Some helpful hints can be found [here](http://bioconductor.org/developers/unitTesting-guidelines/)

4. R code:  Please review the code specifically in internal.R.  It seems like there is some opportunity to make your code more efficient and robust. See the following [here](http://bioconductor.org/developers/how-to/efficient-code/).  You have a lot of for loops and apply that might be able to be vectorized and there are some instances of 1:length(variable) that could be updated. 

I think these packages are very close to acceptance, please respond back here after you have pushed updates responding what has been changed or any further clarification. 

Thank you 
Lori

**Comment by khadija-a** [comment]
I changed the package as required.

Thanks,
Khadija

**Comment by lshep** [comment]
Please ensure the hook was set up and do a version bump of both packages so new builds can be generated.   The hook instructions can be found [here](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook)

**Comment by khadija-a** [comment]
I made the required changes for both packages. I followed the instructions to set up the hook, but I am getting an error that says: 'the last delivery was not successful. Invalid HTTP Response: 400.'.
Could you please help me with that?
Thanks,
Khadija

**Comment by lshep** [comment]
I'll look into this ERROR in the meantime I will manually force rebuilds of the package.

**Comment by lshep** [comment]
Thank you for making the changes. To get the WARNING fixed you would have to remove the .Rnw file from the inst/doc as well, since it is in the vignette directory already it is not needed in the inst/doc directory. Please move the NEWS file to the top level of your package directory and delete the inst/doc directory in both packages.  Let me know when this changes occurs and I will kick off new builds.  After this is complete I will recommend the package be accepted.

**Comment by khadija-a** [comment]
I made the required changes for both packages.
Thank you very much for your help!

**Comment by lshep** [comment]
I will mark your package as accepted. You will receive svn instructions for uploading the packages to Bioconductor (typically about a week). Please keep the issue open.  Thank you for your submission.
