### ISSUE TITLE
pareg

### ISSUE THREAD

**Issue by kpj** [Bioconductor/Contributions#2537]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cbg-ethz/pareg

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Is this what we are supposed to see?

![pareghist](https://user-images.githubusercontent.com/4624066/155412530-6da8940c-9b9d-44ff-85ab-178761a84bd9.jpg)

Also, consider using BiocStyle to format/render your vignette.  See the developer guidelines

**Comment by kpj** [comment]
@vjcitn: Thanks a lot for the feedback!

> Is this what we are supposed to see?

Actually no, I fixed the issue.

> Consider using BiocStyle to format/render your vignette. See the developer guidelines

I am using `output: BiocStyle::html_document` in the header of my vignette and follow the other advice in section 2 of the [BiocStyle](https://bioconductor.org/packages/devel/bioc/vignettes/BiocStyle/inst/doc/AuthoringRmdVignettes.html) docs.
What else should I do?

**Comment by vjcitn** [comment]
Looking good now.  Do bump the version number with every change to source code.  I'd suggest you just do that now.  Formal review will begin soon

**Comment by jianhong** [comment]
# Package 'pareg' Review
I have trouble in checking the package via devtools:check(document = TRUE) on my computer, I have error "Python module tensorflow_probability was not found.". I am not sure how to figure this out. Once I figured out that, I can come back to review the documentation part.

## The DESCRIPTION file
- [ ] R version should be no less than 4.2

## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 25 import(dplyr)
	* in line 26 import(ggplot2)
	* in line 27 import(ggraph)
	* in line 28 import(nloptr)
	* in line 29 import(progress)
	* in line 30 import(tensorflow)
	* in line 31 import(tidyr)
	* in line 32 import(tidyverse)
    
## General package development
- [ ] If possible, replace S3 object by S4 class for `pareg`, `pareg.family`, `cv.edgenet`, etc.

## R code
- [ ] No `paste` in `message()`, `message`, `stop`. 
	* In file R/main.R:
		+ at line 79 found '      stop(paste('
- [ ] `::` is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development.
	* In file R/netreg.R:
		+ at line 29 found '        initializer(tf$shape(1), tensorflow::tf$float32)'
		+ at line 218 found '  tensorflow::tf$cast(x, tensorflow::tf$float32)'
		+ at line 225 found '  tensorflow::tf$constant(x, tensorflow::tf$float32)'
		+ at line 233 found '  tensorflow::tf$Variable('
		+ at line 234 found '    initializer(shape(m, n), tensorflow::tf$float32),'
		+ at line 244 found '  tensorflow::tf$Variable('
		+ at line 245 found '    initializer(shape(m), tensorflow::tf$float32),'
		+ at line 253 found '  tensorflow::tf$Variable('
		+ at line 254 found '    tf$zeros(shape(), tensorflow::tf$float32),'
		+ at line 361 found '    "logit" = stats::binomial(link = "logit")$linkfun,'
		+ at line 362 found '    "log" = stats::binomial(link = "log")$linkfun,'
		+ at line 363 found '    "probit" = stats::binomial(link = "probit")$linkfun,'
		+ at line 394 found '    "logit" = stats::binomial(link = "logit")$linkfun,'
		+ at line 395 found '    "log" = stats::binomial(link = "log")$linkfun,'
		+ at line 396 found '    "probit" = stats::binomial(link = "probit")$linkfun,'
		+ at line 424 found '    "logit" = stats::binomial(link = "logit")$linkfun,'
		+ at line 425 found '    "log" = stats::binomial(link = "log")$linkfun,'
		+ at line 426 found '    "probit" = stats::binomial(link = "probit")$linkfun,'
		+ at line 511 found '    prob <- tfprobability::tfd_bernoulli(probs = mu.hat[, j])'
		+ at line 539 found '    prob <- tfprobability::tfd_beta('
		+ at line 652 found '    optimizer$apply_gradients(purrr::transpose(list('
		+ at line 782 found '  bobele <- nloptr::bobyqa(par, fn,'
		+ at line 1447 found '  input_shape <- keras::shape(dim(x)[[1]], dim(x)[[2]])'
	* In file R/plotting.R:
		+ at line 66 found '  term_graph <- as_tbl_graph(igraph::graph_from_adjacency_matrix('
	* In file R/term_similarities.R:
		+ at line 67 found '  term_similarities <- proxy::simil('
	* In file R/utils.R:
		+ at line 224 found '  pb <- progress::progress_bar$new(total = size)'
- [ ] Vectorize: no unnecessary `for` loops present.
	* In file R/netreg.R:
		+ at line 510 found '  for (j in seq(ncol(y))) {'
		+ at line 525 found '  for (j in seq(ncol(y))) {'
		+ at line 632 found '  for (step in seq_len(maxit)) {'
		+ at line 714 found '    for (fold in seq(nfolds)) {'
		+ at line 1191 found '  for (i in seq(estimatable.params)) {'
		+ at line 1196 found '  for (i in seq(fixed.params)) {'
		+ at line 1201 found '  for (i in seq(pars)) {'
	* In file R/utils.R:
		+ at line 228 found '  for (i in seq_len(size)) {'
- [ ] Functional programming: code repetition.
	* repetition in `.cv.edgenet` and `.edgenet`
		+ in .cv.edgenet
			- line 14:            call. = FALSE)
			- line 15:    }
			- line 16:    if (!is.null(gx)) {
			- line 17:        gx <- cast_float(matrixLaplacian(gx, FALSE, FALSE)$LaplacianMatrix)
			- line 18:    }
			- line 19:    if (!is.null(gy)) {
			- line 20:        gy <- cast_float(matrixLaplacian(gy, FALSE, FALSE)$LaplacianMatrix)
			- line 21:    }
		+ in .edgenet
			- line 7:    y <- cast_float(y)
			- line 8:    if (!is.null(gx)) {
			- line 9:        gx <- cast_float(matrixLaplacian(gx, FALSE, FALSE)$LaplacianMatrix)
			- line 10:    }
			- line 11:    if (!is.null(gy)) {
			- line 12:        gy <- cast_float(matrixLaplacian(gy, FALSE, FALSE)$LaplacianMatrix)
			- line 13:    }
	* repetition in `bernoulli` and `beta_phi_var`
		+ in bernoulli
			- line 4:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 5:        stop("did not recognize link function", call. = FALSE))
			- line 6:    .as.family("bernoulli", link, NULL, linkinv, bernoulli.loss)
			- line 7:}, function (link = c("logit", "probit", "log")) 
			- line 8:{
			- line 10:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 11:        stop("did not recognize link function", call. = FALSE))
			- line 12:    .as.family("bernoulli", link, NULL, linkinv, bernoulli.loss)
			- line 13:}), where = c("package:pareg", "namespace:pareg"), visible = c(TRUE, 
		+ in beta_phi_var
			- line 8:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 9:        stop("did not recognize link function", call. = FALSE))
			- line 10:    .as.family("beta_phi_var", link, linkfun, linkinv, beta.loss)
			- line 11:}, function (link = c("logit", "probit", "log")) 
			- line 12:{
			- line 18:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 19:        stop("did not recognize link function", call. = FALSE))
			- line 20:    .as.family("beta_phi_var", link, linkfun, linkinv, beta.loss)
			- line 21:}), where = c("package:pareg", "namespace:pareg"), visible = c(TRUE, 
	* repetition in `beta` and `beta_phi_lm`
		+ in beta
			- line 1:    "probit", "log")) 
			- line 2:{
			- line 3:    warn.experimental("beta")
			- line 4:    link <- match.arg(link)
			- line 5:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 6:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 7:        )
			- line 8:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 9:        stop("did not recognize link function", call. = FALSE))
			- line 18:{
			- line 19:    warn.experimental("beta")
			- line 20:    link <- match.arg(link)
			- line 21:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 22:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 23:        )
			- line 24:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 25:        stop("did not recognize link function", call. = FALSE))
		+ in beta_phi_lm
			- line 1:    "probit", "log")) 
			- line 2:{
			- line 3:    warn.experimental("beta_phi_lm")
			- line 4:    link <- match.arg(link)
			- line 5:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 6:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 7:        )
			- line 8:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 9:        stop("did not recognize link function", call. = FALSE))
			- line 13:{
			- line 14:    warn.experimental("beta_phi_lm")
			- line 15:    link <- match.arg(link)
			- line 16:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 17:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 18:        )
			- line 19:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 20:        stop("did not recognize link function", call. = FALSE))
	* repetition in `beta` and `beta_phi_var`
		+ in beta
			- line 1:    "probit", "log")) 
			- line 2:{
			- line 3:    warn.experimental("beta")
			- line 4:    link <- match.arg(link)
			- line 5:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 6:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 7:        )
			- line 8:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 9:        stop("did not recognize link function", call. = FALSE))
			- line 18:{
			- line 19:    warn.experimental("beta")
			- line 20:    link <- match.arg(link)
			- line 21:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 22:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 23:        )
			- line 24:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 25:        stop("did not recognize link function", call. = FALSE))
		+ in beta_phi_var
			- line 1:    "probit", "log")) 
			- line 2:{
			- line 3:    warn.experimental("beta_phi_var")
			- line 4:    link <- match.arg(link)
			- line 5:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 6:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 7:        )
			- line 8:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 9:        stop("did not recognize link function", call. = FALSE))
			- line 12:{
			- line 13:    warn.experimental("beta_phi_var")
			- line 14:    link <- match.arg(link)
			- line 15:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 16:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 17:        )
			- line 18:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 19:        stop("did not recognize link function", call. = FALSE))
	* repetition in `beta_phi_lm` and `beta_phi_var`
		+ in beta_phi_lm
			- line 1:    "probit", "log")) 
			- line 2:{
			- line 3:    warn.experimental("beta_phi_lm")
			- line 4:    link <- match.arg(link)
			- line 5:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 6:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 7:        )
			- line 8:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 9:        stop("did not recognize link function", call. = FALSE))
			- line 10:    .as.family("beta_phi_lm", link, linkfun, linkinv, beta.loss, 
			- line 11:        exp)
			- line 12:}, function (link = c("logit", "probit", "log")) 
			- line 13:{
			- line 14:    warn.experimental("beta_phi_lm")
			- line 15:    link <- match.arg(link)
			- line 16:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 17:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 18:        )
			- line 19:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 20:        stop("did not recognize link function", call. = FALSE))
			- line 21:    .as.family("beta_phi_lm", link, linkfun, linkinv, beta.loss, 
			- line 22:        exp)
		+ in beta_phi_var
			- line 1:    "probit", "log")) 
			- line 2:{
			- line 3:    warn.experimental("beta_phi_var")
			- line 4:    link <- match.arg(link)
			- line 5:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 6:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 7:        )
			- line 8:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 9:        stop("did not recognize link function", call. = FALSE))
			- line 10:    .as.family("beta_phi_var", link, linkfun, linkinv, beta.loss)
			- line 11:}, function (link = c("logit", "probit", "log")) 
			- line 12:{
			- line 13:    warn.experimental("beta_phi_var")
			- line 14:    link <- match.arg(link)
			- line 15:    linkfun <- switch(link, logit = stats::binomial(link = "logit")$linkfun, 
			- line 16:        log = stats::binomial(link = "log")$linkfun, probit = stats::binomial(link = "probit")$linkfun, 
			- line 17:        )
			- line 18:    linkinv <- switch(link, logit = logistic, log = exp, probit = gcdf, 
			- line 19:        stop("did not recognize link function", call. = FALSE))
			- line 20:    .as.family("beta_phi_var", link, linkfun, linkinv, beta.loss)

**Comment by kpj** [comment]
@jianhong: Thanks a lot for your review. I changed most of things you mentioned, it should be mostly fine now.

One question, how can I fix this note:
```
fit: no visible global function definition for %as%
Undefined global functions or variables:
  %as%
```

**Comment by jianhong** [comment]
Did you tried to import it from `reticulate` package?

**Comment by kpj** [comment]
Ah great, that's where its definition was hiding!
Thanks a lot, I'll push an update.

**Comment by kpj** [comment]
In this update, I had to set `LazyData: true` in DESCRIPTION as recommended in the [data documentation](https://r-pkgs.org/data.html).
Otherwise, e.g., building the vignettes crashes with `object 'pathway_similarities' not found`.

**Comment by kpj** [comment]
@jianhong: should be ready for another review now :-)

**Comment by jianhong** [comment]
# Package 'pareg' Review
The package passed check and build. It is in pretty good shape. Did I missed anything from last updates?

## The NAMESPACE file
## R code
- [ ] If possible, replace S3 object by S4 class for `pareg`, `pareg.family`, `cv.edgenet`, etc.
- [ ] `::` is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development.
	* In file R/netreg.R:
		+ at line 1323 found '  }, .progress = TRUE, .options = furrr::furrr_options(seed = 42))'
- [ ] Vectorize: no unnecessary `for` loops present.
	* In file R/netreg.R:
		+ at line 508 found '  for (j in seq(ncol(y))) {'
		+ at line 523 found '  for (j in seq(ncol(y))) {'
		+ at line 631 found '  for (step in seq_len(maxit)) {'
		+ at line 713 found '    for (fold in seq(nfolds)) {'
		+ at line 1357 found '  for (i in seq(estimatable.params)) {'
		+ at line 1362 found '  for (i in seq(fixed.params)) {'
		+ at line 1367 found '  for (i in seq(pars)) {'
	* In file R/utils.R:
		+ at line 258 found '  for (i in seq_len(size)) {'
- [ ] Remove unused code.
	* In file R/netreg.R:
		+ at line 1071 found '    # ret <- cv_edgenet_optim('
		+ at line 1087 found '    # )'
- [ ] Functional programming: code repetition.
	* repetition in `.cv.edgenet_gridsearch` and `.cv.edgenet_optim`
		+ in .cv.edgenet_gridsearch
			- line 15:    if (is.null(gx) & is.null(gy) & !is.na(lambda)) {
			- line 16:        stop("you didn't set graphs and lambda != NA_real_. Got nothing to estimate", 
			- line 17:            call. = FALSE)
			- line 18:    }
			- line 33:        psigx, psigy) {
			- line 34:        if (!is.null(gx)) {
			- line 35:            gx <- cast_float(matrixLaplacian(gx, FALSE, FALSE)$LaplacianMatrix)
			- line 36:        }
			- line 37:        if (!is.null(gy)) {
			- line 38:            gy <- cast_float(matrixLaplacian(gy, FALSE, FALSE)$LaplacianMatrix)
			- line 39:        }
			- line 40:        lambda.tensor <- init_zero_scalar(FALSE)
			- line 41:        psigx.tensor <- init_zero_scalar(FALSE)
			- line 42:        psigy.tensor <- init_zero_scalar(FALSE)
			- line 43:        mod <- model(ncol(x), ncol(y), family)
			- line 44:        loss <- edgenet.loss(lambda.tensor, psigx.tensor, psigy.tensor, 
			- line 45:            gx, gy, family)
			- line 46:        fn <- cross.validate(mod, loss, x, y, lambda.tensor, 
			- line 47:            psigx.tensor, psigy.tensor, nfolds, folds, maxit, 
			- line 56:    psigy_optim <- row_optim$psigy
			- line 57:    reg.params <- list(lambda = lambda, psigx = psigx, psigy = psigy)
			- line 58:    estimatable.params <- Filter(is.na, reg.params)
			- line 59:    fixed.params <- Filter(is.finite, reg.params)
		+ in .cv.edgenet_optim
			- line 3:{
			- line 4:    reg.params <- list(lambda = lambda, psigx = psigx, psigy = psigy)
			- line 5:    estimatable.params <- Filter(is.na, reg.params)
			- line 6:    fixed.params <- Filter(is.finite, reg.params)
			- line 8:    if (is.null(gx) & is.null(gy) & !is.na(lambda)) {
			- line 9:        stop("you didn't set graphs and lambda != NA_real_.\n             got nothing to estimate", 
			- line 10:            call. = FALSE)
			- line 11:    }
			- line 14:            call. = FALSE)
			- line 15:    }
			- line 16:    if (!is.null(gx)) {
			- line 17:        gx <- cast_float(matrixLaplacian(gx, FALSE, FALSE)$LaplacianMatrix)
			- line 18:    }
			- line 19:    if (!is.null(gy)) {
			- line 20:        gy <- cast_float(matrixLaplacian(gy, FALSE, FALSE)$LaplacianMatrix)
			- line 21:    }
			- line 22:    lambda.tensor <- init_zero_scalar(FALSE)
			- line 23:    psigx.tensor <- init_zero_scalar(FALSE)
			- line 24:    psigy.tensor <- init_zero_scalar(FALSE)
			- line 25:    mod <- model(ncol(x), ncol(y), family)
			- line 26:    loss <- edgenet.loss(lambda.tensor, psigx.tensor, psigy.tensor, 
			- line 27:        gx, gy, family)
			- line 28:    fn <- cross.validate(mod, loss, x, y, lambda.tensor, psigx.tensor, 
			- line 29:        psigy.tensor, nfolds, folds, maxit, thresh, learning.rate)
	* repetition in `.cv.edgenet_gridsearch` and `.edgenet` and `.edgenet`
		+ in .cv.edgenet_gridsearch
			- line 33:        psigx, psigy) {
			- line 34:        if (!is.null(gx)) {
			- line 35:            gx <- cast_float(matrixLaplacian(gx, FALSE, FALSE)$LaplacianMatrix)
			- line 36:        }
			- line 37:        if (!is.null(gy)) {
			- line 38:            gy <- cast_float(matrixLaplacian(gy, FALSE, FALSE)$LaplacianMatrix)
			- line 39:        }
		+ in .edgenet
			- line 7:    y <- cast_float(y)
			- line 8:    if (!is.null(gx)) {
			- line 9:        gx <- cast_float(matrixLaplacian(gx, FALSE, FALSE)$LaplacianMatrix)
			- line 10:    }
			- line 11:    if (!is.null(gy)) {
			- line 12:        gy <- cast_float(matrixLaplacian(gy, FALSE, FALSE)$LaplacianMatrix)
			- line 13:    }
		+ in .edgenet
			- line 7:    y <- cast_float(y)
			- line 8:    if (!is.null(gx)) {
			- line 9:        gx <- cast_float(matrixLaplacian(gx, FALSE, FALSE)$LaplacianMatrix)
			- line 10:    }
			- line 11:    if (!is.null(gy)) {
			- line 12:        gy <- cast_float(matrixLaplacian(gy, FALSE, FALSE)$LaplacianMatrix)
			- line 13:    }

**Comment by kpj** [comment]
@jianhong: not sure why no new status report is posted, but I addressed everything except for the S3 objects, for loops and code repetitions because I think they are sensible where they occur.
Let me know what you think :-)

**Comment by jianhong** [comment]
@kpj For S3 objects, I agree with you. 
For loops, for example line 508 in `netreg`, will it be possible to split it into two steps like:
```
prob <- apply(mu.hat, 2, FUN)
obj <- apply(y, 2, FUN)
obj <- sum(obj)
```

For repetitions, it will be easy for your maintenance. If you prefer, there is no issue to keep it as it.

Jianhong.

**Comment by lshep** [comment]
The build report posting was a Bioconductor builder issue. We hope to have it remedied and I will kick a manual build of your package shortly.  The build report should post shortly

**Comment by lshep** [comment]
For What its worth: There are errors on the SPB windows machine in the tests 
```
* checking tests ...
  Running 'testthat.R'
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  obj@result$GeneRatio not equal to c("8/10", "2/15").
  2/2 mismatches
  x[1]: "2/15"
  y[1]: "8/10"

  x[2]: "8/10"
  y[2]: "2/15"
  ── Failure (test-utils.R:122:3): enrichplot integration works ──────────────────
  obj@termsim not equal to `termsim`.
  Attributes: < Component "dimnames": Component 1: 2 string mismatches >
  Attributes: < Component "dimnames": Component 2: 2 string mismatches >

  [ FAIL 3 | WARN 0 | SKIP 0 | PASS 14 ]
  Error: Test failures
  Execution halted
```

**Comment by kpj** [comment]
@jianhong Thanks a lot for your feedback.

> For loops, for example line 508 in netreg, will it be possible to split it into two steps like:

In this case I don't think you can split the for loop into two separate apply statements, because the call to `tf$reduce_sum` uses the output of the call to `tfd_bernoulli`. In addition, joining these two parts into a single function and using apply/map would first allocate a vector filled with doubles which is then summed up in the final step. With the for-loop no additional vector is created and a single double is added to. This might be a job for something like `Reduce` but I'd also be fine with leaving it as is. What do you think?

> For repetitions, it will be easy for your maintenance. If you prefer, there is no issue to keep it as it.

I agree that fewer repetitions would lead to easier maintenance. In this case however (mainly because refactoring the code would involve creating an extra validation function which would have to take many parameters), I'd be fine with leaving the code as is.

---

@lshep

> I will kick a manual build of your package shortly

Thanks a lot!

> There are errors on the SPB windows machine in the tests

Do you know why the build report says "Congratulations! The package built without errors or warnings
on all platforms."? When I check the logs, the R CMD CHECK seems to be cut off after starting the tests.

**Comment by lshep** [comment]
We are having trouble with our new windows builder.  I'm working on fixes now to the windows builder

**Comment by kpj** [comment]
@lshep Just wondering whether there are currently also troubles with other parts of the build system. I just pushed a new version to `git@git.bioconductor.org:packages/pareg` but no new comment from @bioc-issue-bot pops up,

**Comment by lshep** [comment]
No other parts are building fine.  I checked your push -- we only rebuild with a valid version bump and the latest did not include a version bump in the description

**Comment by kpj** [comment]
Very interesting, I actually bumped the version (https://github.com/cbg-ethz/pareg/commit/c14122df03af5fa97e3d3a2cef924f21db6ffdcb) in `origin/bioc` after merging in my changes from `origin/master` (https://github.com/cbg-ethz/pareg/commit/496e2688710f8fca20b5885a3134c3575db2db23):
```
commit 41119472fcaf5c825eaf4d04e68b98cc09809c85 (HEAD -> bioc, upstream/master, origin/bioc)
Author: kpj <kim.philipp.jablonski@gmail.com>
Date:   Tue Apr 5 14:45:08 2022 +0200

    Bump version

commit f11699df7d0560fb4dfafca5fa5143467a6ef697
Merge: c14122d 2cf9004
Author: kpj <kim.philipp.jablonski@gmail.com>
Date:   Tue Apr 5 14:22:20 2022 +0200

    Merge branch 'master' of git.bioconductor.org:packages/pareg into bioc

commit c14122df03af5fa97e3d3a2cef924f21db6ffdcb
Author: kpj <kim.philipp.jablonski@gmail.com>
Date:   Tue Apr 5 14:21:57 2022 +0200

    Bump version

commit 496e2688710f8fca20b5885a3134c3575db2db23
Merge: 87d497d 3987005
Author: kpj <kim.philipp.jablonski@gmail.com>
Date:   Tue Apr 5 14:21:27 2022 +0200

    Merge branch 'master' into bioc
```

Maybe the empty merge from `upstream/master` (https://github.com/cbg-ethz/pareg/commit/f11699df7d0560fb4dfafca5fa5143467a6ef697) lead to some confusion? Anyway, it seems to work now after bumping the version again (https://github.com/cbg-ethz/pareg/commit/41119472fcaf5c825eaf4d04e68b98cc09809c85).

**Comment by jianhong** [comment]
# Package 'pareg' Review
The package passed check and build. It is almost there. 

## The DESCRIPTION file
- [ ] 'LazyData:' in the 'DESCRIPTION' should be set to false or removed

## R code
- [ ] no direct slot access with `@` or `slot()` - accessors implemented and used.
	* In file R/utils.R:
		+ at line 210 found '    cls@method <- "pareg"'
		+ at line 212 found '    cls@termsim <- x$term_network'
		+ at line 213 found '    cls@termsim[lower.tri(cls@termsim, diag = TRUE)] <- NA'

## R development
- [ ] update NEWS.md to current version.

**Comment by kpj** [comment]
@jianhong: I fixed the DESCRIPTION and NEWS.md issues.

The direct slot access I probably cannot fix, because they are for an object from another package. And in that package they also use this way of accessing the slots (e.g. https://github.com/YuLab-SMU/enrichplot/blob/e48a727f956174ddce4b5e66722e8ad1aa427797/R/emapplot_utilities.R#L50).
What do you think?

**Comment by jianhong** [comment]
> @jianhong: I fixed the DESCRIPTION and NEWS.md issues.
> 
> The direct slot access I probably cannot fix, because they are for an object from another package. And in that package they also use this way of accessing the slots (e.g. https://github.com/YuLab-SMU/enrichplot/blob/e48a727f956174ddce4b5e66722e8ad1aa427797/R/emapplot_utilities.R#L50). What do you think?

It is a suggestion. If possible, please ask the upstream package to add the api for those slots. Thank you.

**Comment by kpj** [comment]
In that case I'd rather leave it as is and not ask for changes in the upstream package, if that's okay with you.

**Comment by jianhong** [comment]
@kpj Ask will not hurt. It is OK for me to leave it as it. But it will be a concern when they changed the slot names.

And the updated NEWS.md file does not show any readable information for the updates. I am little concern the long-term maintenance of your package.

Jianhong.

**Comment by kpj** [comment]
I did not add any additional news items to NEWS.md because the package has not been released on Bioconductor so far.
For future changes after the initial Bioconductor release I'd create news items.

**Comment by jianhong** [comment]
@kpj 
Please read https://contributions.bioconductor.org/news.html for details about the NEWS.md file. Hope it will help.

Jianhong.

**Comment by lshep** [comment]
@jianhong  I think its fine to leave pre-acceptance updates out of the news.  it becomes especially important after acceptance so that changes can be included in release announcements

**Comment by jianhong** [comment]
@lshep 
OK. Just want to emphasize the importance of the documentation. I will put the package as accepted now.

**Comment by kpj** [comment]
Thank you so much for reviewing the package! Looking forward to seeing it on Bioconductor :-)

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kpj.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pareg")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pareg

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
