### ISSUE TITLE
nnSVG

### ISSUE THREAD

**Issue by lmweber** [Bioconductor/Contributions#2543]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lmweber/nnSVG

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lmweber** [comment]
I just pushed version 0.99.1 to GitHub, which removes a WARNING and NOTE from `BiocCheck()`.

**Comment by jianhong** [comment]
# Package 'nnSVG' Review
The package passed check and build. However there are several things need to be fixed.

## The DESCRIPTION file
- [ ] `Depends` field is not found in DESCRIPTION.
- [ ] R version is not clear in DESCRIPTION.

## R code
- [ ] `vapply` instead of `sapply`.
	* In file R/nnSVG.R:
		+ at line 213 found '  loglik_lm <- sapply(seq_len(nrow(spe)), function(i) {'
- [ ] NOTE: Avoid using '=' for assignment and use '<-'
instead
Found in files:
  R/nnSVG.R (line 229, column 11)
- [ ] Consider to expose BPPARAM at line 168 as a parameter. 
  
## Documentation
- [ ] Vignette should have an *Installation* section.
	* rmd file vignettes/nnSVG.Rmd
- [ ] Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/nnSVG.Rmd
- [ ] NOTE: Avoid 'suppressWarnings'/'*Messages' if possible
(found 1 times)
  suppressWarnings() in R/nnSVG.R (line 154, column 5)

**Comment by lmweber** [comment]
Thank you for the review! I have made the following updates:

---

> Depends field is not found in DESCRIPTION.

Added, done.

>  R version is not clear in DESCRIPTION.

Added, done.

> vapply instead of sapply.
> In file R/nnSVG.R:
> at line 213 found ' loglik_lm <- sapply(seq_len(nrow(spe)), function(i) {'

I have replaced the `sapply` with `vapply` with type `numeric(1)`, thanks.

> NOTE: Avoid using '=' for assignment and use '<-'
> instead
> Found in files:
> R/nnSVG.R (line 229, column 11)

This was a typo and is now fixed, thanks.

> Consider to expose BPPARAM at line 168 as a parameter.

Done. I kept the earlier `n_threads` argument for users who are not familiar with how `BiocParallel` works, and added `BPPARAM` directly for advanced users.

> Vignette should have an Installation section.
> rmd file vignettes/nnSVG.Rmd
> Please include Bioconductor installation instructions using BiocManager.
> rmd file vignettes/nnSVG.Rmd

Done, added in vignette. The installation info is also on the GitHub readme for users who find the package there.

> NOTE: Avoid 'suppressWarnings'/'*Messages' if possible
> (found 1 times)
> suppressWarnings() in R/nnSVG.R (line 154, column 5)

I have now removed the `suppressWarnings()`.

**Comment by lmweber** [comment]
The new WARNING in the build report has noted the installation code in the vignette. Is there a recommended way to remove this? I included `eval=FALSE` so it shouldn't be evaluated.

```
* Checking vignette directory...
    * WARNING: BiocInstaller code found in vignette(s)
      Found in file(s):
        nnSVG.Rmd (line 42)
```

**Comment by lmweber** [comment]
I tried commenting out these lines of code in the vignette code block, but it still returns the WARNING:

```
$warning
[1] " BiocInstaller code found in vignette(s)"
```

**Comment by lmweber** [comment]
Note that I still receive the WARNING even when I replace the installation section with a completely text-based section (without any `BiocManager` code), as follows.

I think `BiocCheck()` is doing a search for any text about installation and returning a WARNING.

```
# Installation

The `nnSVG` package can be installed from Bioconductor.

Installation instructions for the stable release version are shown on the [Bioconductor](https://bioconductor.org/packages/nnSVG) page.

The latest development version can also be installed from the [devel](http://bioconductor.org/developers/how-to/useDevel/) version of Bioconductor or from [GitHub](https://github.com/lmweber/nnSVG).
```

**Comment by lmweber** [comment]
I managed to remove the warning by:

- removing `BiocManager` code
- also removing link to the [Bioc-devel](https://www.bioconductor.org/developers/how-to/useDevel/) page (not sure why this was also causing the warning though)

**Comment by lmweber** [comment]
Not sure why it is taking longer to build now than the earlier version. Locally it builds in a few minutes.

**Comment by lmweber** [comment]
I reduced the size of some of the examples, so this has brought it back under the time limit for the builder. Thank you!

**Comment by lmweber** [comment]
I updated R version dependency to 4.2 for now, following discussions about this on Bioc Slack (in channels `#bioc-builds` and `#package-submission`).

I think this requirement is too restrictive, since it makes it difficult for users to install the package from GitHub (in the time between now and the Bioc-release date) if they are using the release version of R instead of R-devel.

I will think about how to manage this again later, e.g. adding a temporary branch on GitHub that can still be installed in R-release (without the `Depends: R (>= 4.2)` line in `DESCRIPTION`).

**Comment by jianhong** [comment]
@lmweber I agree. You can create a branch for submitting to git@bioconductor and keep you default branch with lower R version for users who need it now.

**Comment by jianhong** [comment]
> I managed to remove the warning by:
> 
> * removing `BiocManager` code
> * also removing link to the [Bioc-devel](https://www.bioconductor.org/developers/how-to/useDevel/) page (not sure why this was also causing the warning though)

Did you try to remove the line about install.packages('BiocManager') only?

**Comment by jianhong** [comment]
## Documentation
- [ ] Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/nnSVG.Rmd

This is the last thing you need to address.

**Comment by jianhong** [comment]
Interesting! looks like the line 39 triggered the warning. See here:

Checking vignette directory...
    * WARNING: BiocInstaller code found in vignette(s)
      Found in file(s):
        nnSVG.Rmd (line 39)

**Comment by lshep** [comment]
This seems like a False positive then -- could either of you open an issue on BiocCheck to repo this bug https://github.com/Bioconductor/BiocCheck/issues

**Comment by lmweber** [comment]
Thanks. Yes, the second version I just pushed above had `BiocManager` commented out inside the code block, so I think this must be a false positive with `BiocCheck`.

I'll open an issue, thanks!

**Comment by lmweber** [comment]
Seems I have a new error now, unrelated to the `BiocManager` issues above, due to dependencies in the vignette.

I'm not sure what is causing this, and I wasn't seeing it previously (the version I pushed just now is identical to the one from a few days ago). I'll do some more testing or wait another day or two and try again.

**Comment by lshep** [comment]
I am in the process of updating the builders.  It could be intermittently related to that.

**Comment by lmweber** [comment]
Ok, no worries. I'll wait a while and then push another version bump.

**Comment by lmweber** [comment]
Ok great, looks like it was just a temporary issue with the builders and it has passed with a new version bump now.

**Comment by lmweber** [comment]
I'm still getting the same warning when I put back the `BiocManager` code in the vignette. I have tried another alternative formatting of the code block now.

```
* Checking vignette directory...
    * WARNING: BiocInstaller code found in vignette(s)
      Found in file(s):
        nnSVG.Rmd (line 38)
```

**Comment by lmweber** [comment]
I'm getting several unrelated errors with the builders now, which I was not seeing previously, e.g. the following. These also seem to be different each run.

I'll try some more version bumps later on in case there are some temporary issues with the builders right now.

The WARNING from the `BiocManager` issue seems to be resolved now though with my latest version of the installation code block in the vignette.

```
Error: package or namespace load failed for 'nnSVG' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'magrittr'
```

```
Error: processing vignette 'nnSVG.Rmd' failed with diagnostics:
there is no package called 'scran'
```

and from the code block running `sessionInfo()`:

```
Error: processing vignette 'nnSVG.Rmd' failed with diagnostics:
subscript out of bounds
```

**Comment by jianhong** [comment]
> I'm getting several unrelated errors with the builders now, which I was not seeing previously, e.g. the following. These also seem to be different each run.
> 
> I'll try some more version bumps later on in case there are some temporary issues with the builders right now.
> 
> The WARNING from the `BiocManager` issue seems to be resolved now though with my latest version of the installation code block in the vignette.
> 
> ```
> Error: package or namespace load failed for 'nnSVG' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
>  there is no package called 'magrittr'
> ```
> 
> ```
> Error: processing vignette 'nnSVG.Rmd' failed with diagnostics:
> there is no package called 'scran'
> ```
> 
> and from the code block running `sessionInfo()`:
> 
> ```
> Error: processing vignette 'nnSVG.Rmd' failed with diagnostics:
> subscript out of bounds
> ```

take it easy. I will go through the package this weekend to see if it is OK to be accepted. No worry about current building errors. And Please make sure to bump up your version at this Friday.

Jianhong.

**Comment by lmweber** [comment]
No worries, that sounds good, thank you! I think there was a temporary glitch with the builders this afternoon.

**Comment by lmweber** [comment]
Great, thanks a lot for your help!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lmweber.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("nnSVG")`. The package 'landing page' will be created at

https://bioconductor.org/packages/nnSVG

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
