### ISSUE TITLE
(inactive) GenomicInteractionHub

### ISSUE THREAD

**Issue by jianhong** [Bioconductor/Contributions#2561]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jianhong/GenomicInteractionHub

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
need to fix line 5 of vignette

**Comment by jianhong** [comment]
@vjcitn Thank you for point it out.

I fixed this typo. But I did not see update here. Do you know the reason?

Jianhong.

**Comment by lshep** [comment]
pushes that trigger builds happen after the package is assigned a reviewer and is review in progress. @vjcitn were pre-review changes/comments

**Comment by LiNk-NY** [comment]
Hi JianHong, @jianhong 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# GenomicInteractionHub #2561

Good package. Nicely put together. My only reservation is the "Hub" naming.
It can cause a bit of confusion as to the purpose of the package based
on the name alone. Others may have a different opinion.

## DESCRIPTION

* Looks good.

## NAMESPACE

* Looks good.
* Consider spelling out some function names so that they are more descriptive
(e.g., `enrichAna`, `annoHubs`).

## vignettes

* You can chunk options such as:
````
```{r,include=TRUE,results="hide",message=FALSE,warning=FALSE}

````
to avoid startup message outputs from loading packages.

* The `annoHub` name is a but confusing given that we have the `AnnotationHub`
package. Consider using a different name, e.g., `hubAnnotate`.

## R

* Make the return conditions (`length(all_gene_id)<minGeneNum`) clear in the
`enrichAna` documentation when `NULL` is returned.
* Minor: Use `is.numeric` instead of `is(x, "numeric")`.
Consider validating the `seq` argument against `seqnames(g)` in
`createRandomHubs`.

Coverage looks great!

```r
covr::package_coverage()
GenomicInteractionHub Coverage: 97.85%
R/enrichAna.R: 95.56%
R/annoHubs.R: 100.00%
R/createRandomHubs.R: 100.00%
R/detectHubs.R: 100.00%
```

## Other

* Optional: Consider beefing up the README.md a bit more to make use of the
GitHub 'landing page' so to speak.

**Comment by jianhong** [comment]
Hi @LiNk-NY Marcel

Thank you for your comments.

> ## NAMESPACE
> * Consider spelling out some function names so that they are more descriptive
>   (e.g., `enrichAna`, `annoHubs`).

I changed the function names to `enrichmentAnalysis` and `annotateNodes`.

> ## vignettes
> * You can chunk options such as:
> 
> ```
> ```{r,include=TRUE,results="hide",message=FALSE,warning=FALSE}
> ```
> 
> to avoid startup message outputs from loading packages.

I add message=FALSE to avoid startup message.

> * The `annoHub` name is a but confusing given that we have the `AnnotationHub`
>   package. Consider using a different name, e.g., `hubAnnotate`.

I renamed the package to GenomicInteractionNodes and submitted as [a new package](https://github.com/Bioconductor/Contributions/issues/2633#issue-1200683997) just in case there is any folder name issues.

> ## R
> * Make the return conditions (`length(all_gene_id)<minGeneNum`) clear in the
>   `enrichAna` documentation when `NULL` is returned.

The documentation is updated for the `NULL` returns.

> * Minor: Use `is.numeric` instead of `is(x, "numeric")`.
Used `is.numeric` to replace `is(x, "numeric")` in `annotateNodes`

>   Consider validating the `seq` argument against `seqnames(g)` in
>   `createRandomHubs`.
Check `seq` argument against TxDb object for `createRandomNodes`

> ## Other
> * Optional: Consider beefing up the README.md a bit more to make use of the
>   GitHub 'landing page' so to speak.
Add documentation for README.md

Jianhong.
