### ISSUE TITLE
ggtranscript

### ISSUE THREAD

**Issue by dzhang32** [Bioconductor/Contributions#2569]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dzhang32/ggtranscript

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by dzhang32** [comment]
Hi, 

I've updated my email in order to address the current build report ERRORS on the GitHub repo. 

However, I'm having trouble pushing the commits to Bioconductor side: 

```
…/ggtranscript on  main via 📐 v4.1.2 
❯ git remote add upstream git@git.bioconductor.org:packages/ggtranscript.git
(base) 
…/ggtranscript on  main via 📐 v4.1.2 
❯ git remote -v                                                             
origin	git@github.com:dzhang32/ggtranscript.git (fetch)
origin	git@github.com:dzhang32/ggtranscript.git (push)
upstream	git@git.bioconductor.org:packages/ggtranscript.git (fetch)
upstream	git@git.bioconductor.org:packages/ggtranscript.git (push)
(base) 
…/ggtranscript on  main via 📐 v4.1.2 
❯ git fetch --all
Fetching origin
Fetching upstream
From git.bioconductor.org:packages/ggtranscript
 * [new branch]      master     -> upstream/master
(base) 
…/ggtranscript on  main via 📐 v4.1.2 took 2s 
❯  git merge upstream/master
Already up to date.
(base) 
…/ggtranscript on  main via 📐 v4.1.2 
❯ git merge origin/main
Already up to date.
(base) 
…/ggtranscript on  main via 📐 v4.1.2 
❯ git push upstream main  
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (6/6), 578 bytes | 578.00 KiB/s, done.
Total 6 (delta 4), reused 4 (delta 2), pack-reused 0
remote: FATAL: W refs/heads/main packages/ggtranscript dzhang32 DENIED by fallthru
remote: error: hook declined to update refs/heads/main
To git.bioconductor.org:packages/ggtranscript.git
 ! [remote rejected] main -> main (hook declined)
error: failed to push some refs to 'git.bioconductor.org:packages/ggtranscript.git'
(base) 
…/ggtranscript on  main via 📐 v4.1.2 
❯ git push origin main  
Everything up-to-date
(base) 
```

I have not come across this before. Googling the error `remote: error: hook declined to update refs/heads/main`, it seems this might be related to a hook on the remote end. 

I was wondering if you could advise on how to resolve this, or let me know if I've done something incorrectly. 

Thanks a lot in advance! 

David

**Comment by dzhang32** [comment]
Hi @ococrook, 

Please ignore my above comment, the problem with pushing to the Bioconductor repo was resolved. 

The remaining WARNING from BiocCheck is related to the `geom_*` functions missing `@return`/`\value` sections in their  `roxygen2` documentation. The reason for this is as I wasn't sure it made sense to document a `@return` value for geom's; they should only be used in combination with a `ggplot()` call and what they return (a `LayerInstance` class object) is not designed to be directly handled by users. I felt adding this to the documentation might confuse rather than aid users. For the original `ggplot2` package and other `ggplot2` extensions I've looked through, their `geom_*` functions also omit the `@return` documentation. In this case, I was wondering whether you would require this WARNING to be addressed before ggtranscript can be reviewed?

Thanks a lot in advance for taking the time to review ggtranscript! 

David

**Comment by ococrook** [comment]
Hi @dzhang32 

I'll ignore the warning for the moment and continue with reviewing the package. One option is to add a `@return`, but add documentation that the users are not meant to manipulate these `geom_*` functions in isolation. I think this would be better for developers and would help if the package ended up having a large number of contributors. 

Looking forward to reviewing the package, will get around to this shortly

best, 
Olly

**Comment by dzhang32** [comment]
Thanks for getting back to me @ococrook. 

I did think about that option for the same reasons you suggest and fell on the fence. With your advice, I am more convinced of the benefit and in addition, it'd be nice to have no WARNINGS. I will implement these `@return` statements alongside making the changes in response to your review. 

Look forward to hearing from you.

**Comment by dzhang32** [comment]
Hi @ococrook, 

Just wanted to check in regarding the timeline for hearing back about `ggtranscript`? Slightly wary that the release schedule is creeping up and hoping to take some time to carefully address your reviews. Thanks!

**Comment by ococrook** [comment]
Hi @dzhang32 

Currently away from my computer but I will finish tomorrow. From what I've started there shouldn't be too much to change before the deadline

**Comment by ococrook** [comment]
This looks pretty good to me, thank you for the attention to detail and easy to follow vignette. `ggtranscript` will make a great addition to the Biocondutor family. Could you make the following changes to the package or let me know if there's a good reason not to make the change.

Once you've made the changes make sure to run `R CMD Check` and `BiocCheck` again. Remember to bump the package version number in both the `Description` and the `NEWS.md` file.

# General

- [ ] If possible please remove build warnings

# Description

- [ ] Could you update R version to 4.2
- [ ] lazydata to false

# News file

- [ ] Version doesn’t match package version, please update

# R code and interop

- [ ] importing `magrittr` for pipe is no longer need, you can switch to the native pipe (optional)

- [ ] I appreciate the data.frame(x) usage to be consistent with ggplot and other gg* packages. If possible, could you add functions that take relevant bioconductor S4 objects, this could streamline the analysis for some users without the need to be experts in ggplot. I believe the `GenomicRanges` infrastructure is relevant, as you mention in the vignette.

- [ ] You have some for loops that look like they could be replaced with vapply’s (remember to avoid sapply if possible)

- [ ] `geom_range` is also a geom form the `ggtree` package, which might confuse `geom_genomic_range` maybe more expressive? 

# Vignette

Looks good!

- [ ] Please add installation instructions via Bioconductor. Remember this should not be evaluated

- [ ] You have unnecessary substructure start first order headings with # and then subheadings with ##/

- [ ] The title is called "Getting started", I would think that ggtranscript getting started or Introduction to ggtranscript would make better titles

# Readme.md

- [ ] Add Bioconductor installation instructions. 

- [ ] Add note to say that github install from devtools is the version under development and maybe unstable

# Unit tests

Looks good!

# Data-raw

- [ ] I think these files better belong in an inst/scripts or inst/extdata directories

**Comment by dzhang32** [comment]
Hi @ococrook, 

Thanks a lot for your review!

>  Could you update R version to 4.2

My understanding is that the update to R version 4.2 is a mandatory requirement from Bioconductor as each release cycle tracks the newest R version - I wanted to check if this correct? My hesitation is as I'm aware of several users of `ggtranscript` having infrastructure restrictions (on a remote server) which would prevent them from updating their R version without a lot of trouble.

**Comment by ococrook** [comment]
Yes, that's the case

If you're in regular contact with these users and its not too much hassle could you create a branch which is 1 version behind for them and direct them to it from the readme? Hopefully, you can delete this branch when they can move to R4.2 and everything syncs up?

**Comment by dzhang32** [comment]
Thanks for the quick clarification and suggestion! Yes, I think the separate branch would solve the issue. 

I am going to get in touch with a few of these users and get their feedback (some of them are co-authors/contributors for the package) to check what they think - will be in touch soon.

**Comment by ococrook** [comment]
Awesome, let me know if that works

**Comment by dzhang32** [comment]
Hi @ococrook, 

After discussing with my colleagues, although we do understand the rationale behind these comments from the perspective of the Bioconductor ecosystem, we've decided to withdraw the `ggtranscript` Bioconductor submission. The main reasons for this are:

- We think upping the requirement R 4.2 will cause some friction (even with the separate branch solve) for some users of `ggtranscript`, especially considering some heavy users that were involved in the development of the package. 
- I've recently moved on to a new post and have much less time to address these reviews. In particular, the comment regarding allowing `ggtranscript` functions to interoperate effectively with Bioconductor objects (e.g. `GenomicRanges`) I suspect will take some time. 

We do really appreciate the time you've taken to review `ggtranscript`, thanks again. 

David

**Comment by ococrook** [comment]
Hi @dzhang32 

No problem and thanks for letting me on. If you're moving onto a new position then it may also be hard to commit to maintaining the package. If anyone decides to take over the package and wants to submit to bioconductor then they can reference this issue and we can go from there. 

Good luck with your new position and thanks for submitting.

Olly
