### ISSUE TITLE
(inactive) unable to deploy shiny app to shinyapp.io (Bioconductor source)

### ISSUE THREAD

**Issue by smes7eves** [Bioconductor/Contributions#2580]
Hi, 
I have the same problem as in [this post](https://community.rstudio.com/t/unable-to-deploy-shiny-app-to-shinyapp-io-problem-maybe-accessing-packages/101930) that had no answers.
Basically, when I try to deploy my InteractiveComplexHeatmap, the action is interrupted

> Error: Unhandled Exception: Child Task 1121686583 failed: Error parsing manifest: Unable to determine package source for Bioconductor package BiocGenerics: Repository must be specified
Execution halted

Any suggestions would be appreciated, thanks!

**Comment by vjcitn** [comment]
restart Rstudio ... options(repos=BiocManager::repositories()) ... ensure that no package in use has been installed from source ... all must come from Bioconductor or CRAN.  then publish event should not generate this error.
