### ISSUE TITLE
hicrep

### ISSUE THREAD

**Issue by MonkeyLB** [Bioconductor/Contributions#259]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MonkeyLB/hicrep

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@hpages will review this package but it is very surprising that it does not use or provide interoperability with any of the Bioconductor infrastructure for working with [genomic ranges](https://bioconductor.org/packages/GenomicRanges) and related infrastructure  infrastructure specifically designed to work with interaction data [HiC biocViews](http://bioconductor.org/packages/3.5/BiocViews.html#___HiC), e.g., [InteractionSet](https://bioconductor.org/packages/InteractionSet)

**Comment by MonkeyLB** [comment]
I follow the instruction to set the webhook, but it seems not working. I get "Invalid HTTP Response: 400" warning. 

I have done a lot changes and modification to my package. Please help me to push them to your end for review. Thanks!

**Comment by mtmorgan** [comment]
Look at https://github.com/Bioconductor/Contributions/#additional-actions and see if the 'Response' reads 'Failed to parse JSON'.

**Comment by MonkeyLB** [comment]
@mtmorgan I followed instruction, but still not working.
Here is the response I got:
Connection: close
Content-Length: 57
Content-Type: text/html;charset=utf-8
Date: Wed, 01 Feb 2017 02:56:24 GMT
Server: Apache/2.4.18 (Ubuntu)
Status: 400 Bad Request
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger 5.0.30
X-XSS-Protection: 1; mode=block

**Comment by mtmorgan** [comment]
What is the content (both 'Headers' and 'Payload') of the request?

**Comment by MonkeyLB** [comment]
Header:
Request URL: http://issues.bioconductor.org/
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/baf7d6b
X-GitHub-Delivery: 8b8d7780-e80a-11e6-8d2e-0cccfb4ddf9e
X-GitHub-Event: ping

Payload:
{
  "zen": "Favor focus over features.",
  "hook_id": 11846802,
  "hook": {
    "type": "Repository",
    "id": 11846802,
    "name": "web",
    "active": true,
    "events": [
      "push"
    ],
    "config": {
      "content_type": "json",
      "insecure_ssl": "0",
      "url": "http://issues.bioconductor.org"
    },
    "updated_at": "2017-01-31T23:11:07Z",
    "created_at": "2017-01-31T23:11:07Z",
    "url": "https://api.github.com/repos/MonkeyLB/hicrep/hooks/11846802",
    "test_url": "https://api.github.com/repos/MonkeyLB/hicrep/hooks/11846802/test",
    "ping_url": "https://api.github.com/repos/MonkeyLB/hicrep/hooks/11846802/pings",
    "last_response": {
      "code": null,
      "status": "unused",
      "message": null
    }
  },
  "repository": {
    "id": 75767357,
    "name": "hicrep",
    "full_name": "MonkeyLB/hicrep",
    "owner": {
      "login": "MonkeyLB",
      "id": 20000491,
      "avatar_url": "https://avatars.githubusercontent.com/u/20000491?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MonkeyLB",
      "html_url": "https://github.com/MonkeyLB",
      "followers_url": "https://api.github.com/users/MonkeyLB/followers",
      "following_url": "https://api.github.com/users/MonkeyLB/following{/other_user}",
      "gists_url": "https://api.github.com/users/MonkeyLB/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MonkeyLB/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MonkeyLB/subscriptions",
      "organizations_url": "https://api.github.com/users/MonkeyLB/orgs",
      "repos_url": "https://api.github.com/users/MonkeyLB/repos",
      "events_url": "https://api.github.com/users/MonkeyLB/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MonkeyLB/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/MonkeyLB/hicrep",
    "description": "R package to evaluate the reproducibility of Hi-C data",
    "fork": false,
    "url": "https://api.github.com/repos/MonkeyLB/hicrep",
    "forks_url": "https://api.github.com/repos/MonkeyLB/hicrep/forks",
    "keys_url": "https://api.github.com/repos/MonkeyLB/hicrep/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/MonkeyLB/hicrep/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/MonkeyLB/hicrep/teams",
    "hooks_url": "https://api.github.com/repos/MonkeyLB/hicrep/hooks",
    "issue_events_url": "https://api.github.com/repos/MonkeyLB/hicrep/issues/events{/number}",
    "events_url": "https://api.github.com/repos/MonkeyLB/hicrep/events",
    "assignees_url": "https://api.github.com/repos/MonkeyLB/hicrep/assignees{/user}",
    "branches_url": "https://api.github.com/repos/MonkeyLB/hicrep/branches{/branch}",
    "tags_url": "https://api.github.com/repos/MonkeyLB/hicrep/tags",
    "blobs_url": "https://api.github.com/repos/MonkeyLB/hicrep/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/MonkeyLB/hicrep/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/MonkeyLB/hicrep/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/MonkeyLB/hicrep/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/MonkeyLB/hicrep/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/MonkeyLB/hicrep/languages",
    "stargazers_url": "https://api.github.com/repos/MonkeyLB/hicrep/stargazers",
    "contributors_url": "https://api.github.com/repos/MonkeyLB/hicrep/contributors",
    "subscribers_url": "https://api.github.com/repos/MonkeyLB/hicrep/subscribers",
    "subscription_url": "https://api.github.com/repos/MonkeyLB/hicrep/subscription",
    "commits_url": "https://api.github.com/repos/MonkeyLB/hicrep/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/MonkeyLB/hicrep/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/MonkeyLB/hicrep/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/MonkeyLB/hicrep/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/MonkeyLB/hicrep/contents/{+path}",
    "compare_url": "https://api.github.com/repos/MonkeyLB/hicrep/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/MonkeyLB/hicrep/merges",
    "archive_url": "https://api.github.com/repos/MonkeyLB/hicrep/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/MonkeyLB/hicrep/downloads",
    "issues_url": "https://api.github.com/repos/MonkeyLB/hicrep/issues{/number}",
    "pulls_url": "https://api.github.com/repos/MonkeyLB/hicrep/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/MonkeyLB/hicrep/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/MonkeyLB/hicrep/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/MonkeyLB/hicrep/labels{/name}",
    "releases_url": "https://api.github.com/repos/MonkeyLB/hicrep/releases{/id}",
    "deployments_url": "https://api.github.com/repos/MonkeyLB/hicrep/deployments",
    "created_at": "2016-12-06T20:15:28Z",
    "updated_at": "2016-12-07T20:25:56Z",
    "pushed_at": "2017-01-31T23:08:11Z",
    "git_url": "git://github.com/MonkeyLB/hicrep.git",
    "ssh_url": "git@github.com:MonkeyLB/hicrep.git",
    "clone_url": "https://github.com/MonkeyLB/hicrep.git",
    "svn_url": "https://github.com/MonkeyLB/hicrep",
    "homepage": null,
    "size": 1053,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "R",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "MonkeyLB",
    "id": 20000491,
    "avatar_url": "https://avatars.githubusercontent.com/u/20000491?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/MonkeyLB",
    "html_url": "https://github.com/MonkeyLB",
    "followers_url": "https://api.github.com/users/MonkeyLB/followers",
    "following_url": "https://api.github.com/users/MonkeyLB/following{/other_user}",
    "gists_url": "https://api.github.com/users/MonkeyLB/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/MonkeyLB/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/MonkeyLB/subscriptions",
    "organizations_url": "https://api.github.com/users/MonkeyLB/orgs",
    "repos_url": "https://api.github.com/users/MonkeyLB/repos",
    "events_url": "https://api.github.com/users/MonkeyLB/events{/privacy}",
    "received_events_url": "https://api.github.com/users/MonkeyLB/received_events",
    "type": "User",
    "site_admin": false
  }
}

**Comment by MonkeyLB** [comment]
@mtmorgan Hi, do you see the problem from the above messege content?

**Comment by mtmorgan** [comment]
I can't see a problem. Please try to remove the web hook and re-apply it. Then commit a version bump to your package. Please report the Header: and Payload: of BOTH the request and response.

**Comment by MonkeyLB** [comment]
@mtmorgan I did what you suggested.

Request:

header:
Request URL: http://issues.bioconductor.org
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/786bab5
X-GitHub-Delivery: 163fef00-ebdc-11e6-8c79-a9bb58053dc6
X-GitHub-Event: ping

Payload:
{
  "zen": "Encourage flow.",
  "hook_id": 11929425,
  "hook": {
    "type": "Repository",
    "id": 11929425,
    "name": "web",
    "active": true,
    "events": [
      "push"
    ],
    "config": {
      "content_type": "json",
      "insecure_ssl": "0",
      "url": "http://issues.bioconductor.org"
    },
    "updated_at": "2017-02-05T19:48:38Z",
    "created_at": "2017-02-05T19:48:38Z",
    "url": "https://api.github.com/repos/MonkeyLB/hicrep/hooks/11929425",
    "test_url": "https://api.github.com/repos/MonkeyLB/hicrep/hooks/11929425/test",
    "ping_url": "https://api.github.com/repos/MonkeyLB/hicrep/hooks/11929425/pings",
    "last_response": {
      "code": null,
      "status": "unused",
      "message": null
    }
  },
  "repository": {
    "id": 75767357,
    "name": "hicrep",
    "full_name": "MonkeyLB/hicrep",
    "owner": {
      "login": "MonkeyLB",
      "id": 20000491,
      "avatar_url": "https://avatars.githubusercontent.com/u/20000491?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MonkeyLB",
      "html_url": "https://github.com/MonkeyLB",
      "followers_url": "https://api.github.com/users/MonkeyLB/followers",
      "following_url": "https://api.github.com/users/MonkeyLB/following{/other_user}",
      "gists_url": "https://api.github.com/users/MonkeyLB/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MonkeyLB/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MonkeyLB/subscriptions",
      "organizations_url": "https://api.github.com/users/MonkeyLB/orgs",
      "repos_url": "https://api.github.com/users/MonkeyLB/repos",
      "events_url": "https://api.github.com/users/MonkeyLB/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MonkeyLB/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/MonkeyLB/hicrep",
    "description": "R package to evaluate the reproducibility of Hi-C data",
    "fork": false,
    "url": "https://api.github.com/repos/MonkeyLB/hicrep",
    "forks_url": "https://api.github.com/repos/MonkeyLB/hicrep/forks",
    "keys_url": "https://api.github.com/repos/MonkeyLB/hicrep/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/MonkeyLB/hicrep/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/MonkeyLB/hicrep/teams",
    "hooks_url": "https://api.github.com/repos/MonkeyLB/hicrep/hooks",
    "issue_events_url": "https://api.github.com/repos/MonkeyLB/hicrep/issues/events{/number}",
    "events_url": "https://api.github.com/repos/MonkeyLB/hicrep/events",
    "assignees_url": "https://api.github.com/repos/MonkeyLB/hicrep/assignees{/user}",
    "branches_url": "https://api.github.com/repos/MonkeyLB/hicrep/branches{/branch}",
    "tags_url": "https://api.github.com/repos/MonkeyLB/hicrep/tags",
    "blobs_url": "https://api.github.com/repos/MonkeyLB/hicrep/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/MonkeyLB/hicrep/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/MonkeyLB/hicrep/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/MonkeyLB/hicrep/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/MonkeyLB/hicrep/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/MonkeyLB/hicrep/languages",
    "stargazers_url": "https://api.github.com/repos/MonkeyLB/hicrep/stargazers",
    "contributors_url": "https://api.github.com/repos/MonkeyLB/hicrep/contributors",
    "subscribers_url": "https://api.github.com/repos/MonkeyLB/hicrep/subscribers",
    "subscription_url": "https://api.github.com/repos/MonkeyLB/hicrep/subscription",
    "commits_url": "https://api.github.com/repos/MonkeyLB/hicrep/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/MonkeyLB/hicrep/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/MonkeyLB/hicrep/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/MonkeyLB/hicrep/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/MonkeyLB/hicrep/contents/{+path}",
    "compare_url": "https://api.github.com/repos/MonkeyLB/hicrep/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/MonkeyLB/hicrep/merges",
    "archive_url": "https://api.github.com/repos/MonkeyLB/hicrep/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/MonkeyLB/hicrep/downloads",
    "issues_url": "https://api.github.com/repos/MonkeyLB/hicrep/issues{/number}",
    "pulls_url": "https://api.github.com/repos/MonkeyLB/hicrep/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/MonkeyLB/hicrep/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/MonkeyLB/hicrep/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/MonkeyLB/hicrep/labels{/name}",
    "releases_url": "https://api.github.com/repos/MonkeyLB/hicrep/releases{/id}",
    "deployments_url": "https://api.github.com/repos/MonkeyLB/hicrep/deployments",
    "created_at": "2016-12-06T20:15:28Z",
    "updated_at": "2016-12-07T20:25:56Z",
    "pushed_at": "2017-02-05T19:45:23Z",
    "git_url": "git://github.com/MonkeyLB/hicrep.git",
    "ssh_url": "git@github.com:MonkeyLB/hicrep.git",
    "clone_url": "https://github.com/MonkeyLB/hicrep.git",
    "svn_url": "https://github.com/MonkeyLB/hicrep",
    "homepage": null,
    "size": 1153,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "R",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "MonkeyLB",
    "id": 20000491,
    "avatar_url": "https://avatars.githubusercontent.com/u/20000491?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/MonkeyLB",
    "html_url": "https://github.com/MonkeyLB",
    "followers_url": "https://api.github.com/users/MonkeyLB/followers",
    "following_url": "https://api.github.com/users/MonkeyLB/following{/other_user}",
    "gists_url": "https://api.github.com/users/MonkeyLB/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/MonkeyLB/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/MonkeyLB/subscriptions",
    "organizations_url": "https://api.github.com/users/MonkeyLB/orgs",
    "repos_url": "https://api.github.com/users/MonkeyLB/repos",
    "events_url": "https://api.github.com/users/MonkeyLB/events{/privacy}",
    "received_events_url": "https://api.github.com/users/MonkeyLB/received_events",
    "type": "User",
    "site_admin": false
  }
}


Response:

headers:
Connection: close
Content-Length: 57
Content-Type: text/html;charset=utf-8
Date: Sun, 05 Feb 2017 19:48:38 GMT
Server: Apache/2.4.18 (Ubuntu)
Status: 400 Bad Request
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger 5.0.30
X-XSS-Protection: 1; mode=block

body:

Only push, issue, and issue comment event hooks supported

**Comment by mtmorgan** [comment]
How are you bumping the version number? You should have a local repository, edit the DESCRIPTION file, commit to your local git, then push to github.

**Comment by MonkeyLB** [comment]
I think it pushes through successfully now.

**Comment by mtmorgan** [comment]
It looks you've figured out the problem. Any guess as to what it was, so that we can help others more quickly?

**Comment by MonkeyLB** [comment]
@mtmorgan changes on the master brunch will not trigger the push. That was what happened to me.

**Comment by mtmorgan** [comment]
Do you mean _only_ changes on the master branch will trigger a build? Because the last build was triggered by a commit (https://github.com/MonkeyLB/hicrep/commit/1ac1219a6051c4827dedd4ce458ddb6e7ab43dab) on master...

**Comment by MonkeyLB** [comment]
@mtmorgan  I mean, the changes on master branch will NOT trigger push. I did the changes on master branch initially, but they were not pushed through. Then I did version bump on a side branch, and it works.

**Comment by MonkeyLB** [comment]
@mtmorgan Hi, I wonder what is the typical length review time for the package? I saw the notice that my package has been built withou errors or warnings on all platforms, but not sure what should be the next step. Is it just wait for further review? Is there anything I should do?

**Comment by mtmorgan** [comment]
I'm sorry for the delay, I will try to review this in the next day or so.

**Comment by mtmorgan** [comment]
DESCRIPTION

- Provide additional detail in the Description: field, more like a
  paper abstract describing the method, merits, and maybe comparison
  with alternative solutinos.

- Likely 'stats' should be in the Imports: field (used internally by
  the package) rather than Depends: field (essential for the end user
  of your package.

R

- avoid use of `:` for sequences, e..g., `1:nrow()`. Use `seq_len()`
  or `seq_along()` instead (code is robust to 1:0)

- `sample(1:nrow(temp))` can be written more efficiently as
  `sample(nrow(temp))`.

- indent code for readability, e.g., get.scc.R:46-60.

- avoid 'copy-and-append', e.g., `get.scc()`

        corr = cov = wei = n = array()
        ...
        corr[i] = ...
        
  in favor of '[pre-allocate and fill][]'
  
[pre-allocate and fill]: http://bioconductor.org/developers/how-to/efficient-code/pre-allocate-and-fill-if-iterations-are-necessary

- This algorithm

    ```
    for (i in 1:ub){
        idx = which(gdist == i*resol)
    ```
    
  has complexity `ub * length(gdist)`, whereas something like (untested!)

    ```
    grp <- match(gdist, seq_len(ub) * resol)
    idx <- split(gdist, grp)
    ```

  has linear complexity so scales much better. Investigate such
  implementations for more efficient code.

- Use `message()` rather than `print()` to communicate with users
  during function execution, e.g., htrain.R:36. Use `warning()` rather
  than `print()` to indicate unusual conditions, e.g., htrain.R:51

- copy-and-append again appears at MatToVec.R:45

    ```
    tmp = NULL
    for (i in as.double(colnames(mat))){
        tmp = c(tmp, rep(i, rc))
    }
    ```
    
  instead `tmp = rep(as.double(colnames(mat)), each=rc)`
- vectorize calculations rather than iterate, 'hoist' constant
  cacluations outside loops to avoid unnecessary re-caclucation, e.g.,
  , e.g., smoothMat.R:40

    ```
    for (i in 1:r){
        for (j in 1:c){
            rlb = ifelse(i-h > 0, i-h, 1)
            rrb = ifelse(i+h < r, i+h, r)
            clb = ifelse(j-h > 0, j-h, 1)
            crb = ifelse(j+h < c, j+h, c)
            smd_matr[i,j] = mean(matr[rlb:rrb, clb:crb])
        }
    }
    ```
    
  becomes
  
    ````
    i <- seq_len(r)
    rlb <- ifelse(i - h > 0, i - h, 1)
    rrb <- ifelse(i + h < r, i + h, r)
    
    j <- seq_len(c)
    clb <- ifelse(j - h > 0, j - h, 1)
    crb <- ifelse(j + h < c, j +  h, c)

    for (i in seq_len(r)){
        for (j in seq_len(c)){
            smd_matr[i,j] = mean(matr[rlb[i]:rrb[i], clb[j]:crb[j]])
        }
    }
    ```
     
vignette

- no need to include vignette products (.R, .html files) in git.

- indicate correct way to install package once accepted to Bioconductor

        source("https://bioconductor.org/biocLite.R")
        biocLite("hicrep")

- Rather than using `r Sys.Date()` for date:, consider a fixed date
  representing 'last revision'.

- In a final code chunk, include the output of `sessionInfo()` to help
  with reproducibility.

**Comment by MonkeyLB** [comment]
@mtmorgan Hi, Thank you very much for your kind suggestions. I have revised my code accordingly, and the system checks returned OK. Please let me know if I need to do further polishing or something. Again, thank you very much for your comments and insights.

**Comment by mtmorgan** [comment]
Thank you I have marked the package as accepted. It will be added to the Bioconductor svn repository and nightly builds over the next few days, with additional information available then.
