### ISSUE TITLE
EventPointer

### ISSUE THREAD

**Issue by jpromeror** [Bioconductor/Contributions#260]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jpromeror/EventPointer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by jpromeror** [comment]
Hi,

The commits regarding to the problems are done. Also I added a second commit with the version bump, now currently waiting for the next build.

Thanks,

Juan Pablo

**Comment by jpromeror** [comment]
Hello,

Issues are solved. Version Bump (0.99.0 to 0.99.1) added and waiting for new build.

Thanks,

Juan Pablo

**Comment by lshep** [comment]
Please ensure your webhook is initialized correctly; we did not receive a notification to start a build. For now I kicked off a new build manually

**Comment by jpromeror** [comment]
Hello,

The webhook is initialized as stated in  https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md

However, in getting a problem with the webhook 

Headers
Connection: close
Content-Length: 20
Content-Type: text/html;charset=utf-8
Date: Thu, 26 Jan 2017 12:23:06 GMT
Server: Apache/2.4.18 (Ubuntu)
Status: 400 Bad Request
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger 5.0.30
X-XSS-Protection: 1; mode=block
Body
Failed to parse JSON

Thanks,

Juan Pablo

**Comment by lshep** [comment]
When you have made changes, try version bump again and let me know that you have tried to submit again.  If it still doesn't connect can you send me a screen shot of the webhook settings

**Comment by mtmorgan** [comment]
open 'Settings' 'Webhooks' then edit and make sure the 'Content type' is application/json. Then click on the failing 'Recent Deliveries' and click 'Redirect'.

**Comment by jpromeror** [comment]
Thanks, mtmorgan.

Yes, I needed to change the Content type to application/json. 

I didn't change any of the settings as it is stated in the Contribution guidelines:

5. Paste the following URL into the Payload URL box, leaving the other settings alone:
http://issues.bioconductor.org

Perhaps this type of error should be mentioned to avoid problems with other users.

Now everything is working fine

**Comment by lshep** [comment]
Please see the following comments: 

Building: 
 - [ ] To get the package to build it seems like you have sometime used png vs PNG when naming and calling your images.

Checks: 
Please fix most NOTES that are occurring, if appropriate,  as we like to have as clean of builds as possible. These include: 
 - [ ] Fix no globalbinding for makeGRangesFromDataFram, queryHits, subjectHits
 - [ ] Be careful using ::: 
 - [ ] Add Unit Tests.
 - [ ] consider shortening longer lines esp in the vignette to avoid run off when final document is generated. 

Vignette: 
 - [ ] We recommend using BiocStyle as the output format: [BiocStyle](https://www.bioconductor.org/packages/devel/bioc/vignettes/BiocStyle/inst/doc/HtmlStyle.html)
 - [ ] Please include download instructions for your package 
```
source("http://www.bioconductor.org/biocLite.R")
biocLite("EventPointer")
```
In your overview of junction arrays:  
- [ ] The default required files can be downloaded from the EventPointer Github repository ;  these are actually included with your package so change the wording. 
 - [ ] So are those input files in a specific format? Are they generally standard output from the technology used to generate the files? 
In the Jusction arrays/Statistical Analysis: 
- [ ] You are calling variables that are never defined? Ex: AffymetrixCdfFile$byChipType(cdfGFile) , how was AffymetrixCdfFile defined? 
- [ ] This is also similar in the RNA-Seq sectoin - what is si, BamInfo = si ?


General: 
- [ ] We would highly recommend reorganizing your R files, but more importantly reorganizing the man files, grouping like or related functions together. There is a documenting syntax that can be used @rdname or @describeIn that will concatenate documentation files together. Esp internal functions.  You really don't need to documnet unexported functions but at the very least consider grouping them together and having one man file for those used internally. 

R code: 
- [ ] I see it in CDFformGTF and EventPointer, but there may be others: if you have
arguments that can only take specific values  ie. input = "Ensembl", "UCSC", or "GTF"  have a check to ensure it is of correct type `stopifnot(input == )`  
- [ ] There seems to be a lot of opportunities to use robust and efficient coding to speed the functions up please see [here](http://bioconductor.org/developers/how-to/efficient-code/).  In particular you seem to use a lot of 1:n syntax and have a lot of for/foreach loops that may be improved through vectorization.  


Thank you for your submission and I look forward to working with you to get your package approved for inclusion in Biocoonductor.  Please respond back with a comment when finished making updates to the package addressing the above concerns.

**Comment by jpromeror** [comment]
Building:

- [x] To get the package to build it seems like you have sometime used png vs PNG when naming and calling your images.
Checks:

Please fix most NOTES that are occurring, if appropriate, as we like to have as clean of builds as possible. These include:

- [x] Fix no globalbinding for makeGRangesFromDataFram, queryHits, subjectHits
- [ ] Be careful using :::
 - [ ]Add Unit Tests.
 - [ ] consider shortening longer lines esp in the vignette to avoid run off when final document is generated.

As some internal functions from SGSeq are accessed, the ::: notation is used. However, as EventPointer depends on SGSeq, any update on it, will be shown in EventPointer. For UnitTests, we are figuring a way to set the tests for EventPointer functions as the output for some is "complex".

Vignette:

 - [x] We recommend using BiocStyle as the output format: BiocStyle
- [x]  Please include download instructions for your package
source("http://www.bioconductor.org/biocLite.R")
biocLite("EventPointer")
In your overview of junction arrays:

 - [x]  The default required files can be downloaded from the EventPointer Github repository ; these are actually included with your package so change the wording.
 - [x] So are those input files in a specific format? Are they generally standard output from the technology used to generate the files?
In the Jusction arrays/Statistical Analysis:
 - [ ] You are calling variables that are never defined? Ex: AffymetrixCdfFile$byChipType(cdfGFile) , how was AffymetrixCdfFile defined?
  - [x] This is also similar in the RNA-Seq sectoin - what is si, BamInfo = si ?
General:

The line AffymetrixCdfFile$byChipType(cdfGFile) is actually a function from the package aroma.affymetrix. In the vignette this is mentioned. For the RNA-Seq section, I've added a comment to explain where the object si is obtained (SGSeq)

 - [x] We would highly recommend reorganizing your R files, but more importantly reorganizing the man files, grouping like or related functions together. There is a documenting syntax that can be used @rdname or @describeIn that will concatenate documentation files together. Esp internal functions. You really don't need to documnet unexported functions but at the very least consider grouping them together and having one man file for those used internally.
R code:

- [x]  I see it in CDFformGTF and EventPointer, but there may be others: if you have
arguments that can only take specific values ie. input = "Ensembl", "UCSC", or "GTF" have a check to ensure it is of correct type stopifnot(input == )
 - [x]  There seems to be a lot of opportunities to use robust and efficient coding to speed the functions up please see here. In particular you seem to use a lot of 1:n syntax and have a lot of for/foreach loops that may be improved through vectorization.

**Comment by lshep** [comment]
Thank you for your current updates.  A few more concerns that should be addressed:

**VIGNETTES:**

write to a tempdir()  not package directory

Statistical Analysis/aroma.affymetrix pre-processing pipeline 
This section does not work fix and show code that would be actually run-able. If something is loaded through another package show the load and use of that other package:
```
> verbose <- Arguments$getVerbose(-8);
Error: object 'Arguments' not found
> timestampOn(verbose);
Error in timestampOn(verbose) : could not find function "timestampOn"
> projectName <- "Prosplice"
> chipType <- "EP_HTA-2_0"
> cdfGFile <- "EP_HTA-2_0,r"
> cdfG <- AffymetrixCdfFile$byChipType(cdfGFile)
Error: object 'AffymetrixCdfFile' not found
> cs <- AffymetrixCelSet$byName(projectName, cdf=cdfG)
Error: object 'AffymetrixCelSet' not found
> bc <- NormExpBackgroundCorrection(cs, method="mle", tag=c("*","r11"));
Error in NormExpBackgroundCorrection(cs, method = "mle", tag = c("*",  : 
  could not find function "NormExpBackgroundCorrection"
> csBC <- process(bc,verbose=verbose,ram=20);
Error in process(bc, verbose = verbose, ram = 20) : 
  could not find function "process"
> qn <- QuantileNormalization(csBC, typesToUpdate="pm");
Error in QuantileNormalization(csBC, typesToUpdate = "pm") : 
  could not find function "QuantileNormalization"
> csN <- process(qn,verbose=verbose,ram=20);
Error in process(qn, verbose = verbose, ram = 20) : 
  could not find function "process"
> plmEx <- ExonRmaPlm(csN, mergeGroups=FALSE)
Error in ExonRmaPlm(csN, mergeGroups = FALSE) : 
  could not find function "ExonRmaPlm"
> fit(plmEx, verbose=verbose)
Error in fit(plmEx, verbose = verbose) : could not find function "fit"
> cesEx <- getChipEffectSet(plmEx)
Error in getChipEffectSet(plmEx) : 
  could not find function "getChipEffectSet"
> ExFit <- extractDataFrame(cesEx, addNames = TRUE)
Error in extractDataFrame(cesEx, addNames = TRUE) : 
  could not find function "extractDataFrame"
> 
```
R code/vignettes: 
```
>   data(ArraysData)
> 
>    Dmatrix<-matrix(c(1,1,1,1,0,0,1,1),nrow=4,ncol=2,byrow=FALSE)
>    Cmatrix<-t(t(c(0,1)))
>    EventsFound<-paste(system.file("extdata",package="EventPointer"),"/EventsFound.txt",sep="")
>    Events<-EventPointer(Design=Dmatrix,
+                       Contrast=Cmatrix,
+                       ExFit=ArraysData,
+                       Eventstxt=EventsFound,
+                       Filter=TRUE,
+                       Qn=0.25,
+                       Statistic="LogFC",
+                       PSI=TRUE)
10:34:55 AM Running EventPointer:  
	** Statistical Analysis: Logarithm of the fold change of both isoforms 
	** Delta PSI will be calculated 
	** Expression filter using 25 quantile 
            ---------------------------------------------------------------- 
	** Calculating PSI...Done 
	** Running Expression Filter...Done 
	** Running Statistical Analysis...Done 

 10:34:56 AM  Analysis Completed> 
```
and 
```
>    EventPointer_RNASeq_IGV(Events,SG_RNASeq,EventsTxt,PathGTF)

  |======================================================================| 100%> 
```
Add new line when code completes. 


**Man files:**
Write to tempdir()  not package directory

If flat2Cdf is also internal can it also go in the InternalFunctions file? 



**R Code:** 
CDFfromGTF.R -  do not use `,` in output file name it can cause issues depending on the os system. We recommend using `_ `

Extend the robust and efficient code to all functions: 
In general, a lot of for loops ....can some of for loops be vectorized with applys? It should speed up code dramatically if can be applied.  Also there are still 1:n syntax that can be substituted with seq_along or seq_len  -  EventPointer, EventPointer_RNASeq, and others.  [Robust and Efficient Code](http://bioconductor.org/developers/how-to/efficient-code/)


should have checks in all functions that have specific input to ensure correctly being used - like how you now check input in  CDFfromGTF and stop if the argument is not of specific expected value - extend out to other user functions - EventDectection, EventPointer, EventPointer_RNASeq, and others....   

Thank you for your continued effort.  Please comment here after you are done pushing changes to let me know what has been addressed and I will review again.

**Comment by jpromeror** [comment]
Hi Lori @lshep,

Just one question.

In the part of Statistical Analysis/aroma.affymetrix pre-processing pipeline, the code that is shown in the vignette is actually a simple guide, to show users how we set the parameters to run aroma.affymetrix.

This package requires a particular folder structure and files. In order to create a runable example, I would need to include those files and folders, but those files are big, increasing the package size and would slow down the process of building the vignette.

My idea is just to put an example of how we set the options for aroma.affymetrix. Could I describe this in the vignette to avoid the issue or I would actually need to include all the files to run the code?.

Thanks!

-Juan Pablo

**Comment by lshep** [comment]
Yes that would be fine.  It was just unclear of how you could actually run it.

**Comment by jpromeror** [comment]
Lori @lshep 

Im almost done with the issues. I noticed that the bot added the Version Bump Required tag, is there a "time-limit" between version bumps? This just to know if I should speed up in the problems regarding with the efficient code.

Thanks.

Juan Pablo

**Comment by lshep** [comment]
There is no time limit in between version bumps.  We add this tag to let you know when you are doing pushes without a version bump it will not be built on our system.  The system only builds with a version bump.

**Comment by hershbc** [comment]
@jpromeror 
I'm very excited to use your EventPointer.  I have successfully created the ExFit file.  I have also successfully run EventPointer with your sample sets.  I am really struggling to make the EventsFound.txt.  I am fairly new to R, so what I have done is download the CDFfromGTF.R file and run it to add the function to my global environment.  I then added every package listed under @import (except "methods" is, I'm not sure what that is)  I saved your files in the working directory so I could make sure it was working before I tried it with the complete files, but I am getting an error pretty early on.  Could you please help me?  I've been trying to get this to work for days (didn't realize you were in the middle of updates) and I would really like to show this analysis to my committee on Tuesday.  

Error in open.connection(con, open) : cannot open the connection 
11.
open.connection(con, open) 
10.
open(con, open) 
9.
connectionForResource(con, "r") 
8.
.sniffGFFVersion(resource(con)) 
7.
.local(con, format, text, ...) 
6.
import(FileForFormat(con, format), ...) 
5.
import(FileForFormat(con, format), ...) 
4.
import(file, format = format, colnames = colnames, feature.type = GFF_FEATURE_TYPES) 
3.
import(file, format = format, colnames = colnames, feature.type = GFF_FEATURE_TYPES) 
2.
makeTxDbFromGFF(file = inputFile, format = "gtf", dataSource = "Custom GTF") 
1.
CDFfromGTF(input = "GTF", inputFile = DONSON_GTF, PSR = PSRProbes, 
    Junc = JunctionProbes, PathCDF = Directory)

**Comment by hershbc** [comment]
Would it be possible to just make the complete EventsFound.txt needed for the EventPointer available?  For everyone using HTA2.0 microarrays, the file will be the same, right?

**Comment by hershbc** [comment]
Hi @jpromeror 
I've been working with your EventPointer this week, I'm very excited to be able to use it.  I hope to have the visualization files in IGV for a presentation on Tuesday.  However, I've had some trouble the last few days installing EventPointer. I have what I believe is the old version of EventPointer, because it allows me to install library(EventPointer) but there is no function for CDFfromGTF.

> biocLite("EventPointer")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.4 (BiocInstaller 1.24.0), R 3.3.2 (2016-10-31).
Installing package(s) ‘EventPointer’
package ‘EventPointer’ is not available (for R version 3.3.2)

**Comment by lshep** [comment]
@hershbc EventPointer is in the review process for submission to Bioconductor and has not been accepted yet.  https://github.com/Bioconductor/Contributions/issues  is a place for submitting new package to Bioconductor.  Any issues or trouble you are having with a package should be submitted as an issue on the package repository https://github.com/jpromeror/EventPointer. 
Once it is accepted it will be available via the biocLite command.  It the meantime you could install from his github repository directly.  biocLite("jpromeror/EventPointer") .  A list of available Bioconductor packages can be found [Here](http://bioconductor.org/packages/release/BiocViews.html#___Software).  Also, for future help on accepted Bioconductor packages, please post to the [support site](https://support.bioconductor.org/)

**Comment by jpromeror** [comment]
@hershbc 

Just as Lori explained, the R package is still in review before being available in bioconductor.
I will try to speed up the process, perhaps you could show the examples from the vignette at your meeting.

**Comment by hershbc** [comment]
Thank you both for the quick replies, this was my first attempt at using anything on GitHub, guess it was just unlucky chance that the first tool I picked was being actively updated.   I have a lot to learn.  I especially appreciate the links to where I can post for help.  I look forward to using this tool in the future!

**Comment by jpromeror** [comment]
Hi Lori @lshep ,

It seems that the build in bioconductor fails, there is an error:

Quitting from lines 302-318 (EventPointer.Rmd) 
Error: processing vignette 'EventPointer.Rmd' failed with diagnostics:
assignment of an object of class "NULL" is not valid for slot 'NAMES' in an object of class "SGFeatureCounts"; is(value, "characterORNULL") is not TRUE
Execution halted

However, Im not able to reproduce the error myself. I've checked the package (in my local machine) in both Windows and Mac OS with no errors or warnings. I've also checked all the examples shown in the vignette in Linux and didn't had any problem.

As I can't reproduce the error, im not sure where to look or how to fix it.  Is there any way to obtain a more detailed report about the build?

Thanks,

Juan Pablo

**Comment by lshep** [comment]
Are you using the devel versions of all packages when testing?  `sessionInfo()` will tell you what versions of packages you are using.  When I clone your repository and test locally, I also get the ERROR that is occurring on our build systems.  I will try to investigate a little further but the code that is having issues: 
```
   BamInfo<-si
   Samples<-BamInfo[,2]
   PathToSamples <- system.file("extdata/bams", package = "SGSeq")
   PathToGTF<-paste(system.file("extdata",package="EventPointer"),"/FBXO31.gtf",sep="")

  # Run PrepareBam function
   SG_RNASeq<-PrepareBam_EP(Samples=Samples,
                            SamplePath=PathToSamples,
                            Ref_Transc="GTF",
                            fileTransc=PathToGTF,
                            cores=1)
```
When I run: 
```
>  SG_RNASeq<-PrepareBam_EP(Samples=Samples,
+                             SamplePath=PathToSamples,
+                             Ref_Transc="GTF",
+                             fileTransc=PathToGTF,
+                             cores=1)
Preparing BAM files for EventPointer...
 Obtaining Bam Information
N1.bam complete.
N2.bam complete.
N3.bam complete.
N4.bam complete.
T1.bam complete.
T2.bam complete.
T3.bam complete.
T4.bam complete.
Done
 Obtaining Reference Transcriptome...Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Done
 Predicting Features from BAMs...N1.bam complete.
N2.bam complete.
N3.bam complete.
N4.bam complete.
T1.bam complete.
T2.bam complete.
T3.bam complete.
T4.bam complete.
N1.bam complete.
N2.bam complete.
N3.bam complete.
N4.bam complete.
T1.bam complete.
T2.bam complete.
T3.bam complete.
T4.bam complete.
Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “NULL” is not valid for slot ‘NAMES’ in an object of class “SGFeatureCounts”; is(value, "characterORNULL") is not TRUE
```

**Comment by jpromeror** [comment]
Tank You!

Yes, the problem was that one of the packages wasn't using the latest devel version. 

Now Im able to get the error. Will Fix it ASAP.

**Comment by jpromeror** [comment]
@lshep 

I've checked the error and it seems that is caused by the SGSeq R package.

One of the functions in it (getSGFeatureCounts) causes the error, even when running the example provided in the man files. Its exactly the same error that appears when using EventPointer.

path <- system.file("extdata", package = "SGSeq")
si$file_bam <- file.path(path, "bams", si$file_bam)
sgfc <- getSGFeatureCounts(si, sgf_pred)

> ?getSGFeatureCounts
> path <- system.file("extdata", package = "SGSeq")
> si$file_bam <- file.path(path, "bams", si$file_bam)
> sgfc <- getSGFeatureCounts(si, sgf_pred)
N1 complete.
N2 complete.
N3 complete.
N4 complete.
T1 complete.
T2 complete.
T3 complete.
T4 complete.
Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “NULL” is not valid for slot ‘NAMES’ in an object of class “SGFeatureCounts”; is(value, "characterORNULL") is not TRUE

Don't know if I have to wait until that problem is fixed.

Thanks Again,

JP

**Comment by lshep** [comment]
I would suggest putting that section in dontrun{} for now so that the builder can actually check your package, and reach out to the SGSeq package maintainer as well as post on the devel mailing list.

**Comment by jpromeror** [comment]
I've already contacted the package maintainer. He posted the problem on the deal mailing list and the issue is already under consideration.

**Comment by jpromeror** [comment]
@lshep 

Now everything is fine again.

Will be aware of any comment or notification made related to the package.

Thanks,

-- Juan Pablo

**Comment by lshep** [comment]
I'll investigate this timeout on malbec2.  It seems odd it would only timeout on one build.  You can ignore this timeout for now.

**Comment by lshep** [comment]
Thank you for you changes. When I tested locally it ran much faster than what is reported (and much under the time requirement).  I will recommend your package be accepted.  You will receive svn instructions via email. Please leave the issue open until you have received the instructions.

**Comment by jpromeror** [comment]
Great. Yes, I was surprised by the timeout but I guess it wast being caused by the updates on the servers.
I'll wait for the svn instructions.

Thanks for everything.
