### ISSUE TITLE
SpatialOmicsOverlay

### ISSUE THREAD

**Issue by maddygriz** [Bioconductor/Contributions#2604]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Nanostring-Biostats/SpatialOmicsOverlay

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
ERROR: dependency 'RBioFormats' is not available for package 'SpatialOmicsOverlay'

This package is github-only.  You can't import or depend on it in a Bioconductor package.  See the guidelines.

**Comment by maddygriz** [comment]
RBioFormats has been removed from the dependency list.

**Comment by vjcitn** [comment]
It looks like you appropriated the code you needed.  But RBioFormats is doing things that we would like to avoid.  At a minimum use BiocFileCache to acquire the jar file and then refer to the jar file as needed through the cache reference.  If I read the current code correctly it seems to copy the file into the installed package area, which should not be done.  Only R utilities should manipulate the installed package folders.

**Comment by vjcitn** [comment]
Here is the advice from our core:  
```
They should download the jar file to a cached location. Download should 
be delayed i.e. not done at installation time or load time but on first use. 
With agreement from  the user if EULA required and in interactive mode.
```

**Comment by maddygriz** [comment]
Thanks for reaching out to the core, that is helpful. I have updated the code to use BiocFileCache but it is currently downloading on load. I will update to the cores recommendation and get back to you

**Comment by maddygriz** [comment]
The jar file download has been moved to BiocFileCache and is not downloaded on loading. The functions that use the jar file ensure that it is in the cache.

**Comment by maddygriz** [comment]
@vjcitn have you had a chance to look at the package after changing the jar download process?

**Comment by vjcitn** [comment]
I will do so now

**Comment by vjcitn** [comment]
FWIW this is what happened on my mac ... still exploring linux
```
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Warning in parseOverlayAttrs(omexml = xml, annots = annots, labworksheet = labWorksheet) :
  Some AOIs do not match annotation file. 
Not Matched: DSP-1012996073013-H-C01, DSP-1012996073013-H-C07, DSP-1012996073013-H-C08, DSP-1012996073013-H-C09, DSP-1012996073013-H-C12, DSP-1012996073013-H-G02
Warning in .local(overlay, annots, plottingFactor, ...) :
  No names on vector, assuming data is in same order as overlay
Warning in knitr::include_graphics(tmp) :
  It is highly recommended to use relative paths for images. You had absolute paths: "/private/var/folders/n4/p9th81md60s8nv12yv40sv8m0000gp/T/Rtmphv3owy/Rbuild601b793c5d9a/SpatialOmicsOverlay/vignettes/SpatialOmicsOverlay_files/figure-html/add image-1.png"
Warning in png::readPNG(path, native = TRUE, info = TRUE) :
  Image uses 16-bit channels but R native format only supports 8-bit, truncating LSB.
Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  no font could be found for family "grey"
Quitting from lines 188-191 (SpatialOmicsOverlay.Rmd) 
Error: processing vignette 'SpatialOmicsOverlay.Rmd' failed with diagnostics:
polygon edge not found
--- failed re-building ‘SpatialOmicsOverlay.Rmd’

SUMMARY: processing the following file failed:
  ‘SpatialOmicsOverlay.Rmd’
```

**Comment by maddygriz** [comment]
@vjcitn I have fixed that issue in the mac vignette build

**Comment by vjcitn** [comment]
R CMD build brings the package to 69 MB.  Note section 5.6 here: https://bioconductor.org/packages/devel/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html

The package would then fail BiocCheck when applied to the tarball.

My initial R CMD check hit:
```
══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test_all.R:13:5): mouse brain tiff can be downloaded ───────────────
  grepl("/.cache/R/SpatialOmicsOverlay/", tifFile) is not TRUE
 ```

The test data makes your package tarball big

```
/tmp/SpatialOmicsOverlay/tests/testthat
PC002284:testthat vincentcarey$ ls -tl testData
total 35624
-rw-r--r--  1 vincentcarey  wheel     9289 Apr 20 05:54 test_LabWorksheet.txt
-rw-r--r--  1 vincentcarey  wheel  7906328 Apr 20 05:54 muBrainSpatialOverlay.RDS
-rw-r--r--  1 vincentcarey  wheel  3211218 Apr 20 05:54 muBrain.zip
-rw-r--r--  1 vincentcarey  wheel    25275 Apr 20 05:54 kidney_annotations_allROIs.txt
-rw-r--r--  1 vincentcarey  wheel   275382 Apr 20 05:54 kidneyXML.RDS
-rw-r--r--  1 vincentcarey  wheel    27506 Apr 20 05:54 kidneyMaskTruth.RDS
-rw-r--r--  1 vincentcarey  wheel  2944842 Apr 20 05:54 kidneyDecodedTruth.RDS
-rw-r--r--  1 vincentcarey  wheel  2418370 Apr 20 05:54 kidneyCoordsTruth.RDS
-rw-r--r--  1 vincentcarey  wheel  1402842 Apr 20 05:54 figureReady.zip
```

The 5MB overall and 5MB per file limits are violated.  I think you can solve this by using ExperimentHub contributions.  Don't rush!  Your package can get reviewed but these basic oversize conditions need to be ameliorated.  @lshep

**Comment by maddygriz** [comment]
@lshep @vjcitn I have fixed that test error and I will work on shrinking the tarball. Thanks!

**Comment by maddygriz** [comment]
@lshep @vjcitn I have reduced the tarball down to ~2mb. This is without the vignette though, does that need to be included?

**Comment by vjcitn** [comment]
Whatever R CMD build produces must not exceed 5MB.  I will have a look.

**Comment by vjcitn** [comment]
Here is what I am seeing after a build (partly; this is from a tar tzvf of the built package):
```
-rw-r--r--  0 vincentcarey staff 14759507 Apr 20 19:23 SpatialOmicsOverlay/inst/doc/SpatialOmicsOverlay.html
drwxr-xr-x  0 vincentcarey staff        0 Apr 20 19:20 SpatialOmicsOverlay/inst/extdata/
-rw-r--r--  0 vincentcarey staff   550582 Apr 20 19:20 SpatialOmicsOverlay/inst/extdata/muBrainSubset_SpatialOverlay.zip
-rw-r--r--  0 vincentcarey staff    20640 Apr 20 19:20 SpatialOmicsOverlay/inst/extdata/muBrain_GxT.zip
-rw-r--r--  0 vincentcarey staff    29480 Apr 16 23:17 SpatialOmicsOverlay/inst/extdata/muBrain_LabWorksheet.txt
drwxr-xr-x  0 vincentcarey staff        0 Apr 20 19:20 SpatialOmicsOverlay/inst/extdata/testData/
-rw-r--r--  0 vincentcarey staff   939248 Apr 20 19:20 SpatialOmicsOverlay/inst/extdata/testData/kidney.zip
-rw-r--r--  0 vincentcarey staff     9289 Apr 20 19:20 SpatialOmicsOverlay/inst/extdata/testData/test_LabWorksheet.txt
drwxr-xr-x  0 vincentcarey staff        0 Apr 16 23:17 SpatialOmicsOverlay/inst/java/
-rw-r--r--  0 vincentcarey staff     3976 Apr 16 23:17 SpatialOmicsOverlay/inst/java/RBioFormats.jar
-rw-r--r--  0 vincentcarey staff 37460318 Apr 16 23:17 SpatialOmicsOverlay/inst/java/bioformats_package.jar
```
did you intend to keep the jar file in the package?  If it is retrieved to cache you should not need it.  I guess the HTML of the vignette is large because of included images.  Can you find a more compact format?  Think of the vignette as mostly helping people to use the software to achieve desired aims -- it does not have to give an exhaustive overview of all image-related outcomes.  And it does not need to exercise every imaging modality. 
 You could refer to a web site that gives all the details, for example.  Vignettes have to cut a balance between comprehensive illustration and feasible production and size aspects.

**Comment by maddygriz** [comment]
I don't see the bioformats_package.jar file in my repo or the built tar file so no it is not supposed to be there. It gets downloaded to the cache and not the inst/java folder. Is it possible that is left over from a previous build?
![image](https://user-images.githubusercontent.com/40255151/164355339-3cab44f6-6466-434b-a7ba-51c0d9fb056e.png)

I just updated the vignette with smaller images so we should be good to go with the package size

**Comment by maddygriz** [comment]
@vjcitn any update from your end?

**Comment by vjcitn** [comment]
When I pulled, the big jar file remained in the repo.  I am now on a train.  I will look at it as soon as I can.  Please bump the z in x.y.z every time you change sources, in the Version in DESCRIPTION.  Thanks

**Comment by vjcitn** [comment]
you made it... around 3.6MB ... vignette looks good.  will clear pre-check

**Comment by maddygriz** [comment]
@vjcitn when trying to push my changes I receive this error. 

> FATAL: W any packages/SpatialOmicsOverlay mgriswold DENIED by fallthru
> (or you mis-spelled the reponame)
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

I looked at my BiocCredentials and it doesn't look like I have access to this package.

**Comment by vjcitn** [comment]
be sure u are using correct git credential   review the faq  if not solved email bioc-devel  @nturaga

**Comment by lshep** [comment]
Did you change your username in the app?

**Comment by lshep** [comment]
There is a mismatch in username.  Give me 5 minutes and I should have it corrected.

**Comment by lshep** [comment]
Please try now. You should now have access

**Comment by maddygriz** [comment]
That worked! thanks

**Comment by vjcitn** [comment]
```
Examples with CPU (user + system) or elapsed time > 5s
                          user system elapsed
readSpatialOverlay      95.533  2.486  81.384
add4ChannelImage        41.033  3.666  31.942
flipY                   42.014  1.587  26.802
changeColoringIntensity 41.430  2.032  25.218
cropSamples             40.590  1.338  26.841
flipX                   39.514  1.201  25.800
addImageOmeTiff         37.722  2.000  25.723
recolor                 37.235  1.662  22.057
plotSpatialOverlay      37.451  1.249  21.959
fluorLegend             37.314  1.195  24.458
cropTissue              35.511  1.433  24.591
themeTransparent        34.654  1.165  21.468
changeImageColoring     32.871  1.571  24.638
imageExtraction         25.660  1.281  13.050
createMask              16.084  0.438  16.548
createCoordFile         10.177  0.126  10.293
fluorData                8.480  0.418   3.849
xmlExtraction            8.323  0.373   3.656
physicalSizes            7.792  0.314   3.288
parseOverlayAttrs        7.732  0.248   3.567
parseScanMetadata        7.569  0.312   3.355
checkValidRes            6.767  0.651   3.378
* checking for unstated dependencies in tests ... OK
* checking tests ...
  Running testthat.R ERROR
TIMEOUT: R CMD check exceeded 15 mins
```
hope the timings can be improved

**Comment by vjcitn** [comment]
I am working on reviewing this package.  I have some concern that the package is licensed MIT but there is wholesale incorporation of GPL-3 code from RBioFormats.  Have you discussed this with A Oles who manages that package?  The existence of GPL-3 code in SpatialOmicsOverlay must be properly acknowledged at top level, IMHO.

**Comment by vjcitn** [comment]
You are including code from an author whose name does not appear in DESCRIPTION.  I believe this is not appropriate, though strictly speaking, perhaps the license is properly followed.  Does this GPL-3 clause
```
#   a) The work must carry prominent notices stating that you modified
# it, and giving a relevant date.
```
apply?

**Comment by maddygriz** [comment]
I have added A Oles as an author and added the relevant modification date. 

I did not discuss the addition of the code with A Oles because the license states that the code can be used verbatim and modified. 

> You may convey verbatim copies of the Program's source code as you
> receive it, in any medium, provided that you conspicuously and
> appropriately publish on each copy an appropriate copyright notice

> You may convey a work based on the Program, or the modifications to
> produce it from the Program, in the form of source code under the
> terms of section 4

**Comment by vjcitn** [comment]
Please don't add him as an author without his assent.  Thanks!

**Comment by maddygriz** [comment]
I think I used the wrong wording. I added him as a copy right holder, a cph. But I can remove the email.

**Comment by vjcitn** [comment]
Since RBioFormats is GPL-3 https://www.gnu.org/licenses/gpl-3.0.en.html becomes relevant.  You are declaring MIT license, but see point 5(c).

**Comment by vjcitn** [comment]
Let me know if you have a plan for dealing with this, we are trying to finish up accepted vs pending packages.  Thanks

**Comment by maddygriz** [comment]
I am working on it. I'm waiting on our legal department and head of biostats to respond with how we need to address this.

**Comment by maddygriz** [comment]
I have confirmed with our team that we don't want to switch licenses. We are considering a couple of options, but this may take some time. Thank you for all of your help up to this point!

**Comment by vjcitn** [comment]
Hi, we'll temporarily close the issue, reopen when you are ready to proceed.  The author of RBioFormats seemed willing to contribute the package to Bioconductor, which would simplify matters for you.  Perhaps you should be in touch.

**Comment by maddygriz** [comment]
@vjcitn Hi Vince, I have been in contact with the RBioFormats team and they said they are working to get it submitted to Bioconductor for this next release. I would like to open this issue again in preparation for their submission. Should we open this issue or should I create a new one? 

Thanks, Maddy

**Comment by lshep** [comment]
When they have submitted to Bioconductor we can reopen this issue.

**Comment by maddygriz** [comment]
@vjcitn and @lshep RBioFormats has been submitted! #2793 Can we reopen this issue?

**Comment by maddygriz** [comment]
@lshep The new build is erroring because RBioFormats isn't available yet. Is there something I need to do on my end other than wait for them to be approved?

**Comment by lshep** [comment]
That is correct. It won't be available until the package is accepted and on our builders.

**Comment by maddygriz** [comment]
@vjcitn @lshep I saw that the deadline for new packages to be accepted was yesterday so since RBioFormats hasn't been accepted yet does that mean that we have missed the ability to get into 3.16 or is there any wiggle room?

**Comment by lshep** [comment]
RBioFormats does not look like it will be in 3.16,  therefore SpatialOmicsOverly will also not be in 3.16 since it is a needed dependency, especially since even if RBioFormats is reviewed and accepted, we still will have to do the official review of this package.  It will be reviewed and included in the next release (3.17) and will be findable in Bioconductor devel until the spring release.

**Comment by vjcitn** [comment]
Can you bump the version @maddygriz to see if a new build will work?  On my laptop it hummed along until 
```
> ## ----pyramidal tiff, echo=FALSE, fig.cap="Pyramidal TIFF", out.width = '50%'----
> knitr::include_graphics("images/pyramidalTIFF.png")
[1] "images/pyramidalTIFF.png"
attr(,"class")
[1] "knit_image_paths" "knit_asis"       

> ## ----java error, error=TRUE---------------------------------------------------
> muBrain <- addImageOmeTiff(overlay = muBrain, ometiff = tifFile,  .... [TRUNCATED] 
Error in .jcall("RBioFormats", "Ljava/lang/Object;", "readPixels", i,  : 
  java.lang.NegativeArraySizeException: -2147483648
In addition: Warning message:
In parseOverlayAttrs(omexml = xml, annots = annots, labworksheet = labWorksheet) :
  Some AOIs do not match annotation file. 
Not Matched: DSP-1012996073013-H-C01, DSP-1012996073013-H-C07, DSP-1012996073013-H-C08, DSP-1012996073013-H-C09, DSP-1012996073013-H-C12, DSP-1012996073013-H-G02

```
It is admirable to have the error thrown in real time but I think that will confound the build process and you will have error flag attached.  I think a narrative will suffice.  Or is this a real error owing to my limited RAM?

**Comment by vjcitn** [comment]
looks like RBioFormats is not past review yet, so this review can't continue yet.

**Comment by maddygriz** [comment]
@vjcitn 

Hi Vince, thanks for starting to look into this. This is a real error that is thrown by either RBioFormats or rJava. But this section of the vignette is supposed to throw that error because most computers can't open the image at res = 1. This is specified in the vignette in the text above that code chunk.

"Using too big of an image will cause a java memory error. If this error occurs, increase your `res` value. Below is an example of the error you will receive if the resolution is too high for your system."

----**java error, error=TRUE**---------------------------------------------------
```
> muBrain <- addImageOmeTiff(overlay = muBrain, ometiff = tifFile, res = 1)
Error in .jcall("RBioFormats", "Ljava/lang/Object;", "readPixels", i,  : 
  java.lang.NegativeArraySizeException: -2147483648
```

But the next line of code shows how to mitigate this issue. 

"The resolution size will affect speed and image resolution through the rest of the analysis. To check the smallest resolution size available, for the fastest speeds, use `checkValidRes()`. For the rest of this tutorial we will be using res = 8 for vignette size restrictions, but res 4-6 is recommended. "

----add image---------------------------------------------------
```
#lowest resolution = fastest speeds
checkValidRes(ometiff = tifFile)
res <- 8
muBrain <- addImageOmeTiff(overlay = muBrain, ometiff = tifFile, res = res)
muBrain
showImage(muBrain)
```

Hope that helps for when RBioFormats has past its review.

**Comment by maddygriz** [comment]
@vjcitn It looks like RBioFormats passed its review last week! Let me know if you need anything from me to continue this review.

**Comment by lshep** [comment]
Could you do a version bump and push to git so that we get a build report now that it is available. Not RBioFormats is having issues on merida1 so it will likely still not be available there but should be able to get a build report for nebbiolo1

**Comment by maddygriz** [comment]
@vjcitn @lshep This build is now only failing on the merida1 where RBioFormats is not available as was stated previously. Let me know if there is anything else that I need to do to aid in this review.

**Comment by maddygriz** [comment]
@vjcitn @lshep I know the build report says that there is an error but as stated [here](https://github.com/Bioconductor/Contributions/issues/2604#issuecomment-1401837656) this is due to RBioFormats not being available on merida1. Let me know if you need anything else from me to continue this review.  - Maddy

**Comment by vjcitn** [comment]
```
In this example, we are downloading a tiff image from a Box folder but this variable is simply the file path to a OME-TIFF.
```{r tiff file}
tifFile <- downloadMouseBrainImage()
```
I don't think downloading from Box is consistent with the guidelines.  But let's put that to one side.  Either Box is very slow or the image is enormous.  I see that you are using BiocFileCache to manage it, which is good.  But please have a look at the time required to get the image.  Is there anything that can be done to speed it along?  Reduce resolution, reduce actual image size?  Is Box a bad distribution resource?  Is the image available in an S3 bucket?

**Comment by vjcitn** [comment]
I guess the vignette is wrong?  The file is coming from us-west-2.amazonaws.com?

**Comment by vjcitn** [comment]
So a tar.gz of 13GB is downloaded.  This takes quite some time and will likely time out on the build system?  Let's discuss how the build system or Hubs can be prepared so that this package can be checked in a timely way.  Then we need some mechanism for notifying users that running the code in the vignette will produce at least 21GB of data in BiocFileCache.

**Comment by vjcitn** [comment]
Finally my effort led to the following: 
```
> muBrain <- addImageOmeTiff(overlay = muBrain, ometiff = tifFile,  .... [TRUNCATED] 
Error in .jcall("RBioFormats", "Ljava/lang/Object;", "readPixels", i,  : 
  java.lang.NegativeArraySizeException: -2147483648
In addition: Warning message:
In parseOverlayAttrs(omexml = xml, annots = annots, labworksheet = labWorksheet) :
  Some AOIs do not match annotation file. 
Not Matched: DSP-1012996073013-H-C01, DSP-1012996073013-H-C07, DSP-1012996073013-H-C08, DSP-1012996073013-H-C09, DSP-1012996073013-H-C12, DSP-1012996073013-H-G02
```
which is in the vignette.  Any clues?

**Comment by maddygriz** [comment]
The vignette is wrong, it is downloading from AWS S3. I will update that.  The file is large and we can't reduce it. It is a stacked OME-TIFF image which is the driving file type of the package. I can remove the .tar file in the download function which will remove 13GB in BiocFileCache but notifying the user about the size is also a good idea. 

As for the java error, you will need to increase your `res` variable.  See this comment for a more in-depth answer. https://github.com/Bioconductor/Contributions/issues/2604#issuecomment-1369973936

**Comment by vjcitn** [comment]
Thanks for the information.  Please do not make a deliberate error in the vignette that requires user intervention.  If the error experience is probable and users need to be informed about it, just narrate it.  I'd suggest you set the res to a feasible level for those who might run the vignette after purling it.

**Comment by vjcitn** [comment]
I am aware that `error=TRUE` is available for vignettes to continue processing.  It is too disruptive here.  The error should not be happening in normal use.

**Comment by maddygriz** [comment]
I have made edits to the vignette regarding the error and mouse download warnings. As for the `downloadMouseBrainImage()` function, I added a user check to see if a user is ok with a 13 GB download and removed the bloat left in the cache. 

I don't think that OSN is the route we want to go for the data storage. In investigating, it looks like the data can only be stored for [5 years](https://www.openstoragenetwork.org/get-involved/get-an-allocation/) and needs to come from an "[academic, non-profit research, or educational institution](https://allocations.access-ci.org/access-allocations-policies)" which NanoString does not fit. 

Now that there is caution around the download, we would prefer to keep the data located on S3 where we have absolute control of the data. In regards to slicing the OME-TIFF, this dataset is representative of the datasets that this package is meant to work with. While the vignette is meant to show off the package to a wider audience, this is only currently meant for NanoString data so a user will need more than 13 GB to work with their own data. If that file size seems large, it is actually on the smaller end of our data and we want to show that this package can handle this type and size of data.  

I know there was a worry about build time with the long file download but the last build was only 8 minutes so I'm not sure if that needs to be addressed further. 
![image](https://user-images.githubusercontent.com/40255151/225063347-515b6d4b-8372-4f6f-bf12-bfbb9d986c46.png)

**Comment by vjcitn** [comment]
OK.  Do you know that the package builds and passes check on macOS?

**Comment by maddygriz** [comment]
We have tested that it runs on macOS but we haven't done the build checks. I can run those checks this week.

**Comment by maddygriz** [comment]
Hi Vince, We have tested on macOS and we ran into some memory issues. The one mac on our team has a memory limit lower than the test OME-TIFF file so we couldn't run all the tests to completion. BiocCheck looked good and we removed the vdiffr tests since ggplot can reverse legends between mac and windows.

**Comment by vjcitn** [comment]
would you bump the version and push for a new build?  i am not sure what has happened with linux.

**Comment by maddygriz** [comment]
I am getting some weird package install errors that I have not seen before on the package builder. Last week, there was an error on the package `cli`, I couldn't find which dependency package used that but SpatialOmicsOveraly doesn't natively. Today's error is about `S4Vectors` not being installed. I did not recently add this package so it must be on the build machine side.

**Comment by maddygriz** [comment]
@vjcitn Hi Vince, I am getting lots of "package unavailable" errors in my build checks. I have sort of been following all the emails about this so I know there are issues on the backend but how should I proceed for this review? Good news is that it looks like RBioFormats is on the mac build now.

**Comment by vjcitn** [comment]
I don't think there's anything you need to do right now.  I will have another look tonight and we may come to closure.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/maddygriz.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SpatialOmicsOverlay")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SpatialOmicsOverlay

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
