### ISSUE TITLE
DifferentialRegulation

### ISSUE THREAD

**Issue by SimoneTiberi** [Bioconductor/Contributions#2611]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SimoneTiberi/DifferentialRegulation

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by SimoneTiberi** [comment]
Hi,
as today, the package is still quite preliminary: we lack a few elements (vignettes, tests, etc...) and there still are some ERRORS/Warnings.

Within a week, the package should be in a pretty definite form.

It's probably best if you can wait a few days before reviewing it.

Thanks,
Simone

**Comment by lshep** [comment]
We won't consider passing for pre-check and assigning a reviewer until those elements are in place.  Let us know when we should do a pre-check

**Comment by SimoneTiberi** [comment]
Thanks @lshep; that's great.

I'll send a message here when the package is ready to be reviewed (probably within a week).

**Comment by SimoneTiberi** [comment]
Hi @lshep (or maybe I'd tag @bioc-issue-bot?),
I sorted almost all issues; would you mind running Bioc checks?

There is still 1 issue with the external data, which is too big (and not yet documented!); this triggers a few warnings:
- package/data too big;
- examples and vignettes too slow.

In the next days, we'll reduce the size of the example data (and document it!), which will fix both issues.

Thanks!

**Comment by vjcitn** [comment]
@lshep shouldn't we close this?  i've visited twice trying to check .... then re-open when actually reviewable?

**Comment by vjcitn** [comment]
You really should not submit until the package passes BiocCheck on your systems and meets the requirements of the submission checklist.  We are not providing a "checking" service, we are reviewing the package once it meets the basic standards for submissions.  Part of the review is building and checking on all platforms, but it is your job to have the package passing before submission.

**Comment by SimoneTiberi** [comment]
Ok, I though the package could be reviewed with very minor issues (i.e., 2 WARNINGs related to 1 problem).
Thanks for the clarification.

I'll fix the issue mentioned above and re-send a message here.

**Comment by lshep** [comment]
```
Error in .precheck_filesize(wd) : files larger than 5Mb:
  /inst/extdata/alevin-fry/sample_2/alevin/geqc_counts.mtx
  /inst/extdata/alevin-fry/sample_2/alevin/quants_mat.mtx
```
We can not proceed until this is corrected

**Comment by SimoneTiberi** [comment]
Hi again,
in version 0.99.2, I changed the size of the internal data, which solves the 2 issues mentioned above (size and time).

On my mac, the package builds, installs and gives no errors or warnings (both check and BiocCheck).

Do you think it can be reviewed?
It'd be helpful for me to see if there are errors/warnings on other OS that I don't see on my mac.

One thing I know is still missing is the description of the internal data (in `inst/script/extdata.Rmd`): I'll add it asap (probably tomorrow).

Thanks,
Simone

**Comment by lshep** [comment]
I will attempt to process again to be assigned a reviewer.  Cheers

**Comment by SimoneTiberi** [comment]
Thanks!

**Comment by SimoneTiberi** [comment]
Dear @vjcitn,
I do get this error:
```
* Checking valid files...
    * ERROR: System files found that should not be git tracked.
```

however I am struggling to identify the files that are causing the problem (not mentioned in the error).

Any ides what those files could be?

Thanks

**Comment by lshep** [comment]
@SimoneTiberi  http://contributions.bioconductor.org/gitignore.html

**Comment by SimoneTiberi** [comment]
Thanks @Ishep !

I had a .gitignore file, but apparently it was incomplete.

Thanks a lot again.

**Comment by SimoneTiberi** [comment]
Hi again @ishep, the problem seems to persist even after adding all `hidden_file_ext` to my `.gitignore`: https://github.com/SimoneTiberi/DifferentialRegulation/blob/master/.gitignore

Is there any way to identify the file which is being tracked?

I also checked all folders and can't see anything wrong.

2 possible issues (although I think both should be fine):
- I have an `.RData` object in the `data` folder: https://github.com/SimoneTiberi/DifferentialRegulation/tree/master/data
- I have various files (txt, mtx and mtx.gz formats) in `inst/extdata`: https://github.com/SimoneTiberi/DifferentialRegulation/tree/master/inst/extdata/alevin-fry

Thanks again

**Comment by lshep** [comment]
If you run the latest BiocCheck locally it should give you an output directory that would list the files; at least that is my understanding @LiNk-NY  .    
Also if they were already checked into git you would have to do a `git rm` on the file and commit that with a version bump to have the removed.  
Hope that helps

**Comment by LiNk-NY** [comment]
Not by default. I am working on showing the output but for now you can do: 
```r
bc <- BiocCheck::BiocCheckGitClone()
bc$error
#' $checkBadFiles
#' $checkBadFiles[[1]]
#' [1] "* ERROR: System files found that should not be git tracked."

#' $checkBadFiles[[2]]
#' [1] "data/DF_cell_types.RData"
```

**Comment by lshep** [comment]
@LiNk-NY  This seems like a false positive since its a data file ?

**Comment by LiNk-NY** [comment]
@lshep 
No, we don't want RData files in there. See this issue: https://github.com/Bioconductor/BiocCheck/issues/155

**Comment by LiNk-NY** [comment]
@SimoneTiberi 
See `?usethis::use_data`

**Comment by SimoneTiberi** [comment]
Thank you both for the explanation.

Actually, `BiocCheck` gives no errors or warnings.

Indeed `BiocCheckGitClone` gives an error, but doesn't say what file should not be tracked.

```
bc <- BiocCheck::BiocCheckGitClone()
bc
$error
[1] "System Files found that should not be git tracked:" 
```

Can I replace the `.RData` file with an `.RDS` object?
Otherwise I'll store the file in a txt in extdata.

Thank you both again

**Comment by SimoneTiberi** [comment]
Oh you just replied to my question; ok great, I'll use `usethis::use_data`, thanks!

**Comment by LiNk-NY** [comment]
> Actually, `BiocCheck` gives no errors or warnings.
> 
> Indeed `BiocCheckGitClone` gives an error, but doesn't say what file should not be tracked.
> 
> ```
> bc <- BiocCheck::BiocCheckGitClone()
> bc
> $error
> [1] "System Files found that should not be git tracked:" 
> ```


Make sure you have version `1.31.36` or greater. 
```r
packageVersion("BiocCheck")
#' [1] '1.31.37'
```

**Comment by SimoneTiberi** [comment]
I removed the `.RData` object (and created a small .txt file in `extdata` instead).

Let's see if this solved the error.

**Comment by SimoneTiberi** [comment]
Ok, issue solved.
Thanks a lot again @LiNk-NY and @lshep!

@vjcitn, the errors/warnings above were sorted, and I don't plan any new edits, so I think the package is ready to be checked.
Let me know if you have comments or questions about the package.

Thank you all again for your work

**Comment by SimoneTiberi** [comment]
Hi all, hi @vjcitn @lshep and @LiNk-NY,
apologies in advance for the pressure, but I see today is the "Last day to commit changes to the Bioc 3.15 branch".

I think the package actually respects all Bioc requirements; would anyone be willing to give it a quick look?

Thanks in advance,
Simone

**Comment by vjcitn** [comment]
The vignette starts off with (in introduction)
```
DifferentialRegulation is …
```
literally.

**Comment by vjcitn** [comment]
The vignette concludes with
```
# sort results by significance:
results_EC = results_EC[ order(results_EC$p_val), ]
# visualize head of results:
head(results_EC)
```
again literally.  The results are not disclosed.  Is this your intention?

**Comment by vjcitn** [comment]
The eval=FALSE may save you time but don't you want to convey the output to the reader?

**Comment by SimoneTiberi** [comment]
Dear Vince @vjcitn ,
thanks for taking a look at the package.

Actually, those 2 issues were solved some time ago and are not present in the latest version; see: https://github.com/SimoneTiberi/DifferentialRegulation/blob/master/vignettes/DifferentialRegulation.Rmd

I am a bit confused: are you seeing Version: 0.99.7 ?
Wasn't the latest vignettes propagated to the Bioc version of the package?

**Comment by vjcitn** [comment]
OK, this seems to be my problem.
```
PC002284:DifferentialRegulation vincentcarey$ git pull
Your configuration specifies to merge with the ref 'refs/heads/main'
from the remote, but no such ref was fetched.
PC002284:DifferentialRegulation vincentcarey$ vi DE*
```
I was able to get 0.99.7 in another folder and I will have a look now.

**Comment by SimoneTiberi** [comment]
Oh, thanks for spotting this.

**Comment by vjcitn** [comment]
I ran CMD check and had no problem;  `Tiberi S (????)` shows up in the vignette and might be ameliorated if you put a date in your DESCRIPTION.

**Comment by vjcitn** [comment]
I ran CMD check and had no problem;  `Tiberi S (????)` shows up in the vignette and might be ameliorated if you put a date in your DESCRIPTION.

**Comment by SimoneTiberi** [comment]
Ah ok; I though the date field was automatically added once in Bioconductor.
E.g., other Bioc packages like `muscat` don't have a date: https://github.com/HelenaLC/muscat/blob/master/DESCRIPTION

If this is not the case, sure I can just add a date and update.

P.s., Thanks for the review!

**Comment by SimoneTiberi** [comment]
@vjcitn, just to clarify: are you waiting for me to add a date on the DESCRIPTION?

I was waiting for you to confirm if/that it's necessary, but maybe we're waiting for each other...

Thanks

**Comment by SimoneTiberi** [comment]
Thanks @vjcitn for taking the time to review my package.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SimoneTiberi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DifferentialRegulation")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DifferentialRegulation

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
