### ISSUE TITLE
BiocUtils

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/Contributions#2617]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/BiocUtils

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```
--- re-building ‘BiocUtils.Rmd’ using rmarkdown
Quitting from lines 39-42 (BiocUtils.Rmd) 
Error: processing vignette 'BiocUtils.Rmd' failed with diagnostics:
could not find function "isTRUEorFALSE"
```
is my R too old?

**Comment by LiNk-NY** [comment]
@vjcitn 
My mistake. I forgot to load the package in the vignette :sweat_smile: 
It should be updated now.

**Comment by ococrook** [comment]
@LiNk-NY Could you remove the `ERROR` and then I can review the package?

**Comment by hpages** [comment]
I'd like to propose the 3 following changes:
- Name the package **BiocInternalUtils** instead of **BiocUtils**. No end user should ever need to use anything from the package directly so it doesn't matter how long and ugly its name is :wink: I just want to avoid any misconception that the package provides user-oriented utility functions.
- I know that we normally recommend camelCase style for function names but, again, since functions like `replaceSlots` are not meant to be seen by the end user, we can do what we want. In my own packages I started to use snake_case for those things that are meant to be used inside package code only, and I like it. It carries meaning so is totally worth the unconventional approach of using a dual naming-style.
-  The name `replace_slots` is ok I guess, although I think I have a small preference for `set_slots` for more consistency with our getter/setter terminology.

Sorry for nitpicking with names and naming style but as we all know naming is important and one of the 2 hardest things in Computer Science :wink: 

H.

**Comment by ococrook** [comment]
@hpages Did you want me to look at the package as well?

**Comment by hpages** [comment]
@ococrook Yes please. I was just chiming in but I'm not reviewing the package.

**Comment by ococrook** [comment]
@LiNk-NY, the review will be completed tomorrow

**Comment by ococrook** [comment]
Okay this looks pretty good to me! Thank you

# BiocUtils

- [ ] Agree with Herves the package would better be called BiocInternalUtils

# NEWS.md

- [ ] The version should match the package version

# Readme.md

- [ ] A readme explaining the purpose of the package and how to install the package using bioconductor instructions would be useful.

- [ ] It would also be helpful to add a section on contributions that are acceptable to this package

# Vignettes

- [ ] The vignette could use an introduction section explain the premise of the package.

# documentation

- [ ] I'm not quite sure what a zero character is, do you mean an empty string?

**Comment by LiNk-NY** [comment]
Thank you Hervé and Oliver for your valuable feedback.

> # BiocUtils
> * [x]  Agree with Herves the package would better be called BiocInternalUtils

I've decided to rename the package to `BiocDevelUtils` as it makes it clear that these functions are aimed for developers. Though I can see how the package could be named `BiocInternalUtils`, I relate the 'internal' term to mainly un-exported functions.

> # NEWS.md
> * [x]  The version should match the package version

This has been updated to the anticipated release version. 

> # Readme.md
> * [x]  A readme explaining the purpose of the package and how to install the package using bioconductor instructions would be useful.
> * [x]  It would also be helpful to add a section on contributions that are acceptable to this package
> 
> # Vignettes
> * [x]  The vignette could use an introduction section explain the premise of the package.
> 
> # documentation
> * [x]  I'm not quite sure what a zero character is, do you mean an empty string?

I've made this more clear by including an `nchar` example. 

I will close this issue and open a new one with the package name.

**Comment by LiNk-NY** [comment]
New issue is at #2634
