### ISSUE TITLE
zenith - try3

### ISSUE THREAD

**Issue by GabrielHoffman** [Bioconductor/Contributions#2630]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DiseaseNeuroGenomics/zenith/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
vignette takes unreasonably long to build.  please make sure it builds within 5 minutes, preferably much less.

**Comment by GabrielHoffman** [comment]
The new version (v0.99.1) runs in 3 minutes on my machine.  If that is still an issue, I'll have to rewrite the vignette

**Comment by vjcitn** [comment]
kableExtra and recount are missing from DESCRIPTION, probably need to be in Suggests

**Comment by vjcitn** [comment]
The vignette is pretty terse.  Consider a new user coming to it.  The vignette took 16 minutes on a nontrivial machine.  Is this because data are being cached?   Is it a one-time charge?

**Comment by LiNk-NY** [comment]
Hi Gabriel, @GabrielHoffman 
Please respond to the items below. 
Best,
Marcel

---

# zenith #2630

* Please fix the timeout before the review can continue.
* Respond to the comments appropriately, i.e., add `recount` and `kableExtra`
to the `Suggests` field in the `DESCRIPTION`
* Remove the `docs` folder from the Git repository. This is generated when the package is built.

**Comment by GabrielHoffman** [comment]
Based on your feedback, I need to restructure the vignette both in terms of runtime and user-facing documentation.  This is a substantial amount of work, and I haven't gotten back to it yet.

Thanks for your patience

Best,
Gabriel

**Comment by GabrielHoffman** [comment]
I updated the package in commit [b0a6999](https://github.com/GabrielHoffman/zenith/commit/b0a6999b04328da2a2fe24c84158d5992af78cf9) to address these issues

Gabriel

**Comment by GabrielHoffman** [comment]
@LiNk-NY I'm following up on this.  How do I get my new version in the testing queue?

Best,
Gabriel

**Comment by vjcitn** [comment]
You'll need to bump the version number in DESCRIPTION, and push to git@git.bioconductor.org:packages/zenith

**Comment by vjcitn** [comment]
The last commit I see there is from April 8.

**Comment by GabrielHoffman** [comment]
I understand part of the issue.  In the previous round, you pulled my code from my GitHub repo.  Now I'm trying to push to the Bioconductor repo, but I don't have permission.  

Is this an issue on my end or yours?

```sh 
glia:zenith> git remote -v
origin	https://git.bioconductor.org/packages/zenith (fetch)
origin	https://git.bioconductor.org/packages/zenith (push)
```

```sh
glia:zenith> git push --set-upstream origin master 
FATAL: W any packages/zenith g.hoffman DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Thanks,
Gabriel

**Comment by vjcitn** [comment]
See point 13 at https://contributions.bioconductor.org/git-version-control.html#faq

**Comment by GabrielHoffman** [comment]
It still doesn't work with SSH:
```r
glia:zenith> git remote -v
origin	git@git.bioconductor.org:packages/zenith (fetch)
origin	git@git.bioconductor.org:packages/zenith (push)
```

I don't have write permission for the `zenith` package, but I do for my `variancePartition` package 
```sh
glia:zenith> ssh -T git@git.bioconductor.org | grep "zenith\|variancePartition"
 R W	packages/variancePartition
 R  	packages/zenith
```

**Comment by vjcitn** [comment]
are you using different identities?  @nturaga

**Comment by nturaga** [comment]
@GabrielHoffman 

You have 3 keys in our system associated with the email: `gabriel.hoffman@mssm.edu`. You must not be using the correct keys. 

please check.

Best,

**Comment by GabrielHoffman** [comment]
I checked my Bioconductor credentials and it has my public key correct.  I also ran the ssh permission check on a different machine (Ubuntu vs OS X), and I get the same results.     

I'm concerned that you pushed the original zenith version to Bioconductor, so it is still under your ownership.  

What else can I try?

Gabriel

**Comment by nturaga** [comment]
I'm not sure by what you mean here? 

```
I'm concerned that you pushed the original zenith version to Bioconductor, so it is still under your ownership.
```

Can you try https://contributions.bioconductor.org/git-version-control.html#faq #15?

Another thing is, I would like to see which public key you think you are using? Can you check the public key and post it here? 

You can pass a specific key by using 

```
ssh -i <key> -T git@git.bioconductor.org
```

**Comment by GabrielHoffman** [comment]
1) Bioc Credentials Web App:
```
BiocCredentials
'gabriel.hoffman@mssm.edu' has access to the following packages:
variancePartition
```

2) My Public Key
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRG45efNPJbwq2cVJ/+YiAyLHAbWvCI0O4JGGAft2aw5jlAYU/s/zVOJxhFHw2zn05P4Sqyt+OxIKbcv8eDqEl9DF+qyRAzw7ibuHbPmtuYwv9eGrNTMrjEM8qjKRQa2dDml/tukfs+3h6mfR78m/k15EIWBOCfpvT2C6aMka3xWpu2IPqkZqt7RkJchh8hPttiNgmuwEbKROyeLxZ/UAE5tBayQAcK7SrVRyMPfy23Fq7Z1k5kBtcHPGRU5x2UbkoBPQHQCQf+PrmzgVnug++ZImquL4fyUsUrnay7rhMfocZ3iQvmS2yWkM8iH78/maH/dm7eAo0O85lm2EHPqCWVXultRqjBuFrrkugbjdyyGHrNPDVH1u2aRytQTPZEbhLt0eB0hCLiiQOCPSTHFdxoZyCATYx2E92Aa2mwuMP6oW6AiETcY9JW9pczJohSmSngq8wvNG+OTkIHZZGHz7en4UfdZGExkNn08CNR++QoyWFR6nPGtaIu4CynILno1k= gabriel.hoffman@mssm.edu
```

3) My ssh config file
```
host git.bioconductor.org
     HostName git.bioconductor.org
     IdentityFile ~/.ssh/id_rsa
     User git
```

Based on point 1, I suspect that my account doesn't have access to the `zenith` package.  I think its not a login issue.  Can you check who has write access to that project on your end?

Thanks for your patience,
Gabriel

**Comment by nturaga** [comment]
I would suggest using a new key.

Create a new key, and add to BiocCredentials.

Try that.

There is nothing wrong on our end.

**Comment by GabrielHoffman** [comment]
1) New key 
```sh
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVRY2XQMQxXB/oCMc8yyS4/PZp5ZQU6d7SHZaz3cPvNXM6CYvivikri5UCwbjOsTIc/OeXDQ+KOt/EjuUOWxmI5m2Kcqvr8Tsw+XJVI7KlknBpv4lqZYWBIESpxS7BygdfYrYtsBcU/oCg9cPqtLIgFgZl8XZg3pvvr7cw2mnIFeo5SzK8L7TCsaNfQDK4ZN2G0azGTTmxgKYk/dheCKtdFYjmuCWX0KG/s7+AzT7bCmBPM8gq5sm4BwZrvJpoOvucCn///AcCoqSdsyKYy6H7KgobpolBX1SrRFGnne0GL6bEX136SxJwfAv2B6gTM/0ZUTCWW5mwnQY2nar9LG1ZXnJ7rzVHLrThpxUUSYOVDxR81ibtKnjy5cC5nU5ET51neqj36MVwWNiVT+0KBDACsQ9CIRRSYclOKQoci4WLgDoiYdpedScnvEQjC5/5BTnIQf3hOrTvZA97mequ0tnOPXWap9PkJWA/tjWNF2mBLMCgUbTb4IIzkhsu79EiUTCFdDCbsGBf5VeKBczhavsCMkIklci+kwmaPBNVBcKzUg0a/ohZJNuEd3EUiqmhFOCgE/AOhVuh53lO98JCkdKA+/QqA7frYscIRaRs0it6wIVZg8+PWq2XuzXR1Me06xMmKCtGmkQHLVcSQB+EM3UbPTsD0Denx219FBqRWz/LYQ== gabrielhoffman@glia.local
```

Still no permission
```r 
glia:zenith> ssh -i ~/.ssh/id_rsa_bioc -T git@git.bioconductor.org | grep "zenith\|variancePartition"
 R W	packages/variancePartition
 R  	packages/zenith
```

2) The Bioconductor Git Credentials App does not show permission for `zenith`, and that should be independent of the login issue, right?

<img width="910" alt="Screen Shot 2022-05-17 at 2 33 19 PM" src="https://user-images.githubusercontent.com/13241293/168885565-4b21ef84-f048-4a6c-9119-490506cda9f5.png">

**Comment by GabrielHoffman** [comment]
Do you have any other suggestions on this, I don't know what else to try on my end

**Comment by nturaga** [comment]
Can you actually access `variancePartition` ? Can you try to update the "patch" number of the version numbers? (i.e `x.y.z`, do `x.y.z+1`)

**Comment by GabrielHoffman** [comment]
I just pushed an update to the devel (i.e.`master`) of variancePartition:

```sh
glia:variancePartition> git push origin
Enumerating objects: 28, done.
Counting objects: 100% (24/24), done.
Delta compression using up to 8 threads
Compressing objects: 100% (16/16), done.
Writing objects: 100% (16/16), 1.62 KiB | 1.62 MiB/s, done.
Total 16 (delta 12), reused 0 (delta 0)
To git.bioconductor.org:packages/variancePartition
   0c4a8fa..730735f  master -> master
```

**Comment by nturaga** [comment]
From what I see on my end, you have access to the package (zenith), I'm not sure anymore what could possibly be wrong on our end, sorry. Can you add a `-v` at the end of the command for a verbose output? I'd like to look at the output. 

It could be because you have an alternative name added "GabrielHoffman" vs "g.hoffman". But I deleted one of them now.

**Comment by GabrielHoffman** [comment]
It just worked:

```sh 
glia:zenith> git push origin  
Enumerating objects: 49, done.
Counting objects: 100% (49/49), done.
Delta compression using up to 8 threads
Compressing objects: 100% (34/34), done.
Writing objects: 100% (35/35), 11.14 KiB | 3.71 MiB/s, done.
Total 35 (delta 20), reused 0 (delta 0)
To git.bioconductor.org:packages/zenith.git
   fc16467..dd37b45  master -> master
```

It seems like you fixed it.  That was strange.  Thanks!  Do you know if this was an issue on my end or your end?  

I confirmed that permission are good:

```sh
glia:zenith>  ssh -i ~/.ssh/id_rsa_bioc -T git@git.bioconductor.org | grep "zenith\|variancePartition"
 R W	packages/variancePartition
 R W	packages/zenith
```

**Comment by nturaga** [comment]
So it seems you've had two BiocCredentials accounts: one as g.hoffman and the other as GabrielHoffman. I deleted one. It's very strange that you've gotten two entries! I wonder how that happened when you submitted your package.

**Comment by LiNk-NY** [comment]
Hi Gabriel, @GabrielHoffman 
Please see the review below. 
Best, 
Marcel

---

# zenith #2630

* Respond to the comments appropriately, i.e., add `recount` and `kableExtra`
to the `Suggests` field in the `DESCRIPTION`
* (Optional) Use `<-` assignment operator instead of `=` for clarity.
* Consider wrapping text to a max of 80 character width for readability and
maintenance.

## DESCRIPTION

* Looks good.

## NAMESPACE

* Consider using camelCase naming consistently, e.g., for `zenith_gsa`.

## vignettes

* If possible, avoid examples with legacy data structures such as
`ExpressionSet` in `zenith.Rmd`.
* Remove `knitr::knit_exit` calls from the vignette. If you have extra code,
you can include it under `/inst/scripts` etc.

## R

* Remove or uncomment commented code, e.g., `aggregate_GO_offspring`
* Avoid nested `lapply` where possible, esp. if the subsequent procedure is to
`unlist`.
* It's more straightforward to create a plain function rather than a method for
an external class (`recodeToList,GeneSetCollection-method`).

**Comment by GabrielHoffman** [comment]
I have address the issues in the following commit: 

# zenith
- I have added `kableExtra` and removed the need for `recount`
- changing from `=` to `<-` too much work at this point, and risks breaking the code
- same with forcing text wraping 

# NAMESPACE
- Other users already depend on this package, so I'd really like to avoid changing function names unless it is absolutely essential

# vignettes
- I only use `ExpressionSet` to load a very small example dataset. It is not used otherwise.
- removed `knitr::knit_exit()`
# R
- removed `aggregate_GO_offspring`
- recoded nested `lapply` call
- I agree with your comment about `recodeToList,GeneSetCollection-method` in general.  But I am writing another package that imports this one and defines `recodeToList` for another class.  So this uses the class-specific function definition

**Comment by LiNk-NY** [comment]
> * changing from `=` to `<-` too much work at this point, and risks breaking the code
> * same with forcing text wraping

I disagree but it is really a matter of style choice even though it impacts legibility.

> * Other users already depend on this package, so I'd really like to avoid changing function names unless it is absolutely essential
 
The package from our viewpoint is in the beta stage and we don't expect them to have a significant user base. 
Changes to function names are normal to the review process. If more convenient, you can leave them as is. 

> * I agree with your comment about `recodeToList,GeneSetCollection-method` in general.  But I am writing another package that imports this one and defines `recodeToList` for another class.  So this uses the class-specific function definition

Please remove this method and generic. The operation in the package can be replaced with: 

```r
geneIds(gsc)
```

**Comment by GabrielHoffman** [comment]
Thanks for your comments.  I have a question about the last one.

I'm not clear on your suggestion to replace `zenith::recodeToList()` with `GSEABase::geneIds()`.  I need a function to do the following:

```r
library(zenith)

# load Hallmark gene sets
gs = get_MSigDB('H')

# recode GeneSetCollection as a list
gs.list = recodeToList(gs)

# show first entries for first 4 gene sets
lapply(gs.list[1:4], head)
#> $M5890_HALLMARK_TNFA_SIGNALING_VIA_NFKB
#> [1] "ENSG00000165029" "ENSG00000144476" "ENSG00000109321" "ENSG00000162772"
#> [5] "ENSG00000070961" "ENSG00000086062"
#> 
#> $M5891_HALLMARK_HYPOXIA
#> [1] "ENSG00000144476" "ENSG00000148926" "ENSG00000170425" "ENSG00000162433"
#> [5] "ENSG00000131016" "ENSG00000149925"
#> 
#> $M5892_HALLMARK_CHOLESTEROL_HOMEOSTASIS
#> [1] "ENSG00000107331" "ENSG00000120437" "ENSG00000131069" "ENSG00000184009"
#> [5] "ENSG00000198099" "ENSG00000170017"
#> 
#> $M5893_HALLMARK_MITOTIC_SPINDLE
#> [1] "ENSG00000136754" "ENSG00000097007" "ENSG00000159842" "ENSG00000276016"
#> [5] "ENSG00000278741" "ENSG00000130402"
```

and `geneIds()` doesn't give this result.  Is there a better way to get this result than the current version of `zenith::recodeToList()`?

Best,
Gabriel

**Comment by LiNk-NY** [comment]
Hi Gabriel, @GabrielHoffman 

Perhaps I'm missing something but this does work with the example you've provided. 

Consider the following: 

```r
identical(
    lapply(gs.list[1:4], head), 
    lapply(GSEABase::geneIds(gs)[1:4], head)
)
#' [1] TRUE
```

Best regards,
Marcel

**Comment by GabrielHoffman** [comment]
Hi Marcel, 
Thanks for your quick response!  You are right, I'm not sure how I missed that before.  I'll make the fix next week.

Cheers,
Gabriel

**Comment by GabrielHoffman** [comment]
Fixed in commit above

Thanks,
Gabriel

**Comment by LiNk-NY** [comment]
Hi Gabriel, @GabrielHoffman 

Sorry for the delay. 

Please remove the `docs` folder from the package. 
Note that the `pkgdown` products can go onto a separate branch. 

To use GitHub Actions, see `biocthis::use_bioc_github_action` with the `biocthis.pkgdown` option enabled.

Best,
Marcel

**Comment by GabrielHoffman** [comment]
@LiNk-NY Done.  Confirm?

**Comment by LiNk-NY** [comment]
@GabrielHoffman

I still see the docs folder here: https://github.com/DiseaseNeuroGenomics/zenith/tree/master/docs
I see that you removed the `docs` folder from the Bioc repo. 
Eventually, both the Bioconductor repository and GH repo will have to be synced. 
It will cause problems down the road. Please remove the `docs` folder from all copies and 
use a GH Action as above to generate the website. 

Best,
Marcel

**Comment by GabrielHoffman** [comment]
@LiNk-NY done

**Comment by LiNk-NY** [comment]
Thank you for your submission!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GabrielHoffman.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("zenith")`. The package 'landing page' will be created at

https://bioconductor.org/packages/zenith

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
