### ISSUE TITLE
BiocDevelUtils

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/Contributions#2634]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/BiocDevelUtils

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
This is a continuation of #2617

cc: @ococrook @hpages

**Comment by ococrook** [comment]
@lshep This package has been reviewied in another issue, but we thought a name change was in benifical. I'm happy with this package.

@hpages  suggested that `replaceSlots` be renamed `set_slots`. What do you think @LiNk-NY @lshep ? Ithink I'd rather the names be consistent within the package but can sympathise with the suggestion.

@LiNk-NY I'm happy with the revision. Remember the version in the description file and the news.md will need to match at release, else they'll get out of sync quite quickly.

**Comment by LiNk-NY** [comment]
@ococrook 

> @hpages suggested that `replaceSlots` be renamed `set_slots`. What do you think @LiNk-NY @lshep ? Ithink I'd rather the names be consistent within the package but can sympathise with the suggestion.

This is a tough one, I think quite a few developers have been using `replaceSlots` for quite some time now: 
https://code.bioconductor.org/search/search?q=replaceSlots
Perhaps we can export both :thinking: 
snake_case is quite associated with S3 so I'd rather stick to camelCase :)
 
> @LiNk-NY I'm happy with the revision. Remember the version in the description file and the news.md will need to match at release, else they'll get out of sync quite quickly.

Yes, the package version at release will be `1.0.0`. 

Best,
Marcel

**Comment by hpages** [comment]
The new name "BiocDevelUtils" strongly suggests another package like **codetoolsBioC** or **devtools**, that is, a package that provides tools that the developer actively uses during the development of their package or as part of the maintenance workflow. This kind of developer tools don't need to be a dependency of the final package. It would be strange to see that **GenomicRanges** or **SummarizedExperiment** depend on something like **codetoolsBioC** or **BiocDevelUtils**.

`BiocDevelUtils::replaceSlots` is a new function that is meant to replace `BiocGenerics:::replaceSlots`. Whether it uses the same name as the original or not doesn't matter. Code that uses the old function will need to be modified to use the new function anyways.

`is01character` is quite cryptic. No idea what it does.

For most people, `isSingleCharacter` is asking if the supplied value is a single letter. But that's not what the function is asking, unfortunately.

I would still recommend to use snake_case for these low-level utilities.

Thanks,
H.

**Comment by LiNk-NY** [comment]
> The new name "BiocDevelUtils" strongly suggests another package like **codetoolsBioC** or **devtools**, that is, a package that provides tools that the developer actively uses during the development of their package or as part of the maintenance workflow. This kind of developer tools don't need to be a dependency of the final package. It would be strange to see that **GenomicRanges** or **SummarizedExperiment** depend on something like **codetoolsBioC** or **BiocDevelUtils**.
 
The use case of the package is to have other packages depend on the functionality in an attempt to wrangle all the helper functions that have been written and re-written numerous times. I don't see why `GenomicRanges` or `SummarizedExperiment` couldn't depend on `BiocDevelUtils` as long as the functionality in the package is well tested and maintained. Perhaps the name here is a bit difficult to pin down and the general `BiocUtils` name may have been sufficient. It would be good to have additional opinions on this.   

> `BiocDevelUtils::replaceSlots` is a new function that is meant to replace `BiocGenerics:::replaceSlots`. Whether it uses the same name as the original or not doesn't matter. Code that uses the old function will need to be modified to use the new function anyways.

Given that it provides the same functionality, I thought it would be appropriate to keep the name the same. Changing it to `setSlots` makes it harder to find. Perhaps using a `replaceSlots` alias would be good enough in the docs. (updated)

> 
> `is01character` is quite cryptic. No idea what it does.
> 

It checks for character vectors of length 0 or 1 with available exceptions for zero length and `NA` inputs. I added a blurb about it in the documentation. 

> For most people, `isSingleCharacter` is asking if the supplied value is a single letter. But that's not what the function is asking, unfortunately.

In R, `character` (type) means a vector so I do not think this is incorrect. We don't really subset individual words and check for the number of individual characters that compose a word like in python `"word"[0]` and `identical(nchar(x), 1L)` performs that test nicely.

**Comment by hpages** [comment]
> I don't see why GenomicRanges or SummarizedExperiment couldn't depend on BiocDevelUtils as long as the functionality in the package is well tested and maintained.

I didn't say that GenomicRanges or SummarizedExperiment couldn't depend on BiocDevelUtils. I said it would be a _strange_ thing to see given that the name of the package suggests that it's yet another addition to the already [huge family of packages meant to help with R package development](https://github.com/IndrajeetPatil/awesome-r-pkgtools). Like it would be a strange thing to see that GenomicRanges depends on codetoolsBioC just because I used the latter at some point to perform some static code analysis.

I think it's important to choose a name that doesn't suggest something that the package isn't. It has nothing to do with being "well tested and maintained".

> Perhaps using a replaceSlots alias would be good enough in the docs. (updated)

Sounds good to me. We'll probably replace all the calls to `BiocGenerics:::replaceSlots` with calls to `setSlots` in all software packages ourselves so this is a non-issue.

> In R, character (type) means a vector so I do not think this is incorrect. 

Again, it's not about correctness, it's about choosing names that are readable and reflect functionality. I do not think that `isSingleCharacter` does that.

> It (`is01character`) checks for character vectors of length 0 or 1 with available exceptions for zero length and NA inputs.

I see. But this name is inconsistent with all the `isSingle*` functions.

We need to get the naming right before these functions start being used in hundreds or thousands of places :wink:

H.

**Comment by LiNk-NY** [comment]
Thanks Hervé @hpages for clarifying.

I think `BiocInternals` is not too long or ugly :wink: 

The comment about "well tested and maintained" refers to the reliability of the underlying software which is what we want when we introduce a wedge-like package such as this one. 

> > In R, character (type) means a vector so I do not think this is incorrect.
> 
> Again, it's not about correctness, it's about choosing names that are readable and reflect functionality. I do not think that `isSingleCharacter` does that.

I have seen the `scalar` term used. Perhaps this is a better naming convention? E.g., `isScalarCharacter`

Thoughts?

cc: @mtmorgan

**Comment by hpages** [comment]
Well if **BiocInternals** is the best I can hope for then why not. Better than **BiocUtils** or **BiocDevelUtils**. I wish we could draw the line for what kind of "internals" go in the package, hopefully only low-level stuff (often called _utilities_ :wink:) and not too high-level things, but it sounds like I'm asking too much so I'll leave it there.

What about `isSingleString`? Anybody coming from any programming language understands what a "single string" is. If you go for `isScalarCharacter`, you also need to rename all the other `isSingle*` functions -> `isScalar*`.

H.

**Comment by LiNk-NY** [comment]
After some "internal" discussion :grin: , the word "internal" seems to imply that this package is intended for the Bioc-core which it is not. Since the package can contain both utilities and internals, we should probably name the package based on the target audience `BiocDeveloper` (a package meant for developers). Apologies for the back and forth!

Renaming those functions is not too much of a hurdle. I'd like to opt for the R-centric approach, so that the language is consistent with the documentation. We can note, as you said, that in other languages these are called 'strings' in the documentation. 

Best,
Marcel

**Comment by LiNk-NY** [comment]
#2640
