### ISSUE TITLE
RgnTX

### ISSUE THREAD

**Issue by yue-wang-biomath** [Bioconductor/Contributions#2635]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/yue-wang-biomath/RgnTX

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by yue-wang-biomath** [comment]
Thanks for your reminding. Now I have subscribed to the bioc-devel mailing list with the email m18896977776@163.com, which is the maintainer email stated in the DESCRIPTION. Please kindly check this.

**Comment by lshep** [comment]
Please push a version bump in the package to trigger the new build so it is checked automatically

**Comment by jianhong** [comment]
# Package 'RgnTX' Review
The package passed check and build. It is in pretty good shape. I like the informative documentation. Well done. However there are several things need to be fixed.

## The DESCRIPTION file
- [ ] R version should be no less than 4.2

## The NAMESPACE file
- [ ] Important: Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 30 import(ggplot2)

## R code
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development.
	* In file R/globals.R:
	    + at line 1 found 'utils::globalVariables(c("x", "vx", "vy", "..density..", "txdb"))'
- [ ] Important: Use `file.path` or proper code style to replace hard coding
	* In file vignettes/RgnTX.Rmd:
	    + at line 288 found 'file <- system.file(package="RgnTX", "extdata/m6A_sites_data.rds")' can be replaced as 'file <- system.file(package="RgnTX", "extdata", "m6A_sites_data.rds")'
	    + at line 443 found 'file <- system.file(package="RgnTX", "extdata/m6A_sites_data.rds")'
	    + at line 633 found 'file <- system.file(package="RgnTX", "extdata/m6A_sites_data.rds")'
- [ ] Important: `message()`, `message`, `stop` instead of `cat` and `print` outside of `show` methods.
    * In file R/overlapCountsTx.R:
        + at line 63 found '                print("Either A or B does not provide transcript id information. Their overlapping is counted at genome level rather than transcriptome")'
- [ ] NOTE: Avoid 'suppressWarnings'/'*Messages' if possible
    * In file R/distanceTx.R:
        + at line 57 found '    suppressWarnings('
    * In file R/overlapCountsTx.R:
        + at line 52 found '    suppressWarnings('
    * In file R/overlapCountsTxIA.R:
        + at line 66 found '    suppressWarnings('
    * In file R/overlapWidthTx.R:
        + at line 48 found '        suppressWarnings('
        + at line 55 found '        suppressWarnings('
        + at line 59 found '        suppressWarnings('
    * In file R/randomizeTransByOrder.R:
        + at line 35 found '    suppressWarnings('
- [ ] NOTE: Avoid using '=' for assignment and use '<-' instead
    * In file R/randomizeTransByOrder.R:
        + at line 38 found '    dist[dist <= 0] = 0'
        + at line 51-68 found '        dist.p = dist[p.index] ...'
        + at line 80-98 found '        dist.n = dist[n.index] ...'
    * In file R/shiftedZScoreTx.R:
        + at line 81 found '    shifted.z.scores[num.steps+1] = original.z.score'
- [ ] NOTE: Functional programming: code repetition.
	* repetition in `distanceTx` and `overlapCountsTx` and `overlapWidthTx`
		+ in distanceTx
			- line 2:{
			- line 3:    if (is(A, "GRangesList")) {
			- line 4:        A <- GRangesList2GRanges(A)
			- line 5:    }
			- line 6:    if (is(B, "GRangesList")) {
			- line 7:        B <- GRangesList2GRanges(B)
			- line 8:    }
			- line 9:    if (!is(A, "GRanges")) {
			- line 10:        stop("A should be either GRanges or GRangesList.")
			- line 11:    }
			- line 12:    if (!is(B, "GRanges")) {
			- line 13:        stop("B should be either GRanges or GRangesList.")
			- line 14:    }
			- line 15:    if (length(A$group) == 0) {
			- line 16:        A$group <- seq_len(length(A))
			- line 17:    }
			- line 18:    if (length(B$group) == 0) {
			- line 19:        B$group <- seq_len(length(B))
			- line 20:    }
		+ in overlapCountsTx
			- line 2:{
			- line 3:    if (is(A, "GRangesList")) {
			- line 4:        A <- GRangesList2GRanges(A)
			- line 5:    }
			- line 6:    if (is(B, "GRangesList")) {
			- line 7:        B <- GRangesList2GRanges(B)
			- line 8:    }
			- line 9:    if (!is(A, "GRanges")) {
			- line 10:        stop("A should be either GRanges or GRangesList.")
			- line 11:    }
			- line 12:    if (!is(B, "GRanges")) {
			- line 13:        stop("B should be either GRanges or GRangesList.")
			- line 14:    }
			- line 15:    if (length(A$group) == 0) {
			- line 16:        A$group <- seq_len(length(A))
			- line 17:    }
			- line 18:    if (length(B$group) == 0) {
			- line 19:        B$group <- seq_len(length(B))
			- line 20:    }
		+ in overlapWidthTx
			- line 1:    B, ...) 
			- line 2:{
			- line 3:    if (is(A, "GRangesList")) {
			- line 4:        A <- GRangesList2GRanges(A)
			- line 5:    }
			- line 6:    if (is(B, "GRangesList")) {
			- line 7:        B <- GRangesList2GRanges(B)
			- line 8:    }
			- line 9:    if (!is(A, "GRanges")) {
			- line 10:        stop("A should be either GRanges or GRangesList.")
			- line 11:    }
			- line 12:    if (!is(B, "GRanges")) {
			- line 13:        stop("B should be either GRanges or GRangesList.")
			- line 14:    }
	* repetition in `getPermSpaceByType` and `GRanges2GRangesList`
		+ in getPermSpaceByType
			- line 34:            process1 <- paste0(x, ",")
			- line 35:            return(process1)
			- line 36:        })
			- line 37:        blockSizes <- unlist(blockSizes)
			- line 40:            process1 <- paste0(x, ",")
			- line 41:            return(process1)
			- line 42:        })
			- line 43:        targetStart <- unlist(targetStart)
			- line 44:        A.frags <- cbind(RefSeqID, targetName, strand, targetStart, 
			- line 45:            blockSizes)
			- line 46:        A.frags <- data.frame(A.frags)
			- line 47:        regions.A <- with(A.frags, makeGRangesListFromFeatureFragments(seqnames = targetName, 
			- line 48:            fragmentStarts = targetStart, fragmentWidths = blockSizes, 
			- line 49:            strand = strand))
		+ in GRanges2GRangesList
			- line 35:        process5 <- paste0(process4, ",")
			- line 36:        return(process5)
			- line 37:    })
			- line 38:    targetStart <- unlist(targetStart)
			- line 48:        process5 <- paste0(process4, ",")
			- line 49:        return(process5)
			- line 50:    })
			- line 51:    blockSizes <- unlist(blockSizes)
			- line 52:    A.frags <- cbind(RefSeqID, targetName, strand, targetStart, 
			- line 53:        blockSizes)
			- line 54:    A.frags <- data.frame(A.frags)
			- line 55:    A.list <- with(A.frags, makeGRangesListFromFeatureFragments(seqnames = targetName, 
			- line 56:        fragmentStarts = targetStart, fragmentWidths = blockSizes, 
			- line 57:        strand = strand))
	* repetition in `getStopCodon` and `randomizeTransByOrder`
		+ in getStopCodon
			- line 20:            strand = "+")
			- line 21:    }
			- line 22:    else {
			- line 23:        R.p.l.exons <- c()
			- line 24:    }
			- line 33:            strand = "-")
			- line 34:    }
			- line 35:    else {
			- line 36:        R.n.l.exons <- c()
			- line 37:    }
			- line 54:    }
			- line 55:    else {
			- line 56:        R.p.r.exons <- c()
			- line 57:    }
			- line 67:    }
			- line 68:    else {
			- line 69:        R.n.r.exons <- c()
			- line 70:    }
		+ in randomizeTransByOrder
			- line 38:            strand = "+")
			- line 39:    }
			- line 40:    else {
			- line 41:        B.p.exons <- c()
			- line 42:    }
			- line 59:    }
			- line 60:    else {
			- line 61:        B.n.exons <- c()
			- line 62:    }
	* repetition in `permTestTx`, `permTestTx_customAll`,  `permTestTx_customPick` , `permTestTxIA`, `permTestTx_customAll` and `permTestTxIA_customPick`
		+ in permTestTx
			- line 6:    rand.ev <- lapply(RSL, function(x) {
			- line 7:        return(ev_function_2(RS2, x, ...))
			- line 8:    })
			- line 9:    rand.ev <- unlist(rand.ev)
			- line 10:    ntimes <- length(rand.ev)
			- line 11:    if (orig.ev < mean(rand.ev)) {
			- line 12:        zscore <- round((orig.ev - mean(rand.ev, na.rm = TRUE))/sd(rand.ev, 
			- line 13:            na.rm = TRUE), 4)
			- line 14:        xcoords <- rand.ev
			- line 15:        rand.mean <- mean(xcoords, na.rm = TRUE)
			- line 16:        rand.sd <- sd(xcoords, na.rm = TRUE)
			- line 17:        ntimes <- length(RSL)
			- line 18:        if (pval_z == FALSE) {
			- line 19:            pval <- (sum(orig.ev >= rand.ev, na.rm = TRUE) + 
			- line 20:                1)/(ntimes + 1)
			- line 21:        }
			- line 22:        else {
			- line 23:            pval <- pnorm(orig.ev, mean(rand.ev), sd(rand.ev), 
			- line 24:                lower.tail = FALSE)
			- line 25:        }
			- line 26:    }
			- line 27:    if (orig.ev >= mean(rand.ev)) {
			- line 28:        zscore <- round((orig.ev - mean(rand.ev, na.rm = TRUE))/sd(rand.ev, 
			- line 29:            na.rm = TRUE), 4)
			- line 30:        xcoords <- rand.ev
			- line 31:        rand.mean <- mean(xcoords, na.rm = TRUE)
			- line 32:        rand.sd <- sd(xcoords, na.rm = TRUE)
			- line 33:        ntimes <- length(RSL)
			- line 34:        if (pval_z == FALSE) {
			- line 35:            pval <- (sum(orig.ev <= rand.ev, na.rm = TRUE) + 
			- line 36:                1)/(ntimes + 1)
			- line 37:        }
			- line 38:        else {
			- line 39:            pval <- pnorm(orig.ev, mean(rand.ev), sd(rand.ev), 
			- line 40:                lower.tail = TRUE)
			- line 41:        }
			- line 42:    }
			- line 43:    pval <- round(pval, 6)
			- line 44:    permTestTx.results <- list(RSL, RS1, RS2, orig.ev, rand.ev, 
			- line 45:        pval, zscore, ntimes)
			- line 46:    names(permTestTx.results) <- c("RSL", "RS1", "RS2", "orig.ev", 
			- line 47:        "rand.ev", "pval", "zscore", "ntimes")
			- line 48:    class(permTestTx.results) <- "permTestTx.results"
			- line 49:    return(permTestTx.results)
		+ in permTestTx_customAll
			- line 5:    rand.ev <- lapply(RSL, function(x) {
			- line 6:        return(ev_function_2(RS2, x, ...))
			- line 7:    })
			- line 8:    rand.ev <- unlist(rand.ev)
			- line 9:    ntimes <- length(rand.ev)
			- line 10:    if (orig.ev < mean(rand.ev)) {
			- line 11:        zscore <- round((orig.ev - mean(rand.ev, na.rm = TRUE))/sd(rand.ev, 
			- line 12:            na.rm = TRUE), 4)
			- line 13:        xcoords <- rand.ev
			- line 14:        rand.mean <- mean(xcoords, na.rm = TRUE)
			- line 15:        rand.sd <- sd(xcoords, na.rm = TRUE)
			- line 16:        ntimes <- length(RSL)
			- line 17:        if (pval_z == FALSE) {
			- line 18:            pval <- (sum(orig.ev >= rand.ev, na.rm = TRUE) + 
			- line 19:                1)/(ntimes + 1)
			- line 20:        }
			- line 21:        else {
			- line 22:            pval <- pnorm(orig.ev, mean(rand.ev), sd(rand.ev), 
			- line 23:                lower.tail = FALSE)
			- line 24:        }
			- line 25:    }
			- line 26:    if (orig.ev >= mean(rand.ev)) {
			- line 27:        zscore <- round((orig.ev - mean(rand.ev, na.rm = TRUE))/sd(rand.ev, 
			- line 28:            na.rm = TRUE), 4)
			- line 29:        xcoords <- rand.ev
			- line 30:        rand.mean <- mean(xcoords, na.rm = TRUE)
			- line 31:        rand.sd <- sd(xcoords, na.rm = TRUE)
			- line 32:        ntimes <- length(RSL)
			- line 33:        if (pval_z == FALSE) {
			- line 34:            pval <- (sum(orig.ev <= rand.ev, na.rm = TRUE) + 
			- line 35:                1)/(ntimes + 1)
			- line 36:        }
			- line 37:        else {
			- line 38:            pval <- pnorm(orig.ev, mean(rand.ev), sd(rand.ev), 
			- line 39:                lower.tail = TRUE)
			- line 40:        }
			- line 41:    }
			- line 42:    pval <- round(pval, 6)
			- line 43:    permTestTx.results <- list(RSL, RS1, RS2, orig.ev, rand.ev, 
			- line 44:        pval, zscore, ntimes)
			- line 45:    names(permTestTx.results) <- c("RSL", "RS1", "RS2", "orig.ev", 
			- line 46:        "rand.ev", "pval", "zscore", "ntimes")
			- line 47:    class(permTestTx.results) <- "permTestTx.results"
			- line 48:    return(permTestTx.results)
		+ in permTestTxIA
			- line 1:    RS2 = NULL, txdb = NULL, type = "mature", ntimes = 50, ev_function_1 = overlapCountsTx, 
			- line 2:    ev_function_2 = overlapCountsTx, pval_z = FALSE, ...) 
			- line 3:{
			- line 4:    orig.ev <- ev_function_1(RS1, RS2, ...)
			- line 5:    RSL <- randomizeFeaturesTxIA(RS1, txdb, type, N = ntimes)
			- line 6:    rand.ev <- lapply(RSL, function(x) {
			- line 7:        return(ev_function_2(RS2, x, ...))
			- line 8:    })
			- line 9:    rand.ev <- unlist(rand.ev)
			- line 10:    ntimes <- length(rand.ev)
			- line 11:    if (orig.ev < mean(rand.ev)) {
			- line 12:        zscore <- round((orig.ev - mean(rand.ev, na.rm = TRUE))/sd(rand.ev, 
			- line 13:            na.rm = TRUE), 4)
			- line 14:        xcoords <- rand.ev
			- line 15:        rand.mean <- mean(xcoords, na.rm = TRUE)
			- line 16:        rand.sd <- sd(xcoords, na.rm = TRUE)
			- line 17:        ntimes <- length(RSL)
			- line 18:        if (pval_z == FALSE) {
			- line 19:            pval <- (sum(orig.ev >= rand.ev, na.rm = TRUE) + 
			- line 20:                1)/(ntimes + 1)
			- line 21:        }
			- line 22:        else {
			- line 23:            pval <- pnorm(orig.ev, mean(rand.ev), sd(rand.ev), 
			- line 24:                lower.tail = FALSE)
			- line 25:        }
			- line 26:    }
			- line 27:    if (orig.ev >= mean(rand.ev)) {
			- line 28:        zscore <- round((orig.ev - mean(rand.ev, na.rm = TRUE))/sd(rand.ev, 
			- line 29:            na.rm = TRUE), 4)
			- line 30:        xcoords <- rand.ev
			- line 31:        rand.mean <- mean(xcoords, na.rm = TRUE)
			- line 32:        rand.sd <- sd(xcoords, na.rm = TRUE)
			- line 33:        ntimes <- length(RSL)
			- line 34:        if (pval_z == FALSE) {
			- line 35:            pval <- (sum(orig.ev <= rand.ev, na.rm = TRUE) + 
			- line 36:                1)/(ntimes + 1)
			- line 37:        }
			- line 38:        else {
			- line 39:            pval <- pnorm(orig.ev, mean(rand.ev), sd(rand.ev), 
			- line 40:                lower.tail = TRUE)
			- line 41:        }
			- line 42:    }
			- line 43:    pval <- round(pval, 6)
			- line 44:    permTestTx.results <- list(RSL, RS1, RS2, orig.ev, rand.ev, 
			- line 45:        pval, zscore, ntimes)
			- line 46:    names(permTestTx.results) <- c("RSL", "RS1", "RS2", "orig.ev", 
			- line 47:        "rand.ev", "pval", "zscore", "ntimes")
			- line 48:    class(permTestTx.results) <- "permTestTx.results"
			- line 49:    return(permTestTx.results)
		+ in permTestTxIA_customPick
			- line 8:            ...)
			- line 9:        orig.ev <- ev_function_1(RS1, RS2, ...)
			- line 10:        RSL <- randomizeFeaturesTxIA(RS1, txdb, type, N = ntimes)
			- line 11:        rand.ev <- lapply(RSL, function(x) {
			- line 12:            return(ev_function_2(x, RS2, ...))
			- line 13:        })
			- line 14:        rand.ev <- unlist(rand.ev)
			- line 15:        ntimes <- length(rand.ev)
			- line 16:        if (orig.ev < mean(rand.ev)) {
			- line 17:            zscore <- round((orig.ev - mean(rand.ev, na.rm = TRUE))/sd(rand.ev, 
			- line 18:                na.rm = TRUE), 4)
			- line 19:            xcoords <- rand.ev
			- line 20:            rand.mean <- mean(xcoords, na.rm = TRUE)
			- line 21:            rand.sd <- sd(xcoords, na.rm = TRUE)
			- line 22:            ntimes <- length(RSL)
			- line 23:            if (pval_z == FALSE) {
			- line 24:                pval <- (sum(orig.ev >= rand.ev, na.rm = TRUE) + 
			- line 25:                  1)/(ntimes + 1)
			- line 26:            }
			- line 27:            else {
			- line 28:                pval <- pnorm(orig.ev, mean(rand.ev), sd(rand.ev), 
			- line 29:                  lower.tail = FALSE)
			- line 30:            }
			- line 31:        }
			- line 32:        if (orig.ev >= mean(rand.ev)) {
			- line 33:            zscore <- round((orig.ev - mean(rand.ev, na.rm = TRUE))/sd(rand.ev, 
			- line 34:                na.rm = TRUE), 4)
			- line 35:            xcoords <- rand.ev
			- line 36:            rand.mean <- mean(xcoords, na.rm = TRUE)
			- line 37:            rand.sd <- sd(xcoords, na.rm = TRUE)
			- line 38:            ntimes <- length(RSL)
			- line 39:            if (pval_z == FALSE) {
			- line 40:                pval <- (sum(orig.ev <= rand.ev, na.rm = TRUE) + 
			- line 41:                  1)/(ntimes + 1)
			- line 42:            }
			- line 43:            else {
			- line 44:                pval <- pnorm(orig.ev, mean(rand.ev), sd(rand.ev), 
			- line 45:                  lower.tail = TRUE)
			- line 46:            }
			- line 47:        }
			- line 48:        pval <- round(pval, 6)
			- line 49:        permTestTx.results <- list(RSL, RS1, RS2, orig.ev, rand.ev, 
			- line 50:            pval, zscore, ntimes)
			- line 51:        names(permTestTx.results) <- c("RSL", "RS1", "RS2", "orig.ev", 
			- line 52:            "rand.ev", "pval", "zscore", "ntimes")
			- line 53:        class(permTestTx.results) <- "permTestTx.results"
			- line 54:        return(permTestTx.results)
		+ in permTestTx_customAll
			- line 5:    rand.ev <- lapply(RSL, function(x) {
			- line 6:        return(ev_function_2(RS2, x, ...))
			- line 7:    })
			- line 8:    rand.ev <- unlist(rand.ev)
			- line 9:    ntimes <- length(rand.ev)
			- line 10:    if (orig.ev < mean(rand.ev)) {
			- line 11:        zscore <- round((orig.ev - mean(rand.ev, na.rm = TRUE))/sd(rand.ev, 
			- line 12:            na.rm = TRUE), 4)
			- line 13:        xcoords <- rand.ev
			- line 14:        rand.mean <- mean(xcoords, na.rm = TRUE)
			- line 15:        rand.sd <- sd(xcoords, na.rm = TRUE)
			- line 16:        ntimes <- length(RSL)
			- line 17:        if (pval_z == FALSE) {
			- line 18:            pval <- (sum(orig.ev >= rand.ev, na.rm = TRUE) + 
			- line 19:                1)/(ntimes + 1)
			- line 20:        }
			- line 21:        else {
			- line 22:            pval <- pnorm(orig.ev, mean(rand.ev), sd(rand.ev), 
			- line 23:                lower.tail = FALSE)
			- line 24:        }
			- line 25:    }
			- line 26:    if (orig.ev >= mean(rand.ev)) {
			- line 27:        zscore <- round((orig.ev - mean(rand.ev, na.rm = TRUE))/sd(rand.ev, 
			- line 28:            na.rm = TRUE), 4)
			- line 29:        xcoords <- rand.ev
			- line 30:        rand.mean <- mean(xcoords, na.rm = TRUE)
			- line 31:        rand.sd <- sd(xcoords, na.rm = TRUE)
			- line 32:        ntimes <- length(RSL)
			- line 33:        if (pval_z == FALSE) {
			- line 34:            pval <- (sum(orig.ev <= rand.ev, na.rm = TRUE) + 
			- line 35:                1)/(ntimes + 1)
			- line 36:        }
			- line 37:        else {
			- line 38:            pval <- pnorm(orig.ev, mean(rand.ev), sd(rand.ev), 
			- line 39:                lower.tail = TRUE)
			- line 40:        }
			- line 41:    }
			- line 42:    pval <- round(pval, 6)
			- line 43:    permTestTx.results <- list(RSL, RS1, RS2, orig.ev, rand.ev, 
			- line 44:        pval, zscore, ntimes)
			- line 45:    names(permTestTx.results) <- c("RSL", "RS1", "RS2", "orig.ev", 
			- line 46:        "rand.ev", "pval", "zscore", "ntimes")
			- line 47:    class(permTestTx.results) <- "permTestTx.results"
			- line 48:    return(permTestTx.results)
	* repetition in `randomizeFeaturesTx` and `randomizeFeaturesTxIA` and `randomizeTx`
		+ in randomizeFeaturesTx
			- line 7:            stop("type must be character.")
			- line 8:        }
			- line 9:        if (!is(N, "numeric")) {
			- line 10:            stop("N must be numeric.")
			- line 11:        }
			- line 12:    }
			- line 36:        randomResults <- randomizeTransByOrder(regions.A, random.length)
			- line 37:        return(randomResults)
			- line 38:    }
			- line 39:    randomResults.List <- lapply(seq_len(N), getRandomFeatures)
			- line 40:    if (N == 1) {
			- line 41:        return(randomResults.List[[1]])
			- line 42:    }
			- line 43:    if (N > 1) {
			- line 44:        return(randomResults.List)
			- line 45:    }
		+ in randomizeFeaturesTxIA
			- line 10:            stop("type must be character.")
			- line 11:        }
			- line 12:        if (!is.numeric(N)) {
			- line 13:            stop("N must be numeric.")
			- line 14:        }
			- line 15:    }
			- line 33:        randomResults <- randomizeTransByOrder(regions.A, random.length)
			- line 34:        return(randomResults)
			- line 35:    }
			- line 36:    randomResults.List <- lapply(seq_len(N), getRandomFeaturesIA)
			- line 37:    if (N == 1) {
			- line 38:        return(randomResults.List[[1]])
			- line 39:    }
			- line 40:    if (N > 1) {
			- line 41:        return(randomResults.List)
			- line 42:    }
		+ in randomizeTx
			- line 13:    }
			- line 14:    if (!is.numeric(N)) {
			- line 15:        stop("N must be numeric.")
			- line 16:    }
			- line 22:        randomResults <- randomizeTransByOrder(regions.A, random_length = random_length)
			- line 23:        return(randomResults)
			- line 24:    }
			- line 25:    randomResults.List <- lapply(seq_len(N), getRandomResultsList)
			- line 26:    if (N == 1) {
			- line 27:        return(randomResults.List[[1]])
			- line 28:    }
			- line 29:    if (N > 1) {
			- line 30:        return(randomResults.List)
			- line 31:    }
-[ ] Enhancement: try to use available codes to replace in-house codes
        + in GRangesList2GRanges.R: try code `unlist(GRangesList(A))`
-[ ] Enhancement: try to make sure the alignment of `seqnames` and `ranges` when you create a `GRanges` object if you use `unique` to filter `seqnames`.
        
## Documentation
- [ ] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/RgnTX.Rmd
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/RgnTX.Rmd
- [ ] Important: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette. You already include that. Please add one or more sentence to emphasize it.

**Comment by yue-wang-biomath** [comment]
Hi, @jianhong
Thanks for reviewing RgnTX and the valuable comments for making the package better. I tried to fix all the Important items and most of the NOTE items. Boxes with ticks have been fixed now as your suggestions.
 
 ## The DESCRIPTION file
* [x]  R version should be no less than 4.2
 
 ## The NAMESPACE file
* [x]  Important: Selective imports using `importFrom` instead of _import all_ with `import`.

 ## R code
 * [x]  NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development.
   
 * [x]  Important: Use `file.path` or proper code style to replace hard coding
    
 * [x]  Important: `message()`, `message`, `stop` instead of `cat` and `print` outside of `show` methods.
   
 * [x]  NOTE: Avoid 'suppressWarnings'/'*Messages' if possible

* [x]  NOTE: Avoid using '=' for assignment and use '<-' instead
  
* [x]  NOTE: Functional programming: code repetition.
   
 * repetition in `distanceTx` and `overlapCountsTx` and `overlapWidthTx`

**Re**: a new function `getFormatCorrect` has been added to replace the repetition part.

   * repetition in `getPermSpaceByType` and `GRanges2GRangesList`

**Re**: a new function `vector2GRangesList` has been added to replace the repetition part.

   * repetition in `getStopCodon` and `randomizeTransByOrder`
     
   * repetition in `permTestTx`, `permTestTx_customAll`,  `permTestTx_customPick` , `permTestTxIA`, `permTestTx_customAll` and `permTestTxIA_customPick`

**Re**: a new function `getPvalZscore` has been added to replace the repetition part.
    * repetition in `randomizeFeaturesTx` and `randomizeFeaturesTxIA` and `randomizeTx`

 * [ ] Enhancement: try to use available codes to replace in-house codes
 * in GRangesList2GRanges.R: try code `unlist(GRangesList(A))`

**Re**: altough `unlist` function is also able to convert a GRangeslist object to a GRanges, I still kept the function `GRangesList2GRanges`. It is not only for format conversion from GRangesList to GRanges, but also for adding two useful metadata columns for efficient calculations conducted by other functions. I added some comments about this in its documentation page to illustrate its special use.

 * [x] Enhancement: try to make sure the alignment of `seqnames` and `ranges` when you create a `GRanges` object if you use `unique` to filter `seqnames`.

**Re**: I have checked all the codes that involve using `unique` to filter `seqnames`. They will not disturbe the alignment of  each `seqnames` and each range, since the `unique` function is only used for filtering seqnames in the FactorList objects, rather rle or vector, as the following example shows:
 
```
regions.A_seqnames
FactorList of length 500
[["71695"]] chr20
[["77375"]] chrX chrX chrX chrX chrX chrX chrX chrX chrX chrX chrX chrX chrX
[["64945"]] chr18
[["53124"]] chr14 chr14 chr14
[["33587"]] chr8
[["35647"]] chr9 chr9 chr9 chr9 chr9 chr9 chr9 ... chr9 chr9 chr9 chr9 chr9 chr9
[["12047"]] chr2 chr2 chr2
[["67905"]] chr19 chr19 chr19 chr19 chr19 chr19 chr19 chr19
[["51496"]] chr14 chr14 chr14 chr14
[["73595"]] chr22 chr22 chr22 chr22 chr22 chr22
...
<490 more elements>

unique(regions.A_seqnames)
FactorList of length 500
[["71695"]] chr20
[["77375"]] chrX
[["64945"]] chr18
[["53124"]] chr14
[["33587"]] chr8
[["35647"]] chr9
[["12047"]] chr2
[["67905"]] chr19
[["51496"]] chr14
[["73595"]] chr22
...
<490 more elements>
```
## Documentation
 * [x]  Important: Vignette should have an _Installation_ section.
   
 * rmd file vignettes/RgnTX.Rmd
* [x]  Important: Please include Bioconductor installation instructions using BiocManager.
   
 * rmd file vignettes/RgnTX.Rmd
* [x]  Important: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette. You already include that. Please add one or more sentence to emphasize it.

**Re**: installation and motivation parts have been added to the vignette now.

**Comment by jianhong** [comment]
# Package 'RgnTX' Review
The package passed check and build. It is almost there. Some small things.

## General R package development
- [ ] NOTE: no need to export all the internal functions. For example the new functions for repetition parts.

## R code
- [ ] NOTE: Use `is.character/numeric/integer/logical` to replace `is(, "character/numeric/integer/logical")`
    * In file R/getPermSpaceByFeatures.R:
        + at line 31 found '    if (!is(type, "character")) {'
    * In file R/getPermSpaceByTxID.R:
        + at line 25 found '    if (!is(trans.ids, "character")) {'
    * In file R/getPermSpaceByType.R:
        + at line 23 found '    if (!is(type, "character")) {'

## Documentation
- [ ] Important: Vignette should have an *Installation* section. I mean this session should be listed in the table of contents.
	* rmd file vignettes/RgnTX.Rmd

**Comment by yue-wang-biomath** [comment]
@jianhong Thanks for suggestions. Now these issues have been addressed.

**Comment by jianhong** [comment]
@yue-wang-biomath Thank you for your contribution. Well done!

**Comment by yue-wang-biomath** [comment]
Thanks @jianhong !

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/yue-wang-biomath.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RgnTX")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RgnTX

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
