### ISSUE TITLE
InterTADs 

### ISSUE THREAD

**Issue by aspaor** [Bioconductor/Contributions#2639]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BiodataAnalysisGroup/InterTADs

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
You import annotables but it is not in CRAN or Bioconductor.  You can't depend on a github-only package.

**Comment by vjcitn** [comment]
Please let us know how you intend to deal with this.

**Comment by aspaor** [comment]
@vjcitn we replaced annotables with bioMart and after checking that everything works we are going to upload the changes to our master repository. I will let you know as soon as possible.

**Comment by aspaor** [comment]
@vjcitn We pushed changes into our master branch, without annotables. Please let us know if everything looks okay.                      

With regards, 
Aspa

**Comment by vjcitn** [comment]
Whenever you make any source change you must increment z in your package version x.y.z.  Otherwise your package will not be rebuilt with the changes, on the single package builder.

**Comment by vjcitn** [comment]
Here is a comment.  In the vignette you have 
```
func_anal_res <- functional_analysis(
    tech = "hg19",
    files_evenDiff = result_evenDiff[[1]],
    files_TADiff = TADiff_result[[1]],
    names.meta = c('groups'),
    exp_parent = 3,
    dbs = c("GO_Molecular_Function_2018",
    "GO_Biological_Process_2018",
    "KEGG_2019_Human"),
    type = c("GO_MF", "GO_BP", "KEGG"),
    genes_cover = c(11459, 14433, 7802),
    p_adjust_method = "fdr",
    cut_off = 0.05,
    criterio = "adj_pvalue",
    min_genes = 3,
    system = "win",
    annotation_file = '/chr1_v19_annotation_gff3.gz',
    dir_name =  system.file("extdata", "Datasets", package="InterTADs"),
    output_folder = paste0("Outputs"))
```
That is somewhat intricate and it would be easy for a user to make an error.  It might be nice to define a configuration object that can be checked for validity, that would then be passed to `functional_analysis`.  Otherwise the user may find that some parameter is misspecified and will need to trace back.

functional_analysis is a long function with few comments ... I see
```
    for (i in input_params) {
        if (is.null(i)) {
            stop("Please provide all the input parameters in the correct type.")
        }
    }
```
which does not really check for 'correct type'.  This is related to the initial comment.

Finally I wonder whether your multiomic data should use a MultiAssayExperiment or related Bioconductor container structure to help unify the related data elements that will be analyzed.

**Comment by vjcitn** [comment]
Checking again.

**Comment by aspaor** [comment]
Dear @vjcitn,

Thank you for your previous comments. Following your instructions we are currently working on making our package more object oriented. We assume that this needs major restructuring and will be completed by the end of June (mid-July). 

With regards,
Aspa

**Comment by vjcitn** [comment]
I noticed that the vignette chunks are all eval=FALSE, be sure that vignette code actually runs when you reopen this issue.  I am closing it for now, just reopen when you have made your revisions to initiate review; also be sure R CMD check and BiocCheck pass when you do this.
