### ISSUE TITLE
methInheritSim

### ISSUE THREAD

**Issue by belleau** [Bioconductor/Contributions#264]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/belleau/methInheritSim

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by LiNk-NY** [comment]
Hi Pascal @belleau, 
Can you please bump the version of your package? Thank you.
Regards,
Marcel

**Comment by belleau** [comment]
The package is up to date.
Best regards
Pascal

**Comment by LiNk-NY** [comment]
Hi Pascal @belleau, 
Thank you for submitting to Bioconductor!
Your package name is quite similar to [methylInheritance](https://github.com/Bioconductor/Contributions/issues/265). 
This may cause some confusion for users.
Please consider renaming the package or even merging both packages into one. 

---

## methylInheritanceSim

### Grammar 
* Avoid the use of `1:n` type of code. Try using `seq_len` or `seq_along()` for more robust code.
* Avoid combining arguments. Some functions should not be a vector but scalar values. For example, `x` in `getDiffCase`. 
* Be mindful of argument order in functions such as `SimInheritance`. The order matters and usually you want your primary object as your first argument. 
* Reduce the size of the monster functions. The functions should be kept as minimal as possible and should be designed to perform one operation at time. An example of some offenders are `ValidateRunSimParameterss`, `SimInheritance`, and `runSim`. 

If you have any questions, feel free to contact me.

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Pascal, @belleau 
Please bump the "z" version of your package (x.y.z) in order to trigger another build. 
Best regards,
Marcel

**Comment by adeschen** [comment]
Hi Marcel @LiNk-NY,

The modifications are not yet completed. We have planned to update the version when all your points will be addressed. That way, the next version will be a "ready to review" version. 

Regards,
Astrid

**Comment by LiNk-NY** [comment]
That works. Thank you Astrid.

**Comment by belleau** [comment]
Hi  Martin @mtmorgan,

Following the renaming of this package, the repository of your package has been changed. We edited the first comment to change the repository: link.

Thanks,

Astrid

**Comment by LiNk-NY** [comment]
Hi Astrid, @belleau
Could you also re-establish the webhook to your package? 

Thank you, 
Marcel

**Comment by belleau** [comment]
Hi Marcel, @LiNk-NY,

I have updated it but there is a warning message: Last delivery was not successful.

Astrid

**Comment by belleau** [comment]
Hello Marcel, @belleau

The webhook is updated but the message: Last delivery was not successful. 
Invalid http response : 400. 
I think it doesn't see methInheritSim version?

Thank you,

Pascal

**Comment by mtmorgan** [comment]
Usually the invalid http response: 400 means that item 6 of the [webhook instructions] is not satisfied: the Content-type: dropdown needs to be json.

[webhook instructions]: https://github.com/Bioconductor/Contributions#adding-a-web-hook

**Comment by belleau** [comment]
Hi Martin @mtmorgan 

We have followed the instructions and it is set to json. Before the package name modification, it used to work correctly. At this moment, we are unable to find the cause of this problem.

Thanks,

Pascal

![webhook](https://cloud.githubusercontent.com/assets/8398253/24640721/5d3c9670-18c7-11e7-982b-62a99fa82918.JPG)

**Comment by LiNk-NY** [comment]
Hi Pascal, @belleau 

Did you update the webhook? 
You can try deleting it first and creating a new one from the settings. 
Don't forget to bump your package's version. 

Regards,
Marcel

**Comment by belleau** [comment]
Hi Marcos, @LiNk-NY 

The webhook has been deleted and re-created. The package's version has been bumped.
The webhook is now working. However, this is the response we got from it:

Sorry, you haven't told us about this repository, please
      go to https://github.com/Bioconductor/Contributions/issues/new .

Regards,
Pascal

**Comment by LiNk-NY** [comment]
Monsieur @belleau, c'est Marcel.  
And I will look into the issue. 
Thanks.

**Comment by LiNk-NY** [comment]
Hi Martin @mtmorgan,
Any ideas on what could be going on here?

A couple of things to keep in mind that may have an effect on the webhook
(although Lori told me it is tracked by number and not by name):
* Package was renamed
* Issue was closed and re-opened

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Pascal, @belleau 
Any luck on getting this to work? It may be that the name change is affecting it somehow. 

Thanks,
Marcel

**Comment by belleau** [comment]
Hi Marcel, @LiNk-NY 

I could temporary change the name and the URL back to what is used to be (without changing the code) and then, update the webhook. This way, we could see if the problem is caused be the name change.

Regards,
Pascal

**Comment by mtmorgan** [comment]
Please do not change the name; this slipped through my radar. I will work on it this afternoon.

**Comment by LiNk-NY** [comment]
Thanks for looking into it Martin @mtmorgan. 
Just a quick note: 
It looks like the SPB is still holding on to the previous name `methylInheritanceSim` but is building the tar ball as `methInheritSim_0.99.8.tar.gz` and subsequently producing an error. 

Marcel

**Comment by mtmorgan** [comment]
@belleau can you try a version bump again? No guarantees...

**Comment by belleau** [comment]
Hi Marcel, @LiNk-NY 

We have corrected all the listed issues. See the corrections/explanations below.

**1.**  Your package name is quite similar to methylInheritance.
This may cause some confusion for users.
Please consider renaming the package or even merging both packages into one.

**Correction:**  The package name has been changed to methInheritSim

**2.** Avoid the use of 1:n type of code. Try using seq_len or seq_along() for more robust code.

**Correction:** The 1:n code has been replaced with seq_len() function. The seq_len() function is now present in those functions: runSim(), getSyntheticChr(), simEachGeneration() and createSampleID().

**3.** Avoid combining arguments. Some functions should not be a vector but scalar values. For example, x in getDiffCase.

**Correction:**  Combined arguments have been removed. The functions impacted by the modification are: getDiffCase(), estBetaAlpha() and estBetaBeta().

**4.** Be mindful of argument order in functions such as SimInheritance. The order matters and usually you want your primary object as your first argument.

**Correction:** Argument order in functions runSim() (visible function) and runOnEachSynCHR() (internal function) has been modified. The methData argument (mandatory methylation data) is now the first argument.

**5.** Reduce the size of the monster functions. The functions should be kept as minimal as possible and should be designed to perform one operation at time. An example of some offenders are ValidateRunSimParameterss, SimInheritance, and runSim.

**Correction:** 1- Code from validateRunSimParameters() function has been split into smaller functions: validateRunSimIntegerParameters(), validateRunSimDoubleParameters(), validateRunSimLogicalParameters() and validateRunSimOtherParameters(). 
2- Code from simInheritance() has been split into smaller functions: testIfAlreadyDone(), simEachGeneration() and saveData(). 
3- Code from runSim() has been split into smaller functions: fixSeed(), createSampleID() and runOnEachSynCHR().

Thanks,
Pascal

**Comment by LiNk-NY** [comment]
Hi Pascal, @belleau 

It seems like there were some build issues with the Single Package Builder (SPB).
Can you please bump the version of your package to get another build? 
Thank you. 

Regards,
Marcel

**Comment by adeschen** [comment]
Hi Marcel, @LiNk-NY 

A new version of the package has been bumped 21 days ago.

Looking forward to hearing from you.

Astrid

**Comment by LiNk-NY** [comment]
Hi Astrid, @adeschen 
Sorry for the delay.

Thank you for making those changes. They look good. 

Congratulations! Your package has been approved!
Thank you for submitting to Bioconductor!

Best regards,
Marcel
