### ISSUE TITLE
BiocDeveloper

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/Contributions#2640]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/BiocDeveloper

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Third time's a charm :crossed_fingers:

**Comment by ococrook** [comment]
I'll take another look at the code and vignette soon, I'll expedite this review because of the back and forward.

Did you appease @hpages ?

**Comment by LiNk-NY** [comment]
I'm afraid that is quite difficult :smile:  
But Hervé is understanding. 
Best,
Marcel

**Comment by hpages** [comment]
Nope, that new name doesn't appease me. Probably the worst of all the names that have been thrown around :sweat_smile:

At least I've tried...

**Comment by LiNk-NY** [comment]
Hehe yes, I knew it wouldn't BUT if you contribute the internals package then I can add it as a dependency :wink:

**Comment by hpages** [comment]
If I do the internals package, I'll just clone BiocDeveloper and rename it BiocInternalUtils :wink:

**Comment by ococrook** [comment]
Thanks for remvoving the error and agreeing the name ;) I do not see any other issues so I'll move to accept

**Comment by hpages** [comment]
I don't agree with the name. I think it's terrible. I think that before renaming the issue twice, we should have reached consensus. Renaming with a "surprise name" after some "internal discussion" to which I was not part is disappointing.

**Comment by hpages** [comment]
@ococrook @LiNk-NY I'm withdrawing this submission until consensus has been reached among the co-authors of the package about the name (I'm one of them). I'm sorry that this discussion about the name didn't happen before the package was submitted. I would have started it had I known that the package was going to be submitted for review but I didn't know.

**Comment by hpages** [comment]
See https://github.com/Bioconductor/BiocDeveloper/issues/1

**Comment by ococrook** [comment]
@hpages sorry I assumed that "internal" discussion had meant that you guys had moved the discussion offline and come to a consensus. My apologies for misinterpreting that. 

I agree a name should be agreed amongst the authors. I'm inclined to close the issue because the package is not really at review stage if the authors aren't all happy about submission.

**Comment by ococrook** [comment]
I liked BiocInternalsUtils if that saves a coin toss

**Comment by hpages** [comment]
Yes please close the issue @ococrook Thanks for your patience and sorry for the back and forth.
