### ISSUE TITLE
IMPACC

### ISSUE THREAD

**Issue by luqingan** [Bioconductor/Contributions#2655]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DataSlingers/IMPACC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
The vignette has long list of optimization trace.  Should suppress.  You should use SummarizedExperiment or other integrative containers in Bioconductor.  Please revise.   Do not use a list like 
```
library(IMPACC)
data(yan)
yan$raw[1:3, 1:3]
##        GSM896803 GSM896804 GSM896805
## A1BG           8         6         2
## A1BGAS        24        18         4
## A1CF        1306      1072       828
yan$sc_cnt[1:3, 1:3]
##        GSM896803 GSM896804 GSM896805
## A1BG    3.169925  2.807355  1.584963
## A1BGAS  4.643856  4.247928  2.321928
## A1CF   10.352043 10.067434  9.695228
head(yan$sc_label)
## [1] "Oocyte " "Oocyte " "Oocyte " "Zygote " "Zygote " "Zygote "
```
Notice the trailing blanks in the cell type strings.  Intended?  Accidental?

Does the vignette reader need to see
```
impacc_multinomial = IMPACC(d=yan$sc_cnt,K = K,reps = 1,feature_evaluation = 'multinomial', verbose=FALSE)
## Burn-in stage
## # weights:  3 (2 variable)
## initial  value 15.249238 
## final  value 12.759554 
## converged
## # weights:  3 (2 variable)
## initial  value 15.249238 
## iter  10 value 10.231735
## iter  10 value 10.231735
## iter  10 value 10.231735
## final  value 10.231735 
## converged
## # weights:  3 (2 variable)
## initial  value 15.249238 
## final  value 12.092815 
## converged
## # weights:  3 (2 variable)
## initial  value 15.249238 
## final  value 10.908304 
## converged
## # weights:  3 (2 variable)
## initial  value 15.249238 
## final  value 9.906160 
## converged
## # weights:  3 (2 variable)
## initial  value 15.249238 
## iter  10 value 0.035134
## iter  20 value 0.005524
## iter  30 value 0.001722
## iter  40 value 0.000603
## iter  50 value 0.000226
## final  value 0.000098 
## converged
## # weights:  3 (2 variable)
## initial  value 15.249238 
## final  value 11.907750 
## converged
## # weights:  3 (2 variable)
## initial  value 15.249238 
## iter  10 value 4.080592
## final  value 4.078276 
## converged
## # weights:  3 (2 variable)
## initial  value 15.249238 
## iter  10 value 3.546823
## iter  20 value 3.460980
## iter  30 value 3.458233
## final  value 3.458233 
## converged
## # weights:  3 (2 variable)
## initial  value 15.249238 
## iter  10 value 1.243145
## iter  20 value 0.727943
## iter  30 value 0.586823
## iter  40 value 0.462228
## iter  50 value 0.368125
## iter  60 value 0.306748
## iter  70 value 0.264036
## iter  80 value 0.232274
## iter  90 value 0.207367
## iter 100 value 0.187116
## final  value 0.187116 
## stopped after 100 iterations
## # weights:  3 (2 variable)
## initial  value 15.249238 
## final  value 12.837630 
## converged
## # weights:  3 (2 variable)
## initial  value 15.249238 
## iter  10 value 10.021199
## iter  20 value 10.010808
## iter  30 value 10.009744
## iter  40 value 10.009324
## iter  50 value 10.009074
## iter  60 value 10.008905
## iter  70 value 10.008784
## iter  80 value 10.008693
## iter  90 value 10.008622
```

Please look carefully at guidelines for submission.

**Comment by vjcitn** [comment]
Will you be addressing these comments?  For now I will close the issue; reopen when you have a response.
