### ISSUE TITLE
protlocassigndoc

### ISSUE THREAD

**Issue by mooredf22** [Bioconductor/Contributions#2656]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mooredf22/protlocassigndoc

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

# # # # # 
This is a workflow package that is connected to the "protlocassign" package, Issue #2541. Since this workflow package consists of more extensive documentation than can fit in the protlocassign package, these two submissions should be considered together.

**Comment by mooredf22** [comment]
This documentation package for the "protlocassign" package requires loading "protlocassign", which is the reason for the error. This package is currently under review (issue 2541) for Bioconductor and thus apparently cannot be directly loaded. Thus, it appears that we must wait for this other review to be completed before this one (protlocassigndoc) can move forward.

**Comment by vjcitn** [comment]
Looks like you should have used the related packages protocol.  @lshep

**Comment by mooredf22** [comment]
I see, thanks. Could you point me to where I can find information about the "related packages protocol"? I have searched Bioconductor for that but have not found a description.

**Comment by vjcitn** [comment]
https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#submitting-related-packages

which is linked from 1.5 of the general guidelines

**Comment by mooredf22** [comment]
I re-submitted protlocassign (#2541) according to the guidelines and it ran without errors. It appears, though, that that issue and the current one need to be merged. Let me know if I need to do anything else to make that happen.

**Comment by lgatto** [comment]
From the link posted above, it look like you need to add it to the `protlocassign` issue by adding a comment containing
```
 AdditionalPackage: https://github.com/mooredf22/protlocassigndoc
```

**Comment by lshep** [comment]
If we want to combined these issues and go the additional package route -- I will need to do some manual adjustments.  @mooredf22  would you like to move this review to the other as an additional package?

**Comment by mooredf22** [comment]
Yes, for sure. Thanks for taking care of this. The DESCRIPTION file of protlocassign already references protlocassigndoc. Let me know if I need to do anything else on my end to make this happen.Sent from my iPhoneOn Oct 11, 2022, at 8:42 AM, lshep ***@***.***> wrote:﻿
If we want to combined these issues and go the additional package route -- I will need to do some manual adjustments.  @mooredf22  would you like to move this review to the other as an additional package?

**Comment by lshep** [comment]
I manually updated the database to point this package to the 1541 issue. If you do a valid version bump and push to git.bioconductor.org for protlocassigndoc you should now see the build report results in issue 1541 now and you should be able to access the version of the package under review.  @lgatto  that will mean you should review both of these packages under the 1541 issue and not accept unless they are both ready.

**Comment by lshep** [comment]
I stand corrected.  It didn't work to manually reassign it. Could you please use the `AdditionalPackage: https://github.com/mooredf22/protlocassigndoc`    in issue 1541  please to link the issues.
