### ISSUE TITLE
CTSV

### ISSUE THREAD

**Issue by jingeyu** [Bioconductor/Contributions#2663]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jingeyu/CTSV

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for the submission.  The vignette includes
```
Y is a n×G count bulk ST data matrix, where each row stands for a spot and each column represents a gene.
loc is a n×2 location matrix, where each row is a two-dimensional coordinate for the corresponding spot.
W is the cell-type-specific matrix with n×K dimensions, where K is the number of cell types.
num_core: for parallel processing, the number of cores used. If set to 1, parallel processing i
```
Please use a derivate of SummarizedExperiment, perhaps SpatialExperiment, to help users who may be familiar with related Bioconductor infrastructure for your application.  The use of BiocParallel should be mediated through bpparam setting.

**Comment by jingeyu** [comment]
Thank you for your comments.

Answer to point 1: I have revised the main R function 'CTSV.R' to support the use of SpatialExperiemnt, thus the input of main function 'ctsv' are SpatialExperiment class object instead of 'Y' and 'loc'.

Answer to point 2: I have added BPPARAM parameter as input parameter of 'ctsv' function to control parallel process, details can be attached in vignette. 

And I have updated DESCRIPTION, NAMESPACE, CTSV.R, CTSVexample.RData, test-ctsv.R, and vignette in my CTSV repository since the input of our function is changed. Please check it.

**Comment by vjcitn** [comment]
Bump the version number in DESCRIPTION whenever you make source changes.

When installing on linux I saw
```
6: In readLines(file) :
  incomplete final line found on '/home/stvjc/SUBMISSIONS/CTSV/DESCRIPTION'
7: roxygen2 requires Encoding: "UTF-8"
```

In vignette, use suppressPackageStartupMessages to wrap your library commands to reduce space taken up by attachment messages.

```
Running CTSV
We are now ready to run CTSV on the bulk ST data using ctsv function.

spe is a n×G count bulk ST data matrix, where each row stands for a spot and each column represents a gene.
```
that's from the vignette ... is it still true, or is spe a SpatialExperiment instance?

**Comment by jingeyu** [comment]
Thank you for your comments!

Answer to version:
Apologize for my mistake. I have bumped the version number from 0.99.0 to 0.99.2 in this update version.

Answer to Linux installation:
(1) I added a blank line in the end of the DESCRIPTION  hoping to avoid the Warning.
(2) In the DESCRIPTION file I set 'Encoding: UTF-8' and when I run 'roxygen2::roxygenise()', 'roxygen2 requires Encoding: "UTF-8"' did not appeared. 
Furthermore, when I install the source package on linux (x86_64-pc-linux-gnu (64-bit)) none of the warning messages listed appeared.So I have no idea why these two warnings appear.
 
Answer to vignette:
 (1). I used ’suppressPackageStartupMessages‘ in vigentte in the new version.
 (2). spe is actually a SpatialExperiment instance, and I revised the statement in vignette.

**Comment by jingeyu** [comment]
Thank you for the bulid report. I found two same ERRORS in  'BiocCheck' on Linux and MacOS systems separately, one is 'Maintainer must subscribe to the bioc-devel mailing list' and the other one is 'Maintainer must register at the support site'. 

1. I have successfully subscribed to the bioc-devl mailing list with the information "You have successfully confirmed your subscription request for "yjgruc@ruc.edu.cn" to the Bioc-devel mailing list.'.

2. I have registered at the support site via mu github accout with the information in the website " Successfully signed in as 7c38eb88.".

3. Furthermore, I bumped the version of CTSV from 0.99.2 to 0.99.3.

**Comment by jingeyu** [comment]
Thank you for the bulid report. I found two same ERRORS in 'BiocCheck' on Linux and MacOS systems separately, one is 'Maintainer must subscribe to the bioc-devel mailing list' and the other one is 'Maintainer must register at the support site'.

1. I have successfully subscribed to the bioc-devl mailing list with the information "You have successfully confirmed your subscription request for "[yjgruc@ruc.edu.cn](mailto:yjgruc@ruc.edu.cn)" to the Bioc-devel mailing list.'.

2. I have registered at the support site via mu github accout with the information in the website " Successfully signed in as 7c38eb88.".

3. Furthermore, I bumped the version of CTSV from 0.99.2 to 0.99.3 in my github repository.

**Comment by jingeyu** [comment]
Thank you for the bulid report!

**Comment by jingeyu** [comment]
Dear Bioconductor,  is there anything else that I should amend?

**Comment by LiNk-NY** [comment]
Hi Jinge Yu, @jingeyu 
Thank you for your submission.
Sorry for the delay in the review. I will provide a review in the next couple of days. 
Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi JingeYu, @jingeyu 

Please see the review below. 
Best regards,
Marcel

--- 

# CTSV #2663

Ideally, the package would accept mainly `SpatialExperiment` inputs as well as
matrix inputs for the counts and spatial coordinates information.

## DESCRIPTION

* (Optional) Wrap the text in the Description to a max of 80 character-width
* Add BugReports and URL fields
* Update the R depends field to R `>= 4.2.0` (see BiocCheck).

## NAMESPACE

* The main function should be in the same case as the package i.e.,
`CTSV::CTSV`.

## vignettes

* Consider using Bioconductor `BiocStyle::html_document` vignette generator
* For readability and maintenance, keep the max character width at 80.
* Explain what RCTD is before using the acronym.
* Avoid using non-standard interfaces to `SpatialExperiment`. Promote good
practice by using `assay(spe)`.
* Remove all the superfluous `print` functions.

## R

* The input checks in `ctsv` are redundant and verbose. Please combine
conditions, e.g., `if (missing(spe) || !is(spe, "SpatialExperiment"))`
* Avoid using emphatic language, e.g., the exclamation point `!`, in messages.
* Avoid formalities ('please') in the messages and only provide the
information necessary for the user, e.g.,
`"The threshold limit must be between 0 and 1"`.
* Use the standard interface (`assay`) and avoid the use of `@`.

## /

* Remove the `build` folder from the package, it inteferes with the
installation:

```r
Warning in file(con, "w") :
  cannot open file '00LOCK-CTSV/00new/CTSV/doc/index.html': No such file or directory
Error in file(con, "w") : cannot open the connection
ERROR: installing vignettes failed
```

## tests

* Consider improving function coverage:

```r
covr::package_coverage()
CTSV Coverage: 26.26%
R/CTSV.R: 26.26%
```

**Comment by jingeyu** [comment]
Hi @LiNk-NY, thank you for your review, I have addressed the points you proposed.

0.  "Ideally, the package would accept mainly SpatialExperiment inputs as well as
matrix inputs for the counts and spatial coordinates information." 
Response: Our package mainly takes SpatialExperiment as inputs for the counts and spatial coordinates information, and the parameter 'W' in the main function 'CTSV' is the cell-type proportion matrix that is necessary for our method. And the 'num_core' is set for paralleling computation.

### **DESCRIPTION**
1. I have wrapped the text in the Description to a max of 80 character-width.
2. I have added BugReports and URL fields.
3. I have updated the R depends field to R >= 4.2.

### **NAMESPACE**
1. The main function is in the same case as the package i.e., CTSV::CTSV in the revised version.

### **Vignettes**
1. I have used the Bioconductor BiocStyle::html_document vignette generator in the new version.
2. I have wrapped the text in the Description to a max of 80 character width.
3.  'RCTD' is a typo here, it should be 'CTSV' actually, and I fixed the problem, sorry for my carelessness.
4. I used 'assay(spe)' instead of slot in the new version.
5. I have removed print functions.

### **R**
1. I have combined some input checks and there are few input checks now.
2. I deleted all the exclamation point '!' in the R function.
3. I deleted formalities ('please') in the messages and only provided the information necessary for the user.
4. I have used the standard interface (assay) and avoided the use of @ in the new version.

### **/**
1. I deleted the bulid folder in the new version.

### **tests**
I have improved the function coverage from 26.26% to 83.33%.
`covr::package_coverage()`
`CTSV Coverage: 83.33%`
`R/CTSV.R: 83.33%`

**Comment by LiNk-NY** [comment]
Hi JingeYu, @jingeyu 

Thank you for making those changes. It would be good to have some flexibility in the input and not restrict to only `SpatialExperiment` users but this mostly a design choice. 
Also note that in R `print(K)` is the same as `K`. Consider removing the extra `print` calls in the examples.

The package looks ready. Thank you for your submission. 

Best regards,
Marcel

**Comment by jingeyu** [comment]
> Hi JingeYu, @jingeyu
> 
> Thank you for making those changes. It would be good to have some flexibility in the input and not restrict to only `SpatialExperiment` users but this mostly a design choice. Also note that in R `print(K)` is the same as `K`. Consider removing the extra `print` calls in the examples.
> 
> The package looks ready. Thank you for your submission.
> 
> Best regards, Marcel

Hi @LiNk-NY, I will remove extra 'print' in the examples. And the input format folllowed the advice of  [vjcitn](https://github.com/vjcitn) -- "Please use a derivate of SummarizedExperiment, perhaps SpatialExperiment, to help users who may be familiar with related Bioconductor infrastructure for your application."

Best regards,
 Jinge Yu

**Comment by LiNk-NY** [comment]
Hi JingeYu, @jingeyu 

That doesn't mean you can't have both types of inputs. Some users may not have a `SpatialExperiment` to work with, although we expect most users do. There are many packages in Bioconductor that allow, for example, either a `SummarizedExperiment` or `matrix` as input. 

Best regards,
Marcel

**Comment by jingeyu** [comment]
> Hi JingeYu, @jingeyu
> 
> That doesn't mean you can't have both types of inputs. Some users may not have a `SpatialExperiment` to work with, although we expect most users do. There are many packages in Bioconductor that allow, for example, either a `SummarizedExperiment` or `matrix` as input.
> 
> Best regards, Marcel

Hi Marcel, @LiNk-NY, thank your for your suggestions, and I will improve my package in the next few days!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jingeyu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CTSV")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CTSV

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
