### ISSUE TITLE
omada

### ISSUE THREAD

**Issue by BioSok** [Bioconductor/Contributions#2668]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BioSok/omada

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for your submission.  I see in the vignette
```
partition.agreement.scores <- omada.analysis[[1]]
partition.agreement.plot <- omada.analysis[[2]]
feature.selection.scores <- omada.analysis[[3]]
feature.selection.plot <- omada.analysis[[4]]
cluster.voting.scores <- omada.analysis[[5]]
cluster.voting.cluster.memberships <- omada.analysis[[6]]
cluster.voting.metric.votes <- omada.analysis[[7]]
cluster.voting.k.votes <- omada.analysis[[8]]
cluster.voting.plot <- omada.analysis[[9]]
sample.memberships <- omada.analysis[[10]]
signature.feature.coefs <- omada.analysis[[11]]
signature.feature.plot <- omada.analysis[[12]]
```
This is not convenient for users.  Please define a class that can manage this complexity for the user; join the mentoring program if this is not clear.  Bioconductor infrastructure for gene set management (e.g., GSEABase or BiocSet) should be used to participate meaningfully in the ecosystem.

**Comment by BioSok** [comment]
Hey, thanks for the feedback. I have created a class, could you check if it's to your standards? Thanks!

**Comment by vjcitn** [comment]
It is getting a little better, but
```
# Extract results
stabilities.per.cluster <- existing.dataset.analysis[[1]]
maximum.stability <- existing.dataset.analysis[[2]]
average.stability <- existing.dataset.analysis[[3]]
simulated.dataset <- existing.dataset.analysis[[4]]
```

### Automated clustering analysis: Omada
Using `omada()` along with a gene expression dataframe and an upper k (number of clusters to be considered) we can run the whole analysis toolkit to automate clustering decision making and produce the estimated optimal clusters.

```{r omada, warning = FALSE, message = FALSE, cache = TRUE, fig.width = 7, fig.asp = .42, fig.align='center'}
# Running the whole cascade of tools inputting an expression dataset 
# and the upper k (number of clusters) to be investigated
omada.analysis <- omada(toy_genes, method.upper.k = 4)
# Plot results
omada.analysis$partition.agreement.plot
omada.analysis$feature.selection.plot
omada.analysis$cluster.voting.plot
omada.analysis$signature.feature.plot
```
is still not in line with how most bioconductor packages work.  The extraction of results using [[i]] on existing.dataset.analysis is better accomplished with functions on the existing.dataset.analysis which could be an instance of an S3 or S4 class.  We distinguish "getters" and "setters".  You would define get_stabilities_per_cluster as a method on the analysis class.

Then with your plot calls via "$", you have an object class with omada.analysis as an instance; you would define, say the method "plot" with a parameter type that is one of "partition.agreement" or "feature.selection" and so forth.

**Comment by BioSok** [comment]
Hey! I have restructured the functions with getters as well as the vignette.

**Comment by vjcitn** [comment]
Bump the version number in DESCRIPTION whenever you commit a change to source.

**Comment by BioSok** [comment]
Bumped it to 0.99.1 from 0.99.0

**Comment by BioSok** [comment]
Hey @nturaga , it seems I don't have access to push to the repo as I'm getting:

FATAL: W any packages/omada s.kariotis DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Also, I submitted 2 packages few years ago and from the Bioconductor Git Credentials I can see I only have access to those.

**Comment by nturaga** [comment]
Hi, this should be fixed now. please try to push again.

**Comment by lshep** [comment]
we are experiencing some issues with the newly added windows builder that is prevent the new build report from being posted. We are working on a remedy.  We appreciate your patience and understanding.

**Comment by nturaga** [comment]
## DESCRIPTION

- Your name isn't "Developer" , so i'm not sure why the name of the person is listed this way.

```
Authors@R: person("Sokratis Kariotis", "Developer", role = c("aut", "cre"),
                     email = "sokratiskariotis@gmail.com"
```

## build report

Please fix the following NOTEs

- NOTE: Update R version dependency from 4.1 to 4.2.0.

- Checking coding practice...
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
    * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
    * NOTE: Avoid using '=' for assignment and use '<-' instead

 - NOTE: Consider adding runnable examples to man pages that
      document exported objects.

 - NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.

**Comment by BioSok** [comment]
> ## DESCRIPTION
> * Your name isn't "Developer" , so i'm not sure why the name of the person is listed this way.
> 
> ```
> Authors@R: person("Sokratis Kariotis", "Developer", role = c("aut", "cre"),
>                      email = "sokratiskariotis@gmail.com"
> ```
> 
> ## build report
> Please fix the following NOTEs
> 
> * NOTE: Update R version dependency from 4.1 to 4.2.0.
> * Checking coding practice...
>   
>   * NOTE: Avoid 1:...; use seq_len() or seq_along()
>   * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
>   * NOTE: Avoid using '=' for assignment and use '<-' instead
> * NOTE: Consider adding runnable examples to man pages that
>   document exported objects.
> * NOTE: Consider adding a NEWS file, so your package news will be
>   included in Bioconductor release announcements.

Fixed!

**Comment by BioSok** [comment]
> ## DESCRIPTION
> * Your name isn't "Developer" , so i'm not sure why the name of the person is listed this way.
> 
> ```
> Authors@R: person("Sokratis Kariotis", "Developer", role = c("aut", "cre"),
>                      email = "sokratiskariotis@gmail.com"
> ```
> 
> ## build report
> Please fix the following NOTEs
> 
> * NOTE: Update R version dependency from 4.1 to 4.2.0.
> * Checking coding practice...
>   
>   * NOTE: Avoid 1:...; use seq_len() or seq_along()
>   * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
>   * NOTE: Avoid using '=' for assignment and use '<-' instead
> * NOTE: Consider adding runnable examples to man pages that
>   document exported objects.
> * NOTE: Consider adding a NEWS file, so your package news will be
>   included in Bioconductor release announcements.

Dear @nturaga , is there an update on the package review process? I am asking because we are trying to align its release to the relevant paper's submission. Thanks!

**Comment by nturaga** [comment]
@BioSok 

Your package looks fine to accept. Please issue another build report.

One issue is that there is no `sessionInfo()` inside your vignette. Please include it.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/BioSok.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("omada")`. The package 'landing page' will be created at

https://bioconductor.org/packages/omada

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
