### ISSUE TITLE
mslp

### ISSUE THREAD

**Issue by ccshao** [Bioconductor/Contributions#2669]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ccshao/mslp

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```
> res <- pp_tcga(P_mut, P_cna, P_expr, P_z)
(II) Pre-process mutation data.

Error in fread(p_mut, select = c("Tumor_Sample_Barcode", "Gene", "Variant_Classification")) : 
  File 'data_mutations_extended.txt' does not exist or is non-readable.
```
Your vignette has global setting eval=FALSE.  This is inappropriate.  The vignette should exercise package code and produce results illuminating to the reader.  As you can see above, when I purl the Rmd file and try to run code, it fails.

Are you using cBioPortalData?  GRanges?  Any other Bioconductor data structures?

**Comment by ccshao** [comment]
@vjcitn thank you very much for the quick updates and suggestions. 

The codes you cited are used to preprocess tab-separated data downloaded directly from data repo like cBioPortal.  That is why they are not running. I am not using Bioconductor data structures

Most of the codes in the vignette should work without issues and I have tested on my local computer, except **two** chunks dealing data from public resources. You are right about that the global `eval=FALSE` is inappropriate. 

I would like to suggest the following changes:
- remove the global `eval=FALSE`
- add the `eval=FALSE` dealing with public sources

Thus the codes in the vigentte should be ok. Let me know your opinions. Thanks!

**Comment by vjcitn** [comment]
When you make the changes you propose (and I would encourage you to consider how Bioconductor data structures and packages help you and users achieve the aims of the package) bump the version in DESCRIPTION, and add a comment to your issue.  I will reevaluate at that time (depending on my availability there may be a delay).

**Comment by jianhong** [comment]
# Package 'mslp' Review
The package passed check and build. However there are several things need to be fixed.

## The DESCRIPTION file
- [ ] R version should be no less than 4.2

## General package development
- [ ] Important: Consider adding runnable examples
      to man pages that documentexported
      objects.
      
- [ ] Important: Usage of dontrun{} / donttest{}
      found in man page examples.7% of man
      pages use one of these cases.
    
- [ ] Important: Consider adding a NEWS file, so
      your package news will be included in
      Bioconductor release announcements.

- [ ] Important: Consider adding unit tests. We
      strongly encourage them. See
      http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
      
- [ ] Important: All the format of function inputs should be checked.

## R code
- [ ] Important: No `paste` in `message()`, `message`, `stop`
	* In file R/genie3.R:
		+ at line 68 found '          message(paste("Gene ", missing.gene.name, " was not in the expression matrix\n", sep = ""))'
		+ at line 86 found '    message(paste("Starting RF computations with ", nb.trees,'
		+ at line 94 found '    if (trace) message(paste("Computing gene ", target.gene.idx, "/", ngene, "\n", sep = ""))'
- [ ] NOTE: Try to search object via `mget` from `org.Xx.egSYMBOL2EG` or `org.Xx.egALIAS2EG` to search entrez id by symbol. 
	* In file R/compensationSLP.R:
		+ at line 61 found '    anno <- as.data.table(org.Hs.eg.db::org.Hs.egSYMBOL)[match(unique(symbol), symbol)]'
	* In file R/correlationSLP.R:
		+ at line 53 found '    anno       <- as.data.table(org.Hs.eg.db::org.Hs.egSYMBOL)[match(unique(symbol), symbol)]'
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development.
	* In file R/compensationSLP.R:
		+ at line 61 found '    anno <- as.data.table(org.Hs.eg.db::org.Hs.egSYMBOL)[match(unique(symbol), symbol)]'
		+ at line 98 found '      invisible(capture.output(res <- RankProd::RankProducts(mtx, cl = rep(1, ncol(mtx)), logged = TRUE, gene.names = rownames(mtx), calculateProduct = FALSE, ...)))'
	* In file R/consensusSLP.R:
		+ at line 176 found '    k_res <- fmsb::Kappa.test(mtx)'
	* In file R/correlationSLP.R:
		+ at line 53 found '    anno       <- as.data.table(org.Hs.eg.db::org.Hs.egSYMBOL)[match(unique(symbol), symbol)]'
	* In file R/genie3.R:
		+ at line 75 found '  if (methods::is(K, "numeric")) {'
		+ at line 101 found '    rf <- randomForest::randomForest(x, y, mtry = mtry, ntree = nb.trees, importance = TRUE, ...)'
		+ at line 102 found '    im <- randomForest::importance(rf)[, importance.measure]'
	* In file R/utils.R:
		+ at line 47 found '  anno     <- as.data.table(org.Hs.eg.db::org.Hs.egENSEMBL)[match(unique(ensembl_id), ensembl_id)]'
		+ at line 210 found '        invisible(capture.output(rp_res <- RankProd::RankProducts(mtx,'
		+ at line 252 found '  roc_res <- try(pROC::roc(tr_slp ~ im, roc_data, levels = c("NO", "YES"), direction = "<"), silent = TRUE)'
		+ at line 257 found '    roc_thresh <- pROC::coords(roc_res, "best", best.method = "youden", transpose = TRUE)[1]'
	* In file R/zzz.R:
		+ at line 10 found 'if(getRversion() >= "2.15.1")  utils::globalVariables(c("."))'
- [ ] Important: `1:n` is not suggested in source code. Use `seq_along` or `seq.int` instead.
	* In file R/correlationSLP.R:
		+ at line 97 found '      .[1:topgene] %>%'
- [ ] NOTE: Vectorize: no unnecessary `for` loops present.
	* In file R/genie3.R:
		+ at line 67 found '        for (missing.gene.name in missing.gene.names) {'
		+ at line 93 found '  for (target.gene.idx in seq_len(ngene)) {'
- [ ] Important: Remove unused code.
	* In file R/genie3.R:
		+ at line 30 found '    # seed               = NULL,'
		+ at line 33 found '  # if (!is.null(seed)) set.seed(seed)'
- [ ] NOTE: Use `is.character/numeric/integer/logical` to replace `is(, "character/numeric/integer/logical")`
	* In file R/genie3.R:
		+ at line 75 found '  if (methods::is(K, "numeric")) {'
- [ ] NOTE: Functional programming: code repetition.
	* repetition in `comp_slp` and `corr_slp`
		+ in comp_slp
			- line 6:        V1]]
			- line 7:    if (is.null(mutgene)) {
			- line 8:        mutgene <- intersect(unique(mut_lite$mut_entrez), rownames(zscore_data))
			- line 9:    }
			- line 10:    else {
			- line 11:        mutgene <- intersect(unique(mutgene), rownames(zscore_data))
			- line 12:    }
			- line 13:    message("(==) Number of mutations: ", length(mutgene), ".")
			- line 14:    suppressPackageStartupMessages(res <- foreach(i = mutgene) %dopar% 
			- line 15:        {
			- line 20:    if (length(res) > 0) {
			- line 21:        res <- rbindlist(res)
			- line 22:        anno <- as.data.table(org.Hs.eg.db::org.Hs.egSYMBOL)[match(unique(symbol), 
			- line 23:            symbol)]
			- line 24:        res <- merge(res, anno, by.x = "mut_entrez", by.y = "gene_id", 
			- line 25:            all.x = TRUE) %>% setnames("symbol", "mut_symbol") %>% 
			- line 26:            merge(anno, by.x = "slp_entrez", by.y = "gene_id", 
			- line 27:                all.x = TRUE) %>% setnames("symbol", "slp_symbol") %>% 
			- line 28:            setcolorder(c("mut_entrez", "mut_symbol", "slp_entrez", 
			- line 29:                "slp_symbol", "pvalue", "fdr")) %>% .[order(fdr)]
			- line 30:        return(res)
			- line 31:    }
			- line 32:    else {
			- line 33:        message("(II) No potential SLPs from compensationModule.")
			- line 34:    }
		+ in corr_slp
			- line 5:    if (is.null(mutgene)) {
			- line 6:        mutgene <- intersect(unique(mut_data$mut_entrez), rownames(expr_data))
			- line 7:    }
			- line 8:    else {
			- line 9:        mutgene <- intersect(mutgene, rownames(expr_data))
			- line 10:    }
			- line 11:    message("(II) Number of mutations: ", length(mutgene), ".")
			- line 12:    suppressPackageStartupMessages(genie3_res <- foreach(i = mutgene) %dorng% 
			- line 13:        {
			- line 18:    if (length(genie3_res) > 0) {
			- line 19:        genie3_res <- rbindlist(genie3_res)
			- line 20:        anno <- as.data.table(org.Hs.eg.db::org.Hs.egSYMBOL)[match(unique(symbol), 
			- line 21:            symbol)]
			- line 22:        genie3_res <- merge(genie3_res, anno, by.x = "mut_entrez", 
			- line 23:            by.y = "gene_id", all.x = TRUE) %>% setnames("symbol", 
			- line 24:            "mut_symbol") %>% merge(anno, by.x = "slp_entrez", 
			- line 25:            by.y = "gene_id", all.x = TRUE) %>% setnames("symbol", 
			- line 26:            "slp_symbol") %>% setcolorder(c("mut_entrez", "mut_symbol", 
			- line 27:            "slp_entrez", "slp_symbol", "im")) %>% .[order(-im)]
			- line 28:        return(genie3_res)
			- line 29:    }
			- line 30:    else {
			- line 31:        message("(II) No potential SLPs from correlationModule.")
			- line 32:    }
## Documentation
- [ ] Important: Vignette should use `BiocStyle` package for formatting.
	* rmd file vignettes/mslp.Rmd
- [ ] Important: Vignette should have an *Introduction* section..
	* rmd file vignettes/mslp.Rmd
- [ ] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/mslp.Rmd
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/mslp.Rmd
- [ ] Important: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/mslp.Rmd
- [ ] NOTE: Please consider to add sample code to data preprocessing with `cBioPortalData` package.

**Comment by ccshao** [comment]
@jianhong  Many thanks for the quick feedbacks! I will update the thread addressing all issues.

**Comment by ccshao** [comment]
@jianhong I'm preparing commits and pushes for the above issues. Some of them are not clear to me, and it would be great to get your suggestions.

## Functional programming: code repetition
> NOTE: Functional programming: code repetition.
> repetition in comp_slp and corr_slp

I'm not sure what the problems is, while the codes try to use the intersect sets between mutgene and expression data
```
#- corr_slp, similar in comp_slp
  if (is.null(mutgene)) {
    #- Mutations detected in expression data.
    mutgene <- intersect(unique(mut_data$mut_entrez), rownames(expr_data))
  } else {
    #- Mutations given.
    mutgene <- intersect(mutgene, rownames(expr_data))
  }
...
```


## Vectorize: no unnecessary for loops
> NOTE: Vectorize: no unnecessary for loops present. 

Th codes capture the missing genes and print them out one by one. What is your suggestion for vectorization?
```

#- line 67
      missing.gene.names <- setdiff(input.gene.names, gene.names)
      if (length(missing.gene.names) != 0) {
        for (missing.gene.name in missing.gene.names) {
          message("Gene ", missing.gene.name, " was not in the expression matrix\n")
        }
...

#- line 93
  for (target.gene.idx in seq_len(ngene)) {
    if (trace) message("Computing gene ", target.gene.idx, "/", ngene, "\n")

    target.gene.name       <- gene.names[target.gene.idx]
    these.input.gene.names <- setdiff(input.gene.names, target.gene.name)

    x  <- expr.matrix[, these.input.gene.names]
...
 
```

Thanks!

**Comment by ccshao** [comment]
@jianhong I have tried to address all the issues, see the summary bellow. Let me know if there are questions, thanks!

## The DESCRIPTION file
R version should be no less than 4.2. 
Fixed.

## General package development
Important: Consider adding runnable examples
to man pages that documentexported
objects.

Add runnable examples for nearly all fucntions, while a few of exception are refered to the vigenette.

Important: Usage of dontrun{} / donttest{}
found in man page examples.7% of man
pages use one of these cases.
Deleted dontrun.

Important: Consider adding a NEWS file, so
your package news will be included in
Bioconductor release announcements.
news.md added.

Important: Consider adding unit tests. We
strongly encourage them.
Unit test added for two critial functions.

Important: All the format of function inputs should be checked.
Added codes to check input formats.


## R code
Important: No paste in message(), message, stop
Fixed.

NOTE: Try to search object via mget from org.Xx.egSYMBOL2EG or org.Xx.egALIAS2EG to search entrez id by symbol. 
Reply: as.data.table approach make it feasible for later merge steps, and I would like to keep it.

NOTE: :: is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to
Reply: manully double check the import items when you make any change in the DESCRIPTION file during development. 
Double checked.

Important: 1:n is not suggested in source code. Use seq_along or seq.int instead. 
Fixed.

NOTE: Vectorize: no unnecessary for loops present.
Unclear.

Important: Remove unused code. 
Fixed.

NOTE: Use is.character/numeric/integer/logical to replace is(, "character/numeric/integer/logical")
Fixed.

NOTE: Functional programming: code repetition.
Unclear.

## Documentation
Important: Vignette should use BiocStyle package for formatting. 
Fixed.

Important: Vignette should have an Introduction section.. 
Added.

Important: Vignette should have an Installation section.
Added.

Important: Please include Bioconductor installation instructions using BiocManager. 
Added.

Important: Vignette includes motivation for submitting to Bioconductor as part of the abstract/intro of the main vignette. 
Added.

NOTE: Please consider to add sample code to data preprocessing with cBioPortalData package.
Reply: Thanks for the nice suggestion. The cBioPortalData doesn't provide the same datasets as from website at the moment.
For example, **laml_mutations.tsv** provides by `cBioDataPack("laml_tcga_pan_can_atlas_2018", ask = FALSE)` has much less infomation than **data_mutations.txt** downloaded from the cbioportal website.

**Comment by jianhong** [comment]
# Package 'mslp' Review
Thank you for the updates. The package passed check and build. It is almost there. 

## R code
- [ ] NOTE: Vectorize: no unnecessary `for` loops present. Try to use functions like  `apply`, `vapply`, `lapply` or `mapply` to replace the loops. 
	* In file R/genie3.R:
		+ at line 63 found '        for (missing.gene.name in missing.gene.names) {'
		+ at line 88 found '  for (target.gene.idx in seq_len(ngene)) {'

- [ ] Important: Remove unused code.
	* In file R/genie3.R:
		+ at line 71 found '  # if (methods::is(K, "numeric")) {'
        
- [ ] NOTE: Functional programming: code repetition. Use helper function may help you to remove the repetition.

## Documentation
- [ ] Important: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/mslp.Rmd

**Comment by ccshao** [comment]
## R code

> NOTE: Vectorize: no unnecessary for loops present. Try to use functions like apply, vapply, lapply or mapply to replace the loops.

> at line 63 found ' for (missing.gene.name in missing.gene.names) {'

Fixed.

---
> at line 88 found ' for (target.gene.idx in seq_len(ngene)) {'

Reply: Here the `for` loop is better as the pre-defined output `weight.matrix` is updated for each of target.gene.idx with results `im`. See the codes bellow.

```
weight.matrix <- matrix(0.0, nrow = num.genes, ncol = num.genes)
weight.matrix[im.names, target.gene.name] <- im
```

---
> Important: Remove unused code.

> at line 71 found ' # if (methods::is(K, "numeric")) {'

Fixed

---
> NOTE: Functional programming: code repetition. Use helper function may help you to remove the repetition.

Rely: I would like to elabrate a little bit of the codes as they are not repetitive in my opinon, and helper function is already employed.
In `comp_slp`:

```
  #- Mutations are detected in the zscore data.
  if (is.null(mutgene)) {
    mutgene <- intersect(unique(mut_lite$mut_entrez), rownames(zscore_data))
  } else {
    mutgene <- intersect(unique(mutgene), rownames(zscore_data))
```
Get the interested genes for downstream analysis

```
  message("(==) Number of mutations: ", length(mutgene), ".")

  suppressPackageStartupMessages(
    res <- foreach(i = mutgene) %dopar% {
      fn_sub_comp_slp(i, zscore_data, mut_lite, positive_perc = positive_perc, p_thresh = p_thresh, ...)
    })
```
`fn_sub_comp_slp` is the helper function to perform the calculation for each genes.

```
  res[lengths(res) == 0] <- NULL

  if (length(res) > 0) {
    res <- rbindlist(res)

    anno <- as.data.table(org.Hs.eg.db::org.Hs.egSYMBOL)[match(unique(symbol), symbol)]
    res  <- merge(res, anno, by.x = "mut_entrez", by.y = "gene_id", all.x = TRUE) %>%
      setnames("symbol", "mut_symbol") %>%
      merge(anno, by.x = "slp_entrez", by.y = "gene_id", all.x = TRUE) %>%
      setnames("symbol", "slp_symbol") %>%
      setcolorder(c("mut_entrez", "mut_symbol", "slp_entrez", "slp_symbol", "pvalue", "fdr")) %>%
      .[order(fdr)]

    return(res)
  } else {
    message("(II) No potential SLPs from compensationModule.")
  }

```
If SLPs identified, aggregate the data and update the annotation. Only run once.

Similarly in `corr_slp`, `fn_sub_corr_slp` is the helper function and runs on each gene. The codes aftewards aggregate the results and only run once.
```
  if (is.null(mutgene)) {
    #- Mutations detected in expression data.
    mutgene <- intersect(unique(mut_data$mut_entrez), rownames(expr_data))
  } else {
    #- Mutations given.
    mutgene <- intersect(mutgene, rownames(expr_data))
  }

  message("(II) Number of mutations: ", length(mutgene), ".")

  suppressPackageStartupMessages(
    genie3_res <- foreach(i = mutgene) %dorng% {
      fn_sub_corr_slp(i, expr_data, mut_data, im_thresh, topgene, ...)
    })

  genie3_res[lengths(genie3_res) == 0] <- NULL

  if(length(genie3_res) > 0) {
    genie3_res <- rbindlist(genie3_res)
    anno       <- as.data.table(org.Hs.eg.db::org.Hs.egSYMBOL)[match(unique(symbol), symbol)]
    genie3_res <- merge(genie3_res, anno, by.x = "mut_entrez", by.y = "gene_id", all.x = TRUE) %>%
      setnames("symbol", "mut_symbol") %>%
      merge(anno, by.x = "slp_entrez", by.y = "gene_id", all.x = TRUE) %>%
      setnames("symbol", "slp_symbol") %>%
      setcolorder(c("mut_entrez", "mut_symbol", "slp_entrez", "slp_symbol", "im")) %>%
      .[order(-im)]

    return(genie3_res)
  } else {
    message("(II) No potential SLPs from correlationModule.")
  }
```

## Documentation

> Important: Vignette includes motivation for submitting to Bioconductor as part of the abstract/intro of the main vignette. 

Added.

Many thanks for your time and effort, looking forward to your opinions.

**Comment by ccshao** [comment]
@jianhong I have updated the pacakges with explanations on some codes, would you mind to offer your opinions? Many thanks!

see https://github.com/Bioconductor/Contributions/issues/2669#issuecomment-1162864243 for my comments.

**Comment by jianhong** [comment]
@ccshao 
Sorry for the late reply. 
Last thing for the package, please update the documents for data by adding such as `@usage data(compSLP)` to avoid the wrong usage section.

**Comment by ccshao** [comment]
@jianhong Thanks for your reply. The `usage` sections, as well as dataset names, were updated.

**Comment by jianhong** [comment]
Hi @ccshao,

I will mark the package as accepted. If possible, please consider to change the format of the example line utils.R:est_im line 185. Current line is wider than 100 characters and will be truncated in the PDF manual.

**Comment by ccshao** [comment]
@jianhong many thanks for your time and efforts! I have submitted a commit to address the issue of long code lines.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ccshao.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("mslp")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mslp

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
