### ISSUE TITLE
wiggleplotr

### ISSUE THREAD

**Issue by kauralasoo** [Bioconductor/Contributions#267]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kauralasoo/wiggleplotr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Thank you for your interest in Bioconductor. Please see the following comments: 

**build report warnings:** 
- [ ] change R version to 3.4 in description
- [ ] add a news file to keep track of large changes/announcements

**vignette:** 
- [ ] add installation and loading of package 
```
source("http://www.bioconductor.org/biocLite.R")
biocLite("wiggleplotr")
library(wiggleplotr)
```
- [ ] Visualizing RNA-seq read coverage: Can you fix the formatting of code it is hard to read and when I tried to run I needed a library(dplyr) with it 
- [ ] Downloading transcript metadata: make sure you are saving data in vignette to tempdir() - saveRDS(data, "transcript_metadata.rds")  
- [ ] Downloading the full transcript database from Ensembl:  Please make sure you are using the devel versions of all your packages.  from the NEWS file of GenomicFeatures: makeTranscriptDbFromBiomart does not exist anymore and was renamed in GenomicFeatures 1.20 makeTxDbFromBiomart()  
- [ ] Also at the very end finish the example, even if eval=FALSE show your function with the variables just described 

**man files:**
- [ ] probably should add a better description to the wiggleplotr.Rd - maybe a link to the main functions to use

**R code:**
- [ ] shortenIntrons.R: 
There is opportunity to improve code efficiency by avoiding 1:n iterations: 
shrinkIntronsCoverage: change 1:length(new_annot) to seq_len(new_annot) 
translateExonCoordinates: also has this structure 
- [ ] functions.R 
joinExons - is there a way to vectorize the for loop; it would be more efficient and speed up the code

Please push changes and then comment back here with how the above concerns have been addressed. Thank you and I look forward to hearing from you soon. 

Lori

**Comment by lawremi** [comment]
Would be nice if this supported TxDb objects directly (along with a gene selection) instead of requiring the user to extract the exons and cds's and pass the annotations separately. Also, it's probably worth accepting a SummarizedExperiment, since that can contain everything, with the CDSs as a meta column.

**Comment by lshep** [comment]
Yes those are excellent points and should be addressed as well @kauralasoo .  It would greatly increase the use-ability aspect of your package for many Bioconductor users.

**Comment by kauralasoo** [comment]
Dear Lori and Lawrence,

Thank you for the useful feedback. I've pushed the changes to the git repository, but there seems to be some delay in the package being rebuilt. In particular, I have made the following changes to address your comments:

**build report warnings:**

- [x]  change R version to 3.4 in description
- [x]  add a news file to keep track of large changes/announcements

**vignette:**
- [x]  add installation and loading of package

_Added corresponding sections to the start of the vignette._

- [x] Visualizing RNA-seq read coverage: Can you fix the formatting of code it is hard to read and when I tried to run I needed a library(dplyr) with it

_I reformatted code and added library(dplyr) to the beginning of the vignette._

- [x]  Downloading transcript metadata: make sure you are saving data in vignette to tempdir() - saveRDS(data, "transcript_metadata.rds")

_saveRDS now uses tempfile()._

- [x] Downloading the full transcript database from Ensembl: Please make sure you are using the devel versions of all your packages. from the NEWS file of GenomicFeatures: makeTranscriptDbFromBiomart does not exist anymore and was renamed in GenomicFeatures 1.20 makeTxDbFromBiomart()

_Changed the name of the function to makeTxDbFromBiomart()._

- [x] Also at the very end finish the example, even if eval=FALSE show your function with the variables just described

_I've now extended the example to show how the downloaded metadata can be used in the plotCoverage() function._

**man files:**
- [x]  probably should add a better description to the wiggleplotr.Rd - maybe a link to the main functions to use

_Good point! Added links to plotCoverage() and plotTranscripts() functions as well as instructions to open the vignette._

**R code:**
- [x]  shortenIntrons.R:
There is opportunity to improve code efficiency by avoiding 1:n iterations:
shrinkIntronsCoverage: change 1:length(new_annot) to seq_len(new_annot)
translateExonCoordinates: also has this structure

_Yes, I had forgotten about this. Replaced 1:length(x) with seq_along(x)._

- [ ]  functions.R
joinExons - is there a way to vectorize the for loop; it would be more efficient and speed up the code

_Thank you for the comment. I left this unchanged at the moment, mainly because this not likely to have any perceived difference for the user. The for loop iterates over transcripts of a gene which means that there is going be only a small number of iterations (1-15) per function call. Furthermore, when making coverage plots, vast majority of the time is spent on fetching read coverage from the BigWig files on disk._

**User interface**
- [ ] Would be nice if this supported TxDb objects directly (along with a gene selection) instead of requiring the user to extract the exons and cds's and pass the annotations separately.

_Thank you for the comment. I completely agree that it's a good practice to support standard Bioconductor objects as input. However, when I looked into the TxDb object created by makeTxDbFromBiomart() I noticed that it only contains the long and cryptic Ensembl gene id (e.g ENSG00000111912) and not the human-readable gene name (e.g. NCOA7). As a result, the user would still have to download the gene id to gene name mapping separately from biomart and supply it as an additional argument. Secondly, in addition to gene selection, there should also be an option for transcript selection, because many genes have a large number of transcripts (NCOA7 has 11) and the plots become cluttered very quickly. These two issues would effectively defeat the purpose of having a simpler interface. 
Finally, I would prefer not to add a large dependency (GenomicFeatures) to the package when it is not essential for it's main functionality. Just yesterday, I was unable to install GenomicFeatures on R 3.4.0, probably because of its dependence on sqlite and/or libcurl._

- [ ] Also, it's probably worth accepting a SummarizedExperiment, since that can contain everything, with the CDSs as a meta column.

_I'm not sure I follow you here. My impressions is that SummarizedExperiment is designed for 'matrix-like' objects (assays), but there is no matrix in my cases, there are only two lists of GRanges objects and a data frame with paths to BigWig files._

_Although now that I am thinking about, maybe I could simplify the interface by only requiring the exons argument (one list of GRanges objects) to be specified and make cdss and transcript_annotations arguments optional. In this case, if transcript_annotations is not supplied then the names of the exons GRanges list would ne used as labels on the plot. Do you think that would be useful?_

Thank you,
Kaur

**Comment by lawremi** [comment]
> As a result, the user would still have to download the gene id to gene name mapping separately from biomart and supply it as an additional argument. 

Then maybe an OrgDb object, which contains the gene symbols.

> Secondly, in addition to gene selection, there should also be an option for transcript selection, 

I think that's still easy to do.

> Finally, I would prefer not to add a large dependency (GenomicFeatures) to the package when it is not essential for it's main functionality.

Could be done via Suggests as long as you don't rely on dispatch, just simple reflection.

>  My impressions is that SummarizedExperiment is designed for 'matrix-like' objects (assays), but there is no matrix in my cases, there are only two lists of GRanges objects and a data frame with paths to BigWig files.

The coverage could be stored in a matrix, and it could be stored on disk, transparently, using DelayedArray. Right now, I think the only format is HDF5, but support for BigWig is a real possibility.

**Comment by lshep** [comment]
Hello.  Please see the following comments: 

**DESCRIPTION:** 
Change R to 3.4 instead of 3.3 

**VIGNETTE:** 
Downloading the full transcript database from Ensembl: 
save file to temporary directory
saveDb(txdb, "TranscriptDb_GRCh38_78.db")

**GENERAL**

*Although now that I am thinking about, maybe I could simplify the interface by only requiring the exons argument (one list of GRanges objects) to be specified and make cdss and transcript_annotations arguments optional. In this case, if transcript_annotations is not supplied then the names of the exons GRanges list would ne used as labels on the plot. Do you think that would be useful?*

Yes I think this would be an excellent idea.  It would allow more adaptability to your application and expand your audience.  
I think it is then still worth considering Michael's suggestions of the option to allow for TxDb object as well as SummarizedExperiment. While you argue it defeats the purpose of a simpler interface, I think you could still maintain the simple interface while allowing the program to be more flexible for a variety of user cases; Either through dispatch or wrapper functions that would convert the other formats to the needed simply interface arguments thereby leaving your main function relatively untouched. As they are highly used Bioconductor objects it would again branch out to more users.

**Comment by kauralasoo** [comment]
Hello. Thank you both for your helpful comments. I didn't know abut OrgDb, but you are right, I could write a wrapper function that takes TxDb, OrgDb and a list of gene or transcript ids as input and uses those to make transcript and read coverage plots. I also discovered just recently that there is ensembldb package that contains all of the required information (including gene names that are usually missing from TxDb objects). I'll write one or two wrapper functions to support these objects.

I still don't see the benefit of storing read coverage in SummarizedExperiment objects, though. Correct me if I'm wrong, but I am not aware of any Bioconductor package that produces SummarizedExperiment objects with read coverage inside. This matrix would by huge (3 billion rows) and you are right that it could be stored on disk using DelayedArray and HDF5. However, what would be in the rowData() slot then? A GRanges list with 3 billion elements, each one containing all of the transcripts that overlap a particular nucleotide? Maybe I am misunderstanding something, but this does not seem like the most efficient way of doing it. 

Kaur

**Comment by lshep** [comment]
That is a fair point. Please implement the others

**Comment by lawremi** [comment]
It would be easy to implement an efficient SummarizedExperiment for coverage. There is GPos for storing the `rowData()`. And Herve has an Rle-backed DelayedArray for in-memory convenience.

**Comment by lshep** [comment]
As we are getting closer to the spring release I just wanted to check in to see if you had any questions or updates to make sure you could get your package in this release cycle.

**Comment by kauralasoo** [comment]
Hello. I have now made the following changes:

- [x] Changed R version to 3.4
- [x] Save TxDb object to a temporary file.
- [x] Modified the plotTranscripts and plotCoverage functions so that they now work with just the exons GRanges list provided. The cdss and transcript_annotations arguments can still be provided, but they are now optional.
- [x] Added four wrapper functions to extract transcript annotations automatically from ensembldb and TxDb objects (plotTranscriptsFromEnsembldb, plotCoverageFromEnsembldb, plotTranscriptsFromUCSC, plotTranscriptsFromUCSC).
- [x] Updated documentation and vignette to reflect those changes. 

Let me know if you have any additional comments.

Best,
Kaur

P.S: Build currently fails on the Windows machine with  "there is no package called 'Biobase'" error. I don't think there's anything I can do about it.

**Comment by lshep** [comment]
Thank you for you updates. I think the wrappers will make an easier use case for users and reach a broader Bioconductor scope. 

Some Notes: 
- [ ] The Biobase windows error is on our end.  Since we are still in the processing of correcting we will ignore for now.  If there are other ERRORS once corrected we will expect these get corrected asap. 
- [ ] Please include Bioconductor installation instructions in your README as well, you may include your github as a link to development version and that the stable version is on Bioconductor. 
```
source("http://www.bioconductor.org/biocLite.R")
biocLite("wiggleplotr")
```

Otherwise looks good to me.   @lawremi, do you have any other comments?

**Comment by lshep** [comment]
I have marked your package as accepted but please consider the above comments. 
Please leave the issue open and you will receive svn credentials via email (normally within in a week) for inclusion in Bioconductor devel.

**Comment by kauralasoo** [comment]
Thanks! I have now updated the GitHub README to refer to Bioconductor as the main location to download the package.
