### ISSUE TITLE
(inactive) "CellSurvAssay" R package submission

### ISSUE THREAD

**Issue by PickeringLab** [Bioconductor/Contributions#2684]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PickeringLab/CellSurvAssay

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for your submission.  It does not interact with any Bioconductor resources or software.  But some of the pharmacogenomic packages might have data that would help illustrate value of your package?  Please have a look and respond on this issue.

**Comment by PickeringLab** [comment]
Hello @vjcitn,

Thank you very much for your comment.

Ours is only the second package which addresses Clonogenic Survival Analysis using R, and so we think this will add to the diversity of the tools within Bioconductor. We explained the purpose and utility of the package in the pkgdown website https://pickeringlab.github.io/CellSurvAssay/ , but just to explain:
1.	Our package is aimed to motivate more researchers performing Clonogenic Survival Analysis to use R. It uses the statistical models of the Bioconductor package CFAssay ([Bioconductor - CFAssay](https://bioconductor.org/packages/release/bioc/html/CFAssay.html)), but makes performing the steps simple, which will make more people interested in using R. Though CFAssay is available for a few years now, we have found that researchers performing this type of analysis are still using automated software and not very keen to switch to R.
2.	One complaint among researchers is that the automated software available provide much better figures, and R doesn’t. That’s why we provided a function that plots the figures using ggplot(), which will provide much better figures and allow more customization than what CFAssay provided. Also, plotting in ggplot() is not very easy for beginners, so we also made the function simple for them.
3.	Calculating Dose enhancement ratios are very useful and an essential step in this type of analysis, but not provided by any R package or automated software. We provided such a function as well.
4.	We also fixed a bug present in the CFAssay package.

As our package is targeted to this particular type of experiment, we don’t think we can use data from other pharmacogenomic packages to illustrate the value of our package. Is this a requirement that we must fulfil for our package to get accepted?

Thanks and regards,
@PickeringLab 

> Thanks for your submission. It does not interact with any Bioconductor resources or software. But some of the pharmacogenomic packages might have data that would help illustrate value of your package? Please have a look and respond on this issue.

**Comment by vjcitn** [comment]
```
> lqmodelFit 
function (data, ctype, method = "ml", PEmethod = "fit") 
{
    invisible(utils::capture.output(fit <- CFAssay::cellsurvLQfit(subset(data, 
        cline == ctype), method = method, PEmethod = PEmethod)))
    intro <- paste0("****** Cell type: ", ctype, " ******\n\n")
    end <- paste0("\n*** Analysis by CellSurvAssay v", utils::packageVersion("CellSurvAssay"), 
        " ***")
    cat(intro)
    print(fit)
    cat(end)
}
```
The value returned by the function is NULL.  Typically a fitting procedure returns a data structure with parameter estimates and their variability, metadata about the fitting request, which is then rendered to the user by a print method.  This function is a form of scripting that we don't happily endorse.  capture.output should not be necessary.  the cfa2way in CFAssay is somewhat more appropriately designed.  Can't the functions in CellSurvAssay simply be added to CFAssay?  The use of data.frame as opposed to a self-describing data structure like SummarizedExperiment seems to me a missed opportunity.  Why should this package be part of the Bioconductor ecosystem if all it is doing is providing interfaces to lm, glm etc.?  Seems more suited to CRAN.

**Comment by vjcitn** [comment]
Will you be working on this submission?  @lshep
