### ISSUE TITLE
EasyCellType

### ISSUE THREAD

**Issue by rx-li** [Bioconductor/Contributions#2687]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rx-li/EasyCellType

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
# Package 'EasyCellType' Review
Thank you for submition your package to Bioconductor. The package passed check and build.  However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.

## The DESCRIPTION file
- [ ] At least 3 sentences in `Description` field is required.
- [ ] R version should be no less than 4.2

## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 6 import(clusterProfiler)
	* in line 7 import(dplyr)
	* in line 8 import(forcats)
	* in line 9 import(ggplot2)
    
## General package development
- [ ] NOTE: Consider clarifying how 12 object(s) are
      initialized. Maybe they are part of a data set
      loaded with data(), or perhaps part of an
      object referenced in with() or within().
- [ ] Important: All parameters of a function need to be checked at the beginning of the function.

## R code
- [ ] NOTE: no direct slot access with `@` or `slot()` - accessors implemented and used.
	* In file R/process_results.R:
		+ at line 11 found '    enrich.re.l <- lapply(data, function(x) x@result)'
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development.
	* In file R/easyct.R:
		+ at line 47 found '  db.data.human <- db.data %>% dplyr::filter(spe == species)'
		+ at line 52 found '      dplyr::filter(organ %in% tissue) %>%'
		+ at line 53 found '      dplyr::select(celltype, entrezid)'
		+ at line 56 found '      dplyr::select(celltype, entrezid)'
	* In file R/plot_dot.R:
		+ at line 24 found '    enrich.d <- data.f %>% dplyr::group_by(cluster) %>% '
		+ at line 25 found '      dplyr::arrange(p.adjust) %>%'
		+ at line 26 found '      dplyr::slice(1:5)'
	* In file R/process_results.R:
		+ at line 18 found '      dplyr::group_by(cluster) %>%'
		+ at line 20 found '      dplyr::mutate(method = "hard_enrich")'
		+ at line 28 found '      dplyr::mutate(method = "hard_fisher") '
	* In file R/test_fisher.R:
		+ at line 25 found '    common_id <- base::intersect(testgenes[, paste(cols[1])], target_cell$entrezid)'
		+ at line 41 found '        dplyr::filter(cols[1] %in% common_id)'
- [ ] Important: `1:n` is not suggested in source code. Use `seq_along` or `seq.int` instead.
	* In file R/plot_bar.R:
		+ at line 26 found '      d <- d[1:10, ]'
	* In file R/plot_dot.R:
		+ at line 26 found '      dplyr::slice(1:5)'
		+ at line 29 found '      lapply(as.numeric(table(enrich.d$cluster)), function(x) size[1:x])'
		+ at line 44 found '      lapply(as.numeric(table(data.f$cluster)), function(x) size[1:x])'
	* In file R/process_results.R:
		+ at line 32 found '                                              na.last = TRUE), ][1:5, ]) %>% '
- [ ] NOTE: Vectorize: no unnecessary `for` loops present.
	* In file R/easyct.R:
		+ at line 63 found '    for (i in seq(length(data.l))) {'
		+ at line 72 found '    for (i in seq(length(data.l))) {'
	* In file R/test_fisher.R:
		+ at line 21 found '  for (i in seq(length(cellname))) {'
- [ ] Important: Remove unused code.
	* In file R/easyct.R:
		+ at line 31 found '  # loadRData <- function(fileName){'
		+ at line 33 found '  #   load(fileName)'
		+ at line 34 found '  #   get(ls()[ls() != "fileName"])'
		+ at line 35 found '  # }'
		+ at line 43 found '  #classes <- as.character(unlist(unique(data[, paste(cols[2])])))'

	* In file R/plot_dot.R:
		+ at line 37 found '            #axis.text.x=element_text(angle=45, hjust=1),'
		+ at line 52 found '            #axis.text.x=element_text(angle=45, hjust=1),'
- [ ] Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays.
	* In file R/easyct.R:
		+ at line 44 found '  data.l <- split(data, f=data[, paste(cols[2])])'
		+ at line 61 found '    input.l <- lapply(data.l, function(x) x[, paste(cols[3])])'
		+ at line 64 found '      names(input.l[[i]]) <- data.l[[i]][, paste(cols[1])]'
	* In file R/plot_bar.R:
		+ at line 26 found '      d <- d[1:10, ]'
		+ at line 54 found '  data.l_sort <- lapply(data.l, function(x) x[order(x$method, x$p.adjust),])'
		+ at line 57 found '    plot_one_cluster(data.l_sort_bar[[x]], names(data.l_sort_bar)[x]))'
	* In file R/process_results.R:
		+ at line 15 found '    enrich.d <- enrich.re.d[, c("ID", "p.adjust", "cluster")]'
	* In file R/test_fisher.R:
		+ at line 22 found '    target_cell <- ref[ref$celltype == cellname[i], ]'
		+ at line 25 found '    common_id <- base::intersect(testgenes[, paste(cols[1])], target_cell$entrezid)'
		+ at line 43 found '      score_f <- testgenes_f[, paste(cols[3])]'
## Documentation
- [ ] Important: Vignette includes `sessionInfo()`.
- [ ] Important: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
- [ ] Important: There is no runnable codes in vignettes.
- [ ] Important: The libraries loaded in vignettes are not listed as suggested packages.
- [ ] Important: The documentation for returns of functions need to be improved.
- [ ] Important: The documentation for description of functions are required.

**Comment by rx-li** [comment]
Thanks so much for your comments! Please find my responses below. 

## The DESCRIPTION file
- More words were added in the description field. 
- R version has been changed to 4.2.0.

## The NAMESPACE file
- Using `importFrom` instead of `import`.

## General package development
- I included `@importFrom rlang .data` to address this note. But there are still 6 objects that been pointed when running BiocCheck. I checked the variables, "spe", "organ", "celltype" and "entrezid" are from dataset loaded with data(). "ID" and "cluster" are from the `porcess_results` function in the package. 
- Including codes to check the parameters.

## R code
- Stopped using slot access with `@` in file R/process_results.R. Changed to `enrich.re.l <- lapply(results.c, function(x) x[seq(dim(x)[1]), drop=FALSE])`. 
- `::` has been removed.
- `1:n` has been changed to `seq.int`.
- Changed the 3 `for` loops to `lapply`.
- Unused data has been removed.
- Considering to add `drop=FALSE`:
  1. In file R/easyct.R:
   At line 71 (line 44 in the previous version), add `drop=FALSE` for `split`.
   At line 85 and 88 (line 61 and 64 in the previous version), I would like to have a dimension reduction. So I did not include `drop=FALSE` here. 
  2. In file R/plot_bar.R, add `drop=FALSE` at line 39, 67 and 70 (line 26, 54 and 57 in the previous version).
  3. In file R/process_results.R, add `drop=FALSE` at line 22 (line 16 in the previous version).
  4. In file R/test_fisher.R:
   At line 33 (line 22 in the previous version), add `drop=FALSE`
   At line 36 and 52 ( line 25 and 43 in the previous version), I did not include `drop=FALSE` here since I would like to reduce the data frame to a vector. 

## Documentation
- Added `sessionInfo()` right before the reference.  
- Added `motivation for submitting to Bioconductor` under the introduction of the main vignette.
- Added a data set under `data/`. All chunks in vignette should be runnable. But it might need some time to finish the analysis. 
- Added the libraries loaded in vignettes in suggested packages.
- Updated the returns of the functions. 
- Added description for the functions. 

Thanks again for your time!

**Comment by jianhong** [comment]
@rx-li,

Thank you for your answers. Could you please push the changes to git.bioconductor.org?
Please read [this documentation](http://contributions.bioconductor.org/git-version-control.html#new-package-workflow) for setting
up remotes to push to git.bioconductor.org. It is required to push a
version bump to git.bioconductor.org to trigger a new build.

**Comment by rx-li** [comment]
@jianhong,

Hi! Thanks for letting me know. I have pushed the changes to git.bioconductor.org. Please let me know if you find any questions.

**Comment by jianhong** [comment]
@rx-li ,

Could you please also update your version number to trigger a builder? After that I can start my review.

**Comment by rx-li** [comment]
@jianhong 

Thanks for letting me know! I have updated the version number.

**Comment by rx-li** [comment]
I think I have subscribed to the bioc-devel mailing list...

**Comment by jianhong** [comment]
please try to bump up the version number again to confirm the issue.

Best!

Your sincerely,

Jianhong Ou

**Comment by rx-li** [comment]
@jianhong 
Just bumped. Thanks so much.

**Comment by jianhong** [comment]
# Package 'EasyCellType' Review
The package passed check and build. It is almost there. 

## The DESCRIPTION file
- [ ] Important: 'LazyData:' in the 'DESCRIPTION' should be set to false or removed
- [ ] Note: Malformed Title field: should not end in a period.

## R code
- [ ] Note: try to use `match.arg` or `stopifnot` to replace the codes 'if(!xxx %in% yyy)' for arguments check. 
    * In file R/easyct.R:
        + at line 39 found '  if(!is.data.frame(data)){'
        + at line 40 found '    stop("Input should be a data frame")'
        + at line 42 found '  if(!db %in% c("cellmarker", "panglao", "clustermole")){'
        + at line 43 found '    stop("The database should be chosen from cellmarker, panglao and clustermole.")'
        + at line 45 found '  if(!species %in% c("Human", "Mouse")){'
        + at line 46 found '    stop("The speices should be either Human or Mouse.")'
        + at line 48 found '  if(!test %in% c("GSEA", "fisher")){'
        + at line 49 found '    stop("The test should be specified as GSEA or fisher.")'
        + at line 51 found '  if(!scoretype %in% c("std", "pos", "neg")){'
        + at line 52 found '    stop("The score type should be chosen from std, pos and neg.")'
        + at line 54 found '  if(!is.numeric(p_cut)){'
        + at line 55 found '    stop("Cutoff of p value should be a number")'
        + at line 64 found '  if(length(tissue) > 0 && mean(tissue %in% unique(db.data.human$organ)) != 1){'
        + at line 65 found '    stop("Please refer the tissue types using data(cellmarker_tissue), '
    * In file R/plot_bar.R:
        + at line 29 found '  if(!test %in% c("GSEA", "fisher")){'
        + at line 30 found '    stop("The test should be specified as GSEA or fisher.")'
        + at line 32 found '  if(is.null(data)){'
        + at line 33 found '    stop("Data should be annotation results")'
    * In file R/plot_dot.R:
        + at line 26 found '  if(!test %in% c("GSEA", "fisher")){'
        + at line 27 found '    stop("The test should be specified as GSEA or fisher.")'
        + at line 29 found '  if(is.null(data)){'
        + at line 30 found '    stop("Annotation results should be specified.")'
    * In file R/process_results.R:
        + at line 15 found '  if(!test %in% c("GSEA", "fisher")){'
        + at line 16 found '    stop("The test should be specified as GSEA or fisher.")'
        + at line 18 found '  if(is.null(data)){'
        + at line 19 found '    stop("Annotation results should be specified.")'
    * In file R/test_fisher.R:
        + at line 16 found '  if(!is.data.frame(testgenes)){'
        + at line 17 found '    stop("Input data should be a data frame")'
        + at line 19 found '  if(is.null(ref)){'
        + at line 20 found '    stop("Reference database should be specified")'
        + at line 22 found '  if(length(cols) != ncol(testgenes)){'
        + at line 23 found '    stop("Dimension does not match; Check the input data frame and column names")'
        
- [ ] NOTE: Consider clarifying how 8 object(s)
          are initialized. Maybe they are part of a
          data set loaded with data(), or perhaps
          part of an object referenced in with() or
          within().
          easyct: no visible binding for global variable ‘spe’
            easyct: no visible binding for global variable ‘organ’
            easyct: no visible binding for global variable ‘celltype’
            easyct: no visible binding for global variable ‘entrezid’
            plot_bar : plot_one_cluster: no visible binding for global variable
              ‘ID’
            plot_dot: no visible binding for global variable ‘cluster’
            plot_dot: no visible binding for global variable ‘ID’
            process_results: no visible binding for global variable ‘cluster’
            Undefined global functions or variables:
              ID celltype cluster entrezid organ spe

**Comment by rx-li** [comment]
Thanks so much for your comments. 
Please find my responses below.

## The DESCRIPTION file
- Removed LazyData.
- Removed the period in the title.

## R code
- In file R/easyct.R: Modified all codes for parameter checking. Using `stopifnot` now.
- In file R/plot_bar.R: Modified all codes for parameter checking. Using `stopifnot` now.
- In file R/plot_dot.R: Modified all codes for parameter checking. Using `stopifnot` now.
- In file R/process_results.R: Modified all codes for parameter checking. Using `stopifnot` now.
- In file R/test_fisher.R: Modified all codes for parameter checking. Using `stopifnot` now.

- The NOTE has been addressed by using `.data`.

Thanks for your help again, and please feel free to let me know if you have any other questions.

**Comment by jianhong** [comment]
I got some warning during check:

```
 Variables with usage in documentation object 'cellmarker_tissue' but not in code:
  ‘cellmarker_tissue’
```

Could you please try to follow [this](https://stackoverflow.com/questions/57396392/warning-variables-with-usage-in-documentation-object-fang-but-not-in-code) direction to update your help files?

**Comment by rx-li** [comment]
@jianhong 
Thanks for the insight. I just updated the files.

**Comment by rx-li** [comment]
Thanks so much for your help on the package building.

I am wondering if you can provide a Bioconductor repo link of our package?

Best regards,
Ruoxing

**Comment by lshep** [comment]
You can use a package short url that will default to the devel version package landing page until released and then always redirect to the most current released version:  https://bioconductor.org/packages/EasyCellType   .  It is not activate yet but will be within the next 48 hours that also provides links to the git repo https://git.bioconductor.org/packages/EasyCellType     ( or   git@git.bioconductor.org:packages/EasyCellType  for developers)

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/rx-li.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("EasyCellType")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EasyCellType

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
