### ISSUE TITLE
fgsea

### ISSUE THREAD

**Issue by assaron** [Bioconductor/Contributions#27]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ctlab/fgsea

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Your package looks great. Some minor suggestions below. 

R

- code looks good
- since a data.frame is universally understood by R users, but a
  data.table is not, consider coercing return values to data.frame.

vignette

- Rather than using `structure(..., names=...)`, consider `setNames()`
- Consider adding a 'Modified' date in addition to the automatically
  generated compliation date

man

- Provide more extensive description of example data sets, including
  how they were generated / how the user could generate them.
- Typo in exampleRanks 'gene-level'
- in the @return field document the nature of the return value, e.g.,
  data.table with columns ...

src

- good

tests

- nice to see; they look good!

**Comment by assaron** [comment]
Martin, thanks for the quick review. I've fixed everything you mentioned except the issue with data.table. Do you think it would realy better to return data.frame? data.table is not universal but, I believe, is pretty standard, it has a very similar interface to data.frame and actually is a data.frame subclass. In principle, I can add a `DT` argument to `fgsea` which will control whether data.table or data.frame should be returned, with data.frame being default.

**Comment by mtmorgan** [comment]
@assaron I'll leave it up to you.

As a final issue, `example(fgsea)` creates a result `fgseeaRes1`, but this does not display

```
> fgseaRes1
> (fgseaRes1)
                    pathway      pval      padj        ES       NES
1: 1221633_Meiotic_Synapsis 0.5448895 0.5448895 0.2885754 0.9397868
   nMoreExtreme size
1:         3155   27
```

Can this be addressed?

**Comment by assaron** [comment]
@mtmorgan I'd leave it is as is then. The printing issue should be fixed now.

**Comment by assaron** [comment]
@mtmorgan Thanks! So, what are my next steps?

**Comment by mtmorgan** [comment]
The package will be added to our svn repository and nightly build (the issue will then be close); you'll be notified several days after that with svn credentials and additional information.

**Comment by assaron** [comment]
@mtmorgan  sorry to bother you, but I haven't received the svn credentials. Is this OK?

**Comment by mtmorgan** [comment]
On 07/04/2016 06:50 AM, Alexey Sergushichev wrote:
> @mtmorgan <https://github.com/mtmorgan> sorry to bother you, but I
> haven't received the svn credentials. Is this OK?

yes, the process is backed up but expect credentials shortly.

>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Bioconductor/Contributions/issues/27#issuecomment-230263073>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAHPGNtxs2kw4FD_XRYmO5VUDyYAZPoIks5qSOVugaJpZM4I7H7K>.
>


This email message may contain legally privileged and/or confidential information.  If you are not the intended recipient(s), or the employee or agent responsible for the delivery of this message to the intended recipient(s), you are hereby notified that any disclosure, copying, distribution, or use of this email message is prohibited.  If you have received this message in error, please notify the sender immediately by e-mail and delete this email message from your computer. Thank you.
