### ISSUE TITLE
(inactive) Submission of the "phenomis" package for post-processing and univariate analysis of omics data

### ISSUE THREAD

**Issue by ethevenot** [Bioconductor/Contributions#2704]
Dear Bioconductor team,

Please find below the GitHub link to the "phenomis" package that we would like to submit to Bioconductor.

The package provides methods for the post-processing (quality control, normalization), univariate hypothesis testing, clustering, and annotation of omics single or multiple datasets. It is mainly focused on metabolomics data but applications to proteomics and transcriptomics data are described in the vignette.

The package complements the "ropls" and "biosigner" Bioconductor packages, which focus on downstream multivariate analysis and feature selection. These 3 packages therefore enables to design comprehensive statistical and annotation workflows, as described in the vignette for single and multiple omics data sets. All of these 3 packages support the SummarizedExperiment and MultiAssayExperiment formats, but also the ExpressionSet and MultiDataSet formats.

We thank you in advance for reviewing the package.

Best Regards,

Etienne.

The remaining notes from the checks are commented below:

I. R CMD check: 1 note

1) N  checking for non-standard things in the check directory
   Found the following files/directories:
     'met_dataMatrix.tsv' 'met_sampleMetadata.tsv'
     'met_variableMetadata.tsv' 'metabo' 'pro_dataMatrix.tsv'
     'pro_sampleMetadata.tsv' 'pro_variableMetadata.tsv' 'prometis'
	 
This files/directories are generated in the examples of the "writing" method (note that the
\dontrun{} has been modified to \donttest{} according to the Bioconductor guidelines).

II. R CMD BiocCheck: 8 notes

1) NOTE: Consider adding these automatically suggested biocViews: Sequencing, Coverage, KEGG

"BatchEffect" has been included as previously suggested. These remaining suggestions, however, are not relevant.

2) NOTE:  Avoid 'cat' and 'print' outside of 'show' methods

There is no call to 'cat'. The very few calls to 'print' provide useful summaries which cannot be
provided by the 'message' function.

3) NOTE:  Avoid the use of 'paste' in condition signals

The very few uses of 'paste' provide the users with useful hints to address the raised issues.

4) NOTE: Recommended function length <= 50 lines.There are 56 functions > 50 lines.

We did our best to shorten the function code.

5) NOTE: Usage of dontrun{} / donttest{} found in man page examples.12% of man pages use one of these cases.

Annotating examples requiring to query the ChEBI database may take about 1 min and fail if the database is 
unavailable for some reason. In addition, examples with the "writing" method have been flagged with 'donttest'
to avoid writing on the user file disk.

6) NOTE: Consider shorter lines; 830 lines (7%) are > 80 characters long.

Again, we did our best to follow this recommendation.

7) NOTE: Consider multiples of 4 spaces for line indents; 5006 lines (44%) are not.

I must admit that I am used to the 2 spaces which I find provides a clear view
of the indentations (and is the default with RStudio). Because I do not think that
there is an automated way to swith all the code to 4 spaces, I would prefer to stick
to this display in the package if possible

8) NOTE: Cannot determine whether maintainer is subscribed to the Bioc-Devel mailing list (requires admin credentials).

I am member of the Bioc-Devel mailing list as a maintainer of the ropls and biosigner Bioconductor packages.

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/odisce/phenomis

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by ethevenot** [comment]
The package version number has now been formatted to 0.99.0

**Comment by lshep** [comment]
Please resubmit as a new issue so other pre-checks can be passed/performed.

**Comment by ethevenot** [comment]
Thank you. I have resubmitted to issue #2705. It thought that the 0.99.0 was not mandatory anymore for the package submission.

**Comment by lshep** [comment]
0.99.0 is mandatory for all new Bioconductor packages with very few exceptions
