### ISSUE TITLE
Submission of the new "phenomis" package for postprocessing and univariate analysis of omics data

### ISSUE THREAD

**Issue by ethevenot** [Bioconductor/Contributions#2706]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/odisce/phenomis

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
This is what the first comment was edited with; please create NEW issues to provide your content in response to review.
```
Dear Bioconductor team,

Please find below the GitHub link to the "phenomis" package that we would like to submit to Bioconductor.

The package provides methods for the post-processing (quality control, normalization), univariate hypothesis testing, clustering, and annotation of omics single or multiple datasets. It is mainly focused on metabolomics data but applications to proteomics and transcriptomics data are described in the vignette.

The package complements the "ropls" and "biosigner" Bioconductor packages, which focus on downstream multivariate analysis and feature selection. These 3 packages therefore enables to design comprehensive statistical and annotation workflows, as described in the vignette for single and multiple omics data sets. All of these 3 packages support the SummarizedExperiment and MultiAssayExperiment formats, but also the ExpressionSet and MultiDataSet formats.

We thank you in advance for reviewing the package.

Best Regards,

Etienne.

The remaining notes from the checks are commented below:

I. R CMD check: 1 note

1) N  checking for non-standard things in the check directory
   Found the following files/directories:
     'met_dataMatrix.tsv' 'met_sampleMetadata.tsv'
     'met_variableMetadata.tsv' 'metabo' 'pro_dataMatrix.tsv'
     'pro_sampleMetadata.tsv' 'pro_variableMetadata.tsv' 'prometis'
	 
This files/directories are generated in the examples of the "writing" method (note that the
\dontrun{} has been modified to \donttest{} according to the Bioconductor guidelines).

II. R CMD BiocCheck: 8 notes

1) NOTE: Consider adding these automatically suggested biocViews: Sequencing, Coverage, KEGG

"BatchEffect" has been included as previously suggested. These remaining suggestions, however, are not relevant.

2) NOTE:  Avoid 'cat' and 'print' outside of 'show' methods

There is no call to 'cat'. The very few calls to 'print' provide useful summaries which cannot be
provided by the 'message' function.

3) NOTE:  Avoid the use of 'paste' in condition signals

The very few uses of 'paste' provide the users with useful hints to address the raised issues.

4) NOTE: Recommended function length <= 50 lines.There are 56 functions > 50 lines.

We did our best to shorten the function code.

5) NOTE: Usage of dontrun{} / donttest{} found in man page examples.12% of man pages use one of these cases.

Annotating examples requiring to query the ChEBI database may take about 1 min and fail if the database is 
unavailable for some reason. In addition, examples with the "writing" method have been flagged with 'donttest'
to avoid writing on the user file disk.

6) NOTE: Consider shorter lines; 830 lines (7%) are > 80 characters long.

Again, we did our best to follow this recommendation.

7) NOTE: Consider multiples of 4 spaces for line indents; 5006 lines (44%) are not.

I must admit that I am used to the 2 spaces which I find provides a clear view
of the indentations (and is the default with RStudio). Because I do not think that
there is an automated way to swith all the code to 4 spaces, I would prefer to stick
to this display in the package if possible

8) NOTE: Cannot determine whether maintainer is subscribed to the Bioc-Devel mailing list (requires admin credentials).

I am member of the Bioc-Devel mailing list as a maintainer of the ropls and biosigner Bioconductor packages.




```

**Comment by ethevenot** [comment]
Dear Bioconductor Team,

I keep receiving this warning regarding the size of the vignette, although the size I have is 3.3 MB. I do not know why there is a difference (linux vs windows?), what is the actual size of the vignette on your side (the warning only says "above 5MB"), and how I could reduce the size (the vignette does not appear particularly big on my size). I have already reduced the number of figures and their sizes. I would appreciate some help from your side. I thank you very much in advance.
Best Regards,
Etienne.

**Comment by nturaga** [comment]
Hi @ethevenot Please issue a new build report by bumping the version number.

There are many NOTEs you can fix in the build report quite easily.

**Comment by nturaga** [comment]
# Review

## DESCRIPTION

ok

## NAMESPACE

ok

## NEWS

ok

## vignette

Good! 

## Tests

Good! 

## R

- End user messages as given in the NOTEs on the 
'BiocCheck::BiocCheck()' function should be corrected. 

- Good examples cases! 

- BiocCheck complains about the spacing in the code,
  but you can ignore this. It's well written. If you are able to
  follow it, that's fine. 

- Lots of "magic numbers" in the function arguments. Be 
  sure to explain why some values are set the way they are
  as defaults for the arguments.

**Comment by ethevenot** [comment]
Dear Bioconductor reviewer,

We are pleased to submit our revised version of the package in addition to our responses to your comments below.

We thank you in advance for reviewing this revised package and we hope that this new version will now be accepted in Bioconductor.

Etienne Thévenot.

Responses to the comments:

1) There are many NOTEs you can fix in the build report quite easily.

The code has been reformatted thoroughly to address all NOTEs. In particular the largest functions have been refactorized, the 80 character line rule was followed in all possible cases, and the messages have been cleaned.

The three remaining NOTES from the 'BiocCheck::BiocCheck()' function are discussed below:

  1.1) NOTE: Recommended function length <= 50 lines. There are 69 functions > 50 lines.

All functions larger than 200 lines have been refactorized to facilitate the reading of the code. The longest function has now < 185 lines.

  1.2) NOTE: Usage of dontrun{} / donttest{} found in man page examples. 12% of man pages use one of these cases.

There are 4 calls to donttest (2 in the examples from the annotating method and 2 in the examples from the writing method), which are motivated by the following reasons: "annotating" examples requiring to query the ChEBI database may take about 1 min and fail if the database is unavailable for some reason. In addition, examples with the "writing" method have been flagged with 'donttest' to avoid writing on the user file disk.

  1.3) NOTE: Consider shorter lines; 359 lines (3%) are > 80 characters long.

All files were manually parsed to shorten the lines. The remaining lines which are > 80 characters long often result from the usage of the package name in front of the function name to facilitate the reading of the code (package_name::function_name).

2) Lots of "magic numbers" in the function arguments. Be sure to explain why some values are set the way they are as defaults for the arguments.

All method/function documentations were checked and completed, e.g. to detail the meaning of parameters or their default values which may be less familiar to people outside the metabolomics/proteomics community (in particular in the 'annotating', 'inspecting', and 'reducing' methods).

**Comment by nturaga** [comment]
Hi @lshep / @vjcitn  FWIW, I can no longer change the label to "Accepted" on this package. 

Please do so. It passes all the checks, and the code is in good standing. I am ready to accept this package.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ethevenot.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("phenomis")`. The package 'landing page' will be created at

https://bioconductor.org/packages/phenomis

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
