### ISSUE TITLE
Submit HDO.db package

### ISSUE THREAD

**Issue by huerqiang** [Bioconductor/Contributions#2734]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YuLab-SMU/HDO.db

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for submission, but please look at your compiled vignette.  Vignette is not demonstrative.  Should show some results like
```
> head(DOTERM)
         do_id                     Term
1 DOID:0001816             angiosarcoma
2 DOID:0002116                pterygium
3 DOID:0014667    disease of metabolism
4 DOID:0040001           shrimp allergy
5 DOID:0040002          aspirin allergy
6 DOID:0040003 benzylpenicillin allergy
```
You should also reflect some of the metadata in the vignette, such as the version of HDO.

**Comment by huerqiang** [comment]
@vjcitn Thanks. We have updated the vignette.

**Comment by vjcitn** [comment]
When I compile your package and look at vignette this is what I see:
![hdo](https://user-images.githubusercontent.com/4624066/183612271-4d56d72d-579c-453a-aa84-da5cf3eb3402.jpg)

please make this a document that a user will be able to learn from.  It should start with a prose
paragraph indicating your purpose in contributing the package to Bioconductor.  It would be nice
if it indicated the scientific value with a narrated example.  It would also be appropriate to give a
sense of the hierarchy perhaps with a screenshot like

![obopic](https://user-images.githubusercontent.com/4624066/183616270-abd223ce-574c-4e66-8dbe-6628e74cd144.jpg)

**Comment by huerqiang** [comment]
@vjcitn Thank you for your suggestion, we have completed the relevant changes.

**Comment by huerqiang** [comment]
@vjcitn Hi, we have completed the revision for a few days, is it possible to proceed further? Please see if there are any other issues, thanks.

**Comment by vjcitn** [comment]
While I am passing this package, it is using obsolete methods.  
```
> GO.db
GODb object:
| GOSOURCENAME: Gene Ontology
| GOSOURCEURL: http://current.geneontology.org/ontology/go-basic.obo
| GOSOURCEDATE: 2022-03-10
| Db type: GODb
| package: AnnotationDbi
| DBSCHEMA: GO_DB
| GOEGSOURCEDATE: 2022-Mar17
| GOEGSOURCENAME: Entrez Gene
| GOEGSOURCEURL: ftp://ftp.ncbi.nlm.nih.gov/gene/DATA
| DBSCHEMAVERSION: 2.1

Please see: help('select') for usage information
> HDO.db
Error: object 'HDO.db' not found
No suitable frames for recover()
```
The AnnotationDbi approaches are not used.  The vignette uses as.list and toTable instead of select().  We
need to update our contribution guidelines to ensure updated methods are used.

**Comment by vjcitn** [comment]
This is also somewhat confusing:
```
> DO.db::DO()
Quality control information for DO:


This package has the following mappings:

DOANCESTOR has 6569 mapped keys (of 11002 keys)
DOCHILDREN has 1811 mapped keys (of 2279 keys)
DOOBSOLETE has 2374 mapped keys (of 2374 keys)
DOOFFSPRING has 1811 mapped keys (of 2279 keys)
DOPARENTS has 6569 mapped keys (of 11003 keys)
DOTERM has 6570 mapped keys (of 11003 keys)


Additional Information about this package:

DB schema: DO_DB
DB schema version: 1.0
> HDO.db::DO()
Quality control information for DO:


This package has the following mappings:

DOANCESTOR has 66768 mapped keys (of 11002 keys)
DOCHILDREN has 11034 mapped keys (of 2279 keys)
DOOFFSPRING has 66768 mapped keys (of 2279 keys)
DOPARENTS has 11034 mapped keys (of 11003 keys)
DOTERM has 11003 mapped keys (of 11003 keys)


Additional Information about this package:

DB schema: DO_DB
DB schema version: 2.0
```
maybe use HDO()?

**Comment by huerqiang** [comment]
@vjcitn The HDO.db now support `select()` interface and we have changed `DO()` to `HDO()`.
![image](https://user-images.githubusercontent.com/48857018/186753437-eeb33b69-b54f-46db-bf69-0edccdbec796.png)

**Comment by huerqiang** [comment]
@vjcitn Hi, has this package entered the review process?

**Comment by vjcitn** [comment]
there is a sqlite file in your package exceeding size 5mb   i am deliberating hiw to proceed   need a few more days

**Comment by vjcitn** [comment]
I am sorry to be taking so long with this.  You have done a good job of emulating the GO.db and using the AnnotationDbi methods.  I am still conflicted with the question of how to handle ontologies in Bioconductor.  https://obofoundry.org/ontology/doid.html shows that this resource is frequently updated.  The "traditional annotation" package processing is not ideal, but maybe we should do this for now.  It allows the >5MB file, right @lshep ?  Let's go along this route if that works.

**Comment by lshep** [comment]
Yes. For a "traditional annotation" package that contains large files, the package can be reviewed here but the package will not be added to the git.bioconductor.org echosystem.  The package will have to be manually uploaded by a team member any time there is an update to the package.  The other alternative is to convert it to an annotationhub package and utilize that interface instead of having the large data file present in the package directly.

**Comment by huerqiang** [comment]
@lshep Hi, how is the review progress of this package, do I need to make any changes?

**Comment by Kayla-Morrell** [comment]
@huerqiang - The package has been added to our devel builder and the script to make it available is currently running. It should finish in the next couple of hours and then the package will be available in the devel version of Bioconductor. Thank you for your contribution!
