### ISSUE TITLE
crisprViz

### ISSUE THREAD

**Issue by Jfortin1** [Bioconductor/Contributions#2736]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Jfortin1/crisprViz

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Kayla-Morrell** [comment]
@Jfortin1 - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: README installation instructions should also include Bioconductor
  installation instructions. For the .Rmd file these instructions should be
included in an `eval = FALSE` code chunk.

## DESCRIPTION

- [ ] SUGGESTION: I see 'testthat' listed under Suggests but you don't have any
  unit tests. I would suggest removing this package or adding in unit tests.

## Data

- [ ] REQUIRED: Could you add a bit of source information to the two Ideogram
  data files? Where does this data come from?
- [ ] REQUIRED: I didn't see the Ideogram datasets used in the vignette or in
  code. Are these actually used somewhere? 

## Vignette

- [ ] REQUIRED: The installation sections needs to show users how to download
  and load the package from Bioconductor, not github. This code can be included
in an `eval = FALSE` code chunk.
- [ ] REQUIRED: The figure in the figures directory is not referenced in the
  vignette. It should be removed if not used.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests.We strongly encourage them. See
  https://contributions.bioconductor.org/tests.html.

## R code

- [ ] SUGGESTION: Avoid `suppressWarnings`/`*Messages` if possible (found 4 times)
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 42 
lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 263 lines that are not.

Best,
Kayla

**Comment by Jfortin1** [comment]
Thank you Kayla for your review @Kayla-Morrell. Please find below my comments.

Best,
JP 


 ## General package development
 * [x]  REQUIRED: README installation instructions should also include Bioconductor
   installation instructions. For the .Rmd file these instructions should be
   included in an `eval = FALSE` code chunk.

**Done.**
 
 ## DESCRIPTION
 * [x]  SUGGESTION: I see 'testthat' listed under Suggests but you don't have any
   unit tests. I would suggest removing this package or adding in unit tests.

**We have now added unit tests.**
 
 ## Data
 * [x]  REQUIRED: Could you add a bit of source information to the two Ideogram
   data files? Where does this data come from?
 * [x]  REQUIRED: I didn't see the Ideogram datasets used in the vignette or in
   code. Are these actually used somewhere?

**Great catch, we have now removed those files as they are irrelevant to the current version of the package.**
 
 ## Vignette
 * [x]  REQUIRED: The installation sections needs to show users how to download
   and load the package from Bioconductor, not github. This code can be included
   in an `eval = FALSE` code chunk.

**Done.**

 * [x]  REQUIRED: The figure in the figures directory is not referenced in the
   vignette. It should be removed if not used.

**Indeed, now removed.**
 
 ## Unit tests
 * [x ]  SUGGESTION: Consider adding unit tests.We strongly encourage them. See
   https://contributions.bioconductor.org/tests.html.

**Thanks for the suggestion, we have now added unit tests.**
 
 ## R code
 * [x]  SUGGESTION: Avoid `suppressWarnings`/`*Messages` if possible (found 4 times)

**Necessary for not-so-useful warnings from external packages.**
 
 * [x]  SUGGESTION: For formatting reasons, consider shorter lines. There are 42
   lines that are  80 characters long.

**Done, besides a couple of lines that have long urls.**

 * [x]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
   line indents. There are 263 lines that are not.

**Our (unpopular) indentation style for function parameters across our R packages is to align with the opening bracket, causing this BiocCheck warning.**

**Comment by Jfortin1** [comment]
Hi Kayla @Kayla-Morrell, is there anything else that I need to do from my side for this review?

Best,
JP

**Comment by Kayla-Morrell** [comment]
Hello JP @Jfortin1 - I'm currently wrapping up an initial review of a multiple package submission which has used up the majority of my time. I'll work on reviewing the changes you made and get back to you in the next couple days. Sorry for the delay.

Best,
Kayla

**Comment by Jfortin1** [comment]
Thanks @Kayla-Morrell for the heads up!

**Comment by Kayla-Morrell** [comment]
@Jfortin1 - Thank you again for your patience and making the necessary changes. I have looked everything over and it all looks good. I'm more than happy to accept that package.

Best,
Kayla

**Comment by Jfortin1** [comment]
Thank you @Kayla-Morrell !

**Comment by Jfortin1** [comment]
Would it be possible to add the package to the nightly builds sometime this week? Thank you!

**Comment by lshep** [comment]
I'm very sorry for the delay. I will be ingesting packages later this afternoon and it should be on the nightly builds within 48 hours.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jfortin1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("crisprViz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/crisprViz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
