### ISSUE TITLE
iSEEhub

### ISSUE THREAD

**Issue by kevinrue** [Bioconductor/Contributions#2749]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/iSEE/iSEEhub/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```'
Do you really want all these in Suggests:

Packages suggested but not available:
  'BioPlex', 'bodymapRat', 'CLLmethylation', 'CopyNeutralIMA', 'covr',
  'curatedAdipoArray', 'curatedAdipoChIP', 'curatedMetagenomicData',
  'curatedTCGAData', 'DuoClustering2018', 'easierData', 'emtdata',
  'FieldEffectCrc', 'GSE103322', 'GSE13015', 'GSE62944', 'HDCytoData',
  'HMP16SData', 'HumanAffyData', 'imcdatasets', 'mcsurvdata',
  'MetaGxBreast', 'MetaGxOvarian', 'MetaGxPancreas', 'MethylSeqData',
  'muscData', 'ObMiTi', 'quantiseqr', 'restfulSEData', 'RLHub',
  'sesameData', 'SimBenchData', 'SingleCellMultiModal',
  'spatialDmelxsim', 'STexampleData', 'TabulaMurisData',
  'TENxVisiumData', 'tissueTreg', 'VectraPolarisData'
```
maybe Enhances would be better?  For Check to succeed without changing environment, all those are needed?

**Comment by kevinrue** [comment]
`Enhances` sounds like a suitable choice. I never fully understood the exact purpose of `Enhances`, and many times in the past `Suggests` was recommended to me for various scenarios, which is why it was my first choice here too.

None of the packages (well, perhaps one for unit testing) are needed for check to succeed, as the packages are only loaded (in some cases, installed) during the runtime of the shiny app, which doesn't happen during check, build, or test.

I'll move them all to `Enhances` ASAP and see what effect it has on Check.

Thanks

**Comment by kevinrue** [comment]
https://github.com/Bioconductor/Contributions/issues/2749#issuecomment-1221274695

Fixed in https://github.com/iSEE/iSEEhub/pull/22

**Comment by kevinrue** [comment]
FYI, I've already discussed the following error on the BioC Slack:
```
    * ERROR: Remove install() calls (found 1 times)
```
See https://community-bioc.slack.com/archives/C0207H5QC3X/p1660313871200209

**Comment by nilseling** [comment]
Hi @kevinrue 
I'm currently on holidays but will post my review as soon as I'm back (10th September).

**Comment by kevinrue** [comment]
btw, note: we've pushed two new versions that haven't triggered new builds

**Comment by nilseling** [comment]
Have you bumped the package version? In the linked Github repo I don't see new changes and the version is still at `0.99.1`.

**Comment by kevinrue** [comment]
Yeah, so when i bumped the version to 0.99.1 nothing happened. Then I thought Charlotte bumped it to 0.99.2 but you make me realise that the PR hasn't been merged yet, it's only open at the moment.

**Comment by kevinrue** [comment]
OK, so there's something funky about the PR for 0.99.2, github action is throwing an error for something that worked before and that the PR is not touching, possibly something about the repositories where packages are installed from. In any case, you can review 0.99.1 in the meantime, because 0.99.2 is only bringing minor aesthetic fixes. We might even pack fixes following your review in that PR, depending on timings.

**Comment by nilseling** [comment]
Sounds good, that's also what I wanted to suggest as I don't have major comments anyway. 

First of all, thanks for submitting `iSEEhub`. The package is in a great shape and there are only a few things that I noticed:

- [x] `R CMD build` should pass without errors, warnings and notes: Please address the last NOTEs by selectively importing `capture.output`, `code`, `hr`, `installed.packages`, `modalDialog`, `removeModal` and `showModal`.
  
- [x] Checking the discussion on Slack, I think the `ERROR: Remove install() calls (found 1 times)` can be ignored.

## Documentation

- [x] The vignette is lacking an _Introduction_ section. Even though `iSEEhub` is an extension to `iSEE`, you should consider adding a short introduction to explain its use cases. Please also motivate its inclusion in Bioconductor as link between `iSEE` and `ExperimentHub`. 

## The CITATION file

- [ ] The CITATION file contains invalid DOIs. Exclude of adapt the file until the DOIs are active.

## R code

- [x] Add a validity check that `ehub` is actually an `ExperimentHub` object.

## Shiny apps

- [x] The tour doesn't seem to point at the right locations (e.g. when selecting the Info tab, the Launch button cannot be found) 

## Unit test

- [x] Looks good but there is still one test failing.

**Comment by kevinrue** [comment]
Sounds all good. As it happened, I've just merged 0.99.2 before noticing your review. So:

- We'll make another PR (0.99.3) to incorporate changes following your review.
- Bumping 0.99.2 still didn't trigger another build of the single package builder. Not sure what I'm missing

**Comment by nilseling** [comment]
Did you `git push upstream main:master`?

**Comment by kevinrue** [comment]
> IMPORTANT: Please read [this documentation](http://contributions.bioconductor.org/git-version-control.html#new-package-workflow) for setting
up remotes to push to git.bioconductor.org. It is required to push a
version bump to git.bioconductor.org to trigger a new build.

i feel such a newb right now xD

**Comment by kevinrue** [comment]
Target achieved; only one ERROR left, which we agreed to ignore:
```
* Checking parsed R code in R directory, examples, vignettes...
    * ERROR: Remove install() calls (found 1 times)
```
Probably worth bringing in a core team member at this point to establish this as a precedent of non-core package being allowed this ERROR, and possibly turning it into a WARNING?

Thanks for the review!

**Comment by nilseling** [comment]
I have now accepted the package for inclusion in Bioconductor allowing the `BiocManager::install()` call as an exception.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kevinrue.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("iSEEhub")`. The package 'landing page' will be created at

https://bioconductor.org/packages/iSEEhub

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
