### ISSUE TITLE
FuseSOM

### ISSUE THREAD

**Issue by ecool50** [Bioconductor/Contributions#2751]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ecool50/FuseSOM

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for your contribution, it looks very interesting.  However, yasomi is not in CRAN.  At this time, Bioconductor packages can depend only on other Bioconductor packages, or packages distributed by CRAN.  Consider using the som package at CRAN.  Let us know if we should close out this submission.

**Comment by kevinrue** [comment]
As a less important change that will also need to be addressed at some point:

I also see this line in the DESCRIPTION file above:
```
License: `use_mit_license()`, `use_gpl3_license()` 
```

Those are functions of the [usethis](https://usethis.r-lib.org/) package.

The authors will need to either:

- Call `usethis::use_mit_license()` or `usethis::use_gpl3_license()` from the R console to fill this field automatically.
- Choose a valid license name (see [here](https://r-pkgs.org/license.html)) and manually edit this field, e.g.

```
License: Artistic-2.0
```

**Comment by ecool50** [comment]
Amazing! Thanks for the feedback. I am currently working on the changes and will update when it is ready for reevaluation.

**Comment by ecool50** [comment]
Hey @vjcitn and @kevinrue, I have made updates to the FuseSOM package to remove the dependence on `yasomi` and also fixed the licensing issue. Would it be possible to reevaluate?
Thanks

**Comment by vjcitn** [comment]
we will reevaluate next week  thanks

**Comment by vjcitn** [comment]
the .o and .so files in /src must be removed

**Comment by vjcitn** [comment]
```
-- re-building ‘Introduction.Rmd’ using rmarkdown
Quitting from lines 66-68 (Introduction.Rmd) 
Error: processing vignette 'Introduction.Rmd' failed with diagnostics:
"batch_som_optim_continuous" not available for .C() for package "FuseSOM"
--- failed re-building ‘Introduction.Rmd’

SUMMARY: processing the following file failed:
  ‘Introduction.Rmd’

Error: Vignette re-building failed.
```
BTW it is much preferred to use .Call instead of .C  -- please see Writing R Extensions.

**Comment by vjcitn** [comment]
FYI this is the commit behind the source I used to generate error above:
```
commit b3921fba5a13e0233abf08a78ab1cbe815256d58
Author: Elijah Willie <ewillie@sfu.ca>
Date:   Sat Aug 27 00:06:45 2022 -0700

    Update Introduction.Rmd
```

**Comment by ecool50** [comment]
Hi @vjcitn, I will fix the introduction compilation issue and remove the `.so` and `.o` files. However, for the C-code, is it essential to have using the `.Call` format? I did not write the source code and it will take me some time to rewrite everything to use the `.Call` format. Can it be assessed and accepted using the `.C` format and I will update it in the next iteration? Please let me know.
Thanks

**Comment by vjcitn** [comment]
yes

**Comment by ecool50** [comment]
HI @vjcitn, I have made the necessary updates. Please have look and let me know your thoughts.

**Comment by vjcitn** [comment]
Sorry for delay.  My latest attempt led to:
```
Quitting from lines 66-68 (Introduction.Rmd) 
Error: processing vignette 'Introduction.Rmd' failed with diagnostics:
"batch_som_optim_continuous" not available for .C() for package "FuseSOM"
--- failed re-building ‘Introduction.Rmd’

```

**Comment by vjcitn** [comment]
But I was able to run the vignette code, so pre-check is passed.  Now the build system.... after it is ingested ... gets to have a try.

**Comment by hpages** [comment]
Hi @ecool50, please address the issues reported by the automated single package builder (SPB) above, so I can start the review. Thanks!

**Comment by nick-robo** [comment]
I have addressed all the errors and warnings apart from `ERROR: Maintainer must subscribe to the bioc-devel mailing list.` in version `0.99.1` which is now on the repository.

**Comment by hpages** [comment]
Hi @ecool50,

Please address the import issues (various "no visible global function definition for" NOTES by `R CMD check`). For the **methods**, **stats**, and **S4Vectors** imports, _full_ imports (e.g. `import(stats)`) are preferred over _selective_ imports (e.g. `importFrom("stats", "aggregate", "cor", "cov.wt", "kmeans", "prcomp", "princomp", "quantile", "sd")`).

Also please try to reduce the number of NOTES reported by `BiocCheck()`. 13 NOTES is a lot and some of them should be easy to avoid.

I'm not sure what this NOTE is about:

> NOTE: License 'GPL (>=2)' unknown; licenses cannot restrict use

The GPL licenses (version 2 or 3) are fine and plenty of Bioconductor packages use them. Maybe `BiocCheck()` fails to parse your `License:` field properly. Maybe try with `GPL (>= 2)` (note the space between `>=` and `2`). If that doesn't help we'll just ignore that note.

Thanks,
H.

**Comment by ecool50** [comment]
AdditionalPackage: https://github.com/SydneyBioX/spicyWorkflow

**Comment by hpages** [comment]
Hi @ecool50,

**spicyWorkflow** depends on **simpleSeg**, which has been submitted in a separate issue and has not been accepted yet. So **spicyWorkflow** can't be submitted as an additional package to **FuseSOM**. Please submit **spicyWorkflow** as a separate package once **FuseSOM** and **simpleSeg** both get accepted. I'll ignore it for now. Thanks!

Now I'm going to take a look at **FuseSOM** and come up with some feedback.

H.

**Comment by hpages** [comment]
Hi @ecool50 ,

Sorry for the delay and thanks for your patience.

Package looks good and is ready to go. Only thing I will ask you is to fix the titles of some of your man pages. Some of them look like this (e.g. `?runFuseSOM`):
```
runFuseSOM               package:FuseSOM               R Documentation

A wrapper function to run the FuseSOM algorithm. This function accepts
a matrix, dataframe or a SingleCellExperiment object. For matrices and
dataframes, it is assumed that markers are the columns and samples
rows.

Description:

     A wrapper function to run the FuseSOM algorithm. This function
     accepts a matrix, dataframe or a SingleCellExperiment object. For
     matrices and dataframes, it is assumed that markers are the
     columns and samples rows.
```
As you can see the title is a copy of the Description field, that is, a full paragraph made of 3 sentences! A title should be much shorter, ideally it should fit in a single line, and with no trailing period.

Thanks,
H.

**Comment by ecool50** [comment]
Hi @hpages, thanks for all your efforts. I have made the requested changes. Please let me know if you need anything else.

**Comment by hpages** [comment]
All is good. Thanks @ecool50

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ecool50.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("FuseSOM")`. The package 'landing page' will be created at

https://bioconductor.org/packages/FuseSOM

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
