### ISSUE TITLE
`genomicRegionsFromGeneSymbols`

### ISSUE THREAD

**Issue by davidechicco** [Bioconductor/Contributions#2752]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/davidechicco/genomicRegionsFromGeneSymbols

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
there is no vignette.  please read contributor guidelines.

**Comment by vjcitn** [comment]
```
Running examples in 'genomicRegionsFromGeneSymbols-Ex.R' failed
The error most likely occurred in:

> ### Name: getGenomicRegionsFromGeneSymbols
> ### Title: Function that reads in a list of probesets' ID's for the GPL96
> ###   platform and returns the annotations for them, if found
> ### Aliases: getGenomicRegionsFromGeneSymbols
> 
> ### ** Examples
> 
> gene_symbols_list <- c("AK4", "ALDOC", "EGLN1", "FAM162A", "MTFP1", "PDK1", "PGK1")
> verboseFlag <- FALSE
> trackName <- "neuroblastomaPrognosticSignature2020"
> outputFolder  <- "./test"
> outputFileFormat <- "BED"
> outputFileFlag <- FALSE
> arrangedAnnotations <- getGenomicRegionsFromGeneSymbols(gene_symbols_list, trackName, outputFileFlag, outputFolder, outputFileFormat, verboseFlag)
Warning: no probe sets were found for: MTFP1
Processed URL: https://www.ensembl.org/?redirect=no
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [www.ensembl.org:443] Operation timed out after 300000 milliseconds with 0 bytes received
Calls: getGenomicRegionsFromGeneSymbols ... request_fetch -> request_fetch.write_memory -> <Anonymous>
Execution halted
```
is that familiar?  does your package pass check most of the time?

**Comment by davidechicco** [comment]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/davidechicco/genomicRegionsFromGeneSymbols

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by davidechicco** [comment]
> there is no vignette. please read contributor guidelines.

@vjcitn Thanks for having noticed it; I just added them in the new package version that I just submitted. I hope I submitted it in the right way.

> is that familiar? does your package pass check most of the time?

It rarely happens. My package passes all the checks most of the times.

**Comment by vjcitn** [comment]
Thanks for adding the vignette.  I have some concerns.  First, my attempt to check the package after your revisions led to 
```
 ERROR
Running the tests in 'tests/runTests.R' failed.
Last 13 lines of output:
   
  1 Test Suite : 
  genomicRegionsFromGeneSymbols RUnit Tests - 1 test function, 1 error, 0 failures
  ERROR in test_genomicRegionsFromGeneSymbols: Error in curl::curl_fetch_memory(url, handle = handle) : 
    Timeout was reached: [www.ensembl.org:443] Operation timed out after 10001 milliseconds with 484445 bytes received
  
  Test files with failing tests
  
     test_genomicRegionsFromGeneSymbolsChecker.R 
       test_genomicRegionsFromGeneSymbols 
  
  
  Error in BiocGenerics:::testPackage("genomicRegionsFromGeneSymbols") : 
    unit tests failed for package genomicRegionsFromGeneSymbols
```
Perhaps you can make the test more fault tolerant.

More seriously, though, you have to explain why this package is needed in Bioconductor; we do ask for abstract information on package significance to the ecosystem in our contributions page.  Gene regions can be obtained for symbols with relatively simple manipulations of EnsDb.Hsapiens.v79 for example (or v75, etc.) -- call the genes() method and interrogate the mcols of the output.  Your code makes use of biomaRt, org.Hs.eg.db, affy chip annotations, etc.  How does your approach represent a suitable solution, for what use cases?
```
> gg = c("AK4", "ALDOC", "EGLN1", "FAM162A", "MTFP1", "PDK1", "PGK1")
> gg
[1] "AK4"     "ALDOC"   "EGLN1"   "FAM162A" "MTFP1"   "PDK1"    "PGK1"   
> library(EnsDb.Hsapiens.v79)
g12/66 packages newly attached/loaded, see sessionInfo() for details.
> g79 = genes(EnsDb.Hsapiens.v79)
> g79[ g79$gene_name %in% gg ]
GRanges object with 7 ranges and 6 metadata columns:
                  seqnames              ranges strand |         gene_id
                     <Rle>           <IRanges>  <Rle> |     <character>
  ENSG00000162433        1   65147549-65232145      + | ENSG00000162433
  ENSG00000135766        1 231363751-231425044      - | ENSG00000135766
  ENSG00000109107       17   28573115-28577264      - | ENSG00000109107
  ENSG00000152256        2 172555373-172608669      + | ENSG00000152256
  ENSG00000242114       22   30425530-30429053      + | ENSG00000242114
  ENSG00000114023        3 122384176-122412334      + | ENSG00000114023
  ENSG00000102144        X   78065188-78129296      + | ENSG00000102144
                    gene_name   gene_biotype seq_coord_system      symbol
                  <character>    <character>      <character> <character>
  ENSG00000162433         AK4 protein_coding       chromosome         AK4
  ENSG00000135766       EGLN1 protein_coding       chromosome       EGLN1
  ENSG00000109107       ALDOC protein_coding       chromosome       ALDOC
  ENSG00000152256        PDK1 protein_coding       chromosome        PDK1
  ENSG00000242114       MTFP1 protein_coding       chromosome       MTFP1
  ENSG00000114023     FAM162A protein_coding       chromosome     FAM162A
  ENSG00000102144        PGK1 protein_coding       chromosome        PGK1
                       entrezid
                         <list>
  ENSG00000162433 205,100507855
  ENSG00000135766         54583
  ENSG00000109107           230
  ENSG00000152256          5163
  ENSG00000242114         51537
  ENSG00000114023         26355
  ENSG00000102144          5230
  -------
  seqinfo: 319 sequences (1 circular) from GRCh38 genome
> as.character(granges(.Last.value))
          ENSG00000162433           ENSG00000135766           ENSG00000109107 
  "1:65147549-65232145:+" "1:231363751-231425044:-"  "17:28573115-28577264:-" 
          ENSG00000152256           ENSG00000242114           ENSG00000114023 
"2:172555373-172608669:+"  "22:30425530-30429053:+" "3:122384176-122412334:+" 
          ENSG00000102144 
  "X:78065188-78129296:+" 
```

**Comment by davidechicco** [comment]
@vjcitn Thanks for your comments and your feedback. To be honest, I did not know about the existence of the `genes()` function of `EnsDb.Hsapiens.v79`, I am discovering it right now. It looks much easier to use than my proposed package.
I think the only asset of my package could then be that it was designed for that goal, that is the retrieval of genomic regions from gene symbols. Before starting to work on my package, I looked for existing ways to retrieve genomic regions from gene symbols and I did not find about the  `genes()` function of `EnsDb.Hsapiens.v79` anywhere.
I'd be happy to move on with my package and to improve it for the inclusion on Bioconductor, but if you think it's redundant and does not add anything new or interesting, I'm available to discard it of course.

**Comment by hpages** [comment]
> I looked for existing ways to retrieve genomic regions from gene symbols and I did not find about the genes() function of EnsDb.Hsapiens.v79 anywhere.

Did you try to ask on [our support site](https://support.bioconductor.org) about that? Those are basic manipulations that most people in the community are familiar with. FWIW an even better way to retrieve gene regions is with `transcriptsBy( , by="gene")` if you don't mind getting the result in a GRangesList object instead of a GRanges object. This avoids the artificially long genes that we see sometimes in the result when `genes()` is used with a TxDb object based on UCSC annotations.

**Comment by vjcitn** [comment]
I would propose that we close this issue.  I can imagine some helper functions for gene annotation that you might contribute in a package but you have to make a convincing case for how they simplify work for users relative to what already exists.

**Comment by vjcitn** [comment]
@davidechicco I will close; reopen if you would like to pursue further.  Thank you.
