### ISSUE TITLE
BioNAR

### ISSUE THREAD

**Issue by lptolik** [Bioconductor/Contributions#2780]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lptolik/BioNAR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Vignette is taking a while to build, so I ran a purled version and saw
```
 head(mc)
     ID      DEG  BET         CC      SL       mnSP    PR         sdSP   
[1,] "273"   "12" "833.233"   "0.106" "44656"  "3.424" "0.000786" "0.707"
[2,] "6455"  "22" "5444.71"   "0.082" "170211" "2.955" "0.001337" "0.683"
[3,] "1759"  "16" "1744.932"  "0.217" "150771" "3.062" "0.000962" "0.687"
[4,] "1785"  "27" "10994.509" "0.071" "218717" "2.89"  "0.001644" "0.701"
[5,] "26052" "6"  "291.138"   "0.133" "55060"  "3.503" "0.000405" "0.743"
[6,] "2923"  "7"  "1225.709"  "0.095" "55104"  "3.391" "0.000531" "0.758"
```
those character representations of numeric (esp. floating point) data are not desirable.  Can you
intervene to ensure that the user gets entities of appropriate type?  Looks like calcAllClustering is slow and perhaps you don't want to do this in the vignette.  Maybe you can precompute and use
a serialized result.

**Comment by DarioS** [comment]
While you are working on getting the code to build and check fine, please also update to meet [the Developer's Guide rules](https://contributions.bioconductor.org/r-code.html).

> * Always use space after a comma. This: `a, b, c`.
> * Space around all binary operators: `a == b`.
> Use `camelCase`: initial lowercase, then alternate case between words.

Your variable naming usage is inconsistent e.g. `intra_m`, `inter_m`, `intraEdgesM`.  Also, don't use uninformative variable names like `i` or `gg`. Use names such as `sampleIndex` instead for readability.

**Comment by DarioS** [comment]
Thanks for fixing the errors and warnings. There are currently a number of issues which I have identified.

- See code and syntax requests in my previous comment.
- The package needs integration with existing Bioconductor classes and packages. It currently lacks any. For example, [Pairs ](https://rdrr.io/bioc/S4Vectors/man/Pairs-class.html)would be a good data container for binary PPI edges.
- Please don't use flatfile.go.BP.csv, flatfile.go.MF.csv, flatfile.go.CC.csv files. You are required to use [AnnotationDbi](https://bioconductor.org/packages/release/bioc/html/AnnotationDbi.html) to interact with [GO.db](https://bioconductor.org/packages/release/data/annotation/html/GO.db.html) to interface with existing Bioconductor infrastructure.
- See the developer's guide section about [vignettes](https://contributions.bioconductor.org/docs.html#vignettes). There need to be installation instructions near the beginning. Introduction and Overview of Capabilities sections are currently empty. Use the Predefined Network has only code but no paragraphs of explanations about what it does and how the user should interpret the output. It's not clear what biological problem the package is trying to solve. The vignette is a disjointed collection of section headings with many one-sentence or empty explanations that lacks meaningful connection between consecutive sections. The introduction of the vignette doesn't explain what the data set used in all of the following samples is.
- Things which should be a documented function in the package are instead lengthy code blocks in the vignette. For example, the `plot.bridgeness` chunk and `plotly` chunks ought to be converted into a function which the user could execute.
- Data sets need their own documentation. See Package Data in the developer's guide. The files PPI_Presynaptic.csv, flatfile_human_gene2HDO.csv, SCH_flatfile.csv, PresynAn.csv, flatfile.go.BP.csv, flatfile.go.MF.csv, flatfile.go.CC.csv are not documented according to Bioconductor requirements.
- The majority of your exported functions should have a unit test. Please see the [Unit Tests](https://contributions.bioconductor.org/tests.html) section of the developer's guide. Currently, there is only one trivial unit test of get functions. Unit tests became a Bioconductor requirement a couple of years ago so, although many older packages don't have unit tests, all new ones are required to have comprehensive ones.
```r
test_that("proper algorithm selected",{
  expect_error(getRobustness(karate,'alg',matrix(0,ncol = 1,nrow = 1)),"Membership.*")
  expect_error(getClustering(karate,'alg'),".*lec*")
})
```

**Comment by lptolik** [comment]
Dear Dario,

Thank you for reviewing our package. 

Could you, please clarify what do you mean when you propose to use [Pairs ](https://rdrr.io/bioc/S4Vectors/man/Pairs-class.html) for binary PPI edges as an integration with Bioconductor packages and classes? 

We are already using [synaptome.db](https://bioconductor.org/packages/devel/data/annotation/html/synaptome.db.html), [fgsea](https://bioconductor.org/packages/devel/bioc/html/fgsea.html) and I'm incorporating [GO.db](https://bioconductor.org/packages/release/data/annotation/html/GO.db.html) to replace the static annotation. 

The central classes of the package are Graph, Node, and Edge from the igraph package. If you think that export of some data would simplify its reuse by others I can create accessor functions to export edges in the Pairs and nodes as Vector with Annotation metadata, but for the internal algorithms use of [S4Vectors](https://rdrr.io/bioc/S4Vectors/) classes is excessive and unnecessary at the moment. We will consider its usage for the future.

Cheers,
Anatoly on behalf of the package developers

**Comment by DarioS** [comment]
Ah, thanks for the clarification. It seems wise to stick with Graph, Node and Edge data container classes.

**Comment by lptolik** [comment]
# Review’s Comments

We appreciate the reviewer’s comments regarding our package submission to BioConductor. We have gone through each of them, answering them as completely as possible, please see the responses below. We would be grateful if the review could now provide us with any additional comments, so that we can be in the position to complete these and finalise our package for submission to BioConductor for the 26th of October 2022 release date.

## Comment (1):  
“_While you are working on getting the code to build and check fine, please also update to meet_ [_the Developer's Guide rules_](https://contributions.bioconductor.org/r-code.html)_._
* _Always use space after a comma. This: a, b, c._
* _Space around all binary operators: a == b._
* _Use camelCase: initial lowercase, then alternate case between words._”

### Response (1):  
We have changed all functions to the camelCase, added spaces, and applyed RStudio formatting to all our code.

## Comment (2):  
“_Your variable naming usage is inconsistent e.g. intra_m, inter_m, intraEdgesM. Also, don't use uninformative variable names like I or gg. Use names such as sampleIndex instead for readability._”  

### Response (2):  
We have tried to go back through and make the variable names as meaningful and consistent as possible. Most variable names we use already carry meaning; the review commented on ‘gg’, which actually stands for ‘gene-graph’, and in the context of the package carries a lot of meaning.

## Comment (3):  
“_Thanks for fixing the errors and warnings. There are currently a number of issues which I have identified._
* _See code and syntax requests in my previous comment._
* _The package needs integration with existing Bioconductor classes and packages. It currently lacks any. For example, Pairs would be a good data container for binary PPI edges._”

### Response (3):  
Our package is designed around graphs, or networks, as the underlying data container. One of the fundamental and universal R packages to both represented and preform analysis with this type of data is called igraph. Although we acknowledge igraph is not part of BioConductor, we note other BioConductor packages also rely on igraph to store and represent its data, e.g. RedeR.

## Comment (4):  
“_Please don't use flatfile.go.BP.csv, flatfile.go.MF.csv, flatfile.go.CC.csv files. You are required to use_ [_AnnotationDbi_](https://bioconductor.org/packages/release/bioc/html/AnnotationDbi.html) _to interact with_ [_GO.db_](https://bioconductor.org/packages/release/data/annotation/html/GO.db.html) _to interface with existing Bioconductor infrastructure._”  

### Response (4):  
We have added the function ‘annotateGOont’ to our code to use GO.db to add GO annotations to graph nodes. However, we also feel it is important to provide the user functionality to load & save annotation flat files, as many labs manually created subsets of GO for their own analysis.

## Comment (5):  
“_See the developer's guide section about_ [_vignettes_](https://contributions.bioconductor.org/docs.html#vignettes)_. There need to be installation instructions near the beginning. Introduction and Overview of Capabilities sections are currently empty. Use the Predefined Network has only code but no paragraphs of explanations about what it does and how the user should interpret the output. It's not clear what biological problem the package is trying to solve. The vignette is a disjointed collection of section headings with many one-sentence or empty explanations that lacks meaningful connection between consecutive sections. The introduction of the vignette doesn't explain what the data set used in all of the following samples is._”  

## Response (5):  
We have added an installation section to our package repo, instructing the use how to install our package. We have significantly edited vignette to include Introduction and detailed Overview of capabilities. We hope that Introduction now answers the question about biological problem. We have also edited and expanded the vignette sections to make the links between them, and explained the origin of the datasets.

## Comment (6):  
“_Things which should be a documented function in the package are instead lengthy code blocks in the vignette. For example, the plot.bridgeness chunk and plotly chunks ought to be converted into a function which the user could execute._”  

### Response (6):  
A new function called ‘plotBridgeness’ has been added to our code.

## Comment (7):  
“_Data sets need their own documentation. See Package Data in the developer's guide. The files PPI_Presynaptic.csv, flatfile_human_gene2HDO.csv, SCH_flatfile.csv, PresynAn.csv, flatfile.go.BP.csv, flatfile.go.MF.csv, flatfile.go.CC.csv are not documented according to Bioconductor requirements._”  

### Response (7):  
Data sets were annotated as requested.

## Comment (8):  
“_The majority of your exported functions should have a unit test. Please see the_ [_Unit Tests_](https://contributions.bioconductor.org/tests.html) _section of the developer's guide. Currently, there is only one trivial unit test of get functions. Unit tests became a Bioconductor requirement a couple of years ago so, although many older packages don't have unit tests, all new ones are required to have comprehensive ones._”  

### Response (8):  
At the moment the test coverage is above 85%, which covers all exported functions.

**Comment by DarioS** [comment]
Thanks for the updates. I think that the package is now ready for acceptance.

Note that unit tests are equally important for non-exported functions as they are for exported functions. Their purpose is to test that calculations are correct and that their outputs don't change over time.

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lptolik.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BioNAR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BioNAR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
