### ISSUE TITLE
metabinR

### ISSUE THREAD

**Issue by gkanogiannis** [Bioconductor/Contributions#2796]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gkanogiannis/metabinR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```
reads.mapping <- fread(
        system.file("extdata", "reads_mapping.tsv.gz",package = "metabinR")
    )
reads.mapping$AB_id <- abundances$V3[
                                        match(reads.mapping$genome_id,
                                        abundances$V1)
                                    ]
reads.mapping <- reads.mapping[order(reads.mapping$anonymous_read_id),]
```
this is from vignette.  Syntax and manipulations are complex.  Can you define higher-level data structures and methods to make this easier for the user?

**Comment by vjcitn** [comment]
What if the abundances$V1 don't match any reads.mapping$genome_id ... ?  Of course it works in your example but we want some defensive programming to help users deal with possible inconsistencies between independently managed resources.  This is one of the motivations behind SummarizedExperiment, in which sample-level data and quantifications can have all kinds of identifiers, and we want to hand the user something that has some validity checking on construction.

**Comment by vjcitn** [comment]
![pix](https://user-images.githubusercontent.com/4624066/195090721-1508d7ea-91f4-4a3c-93a8-14ee0a699db0.jpg)

is that really what we want in the vignette?

**Comment by vjcitn** [comment]
Why not just print the table?

**Comment by vjcitn** [comment]
Thanks for the submission, let us know your plans.

**Comment by gkanogiannis** [comment]
> ```
> reads.mapping <- fread(
>         system.file("extdata", "reads_mapping.tsv.gz",package = "metabinR")
>     )
> reads.mapping$AB_id <- abundances$V3[
>                                         match(reads.mapping$genome_id,
>                                         abundances$V1)
>                                     ]
> reads.mapping <- reads.mapping[order(reads.mapping$anonymous_read_id),]
> ```
> 
> this is from vignette. Syntax and manipulations are complex. Can you define higher-level data structures and methods to make this easier for the user?

I updated vignette to use dplyr-style operation for merging and ordering. I hope it looks better now.

**Comment by gkanogiannis** [comment]
> What if the abundances$V1 don't match any reads.mapping$genome_id ... ? Of course it works in your example but we want some defensive programming to help users deal with possible inconsistencies between independently managed resources. This is one of the motivations behind SummarizedExperiment, in which sample-level data and quantifications can have all kinds of identifiers, and we want to hand the user something that has some validity checking on construction.

The purpose of `metabinR` is to perform 3 types of binning (AB, CB and HC). It takes as input a set of fasta/fastq files and creates bins of reads. 
The evaluation of the generated bins of reads is beyond the scope of this package and no mechanism or function is offered for this purpose. 

For demonstration only, a simple way to perform evaluation of the bins is given in the vignette. 

Example input fasta files are generated by reads simulator `CAMISIM` and simple evaluation is done using the design files generated by it (for example the names of the fields of the produced distribution.txt and reads_mapping.tsv).

In the vignette example reads.mapping$genome_id always matches abundances$genome_id because it was fixed from the design.
Users of `metabinR` are expected to use their own way of evaluation of the produced reads bins.

**Comment by gkanogiannis** [comment]
> Why not just print the table?

Apologies for the ugliness. Changed it to plot it as table with `knitr::kable`.

**Comment by gkanogiannis** [comment]
Dear @vjcitn , thank you for the pre-review comments.
Please see my replies above.
Pushed updated version 0.99.1 to github repo.
Looking forward for the continuation of the review.

**Comment by vjcitn** [comment]
You've improved the aesthetics somewhat but I still think defensive programming and integrative datastructures like SummarizedExperiment or TreeSummarizedExperiment should be considered.

**Comment by gkanogiannis** [comment]
> You've improved the aesthetics somewhat but I still think defensive programming and integrative datastructures like SummarizedExperiment or TreeSummarizedExperiment should be considered.

Dear @vjcitn it is something that I will for sure consider as improvement.
Thank you.

**Comment by gkanogiannis** [comment]
Dear @hpages salut. J'espere que tout va bien. I was wondering if we are on track here and if I am going to receive soon an initial review of `metabinR`, in order to have some time until the deadline of 26 October for corrections and improvements based on your comments.

Looking forward to receiving your review,
Anestis

**Comment by hpages** [comment]
Hi @gkanogiannis Tout va bien merci. Sorry for the slow response. I'm taking a look at **metabinR** and will come back with some feedback. Thanks for you patience.

**Comment by gkanogiannis** [comment]
Dear Hervé @hpages, thank you so much for your time and effort.

**Comment by gkanogiannis** [comment]
Dear @hpages, I was wondering if it will be possible to receive a review and feedback on this package. I am worried that it will not make it to the manifest of new release. Thank you again so much for tour efforts.

**Comment by hpages** [comment]
Thanks for your patience @gkanogiannis.

Package looks good. Only minor cosmetic issue is this:
```
> library(metabinR)
To cite metabinR in publications use:



A BibTeX entry for LaTeX users is

  @Article{,
    title = {A scalable assembly-free variable selection algorithm for biomarker discovery from metagenomes},
    author = {Gkanogiannis Anestis and Thomas Bruls},
    journal = {BMC Bioinformatics},
    year = {2016},
    volume = {Aug 19;17(1):311},
    doi = {10.1186/s12859-016-1186-3},
    url = {https://dx.doi.org/10.1186/s12859-016-1186-3},
  }
```
This is not considered good practice. Please remove. Typical Bioconductor workflows will start by loading many packages, sometimes dozens or more. Bioconductor recommends packages to be as quiet as possible at load time.

Thanks

**Comment by gkanogiannis** [comment]
Dear @hpages, citation message on package attach is removed and version bumped.
Thank you once again for your time and effort in reviewing `metabinR`.

**Comment by hpages** [comment]
All looks good. Thanks!

**Comment by gkanogiannis** [comment]
Merci beaucoup, bonne soirée Hervé @hpages !

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/gkanogiannis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("metabinR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/metabinR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
