### ISSUE TITLE
(inactive) ASCETIC

### ISSUE THREAD

**Issue by danro9685** [Bioconductor/Contributions#2797]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/danro9685/ASCETIC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission.  I think it needs some work.  First, there is no definition of "agony" readily visible in the documents.  Second, no Bioconductor data structures are used, and the main structure I saw had patients as rows and mutations as columns.  It might be relevant to look at curatedTCGAData structures to see how cancer mutational data are structured for use in Bioconductor ... and there are other packages that could be relevant.  It is important for the submission to include some indication of why and how the software fits in the Bioconductor ecosystem.  Let us know your thoughts.

**Comment by danro9685** [comment]
Dear @vjcitn,

Thanks for your quick feedback. We will include a definition of agony, sorry for missing this.
And, we will have a look at curatedTCGAData and other potentially interesting packages within Bioconductor.
We will get back to you soon.

Thank you,
Daniele

**Comment by danro9685** [comment]
Dear @vjcitn,

We have updated the documentation as suggested.
Moreover, we have looked at the curatedTCGAData package, but we could not retrieve information on cancer cell fractions data from it, which are required for our tool.

Please let us know if you have additional  pre-review suggestions.

Thanks,
Daniele

**Comment by luca-dex** [comment]
Dear @vjcitn 
I'm the maintainer of the package. I already added the bioconductor remotes to our package and we're trying to push some changes but, at the moment, ASCETIC is not among the packages to which I access on git.bioconductor.org so my SSH key is not accepted. 

```
$ git fetch --all
Fetching origin
Fetching upstream
FATAL: R any packages/ASCETIC l.desano DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: could not fetch upstream

```

Could you please help us in sorting out this issue?

Thanks

**Comment by lshep** [comment]
push access has not been granted yet as this package is still in the pre-check stage. Once the package passes pre-checks it will be added to git.bioconductor.org.  At this stage updating the github and pinging @vjcitn is sufficient

**Comment by luca-dex** [comment]
thanks @lshep for the clarification

**Comment by luca-dex** [comment]
Hi @vjcitn and @lshep 

We would like to know if there anything we should do for this package or if everything is fine.

Thanks

**Comment by luca-dex** [comment]
Hi @vjcitn and @lshep I still cannot push on this repository, so we cannot trigger new build.
Could you please let us know how we can proceed?

I have the repo configured properly in BiocCredentials and I'm able to trigger push on other repository buy this one is not accepting my credentials.

Best,

**Comment by lshep** [comment]
again -- @vjcitn  has not processed it passed pre-checks so you would not have access on git.bioconductor.org

**Comment by luca-dex** [comment]
thanks for the clarification @lshep 
is there anything we can do at this stage to speed up the process, in order to avoid to pass the deadline of Wednesday?

Best,

**Comment by vjcitn** [comment]
I just compiled the vignette.  I see
```
## Warning in check.data(x): variable 2 has levels that are not observed in the
## data.
## Warning in check.data(x): variable 3 has levels that are not observed in the
## data.
## Warning in check.data(x): variable 10 has levels that are not observed in the
## data.
## Warning in check.data(x): variable 13 has levels that are not observed in the
## data.
## Warning in check.data(x): variable 17 has levels that are not observed in the
## data.
## Warning in check.data(x): variable 18 has levels that are not observed in the
## data.
## Warning in check.data(x): variable 20 has levels that are not observed in the
## data.
## Warning in check.data(x): variable 27 has levels that are not observed in the
## data.

We refer to the manual for a detailed description of each parameter and to the ASCETIC manuscript for details on the method.
```
You have similar content in .rnw and .Rmd.  Please fix the warnings and simplify the vignette layout before review can begin.

**Comment by danro9685** [comment]
Dear @vjcitn,
This warning is generated during the likelihood fit part of the inference by ASCETIC when input data, which are expected to be binary (two levels, 0 and 1), show only one level.
This is something that can happen, i.e., the user sometimes can have data of this type, and it is not an error (the warning needs to be shown in these cases).
We can easily remove it, but I was wondering if you still wants us to do it, being this a common workflow for the user?
Please let us know so that we can proceed accordingly.
Thanks,
Daniele and @luca-dex

**Comment by danro9685** [comment]
Dear @vjcitn,
Just to be sure, I have fixed the input data to remove the warnings, as you have asked.
All the best,
Daniele

**Comment by luca-dex** [comment]
Dear @vjcitn ,
considering that the deadline for  new packages to be included in bioc 3.16 has passed, we would like to know what should we do and if there still possibility to include our package in the release.

Please, let us know

Best,

**Comment by vjcitn** [comment]
I'd suggest that you improve the package to meet guidelines/reviewer/pre-reviewer advice and get it added to Bioc 3.17.  There is no rush, you can distribute via github, tell people it is in 3.17 once it passes review, etc.  Sorry for delays but there are so many tasks in connection with getting to a release that some submissions that come in close to release time just don't make it in.

**Comment by luca-dex** [comment]
Thanks @vjcitn 

we will follow your suggestion.

**Comment by DarioS** [comment]
The issues identified by Vincent still apply. In addition,

- The package needs conform to Bioconductor [coding style](https://contributions.bioconductor.org/r-code.html). `camelCase` instead of `snake_case`. Don't use `=` for variable assignment but `<-`. Use spaces around assignment operators and after commas. In most cases, don't use `for` loops but `vapply` or `lapply`.
- Phyogenetic trees can be input. But the software doesn't make use of Bioconductor package [treeio](http://bioconductor.org/packages/release/bioc/html/treeio.html) infrastructure.
- Return values are a basic list. The package should define [a class with accessor functions](https://contributions.bioconductor.org/r-code.html#class-design) to store results in.
- Vignette provides no biological interpretation of the results. What is the user supposed to discover in the results?
- `man` folder has 30 Rd files but vignette demonstrates only 5 functions. Please make it more comprehensive.

**Comment by lshep** [comment]
@luca-dex  may we expect updates to the package soon?

**Comment by danro9685** [comment]
Dear @lshep,
Sorry for the radio silence from our side, we have been pretty full in this period.
But me and @luca-dex plan to fix this soon.
Thanks!

**Comment by danro9685** [comment]
Dear @lshep,

Just a quick update on this.
The maintainer of the package (@luca-dex) has been traveling with very limited Internet access since last month and will be back on January 21st .

I am working to address the issues for the review, but it will take a little bit more time given that @luca-dex is not available for two more weeks.

I apologize for the inconvenience. We will try to finalize this soon.

Thanks,
Daniele

**Comment by DarioS** [comment]
No rush. It is currently summer holidays in Australia with most researchers returning to work next week.

**Comment by danro9685** [comment]
Dear @DarioS,

Me and @luca-dex are working at all the suggestions you have provided and plan to push the updated version of the ASCETIC package within next week.
So, I would ask you if possibile to reopen this issue.

Thanks,
Daniele & Luca

**Comment by luca-dex** [comment]
Dear @DarioS  and @lshep,
during past weeks we worked on improving the packages following the feedback we received and we think we addressed the issues that were blocking the release of the package. We also revised the documentation of the package and we did a cleanup of the C code that is not more integrated in the package.

We kindly ask you to reopen the issue, if possible.

Thanks a lot for your understanding

Luca & Daniele

**Comment by luca-dex** [comment]
Dear @lshep ,
I have remotes correctly set up, but when I try to push a version bump but I got the following error:

```
$ git push upstream devel
FATAL: W any packages/ASCETIC l.desano DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Am I missing something? It was working before

**Comment by luca-dex** [comment]
Just to add that ASCETIC is not in the list of pachages to which I have access on BiocCredentials anymore:

'luca.desano@gmail.com' has access to the following packages:
TRONCO
OncoScore
SIMLR
SparseSignatures
RESOLVE

**Comment by lshep** [comment]
The submitter is granted access on initial submit.  Should both you and @danro9685 have access? We normally only allow one active maintainer but if necessary we can add access to both?

**Comment by luca-dex** [comment]
Thanks @lshep. Could you please remove @danro9685 and leave only me as maintainer?

**Comment by lshep** [comment]
Yes.  Please try again in 10 min.  It should be active by then

**Comment by luca-dex** [comment]
Dear @lshep and @DarioS ,
do you have any update for us? we would like to know if the package will be accepted for the incoming release.

Best,

**Comment by DarioS** [comment]
Ah, I was expecting a point-by-point response to the issues raised before. Looking at the code again, only one is partially addressed. It could be accepted after all of the other issues are addressed with major changes to the code.

**Comment by danro9685** [comment]
Dear @DarioS,

Looking back at your review:
1) _The package needs conform to Bioconductor coding style. camelCase instead of snake_case. Don't use = for variable assignment but <-. Use spaces around assignment operators and after commas. In most cases, don't use for loops but vapply or lapply._ **Should have been addressed, we already implemented a major refactory to the whole package.**
2) _Vignette provides no biological interpretation of the results. What is the user supposed to discover in the results?_ **We have added a discussion in the vignette. The related paper is currently under review, we will include more details and the link the paper once it is published if this is fine.**
3) _man folder has 30 Rd files but vignette demonstrates only 5 functions. Please make it more comprehensive._ **We realized most of the functions were internal, so we remove them and used the . in the functions name. So the ones that are demonstrated are actually the correct ones.**

So, the following items should be missing:
A) _Phyogenetic trees can be input. But the software doesn't make use of Bioconductor package [treeio](http://bioconductor.org/packages/release/bioc/html/treeio.html) infrastructure._
B) _Return values are a basic list. The package should define [a class with accessor functions](https://contributions.bioconductor.org/r-code.html#class-design) to store results in._

Please let me know if I am correct or if I am missing something.
All the best,
Daniele

**Comment by DarioS** [comment]
1. No, the package still has widespread usage of `for` loops instead of `vapply` or `mapply`. See [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize) instructions. Also, example code for functions and in the vignette still has use of `=` for assignments instead of `<-`.
2. Needs more biological interpretation.

> The output of this analysis is a a list of 4 elements: 1) dataset, input dataset; 2) ccfDataset, input ccf dataset; 3) poset, partially order set among mutations estimated by ASCETIC from the agony ranking and 4) inference, inferred ASCETIC evolutionary model for each selected regularization.

This is a general statement about the output of the software. What do each of the four list elements show biologically for the example data set chosen to use? The above sentence has nothing specifically to do with the example data set used or the results generated and is too generic.
3. I see that the number of user-facing functions has been reduced. However, only 4 out of 15 Rd files have an `\examples` section. Please refer to [Examples](https://contributions.bioconductor.org/docs.html#examples) section of developer's guide.
> All man pages should have an runnable examples.

Also, note Vincent Carey's issues still apply. The software lacks utilisation of existing Bioconductor infrastructure. Yes, it should use existing Bioconductor data structures for phylogenetic trees and mutations, rather than a numeric `matrix` of 0s and 1s.

> - First, there is no definition of "agony" readily visible in the documents.
> - Second, no Bioconductor data structures are used, and the main structure I saw had patients as rows and mutations as columns (i.e. typically features are in rows and biological samples are in columns in other packages such as edgeR, MultiAssayExperiment, VariantAnnotation). It is important for the submission to include some indication of **why and how the software fits in the Bioconductor ecosystem**.

To address the first issue, I think you could simply tale the description of agony from agony.Rd and put it in the vignette. I found it intuitive. Remember, the vignette is typically the first documentation that a package user will read. So, basic concepts such as the definition of agony should be defined there.

Also, doesn't the algorithm handle heterozygous and homozygous variants differently? It is intended for cancer analysis and whether a particular variant is heterozygous or homozygous could be important but the software seems to only take 0 or 1 as input. Important limitations of the algorithm should be clearly stated.

**Comment by danro9685** [comment]
Dear @DarioS,

Thanks for the detailed feedbacks, we are working on it.
Just one minor clarification re: "3. I see that the number of user-facing functions has been reduced. However, only 4 out of 15 Rd files have an \examples section. Please refer to [Examples](https://contributions.bioconductor.org/docs.html#examples) section of developer's guide." We have example for the 5 exported function by ASCETIC. The other man pages are for data we provide to run these 5 functions. Are examples also required for data?

Thanks,
Daniele

**Comment by danro9685** [comment]
Dear @DarioS,

Apologies for the second message, I'd need an other clarification.
You mention: doesn't the algorithm handle heterozygous and homozygous variants differently?
I have explained this better in the current vignette (performing a couple of checks then @luca-dex will push it), but ASCETIC takes as input phylogenies and combine them together. So heterozygous and homozygous variants are handled as separated (binary events).

We will work on the remaining issues, thanks for your comments.

All the best,
Daniele

**Comment by DarioS** [comment]
Thanks for the clarifications. I had in mind a set of variables <chromosome, position, reference allele, alternate allele> for a mutation (not the genotype). A clarifying explanation might be useful.

**Comment by danro9685** [comment]
Dear @DarioS,

Sounds good. We have improved the package with all the requested information, @luca-dex is still working at a couple of things, but he will push the latest version with the updates this weekend.

Thanks,
Daniele

**Comment by luca-dex** [comment]
Dears,

> No, the package still has widespread usage of for loops instead of vapply or mapply. See [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize) instructions. Also, example code for functions and in the vignette still has use of = for assignments instead of <-.

No more NOTE when running `BiocCheck()` concerning the use of `=`, we also removed all the statement using `1:...` and substituted with the use of `seq_len()`. We are working on avoiding the use of for loops, but it is more complex because many of them have side effects. 

> 3. I see that the number of user-facing functions has been reduced. However, only 4 out of 15 Rd files have an `\examples` section. Please refer to [Examples](https://contributions.bioconductor.org/docs.html#examples) section of developer's guide.

All the functions now have runnable examples, all the datasets are used in examples or in the vignette. The vignette should now be more clear

> - First, there is no definition of "agony" readily visible in the documents.

We added the information based on the suggestion received

> A) Phyogenetic trees can be input. But the software doesn't make use of Bioconductor package [treeio](http://bioconductor.org/packages/release/bioc/html/treeio.html) infrastructure.
> B) Return values are a basic list. The package should define [a class with accessor functions](https://contributions.bioconductor.org/r-code.html#class-design) to store results in.

We are working on it

**Comment by luca-dex** [comment]
Dear @DarioS we worked also on the following point:

> A) Phyogenetic trees can be input. But the software doesn't make use of Bioconductor package [treeio](http://bioconductor.org/packages/release/bioc/html/treeio.html) infrastructure.

We tried to find a way to integrate the data provided by `treeio` but this package works with classic phylogeny, while our package works with [mutational tree](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0936-x). There isn't a straightforward way to convert the output of `treeio` and use it as input for our package and, up to our knowledge, we didn't find any R package that allows to work on mutation trees differently than what we're doing now (with adjacency matrix).

At the moment, creating a conversion tool from one data type to the other is outside of the scope of this package.

We better defined these aspects in the documentation to avoid misundestanding on the input data.

We would like to know if you think it would be possible to include our package in the current release or if you think we will have to wait for next round of review.

Thanks for your support

**Comment by DarioS** [comment]
Ah, perhaps treeio is not suitable for such tree representation then. However, the package still

- Has numerous `for` loops.
- Does not use any Bioconductor classes and does not have a connection to the existing Bioconductor ecosystem.
- Vignette still lacks biological interpretation. "ASCETIC is a novel framework for the inference of a set of statistically significant temporal patterns involving alternations in driver genes from cancer genomics data." What novel temporal patterns are identified in the example data sets?
- Lacks a container class with a `show` method for the results and floods the R console with a huge amount of output (this is fine and seen for many CRAN packages but is not fine for Bioconductor. Please try [edgeR](http://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf) as an example of what is expected).

```r
library(edgeR)
myData <- matrix(rpois(500, 100), ncol = 5, dimnames = list(paste("Gene", 1:100), paste("Patient", 1:5)))
edgeRcontainer <- DGEList(myData, genes = rownames(myData))
edgeRcontainer
```
results in the display of

```r
An object of class "DGEList"
$counts
       Patient 1 Patient 2 Patient 3 Patient 4 Patient 5
Gene 1       107        95       107       106        92
Gene 2        98       117        91        92       128
Gene 3        95        93       115        98        93
Gene 4       123       130       110        93       133
Gene 5       105       113       103       122        98
95 more rows ...
$samples
          group lib.size norm.factors
Patient 1     1    10081            1
Patient 2     1    10102            1
Patient 3     1     9988            1
Patient 4     1    10025            1
Patient 5     1    10094            1
$genes
        genes
Gene 1 Gene 1
Gene 2 Gene 2
Gene 3 Gene 3
Gene 4 Gene 4
Gene 5 Gene 5
95 more rows ...
```

Note the "95 more rows ...". In contrast, ASCETIC prints everything into the R console. On a realistic data set with about 20000 genes (e.g. exome sequencing data), this would be much worse than for the small example consisting of only twenty genes in the vignette and that is already flooding the R console with many vertical screens of output.

![image](https://user-images.githubusercontent.com/631218/233208996-823e1777-e7ae-45a7-912a-9a3e53ebdc4e.png)


There are still major changes required to meet the Bioconductor contributor requirements.

**Comment by lshep** [comment]
@danro9685  will you be making any updates soon to address @DarioS  concerns?  We generally like to see responses within 2-3 weeks to keep reviews moving in the process and to included in Bioconductor as soon as possible.

**Comment by danro9685** [comment]
Dear @lshep,

Apologies for the delay on our side. Let me include @luca-dex in the loop, he is the one now looking into the changes of the package.

Thank you for the reminder!
Daniele

**Comment by luca-dex** [comment]
Dears @lshep 
during the past few months we have been really active, but we are continuing to work on the package. Concerning the feedback received from @DarioS :

- `for` **loops.** The majority of the loops in the package have side effects and cannot be substituted with apply-style function. We can refactor the one that can be substituted and insert a comment on the other. Is it a possible solution?

- **Biological motivation behind this package.** We included a link to a preprint version of the paper that will present the theorethical approach behind this package. The paper is at an advanced stage of revision of Nature Communications and we hope it will be published soon

- **use of other Bioconductor package.** We didn't find any other package suitable to be integrated with ASCETIC. We looked into the one you suggested, but with not much success. Do you have any other suggestion?

- **Lacks a container class with a `show` method.** We can look into it in coming months. This was not something we were planning to do and it will take a bit of time to be completed.

We understand that our request is now pending since long time. In case it is possible we would like to keep it open. If not, it is fine to us to close it. We will reopen the request as soon as we will address last two points raised.

Thank you for your patience and support
Best

**Comment by danro9685** [comment]
Dear @lshep, Dear @DarioS,
As the manuscript of the method has been finally published in Nature Communications (https://www.nature.com/articles/s41467-023-41670-3), I have now updated the biological motivation behind this package.
I expect @luca-dex to be fixing the issues with for loops soon and then pushing the updated version.
Please when you can let us know your feedback on points 3 and 4 of @luca-dex's previous questions.
All the best,
Daniele

**Comment by DarioS** [comment]
- ASCETIC is a package that computes on mutations. It should at least use [RaggedExperiment](https://bioconductor.org/packages/release/bioc/html/RaggedExperiment.html) as the main input data type. See [Common Classes](https://contributions.bioconductor.org/important-bioconductor-package-development-features.html?q=show#commonclass) for other potential interoperability opportunities.
- A container class and `show` method for your results is essential. See [Class Design](https://contributions.bioconductor.org/r-code.html?#class-design).

> Implement a `show()` method to effectively convey information to your users without overwhelming them with detail.

**Comment by lshep** [comment]
@luca-dex / @danro9685  did this last push address @DarioS comments?  Normally if the package is ready for re-review a comment is made to indicate such

**Comment by luca-dex** [comment]
Thanks @lshep for the clarification. We are working to have the package ready for next review, but at the moment we have still some work to do. We will give a sign as soon as it is done and can be reviewed.

**Comment by lshep** [comment]
We will close this issue for now. Please let us know when you are ready to continue and we will reopen.
