### ISSUE TITLE
mnmer

### ISSUE THREAD

**Issue by labinfo-lncc** [Bioconductor/Contributions#2843]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/labinfo-lncc/mnmer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission.  I see that no Bioconductor data structures are used; what is the motivation for including it in the Bioconductor ecosystem?  Perhaps users could benefit from use of GenomicFiles or FaFiles ...
This sequence in your vignette
```
Bases other than A, C, T, and G were disregarded.

For classification outside of mnmer, we utilize the (1,1)-mer feature matrices.

Here’s a real-world example of code using , and :

library(caret)
## Loading required package: ggplot2
## Loading required package: lattice
classes <- replicate(nrow(mosquito), "mosquito.vir")
featureMatrix_mosquito <- cbind(mosquito,classes)
classes <- replicate(nrow(plant), "plant.vir")
featureMatrix_plant <- cbind(plant,classes)

featureMatrix <- rbind(featureMatrix_mosquito, featureMatrix_plant)
featureMatrix <- subset(featureMatrix, select = -c(seqid))
train_index <- caret::createDataPartition(featureMatrix$classes, p=0.8, list=FALSE)
train <- featureMatrix[train_index, ]
test <- featureMatrix[-train_index, ]
control <- caret::trainControl(method="cv", 
                        summaryFunction=twoClassSummary, 
```
seems to be too complex, some class to manage the various features and class types should be introduced.  Also there seem to be words missing at the line that includes "real-world example".  Please explain the scientific interpretation of the worked example.

**Comment by labinfo-lncc** [comment]
Dear, Vince Carey

Thank you for reviewing our package. 

The mnmer package was created to provide a quick and easy approach to generate (m,n)-mers, a novel feature extraction technique (Paper in press). We opted to have a few dependencies so that our functions would not fail in the future (low coupling). We wrote the main code in C++ in order to operate faster with huge FASTA files. Therefore, we choose not to use GenomicFiles or FaFiles. 
The mnmer function returns a feature matrix that may be used for clustering or classification. In essence, the example described in the vignette is to distinguish between viruses that infect plants and viruses that infect insects. We applied the (m,n)-mers as a feature from FASTA files and used them for classification with Random Forest within the Caret package. We updated the vignette to incorporate additional information about this example.
Furthermore, we want our package to be a part of the Bioconductor ecosystem because of its stability, realibility, and ease of distribution to the scientific community.

**Comment by labinfo-lncc** [comment]
Dear, Vince Carey

Thank you for reviewing our package. 

The mnmer package was created to provide a quick and easy approach to generate (m,n)-mers, a novel feature extraction technique (Paper in press). We opted to have a few dependencies so that our functions would not fail in the future (low coupling). We wrote the main code in C++ in order to operate faster with huge FASTA files. Therefore, we choose not to use GenomicFiles or FaFiles. 
The mnmer function returns a feature matrix that may be used for clustering or classification. In essence, the example described in the vignette is to distinguish between viruses that infect plants and viruses that infect insects. We applied the (m,n)-mers as a feature from FASTA files and used them for classification with Random Forest within the Caret package. We updated the vignette to incorporate additional information about this example.
Furthermore, we want our package to be a part of the Bioconductor ecosystem because of its stability, realibility, and ease of distribution to the scientific community.

**Comment by vjcitn** [comment]
Thanks for your note.  You are not taking advantage of existing Bioconductor infrastructure.  The Biostrings package has efficient self-describing representations of FASTA data:
```
Browse[2]> inputParameter1
[1] "/home/stvjc/R-43dev-dist/lib/R/library/mnmer/extdata/mosquito_vir.fasta"
Browse[2]> readDNAStringSet(inputParameter1)
DNAStringSet object of length 25:
     width seq                                              names               
 [1] 11676 ATGTCAAGCCAATTCATTTTTGA...TCGATCAAAATTTGATTTTTAA MH734985.1_8_1
 [2]   702 ATGGCAAACCAATTTATTTTCCA...CCAATTCGGCATAAACATTTAA AB334184.1_23_2
 [3]  6759 ATGGACAACCACAAGATCAATCA...TCGATCAAAATTCGATTTTTGA MH735095.1_50_3
 [4]   702 ATGTCAAGCCAATTCATTTTTGA...GCAATTCGGCATCAACATCTAA MH734985.1_62_4
 [5]   702 ATGTCAAGCCAATTCATTTTTGA...CCAATTTGGTATAAATATCTAA MH734984.1_63_5
 ...   ... ...
[21] 12218 GTACTCCACACTAATAACTTACA...AAAAATCAATTTCTTTATATAG KP063897.1_365_21
[22]  4463 AGTAGTGTACTACCGATACAATC...TTGATATCGGTAGCACACTACT KX100152.1_405_22
[23]  6855 CCCTCAGTTATACAATTACTAAA...AAGCAGTAACATATGATGAGGA NC_034489.1_414_23
[24]  1068 GTTAATATCAGAGGTAAATAACC...CACTTTTGTCAAACTTTCTAAG KF254795.1_424_24
[25] 12189 ATGGCTGCGTGAGACACACGTAG...GTTATTTTGTTTTTAATATTTC LC500216.1_438_25
```
k-mer distributions are computed using oligonucleotideFrequency.  You have a nice vignette so I will pass pre-check but in review you will likely have to take advantage of Bioconductor infrastructure to achieve some of the aims of the package.

**Comment by vjcitn** [comment]
Using "inputParameter1" as a variable name in mnmer is not advisable.  Use variable names that have semantic value.

**Comment by DarioS** [comment]
Consists of one function which is 48 lines of code. Perhaps could instead be added to an existing package such as [Biostrings](https://bioconductor.org/packages/release/bioc/html/Biostrings.html).

**Comment by labinfo-lncc** [comment]
We appreciate your suggestion. We included the BioStrings utility readDNAStringSet and alphabetFrequency in our main function. Now, the mnmer package has new functionality importing BioStrings, such as reading fasta.gz files and filtering sequences based on N + IUPAC content. We have updated the package documentation. As our package consists of R and C++ code, it is tied to a proposal for novel feature extraction. The paper was submitted for publication. After publication, we will consider mnmer may be incorporated in a much larger package such as Biostrings.

**Comment by DarioS** [comment]
I think that it is a nice idea to implement conditional frequencies as a companion to unconditional frequencies, but instead of adding another package for users to install, I would like to see a [pull request to Biostrings](https://github.com/Bioconductor/Biostrings/pulls)' `oligonucleotideFrequency` function. Your function still needs improved interoperability with Bioconductor classes, such as `XStringSet`, which `oligonucleotideFrequency` already has. Also, please read the [Contributions handbook](https://contributions.bioconductor.org/) for appropriate coding style.

- Avoid `for` loops in R code wherever possible. For example,
  ```r
     for (i in 1:length(seqs)){
          ni <-  alphabetFrequency (seqs[i], baseOnly=TRUE, as.prob=TRUE)
          ...
  ```
  This is inefficient because you should use vectorised operations when they are available, rather than calling `alphabetFrequency` repeatedly for each single sequence. It is substantially faster to call it once with a vector of inputs.
- Don't use `1:length(seqs)` but use `seq_along(seqs)`.
- Avoid variable names such as `sqs` and `ts` for future maintainability. Please see [self-documenting code](https://hackbrightacademy.com/blog/writing-self-documenting-code/#:~:text=What%20is%20self%2Ddocumenting%20code,not%20heard%20the%20term%20before.) for better naming.

This and some other coding issues are described in [Section 15.3.1: Code Syntax and Efficiency](https://contributions.bioconductor.org/r-code.html) and [Section 15.4.3: Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize).

There is only one unit test and it seems to be an attempt to cheat the package checking system by specifying two irrelevant checks which are unrelated to mnmer package's code.
```r
test_that("mnmer", {
  expect_equal(2 * 2, 4)
  expect_that(1 / "a", throws_error())
})
```

Please replace this by a small number (> 1) of meaningful unit tests which check the correctness of the calculations on very small test data, for which the correct result can be manually calculated and easily compared to the package-computed value.

**Comment by vjcitn** [comment]
Hi there -- I want to thank the contributors and Dario for their engagement on this package.  I think closure/decline needs to be reconsidered by a broader group of evaluators and we will get back to you soon.

**Comment by vjcitn** [comment]
Hi, I am joining the review process here.  Dario has a number of important suggestions on loops, seq and unit tests, please take care of these.  The concept of contributing the function to Biostrings is interesting but we will table that for now.

This material in the vignette
```
The package needs 4.0.0 or later, Biostrings and Utils.

The user should install the package from the GitHub repository. It can be done by using the package.

library(devtools)
install_github("labinfo-lncc/mnmer", ref="main")
```
is problematic.  The first sentence is incomplete and has a case error.  The installation instructions should follow the contributions manual and not refer to devtools and github.

I also don't understand how

![PR](https://user-images.githubusercontent.com/4624066/213341166-963e7bee-8530-4a2f-8c94-b474cf471f3e.jpg)

has a caption indicating AUC-PR value .95.  The line seems to indicate a perfect procedure.  Please clarify, this seems to occur later too.

**Comment by otaviojbbrustolini** [comment]
Dear Collaborators,
We appreciate your significant suggestions for improving our package. Unfortunately, we are rethinking the submission. We wish to make more refinements and optimizations shortly. So, we want to decline the submission of the package mnmer.

**Comment by labinfo-lncc** [comment]
Dear Collaborators,
We appreciate your significant suggestions for improving our package. Unfortunately, we are rethinking the submission. We wish to make more refinements and optimizations shortly. So, we want to decline the submission of the package mnmer.
