### ISSUE TITLE
partCNV

### ISSUE THREAD

**Issue by rx-li** [Bioconductor/Contributions#2861]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rx-li/partCNV

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission.  It needs some work before we review.  1) example(partCNV) doesn't really do anything.  2) you include cytoband addresses that are 0 based, that come from UCSC, but Bioconductor already has cytobands for hg38 in a GRanges in AH53178, adhering to the 1-based convention of Bioconductor, 3) when I look at the vignette, the colors in the UMAP visualizations do not have a key visible.

**Comment by rx-li** [comment]
Dear Vince,

Thanks so much for the insights.
I have updated the package:
1. The examples should run normally now.
2. I deleted the cytoband data, and use "AH53178"  in AnnotationHub now.
3. I added the axises back to the UMAP.

Please let me know if you have any questions.

Best regards,
Ruoxing

**Comment by ococrook** [comment]
Hi @rx-li 

Thanks for the submission the package looks interesting a useful. Having a first quick pass through the package there are some aspect that need addressing before a more detailed review.

Bioconductor objects:

Whilst we are happy for methods to also work on Seurat object we require that the package build on the BioC infrastructure. If  I've understood your package correctly it could start from a `SingeCellExperiment` object instead? Do correct me if there a more appropriate object. I imagine getting your code to work with Bioc object will change quite a lot of the vignette and code so its worth addressing the issues first

Other issues:

- [ ] add biocViews: SingleCell, Classification
- [ ] 'LazyData:' in the 'DESCRIPTION' should be set to false or removed
- [ ] Avoid 1:...; use seq_len() or seq_along()
- [ ] Avoid 'cat' and 'print' outside of 'show' methods
- [ ] Avoid using '=' for assignment and use '<-' instead
- [ ] Avoid the use of 'paste' in condition signals
- [ ] Please add a NEWS file
- [ ] Please add Unit tests

Looking forward to including this package in the Bioc family

**Comment by rx-li** [comment]
Dear @ococrook,

Thanks so much for your review and comments.
You are right about the `SingleCellExperiment` object. If we start from the `SingeCellExperiment` object, counts can be normalized and log transformed manually, and I have included the normalization method in the vignette. 

For the other issues, please find the one-by-one responses below:
- add biocViews: SingleCell, Classification 
    - Added required biocViews in the Description file
- 'LazyData:' in the 'DESCRIPTION' should be set to false or removed
    - Removed "LazyData"
- Avoid 1:...; use seq_len() or seq_along()
    - Changed "1:..." to seq_len()
- Avoid 'cat' and 'print' outside of 'show' methods
    - Changed "print" or "cat" to "message" 
- Avoid using '=' for assignment and use '<-' instead
    - Modified accordingly
- Avoid the use of 'paste' in condition signals
    - Removed "paste" in signaling functions
- Please add a NEWS file
    - Added NEWS file 
- Please add Unit tests
    - Added unit tests.
 
Thanks again for your help. Looking forward to your reply.

**Comment by ococrook** [comment]
Sorry did you have a look through the build report and fix the Errors? http://staging.bioconductor.org:8000/job/18410/ 

You also need to state the R version of the code.

**Comment by ococrook** [comment]
@rx-li 

The package still builds with Errors, we can close the issue until you have time address these at which point we can re-open the issue if necessary?

**Comment by rx-li** [comment]
@ococrook 
I am so sorry that I overlooked the email regarding the issue. I will address it ASAP. 
Thanks so much.

**Comment by ococrook** [comment]
@rx-li 

Are you subscribed to the mailing list?

**Comment by lshep** [comment]
I don't see the maintainer email registered.  If you tried to register, there is normally a confirmation email sent. It can sometimes be marked as spam/junk.  Please check those folders for the confirmation email.

**Comment by ococrook** [comment]
The package only cursorily engages with `SingelCellExperiment` as a passing comment. For the package to be accepted to Bioconductor it needs to be more carefully integrated into the workflow.

**Comment by rx-li** [comment]
Dear @ococrook 

Thanks for your comment. I will add more steps on how to start from `SingelCellExperiment`. 

Best regards,
Ruoxing

**Comment by ococrook** [comment]
Brilliant, thank you!

**Comment by rx-li** [comment]
Dear @ococrook,

Good afternoon. 

I have added a function which can normalize the counts for a `SingleCellExperiment` object, and its results can be used in the analysis. 
Please let me know if anything else is needed. 

Thanks,
Ruoxing

**Comment by ococrook** [comment]
Great, thank you Ruoxing.

Can you add Bioconductor install instructions and then I can accept the package

**Comment by rx-li** [comment]
The install instructions are added. 
Thanks so much, @ococrook!

**Comment by rx-li** [comment]
Dear @ococrook ,

Thanks for accepting our package. 

I am wondering where I can access the Bioconductor webpage of the package. 
I saw that the package had been nightly built, but I did not find the URL for the package.

Best regards,
Ruoxing

**Comment by ococrook** [comment]
Hi @rx-li,

It will appear it due course, it can take sometime for the maintainers to set-up the webpage. Youll be able to search here when it's ready: https://www.bioconductor.org/packages/devel/BiocViews.html#___Software. I suspect if should take a few more days.

Best wishes,
Olly

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/rx-li.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("partCNV")`. The package 'landing page' will be created at

https://bioconductor.org/packages/partCNV

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
