### ISSUE TITLE
HERON

### ISSUE THREAD

**Issue by mcilwain** [Bioconductor/Contributions#2880]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Ong-Research/HERON

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by mcilwain** [comment]
Hello, I'm having trouble with the package building on the MacOS (merida1).  It seems that the metap package (from CRAN) is missing? 

ERROR: dependency metap is not available for package HERON

Is there a way to get this dependency installed on the build machine?

**Comment by lshep** [comment]
yes I can investigate.  @HelenaLC in the meantime you can review based on the linux

**Comment by LiNk-NY** [comment]
Hi @mcilwain 

Thank you for your submission. Please see the review below.

Best regards,
Marcel

---

# HERON #2880

## DESCRIPTION

* Include `BugReports` and `URL` fields

## NAMESPACE

* Looks good.

## vignettes

* Avoid using `;` in R code.
* Is the data using the legacy `ExpressionSet` data structure? `pData` is an
old interface.

## R

* If possible, avoid acronyms `CCT` and opt for descriptive names.
* Reduce the cyclomatic complexity in functions such as `CCT`, `findBlocksT`,
if possible. See the `cyclocomp` package.
* Data looks good.
* Remove all `;` from the R code. It is not necessary when there adequate
space (e.g., `findEpitopeSegments`).
* Avoid the 'copy and append' method when using `for` loops in
`getClusterSegments` and other functions. We recommend the 'allocate and fill'
method. For example:
```r
result <- vector("numeric", length = 10)
for (i in seq_along(result))
    result[i] <- ...
```
* Avoid `1:n` sequence generation, use `seq_along` or `seq_len`
* Remove exclamation points in error messages, e.g., `!`.
* Avoid code repetition in `wilkMin/Max*Meta` functions. It seems that they
can be combined into a single function with `n` and `min/max` parameters.

## tests

* We highly recommend improving the coverage of tests:
```r
> covr::package_coverage()
HERON Coverage: 23.64%
R/CCT.R: 0.00%
R/meta.R: 0.00%
R/preprocess.R: 0.00%
R/stat.R: 0.00%
R/epitope_finding.R: 19.65%
R/multilevel.R: 47.54%
R/misc.R: 67.53%
R/epitope.R: 91.26%
```

**Comment by LiNk-NY** [comment]
Hi @mcilwain 
We will close the issue due to inactivity. 
Thank you for your submission.
Best regards,
Marcel

**Comment by mcilwain** [comment]
So I should resubmit after I get a new iteration ready?

Thanks,
Sean

________________________________

**Comment by LiNk-NY** [comment]
You can re-open the issue when ready. 
Thanks!

**Comment by mcilwain** [comment]
@LiNk-NY, @HelenaLC , @lshep, @vjcitn, I'm ready with a new version bump for review.  Could I get the issue reopened?

**Comment by LiNk-NY** [comment]
Hi @mcilwain 
Can you respond to the review item by item? 
Thank you.
Best,
Marcel

**Comment by mcilwain** [comment]
> Hi @mcilwain
> 
> Thank you for your submission. Please see the review below.
> 
> Best regards, Marcel
> 
> # HERON #2880
> ## DESCRIPTION
> * Include `BugReports` and `URL` fields
Thanks, Included.

> ## NAMESPACE
> * Looks good.
Thanks
> 
> ## vignettes
> * Avoid using `;` in R code.
I have removed all unneccessary ";"

> * Is the data using the legacy `ExpressionSet` data structure? `pData` is an
>   old interface.
I have recoded HERON to use subclasses of SummarizedExperiment and removed all references to pData

> 
> ## R
> * If possible, avoid acronyms `CCT` and opt for descriptive names.
I renamed the functions and file to a more descriptive function name

> * Reduce the cyclomatic complexity in functions such as `CCT`, `findBlocksT`,
>   if possible. See the `cyclocomp` package.
I have reduced the cyclocomp in for CaucyCombinationTest

> * Data looks good.
Thanks
> * Remove all `;` from the R code. It is not necessary when there adequate
>   space (e.g., `findEpitopeSegments`).
I did a remove of the ';'

> * Avoid the 'copy and append' method when using `for` loops in
>   `getClusterSegments` and other functions. We recommend the 'allocate and fill'
>   method. For example:
> 
> ```r
> result <- vector("numeric", length = 10)
> for (i in seq_along(result))
>     result[i] <- ...
> ```
> 
Where I could, I have replaced the copy and append code with allocate and fille

> * Avoid `1:n` sequence generation, use `seq_along` or `seq_len`
I believe I replaced all of these 

> * Remove exclamation points in error messages, e.g., `!`.
Removed

> * Avoid code repetition in `wilkMin/Max*Meta` functions. It seems that they
>   can be combined into a single function with `n` and `min/max` parameters.
I have recoded these to reduce code repetition


> 
> ## tests
> * We highly recommend improving the coverage of tests:
> 
> ```r
> > covr::package_coverage()
> HERON Coverage: 23.64%
> R/CCT.R: 0.00%
> R/meta.R: 0.00%
> R/preprocess.R: 0.00%
> R/stat.R: 0.00%
> R/epitope_finding.R: 19.65%
> R/multilevel.R: 47.54%
> R/misc.R: 67.53%
> R/epitope.R: 91.26%
> ```

New coverage of tests:
HERON Coverage: 96.85%
R/epitope.R: 93.81%
R/multilevel.R: 94.48%
R/misc.R: 96.30%
R/epitope_finding.R: 96.82%
R/stat.R: 97.52%
R/meta.R: 99.03%
R/AllClasses.R: 100.00%
R/CaucyCombinatonTest.R: 100.00%
R/preprocess.R: 100.00%

Thanks!

**Comment by LiNk-NY** [comment]
Hi @mcilwain 
Sorry for the delay in getting back to you. It has been a pretty busy past few weeks.
Your package looks good to go. It passes `R CMD build` and `check` as well as `BiocCheck`.
Best regards,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mcilwain.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HERON")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HERON

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
