### ISSUE TITLE
DiffCircaPipeline

### ISSUE THREAD

**Issue by XiangningXue** [Bioconductor/Contributions#2886]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DiffCircaPipeline/DiffCircaPipeline

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
I see you are importing diffCircadian.  Is that to be submitted as a related package?  @lshep

**Comment by XiangningXue** [comment]
Hi Vince,

I do not intend to submit the package diffCircadian because I am not the package’s creator. In that case, could I continue to submit my package, or should I rewrite my package to exclude the part I used diffCircadian functions?

Best,
Xiangning

From: Vince Carey ***@***.***>
Date: Wednesday, January 4, 2023 at 8:05 AM
To: Bioconductor/Contributions ***@***.***>
Cc: Xiangning Xue ***@***.***>, Mention ***@***.***>
Subject: Re: [Bioconductor/Contributions] DiffCircaPipeline (Issue #2886)

I see you are importing diffCircadian. Is that to be submitted as a related package? @lshep<https://github.com/lshep>

**Comment by lshep** [comment]
All dependencies of packages must be on CRAN or Bioconductor. If diffCircadian is not going to be submitted, then yes you would have to exclude the use in your package.

**Comment by XiangningXue** [comment]
Thanks, I will update my package. When it is updated, could I follow up with this email?

Best,
Xiangning

From: lshep ***@***.***>
Date: Wednesday, January 4, 2023 at 9:52 AM
To: Bioconductor/Contributions ***@***.***>
Cc: Xiangning Xue ***@***.***>, Mention ***@***.***>
Subject: Re: [Bioconductor/Contributions] DiffCircaPipeline (Issue #2886)

All dependencies of packages must be on CRAN or Bioconductor. If diffCircadian is not going to be submitted, then yes you would have to exclude the use in your package.

**Comment by lshep** [comment]
Yes. Let us know when the changes have been made to your github and we will continue the pre-review checks.

**Comment by XiangningXue** [comment]
Hi there,

I have updated the package without citing diffCircadian.

Thanks,
Xiangning

From: lshep ***@***.***>
Date: Wednesday, January 4, 2023 at 9:55 AM
To: Bioconductor/Contributions ***@***.***>
Cc: Xiangning Xue ***@***.***>, Mention ***@***.***>
Subject: Re: [Bioconductor/Contributions] DiffCircaPipeline (Issue #2886)

Yes. Let us know when the changes have been made to your github and we will continue the pre-review checks.

**Comment by vjcitn** [comment]
ggradar seems to be absent from both Bioconductor and CRAN.  You can't depend on or import from  a package that is only in github.  Sorry.

**Comment by XiangningXue** [comment]
I will work on changing the packages. Thanks for checking.

**Comment by vjcitn** [comment]
I don't see any changes yet.  Reopen this issue when you are ready.
