### ISSUE TITLE
MsDataHub submission

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/Contributions#2887]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RforMassSpectrometry/MsDataHub

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lgatto** [comment]
Just a quick note about the warning:

```
* Checking vignette directory...
    * WARNING: Evaluate more vignette chunks.
        7 code chunks / 10 total = 70% percent unevaluated
        0 non-exec code chunks (e.g., '``` r')
```

This is a data package and the non-evaluated code chunks show how to download datasets without actually doing so to save disk time when first building the package/vignette and space thereafter (assuming the cache is persistent). I can of course change this if preferred.

**Comment by lazappi** [comment]
I'm happy to ask the core and see what they think but my feeling is the vignette should be executed like for a normal package (I had a quick look at a couple of data packages and that seems to be the case). The space concern is reasonable though so I would suggest trying to show whatever the smallest reasonable amount of data is.

**Comment by vjcitn** [comment]
What are the sizes of downloads needed to carry this out?

**Comment by lgatto** [comment]
For now, there's 484M of data files, detailed below. 

```
cdf:
total 3.6M
-rw-r--r-- 1 lgatto lgatto 3.6M Nov 28 14:50 ko15.CDF

cptac:
total 30M
-rw-r--r-- 1 lgatto lgatto 8.5M Dec  1 12:53 cptac_a_b_c_peptides.txt
-rw-r--r-- 1 lgatto lgatto 6.9M Dec  1 12:53 cptac_a_b_peptides.txt
-rw-r--r-- 1 lgatto lgatto  15M Dec  1 12:53 cptac_peptides.txt

PXD000001:
total 310M
-rw-r--r-- 1 lgatto lgatto 9.4M Nov 29 09:32 TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzid
-rw-r--r-- 1 lgatto lgatto 301M Nov 29 09:32 TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML.gz

sciex:
total 35M
-rw-r--r-- 1 lgatto lgatto 17M Nov 28 14:51 20171016_POOL_POS_1_105-134.mzML
-rw-r--r-- 1 lgatto lgatto 18M Nov 28 14:51 20171016_POOL_POS_3_105-134.mzML

TripleTOF-SWATH:
total 107M
-rw-r--r-- 1 lgatto lgatto 39M Nov 27 18:29 PestMix1_DDA.mzML
-rw-r--r-- 1 lgatto lgatto 69M Nov 27 18:29 PestMix1_SWATH.mzML
``` 

There will be more - for example, some data from the recently added `MsQuality` package will also be added once this one makes it into Bioconductor. I would prefer to be consistent and introduce all datasets in the same way, either with code evaluation, or without.

**Comment by vjcitn** [comment]
Let's present this option set to the TAB on the next call February call   I will set a seven minute timeframe to present the data and have a discussion

**Comment by lgatto** [comment]
@lazappi - I just found an issue with the package. One of the files has been uploaded with a typo, so that now there's an inconsistency between the filename and the alias in the documentation, which generates a warning:

```
 checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘TMT_Erwinia_1uLSike_Top10HCD_iso1l2_45stepped_60min_01-20141210.mzid’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```
(it should be `TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzid`)

I am waiting to hear from Lori to see if this can be changed or it I should simple keep the filename with typo and update the man page accordingly.

There's another issue with this and another file (with a similar name):

```
> MsDataHub::TMT_Erwinia_1uLSike_Top10HCD_iso1l2_45stepped_60min_01-20141210.mzid()
Error: unexpected symbol in "MsDataHub::TMT_Erwinia_1uLSike_Top10HCD_iso1l2_45stepped_60min_01-20141210.mzid"
> MsDataHub::TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML.gz()
Error: unexpected symbol in "MsDataHub::TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML.gz"
```

which I suspect might be because of the long file/function names. I have asked Lori.

**Comment by lgatto** [comment]
@lazappi - some updates:
- The typo has been fixed by Lori.
- The error is due to a `-` in the file names, that doesn't translate to function names. Am waiting to hear from Lori to see how to best address this. 

I'll keep you posted.

**Comment by lgatto** [comment]
Hi @lazappi - The feedback from the TAB was to "evaluate as needed", without enforcing anything particular. 

I have updated the vignette with evaluated code chunks and illustrate loading them with existing infrastructure. Let's see how things go in terms of timing when the vignette is evaluated the first time and data are downloaded and cached.

**Comment by lgatto** [comment]
So the error here is about runnable man page examples, which essentially boils down to the code in the vignette. I am happy to duplicate the vignette's chunks in the man pages examples, but we might be running in circles here.

**Comment by lazappi** [comment]
I think this error is going to happen on the actual build machines which we don't want so there probably needs to be some kind of examples, either the same as in the vignette or some small dummy example as you see fit.

**Comment by lshep** [comment]
@lazappi The error wouldnt occur on the daily builders as we still don't run bioccheck across all existing packages.  I think its okay to let it go.

**Comment by lgatto** [comment]
Thank you. May be it might be useful to reflect on the package requirements for data packages. I am not sure that executable code in all examples and vignettes make sense - there isn't much any smaller dummy example I can run other than loading the data. This will inevitably lead to duplication in the man pages and the vignette, which isn't very useful for the user. 

Maybe that in such cases, it would be allowed to not have examples in the man pages but explicitly redirect the users to the vignette or, alternatively, have examples in the man page and use the vignette for a general overview of the data without examples (or longer ones that make use of the data... although these are generally present in the software package).

**Comment by lazappi** [comment]
Hi @lgatto

Thanks for submitting **MsDataHub** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation. There are only very minor comments other than a question about how the package works.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :question: I haven't reviewed a data package before so I might be misunderstanding how it works but I would expect the package to contain functions for downloading each of the datasets. As far as I can see it just contains metadata of each dataset and you still need the original packages to get them. Is this correct of is there something I am missing?

## DESCRIPTION file

- [ ] :green_circle: Consider adding a `BugReports` field
- [ ] :green_circle: Consider adding a `URL` field

## Documentation


### Vignette

- [ ] :green_circle: I don't think it's necessary to include the GitHub installation instructions, users will be able to install the release/devel version from Bioconductor after the package is accepted

### Man pages

- [ ] :green_circle: Consider adding a package man page

**Comment by lgatto** [comment]
## General package development

> * I haven't reviewed a data package before so I might be misunderstanding how it works but I would expect the package to contain functions for downloading each of the datasets. As far as I can see it just contains metadata of each dataset and you still need the original packages to get them. Is this correct of is there something I am missing?

Yes, the package defines a metadata table that describes the datasets, that have already been made available via ExperimentHub. The functions to download the data are created when the package is loaded. This is handled by `ExperimentHub::createHubAccessors()` that is called by `.onLoad`, defined in `zzz.R`: a function `foodata()` will be created for data with title `foo`; and the title is retrieved from the metadata.

No other packages are involved.

## DESCRIPTION file

> * Consider adding a `BugReports` field

There is already a BugReports field that points to https://github.com/RforMassSpectrometry/MsDataHub/issues.

> * Consider adding a `URL` field

I have added a pkgdown file that is referred to in the URL field: https://rformassspectrometry.github.io/MsDataHub/

## Documentation
### Vignette

> I don't think it's necessary to include the GitHub installation instructions, users will be able to install the release/devel version from Bioconductor after the package is accepted

I have removed the Github installation instructions. Generally, I do however find these important as some new features are first released on Github for alpha-testing before being pushed to devel. In the case of a data package, it's probably not relevant.

### Man pages

> * Consider adding a package man page

There's a package man page, that also documents to `MsDataHub()` function: see ?MsDataHub.

**Comment by lgatto** [comment]
As [discussed above](https://github.com/Bioconductor/Contributions/issues/2887#issuecomment-1453444588), the error is 

```
* Checking man page documentation...
snapshotDate(): 2023-02-28
    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples.
```
and can be ignored.

**Comment by lazappi** [comment]
Thanks. I am happy to approve this now as we have been told we can ignore that error 🎉. It should be in Bioconductor devel in a few days after it is picked up by the build system.

**Comment by lgatto** [comment]
Thank you!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lgatto.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MsDataHub")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MsDataHub

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
