### ISSUE TITLE
SiPSiC

### ISSUE THREAD

**Issue by DanielDavis12** [Bioconductor/Contributions#2891]
Repository: https://github.com/DanielDavis12/SiPSiC

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by DanielDavis12** [comment]
@vjcitn Hi, thanks for checking out my proposed package.
You added a "pending pre-review changes" label, but unfortunately I can't figure out what is wrong with the current version.. Could you maybe share some insight?

**Comment by vjcitn** [comment]
Looks like my comment was lost.  I will try to reconstruct.

**Comment by vjcitn** [comment]
```
## Make sure your matrix is indeed a sparse matrix (of type dgCMatrix)! 

rownames(geneCountsMatrix) <- c("Gene1", "Gene2", "Gene3", "Gene4")
colnames(geneCountsMatrix) <- c("Cell1", "Cell2", "Cell3", "Cell4")
pathwayGenesList <- c("Gene1", "Gene2", "Gene4")
```
This isn't "wrong" but it doesn't use Bioconductor classes in the expected way.  The purpose of SummarizedExperiment and derivatives is to couple metadata and numerical data in useful ways.

```
> SingleCellExperiment(assays=SimpleList(counts=geneCountsMatrix))
class: SingleCellExperiment 
dim: 4 4 
metadata(0):
assays(1): counts
rownames(4): Gene1 Gene2 Gene3 Gene4
rowData names(0):
colnames(4): Cell1 Cell2 Cell3 Cell4
colData names(0):
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):
> sce = .Last.value
> assay(sce)
4 x 4 sparse Matrix of class "dgCMatrix"
      Cell1 Cell2 Cell3 Cell4
Gene1     1     .     .     .
Gene2     .     2     .     .
Gene3     .     .     3     .
Gene4     .     .     .     4
> colData(sce)
DataFrame with 4 rows and 0 columns
> metadata(sce)
list()
```
When you use SingleCellExperiment to organize your data, you can use sparse structures for numerics, you can annotate features and cells, connect projections, filter on cell characteristics or feature sets, and so forth, and interoperate better with many packages and functions in the Bioconductor ecosystem.

I will be in Israel at the end of Feb and early march.  If your lab or institution would like to have a talk or meeting about Bioconductor I may be able to do that.

**Comment by vjcitn** [comment]
With "real data" you'd want colData to have information about each cell, and rowData to have information about genes with precise nomenclature.  You could also use a GRanges to annotate the rows.  You would want information in the metadata slot to help describe provenance of the data, and so forth.  Read the vignette for SingleCellExperiment package  (and perhaps SummarizedExperiment) too.

**Comment by DanielDavis12** [comment]
> ```
> ## Make sure your matrix is indeed a sparse matrix (of type dgCMatrix)! 
> 
> rownames(geneCountsMatrix) <- c("Gene1", "Gene2", "Gene3", "Gene4")
> colnames(geneCountsMatrix) <- c("Cell1", "Cell2", "Cell3", "Cell4")
> pathwayGenesList <- c("Gene1", "Gene2", "Gene4")
> ```
> 
> This isn't "wrong" but it doesn't use Bioconductor classes in the expected way. The purpose of SummarizedExperiment and derivatives is to couple metadata and numerical data in useful ways.
> 
> ```
> > SingleCellExperiment(assays=SimpleList(counts=geneCountsMatrix))
> class: SingleCellExperiment 
> dim: 4 4 
> metadata(0):
> assays(1): counts
> rownames(4): Gene1 Gene2 Gene3 Gene4
> rowData names(0):
> colnames(4): Cell1 Cell2 Cell3 Cell4
> colData names(0):
> reducedDimNames(0):
> mainExpName: NULL
> altExpNames(0):
> > sce = .Last.value
> > assay(sce)
> 4 x 4 sparse Matrix of class "dgCMatrix"
>       Cell1 Cell2 Cell3 Cell4
> Gene1     1     .     .     .
> Gene2     .     2     .     .
> Gene3     .     .     3     .
> Gene4     .     .     .     4
> > colData(sce)
> DataFrame with 4 rows and 0 columns
> > metadata(sce)
> list()
> ```
> 
> When you use SingleCellExperiment to organize your data, you can use sparse structures for numerics, you can annotate features and cells, connect projections, filter on cell characteristics or feature sets, and so forth, and interoperate better with many packages and functions in the Bioconductor ecosystem.
> 
> I will be in Israel at the end of Feb and early march. If your lab or institution would like to have a talk or meeting about Bioconductor I may be able to do that.

@vjcitn 
I updated the package so that the examples now use the SingleCellExperiment package, as required. Thanks for the information. 
Also - huge thanks for your kind offer! We will check internally if that's feasible on our side and will contact you if it turns out possible. Either way, enjoy your trip.

**Comment by Kayla-Morrell** [comment]
@DanielDavis12 - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: The installation instructions should include Bioconductor
  installation instructions. See these installation instructions on any current
Bioconductor package landing page (e.g. GenomicRanges).
- [ ] REQUIRED: The .tar.gz file should be removed as we do not allow these
  types of files to be part of the raw package directory.

## DESCRIPTION

- [ ] REQUIRED: Package version should be 0.99.0 (or 0.99.1 for the next version
  bump).
- [ ] REQUIRED: For the 'License' field the file needs to be named LICENSE, it's
  misspelled. Change it here as well as the file itself.
- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        ImmunoOncology, DataImport
- [ ] SUGGESTION: We encourage including the 'BugReports' field with a relevant
  link to GitHub for reporting issues.

## NAMESPACE

- [ ] SUGGESTION: Generally 'importFrom()' is encouraged over importing an
  entire package.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be
  included in Bioconductor release announcements.

## Vignette

- [ ] REQUIRED: There should be an Introduction section that serves as an
  abstract to introduce the objective, models, unique functions, key points, etc
that distinguish the package from other packages in the same area. It should
include a short motivation for the package in general as well as motivation for
inclusion of the package in Bioconductor.
- [ ] REQUIRED: Add an 'Installation' section that shows to users how to
  download and load the package from Bioconductor. These instructions and any
installation instructions should be in an `eval = FALSE` code chunk.
- [ ] REQUIRED: Line 42, use accessors and don't access S4 class slots via '@'.

## Man page

- [ ] REQUIRED: In getPathwayScores examples code use accessors and don't access
  S4 class slots via '@'.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  https://contributions.bioconductor.org/tests.html.

## R code

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 40
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spacees for
  line indents. There are 56 lines that are not.

Best,
Kayla

**Comment by DanielDavis12** [comment]
> @DanielDavis12 - Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be (though we strongly encourage them). Comment back here with updates that have been made and when the package is ready for a re-review.
> 
> ## General package development
> * [ ]  REQUIRED: The installation instructions should include Bioconductor
>   installation instructions. See these installation instructions on any current
>   Bioconductor package landing page (e.g. GenomicRanges).
> * [ ]  REQUIRED: The .tar.gz file should be removed as we do not allow these
>   types of files to be part of the raw package directory.
> 
> ## DESCRIPTION
> * [ ]  REQUIRED: Package version should be 0.99.0 (or 0.99.1 for the next version
>   bump).
> * [ ]  REQUIRED: For the 'License' field the file needs to be named LICENSE, it's
>   misspelled. Change it here as well as the file itself.
> * [ ]  SUGGESTION: Consider adding these automatically suggested biocViews:
>   ImmunoOncology, DataImport
> * [ ]  SUGGESTION: We encourage including the 'BugReports' field with a relevant
>   link to GitHub for reporting issues.
> 
> ## NAMESPACE
> * [ ]  SUGGESTION: Generally 'importFrom()' is encouraged over importing an
>   entire package.
> 
> ## NEWS
> * [ ]  SUGGESTION: Consider adding a NEWS file, so your package news will be
>   included in Bioconductor release announcements.
> 
> ## Vignette
> * [ ]  REQUIRED: There should be an Introduction section that serves as an
>   abstract to introduce the objective, models, unique functions, key points, etc
>   that distinguish the package from other packages in the same area. It should
>   include a short motivation for the package in general as well as motivation for
>   inclusion of the package in Bioconductor.
> * [ ]  REQUIRED: Add an 'Installation' section that shows to users how to
>   download and load the package from Bioconductor. These instructions and any
>   installation instructions should be in an `eval = FALSE` code chunk.
> * [ ]  REQUIRED: Line 42, use accessors and don't access S4 class slots via '@'.
> 
> ## Man page
> * [ ]  REQUIRED: In getPathwayScores examples code use accessors and don't access
>   S4 class slots via '@'.
> 
> ## Unit tests
> * [ ]  SUGGESTION: Consider adding unit tests. We strongly encourage them. See
>   https://contributions.bioconductor.org/tests.html.
> 
> ## R code
> * [ ]  SUGGESTION: For formating reasons, consider shorter lines. There are 40
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formating reasons, consider multiples of 4 spacees for
>   line indents. There are 56 lines that are not.
> 
> Best, Kayla

Hello Kayla,

Thanks for the clear comments. I pushed an updated version of the package to Bioc's git, with all required changes applied and most of the suggestions too (except for the unit tests and R code ones). 
The package is ready for a re-review.

Best,

Daniel

**Comment by Kayla-Morrell** [comment]
@DanielDavis12 - Thank you for making the necessary changes. There are a couple points that still need to be addressed before I can accept the package. Please see the requirements below and let me know when the package is ready to be re-reviewed. Also, keep in mind that the deadline for new packages to be accepted for the upcoming release is April 19th.

## General package development

- [ ] REQUIRED: There are still a couple files in the package that aren't allowed, the tar.gz and LICENCE file. I even did a fresh clone of the package from Bioconductor git and they are still there. I'm not sure if you just deleted them (because I see the commits where you did) but perhaps you need to do a `git rm` as well?

## NEWS

- [ ] REQUIRED: It is great that you are including a NEWS file for the package but it should be populated. Please see our documentation here (https://contributions.bioconductor.org/news.html) to be sure it is formatted properly.

Best,
Kayla

**Comment by DanielDavis12** [comment]
> @DanielDavis12 - Thank you for making the necessary changes. There are a couple points that still need to be addressed before I can accept the package. Please see the requirements below and let me know when the package is ready to be re-reviewed. Also, keep in mind that the deadline for new packages to be accepted for the upcoming release is April 19th.
> 
> ## General package development
> * [ ]  REQUIRED: There are still a couple files in the package that aren't allowed, the tar.gz and LICENCE file. I even did a fresh clone of the package from Bioconductor git and they are still there. I'm not sure if you just deleted them (because I see the commits where you did) but perhaps you need to do a `git rm` as well?
> 
> ## NEWS
> * [ ]  REQUIRED: It is great that you are including a NEWS file for the package but it should be populated. Please see our documentation here (https://contributions.bioconductor.org/news.html) to be sure it is formatted properly.
> 
> Best, Kayla

Hello Kayla, 

Thanks for the additional information. I removed the files you mentioned and pushed the new version both to my GitHub repository and to Bioconductor's. The NEWS file has also been updated as required. 
Surprisingly, Bioconductor's automatic build on Linux raised a warning about one of the value tags in a man file, although the man files have not been changed and look intact on my windows environment.. Should I address that? If so - how can I find more detailed information about this considering that on my environment there are no warnings? 

Best,

Daniel

**Comment by Kayla-Morrell** [comment]
@DanielDavis12 - Thank you for making those changes. The WARNING can be ignored for now, it's most likely something on our end. I'm more than happy to accept the package now.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/DanielDavis12.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SiPSiC")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SiPSiC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
