### ISSUE TITLE
magpie

### ISSUE THREAD

**Issue by dxd429** [Bioconductor/Contributions#2898]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dxd429/magpie

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
This ERROR is quite concerning if you are trying to download anything from CRAN it should be in an eval=FALSE section or dontrun .  You should never install a package for a user without their knowledge.

**Comment by dxd429** [comment]
Hi, I already subscribed to the mailing list, but still got the error: "ERROR: Maintainer must subscribe to the bioc-devel mailing list."

**Comment by ococrook** [comment]
Hi @dxd429 

Don't worry about that error, I'll have a look into it.

**Comment by ococrook** [comment]
Hi @dxd429 

This package looks quite good, thanks for the submission

Minor:

- [ ] Please update the R dependency
- [ ] Please add units tests

General comments:

Please add a `Readme`  it's currently not clear what the package is trying to do without going into the package

There is quite a lot of code that is undocumented or uncommented, it's hard to workout what each function does without at least a description of its intended use. I dont expect the same quality of description as exported code but some explaination would help. The code could also benifit from more white space and starting function arguments on new lines

Is there any need for the LICENSE file - what is this doing in addition to the MIT license?

**Comment by dxd429** [comment]
> Hi @dxd429
> 
> This package looks quite good, thanks for the submission
> 
> Minor:
> 
> * [ ]  Please update the R dependency
> * [ ]  Please add units tests
> 
> General comments:
> 
> Please add a `Readme` it's currently not clear what the package is trying to do without going into the package
> 
> There is quite a lot of code that is undocumented or uncommented, it's hard to workout what each function does without at least a description of its intended use. I dont expect the same quality of description as exported code but some explaination would help. The code could also benifit from more white space and starting function arguments on new lines
> 
> Is there any need for the LICENSE file - what is this doing in addition to the MIT license?

Hi Oliver,

Thank you for your comments! I will address minors and your comments accordingly. Regarding the LICENSE file, I think it was generated accidentally and will remove it. Once updated, I will push it again.

**Comment by dxd429** [comment]
> Hi @dxd429
> 
> This package looks quite good, thanks for the submission
> 
> Minor:
> 
> * [ ]  Please update the R dependency
> * [ ]  Please add units tests
> 
> General comments:
> 
> Please add a `Readme` it's currently not clear what the package is trying to do without going into the package
> 
> There is quite a lot of code that is undocumented or uncommented, it's hard to workout what each function does without at least a description of its intended use. I dont expect the same quality of description as exported code but some explaination would help. The code could also benifit from more white space and starting function arguments on new lines
> 
> Is there any need for the LICENSE file - what is this doing in addition to the MIT license?

Hi Oliver,

About the unit test, I was trying to submit an Experimental Data package to store the data for main function testing. I tried to include 8 small data files, but the largest data file is still 11.3 MB which prevents me from submitting it on Bioconductor. Can I run the unit test with the Data package published on GitHub instead?

**Comment by ococrook** [comment]
Sorry for the slow reply - for some reasons I didn't get a notification.

Unit tests shouldn't really rely on large data, and should be as small as possible. It's best to try to make the data smaller or have simulations where you know what the output should be and can see any errors quickly.

**Comment by dxd429** [comment]
> Sorry for the slow reply - for some reasons I didn't get a notification.
> 
> Unit tests shouldn't really rely on large data, and should be as small as possible. It's best to try to make the data smaller or have simulations where you know what the output should be and can see any errors quickly.

Hi Oliver,

I addressed the comments you raised, and now it passed the check with no errors:

- updated R dependency to R (>= 4.2.0)
- Add a Readme file for the introduction
- Comments are added for each function and each argument now starts at a new line.
- License file is needed here to avoid the warning from CMD check: Invalid license file pointers: LICENSE

However, I was not able to find a .BAM file that is less than 5MB for unit test, so there is no unit test for now. Is a unit test required here?

**Comment by ococrook** [comment]
Thanks! Looks good

I think we should check with @lshep on the unit test front. Personally, I'm anxious that bugs can accumulate easily without units tests.

@lshep the author is finding it hard to obtain suitable data for unit testing. I suggested trying to make the data smaller or using simulated data but they don't seem to find it possible. Can we exceed the 5mb limit in this case? Or do you have another way to proceed? Thanks!

**Comment by lshep** [comment]
The 5mb limit is a hard limit and cannot be removed.  Would a BAM file from the AnnotationHub be usable?

**Comment by dxd429** [comment]
> The 5mb limit is a hard limit and cannot be removed. Would a BAM file from the AnnotationHub be usable?

Hi, thank you for replying, but it depends on the type of data. I made an ExperimentData package which contains the .BAM files needed for purposes like unit test, but still was not able to pass Biocheck because of their sizes. But I did see some ExperimentData packages containing files larger than 5MB, so is this a doable way? 

I will try to find a published ExperimentData packge with .BAM files if I cannot publish mine.

Thank you!

**Comment by lshep** [comment]
ExperimentHub packages do not have the data contained in them directly.  The Data files are stored on a server and ExpeirmentHub points to the data to download.

**Comment by dxd429** [comment]
> ExperimentHub packages do not have the data contained in them directly. The Data files are stored on a server and ExpeirmentHub points to the data to download.

Thank you for the information! But I checked some "ExperimentData" packages containing .BAM files, for example, "SCLCBam" and "MMDiffBamSubset". They put large (50 - 100 MB) .BAM files in "inst/extdata/" folder instead of a server. A ExperimentHub package should also have "metadata.csv" in that folder as I checked, but I do not see it in theirs.

If a unit test is required here, may I have any suggestions on using files that are at most 12 MB in the test? My package utilizes .BAM files from MeRIP-Seq experiments, which are not available in any published package for now. 

Thank you!

**Comment by lshep** [comment]
These were legacy experiment data packages before we transitioned to using git and tracking experiment data packages.

**Comment by dxd429** [comment]
> These were legacy experiment data packages before we transitioned to using git and tracking experiment data packages.

I see. Then for the unit test, can I use data from the data package on my GitHub instead? If not, should I make an ExperimentHub package for the unit test?

Thank you!

**Comment by lshep** [comment]
We do not allow data to be downloaded and used from github it would have to be on a trusted server like zenodo, aws, etc.  Again, if you are finding BAM files in other packages why not just use the ones that are already available then?

**Comment by dxd429** [comment]
> We do not allow data to be downloaded and used from github it would have to be on a trusted server like zenodo, aws, etc. Again, if you are finding BAM files in other packages why not just use the ones that are already available then?

The .BAM files from other packages are from RNA-Seq experiments, not MeRIP-Seq which is what my package is designed for. But I guess they could work since it is just for the unit test. Thank you for suggesting and I will try and see if it works.

**Comment by dxd429** [comment]
> Thanks! Looks good
> 
> I think we should check with @lshep on the unit test front. Personally, I'm anxious that bugs can accumulate easily without units tests.
> 
> @lshep the author is finding it hard to obtain suitable data for unit testing. I suggested trying to make the data smaller or using simulated data but they don't seem to find it possible. Can we exceed the 5mb limit in this case? Or do you have another way to proceed? Thanks!

Hi Oliver,

I was finally able to use one of the Bioconductor package "TBX20BamSubset" to perform the unit test. I added the unit test but got a warning saying "R CMD check exceeded 10 min requirement" on one of the platform. 

As I checked, one option for me is "long test", but it says "The Long Tests setup forces developers to split the testing code in their package between “short tests” and “long tests”. The former go in the tests subdirectory and must be able to run in less than 40 min" on the Bioconductor page. my unit test runs in around 3 mins, so short test should be good here.

Do you have any suggestions? Thank you in advance!

**Comment by lshep** [comment]
I think it will be okay to proceed despite this warning.

**Comment by dxd429** [comment]
@ococrook Hi, is the package ready for next step of the review process?

**Comment by ococrook** [comment]
Could you align the package versions between the `NEWS.md` and the `Description` and then I can accept the package

**Comment by dxd429** [comment]
> Could you align the package versions between the `NEWS.md` and the `Description` and then I can accept the package

@ococrook Hi, I aligned the version numbers and it was built successfully.

**Comment by ococrook** [comment]
Brilliant, thank you!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dxd429.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("magpie")`. The package 'landing page' will be created at

https://bioconductor.org/packages/magpie

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
