### ISSUE TITLE
ClusterFoldSimilarity

### ISSUE THREAD

**Issue by OscarGVelasco** [Bioconductor/Contributions#2900]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/OscarGVelasco/ClusterFoldSimilarity

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
You don't declare a need for SeuratData but we have
```
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/FEB7/ClusterFoldSimilarity$ grep SeuratData man/*
man/cluster_fold_similarity.Rd:library(SeuratData)
```
SeuratData is not on CRAN and is not in Bioconductor.  You must use in Suggests in DESCRIPTION to declare this, and it is not allowed unless it is in CRAN or Bioconductor.  If you want to modify to comply with the guidelines, reopen the issue.  Thanks!

**Comment by OscarGVelasco** [comment]
Hi,
I have made the required changes to comply with the guidelines and I would like to re-open this issue.
Many thanks

**Comment by vjcitn** [comment]
Please be sure that R CMD check passes for your package:
```
* checking examples ... ERROR
Running examples in 'ClusterFoldSimilarity-Ex.R' failed
The error most likely occurred in:

> ### Name: plot_clusters_graph
> ### Title: Creates a graph plot using the similarity values calculated with
> ###   ClusterFoldSimilarity().
> ### Aliases: plot_clusters_graph
> 
> ### ** Examples
> 
> # singlecell.object.list consist of 2 or more single-cell objects
> # By default plots a graph using the similarity values: 
> similarity.table.top <- cluster_fold_similarity(sce_list = singlecell.object.list,top_n = 1)
Error in cluster_fold_similarity(sce_list = singlecell.object.list, top_n = 1) : 
  object 'singlecell.object.list' not found
Execution halted
* checking for unstated dependencies in vignettes ... NOTE
'library' or 'require' calls not declared from:
  ‘BiocStyle’ ‘dplyr’
* checking package vignettes in 'inst/doc' ... OK
* checking running R code from vignettes ...
  'ClusterFoldSimilarity.Rmd' using 'UTF-8'... OK
 NONE
* checking re-building of vignette outputs ...
```

**Comment by OscarGVelasco** [comment]
Hi again,
I have updated the examples and now R CMD check pass with no errors
thanks

**Comment by OscarGVelasco** [comment]
Dear @DarioS ,
I have checked the error, and I have already subscribed to the mailing list:
* ERROR: Maintainer must subscribe to the bioc-devel mailing list
 
How should I proceed? should I push the package again despite having no modifications to trigger a new build?
thanks

**Comment by DarioS** [comment]
That's fine. I will begin your review in the next few days. Don't overlook the warnings, though.

> ```
> * checking Rd cross-references ... WARNING
> Missing link or links in documentation object 'cluster_fold_similarity.Rd':
>   DataFrame-class
> 
> Missing link or links in documentation object 'similarity_heatmap.Rd':
>   DataFrame-class
> ```
and

> ```
> * checking dependencies in R code ... WARNING
> '::' or ':::' imports not declared from:
>   data.table ggplot2 igraph
> ```

**Comment by OscarGVelasco** [comment]
Dear @DarioS 
I managed to fix all the errors & warnings, and did a push to the BioC repo.
Let me know if is there any more suggestions or fixes when you have some time to review it. 
Looking forward to it and many thanks for the support, best wishes.

**Comment by DarioS** [comment]
The package has a variety of non-conformities with the Bioconductor developer's guide, particularly the [R Code](url) section of it.

- All function names and variable names should use camelCase and not snake_case. See [Variable Names](https://contributions.bioconductor.org/r-code.html#variable-names) and [Function Names](https://contributions.bioconductor.org/r-code.html#rcode-function-names).
- Variable assignment is inconsistent. For example, `is_sce <- FALSE` and `top_n_genes = 1`. See the last rule in [Code Syntax](https://contributions.bioconductor.org/r-code.html#code-syntax-and-efficiency).
  > Use <- instead of = for assigning variables except in function arguments.

- Inconsistent spacing around operators. For example, `length(features) == 0` and `diff_neg_pos=2`. Please see [Use of Space](https://contributions.bioconductor.org/r-code.html#use-of-space).
- `for` loops not to be used. Please see [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize).
- A number of packages are listed in Suggests field of DESCRIPTION but they are incorrectly loaded in examples.
  ```r
  library(Seurat)
  library(scRNAseq)
  ```
  These should be conditionally loaded using `requireNamespace`, not `library`. See [Suggested Packages](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages) instructions.
- The vignette ought to have a section near the beginning explaining installation. See [Installation](https://contributions.bioconductor.org/docs.html#installation) section. The vignette has a setup chunk at the very _end_. It should be at the beginning of a vignette, not at the end.
- The examples use large single-cell RNA sequencing data sets. Please make the example data smaller and easier to use. Function examples should not use complete gene expression data sets but a subset sufficient to illustrate the key concepts.
  ```r
  Sys.time()
  mouse.brain.romanov <- scRNAseq::RomanovBrainData(ensembl = TRUE)
  Sys.time()
  ```

  I see

  ```r
  "2023-03-30 17:08:32 AEDT"
  snapshotDate(): 2023-03-29
  downloading 1 resources
  retrieving 1 resource
  100%
  loading from cache
  downloading 1 resources
  retrieving 1 resource
  loading from cache
  28%
  snapshotDate(): 2022-12-16
  downloading 1 resources
  retrieving 1 resource
  100%
  loading from cache
  require("ensembldb")
  Warning messages:
  1: download failed
  web resource path: 'https://annotationhub.bioconductor.org/metadata/annotationhub.sqlite3'
  local file path: 'C:\Users\dstr7320\AppData\Local/R/cache/R/AnnotationHub\file26685aba3830'
  reason: transfer closed with 88822945 bytes remaining to read
  2: bfcdownload() failed
  rid: BFC1
  file: 'https://annotationhub.bioconductor.org/metadata/annotationhub.sqlite3'
  reason: download failed
  3: Could not check database for updates.
  Database source currently unreachable.
  This should only be a temporary interruption.
  Using previously cached version.
  4: Unable to map 2692 of 24341 requested IDs.
  "2023-03-30 18:56:34 AEDT"
  ```

  So, it runs for almost two hours and fails. The average download speed is 500 Kbps, which is typical for other data sets which I have downloaded from North America to Australia. Therefore, please choose examples which will work in the southern hemisphere as well as they do in the northern hemisphere.

 - The vignette is mostly code directly copied from the functions examples. Please make the vignette distinct from function examples. For example, the code in section "Using ClusterFoldSimilarity to find similar clusters across datasets" is a direct copy from `?similarity_heatmap` and `?cluster_fold_similarity`.
 - The vignette lacks interpretation of the outputs. For example "We can plot the heatmap of all the similarity values for any number of independent datasets" is followed by a code chunk that generates a plot and is followed by the next section heading. Each output, such as a plot or a table, should be followed by one or two sentences explaining what patterns or trends the reader should notice in the output.
 - Please avoid unnecessary package dependencies. You only use `data.table` on two lines of code in the entire package. Instead use Bioconductor's [DataFrame](https://bioconductor.org/packages/S4Vectors) for tabular data.
 - NAMESPACE file lacks any import statements. Please refer to [Imported Functions](https://contributions.bioconductor.org/namespace.html?q=importFrom#imported-functions) section about them.

**Comment by OscarGVelasco** [comment]
Hi again @DarioS,
Thanks a lot for your comments.

I have already addressed some of them:
> * All function names and variable names should use camelCase and not snake_case. See [Variable Names](https://contributions.bioconductor.org/r-code.html#variable-names) and [Function Names](https://contributions.bioconductor.org/r-code.html#rcode-function-names).
> * Variable assignment is inconsistent. For example, `is_sce <- FALSE` and `top_n_genes = 1`. See the last rule in [Code Syntax](https://contributions.bioconductor.org/r-code.html#code-syntax-and-efficiency).
>   > Use <- instead of = for assigning variables except in function arguments.
> * Inconsistent spacing around operators. For example, `length(features) == 0` and `diff_neg_pos=2`. Please see [Use of Space](https://contributions.bioconductor.org/r-code.html#use-of-space).
> * The vignette ought to have a section near the beginning explaining installation. See [Installation](https://contributions.bioconductor.org/docs.html#installation) section. The vignette has a setup chunk at the very _end_. It should be at the beginning of a vignette, not at the end.
> * Please avoid unnecessary package dependencies. You only use `data.table` on two lines of code in the entire package. Instead use Bioconductor's [DataFrame](https://bioconductor.org/packages/S4Vectors) for tabular data.

I am now fixing the for loops sections
> * for loops not to be used. Please see [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize).

However I have some questions regarding the other points:
> * A number of packages are listed in Suggests field of DESCRIPTION but they are incorrectly loaded in examples.
>   ```r
>   library(Seurat)
>   library(scRNAseq)
>   ```
>   These should be conditionally loaded using `requireNamespace`, not `library`.

I have checked the documentation and other examples, would something like the following be valid?

```r
stopifnot (requireNamespace("Seurat"))
stopifnot (requireNamespace("SingleCellExperiment"))
stopifnot (requireNamespace("scRNAseq"))
```

As for the example loading and executing, I am sorry to hear that. In my laptop it takes some minutes to run, and I was expecting the package _"scRNAseq"_ to work correctly for everyone as it is part of _Bioconductor_.
I have some concerns as of how to approach this problem: my package needs as input **at least 2 independent single-cell datasets**, with the known labels of the cell-types (for example purposes), additionally those datasets _should be pre-processed with a standard single-cell pipeline_ (like Seurat), otherwise I need to add this pre-processing to the examples, which makes them more complex and time consuming (like the examples that I used originally). 
I have seen several package examples that have the **#'\dontrun flag**, I am not sure if that would be an option. Otherwise I will have to rely on external databases, using other packages like scRNAseq (which could be unavailable in the future).

And lastly, the NAMESPACE import statement, I have check the documentation but I am not sure what do I have to add (the NAMESPACE is automatically created by Roxygen and it adds "# Generated by roxygen2: do not edit by hand".
Should I just add e.g.: import(ggplot2) to the NAMESPACE file for all the imported packages?

> * NAMESPACE file lacks any import statements. Please refer to [Imported Functions](https://contributions.bioconductor.org/namespace.html?q=importFrom#imported-functions) section about them.

Thanks a lot in advance.
Best,

**Comment by DarioS** [comment]
For packages used in examples, see [Suggested Packages](https://cran.r-project.org/doc/manuals/R-exts.html#Suggested-packages) of Writing R Extensions for instructions and example.

> ```r
> if (requireNamespace("rgl", quietly = TRUE))
> {
>   # Run some code using rgl functions.
> }
> ```

No, don't use `\dontrun`. I don't know what would be a good workaround. scRNAseq doesn't offer an option to download a subset of genes or cells, which might help. I cleared my cache and tried `RomanovBrainData` again today. It failed after 18 minutes. The average download speed was 4 Mbps. I will ask developer of scRNAseq for assistance and let you know more soon.

When you use functions from another package inside of your package's functions, you should be precisely importing them. For example `#' @importFrom survival concordance`. Have a read of [Imports](https://roxygen2.r-lib.org/articles/namespace.html#imports). That will automtically fill in the NAMESPACE file with what it needs to have.

**Comment by lshep** [comment]
@OscarGVelasco  / @DarioS  just wanted to check in on the status of this issue?  We like to continue conversation in 2-3 week time periods to make sure packages continue to move through the process and get added to Bioconductor as soon as possible.

**Comment by OscarGVelasco** [comment]
Hi, thanks for your message. The package had a massive update due to the incoming submission to a journal. It has some new features, and I have fixed all the major pending issues, however, I am afraid that to remove some of the for loop is quite complex, will be highly time consuming and with no major gain, as the major computation is done in the secondary functions, where they are properly formated using the apply function family.
I will push the new version as soon as possible so we can move with the bioconductor review process.
Thanks,

> @OscarGVelasco / @DarioS just wanted to check in on the status of this issue? We like to continue conversation in 2-3 week time periods to make sure packages continue to move through the process and get added to Bioconductor as soon as possible.

**Comment by OscarGVelasco** [comment]
Dear @DarioS,
Apologies for the delay. I have done numerous upgrades to the package, including:
- examples: now the function examples are lighter, easier to run, and with no external data dependencies, so no data download needed.
- "for" loops: I have remove the most computational-intensive ones, and I have included BiocParallel computing as an option, using bplapply.

Still, some external data is needed for the Vignettes (using the bioconductor package scRNAseq), in my laptop it needs on average 7 minutes to generate the full Vignette.

Let me know if it is ok.
Many thanks in advance

**Comment by DarioS** [comment]
Please also ensure that you follow [R coding rules as specified in Contributor's Guide](http://contributions.bioconductor.org/r-code.html). Importantly, BiocCheck shows

> ```
> * Checking coding practice...
>     * NOTE: Avoid sapply(); use vapply()
>     * NOTE: Avoid 1:...; use seq_len() or seq_along()
>     * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
>     * NOTE: Avoid using '=' for assignment and use '<-' instead
>     * NOTE: Avoid the use of 'paste' in condition signals
>     * NOTE: Avoid redundant 'stop' and 'warn*' in signal conditions
> * Checking parsed R code in R directory, examples, vignettes...
>     Found @ in vignettes/ClusterFoldSimilarity.Rmd
>     * NOTE: Use accessors; don't access S4 class slots via '@' in
>       examples/vignettes.
> ```

A comprehensive package review will commence when these basic coding issues are addressed.

**Comment by OscarGVelasco** [comment]
Dear @DarioS,
I have addressed and re-check with BiocCheck the notes mentioned, and pushed an updated version of the package.

**Comment by DarioS** [comment]
Thanks for continued development of your R package. I note some remaining issues.

- No HTML files should be in vignettes directory but only Rmd in there. The HTML will be created during package build.

- Some of the function examples don't make sense. For instance

  ```r
  > counts[1:5, 1:5]
            cell1    cell2     cell3    cell4      cell5
  gene1 5763.5686 6543.666 6081.2129 8760.873 4671.61447
  gene2 5095.4526 4846.960  540.6057 9415.429 4179.07442
  gene3 3987.3539 6856.783 4887.9943 1389.357 6481.85052
  gene4 2174.5354 7029.079 1698.6390 3463.098 4095.26644
  gene5  379.1686 7425.181 7565.3920 3179.409   12.27383
  ```

  Why do you simulate from a non-count distribution and create decimal numbers in a matrix of counts? This also demonstrates that ClusterFoldSimilarity lacks sufficient integration with other relevant Bioconductor packages. [splatter](https://bioconductor.org/packages/release/bioc/html/splatter.html) is a single-cell RNA data simulator and should be used to simulate such data, not `runif`.
  
  Also, the main input variable is called sceList but its format is "A list of Single Cell Experiments or Seurat objects." It is counterintuitive that a variable called sceList would have Seurat objects in it.
  
- The initial comment about code style still stands. I see `seu.1`, `similarity.table`,, `pancreas_muraro`, etc.
>   All function names and variable names should use camelCase and not snake_case. See [Variable Names](https://contributions.bioconductor.org/r-code.html#variable-names) and [Function Names](https://contributions.bioconductor.org/r-code.html#rcode-function-names).

- The parameter `parallel` is boolean. The user cannot control how many cores are used nor the backend. Please refer to [Parallel Recommendations](https://contributions.bioconductor.org/r-code.html?q=BPPARAM#parallel-recommendations).

- Do not use single character variable names. I see `i`, `j`, `k`, `y`. Use names such as `cellIndex`, `sampleIndex` for self-documenting code.

- Inconsistent space after comma. For instance,
  ```r
  do.call("rbind",lapply(intermediateResults,function(x)do.call(rbind, x)))
  ```
  
- Vignette is somewhat confusing. At the beginning "ClusterFoldSimilarity will obtain the raw count data from these objects" but a couple of paragraphs later "Normalize and identify variable features for each dataset independently". Why is the existing normalisation unable to be used and must be redone? Please add a clarifying paragraph explaining this.
  
  Figure 1, network of clusters. Why are the edges directional? There is no causal relationship. The node labels are not readable. Please make the figure larger using `fig.width` and `fig.height` chunk options. Also for second figure.
  
  Below `similarity.table`, there is no explanation at all about what the table columns mean. What is `sem`, `w` and why do they matter? Don't present results without any interpretation accompanying them. Same for other tables below it.

**Comment by OscarGVelasco** [comment]
Thanks for your comments, I will modify the code accordingly. 
Although, I need to clarify some of your points:

> Why do you simulate from a non-count distribution and create decimal numbers in a matrix of counts? This also demonstrates that ClusterFoldSimilarity lacks sufficient integration with other relevant Bioconductor packages. [splatter](https://bioconductor.org/packages/release/bioc/html/splatter.html) is a single-cell RNA data simulator and should be used to simulate such data, not runif.

splatter returns the simulated single-cell data as a SingleCellExperiment object, which is accepted by ClusterFoldSimilarity, making splatter directly compatible with our package. We have made our package compatible with -by far- the most 2 used single-cell objects. The majority of single-cell tools are only compatible with one or with none, forcing the user to adapt to the package itself. We have make great efforts to make our package compatible and also for keeping the number of dependencies as low as possible. splatter has several dependencies, which will make our package to add several unwanted dependencies just for showing the toy examples. Additionally, splatter just returns the counts generated, and to compute the similarities we need clusters/groups, which will introduce several costly computing steps, like normalising, dim. reduction and clustering (x2 because we need at least 2 datasets). I have modify the examples with a random poisson distribution, which is closer to a real single-cell data distribution: as it is a very small simulation, just for illustration purposes, I believe it is clearer and simple this way (additionally, I copied this approach from other packages). I understand your point, but If it is possible I would like to avoid splatter if it is not strictly mandatory for single-cell packages, and thus avoid a large number of external dependencies.

> The parameter parallel is boolean. The user cannot control how many cores are used nor the backend. Please refer to [Parallel Recommendations](https://contributions.bioconductor.org/r-code.html?q=BPPARAM#parallel-recommendations).

I checked the biocParallel recommendations before including it, and I saw this point:
"Allow the user to specify the BiocParallel back-end. Do this by invoking bplapply() without specifying BPPARAM; the user can then override the default choice with BiocParallel::register()."
From my understanding, we should not include BPPARAM on bplapply, and that is exactly what I did, I understood that the user should call BiocParallel::register() with their desired BPPARAM config before using our package, and this will be automatically picked up as the default: BPPARAM = bpparam() 
Please let me know which is the desired implementation, I am a little bit confused.

> Vignette is somewhat confusing. At the beginning "ClusterFoldSimilarity will obtain the raw count data from these objects" but a couple of paragraphs later "Normalize and identify variable features for each dataset independently". Why is the existing normalisation unable to be used and must be redone? Please add a clarifying paragraph explaining this.

ClusterFoldSimilarity uses raw counts because of the bayesian prior distribution estimation, but for the user to obtain the clusters (in this example we try to reproduce a full experiment) it needs first to pre-process the data: normalisation, get variable features, dim. reduction and clustering, and thus normalisation is needed because of this. If cell groups already exists and no clustering is needed, then the user can use their data directly with ClusterFoldSimilarity with no normalisation, but for the purpose of the vignettes we wanted to show an archetypical single-cell analysis. I will try to add some clarifications, but the need for clustering itself explains the normalisation step.

> Figure 1, network of clusters. Why are the edges directional? There is no causal relationship.

This is directly related with the methodology of the statistical score calculation and it is addressed on the paper to be published. Indeed, the directionality of the edges is the most important feature of the plot. The similarities are calculated for every pair of clusters from different datasets, and these similarities might not be reciprocal due to the heterogeneity of single-cell experiments. Suppose that you have 3 datasets each with a series of clusters a,b,...  
- the most similar cluster for dataset.2-cluster.b in dataset.1 is dataset.1-cluster.a
- the most similar cluster for dataset.1-cluster.a in dataset.2 is dataset.2-cluster.f
- the most similar cluster for dataset.3-cluster.a in dataset.2 is dataset.2-cluster.b, and in dataset.1 is dataset.1-cluster.a
dataset.2-cluster.b -> dataset.1-cluster.a 
dataset.1-cluster.a -> dataset.2-cluster.f
dataset.3-cluster.a -> dataset.1-cluster.a 
dataset.3-cluster.a -> dataset.2-cluster.b 
The directed graph plot with this directionalities and the edge-weight=similarity will show the relationship that can be inferred from these connections, the dataset.3 will show an indirect relationship between dataset.1-cluster.a and dataset.2-cluster.b. A common case is to have clusters that are a mix of populations so you will see these kind of relationships, and the graph plot will give you a lot of information about it. Also, we can think of an scenario in which a cell-type is missing in some of the datasets, which will make this cell-type group point to the closest related one, but it might not have incoming connections from the other datasets, as this cell-type does not exists within them (in the example, this will be dataset.2-cluster.b not existing in dataset.1, but the closest is dataset.1-cluster.a, then dataset.1-cluster.a might be the same cell-type as dataset.2-cluster.f).
As my initial comment, this is purely methodological.


Again, thanks for your inputs. Best regards,

**Comment by DarioS** [comment]
Thanks for the clarifications. That is all fine. Indeed, random draws from a Poisson distribution is sufficient.

**Comment by OscarGVelasco** [comment]
Hi again,
Is there any updates from the review of the package?
Thanks in advance

**Comment by DarioS** [comment]
Oh, it is customary to provide a list of responses when no more modifications are to be made. I thought you were editing.

- Change installation instructions in vignette to use BiocManager rather than devtools' `install_github`,
- Do a final spell-check. For example, srink is meant to be shrink, feataure is meant to be feature, etc.
- Unable to access example data set. This is [a system-wide issue](https://github.com/Bioconductor/ExperimentHub/issues/33) and we are awating its resolution.

```r
> pancreasMuraro <- scRNAseq::MuraroPancreasData(ensembl=FALSE)
snapshotDate(): 2023-04-24
see ?scRNAseq and browseVignettes('scRNAseq') for documentation
downloading 1 resources
retrieving 1 resource
Error: failed to load resource
  name: EH2692
  title: Muraro pancreas counts
  reason: 1 resources failed to download

```

**Comment by OscarGVelasco** [comment]
Thanks for your comments and your review @DarioS 
I have fixed the spelling errors and installation instructions.

As for the data access error, as I have no control over it, which are the next steps here? Is there anything else needed from my side?

Many thanks and best regards,

**Comment by DarioS** [comment]
Data server error was fixed by Bioconductor staff and now download succeeds. The other issues have been addressed.

**Comment by OscarGVelasco** [comment]
I really want to thank you @DarioS for your in detail review, your time and your patience. I know how hard it is to read other´s code, and I really think that the package has improved thanks to your comments and inputs.
Best wishes.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/OscarGVelasco.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ClusterFoldSimilarity")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ClusterFoldSimilarity

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
