### ISSUE TITLE
shiny.gosling

### ISSUE THREAD

**Issue by anirbanshaw24** [Bioconductor/Contributions#2907]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Appsilon/shiny.gosling

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Anirban @anirbanshaw24 

Thank you for your submission. 
Unfortunately, though a well written package, 
`shiny.gosling` does not satisfy the interoperability requirements for Bioconductor. 

I have added a few suggestions to better integrate with the Bioconductor ecosystem,
if you wish to have the package published in Bioconductor. 

I also encourage others to comment.  

cc: @vjcitn @hpages 

Best regards,
Marcel

---

# shiny.gosling #2907

* It doesn't look like the package is making use of Bioconductor
infrastructure or data visualization packages.

## DESCRIPTION

* Consider importing data from our reference genome packages.
* Consider using data viz packages like `trackViewer`.
* Remove `BiocManager` and `BiocCheck` from the DESCRIPTION file. They are not
needed for package installation.

**Comment by vjcitn** [comment]
I would agree that the package should do more to work with Bioconductor data before joining the ecosystem.  How could an annotated GRanges be visualized using shiny.gosling?  The vignette gives a pretty limited example.  The potential seems very significant, but let's not make the Bioconductor users figure out how to connect the wealth of information in AnnotationHub and other data resources in genomic coordinates with the gosling visualization discipline?  Let's have some more worked out examples.

**Comment by vjcitn** [comment]
I looked a little more closely at the submitted vignette.  cancer_data is not used.   We have 
```
> cist = readLines(cistrome_data)
Warning message:
In readLines(cistrome_data) :
  incomplete final line found on 'https://server.gosling-lang.org/api/v1/tileset_info/?d=cistrome-multivec'
> cistl = jsonlite::fromJSON(cist)
> names(cistl[[1]])
 [1] "resolutions"  "min_pos"      "max_pos"      "tile_size"    "shape"       
 [6] "row_infos"    "name"         "datatype"     "coordSystem"  "coordSystem2"
> str(cistl[[1]])
List of 10
 $ resolutions : int [1:15] 16384000 8192000 4096000 2048000 1024000 512000 256000 128000 64000 32000 ...
 $ min_pos     : int 0
 $ max_pos     : num 3.21e+09
 $ tile_size   : int 256
 $ shape       : int [1:2] 256 228
 $ row_infos   : chr [1:228] "Homo sapiens\tTH1_K27AC_REP2\tGSM2048305\tGSE77299\tNone\tTh1\tTonsil\tNone\tH3K27ac\thm\tNone" "Homo sapiens\tH3K27AC_CHIPSEQ_HUMAN_REP1\tGSM1375210\tGSE49624\tNone\tSpermatid\tNone\tACTIVE MOTIF\tH3K27ac\thm\tNone" "Homo sapiens\tILC1_K27AC_REP2\tGSM2048292\tGSE77299\tNone\tILC1\tTonsil\tNone\tH3K27ac\thm\tNone" "Homo sapiens\tTH17_K27AC_REP2\tGSM2048310\tGSE77299\tNone\tTh17\tTonsil\tNone\tH3K27ac\thm\tNone" ...
 $ name        : chr "my_file_genome_wide.multires.mv5"
 $ datatype    : chr "multivec"
 $ coordSystem : chr ""
 $ coordSystem2: chr ""
```
so opportunities for self-description are missed (what should we call the "coordSystem") and the vignette could illuminate on what mv5 format is, what a multivec is, and so forth.  The effects of clicking on a rendered tile are not discussed or presented in the interface.

**Comment by vjcitn** [comment]
`example(use_gosling)` produces a really nice display, but the data are built out of a CSV file taken from a server.  See [one Bioconductor package](https://www.bioconductor.org/packages/release/bioc/vignettes/StructuralVariantAnnotation/inst/doc/vignettes.html) that addresses representation of structural variants in VCF and shows a circos plot ... it would be very nice to use gosling to depict and annotate that information.  BTW the key on example(use_gosling) has "delection", a spelling error?

**Comment by anirbanshaw24** [comment]
Thanks for your inputs Marcel and Vince 💯 
`delection` does look like a spelling error. Somehow got pass spell check in CI. We will fix it.
Regarding integrating more with bioc and other comments, we will take some time to review it and make changes.
This is our first bioc submission. Is there a deadline to make these changes ? And after making the changes, we resubmit as described [here](https://contributions.bioconductor.org/git-version-control.html#new-package-workflow) right ?

**Comment by vjcitn** [comment]
The only deadline concerns the release you would like to be a part of.  It seems likely that Bioc 3.17 will close to new submissions in mid-April.  But later filings become part of the devel branch for 3.18 which will be cut in October.  We are happy to discuss your plans.  We can keep the issue open for a while and when you are ready, just file a comment.

**Comment by vjcitn** [comment]
checking in.  do you plan to submit for this release?

**Comment by anirbanshaw24** [comment]
Hi Vince,
We are aiming for this release. Our folks are working on this update. Will let you know if anything changes.

**Comment by anirbanshaw24** [comment]
Hi @vjcitn, 
We identified more complexity to resolve the comments and will take more time to do it. So, we have to go for the next release. We do not have enough time to submit for this release. 
Hope that is fine.

**Comment by vjcitn** [comment]
Thanks for the info.  You can submit at any time.  @lshep do we close the issue and a new one gets opened by contributor?

**Comment by lshep** [comment]
We can close the issue for now.  When you are ready comment back here for us to reopen it.

**Comment by anirbanshaw24** [comment]
Hello @LiNk-NY 
We have taken care of the comments made by reviewers.
I made a submission with version bump to bioc repo. But the build report is not trigerred. 
Could you please help me to submit the package once more.
cc. @lshep @vjcitn

**Comment by LiNk-NY** [comment]
Hi @anirbanshaw24 
Thank you for making those changes. 
The package looks to be in good shape. 
Thank you for your contribution!
Best,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/anirbanshaw24.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("shiny.gosling")`. The package 'landing page' will be created at

https://bioconductor.org/packages/shiny.gosling

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
