### ISSUE TITLE
BiocFileCache

### ISSUE THREAD

**Issue by lshep** [Bioconductor/Contributions#292]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/BiocFileCache

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Looks good. My only suggestion is to add a \details section to the man page that tells more about the object. A very thorough example would be \details on ?GAlignments describing the GAlignments class. Another (less thorough) example is the ?VCF man page. You may not need the level of detail in ?GAlignments, but I think it's useful to touch on what the class basically is, mention slots if appropriate, and give a high-level view of how the data are stored and therefore what kinds of access is possible.

Val

**Comment by lawremi** [comment]
For the directory location, you could use the standard cache directory as laid out by the XDG standard, via the rappdirs package on CRAN. 

The vignette should put more emphasis on the workflow at the end. Currently, the vignette is more like a manual than a demonstration. How does one use this in practice?

What about lazy caching, where if the remote resource has already been cached, it's used automatically? The vignette makes it look like that logic is left to the user, although I see code in the package for updating the cache using HTTP last modified checks.

Do you envision packages like rtracklayer relying on BiocFileCache, where given a remote resource, it hits the cache first?

What about caching the loading of objects, so if I've already loaded a potentially large object, it reuses the object that is already in memory? I think you could do this with weak references (see Writing R Extensions).

I realize the package name contains "File" but what about supporting alternative cache implementations (e.g., redis)? Maybe the API should have a way to get a connection object, for which there can be alternative implementations (at the C level at least). Or a URL, but R has no extensible way of implementing new URL schemes.

**Comment by lshep** [comment]
Thank you for the suggestions 

Updates: 

 - [X] a details section has been added to the man page describing both the class
   object and what is tracked in the sqlite database
 - [X] the default cache location now utilizes rappdirs::user_cache_dir
 - [X] updated bfcadd and bfcrpath to allow for a more automated search and
   add to cache 
 - [X] added schema/version check for when there are updates

Comments: 
  yes. we would envision other applications to utilize BiocFileCache to manage
  resources
 
  Caching loading of objects and supporting alternative cache implementation
  we will consider for future implementation.

**Comment by lshep** [comment]
Okay.  Everything seems to be straightened out now.  Please see the above comment for the changes.  The most recent ERROR had to do with normalizing and expanding the paths on windows to account for "\\" vs "/"   and how normalizePath works on each system.

**Comment by vobencha** [comment]
What do you think @lawremi? Any more comments or are we good to go?
Val

**Comment by vobencha** [comment]
Looks good to me. Accepting the package.
Val
