### ISSUE TITLE
pfamAnalyzeR

### ISSUE THREAD

**Issue by kvittingseerup** [Bioconductor/Contributions#2937]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kvittingseerup/pfamAnalyzeR

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Kayla-Morrell** [comment]
@kvittingseerup - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review. Also, keep in mind that the deadline for packages to be accepted for the 
upcoming release is April 19th.

## DESCRIPTION

- [ ] SUGGESTION: The 'Description:' field in the DESCRIPTION is made up by less
  than 3 sentences. Please consider expanding this field and structure it as a
full paragraph.
- [ ] REQUIRED: License 'GPL (>= 2)' unknown; licenses cannot restrict use. Try
  'GPL-2' instead.
- [ ] REQUIRED: 'LazyData:' should be set to false.
- [ ] REQUIRED: Update R version dependency from 4.0.0 to 4.3.0.
- [ ] REQUIRED: Packages listed under depends provide essential functionality
  for users of the package. It is unusual for more than three packages to be
listed as depends. I would suggest moving some of these packages to 'Imports:'
instead.
- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports:' field that
  includes a relevant link to GitHub for reporting issues.

## NAMESPACE

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing the
  entire package.
- [ ] REQUIRED: Exporting all functions with `exportPattern("^[[:alpha:]]+")` is
  strongly discouraged and not allowed. Functions and generics should be
exported individually, for clarity and control.

## NEWS

- [ ] REQUIRED: While it's great to include a NEWS file it doesn't seem like
  it's formated properly. Please take a look at our documentation here:
https://contributions.bioconductor.org/news.html. You can check your news file
after installing the package by running `utils::news(package="pfammAnalyzeR")`.

## Data

- [ ] REQUIRED: There needs to be documentation the data present in
  `inst/extdata/`. The documentation belongs in `inst/script/` and can vary.
Most importantly the script must clearly document how the data was generated and
source information. It should include source URLs and any key information
regarding filtering or processing. It can be executable code, sudo code, or a
text description. Users should be able to download and roughly reproduce the
file or object that is present as data.

## Vignette

- [ ] REQUIRED: The vignette should demonstrate how to use the package to
  accomplish a task and should provide more context with the code.
- [ ] REQUIRED: There should be an introduction section that serves as an
  abstract to introduce the objective, models, unique functions, key points, etc
that distinguishs the package from other packages in the same area. It should
include a short motivation for the package in general as well as mmotivation for
inclusion of the package in Bioconductor.
- [ ] REQUIRED: There should be an installation section that shows users how to
  download and load the package from Bioconductor. These instructions and any
installations instructions should be in an `eval = FALSE` code chunk.
- [ ] SUGGESTION: If appropriate we strongly encourage a table of contents.
- [ ] REQUIRED: The final section of the vignette should be 'Session Info' and
  should include `sessionInfo()`.

## Unit tests

- [ ] SUGGESTION: We strongly encourage the use of unit tests.

## R code

- [ ] SUGGESTION: Undefined global functions or variables:
  . envelope_end envelope_start hmm_alligned_length hmm_end hmm_start
  indel_size seq_alligned_length
- [ ] REQUIRED: Avoid 1:...; use `seq_len()` or `seq_along()` instead.
- [ ] REQUIRED: Avoid 'suppressWarnings'/'Messages' if possible (found 3
      times)
- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 41
  lines that are > 80 characters long.

Best,
Kayla

**Comment by kvittingseerup** [comment]
Dear @Kayla-Morrell 

Thank you so much for taking the time to review my package! I really appreciate it 😃 .

In the new version, I have updated pfamAnalyzeR in accordance with your guidelines. All `REQUIRED` has been implemented, and most `SUGGESTION` as well. 

The only exception for the `REQUIRED` are the use of `suppressWarnings`

Due to the strange file format of the Pfam outputs, the `suppressWarnings()` are needed (as warnings are expected from some of the things I have to try and would just confuse the user) .


I hope the package is now acceptable, given the upcoming deadline you mention 🤞

**Comment by kvittingseerup** [comment]
Dear @Kayla-Morrell 

Do you think we can have pfamAnalyzeR ready before the 19th of April?

**Comment by Kayla-Morrell** [comment]
@kvittingseerup - Thank you for making the necessary changes. I've looked everything over and have just one requirement that must be met before I accept the package. Please let me know when the change has been made and I'll review the change. I am very confident this can be done by the 19th of April.

## DESCRIPTION

- [ ] REQUIRED: Now that you are using the 'MIT' license it needs to read 'MIT + file LICENSE' and include the necessary LICENSE file in the top directory of the package.

Best,
Kayla

**Comment by kvittingseerup** [comment]
Dear @Kayla-Morrell 

Thank you for your prompt action. I have now added the description and the license file.

**Comment by Kayla-Morrell** [comment]
@kvittingseerup - Great, thanks for making that change! I'm happy to accept the package now.

Best,
Kayla

**Comment by kvittingseerup** [comment]
Thanks for all the help @Kayla-Morrell. It really improved the package.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kvittingseerup.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pfamAnalyzeR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pfamAnalyzeR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
