### ISSUE TITLE
ZygosityPredictor

### ISSUE THREAD

**Issue by mrheinnecker** [Bioconductor/Contributions#2941]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CO-DKFZ/ZygosityPredictor

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
# Package 'ZygosityPredictor' Review
Thank you for submition your package to Bioconductor. The package passed check and build.  However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please condsider; Important: must be addressed.

## The DESCRIPTION file
- [x] Important: Please update the R version to >= 4.3.0

## The NAMESPACE file
- [x] Note: Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 6 import(datastructures)
	* in line 7 import(dplyr, except = c(first,last))
	* in line 8 import(dplyr, except = c(first,last)) ## why repeating here?
	* in line 10 import(stringr)
	* in line 11 import(tibble)
    
## General package development
- [x] NOTE: Consider adding the maintainer's ORCID iD in 'Authors@R' with
      'comment=c(ORCID="...")'
- [x] Important: Consider adding unit tests. We strongly encourage them. See
      https://contributions.bioconductor.org/tests.html

## R code
- [ ] Important: `vapply` instead of `sapply`.
	* In file R/fncts.R:
		+ at line 1305 found '  a_star_nodes <- sapply(still_present_muts, function(MUT){'
		+ at line 1310 found '    return(sapply(all_partners, function(x)return(1), simplify=FALSE) %>% '
- [ ] Important: No `paste` in `message()`, `message`, `stop`
	* In file R/fncts.R:
		+ at line 462 found '    error_message <- paste('
		+ at line 762 found '    error_message <- paste('
		+ at line 791 found '      warning_message <- paste("cna_type column of input somCna contains", '
		+ at line 801 found '        warning_message <- paste("tcn column of input somCna contains", '
		+ at line 818 found '        warning_message <- paste("tcn column of input somCna contains", '
		+ at line 847 found '      error_message <- paste('
		+ at line 881 found '      error_message <- paste('
		+ at line 1008 found '    warning_message <- paste('
		+ at line 1106 found '    warning_message <- paste("input bamRna does not exist:", bamRna,'
		+ at line 1652 found '      warning_message <- paste('
		+ at line 1825 found '    log_message <- paste("~", round('
		+ at line 1938 found '    warning_message <- paste('
- [ ] Important: `warning`, `message`, `stop` instead of `cat` and `print` outside of `show` methods.
	* In file R/fncts.R:
		+ at line 4 found '    cat(paste(c("\n",rep("  ", level)), collapse=""), '
		+ at line 1630 found '    cat("\n", GENE)'
		+ at line 1832 found '    cat("\n", log_message)'
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
- [ ] NOTE: Avoid 'suppressWarnings'/'*Messages' if possible
	* In file R/fncts.R:
		+ at line 620 found '        suppressWarnings('
- [ ] Note: Coding style. I am not understand this kind of coding style: eg. in file R/fncts.R line 18 '  ref_pos1 <- pos1 %>% as.numeric()'. Will it be OK to write as 'ref_pos1 <- as.numeric(pos1)'. Looks like you really enjoy the pipe style.
- [ ] NOTE: Functional programming: code repetition.
	* repetition in `aff_germ_copies` and `aff_som_copies`
		+ in aff_germ_copies
			- line 1:    af, tcn, purity, sex, cc = 1, c_normal = NULL) 
			- line 2:{
			- line 3:    purity <- check_purity(purity)
			- line 4:    af <- check_af(af)
			- line 5:    tcn <- check_tcn(tcn)
			- line 6:    cc <- check_cc(cc)
			- line 7:    if (is.null(c_normal)) {
			- line 8:        sex <- check_sex(sex)
			- line 9:        chr <- check_chr(chr)
			- line 10:        if ((sex == "male" & (chr == "X" | chr == "chrX")) | 
			- line 11:            (chr == "Y" | chr == "chrY")) {
			- line 12:            c_normal <- 1
			- line 13:        }
			- line 14:        else {
			- line 15:            c_normal <- 2
			- line 16:        }
			- line 17:    }
			- line 18:    else {
			- line 19:        c_normal <- check_ploidy(c_normal)
			- line 20:    }
			- line 21:    aff_cp <- af * (tcn + c_normal * (1/purity - 1)) - 1/purity + 
			- line 22:        1
		+ in aff_som_copies
			- line 1:    af, tcn, purity, sex, c_normal = NULL) 
			- line 2:{
			- line 3:    purity <- check_purity(purity)
			- line 4:    af <- check_af(af)
			- line 5:    tcn <- check_tcn(tcn)
			- line 6:    if (is.null(c_normal)) {
			- line 7:        sex <- check_sex(sex)
			- line 8:        chr <- check_chr(chr)
			- line 9:        if ((sex == "male" & (chr == "X" | chr == "chrX")) | 
			- line 10:            (chr == "Y" | chr == "chrY")) {
			- line 11:            c_normal <- 1
			- line 12:        }
			- line 13:        else {
			- line 14:            c_normal <- 2
			- line 15:        }
			- line 16:    }
			- line 17:    else {
			- line 18:        c_normal <- check_ploidy(c_normal)
			- line 19:    }
			- line 20:    aff_cp <- af * (tcn + c_normal * ((1/purity) - 1))
			- line 21:    return(aff_cp)
	* repetition in `check_gr_gene_model` and `check_gr_germ` and `check_gr_som` and `check_refgen`
		+ in check_gr_gene_model
			- line 7:        error_message <- paste("input geneModel must be a GRanges object;", 
			- line 8:            "given input appears to be:", paste(unlist(class(geneModel)), 
			- line 9:                collapse = ";"))
			- line 10:        stop(error_message)
			- line 11:    }
			- line 12:    else if (!(("gene" %in% names(GenomicRanges::elementMetadata(geneModel)) | 
			- line 13:        "GENE" %in% names(GenomicRanges::elementMetadata(geneModel))))) {
			- line 16:        stop(error_message)
			- line 17:    }
			- line 18:    else {
			- line 19:        col_gene <- str_match(names(GenomicRanges::elementMetadata(geneModel)), 
			- line 20:            "gene|GENE") %>% .[which(!is.na(.))]
		+ in check_gr_germ
			- line 5:            error_message <- paste("input germSmallVars must be a GRanges object;", 
			- line 6:                "given input appears to be:", paste(unlist(class(germSmallVars)), 
			- line 7:                  collapse = ";"))
			- line 8:            stop(error_message)
			- line 9:        }
			- line 10:        else if (!(("gene" %in% names(GenomicRanges::elementMetadata(germSmallVars)) | 
			- line 11:            "GENE" %in% names(GenomicRanges::elementMetadata(germSmallVars))) & 
			- line 20:            stop(error_message)
			- line 21:        }
			- line 22:        else {
			- line 23:            col_gene <- str_match(names(GenomicRanges::elementMetadata(germSmallVars)), 
			- line 24:                "gene|GENE") %>% .[which(!is.na(.))]
		+ in check_gr_som
			- line 5:            error_message <- paste("input somSmallVars must be a GRanges object;", 
			- line 6:                "given input appears to be:", paste(unlist(class(somSmallVars)), 
			- line 7:                  collapse = ";"))
			- line 8:            stop(error_message)
			- line 9:        }
			- line 10:        else if (!(("gene" %in% names(GenomicRanges::elementMetadata(somSmallVars)) | 
			- line 11:            "GENE" %in% names(GenomicRanges::elementMetadata(somSmallVars))) & 
			- line 20:            stop(error_message)
			- line 21:        }
			- line 22:        else {
			- line 23:            col_gene <- str_match(names(GenomicRanges::elementMetadata(somSmallVars)), 
			- line 24:                "gene|GENE") %>% .[which(!is.na(.))]
		+ in check_refgen
			- line 2:    . <- NULL
			- line 3:    if (!is(geneModel, "GRanges")) {
			- line 4:        error_message <- paste("input geneModel must be a GRanges object;", 
			- line 5:            "given input appears to be:", paste(unlist(class(geneModel)), 
			- line 6:                collapse = ";"))
			- line 7:        stop(error_message)
			- line 8:    }
			- line 9:    else if (!("gene" %in% names(GenomicRanges::elementMetadata(geneModel)))) {
			- line 10:        error_message <- paste("input geneModel requires the following metadata", 
			- line 11:            "columns: 'gene'")
			- line 12:        stop(error_message)
			- line 13:    }
			- line 14:    else {
			- line 15:        col_gene <- str_match(names(GenomicRanges::elementMetadata(geneModel)), 
			- line 16:            "gene|GENE") %>% .[which(!is.na(.))]
			- line 17:        GenomicRanges::elementMetadata(geneModel)[, "gene"] <- GenomicRanges::elementMetadata(geneModel)[, 
			- line 18:            col_gene]
			- line 19:        return(geneModel)
			- line 20:    }
	* repetition in `check_gr_germ` and `check_gr_som`
		+ in check_gr_germ
			- line 1:{
			- line 2:    . <- NULL
			- line 3:    if (!is.null(germSmallVars)) {
			- line 4:        if (!is(germSmallVars, "GRanges")) {
			- line 5:            error_message <- paste("input germSmallVars must be a GRanges object;", 
			- line 6:                "given input appears to be:", paste(unlist(class(germSmallVars)), 
			- line 7:                  collapse = ";"))
			- line 8:            stop(error_message)
			- line 9:        }
			- line 10:        else if (!(("gene" %in% names(GenomicRanges::elementMetadata(germSmallVars)) | 
			- line 11:            "GENE" %in% names(GenomicRanges::elementMetadata(germSmallVars))) & 
			- line 12:            ("af" %in% names(GenomicRanges::elementMetadata(germSmallVars)) | 
			- line 13:                "AF" %in% names(GenomicRanges::elementMetadata(germSmallVars))) & 
			- line 14:            ("ref" %in% names(GenomicRanges::elementMetadata(germSmallVars)) | 
			- line 15:                "REF" %in% names(GenomicRanges::elementMetadata(germSmallVars))) & 
			- line 16:            ("alt" %in% names(GenomicRanges::elementMetadata(germSmallVars)) | 
			- line 17:                "ALT" %in% names(GenomicRanges::elementMetadata(germSmallVars))))) {
			- line 18:            error_message <- paste0("input germSmallVars requires the following metadata columns:", 
			- line 19:                " 'gene', 'ref', 'alt', 'ACMG_class'  and 'af'")
			- line 20:            stop(error_message)
			- line 21:        }
			- line 22:        else {
			- line 23:            col_gene <- str_match(names(GenomicRanges::elementMetadata(germSmallVars)), 
			- line 24:                "gene|GENE") %>% .[which(!is.na(.))]
			- line 25:            col_af <- str_match(names(GenomicRanges::elementMetadata(germSmallVars)), 
			- line 26:                "af|AF") %>% .[which(!is.na(.))]
			- line 27:            col_ref <- str_match(names(GenomicRanges::elementMetadata(germSmallVars)), 
			- line 28:                "ref|REF") %>% .[which(!is.na(.))]
			- line 29:            col_alt <- str_match(names(GenomicRanges::elementMetadata(germSmallVars)), 
			- line 30:                "alt|ALT") %>% .[which(!is.na(.))]
			- line 31:            GenomicRanges::elementMetadata(germSmallVars)[, "gene"] <- GenomicRanges::elementMetadata(germSmallVars)[, 
			- line 32:                col_gene]
			- line 33:            GenomicRanges::elementMetadata(germSmallVars)[, "af"] <- GenomicRanges::elementMetadata(germSmallVars)[, 
			- line 34:                col_af]
			- line 35:            GenomicRanges::elementMetadata(germSmallVars)[, "ref"] <- GenomicRanges::elementMetadata(germSmallVars)[, 
			- line 36:                col_ref]
			- line 37:            GenomicRanges::elementMetadata(germSmallVars)[, "alt"] <- GenomicRanges::elementMetadata(germSmallVars)[, 
			- line 38:                col_alt]
			- line 39:            GenomicRanges::elementMetadata(germSmallVars)["mid"] <- seq_len(length(germSmallVars))
			- line 40:            return(germSmallVars)
			- line 41:        }
			- line 42:    }
			- line 43:    else {
			- line 44:        warning_message <- paste("Input germSmallVars empty/does not contain variants.", 
			- line 45:            "Assuming there are no germline small variants")
			- line 46:        warning(warning_message)
			- line 47:        return(NULL)
			- line 48:    }
		+ in check_gr_som
			- line 1:{
			- line 2:    . <- NULL
			- line 3:    if (!is.null(somSmallVars)) {
			- line 4:        if (!is(somSmallVars, "GRanges")) {
			- line 5:            error_message <- paste("input somSmallVars must be a GRanges object;", 
			- line 6:                "given input appears to be:", paste(unlist(class(somSmallVars)), 
			- line 7:                  collapse = ";"))
			- line 8:            stop(error_message)
			- line 9:        }
			- line 10:        else if (!(("gene" %in% names(GenomicRanges::elementMetadata(somSmallVars)) | 
			- line 11:            "GENE" %in% names(GenomicRanges::elementMetadata(somSmallVars))) & 
			- line 12:            ("af" %in% names(GenomicRanges::elementMetadata(somSmallVars)) | 
			- line 13:                "AF" %in% names(GenomicRanges::elementMetadata(somSmallVars))) & 
			- line 14:            ("ref" %in% names(GenomicRanges::elementMetadata(somSmallVars)) | 
			- line 15:                "REF" %in% names(GenomicRanges::elementMetadata(somSmallVars))) & 
			- line 16:            ("alt" %in% names(GenomicRanges::elementMetadata(somSmallVars)) | 
			- line 17:                "ALT" %in% names(GenomicRanges::elementMetadata(somSmallVars))))) {
			- line 18:            error_message <- paste0("input somSmallVars requires the following metadata columns:", 
			- line 19:                "'gene'/'GENE', 'ref'/'REF',", " 'alt'/'ALT' and 'af'/'AF'")
			- line 20:            stop(error_message)
			- line 21:        }
			- line 22:        else {
			- line 23:            col_gene <- str_match(names(GenomicRanges::elementMetadata(somSmallVars)), 
			- line 24:                "gene|GENE") %>% .[which(!is.na(.))]
			- line 25:            col_af <- str_match(names(GenomicRanges::elementMetadata(somSmallVars)), 
			- line 26:                "af|AF") %>% .[which(!is.na(.))]
			- line 27:            col_ref <- str_match(names(GenomicRanges::elementMetadata(somSmallVars)), 
			- line 28:                "ref|REF") %>% .[which(!is.na(.))]
			- line 29:            col_alt <- str_match(names(GenomicRanges::elementMetadata(somSmallVars)), 
			- line 30:                "alt|ALT") %>% .[which(!is.na(.))]
			- line 31:            GenomicRanges::elementMetadata(somSmallVars)[, "gene"] <- GenomicRanges::elementMetadata(somSmallVars)[, 
			- line 32:                col_gene]
			- line 33:            GenomicRanges::elementMetadata(somSmallVars)[, "af"] <- GenomicRanges::elementMetadata(somSmallVars)[, 
			- line 34:                col_af]
			- line 35:            GenomicRanges::elementMetadata(somSmallVars)[, "ref"] <- GenomicRanges::elementMetadata(somSmallVars)[, 
			- line 36:                col_ref]
			- line 37:            GenomicRanges::elementMetadata(somSmallVars)[, "alt"] <- GenomicRanges::elementMetadata(somSmallVars)[, 
			- line 38:                col_alt]
			- line 39:            GenomicRanges::elementMetadata(somSmallVars)["mid"] <- seq_len(length(somSmallVars))
			- line 40:            return(somSmallVars)
			- line 41:        }
			- line 42:    }
			- line 43:    else {
			- line 44:        warning_message <- paste("Input somSmallVars empty/does not contain variants.", 
			- line 45:            "Assuming there are no somatic small variants")
			- line 46:        warning(warning_message)
			- line 47:        return(NULL)
			- line 48:    }
	* repetition in `check_ploidy` and `check_purity`
		+ in check_ploidy
			- line 4:    }
			- line 5:    else if (is.na(as.numeric(ploidy))) {
			- line 6:        error_message <- paste("input ploidy/c_normal must be numeric or a character that can", 
			- line 7:            "be converted to numeric;\n  ", ploidy, "can not be converted to numeric")
			- line 8:        stop(error_message)
			- line 9:    }
			- line 10:    else {
			- line 11:        return(as.numeric(ploidy))
			- line 12:    }
		+ in check_purity
			- line 1:{
			- line 2:    if (is.na(as.numeric(purity))) {
			- line 3:        error_message <- paste("input purity must be numeric or a character that can", 
			- line 4:            "be converted to numeric;\n  ", purity, "can not be converted to numeric")
			- line 5:        stop(error_message)
			- line 6:    }
			- line 9:    }
			- line 10:    else {
			- line 11:        return(as.numeric(purity))
			- line 12:    }
	* repetition in `classify_combination` and `finalize_snp_phasing`
		+ in classify_combination
			- line 65:    if (eval_full == TRUE) {
			- line 66:        mtcn <- min(as.numeric(tcn1), as.numeric(tcn2))
			- line 67:        left_wt_copies <- ifelse(status == "diff", mtcn - sum(as.numeric(aff_copies1), 
			- line 68:            as.numeric(aff_copies2)), mtcn - max(as.numeric(aff_copies1), 
			- line 69:            as.numeric(aff_copies2)))
			- line 70:        pre_score <- ifelse(status == "diff" & left_wt_copies < 
			- line 71:            0.5, 2, 1)
		+ in finalize_snp_phasing
			- line 7:    aff_copies2 <- main_comb[["aff_cp2"]]
			- line 8:    mtcn <- min(as.numeric(tcn1), as.numeric(tcn2))
			- line 9:    left_wt_copies <- ifelse(status == "diff", mtcn - sum(as.numeric(aff_copies1), 
			- line 10:        as.numeric(aff_copies2)), mtcn - max(as.numeric(aff_copies1), 
			- line 11:        as.numeric(aff_copies2)))
			- line 12:    pre_score <- ifelse(status == "diff" & left_wt_copies < 0.5, 
			- line 13:        2, 1)
	* repetition in `prepare_germline_variants` and `prepare_somatic_variant_table`
		+ in prepare_germline_variants
			- line 7:        else {
			- line 8:            df_germ <- germSmallVars %>% IRanges::mergeByOverlaps(somCna) %>% 
			- line 9:                as_tibble() %>% mutate(cna_type = ifelse(str_detect(cna_type, 
			- line 10:                "LOH"), "LOH", "HZ")) %>% select(chr = 1, pos = 2, 
			- line 11:                gene, ref, alt, af, tcn, cna_type, tcn_assumed) %>% 
			- line 12:                mutate_at(.vars = c("af", "tcn"), .funs = as.numeric) %>% 
			- line 13:                rowwise() %>% mutate(origin = "germline", class = define_class(ref, 
			- line 14:                alt), aff_cp = aff_germ_copies(chr, af, tcn, 
			- line 15:                purity, sex, 1), wt_cp = tcn - aff_cp, pre_info = ifelse(base::isTRUE(cna_type == 
		+ in prepare_somatic_variant_table
			- line 4:        if (!is.null(somSmallVars)) {
			- line 5:            rel <- somSmallVars %>% IRanges::mergeByOverlaps(somCna) %>% 
			- line 6:                as_tibble() %>% mutate(cna_type = ifelse(str_detect(cna_type, 
			- line 7:                "LOH"), "LOH", "HZ")) %>% select(chr = 1, pos = 2, 
			- line 8:                gene, ref, alt, af, tcn, cna_type, tcn_assumed) %>% 
			- line 9:                mutate_at(.vars = c("tcn", "af"), .funs = as.numeric) %>% 
			- line 10:                rowwise() %>% mutate(origin = "somatic", class = define_class(ref, 
			- line 11:                alt), aff_cp = aff_som_copies(chr, af, tcn, purity, 
			- line 12:                sex), wt_cp = tcn - aff_cp, pre_info = ifelse(base::isTRUE(str_detect(cna_type, 
## Documentation
- [ ] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/Usage.Rmd
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/Usage.Rmd

**Comment by mrheinnecker** [comment]
### All issues addresseed

Thank you very much for the detailed review. I tried to address everything you mentioned and the package is now ready for a second review step.

## The DESCRIPTION file

- [x]  Important: Please update the R version to >= 4.3.0
done

## The NAMESPACE file

- [x] Note: Selective imports using importFrom instead of import all with import
changed imports for every function and corrected NAMESPACE file


## General package development

- [x]  NOTE: Consider adding the maintainer's ORCID iD in 'Authors@R' with
'comment=c(ORCID="...")'
added my ORCID id in the DESCRIPTION file
- [x]   Important: Consider adding unit tests. We strongly encourage them.
Unit tests added in /inst/tests/unit_tests.R
Thank you for brining this up. I worked myself a bit into the principle of unit tests now and added some for my functions. In the course of doing that i even noticed some actual issues in the functions which i could resolve then. I included unit tests for the 3  main functions which are exported into the namespace and also some for internal functions. I hope it is fine to add additional ones over the process of further development of the package, as for many functions the output is complicated and the unit tests therefore dificult. 

## R code

- [x] Important: vapply instead of sapply.
done
- [x] Important: No paste in message(), message, stop
done
- [x] Important: warning, message, stop instead of cat and print outside of show methods.
done

- [x] NOTE: :: is not suggested in source code
removed all of them and adjusted the dependencies for each function
- [ ] NOTE: Avoid 'suppressWarnings'/'*Messages' if possible
Unfortunately, this one needs to stay there. As the subsetByOverlaps function will give me the warning that the two objects have no overlapping regions at all. As I have to loop over every sCNA region to get the desired output, there will be a lot of non-overlapping function calls and the warning is thrown several times. I thought of working around this but i think this is the best way to handle it.
- [x] Note: Coding style. 
Yes, i think i really enjoy the pipe style... but you are totally right, in some cases it was too much. I tried to fix it for as many as posiible.
- [x] NOTE: Functional programming: code repetition
Thank you for pointing that out. I fixed all except one of the code duplications and could even get rid of some functions.
For one of the duplications it had to stay as it is. (check_ploidy and check_purity)

## Documentation

- [x] Important: Vignette should have an Installation section.
done
- [x] Important: Please include Bioconductor installation instructions using BiocManager.
done

**Comment by jianhong** [comment]
Please push your changes to git@git.bioconductor.org:packages/ZygosityPredictor to trigger a new build.
A quick tutorial for setting up remotes and pushing to upstream can be found [here](https://bioconductor.org/developers/how-to/git/new-package-workflow/).

**Comment by mrheinnecker** [comment]
All build issues fixed. What are the next steps?

**Comment by jianhong** [comment]
# Package 'ZygosityPredictor' Review
It is almost there. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.

## The DESCRIPTION file
- [ ] Important: import/suggusted GenomicRanges multiple times

## R code
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/fncts.R:
		+ at line 1249 found '  for(n in seq_len(str_count(sames$status, "same") %>% sum())){'
		+ at line 2133 found '    for (neighbor in names(nodes[[crnt$data]])) {'
- [ ] Important: Remove unused code.
	* In file R/fncts.R:
		+ at line 168 found '  # tcn1 <- main_comb[['tcn1']]'
		+ at line 169 found '  # tcn1 <- main_comb[['tcn2']]'
		+ at line 170 found '  # aff_copies1<- main_comb[['aff_cp1']]'
		+ at line 171 found '  # aff_copies2 <-  main_comb[['aff_cp2']]'
		+ at line 172 found '  # classified_reads <- main_classified_reads'
		+ at line 571 found '          #ifelse(base::isTRUE(str_detect(cna_type,'LOH')), '
		+ at line 1117 found '      #DelayedArray::rowRanges() %>%'
		+ at line 1133 found '    #dplyr::rename(pos=start, chr=seqnames) %>%'
		+ at line 1224 found '    #print(sub_classified_reads)'
		+ at line 1333 found '  #main_comb <- all_combinations[1,]'
		+ at line 2128 found '    #if (identical(crnt$data, goal))'
## Documentation
- [ ] Important: Variables with usage in documentation object 'GR_GENE_MODEL', 'GR_GERM_SMALL_VARS', 'GR_SCNA', 'GR_SOM_SMALL_VARS' but not in code. Try `@usage data(GR_SCNA)` to fix that.

**Comment by mrheinnecker** [comment]
### The DESCRIPTION file



 - [x] Important: import/suggusted GenomicRanges multiple times
done
### R code
- [ ] NOTE: Vectorize: for loops present, try to replace them by *apply funcitons.
Both for loops carry out very basic things (pathfinding algorithms), that sometimes require intermediate data from loop iterations. I am currently looking for an apply based solution but I think there is no way to do it by them. I know for loops in R should be avoided but I think for those cases they need to stay. Would that work out?
- [x] Important: Remove unused code.
done
### Documentation
- [x] Important: Variables with usage in documentation object 'GR_GENE_MODEL', 'GR_GERM_SMALL_VARS', 'GR_SCNA', 'GR_SOM_SMALL_VARS' but not in code. Try @usage data(GR_SCNA) to fix that.
done

**Comment by mrheinnecker** [comment]
I forgot to recreate the manual files for the updated data documentation, but now they are there.

**Comment by jianhong** [comment]
Great job! Thank you for your contribution.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mrheinnecker.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ZygosityPredictor")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ZygosityPredictor

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
