### ISSUE TITLE
BSgenomeForge

### ISSUE THREAD

**Issue by kakopo** [Bioconductor/Contributions#2943]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/BSgenomeForge

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by PeteHaitch** [comment]
Hi @kakopo,

Thank you for submitting **BSgenomeForge** to Bioconductor.

Overall, the package is in good shape and close to being ready for acceptance.

In my review below I have separated the issues into Required and Recommended points that I would ask you to address before the package can be accepted.
Would you please provide line-by-line comments to my initial review so that I know what changes I'm looking for in my re-review.

Cheers,
Pete

### Required

- [ ] Please remove `README-Oct2022.md` from the git repository.
- [ ] Is @kakopo or @hpages going to be the maintainer of the package? Please ensure that whoever is maintainer has `"cre"` included as their `role` in the `Authors@R` field of the `DESCRIPTION` (currently it's @hpages).
- [ ] I think the examples in the `.Rd` files and the vignette should probably set `destdir = tempdir()` so as not to pollute the user's or build machine's working directory.
- [ ] When running the first example from the vignette (actually, all of them) I got a warning that wasn't present in the rendered vignette. What does it mean and should it be addressed?

``` r
suppressPackageStartupMessages(library(BSgenomeForge))
forgeBSgenomeDataPkgFromNCBI(assembly_accession="GCA_009729545.1",
                             organism="Acidianus infernus",
                             pkg_maintainer="Jane Doe <janedoe@gmail.com>")
#> Creating package in ./BSgenome.Ainfernus.NCBI.ASM972954v1
#> Warning in file.rename(filepath, to): cannot rename file
#> '/var/folders/xb/3bl_ghcd3l5gcp6lxnkzy81h0000gn/T//RtmpPS7qnp/single_sequences.2bit'
#> to './BSgenome.Ainfernus.NCBI.ASM972954v1/inst/extdata/single_sequences.2bit',
#> reason 'No such file or directory'
```

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R Under development (unstable) (2023-02-13 r83829)
#>  os       macOS Ventura 13.2.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Australia/Melbourne
#>  date     2023-03-14
#>  pandoc   2.19.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package              * version   date (UTC) lib source
#>  Biobase                2.59.0    2022-12-20 [1] Bioconductor
#>  BiocGenerics         * 0.45.0    2022-12-20 [1] Bioconductor
#>  BiocIO                 1.9.2     2023-01-20 [1] Bioconductor
#>  BiocParallel           1.33.9    2022-12-23 [1] Bioconductor
#>  Biostrings           * 2.67.0    2022-12-20 [1] Bioconductor
#>  bitops                 1.0-7     2021-04-24 [1] CRAN (R 4.3.0)
#>  BSgenome             * 1.67.4    2023-02-08 [1] Bioconductor
#>  BSgenomeForge        * 0.99.0    2023-03-13 [1] Bioconductor
#>  cli                    3.6.0     2023-01-09 [1] CRAN (R 4.3.0)
#>  codetools              0.2-19    2023-02-01 [1] CRAN (R 4.3.0)
#>  crayon                 1.5.2     2022-09-29 [1] CRAN (R 4.3.0)
#>  DelayedArray           0.25.0    2022-12-20 [1] Bioconductor
#>  digest                 0.6.31    2022-12-11 [1] CRAN (R 4.3.0)
#>  evaluate               0.20      2023-01-17 [1] CRAN (R 4.3.0)
#>  fastmap                1.1.1     2023-02-24 [1] CRAN (R 4.3.0)
#>  fs                     1.6.1     2023-02-06 [1] CRAN (R 4.3.0)
#>  GenomeInfoDb         * 1.35.15   2023-02-03 [1] Bioconductor
#>  GenomeInfoDbData       1.2.9     2023-02-18 [1] Bioconductor
#>  GenomicAlignments      1.35.1    2023-03-09 [1] Bioconductor
#>  GenomicRanges        * 1.51.4    2022-12-20 [1] Bioconductor
#>  glue                   1.6.2     2022-02-24 [1] CRAN (R 4.3.0)
#>  htmltools              0.5.4     2022-12-07 [1] CRAN (R 4.3.0)
#>  IRanges              * 2.33.0    2022-12-20 [1] Bioconductor
#>  knitr                  1.42      2023-01-25 [1] CRAN (R 4.3.0)
#>  lattice                0.20-45   2021-09-22 [1] CRAN (R 4.3.0)
#>  lifecycle              1.0.3     2022-10-07 [1] CRAN (R 4.3.0)
#>  Matrix                 1.5-3     2022-11-11 [1] CRAN (R 4.3.0)
#>  MatrixGenerics         1.11.0    2022-12-20 [1] Bioconductor
#>  matrixStats            0.63.0    2022-11-18 [1] CRAN (R 4.3.0)
#>  RCurl                  1.98-1.10 2023-01-27 [1] CRAN (R 4.3.0)
#>  reprex                 2.0.2     2022-08-17 [1] CRAN (R 4.3.0)
#>  restfulr               0.0.15    2022-06-16 [1] CRAN (R 4.3.0)
#>  rjson                  0.2.21    2022-01-09 [1] CRAN (R 4.3.0)
#>  rlang                  1.0.6     2022-09-24 [1] CRAN (R 4.3.0)
#>  rmarkdown              2.20      2023-01-19 [1] CRAN (R 4.3.0)
#>  Rsamtools              2.15.1    2022-12-30 [1] Bioconductor
#>  rstudioapi             0.14      2022-08-22 [1] CRAN (R 4.3.0)
#>  rtracklayer          * 1.59.1    2022-12-30 [1] Bioconductor
#>  S4Vectors            * 0.37.4    2023-02-26 [1] Bioconductor
#>  sessioninfo            1.2.2     2021-12-06 [1] CRAN (R 4.3.0)
#>  SummarizedExperiment   1.29.1    2022-12-20 [1] Bioconductor
#>  withr                  2.5.0     2022-03-03 [1] CRAN (R 4.3.0)
#>  xfun                   0.37      2023-01-31 [1] CRAN (R 4.3.0)
#>  XML                    3.99-0.13 2022-12-04 [1] CRAN (R 4.3.0)
#>  XVector              * 0.39.0    2022-12-20 [1] Bioconductor
#>  yaml                   2.3.7     2023-01-23 [1] CRAN (R 4.3.0)
#>  zlibbioc               1.45.0    2022-12-20 [1] Bioconductor
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

- [ ] Running `R CMD check` and `R CMD install` on the `BSgenome.Ainfernus.NCBI.ASM972954v1` example created during the vignette both failed (run via command line or with **devtools** wrappers). Please clarify why this fails and fix if it should be working.

``` r
suppressPackageStartupMessages(library(BSgenomeForge))
forgeBSgenomeDataPkgFromNCBI(assembly_accession="GCA_009729545.1",
                             organism="Acidianus infernus",
                             pkg_maintainer="Jane Doe <janedoe@gmail.com>")
#> Creating package in ./BSgenome.Ainfernus.NCBI.ASM972954v1
#> Warning in file.rename(filepath, to): cannot rename file
#> '/var/folders/xb/3bl_ghcd3l5gcp6lxnkzy81h0000gn/T//RtmpjMSWrA/single_sequences.2bit'
#> to './BSgenome.Ainfernus.NCBI.ASM972954v1/inst/extdata/single_sequences.2bit',
#> reason 'No such file or directory'
devtools::build("./BSgenome.Ainfernus.NCBI.ASM972954v1")
#> ── R CMD build ─────────────────────────────────────────────────────────────────
#> * checking for file ‘/private/var/folders/xb/3bl_ghcd3l5gcp6lxnkzy81h0000gn/T/RtmpFXx1Ut/reprex-173f83094461c-beton-fish/BSgenome.Ainfernus.NCBI.ASM972954v1/DESCRIPTION’ ... OK
#> * preparing ‘BSgenome.Ainfernus.NCBI.ASM972954v1’:
#> * checking DESCRIPTION meta-information ... OK
#> * checking for LF line-endings in source and make files and shell scripts
#> * checking for empty or unneeded directories
#> * building ‘BSgenome.Ainfernus.NCBI.ASM972954v1_1.0.0.tar.gz’
#> [1] "/private/var/folders/xb/3bl_ghcd3l5gcp6lxnkzy81h0000gn/T/RtmpFXx1Ut/reprex-173f83094461c-beton-fish/BSgenome.Ainfernus.NCBI.ASM972954v1_1.0.0.tar.gz"
devtools::check_built("BSgenome.Ainfernus.NCBI.ASM972954v1_1.0.0.tar.gz")
#> ══ Checking ════════════════════════════════════════════════════════════════════
#> Setting env vars:
#> • _R_CHECK_CRAN_INCOMING_REMOTE_               : FALSE
#> • _R_CHECK_CRAN_INCOMING_                      : FALSE
#> • _R_CHECK_FORCE_SUGGESTS_                     : FALSE
#> • _R_CHECK_PACKAGES_USED_IGNORE_UNUSED_IMPORTS_: FALSE
#> ── R CMD check ─────────────────────────────────────────────────────────────────
#> * using log directory ‘/private/var/folders/xb/3bl_ghcd3l5gcp6lxnkzy81h0000gn/T/RtmpjMSWrA/BSgenome.Ainfernus.NCBI.ASM972954v1.Rcheck’
#> * using R Under development (unstable) (2023-02-13 r83829)
#> * using platform: aarch64-apple-darwin20 (64-bit)
#> * R was compiled by
#>     Apple clang version 13.0.0 (clang-1300.0.29.3)
#>     GNU Fortran (GCC) 12.0.1 20220312 (experimental)
#> * running under: macOS Ventura 13.2.1
#> * using session charset: UTF-8
#> * using options ‘--no-manual --as-cran’
#> * checking for file ‘BSgenome.Ainfernus.NCBI.ASM972954v1/DESCRIPTION’ ... OK
#> * this is package ‘BSgenome.Ainfernus.NCBI.ASM972954v1’ version ‘1.0.0’
#> * checking package namespace information ... OK
#> * checking package dependencies ... OK
#> * checking if this is a source package ... OK
#> * checking if there is a namespace ... OK
#> * checking for executable files ... OK
#> * checking for hidden files and directories ... OK
#> * checking for portable file names ... OK
#> * checking for sufficient/correct file permissions ... OK
#> * checking whether package ‘BSgenome.Ainfernus.NCBI.ASM972954v1’ can be installed ... ERROR
#> Installation failed.
#> See ‘/private/var/folders/xb/3bl_ghcd3l5gcp6lxnkzy81h0000gn/T/RtmpjMSWrA/BSgenome.Ainfernus.NCBI.ASM972954v1.Rcheck/00install.out’ for details.
#> * DONE
#> 
#> Status: 1 ERROR
#> See
#>   ‘/private/var/folders/xb/3bl_ghcd3l5gcp6lxnkzy81h0000gn/T/RtmpjMSWrA/BSgenome.Ainfernus.NCBI.ASM972954v1.Rcheck/00check.log’
#> for details.
#> 
#> ── R CMD check results ────────── BSgenome.Ainfernus.NCBI.ASM972954v1 1.0.0 ────
#> Duration: 8.3s
#> 
#> ❯ checking whether package ‘BSgenome.Ainfernus.NCBI.ASM972954v1’ can be installed ... ERROR
#>   See below...
#> 
#> ── Install failure ─────────────────────────────────────────────────────────────
#> 
#> * installing *source* package ‘BSgenome.Ainfernus.NCBI.ASM972954v1’ ...
#> ** using staged installation
#> ** R
#> ** byte-compile and prepare package for lazy loading
#> ** help
#> *** installing help indices
#> ** building package indices
#> ** testing if installed package can be loaded from temporary location
#> Error: package or namespace load failed for ‘BSgenome.Ainfernus.NCBI.ASM972954v1’:
#>  .onLoad failed in loadNamespace() for 'BSgenome.Ainfernus.NCBI.ASM972954v1', details:
#>   call: system.file("extdata", package = pkgname, lib.loc = libname, 
#>   error: no file found
#> Error: loading failed
#> Execution halted
#> ERROR: loading failed
#> * removing ‘/private/var/folders/xb/3bl_ghcd3l5gcp6lxnkzy81h0000gn/T/RtmpjMSWrA/BSgenome.Ainfernus.NCBI.ASM972954v1.Rcheck/BSgenome.Ainfernus.NCBI.ASM972954v1’
#> 
#> 1 error ✖ | 0 warnings ✔ | 0 notes ✔
#> Error: R CMD check found ERRORs
devtools::install_local("BSgenome.Ainfernus.NCBI.ASM972954v1_1.0.0.tar.gz")
#> 
#> ── R CMD build ─────────────────────────────────────────────────────────────────
#> * checking for file ‘/private/var/folders/xb/3bl_ghcd3l5gcp6lxnkzy81h0000gn/T/RtmpjMSWrA/remotesa342a261972/BSgenome.Ainfernus.NCBI.ASM972954v1/DESCRIPTION’ ... OK
#> * preparing ‘BSgenome.Ainfernus.NCBI.ASM972954v1’:
#> * checking DESCRIPTION meta-information ... OK
#> * checking for LF line-endings in source and make files and shell scripts
#> * checking for empty or unneeded directories
#> * building ‘BSgenome.Ainfernus.NCBI.ASM972954v1_1.0.0.tar.gz’
#> Warning in i.p(...): installation of package
#> '/var/folders/xb/3bl_ghcd3l5gcp6lxnkzy81h0000gn/T//RtmpjMSWrA/filea343a79169b/BSgenome.Ainfernus.NCBI.ASM972954v1_1.0.0.tar.gz'
#> had non-zero exit status
```

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R Under development (unstable) (2023-02-13 r83829)
#>  os       macOS Ventura 13.2.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Australia/Melbourne
#>  date     2023-03-14
#>  pandoc   2.19.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package              * version   date (UTC) lib source
#>  Biobase                2.59.0    2022-12-20 [1] Bioconductor
#>  BiocGenerics         * 0.45.0    2022-12-20 [1] Bioconductor
#>  BiocIO                 1.9.2     2023-01-20 [1] Bioconductor
#>  BiocParallel           1.33.9    2022-12-23 [1] Bioconductor
#>  Biostrings           * 2.67.0    2022-12-20 [1] Bioconductor
#>  bitops                 1.0-7     2021-04-24 [1] CRAN (R 4.3.0)
#>  BSgenome             * 1.67.4    2023-02-08 [1] Bioconductor
#>  BSgenomeForge        * 0.99.0    2023-03-13 [1] Bioconductor
#>  cachem                 1.0.7     2023-02-24 [1] CRAN (R 4.3.0)
#>  callr                  3.7.3     2022-11-02 [1] CRAN (R 4.3.0)
#>  cli                    3.6.0     2023-01-09 [1] CRAN (R 4.3.0)
#>  codetools              0.2-19    2023-02-01 [1] CRAN (R 4.3.0)
#>  crayon                 1.5.2     2022-09-29 [1] CRAN (R 4.3.0)
#>  curl                   5.0.0     2023-01-12 [1] CRAN (R 4.3.0)
#>  DelayedArray           0.25.0    2022-12-20 [1] Bioconductor
#>  desc                   1.4.2     2022-09-08 [1] CRAN (R 4.3.0)
#>  devtools               2.4.5     2022-10-11 [1] CRAN (R 4.3.0)
#>  digest                 0.6.31    2022-12-11 [1] CRAN (R 4.3.0)
#>  ellipsis               0.3.2     2021-04-29 [1] CRAN (R 4.3.0)
#>  evaluate               0.20      2023-01-17 [1] CRAN (R 4.3.0)
#>  fastmap                1.1.1     2023-02-24 [1] CRAN (R 4.3.0)
#>  fs                     1.6.1     2023-02-06 [1] CRAN (R 4.3.0)
#>  GenomeInfoDb         * 1.35.15   2023-02-03 [1] Bioconductor
#>  GenomeInfoDbData       1.2.9     2023-02-18 [1] Bioconductor
#>  GenomicAlignments      1.35.1    2023-03-09 [1] Bioconductor
#>  GenomicRanges        * 1.51.4    2022-12-20 [1] Bioconductor
#>  glue                   1.6.2     2022-02-24 [1] CRAN (R 4.3.0)
#>  htmltools              0.5.4     2022-12-07 [1] CRAN (R 4.3.0)
#>  htmlwidgets            1.6.1     2023-01-07 [1] CRAN (R 4.3.0)
#>  httpuv                 1.6.9     2023-02-14 [1] CRAN (R 4.3.0)
#>  IRanges              * 2.33.0    2022-12-20 [1] Bioconductor
#>  knitr                  1.42      2023-01-25 [1] CRAN (R 4.3.0)
#>  later                  1.3.0     2021-08-18 [1] CRAN (R 4.3.0)
#>  lattice                0.20-45   2021-09-22 [1] CRAN (R 4.3.0)
#>  lifecycle              1.0.3     2022-10-07 [1] CRAN (R 4.3.0)
#>  magrittr               2.0.3     2022-03-30 [1] CRAN (R 4.3.0)
#>  Matrix                 1.5-3     2022-11-11 [1] CRAN (R 4.3.0)
#>  MatrixGenerics         1.11.0    2022-12-20 [1] Bioconductor
#>  matrixStats            0.63.0    2022-11-18 [1] CRAN (R 4.3.0)
#>  memoise                2.0.1     2021-11-26 [1] CRAN (R 4.3.0)
#>  mime                   0.12      2021-09-28 [1] CRAN (R 4.3.0)
#>  miniUI                 0.1.1.1   2018-05-18 [1] CRAN (R 4.3.0)
#>  pkgbuild               1.4.0     2022-11-27 [1] CRAN (R 4.3.0)
#>  pkgload                1.3.2     2022-11-16 [1] CRAN (R 4.3.0)
#>  prettyunits            1.1.1     2020-01-24 [1] CRAN (R 4.3.0)
#>  processx               3.8.0     2022-10-26 [1] CRAN (R 4.3.0)
#>  profvis                0.3.7     2020-11-02 [1] CRAN (R 4.3.0)
#>  promises               1.2.0.1   2021-02-11 [1] CRAN (R 4.3.0)
#>  ps                     1.7.2     2022-10-26 [1] CRAN (R 4.3.0)
#>  purrr                  1.0.1     2023-01-10 [1] CRAN (R 4.3.0)
#>  R6                     2.5.1     2021-08-19 [1] CRAN (R 4.3.0)
#>  rcmdcheck              1.4.0     2021-09-27 [1] CRAN (R 4.3.0)
#>  Rcpp                   1.0.10    2023-01-22 [1] CRAN (R 4.3.0)
#>  RCurl                  1.98-1.10 2023-01-27 [1] CRAN (R 4.3.0)
#>  remotes                2.4.2     2021-11-30 [1] CRAN (R 4.3.0)
#>  reprex                 2.0.2     2022-08-17 [1] CRAN (R 4.3.0)
#>  restfulr               0.0.15    2022-06-16 [1] CRAN (R 4.3.0)
#>  rjson                  0.2.21    2022-01-09 [1] CRAN (R 4.3.0)
#>  rlang                  1.0.6     2022-09-24 [1] CRAN (R 4.3.0)
#>  rmarkdown              2.20      2023-01-19 [1] CRAN (R 4.3.0)
#>  rprojroot              2.0.3     2022-04-02 [1] CRAN (R 4.3.0)
#>  Rsamtools              2.15.1    2022-12-30 [1] Bioconductor
#>  rstudioapi             0.14      2022-08-22 [1] CRAN (R 4.3.0)
#>  rtracklayer          * 1.59.1    2022-12-30 [1] Bioconductor
#>  S4Vectors            * 0.37.4    2023-02-26 [1] Bioconductor
#>  sessioninfo            1.2.2     2021-12-06 [1] CRAN (R 4.3.0)
#>  shiny                  1.7.4     2022-12-15 [1] CRAN (R 4.3.0)
#>  stringi                1.7.12    2023-01-11 [1] CRAN (R 4.3.0)
#>  stringr                1.5.0     2022-12-02 [1] CRAN (R 4.3.0)
#>  SummarizedExperiment   1.29.1    2022-12-20 [1] Bioconductor
#>  urlchecker             1.0.1     2021-11-30 [1] CRAN (R 4.3.0)
#>  usethis                2.1.6     2022-05-25 [1] CRAN (R 4.3.0)
#>  vctrs                  0.5.2     2023-01-23 [1] CRAN (R 4.3.0)
#>  withr                  2.5.0     2022-03-03 [1] CRAN (R 4.3.0)
#>  xfun                   0.37      2023-01-31 [1] CRAN (R 4.3.0)
#>  XML                    3.99-0.13 2022-12-04 [1] CRAN (R 4.3.0)
#>  xopen                  1.0.0     2018-09-17 [1] CRAN (R 4.3.0)
#>  xtable                 1.8-4     2019-04-21 [1] CRAN (R 4.3.0)
#>  XVector              * 0.39.0    2022-12-20 [1] Bioconductor
#>  yaml                   2.3.7     2023-01-23 [1] CRAN (R 4.3.0)
#>  zlibbioc               1.45.0    2022-12-20 [1] Bioconductor
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

- [ ] Could the `eval=FALSE` chunks in the vignette instead be evaluated (which might have caught the above issue I had) or does it get a bit circular building/checking/installing another package during the building/checking/installing of **BSgenomeForge**?
- [ ] Please add an *Installation* section to the vignette (https://contributions.bioconductor.org/docs.html?vignettes#installation)

### Recommended

- [ ] `BiocCheck::BiocCheck()` suggests `Consider adding the maintainer's ORCID iD in 'Authors@R' with 'comment=c(ORCID="...")'`
- [ ] Consider adding a package-level man page (https://contributions.bioconductor.org/docs.html?vignettes#package-level-documentation)
- [ ] Consider adding some more unit tests. You could take a look at running `covr::report()` to help identify code that would benefit from unit tests.

**Comment by kakopo** [comment]
Hi @PeteHaitch,
Thank you for the initial review. I and @hpages worked on them and I hope the package is in better shape! I am adding comments to all the changes put in place. 

### Required 

> [x] Please remove `README-Oct2022.md` from the git repository.

Done.

> [x]  Is @kakopo or @hpages going to be the maintainer of the package? Please ensure that whoever is maintainer has `"cre"` included as their `role` in the `Authors@R` field of the `DESCRIPTION` (currently it's @hpages).

@hpages shall be the package maintainer.

> [x] I think the examples in the `.Rd` files and the vignette should probably set `destdir` = `tempdir()` so as not to pollute the user's or build machine's working directory.

Done.

> [x] When running the first example from the vignette (actually, all of them) I got a warning that wasn't present in the rendered vignette. What does it mean and should it be addressed?

In my correspondence with @hpages, he mentioned that the warning you get when calling `forgeBSgenomeDataPkgFromNCBI()` is probably because you installed BSgenomeForge from a source tarball
obtained without using the `--keep-empty-dirs` option. 
Perhaps you could try installing the package with this option and see if the same error returns, thanks!

> [x] Running `R CMD check` and `R CMD install` on the `BSgenome.Ainfernus.NCBI.ASM972954v1` example created during the vignette both failed (run via command line or with devtools wrappers). Please clarify why this fails and fix if it should be working.

This seems to fail because of an issue similar to the above. I hope the above solution fits here as well.

> [x] Could the `eval=FALSE` chunks in the vignette instead be evaluated (which might have caught the above issue I had) or does it get a bit circular building/checking/installing another package during the building/checking/installing of BSgenomeForge?

The `eval=FALSE` chunks were not evaluated as they do the circular building/checking/installing of BSgenomeForge, so it was best to leave them unchecked. 


> [x]  Please add an Installation section to the vignette (https://contributions.bioconductor.org/docs.html?vignettes#installation)

Done.

### Recommended
> [x]  `BiocCheck::BiocCheck()` suggests `Consider adding the maintainer's ORCID iD in 'Authors@R' with 'comment=c(ORCID="...")'`

Neither @hpages nor I have an ORCID.

> [x] Consider adding a package-level man page (https://contributions.bioconductor.org/docs.html?vignettes#package-level-documentation)

This was not added.

> [x] Consider adding some more unit tests. You could take a look at running covr::report() to help identify code that would benefit from unit tests.

Done.

**Comment by PeteHaitch** [comment]
Thank you for making the required changes, @kakopo and @hpages.
I'm now happy to accept **BSgenomeForge** into Bioconductor.
Congratulations and thank you for your contribution!

I can confirm that building the package with `R CMD build --keep-empty-dirs` eliminated the extraneous warning in the vignette and in checking and installing the example packages from the vignette.

**Comment by PeteHaitch** [comment]
Sorry, before I can formally accept the package could you please try please push to `git@git.bioconductor.org:packages/BSgenomeForge` to trigger a new build.
The most recent build (https://github.com/Bioconductor/Contributions/issues/2943#issuecomment-1488062691) returned an error on macOS (`merida1`), although the package passes checks on my personal macOS (Apple silicon) device.

**Comment by lshep** [comment]
@PeteHaitch The mac builder is still down. if it is building on linux and your local mac I would use those right now for reference.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kakopo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BSgenomeForge")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BSgenomeForge

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
