### ISSUE TITLE
spicyWorkflow

### ISSUE THREAD

**Issue by SOMS-Maintainer** [Bioconductor/Contributions#2967]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SydneyBioX/spicyWorkflow

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```
* checking for file 'spicyWorkflow/DESCRIPTION' ... OK
* preparing 'spicyWorkflow':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘spicyWorkflow.Rmd’ using rmarkdown
Quitting from lines 564-575 (spicyWorkflow.Rmd) 
Error: processing vignette 'spicyWorkflow.Rmd' failed with diagnostics:
subscript contains invalid names
--- failed re-building ‘spicyWorkflow.Rmd’

SUMMARY: processing the following file failed:
  ‘spicyWorkflow.Rmd’

Error: Vignette re-building failed.
```
pre-check fails.  Please run R CMD check on your package before submitting it.  Please run it in a completely cleared workspace.

**Comment by SOMS-Maintainer** [comment]
We are waiting on ClassifyR to be patched on devel, as it is causing an error.

**Comment by lshep** [comment]
@SOMS-Maintainer  have you reached out to the ClassifyR maintainers to request this patch? The package while it has one timeout on devel mac, is building only with warnings on all the other bioconductor build machines in release and devel. If you have not been in contact they might not be aware of the issue?

**Comment by SOMS-Maintainer** [comment]
@lshep We are in contact with Dario, and he is aware of the issue.

**Comment by SOMS-Maintainer** [comment]
Alright, errors are gone and it's ready to go @vjcitn

**Comment by SOMS-Maintainer** [comment]
I am having trouble replicating this error in the following environment.

```r
r$> sessionInfo()
R version 4.3.0 alpha (2023-03-29 r84123)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 11 (bullseye)
...
r$> BiocManager::version()
[1] ‘3.17’
```

Running `devtools::build()` and `devtools::check()` goes smoothly without errors. Do you have any advice on how to find the issue?

**Comment by jianhong** [comment]
Try [docker](http://bioconductor.org/help/docker/). If you still have trouble in repeating the error, just try update the version number to trigger another build.

**Comment by SOMS-Maintainer** [comment]
Looks like the problem was the number of cores!

**Comment by jianhong** [comment]
# Package 'spicyWorkflow' Review
Thank you for submition your package to Bioconductor. The package passed check and build. But when build the vignettes, my system got crashed and restarted. My system is  macOS Big Sur M1 chip. I don't think this is acceptable. Please try to fix the issue and answer the following comments line by line when you are ready for a second review.
Code: Note: please condsider; Important: must be addressed.

## The DESCRIPTION file
- [ ] At least 3 sentences in `Description` field is required.
- [ ] update the R required version to 4.3.0
- [ ] NOTE: Consider adding the maintainer's ORCID iD in 'Authors@R'
      with 'comment=c(ORCID="...")'
 
## R code:
- [ ] Important: fix the hard coding:
        * rmd file vignettes/spicyWorkflow.Rmd
            - line 111: pathToImages <- "../inst/extdata/images" # suggest `?system.file`
            - line 128: dir.create("../inst/extdata/h5Files") # change to a tmp file
            - line 132: h5FilesPath = "../inst/extdata/h5Files",
            - line 147: clinical <- read.csv("../inst/extdata/1-s2.0-S0092867421014860-mmc1.csv")
- [ ] Important: Use `vapply` to replace `sapply`
        * rmd file vignettes/spicyWorkflow.Rmd
            - line 118: files <- sapply(imageDirs, list.files, pattern = "tif", full.names = TRUE, simplify = FALSE)
 - [ ] Auto detect available cores and minimize the used cores for the vignette at
         * rmd file vignettes/spicyWorkflow.Rmd
             - line 91: nCores <- 5
 
## Documentation
- [ ] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/spicyWorkflow.Rmd
- [ ] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/spicyWorkflow.Rmd
- [ ] Important: Cause system crash by build the  vignettes/spicyWorkflow.Rmd.
- [ ] Important: move the `docs` folder and the `_pkgdown.yml` to a separate branch like `gh-pages`.

**Comment by SOMS-Maintainer** [comment]
Hi @jianhong,

Thanks for the feedback, I am currently working through your comments. I think I have solved the memory issue that caused your session to crash, let me know if you can run through it now. In order to run the current version, you must have a valid devel Bioc installation.

**Comment by SOMS-Maintainer** [comment]
Hi @jianhong,

I belive I have addressed all the problems.

## The DESCRIPTION file
- [x] At least 3 sentences in `Description` field is required.
- [x] update the R required version to 4.3.0
- [x] NOTE: Consider adding the maintainer's ORCID iD in 'Authors@R'
      with 'comment=c(ORCID="...")'
 
## R code:
- [x] Important: fix the hard coding:
        * rmd file vignettes/spicyWorkflow.Rmd
            - line 111: pathToImages <- "../inst/extdata/images" # suggest `?system.file`
            - line 128: dir.create("../inst/extdata/h5Files") # change to a tmp file
            - line 132: h5FilesPath = "../inst/extdata/h5Files",
            - line 147: clinical <- read.csv("../inst/extdata/1-s2.0-S0092867421014860-mmc1.csv")
- [x] Important: Use `vapply` to replace `sapply`
        * rmd file vignettes/spicyWorkflow.Rmd
            - line 118: files <- sapply(imageDirs, list.files, pattern = "tif", full.names = TRUE, simplify = FALSE)
 - [x] Auto detect available cores and minimize the used cores for the vignette at
         * rmd file vignettes/spicyWorkflow.Rmd
             - line 91: nCores <- 5
 
## Documentation
- [x] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/spicyWorkflow.Rmd
- [x] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/spicyWorkflow.Rmd
- [x] Important: Cause system crash by build the  vignettes/spicyWorkflow.Rmd.
- [x] Important: move the `docs` folder and the `_pkgdown.yml` to a separate branch like `gh-pages`.

**Comment by jianhong** [comment]
when making changes to your repository push to
git@git.bioconductor.org:packages/spicyWorkflow to trigger a new build.
A quick tutorial for setting up remotes and pushing to upstream can be found [here](https://bioconductor.org/developers/how-to/git/new-package-workflow/).

**Comment by SOMS-Maintainer** [comment]
Sorry about that, forgot to push.

**Comment by SOMS-Maintainer** [comment]
Setting a variable number of cores seems to be causing issues on BBS. I set the cores to 1, conditional on a flag.

**Comment by SOMS-Maintainer** [comment]
The last build seems to have disappeared, so I pushed again.

**Comment by ellispatrick** [comment]
Hi @jianhong, we have tracked down a mac with a Big Sur M1 chip and the workflow appears to build fine on that computer. Hopefully it is working on your end.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SOMS-Maintainer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("spicyWorkflow")`. The package 'landing page' will be created at

https://bioconductor.org/packages/spicyWorkflow

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
