### ISSUE TITLE
Moonlight2R

### ISSUE THREAD

**Issue by mtiberti** [Bioconductor/Contributions#2993]
Hi, here's our submission for the `Moonlight2R` package. Thanks for reviewing it!

- Repository: https://github.com/ELELAB/Moonlight2R

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

**Comment by ococrook** [comment]
My apologies for the delay - this is quite a busy time for package submission. The package looks good and a few improvements to the package would make it great! Could you address the following or breifly explain that it's not possible/appropraite.

My main comment is that the package relies on data.frames and tables as input into its analysis, it would be much better if it interoperates with the already available bioconductor infrastructure on differential expression etc. 

- [ ] Please add unit tests as this helps avoid bug accumulate over successive versions
- [ ] I think you need to add the follow imports to the NAMESPACE 
 importFrom("stats", "end", "start")
  importFrom("utils", "head")
- [ ] “You can remove the “no visible bindings for global variable” NOTE by adapting the following code
utils::globalVariables(c(“ID”))
- [ ] LazyData to false
- [ ] Update R version to 4.3
- [ ] The License is unclear (you have to fix a license it can’t be a conditional statement)

R code
- [ ] You have some instances of sapply, we strongly suggest switching to vapply
- [ ] The 1:.. Construct can go wrong ( e.g. 1:-1) switch to seq_len, seq.int, seq_along etc.
- [ ] There is some uncommented code in the package - sometime its need to clarify something but commented out code mid-function is likely to be confusing
- [ ] The code is quite crowded in places - adding extra white space can help and a space after commas can be really useful
- [ ] Try to be consistent with indenting in if statements and for loops
- [ ] Please switch \dontrun in examples to \donttest to ensure they still correct syntax
- [ ] Please check the inputs to the functions to help the user. Getting the code wrong currently leads to cryptic errors. 

Vignette
- [ ] You have quite a lot of `eval = FALSE` chunks. This can be more unhelpful than helpful. If they’re too slow you consider preloading the result?

**Comment by mtiberti** [comment]
thank you very much @ococrook - and no worries about the timing. We'll try to get the changes in as soon as possible but having seen what needs to be changed we think it's unlikely we'll manage before the deadline for 3.17. Keep you posted!

**Comment by ococrook** [comment]
I wouldn't worry to much about the deadline  - the package will still be added to the devel build when accepted and you can install from there.

**Comment by ococrook** [comment]
Hi @mtiberti, is this still active? We can close the issue if you need more time and re-open it at a later date when you're ready. If you no longer plan to make the changes that also works and we can also close the issue.

Best wishes,
Olly

**Comment by mtiberti** [comment]
hi @ococrook,

we are actively working on the package as a new paper connected to it is under review, and the reviewers asked for some changes. We should soon be able to update the version in Bioconductor soon and work on the revision as well, so I would keep the issue open if possible

Thank you!

**Comment by lshep** [comment]
We are closing the package review for inactivity.  When you are ready to push changes to git.bioconductor.org and continue the process please let us know with a message here and we will reopen the issue.

**Comment by mtiberti** [comment]
hi, we would like to start pushing changes to the repository again. We are ready to push a couple of new functions/fixes that were done during the revision of the associated paper and will follow through revision points from there. Thank you

**Comment by mtiberti** [comment]
hi @ococrook, sorry it took us a while, we were busy with revisions for the paper we recently published for this package, but we now managed to work on revisions and considered/implemented all your suggestions. We think overall code quality and robustness did improve, so thank you! Answers to your points below

## General

> My main comment is that the package relies on data.frames and tables as input into its analysis, it would be much better if it interoperates with the already available bioconductor infrastructure on differential expression etc.

Moonlight2R takes a table of differential expression analysis results as primary data input. We have not been able to find a ready-made container for DEA data as SummarizedExperiment is mostly designed for matrices containing samples x features.

Further, we have investigated differential expression data structures in BioConductor and found that the most popular DEA tools (edgeR, DESeq2 and limma) each use a _unique and different_ data structure based on a SummarizedExperiment object. These DEA tools have a function that can be used in the end to convert from their data representation to a `data.frame` that contains the differentially expressed genes, log fold change values, FDR values etc - functions that we ourselves use at the end of the DEAm, when we perform it outside of Moonlight2R. Therefore, this seems to be the most transferable data format that these tools can produce. Using one of the specialised data formats as inputs would restrict our ability to support natively only some of the aforementioned tools, while we would like to be more general and support the output from all of them with a minimal overhead. In this sense, We think that maintaining Moonlight’s flexibility in accepting a simple as possible DEA data format is beneficial for its usage.

Nonetheless, we are open for further suggestions on how we can interoperate with the BioConductor infrastructure on differential expression

>  Please add unit tests as this helps avoid bug accumulate over successive versions

we added unit tests with `testthat`

>  I think you need to add the follow imports to the NAMESPACE
> importFrom("stats", "end", "start")
> importFrom("utils", "head")

this was fixed

>  “You can remove the “no visible bindings for global variable” NOTE by adapting the following code
> utils::globalVariables(c(“ID”))

done - we added these calls where necessary

>  LazyData to false

done - and refactored code and vignettes to comply to this

>  Update R version to 4.3

done

>  The License is unclear (you have to fix a license it can’t be a conditional statement)

done - we just left GPL 3

## R code

>  You have some instances of sapply, we strongly suggest switching to vapply

we switched all instances of `sapply` to `vapply`

>  The 1:.. Construct can go wrong ( e.g. 1:-1) switch to seq_len, seq.int, seq_along etc.

we replaced all instances of such constructs

>  There is some uncommented code in the package - sometime its need to clarify something but commented out code mid-function is likely to be confusing

we removed commented code

>  The code is quite crowded in places - adding extra white space can help and a space after commas can be really useful
>  Try to be consistent with indenting in if statements and for loops

we considered these comments and uniformed and streamlined code style throughout the package, addressing these and other considerations

>  Please switch \dontrun in examples to \donttest to ensure they still correct syntax

we replaced all instances

>  Please check the inputs to the functions to help the user. Getting the code wrong currently leads to cryptic errors.

we added checks for all user-facing functions

## Vignette

> You have quite a lot of eval = FALSE chunks. This can be more unhelpful than helpful. If they’re too slow you consider preloading the result?

we changed most of these to `eval=TRUE` where possible and preloaded results where relevant

**Comment by ococrook** [comment]
Thanks for the changes!

I get a couple of errors when going through the vignette, which you could help me with

whenever I run `URA` I get

> "object 'DiseaseList' not found"

whenever I run RMA I get 

> Error in get("EncodePromoters") : object 'EncodePromoters' not found

do something additional need to be passed to these functions to make them work?

**Comment by mtiberti** [comment]
hi @ococrook,

thank you again,

no - these functions should work out of the box, there were a couple of `data()` calls missing in the vignette. We have now added them in. We've also retried running each code line in the vignette from the generated html file and found a couple of other issues, which we fixed - hopefully it should be fine now

More in general regarding your question, two functions (`DMA`, and `moonlight`, which internally calls `DMA`), as used in our vignette, do require a couple of data files that contain pre-computed CScape-Somatic scores. These are available on the CScape-Somatic website, as detailed in the vignette in the `DMA: Driver Mutation Analysis` section. These files take ~50GB of disk space in total.

**Comment by ococrook** [comment]
Thanks! I suspect there is some windows magic happening because:

```{r,}
dataURA <- URA(dataGRN = dataGRN,
               DEGsmatrix = DEGsmatrix,
               BPname = BPselected, 
               nCores=1)
```
gives

> Error in { : task 1 failed - "object 'DiseaseList' not found"
4: stop(simpleError(msg, call = expr))
3: e$fun(obj, substitute(ex), parent.frame(), e$data)
2: foreach(j = seq.int(tRlist), .combine = "rbind", .packages = "foreach") %dopar% 
       {
           currentTF <- as.character(tRlist[j])
           currentTF_regulon <- names(which(dataGRN$miTFGenes[currentTF, 
               ] > as.numeric(dataGRN$maxmi[currentTF])))
           currentTF_regulon <- as.matrix(currentTF_regulon)
           DEGsregulon <- intersect(rownames(DEGsmatrix), currentTF_regulon)
           if (length(DEGsregulon) > 2) {
               tabFEA <- FEA(BPname = BPname, DEGsmatrix = DEGsmatrix[DEGsregulon, 
                   ])
               return(tabFEA$Moonlight.Z.score)
           }
           else {
               return(rep(0, length(BPname)))
           }
       }
1: URA(dataGRN = dataGRN, DEGsmatrix = DEGsmatrix, BPname = BPselected, 
       nCores = 1)

It looks like it still can't find `DiseaseList` despite it being clearly loaded. I wonder whether you need to check whether `DiseaseList` is in the environment and if not call the data from inside the function? You could check this by `names(.GlobalEnv)` inside the function but I suspect that it's correctly exporting for you. There is no windows build report so I assume this is a windows only issue for the moment.

**Comment by mtiberti** [comment]
thanks, indeed we tested it on Linux (Docker container from `bioconductor:devel`) and MacOS and it was working fine. I currently don't have a Windows computer at work, I'll try and see if I can find one and test it on there, and I'll try out your idea - we do call `data` inside other functions but not in that one so that might very well be the culprit. I'll be back to you

**Comment by mtiberti** [comment]
hi @ococrook ,

just a question - to fix this problem we are adding conditional `data()` calls to our functions where applicable, this seems to work (I could test it on Windows), but we get a note, e.g.

```
* checking R code for possible problems ... [70s/76s] NOTE
Found the following calls to data() loading into the global environment:
File ‘Moonlight2R/R/DMA.R’:
  data(variable_name)
File ‘Moonlight2R/R/FEA.R’:
  data(variable_name)
...
```

our checks are like

```
    if (! variable_name %in% names(.GlobalEnv)) {
      data(variable_name)
```

so we're not just blindly loading them, just when we are not overloading pre-existing variables in the global environment. Do you think this is an acceptable compromise?

Thanks

**Comment by ococrook** [comment]
Yes! That's the best approach I think

**Comment by mtiberti** [comment]
Great! I will do a final round of tests later today and push our commits, will ping you when/if we pass checks

**Comment by mtiberti** [comment]
@ococrook thanks for your patience, I have tested the package on Windows after applying the fix you suggested and it worked fine for me, as well as doing the usual checks on Linux. We also slimmed down the examples quite a bit as we were getting a package check timeout. I think it's ready if you want to give it another go

**Comment by mtiberti** [comment]
thank you @ococrook ! We're happy the package was accepted. So now we just have to wait for the package to appear in the nightly builds and we should be done. If we need to change/add something after this step we will just push to the repo before or after release following BioC version numbering

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mtiberti.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Moonlight2R")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Moonlight2R

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
