### ISSUE TITLE
gdrplatform release [fourth package: gDRimport]

### ISSUE THREAD

**Issue by gladkia** [Bioconductor/Contributions#2997]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gdrplatform/gDRimport

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain the use of gDRimport.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
This is somewhat problematic:
```
 checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
  NB: this package now depends on R (>= 3.5.0)
  WARNING: Added dependency on R >= 3.5.0 because serialized objects in
  serialize/load version 3 cannot be read in older versions of R.
  File(s) containing such objects:
    'gDRimport/inst/extdata/data2/ref_D300_trt_Tecan_96_well_plates.RDS'
    'gDRimport/inst/extdata/data2/ref_RawData_Tecan_96_well_plates.RDS'
    'gDRimport/inst/extdata/data2/ref_manifest_Tecan_96_well_plates.RDS'
    'gDRimport/inst/extdata/data3/ref_D300_384_well_plate_example.RDS'
    'gDRimport/inst/extdata/data3/ref_D300_96_well_plate_example.RDS'
    'gDRimport/inst/extdata/data3/ref_Gnumber_D300_384_well_plate.RDS'
    'gDRimport/inst/extdata/data3/ref_Gnumber_D300_96_well_plate.RDS'
    'gDRimport/inst/extdata/data4/ref_l.RDS'
    'gDRimport/inst/extdata/pset/Tavor_2020.RDS'

```
Can you use re-build and save in R >= 4.3?  We do have a requirement that R>=4.3 be set for packages in Bioc 3.17.

**Comment by vjcitn** [comment]
Also:
```
* checking examples ... ERROR
Running examples in 'gDRimport-Ex.R' failed
The error most likely occurred in:

> ### Name: load_data
> ### Title: Load data
> ### Aliases: load_data
> 
> ### ** Examples
> 
>  td <- get_test_data()
>  l_tbl <- load_data(td$m_file, td$t_files, td$r_files)
WARN [2023-04-16 05:49:26] Header Clid in /home/stvjc/SUBMISSIONS/APR1/gDRimport.Rcheck/gDRimport/extdata/data1/manifest.xlsx corrected to Clid
Error in check_metadata_headers(corrected_names, df_name) : 
  Metadata field name: Clid in /home/stvjc/SUBMISSIONS/APR1/gDRimport.Rcheck/gDRimport/extdata/data1/manifest.xlsx is not valid (reserved for output)
Calls: load_data ... FUN -> check_metadata_names -> check_metadata_headers
Execution halted
```

**Comment by gladkia** [comment]
> Also:
> 
> ```
> * checking examples ... ERROR
> Running examples in 'gDRimport-Ex.R' failed
> The error most likely occurred in:
> 
> > ### Name: load_data
> > ### Title: Load data
> > ### Aliases: load_data
> > 
> > ### ** Examples
> > 
> >  td <- get_test_data()
> >  l_tbl <- load_data(td$m_file, td$t_files, td$r_files)
> WARN [2023-04-16 05:49:26] Header Clid in /home/stvjc/SUBMISSIONS/APR1/gDRimport.Rcheck/gDRimport/extdata/data1/manifest.xlsx corrected to Clid
> Error in check_metadata_headers(corrected_names, df_name) : 
>   Metadata field name: Clid in /home/stvjc/SUBMISSIONS/APR1/gDRimport.Rcheck/gDRimport/extdata/data1/manifest.xlsx is not valid (reserved for output)
> Calls: load_data ... FUN -> check_metadata_names -> check_metadata_headers
> Execution halted
> ```

Hi @vjcitn - please assure that you have the latest gDRtestData ([ec3f8fd004edbd5b3627f534fb06b82a0ea79150](https://github.com/gdrplatform/gDRtestData/commit/ec3f8fd004edbd5b3627f534fb06b82a0ea79150); v 0.99.3; current master).

**Comment by gladkia** [comment]
> This is somewhat problematic:
> 
> ```
>  checking for LF line-endings in source and make files and shell scripts
> * checking for empty or unneeded directories
>   NB: this package now depends on R (>= 3.5.0)
>   WARNING: Added dependency on R >= 3.5.0 because serialized objects in
>   serialize/load version 3 cannot be read in older versions of R.
>   File(s) containing such objects:
>     'gDRimport/inst/extdata/data2/ref_D300_trt_Tecan_96_well_plates.RDS'
>     'gDRimport/inst/extdata/data2/ref_RawData_Tecan_96_well_plates.RDS'
>     'gDRimport/inst/extdata/data2/ref_manifest_Tecan_96_well_plates.RDS'
>     'gDRimport/inst/extdata/data3/ref_D300_384_well_plate_example.RDS'
>     'gDRimport/inst/extdata/data3/ref_D300_96_well_plate_example.RDS'
>     'gDRimport/inst/extdata/data3/ref_Gnumber_D300_384_well_plate.RDS'
>     'gDRimport/inst/extdata/data3/ref_Gnumber_D300_96_well_plate.RDS'
>     'gDRimport/inst/extdata/data4/ref_l.RDS'
>     'gDRimport/inst/extdata/pset/Tavor_2020.RDS'
> ```
> 
> Can you use re-build and save in R >= 4.3? We do have a requirement that R>=4.3 be set for packages in Bioc 3.17.

Would it be possible to switch to R >= 4.2 instead of R >= 4.3? We need to support internally 4.2 as well.

Unfortunately, I still can't rebuild any package except for the gDRstyle.
```
gladkia@gladkia-UHMD6M /tmp % LANG=en_US.utf8 git clone git@git.bioconductor.org:packages/gDRstyle.git
Cloning into 'gDRstyle'...
remote: Enumerating objects: 1449, done.
remote: Counting objects: 100% (1449/1449), done.
remote: Compressing objects: 100% (655/655), done.
remote: Total 1449 (delta 772), reused 1336 (delta 701), pack-reused 0
Receiving objects: 100% (1449/1449), 191.97 KiB | 166.00 KiB/s, done.
Resolving deltas: 100% (772/772), done.

gladkia@gladkia-UHMD6M /tmp % LANG=en_US.utf8 git clone git@git.bioconductor.org:packages/gDRimport.git
Cloning into 'gDRimport'...
FATAL: R any packages/gDRimport gladkia DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by vjcitn** [comment]
Please read your vignette.  Much of it looks like
```
r_df <- load_results(result_path(td1))
## INFO [2023-04-20 14:37:58] Reading file /home/stvjc/R/x86_64-pc-linux-gnu-library/4.3/gDRimport/extdata/data1/RawData_day0.xlsx, sheet Readout_0077vs0068_day7
## New names:
## • `` -> `...1`
## • `` -> `...2`
## • `` -> `...3`
## • `` -> `...4`
## • `` -> `...5`
## • `` -> `...6`
## • `` -> `...7`
## • `` -> `...8`
## • `` -> `...9`
## • `` -> `...10`
## • `` -> `...11`
## • `` -> `...12`
## • `` -> `...13`
## • `` -> `...14`
## • `` -> `...15`
## • `` -> `...16`
## • `` -> `...17`
## • `` -> `...18`
## • `` -> `...19`
## • `` -> `...20`
## • `` -> `...21`
## • `` -> `...22`
## • `` -> `...23`
## • `` -> `...24`
## • `` -> `...25`
```
The vignette is supposed to narrate the purpose and use of the package.  It does not need to exhibit all types of I/O that a user might encounter.

**Comment by gladkia** [comment]
@vjcitn fixed.

**Comment by gladkia** [comment]
@vjcitn fixed.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/gladkia.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gDRimport")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gDRimport

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
