### ISSUE TITLE
(inactive) CAMPP2

### ISSUE THREAD

**Issue by mtiberti** [Bioconductor/Contributions#2999]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ELELAB/CAMPP2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```
--- re-building ‘vignette_campp2.Rmd’ using rmarkdown
Quitting from lines 261-262 (vignette_campp2.Rmd) 
Error: processing vignette 'vignette_campp2.Rmd' failed with diagnostics:
package or namespace load failed for 'CAMPP2':
 object 'predict' is not exported by 'namespace:randomForest'
--- failed re-building ‘vignette_campp2.Rmd’

```

**Comment by mtiberti** [comment]
thanks @vjcitn - I should have fixed that in the `CAMPP2` master. I can't quite explain that before this change it built/checked correctly on my system (I'm using a slightly modified version of the BioC devel Docker image). After this change, I have redone `R CMD build`, `R CMD check`, `BiocCheck::BiocCheck()` and they all end without warnings or errors. I've also tried `devtools::build_vignettes()` for good measure.

Can you try again now? Or if it errors out again, if you can please tell me you are exactly doing so I can reproduce the problem. Thank you.

**Comment by HelenaLC** [comment]
Before getting into an in-depth review, I notice that the majority of functions operates on a `data.frame` of measurement data or abundances. Meanwhile, there is a lot of existing infrastructure for the types of analyses (e.g., dimension reduction, aggregation, clustering, etc.). Bioconductor places a strong emphasis on re-use of code and classes where it makes sense, which I think it does here. Namely, why not use the `SummarizedExperiment` at the center of it all?

**Comment by mtiberti** [comment]
thank you @HelenaLC ! Your point definitely makes sense, just a couple of comments:

1. I'm just a bit dubious whether this would be as easy/straightforward to use for people not as much into coding, i.e. if they would need to create a `SummarizedExperiment` object starting from their data and then proceed with the analyses they need. This is especially as the package is designed to be used by people with relatively small experience in bioinformatics/coding and possibly without too much tweaking
2. I'm a bit worried about the timeframe, since we're trying to get the package out with 3.17, it sound like this would require quite a bit of refactoring (+ regular code review of course)

Do you think it would make sense to do this switch after the package is reviewed and (hopefully) included in BioC or do you see this as a necessary step before further review?

Many thanks in either case!

**Comment by vjcitn** [comment]
"I'm just a bit dubious whether this would be as easy/straightforward to use for people not as much into coding" -- Hi @mtiberti !   We've been creating code used by all bioinformaticians worldwide for 20 years now.  The value of self-describing, coherently linked data structures for assay+sample metadata (colData)+feature metadata (rowData and rowRanges) may not be apparent to folks who are not much into coding, and those folks are free to do what they like.  But the value of an ecosystem with highly self-descriptive data structures is definitely compromised when packages come in that don't participate in the framework.  So please consider how you and your users can take advantage of Bioconductor infrastructure, if you want to be reviewed and distributed in Bioconductor.  Packages that operate on data frames can be managed and distributed by other avenues.  Thanks for your submission!

**Comment by lshep** [comment]
In our experience if it doesn't happen in the review it doesn't happen. 

SummaizedExperiment is fairly easy to construct and has many benefits that help naive users. The easiest example is filtering and subsetting.  A user would have to match and filter each individual data.frame while subsetting a SummarizedExperiment object would do this for all data present on the object. 

From that point of view too, when I worked through some of the vignette to try to see the data, I ended up with over a dozen data frame in my R session. This is overwhelming and unwieldy. 

I also did not do a full in depth review but on a quick glance through the vignette some other issues: 

- [ ] You should not default write to a working directory. Please use a tempdir()
- [ ] This section does not work. Please review how to load data in R 
```
load("./data/campp2_brca_1.rda")
load("./data/campp2_brca_1_meta.rda")
load("./data/campp2_brca_2.rda")
load("./data/campp2_brca_2_meta.rda")
```
- [ ] I also suggest having your plotting functions show in a viewing window/interactively rather than save directly. Users will likely want to view/preview plots before saving them.

**Comment by mtiberti** [comment]
got it - thank you for your insights @vjcitn and @lshep. We'll refactor the package to use Bioconductor data structures (such as `SummarizedExperiments`) and fix the other issues that you pointed out. We'll be back to you as soon as possible

**Comment by lshep** [comment]
How is the refactoring coming?  May we expect updates soon or should we close this for now?
