### ISSUE TITLE
gdrplatform release [fifth package: gDRcore]

### ISSUE THREAD

**Issue by bczech** [Bioconductor/Contributions#3003]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gdrplatform/gDRcore

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of gDRcore.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
i updated all sources, still
```
* checking dependencies in R code ... WARNING
'loadNamespace' or 'requireNamespace' call not declared from: ‘gDRinternalData’
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ... ERROR
Running examples in 'gDRcore-Ex.R' failed
The error most likely occurred in:

> ### Name: convert_mae_to_raw_data
> ### Title: Transform mae into raw data
> ### Aliases: convert_mae_to_raw_data
> 
> ### ** Examples
> 
> mae <- get_synthetic_data("finalMAE_small.RDS")
Error in get_synthetic_data("finalMAE_small.RDS") :
could not find function "get_synthetic_data"
```

```
commit 5ff49eab65e766cb03fcceaa21dc95d795d9fe3a (HEAD -> master, origin/master, origin/HEAD)
Merge: 7abac1a 7d59f92
Author: gladkia <41166437+gladkia@users.noreply.github.com>
Date:   Sat Apr 15 16:51:56 2023 +0200

    Merge pull request #68 from gdrplatform/GDR-1919_2
    
    Gdr 1919 2

commit 7d59f92e6cb30d61563df122b68bcf50072107a4
Author: Arkadiusz Gladki <arkadiusz.gladki@contractors.roche.com>
Date:   Sat Apr 15 15:45:16 2023 +0200

    bugfix: move .clear_rownames to prepare_input step

```

**Comment by gladkia** [comment]
Hi @vjcitn,
Thanks! Fixed. 

Please assure that you have the latest gDRtestData (https://github.com/gdrplatform/gDRtestData/commit/4a32e86749ca455d8c5fa98a8aeb5f46c8822e5b; v 0.99.4; current master) and gDRimport (https://github.com/gdrplatform/gDRimport/commit/61afe11980ae59d8fb0bf86d25d1ebd5bb5b8236); v 0.99.4; current main).

**Comment by vjcitn** [comment]
7d59f92 still has
```
* checking examples ... ERROR
Running examples in 'gDRcore-Ex.R' failed
The error most likely occurred in:

> ### Name: convert_mae_to_raw_data
> ### Title: Transform mae into raw data
> ### Aliases: convert_mae_to_raw_data
> 
> ### ** Examples
> 
> mae <- get_synthetic_data("finalMAE_small.RDS")
Error in get_synthetic_data("finalMAE_small.RDS") : 
```

**Comment by vjcitn** [comment]
could not find function "get_synthetic_data"

**Comment by vjcitn** [comment]
hold on a minute.

**Comment by vjcitn** [comment]
```
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  10/12 mismatches (average diff: 214421)
  [2]   55913 -  61367 ==   -5454
  [3]   61367 - 159394 ==  -98027
  [4]   14426 - 455904 == -441478
  [5]  159394 -  54833 ==  104561
  [6]   34391 - 146833 == -112442
  [7]  455904 -  55913 ==  399991
  [8]  455901 -  14426 ==  441475
  [9]   54833 -  34391 ==   20442
  [10]  41199 - 455901 == -414702
  ...

  [ FAIL 1 | WARN 0 | SKIP 0 | PASS 183 ]
  Error: Test failures
  Execution halted
```
```
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/APR1/gDRcore/FOO/gDRcore$ git remote -v
origin	git@git.bioconductor.org:packages/gDRcore (fetch)
origin	git@git.bioconductor.org:packages/gDRcore (push)
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/APR1/gDRcore/FOO/gDRcore$ git log |head -5
commit e573ad8640674d0fca7cc24d3cbfb831c978e718
Merge: 4df322e e279b9f
Author: gladkia <41166437+gladkia@users.noreply.github.com>
Date:   Mon Apr 17 14:37:07 2023 +0200
```
give me an email when you think the git.bioconductor.org package images are synchronized and should pass check, regardless of what the single-package builder
 results are.   stvjc@channing.harvard.edu

**Comment by gladkia** [comment]
> ```
> Running the tests in 'tests/testthat.R' failed.
> Last 13 lines of output:
>   10/12 mismatches (average diff: 214421)
>   [2]   55913 -  61367 ==   -5454
>   [3]   61367 - 159394 ==  -98027
>   [4]   14426 - 455904 == -441478
>   [5]  159394 -  54833 ==  104561
>   [6]   34391 - 146833 == -112442
>   [7]  455904 -  55913 ==  399991
>   [8]  455901 -  14426 ==  441475
>   [9]   54833 -  34391 ==   20442
>   [10]  41199 - 455901 == -414702
>   ...
> 
>   [ FAIL 1 | WARN 0 | SKIP 0 | PASS 183 ]
>   Error: Test failures
>   Execution halted
> ```
> 
> ```
> stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/APR1/gDRcore/FOO/gDRcore$ git remote -v
> origin	git@git.bioconductor.org:packages/gDRcore (fetch)
> origin	git@git.bioconductor.org:packages/gDRcore (push)
> stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/APR1/gDRcore/FOO/gDRcore$ git log |head -5
> commit e573ad8640674d0fca7cc24d3cbfb831c978e718
> Merge: 4df322e e279b9f
> Author: gladkia <41166437+gladkia@users.noreply.github.com>
> Date:   Mon Apr 17 14:37:07 2023 +0200
> ```
> 
> give me an email when you think the git.bioconductor.org package images are synchronized and should pass check, regardless of what the single-package builder results are. [stvjc@channing.harvard.edu](mailto:stvjc@channing.harvard.edu)

@vjcitn, fixed (and an email sent as well).

**Comment by vjcitn** [comment]
```
* checking dependencies in R code ... WARNING
'loadNamespace' or 'requireNamespace' call not declared from: ‘gDRinternalData’
```
a concern?

**Comment by gladkia** [comment]
I think not. 
gDRcore supports two scenarios for fetching the annotations for drugs and cell lines. In the first scenario (internal use)  the annotations are fetched gDRinternalData. In the second scenario (public use) the annotations are fetched from the (publicly available) gDRtestData. Please find the key code chunks in the [link1](https://github.com/gdrplatform/gDRcore/blob/ef65420671361543cb81d50e62e37546b7c8ca37/R/add_annotation.R#L42-L45) and [link2](https://github.com/gdrplatform/gDRcore/blob/ef65420671361543cb81d50e62e37546b7c8ca37/R/add_annotation.R#L136-L140).

**Comment by gladkia** [comment]
Hi @vjcitn,

Thanks for your current support! 
FYI, we've just fixed all the warnings and errors in gDRcore. The review should be much simpler now (hopefully).
Thanks in advance.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bczech.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gDRcore")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gDRcore

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
