### ISSUE TITLE
gdrplatform release [sixth package: gDR]

### ISSUE THREAD

**Issue by gladkia** [Bioconductor/Contributions#3004]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gdrplatform/gDR

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of gDR.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```
--- re-building ‘gDR.Rmd’ using knitr
Quitting from lines 95-98 (gDR.Rmd) 
Error: processing vignette 'gDR.Rmd' failed with diagnostics:
'length = 3840' in coercion to 'logical(1)'
--- failed re-building ‘gDR.Rmd’
```

**Comment by gladkia** [comment]
@vjcitn thanks - we will merge the bugfix soon (https://github.com/gdrplatform/gDRcore/pull/62).

**Comment by gladkia** [comment]
@vjcitn fixed.

**Comment by gladkia** [comment]
Hi @vjcitn and  @lshep, 

I would like to push the latest changes to `git@git.bioconductor.org:packages/gDR.git` but I'm getting: 

```
gladkia@gladkia-UHMD6M /tmp % git clone git@git.bioconductor.org:packages/gDR.git        
Cloning into 'gDR'...
FATAL: R any packages/gDR gladkia DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I see the same issue for other packages, submitted as candidates for the 3.17 release, on which gDR depends (gDRcore, gDRutils, gDRimport, gDRtestData). How to solve it? 

Thanks in advance for your help!

Best,
Arek

**Comment by vjcitn** [comment]
I don't think we are using git.bioconductor.org yet ... the package is not far enough along.  we are working from your github.  And finding 
```
* checking dependencies in R code ... WARNING
'loadNamespace' or 'requireNamespace' call not declared from: ‘gDRinternalData’
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ... ERROR
Running examples in 'gDRcore-Ex.R' failed
The error most likely occurred in:

> ### Name: convert_mae_to_raw_data
> ### Title: Transform mae into raw data
> ### Aliases: convert_mae_to_raw_data
> 
> ### ** Examples
> 
> mae <- get_synthetic_data("finalMAE_small.RDS")
Error in get_synthetic_data("finalMAE_small.RDS") : 
  could not find function "get_synthetic_data"
Execution halted
```
Please sync all your packages to a consistent state in your github and ensure that they will pass check.

**Comment by vjcitn** [comment]
building gDR fails
```
* checking for file 'gDR/DESCRIPTION' ... OK
* preparing 'gDR':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘gDR.Rmd’ using knitr
Quitting from lines 113-121 (gDR.Rmd) 
Error: processing vignette 'gDR.Rmd' failed with diagnostics:
subscript contains invalid names
--- failed re-building ‘gDR.Rmd’

SUMMARY: processing the following file failed:
  ‘gDR.Rmd’
```

```
 sessionInfo()
R Under development (unstable) (2023-03-18 r84003)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS:   /home/stvjc/R-43dev-dist/lib/R/lib/libRblas.so 
LAPACK: /home/stvjc/R-43dev-dist/lib/R/lib/libRlapack.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/New_York
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gDR_0.99.3       gDRutils_0.99.4  gDRimport_0.99.3 gDRcore_0.99.3  
[5] rmarkdown_2.21  

loaded via a namespace (and not attached):
 [1] Matrix_1.5-4                compiler_4.3.0             
 [3] SummarizedExperiment_1.29.1 Biobase_2.59.0             
 [5] GenomicRanges_1.51.4        bitops_1.0-7               
 [7] IRanges_2.33.1              fastmap_1.1.1              
 [9] lattice_0.21-8              XVector_0.39.0             
[11] GenomeInfoDb_1.35.16        knitr_1.42                 
[13] BiocGenerics_0.45.3         backports_1.4.1            
[15] DelayedArray_0.25.0         checkmate_2.1.0            
[17] tibble_3.2.1                MatrixGenerics_1.11.1      
[19] GenomeInfoDbData_1.2.10     pillar_1.9.0               
[21] rlang_1.1.0                 utf8_1.2.3                 
[23] xfun_0.38                   cli_3.6.1                  
[25] magrittr_2.0.3              zlibbioc_1.45.0            
[27] grid_4.3.0                  digest_0.6.31              
[29] lifecycle_1.0.3             S4Vectors_0.37.5           
[31] vctrs_0.6.1                 startup_0.20.0             
[33] evaluate_0.20               glue_1.6.2                 
[35] data.table_1.14.8           stats4_4.3.0               
[37] RCurl_1.98-1.12             fansi_1.0.4                
[39] matrixStats_0.63.0          tools_4.3.0                
[41] pkgconfig_2.0.3             htmltools_0.5.5  
```

**Comment by vjcitn** [comment]
I am going to pass the pre-check so that the build system reports are directly addressible by you.  I would not begin reviewing until you get to a WARNINGS state.

**Comment by gladkia** [comment]
@vjcitn, thanks!  Can you please give me some hints on how to trigger the build system reports?

**Comment by gladkia** [comment]
@vjcitn, FYI, the error in the gDR vignette has just been fixed.

**Comment by vjcitn** [comment]
```
td <- get_test_data()
td$m_file
[1] “/home/stvjc/R/x86_64-pc-linux-gnu-library/4.3/gDRimport/extdata/data1/manifest.xlsx”

td$t_files
[1] “/home/stvjc/R/x86_64-pc-linux-gnu-library/4.3/gDRimport/extdata/data1/Template_7daytreated.xlsx” [2] “/home/stvjc/R/x86_64-pc-linux-gnu-library/4.3/gDRimport/extdata/data1/Template_Untreated.xlsx”
```
This is quite unpleasant, in the vignette.  You should define an object class that manages the paths, with methods that
can use them.  You don't have to use S4 but it is recommended.

**Comment by gladkia** [comment]
> ```
> td <- get_test_data()
> td$m_file
> [1] “/home/stvjc/R/x86_64-pc-linux-gnu-library/4.3/gDRimport/extdata/data1/manifest.xlsx”
> 
> td$t_files
> [1] “/home/stvjc/R/x86_64-pc-linux-gnu-library/4.3/gDRimport/extdata/data1/Template_7daytreated.xlsx” [2] “/home/stvjc/R/x86_64-pc-linux-gnu-library/4.3/gDRimport/extdata/data1/Template_Untreated.xlsx”
> ```
> 
> This is quite unpleasant, in the vignette. You should define an object class that manages the paths, with methods that can use them. You don't have to use S4 but it is recommended.

Hi,
We've just merged the PRs with the suggested solution (https://github.com/gdrplatform/gDR/pull/28, https://github.com/gdrplatform/gDRcore/pull/75 and https://github.com/gdrplatform/gDRimport/pull/42).

**Comment by gladkia** [comment]
Hi, @vjcitn and @lshep
Thanks in advance for the feedback regarding the current status.

**Comment by vjcitn** [comment]
are you bumping version numbers to get new builds?

**Comment by gladkia** [comment]
Hi,

No just to assure all dependencies are up-to-date.

Best,
Arek

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/gladkia.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gDR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gDR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
