### ISSUE TITLE
GRETTA

### ISSUE THREAD

**Issue by ytakemon** [Bioconductor/Contributions#3011]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ytakemon/GRETTA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by ytakemon** [comment]
Hello, This submission is part of a manuscript revision for a journal, and our deadline is the end of May. Would it be possible to have my tool reviewed as soon?

**Comment by vjcitn** [comment]
in your  vignette you have
```
## Path to data to pre-processed data
gretta_data_dir <- "/projects/marralab/ytakemon_prj/DepMap/GRETTA_data/22Q2/data/"
gretta_output_dir <- "/projects/marralab/ytakemon_prj/DepMap/GRETTA_troubleshooting/"
```
there is no way this can work, it involves code specific to your machine.  Please verify that your package can be installed, pass R CMD check, pass BiocCheck, on a completely clean machine and let us know when this has occurred.

**Comment by ytakemon** [comment]
Hi @vjcitn ,

The purpose of my package is to be able to process publicly available data, and this data (~11 Gb) is required to be downloaded separately (~11 Gb, see below) for the tutorial on the vignette to process.  I saw there is a limit to the size of a Bioconductor package, so I wasn't quite sure how to achieve this without linking to an external path. Do you have any suggestions?

```
# Make a new directory/folder called GRETTA_project and go into directory
mkdir GRETTA_project
cd GRETTA_project

# Download data from the web
wget https://www.bcgsc.ca/downloads/ytakemon/GRETTA/22Q2/GRETTA_DepMap_22Q2_data.tar.gz

# Extract data and data documentation
tar -zxvf GRETTA_DepMap_22Q2_data.tar.gz
```

**Comment by vjcitn** [comment]
We can have packages that *work with* large data bundles but neither the submissions or the checking themselves should require the large bundle.  Can't you produce an extract that is of modest size that accomplishes the testing and demonstration of the package, leaving it up to the user to obtain the large bundle when required for the user's work?

**Comment by vjcitn** [comment]
If the bundle is made available BiocFileCache should be used to manage its storage and retrieval for the user.

**Comment by ytakemon** [comment]
Thank you for the suggestion. I will see how small I can make this test data bundle and will push an update soon.

**Comment by ytakemon** [comment]
Please take another look @vjcitn. I've generated a small bundle, as you suggested. This bundle is now used by both the vignette, examples, and tests.

**Comment by vjcitn** [comment]
Still does not run out of the box
```
> ### Name: get_GeneNameID
> ### Title: Get unique DepMap-compatible gene IDs
> ### Aliases: get_GeneNameID get_DepMapID
> 
> ### ** Examples
> 
> gretta_data_dir <- '/projects/marralab/ytakemon_prj/DepMap/GRETTA_data/22Q2/data'
> 
> get_GeneNameID('A1CF', data_dir = gretta_data_dir)
Error in get_GeneNameID("A1CF", data_dir = gretta_data_dir) : 
  DepMap data directory does not exists. Please check again and provide the full path to the DepMap data directory.
```
git:
```
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS/MAY16/GRETTA$ git log |head
commit 4821cd82d0bc77b75a7989fc296333a4244f2fb1
Author: ytakemon <yuka.takemon@gmail.com>
Date:   Sat May 20 18:42:52 2023 -0700

    v0.99.1 to fix paths for bioconductor pre-check

```

**Comment by ytakemon** [comment]
Thanks for your patients. This is my first time creating an R package. I've now tried running examples and checks on another device, and this time GRETTA should run out of the box. Please check again.

**Comment by Kayla-Morrell** [comment]
@ytakemon - Just checking it to see what the status of this package is. If no progress is made to fix the errors within the next couple of weeks I will have to close the issue due to inactivity.

Best,
Kayla

**Comment by ytakemon** [comment]
Hi @Kayla-Morrell , the build report link leads to a "Page not found" site. Is there another way for me to see what is causing the issue?

**Comment by lshep** [comment]
http://staging.bioconductor.org:8000/job/19188/

**Comment by ytakemon** [comment]
I see that the builds show warnings due to "WARNING: directory GRETTA/man/figures is empty". However, these are figures that are useful to illustrate how the package works in the README page. Could I get some advice on how to deal with this?

**Comment by Kayla-Morrell** [comment]
@ytakemon - I would suggest moving these figures into an 'inst/figures/' directory and access them from there. Usually the man page directories should only contain the man pages, nothing else.

**Comment by ytakemon** [comment]
Hi @Kayla-Morrell, Thank you for your suggestion. I've moved the figures into "inst/figures". However, the build shows a warning indicating that the directory is empty, but 3 .png files should be contained. I can see them on my own repo and .png isn't part of the .gitignore file either, so I am not quite sure why this is occuring. Do you have any suggestions for how I can resolve this?

**Comment by Kayla-Morrell** [comment]
@ytakemon - I'm not sure how to fix this warning, but I can ask others on the team. I can do my review based on the current state of the package since there are no ERRORs. I'll have the review posted in the next couple of days.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@ytakemon - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: The Installation sections in the README files should include
  Bioconductor installation instructions (using BiocManager). For the .Rmd file,
the installation instructions should be in an `eval = FALSE` code chunk.
- [ ] SUGGESTION: Since you are using a standard license, it's not necessary to
  include the LICENSE.md file within the package.
- [ ] REQUIRED: There are some things included in the package that aren't
  standard practice for a Bioconductor package. The 'DepMap_data_versions' and
'Singularity' directories should be removed unless you can justify keeping them.
- [ ] SUGGESTION: I would move the 'GRETTA_hex_logo-02.png' to the
  'inst/figures/' directory.
- [ ] REQUIRED: The DepMap data is readily available for use via the ExperimentHub
  package [depmap](https://bioconductor.org/packages/devel/data/experiment/html/depmap.html).
  I would look at getting data from here instead of downloading the data, especially since
  it's quite large.

## DESCRIPTION

- [ ] REQUIRED: Update R version dependency from 4.2.0 to 4.3.0.

## NAMESPACE

- [ ] REQUIRED: There shouldn't be a need to export `%>%`. 

## Vignette

- [ ] REQUIRED: R code blocks should not include `eval = FALSE` unless it's an
  Installation section. 
- [ ] REQUIRED: The Installation section should demonstrate how to install the
  package from Bioconductor, not github.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to the main functions. Users should be able to have a
relevant page display with `?GRETTA`.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@ytakemon - Just checking in to see the status of this submission. The deadline for accepting new packages into the Bioconductor 3.18 release is 10/18/23. Any packages accepted after this date will be included in the next release.

Best,
Kayla

**Comment by ytakemon** [comment]
Hi @Kayla-Morrell, Sorry I am currently trying to write my up PhD thesis and won't be able to address them in the next two days. When is the next release planned? I will aim to address them by then.

**Comment by Kayla-Morrell** [comment]
@ytakemon - No worries, the next release will be roughly 6 months from now.

**Comment by lshep** [comment]
@ytakemon  should we close this issue until you are ready to make updates?

**Comment by ytakemon** [comment]
Sure that would be fine. thanks
