### ISSUE TITLE
decontX

### ISSUE THREAD

**Issue by yuan-yin-truly** [Bioconductor/Contributions#3020]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/campbio/decontX

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Do you know what is going on here?:
```
Quitting from lines 63-69 (decontX.Rmd) 
Error: processing vignette 'decontX.Rmd' failed with diagnostics:
no method or default for coercing "DelayedMatrix" to "SVT_SparseArray"
--- failed re-building ‘decontX.Rmd’

```

**Comment by yuan-yin-truly** [comment]
Hi @vjcitn, thank you for your help! I think it has to do with package TENxPBMCData not installed in your system. This package is currently listed under Suggests in the DESCRIPTION file. Could you try installing TENxPBMCData (https://bioconductor.org/packages/release/data/experiment/html/TENxPBMCData.html) and rebuild vignette?

**Comment by jianhong** [comment]
# Package 'decontX' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. It is in pretty good shape. And it is a complex package. I will leave comments for multiple times. But before my next comments, please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.
## The DESCRIPTION file
- [ ] Important: R version should be no less than 4.3
- [ ] Important: At least three sentences in Description.
## The NAMESPACE file
- [ ] Note: Function names use `camelCase` or `snake_case` and do not include `.`.
	* in line 3 export("decontXcounts<-")
	* in line 13 exportMethods("decontXcounts<-")
## General package development
- [ ] FYI: I am not sure Seurat will fix this issue or not. This is not related to this package.
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)

## R code
- [ ] NOTE: no direct slot access with `@` or `slot()` - accessors implemented and used.
	* In file R/stan_helpers.R:
		+ at line 28 found '  val <- stan_vb_output@sim$est'
- [ ] Important: `vapply` instead of `sapply`.
	* In file R/stanmodels.R:
		+ at line 10 found 'stanmodels <- sapply(stanmodels, function(model_name) {'
- [ ] Important: No `paste` in `message()`, `message`, `stop`
	* In file R/celda_functions.R:
		+ at line 19 found '      message(paste(..., sep = sep))'
- [ ] Note: Will it better to use `writeLines` instead of `cat`?
	* In file R/celda_functions.R:
		+ at line 14 found '      cat(paste(..., "\n", sep = sep),'
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
- [ ] NOTE: `1:n` is not suggested in source code. Use `seq_along` or `seq.int` instead.
	* In file R/plot_decontPro.R:
		+ at line 53 found '                                  breaks = c(1, 5, 10 ^ (1:4))) +'
		+ at line 162 found '                                  breaks = c(1, 5, 10 ^ (1:4))) +'
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/celda_functions.R:
		+ at line 111 found '    for (i in seq_along(features)) {'
	* In file R/decon.R:
		+ at line 184 found '    for (i in batchIndex) {'
		+ at line 430 found '  for (bat in batchIndex) {'
		+ at line 1340 found '  for (i in seq(K)) {'
		+ at line 1343 found '    for (j in setdiff(seq(K), i)) {'
		+ at line 1359 found '  for (i in seq(K)) {'
	* In file R/plot_decontPro.R:
		+ at line 38 found '  for (i in seq_along(features)) {'
		+ at line 140 found '  for (i in seq_along(features)) {'
	* In file R/plot_decontx.R:
		+ at line 192 found '    for (i in seq_along(assayName)) {'
		+ at line 365 found '    for (i in seq_along(assayName)) {'
		+ at line 506 found '    for (i in seq_along(groupClusters)) {'
- [ ] Important: Remove unused code.
	* In file R/decon.R:
		+ at line 654 found '  # nG <- nrow(counts)'
		+ at line 851 found '  # ll = sum( t(counts) * log( (1-conP )*geneDist[z,] + conP * conDist[z, ] +'
		+ at line 852 found '  # 1e-20 ) )  # when dist_mat are K x G matrices'
		+ at line 864 found '  # ll <- sum(t(counts) * log(theta * t(cellDist) +'
		+ at line 865 found '  #        (1 - theta) * t(bgDist) + 1e-20))'
- [ ] Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.
	* In file R/celda_functions.R:
		+ at line 97 found '      search <- SummarizedExperiment::rowData(x)[, by]'
		+ at line 102 found '      search <- x[, by]'
	* In file R/decon.R:
		+ at line 189 found '      tempUMAP[result$runParams$batch == i, ] <- result$estimates[[i]]$UMAP'
		+ at line 452 found '    countsBat <- counts[, batch == bat]'
		+ at line 453 found '    bgBat <- countsBackground[, batchBackground == bat]'
		+ at line 540 found '    estRmat <- estRmat[, !(allCol %in% subCol)]'
		+ at line 544 found '    estRmat <- estRmat[, allCol]'
		+ at line 853 found '  ll <- sum(Matrix::t(counts) * log(theta * t(phi)[z, ] +'
		+ at line 854 found '    (1 - theta) * t(eta)[z, ] + 1e-20))'
		+ at line 866 found '  ll <- sum(t(counts) * log(theta * t(phi)[cbZ, ] +'
		+ at line 867 found '    (1 - theta) * t(eta)[globalZ, ] + 1e-20))'
		+ at line 889 found '  logPr <- log(t(phi)[z, ] + 1e-20) + log(theta + 1e-20)'
		+ at line 890 found '  logPc <- log(t(eta)[z, ] + 1e-20) + log(1 - theta + 1e-20)'
		+ at line 932 found '    logPr <- log(t(phi)[cbZ, ] + 1e-20) + log(theta + 1e-20)'
		+ at line 934 found '      log(t(eta)[globalZ, ] + 1e-20) + log(1 - theta + 1e-20)'
		+ at line 1342 found '    phi[i, ix] <- max(phi[i, ])'
		+ at line 1344 found '      phi[j, ix] <- 0'
		+ at line 1351 found '    stats::rmultinom(1, size = rNbyC[i], prob = phi[z[i], ])'
		+ at line 1370 found '    stats::rmultinom(1, size = cNbyC[i], prob = eta[, z[i]])'
	* In file R/plot_decontPro.R:
		+ at line 42 found '    df <- data.frame(con = counts[feature, ],'
		+ at line 43 found '                     decon = decontaminated_counts[feature, ])'
		+ at line 145 found '      con = counts[feature, ],'
		+ at line 146 found '      decon = decontaminated_counts[feature, ],'
	* In file R/plot_decontx.R:
		+ at line 60 found '  df <- df[!naIx, ]'
		+ at line 212 found '    counts <- x[geneMarkerIndex, ]'
		+ at line 383 found '    counts <- x[geneMarkerIndex, ]'
		+ at line 468 found '    z <- SummarizedExperiment::colData(x)[, z]'
		+ at line 511 found '    x <- x[, !na.ix]'
	* In file R/stan_helpers.R:
		+ at line 72 found '  unscaled_rates <- t(r_est[dat$cell_type, ])'
- [ ] NOTE: Functional programming: code repetition.
	* repetition in `.cDCalcEMbgDecontamination` and `.cDCalcEMDecontamination`
		+ in .cDCalcEMbgDecontamination
			- line 17:        phi <- celda::normalizeCounts(phiUnnormalized, normalize = "proportion", 
			- line 18:            pseudocountNormalize = 1e-20)
			- line 19:        eta <- celda::normalizeCounts(etaUnnormalized, normalize = "proportion", 
			- line 20:            pseudocountNormalize = 1e-20)
			- line 21:        return(list(estRmat = estRmat, theta = theta, phi = phi, 
			- line 22:            eta = eta, delta = deltaV2))
		+ in .cDCalcEMDecontamination
			- line 18:        phi <- celda::normalizeCounts(rnGByK, normalize = "proportion", 
			- line 19:            pseudocountNormalize = 1e-20)
			- line 20:        eta <- celda::normalizeCounts(cnGByK, normalize = "proportion", 
			- line 21:            pseudocountNormalize = 1e-20)
			- line 22:        return(list(estRmat = estRmat, theta = theta, phi = phi, 
			- line 23:            eta = eta, delta = deltaV2))
	* repetition in `.colSumByGroupInteger` and `.colSumByGroupNumeric`
		+ in .colSumByGroupInteger
			- line 1:    group, K) 
			- line 2:{
			- line 3:    group <- factor(group, levels = seq(K))
			- line 4:    res <- .Call("_colSumByGroup", x, group)
			- line 5:    return(res)
		+ in .colSumByGroupNumeric
			- line 1:    group, K) 
			- line 2:{
			- line 3:    group <- factor(group, levels = seq(K))
			- line 4:    res <- .Call("_colSumByGroup_numeric", x, group)
			- line 5:    return(res)
	* repetition in `plotDecontXMarkerExpression` and `plotDecontXMarkerPercentage`
		+ in plotDecontXMarkerExpression
			- line 5:        legend <- "none"
			- line 6:        temp <- .processPlotDecontXMarkerInupt(x = x, z = z, 
			- line 7:            markers = markers, groupClusters = groupClusters, 
			- line 8:            by = by, exactMatch = exactMatch)
			- line 9:        x <- temp$x
			- line 10:        z <- temp$z
			- line 11:        geneMarkerIndex <- temp$geneMarkerIndex
			- line 12:        groupClusters <- temp$groupClusters
			- line 13:        xlab <- temp$xlab
			- line 14:        if (inherits(x, "SingleCellExperiment")) {
			- line 15:            df.list <- list()
			- line 16:            for (i in seq_along(assayName)) {
			- line 17:                counts <- SummarizedExperiment::assay(x[geneMarkerIndex, 
			- line 18:                  ], assayName[i])
			- line 25:            if (length(assayName) > 1) {
			- line 26:                legend <- "right"
			- line 27:            }
			- line 28:        }
			- line 29:        else {
			- line 30:            counts <- x[geneMarkerIndex, ]
		+ in plotDecontXMarkerPercentage
			- line 10:        }
			- line 11:        temp <- .processPlotDecontXMarkerInupt(x = x, z = z, 
			- line 12:            markers = markers, groupClusters = groupClusters, 
			- line 13:            by = by, exactMatch = exactMatch)
			- line 14:        x <- temp$x
			- line 15:        z <- temp$z
			- line 16:        geneMarkerIndex <- temp$geneMarkerIndex
			- line 17:        geneMarkerCellTypeIndex <- temp$geneMarkerCellTypeIndex
			- line 18:        groupClusters <- temp$groupClusters
			- line 19:        xlab <- temp$xlab
			- line 20:        if (inherits(x, "SingleCellExperiment")) {
			- line 21:            df.list <- list()
			- line 22:            for (i in seq_along(assayName)) {
			- line 23:                counts <- SummarizedExperiment::assay(x[geneMarkerIndex, 
			- line 24:                  ], assayName[i])
			- line 31:            if (length(assayName) > 1) {
			- line 32:                legend <- "right"
			- line 33:            }
			- line 34:        }
			- line 35:        else {
			- line 36:            counts <- x[geneMarkerIndex, ]
## Documentation
- [ ] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/decontPro.Rmd
	* rmd file vignettes/decontX.Rmd
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/decontPro.Rmd
	* rmd file vignettes/decontX.Rmd
- [ ] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/decontPro.Rmd
	* rmd file vignettes/decontX.Rmd
- [ ] To avoid the '* NOTE: Consider adding runnable examples to man pages that document exported objects.' in BiocCheck, could you please add runnable examples to
			- decontXcounts.Rd
- [ ] NOTE: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements.

**Comment by yuan-yin-truly** [comment]
Hi @jianhong, thank you for all the feedback! I have created and merged a pull request (https://github.com/campbio/decontX/pull/9) into the devel branch to address your feedback.

**Summary:**
- All the _**Important**_ points are addressed except:
    - **_Important: vapply instead of sapply._** This piece of code is autogenerated by rstantools packaged and we are advised not to manually edit.
    - **_Important: Please consider to add drop=FALSE to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable._** I would leave these code as is, as dimension reduction after subsetting (matrix subset to get vector) was part of the design.
- Some of the _**Note**_ points are addressed.

Please feel free to let me know if you have any questions. 

Again thank you very much!


**Detailed Response:**
> # Package 'decontX' Review
> Thank you for submitting your package to Bioconductor. The package passed check and build. It is in pretty good shape. And it is a complex package. I will leave comments for multiple times. But before my next comments, please try to answer the comments line by line when you are ready for a second review. Code: Note: please consider; Important: must be addressed.
> 
> ## The DESCRIPTION file
> * [x]  Important: R version should be no less than 4.3
> * [x]  Important: At least three sentences in Description.
> 
> ## The NAMESPACE file
> * [ ]  Note: Function names use `camelCase` or `snake_case` and do not include `.`.
>   
>   * in line 3 export("decontXcounts<-")
>   * in line 13 exportMethods("decontXcounts<-")
> 
> ## General package development
> * [ ]  FYI: I am not sure Seurat will fix this issue or not. This is not related to this package.
>   The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
>   which was just loaded, will retire in October 2023.
>   Please refer to R-spatial evolution reports for details, especially
>   https://r-spatial.org/r/2023/05/15/evolution4.html.
>   It may be desirable to make the sf package available;
>   package maintainers should consider adding sf to Suggests:.
>   The sp package is now running under evolution status 2
>   (status 2 uses the sf package in place of rgdal)
> 
> ## R code
> * [ ]  NOTE: no direct slot access with `@` or `slot()` - accessors implemented and used.
>   
>   * In file R/stan_helpers.R:
>     
>     * at line 28 found '  val <- stan_vb_output@sim$est'
> * [ ]  Important: `vapply` instead of `sapply`.
>   
>   * In file R/stanmodels.R:
>     
>     * at line 10 found 'stanmodels <- sapply(stanmodels, function(model_name) {'
> * [x]  Important: No `paste` in `message()`, `message`, `stop`
>   
>   * In file R/celda_functions.R:
>     
>     * at line 19 found '      message(paste(..., sep = sep))'
> * [ ]  Note: Will it better to use `writeLines` instead of `cat`?
>   
>   * In file R/celda_functions.R:
>     
>     * at line 14 found '      cat(paste(..., "\n", sep = sep),'
> * [ ]  NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
> * [x]  NOTE: `1:n` is not suggested in source code. Use `seq_along` or `seq.int` instead.
>   
>   * In file R/plot_decontPro.R:
>     
>     * at line 53 found '                                  breaks = c(1, 5, 10 ^ (1:4))) +'
>     * at line 162 found '                                  breaks = c(1, 5, 10 ^ (1:4))) +'
> * [ ]  NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
>   
>   * In file R/celda_functions.R:
>     
>     * at line 111 found '    for (i in seq_along(features)) {'
>   * In file R/decon.R:
>     
>     * at line 184 found '    for (i in batchIndex) {'
>     * at line 430 found '  for (bat in batchIndex) {'
>     * at line 1340 found '  for (i in seq(K)) {'
>     * at line 1343 found '    for (j in setdiff(seq(K), i)) {'
>     * at line 1359 found '  for (i in seq(K)) {'
>   * In file R/plot_decontPro.R:
>     
>     * at line 38 found '  for (i in seq_along(features)) {'
>     * at line 140 found '  for (i in seq_along(features)) {'
>   * In file R/plot_decontx.R:
>     
>     * at line 192 found '    for (i in seq_along(assayName)) {'
>     * at line 365 found '    for (i in seq_along(assayName)) {'
>     * at line 506 found '    for (i in seq_along(groupClusters)) {'
> * [x]  Important: Remove unused code.
>   
>   * In file R/decon.R:
>     
>     * at line 654 found '  # nG <- nrow(counts)'
>     * at line 851 found '  # ll = sum( t(counts) * log( (1-conP )*geneDist[z,] + conP * conDist[z, ] +'
>     * at line 852 found '  # 1e-20 ) )  # when dist_mat are K x G matrices'
>     * at line 864 found '  # ll <- sum(t(counts) * log(theta * t(cellDist) +'
>     * at line 865 found '  #        (1 - theta) * t(bgDist) + 1e-20))'
> * [ ]  Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.
>   
>   * In file R/celda_functions.R:
>     
>     * at line 97 found '      search <- SummarizedExperiment::rowData(x)[, by]'
>     * at line 102 found '      search <- x[, by]'
>   * In file R/decon.R:
>     
>     * at line 189 found '      tempUMAP[result$runParams$batch == i, ] <- result$estimates[[i]]$UMAP'
>     * at line 452 found '    countsBat <- counts[, batch == bat]'
>     * at line 453 found '    bgBat <- countsBackground[, batchBackground == bat]'
>     * at line 540 found '    estRmat <- estRmat[, !(allCol %in% subCol)]'
>     * at line 544 found '    estRmat <- estRmat[, allCol]'
>     * at line 853 found '  ll <- sum(Matrix::t(counts) * log(theta * t(phi)[z, ] +'
>     * at line 854 found '    (1 - theta) * t(eta)[z, ] + 1e-20))'
>     * at line 866 found '  ll <- sum(t(counts) * log(theta * t(phi)[cbZ, ] +'
>     * at line 867 found '    (1 - theta) * t(eta)[globalZ, ] + 1e-20))'
>     * at line 889 found '  logPr <- log(t(phi)[z, ] + 1e-20) + log(theta + 1e-20)'
>     * at line 890 found '  logPc <- log(t(eta)[z, ] + 1e-20) + log(1 - theta + 1e-20)'
>     * at line 932 found '    logPr <- log(t(phi)[cbZ, ] + 1e-20) + log(theta + 1e-20)'
>     * at line 934 found '      log(t(eta)[globalZ, ] + 1e-20) + log(1 - theta + 1e-20)'
>     * at line 1342 found '    phi[i, ix] <- max(phi[i, ])'
>     * at line 1344 found '      phi[j, ix] <- 0'
>     * at line 1351 found '    stats::rmultinom(1, size = rNbyC[i], prob = phi[z[i], ])'
>     * at line 1370 found '    stats::rmultinom(1, size = cNbyC[i], prob = eta[, z[i]])'
>   * In file R/plot_decontPro.R:
>     
>     * at line 42 found '    df <- data.frame(con = counts[feature, ],'
>     * at line 43 found '                     decon = decontaminated_counts[feature, ])'
>     * at line 145 found '      con = counts[feature, ],'
>     * at line 146 found '      decon = decontaminated_counts[feature, ],'
>   * In file R/plot_decontx.R:
>     
>     * at line 60 found '  df <- df[!naIx, ]'
>     * at line 212 found '    counts <- x[geneMarkerIndex, ]'
>     * at line 383 found '    counts <- x[geneMarkerIndex, ]'
>     * at line 468 found '    z <- SummarizedExperiment::colData(x)[, z]'
>     * at line 511 found '    x <- x[, !na.ix]'
>   * In file R/stan_helpers.R:
>     
>     * at line 72 found '  unscaled_rates <- t(r_est[dat$cell_type, ])'
> * [ ]  NOTE: Functional programming: code repetition.
>   
>   * repetition in `.cDCalcEMbgDecontamination` and `.cDCalcEMDecontamination`
>     
>     * in .cDCalcEMbgDecontamination
>       
>       * line 17:        phi <- celda::normalizeCounts(phiUnnormalized, normalize = "proportion",
>       * line 18:            pseudocountNormalize = 1e-20)
>       * line 19:        eta <- celda::normalizeCounts(etaUnnormalized, normalize = "proportion",
>       * line 20:            pseudocountNormalize = 1e-20)
>       * line 21:        return(list(estRmat = estRmat, theta = theta, phi = phi,
>       * line 22:            eta = eta, delta = deltaV2))
>     * in .cDCalcEMDecontamination
>       
>       * line 18:        phi <- celda::normalizeCounts(rnGByK, normalize = "proportion",
>       * line 19:            pseudocountNormalize = 1e-20)
>       * line 20:        eta <- celda::normalizeCounts(cnGByK, normalize = "proportion",
>       * line 21:            pseudocountNormalize = 1e-20)
>       * line 22:        return(list(estRmat = estRmat, theta = theta, phi = phi,
>       * line 23:            eta = eta, delta = deltaV2))
>   * repetition in `.colSumByGroupInteger` and `.colSumByGroupNumeric`
>     
>     * in .colSumByGroupInteger
>       
>       * line 1:    group, K)
>       * line 2:{
>       * line 3:    group <- factor(group, levels = seq(K))
>       * line 4:    res <- .Call("_colSumByGroup", x, group)
>       * line 5:    return(res)
>     * in .colSumByGroupNumeric
>       
>       * line 1:    group, K)
>       * line 2:{
>       * line 3:    group <- factor(group, levels = seq(K))
>       * line 4:    res <- .Call("_colSumByGroup_numeric", x, group)
>       * line 5:    return(res)
>   * repetition in `plotDecontXMarkerExpression` and `plotDecontXMarkerPercentage`
>     
>     * in plotDecontXMarkerExpression
>       
>       * line 5:        legend <- "none"
>       * line 6:        temp <- .processPlotDecontXMarkerInupt(x = x, z = z,
>       * line 7:            markers = markers, groupClusters = groupClusters,
>       * line 8:            by = by, exactMatch = exactMatch)
>       * line 9:        x <- temp$x
>       * line 10:        z <- temp$z
>       * line 11:        geneMarkerIndex <- temp$geneMarkerIndex
>       * line 12:        groupClusters <- temp$groupClusters
>       * line 13:        xlab <- temp$xlab
>       * line 14:        if (inherits(x, "SingleCellExperiment")) {
>       * line 15:            df.list <- list()
>       * line 16:            for (i in seq_along(assayName)) {
>       * line 17:                counts <- SummarizedExperiment::assay(x[geneMarkerIndex,
>       * line 18:                  ], assayName[i])
>       * line 25:            if (length(assayName) > 1) {
>       * line 26:                legend <- "right"
>       * line 27:            }
>       * line 28:        }
>       * line 29:        else {
>       * line 30:            counts <- x[geneMarkerIndex, ]
>     * in plotDecontXMarkerPercentage
>       
>       * line 10:        }
>       * line 11:        temp <- .processPlotDecontXMarkerInupt(x = x, z = z,
>       * line 12:            markers = markers, groupClusters = groupClusters,
>       * line 13:            by = by, exactMatch = exactMatch)
>       * line 14:        x <- temp$x
>       * line 15:        z <- temp$z
>       * line 16:        geneMarkerIndex <- temp$geneMarkerIndex
>       * line 17:        geneMarkerCellTypeIndex <- temp$geneMarkerCellTypeIndex
>       * line 18:        groupClusters <- temp$groupClusters
>       * line 19:        xlab <- temp$xlab
>       * line 20:        if (inherits(x, "SingleCellExperiment")) {
>       * line 21:            df.list <- list()
>       * line 22:            for (i in seq_along(assayName)) {
>       * line 23:                counts <- SummarizedExperiment::assay(x[geneMarkerIndex,
>       * line 24:                  ], assayName[i])
>       * line 31:            if (length(assayName) > 1) {
>       * line 32:                legend <- "right"
>       * line 33:            }
>       * line 34:        }
>       * line 35:        else {
>       * line 36:            counts <- x[geneMarkerIndex, ]
> 
> ## Documentation
> * [x]  Important: Vignette should have an _Installation_ section.
>   
>   * rmd file vignettes/decontPro.Rmd
>   * rmd file vignettes/decontX.Rmd
> * [x]  Important: Please include Bioconductor installation instructions using BiocManager.
>   
>   * rmd file vignettes/decontPro.Rmd
>   * rmd file vignettes/decontX.Rmd
> * [ ]  Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
>   
>   * rmd file vignettes/decontPro.Rmd
>   * rmd file vignettes/decontX.Rmd
> * [ ]  To avoid the '* NOTE: Consider adding runnable examples to man pages that document exported objects.' in BiocCheck, could you please add runnable examples to
>   - decontXcounts.Rd
> * [ ]  NOTE: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements.

**Comment by jianhong** [comment]
Before I close this review, I just want to say, please make sure to update a NEWS file and make sure the LICENSE and LICENSE.md file are consistent.

**Comment by yuan-yin-truly** [comment]
> Before I close this review, I just want to say, please make sure to update a NEWS file and make sure the LICENSE and LICENSE.md file are consistent.

Hi @jianhong 
Thank you! I just did the following to the local devel branch and origin devel branch:

- Added NEWS.md
- Removed LICENSE.md and kept only LICENSE
- Bumped version in DESCRIPTION

Was trying to push to upstream (git.bioconductor.org) but was blocked. May I know in the future if there is any changes, I just need to push to origin devel branch?

**Comment by lshep** [comment]
It wasn't blocked it went through to git.biconductor.org.  you just wont get a new build report as once packages are accepted they move to the official Bioconductor daily builder.

**Comment by jianhong** [comment]
I did not expect you will patch the package today. No need to change it now. Once you package got accepted, the auto build system will not work. Please keep those comments in mind for your next updates.


From: Yuan Yin ***@***.***>
Date: Thursday, October 19, 2023 at 2:15 PM
To: Bioconductor/Contributions ***@***.***>
Cc: JIANHONG OU ***@***.***>, Mention ***@***.***>
Subject: Re: [Bioconductor/Contributions] decontX (Issue #3020)

Before I close this review, I just want to say, please make sure to update a NEWS file and make sure the LICENSE and LICENSE.md file are consistent.

Hi @jianhong<https://github.com/jianhong>
Thank you! I just did the following to the local devel branch and origin devel branch:

  *   Added NEWS.md
  *   Removed LICENSE.md and kept only LICENSE
  *   Bumped version in DESCRIPTION

Was trying to push to upstream (git.bioconductor.org) but was blocked. May I know in the future if there is any changes, I just need to push to origin devel branch?

**Comment by yuan-yin-truly** [comment]
@jianhong To clarify, I should wait until status change from 3a. accepted to another status (which one?), and then try pushing the new changes to git.bioconductor.org again?

**Comment by lshep** [comment]
The changes are already in git.bioconductor.org.  You dont need to do anything further to get them into Bioconductor

**Comment by yuan-yin-truly** [comment]
Hi @lshep, just to clarify, I made some changes a couple of minutes ago after Jianhong changed the packaged status to 3a. accepted, and when I try to push the changes to git.bioconductor.org, I had the following message on my git command line even though I have bumped version in DESCRIPTION:

remote: Error: Please bump the version again and push.
remote: 
remote: The build did not start as expected. If the issue persists,
remote: please reach out at bioc-devel@r-project.org or post on the
remote: Github issue where your package is being reviewed.
remote: 
remote: 400 Client Error: Bad Request for url: https://issues.bioconductor.org/start_build
remote: 
To git.bioconductor.org:packages/decontX.git
   ca82730..03e3e7d  devel -> devel

and I had this message in this issue:

> cannot build unless issue is open and has the 'pre-review' label or '2. review in progress' label, or is closed and has the 'TESTING' label.

I was wondering if the changes I made were pushed to git.bioconductor.org? Or should I wait until some other status (maybe after the nightly build) and try pushing the changes to upstream (git.bioconductor.org) again? Thank you!

**Comment by lshep** [comment]
Again -- the changes were pushed to git.bioconductor.org -- the error is that it would not trigger an on demand build by the single package builder.  We normally don't expect changes while a package is accepted but hasn't been added to the daily builder yet so its a rare edge case.

**Comment by yuan-yin-truly** [comment]
> Again -- the changes were pushed to git.bioconductor.org -- the error is that it would not trigger an on demand build by the single package builder. We normally don't expect changes while a package is accepted but hasn't been added to the daily builder yet so its a rare edge case.

Got ya! It makes sense. Thank you for clarifying!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/yuan-yin-truly.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("decontX")`. The package 'landing page' will be created at

https://bioconductor.org/packages/decontX

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
