### ISSUE TITLE
RNAseqCovarImpute

### ISSUE THREAD

**Issue by brennanhilton** [Bioconductor/Contributions#3021]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/brennanhilton/RNAseqCovarImpute

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
```
* checking examples ... ERROR
Running examples in 'RNAseqCovarImpute-Ex.R' failed
The error most likely occurred in:

> ### Name: combine_rubins
> ### Title: combine_rubins
> ### Aliases: combine_rubins
> 
> ### ** Examples
> 
> data(RNAseqCovarImpute_data)
> intervals <- get_gene_bin_intervals(example_DGE, example_data, m = 10)
Error in get_gene_bin_intervals(example_DGE, example_data, m = 10) : 
  unused argument (m = 10)
Execution halted
```

**Comment by brennanhilton** [comment]
We fixed the examples, now BiocCheck returns some NOTES but no ERRORS or WARNINGS.
Thanks,
Brennan

**Comment by vjcitn** [comment]
WHenever you change source, please bump the version.  At this point it should be 0.99.1

**Comment by vjcitn** [comment]
```
> coef_se <- limmavoom_imputed_data_list_parallel(
+     gene_intervals = intervals,
+     DGE = example_DGE,
+     imputed_data_list = gene_bin_impute,
+     m = 2,
+     voom_formula = "~x + y + z + a + b",
+     predictor = "x"
+ )
Error in limmavoom_imputed_data_list_parallel(gene_intervals = intervals,  : 
  argument "cores" is missing, with no default
Calls: limmavoom_imputed_data_list_parallel -> makeCluster -> makePSOCKcluster
Execution halted
```

**Comment by brennanhilton** [comment]
Sorry, I thought BiocCheck was running examples. Checking them with devtools::run_examples now and they all work after adding in the "cores" argument to the example for that function. I've updated the version to 0.99.2

**Comment by lazappi** [comment]
Hi @brennanhilton

Thanks for submitting **RNAseqCovarImpute** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: There are some NOTEs in the build report, please address as many of these as possible.
  - [ ] Remember to check the notes from `BiocCheck::BiocCheck()`

## DESCRIPTION file

- [ ] :green_circle: The `Description` field can be split over multiple lines to make it easier to read
- [ ] :rotating_light: The package should depend on the version of R at release
- [ ] :green_circle: Consider adding a `BugReports` field, this is usually a link to the GitHub issues page or the Bioconductor support site
- [ ] :green_circle: Consider adding a `URL` field, this is usually a link to the GitHub repository

## The NEWS file

- [ ] :warning: Remember to keep the `NEWS` file up to date as you make changes to the package

## Documentation

### README

- [ ] :warning: If you want to show code examples in the `README` it may be better to use **RMarkdown**, that way you can be sure the code is up to date with the package

### Vignette

- [ ] :rotating_light: Please add a table of contents
- [ ] :rotating_light: Please update the *Introduction* section to mention your motivation for including the package in Bioconductor and any similar packages (if applicable)
- [ ] :rotating_light: In general warnings, messages and other output should be shown so that the output in the vignette matches what the user will see when they run the code
- [ ] :warning: There is a section about gene sets but no code here, please consider adding an example

### Man pages

- [ ] :warning: It is recommended to add a package man page
- [ ] :warning: Some of the function arguments just point to functions in other packages. It is fine to refer to those for more detail but please add some description for the user of what those arguments do. Alternatively, you could use `...` and say "Arguments passed to `pkg::function()`".

## Unit tests

- [ ] :rotating_light: Please consider adding unit tests, this is highly recommended.

## Code

### R

- [ ] :rotating_light: Please use `seq_along()`/`seq_len()` instead of `1:...`
- [ ] :waring: Please consider adding validity tests for arguments in exported functions
- [ ] :rotating_light: The `BiocParallel` package should be used for parallelisation with any parallel functions having a `BPPARAM` argument
- [ ] :green_circle: Function imports can be combined into one line like `importFrom <pkg> <func1>, <func2>, ...`

### Third-party code

- [ ] :rotating_light: Please make sure you have followed the [guidelines for third-party code](https://contributions.bioconductor.org/third-party-code.html) and complied with the LICENSE for any code borrowed from other packages.

**Comment by lazappi** [comment]
Just letting you know the dates for the next Bioconductor release are now available https://bioconductor.org/developers/release-schedule/

**Comment by brennanhilton** [comment]
Hi Luke!

Thanks for reviewing my package! I have just updated and pushed version 0.99.8 to Bioconductor. Here are some of the changes in Bold:
DESCRIPTION file

  *   🟢 The Description field can be split over multiple lines to make it easier to read Tried this but was getting errors when building
  *   🚨 The package should depend on the version of R at release Added depends on R (>= 4.3.0)
  *   🟢 Consider adding a BugReports field, this is usually a link to the GitHub issues page or the Bioconductor support site Added
  *   🟢 Consider adding a URL field, this is usually a link to the GitHub repository Added

The NEWS file

  *   ⚠️ Remember to keep the NEWS file up to date as you make changes to the package I am now keeping this updated for versions that I commit and push to Bioconductor, I have noted changes for the last two versions (0.99.7 and 0.99.8)

Documentation
README

  *
⚠️ If you want to show code examples in the README it may be better to use RMarkdown, that way you can be sure the code is up to date with the package I only include that README to display on the github page. It is knit from a .Rmd file with "output: github_document". Is that okay?

Vignette

     *   🚨 Please add a table of contents The vignettes do have table of contents when I knit them to html locally. Is there something I am missing? Should look something like this: https://brennanhilton.github.io/Impute_Covariate_Data_in_RNA_sequencing_Studies.html
     *   🚨 Please update the Introduction section to mention your motivation for including the package in Bioconductor and any similar packages (if applicable) The introduction section is quite extensive and states the motivations for the package, but maybe the vignette is not knitting properly?
     *   🚨 In general warnings, messages and other output should be shown so that the output in the vignette matches what the user will see when they run the code I updated the code chunks that use the functions of my package by removing message=FALSE, warning=FALSE, etc.
     *   ⚠️ There is a section about gene sets but no code here, please consider adding an example I will work on this in the future - I would need to create another example dataset that has real genes and can be used with common pathway enrichment methods
  *

Man pages

  *   ⚠️ It is recommended to add a package man page Added
  *   ⚠️ Some of the function arguments just point to functions in other packages. It is fine to refer to those for more detail but please add some description for the user of what those arguments do. Alternatively, you could use ... and say "Arguments passed to pkg::function()". Added Arguments passed to pkg::function() along with the details from those functions

Unit tests

  *   🚨 Please consider adding unit tests, this is highly recommended. Added the file structure and some basic unit tests for the core functions, I will continue to update these with the package

Code
R

  *   🚨 Please use seq_along()/seq_len() instead of 1:... There is only one instance of "1:" and it occurs in some of the code borrowed from limma::voom. I elected to keep this code unchanged as much as possible.
  *   :waring: Please consider adding validity tests for arguments in exported functions Added
  *   🚨 The BiocParallel package should be used for parallelisation with any parallel functions having a BPPARAM argument Added - now the impute_by_gene_bin and limmavoom_imputed_data_list functions use bplapply.  I added the argument to these functions "param = bpparam()", which is passed to bplapply as the BPPARAM argument. The user can specifiy "param = SerialParam()" if they do not want to run in parallel, or do any other BiocParallel things there.
  *   🟢 Function imports can be combined into one line like importFrom <pkg> <func1>, <func2>, ... I tried this, but devtools::document() still put each importFrom on a new line in the man pages. I didn't want to manually edit those so opted to keep the default new line behavior. But let me know if I missed something.

Third-party code

  *   🚨 Please make sure you have followed the guidelines for third-party code<https://contributions.bioconductor.org/third-party-code.html> and complied with the LICENSE for any code borrowed from other packages. The link provided is broken, but I was able to find some 3rd party code materials. This external code page is not really relevant (https://contributions.bioconductor.org/cmavericks-best-practices.html#external-code-sources)
  *   This general guidelines page (https://www.bioconductor.org/developers/package-guidelines/) does not have very specific guidelines, but says I must comply with the license for borrowed code. The limma package has GPL (>=2), so I am in compliance with the license. But let me know if I need to do anything more for this

General package development

  *   ⚠️ There are some NOTEs in the build report, please address as many of these as possible.
     *   Remember to check the notes from BiocCheck::BiocCheck()

Here are my notes on the 9 current NOTEs from BiocCheck:

* NOTE: Consider adding these automatically suggested biocViews:
      Bayesian Bayesian procedures in limma are used, but I dont think Bayesian is really a central theme of this package

* NOTE: The Description field in the DESCRIPTION is made up by less
  than 3 sentences. Please consider expanding this field, and
  structure it as a full paragraph The description is actually quite long, just not structured with periods but as a list with 1), 2), 3), etc.

* NOTE: License 'GPL (>= 3)' unknown; licenses cannot restrict use Not sure what is going on here but I think GPL (>= 3) is good, does not restrict use.

* NOTE: Avoid 1:...; use seq_len() or seq_along() None of my code used 1:.., just one piece of code adapted from limma::voom, and I wanted to modify that borrowed code as little as possible

* NOTE: The recommended function length is 50 lines or less. There
  are 3 functions greater than 50 lines. Two of the long functions are the ones adapted from limma::voom, so I think best to keep as they are. The combine_rubins functions is long, but I think all elements of that function need to be in one place. It is a series of stats calculations, and I think more confusing to split into separate functions

For all below I used a code styling function: styler::style_pkg(transformers = biocthis::bioc_style()). Changes were made to my original code, so I think all .R and .Rmd files should be correctly formatted to the bioconductor style. These could occur in .Rd man files or other filetypes. Does it seem okay to leave as is?

* NOTE: Consider shorter lines; 175 lines (10%) are > 80 characters
      long.
* NOTE: Consider 4 spaces instead of tabs; 33 lines (2%) contain
      tabs.
* NOTE: Consider multiples of 4 spaces for line indents; 269 lines
      (15%) are not.

Thanks again for reviewing the package, and I am happy to do my best to implement any more changes.

Best wishes,
Brennan

________________________________
From: Luke Zappia ***@***.***>
Sent: Monday, August 21, 2023 12:39 AM
To: Bioconductor/Contributions ***@***.***>
Cc: Baker, Brennan H. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Bioconductor/Contributions] RNAseqCovarImpute (Issue #3021)


Hi @brennanhilton<https://github.com/brennanhilton>

Thanks for submitting RNAseqCovarImpute 🎉! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

What next?

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the ... menu on this comment to reply directly to my points below.

Luke

Review

Key: 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question

General package development

  *    ⚠️ There are some NOTEs in the build report, please address as many of these as possible.
     *    Remember to check the notes from BiocCheck::BiocCheck()

DESCRIPTION file

  *    🟢 The Description field can be split over multiple lines to make it easier to read
  *    🚨 The package should depend on the version of R at release
  *    🟢 Consider adding a BugReports field, this is usually a link to the GitHub issues page or the Bioconductor support site
  *    🟢 Consider adding a URL field, this is usually a link to the GitHub repository

The NEWS file

  *    ⚠️ Remember to keep the NEWS file up to date as you make changes to the package

Documentation
README

  *    ⚠️ If you want to show code examples in the README it may be better to use RMarkdown, that way you can be sure the code is up to date with the package

Vignette

  *    🚨 Please add a table of contents
  *    🚨 Please update the Introduction section to mention your motivation for including the package in Bioconductor and any similar packages (if applicable)
  *    🚨 In general warnings, messages and other output should be shown so that the output in the vignette matches what the user will see when they run the code
  *    ⚠️ There is a section about gene sets but no code here, please consider adding an example

Man pages

  *    ⚠️ It is recommended to add a package man page
  *    ⚠️ Some of the function arguments just point to functions in other packages. It is fine to refer to those for more detail but please add some description for the user of what those arguments do. Alternatively, you could use ... and say "Arguments passed to pkg::function()".

Unit tests

  *    🚨 Please consider adding unit tests, this is highly recommended.

Code
R

  *    🚨 Please use seq_along()/seq_len() instead of 1:...
  *    :waring: Please consider adding validity tests for arguments in exported functions
  *    🚨 The BiocParallel package should be used for parallelisation with any parallel functions having a BPPARAM argument
  *    🟢 Function imports can be combined into one line like importFrom <pkg> <func1>, <func2>, ...

Third-party code

  *    🚨 Please make sure you have followed the guidelines for third-party code<https://contributions.bioconductor.org/third-party-code.html> and complied with the LICENSE for any code borrowed from other packages.

**Comment by brennanhilton** [comment]
Luke,
My initial reply (directly from my email) was not showing up nicely here. See below for a more nicely formatted reply.
Thanks again for reviewing my package!
Brennan

> Hi @brennanhilton
> 
> Thanks for submitting **RNAseqCovarImpute** 🎉! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.
> 
> **What next?**
> 
> Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.
> 
> Luke
> 
> # Review
> **Key:** 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question
> 
> ## General package development
> * [ ]  ⚠️ There are some NOTEs in the build report, please address as many of these as possible.
>   
>   * [ ]  Remember to check the notes from `BiocCheck::BiocCheck()`
**See bottom of this reply for my notes on all BiocCheck NOTEs**
> ## DESCRIPTION file
> * [ ]  🟢 The `Description` field can be split over multiple lines to make it easier to read
**Tried this but was getting errors when building**
> * [ ]  🚨 The package should depend on the version of R at release
**Added depends on R (>= 4.3.0)**
> * [ ]  🟢 Consider adding a `BugReports` field, this is usually a link to the GitHub issues page or the Bioconductor support site
**Added**
> * [ ]  🟢 Consider adding a `URL` field, this is usually a link to the GitHub repository
**Added**
> 
> ## The NEWS file
> * [ ]  ⚠️ Remember to keep the `NEWS` file up to date as you make changes to the package
**I am now keeping this updated for versions that I commit and push to Bioconductor, I have noted changes for the last two versions (0.99.7 and 0.99.8)**
> 
> ## Documentation
> ### README
> * [ ]  ⚠️ If you want to show code examples in the `README` it may be better to use **RMarkdown**, that way you can be sure the code is up to date with the package
**I only include that README to display on the github page. It is knit from a .Rmd file with "output: github_document". Is that okay?**
> 
> ### Vignette
> * [ ]  🚨 Please add a table of contents
**The vignettes do have table of contents when I knit them to html locally. Is there something I am missing? Should look something like this: https://brennanhilton.github.io/Impute_Covariate_Data_in_RNA_sequencing_Studies.html**
> * [ ]  🚨 Please update the _Introduction_ section to mention your motivation for including the package in Bioconductor and any similar packages (if applicable)
**The introduction section is quite extensive and states the motivations for the package, but maybe the vignette is not knitting properly?**
> * [ ]  🚨 In general warnings, messages and other output should be shown so that the output in the vignette matches what the user will see when they run the code
**I updated the code chunks that use the functions of my package by removing message=FALSE, warning=FALSE, etc.**
> * [ ]  ⚠️ There is a section about gene sets but no code here, please consider adding an example
**I will work on this in the future - I would need to create another example dataset that has real genes and can be used with common pathway enrichment methods**
> 
> ### Man pages
> * [ ]  ⚠️ It is recommended to add a package man page
**Added**
> * [ ]  ⚠️ Some of the function arguments just point to functions in other packages. It is fine to refer to those for more detail but please add some description for the user of what those arguments do. Alternatively, you could use `...` and say "Arguments passed to `pkg::function()`".
**Added Arguments passed to pkg::function() along with the details from those functions**
> 
> ## Unit tests
> * [ ]  🚨 Please consider adding unit tests, this is highly recommended.
**Added the file structure and some basic unit tests for the core functions, I will continue to update these with the package**
> 
> ## Code
> ### R
> * [ ]  🚨 Please use `seq_along()`/`seq_len()` instead of `1:...`
**There is only one instance of "1:" and it occurs in some of the code borrowed from limma::voom. I elected to keep this code unchanged as much as possible.**
> * [ ]  :waring: Please consider adding validity tests for arguments in exported functions
**Added**
> * [ ]  🚨 The `BiocParallel` package should be used for parallelisation with any parallel functions having a `BPPARAM` argument
**Added - now the impute_by_gene_bin and limmavoom_imputed_data_list functions use bplapply.  I added the argument to these functions "param = bpparam()", which is passed to bplapply as the BPPARAM argument. The user can specifiy "param = SerialParam()" if they do not want to run in parallel, or do any other BiocParallel things there.**
> * [ ]  🟢 Function imports can be combined into one line like `importFrom <pkg> <func1>, <func2>, ...`
**I tried this, but devtools::document() still put each importFrom on a new line in the man pages. I didn't want to manually edit those so opted to keep the default new line behavior. But let me know if I missed something.**
> 
> ### Third-party code
> * [ ]  🚨 Please make sure you have followed the [guidelines for third-party code](https://contributions.bioconductor.org/third-party-code.html) and complied with the LICENSE for any code borrowed from other packages.
**The link provided is broken, but I was able to find some 3rd party code materials. This external code page is not really relevant (https://contributions.bioconductor.org/cmavericks-best-practices.html#external-code-sources) 
This general guidelines page (https://www.bioconductor.org/developers/package-guidelines/) does not have very specific guidelines, but says I must comply with the license for borrowed code. The limma package has GPL (>=2), so I am in compliance with the license. But let me know if I need to do anything more for this**

Here are my notes on the 9 current NOTEs from BiocCheck:
NOTE: Consider adding these automatically suggested biocViews:
 **Bayesian Bayesian procedures in limma are used, but I dont think Bayesian is really a central theme of this package**
NOTE: The Description field in the DESCRIPTION is made up by less
  than 3 sentences. Please consider expanding this field, and
  structure it as a full paragraph 
**The description is actually quite long, just not structured with periods but as a list with 1), 2), 3), etc.**
NOTE: License 'GPL (>= 3)' unknown; licenses cannot restrict use 
**Not sure what is going on here but I think GPL (>= 3) is good, does not restrict use.**
NOTE: Avoid 1:...; use seq_len() or seq_along()
**None of my code used 1:.., just one piece of code adapted from limma::voom, and I wanted to modify that borrowed code as little as possible** 
NOTE: The recommended function length is 50 lines or less. 
**There are 3 functions greater than 50 lines. Two of the long functions are the ones adapted from limma::voom, so I think best to keep as they are. The combine_rubins functions is long, but I think all elements of that function need to be in one place. It is a series of stats calculations, and I think more confusing to split into separate functions**

**For all below I used a code styling function: styler::style_pkg(transformers = biocthis::bioc_style()). Changes were made to my original code, so I think all .R and .Rmd files should be correctly formatted to the bioconductor style. These could occur in .Rd man files or other filetypes. Does it seem okay to leave as is?**
NOTE: Consider shorter lines; 175 lines (10%) are > 80 characters
      long.
NOTE: Consider 4 spaces instead of tabs; 33 lines (2%) contain
      tabs.
NOTE: Consider multiples of 4 spaces for line indents; 269 lines
      (15%) are not.

**Comment by lazappi** [comment]
> >   * [ ]   Remember to check the notes from `BiocCheck::BiocCheck()`
> ** NOTE: License 'GPL (>= 3)' unknown; licenses cannot restrict use **Not sure what is going on here but I think GPL (>= 3) is good, does not restrict use.**

I guess it's not been recognised for some reason? Maybe check it is specified correctly? I would expect an error if this was completely failing though.

> > * [ ]   🟢 The `Description` field can be split over multiple lines to make it easier to read
> >   **Tried this but was getting errors when building**

Hmmm....I think you also have to indent it, did you try that? You should be able to see examples of what works in other packages. This isn't a big deal though.

> > * [ ]   ⚠️ If you want to show code examples in the `README` it may be better to use **RMarkdown**, that way you can be sure the code is up to date with the package
> >   **I only include that README to display on the github page. It is knit from a .Rmd file with "output: github_document". Is that okay?**

Yep, that should be fine

> > * [ ]   🚨 Please add a table of contents
> >   **The vignettes do have table of contents when I knit them to html locally. Is there something I am missing? Should look something like this: [brennanhilton.github.io/Impute_Covariate_Data_in_RNA_sequencing_Studies.html](https://brennanhilton.github.io/Impute_Covariate_Data_in_RNA_sequencing_Studies.html)**

Hmmm...I thought this needs to be set in the YAML section but maybe it is turned on by default for `BiocStyle::html_document`. As long as it's there this should be fine.

> > * [ ]   🚨 Please update the _Introduction_ section to mention your motivation for including the package in Bioconductor and any similar packages (if applicable)
> >   **The introduction section is quite extensive and states the motivations for the package, but maybe the vignette is not knitting properly?**

I think it renders fine and you introduce the package functionality well. What we are looking for is a description of how the package interacts with other Bioconductor packages or more generally why it is included in Bioconductor.

> > * [ ]   🚨 In general warnings, messages and other output should be shown so that the output in the vignette matches what the user will see when they run the code
> >   **I updated the code chunks that use the functions of my package by removing message=FALSE, warning=FALSE, etc.**

These still seem to be there in the version I pulled from Bioconductor?

> > * [ ]   ⚠️ There is a section about gene sets but no code here, please consider adding an example
> >   **I will work on this in the future - I would need to create another example dataset that has real genes and can be used with common pathway enrichment methods**

Could you maybe mention this in the text? At the moment it just reads like there is an example missing which could be confusing for readers.

> > * [ ]   🚨 The `BiocParallel` package should be used for parallelisation with any parallel functions having a `BPPARAM` argument
> >   **Added - now the impute_by_gene_bin and limmavoom_imputed_data_list functions use bplapply.  I added the argument to these functions "param = bpparam()", which is passed to bplapply as the BPPARAM argument. The user can specifiy "param = SerialParam()" if they do not want to run in parallel, or do any other BiocParallel things there.**

Thanks! By convention this argument should be called `BPPARAM` for consistency between packages, can you please update that? I also think it might be clearer to say something like "A `BiocParallelParam` object" in the argument description, at the moment it sounds like you are passing on a list of arguments when you actually need the object.

> > * [ ]   🟢 Function imports can be combined into one line like `importFrom <pkg> <func1>, <func2>, ...`
> >   **I tried this, but devtools::document() still put each importFrom on a new line in the man pages. I didn't want to manually edit those so opted to keep the default new line behavior. But let me know if I missed something.**

I guess in the `.Rd` they need to be on separate lines but in the `.R` files you can combine them. This isn't important though so whatever works for you.

> > * [ ]   🚨 Please make sure you have followed the [guidelines for third-party code](https://contributions.bioconductor.org/third-party-code.html) and complied with the LICENSE for any code borrowed from other packages.
> >   **The link provided is broken, but I was able to find some 3rd party code materials. This external code page is not really relevant ([contributions.bioconductor.org/cmavericks-best-practices.html#external-code-sources](https://contributions.bioconductor.org/cmavericks-best-practices.html#external-code-sources))
> >   This general guidelines page ([bioconductor.org/developers/package-guidelines](https://www.bioconductor.org/developers/package-guidelines/)) does not have very specific guidelines, but says I must comply with the license for borrowed code. The limma package has GPL (>=2), so I am in compliance with the license. But let me know if I need to do anything more for this**

You are right, that does seem to have disappeared. I think to be safer it would be good to include comments on the functions you have borrowed stating where they originally came from and what license they are covered by. This should be in the documentation so it is visible to users but additional normal comments are also encouraged.

Some other things I noticed:

* **{BiocParallel}** should be in `Imports` not `Depends` (unless there is a reason for it to be here)
* `lowess_all_gene_bins()` seems to be missing argument documentation. Please make sure arguments for all exported functions are documented.
* I think you have both `@export` and `@keywords internal` for some functions. These are trying to do opposite things so I would just keep whichever one you intended.

**Comment by brennanhilton** [comment]
> > > * [ ]    Remember to check the notes from `BiocCheck::BiocCheck()`
> > >   ** NOTE: License 'GPL (>= 3)' unknown; licenses cannot restrict use **Not sure what is going on here but I think GPL (>= 3) is good, does not restrict use.**
> 
> I guess it's not been recognised for some reason? Maybe check it is specified correctly? I would expect an error if this was completely failing though.
**Changed to GPL-3, which fixed the note**
> 
> > > * [ ]    🟢 The `Description` field can be split over multiple lines to make it easier to read
> > >   **Tried this but was getting errors when building**
> 
> Hmmm....I think you also have to indent it, did you try that? You should be able to see examples of what works in other packages. This isn't a big deal though.
**Thanks, indents worked!**
> 
> > > * [ ]    ⚠️ If you want to show code examples in the `README` it may be better to use **RMarkdown**, that way you can be sure the code is up to date with the package
> > >   **I only include that README to display on the github page. It is knit from a .Rmd file with "output: github_document". Is that okay?**
> 
> Yep, that should be fine
> 
> > > * [ ]    🚨 Please add a table of contents
> > >   **The vignettes do have table of contents when I knit them to html locally. Is there something I am missing? Should look something like this: [brennanhilton.github.io/Impute_Covariate_Data_in_RNA_sequencing_Studies.html](https://brennanhilton.github.io/Impute_Covariate_Data_in_RNA_sequencing_Studies.html)**
> 
> Hmmm...I thought this needs to be set in the YAML section but maybe it is turned on by default for `BiocStyle::html_document`. As long as it's there this should be fine.
> 
> > > * [ ]    🚨 Please update the _Introduction_ section to mention your motivation for including the package in Bioconductor and any similar packages (if applicable)
> > >   **The introduction section is quite extensive and states the motivations for the package, but maybe the vignette is not knitting properly?**
> 
> I think it renders fine and you introduce the package functionality well. What we are looking for is a description of how the package interacts with other Bioconductor packages or more generally why it is included in Bioconductor.
> 
**Added something like this as a new first paragraph to the intro in the vignette, to say that my package interacts with limma and is an extension of the voom method for situations with missing covariate data**
> > > * [ ]    🚨 In general warnings, messages and other output should be shown so that the output in the vignette matches what the user will see when they run the code
> > >   **I updated the code chunks that use the functions of my package by removing message=FALSE, warning=FALSE, etc.**
> 
> These still seem to be there in the version I pulled from Bioconductor?
> 
**Sorry about that! I went back and removed message and warning = FALSE from most code chunks**
> > > * [ ]    ⚠️ There is a section about gene sets but no code here, please consider adding an example
> > >   **I will work on this in the future - I would need to create another example dataset that has real genes and can be used with common pathway enrichment methods**
> 
> Could you maybe mention this in the text? At the moment it just reads like there is an example missing which could be confusing for readers.
> 
**Yes I see how that could look like a missing example - I just removed that part for now and might make a whole separate vignette in the future for downstream pathway analysis**
> > > * [ ]    🚨 The `BiocParallel` package should be used for parallelisation with any parallel functions having a `BPPARAM` argument
> > >   **Added - now the impute_by_gene_bin and limmavoom_imputed_data_list functions use bplapply.  I added the argument to these functions "param = bpparam()", which is passed to bplapply as the BPPARAM argument. The user can specifiy "param = SerialParam()" if they do not want to run in parallel, or do any other BiocParallel things there.**
> 
> Thanks! By convention this argument should be called `BPPARAM` for consistency between packages, can you please update that? I also think it might be clearer to say something like "A `BiocParallelParam` object" in the argument description, at the moment it sounds like you are passing on a list of arguments when you actually need the object.
> 
**Changed argument to 'BPPARAM' and the documentation to 'A BiocParallelParam object'**
> > > * [ ]    🟢 Function imports can be combined into one line like `importFrom <pkg> <func1>, <func2>, ...`
> > >   **I tried this, but devtools::document() still put each importFrom on a new line in the man pages. I didn't want to manually edit those so opted to keep the default new line behavior. But let me know if I missed something.**
> 
> I guess in the `.Rd` they need to be on separate lines but in the `.R` files you can combine them. This isn't important though so whatever works for you.
> 
**Got it, I am keeping them combined on the same line in the .R files**
> > > * [ ]    🚨 Please make sure you have followed the [guidelines for third-party code](https://contributions.bioconductor.org/third-party-code.html) and complied with the LICENSE for any code borrowed from other packages.
> > >   **The link provided is broken, but I was able to find some 3rd party code materials. This external code page is not really relevant ([contributions.bioconductor.org/cmavericks-best-practices.html#external-code-sources](https://contributions.bioconductor.org/cmavericks-best-practices.html#external-code-sources))
> > >   This general guidelines page ([bioconductor.org/developers/package-guidelines](https://www.bioconductor.org/developers/package-guidelines/)) does not have very specific guidelines, but says I must comply with the license for borrowed code. The limma package has GPL (>=2), so I am in compliance with the license. But let me know if I need to do anything more for this**
> 
> You are right, that does seem to have disappeared. I think to be safer it would be good to include comments on the functions you have borrowed stating where they originally came from and what license they are covered by. This should be in the documentation so it is visible to users but additional normal comments are also encouraged.
> 
**Added this to the documentation for my functions that borrow code: 'Adapted from limma::voom. Code from limma covered by License: GPL (>=2)'**
> Some other things I noticed:
> 
> * **{BiocParallel}** should be in `Imports` not `Depends` (unless there is a reason for it to be here)
> * `lowess_all_gene_bins()` seems to be missing argument documentation. Please make sure arguments for all exported functions are documented.
> * I think you have both `@export` and `@keywords internal` for some functions. These are trying to do opposite things so I would just keep whichever one you intended.
**I fixed this so the internal functions are not exported anymore by removing @export from those. I moved BiocParallel to imports rather than depends**

**Comment by lazappi** [comment]
I am happy with this now so have accepted the package. Congratulations on getting the package into Bioconductor and thanks for your responses to my comments.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/brennanhilton.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RNAseqCovarImpute")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RNAseqCovarImpute

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
