### ISSUE TITLE
MICSQTL

### ISSUE THREAD

**Issue by YuePan027** [Bioconductor/Contributions#3023]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YuePan027/MICSQTL

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by YuePan027** [comment]
@jianhong I would like to inquire about accessing the git@git.bioconductor.org as an upstream repository. I am currently working on pushing my package to incorporate the latest changes. Could you please provide some guidance? Thank you!
![upstream](https://github.com/Bioconductor/Contributions/assets/109984500/94d69517-3447-45f9-bef8-4b503e527474)

**Comment by lshep** [comment]
Have you activated your [Bioconductor Git Credentials Account](https://git.bioconductor.org/BiocCredentials) as suggested in the comment above.  Once you activate the account you can control ssh keys for access.

**Comment by YuePan027** [comment]
I attempted to activate my account, but I received an error message stating that my email "is not associated with a maintainer of a Bioconductor package," despite having signed up previously. As per the feedback I received, a member of the Bioconductor Core Team will review the situation. Do you have any additional suggestions to help resolve this issue and proceed with the package review/activation process? Thanks!

**Comment by lshep** [comment]
there is a change that it is case sensitive as it most of Bioconductor -- are you trying with the email used in the DESCRIPTION `Yue.Pan@STJUDE.ORG`  as I see the account in the app but that it has not been activated.  Please also remember to check junk/spam folders as confirmation emails sent can often be marked as spam.

@jianhong  I am investigating the support site registration as I do see the email registered but the api is returning false. So you can ignore the support site ERROR for now
It looks like the mailing list was signed up for successfully and I expect this ERROR to be resolved on the next check.

**Comment by YuePan027** [comment]
Yes I have tried with the email address I provided during the registration process and have thoroughly checked my inbox, including the deleted and spam folders. However, I have not received any activation email. Do you happen to know that if it is possible for the Bioconductor tech support team to manually activate my account? If I can not get my git credentials account activated in this case, what would be the appropriate way to submit my changes to Bioconductor site for review? Thank you!
![image](https://github.com/Bioconductor/Contributions/assets/109984500/877783ac-fa69-46a4-a993-87c83f006187)

**Comment by lshep** [comment]
I can manually reset the account.  I will contact you privately with additional log in information with a temp password.

**Comment by YuePan027** [comment]
@lshep Thank you! I just activated my git credentials account successfully. I still failed to fetch all changes though. 
![image](https://github.com/Bioconductor/Contributions/assets/109984500/2a3cf9a9-4844-4ed7-8abc-e4896dd55fd7)

In addition, I have attempted to run BiocCheck::BiocCheck() to address the error regarding registration at the support site. However, I still encounter the same error message. Could you please confirm if there are any additional steps I need to take? Is there a waiting period before I can make any changes? Thank you for your assistance.

**Comment by YuePan027** [comment]
@jianhong @lshep 
We have addressed the issues based on the report from the last submission: 

1. "Error in .check_ncores(cores): 3 simultaneous processes spawned"  

The error in the CIBERSORT function has been resolved. 

 

2. "LaTeX Error: Unicode character (U+2265) not set up for use with LaTeX."  

The problematic character has been replaced, and the LaTeX manual will now be generated as expected. 

 

3. "* NOTE: Update R version dependency from 4.2.0 to 4.3.0."  

The R version dependency has been updated to 4.3.0. 

 

4. "* NOTE: Consider adding these automatically suggested biocViews: Coverage."  

The automatically suggested biocViews, including "Coverage," have been added. 

 

5. "* NOTE: Consider adding the maintainer's ORCID iD in 'Authors@R' with 'comment=c(ORCID="...")'."  

The maintainer's ORCID iD has been added as suggested. 

 

6. "* NOTE: 'sessionInfo' not found in vignette(s)."  

'sessionInfo' has been added to the vignette(s). 

 

7. "* NOTE: Avoid 'suppressWarnings'/'*Messages' if possible."  

We have removed supressWarnings/Messages in the csQTL function by disabling messages from the imported package TOAST. 

 

8. "* NOTE: The recommended function length is 50 lines or less."  

     We have made an effort to break down functions into shorter ones. However, some functions like deconv, and certain utility functions cannot be further reduced due to their inherent computational requirements. 

 

9. "* WARNING: Empty or missing \value sections found in man pages."  

The output of the functions is stored in the parent slots, and this has been clarified in \value, although we do not use subsections. 

   

10. "* NOTE: Consider shorter lines; 26 lines (1%) are > 80 characters long. 

              NOTE: Consider multiples of 4 spaces for line indents; 75 lines (3%) are not."  

     We have made the necessary changes to ensure most lines are less than 80 characters and have adjusted line indents. The remaining code has been checked using the styler package. For arguments of functions, the 4-space indents have been maintained. 

 

11. "* ERROR: Maintainer must subscribe to the bioc-devel mailing list."  

I have subscribed to the bioc-devel mailing list, resolving this error. 

 

12. "ERROR: Maintainer must register at the support site."  

I have registered at the support site with my maintainer email listed in the DESCRIPTION file (not my Github account email). Based on the reply from the core team (@lshep), there is an issue with the support site that fails to recognize my registered email. It will take some time to fix. Please disregard this error for now.

**Comment by jianhong** [comment]
# Package 'MICSQTL' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. It is in pretty good shape. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.

## The NAMESPACE file
- [ ] Important: Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 9 import(SummarizedExperiment)
	* in line 10 import(TOAST)
	* in line 11 import(ggplot2)
	* in line 12 import(ggpubr)
	* in line 13 import(ggridges)

## General package development

- [ ] Important: Empty or missing \value sections found in man pages.
  * Found in files:
     man/se.Rd
     
- [ ] Important:  Consider adding more unit tests.
Current unit tests only covered 14.5%. The bottom line is 30%.

## R code
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.

- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/deconv.R:
		+ at line 131 found '            for (i in seq_len(max_iter)){'
	* In file R/utils.R:
		+ at line 69 found '    for (k in seq_len(K)) {'
		+ at line 88 found '            for (k in seq_len(K)) {'
		+ at line 153 found '        for (k in seq_len(K)) {'
		+ at line 154 found '            for (j in seq_len(joint_rank_estimate)) {'
		+ at line 329 found '    for (s in seq_len(num_samples)) {'
		+ at line 331 found '        for (b in seq(n_blocks)) {'
		+ at line 388 found '    for (s in seq_len(num_samples)) {'
		+ at line 452 found '    for (k in seq_len(K)) {'
		+ at line 480 found '    for (k in seq_len(K)) {'
- [ ] Important: Remove unused code.
	* In file R/csQTL.R:
		+ at line 73 found '                # data.frame(factor(t(SNP_dat)[, test_protein[i]]))'
		+ at line 87 found '                #suppressWarnings() #%>%'
		+ at line 88 found '                #suppressMessages()'
	* In file R/deconv.R:
		+ at line 132 found '                #cat("iter", i, "\n")'
		+ at line 140 found '                #cat("diff = ", max(diff), "\n")'
		+ at line 142 found '                    #cat("converged", "\n")'
		+ at line 145 found '                    #cat("reach max iter", "\n")'
		+ at line 146 found '                    #cat(colnames(diff)[col(diff)[diff==max(diff)]])'
	* In file R/feature_filter.R:
		+ at line 102 found '        # se <- se[target_protein, ]'
		+ at line 164 found '        # se <- se[idx3,]'
	* In file R/utils.R:
		+ at line 265 found '    # SVD <- get_svd(X, rank=2)'
		+ at line 443 found '    # if(center){'
		+ at line 444 found '    #     blocks <- lapply(blocks,function(X) scale(X, center=T, scale=FALSE))'
		+ at line 445 found '    # }'
		+ at line 474 found '    # dim(joint_scores)[2]'

- [ ] Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.
	* In file R/ajive.R:
		+ at line 62 found '            dat2 <- methods::slot(se, "metadata")[[test]][in_use, ]'
	* In file R/csQTL.R:
		+ at line 77 found '                    as.matrix(protein_tab[protein_name, ])'
		+ at line 99 found '            return(res_df[, c("protein", "SNP", colnames(prop))])'
	* In file R/deconv.R:
		+ at line 118 found '        ini_prop <- result[, seq_len(ncol(ref_gene))]'
		+ at line 121 found '            X = assay(se)[mrk_prot, ],'
		+ at line 134 found '                    X = assay(se)[mrk_prot, ],'
	* In file R/feature_filter.R:
		+ at line 101 found '        methods::slot(se, "metadata")$target_dat <- assay(se)[target_protein, ]'
		+ at line 149 found '                        target_protein[i]), ]'
		+ at line 157 found '                    anno_SNP$CHROM == df[1, 1])'
		+ at line 166 found '            methods::slot(se, "metadata")$target_dat[idx3, ]'
	* In file R/utils.R:
		+ at line 25 found '        X = assay(se)[mrk_prot, ],'
		+ at line 71 found '            block_svd[[k]][["u"]][, seq_len(initial_signal_ranks[k])]'
		+ at line 89 found '                block_wedin_samples[k, ] <- get_wedin_bound_samples('
		+ at line 155 found '                score <- t(blocks[[k]]) %*% joint_scores[, j]'
		+ at line 353 found '    U_perp <- SVD[["u"]][, -(seq_len(signal_rank))]'
		+ at line 361 found '    V_perp <- SVD[["v"]][, -(seq_len(signal_rank))]'
		+ at line 396 found '        perp_resampled <- perp_basis[, sampled_col_index]'
- [ ] Important: Could you check about the function `S4vector::metadata` vs. `methods::slot(se, "metadata")` in your codes?

## Documentation
- [ ] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/MICSQTL.Rmd
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/MICSQTL.Rmd
- [ ] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/MICSQTL.Rmd

**Comment by YuePan027** [comment]
@jianhong Thank you for your feedbacks and insightful comments. We have made the following revisions: 
1. The NAMESPACE file
•	  Important: Selective imports using importFrom instead of import all with import.
o	in line 9 import(SummarizedExperiment)
o	in line 10 import(TOAST)
o	in line 11 import(ggplot2)
o	in line 12 import(ggpubr)
o	in line 13 import(ggridges)
_In the case of TOAST and ggpubr, we selectively import only the necessary functions using importFrom. However, for the remaining packages, due to the extensive use of multiple functions, it is more convenient to import the entire packages._

2. General package development
•	  Important: Empty or missing \value sections found in man pages.
o	Found in files:
man/se.Rd
_This documentation provides information about our example data file, which is saved as a SummarizedExperiment object. Since it is not a function with returned values, it does not include a \value section in the man pages._

•	  Important: Consider adding more unit tests.
Current unit tests only covered 14.5%. The bottom line is 30%.
_We have added more unit tests and according to covr::report(), the coverage is 58.87% now._

3. R code
•	  NOTE: :: is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep ::. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
•	
_We have removed some duplicated :: from each function._

•	  NOTE: Vectorize: for loops present, try to replace them by *apply funcitons.
o	In file R/deconv.R:
	at line 131 found ' for (i in seq_len(max_iter)){'

_We have updated the for loop to a while loop. This step is done in a recursive way, which makes *apply funcitons not appropriate since they are designed for independent processes._

o	In file R/utils.R:
	at line 69 found ' for (k in seq_len(K)) {'
	at line 88 found ' for (k in seq_len(K)) {'
	at line 153 found ' for (k in seq_len(K)) {'
	at line 154 found ' for (j in seq_len(joint_rank_estimate)) {'
	at line 329 found ' for (s in seq_len(num_samples)) {'
	at line 331 found ' for (b in seq(n_blocks)) {'
	at line 388 found ' for (s in seq_len(num_samples)) {'
	at line 452 found ' for (k in seq_len(K)) {'
	at line 480 found ' for (k in seq_len(K)) {'

_These functions are implementations of code developed by other contributors, and we prefer not to modify their original code._

•	  Important: Remove unused code.
o	In file R/csQTL.R:
	at line 73 found ' # data.frame(factor(t(SNP_dat)[, test_protein[i]]))'
	at line 87 found ' #suppressWarnings() #%>%'
	at line 88 found ' #suppressMessages()'
o	In file R/deconv.R:
	at line 132 found ' #cat("iter", i, "\n")'
	at line 140 found ' #cat("diff = ", max(diff), "\n")'
	at line 142 found ' #cat("converged", "\n")'
	at line 145 found ' #cat("reach max iter", "\n")'
	at line 146 found ' #cat(colnames(diff)[col(diff)[diff==max(diff)]])'
o	In file R/feature_filter.R:
	at line 102 found ' # se <- se[target_protein, ]'
	at line 164 found ' # se <- se[idx3,]'
o	In file R/utils.R:
	at line 265 found ' # SVD <- get_svd(X, rank=2)'
	at line 443 found ' # if(center){'
	at line 444 found ' # blocks <- lapply(blocks,function(X) scale(X, center=T, scale=FALSE))'
	at line 445 found ' # }'
	at line 474 found ' # dim(joint_scores)[2]'

_We have removed all unused code._

•	  Important: Please consider to add drop=FALSE to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.
o	In file R/ajive.R:
	at line 62 found ' dat2 <- methods::slot(se, "metadata")[[test]][in_use, ]'
o	In file R/csQTL.R:
	at line 77 found ' as.matrix(protein_tab[protein_name, ])'
	at line 99 found ' return(res_df[, c("protein", "SNP", colnames(prop))])'
o	In file R/deconv.R:
	at line 118 found ' ini_prop <- result[, seq_len(ncol(ref_gene))]'
	at line 121 found ' X = assay(se)[mrk_prot, ],'
	at line 134 found ' X = assay(se)[mrk_prot, ],'
o	In file R/feature_filter.R:
	at line 101 found ' methods::slot(se, "metadata")$target_dat <- assay(se)[target_protein, ]'
	at line 149 found ' target_protein[i]), ]'
	at line 157 found ' anno_SNP$CHROM == df[1, 1])'
	at line 166 found ' methods::slot(se, "metadata")$target_dat[idx3, ]'

_We have added drop = FALSE to all main functions whenever a data set is subsetted._

o	In file R/utils.R:
	at line 25 found ' X = assay(se)[mrk_prot, ],'
	at line 71 found ' block_svd[[k]][["u"]][, seq_len(initial_signal_ranks[k])]'
	at line 89 found ' block_wedin_samples[k, ] <- get_wedin_bound_samples('
	at line 155 found ' score <- t(blocks[[k]]) %*% joint_scores[, j]'
	at line 353 found ' U_perp <- SVD[["u"]][, -(seq_len(signal_rank))]'
	at line 361 found ' V_perp <- SVD[["v"]][, -(seq_len(signal_rank))]'
	at line 396 found ' perp_resampled <- perp_basis[, sampled_col_index]'

_These functions are implementations of code developed by other contributors, and we prefer not to modify their original code._

•	  Important: Could you check about the function S4vector::metadata vs. methods::slot(se, "metadata") in your codes?

_We have replaced all methods::slot(se, "metadata") by S4vector::metadata._

4. Documentation
•	  Important: Vignette should have an Installation section.
o	rmd file vignettes/MICSQTL.Rmd
•	  Important: Please include Bioconductor installation instructions using BiocManager.

_We have added an Installation section using BiocManager._

o	rmd file vignettes/MICSQTL.Rmd
•	  Note: Vignette includes motivation for submitting to Bioconductor as part of the abstract/intro of the main vignette.
o	rmd file vignettes/MICSQTL.Rmd

_We have added our motivation by including "This is a novel pipeline for multi-omic integrative data analysis. It performs bulk proteomics deconvolution using matched transcriptomes, enables cell-type-specific protein Quantitative Trait Loci mapping, and facilitates multi-modal data integration and dimension reduction."_

_We are still in the process of addressing the "ERROR: Maintainer must register at the support site." We have reached out to the core team, specifically @lshep, and are eagerly awaiting their response._

**Comment by jianhong** [comment]
Did you tried to put the your email address to lower case in the package?

**Comment by YuePan027** [comment]
Thanks for your comments @jianhong ! I just checked locally, and the registration error has been resolved after using lowercase of my email address. I will submit the updated version to the Bioconductor upstream repository.

**Comment by jianhong** [comment]
Please try to put `eval=FALSE` in your setup section and put the `library(MICSQTL)` into next executable code section in MICSQTL.rmd to fix the error.

**Comment by YuePan027** [comment]
Thank you @jianhong for your suggestions! The package passed local check and I will update the upstream soon.

**Comment by YuePan027** [comment]
@jianhong I just push the updates to the Bioconductor upstream repository. Both errors have been addressed. Thanks again for your comments and help!

**Comment by YuePan027** [comment]
@jianhong May I ask if we have to address the warning and time-out issues? 

The warning arises from a missing \value from "man/se.Rd", which serves as our package's documentation for example data and lacks a return value description. Can you please clarify if a \value return is required for example data documentation or suggest an alternative resolution?

Regarding the time-out issue, we must incorporate an adequate number of samples and biomarkers to ensure reasonable results presented in the vignette. Is there a possibility that these issues can be skipped during the review process?

We currently have a manuscript awaiting submission soon, and it would be greatly appreciated if we could have the package published before that. If these matters must be resolved, please let us know so that we can streamline the package review process. Thank you!

**Comment by jianhong** [comment]
@YuePan027 Please add code to avoid the time-out platform in your vignettes.

**Comment by YuePan027** [comment]
@jianhong Thank you for your comments! We have resolved the timeout issue by downsizing the data in the function's example code. Please let us know if we should address any other concerns.

**Comment by jianhong** [comment]
@YuePan027 Almost there! Please add `@return` in your `data-se.R` to remove the warning. Also please do not to forget to update your NEWS.md to describe the initial contents of your package. And then I think it is ready to be accepted.

**Comment by YuePan027** [comment]
@jianhong We have addressed the warning and also updated the NEWS.md. Please let us know if anything else need to be done before publication. Thank you!

**Comment by YuePan027** [comment]
@lshep Could you please help in checking the status of our package? We currently have a manuscript that is awaiting submission, and the deadline is rapidly approaching. It would be greatly appreciated if we could have the package published prior to that. Thank you!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/YuePan027.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MICSQTL")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MICSQTL

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
