### ISSUE TITLE
(inactive) HiTIMED

### ISSUE THREAD

**Issue by zzhang23** [Bioconductor/Contributions#3030]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SalasLab/HiTIMED

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by DarioS** [comment]
The proposed package is limited in terms of functionality and has inefficient coding style. Major revisions are needed.

- The majority of the function consists of copied and pasted code that does the same calculation for a different subset of rows and columns.

  ```r
  proj2[proj2<1e-05]<-0

  for (i in seq_len(nrow(proj2))) {
    z<-1/sum(proj2[i,])
    proj2[i,]<-z*proj2[i,]
  }

  proj3A<-as.data.frame(projectCellType_CP(
    tumor_beta[rownames(as.data.frame(
      HiTIMED_Library[[paste0(tumor_type,"_h3A")]])),],
      as.matrix(as.data.frame(HiTIMED_Library[[paste0(tumor_type,"_h3A")]])), 
      lessThanOne = TRUE))

  proj3A[proj3A<1e-05]<-0

  for (i in seq_len(nrow(proj3A))) {
    z<-1/sum(proj3A[i,])
    proj3A[i,]<-z*proj3A[i,]
  }
  ```

  Please convert into a single loop.

- Do not use `for` loops. Please see [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize) section of software developer's manual for Bioconductor requirement.
- Use spaces around binary operators and assignments. Please see [Use of Space](https://contributions.bioconductor.org/r-code.html#use-of-space).
- Hard-coded threshold `1e-05` used. Need to be a user-customisable parameter: `proj2[proj2<1e-05]<-0`.
- Algorithm has narrow applicability.
  > The function estimates proportions up to 17 cell types in tumor microenvironment for 20 types of carcinomas.

  How will it be useful to anyone not studying carcinoma? Please justify why this package should be part of Bioconductor and useful to many users, not only a niche audience.
  
- There is no support for S4 container classes of methylation data in Bioconductor. Interoperability with Bioconductor classes needs to be improved. [GenomicRatioSet](https://rdrr.io/bioc/minfi/man/GenomicRatioSet-class.html) class objects should be supported as input.
- `#' @importFrom minfi getBeta preprocesRaw` but neither function is used in the pacakge. Ensure that imported functions are only those ones which are used by the package.
- Software lacks checking of input parameter validity at the beginning of the function.
  ```r
  > HiTIMED_result<-HiTIMED_deconvolution(Example_Beta,"SKCM",2,"tumor")
  Error in `[.data.frame`(idmc.dat, , paste0("iDMC_", tumor_type, ".hyper")) : 
    undefined columns selected
  ```
  Please refer to [match.arg](https://blog.r-hub.io/2022/03/10/input-checking/) for how to validate categorical inputs.
- `h` paramter lacks enough details for users to confidently choose a value. Please expand explanation of it.
  > #' h Numeric variable. Specify the layer of deconvolution in the hierarchical model. Default is 6.
- Is the return value a proportion or a percentage?
  > #' @return
  > #' A matrix with predicted cell proportions in tumor microenvironment.

   ```r
  > HiTIMED_result
                       Tumor Endothelial Epithelial   Stromal Bnv
  6285625076_R06C02 77.88562   0.3804442   2.769006 0.1058968   0
  6929718079_R01C01 52.80266   8.0285040   6.912965 5.8819356   0
  6042316015_R02C02 77.84163   2.0481265   5.214845 0.4568897   0
   ```
   
  [Proportions](https://influentialpoints.com/Training/basic_statistics_proportion.htm) range from 0 to 1.

- Unit tests are inadequate. There are three `expect_error` tests. But, there are no tests for correctness of calculations. Please create more unit tests that check for correctness.
- The vignette is short and lacks any motivation and results interpretation. What do the results show and why is it important? Please add a couple of sentences of biological intepretation below the result output. Also, the package has only one function and no plotting or summarisation functions. Please incorporate more functionality into the package.
- Vignette contains non-working code. Please check that all of the code works.
```r
# Step 1: Load example data
> data("Example_Beta") 
Warning message:
In data("Example_Beta") : data set ‘Example_Beta’ not found

**Comment by lshep** [comment]
@zzhang23 do you have any updates for the concerns raised by @DarioS ?  May we expected updates to be pushed soon?

**Comment by lshep** [comment]
Please note that the resources that are included in ExperimentHub for this package require an associated package be submitted and accepted. If this review is not reactivated by next release, we will remove the entries from the ExperimentHub and delete the files from our hosting server.
