### ISSUE TITLE
curatedPCaData

### ISSUE THREAD

**Issue by Syksy** [Bioconductor/Contributions#3047]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Syksy/curatedPCaData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Syksy** [comment]
Dear @LiNk-NY ,

thank you for reviewing our package submission!

In its current state, the package runs but produces one ERROR on the 'nebbiolo2 CHECK output'-platform for unit tests.
I am checking out the ERROR reported by the bot above, and it is in:
```
* checking for unstated dependencies in tests ... OK
* checking tests ...
  Running runTests.R [10s/10s]
 [10s/10s] ERROR
Running the tests in tests/runTests.R failed.
Last 20 lines of output:
  
  Welcome to Bioconductor
  
      Vignettes contain introductory material; view with
      'browseVignettes()'. To cite Bioconductor, see
      'citation("Biobase")', and for packages 'citation("pkgname")'.
  
  
  Attaching package: 'Biobase'
  
  The following object is masked from 'package:MatrixGenerics':
  
      rowMedians
  
  The following objects are masked from 'package:matrixStats':
  
      anyMissing, rowMedians
  
  Error in library("RUnit", quietly = TRUE) : 
    there is no package called 'RUnit'
  Calls: <Anonymous> -> library
  Execution halted
```

It appears that I've misunderstood the notation, and was accidentally mixing `RUnit` and `testthat` unit test notation, while my original intention was to only use the latter for unit tests. I will correct this mistake and bump it as soon as I'm done testing it on my own system. My apologies as I was not able to produce this error, as I had both unit test packages available.

**Comment by LiNk-NY** [comment]
Hi @Syksy 
Thank you for your submission. 
Please see the review below.
Best,
Marcel

---

# curatedPCaData #3047

* Please separate the analysis functionality from the infrastructure. The
package should only deliver the data to the user and demonstrate how to
obtain the data from `ExperimentHub`.
* The package has extensive efforts to work with the metadata but these
can be avoided by strategically using metadata from the `ExperimentHub`
resources.

## DESCRIPTION

* Looks good.
* The `BiocGenerics` Suggests: seems out of place.
* The CC license is not good for software consider using a different license.

## NAMESPACE

* Avoid importing `testthat` and the `expect_s4_class` function. To test for
S4 class, use the name of the class, e.g., `is(X, "KnownS4Class")`

## vignettes

* Consider restricting the text to 80 column width. It makes it easier to
review and maintain.
* The demos in the vignettes should show the user how to obtain the data,
it does not necessarily need to show the user how to analyze it. The latter
would be more appropriate in a separate workflow package.
* Remove the analysis vignette as it is out of the scope of the package.
* Consider using `MatchedAssayExperiment` instead of intersecting `colnames`
and `"sample_names"` in the `colData` (Decipher vs BCR section).
* Consider using `$` to access `colData` columns, e.g., `mae_ren$sample_type`
* Consider using `TCGAutils::TCGAprimaryTumors` for subsetting for primary
tumor samples with TCGA data.
* The Oncoprint example looks complicated for a new user. If you are working
with TCGA data consider using `TCGAutils::oncoPrintTCGA`, otherwise consider
adding a helper function.
* Reduce the amount of code in the `overview.Rmd` vignette. Pre-processing
with `eval(parse(...))` is usually not the way to go. It seems that more
needs to be done at the dataset and package level to avoid the juggling
of `metadata` in the vignette. Add helper functions in the package to extract
and create a single row for each of your summaries of interests, for example,
`gleasons(mae_object)` would return one row as given by the pre-processing
step in the vignette.
* Consider using `*.bib` reference file rather than hard-coding references in
the vignette.
* Use single backticks to enclose code nouns, e.g. `colData` and
`MultiAssayExperiment`

## R

* Use a more descriptive argument than `slots` in `getPCa`
* Consider refactoring the logic in `wrapperSortonco`. It may be safer and
more robust to apply a function recursively instead.

## tests

* Consider increasing the coverage:
```r
> covr::package_coverage()
curatedPCaData Coverage: 24.14%
R/wrappers.R: 0.00%
R/getpca.R: 76.92%
```

**Comment by Syksy** [comment]
Hi @LiNk-NY ,

thank you for a very throughout review of the package; the points raised make sense, and I am in the process of addressing them.

There were however couple items for which I would like to inquire more information and advice; these mainly stem from the fact that the package is associated to a publication that is already accepted (the journal in question is _Scientific Data_), and is in the editorial phase:

> The CC license is not good for software consider using a different license.

I do agree with this sentiment, and would normally use MIT or GPL-3; however, the editor of the journal requested here prior to acceptance (citing verbatim, the package was previously GPL-3 license):
"_* Please issue your code with a CC0 or CC-BY licence. The current GNU GPL is too restrictive to comply with Scientific Data's publication policies._"

And we've already complied with the above request. Would it be possible to continue having the current CC-BY 4.0 license, as this appears to be a requirement for this particular journal? To my understanding, it would be acceptable for a software package focusing on data rather than code to use the CC licenses.

> Please separate the analysis functionality from the infrastructure. The
package should only deliver the data to the user and demonstrate how to
obtain the data from ExperimentHub.

I understand your point and see that for a package labeled `ExperimentData` this makes sense, thus we're pursuing this. However, for the publication, we did already create a lot of vignette material which reproduced perfectly the conclusions and even figures of the publication, and this was part of the appeal as the reader could easily track down how the resources were utilized. 

Is there some way you could suggest that we could keep vignettes? My first intuition is to separate these into an another package, call it for example `curatedPCaAnalysis`, and keep linking to its GitHub in the current package for user/reader convenience. All the computational portions as well as downstream inference would be then still easily accessible, while for this package we'd focus solely on the data and its retrieval as requested here. 

My plan would be that we would then later return to this analysis-focused package and see if it'd be Bioconductor-compatible or not, after the `curatedPCaData` has been revised according to the requested changes.

Thank you for any insight or advice!

**Comment by LiNk-NY** [comment]
Hi @Syksy 

> And we've already complied with the above request. Would it be possible to continue having the current CC-BY 4.0 license, as this appears to be a requirement for this particular journal? To my understanding, it would be acceptable for a software package focusing on data rather than code to use the CC licenses.

I am no authority in licensing but it seems that we do have some packages using the CC license already. 

> However, for the publication, we did already create a lot of vignette material which reproduced perfectly the conclusions and even figures of the publication, and this was part of the appeal as the reader could easily track down how the resources were utilized.

The vignette materials belong in a separate repository. The data and its analysis should be separate entities and of course the latter depends on the former. Consider creating your own `workflow` package (which would be a compilation of your vignette material) that depends on the experiment data package. 

> Is there some way you could suggest that we could keep vignettes? My first intuition is to separate these into an another package, call it for example `curatedPCaAnalysis`, and keep linking to its GitHub in the current package for user/reader convenience. All the computational portions as well as downstream inference would be then still easily accessible, while for this package we'd focus solely on the data and its retrieval as requested here.

Yes, the `curatedPCaAnalysis` idea relates to my response above and it would work well to separate data and analyses.  It could be achieved in package format where `curatedPCaData` is a listed dependency in the `DESCRIPTION` file. 

Note that the vignettes in the current package should only demonstrate to the user how to obtain the data and refer users to `curatedPCaAnalysis` for example analysis workflows using the data.

**Comment by Syksy** [comment]
Above ERROR resulted from the fact that the build service uses R 4.3.1, while BiocCheck had suggested that I elevate the package's R dependency to R 4.4.0. I have now reverted back the dependency to R version 4.3.0.

**Comment by Syksy** [comment]
Hello @LiNk-NY 

Thank you once again for taking the time to review our package submission.

As you will find above, the 0.99.3 submission check passes (with my little blunder on too high R 4.4 requirement on 0.99.2, apologies about that).

I have compiled a point-by-point list of your original review citing it verbatim at: https://github.com/Syksy/curatedPCaData/issues/44

At each check-box you'll find your original comments, with the response and corresponding links below each point.
I have tried my best to directly list commits and other practical changes that have now been implemented to the package based on your review comments. I hope you will find these improvements satisfactory, making `curatedPCaData` suitable to be a Bioconductor-package of this type.

**Comment by LiNk-NY** [comment]
Hi @Syksy 
Sorry for the delay. 
Thank you for making those changes. Can you bump the version for another build? 
Can you please post the list in issue https://github.com/Syksy/curatedPCaData/issues/44 as a comment on this thread? 
Thank you. 
Best,
Marcel

**Comment by Syksy** [comment]
Hello @LiNk-NY 
thank you, much appreciated!
Above is the latest version bump reported by the bot, which passed cleanly. 
Here is the original point-by-point response provided for the review (unedited from Aug 10th):

### *curatedPCaData https://github.com/Bioconductor/Contributions/issues/3047*

- [x] _Please separate the analysis functionality from the infrastructure. The
package should only deliver the data to the user and demonstrate how to
obtain the data from ExperimentHub._

OK; As discussed in the submission thread for BioConductor at https://github.com/Bioconductor/Contributions/issues/3047#issuecomment-1625486043 , these downstream vignettes are to be moved to a new `workflow` package called `curatedPCaWorkflow` at: https://github.com/Syksy/curatedPCaWorkflow . Work will continue there-in regarding the proposed improvements. Please see answers below for specific actions taken toward this package-wide adjustment.

- [x] _The package has extensive efforts to work with the metadata but these
can be avoided by strategically using metadata from the ExperimentHub
resources._

Multiple steps have been taken to address this and are further elaborated in answers below; briefly:
- Functionality that previously existed inside the main `overview` vignette has been moved to `/R/getpcasummaries.R`, and these functions are generalizable to any requested variable, are not dataset-specific, and contain e.g. standard documentation and unit testing.
- Functionality that was deemed to be more toward downstream analyses has been moved away from the package, in particular functions contained previously at `/R/wrappers.R`.
- The new functions utilize strategically both the internally provided `metadata.csv` (for example function `getPCaStudies`) as well as the clinical metadata accessible via `colData` (for example functions `getPCaSummaryTable`, `getPCaSummarySurv`, `getPCaSummarySamples` , and `getPCaSummaryStudies`).

### **DESCRIPTION**

- [x] _Looks good._

OK

- [x] _The BiocGenerics Suggests: seems out of place._

OK; Addressed in https://github.com/Syksy/curatedPCaData/commit/7ba59f5fb1bd917a0a0fc48e5245aad34cfec51b ; in addition, the package dependencies have been made more lean as the functions at `/R/wrappers.R` are no longer present, removing the `import` need for e.g. `dplyr` and `stringr`.

- [x] _The CC license is not good for software consider using a different license._

OK; CC-BY 4.0 should still be fine based on discussion at https://github.com/Bioconductor/Contributions/issues/3047#issuecomment-1625486043

### **NAMESPACE**

- [x] _Avoid importing testthat and the expect_s4_class function. To test for
S4 class, use the name of the class, e.g., is(X, "KnownS4Class")_

OK; This has now been adjusted to using just native R tests in: https://github.com/Syksy/curatedPCaData/commit/4c1a481a82060d371da958c23980853ac0080ed5 and the tests themselves were subsequently extended to cover the new functions at https://github.com/Syksy/curatedPCaData/commit/32352235fd9f0df8c04fd5d677ae2fb53c2b984c and https://github.com/Syksy/curatedPCaData/commit/ed9d0b8b2b0fd1ab2c8fd7647224fa05a062caa8 .

### **vignettes**

- [x] _Consider restricting the text to 80 column width. It makes it easier to
review and maintain._

OK; this formatting issue has been addressed in https://github.com/Syksy/curatedPCaData/commit/bb76b0121fdd8fcd7e949c583160eb36d1c04db4 . Furthermore, the rest of the code has also been double-checked for formatting (multiples of 4 spacebar indents, no tabs, char width 80), of which vast majority are fixed in e.g. https://github.com/Syksy/curatedPCaData/commit/019a304e9dffaf0b92046a308486dd80b6b5eec8 . The 12 lines (~0% of all code) longer than 80 chars and 11 lines (~0% of all code) that violate 4*spacebar multiples are special cases such as long URLs or automatically generated package Rd TeX-like code, respectively.

- [x] _The demos in the vignettes should show the user how to obtain the data,
it does not necessarily need to show the user how to analyze it. The latter
would be more appropriate in a separate workflow package._

OK; Notable effort has been put into revising the `overview` vignette so it exemplifies this effectively with generalizable code, while rest of the vignettes that had an analysis focus have been now shifted to the separate `curatedPCaWorkflow`-package. See comments below.

- [x] _Remove the analysis vignette as it is out of the scope of the package._

OK; Done in https://github.com/Syksy/curatedPCaData/commit/ee1c94bd8e09d9e6d072e5c5f27dd1655bcbc872 by moving to use `curatedPCaWorkflow` instead.

- [x] _Consider using MatchedAssayExperiment instead of intersecting colnames
and "sample_names" in the colData (Decipher vs BCR section)._

OK; This pointer has been addressed in the PR by @ACSoupir at https://github.com/Syksy/curatedPCaData/pull/45 . However, as the `analyses` vignette has now been incorporated into the workflow package instead, this fix was not merged into `curatedPCaData`. This fix will instead be incorporated into the `curatedPCaWorkflow`.

- [x] _Consider using $ to access colData columns, e.g., mae_ren$sample_type_

OK; After the other fixes both into the `overview` vignette as well as the generalized functions provided now in `/R/getpcasummaries.R`, all calls of type `mae_obj[,"variable"]` are now instead formatted as `mae_obj$variable`.

- [x] _Consider using TCGAutils::TCGAprimaryTumors for subsetting for primary
tumor samples with TCGA data._

OK, at least partially; this revision request was not implemented as suggested here _per se_. I explored both the `TCGAutils` (and the `curatedTCGAdata`) for this purpose. However, I ended up with the conclusion that this would've been best implemented as part of the data curation step in `curatedPCaData`, rather than implemented here when we're just offering the "window" to the data. In all of our datasets, the `sample_type` field in `colData` was extracted from the original source and represents the sample types (primary, normal, metastatic, ...). In this respect, I feel it would be a bit much to bring in a dependency just for TCGA, when this information is already available in the `colData`. However, to address the original purpose of subsetting to certain sample types, I have now modified the main `getPCa` function to allow subsetting the creation of the MAE object via `MultiAssayExperiment::subsetByColData` which will utilize the `sample_type` available in our data : https://github.com/Syksy/curatedPCaData/commit/ba50efa4e16d266593589403709ae6a4ffa9f9cf . I hope this adjustment fulfills the requested improvement to the package - if not, please let me know and I will revise accordingly to the best of my ability.

- [x] _The Oncoprint example looks complicated for a new user. If you are working
with TCGA data consider using TCGAutils::oncoPrintTCGA, otherwise consider
adding a helper function._

OK; The oncoprint related functions and wrappers have been now moved to the new `curatedPCaWorkflow` package (e.g. commit https://github.com/Syksy/curatedPCaData/commit/62be8a42449421dac6888d1d3c787242be8ea192 ). In hindsight, they are somewhat downstream analyses already, and therefore are better suited for this workflow-package. Thus, the oncoprint and their related functions are no longer part of the `curatedPCaData`-package.

- [x] _Reduce the amount of code in the overview.Rmd vignette. Pre-processing
with eval(parse(...)) is usually not the way to go. It seems that more
needs to be done at the dataset and package level to avoid the juggling
of metadata in the vignette. Add helper functions in the package to extract
and create a single row for each of your summaries of interests, for example,
gleasons(mae_object) would return one row as given by the pre-processing
step in the vignette._

OK; This is a fair point, and indeed should've been the design already in the start. Notable effort has now been done to move the functionality previously coded inside the `overview` vignette, and made exported by the package itself accompanied by suitable examples, testing, and documentation. To enumerate these functions and key commits, of which majority resides now in the file located at `R/getpcasummaries.R`:
- `getPCaSummaryTable` : https://github.com/Syksy/curatedPCaData/commit/6d1aaaae356f11c1cdc73715aba9540e353ee2cc
- `getPCaSummarySurv` : https://github.com/Syksy/curatedPCaData/commit/6d1aaaae356f11c1cdc73715aba9540e353ee2cc
- `getPCaSummarySamples` : https://github.com/Syksy/curatedPCaData/commit/e4129376e1b6280bf14483baf908e51852bdfc43
- `getPCaSummaryStudies` : https://github.com/Syksy/curatedPCaData/commit/b6bffd1ef4b3e669583576e9acc256d5e9934d84 and https://github.com/Syksy/curatedPCaData/commit/f8ef61ce7aec3e6da965afdbe65b5a5b46b19bea
- `getPCaStudies` : https://github.com/Syksy/curatedPCaData/commit/71c73c6cc4b44401c730d9e7f268f8a9942fcf0c

With the above functions now in use by the vignette and exported by the user, the revision(s) addresses the above mentioned issues and clean up the vignette (Rmd commits mainly in https://github.com/Syksy/curatedPCaData/commit/2f1b02a34948400e99cf18c88b5053b3b6b81981 , https://github.com/Syksy/curatedPCaData/commit/90a37f3ba3609a4870da170c8fc375bcaf475a16 , https://github.com/Syksy/curatedPCaData/commit/7abab8cab289c3f31e587341874ae6121d4a248b )

- [x] _Consider using *.bib reference file rather than hard-coding references in
the vignette._

OK; The citations have now been revised as requested in https://github.com/Syksy/curatedPCaData/commit/1940b500d809ac06046f120d280bb9f2de49731a and https://github.com/Syksy/curatedPCaData/commit/dff5dee69bc1506bb6485913bea998d43db1ad86 .

- [x] _Use single backticks to enclose code nouns, e.g. colData and
MultiAssayExperiment_

OK; These mentioned triple backticks have been corrected to single backticks in https://github.com/Syksy/curatedPCaData/commit/0b46706998a9b783c023dcff28e79fa10f3045ea .

### **R**

- [x] _Use a more descriptive argument than slots in getPCa_

OK; The name of the argument has now been changed to `assays` in order to be more in line with the naming conventions in `MultiAssayExperiment` via commit https://github.com/Syksy/curatedPCaData/commit/633d17eb510a5d9c1375b88901af409d20fe718f .

- [x] _Consider refactoring the logic in wrapperSortonco. It may be safer and
more robust to apply a function recursively instead._

OK; This function has now been moved to be as part of the `curatedPCaWorkflow` instead, as it relates to oncoprints ( https://github.com/Syksy/curatedPCaData/commit/62be8a42449421dac6888d1d3c787242be8ea192 ).

### **tests**

- [x] _Consider increasing the coverage:_
> covr::package_coverage()
curatedPCaData Coverage: 24.14%
R/wrappers.R: 0.00%
R/getpca.R: 76.92%

After adjustments such as moving the wrappers focused on e.g. oncoprints out of the package ( https://github.com/Syksy/curatedPCaData/commit/62be8a42449421dac6888d1d3c787242be8ea192 ), adding new functions for replacing the ones previously defined inside vignette (e.g. https://github.com/Syksy/curatedPCaData/commit/6d1aaaae356f11c1cdc73715aba9540e353ee2cc , https://github.com/Syksy/curatedPCaData/commit/e4129376e1b6280bf14483baf908e51852bdfc43 , https://github.com/Syksy/curatedPCaData/commit/b6bffd1ef4b3e669583576e9acc256d5e9934d84 , https://github.com/Syksy/curatedPCaData/commit/71c73c6cc4b44401c730d9e7f268f8a9942fcf0c), and extending the testing coverage ( https://github.com/Syksy/curatedPCaData/commit/32352235fd9f0df8c04fd5d677ae2fb53c2b984c ), the output for this coverage testing is as follows:

> covr::package_coverage()
curatedPCaData Coverage: 89.60%
R/getpca.R: 79.61%
R/getpcasummaries.R: 94.87%

Thus, key functionality is tested, with the parts not covered related to marginal cases like download timeout.

**Comment by Syksy** [comment]
> Hi @Syksy Sorry for the delay. Thank you for making those changes. Can you bump the version for another build? Can you please post the list in issue [Syksy/curatedPCaData#44](https://github.com/Syksy/curatedPCaData/issues/44) as a comment on this thread? Thank you. Best, Marcel

Dear @LiNk-NY 
Thank you once again for taking a comprehensive look at the package - however, would it be possible to have this review round some time soon? We had originally hoped to aim for the Bioconductor 3.18, and the window seems to be closing.
Apologies for the extra poke!

**Comment by LiNk-NY** [comment]
Apologies for the delay @Syksy 

The release has been a handful to say the least. 
Thank you for making those changes. The vignette looks to be in good shape. 
I noticed that you are running `getPCa` on all available studies. Although there is caching implemented, I think it would be more natural for the user to see an example with a single study or smaller subset of studies, e.g., `getPCa('abida')` and show how the package works with those. 

Note. I currently can't do 

```r
maes <- lapply(studies[1:2], getPCa)
studytable <- getPCaSummaryStudies(maes)
```


Best regards,
Marcel

**Comment by LiNk-NY** [comment]
@Syksy 
Any updates? Thanks!

**Comment by Syksy** [comment]
Dear @LiNk-NY ,
thank you for your patience - I hope to have now addressed the remaining issues, and you can find the latest `curatedPCaData` v0.99.5 build above by the bot.

> The release has been a handful to say the least. Thank you for making those changes. The vignette looks to be in good shape. I noticed that you are running `getPCa` on all available studies. Although there is caching implemented, I think it would be more natural for the user to see an example with a single study or smaller subset of studies, e.g., `getPCa('abida')` and show how the package works with those.

Thanks, the vignette has now been refined further; in order to address the practical show-casing of a single study and how to handle the MAE-object, I've added a new section mainly with this commit: https://github.com/Syksy/curatedPCaData/commit/14dd8d269d7317a6588e76dbd96b0b664568f961

I did not include the `abida` study as it consists of metastatic samples only, and is therefore a very specialized study. Instead, I picked the representative `taylor` study. As you can see from the `overview` vignette's new Section 5, this latest addition showcases retrieval of data, its subsets (both in `assays` and `sample_type`s), and then proceeds to standard survival related analyses such as Kaplan-Meier curves and a Cox proportional hazards model. These were part of readily suggested `survival` and `survminer`, so no further `Suggests` were necessary to add this. At the same time, this new section briefly highlights such useful functions as `wideFormat` and `longFormat` from `MultiAssayExperiment` for their importance to end-users.

Hopefully you'll find this use-case useful in respect to the request above.

> Note. I currently can't do
> 
> ```r
> maes <- lapply(studies[1:2], getPCa)
> studytable <- getPCaSummaryStudies(maes)
> ```

This was a mistake on my part, with building the `getPCaSummaryStudies` function with the implicit assumption that it is either given a named list or a character vector of study names. In this cited case the function was caught in an error, as a non-named list is given instead. This issue has now been addressed in the following commit: https://github.com/Syksy/curatedPCaData/commit/b78ccff4450b1b65407b67bef368ac67b1d369a0
After this adjustment, above issue is resolved.

Further small commits are also added, mainly with minimal fixes or e.g. code formatting.


I hope that you would find above adjustments suitable for these requested revisions,
Kind regards,
Syksy

**Comment by LiNk-NY** [comment]
Hi Syksy, @Syksy 
Thank you for making those changes. 
Your package has been accepted. 
Best regards,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Syksy.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("curatedPCaData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/curatedPCaData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
