### ISSUE TITLE
DASC -- New package for Batch Detection

### ISSUE THREAD

**Issue by aayushraman** [Bioconductor/Contributions#305]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/aayushraman/DASC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by aayushraman** [comment]
There is a change in the maintainer's mail id to 982869874@qq.com. It has been updated on the DESCRIPTION file under DASC package.

**Comment by aayushraman** [comment]
Hello Sir, 

We have updated our package. We went through the errors reported in the above link. As per our `DESCRIPTION` file, we have mentioned that `NMF`, `cvxclustr` and `Biobase` packages (as Imports) are required by our package. We tried building our package with and without the above packages. We didn't get any error when the packages, however, got the exact same error when it was not present. I would request if you can build DASC after installing the required packages.

We have improved our running time for building the package by reducing the time taken by running the example in our vignette. We would request if you can submit our package to the queue.

Thanks,
-Ar

**Comment by vobencha** [comment]
The single package builder (SPB) report shows errors and timeouts:
http://bioconductor.org/spb_reports/DASC_buildreport_20170306051600.html

The package must pass R CMD build and check on all 3 platforms before I do a full review. Please change the version to 0.99.1 and bump the 'z' portion each time you want the SPB to do a new build. For example, 0.99.2, 0.99.3, 0.99.4 etc.

All of this is documented here:
https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md

Valerie

**Comment by aayushraman** [comment]
We have updated our code and made all the necessary changes. As per our DESCRIPTION file, we have mentioned that `NMF`, `cvxclustr` and `Biobase` packages (as Imports) are required by our package. Can you please re-build our package ?

Thanks,
-Ar

**Comment by vobencha** [comment]
I do not manually rebuild your package. The Single Package Builder is an automated process. A build is triggered by a version bump (which is done by you). Please read instructions here: https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md

**Comment by aayushraman** [comment]
Hello, 

My current version is 0.1.2. Earlier it was 0.1.1. and then one of core engineers from Bioconductor told me to do version bump again : https://stat.ethz.ch/pipermail/bioc-devel/2017-March/010585.html, so now it becomes 0.1.2. 

Do I need to change the version to 0.99.3 or 0.1.1 now ? I am sorry I am little confused.

Best,
-Ar

**Comment by vobencha** [comment]
@aayushraman yes, you should change the version to 0.99.*, however, I think the SPB should re-build based on a bump in 'z' regardless.
@lshep , can you look into why we didn't get a new build for this one?
Thanks.
Val

**Comment by lshep** [comment]
Please change to 0.99.z  standard.  There haven't been any pushes.  Could you please check that the webhook was set up.  I sent the information on your question on the mailing list but here is the information again: 
https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook

**Comment by aayushraman** [comment]
I have changed the version to 0.99.1 and the webhook has been properly set up. Here is the screen shot of my webhook page. Do I need to do anything else ?

Thanks,
-Ar

<img width="1088" alt="screen shot 2017-03-17 at 2 18 44 pm" src="https://cloud.githubusercontent.com/assets/4062603/24059334/b812eabc-0b1c-11e7-9be0-5a8bfbdb288c.png">

**Comment by lshep** [comment]
I'm not sure why you didn't get a rebuild.  I will manually push this on and then hopefully should you need any revisions, a new version bump should trigger a build.

**Comment by aayushraman** [comment]
I will change the version if I require any revisions. Thanks a lot!

**Comment by aayushraman** [comment]
Hi @vobencha and @lshep 

I hope you are doing good.

Regarding ERRORS: I am not sure why I am getting "ERROR" when my package is getting built on WINDOWS system (Windows Server 2012 R2 Standard/x64). We have already mentioned Biobase as one of the packages to be imported before the built. The previous report (http://bioconductor.org/spb_reports/DASC_buildreport_20170317154938.html) didn't show any errors too. 

Am I missing anything ?

Regarding WARNINGS and Notes: 

```
This is a software package
    # of chunks: 26, # of eval=FALSE: 14 (53%)
    * WARNING: Evaluate more vignette chunks.
```

The reason I am not evaluating a lot of my code is because my main function, convexBatch takes more than > 5 mins to run and therefore, it would exceed the limit required for running the `check` command. 

```
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * NOTE: Consider multiples of 4 spaces for line indents, 1
      lines(0%) are not.
    First 1 lines:
      man/convexBatch.Rd:8   nrun, spanning = FALSE, annotation)
    See http://bioconductor.org/developers/how-to/coding-style/
```

I am not sure what I am missing here. Where do I have use the indent in my function definition ? Can you please help me ?

Thanks,
-Ar

**Comment by vobencha** [comment]
Hi,
You can ignore the Biobase error - that is a problem on our end. The important thing to focus on now is the run-time and sample data size.

You said you've commented out the vignette code (and probably some examples) in order to meet the build/check time requirements. This is not the right approach. The purpose of the nightly builds is to confirm the package functions operate as expected and no changes in R or other dependencies have broken the package function. By commenting out the code you've bypassed these checks and balances. Each exported function should be evaluated at least once. 

Please revisit the 'slow' functions and look for inefficiencies. This page might be helpful: http://www.bioconductor.org/developers/how-to/efficient-code/.

Another suggestion is to use smaller sample data. The functions should be flexible enough to work on a small subset as well as the large data files they are intended for. 

Keep these points in mind from the guidelines:
http://www.bioconductor.org/developers/package-guidelines/
- size of built tarball must be >= 4 MB
- package must pass R CMD check --no-build-vignettes in <= 5 min

Also, please 
- Rename your functions to all camelCase or all underscores. Currently you have a mixture of dots, underscores and camelCase.
- Add examples to all man pages.

Valerie

**Comment by aayushraman** [comment]
@vobencha I am not sure why I got `VERSION BUMP REQUIRED` label, when I changed the version from 0.99.2 to 0.99.3 . I am not sure why I got a timeout error ? The runtime pass R CMD check --no-build-vignettes for my package ~ 3 min and 45 sec in my windows computer.

-Ar

**Comment by aayushraman** [comment]
Hi @vobencha and @lshep

I hope you are doing good. I am not sure why I got a timeout error. The runtime for R CMD check for my package on my windows computer is ~ 3 min and 45 sec. Can you please check if the problem is 
with the package of with the build system ?

Thanks,
-Ar

**Comment by lshep** [comment]
It is getting hung up on the tests. Please review the tests you are performing.

**Comment by aayushraman** [comment]
@lshep Thanks for letting me know. Can I look at the `TIMEOUT` error that came from windows server, **tokay2** ? I cannot see the error in the report above (http://bioconductor.org/spb_reports/DASC_buildreport_20170328150219.html). Also, how is it possible that my tests are running fine on linux and mac and but not on windows ?

**Comment by aayushraman** [comment]
@lshep and @vobencha Thanks a lot for helping us to improve the package.

**Comment by vobencha** [comment]
Hi,
Please see comments and suggestion below.

1. vignette
  - There is no need for user to manually check that package dependencies are installed. That is the job of the NAMESPACE and DESCRIPTION. You have all 3 of these packages in Imports so these will be downloaded and installed when the user invokes biocLite("DASC"). Please remove this line:
```
Please, make sure to that NMF, cvxclustr and Biobase are installed in your system before running DASC.
```
  - Explain what type of data are in the Stanford dataset (counts, expression, ...).
  - Section 7 has this line:
```
We are currently working on vignette and will be uploading more examples soon.
```
If the vignette is not complete please let me know when it is. Otherwise remove the line.

2. man pages

The man pages need quite a bit of work. You have a good background section in the vignette and some of that infromation needs to be included on the man pages. Please add and fill out a \details section and consider renaming some functions with non-nonsensical names.

- function names
These names are not descriptive, please consider renaming:
my_seeding_method.Rd
my_objective_function.Rd
my_algorithm.Rd 
update_G.Rd
W_toVector.Rd
get_class.Rd: It doesn't look like this function 'get a class' at all ...?

- add more details
merge.Rd: Even though this is not exported the man page tells the user very little about what type of nodes (from igraph?) are being merged and how. Also need to add an example.

  convex_batch.Rd: Why is this function called convex batch? What does it do? Please add \details section that gives some background of what it is and when it would be used.

Let me know if you have questions.
Valerie

**Comment by aayushraman** [comment]
Hi @vobencha 

We have made all the changes that you requested us to do. I think the error that we are getting is not due to the package but due to the absence of the package in your windows system. We are looking forward to your inputs.

Best,
-Ar and @HaidYi

**Comment by aayushraman** [comment]
Hi @vobencha

We have made all the changes that you requested us to do. I think the error that we are getting is not due to the package but due to the absence of the package in your windows system. We are looking forward to your inputs.

Best,
-Ar and @HaidYi

**Comment by vobencha** [comment]
@lshep, can you please kick off another build when you get a chance?

**Comment by aayushraman** [comment]
@lshep sure.. here you go!

**Comment by vobencha** [comment]
Thanks for making the changes. Just a few things left.

1) Please add this paragraph from the vignette to the stanfordData.Rd man page:
Stanford gene expression dataset (Chen et. al. PNAS, 2015; Gilad et. al. F1000 Research, 2015). It is a filtered raw counts dataset which was published by Gilad et al. F1000 Research. 30% of genes with the lowest expression & mitochondrial genes were removed (Gilad et al.F1000 Research).

2) There should only be one .Rmd file in vignettes/ along with png files. Please remove all others:
```
~/proj/git/software/DASC/vignettes >ls
ClusterNumber_Fig4.png   DASC_html.html  DASC_pdf.pdf  NMF_Rank_Fig3.png
Consensus_Plot_Fig2.png  DASC_html.Rmd   DASC_pdf.Rmd  PCA_Plot_Fig1.png
```
3) The merge.Rd man page still does not describe what a 'node' is. Is this a class from the DASC package or another package?

Valerie

**Comment by aayushraman** [comment]
@vobencha Thanks for your comments. 

1. I will add it to the man files.
2. Can I have put extra .Rmd and png files inside a `ext` or `inst` folder ? 
3. Based of the dataset, we form a graph and traverse the graph such we are able to find and merge 2 disjoint sets. This is not a class from DASC or another package. 

-Ar

**Comment by aayushraman** [comment]
Hi @vobencha

We have made the changes that you asked us to do. Please let us know if you have any more questions. 

Best,
-Ar and @HaidYi

**Comment by vobencha** [comment]
- You can have more than 1 .Rmd file in vignettes/ if you have more than one vignette. You can also have multiple figure files, .png or .pdf etc. in vignettes/. Please put the .Rmd and .png files used to create your vignette in the vignettes/ directory and remove them from inst/extdata.

The files you should delete are the .html and .pdf files. The vignette is created real time when R CMD build is run. In general there is no reason to have static html and pdf files around. Why are these files in the package?

- The point of #3 above was to get you to add this detail to the man page, not explain it to me here in the package review. Please add this explanation to the merge.Rd man page.

Valerie

**Comment by aayushraman** [comment]
Hi @vobencha 

I have made the changes to the package. I have removed .html & .pdf files and moved the files to vignette directory.  I have added the explanation about merge function in the Rmd file. 

-Ar

**Comment by vobencha** [comment]
Thanks for making the changes. The package is approved - you should get an email in the next week with svn instructions and next steps.
Valerie

**Comment by aayushraman** [comment]
@vobencha Thanks a lot for improving our package.

-Ar
