### ISSUE TITLE
SARC

### ISSUE THREAD

**Issue by Krutik6** [Bioconductor/Contributions#3071]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Krutik6/SARC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by DarioS** [comment]
Overall, the package implementation is good but there are some issues which need to be addressed.
- Please choose a more informative title for the vignette than "SARC_guide". See [DESeq2](http://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html) and [batchelor](https://bioconductor.org/packages/release/bioc/vignettes/batchelor/inst/doc/correction.html) for examples.
- There are duplicate rows in test data file.
```r
> test_bed  # Why is second and third row exactly the same?
      SAMPLE CHROM     START       END TYPE VALUE       TOOL
1 Sample_616  chr1 161487763 161565521  DUP     1 exomeDepth
2 Sample_617  chr1  17034387  17090909  DEL     0 exomeDepth
3 Sample_617  chr1  17034387  17090909  DEL     0 exomeDepth
```
- The example BED files do not conform to the [BED file standard](http://genome.ucsc.edu/FAQ/FAQformat.html#format1). Please do not redefine widely used bioinformatics file formats. Also, the `data` directory should contain .bed files, not .rda files of data frames claiming to be BED format.
- The package only works with copy number variants. Why is [MultiAssayExperiment](https://bioconductor.org/packages/release/bioc/html/MultiAssayExperiment.html) used as the main data container?

```r
> SARC <- regionSet(bed = test_bed, test_cov)
> SARC
A MultiAssayExperiment object of 0 listed
 experiments with no user-defined names and respective classes.
 Containing an ExperimentList class object of length 0:
```

 Please redesign it to use [RaggedExperiment](https://bioconductor.org/packages/release/bioc/html/RaggedExperiment.html) instead.

> This package provides a flexible representation of copy number, mutation, and other data that fit into the ragged array schema for genomic location data.

- Integration with existing Bioconductor functionality needs improvement. Don't use external utilities if not necessary.

> The cov file should comprise of coverage from BAM files. These can be retrieved using SAMTOOLS or BCFTOOLs.

Please replace this by runnable code using `coverage` function from [GenomicAlignments](https://bioconductor.org/packages/release/bioc/html/GenomicAlignments.html) applied to a BAM file in data folder.

- The package advocates for comparing read coverage between different samples directly. This is not sensible. What if sample A has 50 million reads in total but sample B has 200 million reads in total? Read coverage is not a valid indicator of copy number unless it is scaled by the library size.

- Function examples should not use `library(packageName)` but check for presence of package installed. Please see [Suggested Packages](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages) instructions for how to best load a package in an Examples section.

- It is not clear if test data 1 and 2 are simulated data or experimental biological data. Please state the source of the data.

- Unit tests are inadequate. For example, test_stats.R tests the number of columns and column names but not whether the expected genes are significantly different or not. Please test that the calculations of your algorithm are correct.
```r
expect_equal(ncol(x), 13)
expect_equal(names(x)[12], "CNV.SCORE")
expect_equal(names(x)[13], "CNV.TIER")
```

- All of the examples use data packages such as `TxDb.Hsapiens.UCSC.hg38.knownGene`. Please comment on the applicability of SARC to other species such as _Mus musculus_. The generalisability of it should be explained in the vignette.

**Comment by Krutik6** [comment]
Cheers @DarioS. Will aim to address each point within 2-weeks.
Krutik

**Comment by Krutik6** [comment]
Dear @DarioS ,

Thank you for your comments, and apologies in the delay in resubmission - had github issues (thanks @lshep for helping with them). I believe this tool has been improved for the better of the users and the research community. I have listed the suggestions along with a response. Any minor additional changes have bee listed in the end of this response. 

1. Please choose a more informative title for the vignette than "SARC_guide". See DESeq2 and batchelor for examples.
Yes, this would be for the best. The title has been renamed to "Tutorial of the SARC R Package. Flagging the confidence of CNVs from WES/ WGS cohorts."

2. There are duplicate rows in test data file. 
Sorry this was a mistake - third row was from the tool clinCNV. This has been corrected for test_cnv and test_cnv2.

3. The example BED files do not conform to the BED file standard. Please do not redefine widely used bioinformatics file formats. Also, the data directory should contain .bed files, not .rda files of data frames claiming to be BED format.
You are correct - this would have just caused confusion. Instead, I have renamed these to `cnv` files. I have mentioned that they are inspired by, and perform the same function as CNV .BED files, but are a different entity. I thought it would be simpler to create a specific class of file, rather than continue with claiming I had used .bed files - when I hadn't. Furthermore, I did prefer to keep .rda files because they could be compressed and were simple to call with data(x), so this was an all-round better solution I think.

4. The package only works with copy number variants. Why is MultiAssayExperiment used as the main data container?
Please redesign it to use RaggedExperiment instead.
I had used MAE because I was used to them - I have completely changed to RaggedExperiments now. This has also been explained in the vignette. I have altered the DESCRIPTION file to be dependant on RaggedExperiment instead and removed any mention of MultiAssayExperiments.

5. Please replace this by runnable code using coverage function from GenomicAlignments applied to a BAM file in data folder.
I have added a small .bam and bam.bai file in the /inst/extdata folder and provided a small indication of how this could be used in the vignette. I did not wish to overburden the SARC vignette with another tool - so I have added the tutorials of GenomicAlignments. I have also added a link for bamsignals as I thought this was another good Bioconductor tool to perform a similair job.

6. The package advocates for comparing read coverage between different samples directly. This is not sensible. What if sample A has 50 million reads in total but sample B has 200 million reads in total? Read coverage is not a valid indicator of copy number unless it is scaled by the library size.
I agree - at first I avoided normalisation as I thought this would skew very small variants, but after running some comparisons, this was a very useful comment. I have given an example in the vignette on how to normalise to RPM also, and mention several times that the data has been normalsed - and removed any mention of raw coverage.

7. Function examples should not use library(packageName) but check for presence of package installed. Please see Suggested Packages instructions for how to best load a package in an Examples section.
I have altered this in the examples and the vignettes to instead use require or  if (requireNamespace("X", quietly = TRUE)) {}

8. It is not clear if test data 1 and 2 are simulated data or experimental biological data. Please state the source of the data.
Sorry - this was clinical data from our cohort. I have further anonymised this data and added some citations. 

9. Unit tests are inadequate. For example, test_stats.R tests the number of columns and column names but not whether the expected genes are significantly different or not. Please test that the calculations of your algorithm are correct.
Appologies - I have added further unit tests to check the maths and functions of the statistical functions. 

10. All of the examples use data packages such as TxDb.Hsapiens.UCSC.hg38.knownGene. Please comment on the applicability of SARC to other species such as Mus musculus. The generalisability of it should be explained in the vignette.
This is fair enough. I had intended this to be a clinical tool, but if it can help researchers working with model organisms, then I am happy to promote this. I have added a section at the end of the vignette to do just this.

Minor updates
New `csv` dataframes will be stored as nested lists within the RaggedExperiment object. To avoid removing older dataframes, users will have the option to rename the new dataframes that are being nested.
Added new parameter to fix a plotting bug where the log flag not having a logbase as a parameter.

Thank you for your comments, again this tool has been improved for the better I think.
Please communicate any other issues - or indadequate changes and I will try to respond promptly.

**Comment by DarioS** [comment]
Thank you for the significant updates to SARC. I have a few minor remaining issues to raise.

- Don't use `require` in the vignette for code users will run, but do use `library`. `require()` is usually only used if you are loading packages inside a function so that the function will continue to execute after warning, if a package doesn’t exist.
- RStudio automatically does spell-check and underlines potential mistakes. Please fix whichever underlining is relevant.
  
   ![image](https://github.com/Bioconductor/Contributions/assets/631218/fea1e199-0104-4b4d-8b4f-9abddad9b62a)
   
- `x <- coverage(x = "../inst/extdata/test.bam")` is error unless user's working directory is the package directory. Please do it more robustly, such as `system.file("extdata", "test.bam", package="SARC")`

  The paths elsewhere also need updating for robustness.
  ```r
  load(file ="../inst/extdata/test_cov_raw.rda")
  load(file ="../inst/extdata/librarySizes.rda")
  ```
- The `for` loop in the vignette is unnecessary and can be done with vectorisation. Please verify that
  ```r
  t(t(test_cov[, 5:ncol(test_cov)]) / libsizes$PerMillion)
  ```
  gives the same result as the `for` loop, but does it more concisely and is vectorised.

**Comment by Krutik6** [comment]
Hi @DarioS, I have made some more updates on the package which I will list here.

1. Don't use require in the vignette for code users will run, but do use library. require() is usually only used if you are loading packages inside a function so that the function will continue to execute after warning, if a package doesn’t exist.

Sorry I could not find the function `library. require()`, so instead just used `library()` in the vignette. Hope this is sufficient.

2. RStudio automatically does spell-check and underlines potential mistakes. Please fix whichever underlining is relevant.

Thanks - I have done this now on the vignette, all R function scripts and test scripts.

3.  x <- coverage(x = "../inst/extdata/test.bam") is error unless user's working directory is the package directory. Please do it more robustly, such as system.file("extdata", "test.bam", package="SARC")

You were right to comment on this - thanks for catching the potential bugs that would occur. All calls from `extdata` are now called using `system.file()`.

4. The for loop at the end.

Yes it gave almost the same result, minus a few columns which were easily re-added. I used this instead of the forloop.

**Comment by DarioS** [comment]
The package has been substantially improved and will be good member of the Bioconductor ecosystem.

**Comment by Krutik6** [comment]
Thanks for all the help @DarioS and @lshep :) Hopefully it will help bioinformaticians with CNV data.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Krutik6.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SARC")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SARC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
