### ISSUE TITLE
ggkegg

### ISSUE THREAD

**Issue by noriakis** [Bioconductor/Contributions#3078]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/noriakis/ggkegg

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

Some functions use snake case names instead of the camel case names specified in the guidelines. This is because the package has some functions that are intended to be used with functions in `dplyr`, such as `mutate`. If necessary, I will make the changes. Also, some functions download files from the web server and have \dontrun{} in their examples.

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by HelenaLC** [comment]
# code

- [ ] Consider having a look at the code-style guidelines [here](https://contributions.bioconductor.org/r-code.html#coding-style), and adapting code accordingly; e.g., the somewhat arbitrary indentation, linebreaks, and spacing in *ggkegg.R* and *utils.R* makes it very difficult to read/comprehend the code.

- [ ] Initializing empty objects and appending is very inefficient, and this should be done using `vapply/lapply` instead. E.g., `find_parenthesis_pairs()` in *utils.R*, `parse_reaction_layout()` in *parse_reaction_layout*, *ggkegg.R* lines 12+, etc. See [here](https://contributions.bioconductor.org/r-code.html#vectorize) for details on vectorizing computations. 

# documentation

- [ ] Please add runnable to example to `ggkegg`.
- [ ] Examples of exported functions should generally not make use of `donttest` flags. Please add runnable examples, unless there's a specific justification for doing this. 
- [ ] Would be nice to properly format examples code (e.g., selected linebreaks, 4-space tab indentation). Man pages are properly the most viewed pieces of documentation, and it's nice for them to be clean; perhaps also consider adding comments (brief headers/explanations) where useful. 

# vignette

- [ ] The `eval=FALSE` flag, or equivalent tricks in markdown, undermine the benefit of vignettes and are generally not allowed (e.g., code chunk at lines 63+). Similar, multiple code chunks are commented out completely. Please either run or remove them.
- [ ] The `BiocStyle` package has some handy utils to hyperlink external packages, e.g., `BiocStyle::Biocpkg()` for Bioc packages. Consider implementing these.
- [ ] Especially in the vignette, I strongly recommend sticking to 4-space tab indentation, making it much cleaner/easier to read. Remember that the corresponding HTML document will be displayed online and viewed by most package users.
- [ ] There's a link to an external website with more complex use cases. This is nice, I think. However, I find the package vignette rather sparse/underwhelming compared to what the package can actually do. Perhaps you could consider including a view more elaborate examples?
- [ ] Related to the above: I did a Bioc search, and there a various packages related to KEGG pathways. E.g., [this one](https://www.bioconductor.org/packages/release/bioc/html/KEGGlincs.html) includes a real-life example that is downloaded in the vignette. Perhaps you could consider a similar approach?
- [ ] Consider including pointers to related Bioc infrastructure, e.g., have a look [here](https://www.bioconductor.org/packages/release/BiocViews.html#___KEGG)
- [ ] Typo lines 28: directroy -> directory
- [ ] Remove superfluous comma in line 85.

# other

- [ ] In the READEME, please add Bioc installation instructions using `BiocManager`.
- [ ] Please add a NEWS file tracking version-specific changes.
- [ ] In the DESCRIPTION, consider adding `URL:` and `BugReport:` fields pointing to *https://github.com/noriakis/ggkegg* and *.../issues*, respectively.
- [ ] Please consider adding unit tests; Bioc strongly encourages them! The package's code base is on the rather large & complex end. So broad unit test coverage would be greatly help with assuring long-term reliability and robustness of the package.

**Comment by noriakis** [comment]
Dear Dr. Crowell,

Thank you very much for your detailed review of the package.
I will try to correct the points you have raised and report back to you within a month.

Sincerely,
Noriaki Sato

**Comment by noriakis** [comment]
Dear Dr. Crowell,

I apologize for the delay in reporting back. Currently, not all the points have been addressed and I describe the progress below, reflecting the latest commit in the [repository](https://github.com/noriakis/ggkegg). The refinement of code-style and vignette rewrite will be done by the end of August.

Sincerely,
Noriaki Sato

# code
- [ ] Consider having a look at the code-style guidelines [here](https://contributions.bioconductor.org/r-code.html#coding-style), and adapting code accordingly; e.g., the somewhat arbitrary indentation, linebreaks, and spacing in ggkegg.R and utils.R makes it very difficult to read/comprehend the code.

    Thank you for this comment. Indentation has been fixed, but the other code-style improvement is still in progress.

- [x] Initializing empty objects and appending is very inefficient, and this should be done using vapply/lapply instead. E.g., find_parenthesis_pairs() in utils.R, parse_reaction_layout() in parse_reaction_layout, ggkegg.R lines 12+, etc. See [here](https://contributions.bioconductor.org/r-code.html#vectorize) for details on vectorizing computations.

    Thank you for this comment. I have corrected the codes where empty objects were initialized and the elements were appended.

# documentation
- [x] Please add runnable to example to ggkegg.
- [ ] Examples of exported functions should generally not make use of donttest flags. Please add runnable examples, unless there's a specific justification for doing this.

    I apologize for the usage of \donttest{}, as I originally thought that recursive downloading from KEGG REST API was not desirable. I am currently improving the examples throughout the package using the real IDs as examples taking into account the comment below.

- [ ] Would be nice to properly format examples code (e.g., selected linebreaks, 4-space tab indentation). Man pages are properly the most viewed pieces of documentation, and it's nice for them to be clean; perhaps also consider adding comments (brief headers/explanations) where useful.

# vignette
- [x] The eval=FALSE flag, or equivalent tricks in markdown, undermine the benefit of vignettes and are generally not allowed (e.g., code chunk at lines 63+). Similar, multiple code chunks are commented out completely. Please either run or remove them.

- [ ] The BiocStyle package has some handy utils to hyperlink external packages, e.g., BiocStyle::Biocpkg() for Bioc packages. Consider implementing these.

- [ ] Especially in the vignette, I strongly recommend sticking to 4-space tab indentation, making it much cleaner/easier to read. Remember that the corresponding HTML document will be displayed online and viewed by most package users.

- [ ] There's a link to an external website with more complex use cases. This is nice, I think. However, I find the package vignette rather sparse/underwhelming compared to what the package can actually do. Perhaps you could consider including a view more elaborate examples?

- [ ] Related to the above: I did a Bioc search, and there a various packages related to KEGG pathways. E.g., [this one](https://www.bioconductor.org/packages/release/bioc/html/KEGGlincs.html) includes a real-life example that is downloaded in the vignette. Perhaps you could consider a similar approach?

- [ ] Consider including pointers to related Bioc infrastructure, e.g., have a look [here](https://www.bioconductor.org/packages/release/BiocViews.html#___KEGG)

    Vignette is currently being updated taking into account the comments, implmenting `Biocpkg`, code formatting, including more elaborate examples, and introduction of the other packages using KEGG information.

- [x] Typo lines 28: directroy -> directory
- [x] Remove superfluous comma in line 85.

# other
- [x] In the READEME, please add Bioc installation instructions using BiocManager.
- [x] Please add a NEWS file tracking version-specific changes.
- [x] In the DESCRIPTION, consider adding URL: and BugReport: fields pointing to https://github.com/noriakis/ggkegg and .../issues, respectively.
 - [x] Please consider adding unit tests; Bioc strongly encourages them! The package's code base is on the rather large & complex end. So broad unit test coverage would be greatly help with assuring long-term reliability and robustness of the package.

    I have added unit tests for functions, but not all of them are covered currently.

**Comment by noriakis** [comment]
Dear @HelenaLC,

I apologize for the delay in revising the codes, but I think I have completed correcting the points you have kindly raised. Below I have described the point-by-point responses, and I would be grateful if you could review the package again.

Sincerely,
Noriaki Sato

# code
- [x] Consider having a look at the code-style guidelines [here](https://contributions.bioconductor.org/r-code.html#coding-style), and adapting code accordingly; e.g., the somewhat arbitrary indentation, linebreaks, and spacing in ggkegg.R and utils.R makes it very difficult to read/comprehend the code.
    **Thank you for this comment. I try to adapt the code style to guidelines especially for indentation, linebreaks, spacing.**

- [x] Initializing empty objects and appending is very inefficient, and this should be done using vapply/lapply instead. E.g., find_parenthesis_pairs() in utils.R, parse_reaction_layout() in parse_reaction_layout, ggkegg.R lines 12+, etc. See [here](https://contributions.bioconductor.org/r-code.html#vectorize) for details on vectorizing computations.
    **Thank you for this comment.  I have corrected the codes where empty objects were initialized and the elements were appended to use `vapply` or `lapply`.**

# documentation
- [x] Please add runnable to example to ggkegg.
    **I added a runnable example to `ggkegg`.**

- [x] Examples of exported functions should generally not make use of donttest flags. Please add runnable examples, unless there's a specific justification for doing this.
    **I apologize for the usage of \donttest{}, as I originally thought that recursive downloading from KEGG REST API was not desirable. I am currently improving the examples throughout the package using the real IDs as examples taking into account the comment below.**

- [x] Would be nice to properly format examples code (e.g., selected linebreaks, 4-space tab indentation). Man pages are properly the most viewed pieces of documentation, and it's nice for them to be clean; perhaps also consider adding comments (brief headers/explanations) where useful.
    **Thank you for this comment. I have reformatted the example codes and insert the comments where appliable.**

# vignette
- [x] The eval=FALSE flag, or equivalent tricks in markdown, undermine the benefit of vignettes and are generally not allowed (e.g., code chunk at lines 63+). Similar, multiple code chunks are commented out completely. Please either run or remove them.
    **I have removed `eval=FALSE` section, and added runnable codes.**

- [x] The BiocStyle package has some handy utils to hyperlink external packages, e.g., BiocStyle::Biocpkg() for Bioc packages. Consider implementing these.
    **Thank you for this suggestion. I have implemented `Biocpkg()` in the vignette.**

- [x] Especially in the vignette, I strongly recommend sticking to 4-space tab indentation, making it much cleaner/easier to read. Remember that the corresponding HTML document will be displayed online and viewed by most package users.
    **Thank you for this comment. I have reformatted the codes in the vignette.** 

- [x] There's a link to an external website with more complex use cases. This is nice, I think. However, I find the package vignette rather sparse/underwhelming compared to what the package can actually do. Perhaps you could consider including a view more elaborate examples?
    **Thank you for this important comment. As you stated, the package vignette has few examples of codes, initially to avoid downloading the files from REST API. I added more elaborative examples in the vignette.**

- [x] Related to the above: I did a Bioc search, and there a various packages related to KEGG pathways. E.g., [this one](https://www.bioconductor.org/packages/release/bioc/html/KEGGlincs.html) includes a real-life example that is downloaded in the vignette. Perhaps you could consider a similar approach?
    **Thank you for the suggestion. I have referenced `KEGGlincs` vignette and added a real-life example in the vignette. Also, I have referenced the package in the introduction.**

- [x] Consider including pointers to related Bioc infrastructure, e.g., have a look [here](https://www.bioconductor.org/packages/release/BiocViews.html#___KEGG)
    **Thank you for this point. I have described the relevant packages in the introduction section of the vignette.**

- [x] Typo lines 28: directroy -> directory
- [x] Remove superfluous comma in line 85.
    **Thank you for these points. I have corrected the typo and the unnecessary comma.**

# other
- [x] In the READEME, please add Bioc installation instructions using BiocManager.
- [x] Please add a NEWS file tracking version-specific changes.
- [x] In the DESCRIPTION, consider adding URL: and BugReport: fields pointing to https://github.com/noriakis/ggkegg and .../issues, respectively.

    **I have added Bioc installation instructions, NEWS file tracking version specific changes. Also, URL: and BugReport: field have been added on DESCRIPTION.**

- [x] Please consider adding unit tests; Bioc strongly encourages them! The package's code base is on the rather large & complex end. So broad unit test coverage would be greatly help with assuring long-term reliability and robustness of the package.

    **Thank you for raising this point. I have added unit tests for the main functions**

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/noriakis.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ggkegg")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ggkegg

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
