### ISSUE TITLE
roastgsa

### ISSUE THREAD

**Issue by adricaba** [Bioconductor/Contributions#3086]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BBIRBCF/roastgsa

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Kayla-Morrell** [comment]
@adricaba - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding the maintainer's ORCID iD in 'Authors@R' with
  'comment=c(ORCID="...")'
- [ ] REQUIRED: Update R version dependency from 4.1 to 4.3.0.
- [ ] REQUIRED: Depends should include packages that provide *essential*
  functionality for your package. It is unusual for more than 3 packages to be
listed as Depends. I would suggest moving some to Imports instead (packages that
provide functions, methods, or classes used inside your package).
- [ ] SUGGESTION: We encourage the use of the 'BugReports:' field which includes
  a relevant link to GitHub for reporting issues.
- [ ] REQUIRED: There is a file 'DESCRIPTION~' which should be removed.

## NAMESPACE

- [ ] REQUIRED: Exported functions should use 'camelCase' or 'snake_case' and
  not include '.' which indicates S3 dispatch.
- [ ] REQUIRED: Internal functions should not be exported.

## NEWS

- [ ] REQUIRED: It's great practice to include a NEWS file. However, it doesn't
  seem to be formated properly. This can be checked by running
`utils::news(package="roastgsa")`. Please look at our documentation about NEWS
file formating here - https://contributions.bioconductor.org/news.html#news.

## Data

- [ ] REQUIRED: We require documentation for data included in the `data/`
  directory. This documentation should include information concerning creation
and source information.

## Vignettes

- [ ] SUGGESTION: We encourage the use of BiocStyle for formatting.
- [ ] REQUIRED: Each vignette needs an 'Installation' section that demonstrates
  to the user how to download and load the pacakge from Bioconductor. The code
should look something like the following and be included in an `eval = FALSE`
code chunk.

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("roastgsa")
```
- [ ] SUGGESTION: We strongly encourage the use of table of contents.

## Man pages

- [ ] REQUIRED: You do not need to document internal functions.
- [ ] REQUIRED: All man pages need runnable examples. The code for 'htmlrgsa',
  'ploteffsignaturesize', and 'varrotrand' need to be run (not commented out). 

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  https://contributions.bioconductor.org/tests.html

## R code

- [ ] SUGGESTION: Avoid `cat` outside of `show` methods, this is found in the
  R/utils.R file.
- [ ] SUGGESTION: Avoid using `=` for assignment and use `<-` instead. 

Best,
Kayla

**Comment by adricaba** [comment]
Dear Kayla,

thanks for all comments. 

We have addressed all the REQUIRED comments and most of the SUGGESTED comments: 

- Adding the maintainer's ORCID iD in ***@***.***’ 
- Update R version dependency from 4.1 to 4.3.0
- Move depends packages to import
- use of the ‘BugReports
- 'DESCRIPTION~’ file is removed
- Avoid '.’ in exported functions
- NEWS file in md format. 
- documentation for data included in man folder.
- Vignettes in BiocStyle format
- 'Installation’ section in all vignettes
- use of table of contents in all vignettes
- Eliminate documentation for internal functions
- All man pages have runnable examples
- Change = to -> for assignment

We have pushed the version 0.99.3 of the package. Let us know if there is any issue unresolved, please. 

Best,
Adria

**Comment by Kayla-Morrell** [comment]
@adricaba - Thank you for making the necessary changes. The last version was 0.99.3, as shown in this build report - https://github.com/Bioconductor/Contributions/issues/3086#issuecomment-1667640660. Please push a version bump to trigger the new build.

**Comment by adricaba** [comment]
Hi Kayla,

I finally managed to make it work, apologises for the delay, I had a few warnings that I had to deal to. 

Let me know if there is any further concern.  

Best,
Adria

**Comment by Kayla-Morrell** [comment]
@adricaba - Thank you for making the necessary changes. I have looked everything over and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/adricaba.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("roastgsa")`. The package 'landing page' will be created at

https://bioconductor.org/packages/roastgsa

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
