### ISSUE TITLE
ClustIRR

### ISSUE THREAD

**Issue by snaketron** [Bioconductor/Contributions#3087]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/snaketron/ClustIRR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
# Package 'ClustIRR' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.
## The DESCRIPTION file
- [ ] Important: R version should be no less than 4.3
## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 3 import(future)
	* in line 4 import(future.apply)
	* in line 7 import(stringdist)
	* in line 9 import(visNetwork)
## General package development
- [ ] Important: Package files exceed the 5MB size limit.
## R code
- [ ] Note: Use S4 object instead of S3 object.
	* In file R/cluster.R:
		+ at line 60 found '        return(base::structure('
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/cluster.R:
		+ at line 32 found '    for (chain in chains) {'
	* In file R/graph.R:
		+ at line 15 found '    for (chain in base::names(clust_irr$clust)) {'
		+ at line 65 found '    for (chain in names(clust_irr$clust)) {'
		+ at line 99 found '    for (chain in names(clust_irr$clust)) {'
		+ at line 171 found '    for (i in base::seq_along(shapes)) {'
		+ at line 200 found '    for (chain in chains) {'
		+ at line 201 found '        for (type in types) {'
		+ at line 293 found '    for (c in chains) {'
		+ at line 389 found '    for (c in chains) {'
		+ at line 396 found '    for (i in base::seq_along(l)) {'
		+ at line 440 found '    for (c in l) {'
	* In file R/input_check.R:
		+ at line 162 found '    for (i in seq_len(length(control_in))) {'
		+ at line 193 found '    for (n in base::colnames(x)) {'
	* In file R/local_clust.R:
		+ at line 367 found '    for (i in seq_len(length(motif_ref))) {'
- [ ] Important: Remove unused code.
	* In file R/local_clust.R:
		+ at line 225 found '    # f_s = x[1]'
		+ at line 226 found '    # f_r = x[2]'
		+ at line 227 found '    # n_s = x[3]'
		+ at line 228 found '    # n_r = x[4]'
		+ at line 230 found '    # q = f_s,'
		+ at line 231 found '    # m = f_r+f_s,'
		+ at line 232 found '    # n = n_r+n_s-(f_r+f_s),'
		+ at line 233 found '    # k = n_r+n_s'
		+ at line 235 found '    # ove <- (x[1] / x[3]) / ((x[2] / x[4]))'
		+ at line 238 found '    # q <- x[1]'
		+ at line 239 found '    # m <- x[1] + x[2]'
		+ at line 240 found '    # k <- x[3] + x[4]'
		+ at line 241 found '    # n <- k - m'
		+ at line 267 found '    # x = k in k-mer'
		+ at line 297 found '    # x = k in k-mer'
		+ at line 304 found '        # o <- o[1, o[1, ] >= min_o]'
		+ at line 352 found '        # OvE = o/e'
- [ ] Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.
	* In file R/graph.R:
		+ at line 16 found '        tmp_d <- clust_irr$inputs$s[, c(chain, "id")]'
		+ at line 19 found '            tmp_d <- tmp_d[!base::duplicated(tmp_d[[chain]]), ]'
		+ at line 21 found '        tmp_e <- e[e$chain == chain, ]'
		+ at line 42 found '        me <- me[!(me$from == me$to), ]'
		+ at line 144 found '        nodes <- nodes[!base::duplicated(nodes$label), ]'
		+ at line 145 found '        edges <- edges[edges$from %in% nodes$id & edges$to %in% nodes$id, ]'
		+ at line 198 found '    edges <- base::unique(edges[, c("edge_id", "motif", "type", "chain")])'
		+ at line 417 found '    nodes <- nodes[order(nodes$label), ]'
		+ at line 432 found '    e <- edges[edges$from == id | edges$to == id, ]'
	* In file R/input_check.R:
		+ at line 124 found '        if (all(global_pairs[, c(1, 2)] %in% s) == FALSE) {'
	* In file R/local_clust.R:
		+ at line 94 found '        X = m[, c("f_s", "f_r", "n_s", "n_r")],'
		+ at line 204 found '    kmers_r <- kmers_r[kmers_r$motif %in% kmers_s$motif, ]'
		+ at line 303 found '        o <- o[1, ]'
- [ ] NOTE: Functional programming: code repetition.
	* repetition in `check_dataframe` and `check_matrix`
		+ in check_dataframe
			- line 1:{
			- line 2:    w <- base::paste0(base::deparse(base::substitute(x)), " has to be of type data frame")
			- line 3:    if (!base::is.data.frame(x)) {
			- line 4:        base::stop(w)
			- line 5:    }
		+ in check_matrix
			- line 1:{
			- line 2:    w <- base::paste0(base::deparse(base::substitute(x)), " has to be of type matrix")
			- line 3:    if (!base::is.matrix(x)) {
			- line 4:        base::stop(w)
			- line 5:    }
	* repetition in `check_dataframe_empty`, `check_dataframe_na`, `check_logical`, `check_singlevalue`,  `check_infinity`, `check_greaterthan`, `check_lessthan`, `check_numeric`
		+ in check_dataframe_empty
			- line 1:{
			- line 2:    w <- base::paste0(base::deparse(base::substitute(x)), " contains empty values")
			- line 3:    if (base::any(x == "", na.rm = TRUE)) {
			- line 4:        base::warning(w)
			- line 5:    }
		+ in check_dataframe_na
			- line 1:{
			- line 2:    w <- base::paste0(base::deparse(base::substitute(x)), " contains NA value")
			- line 3:    if (base::any(base::is.na(x))) {
			- line 4:        base::warning(w)
			- line 5:    }
		+ in check_logical
			- line 40:{
			- line 41:    w <- base::paste0(base::deparse(base::substitute(x)), " has to be logical")
			- line 42:    if (base::any(base::is.na(x))) {
			- line 43:        base::stop(w)
			- line 44:    }
		+ in check_singlevalue
			- line 1:{
			- line 2:    w <- base::paste0(base::deparse(base::substitute(x)), " has to be a single value")
			- line 3:    if (base::any(base::is.na(x))) {
			- line 4:        base::stop(w)
			- line 5:    }
		+ in check_greaterthan
			- line 1:    v) 
			- line 2:{
			- line 3:    w <- base::paste0(base::deparse(base::substitute(x)), " has to be <= ", 
			- line 4:        v)
			- line 5:    if (base::any(x > v)) {
			- line 6:        base::stop(w)
			- line 7:    }
		+ in check_lessthan
			- line 1:    v) 
			- line 2:{
			- line 3:    w <- base::paste0(base::deparse(base::substitute(x)), " has to be >= ", 
			- line 4:        v)
			- line 5:    if (base::any(x < v)) {
			- line 6:        base::stop(w)
			- line 7:    }
		+ in check_infinity
			- line 1:{
			- line 2:    w <- base::paste0(base::deparse(base::substitute(x)), " has to be a finite number")
			- line 3:    if (base::any(base::is.infinite(x))) {
			- line 4:        base::stop(w)
			- line 5:    }
		+ in check_numeric
			- line 1:{
			- line 2:    w <- base::paste0(base::deparse(base::substitute(x)), " has to be numeric")
			- line 3:    if (base::any(!base::is.numeric(x))) {
			- line 4:        base::stop(w)
			- line 5:    }
	* repetition in `check_local_max_fdr`, `check_local_min_o` and `check_local_min_ove`
		+ in check_local_max_fdr
			- line 1:{
			- line 2:    check_infinity(local_max_fdr)
			- line 3:    check_numeric(local_max_fdr)
			- line 4:    check_singlevalue(local_max_fdr)
		+ in check_local_min_ove
			- line 1:{
			- line 2:    check_infinity(local_min_ove)
			- line 3:    check_numeric(local_min_ove)
			- line 4:    check_singlevalue(local_min_ove)
		+ in check_local_min_o
			- line 1:{
			- line 2:    check_infinity(local_min_o)
			- line 3:    check_numeric(local_min_o)
			- line 4:    check_wholenumber(local_min_o)
	* repetition in `check_r` and `check_s`
		+ in check_r
			- line 1:{
			- line 2:    check_missing(r)
			- line 3:    check_dataframe(r)
			- line 4:    check_rowcount(r)
			- line 5:    check_dataframe_colnames(r)
			- line 6:    check_dataframe_na(r)
			- line 7:    check_dataframe_empty(r)
		+ in check_s
			- line 1:{
			- line 2:    check_missing(s)
			- line 3:    check_dataframe(s)
			- line 4:    check_rowcount(s)
			- line 5:    check_dataframe_colnames(s)
			- line 6:    check_dataframe_na(s)
			- line 7:    check_dataframe_empty(s)
	* repetition in `get_clust_v1` and `get_clust_v23`
		+ in get_clust_v1
			- line 1:    cdr3_ref, ks, cores, control) 
			- line 2:{
			- line 3:    l <- get_localclust_v1(cdr3 = cdr3, cdr3_ref = cdr3_ref, 
			- line 4:        ks = ks, cores = cores, control = control)
			- line 5:    if (!base::is.null(control$global_pairs)) {
			- line 6:        g <- control$global_pairs
			- line 7:    }
			- line 8:    else {
			- line 9:        if (control$low_mem) {
			- line 10:            g <- get_global_clust_mem(cdr3 = base::unique(cdr3), 
			- line 11:                global_max_dist = control$global_max_dist)
			- line 12:        }
			- line 13:        else {
			- line 14:            g <- get_global_clust(cdr3 = base::unique(cdr3), 
			- line 15:                global_max_dist = control$global_max_dist)
			- line 16:        }
			- line 17:    }
		+ in get_clust_v23
			- line 1:    cdr3_ref, version, ks, cores, control) 
			- line 2:{
			- line 3:    l <- get_localclust_v23(cdr3 = cdr3, cdr3_ref = cdr3_ref, 
			- line 4:        ks = ks, cores = cores, control = control)
			- line 5:    if (!base::is.null(control$global_pairs)) {
			- line 6:        g <- control$global_pairs
			- line 7:    }
			- line 8:    else {
			- line 9:        if (control$low_mem) {
			- line 10:            g <- get_global_clust_mem(cdr3 = base::unique(cdr3), 
			- line 11:                global_max_dist = control$global_max_dist)
			- line 12:        }
			- line 13:        else {
			- line 14:            g <- get_global_clust(cdr3 = base::unique(cdr3), 
			- line 15:                global_max_dist = control$global_max_dist)
			- line 16:        }
			- line 17:        if (version == 3) {
	* repetition in `get_global_clust` and `get_global_clust_mem`
		+ in get_global_clust
			- line 5:    get_hamming_dist <- function(x, cdr3, cdr3_len, global_max_dist) {
			- line 6:        is <- base::which(cdr3_len == x)
			- line 7:        if (base::length(is) == 1) {
			- line 8:            return(NULL)
			- line 9:        }
			- line 23:            return(NULL)
			- line 24:        }
			- line 25:        return(base::cbind(cdr3[is[js[, 1]]], cdr3[is[js[, 2]]]))
			- line 26:    }
			- line 27:    hd <- base::lapply(X = cdr3_lens, FUN = get_hamming_dist, 
			- line 28:        cdr3 = cdr3, cdr3_len = cdr3_len, global_max_dist = global_max_dist)
			- line 29:    hd <- base::do.call(base::rbind, hd)
			- line 30:    return(hd)
		+ in get_global_clust_mem
			- line 2:{
			- line 3:    get_hamming_dist <- function(x, cdr3, cdr3_len, global_max_dist) {
			- line 4:        is <- base::which(cdr3_len == x)
			- line 5:        if (base::length(is) == 1) {
			- line 6:            return(NULL)
			- line 7:        }
			- line 23:            return(hd)
			- line 24:        }
			- line 25:        return(base::cbind(cdr3[is[hd[, 1]]], cdr3[is[hd[, 2]]]))
			- line 26:    }
			- line 29:    hd <- base::lapply(X = cdr3_lens, FUN = get_hamming_dist, 
			- line 30:        cdr3 = cdr3, cdr3_len = cdr3_len, global_max_dist = global_max_dist)
			- line 31:    hd <- base::do.call(base::rbind, hd)
			- line 32:    return(hd)
	* repetition in `get_localclust_v1` and `get_localclust_v23`
		+ in get_localclust_v1
			- line 1:    cdr3_ref, ks, cores, control) 
			- line 2:{
			- line 3:    if (control$trim_flank_aa != 0) {
			- line 4:        cdr3_core <- get_trimmed_flanks(x = cdr3, flank_size = control$trim_flank_aa)
			- line 5:        cdr3_ref_core <- get_trimmed_flanks(x = cdr3_ref, flank_size = control$trim_flank_aa)
			- line 6:    }
			- line 7:    else {
			- line 8:        cdr3_core <- cdr3
			- line 9:        cdr3_ref_core <- cdr3_ref
			- line 10:    }
			- line 11:    motifs <- base::lapply(X = ks, FUN = get_motifs_v1, cdr3 = cdr3_core, 
			- line 12:        cdr3_ref = cdr3_ref_core, B = control$B, min_o = control$local_min_o, 
			- line 20:    me$pass <- FALSE
			- line 21:    me$pass[me$fdr <= control$local_max_fdr & me$ove >= control$local_min_ove & 
			- line 22:        me$f_s >= control$local_min_o] <- TRUE
			- line 23:    lp <- get_motif_in_seq(cdr3 = cdr3, cdr3_core = cdr3_core, 
			- line 24:        motif = me$motif[me$pass == TRUE])
			- line 25:    return(base::list(m = me, lp = lp))
		+ in get_localclust_v23
			- line 1:    cdr3_ref, ks, cores, control) 
			- line 2:{
			- line 3:    if (control$trim_flank_aa != 0) {
			- line 4:        cdr3_core <- get_trimmed_flanks(x = cdr3, flank_size = control$trim_flank_aa)
			- line 5:        cdr3_ref_core <- get_trimmed_flanks(x = cdr3_ref, flank_size = control$trim_flank_aa)
			- line 6:    }
			- line 7:    else {
			- line 8:        cdr3_core <- cdr3
			- line 9:        cdr3_ref_core <- cdr3_ref
			- line 10:    }
			- line 11:    m <- base::lapply(X = ks, FUN = get_motifs_v23, cdr3 = cdr3_core, 
			- line 12:        cdr3_ref = cdr3_ref_core, min_o = control$local_min_o)
			- line 22:    m$pass <- FALSE
			- line 23:    m$pass[m$fdr <= control$local_max_fdr & m$ove >= control$local_min_ove & 
			- line 24:        m$f_s >= control$local_min_o] <- TRUE
			- line 25:    lp <- get_motif_in_seq(cdr3 = cdr3, cdr3_core = cdr3_core, 
			- line 26:        motif = m$motif[m$pass == TRUE])
			- line 27:    return(base::list(m = m, lp = lp))
## Documentation
- [ ] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/User_manual.Rmd
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/User_manual.Rmd
- [ ] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/User_manual.Rmd

## Others
- [ ] Note: move the gene symbols list into a global variable and replace the corresponding codes to subfunction.
	* in `graph.R` line 296, line 316, line 330, line 366, line 446-452
	* in `input_check.R` line 199-209
	* in `utils.R` line 7-12

**Comment by snaketron** [comment]
> ## The NAMESPACE file
> * [x]  Selective imports using `importFrom` instead of _import all_ with `import`.
>   
>   * in line 3 import(future)
>   * in line 4 import(future.apply)
>   * in line 7 import(stringdist)
>   * in line 9 import(visNetwork)

Fixed in previous (commit id: 92d7c9cacba103d10f3c5949adb4042ab17141e3) push.

**Comment by snaketron** [comment]
> * [x]  NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.

We have removed `::` and double-checked the dependencies. Only in the case of the package future we left the `::` symbols in local_clust.R. Without this we encountered errors documented earliers by the developers of future here: https://github.com/HenrikBengtsson/future/issues/152

> ## The DESCRIPTION file
> * [x]  Important: R version should be no less than 4.3

Both fixes are provided in the following commit id: 55fbfb4a08d78befa6e579f80795287ed5ecb98e

**Comment by snaketron** [comment]
> ## Documentation
> * [x]  Important: Vignette should have an _Installation_ section.
>   
>   * rmd file vignettes/User_manual.Rmd
> * [x]  Important: Please include Bioconductor installation instructions using BiocManager.
>   
>   * rmd file vignettes/User_manual.Rmd
> * [x]  Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
>   
>   * rmd file vignettes/User_manual.Rmd

We included a Installation section in the vignette.

Commit id: e28534d62aca60dc340bab7c2d3ccff8503c8070

**Comment by snaketron** [comment]
> * [x]  Note:  Use S4 object instead of S3 object.
> * In file R/cluster.R:
>   
>   * at line 60 found '        return(base::structure('

Using object oriented programming was not necessary at all. We needed a simple list with two elements as output and this is what we did.

**Comment by snaketron** [comment]
> * [x] NOTE: Functional programming: code repetition.

We reduced the code repetition.

While it is possible to reduce the code repetition in the functions in input_check.R, we think that the code repetition here is an asset:
1) it improves readability while we check the individual parameters
2) while ClustIRR is mature in terms of its functionality, we can see many directions in which ClustIRR may soon evolve (acquire new input parameters as well). Adding new input parameters or removing the old ones is easily done given that the different parameters are treated/checked independently of each other.
3) the main drawback, as mentioned by the reviewer, is code redundancy

**Comment by snaketron** [comment]
> ## General package development
> * [ ]  Important: Package files exceed the 5MB size limit.

Dear @jianhong,

thank you for the review of our package.

We have addressed all *important* comments except for the one above (we do not find this error as all files in the package are smaller than 5mb). The file you are referencing appears to be an .git file. Right? As far as I understand git removing this file could be damaging.

Furthermore, we addressed nearly all *notes*. Our comments on the individual issues are shown above.

**Comment by jianhong** [comment]
> > * [x]   Note:  Use S4 object instead of S3 object.
> > * In file R/cluster.R:
> >   
> >   * at line 60 found '        return(base::structure('
> 
> Using object oriented programming was not necessary at all. We needed a simple list with two elements as output and this is what we did.

If you do not want to change to S4 object, please keep the S3 object. You changed in your code part but did not change the documentation. I still suggest you to change it into S4 object because your `plot_graph` is depend on this object. If you use S4 object, you can simply merge the `check_clustirr` into the object construction step. But this is not required.

**Comment by jianhong** [comment]
Other minor issues:

## R code
- [ ] Important:`is()` or `inherits()` instead of `class()`.
	* In file R/input_check.R:
		+ at line 219 found '    if(any(sapply(x, class) != "character")) {'
- [ ] Important: `vapply` instead of `sapply`.
	* In file R/input_check.R:
		+ at line 219 found '    if(any(sapply(x, class) != "character")) {'
- [ ] Important: No `paste` in `message()`, `message`, `stop`
	* In file R/input_check.R:
		+ at line 206 found '        stop(paste0("unallowed columns in s/r, allowed are ",'
		+ at line 215 found '        stop(paste0("mixed chains, allowed chain combinations are ",'

**Comment by snaketron** [comment]
Dear @jianhong 

in the latest push we addressed both issues (R code and S4 object)

**Comment by jianhong** [comment]
## Namespace
- [ ] Important: please export the S4 class.

## R code
- [ ] NOTE: no direct slot access with `@` or `slot()` - accessors implemented and used.
	* In file R/graph.R:
		+ at line 16 found '        tmp_d <- clust_irr@inputs$s[, c(chain, "id")]'
		+ at line 18 found '        if (clust_irr@inputs$version != 2) {'
		+ at line 141 found '        types = types, s = clust_irr@inputs$s'
## Documentation
- [ ] Important: missing documentation for the new S4 class.

**Comment by snaketron** [comment]
Dear @jianhong

the S4 object related issues should be solved now.

**Comment by jianhong** [comment]
You may misunderstand the slot access comments. Please do not use `@` or `slot` outside of accessors. See reference [here](https://contributions.bioconductor.org/r-code.html?q=S4#class-design) and [here](http://adv-r.had.co.nz/S4.html) for complete implementation of a S4 object.

**Comment by snaketron** [comment]
@jianhong I implemented the code according to Hadley Wickham's tutorial 'The S4 object system' (you refer to this tutorial)

Text from the tutorial:
> To access slots of an S4 object you use @, not $:
> hadley <- new("Person", name = "Hadley")
> hadley@age
> Or if you have a character string giving a slot name, you use the slot function:
> slot(hadley, "age")

In our case the object is a multifactorial result from our packages' main function. We *expect* the user to access directly the two slots of this object. And yes, we can implement two accessors that do the same thing slots does, but this looks like an overkill in our particular example. 

I completely agree with the idea stated in the  Biocconductor guidelines:
> Generally @ should only be used in an accessor, all other code should use the accessor. The accessor does not need to  be exported from the class if the user has no need or business accessing parts of your data object.

However, here we are not hiding anything from the user, i.e. the two slots that are available are exported and should be directly accessible.

Please let me know what you think.

**Comment by jianhong** [comment]
Does that mean you never though any possibility the others will import your package and re-use the S4 class?

**Comment by snaketron** [comment]
I am quite certain that we will re-use the S4 class in the future, most likely in some new functions of this package. 

Not sure about others. My guess is that others will primarily apply ClustIRR to analyze their data. Currently, we see few R-packages that deal with downstream analysis TCR-seq data, so it is difficult to imagine how other developers will react to this package.

**Comment by jianhong** [comment]
If answer is yes, then the accessor are encouraged.

**Comment by snaketron** [comment]
The accessor functions are implemented (since version 0.99.25)

Btw: the core functionality of the package is complete (has been in a while), but we are continuously updating the auxiliary functions. Hence, do not be surprised if you see a bunch of other changes in the code and we will likely add even more in the near future :)

**Comment by jianhong** [comment]
@snaketron It is almost there. Please remove the unused code in `test-joint-graph.R` and update your NEWS file.

**Comment by snaketron** [comment]
@jianhong  great! I incorporated the changes.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/snaketron.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ClustIRR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ClustIRR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
