### ISSUE TITLE
crisprShiny

### ISSUE THREAD

**Issue by Jfortin1** [Bioconductor/Contributions#3091]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/crisprVerse/crisprShiny

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe @Jfortin1 

Thank you for your submission. 
Please fix the error and bump the version for another build.
See the review below. 
Best,
Marcel

--- 

# crisprShiny #3091

## DESCRIPTION

* Consider wrapping text to a max 80 character width limit.
* Remove the `StagedInstal` field from the `DESCRIPTION` (see
https://blog.r-project.org/2019/02/14/staged-install/ for details)
* Update R version to `4.3.0`

## NAMESPACE

* Looks good.

## vignettes

* Should the main function run the app itself, i.e., `crisprShiny`?
* Indicate that using the `criprShiny` modules is for developer use.

## R

* Consider formatting the code with `styler` or other syntax guide for
arguments and function body delimiters `{`.
* It seems that `.filterTemplate` is not used in the code. Consider removing
it.
* Add the `shiny` package to the `Depends` field.
* `.renderTssAnnotationTab()` has an "add plot" comment. Please resolve.
* Remove commented code in `.enzymeAnnotationDataTable`
* Ideally the tooltip annotation data should be treated as data and not text
in a `switch` call (`interface_tooltips.R`).

## tests

* Resolve the issue with the test:

```r
> covr::package_coverage()
Error: Failure in `/tmp/RtmpgxoZxh/R_LIBS4b94575f2ce6/crisprShiny/crisprShiny-tests/testthat.Rout.fail`
setup.*\\.[rR]$", env = env, wrap = FALSE)
  8. │             └─base::lapply(...)
  9. │               └─testthat (local) FUN(X[[i]], ...)
 10. │                 └─testthat::source_file(path, env = env, chdir = chdir, wrap = wrap)
 11. │                   ├─base::withCallingHandlers(...)
 12. │                   └─base::eval(exprs, env)
 13. │                     └─base::eval(exprs, env)
 14. │                       └─utils::data("txdb_human", package = "crisprDesignData") at crisprShiny-tests/testthat/setup.R:4:0
 15. │                         └─base::find.package(package, lib.loc, verbose = verbose)
 16. │                           └─base::stop(packageNotFoundError(bad, lib.loc, sys.call()))
 17. └─testthat (local) `<fn>`(`<pckgNtFE>`)
 18.   └─rlang::abort(...)
```
which means that `crisprDesignData` should be added to the `Imports` or
`Suggests`.

**Comment by Jfortin1** [comment]
Hi @lshep,

I just got back from a 3-month sabbatical and did not have the time to follow up with this package submission.
Could we reopen this issue please? We have now finished the review of the package

**Comment by LiNk-NY** [comment]
Hi @Jfortin1 
When ready, please respond to the bullet points in the review. Thanks!
-Marcel

**Comment by Jfortin1** [comment]
Hi @LiNk-NY, thank you for your review. Here's a response:

## DESCRIPTION

- Consider wrapping text to a max 80 character width limit. **DONE**
- Remove the StagedInstal field from the DESCRIPTION  **DONE**
- Update R version to 4.3.0  **DONE (updated to 4.4.0 now)**

## NAMESPACE

- Looks good.


## vignettes

- Should the main function run the app itself, i.e., crisprShiny? **For internal deployment at Genentech, we need the main function to behave that way**


## R

- Consider formatting the code with styler or other syntax guide for arguments and function body delimiters **We are following the internal syntax of our R ecosystemt at Genentech**.
- It seems that .filterTemplate is not used in the code. Consider removing it. **DONE**
- Add the shiny package to the Depends field.  **DONE**
- .renderTssAnnotationTab() has an "add plot" comment. Please resolve.  **DONE**
- Remove commented code in .enzymeAnnotationDataTable  **DONE**
- Ideally the tooltip annotation data should be treated as data and not text in a switch call (interface_tooltips.R).  **DONE**

## tests

- Resolve the issue below with the test:
```
> covr::package_coverage()
Error: Failure in `/tmp/RtmpgxoZxh/R_LIBS4b94575f2ce6/crisprShiny/crisprShiny-tests/testthat.Rout.fail`
setup.*\\.[rR]$", env = env, wrap = FALSE)
  8. │             └─base::lapply(...)
  9. │               └─testthat (local) FUN(X[[i]], ...)
 10. │                 └─testthat::source_file(path, env = env, chdir = chdir, wrap = wrap)
 11. │                   ├─base::withCallingHandlers(...)
 12. │                   └─base::eval(exprs, env)
 13. │                     └─base::eval(exprs, env)
 14. │                       └─utils::data("txdb_human", package = "crisprDesignData") at crisprShiny-tests/testthat/setup.R:4:0
 15. │                         └─base::find.package(package, lib.loc, verbose = verbose)
 16. │                           └─base::stop(packageNotFoundError(bad, lib.loc, sys.call()))
 17. └─testthat (local) `<fn>`(`<pckgNtFE>`)
 18.   └─rlang::abort(...)
```
which means that crisprDesignData should be added to the Imports or Suggests. 
 **DONE**

**Comment by LiNk-NY** [comment]
Hi Jean-Philippe, @Jfortin1 

Apologies for the delay in getting back to you. 
I have taken a second look at the package. It looks good to me. 
Please be aware that the check on merida is close to timing out. You may want to consider reducing the check timing to avoid a timeout on Mac. 
Your package has been accepted. Thank you for your contribution.

Best regards,
Marcel

**Comment by Jfortin1** [comment]
@LiNk-NY Thanks Marcel!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jfortin1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("crisprShiny")`. The package 'landing page' will be created at

https://bioconductor.org/packages/crisprShiny

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
