### ISSUE TITLE
zitools submission

### ISSUE THREAD

**Issue by cmeyring** [Bioconductor/Contributions#3094]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kreutz-lab/zitools

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

Justification for one warning: set.seed is used when randomly dividing a matrix into smaller blocks to ensure a reproducible process.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
THanks for your submission.  There's a lot going on here that should be remedied before review.  First, I saw
```
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-weights.R:27:5'): Compare results for sd, mean, rowMeans2 and colMeans2 on Zi object with weights equal to 1 to the case where Zi@inputcounts is used ──
  unname(rowMeans2(ZiW1)) (`actual`) not identical to rowMeans2(ZiW1@inputcounts) (`expected`).

  `names(actual)` is absent
  `names(expected)` is a character vector ('1', '2', '3', '4', '5', ...)
  ── Failure ('test-weights.R:28:5'): Compare results for sd, mean, rowMeans2 and colMeans2 on Zi object with weights equal to 1 to the case where Zi@inputcounts is used ──
  unname(colMeans2(ZiW1)) (`actual`) not identical to colMeans2(ZiW1@inputcounts) (`expected`).

  `names(actual)` is absent
  `names(expected)` is a character vector ('1', '2', '3', '4', '5', ...)

  [ FAIL 2 | WARN 0 | SKIP 0 | PASS 7 ]
  Error: Test failures
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking running R code from vignettes ... NONE
  'my-vignette.Rmd' using 'UTF-8'... OK
```
and that should be corrected.  Additionally, don't call your vignette "my-vignette.Rmd".  Please use a package-oriented name.  There is a download.file in the vignette, but the file is in the github repo and is small so it could just be placed in /data.  In general we don't have downloads to working folder but ask that developers put retrieved artifacts in BiocFileCache, and the retrieval needs to be from a durable source, possibly ExperimentHub.  There should be no .Rproj file in the submitted repo.

**Comment by vjcitn** [comment]
hi do u plan on revising?

**Comment by cmeyring** [comment]
Hi, yes I’ll revise beginning from next week. Von meinem iPhone gesendetAm 12.09.2023 um 20:41 schrieb Vince Carey ***@***.***>:﻿
hi do u plan on revising?

**Comment by cmeyring** [comment]
Hello Vince,

thanks for the comment. I've updated the submitted repository, but I still have two questions:  When I am running the tests of the package I don't get a error message. What command did you use to run the tests? 
And for the download.file, it is a dataset from another working group. I am probably not allowed to store the file in data, right? Therefore, I added the download.file. 

Thanks in advance

**Comment by vjcitn** [comment]
I am working with the checkout
```
(base) %vjc> cd zitools
(base) %vjc> git log
commit fef06599d56709e7676c02a761926c9a051fdd52 (HEAD -> main, origin/main, origin/HEAD)
Author: cmeyring <carlotta-meyring@web.de>
Date:   Mon Sep 18 11:46:53 2023 +0200

    remove .Rproj
```
I am using
```
R version 4.3.1 Patched (2023-08-27 r85021) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```
I get
```
  Running ‘testthat.R’
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-weights.R:27:5'): Compare results for sd, mean, rowMeans2 and colMeans2 on Zi object with weights equal to 1 to the case where Zi@inputcounts is used ──
  unname(rowMeans2(ZiW1)) (`actual`) not identical to rowMeans2(ZiW1@inputcounts) (`expected`).
  
  `names(actual)` is absent
  `names(expected)` is a character vector ('1', '2', '3', '4', '5', ...)
  ── Failure ('test-weights.R:28:5'): Compare results for sd, mean, rowMeans2 and colMeans2 on Zi object with weights equal to 1 to the case where Zi@inputcounts is used ──
  unname(colMeans2(ZiW1)) (`actual`) not identical to colMeans2(ZiW1@inputcounts) (`expected`).
  
  `names(actual)` is absent
  `names(expected)` is a character vector ('1', '2', '3', '4', '5', ...)
  
  [ FAIL 2 | WARN 0 | SKIP 0 | PASS 7 ]
  Error: Test failures
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking running R code from vignettes ...
  'zitools_tutorial.Rmd' using 'UTF-8'... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 ERROR, 1 NOTE
```
with R CMD build followed by R CMD check on
```
-rw-r--r--  1 vincent vincent   179407 Sep 30 23:41 zitools_0.99.0.tar.gz
```

**Comment by cmeyring** [comment]
Hello Vince, 

the new version is pushed and I should work now.

**Comment by lshep** [comment]
There are still ERROR when we run this.  Please run R CMD check with the most recent version of R and updated versions of Bioconductor packages  
```
  Running ‘testthat.R’
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-weights.R:27:5'): Compare results for sd, mean, rowMeans2 and colMeans2 on Zi object with weights equal to 1 to the case where Zi@inputcounts is used ──
  unname(rowMeans2(ZiW1)) (`actual`) not equal to rowMeans2(ZiW1@inputcounts) (`expected`).
  
  `names(actual)` is absent
  `names(expected)` is a character vector ('1', '2', '3', '4', '5', ...)
  ── Failure ('test-weights.R:28:5'): Compare results for sd, mean, rowMeans2 and colMeans2 on Zi object with weights equal to 1 to the case where Zi@inputcounts is used ──
  unname(colMeans2(ZiW1)) (`actual`) not equal to colMeans2(ZiW1@inputcounts) (`expected`).
  
  `names(actual)` is absent
  `names(expected)` is a character vector ('1', '2', '3', '4', '5', ...)
  
  [ FAIL 2 | WARN 0 | SKIP 0 | PASS 7 ]
  Error: Test failures
  Execution halted
```

**Comment by lshep** [comment]
You also cannot store data on github or personal spaces like dropbox.  Example data for vignettes, man pages, and tests should be included with the package and/or using the ExperimentHub.

**Comment by lshep** [comment]
@cmeyring any update?

**Comment by cmeyring** [comment]
Hello, 
is it possible to reopen this issue? I was in between Master Thesis,  PhD stages, and therefore, didn't have the time to adress the issues. However they are adressed now and I would like to reopen the issue, if that is possible. 

Thanks in advance

**Comment by lshep** [comment]
Before this submission moves on in the review process:

- [ ] remove the git committed zip of the package `zitools_0.0.0.9000.zip`

- [ ] Please remove Readme.txt in R/ directory. The R directory should contain
  code files only.

- [ ] Please run R CMD build, R CMD check and R CMD BiocCheck. There are still
  ERROR's when running R CMD check and numerous Warnings and Notes from
  BiocCheck.

**Comment by cmeyring** [comment]
Everything should be fine now, R CMD build and check run without any errors and Warnings. BiocCheck also runs without any errors, however one warning occurrs to a set.seed usage which is needed in that particular function. However, at the end of the function the seed is reset to its old random seed.

**Comment by cmeyring** [comment]
The Warning when running BiocCheck is due to the usage of set.seed. However, it is needed when randomly dividing a matrix into smaller blocks to ensure a reproducible process. After the usage of the function, the seed is set back to its old seed before.

**Comment by Kayla-Morrell** [comment]
@cmeyring - Thank you for submitting to _Bioconductor_. Please see the initial review of 
the package below. The required changes must be made while the suggested 
changes do not have to be (though we strongly encourage them). Comment back 
here with updates that have been made and when the package is ready for a 
re-review.

## General package development

- [ ] REQUIRED: The README file should also provide Bioconductor installation instructions.

## DESCRIPTION

- [ ] SUGGESTION: The Description field in the DESCRIPTION is made up by less than 3 sentences. Please consider expanding this field and structure it as a full paragraph.
- [ ] REQUIRED: Update R version dependency from 4.3.0 to 4.4.0.
- [ ] SUGGESTION: Provide the 'URL' field in DESCRIPTION.

## NAMESPACE

- [ ] SUGGESTION: Consider adding `importFrom("stats", "predict")`.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements.

## CITATION

- [ ] SUGGESTION: Checking CITATION. CITATION file not found. Only include a CITATION file if there is a preprint or publication for this Bioconductor package. Note that Bioconductor packages are not required to have a CITATION file but it is useful both for users and for tracking Bioconductor project-wide metrics. When including a CITATION file, add the publication using the 'doi' argument of 'bibentry()'.

## Vignette

- [ ] SUGGESTION: We encourage the use of BiocStyle for formatting.
- [ ] REQUIRED: The 'Installation' section should show users how to download and load the package from Bioconductor. This code chunk should include `eval = FALSE`.
- [ ] SUGGESTION: We encourage the use of table of contents.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the package and links to the main functions. Users should be able to have a relevant page display with `?zitools`.
- [ ] REQUIRED: All exported objects need to have runnable examples in the man page.

## R code

- [ ] SUGGESTION: Checking R code for possible problems.
        calcWeights: no visible global function definition for predict
        omit_str_zero: no visible global function definition for predict
- [ ] REQUIRED: Avoid use of direct slot access with `@`. Accessor methods should be created and utlizied instead.
- [ ] REQUIRED: Avoid 1:...; use seq_len() or seq_along().
- [ ] REQUIRED: Avoid 'suppressWarnings'/'*Messages' if possible (found 1 time).
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 72 lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 702 lines that are not.

Best,
Kayla

**Comment by cmeyring** [comment]
Hey Kayla, 
thank you for the comments. 
I pushed the updated package. However, there is an error when building on MacOS. I think this might be because there is not yet R.4.4 on merida1 (macOS) and therefore the R CMD build fails, as R.4.4 is required for the package. 

I further adressed all the comments. However, I couldn't adress all, as stated below. 

- [x] REQUIRED: The README file should also provide Bioconductor installation instructions.
- 
- [x] SUGGESTION: The Description field in the DESCRIPTION is made up by less than 3 sentences. Please consider expanding this field and structure it as a full paragraph

- [x] REQUIRED: Update R version dependency from 4.3.0 to 4.4.0

- [x]  SUGGESTION: Provide the 'URL' field in DESCRIPTION
- [ ] SUGGESTION: Consider adding importFrom("stats", "predict").
- [ ] SUGGESTION: Checking R code for possible problems.

**adding importFrom("stats", "predict") is not working because the predict function is used from the pscl package and as I understood it is nor correctly defined as a method for the generic function stats::predict** 

- [x]  SUGGESTION: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements.

- [ ] SUGGESTION: Checking CITATION. CITATION file not found. Only include a CITATION file if there is a preprint or publication for this Bioconductor package. Note that Bioconductor packages are not required to have a CITATION file but it is useful both for users and for tracking Bioconductor project-wide metrics. When including a CITATION file, add the publication using the 'doi' argument of 'bibentry()'.

 **There is not yet a submitted preprint/publication. When the preprint is submitted the citation file will be added.** 

- [x] SUGGESTION: We encourage the use of BiocStyle for formatting.

- [x]  REQUIRED: The 'Installation' section should show users how to download and load the package from Bioconductor. This code chunk should include eval = FALSE.

 - [x] SUGGESTION: We encourage the use of table of contents.

- [x]  SUGGESTION: We encourage having a package man page with an overview of the package and links to the main functions. Users should be able to have a relevant page display with ?zitools.

- [x]  REQUIRED: All exported objects need to have runnable examples in the man page.

- [x] REQUIRED: Avoid use of direct slot access with @. Accessor methods should be created and utlizied instead.

- [x]  REQUIRED: Avoid 1:...; use seq_len() or seq_along().

 - [ ] REQUIRED: Avoid 'suppressWarnings'/'*Messages' if possible (found 1 time).

**The suppressed warnings message is used in the ziMain function because the class of the count matrix of the phyloseq object is an otu_table, however we extract the count matrix and define it as a matrix which is perfectly fine at that step, however, it will produce a warning and therefore, we decided to supress the warning as we only need the count matrix of the class matrix.**  

- [x] SUGGESTION: For formatting reasons, consider shorter lines. There are 72 lines that are > 80 characters long.

 

- [x] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 702 lines that are not.

Best, Carlotta

**Comment by lshep** [comment]
merida1 was run in error -- please ignore the error in the build report and proceed with the clean build displayed on linux

**Comment by Kayla-Morrell** [comment]
@cmeyring - Thank you for making the necessary changes. I have looked everything over and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cmeyring.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("zitools")`. The package 'landing page' will be created at

https://bioconductor.org/packages/zitools

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
