### ISSUE TITLE
MicroBioMap

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/Contributions#3100]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/seandavi/MicroBioMap

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by seandavi** [comment]
A quick look through the build reports shows that dependencies are "not available." Not sure what is up, but is this a problem with the builder, as both BiocFileCache and SingleCellExperiemnt are both Bioconductor packages?

**Comment by lshep** [comment]
I'm going to try and manually kick off a rebuild to see if it was an intermittent issue.

**Comment by DarioS** [comment]
I will begin my formal review of this submission soon. In the meantime, please address the [R Code](http://contributions.bioconductor.org/r-code.html) issues raised by BiocCheck.

> ```
> * Checking coding practice ...
>     * NOTE: Avoid 1:...; use seq_len() or seq_along()
>     * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
>     * NOTE: Avoid using '=' for assignment and use '<-' instead
> ```

**Comment by DarioS** [comment]
I have reviewed MicroBioMap and noted some issues.

- In biocViews, it ought to have ExperimentData in the list of views.
- Inconsistent variable and function naming. Both `snake_case` and `camelCase` are present. See [Variable Names](https://contributions.bioconductor.org/r-code.html#variable-names) and [Function Names](https://contributions.bioconductor.org/r-code.html#rcode-function-names). `camelCase` is Bioconductor's standard.
- The package consists of just one exported function, `get_compendium`. There ought to be more functionality available.
- Vignette is incomplete. It has some `[ ] TODO` parts. It would be interesting to demonstrate the identification of an association between some genus and some sample phenotype. Demonstrate its biological usefulness.
- [Background Text for Pipeline](https://github.com/seandavi/MicroBioMap/issues/6) is what I was seeking. This will be important for users to know.

**Comment by seandavi** [comment]
Hi, Dario. Thanks for the thoughtful review. I hope it wasn't too onerous!

On Fri, Sep 8, 2023 at 7:00 AM Dario Strbenac ***@***.***>
wrote:

> I have reviewed MicroBioMap and noted some issues.
>
>    - In biocViews, it ought to have ExperimentData in the list of views.
>
> ExperimentData is not allowed in Software packages.

>
>    - Inconsistent variable and function naming. Both snake_case and
>    camelCase are present. See Variable Names
>    <https://contributions.bioconductor.org/r-code.html#variable-names>
>    and Function Names
>    <https://contributions.bioconductor.org/r-code.html#rcode-function-names>.
>    camelCase is Bioconductor's standard.
>
> Fixed.

>
>    - The package consists of just one exported function, get_compendium.
>    There ought to be more functionality available.
>
> I want to stick to the do one thing and do it well. Access to 170,000
microbiome samples, all homogeneously processed, is quite a bit of
functionality, even though it is implemented as a single function. Just a
reminder that GEOquery also exposes only one function (not quite true, but
basically that is the case). If you have thoughts about improving the data
access functionality, please share them.

>
>    - Vignette is incomplete. It has some [ ] TODO parts. It would be
>    interesting to demonstrate the identification of an association between
>    some genus and some sample phenotype. Demonstrate its biological usefulness.
>
> The data do not include sample phenotypes just yet. The rationale is that
the paper (in preparation) describing these data and analyzing them focuses
on regional variation. I'll add some additional documentation and use cases
to the vignette(s). These will largely expose functionality from other
packages, though. I don't foresee lots of analysis functionality going into
MicroBioMap.

**Comment by DarioS** [comment]
Are any more commits expected soon? I still see [open issues](https://github.com/seandavi/MicroBioMap/issues) remaining in the tracker.

**Comment by lshep** [comment]
@seandavi any additional comments in response to @DarioS ?

**Comment by seandavi** [comment]
I don't have anything else right now, no. I'm fine if you'd rather this just go into devel for the next release cycle.

**Comment by lshep** [comment]
Is the package still being worked on @seandavi  or is it ready for a review by @DarioS ?

**Comment by seandavi** [comment]
Hi, @DarioS and @lshep. Collaborators are still working on components of the package. I'm going to close this for now and will reopen when their contributions are complete.

**Comment by DarioS** [comment]
Now that the journal article is published, it might be a good time to crack the metaphorical whip on Rich Abdill.

**Comment by seandavi** [comment]
The package has been transferred to another owner and repository, so this contribution is now defunct. I'm no longer directly involved with the project, but the team may still have plans to do a submission. I'll ping them. Thanks for the reminder!
