### ISSUE TITLE
homosapienDEE2CellScore data package

### ISSUE THREAD

**Issue by flaviusb** [Bioconductor/Contributions#3101]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/flaviusb/homosapienDEE2CellScore

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission.  The vignette has no explanatory content.  Please examine other package vignettes and make improvements so that a visitor to your package can understand its intent and value.

**Comment by lshep** [comment]
@flaviusb Do you plan on revising the package?

**Comment by flaviusb** [comment]
Yes, I do plan on revising this, I just missed the notification somehow and got busy at work.

**Comment by vjcitn** [comment]
update?

**Comment by lshep** [comment]
As there has been no progress we will close the issue for inactivity.  When you have made changes please comment here that we should look at reopen the issue.

**Comment by flaviusb** [comment]
I have made some updates - expanding out the vignette with some explanatory text to show what the data package contains and explaining the usage of it.

**Comment by lshep** [comment]
Can you please correct ERROR, warnings, notes before proceeding with an assigned reviewer

**Comment by flaviusb** [comment]
I am working on this again.

**Comment by lshep** [comment]
Please push changes to git.bioconductor.org to trigger a new report.

**Comment by Kayla-Morrell** [comment]
@flaviusb - Thank you for submitting to _Bioconductor_. Please see the initial review of 
the package below. The required changes must be made while the suggested 
changes do not have to be (though we strongly encourage them). Comment back 
here with updates that have been made and when the package is ready for a 
re-review.

## General package development

- [ ] REQUIRED: When the package is accepted, please include instructions to the README file on how to install the package from Bioconductor.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding the maintainer's ORCID iD in 'Authors@R' with 'comment=c(ORCID="...")'.
- [ ] SUGGESTION: Consider adding the automatically suggested biocViews:
	ExpressionData
- [ ] SUGGESTION: We encourage the use of the 'BugReports:' field which includes the relevant link to GitHub for reportings issues.

## NEWS file

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements.

## Citation

- [ ] SUGGESTION: (Optional) CITATION file not found. Only include a CITATION file if there is a preprint or publication for this Bioconductor package. Note that Bioconductor packages are not required to have a CITATION file but it is useful both for users and for tracking Bioconductor project-wide metrics. When including a CITATION file, add the publication using the 'doi' argument of 'bibentry()'.

## Vignette

- [ ] SUGGESTION: We suggest using the 'BiocStyle' package for formatting.
- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to the user how to install the package from Bioconductor. This code chunk should include `eval = FALSE`.
- [ ] SUGGESTION: We suggest the use of table of contents.
- [ ] REQUIRED: 'sessionInfo' not found in vignette which we require.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the package and links to the main function. Users should be able to have a relevant page display with `?homosapienDEE2CellScore`.
- [ ] REQUIRED: All man pages that document exported objects need to contain runnable examples.
- [ ] SUGGESTION: Checking Rd line widths. Lines wider than 100 characters will be truncated in the PDF manual.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See https://contributions.bioconductor.org/tests.html.

## R code

- [ ] SUGGESTION: Avoid 'sapply()', use 'vapply()' instead.
- [ ] SUGGESTION: Avoid 'cat' and 'print' outside of 'show' methods.
- [ ] SUGGESTION: Avoid using '=' for assignment and use '<-' instead
- [ ] SUGGESTION: Avoid 'suppressWarnings'/'*Messages' if possible
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 160 lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 175 lines that are not.

Best,
Kayla

**Comment by Kayla-Morrell** [comment]
@flaviusb - Thank you for making the necessary changes. I've reviewed everything and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/flaviusb.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("homosapienDEE2CellScore")`. The package 'landing page' will be created at

https://bioconductor.org/packages/homosapienDEE2CellScore

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
