### ISSUE TITLE
AnnotationFilter

### ISSUE THREAD

**Issue by jotsetung** [Bioconductor/Contributions#311]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/AnnotationFilter

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Hi,

1) biocViews
I'd add some more. How about Software and Infrastructure? Even though these are top-level terms they are still descriptive.

2) vignette
I'd recommend adding a Background or Introduction. Overall I didn't get a good feel for why these are important or how they should be used. I think it's worth mentioning / clarifying the points listed below.

- Background
 -- Why was this package created, why the need for more flexible or more structured filtering, etc.
 -- Clearly state that these filters were designed to work on sqlite database tables. If there are other restrictions they should be mentioned up front, e.g., how the db tables are structured or related to each other etc. Can any user with annotation data in an sqlite db use these, etc.
 
- Filter Classes
 -- show how to discover the filters, i.e., supportedFilters()
 -- mention the general categories of filter (character, integer and other ...) and highlight their qualities
 -- discuss filter qualities, e.g., they can be created but not changed, subsetting, overlap operations ...
 -- examples of creating and manipulating filters

- Using the filters
  The ensembl.db example is complicated and non-intuitive. If I were a user reading this for the first time I would think the overhead involved is too much and just write my own. Don't some of the functions in Organism.dplyr use these filters ... ? I guess Organism.dplyr can't be modified to use AnnotationFilter until this is approved. At any rate, starting with a simple example would be helpful. Maybe use just an OrgDb or TxDb then move on to the ensembl.db/EnsDb as an advanced example.

  It would be helpful to demonstrate how one would look at the columns of a sqlite database to determine what filter(s) would be appropriate (column name must be present to use a specific filter). Then choose a filter and modify an existing function to use the filter. Walk the user through the process step-by-step.

Valerie

**Comment by jotsetung** [comment]
Thank you Valerie @vobencha for your helpful suggestions. I expanded the vignette and added more examples - actually using an `ensembldb` SQLite database, which in the end breaks the vignette because the `ensembldb` in the devel branch does not yet import and use `AnnotationFilter`. Thus methods and classes get masked once the `ensembldb` package is loaded.

I will replace the `ensembldb` database with another database (`TxDb` or similar) to fix the problem.

Jo

**Comment by jotsetung** [comment]
I'm using now the `org.Hs.eg.db` SQLite database as an example to show how a very simple filtering could be setup using `AnnotationFilter`. Suggestions to further improve the vignette are welcome.
