### ISSUE TITLE
TSAR

### ISSUE THREAD

**Issue by CGAO123** [Bioconductor/Contributions#3113]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CGAO123/TSAR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by CGAO123** [comment]
I am having issues with pushing to bioconductor branch. The error relates having a .rapphistory file in the directory, which I have deleted in my github repo and pushed to upstream devel branch. I have pushed the changes to `git@git.bioconductor.org:packages/TSAR`, but it appears from the new build that the change is not reflected. I attempted re-pushing, and I was noted that everything is already up-to-date.
How can I check to make sure that I have the write version in the bioconductor branch.

**Comment by lshep** [comment]
did you do `git rm` to officially delete it and `git commit` it accordingly?

**Comment by CGAO123** [comment]
I manually deleted the file on github and pushed the changes. Right now, git rm cannot find the deleted file.

**Comment by DarioS** [comment]
The package is a fairly well-developed state. I note some issues with Bioconductor's coding requirements, however.

- Bioconductor already has some qPCR software such as [NormqPCR](https://bioconductor.org/packages/release/bioc/html/NormqPCR.html) and [HTqPCR](https://bioconductor.org/packages/release/bioc/html/HTqPCR.html). How does TSAR differ to those?
- Three separate Shiny applications seems clunky. How about three [tabs](https://rstudio.github.io/shiny/reference/tabsetPanel.html) in one application?

> TSAR contains three separate Shiny application regarding, data pre-processing, data analysis, and data visualization.

- Widespread use of `for` loops. While rarely necessary, they can often be replaced by fast vectorisation. See [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize).
- Lack of inline code commenting. See [Comments](https://contributions.bioconductor.org/r-code.html?q=comments#rcode-comments). Comments are useful if new maintainer takes over package updates.
- When a function parameter should be one of a limited set of values, use [match.arg](https://stat.ethz.ch/R-manual/R-devel/library/base/html/match.arg.html) to check for validity. For example, `y` for `TSA_average` does not.
- The vignette should be organised according to the requirements. See [Vignettes](https://contributions.bioconductor.org/docs.html#vignettes). Introduction and Installation sections are lacking. I do not even see what T.S.A. is an abbreviation for. Current installation instructions need to remove `remotes` and replace by [BiocManager](https://cran.r-project.org/web/packages/BiocManager/vignettes/BiocManager.html) which can install from GitHub until a package is accepted into Bioconductor.
- Example data sets' provenance is not clear. See [Data](https://contributions.bioconductor.org/docs.html#data-man). Is data available from a repository? What is the accession ID?
- Vignette code chunk results lacks interpretation. Add one or two sentences after each result explaining to the reader what they should notice from the result.
- No non-Shiny vignette chunks are allowed to have `eval = FALSE`. Please see [Evaluated Code Chunks](https://contributions.bioconductor.org/docs.html#evaluated-code-chunks).

**Comment by CGAO123** [comment]
Hi Dario, thank you for reviewing my package. 

TSAR stands for Thermal Shift Analysis(TSA) in R. TSA is a type of qPCR data given it is outputted by QuantStudio. However, TSA analyzes a completely different topic, protein unfolding curve, which NormqPCR and HTqPCR do not focus on. I have now updated all my vignettes to include this explanation in the correct vignette structure.

Regarding the three separate shiny applications, they are implemented separately because the workflow can be accessed in all these three different stages independently. I kept them separate so that it is easier for user to exit and re-enter workflow freely given the experiments for TSA analysis usually take place over a long span of time.

Regarding for-loops, I made some edits to remove unnecessary ones. I also added more inline comments to notate the codes better. All match.arg() checks for parameters with limited set of values are implemented now. Proper notation for installing package through biocmanager is also implemented. Lastly, all eval=false on non-shiny command are now removed.

Regarding the provenance of dataset. They are experimentally obtained by me and I have now updated my man pages to include such information.

Thank you so much for the edit suggestions and let me know if there are any other things I can improve on.

Best

**Comment by DarioS** [comment]
There are still some `for` loops remaining which can straightforwardly be vectorised.

```r
    dataset <- c()
    for (i in seq_len(length(data))) {
        if (is.data.frame(data[[i]]) == FALSE) {
            dataset[[i]] <- data.frame(read.csv(file = toString(data[i]), header = TRUE))
        } else {
            dataset[[i]] <- data.frame(data[[i]])
        }
    }
```

and

```r
tsar_data <- c()
for (i in seq_len(length(dataset))) {
        cur <- dataset[[i]]
        cur <- mutate(cur, ExperimentFileName = name[i])
        tsar_cur <- cur %>% mutate(well_ID = paste(cur$Well.Position, cur$Protein, cur$Ligand, date[i], sep = "_"))
        tsar_data <- rbind(tsar_data, tsar_cur)
    }
```

Please consider my illustrative example.

```r
personNames <- c("Adam", "Ben", "Chris")
dataFrameList <- lapply(personNames, function(name) data.frame(Name = name, Age = rpois(1, 30)))
dataFrameCombined <- do.call(rbind, dataFrameList) # rbind all of them once to be memory-efficient.
dataFrameCombined
```

**Comment by CGAO123** [comment]
Thank you so much for the suggestion and the example illustration. I have now changed several for-loops to lapply and ensured all tests were passed appropriately. Please let me know of any other plausible enhancements.

**Comment by DarioS** [comment]
There are still some inefficient `for` loops remaining that iteratively reallocate memory.

```r
screened <- data.frame()
for (i in unique(section$Well.Position)) {
  ...                ...
  screened <- rbind(screened, by_well)
}
```

and 

```r
kept <- data.frame()
for (i in unique(raw_data$Well.Position)) {
  ...                ...
  kept <- rbind(kept, by_well)
}
```

**Comment by CGAO123** [comment]
Thank you for pointing it out, I have changed these using vectorise. I also removed couple other inefficient for loops I saw. Please let me know if I have missed other plausible enhancements.

**Comment by DarioS** [comment]
The package has been substantially improved.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/CGAO123.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TSAR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TSAR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
