### ISSUE TITLE
pgxRpi

### ISSUE THREAD

**Issue by hangjiaz** [Bioconductor/Contributions#3120]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/progenetix/pgxRpi

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Please explain in your vignette what "progenetix" is.  Is it a versioned data resource?  Please imagine a newcomer coming to your package, reading the vignettes to find inspiration to learn about your tool.

**Comment by hangjiaz** [comment]
Hi @vjcitn,

Thanks for your feedback. I have updated the vignettes as suggested.

**Comment by LiNk-NY** [comment]
Hi @hangjiaz 

Thank you for your submission. 
After a brief review, there were some major issues with the package.
Please see the notes below.

Best,
Marcel

---

# pgxRpi

* The package does not make use of Bioconductor infrastructure (e.g., `GRanges`,
`RaggedExperiment`, etc.) and copies code from the `copynumber` package. 
Has this been cleared with the maintainer of `copynumber`?

## DESCRIPTION

* Wrap Description to 80 line width.

## NAMESPACE

* Minimal number of exports, looks good.

## vignettes

* How can users discover filters, sample and individual identifiers?
* Is the package's main aim to provide an API to the data? There are examples
of analyses and plotting which may be more appropriate in another package(s).
* The `cnv_matrix` has combined data in the column names, is there a way
to resolve this and have uniform names / data? For example, some columns are
`X.67000000.68000000.DEL` and others are `X1.1400000.2400000.DUP`.
* It looks like there are multiple copies of the data in `freq_pgxfreq`.
Consider only providing either both "NCIT:C4038", "pgx:icdom-85003" or just
"total".
* Why not use a Bioconductor representation for `freq_pgxfreq` such as
`GRanges` or `RaggedExperiment`?

## R

* Remove copy-and-append code in `transform_id`. It seems that you simply want
to do `paste(..., collapse = ",")`.
* Rename the data to have more specific names (e.g., `hg19` is too broad).
* It looks like there is code copied and pasted from the `copynumber` package.
* Reduce code repetition by creating helper functions, e.g., for obtaining
`remain.id` from multiple URLs. This will also reduce the cyclomatic
complexity of the software.

**Comment by hangjiaz** [comment]
Hi Marcel @LiNk-NY,

Thanks very much for your review and valuable suggestions! The point-to-point response is below:

> # pgxRpi
> * The package does not make use of Bioconductor infrastructure (e.g., `GRanges`,
>   `RaggedExperiment`, etc.) and copies code from the `copynumber` package.
>   Has this been cleared with the maintainer of `copynumber`?
* **In the latest version, the main change is in the data structure of CNV frequency data, which consists of CNV frequency values and associated metadata. Originally this data was a list with two slots "data" and "meta".
Following suggestions, now we store "freq_pgxfreq" using the *GRangesList* infrastructure and store "freq_pgxmatrix" using the *RangedSummarizedExperiment* container based on their different data formats.** 
* **The code in “helper_pgxFreqplot.R” is taken from the `copynumber` package with minor modifications. Since `copynumber` uses the Artistic 2.0 license, based on the [rule](https://opensource.org/license/artistic-2-0/) I queried, I could distribute the modified version as source, provided that I clearly document how it differs from the standard version and use the original license. `pgxRpi` uses the same license as `copynumebr` (Artistic 2.0) and I have placed the reference and modification notice at the top of the relevant script “helper_pgxFreqplot.R”.  However, if this approach is not in accordance with proper licensing or if there are any concerns, kindly inform me, and I will make the necessary adjustments.**

> ## DESCRIPTION
> * Wrap Description to 80 line width.
**Changed**
> ## NAMESPACE
> * Minimal number of exports, looks good.
> 
> ## vignettes
> * How can users discover filters, sample and individual identifiers?
**Added description of concepts for filters, sample, and individual identifiers and how to discover them in vignette "Introduction_1_loadmetadata".**
> * Is the package's main aim to provide an API to the data? There are examples
>   of analyses and plotting which may be more appropriate in another package(s).
**Agreed and removed survival analysis in vignette "Introduction_1_loadmetadata" and CNV frequency clustering analysis in vignette "Introduction_3_loadfrequency".**
> * The `cnv_matrix` has combined data in the column names, is there a way
>   to resolve this and have uniform names / data? For example, some columns are
>   `X.67000000.68000000.DEL` and others are `X1.1400000.2400000.DUP`.
**The column name of cnv_matrix follows the format [chr].[start].[end].[cnv type]. Importing the data into R causes an "X" prefix before autosomes because they are numbers, which can be misleading. To fix this, I replaced the "X" prefix with "chr". For example, the columns are `chrX.67000000.68000000.DEL` and `chr1.1400000.2400000.DUP` now.**
> * It looks like there are multiple copies of the data in `freq_pgxfreq`.
>   Consider only providing either both "NCIT:C4038", "pgx:icdom-85003" or just
>   "total".
> * Why not use a Bioconductor representation for `freq_pgxfreq` such as
>   `GRanges` or `RaggedExperiment`?
**The new "freq_pgxfreq" is a *GRangeslist* containing multiple *GRanges* objects for each filer, and the "total" data has been removed. The corresponding vignette has been changed accordingly.**
> ## R
> * Remove copy-and-append code in `transform_id`. It seems that you simply want
>   to do `paste(..., collapse = ",")`.
**Fixed, I admit the original code is stupid.**  
> * Rename the data to have more specific names (e.g., `hg19` is too broad).
**I renamed the data from "hg19" "hg38" to "hg19_cytoband" "hg38_cytoband".**
> * It looks like there is code copied and pasted from the `copynumber` package.
**I restructured the previous reference announcement and added details about which functions I changed.**
> * Reduce code repetition by creating helper functions, e.g., for obtaining
>   `remain.id` from multiple URLs. This will also reduce the cyclomatic
>   complexity of the software.
**Agreed, I created a `disease_code_check` helper function to reduce code repetition for the `pgidCheck` function.**

Please let me know if there are further changes that need to be made.

Best,
Hangjia

**Comment by LiNk-NY** [comment]
Hi HangJia, @hangjiaz 

Thank you for making those changes. The package is in a better state. 

I was suggesting that it would be good to expose the terms to the users in addition to referring them to the API documentation. For example, you could expose the "resources" section in https://progenetix.org/beacon/filtering_terms/ to inform the users what resource IDs are available. With the resource ID, the users can then see a list of available IDs parsed from the linked JSON file, e.g.,: 

```json
            {
                "count": 60,
                "id": "cbioportal:acyc_mskcc_2013",
                "label": "",
                "type": "ontologyTerm"
            },
            {
                "count": 253,
                "id": "cbioportal:aml_target_2018_pub",
                "label": "",
                "type": "ontologyTerm"
            }
```

This would enhance the user's experience and they would spend less time browsing through all the IDs on the website. 

Please see `GenomicDataCommons::available_fields(x=GenomicDataCommons::cases())` as an example of returning filter IDs. 
This may also be applicable to other filters such as `biosamples` etc.

Consider using a more formal API request mechanism, i.e. with the `httr` package and using `httr::GET` rather than `rjson::fromJSON` which would allow for `httr::stop_for_status` and `httr::content` calls on the response. 

Please use a more simple default argument for `filters` in `pgxLoader` e.g.,: `c("biosample", "variant","frequency","individual")` and select from the options with `match.arg`. Any argument outside of that would produce an error from `match.arg`. If possible, reduce the number of `if` statements in the function. 

Note that `if (x == TRUE)` is the same as `if (x)` in reference to `R/pgxSegprocess.R`. If you are expecting alternative values in those variables, consider using `isTRUE()`.

**Comment by hangjiaz** [comment]
Hi Marcel, @LiNk-NY 

Thanks very much for your valuable suggestions, which are really helpful! Here is my response:

> I was suggesting that it would be good to expose the terms to the users in addition to referring them to the API documentation. For example, you could expose the "resources" section in https://progenetix.org/beacon/filtering_terms/ to inform the users what resource IDs are available. With the resource ID, the users can then see a list of available IDs parsed from the linked JSON file.
> This would enhance the user's experience and they would spend less time browsing through all the IDs on the website.
> 
> Please see `GenomicDataCommons::available_fields(x=GenomicDataCommons::cases())` as an example of returning filter IDs. This may also be applicable to other filters such as `biosamples` etc.

I completely agree with the idea of exposing all available filters to make querying easier. To address this, I've created the `pgxFilter` function, which allows users to access all filters or specific ones based on a specified prefix. This function, along with the `pgxCount` function, provides more comprehensive metadata. As for the omission of other identifiers such as  `biosample_id`, it is because it's part of the biosample metadata returned by the `pgxLoader` function.

> Consider using a more formal API request mechanism, i.e. with the `httr` package and using `httr::GET` rather than `rjson::fromJSON` which would allow for `httr::stop_for_status` and `httr::content` calls on the response.

Noted and updated. The package no longer utilizes the *rjson* package, and I've adjusted the DESCRIPTION accordingly.

> Please use a more simple default argument for `filters` in `pgxLoader` e.g.,: `c("biosample", "variant","frequency","individual")` and select from the options with `match.arg`. Any argument outside of that would produce an error from `match.arg`. If possible, reduce the number of `if` statements in the function.

* Your suggestion regarding the `match.arg` function is greatly appreciated. I've simplified the `type` argument to accept values "b" (biosample), "i" (individual), "v" (variant), or "f" (frequency), and this is now included in documentation.

* To reduce `if` statements within the `pgxLoader` function, I've introduced two new functions, `checkMissingParameters` and `checkUnusedParameters` in the "helper_pgxLoader.R" script. These functions make argument checking more straightforward and the code more streamlined.

> Note that `if (x == TRUE)` is the same as `if (x)` in reference to `R/pgxSegprocess.R`. If you are expecting alternative values in those variables, consider using `isTRUE()`.

I've simplified the code accordingly.

**Comment by LiNk-NY** [comment]
> * Your suggestion regarding the `match.arg` function is greatly appreciated. I've simplified the `type` argument to accept values "b" (biosample), "i" (individual), "v" (variant), or "f" (frequency), and this is now included in documentation.

It's best to leave the argument as `type = c("biosample", "variant","frequency","individual")` and then use `match.arg` within the function to select a default (usually the first option)

**Comment by hangjiaz** [comment]
Hi Marcel, @LiNk-NY

> It's best to leave the argument as `type = c("biosample", "variant","frequency","individual")` and then use `match.arg` within the function to select a default (usually the first option)

Thanks for your suggestions, I have changed "pgxLoader.R" and vignettes accordingly.

**Comment by LiNk-NY** [comment]
Hi HangJia, @hangjiaz 

Thank you for making those changes! 
Your package has been accepted.

Best regards,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hangjiaz.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pgxRpi")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pgxRpi

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
