### ISSUE TITLE
GNOSIS

### ISSUE THREAD

**Issue by Lydia-King** [Bioconductor/Contributions#3132]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Lydia-King/GNOSIS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Can the vignette provide some more concrete illustration of the capabilities?  The link to the paper is useful but the package vignette is an opportunity to provide a concise illustration of major benefits achievable through the use of the package/app.

**Comment by Lydia-King** [comment]
I have updated the vignette to provide a brief overview of what you can do in GNOSIS, including screenshots. If additional information is needed, please let me know.

**Comment by jianhong** [comment]
# Package 'GNOSIS' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.
## The DESCRIPTION file
- [ ] R version is not clear in DESCRIPTION.
## The NAMESPACE file
- [ ] Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 4 import(DT)
	* in line 5 import(RColorBrewer)
	* in line 6 import(cBioPortalData)
	* in line 7 import(compareGroups)
	* in line 8 import(fontawesome)
	* in line 9 import(partykit)
	* in line 10 import(reshape2)
	* in line 11 import(rpart)
	* in line 12 import(shinycssloaders)
	* in line 13 import(shinyjs)
	* in line 15 import(survival)
	* in line 16 import(survminer)

## R code
- [ ] Important: `vapply` instead of `sapply`.
	* In file R/Global_Functions.R:
		+ at line 6 found 'sapply <- base::sapply'
- [ ] Important: `showNotification` instead of `cat` and `print` outside of `show` methods.
	* In file R/Global_Functions.R:
		+ at line 44 found '                print(datalist[[plot]]())'
		+ at line 59 found '                    print(datalist[[plot]]())'
		+ at line 80 found '                print(plot(datalist[[plot]]()))'
		+ at line 95 found '                    print(datalist[[plot]]())'
		+ at line 117 found '                print(datalist[[plot]]())'
		+ at line 132 found '                    print(datalist[[plot]]())'
	* In file R/Tab1_Input_Files_Server.R:
		+ at line 647 found '                        print(m$message)'
	* In file R/Tab4_Exploratory_Plots_Server.R:
		+ at line 527 found '                print(CNAHistogram())'
		+ at line 542 found '                print(CNAHistogram())'
		+ at line 564 found '                    print(CNAHisttab())'
		+ at line 580 found '                    print(CNAHisttab())'
		+ at line 748 found '                print(CNADense())'
		+ at line 764 found '                print(CNADense())'
		+ at line 933 found '                    print(CNADist1Plot())'
		+ at line 949 found '                    print(CNADist1Plot())'
		+ at line 1070 found '                    print(CNADist2Plot())'
		+ at line 1086 found '                    print(CNADist2Plot())'
		+ at line 1265 found '                print(CNABoth())'
		+ at line 1280 found '                print(CNABoth())'
		+ at line 1408 found '                    print(CNADist2Plot1())'
		+ at line 1424 found '                    print(CNADist2Plot1())'
	* In file R/Tab5_KaplanMeier_Plots_Server.R:
		+ at line 552 found '                    print(KMR1Plot())'
		+ at line 568 found '                    print(KMR1Plot())'
		+ at line 585 found '                print(KMR2Plot())'
		+ at line 600 found '                print(KMR2Plot())'
	* In file R/Tab6_Association_Tests_Server.R:
		+ at line 91 found '                            cat(noquote('
		+ at line 105 found '                            print(stats::chisq.test(..('
		+ at line 379 found '                            cat(noquote('
		+ at line 393 found '                            print(stats::fisher.test('
		+ at line 531 found '                                    cat('
		+ at line 666 found '                                    cat(noquote('
		+ at line 680 found '                                    print(stats::fisher.test('
		+ at line 686 found '                                    cat('
		+ at line 755 found '                                    cat('
		+ at line 834 found '                                    cat('
		+ at line 957 found '                            cat(noquote('
		+ at line 972 found '                            print(car::leveneTest('
		+ at line 1096 found '                            cat(noquote('
		+ at line 1110 found '                            print(stats::fligner.test('
		+ at line 1235 found '                            cat(noquote('
		+ at line 1261 found '                            print(as.data.frame(Data1))'
		+ at line 1262 found '                            print(stats::shapiro.test(..(datalist1[[data]]('
		+ at line 1385 found '                            cat(noquote('
		+ at line 1400 found '                            print(summary(res.aov))'
		+ at line 1657 found '                            cat(noquote('
		+ at line 1671 found '                            print(Kw)'
		+ at line 1940 found '                            cat(noquote('
		+ at line 1955 found '                            print(stats::pairwise.t.test('
		+ at line 2107 found '                            cat(noquote('
		+ at line 2121 found '                            print('
		+ at line 2318 found '                print(..(Compare_Code()))'
	* In file R/Tab7_Cox_PH_Models_Server.R:
		+ at line 131 found '                            cat(noquote(paste('
		+ at line 164 found '                            print(summary(res.cox))'
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.

- [ ] Important: `1:n` is not suggested in source code. Use `seq_along` or `seq.int` instead.

	* In file R/Tab4_Exploratory_Plots_Server.R:
		+ at line 782 found '                        as.character(1:..('
		+ at line 786 found '                        x = c(1:length(..('
		+ at line 853 found '                        x = c(1:length(..('
	* In file R/Tab6_Association_Tests_Server.R:
		+ at line 33 found '                    for (i in 1:length(..(input$Tab6_Select_Categorical_Variable_2))) {'
		+ at line 86 found '                        for (i in 1:length(c('
		+ at line 93 found '                                    "Categorical Variable 1:",'
		+ at line 163 found '                        for (i in 1:length(..('
		+ at line 223 found '                        for (i in 1:length(..('
		+ at line 319 found '                    for (i in 1:length(..(input$Tab6_Select_Categorical_Variable_2))) {'
		+ at line 374 found '                        for (i in 1:length(c('
		+ at line 381 found '                                    "Categorical Variable 1:",'
		+ at line 448 found '                        for (i in 1:length(..('
		+ at line 503 found '                        for (i in 1:length(..('
		+ at line 610 found '                    for (i in 1:length(..(input$Tab6_Select_Categorical_Variable_2))) {'
		+ at line 659 found '                        for (i in 1:length(c('
		+ at line 668 found '                                            "Categorical Variable 1:",'
		+ at line 744 found '                        for (i in 1:length(..('
		+ at line 808 found '                        for (i in 1:length(..('
		+ at line 954 found '                        for (i in 1:length(..('
		+ at line 1029 found '                        for (i in 1:length(..('
		+ at line 1093 found '                        for (i in 1:length(..('
		+ at line 1166 found '                        for (i in 1:length(..('
		+ at line 1230 found '                        for (i in 1:length(c('
		+ at line 1314 found '                        for (i in 1:length(..('
		+ at line 1375 found '                        for (i in 1:length(c('
		+ at line 1452 found '                        for (i in 1:length(..('
		+ at line 1510 found '                        for (i in 1:length(c('
		+ at line 1649 found '                        for (i in 1:length(..('
		+ at line 1719 found '                        for (i in 1:length(..('
		+ at line 1778 found '                        for (i in 1:length(..('
		+ at line 1937 found '                        for (i in 1:length(..('
		+ at line 2026 found '                        for (i in 1:length(..('
		+ at line 2104 found '                        for (i in 1:length(..('
		+ at line 2195 found '                        for (i in 1:length(..('
	* In file R/Tab7_Cox_PH_Models_Server.R:
		+ at line 128 found '                        for (i in 1:length(..('
		+ at line 229 found '                        for (i in 1:length(..('
	* In file R/Tab8_Adjusted_Survival_Curves_Server.R:
		+ at line 97 found '                        for (n_levels_1 in 1:length(levels(as.factor(..('
		+ at line 115 found '                        for (n_levels_2 in 1:length(levels(as.factor(..('
		+ at line 134 found '                            data.frame("Row" = 1:length(Levels_Vector_2)) %>%'
		+ at line 157 found '                        for (n_levels_1 in 1:length(levels(as.factor(..('
		+ at line 175 found '                        for (n_levels_2 in 1:length(levels(as.factor(..('
		+ at line 194 found '                            data.frame("Row" = 1:length(Levels_Vector_2)) %>%'
		+ at line 212 found '                        for (constant_var in 1:length(..('
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/Tab6_Association_Tests_Server.R:
		+ at line 33 found '                    for (i in 1:length(..(input$Tab6_Select_Categorical_Variable_2))) {'
		+ at line 86 found '                        for (i in 1:length(c('
		+ at line 163 found '                        for (i in 1:length(..('
		+ at line 223 found '                        for (i in 1:length(..('
		+ at line 319 found '                    for (i in 1:length(..(input$Tab6_Select_Categorical_Variable_2))) {'
		+ at line 374 found '                        for (i in 1:length(c('
		+ at line 448 found '                        for (i in 1:length(..('
		+ at line 503 found '                        for (i in 1:length(..('
		+ at line 610 found '                    for (i in 1:length(..(input$Tab6_Select_Categorical_Variable_2))) {'
		+ at line 659 found '                        for (i in 1:length(c('
		+ at line 744 found '                        for (i in 1:length(..('
		+ at line 808 found '                        for (i in 1:length(..('
		+ at line 954 found '                        for (i in 1:length(..('
		+ at line 1029 found '                        for (i in 1:length(..('
		+ at line 1093 found '                        for (i in 1:length(..('
		+ at line 1166 found '                        for (i in 1:length(..('
		+ at line 1230 found '                        for (i in 1:length(c('
		+ at line 1314 found '                        for (i in 1:length(..('
		+ at line 1375 found '                        for (i in 1:length(c('
		+ at line 1452 found '                        for (i in 1:length(..('
		+ at line 1510 found '                        for (i in 1:length(c('
		+ at line 1649 found '                        for (i in 1:length(..('
		+ at line 1719 found '                        for (i in 1:length(..('
		+ at line 1778 found '                        for (i in 1:length(..('
		+ at line 1937 found '                        for (i in 1:length(..('
		+ at line 2026 found '                        for (i in 1:length(..('
		+ at line 2104 found '                        for (i in 1:length(..('
		+ at line 2195 found '                        for (i in 1:length(..('
	* In file R/Tab7_Cox_PH_Models_Server.R:
		+ at line 128 found '                        for (i in 1:length(..('
		+ at line 229 found '                        for (i in 1:length(..('
	* In file R/Tab8_Adjusted_Survival_Curves_Server.R:
		+ at line 97 found '                        for (n_levels_1 in 1:length(levels(as.factor(..('
		+ at line 115 found '                        for (n_levels_2 in 1:length(levels(as.factor(..('
		+ at line 157 found '                        for (n_levels_1 in 1:length(levels(as.factor(..('
		+ at line 175 found '                        for (n_levels_2 in 1:length(levels(as.factor(..('
		+ at line 212 found '                        for (constant_var in 1:length(..('
- [ ] Important: Use `file.path` to replace `paste`
	* In file R/Tab1_Input_Files_Server.R:
		+ at line 232 found '                                if (file.exists(paste0(file_dir, "/", samp, "/data_cna.txt"))) {'
- [ ] NOTE: Functional programming: code repetition. There are lots of code repetition. I list one here for your information.
	* repetition in `Tab7_Multivariate_CoxPH` and `Tab7_Univariate_CoxPH`
		+ in Tab7_Multivariate_CoxPH
			- line 6:            width = 12, status = "primary", dropdownMenu = boxDropdown(icon = fontawesome::fa_i(name = "info-circle", 
			- line 7:                verify_fa = FALSE), boxDropdownItem(HTML(paste("Useful Resources for Cox Models:", 
			- line 8:                "<br/>")), tags$a(href = "http://www.sthda.com/english/wiki/cox-proportional-hazards-model", 
			- line 9:                "Cox PH Model Basics in R"), tags$a(href = "http://www.sthda.com/english/wiki/cox-model-assumptions", 
			- line 16:            sidebar = boxSidebar(id = "Tab7_Multivariable_Cox_Sidebar", 
			- line 17:                width = 25, background = "#599740", icon = shiny::icon("rectangle-list"), 
			- line 18:                selectizeInput(ns("Tab7_Multivariable_Cox_Survival_Time"), 
			- line 19:                  "Survival Time:", choices = "", width = "95%"), 
			- line 20:                selectizeInput(ns("Tab7_Multivariable_Cox_Event_Status"), 
			- line 21:                  "Event Status:", choices = "", width = "95%"), 
			- line 22:                selectizeInput(ns("Tab7_Multivariable_Cox_Select_Variables"), 
			- line 23:                  "Select Variable:", choices = "", multiple = TRUE, 
		+ in Tab7_Univariate_CoxPH
			- line 4:        dropdownMenu = boxDropdown(icon = fontawesome::fa_i(name = "info-circle", 
			- line 5:            verify_fa = FALSE), boxDropdownItem(HTML(paste("Useful Resources for Cox Models:", 
			- line 6:            "<br/>")), tags$a(href = "http://www.sthda.com/english/wiki/cox-proportional-hazards-model", 
			- line 7:            "Cox PH Model Basics"), tags$a(href = "http://www.sthda.com/english/wiki/cox-model-assumptions", 
			- line 12:        sidebar = boxSidebar(id = "Tab7_Univariate_Cox_Sidebar", 
			- line 13:            width = 25, background = "#599740", icon = shiny::icon("rectangle-list"), 
			- line 14:            selectizeInput(ns("Tab7_Univariate_Cox_Survival_Time"), 
			- line 15:                "Survival Time:", choices = "", width = "95%"), 
			- line 16:            selectizeInput(ns("Tab7_Univariate_Cox_Event_Status"), 
			- line 17:                "Event Status:", choices = "", width = "95%"), 
			- line 18:            selectizeInput(ns("Tab7_Univariate_Cox_Select_Variables"), 
			- line 19:                "Select Variable:", choices = "", multiple = TRUE, 
- [ ] Important: When use `API Upload`, it ask input `y/n` in background to `Create cBioPortalData cache at $Caches_folder` for the first run.
## Documentation
- [ ] Important: Vignette should have an *Introduction* section..
	* rmd file vignettes/GNOSIS.Rmd
- [ ] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/GNOSIS.Rmd
- [ ] Note: The font in the images is hard to read.  
	* rmd file vignettes/GNOSIS.Rmd
- [ ] Note: Lacking help information for `Recode/Subset Data`. No error message when showing a blank plot in `Exploratory Plots`.

**Comment by Lydia-King** [comment]
# Response to Review 
 Thank you @jianhong for the comments and suggestions. Please find my response below. 

 ## The DESCRIPTION file
 * [x]  R version is not clear in DESCRIPTION.
   * Added R version to DESCRIPTION. 

 ## The NAMESPACE file
 * [x]  Selective imports using `importFrom` instead of _import all_ with `import`.
   * Used `importFrom` for listed packages.
 
 ## R code
 * [x]  Important: `vapply` instead of `sapply`.
   * Changed `sapply` to `vapply`.

 * [x]  Important: `showNotification` instead of `cat` and `print` outside of `show` methods.
   * Addressed. Either removed `print`/`cat` from code or changed to `show_object()`. The `show()` function is already used by the shinyjs package, so had to use `show_object()`, defined by `show_object <- methods::show` in R/Global_Functions.R.   

 * [x]  NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
   * Removed `::` from all R scripts, except Global_Functions.R where `::` is used to define functions that may occur in multiple packages.  

 * [x]  Important: `1:n` is not suggested in source code. Use `seq_along` or `seq.int` instead.
   Changed all `1:n` to `seq.int` except for R/Tab6_Association_Tests_Server.R lines 93, 380 and 665, where the `1:` is part of a text string.  

 * [ ]  NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
   * Thank you for the suggestion, this point has not been addressed but will be heavily considered going forward. 

 * [x]  Important: Use `file.path` to replace `paste`
   * Replaced `paste` with `file.path`. 

 * [ ]  NOTE: Functional programming: code repetition. There are lots of code repetition. I list one here for your information.
   * Thank you for the suggestion, I am quite new to using shiny modules and will look into how to share code between modules.  

 * [x]  Important: When use API Upload, it ask input y/n in background to Create `cBioPortalData` cache at $Caches_folder for the first run. 
   * Addressed using argument `ask = F` in `downloadStudy()`.  

## Documentation
 * [x]  Important: Vignette should have an _Introduction_ section..
    * Added Introduction Seciton. 

 * [x]  Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
    * Added motivation for submitting to Bioconductor. 

 * [ ]  Note: The font in the images is hard to read.
    * Not addressed. Will consider updating figures. 

 * [ ]  Note: Lacking help information for `Recode/Subset Data`. No error message when showing a blank plot in `Exploratory Plots`.
   * Not addressed. Will consider adding help info for `Recode/Subset Data` tab.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Lydia-King.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GNOSIS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GNOSIS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
