### ISSUE TITLE
(inactive) decd

### ISSUE THREAD

**Issue by menggf** [Bioconductor/Contributions#315]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/menggf/decd

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by menggf** [comment]
Dear @vobencha and other reviewers,

 We have corrected nearly all the errors and warnings in our package. Now, the only problem seems to be that it has too few runnable examples in both vignette chunks and man pages. This package is designed for big data (e.g. one thousand patients * twenty thousand genes).  It is impossible to include such huge data in a package. And it also will slow down the package installation and building. Our solution is to provide a test data in a website and users can download such data for evaluation (see vignette).

Therefore, we ask to skip such a warning or error and start the review process. 

Thanks

**Comment by vobencha** [comment]
A function designed for big data should still run on a small subset. The purpose of the nightly builds is to confirm the functions still operate as expected and no changes in R or other dependencies have broken something. By commenting out the man pages and vignettes you've bypassed this check and balance system. The key package functions must be evaluated at least once in either the man pages or vignettes.

Downloading a large file from the web has a couple of disadvantages: the web site must be reachable for the examples to run, the download will take some time (possibly a long time), and the examples run with this large data will take a long time. You have a couple of options, the first is to include a small subset of the data in data/ or inst/extdata. The second is to use data from an existing experimental data package:

  http://www.bioconductor.org/packages/release/BiocViews.html#___ExperimentData

and finally you could create your own data package. I would recommend one of the first 2 options.

Valerie

**Comment by vobencha** [comment]
Any progress or questions? Are you planning to submit an updated version?
Valerie

**Comment by menggf** [comment]
Dear @vobencha ,

Sorry for this late reply. We agree to your comments about test data. Now, we are updating the packages, e.g.  re-writing some functions,  based on comments collected from our colleagues.  We will need more time, e.g. one month, to release the new update, including test data.

If it is possible, please keep it open for another month. Otherwise, please close it and we will start a new issue later when everything is ready.

Thanks,

Guofeng,

**Comment by vobencha** [comment]
Yes, we can keep it open another month.
Valerie

**Comment by vobencha** [comment]
I'm declining this package. When you're ready with a new version please open a new issue.
Valerie
