### ISSUE TITLE
dar

### ISSUE THREAD

**Issue by xec-cm** [Bioconductor/Contributions#3158]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MicrobialGenomics-IrsicaixaOrg/dar

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Could you please provide an abstract/intro section in your vignette that provides motivation for inclusion in Bioconductor and when appropriate a review and comparison to existing Bioconductor packages with similar functionality or scope

**Comment by xec-cm** [comment]
Thanks @lshep, 

The requested introduction is already present in the [README.Rmd](https://github.com/MicrobialGenomics-IrsicaixaOrg/dar/blob/devel/README.Rmd) file, following a similar approach to other Bioconductor packages like [biocthis](https://lcolladotor.github.io/biocthis/). This has been done with the consideration that when using pkgdown to generate the documentation [website for our package](https://microbialgenomics-irsicaixaorg.github.io/dar/), the default landing tab for users is typically the README. This ensures that the introduction is easily accessible in a logical and convenient location for users who visit our package's online documentation. We appreciate your feedback and any additional suggestions to improve the documentation and presentation of our package on Bioconductor.

**Comment by LiNk-NY** [comment]
Hi Francesc, @xec-cm 
Thank you for your submission. 
Please see the review below. 
Best regards,
Marcel

---

# dar #3158

* Ideally, the package should use infrastructure that works well with the rest
of Bioconductor such as `mia`, `TreeSummarizedExperiment`,
`SummarizedExperiment`, etc. rather than `phyloseq`. It looks like the
vignettes suggest the opposite. Please consider evolving the package into more
modern microbiome infrastructure with input from the community.

## DESCRIPTION

* Consider avoiding the `magrritr` dependency and using the base R pipe (`|>`).
* R version dependency should be `4.4.0` or higher
* Consider removing either the `readr` or the `data.table` dependency as they
are both typically used for the same operation (read-in).

## NAMESPACE

* Avoid re-exporting functions such as `%>%` and `:=`. Based on the vignettes,
you can use `|>` and `:=` is not used in the user-facing code.
* `required_deps` seems to be an internal function and does not need to be
exported.

## vignettes

* The `subset` and `filter` operations are a bit unconventional. This may be a
challenge for the user who wants to perform multiple subsets and filters with
their data. Please consider using `SummarizedExperiment`'s method for
`subset`ting. You may also want to take a look at the filtering for
`SummarizedExperiment` provided by the `tidyomics` group.
* Consider providing conversion vignettes from older formats such as
`phyloseq` into newer ones such as `TreeSummarizedExperiment`.

## R

* Avoid recommending unconventional package installation methods, e.g.,
`pak::pkg_install`.
* Avoid setting a seed within a function (`run_aldex`).
* Consider using a more descriptive class name for `recipe`. Also consider
following Bioconductor convention and using sentence case for all class names,
e.g., `SummarizedExperiment`.
* Generally, methods and generics are not needed if they are defined for a
single class. A plain function would accomplish the same with less code to
maintain.
* Please use the data name in the documentation `R/data.R` rather than `NA`.

## tests

* Consider increasing package coverage:

```r
> covr::package_coverage()
dar Coverage: 20.73%
R/ancom.R: 0.00%
R/deseq2.R: 0.00%
R/lefse.R: 0.00%
R/maaslin2.R: 0.00%
R/phyloseq_qc.R: 0.00%
R/plot_methods.R: 0.00%
R/rarefaction.R: 0.00%
R/subset_taxa.R: 0.00%
R/wilcox.R: 0.00%
R/corncob.R: 1.35%
R/aldex2.R: 1.56%
R/filter_taxa.R: 6.76%
R/recipe-class.R: 18.78%
R/metagenomeseq.R: 27.55%
R/misc.R: 41.67%
R/steps_and_checks.R: 47.83%
R/bake.R: 56.94%
R/read_data.R: 98.49%
R/pkg_check.R: 100.00%
```

**Comment by xec-cm** [comment]
Dear Marcel (@LiNk-NY ),

We would like to express our sincere gratitude for the time and effort you have put into reviewing our package. Your feedback is invaluable in helping us improve the quality and usability of our package.

Before we begin making changes to the code, we have prepared a point-by-point response to your comments. This will allow us to clarify certain points and ensure that we fully understand your feedback.

Once again, thank you for your insightful review. We look forward to your response.

Bests 

Francesc

> Hi Francesc, @xec-cm Thank you for your submission. Please see the review below. Best regards, Marcel
> 
> # dar #3158
> * Ideally, the package should use infrastructure that works well with the rest
>   of Bioconductor such as `mia`, `TreeSummarizedExperiment`,
>   `SummarizedExperiment`, etc. rather than `phyloseq`. It looks like the
>   vignettes suggest the opposite. Please consider evolving the package into more
>   modern microbiome infrastructure with input from the community.

We appreciate your suggestion regarding the adoption of `TreeSummarizedExperiment` over `phyloseq`. We share your vision that `TreeSummarizedExperiment` represents the future of microbiome analysis. However, currently `phyloseq` remains the most annually downloaded package on Bioconductor for microbiome data analysis, indicating it is still widely used within the community.

Nevertheless, we understand the importance of keeping up with modern infrastructures and agree that `TreeSummarizedExperiment` offers significant advantages. Therefore, we plan to implement the option for the `recipe` class to accept objects from both `phyloseq` and `TreeSummarizedExperiment`. This will allow users to leverage the strengths of both infrastructures as per their needs.

Additionally, we will refocus the vignette to become a tutorial on how to export from `biom` to `TreeSummarizedExperiment`. 

> ## DESCRIPTION
> * Consider avoiding the `magrritr` dependency and using the base R pipe (`|>`).

We understand your point about avoiding the `magrittr` dependency and using the base R pipe (`|>`) for the sake of package maintainability. However, our package includes substantial code that would need to be significantly modified. For instance, code like this:

```r
otu_table(rec) %>%
    tidyr::pivot_longer(-1, names_to = "sample_id") %>%
    dplyr::left_join(sample_data(rec), by = "sample_id") %>% 
    dplyr::bind_rows(., dplyr::mutate(., !!var := "all"))
```

Therefore, unless there are strong objections, and given that there is no specific note regarding this in the [Bioconductor contribution guidelines](https://contributions.bioconductor.org/readme.html), we would prefer to continue using the `magrittr` pipe. We believe this will allow us to maintain the readability and structure of our existing code while still meeting the overall goals of the Bioconductor project. We appreciate your understanding and flexibility on this matter.

> * R version dependency should be `4.4.0` or higher

In response to the comment about the R version dependency, we will certainly update this.

> * Consider removing either the `readr` or the `data.table` dependency as they
>   are both typically used for the same operation (read-in).

In response to the comment about the `readr` and `data.table` dependencies, we agree with your observation. Both packages are indeed being used for the same operation, specifically for reading in files. To streamline our package and reduce unnecessary dependencies, we plan to remove one or both of these packages and instead utilize the base R functions for file reading. 

> ## NAMESPACE
> * Avoid re-exporting functions such as `%>%` and `:=`. Based on the vignettes,
>   you can use `|>` and `:=` is not used in the user-facing code.

We will avoid re-exporting functions such as `%>%` and `:=`. As you suggested, we can use `|>` in the vignettes, and `:=` is not used in the user-facing code.

> * `required_deps` seems to be an internal function and does not need to be
>   exported.

We will make the necessary adjustments to ensure that it is not exported.

> ## vignettes
> * The `subset` and `filter` operations are a bit unconventional. This may be a
>   challenge for the user who wants to perform multiple subsets and filters with
>   their data. Please consider using `SummarizedExperiment`'s method for
>   `subset`ting. You may also want to take a look at the filtering for
>   `SummarizedExperiment` provided by the `tidyomics` group.

We understand your perspective regarding the use of `subset` and `filter` operations. It's true that the filtering methods provided by `tidyomics` are intuitive. However, they do not specifically support `TreeSummarizedExperiment` nor do they have a use case for microbiome data. 

In addition, adopting these methods would not only require accepting a `TreeSummarizedExperiment` or `SummarizedExperiment` object as input, but it would also necessitate rewriting code that currently works well and serves its purpose. 

Therefore, while we see the value in your suggestion, we propose to consider this change for future releases. This will allow us to thoroughly evaluate the impact and benefits of such a change, ensuring that we continue to provide a package that effectively meets the needs of our users. 

> * Consider providing conversion vignettes from older formats such as
>   `phyloseq` into newer ones such as `TreeSummarizedExperiment`.

We appreciate your suggestion to provide conversion vignettes from older formats such as `phyloseq` into newer ones like `TreeSummarizedExperiment`. We understand the value this could bring in helping users transition between these formats.

However, we believe that our package should remain neutral and not necessarily advocate for one tool over another. While we plan to support both `phyloseq` and `TreeSummarizedExperiment`, we feel that encouraging the use of one tool over another may be better suited to the documentation of those specific packages, such as `mia` or `TreeSummarizedExperiment`.

That being said, if providing such conversion vignettes is a requirement for acceptance, we are willing to include them. 

> ## R
> * Avoid recommending unconventional package installation methods, e.g.,
>   `pak::pkg_install`.

We understand your point about the use of `pak::pkg_install` for package installation. While `pak` offers certain advantages, we acknowledge that it may not be as widely recognized or used within the R community. Therefore, we will revise our package to recommend more commonly used installation methods, such as `BiocManager::install()` or the base R function `install.packages()`.

> * Avoid setting a seed within a function (`run_aldex`).

We understand your point about avoiding setting a seed within a function. However, one of the motivations for our package is to make differential taxa analysis reproducible. In the case of `run_aldex` and other methods, we have the following lines of code:

```r
if (rarefy) { 
    phy <- phyloseq::rarefy_even_depth(phy, rngseed = 1234, verbose = FALSE) 
}
```

This code is used to perform rarefaction if the user has specified that they want to do so. The use of a set seed here ensures that the rarefaction process is reproducible, which is crucial for users who want to be able to replicate their results exactly. 

While we understand the general caution against setting a seed within a function, we believe that in this specific context, it is justified by the need for reproducibility in the analysis. However, we also acknowledge the potential drawbacks of using a set seed, such as giving the impression of more stable results than might actually be the case in practice, and limiting the randomness which is a fundamental part of many statistical methods.

Therefore, to address these concerns, we will implement a warning message whenever the `rarefy = TRUE` option is used, informing users that a set seed is being used and how it might impact their results. We will also provide an option for users to disable the set seed if they prefer.

> * Consider using a more descriptive class name for `recipe`. Also consider
>   following Bioconductor convention and using sentence case for all class names,
>   e.g., `SummarizedExperiment`.

We understand the suggestion to use a more descriptive class name for `recipe` and to follow the Bioconductor convention of using sentence case for all class names. 

> * Generally, methods and generics are not needed if they are defined for a
>   single class. A plain function would accomplish the same with less code to
>   maintain.

We acknowledge your suggestion about methods and generics. In our package, we have methods for both `recipe` and `prep_recipe` classes. For functions specific to one class, we'll consider converting them into plain functions. 

> * Please use the data name in the documentation `R/data.R` rather than `NA`.

We understand the importance of clear and accurate documentation, and we will make this change.

> ## tests
> * Consider increasing package coverage:
> ```r
> > covr::package_coverage()
> dar Coverage: 20.73%
> R/ancom.R: 0.00%
> R/deseq2.R: 0.00%
> R/lefse.R: 0.00%
> R/maaslin2.R: 0.00%
> R/phyloseq_qc.R: 0.00%
> R/plot_methods.R: 0.00%
> R/rarefaction.R: 0.00%
> R/subset_taxa.R: 0.00%
> R/wilcox.R: 0.00%
> R/corncob.R: 1.35%
> R/aldex2.R: 1.56%
> R/filter_taxa.R: 6.76%
> R/recipe-class.R: 18.78%
> R/metagenomeseq.R: 27.55%
> R/misc.R: 41.67%
> R/steps_and_checks.R: 47.83%
> R/bake.R: 56.94%
> R/read_data.R: 98.49%
> R/pkg_check.R: 100.00%
> ```

We have used `covr::package_coverage(type = "all")` to calculate the test coverage, which gives us a coverage of 93.44%. This is significantly higher than the 20.73% reported. Here are the detailed results:

```
dar Coverage: 93.44%
R/corncob.R: 77.24%
R/plot_methods.R: 85.88%
R/recipe-class.R: 87.83%
R/rarefaction.R: 88.89%
R/wilcox.R: 96.47%
R/deseq2.R: 96.70%
R/aldex2.R: 96.88%
R/steps_and_checks.R: 97.83%
R/metagenomeseq.R: 97.89%
R/read_data.R: 98.49%
R/maaslin2.R: 98.67%
R/ancom.R: 99.15%
R/lefse.R: 99.23%
R/bake.R: 100.00%
R/filter_taxa.R: 100.00%
R/misc.R: 100.00%
R/phyloseq_qc.R: 100.00%
R/pkg_check.R: 100.00%
R/subset_taxa.R: 100.00%
```

We would like to note that `covr::package_coverage()` excludes the examples in the documentation, which we believe is not ideal for Bioconductor packages. Bioconductor guidelines suggest that all exported functions should have code examples, and we believe that these examples should be included in the test coverage calculation. 

We would like to understand if there is a specific reason for preferring the use of `covr::package_coverage()` without the `type = "all"` argument. This will help us ensure that we are meeting the Bioconductor standards and expectations. We look forward to your feedback.

**Comment by xec-cm** [comment]
Dear Marcel (@LiNk-NY ),

We would like to express our sincere gratitude for the time and effort you have put into reviewing our package. Your feedback is invaluable in helping us improve the quality and usability of our package. Next, we will explain the changes we have made to address your comments.

# dar #3158

> -   Ideally, the package should use infrastructure that works well with the rest of Bioconductor such as `mia`, `TreeSummarizedExperiment`, `SummarizedExperiment`, etc. rather than `phyloseq.` It looks like the vignettes suggest the opposite. Please consider evolving the package into more modern microbiome infrastructure with input from the community.

We appreciate your suggestion regarding the adoption of TreeSummarizedExperiment over phyloseq. We share your vision that TreeSummarizedExperiment represents the future of microbiome analysis. However, currently, phyloseq remains the most annually downloaded package on Bioconductor for microbiome data analysis, indicating it is still widely used within the community.

Nevertheless, we understand the importance of keeping up with modern infrastructures and agree that TreeSummarizedExperiment offers significant advantages. Therefore, now dar accepts both phyloseq and TreeSummarizedExperiment class objects as inputs.

Additionally, we have refocused the vignette to become a tutorial on how to import biom, qiime, mothur, metaphlan, and humann to TreeSummarizedExperiment and phyloseq class objects.

## DESCRIPTION

> -   Consider avoiding the `magrritr` dependency and using the base R pipe (`|>`).

We understand your point about avoiding the magrittr dependency and using the base R pipe (`|>`) for the sake of package maintainability. However, our package includes substantial code that would need to be significantly modified. For instance, code like this:

```{r}
otu_table(rec) %>%
    tidyr::pivot_longer(-1, names_to = "sample_id") %>%
    dplyr::left_join(sample_data(rec), by = "sample_id") %>% 
    dplyr::bind_rows(., dplyr::mutate(., !!var := "all"))
```

Therefore, unless there are strong objections, and given that there is no specific note regarding this in the Bioconductor contribution guidelines, we would prefer to continue using the magrittr pipe. The magrittr pipe is widely used and recognized in the R community and still used in some Bioconducor packages. We appreciate your understanding in this matter.

> -   R version dependency should be `4.4.0` or higher

We have updated the R version dependency to 4.4.0.

> -   Consider removing either the `readr` or the `data.table` dependency as they are both typically used for the same operation (read-in).

We have removed the `data.table` dependency as suggested.

## NAMESPACE

> -   Avoid re-exporting functions such as `%>%` and `:=`. Based on the vignettes, you can use `|>` and `:=` is not used in the user-facing code.

We have removed the re-exporting of `%>%`and `:=`. Now vignettes and code examples use `|>`

> -   `required_deps` seems to be an internal function and does not need to be exported.

We made the necessary changes to avoid exporting `required_deps`.

## VIGNETTES

> -   The `subset` and `filter` operations are a bit unconventional. This may be a challenge for the user who wants to perform multiple subsets and filters with their data. Please consider using `SummarizedExperiment`'s method for `subset`ting. You may also want to take a look at the filtering for `SummarizedExperiment` provided by the `tidyomics` group.

We appreciate your suggestion regarding the `subset` and `filter` operations. We understand that adopting the `SummarizedExperiment`'s method for `subset`ting and the filtering provided by the `tidyomics` group could potentially enhance the user experience.

However, one of the initial objectives in the design of the package was to allow all steps of the `recipe` to be defined in a pipeable manner. While we appreciate the `SummarizedExperiment`'s method for `subset`ting  using the `[`, it does not align with our philosophy. This is primarily because the subsetting of a `SummarizedExperiment` does not work well with the base R pipe.

```{r}
data(GlobalPatterns, package = "mia")
tse <- GlobalPatterns
tse

# Non pipeable approach works
tse[rowSums(assay(tse)) > 0, ]

# Magrittr pipe works
tse %>% .[rowSums(assay(.)) > 0, ]

# Base R pipe does not work
tse |> _[rowSums(assay(x = _)) > 0, ]
```

Regarding the `tidyomics` group's approach, we find it appealing but it's not feasible to apply it directly to the `recipe` or `prep_recipe` objects. Therefore, we retain the functionality of `step_filter_taxa`, which takes an expression as input for more customizable filtering. 

In addition, we have implemented functions that align with the philosophy of the `tidyomics`: `step_filter_by_abundance`, `step_filter_by_prevalence`, `step_filter_by_rarity`, and `step_filter_by_variance`. These functions take a threshold value as input to filter the `phyloseq` object contained within the `recipe` object.

Also, we have redefined the `step_subset_taxa` function. It no longer takes an expression, but instead takes two parameters: `tax_level`, indicating the taxonomic level to filter, and `taxa`, indicating the taxa to retain.

To further assist users, we have created a vignette titled "Filtering and Subsetting". This guide explains how to filter or subset directly from the `recipe` object. However, we also remind users that they can filter the `TSE` or `phyloseq` object prior to constructing the `recipe` object. This allows users to apply the filtering and subsetting approach that best suits their needs and preferences.

> -   Consider providing conversion vignettes from older formats such as phyloseq into newer ones such as `TreeSummarizedExperiment`.

We appreciate your suggestion to provide conversion vignettes from older formats such as `phyloseq` into newer ones like `TreeSummarizedExperiment`. We understand the value this could bring in helping users transition between these formats.

However, we believe that our package should remain neutral and not necessarily advocate for one tool over another. While we plan to support both `phyloseq` and `TreeSummarizedExperiment`, we feel that encouraging the use of one tool over another may be better suited to the documentation of those specific packages, such as `mia` or `TreeSummarizedExperiment.`

## R

> -   Avoid recommending unconventional package installation methods, e.g., `pak::pkg_install`.

We understand your point about the use of `pak::pkg_install` for package installation. While `pak` offers certain advantages, we acknowledge that it may not be as widely recognized or used within the Bioconductor community. Therefore, `dar` now recommends more commonly used installation methods, such as `BiocManager::install()` or the base R function `install.packages()`.

> -   Avoid setting a seed within a function (`run_aldex`).

We understood your point about avoiding setting a seed within a function. However, one of the motivations for our package is to make differential taxa analysis reproducible. In the case of `run_aldex` and other methods, we have the following lines of code:

```{r}
if (rarefy) { 
  phy <- phyloseq::rarefy_even_depth(phy, rngseed = 1234, verbose = FALSE) 
}
```

This code is used to perform rarefaction if the user has specified that they want to do so. The use of a set seed here ensures that the rarefaction process is reproducible, which is crucial for users who want to be able to replicate their results exactly.

While we understood the general caution against setting a seed within a function, we believed that in this specific context, it was justified by the need for reproducibility in the analysis. However, we also acknowledged the potential drawbacks of using a set seed, such as giving the impression of more stable results than might actually be the case in practice, and limiting the randomness which is a fundamental part of many statistical methods.

Therefore, to address these concerns, we implemented a warning message whenever the `rarefy = TRUE` option is used, informing users that a set seed is being used and how it might impact their results. We also provided an option for users to disable the set seed if they prefer (`rarefy = "no_seed"`).

> -   Consider using a more descriptive class name for `recipe.` Also consider following Bioconductor convention and using sentence case for all class names, e.g., `SummarizedExperiment.`

We appreciate your valuable feedback. Taking into account your suggestion, we have decided to rename the `recipe` class to `Recipe` and `prep_recipe` to `PrepRecipe`. We believe these changes will not only adhere to the Bioconductor convention but also maintain the simplicity and relevance of the class names.

> -   Generally, methods and generics are not needed if they are defined for a single class. A plain function would accomplish the same with less code to maintain.

We appreciate your feedback. We’ve chosen to use methods and generics in our package with the intention of enhancing the interoperability of some functions in the future. 

> -   Please use the data name in the documentation `R/data.R` rather than `NA`.

We have made the necessary changes to address these issues.

## tests

> -   Consider increasing package coverage:

```{r}
> covr::package_coverage()
dar Coverage: 20.73%
R/ancom.R: 0.00%
R/deseq2.R: 0.00%
R/lefse.R: 0.00%
R/maaslin2.R: 0.00%
R/phyloseq_qc.R: 0.00%
R/plot_methods.R: 0.00%
R/rarefaction.R: 0.00%
R/subset_taxa.R: 0.00%
R/wilcox.R: 0.00%
R/corncob.R: 1.35%
R/aldex2.R: 1.56%
R/filter_taxa.R: 6.76%
R/recipe-class.R: 18.78%
R/metagenomeseq.R: 27.55%
R/misc.R: 41.67%
R/steps_and_checks.R: 47.83%
R/bake.R: 56.94%
R/read_data.R: 98.49%
R/pkg_check.R: 100.00%
```

New package coverage 

```{r}
> covr::package_coverage()
dar Coverage: 87.66%
R/steps_and_checks.R: 69.57%
R/recipe-class.R: 71.32%
R/bake.R: 75.58%
R/read_data.R: 76.77%
R/plot_methods.R: 86.27%
R/misc.R: 86.56%
R/wilcox.R: 91.76%
R/deseq2.R: 98.90%
R/ancom.R: 99.15%
R/lefse.R: 99.23%
R/maaslin2.R: 99.33%
R/aldex2.R: 100.00%
R/filter_by_abundance.R: 100.00%
R/filter_by_prevalence.R: 100.00%
R/filter_by_rarity.R: 100.00%
R/filter_by_variance.R: 100.00%
R/filter_taxa.R: 100.00%
R/metagenomeseq.R: 100.00%
R/phyloseq_qc.R: 100.00%
R/pkg_check.R: 100.00%
R/rarefaction.R: 100.00%
R/subset_taxa.R: 100.00%
R/subset_taxa.R: 100.00%
```

**Comment by LiNk-NY** [comment]
Hi @xec-cm 

Thank you for making those changes. The package looks almost ready.

> ## R
> > * Avoid recommending unconventional package installation methods, e.g., `pak::pkg_install`.
> 
> We understand your point about the use of `pak::pkg_install` for package installation. While `pak` offers certain advantages, we acknowledge that it may not be as widely recognized or used within the Bioconductor community. Therefore, `dar` now recommends more commonly used installation methods, such as `BiocManager::install()` or the base R function `install.packages()`.

I do not see the use case for separating Bioconductor and CRAN packages in `recipes_pkg_check`. Please simplify the code by pasting all packages with `BiocManager::install(c({all_packages}))`. The command would install packages from the appropriate repository (either CRAN or Bioconductor). We do not recommend the use of `install.packages()` and your package should not advertise otherwise. 

Best regards,
Marcel

**Comment by xec-cm** [comment]
Hi @LiNk-NY 

Thank you for your feedback. After overcoming yet another challenge with TIMEOUTS, we have incorporated your latest suggestion into our package. Now, we recommend installing all missing dependencies using `BiocManager::install()`.

Bests 

Francesc

**Comment by LiNk-NY** [comment]
Hi Francesc, @xec-cm

Thank you for making those changes. 
It seems that the examples are taking to long to check? Consider using a smaller dataset to reduce the time. 
The warnings show that the checks are over 10 minutes. 

Thank you for your submission.

Best,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/xec-cm.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("dar")`. The package 'landing page' will be created at

https://bioconductor.org/packages/dar

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
