### ISSUE TITLE
Kinship2

### ISSUE THREAD

**Issue by LouisLeNezet** [Bioconductor/Contributions#3159]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LouisLeNezet/kinship2

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LouisLeNezet** [comment]
Hi,
Concerning the version number, this package is a transfer from CRAN.
I would like to keep the old name and the version history.

**Comment by lshep** [comment]
We like to see a clean package branch for inclusion and distribution, and extra features and integration controlled on different branches. There seems to be a lot of extra top level directories/files that should probably not be included by default to a user: idea, noweb, documentation.  There is also a built tar of the package that has been checked into git that should be removed.  If the directories above have a different intended use please explain as generally there is standard locations to place files.

**Comment by LouisLeNezet** [comment]
Hi,
Sorry, it's my first time and I didn't know about that.
I've modify the default branch to main, with a clean repository.

**Comment by LouisLeNezet** [comment]
Hi,
There is some discussion going on about the name of the package.
The problematic being, should we keep the previous name use on CRAN.

> Note that keeping the name means that there's a strong expectation that the package does not break existing code that relies on it. Preserving backward compatibility requires being very cautious and implementing a 2 x 6-month transition plan that involves a lot of .Deprecated() calls for the 1st 6-month period followed by a lot of .Defunct() calls for the 2nd 6-month period, finally followed by the removal of all the obsolete stuff. This is a lot more work than just using a new name for the BioC package and deprecating the CRAN package.

The other solution would be to rename this package and deprecate the one on CRAN.

**Comment by lshep** [comment]
They raise good points.  It really is up to you how you would like to proceed.  If you would like to submit with a different name, we would close this issue and have you resubmit when the repo has been updated accordingly.

**Comment by LouisLeNezet** [comment]
The package will be re-issued with the new name Pedigree.
