### ISSUE TITLE
netReg

### ISSUE THREAD

**Issue by dirmeier** [Bioconductor/Contributions#317]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dirmeier/netReg

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@hpages will provide a review of this package, but I note that it's odd that it has no dependencies on other Bioconductor packages. Motivation for introducing dependencies would be to facilitate interoperability between related packages (i.e., use classes and methods defined in similar packages for robust data management) and to reduce code duplication. Are there really no connections between your package and existing Bioconductor packages?

**Comment by dirmeier** [comment]
Dear Martin,
the package is a pure C++ implementation of a regularized regression model using biological networks. I really need any other dependencies on Bioconductor packages I guess. 
But maybe it makes sense to add some nice plotting routines using some Bioc-packages indeed.
Best, Simon

**Comment by dirmeier** [comment]
I seriously have no idea why windows wants to execute `configure`. Adding a `configure.win` does not change anything. I neither found anything on the web regarding this issue.

**Comment by mtmorgan** [comment]
Let's ignore the warning; is a version bump required to build your most recent commits? I'll then provide a review.

**Comment by dirmeier** [comment]
Hello @mtmorgan, thank you for the info. I just updated the version.

**Comment by dirmeier** [comment]
I've checked and several other packages seem to have the same error. Is this something my package is causing?

**Comment by mtmorgan** [comment]
This is  a problem on our end; please ignore.

**Comment by mtmorgan** [comment]
I've looked at this package and, remarkably, don't have anything substantial to contribute! I'll mark this as 'accepted'. The package will be added to our nightly builds and svn source control, with additional information sent via mail in the next several days.

**Comment by dirmeier** [comment]
That's wonderful. Thank you.
