### ISSUE TITLE
enrichViewNet

### ISSUE THREAD

**Issue by adeschen** [Bioconductor/Contributions#3173]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/adeschen/enrichViewNet

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jianhong** [comment]
# Package 'enrichViewNet' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. It is in pretty good shape. If you can enhance the power of functions using RCy3 to explore the data will be even better, but that is out of this review process. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.

## R code
- [ ] Important:`is()` or `inherits()` instead of `class()`.
	* In file R/methodsEmapInternal.R:
		+ at line 73 found '    if (!("list" %in% class(gostObject) && "result" %in% names(gostObject) &&'
	* In file R/methodsInternal.R:
		+ at line 178 found '    if (!("list" %in% class(gostObject) && "result" %in% names(gostObject) &&'
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
	* In file R/methodsEmapInternal.R:
		+ at line 196 found '            unlist(stringr::str_split(gostResults$intersection[i], '
		+ at line 209 found '        geneID=stringr::str_replace_all(gostResults$intersection, ",", "/"),'
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/methodsEmapInternal.R:
		+ at line 194 found '    for (i in seq_len(nrow(gostResults))) {'
	* In file R/methodsInternal.R:
		+ at line 258 found '    for (i in seq_len(length(source))) {'
		+ at line 414 found '    for (i in seq_len(nrow(gostResults))) {'
		+ at line 436 found '        for (g in genes[genes %in% res$target]) {'
		+ at line 532 found '    for (i in seq_len(nrow(gostResults))) {'
		+ at line 546 found '            for (g in genesTarget) {'
		+ at line 624 found '    for (i in seq_len(nrow(gostResults))) {'
		+ at line 636 found '        for (j in seq_len(nrow(genes))) {'
- [ ] Important: Remove unused code.
	* In file R/methodsInternal.R:
		+ at line 106 found '            #message("Cytoscape is running.\n")'
		+ at line 639 found '                #print(geneName)'
- [ ] NOTE: Use `is.character/numeric/integer/logical` to replace `is(, "character/numeric/integer/logical")`
	* In file R/methodsEmapInternal.R:
		+ at line 108 found '    if (!is(showCategory, "character") && '
		+ at line 109 found '            !(is(showCategory, "numeric") && (showCategory > 0))) {'
		+ at line 114 found '    if (!is(groupCategory , "logical")) {'
		+ at line 119 found '    if (!is(categoryLabel, "numeric") || !(categoryLabel > 0)) {'
		+ at line 123 found '    if (!is(categoryNode, "numeric") || !(categoryNode > 0)) {'
	* In file R/methodsInternal.R:
		+ at line 203 found '    if (!is(removeRoot, "logical")) {'
		+ at line 208 found '    if (!is(fileName, "character")) {'
- [ ] Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.
- [ ] NOTE: Functional programming: code repetition.
	* repetition in `createEnrichMap` and `createNetwork`
		+ in createEnrichMap
			- line 13:    if (source == "TERM_ID") {
			- line 14:        gostResults <- gostResults[gostResults$term_id %in% termIDs, 
			- line 15:            ]
			- line 16:    }
			- line 17:    else {
			- line 18:        gostResults <- gostResults[gostResults$source == source, 
			- line 19:            ]
			- line 20:    }
			- line 21:    if (removeRoot) {
			- line 22:        gostResults <- removeRootTerm(gostResults)
			- line 23:        if (nrow(gostResults) == 0) {
			- line 24:            stop("With removal of the root term, there is no ", 
			- line 25:                "enrichment term left")
			- line 26:        }
			- line 27:    }
		+ in createNetwork
			- line 10:    if (source == "TERM_ID") {
			- line 11:        gostResults <- gostResults[gostResults$term_id %in% termIDs, 
			- line 12:            ]
			- line 13:    }
			- line 14:    else {
			- line 15:        gostResults <- gostResults[gostResults$source == source, 
			- line 16:            ]
			- line 17:    }
			- line 18:    if (removeRoot) {
			- line 19:        gostResults <- removeRootTerm(gostResults)
			- line 20:        if (nrow(gostResults) == 0) {
			- line 21:            stop("With removal of the root term, there is no ", 
			- line 22:                "enrichment term left")
			- line 23:        }
			- line 24:    }
	* repetition in `extractNodesAndEdgesWhenIntersection` and `extractNodesAndEdgesWhenNoIntersection`
		+ in extractNodesAndEdgesWhenIntersection
			- line 1:    objs = list(function (gostResults, gostObject) 
			- line 2:    {
			- line 3:        done <- array()
			- line 4:        nodes <- list()
			- line 5:        edges <- list()
			- line 7:            ",")))
			- line 8:        res <- gconvert(query = c(geneInter), organism = gostObject$meta$query_metadata$organism)
			- line 9:        for (i in seq_len(nrow(gostResults))) {
			- line 10:            term <- gostResults$term_id[i]
			- line 11:            query <- gostResults$query[i]
			- line 12:            termName <- gostResults$term_name[i]
			- line 13:            nodes[[length(nodes) + 1]] <- data.frame(id = c(term), 
			- line 14:                group = c("TERM"), alias = c(termName), stringsAsFactors = FALSE)
			- line 19:                geneName <- genes$name[j]
			- line 20:                if (!g %in% done) {
			- line 21:                  nodes[[length(nodes) + 1]] <- data.frame(id = c(g), 
			- line 22:                    group = c("GENE"), alias = c(geneName), stringsAsFactors = FALSE)
			- line 23:                  done <- c(done, g)
			- line 24:                }
			- line 25:                edges[[length(edges) + 1]] <- data.frame(source = c(term), 
			- line 26:                  target = c(g), interaction = c("contains"), 
			- line 27:                  stringsAsFactors = FALSE)
			- line 28:            }
			- line 29:        }
			- line 30:        nodeInfo <- do.call(rbind, nodes)
			- line 31:        edgeInfo <- do.call(rbind, edges)
			- line 32:        return(list(nodes = nodeInfo, edges = edgeInfo))
		+ in extractNodesAndEdgesWhenNoIntersection
			- line 1:    objs = list(function (gostResults, gostObject) 
			- line 2:    {
			- line 3:        done <- array()
			- line 4:        nodes <- list()
			- line 5:        edges <- list()
			- line 6:        resAll <- gconvert(query = c(gostResults$term_id), organism = gostObject$meta$query_metadata$organism)
			- line 7:        for (i in seq_len(nrow(gostResults))) {
			- line 8:            term <- gostResults$term_id[i]
			- line 9:            query <- gostResults$query[i]
			- line 10:            termName <- gostResults$term_name[i]
			- line 11:            nodes[[length(nodes) + 1]] <- data.frame(id = c(term), 
			- line 12:                group = c("TERM"), alias = c(termName), stringsAsFactors = FALSE)
			- line 19:                  if (!g %in% done) {
			- line 20:                    nodes[[length(nodes) + 1]] <- data.frame(id = c(g), 
			- line 21:                      group = c("GENE"), alias = c(geneName), 
			- line 22:                      stringsAsFactors = FALSE)
			- line 23:                    done <- c(done, g)
			- line 24:                  }
			- line 25:                  edges[[length(edges) + 1]] <- data.frame(source = c(term), 
			- line 26:                    target = c(g), interaction = c("contains"), 
			- line 27:                    stringsAsFactors = FALSE)
			- line 28:                }
			- line 29:            }
			- line 30:        }
			- line 31:        nodeInfo <- do.call(rbind, nodes)
			- line 32:        edgeInfo <- do.call(rbind, edges)
			- line 33:        return(list(nodes = nodeInfo, edges = edgeInfo))
	* repetition in `validateCreateEnrichMapArguments` and `validateCreateNetworkArguments`
		+ in validateCreateEnrichMapArguments
			- line 3:    {
			- line 4:        if (!("list" %in% class(gostObject) && "result" %in% 
			- line 5:            names(gostObject) && "meta" %in% names(gostObject))) {
			- line 6:            stop("The gostObject object should be a list with meta ", 
			- line 7:                "and result as entries corresponding to gprofiler2 ", 
			- line 8:                "enrichment output.")
			- line 9:        }
			- line 16:        }
			- line 17:        if (source != "TERM_ID") {
			- line 18:            if (sum(gostObject$result$source == source) < 1) {
			- line 19:                stop("There is no enriched term for the selected ", 
			- line 20:                  "source '", source, "'.")
			- line 21:            }
			- line 22:        }
			- line 23:        else {
			- line 24:            if (is.null(termIDs)) {
			- line 25:                stop("A vector of terms should be given through the ", 
			- line 26:                  "'termIDs' parameter when source is 'TERM_ID'.")
			- line 27:            }
			- line 28:            else {
			- line 29:                if (!all(termIDs %in% gostObject$result$term_id)) {
			- line 30:                  stop("Not all listed terms are present in the  ", 
			- line 31:                    "enrichment results.")
			- line 32:                }
			- line 33:            }
			- line 34:        }
		+ in validateCreateNetworkArguments
			- line 2:    {
			- line 3:        if (!("list" %in% class(gostObject) && "result" %in% 
			- line 4:            names(gostObject) && "meta" %in% names(gostObject))) {
			- line 5:            stop("The gostObject object should be a list with meta ", 
			- line 6:                "and result as entries corresponding to gprofiler2 ", 
			- line 7:                "enrichment output.")
			- line 8:        }
			- line 9:        if (source != "TERM_ID") {
			- line 10:            if (sum(gostObject$result$source == source) < 1) {
			- line 11:                stop("There is no enriched term for the selected ", 
			- line 12:                  "source '", source, "'.")
			- line 13:            }
			- line 14:        }
			- line 15:        else {
			- line 16:            if (is.null(termIDs)) {
			- line 17:                stop("A vector of terms should be given through the ", 
			- line 18:                  "'termIDs' parameter when source is 'TERM_ID'.")
			- line 19:            }
			- line 20:            else {
			- line 21:                if (!all(termIDs %in% gostObject$result$term_id)) {
			- line 22:                  stop("Not all listed terms are present in the  ", 
			- line 23:                    "enrichment results.")
			- line 24:                }
			- line 25:            }
			- line 26:        }
## Documentation
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/enrichViewNet.Rmd
- [ ] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/enrichViewNet.Rmd
- [ ] Important: Runable example in vignette is important for user to follow your documentation.
- [ ] Important: Usage of dontrun{} / donttest{} tags found
      in man page examples. 11% of man pages use at
      least one of these tags. If not avoidable, use donttest{} instead of dontrun{}.

**Comment by adeschen** [comment]
Dear @jianhong ,

We thank you for the thoughtful comments and, in response, have revised the code as follows.


### **R code**

- [X] **Important: is() or inherits() instead of class().**

All _class()_ have been replaced by _inherits()_ in the code.

- [X] **NOTE: :: is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep ::. However please note that you need to manually double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.** 

We are now importing the methods and we have removed the :: from the code.

- [X] **NOTE: Vectorize: for loops present, try to replace them by _apply_ functions.** 

All _for()_ loop have been replaced by _*apply_ functions.

- [X] **Important: Remove unused code.** 

The unused code has been removed.

- [X]  **NOTE: Use _is.character/numeric/integer/logical_ to replace _is(, "character/numeric/integer/logical")_.**

All _is(, "character/numeric/integer/logical")_ functions have been replaced.

- [X] **Important: Please consider to add drop=FALSE to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.**

At the moment, we do not use matrices in the code.

- [ ] **NOTE: Functional programming: code repetition.**

The _extractNodesAndEdgesWhenIntersection_ and _extractNodesAndEdgesWhenNoIntersection_ functions are similar but request different data manipulation. We have not found a easy way to remove the repetition from those functions.

We will address the repetition in  _validateCreateEnrichMapArguments_ and _validateCreateNetworkArguments_ functions as soon as possible. As well as in the _createEnrichMap_ and _createNetwork_ functions.


### **Documentation**

- [X] **Important: Please include Bioconductor installation instructions using BiocManager.**  

- rmd file vignettes/enrichViewNet.Rmd

We have included Bioconductor installation instructions using BiocManager in the vignette.

- [X] **Note: Vignette includes motivation for submitting to Bioconductor as part of the abstract/intro of the main vignette.**

-  rmd file vignettes/enrichViewNet.Rmd

We have included the motivation at the end of the Introduction of the main vignette.

- [X] **Important: Runable example in vignette is important for user to follow your documentation.**

All examples in the vignette are now runable.

- [X] **Important: Usage of dontrun{} / donttest{} tags found**

> in man page examples. 11% of man pages use at
> least one of these tags. If not avoidable, use donttest{} instead of dontrun{}.

All _dontrun{} / donttest{}_ have been removed for the man pages.

Best Regards,
Astrid and Pascal

**Comment by jianhong** [comment]
Rd file 'extractNodesAndEdgesWhenIntersection.Rd':
     \examples lines wider than 100 characters:
        results <- parentalNapaVsDMSOEnrichment$result[parentalNapaVsDMSOEnrichment$result$source == "GO:MF", ]

Please fix this as soon as possible. Today is the last day for current release.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/adeschen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("enrichViewNet")`. The package 'landing page' will be created at

https://bioconductor.org/packages/enrichViewNet

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
