### ISSUE TITLE
Submitting BioCor

### ISSUE THREAD

**Issue by llrs** [Bioconductor/Contributions#318]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/llrs/BioCor

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Thank you for your submission.  A few comments to address: 

- [ ] Please update R version dependency from 3.3.0 to 3.4
- [ ]  In pathSim.R: if number of pathways is big use another strategy?  why is different strategy better than using the same for both?
- [ ] in geneSim.R: same as above, why is a different strategy better than using the same for both.  Also please address the comment you have #TODO Improve this section not correctly done? - if it is not correctly done is your package working correctly? 

I think the package is very close to acceptance, please fix the version WARNING and make some comments addressing the above concerns.  Thank you.

**Comment by llrs** [comment]
1.  [x] Done
2.  [x] One way to compute the similarity between each pathway is doing one comparison at time. This requires listing all the genes in a pathway, and all the genes in the other pathway, and then for each gene see if they are in another pathway with the genes in the original pathway. When large amount of similarities are needed, it becomes slow. The alternative strategy uses the incidence matrix to calculate all the similarities between pathways, which should be faster (I can't test if it is faster at large number of pathways) but it requires to have big RAM available.  I also considered parallel execution and bigmemory, but it was too much. 
3. [ ] Thanks for pointing out the duplication of code, I will remove that statment as it is done internally in mpathSim.
 I forgot to remove that comment, it works correctly, and has been tested thoughtfully.

**Comment by lshep** [comment]
The DESCRIPTION file still seems to show version dependency from R 3.3.0 instead of 3.4? Could you please make this change and do a version bump to kick off a new build.  Before doing the version bump please make sure the webhook was set up: [webhook setup](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook).  Once the WARNING is corrected I will recommend your package be accepted.  Please leave the issue open and you will receive svn instructions via email. for inclusion into Bioconductor devel (normally within a week)

**Comment by llrs** [comment]
I have addressed all the comments in the last version change. 
However I would like to know if I can have the restriction of R to  R (>= 3.3.0) which is the version I use to develop the package.
I would like to note that it wasn't build in malbec2 sever, so it wasn't checked in a Linux environment.
I pushed a change about giving proper credit to @GuangchuangYu, if everything is okay I will bump the version shortly.

**Comment by lshep** [comment]
Thank you for your updates I will mark your package as accepted. You should receive svn instructions within the next week for inclusion in Bioconductor devel. 
We encourage the R version to be the version that the package will be released under with the Bioconductor release as we can't ensure compatibility.

**Comment by llrs** [comment]
Thanks to you @lshep, for reviewing the package.
