### ISSUE TITLE
HCATonsilData

### ISSUE THREAD

**Issue by federicomarini** [Bioconductor/Contributions#3190]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/massonix/HCATonsilData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by federicomarini** [comment]
As a couple of notes, relevant to the submission process: 

* The current version contains the version "v1" of the datasets, that have been updated in the meanwhile over the course of the publication process of the manuscript containing this data
* I am submitting for @massonix who has been the main contributor and maintainer of this package, but he is currently feeling not well - and I took over the posting of the issue in this repo
* This package has been created in the scope of the Bioconductor Mentorship program, which stretched out over these months
* Some of the items in the codebase still marked as TODO are not critical for its functionality and will be addressed in due time by the development team 

We are all set for the submission to the ExperimentHub of the newer batch of dataset - I guess it is meaningful to tag @lshep on this one.

Thanks in advance for the feedback that will be provided!
Ramon & Federico

**Comment by massonix** [comment]
Hi!

Thanks Fede for starting this thread! I've been feeling much better, and I've been working all weekend on the package. I have documented how to download the new version of the  [RNA](https://github.com/massonix/HCATonsilData/blob/install_v2/inst/scripts/make-data-tonsil-atlas-rna-v2.Rmd) and [spatial](https://github.com/massonix/HCATonsilData/blob/install_v2/inst/scripts/make-data-tonsil-atlas-spatial-v2.Rmd) datasets, I have created the proper metadata.csv that specifies all the files to be uploaded to the Hub ([RNA](https://github.com/massonix/HCATonsilData/blob/install_v2/inst/extdata/metadata-tonsil-atlas-rna-v2.csv), [Spatial](https://github.com/massonix/HCATonsilData/blob/install_v2/inst/extdata/metadata-tonsil-atlas-spatial-v2.csv)), and I have sharpened the [vignette](https://github.com/massonix/HCATonsilData/blob/vignette_and_todos/vignettes/HCATonsilData.Rmd). 

Tomorrow first thing, I will start all the necessary process to upload everything to the Hub. I have blocked all week to finish that, and given that the package is mostly ready I'm confident that we will finish it in time.

We are aware that we submitted the package at the last minute, but our paper was accepted just 2 weeks ago, and we have had limited time to freeze and curate the dataset. Thank you very much in advance for understanding, and we'll do everything in our power to get it to submission.

**Comment by lshep** [comment]
Let us know when the data is uploaded to the hub and when the package is in a state properly using the hub interface for data retrieval.

**Comment by massonix** [comment]
I have implemented all of the reviews from @HelenaLC and @federicomarini. The final touches will come once we can access the data from the Hub. @lshep I uploaded all data files using AzureStor without errors, please let me know if you can see the files, thanks

**Comment by massonix** [comment]
Hi @lshep,

We applied all pre-review changes. We only got a note saying the the build is 5.1Mb, but we hope it's fine given that documentation is an essential part of an annotation package, and the images we provide are of great help to understand the dataset.

Please let us know how to proceed

Thanks

Ramon

**Comment by federicomarini** [comment]
As an additional note, we did try to compact a bit the images by rastering/lowering the resolution.

We also tried to proactively address some Warnings and Notes from BiocCheck, so I think it is now all ready for the official review round.
Thanks @lshep for the quick reaction on the submission of the v2 files!

Federico

**Comment by lshep** [comment]
Overall really well written and very good documentation.  
A few comments to look into/fix 

**vignette**

- [ ] even tho the code chunks are in an eval=F, they are shown and use Seurat
  and Signac. I would add these packages to the Suggest of the DESCRIPTION.

- [ ] Also the code should be runnable if someone tries to run it.  The
  download_dir is not defined. You should show using a tempdir to define it and
  remove the `dir.create` call and then update the call accordingly
  ```
  download_dir = tempdir()
  destfile = file.path(download_dir, "TonsilAtlasSeuratATAC.tar.gz")
  ```
- [ ] I tried to run the code in the `eval=FALSE` but could not get it to
  run. Please update with above comment and make sure its runnable.

**Comment by federicomarini** [comment]
Thanks Lori @lshep for the swift review, I am glad you find it already in good shape.

I will assist @massonix in editing the vignette (and co.) as you suggested.

**Comment by federicomarini** [comment]
Here's our reply point by point to the items listed above, and a note to some additional slight changes.

> even tho the code chunks are in an eval=F, they are shown and use Seurat
and Signac. I would add these packages to the Suggest of the DESCRIPTION.

Thanks for the suggestion. We were indeed trying to be parsimonious on the number of packages our package would need to install alongside itself, and having them as `Suggests:` entries is likely the most considerate way of handling this.

> Also the code should be runnable if someone tries to run it. The
download_dir is not defined. You should show using a tempdir to define it and
remove the dir.create call and then update the call accordingly
> download_dir = tempdir()
destfile = file.path(download_dir, "TonsilAtlasSeuratATAC.tar.gz")

We replaced the hard coded path for the folder dedicated to downloading, using the `tempdir()` location combined to `file.path()` as suggested. 

We are aware some of the chunks involving download operations might take a while to execute, and we added some heads up as a comment about the size of the expected downloaded file - We hope this can be useful to the readers when they plan to retrieve the dataset.
 
> I tried to run the code in the eval=FALSE but could not get it to
run. Please update with above comment and make sure its runnable.

While addressing the changes needed for the point above, we made sure to check all lines were ideally runnable, even if they are not evaluated as a chunk itself - albeit lenghty, all code chunks now run and work, should readers want to try any of them out, independently of the `eval` parameter.

--

Additionally, we did some minor tweaks to the content of the vignette, and activated the CI/CD via GitHub Actions to have a better idea of the behavior of the package build/check on other systems and configurations.  
As of now, there seems to be an issue in there so we could not directly check all systems as we hoped, but hope it will adjust in due time so we have everything already in place for that.

I am taking over for this as Ramon is relocating soon and has no full access to his old laptop and/or a powerful cabled connection - I hope it is fine for you as well @lshep

**Comment by lshep** [comment]
**Section 5 of vignette**
- [ ] I can't seem to get 
```
htmltools::includeHTML(
  TonsilData_cellinfo_html("Tfr", display_plot = TRUE)
)
```
to work.  It comes up with a file not found error.  I had this issue with another package too and seems to be with my set up but it is unclear to me what system dependency or package I am missing to have this work correctly?  Any ideas? 

**Section 6 of vignette**
- [ ] zellkonverter  should also be in the Suggests since it is used in the vignette. 
- [ ] if this writes to disk make sure the file is a `tempdir()` for examples

**Comment by federicomarini** [comment]
> Section 5 of vignette
I can't seem to get
htmltools::includeHTML(
  TonsilData_cellinfo_html("Tfr", display_plot = TRUE)
)
to work. It comes up with a file not found error. I had this issue with another package too and seems to be with my set up but it is unclear to me what system dependency or package I am missing to have this work correctly? Any ideas?

Hm, this is odd. The idea behind that chunk is that

* This function simply assembles together md-based components to give an overview of the cell type selected by the user
* `TonsilData_cellinfo_html()` returns a character string with the location of the generated HTML page, while simultaneously opening it into a browser window. Alternatively, one can obtain as returned value the full HTML code (and ideally use that to embed it)
* `htmltools::includeHTML()` shows how one can insert that page inside an existing report.

If run correctly, this would give a small item in the vignette which looks like this:

<img width="882" alt="image" src="https://github.com/Bioconductor/Contributions/assets/7447478/627743c4-6282-41df-b3cb-c06dc1704776">

I will leave the chunk as EVAL'd now and see whether something odd happens.

> Section 6 of vignette
zellkonverter should also be in the Suggests since it is used in the vignette.
if this writes to disk make sure the file is a tempdir() for examples

Both very good points indeed - sorry we missed that.
`zellkonverter` is now in the Suggests, and we have an intermediate step to create the filename intended to be used in the call to `writeH5AD()`

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/federicomarini.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HCATonsilData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HCATonsilData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
