### ISSUE TITLE
MSstatsBig

### ISSUE THREAD

**Issue by mstaniak** [Bioconductor/Contributions#3193]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Vitek-Lab/MSstatsBig

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ ]x The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by mstaniak** [comment]
Hi,
we have 4 functions in this package, and 3 of them have runnable examples. Making an example for the remaining functions was a problem because we didn't have publicly available data for this purpose. Is an exception to the 80% example coverage rule an option or should I add the missing example?

**Comment by mstaniak** [comment]
Hi @DarioS, last week I described a reason for ERROR in check, is it OK or should I look for another data set that could be used for runnable examples?

**Comment by DarioS** [comment]
It might be O.K. But, is it possible to use any publicly available data to help identify when the function begins to fail over time?

**Comment by mstaniak** [comment]
@DarioS I updated the package, now it includes an example for this function. No errors or warnings now. Please let me know if there are any other required changes.

**Comment by DarioS** [comment]
MSstasBig is a file handling library for very large files that do not fit into R.A.M. I noted some issues.

- `CamelCaps` is used for functions. It should only be used for classes. Functions and parameters need to be `camelCase`. Please refer to R code of the developer's manual, particularly [Class Names,](https://contributions.bioconductor.org/r-code.html?#class-names), [Function Names](https://contributions.bioconductor.org/r-code.html?#rcode-function-names) and [Variable Names](https://contributions.bioconductor.org/r-code.html?#variable-names).
- Assignment uses `=` but needs to use `<-`. See [Code Syntax and Efficiency](https://contributions.bioconductor.org/r-code.html?#code-syntax-and-efficiency).
- The number of file converters is just two.

  > `MSstatsBig` currently includes converters for Spectronaut and FragPipe.

Could it also handle what seems to be the most popular software at the moment, DIA-NN? Also, what about SCIEX formats?

- The vignette attempts to write to disk in the current working directory. This is not permitted. Please refer to [Web Querying and File Caching](https://contributions.bioconductor.org/r-code.html?q=tempdir#web-querying-and-file-caching).

  > It is not allowed to download or write any files to a users home directory, working directory, or package directory.
  
```r
> getwd()
  "C:/"
> converted_data = BigFragPipetoMSstatsFormat(system.file("extdata", "fgexample.csv", package = "MSstatsBig"),
                                              "output_file.csv", backend="arrow")
Error: IOError: Failed to open local file 'C:/topN_output_file.csv'. Detail: [Windows error 5] Access is denied.
```

- The vignette lacks sufficient explanation.

> Once then, you can load the output file into memory, or collect the arrow file using the code below.

  What does _collecting_ the arrow file mean? _Collection_ has many different meanings in computer science.

> Once the converter is run the clasic `MSstats` workflow can be followed.

  Don't assume that everyone who finds your package is an MSstats expert. Add explanation of the large code chunk.
  
  Also, copying every parameter from a function manual page is not appropriate for a vignette.
  
![image](https://github.com/Bioconductor/Contributions/assets/631218/e520cae9-c022-4b4b-a907-ecb28f15887d)

  Please include useful information which is not found elsewhere.

**Comment by mstaniak** [comment]
Hi,

thank you for the review,

> CamelCaps is used for functions. It should only be used for classes. Functions and parameters need to be camelCase. 

I changed names of function that started with "Big". We can keep the names that start with "MSstats", right? 

> Assignment uses = but needs to use <-. 

Is this required? Our other packages relied heavily on data.table package and followed its style, including '=' usage. We can change it for this package if really necessary, please let me know.

> Could it also handle what seems to be the most popular software at the moment, DIA-NN? Also, what about SCIEX formats?

It can handle DIA-NN output for MSstats via MSstatsPreprocessBig function and other formats with minor pre-processing on user side, I will add information about this to our documentation.

> The vignette attempts to write to disk in the current working directory. This is not permitted.

I changed this by using tempdir()

> The vignette lacks sufficient explanation.

We will update the vignette as soon as possible.

**Comment by mstaniak** [comment]
Hi @DarioS I removed redundant information from the vignette. Instead, I added a few sentences on MSstats workflow (+reference) and applicability to outputs of other tools. Please let me know if other changes are required.

**Comment by DarioS** [comment]
CamelCaps can stay. But [MSstatsTMT](https://www.bioconductor.org/packages/release/bioc/html/MSstatsTMT.html) uses `<-`, so changing all assignments to `<-` is necessary.

**Comment by mstaniak** [comment]
I fixed that, are we good to go?

**Comment by DarioS** [comment]
We are.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mstaniak.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MSstatsBig")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MSstatsBig

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
