### ISSUE TITLE
knowYourCG

### ISSUE THREAD

**Issue by golddc** [Bioconductor/Contributions#3197]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zhou-lab/knowYourCG
Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
You currently download or suggest downloading additional annotation data from github. Downloading from personal github and dropboxes are not allowed. A smaller dataset should be included in the package or the data should be hosted on a trusted public server like zenodo, AWS S3 buckets, Azure Microsoft Data Lakes, etc , minimally an institutional level server. See also AnnotationHub for a Bioconductor distributed solution

**Comment by golddc** [comment]
Hello,

I have removed the part of our vignette that suggests downloading annotation data from github. Thanks for reviewing the package and for bringing this issue to my attention. Please let me know if there are any other issues.



David

From: lshep ***@***.***>
Reply-To: Bioconductor/Contributions ***@***.***>
Date: Monday, October 2, 2023 at 11:08 AM
To: Bioconductor/Contributions ***@***.***>
Cc: "Goldberg, David (NGG)" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Bioconductor/Contributions] knowYourCG (Issue #3197)


You currently download or suggest downloading additional annotation data from github. Downloading from personal github and dropboxes are not allowed. A smaller dataset should be included in the package or the data should be hosted on a trusted public server like zenodo, AWS S3 buckets, Azure Microsoft Data Lakes, etc , minimally an institutional level server. See also AnnotationHub for a Bioconductor distributed solution

**Comment by lshep** [comment]
This is still in the man pages?

**Comment by golddc** [comment]
Hi,

My apologies, I forgot about some of the text in the documentation. There should no longer be any references to downloading data from github. Thank you.



David

From: lshep ***@***.***>
Reply-To: Bioconductor/Contributions ***@***.***>
Date: Friday, October 6, 2023 at 10:28 AM
To: Bioconductor/Contributions ***@***.***>
Cc: "Goldberg, David (NGG)" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Bioconductor/Contributions] knowYourCG (Issue #3197)


This is still in the man pages?

**Comment by lshep** [comment]
All dependencies must be on CRAN or Bioconductor in order to be used.  rnndescent does not appear to be on CRAN or Bioconductor and will have to be removed.

**Comment by golddc** [comment]
I have removed the functions using rnndescent and updated the description file so that the package is no longer suggested. Hopefully, that clears up the errors. Thanks!


David

From: lshep ***@***.***>
Reply-To: Bioconductor/Contributions ***@***.***>
Date: Tuesday, October 10, 2023 at 7:53 AM
To: Bioconductor/Contributions ***@***.***>
Cc: "Goldberg, David (NGG)" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Bioconductor/Contributions] knowYourCG (Issue #3197)


All dependencies must be on CRAN or Bioconductor in order to be used. rnndescent does not appear to be on CRAN or Bioconductor and will have to be removed.

**Comment by lshep** [comment]
Please follow instructions for pushing to git.bioconductor.org with a valid version bump to trigger a new build.  See https://github.com/Bioconductor/Contributions/issues/3197#issuecomment-1755175540

**Comment by golddc** [comment]
Hello,

I created the upstream remote and pushed to git.bioconductor.org.

I am receiving one warning in the build report that there are package files that exceed the 5MB size limit. However, to my knowledge there are no files that are this large. Please let me know if there is any guidance on how to proceed with this warning. Thank you.



David

From: lshep ***@***.***>
Reply-To: Bioconductor/Contributions ***@***.***>
Date: Wednesday, October 11, 2023 at 8:02 AM
To: Bioconductor/Contributions ***@***.***>
Cc: "Goldberg, David (NGG)" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Bioconductor/Contributions] knowYourCG (Issue #3197)


Please follow instructions for pushing to git.bioconductor.org with a valid version bump to trigger a new build. See #3197 (comment)<https://github.com/Bioconductor/Contributions/issues/3197#issuecomment-1755175540>

**Comment by lshep** [comment]
If you run BiocCheck locally, it will give you an output directory with a more verbose check that list the offending files.

**Comment by LiNk-NY** [comment]
Hi David, @golddc 
Thank you for your submission. 
Please see the review below.
Best,
Marcel

--- 

# knowYourCG #3197

## DESCRIPTION

* Remove the `Authors` field, the `Authors@R` is sufficient.
* Add `BugReports` and `URL` fields
* Usually data packages are listed in the `Suggests` field. Why is
`sesameData` a hard dependency?
* The R version dependency should be `4.4.0` or greater.

## NAMESPACE

* Consider avoiding prefixes such as `KYCG_` in function names. The full
address of a function already contains this information, i.e.,
`knowYourCG::KYCG_annoProbes`. Is there potential for function name
clobbering? Perhaps use more descriptive names.
* Use the native `|>` pipe rather than importing `%>%` from `dplyr`.

## vignettes

* It seems like the `sesameDataCache()` automatically downloads all 91 EH
resources. Is there a way to __only__ download the necessary datasets or are
all datasets needed?
* Is there a reason for the subsetting in `vignettes/KYCG.Rmd:L#220`? Perhaps
save the set of names into a vector. Ideally, the returned data should have
those as the first few variables in the data.
* Consider using `SummarizedExperiment` as the main representation for the
`betas` input and allow compatibility for `matrix` class inputs as well.


## R

* Use more descriptive argument names rather than `query` which seems to
be a different input depending on the function.
* Consider moving plotting functionality to a separate package. This would
reduce the dependency heaviness of `knowYourCG`.

## tests

* There was an error in running `covr::package_coverage` but this may have
been due to not downloading all 91 resources to my machine.

**Comment by golddc** [comment]
Thank you Marcel. I am currently working on addressing these points.

Regarding the R version dependency, can this be switched to 4.4.0 when this version is officially released? Or will I need to install the development version now? Please let me know, thanks.


From: Marcel Ramos ***@***.***>
Reply-To: Bioconductor/Contributions ***@***.***>
Date: Monday, November 6, 2023 at 2:51 PM
To: Bioconductor/Contributions ***@***.***>
Cc: "Goldberg, David (NGG)" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Bioconductor/Contributions] knowYourCG (Issue #3197)


Hi David, @golddc<https://github.com/golddc>
Thank you for your submission.
Please see the review below.
Best,
Marcel

________________________________
knowYourCG #3197<https://github.com/Bioconductor/Contributions/issues/3197>
DESCRIPTION

  *   Remove the Authors field, the ***@***.*** is sufficient.
  *   Add BugReports and URL fields
  *   Usually data packages are listed in the Suggests field. Why is
sesameData a hard dependency?
  *   The R version dependency should be 4.4.0 or greater.

NAMESPACE

  *   Consider avoiding prefixes such as KYCG_ in function names. The full
address of a function already contains this information, i.e.,
knowYourCG::KYCG_annoProbes. Is there potential for function name
clobbering? Perhaps use more descriptive names.
  *   Use the native |> pipe rather than importing %>% from dplyr.

vignettes

  *   It seems like the sesameDataCache() automatically downloads all 91 EH
resources. Is there a way to only download the necessary datasets or are
all datasets needed?
  *   Is there a reason for the subsetting in vignettes/KYCG.Rmd:L#220? Perhaps
save the set of names into a vector. Ideally, the returned data should have
those as the first few variables in the data.
  *   Consider using SummarizedExperiment as the main representation for the
betas input and allow compatibility for matrix class inputs as well.

R

  *   Use more descriptive argument names rather than query which seems to
be a different input depending on the function.
  *   Consider moving plotting functionality to a separate package. This would
reduce the dependency heaviness of knowYourCG.

tests

  *   There was an error in running covr::package_coverage but this may have
been due to not downloading all 91 resources to my machine.

**Comment by golddc** [comment]
Hi Marcel,

I have incorporated most of the feedback from the review into our submission. Please see below for some of the comments


  *   It seems like the sesameDataCache() automatically downloads all 91 EH
resources. Is there a way to only download the necessary datasets or are
all datasets needed?

I think there is more flexibility when downloading all datasets, and it is not overly time or memory consuming. A user may not know in advance which resources or platform they want to use for testing. I think it’s best for discovery to use our default setting of testing all datasets, which requires downloading all EH resources. Additionally, once all the resources are cached one could work offline without needing to download again from EH.


  *   Consider moving plotting functionality to a separate package. This would
reduce the dependency heaviness of knowYourCG.
I would prefer to keep the plotting functions in the package. Most functions only depend on ggplot and directly handle the output of the package’s analysis functions, so I think it is convenient. Please let me know if this is ok, alternatively I can try to reduce some of the dependencies.



David








From: Marcel Ramos ***@***.***>
Reply-To: Bioconductor/Contributions ***@***.***>
Date: Monday, November 6, 2023 at 2:51 PM
To: Bioconductor/Contributions ***@***.***>
Cc: "Goldberg, David (NGG)" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Bioconductor/Contributions] knowYourCG (Issue #3197)


Hi David, @golddc<https://github.com/golddc>
Thank you for your submission.
Please see the review below.
Best,
Marcel

________________________________
knowYourCG #3197<https://github.com/Bioconductor/Contributions/issues/3197>
DESCRIPTION

  *   Remove the Authors field, the ***@***.*** is sufficient.
  *   Add BugReports and URL fields
  *   Usually data packages are listed in the Suggests field. Why is
sesameData a hard dependency?
  *   The R version dependency should be 4.4.0 or greater.

NAMESPACE

  *   Consider avoiding prefixes such as KYCG_ in function names. The full
address of a function already contains this information, i.e.,
knowYourCG::KYCG_annoProbes. Is there potential for function name
clobbering? Perhaps use more descriptive names.
  *   Use the native |> pipe rather than importing %>% from dplyr.

vignettes

  *   It seems like the sesameDataCache() automatically downloads all 91 EH
resources. Is there a way to only download the necessary datasets or are
all datasets needed?
  *   Is there a reason for the subsetting in vignettes/KYCG.Rmd:L#220? Perhaps
save the set of names into a vector. Ideally, the returned data should have
those as the first few variables in the data.
  *   Consider using SummarizedExperiment as the main representation for the
betas input and allow compatibility for matrix class inputs as well.

R

  *   Use more descriptive argument names rather than query which seems to
be a different input depending on the function.
  *   Consider moving plotting functionality to a separate package. This would
reduce the dependency heaviness of knowYourCG.

tests

  *   There was an error in running covr::package_coverage but this may have
been due to not downloading all 91 resources to my machine.

**Comment by LiNk-NY** [comment]
@golddc 
Hi David, 

> Thank you Marcel. I am currently working on addressing these points. Regarding the R version dependency, can this be switched to 4.4.0 when this version is officially released? Or will I need to install the development version now? Please let me know, thanks. 

You should be using R devel as indicated in the Bioconductor Guidelines https://contributions.bioconductor.org/use-devel.html#use-devel

> I think there is more flexibility when downloading all datasets, and it is not overly time or memory consuming. A user may not know in advance which resources or platform they want to use for testing. I think it’s best for discovery to use our default setting of testing all datasets, which requires downloading all EH resources. Additionally, once all the resources are cached one could work offline without needing to download again from EH.

Please selectively download only the necessary resources for the example. Excessive downloads require additional costs from Bioconductor especially across multiple users. It is best to minimize the downloads from cloud resources. 

> I would prefer to keep the plotting functions in the package. Most functions only depend on ggplot and directly handle the output of the package’s analysis functions, so I think it is convenient. Please let me know if this is ok, alternatively I can try to reduce some of the dependencies.

Analysis and plotting packages are generally separate entities. Some users may only be interested in the analysis portion of the package and may not want to install the plotting components. With user experience in mind, it is best to separate functionalities into modular packages. See the recommendation below. 

```r
> pkgndep(package="knowYourCG")
'knowYourCG', version 0.99.6
- 122 packages are required for installing 'knowYourCG'.
- 157 packages are required if installing packages listed in all fields in DESCRIPTION.

Following adjustment could be performed:
- Found 1 function is imported from a heavy parent 'gprofiler2'. Moving 'gprofiler2''
  to 'Suggests' will reduce 24 dependencies.
Moving all mentioned packages to 'Suggests' will reduce the dependency packages from 122 to 98.
```

**Comment by golddc** [comment]
Thank you Marcel I am working on updating the package

From: Marcel Ramos ***@***.***>
Reply-To: Bioconductor/Contributions ***@***.***>
Date: Thursday, December 28, 2023 at 10:57 AM
To: Bioconductor/Contributions ***@***.***>
Cc: "Goldberg, David (NGG)" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Bioconductor/Contributions] knowYourCG (Issue #3197)


Thank you Marcel. I am currently working on addressing these points. Regarding the R version dependency, can this be switched to 4.4.0 when this version is officially released? Or will I need to install the development version now? Please let me know, thanks.

You should be using R devel as indicated in the Bioconductor Guidelines https://contributions.bioconductor.org/use-devel.html#use-devel

I think there is more flexibility when downloading all datasets, and it is not overly time or memory consuming. A user may not know in advance which resources or platform they want to use for testing. I think it’s best for discovery to use our default setting of testing all datasets, which requires downloading all EH resources. Additionally, once all the resources are cached one could work offline without needing to download again from EH.

Please selectively download only the necessary resources for the example. Excessive downloads require additional costs from Bioconductor especially across multiple users. It is best to minimize the downloads from cloud resources.

I would prefer to keep the plotting functions in the package. Most functions only depend on ggplot and directly handle the output of the package’s analysis functions, so I think it is convenient. Please let me know if this is ok, alternatively I can try to reduce some of the dependencies.

Analysis and plotting packages are generally separate entities. Some users may only be interested in the analysis portion of the package and may not want to install the plotting components. With user experience in mind, it is best to separate functionalities into modular packages. See the recommendation below.

> pkgndep(package="knowYourCG")

'knowYourCG', version 0.99.6

- 122 packages are required for installing 'knowYourCG'.

- 157 packages are required if installing packages listed in all fields in DESCRIPTION.



Following adjustment could be performed:

- Found 1 function is imported from a heavy parent 'gprofiler2'. Moving 'gprofiler2''

  to 'Suggests' will reduce 24 dependencies.

Moving all mentioned packages to 'Suggests' will reduce the dependency packages from 122 to 98.

**Comment by golddc** [comment]
Hi Marcel,

The plotting functions have been removed and will be included in a separate package in the future. The dependency heavy import has been moved to suggests, and only the used database sets are retrieved from experiment hub. Please let me know if there are any more suggestions. Thank you



David

From: Marcel Ramos ***@***.***>
Reply-To: Bioconductor/Contributions ***@***.***>
Date: Thursday, December 28, 2023 at 10:57 AM
To: Bioconductor/Contributions ***@***.***>
Cc: "Goldberg, David (NGG)" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Bioconductor/Contributions] knowYourCG (Issue #3197)


Thank you Marcel. I am currently working on addressing these points. Regarding the R version dependency, can this be switched to 4.4.0 when this version is officially released? Or will I need to install the development version now? Please let me know, thanks.

You should be using R devel as indicated in the Bioconductor Guidelines https://contributions.bioconductor.org/use-devel.html#use-devel

I think there is more flexibility when downloading all datasets, and it is not overly time or memory consuming. A user may not know in advance which resources or platform they want to use for testing. I think it’s best for discovery to use our default setting of testing all datasets, which requires downloading all EH resources. Additionally, once all the resources are cached one could work offline without needing to download again from EH.

Please selectively download only the necessary resources for the example. Excessive downloads require additional costs from Bioconductor especially across multiple users. It is best to minimize the downloads from cloud resources.

I would prefer to keep the plotting functions in the package. Most functions only depend on ggplot and directly handle the output of the package’s analysis functions, so I think it is convenient. Please let me know if this is ok, alternatively I can try to reduce some of the dependencies.

Analysis and plotting packages are generally separate entities. Some users may only be interested in the analysis portion of the package and may not want to install the plotting components. With user experience in mind, it is best to separate functionalities into modular packages. See the recommendation below.

> pkgndep(package="knowYourCG")

'knowYourCG', version 0.99.6

- 122 packages are required for installing 'knowYourCG'.

- 157 packages are required if installing packages listed in all fields in DESCRIPTION.



Following adjustment could be performed:

- Found 1 function is imported from a heavy parent 'gprofiler2'. Moving 'gprofiler2''

  to 'Suggests' will reduce 24 dependencies.

Moving all mentioned packages to 'Suggests' will reduce the dependency packages from 122 to 98.

**Comment by LiNk-NY** [comment]
Hi David, @golddc 

Please test a `Suggest`ed package's availability with `requireNamespace` in the functions that use the package's functionality. For example, 

```r
myfun <- function(...) {
if (!requireNamespace("gprofiler2", quietly = TRUE))
    stop("Install the 'gprofiler2' to use this function")
gprofiler2::fun()
}
```

Everything else looks good. 

Best regards,
Marcel

**Comment by golddc** [comment]
Hi Marcel,

I updated the function using gprofiler to include the availability check and error handler and the package is building successfully. Hope everything is all set. Thanks.



David

From: Marcel Ramos ***@***.***>
Reply-To: Bioconductor/Contributions ***@***.***>
Date: Friday, February 16, 2024 at 2:48 PM
To: Bioconductor/Contributions ***@***.***>
Cc: "Goldberg, David (NGG)" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Bioconductor/Contributions] knowYourCG (Issue #3197)


Hi David, @golddc<https://github.com/golddc>

Please test a Suggested package's availability with requireNamespace in the functions that use the package's functionality. For example,

myfun <- function(...) {

if (!requireNamespace("gprofiler2", quietly = TRUE))

    stop("Install the 'gprofiler2' to use this function")

gprofiler2::fun()

}

Everything else looks good.

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Thanks @golddc 
I tried to check the package and got an error: 
```r
> cg_lists <- getDBs("MM285.TFBS")
Selected the following database groups:
1. KYCG.MM285.TFBSconsensus.20220116
Error in stopAndCache(title) : 
| File KYCG.MM285.TFBSconsensus.20220116 either not found or needs to be cached to be
| used in sesame.
| Please make sure you have updated ExperimentHub and try
| > sesameDataCache("KYCG.MM285.TFBSconsensus.20220116")
| or download all data
| > sesameDataCache()
| to retrieve and cache needed sesame data.
Calls: getDBs ... capture.output -> withVisible -> .sesameDataGet -> stopAndCache
```
Perhaps the example should run `sesameDataCache("KYCG.MM285.TFBSconsensus.20220116")` instead of 
producing an error.

**Note**. The examples should be self-runnable otherwise they will produce an error on the Bioconductor Build System (BBS) as well.

**Comment by LiNk-NY** [comment]
Hi @golddc 

Thanks for making the update. Unfortunately,
I see the same error with a different dataset. 

```r
> sesameData::sesameDataCache(data_titles=
+ c("KYCG.MM285.TFBSconsensus.20220116","KYCG.MM285.chromHMM.20210210"))
Metadata (N=1):

(1/1) EH6823:

> cg_lists <- getDBs("MM285.TFBS")
Selected the following database groups:
1. KYCG.MM285.TFBSconsensus.20220116
> queries <- cg_lists[(sapply(cg_lists, length) > 40000)]
> result_list <- lapply(queries, testEnrichment, "MM285.chromHMM")
Platform set to: MM285
Selected the following database groups:
1. KYCG.MM285.chromHMM.20210210
Testing against 18 database(s)...
Error in stopAndCache(title) : 
| File MM285.address either not found or needs to be cached to be
| used in sesame.
| Please make sure you have updated ExperimentHub and try
| > sesameDataCache("MM285.address")
| or download all data
| > sesameDataCache()
| to retrieve and cache needed sesame data.
Calls: lapply ... capture.output -> withVisible -> .sesameDataGet -> stopAndCache
Execution halted
```
Can you try clearing your cache so that you can see the errors? 
-Marcel

**Comment by golddc** [comment]
Hi Marcel,

Thank you for pointing that out. I still had data sets cached so wasn’t seeing the same errors. I cleared the cache and went through the examples adding code to cache the files again. Everything should run fine. Please let me know if the package is ok now and if anything else comes to your attention. Thank you.



David

From: Marcel Ramos ***@***.***>
Reply-To: Bioconductor/Contributions ***@***.***>
Date: Wednesday, March 27, 2024 at 1:31 PM
To: Bioconductor/Contributions ***@***.***>
Cc: "Goldberg, David (NGG)" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [Bioconductor/Contributions] knowYourCG (Issue #3197)


Hi @golddc<https://github.com/golddc>

Thanks for making the update. Unfortunately,
I see the same error with a different dataset.

> sesameData::sesameDataCache(data_titles=

+ c("KYCG.MM285.TFBSconsensus.20220116","KYCG.MM285.chromHMM.20210210"))

Metadata (N=1):



(1/1) EH6823:



> cg_lists <- getDBs("MM285.TFBS")

Selected the following database groups:

1. KYCG.MM285.TFBSconsensus.20220116

> queries <- cg_lists[(sapply(cg_lists, length) > 40000)]

> result_list <- lapply(queries, testEnrichment, "MM285.chromHMM")

Platform set to: MM285

Selected the following database groups:

1. KYCG.MM285.chromHMM.20210210

Testing against 18 database(s)...

Error in stopAndCache(title) :

| File MM285.address either not found or needs to be cached to be

| used in sesame.

| Please make sure you have updated ExperimentHub and try

| > sesameDataCache("MM285.address")

| or download all data

| > sesameDataCache()

| to retrieve and cache needed sesame data.

Calls: lapply ... capture.output -> withVisible -> .sesameDataGet -> stopAndCache

Execution halted

Can you try clearing your cache so that you can see the errors?
-Marcel

**Comment by LiNk-NY** [comment]
Hi @golddc 

Thank you for making those changes. 
Your package has been accepted. 

Best regards,
Marcel

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/golddc.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("knowYourCG")`. The package 'landing page' will be created at

https://bioconductor.org/packages/knowYourCG

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
