### ISSUE TITLE
txdbmaker

### ISSUE THREAD

**Issue by hpages** [Bioconductor/Contributions#3226]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/txdbmaker

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by hpages** [comment]
This is a spin-off from **GenomicFeatures** that contains the tools for making TxDb objects. The plan is to deprecate these tools in **GenomicFeatures** (in BioC 3.19), and redirect to the tools in **txdbmaker**. Then to defunct them (in BioC 3.20). And finally to remove them from **GenomicFeatures** (in BioC 3.21). Once this is done, **GenomicFeatures** will only contain the functions and methods to operate on TxDb objects (consumers), while **txdbmaker** provides the tools to make them (producers).

The motivations for this split are:
- **GenomicFeatures** became too big and hard to maintain. This split will make **GenomicFeatures** about half the size. This in turn will make its maintenance easier, will make `R CMD check` significantly faster, and will reduce its dependencies (e.g. it will no longer need to depend on **rtracklayer** and **biomaRt**, or to suggest **RMariaDB**).
- 130+ Bioconductor packages depend on **GenomicFeatures**. Most of them only _consume_ TxDb objects -- they don't need to _produce_ them -- so this split won't affect them. However now they will depend on a lighter  **GenomicFeatures**.
- The `makeTxDbFromBiomart()` function and other _producer_ tools depend on remote services that tend to be unreliable. Because of this, the daily checks on **GenomicFeatures** tend to have good days and bad days. By  moving the _producer_ tools to a separate package, the daily checks on **GenomicFeatures** will be more predictible (i.e. no bad surprises).
- Yes, the split only displaces the problem. But at least now the problem is confined to a smaller package (**txdbmaker**) that very few Bioconductor packages will actually depend on.
- Finally some of the tools in **txdbmaker** should probably be revisited at some point, in an effort to make them more reliable. That work will be slightly facilitated by the small size of the package.

**Comment by lshep** [comment]
I haven't switch the SPB to build on 3.19 yet so its still running R 4.3/Bioc 3.18

**Comment by hpages** [comment]
@lshep I see. I'm just temporarily removing `R (>= 4.4.0)` from `Depends` so we'll see how that goes.

**Comment by hpages** [comment]
Hmm.. `R CMD check` takes only 7m8s on my laptop:
```
hpages@XPS15:~/WIP/txdbmaker$ time R CMD check txdbmaker_0.99.1.tar.gz 
* using log directory ‘/home/hpages/WIP/txdbmaker/txdbmaker.Rcheck’
...
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 2 NOTEs
See
  ‘/home/hpages/WIP/txdbmaker/txdbmaker.Rcheck/00check.log’
for details.

real	7m8.177s
user	3m24.953s
sys	0m7.912s
```
The daily builds are currently running on nebbiolo2 and lconway, and the load is very high on the 2 machines, so maybe that's why `R CMD check` took more than 10 minutes. I'll trigger another build later when the daily builds are not running to see if that makes a difference.

**Comment by hpages** [comment]
`R CMD check` went slightly faster now that the build machines are no longer busy, but still took slightly more than 10 minutes: 12 minutes 13.50 seconds on nebbiolo2, and 10 minutes 5.24 seconds on lconway. I hope that's acceptable.

**Comment by Kayla-Morrell** [comment]
@hpages - Please see the initial review of the package below. No major changes to the package, just a few points that could be addressed. The required changes must be made while the suggested changes do not have to be (though strongly encouraged). Comment back when updates have been made and I'll do a re-review.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding the maintainer's ORCID iD in 'Authors@R' with
  'comment=c(ORCID="...")'
- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        Microarray, GO

## Data

- [ ] REQUIRED: There should be documentation within `inst/scripts/` for the
  files present in `inst/extdata/`. 

## Vignette

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to
  the user how to install the package from Bioconductor. This code chunk should
include `eval = FALSE`.
- [ ] SUGGESTION: We strongly suggest the use of table of contents.

## Man pages

- [ ] SUGGESTION: We encourage a package man page with an overview of the
  package and links to the main functions.

## R code

- [ ] SUGGESTION: Avoid 'cat' and 'print' outside of 'show' methods
- [ ] SUGGESTION: Consider multiples of 4 spaces for line indents; 1448 lines are not.

Best,
Kayla

**Comment by lshep** [comment]
@hpages may we expect updates to the package to address the review comments soon?

**Comment by hpages** [comment]
Hi @Kayla-Morrell, thanks for your feedback. I'll work on it this week.

**Comment by hpages** [comment]
This `R CMD check` WARNING will go away when the package makes it to release:
```
* checking Rd cross-references ... WARNING
Missing link or links in Rd file 'txdbmaker-package.Rd':
  ‘https://bioconductor.org/packages/release/bioc/vignettes/txdbmaker/inst/doc/txdbmaker.html’
```
I thought it might be convenient to link the online vignette off the package man page but I can drop that if it's too problematic.

All REQUIRED changes were made. To document the data in `inst/extdata/` I added a [`README.txt`](https://github.com/Bioconductor/txdbmaker/blob/devel/inst/extdata/README.txt) in `inst/extdata/` rather than in `inst/scripts/`.

Here are the SUGGESTED changes I made:
- The vignette now has a table of contents.
- The package now has its own man page, with a link to the vignette where the main functions are quickly introduced.

H.

**Comment by Kayla-Morrell** [comment]
@hpages - Thank you for making the necessary changes. I've looked everything over and I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hpages.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("txdbmaker")`. The package 'landing page' will be created at

https://bioconductor.org/packages/txdbmaker

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
