### ISSUE TITLE
miRNAss

### ISSUE THREAD

**Issue by cyones** [Bioconductor/Contributions#323]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cyones/miRNAss

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@LiNk-NY will review this package. I could not figure out, from the  man page, the vignette, or actually the `celegans` data object, how the input to this package was to be generated. Minimally augment the vignette to show the upstreaming processing steps required to generate the object, and augment the man page to fully describe `x`. It is also very unusual for a Bioconductor package not to depend, import, or suggest other Bioconductor packages, primarily to facilitate robust data representation and user interoperability between packages. Maybe your package is unrelated to other Bioconductor work flows, but consider whether SummarizedExperiment, GenomicRanges, DataFrame, Biostrings::DNAStringSet are relevant to your package, and implement an appropriate interface to these data representations.

**Comment by cyones** [comment]
@LiNk-NY, thank you very much for your recommendations, this is the first package we try to publish in Bioconductor so we have no experience in the process. 

We have several bioinformatics tools developed (http://fich.unl.edu.ar/sinc/blog/web-demo/) and we are in plans of migrate some of them to R/Bioconductor as it is the most used repository for this kind of tools. For this reason, miRNAss may look a little disconected from the rest of the Bioconductor ecosystem for now. As we move the rest of the tools of the miRNAss pipeline to Bioconductor, the interoperability with Bioconductor will improve. The next tool in plans of migration is HExtractor (https://sourceforge.net/projects/sourcesinc/files/hextractor/). For now, we add as suggested package S4Vectors.

**Comment by LiNk-NY** [comment]
Hi Cristian, @cyones 
Thank you for submitting to Bioconductor! Please find your package review below.
Please contact me if you have any questions. 
Regards,
Marcel 

---

# miRNAss #323

## Overall

As Martin @mtmorgan had mentioned, your package should work well with what is already available in Bioconductor. Please see his suggestions in the comments above. 

### Interoperability

* Once you've figured out what works well with your data, you can include an optional Bioconductor class argument in your main function. This will improve the interoperability of the package. 

### Grammar

*Major*
* Your argument names should be more descriptive especially if this is a created function and not a method. `x` and `y` can be anything, change these to something more meaningful. 
* Avoid the use of `1:n` style sequences. 
* No need to use `gc` in your function. AFAIK, `gc` is for interactive use and R does it for you already.

*Minor*
* Please use arrow `<-` assignment. 

### Documentation

* Include a description to the main function. You want to make it clear to the user what the function is for.

### Vignette

* There is no straight forward way to create a dataset such as `celegans` from other types of data. Please show how this dataset was created. 
* Please add `sessionInfo()` to the vignette.

**Comment by cyones** [comment]
@LiNk-NY and @mtmorgan, thank you very much for your recommendations, we have made all the corrections suggested.
About the interoperability, miRNAss may look a little disconnected from the rest of the Bioconductor ecosystem for now, but we think it is because is the first miRNA prediction tool in Bioconductor. We did not find any tool to extract hairpin sequences from the raw genome nor calculate numerical features from this sequences to feed the miRNAss method. As we mention, we have these tools developed and we are migrating the whole pipeline to Bioconductor. The next tool in plans of migration is HExtractor (https://sourceforge.net/projects/sourcesinc/files/hextractor/).

For now, we have added BiocGeneric as an import to avoid future problems of incompatibility. Also, we expanded the vignette to explain how to obtain the inputs of miRNAss from our current tools, until we finish the migration.

**Comment by LiNk-NY** [comment]
Hi Cristian, @cyones 

I am sure that there is an existing Bioconductor class that you can use to develop your software.
Being that it may be the first miRNA prediction tool, it is even more imperative to use Bioconductor structures already available so that your package can be widely used along with other packages.

Perhaps the package is not ready for Bioconductor submission just yet.

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Your issue has been closed due to inactivity. To submit your revised package to Bioconductor, please create another issue. Thank you. 
-Marcel
