### ISSUE TITLE
RGraphSpace: A lightweight package for representing large igraph objects in a normalized coordinate system.

### ISSUE THREAD

**Issue by castromaa** [Bioconductor/Contributions#3235]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sysbiolab/RGraphSpace

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
PathwaySpace is not a package on CRAN or Bioconductor; Any package that is listed as a dependency must be on CRAN or Bioconductor.  Please remove this dependency or ask the maintainers to submit their package.

**Comment by castromaa** [comment]
Thank you. I had overlooked the removal of "PathwaySpace" from the 'suggests' section. It has now been excluded. It's worth noting that this package is not utilized in any aspect of RGraphSpace; rather, the dependency relationship is the other way around. So, as PathwaySpace relies on RGraphSpace, we are planning to submit PathwaySpace following the evaluation of RGraphSpace by Bioconductor. Any other suggestions, please let us know.

**Comment by lshep** [comment]
When I run R CMD check there is also an issue with the tests; I believe you have a typo and only have GraphSpace instead of RGraphSpace in both your defined test and the runTests.R file.  The unit test also seems rather trivial -- we would hope that more extensive testing of package internals would be reflected in the unit tests. 

However, I will move this into our git system for official build reports from our machines to begin the next phase. Please correct any ERROR, Warning, or Notes that will appear in the report once it is posted.

**Comment by castromaa** [comment]
Thank you, Lori. You are correct, it was a typo from an old nomenclature. We included the "R" in the RGraphSpace name to avoid a potential conflicting name with a web tool in a related field. I'll fix this typo in the github package, thanks.

Regarding the unit tests, there are extensive checks inside the GraphSpace class constructor.  I would be happy to include any suggestions during the next phase.

**Comment by castromaa** [comment]
I've fixed almost all build report issues, but the following ones persist:

#### * ERROR: Maintainer must add package name to Watched Tags on the support site.

I couldn't figure out how to add RGraphSpace to the 'Watched Tags' list. Please, advise.

#### * NOTE: Consider shorter lines; 11 lines (1%) are > 80 characters long.

This node seems to refer to 11 lines in the package's vignette file (RGraphSpace.Rmd). Not sure how to implement this suggestion,  as the .Rmd is formatted to generate an html vignette. I could break lines, but doing so might disrupt the alignment of the vignette paragraphs. Please, advise.

#### * NOTE: Consider multiples of 4 spaces for line indents; 13 lines (1%) are not.

I used the "styler" package to setup 4 spaces for line indents across all .R files. However, 13 lines persist in other files. They seem to refer to the .Rd documentation files, which are generated by roxygen2.

#### * NOTE: Provide 'BugReports' field(s) in DESCRIPTION

"BugReports" field indicates a particular web page for submitting bug reports. Could we designate this suggestion as the package's page on Bioconductor once it becomes available?

**Comment by vjcitn** [comment]
I've fixed almost all build report issues, but the following ones persist:


* I couldn't figure out how to add RGraphSpace to the 'Watched Tags' list. Please, advise.

Here's how you do this.  First, make an account at support.bioconductor.org.  Then visit your profile.  You
will see something like this

![findtags](https://github.com/Bioconductor/Contributions/assets/4624066/bd6f1a51-15aa-4d77-b1ac-0bece86be1ea)

Look towards the bottom to see a "Tags" link.  Click on that and you will find a field where you can enter tags.  Use the name of your package as one of your tags.



The rest of these are "NOTE"s and you can address them at your discretion.  Except that
the BugReports field should include the URL of the Issues page for your source github repo.



#### * NOTE: Provide 'BugReports' field(s) in DESCRIPTION

"BugReports" field indicates a particular web page for submitting bug reports. Could we designate this suggestion as the package's page on Bioconductor once it becomes available?

**Comment by castromaa** [comment]
Thank you for your support; it was greatly helpful. RGraphSpace passed all checks this time.

**Comment by LiNk-NY** [comment]
Hi Mauro, @castromaa 

Thank you for your submission. 
Unfortunately, the package does not leverage any existing Bioconductor software. 
Please consider a submission to CRAN. 

Best regards,
Marcel

**Comment by castromaa** [comment]
Hi Marcel,

Thank you for taking the time to evaluate RGraphSpace. While CRAN is a good suggestion, could I ask you to reconsider Bioconductor? This package is intended to enhance the user experience with RedeR, a package we maintain on Bioconductor. RedeR is an interactive software for visualizing and manipulating nested networks. Currently, it lacks a user-friendly interface to R graphics, requiring users to perform all tasks in a Java interface. RGraphSpace will parse graph objects for RedeR using igraph syntax rules, enabling users to plot the same network in RedeR and ggplot2. As igraph is a very popular tool in network fields, we created RGraphSpace separated from RedeR, so other users (that may not know RedeR) could benefit from using RGraphSpace + igraph + ggplot2. It's worth noting that igraph itself lacks a straightforward interface for ggplot2. Therefore, we believe that this infrastructure could greatly benefit users interested in manipulating and visualizing networks. Please let us know any suggestions on how we could enhance RGraphSpace to align with Bioconductor's standards.

Sincerely,

Mauro

**Comment by vjcitn** [comment]
Thanks for this submission.  I feel that this particular package needs more work to demonstrate its relevance to Bioconductor and genomic data science.  The vignette is very abstract and deals only with a toy example.  I was led to have a look at RedeR which is also very interesting but includes code like 
```
gt3  <- subg(g=hs.inter, dat=ER.limma[ER.limma$degenes.t3!=0,], refcol=1)
```
which is valid, it works, but the user acceptability of this is somewhat questionable.  If I understand it correctly, RGraphSpace would help end-users doing genomic data science to take advantage of RedeR's capabilities.  I would ask that you build up the vignette to really sell the value of RedeR+RGraphSpace to those doing genomic data science.  I would also propose that in doing this you take advantage of some Bioconductor resources for representing genomic data and networks.  like ndexr for networks, and SummarizedExperiment or GSEABase for genomic data or gene sets as one might have for the "ER.limma" references above.  I hope you can follow some of these suggestions as it will be beneficial to your users and to Bioconductor!

**Comment by castromaa** [comment]
Great, thank you Vince. I agree, the vignette is still abstract and contains only a toy example, primarily because we're unable to fully disclose a case study from a companion paper that is currently under revision. But I will expand the vignette to incorporate your suggestions, which I truly appreciate. 

Can I ask another related advise? RGraphSpace is intended to be a lightweight interface for ggplot2, but not only for RedeR. The primary tool that motivated the implementation of RGraphSpace is called PathwaySpace, which we were planing to submit to Bioconductor after RGraphSpace. PathwaySpace is where we plan to showcase the usability of these new tools, particularly for the diffusion of gene signals in pathways, but this will require a normalized graph coordinate system provided by RGraphSpace.

As a brief overview, there are five main tools involved in the dependency design as we envision it:
1 - igraph: a popular tool, providing state-of-the-art graph methods, but lack good plotting capabilities. 
2 - ggplot2: offers state-of-the-art plotting capabilities, but is not readily compatible with igraph data objects.
3 - RedeR: provide an interactive interface for igraph networks.
4 - RGraphSpace: will provide methods to plot igraph and RedeR networks in ggplot2.
5 - PathwaySpace: will provide methods for diffusion of gene signals, using all the others to visualize gene signals onto pathways and graphs.

Therefore, giving this dependency design, would it make sense to submit PathwaySpace now so that the current reviewer could assess all these tools side by side?

**Comment by vjcitn** [comment]
Thanks for the followup.  It sounds like your software has a substantial generic component for *network science*, which would likely get good exposure through CRAN, and a possibly significant application space in genomic data science, which would be appropriate and useful for Bioconductor.  My suggestion at this point would be to consider those packages that enhance ggplot2 and igraph as CRAN packages, and the packages that deal with gene signaling networks as Bioconductor packages, which specifically take advantage of existing tooling for networks and gene sets in Bioconductor.

Why propose CRAN for the more generic components?  Because our reviewing energies and our capacity to support growing numbers of packages are  finite and are approaching limits.  We are trying to make changes to increase capacity and that effort of renovation is impacting our review and processing bandwidth.  So when the review process comes up with "has no bioconductor interop" it is natural to check whether contributors are aware of the CRAN option, which may have real benefits in terms of exposure to non-genomics users.

**Comment by vjcitn** [comment]
Of note is that Bioconductor packages may formally Depend upon CRAN packages.

**Comment by castromaa** [comment]
Thanks for sharing these concerns. It all makes sense to me, and we can definitely proceed with releasing RGraphSpace as a CRAN package. I will move in this direction.

As for submitting PathwaySpace to Bioconductor, we may need to wait a while until RGraphSpace is available on CRAN. I'll close this issue, many thanks.
