### ISSUE TITLE
(inactive) Error with SesameDataCache()

### ISSUE THREAD

**Issue by ardan33** [Bioconductor/Contributions#3237]
[zwdzwd](https://github.com/zwdzwd)
/
[sesame](https://github.com/zwdzwd/sesame)

I previously ran sesame no problem with version 3.17. However, since updating to version 3.18, I am having issues with the sesameDataCache() function.

This is the code I ran:
`if (!require("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install(version="3.18")
BiocManager::install("sesame", force=TRUE)
BiocManager::install("sesameData", force=TRUE)

BiocManager::install("ExperimentHub", force=TRUE)
BiocManager::install("BiocFileCache", force=TRUE)
getwd()
sessionInfo()
library(sesame)
sesame_checkVersion()
library(sesameData)
sesameDataCache()
packageVersion("sesameData")`

This is the error message:
sesame_checkVersion()
SeSAMe requires matched versions of R, sesame, sesameData and ExperimentHub.
Here is the current versions installed:
R: 4.3.1
Bioconductor: 3.18
sesame: 1.20.0
sesameData: 1.20.0
ExperimentHub: 2.10.0

library(sesameData)
sesameDataCache()
Metadata (N=91):

ExperimentHub Caching fails:
error in evaluating the argument 'x' in selecting a method for function 'query': Failed to collect lazy table.
Caused by error in db_collect():
! Arguments in ... must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?

I have no idea how to fix this... as I am extremely new to R. Any help would be appreciated.

**Comment by lshep** [comment]
You should not post help questions here. This is for submitting packages only. https://github.com/zwdzwd/sesame/issues
