### ISSUE TITLE
DegCre package submission

### ISSUE THREAD

**Issue by brianSroberts** [Bioconductor/Contributions#3265]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/brianSroberts/DegCre

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Please write to a tempdir() in examples and vignettes.  I see a write call in man/convertDegCreDataFrame.Rd that would save to the current working directory if run. 

When I tried to build your package I got the following ERROR: 
```
lorikern@jbcj433:~/PkgReview$ R CMD build DegCre 
* checking for file 'DegCre/DESCRIPTION' ... OK
* preparing 'DegCre':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘degcre_introduction_and_examples.Rmd’ using rmarkdown
Warning in doTryCatch(return(expr), name, parentenv, handler) :
  semi-transparency is not supported on this device: reported only once per page
Warning in doTryCatch(return(expr), name, parentenv, handler) :
  semi-transparency is not supported on this device: reported only once per page
Warning in doTryCatch(return(expr), name, parentenv, handler) :
  semi-transparency is not supported on this device: reported only once per page
Warning in grid.Call.graphics(C_polygon, x$x, x$y, list(as.integer(seq_along(x$x)))) :
  semi-transparency is not supported on this device: reported only once per page

Quitting from lines 336-340 [demo convert to DataFrame] (degcre_introduction_and_examples.Rmd)
Error: processing vignette 'degcre_introduction_and_examples.Rmd' failed with diagnostics:
undefined columns selected
--- failed re-building ‘degcre_introduction_and_examples.Rmd’

SUMMARY: processing the following file failed:
  ‘degcre_introduction_and_examples.Rmd’

Error: Vignette re-building failed.
Execution halted

```

**Comment by brianSroberts** [comment]
I have changed the example to write to a temp file. I also fixed a bug in convertDegCreDataFrame() that was causing the vignette build to error. I also added a test function for convertDegCreDataFrame().

**Comment by brianSroberts** [comment]
Hi, just posting again to get this issue to pop up again. I've made the changes and everything should be working correctly now.

**Comment by brianSroberts** [comment]
I'm not able to push to the Bioconductor git. I have activated my git credentials and the ssh key listed there matches mine. But when I try:

git push upstream main:devel

I get

git@git.bioconductor.org: Permission denied (publickey).

Running git remote -v returns:

origin	https://github.com/brianSroberts/DegCre.git (fetch)
origin	https://github.com/brianSroberts/DegCre.git (push)
upstream	git@git.bioconductor.org:packages/DegCre.git (fetch)
upstream	git@git.bioconductor.org:packages/DegCre.git (push)

which seems right.

So I'm not sure what I'm doing wrong. Any help is appreciated!

**Comment by lshep** [comment]
That does look correct as does all our configuration on our end.  I would check out maybe number 15 of http://contributions.bioconductor.org/git-version-control.html#faq  or add a new ssh key.

**Comment by brianSroberts** [comment]
The bio-issue-bot changed the tag from ERROR to WARNINGS. It appears that it is timing out when trying to run examples and build vignettes. The code in those is expected to take a while to run because the inputs are complex in order to faithfully reproduce actual uses of the package. Do I need to do something here?

**Comment by lshep** [comment]
Often times smaller datasets can be used to demonstrate the package effectively.  Can the amount of input being used be minimized to reduce timing. We expect packages to build and check in a reasonable amount of time.

**Comment by jianhong** [comment]
# Package 'DegCre' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. It is in pretty good shape. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.
## The DESCRIPTION file
- [ ] Important: R version should be no less than 4.4
## The NAMESPACE file
- [ ] NOTE: Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 17 import(GenomicRanges)
	* in line 18 import(S4Vectors)
	* in line 19 import(grDevices)
## R code
- [ ] NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/degCreConversions.R:
		+ at line 63 found '    for(binIdY in uniqBinIds){'
	* In file R/degCreCore.R:
		+ at line 1346 found '    for (uniqDBinY in uniqDistBinsX) {'
	* In file R/degCrePlotFuns.R:
		+ at line 223 found '    for(i in seq_along(uniqMaxBinDists)){'
- [ ] Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.
	* In file R/degCreConversions.R:
		+ at line 280 found '        keepHitsMcolsDf <- hitsMcolsDf[,c(seq_len(4),seq(from=8,to=10))]'
		+ at line 282 found '        outDf <- data.frame(keepDegDfx[,seq_len(4)],'
		+ at line 283 found '            keepCreDfx[,seq_len(4)],'
		+ at line 285 found '            keepDegDfx[,seq(from=5,to=ncol(keepDegDfx))],'
		+ at line 286 found '            keepCreDfx[,seq(from=5,to=ncol(keepCreDfx))])'
	* In file R/degCreCore.R:
		+ at line 323 found '    sortPromCreHitsDf <- promCreHitsDf[order(promCreHitsDf$assocDist),]'
		+ at line 455 found '    allDistBinsStatsMat <- cbind(allDistBinsStatsMat[,1],'
		+ at line 456 found '        allAssocProbFDR,allDistBinsStatsMat[,2:ncol(allDistBinsStatsMat)])'
		+ at line 462 found '    sortPromCreHitsStatsDf <- data.frame(sortPromCreHitsDf[,seq_len(3)],'
		+ at line 487 found '    mcolsHitsDf <- sortPromCreHitsStatsDf[,3:ncol(sortPromCreHitsStatsDf)]'
		+ at line 1242 found '  totalObs <- nrow(hitsWithDistDf[subHitsIndex,])'
	* In file R/degCrePerDegFuns.R:
		+ at line 125 found '    uniqGeneDegMcolsDf <- allDegGRMcolsDf[uniqGeneIndices,]'
		+ at line 237 found '        expectAssocPerDegDf[which(!is.na(rawExpectAssocs)),]'
- [ ] NOTE: Try to check the edge condition when using `seq.int` or `seq_len`. For example using `seq.int(min(5, nrow(data)))` to replace `seq.int(5)`
	* In file R/degCreConversions.R:
		+ at line 264 found '        keepDegDfx <- keepDegDfx[,c(seq_len(3),'
		+ at line 272 found '        keepCreDfx <- keepCreDfx[,c(seq_len(3),'
		+ at line 280 found '        keepHitsMcolsDf <- hitsMcolsDf[,c(seq_len(4),seq(from=8,to=10))]'
		+ at line 282 found '        outDf <- data.frame(keepDegDfx[,seq_len(4)],'
		+ at line 283 found '            keepCreDfx[,seq_len(4)],'
	* In file R/degCreCore.R:
		+ at line 462 found '    sortPromCreHitsStatsDf <- data.frame(sortPromCreHitsDf[,seq_len(3)],'
		+ at line 685 found '        outList <- listX[seq_len(5)]'
- [ ] NOTE: Functional programming: code repetition.
	* repetition in `convertDegCreDataFrame` and `convertdegCreResListToGInteraction`
		+ in convertDegCreDataFrame
			- line 2:{
			- line 3:    DegGRX <- degCreResList$DegGR
			- line 4:    CreGRX <- degCreResList$CreGR
			- line 5:    degCreHits <- degCreResList$degCreHits
			- line 6:    maskPassAlpha <- which(mcols(degCreHits)$assocProbFDR <= 
			- line 7:        assocAlpha)
			- line 8:    if (length(maskPassAlpha) < 1) {
			- line 9:        warning("No associations FDRs pass alpha.")
			- line 10:        outDf <- NA
			- line 11:    }
			- line 12:    else {
			- line 13:        keepDegCreHits <- degCreHits[maskPassAlpha]
		+ in convertdegCreResListToGInteraction
			- line 2:    {
			- line 3:        DegGRX <- degCreResList$DegGR
			- line 4:        CreGRX <- degCreResList$CreGR
			- line 5:        degCreHits <- degCreResList$degCreHits
			- line 6:        maskPassAlpha <- which(mcols(degCreHits)$assocProbFDR <= 
			- line 7:            assocAlpha)
			- line 8:        if (length(maskPassAlpha) < 1) {
			- line 9:            warning("No associations FDRs pass alpha.")
			- line 10:            outGInter <- NA
			- line 11:        }
			- line 12:        else {
			- line 13:            keepDegCreHits <- degCreHits[maskPassAlpha] 
## Documentation
- [ ] Note: Vignette should use `BiocStyle` package for formatting.
	* rmd file vignettes/degcre_introduction_and_examples.Rmd
- [ ] Important: Vignette should have an *Installation* section.
	* rmd file vignettes/degcre_introduction_and_examples.Rmd
- [ ] Important: Please include Bioconductor installation instructions using BiocManager.
	* rmd file vignettes/degcre_introduction_and_examples.Rmd

**Comment by brianSroberts** [comment]
> # Package 'DegCre' Review
> Thank you for submitting your package to Bioconductor. The package passed check and build. It is in pretty good shape. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review. Code: Note: please consider; Important: must be addressed.
> 
> ## The DESCRIPTION file
> * [ ]  Important: R version should be no less than 4.4
>
> _The R version has been updated to R 4.3.3 which is the latest public release_
> 
> ## The NAMESPACE file
> * [ ]  NOTE: Selective imports using `importFrom` instead of _import all_ with `import`.
>   
>   * in line 17 import(GenomicRanges)
>   * in line 18 import(S4Vectors)
>   * in line 19 import(grDevices)
>
>  _These have been changed to importFrom()_
> 
> ## R code
> * [ ]  NOTE: `::` is not suggested in source code unless you can make sure all the packages are imported. Some people think it is better to keep `::`. However please note that you need to manully double check the import items when you make any change in the DESCRIPTION file during development. My recommendation is to remove one or two repeats to force the dependency check.
>
> _I prefer to keep the `::` notation in the source code because to me it enhances readability. I have checked the imported items and verified their operation._
>
> * [ ]  NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
>   
>   * In file R/degCreConversions.R:
>     
>     * at line 63 found '    for(binIdY in uniqBinIds){'
>
>  _In testing, I found that running this in a for loop was faster than in an *apply function due to the need to assign out of the loop frame._
>
>   * In file R/degCreCore.R:
>     
>     * at line 1346 found '    for (uniqDBinY in uniqDistBinsX) {'
>
>  _This for loop allows for the overwriting of elements in adjRefAssocProbsX as the algorithm steps through distance bins. It would use more resources within an *apply function._
>
>   * In file R/degCrePlotFuns.R:
>     
>     * at line 223 found '    for(i in seq_along(uniqMaxBinDists)){'
>
>  _This has been replaced with an lapply()_
>
> * [ ]  Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.
>   
>   * In file R/degCreConversions.R:
>     
>     * at line 280 found '        keepHitsMcolsDf <- hitsMcolsDf[,c(seq_len(4),seq(from=8,to=10))]'
>     * at line 282 found '        outDf <- data.frame(keepDegDfx[,seq_len(4)],'
>     * at line 283 found '            keepCreDfx[,seq_len(4)],'
>     * at line 285 found '            keepDegDfx[,seq(from=5,to=ncol(keepDegDfx))],'
>     * at line 286 found '            keepCreDfx[,seq(from=5,to=ncol(keepCreDfx))])'
>
> _"drop=FALSE" has been added to each of these lines_
>
>   * In file R/degCreCore.R:
>     
>     * at line 323 found '    sortPromCreHitsDf <- promCreHitsDf[order(promCreHitsDf$assocDist),]'
>     * at line 455 found '    allDistBinsStatsMat <- cbind(allDistBinsStatsMat[,1],'
>     * at line 456 found '        allAssocProbFDR,allDistBinsStatsMat[,2:ncol(allDistBinsStatsMat)])'
>     * at line 462 found '    sortPromCreHitsStatsDf <- data.frame(sortPromCreHitsDf[,seq_len(3)],'
>     * at line 487 found '    mcolsHitsDf <- sortPromCreHitsStatsDf[,3:ncol(sortPromCreHitsStatsDf)]'
>     * at line 1242 found '  totalObs <- nrow(hitsWithDistDf[subHitsIndex,])'
>
> _"drop=FALSE" has been added to each of these lines_
>
>   * In file R/degCrePerDegFuns.R:
>     
>     * at line 125 found '    uniqGeneDegMcolsDf <- allDegGRMcolsDf[uniqGeneIndices,]'
>     * at line 237 found '        expectAssocPerDegDf[which(!is.na(rawExpectAssocs)),]'
>
> _"drop=FALSE" has been added to each of these lines_
>
> * [ ]  NOTE: Try to check the edge condition when using `seq.int` or `seq_len`. For example using `seq.int(min(5, nrow(data)))` to replace `seq.int(5)`
>   
>   * In file R/degCreConversions.R:
>     
>     * at line 264 found '        keepDegDfx <- keepDegDfx[,c(seq_len(3),'
>     * at line 272 found '        keepCreDfx <- keepCreDfx[,c(seq_len(3),'
>     * at line 280 found '        keepHitsMcolsDf <- hitsMcolsDf[,c(seq_len(4),seq(from=8,to=10))]'
>     * at line 282 found '        outDf <- data.frame(keepDegDfx[,seq_len(4)],'
>     * at line 283 found '            keepCreDfx[,seq_len(4)],'
>
> _These are all instances in which subsets of the data.frames are being kept and thus requires hard subset indices to achieve the end goal._
>
>   * In file R/degCreCore.R:
>     
>     * at line 462 found '    sortPromCreHitsStatsDf <- data.frame(sortPromCreHitsDf[,seq_len(3)],'
>     * at line 685 found '        outList <- listX[seq_len(5)]'
>
> _Again, these are instances where the subsetting must occur over a specified range._
>
> * [ ]  NOTE: Functional programming: code repetition.
>   
>   * repetition in `convertDegCreDataFrame` and `convertdegCreResListToGInteraction`
>     
>     * in convertDegCreDataFrame
>       
>       * line 2:{
>       * line 3:    DegGRX <- degCreResList$DegGR
>       * line 4:    CreGRX <- degCreResList$CreGR
>       * line 5:    degCreHits <- degCreResList$degCreHits
>       * line 6:    maskPassAlpha <- which(mcols(degCreHits)$assocProbFDR <=
>       * line 7:        assocAlpha)
>       * line 8:    if (length(maskPassAlpha) < 1) {
>       * line 9:        warning("No associations FDRs pass alpha.")
>       * line 10:        outDf <- NA
>       * line 11:    }
>       * line 12:    else {
>       * line 13:        keepDegCreHits <- degCreHits[maskPassAlpha]
>     * in convertdegCreResListToGInteraction
>       
>       * line 2:    {
>       * line 3:        DegGRX <- degCreResList$DegGR
>       * line 4:        CreGRX <- degCreResList$CreGR
>       * line 5:        degCreHits <- degCreResList$degCreHits
>       * line 6:        maskPassAlpha <- which(mcols(degCreHits)$assocProbFDR <=
>       * line 7:            assocAlpha)
>       * line 8:        if (length(maskPassAlpha) < 1) {
>       * line 9:            warning("No associations FDRs pass alpha.")
>       * line 10:            outGInter <- NA
>       * line 11:        }
>       * line 12:        else {
>       * line 13:            keepDegCreHits <- degCreHits[maskPassAlpha]
> 
> _Both of these functions start by subsetting the Hits object on assocProbFDR. The same code is optimal for both. This only happens in these two instances so I did not feel it worth writing a separate function._
>
> ## Documentation
> * [ ]  Note: Vignette should use `BiocStyle` package for formatting.
>
>   * rmd file vignettes/degcre_introduction_and_examples.Rmd
>   
>  _The BiocStyle package has been incorporated for the vignetter formatting._
>
> * [ ]  Important: Vignette should have an _Installation_ section.
>   
>   * rmd file vignettes/degcre_introduction_and_examples.Rmd
>
> _An Installation section has been added_
>
> * [ ]  Important: Please include Bioconductor installation instructions using BiocManager.
>   
>   * rmd file vignettes/degcre_introduction_and_examples.Rmd
>
> _The Installation section includes instructions for installation with BiocManager._

**Comment by jianhong** [comment]
# Package 'DegCre' Review
It is almost there. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.

## The DESCRIPTION file
- [ ] Important: Update R version dependency from 4.3.3 to 4.4.0.

## Namespace
- [ ] Note: Consider adding
  importFrom("grDevices", "col2rgb", "rgb")
  importFrom("utils", "head", "tail")

## Documentation
- [ ] Important: Multiple typos. Should `/link` be `\link` ?
- [ ] Important: Installation session should not contain the line 28 `BiocManager::install(version = "3.18")` in vignettes `degcre_introduction_and_examples.Rmd`. In the description, please remove the `version 3.18 (R version 4.3)`.

**Comment by brianSroberts** [comment]
> # Package 'DegCre' Review
> It is almost there. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review. Code: Note: please consider; Important: must be addressed.
> 
> ## The DESCRIPTION file
> * [ ]  Important: Update R version dependency from 4.3.3 to 4.4.0.
>
> _I have made this change to R 4.4.0_
> 
> ## Namespace
> * [ ]  Note: Consider adding
>   importFrom("grDevices", "col2rgb", "rgb")
>   importFrom("utils", "head", "tail")
>
> _These importFrom calls have been added._
> 
> ## Documentation
> * [ ]  Important: Multiple typos. Should `/link` be `\link` ?
>
> _These typos have been fixed._
>
> * [ ]  Important: Installation session should not contain the line 28 `BiocManager::install(version = "3.18")` in vignettes `degcre_introduction_and_examples.Rmd`. In the description, please remove the `version 3.18 (R version 4.3)`.
>
>  _This change has been made._

**Comment by jwokaty** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/brianSroberts.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DegCre")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DegCre

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
