### ISSUE TITLE
cypress

### ISSUE THREAD

**Issue by renlyly** [Bioconductor/Contributions#3272]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/renlyly/cypress

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
You should not be referencing `biocLite.R`. This is a very old way of installing Bioconductor packages that is no longer endorsed. Please use `BiocManager`.

**Comment by renlyly** [comment]
Dear Ishep,
Following your advice, we have removed any comments that might have referenced bioLite, to avoid any confusion. Please take a moment to review the updated version.

**Comment by renlyly** [comment]
Hi @lshep,

**Comment by renlyly** [comment]
> You should not be referencing `biocLite.R`. This is a very old way of installing Bioconductor packages that is no longer endorsed. Please use `BiocManager`.

Hi @lshep,
We have removed any comments that might have referenced bioLite, to avoid any confusion.

**Comment by renlyly** [comment]
Hi @lshep,
We have solved the error and warning in the latest version.

Thank you very much for your time and assistance.

**Comment by HelenaLC** [comment]
# misc

- [ ] in the DESCRIPTION, please update R version dependency from 4.3.0 to 4.4.0

- [ ] I greatly encourage you to expand on unit tests (`devtools::test_coverage()` shows me only plotting functions are being tested at all right now; >85% of code is not)

# code

- [ ] I'd highly recommend implementing minimal validity checks on arguments when functions expect a specific type of input, e.g., argument 1 should be of class X with data A and B available, argument 2 should be a scalar integer etc. - these help avoid confusing errors to the user when a function fails downstream.

- [ ] `@` should never be used for data accession; for any exported classes, please implement respective generics and methods (see [here](https://contributions.bioconductor.org/r-code.html?q=s4#class-development) for details)

- [ ] custom classes should at least come with a validity method that verifies slots are of appropriate format/structure/content etc.

- [ ] related to these two previous comments; I don't quite see why implementing S4 classes that merely contain as series of numeric/characters/matrices/`data.frame`s is the way to go here. I feel that either 1) there should be a more compact show method, appropriate accessor and replacement methods, validity methods etc. or 2) remove these classes and all associated code completely in favor of 3 helper functions that validate inputs/outputs are of the desired format (names and contents matching). In the context of this package, I feel that implementing classes properly provides more work than benefit; up to you! But if you chose 1), the Bioc guidelines for class developement need to be addressed.

# documentation

- [ ] consider adding a package man page with an overview of the package and links to the main functions; users should be able to have a relevant page display with `?cypress`

- [ ] in the README, please add Bioc installation instructions using `BiocManager::install()`

- [ ] `data/` contains 7 .rds files, however, their documentation isn't findable directly except for 2 (those related to GSE60424); please add corresponding aliases (e.g., the *asdPower.Rd* should link to `?quickPowerIBD`)

# vignette

- [ ] in the vignette, `eval=FALSE` flags are generally not permitted; I see 2 un-evaluated chunks (besides installation and loading the vignette) - please let these run, remove them, or (rarely applicable) justify why they cannot be evaluated (see [here](https://contributions.bioconductor.org/docs.html#vignettes) for details)

- [ ] vignette writing: please have this proof-read for typos and grammar; I'm seeing a lot of mistakes that impede readability... e.g.,
  - there are a LOT of missing spaces between letters and commas/parentheses/colons 
  - I'm thinking "Statistical Power, TDR, and FDC" at line 123+ shouldn't use code-style as these are not R-related?
  - line 74: "Unlike the ``simFromData`` function needs to provide a real data, [...]" is not a sentence; maybe "requires a real dataset as input"?
  - line 104: coulumn -> column
  - line 111: "3 real data" doesn't work; should be "datasets" or "data examples"; also, "for estimate" -> "for estimating"
  - line 138: "Unlike ``simFromData()`` which need user to provide" doesn't work; could say "which requires users to"; "`sim_param` have" -> "has"
  - line 149: "runs fastest than" -> "runs faster"
  - etc.

**Comment by HelenaLC** [comment]
Just to note that I'm still seeing things that are missing from the points raised previously; please respond to the comments above when ready so I can get a feel for what's been addressed - thanks!

**Comment by renlyly** [comment]
Hi @HelenaLC,

I've sent a push on git.bioconductor.org to check the time-consuming aspects. I will notify you immediately once we have addressed all the points raised in the comments. Thank you very much for your time and assistance.

Shilin

**Comment by renlyly** [comment]
Hi @HelenaLC , we have addressed all your questions in our updated version. Please see below for a point-by-point response to your questions: /

> # misc
> * [ ]  in the DESCRIPTION, please update R version dependency from 4.3.0 to 4.4.0
**Response**: In our DESCRIPTION, we have set 'Depends: R(>= 4.3.0)'. We encountered a problem because the latest version of R for macOS, R 4.3.2 "Eye Holes", was released on 2023/10/31. If we update the dependency from 4.3.0 to 4.4.0, we will not be able to check our package.
> * [ ]  I greatly encourage you to expand on unit tests (`devtools::test_coverage()` shows me only plotting functions are being tested at all right now; >85% of code is not)
**Response**: Thanks for the suggestion. We have exported a total of 6 functions: 3 plot functions, 2 simulation functions, and one quick power function. Currently, all six functions are being tested. 
> # code
> * [ ]  I'd highly recommend implementing minimal validity checks on arguments when functions expect a specific type of input, e.g., argument 1 should be of class X with data A and B available, argument 2 should be a scalar integer etc. - these help avoid confusing errors to the user when a function fails downstream.
**Response**: Thanks for the suggestion. All 6 exported functions have been equipped with sufficient validity checks on arguments. Please review.
> * [ ]  `@` should never be used for data accession; for any exported classes, please implement respective generics and methods (see [here](https://contributions.bioconductor.org/r-code.html?q=s4#class-development) for details)
**Response**: Thanks for pointing this out. Currently, our code does not use @ for data accession; we have adopted alternative methods instead. We also update the methods. The @ is only present in commented-out code.
> * [ ]  custom classes should at least come with a validity method that verifies slots are of appropriate format/structure/content etc.
**Response**: Thanks for the suggestion. We export two classes, both supplemented with a validity method. we have also added a .rd file for classes and methods.
> * [ ]  related to these two previous comments; I don't quite see why implementing S4 classes that merely contain as series of numeric/characters/matrices/`data.frame`s is the way to go here. I feel that either 1) there should be a more compact show method, appropriate accessor and replacement methods, validity methods etc. or 2) remove these classes and all associated code completely in favor of 3 helper functions that validate inputs/outputs are of the desired format (names and contents matching). In the context of this package, I feel that implementing classes properly provides more work than benefit; up to you! But if you chose 1), the Bioc guidelines for class developement need to be addressed.
**Response**: Thank you for your advice. We have now implemented a more compact show method. Both classes come with a validity method in Allclasses.R. The structure of the result is currently what our package expects

> # documentation
> * [ ]  consider adding a package man page with an overview of the package and links to the main functions; users should be able to have a relevant page display with `?cypress`
**Response:** Thanks for the suggestion. We have added a new package man page. We also added some details. Please review.
> * [ ]  in the README, please add Bioc installation instructions using `BiocManager::install()`
**Response:** Thanks for the suggestion. This section has been added, please check.
> * [ ]  `data/` contains 7 .rds files, however, their documentation isn't findable directly except for 2 (those related to GSE60424); please add corresponding aliases (e.g., the _asdPower.Rd_ should link to `?quickPowerIBD`)
**Response**: Thanks for the suggestion. Now all rd files have been updated. The rd. files related to data are aliases to both dataset names and rda file names.
> # vignette
> * [ ]  in the vignette, `eval=FALSE` flags are generally not permitted; I see 2 un-evaluated chunks (besides installation and loading the vignette) - please let these run, remove them, or (rarely applicable) justify why they cannot be evaluated (see [here](https://contributions.bioconductor.org/docs.html#vignettes) for details)
**Response**: Thanks for the suggestion. This issue has been addressed.
> * [ ]  vignette writing: please have this proof-read for typos and grammar; I'm seeing a lot of mistakes that impede readability... e.g.,
**Response**: Thank you so much for the suggestion. We have made lots of revisions to the vignette content, including typos and grammar corrections. We have also reviewed the use of space requirements.

Shilin

**Comment by renlyly** [comment]
Hi @HelenaLC , we have addressed all your questions in our updated version. Please see below for a point-by-point response to your questions: 

> # misc
>  in the DESCRIPTION, please update R version dependency from 4.3.0 to 4.4.0

**Response**: In our DESCRIPTION, we have set 'Depends: R(>= 4.3.0)'. We encountered a problem because the latest version of R for macOS, R 4.3.2 "Eye Holes", was released on 2023/10/31. If we update the dependency from 4.3.0 to 4.4.0, we will not be able to check our package.

>  I greatly encourage you to expand on unit tests (devtools::test_coverage() shows me only plotting functions are being tested at all right now; >85% of code is not)

**Response**: Thanks for the suggestion. We have exported a total of 6 functions: 3 plot functions, 2 simulation functions, and one quick power function. Currently, all six functions are being tested.
code
 

> I'd highly recommend implementing minimal validity checks on arguments when functions expect a specific type of input, e.g., argument 1 should be of class X with data A and B available, argument 2 should be a scalar integer etc. - these help avoid confusing errors to the user when a function fails downstream.

**Response**: Thanks for the suggestion. All 6 exported functions have been equipped with sufficient validity checks on arguments. Please review.

 

> @ should never be used for data accession; for any exported classes, please implement respective generics and methods (see [here](https://contributions.bioconductor.org/r-code.html?q=s4#class-development) for details)

**Response**: Thanks for pointing this out. Currently, our code does not use @ for data accession; we have adopted alternative methods instead. We also update the methods. The @ is only present in commented-out code.

> Custom classes should at least come with a validity method that verifies slots are of appropriate format/structure/content etc.

**Response**: Thanks for the suggestion. We export two classes, both supplemented with a validity method. we have also added a .rd file for classes and methods.

> 
>  related to these two previous comments; I don't quite see why implementing S4 classes that merely contain as series of numeric/characters/matrices/data.frames is the way to go here. I feel that either 1) there should be a more compact show method, appropriate accessor and replacement methods, validity methods etc. or 2) remove these classes and all associated code completely in favor of 3 helper functions that validate inputs/outputs are of the desired format (names and contents matching). In the context of this package, I feel that implementing classes properly provides more work than benefit; up to you! But if you chose 1), the Bioc guidelines for class developement need to be addressed.

**Response**: Thank you for your advice. We have now implemented a more compact show method. Both classes come with a validity method in Allclasses.R. The structure of the result is currently what our package expects

> # documentation
>  consider adding a package man page with an overview of the package and links to the main functions; users should be able to have a relevant page display with ?cypress

**Response**: Thanks for the suggestion. We have added a new package man page. We also added some details. Please review.

 

> in the README, please add Bioc installation instructions using BiocManager::install()

**Response**: Thanks for the suggestion. This section has been added, please check.

>  data/ contains 7 .rds files, however, their documentation isn't findable directly except for 2 (those related to GSE60424); please add corresponding aliases (e.g., the asdPower.Rd should link to ?quickPowerIBD)

**Response**: Thanks for the suggestion. Now all rd files have been updated. The rd. files related to data are aliases to both dataset names and rda file names.

> # vignette
>  in the vignette, eval=FALSE flags are generally not permitted; I see 2 un-evaluated chunks (besides installation and loading the vignette) - please let these run, remove them, or (rarely applicable) justify why they cannot be evaluated (see [here](https://contributions.bioconductor.org/docs.html#vignettes) for details)

**Response**: Thanks for the suggestion. This issue has been addressed.

> vignette writing: please have this proof-read for typos and grammar; I'm seeing a lot of mistakes that impede readability... e.g.,

**Response**: Thank you so much for the suggestion. We have made lots of revisions to the vignette content, including typos and grammar corrections. We have also reviewed the use of space requirements.

Shilin

**Comment by HelenaLC** [comment]
- [ ] please remove any commented out code that is no-longer in use; see [this note](https://contributions.bioconductor.org/r-code.html?q=comment#rcode-comments) on comments
- [ ] regarding R version dependency: I see, though this is something you need to fix on your end (I am running Bioc 3.19 w/ R 4.4 without issues). Note that the package will be part of Bioc 3.19+, which will not be installable under R 4.3 in any case; so I'd suggest finding a way to write and test your package under the version it'll run under: 4.4
- [ ] I still see `eval=FALSE` in the vignette chunk at line 62+; similarly, the `simFromData` example is currently wrapped in `\donttest{}`; hence the build report `NOTE: consider adding runnable examples to man pages that document exported objects`; so it looks like you are suppressing `simFromData()` in both the example and vignette - please address this.
- [ ] if I'm not mistaken, you replaced `@` accession with `slot()`, which is pretty much the same; my previous comment had suggested to either remove the implementation of a class altogether, or implement proper *accessor and replacement methods* - please address this (again, see [this section](https://contributions.bioconductor.org/r-code.html?q=s4#class-design) on class design).
- [ ] the `cypress_out` validity method currently only validates all slots are `data.frame`s, which will hold true by definition via `setClass`; instead, it should verify the `data.frame`s are in line with the desired structure, i.e., dimension, column names and contents.
  - related to the two previous comments: (though this will not be one-to-one applicable) for a comprehensive example of how to implement an S4 class properly in the context simulation, you could check out [`splatter`](https://github.com/Oshlack/splatter/tree/220606e0959847eba843b1382bbc9cdfff301571/R) (e.g., *SimpleParams-methods.R*)

**Comment by renlyly** [comment]
Dear @HelenaLC ,

Thank you very much for your valuable suggestions. Here are the updates I’ve made based on your feedback:
1. I have made modifications to the comments on the guidelines in section 15.2.7.3.
2. The simFromData() function appears twice in the vignette. I’ve set eval=FALSE for its first occurrence at line 62+ to avoid lengthy processing times. The repetition of simulation and power evaluation is time-consuming. We set eval=TRUE in the latest version without any new warnings and errors.
3. We decided to use \donttest{} for the same reason—repeated simulation and power evaluation takes a considerable amount of time, and we wish to prevent warnings related to execution times exceeding 10 minutes.
4. I greatly appreciate your advice and examples concerning the S4 class. The new S4 class code should now meet the necessary requirements. Key updates include:
  I. Added accessor and replacement methods, with the required SetGenerics and rd. file.
  II. Updated the output functions to ensure there’s no use of slots or ‘@’ outside of accessor functions.
  III. Implemented validity checks for dimensions and names as required.

I hope these adjustments address your concerns satisfactorily.
Best regards,
Shilin

**Comment by HelenaLC** [comment]
Thanks for all this, getting real close I think... hopefully last round of comments:
- I believe the *simFromParam.Rd* and *quickPower.Rd* man pages have some syntax issues that result in faulty formatting (see NOTES in the build report and, e.g., `?quickPower`)
- There are still some `@`s left in *inst/unitTests/test_cypress.R* (fyi, you can use shift+command+F to search the entire package)
- The DESCRIPTION contains a couple syntax (missing/too many spaces), phrasing and grammar mistakes; please revise (e.g., A cell type on AN, input of A SE object not THE, to identify differentialLY expressed genes -> common abbreviation for that is DEGs/never seen csDE)
- The generics defined in *cypress-methods.R* should go under *AllGenerics.R*
- I noticed an instance of `bplapply` in `cypress_wrapper()`; it'd make sense to expose an argument to the user that would enable controlling how to perform parallelizatio, e.g., an argument `BPPARAM` in the function definition that is passed to the `bplapply` call; otherwise users need to be familiar with how to registed a backend with `bpparam()`, which is rather less obvious than passing a parameter imo. (also: still some commented out code here.)

**Comment by renlyly** [comment]
Dear @HelenaLC ,
Thank you again for your constructive feedback. Below are the modifications I've implemented in response to your input:

> •I believe the simFromParam.Rd and quickPower.Rd man pages have some syntax issues that result in faulty formatting (see NOTES in the build report and, e.g., ?quickPower)

A: Thank you for your suggestion. We have revised the syntax issues for Rd. files

> •There are still some @s left in inst/unitTests/test_cypress.R (fyi, you can use shift+command+F to search the entire package)

A: Thank you for your suggestion. We have corrected the @s in unitTests.

> •The DESCRIPTION contains a couple syntax (missing/too many spaces), phrasing and grammar mistakes; please revise (e.g., A cell type on AN, input of A SE object not THE, to identify differentialLY expressed genes -> common abbreviation for that is DEGs/never seen csDE)	

A: We have re-examined the syntax issues in the DESCRIPTION. Regarding the use of the abbreviation csDE, csDE is our research focus, not the DEG. We would like to retain it.

> •The generics defined in cypress-methods.R should go under AllGenerics.R

A: Thanks for the suggestion. We have rectified this issue.

> •I noticed an instance of bplapply in cypress_wrapper(); it'd make sense to expose an argument to the user that would enable controlling how to perform parallelizatio, e.g., an argument BPPARAM in the function definition that is passed to the bplapply call; otherwise users need to be familiar with how to registed a backend with bpparam(), which is rather less obvious than passing a parameter imo. (also: still some commented out code here.)

A: Thank you for your suggestion. We've removed unnecessary code. Regarding bpparam(), we have added related functions.

Shilin

**Comment by HelenaLC** [comment]
Alright, thanks for these modifications - that's all clear now. I noticed one last thing I'd like to be resolved before acceptance, and apologies for missing this earlier as I am more used to `roxygen`-based documentation... 

Looking at the NAMESPACE, you should use `importFrom()` in all but rare cases (see [here](https://contributions.bioconductor.org/namespace.html?q=importfrom#imported-functions) for details) - for 2/3 dependencies, the entire package is currently being imported.

**Comment by renlyly** [comment]
Dear @HelenaLC,

Thank you very much for your guidance and patience. In the recent update, I made the necessary adjustments for the dependencies as advised and ensured it aligns better with practices.

Thank you again for your valuable feedback.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/renlyly.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cypress")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cypress

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
