### ISSUE TITLE
spoon

### ISSUE THREAD

**Issue by kinnaryshah** [Bioconductor/Contributions#3278]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kinnaryshah/spoon

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by kinnaryshah** [comment]
I see that the error is: 

* ERROR: Subscribe to the Bioc-devel mailing list by going to
      https://stat.ethz.ch/mailman/listinfo/bioc-devel

I have already subscribed to this mailing list using the same email in the DESCRIPTION file. Thanks!

**Comment by lshep** [comment]
Have you checked spam or filters?  There is confirmation email that gets sent that sometimes is marked as spam

**Comment by kinnaryshah** [comment]
Thank you! I was able to confirm my subscription.

**Comment by jianhong** [comment]
@kinnaryshah Please fix the warning `Running testthat.R WARNING: R CMD check exceeded 10 min requirement` before I start a review. Thank you.

**Comment by kinnaryshah** [comment]
Thank you for the reminder, @jianhong. 

I see the CheckTime with nebbiolo1 is 7 minutes, but the CheckTime with merida1 is 15 minutes, which exceeds the 10 minute maximum. On my local machine (macOS Ventura Version 13.2.1), the CheckTime is 3 minutes. I'm not sure how to address this warning. Are there substantial environmental differences or constraints between the two environments?

**Comment by jianhong** [comment]
# Package 'spoon' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. It is in pretty good shape. However there are several things need to be fixed. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.

## The DESCRIPTION file
- [ ] Important: `Depends` field is not found in DESCRIPTION.
- [ ] Important: R version is not clear in DESCRIPTION.

## The NAMESPACE file
- [ ] Important: Selective imports using `importFrom` instead of *import all* with `import`.
	* in line 3 import(BRISC)
	* in line 4 import(BiocParallel)
	* in line 5 import(Matrix)
	* in line 6 import(SpatialExperiment)
	* in line 7 import(nnSVG)
	* in line 8 import(purrr)
	* in line 9 import(scuttle)
       
## R code
- [ ] Important: `warning`, `message`, `stop` instead of `cat` and `print` outside of `show` methods.
	* In file R/utils.R:
		+ at line 13 found '    cat("ERROR :",conditionMessage(e), "\n")'
		+ at line 33 found '    cat("ERROR :",conditionMessage(e), "\n")'
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/generate_weights.R:
		+ at line 217 found '    for (i in seq_len(nrow(lambda_hat))) {'
		+ at line 218 found '      for (j in seq_len(ncol(lambda_hat))) {'
- [ ] Important: Remove unused code.
	* In file R/generate_weights.R:
		+ at line 133 found '  #ix <- c(1,2,3)'
- [ ] NOTE: Avoid 'suppressWarnings'/'*Messages' if possible
	* In file R/generate_weights.R:
		+ at line 137 found '    suppressWarnings({'
- [ ] Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.
	* In file R/generate_weights.R:
		+ at line 162 found '  s_g <- unname(as.data.frame(mat_brisc[,2])) |>'
- [ ] NOTE: Functional programming: code repetition.
	* repetition in `generate_weights` and `weighted_nnSVG`
		+ in generate_weights
			- line 3:{
			- line 4:    if (is(input, "SpatialExperiment")) {
			- line 5:        spe <- input
			- line 6:        stopifnot(assay_name %in% assayNames(spe))
			- line 7:    }
			- line 8:    if (is.null(BPPARAM)) {
			- line 9:        BPPARAM <- MulticoreParam(workers = n_threads)
			- line 10:    }
			- line 11:    if (is(input, "SpatialExperiment")) {
		+ in weighted_nnSVG
			- line 6:    if (n_threads > 1) {
			- line 7:        BPPARAM <- MulticoreParam(workers = n_threads)
			- line 8:    }
			- line 9:    if (is(input, "SpatialExperiment")) {
			- line 10:        spe <- input
			- line 11:        stopifnot(assay_name %in% assayNames(spe))
			- line 12:    }
	* repetition in `weighted_nnSVG_calc_mat` and `weighted_nnSVG_calc_spe`
		+ in weighted_nnSVG_calc_mat
			- line 9:        }, error = function(e) {
			- line 10:            cat("ERROR :", conditionMessage(e), "\n")
			- line 11:            list(weighted_LR_stat = NA, weighted_sigma.sq = NA, 
			- line 12:                weighted_tau.sq = NA, weighted_prop_sv = NA)
			- line 13:        })
			- line 14:        return(res)
		+ in weighted_nnSVG_calc_spe
			- line 10:        }, error = function(e) {
			- line 11:            cat("ERROR :", conditionMessage(e), "\n")
			- line 12:            list(weighted_LR_stat = NA, weighted_sigma.sq = NA, 
			- line 13:                weighted_tau.sq = NA, weighted_prop_sv = NA)
			- line 14:        })
			- line 15:        return(res)
## Documentation
- [ ] Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
	* rmd file vignettes/spoon.Rmd

## Other stuff not related to the code review
I noticed that you are using '|>' in source and '%>%' in vignette for pipe operation. Very interesting.

**Comment by kinnaryshah** [comment]
Thank you @jianhong for your thorough review! I've addressed my changes below:


 ## The DESCRIPTION file
 * [x]  Important: `Depends` field is not found in DESCRIPTION.
 _This has been added_
 * [x]  Important: R version is not clear in DESCRIPTION.
  _This has been added in the `Depends` field_

 ## The NAMESPACE file
 * [x]  Important: Selective imports using `importFrom` instead of _import all_ with `import`.
   * in line 3 import(BRISC)
   _added `BRISC_order`, `BRISC_neighbor`, `BRISC_estimation`, `BRISC_prediction`_
   * in line 4 import(BiocParallel)
   _added `bplapply`, `MulticoreParam`_
   * in line 5 import(Matrix)
   _added `rowMeans`_
   * in line 6 import(SpatialExperiment)
   _added `spatialCoords`_
   * in line 7 import(nnSVG)
   _added `nnSVG`, `filter_genes`_
   * in line 8 import(purrr)
    _removed, this was not used_
   * in line 9 import(scuttle)
   _added `computeLibraryFactors`, `logNormCounts`_
   
 
 ## R code
 * [x]  Important: `warning`, `message`, `stop` instead of `cat` and `print` outside of `show` methods.

   * In file R/utils.R:
     
     * at line 13 found '    cat("ERROR :",conditionMessage(e), "\n")'
     _replaced with `message`_
     * at line 33 found '    cat("ERROR :",conditionMessage(e), "\n")'
      _replaced with `message`_

 * [x]  NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
   
   * In file R/generate_weights.R:
     
     * at line 217 found '    for (i in seq_len(nrow(lambda_hat))) {'
     * at line 218 found '      for (j in seq_len(ncol(lambda_hat))) {'
_Using the apply functions did not significantly increase the speed. I've kept it as is since it is personally easier to read the nested loop compared to the vectorized version. Please let me know if you have other insights on this!_
 * [x]  Important: Remove unused code.
   
   * In file R/generate_weights.R:
     
     * at line 133 found '  #ix <- c(1,2,3)'
     _removed_

 * [x]  NOTE: Avoid 'suppressWarnings'/'*Messages' if possible
   
   * In file R/generate_weights.R:
     
     * at line 137 found '    suppressWarnings({'
     _this was not removed because it prints out the following warning for each gene:_
`Warning messages:
1: In BRISC_estimation(coords = coords, y = y_i, x = NULL, cov.model = "exponential",  :
  The ordering of inputs x (covariates) and y (response) in BRISC_estimation has been changed BRISC 1.0.0 onwards.
Please check the new documentation with ?BRISC_estimation.
`
 * [x]  Important: Please consider to add `drop=FALSE` to avoid the reduction of dimension for matrices and arrays. Ignore this if using datatable.
   
   * In file R/generate_weights.R:
     
     * at line 162 found '  s_g <- unname(as.data.frame(mat_brisc[,2])) |>'
_this was added to line 162 and 159_
 * [x]  NOTE: Functional programming: code repetition.
   
   * repetition in `generate_weights` and `weighted_nnSVG`
_Checking that the assay is present in both functions is important to stop each function at the start if the assay is not present. The BPPARAM variable needs to be set separately for each function for parallelization. The second `if (is(input, "SpatialExperiment")) {` in `generate_weights` is necessary because the code is different for `SpatialExperiment` object inputs and matrix inputs. I've left the code as is._
     
     * in generate_weights
       
       * line 3:{
       * line 4:    if (is(input, "SpatialExperiment")) {
       * line 5:        spe <- input
       * line 6:        stopifnot(assay_name %in% assayNames(spe))
       * line 7:    }
       * line 8:    if (is.null(BPPARAM)) {
       * line 9:        BPPARAM <- MulticoreParam(workers = n_threads)
       * line 10:    }
       * line 11:    if (is(input, "SpatialExperiment")) {
     * in weighted_nnSVG
       
       * line 6:    if (n_threads > 1) {
       * line 7:        BPPARAM <- MulticoreParam(workers = n_threads)
       * line 8:    }
       * line 9:    if (is(input, "SpatialExperiment")) {
       * line 10:        spe <- input
       * line 11:        stopifnot(assay_name %in% assayNames(spe))
       * line 12:    }
   * repetition in `weighted_nnSVG_calc_mat` and `weighted_nnSVG_calc_spe`
_These are two separate functions: `weighted_nnSVG_calc_mat` is used for matrix inputs and `weighted_nnSVG_calc_spe` is used for `SpatialExperiment` object inputs. I've left the code as is._
     
     * in weighted_nnSVG_calc_mat
       
       * line 9:        }, error = function(e) {
       * line 10:            cat("ERROR :", conditionMessage(e), "\n")
       * line 11:            list(weighted_LR_stat = NA, weighted_sigma.sq = NA,
       * line 12:                weighted_tau.sq = NA, weighted_prop_sv = NA)
       * line 13:        })
       * line 14:        return(res)
     * in weighted_nnSVG_calc_spe
       
       * line 10:        }, error = function(e) {
       * line 11:            cat("ERROR :", conditionMessage(e), "\n")
       * line 12:            list(weighted_LR_stat = NA, weighted_sigma.sq = NA,
       * line 13:                weighted_tau.sq = NA, weighted_prop_sv = NA)
       * line 14:        })
       * line 15:        return(res)
 
 ## Documentation
 * [x]  Note: Vignette includes `motivation for submitting to Bioconductor` as part of the abstract/intro of the main vignette.
   
   * rmd file vignettes/spoon.Rmd
   _motivation added to the vignette_
 
 ## Other stuff not related to the code review
 I noticed that you are using '|>' in source and '%>%' in vignette for pipe operation. Very interesting.

**Comment by kinnaryshah** [comment]
I wanted to note that I attempted three new builds yesterday after pushing all of my changes. All of these builds had the exact same code except for the version number. I was timed out on the merida1 macOS build twice and got a warning that the build was over the allowed check time on the third attempt. The nebbiolo1 build was fine each time. I believe this issue is not unique to this package (based on the recent [Bioc-devel] Check time on macOS (MIRit) email thread). While the linux builds have been satisfactory, I dealt with a similar macOS issue when first submitting my package for review: the first build on macOS took about 15 minutes and the second took 7 minutes despite no changes being made except for triggering a new build report.

**Comment by lshep** [comment]
the macOS has been problematic as of late;  using linux (nebbiolo1) as the standard for judging the timing right now is advised.  I'll kick off a build manually for you to get a new linux result.

**Comment by kinnaryshah** [comment]
thank you, @lshep!

**Comment by jianhong** [comment]
Please update the dependence of R version to 4.4. The only concern is the running time. After update the R version, I will make it as accepted.

**Comment by kinnaryshah** [comment]
Thanks for all of your help and efforts, @jianhong! I've made the change.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kinnaryshah.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("spoon")`. The package 'landing page' will be created at

https://bioconductor.org/packages/spoon

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
