### ISSUE TITLE
Submit CytoMDS package

### ISSUE THREAD

**Issue by phauchamps** [Bioconductor/Contributions#3281]
- Repository: https://github.com/UCLouvain-CBIO/CytoMDS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by phauchamps** [comment]
Hi @DarioS,

Thank you for accepting to review my package :-) 
Since I created the current issue, I added 2 minor versions of the package to my repository (CytoMDS 0..99.8 -> 0.99.10).
Therefore I can now commit the changes also to the Bioconductor devel repo. However, would you like that I keep it as the 0.99.8 version for the time being, while you are reviewing it? Please let me know :-) 

Thank you again, 

Philippe.

**Comment by phauchamps** [comment]
> Hi @DarioS,
> 
> Thank you for accepting to review my package :-) Since I created the current issue, I added 2 minor versions of the package to my repository (CytoMDS 0..99.8 -> 0.99.10). Therefore I can now commit the changes also to the Bioconductor devel repo. However, would you like that I keep it as the 0.99.8 version for the time being, while you are reviewing it? Please let me know :-)
> 
> Thank you again,
> 
> Philippe.

@DarioS : I finally pushed the new version. Incidentally, this also removed the 'warnings' tag (which was due to MacOS build being to long to generate).

**Comment by DarioS** [comment]
Overall, a good submission. A few issues are noted.

- Frequent copy and paste for case of single core processing.

```r
        if (useBiocParallel){
            distribBlockList <- BiocParallel::bplapply(
                blocks1D,
                FUN = loadFFAndCalcHistograms,
                BPPARAM = BPPARAM,
                BPOPTIONS = BPOPTIONS,
                loadFlowFrameFUN = loadFlowFrameFUN,
                loadFlowFrameFUNArgs = loadFlowFrameFUNArgs,
                channels = channels,
                breaks = breaks,
                verbose = verbose)
        } else {
            distribBlockList <- lapply(
                blocks1D,
                FUN = loadFFAndCalcHistograms,
                loadFlowFrameFUN = loadFlowFrameFUN,
                loadFlowFrameFUNArgs = loadFlowFrameFUNArgs,
                channels = channels,
                breaks = breaks, 
                verbose = verbose)
        }
```

For single core mode, please just use `BiocParallel`'s `SerialParam()` and get rid of all instances of code duplication.

- Inefficient unlisting with `for` loop.

```r
        distrs <- list()
        ind <- 0
        for (b in seq_along(blocks1D)) {
            for(i in seq_along(blocks1D[[b]])) {
                ind <- ind+1    
                distrs[[ind]] <- distribBlockList[[b]][[i]]
            }
        }
```

You should use `unlist` with recursive = `FALSE` instead. I show an example.

```r
example <- list(list(LETTERS[1:5], LETTERS[6:10]), list(LETTERS[11:15], LETTERS[16:20]))
unlist(example, recursive = FALSE)
```

- Don't incrementally grow lists. Use vapply or sapply. See [Code Syntax and Efficiency](https://contributions.bioconductor.org/r-code.html?q=vapply#code-syntax-and-efficiency) of developer's guide.

```r
ffList <- list()

for (i in seq_len(nSample)) {
    ffList[[i]] <- CytoPipeline::subsample(
                OMIP021Trans[[(i+1)%%2+1]],
                nEvents = 1000,
                seed = i)
}
```

- Don't just explain what you do, explain _why_ you do it.

> We now create two simulated data sets, of 20 samples each, by combining events  from the two samples of the OMIP021 original data set. 

I don't understand the purpose of this. Why not analyse experimental data?

- `# References {-}`. The references section is empty. Please add content.

- Objects of class `mdsRes` flood the user's R console with output. Class needs a `show` method to display concisely.

```r
> mdsObj1
$eigen
[1] 8.5817848 0.8525102

$pctvar
[1] 0.9096371 0.0903629

$pwDist
         1       2       3       4       5       6       7       8       9      10      11      12
2  1.76925 
3  0.55560 1.89565
4  1.62995 0.50810 1.78135
5  0.66230 2.17985 0.67050 1.95135
6  1.67935 0.58270 1.92735 0.60060 2.06245
7  0.50030 1.63315 0.67890 1.55475 0.97330 1.60175
8  1.76675 0.44360 1.83945 0.54720 2.20845 0.73850 1.58885
9  0.41880 1.96395 0.57090 1.75765 0.45950 1.87115 0.69840 1.95965
10 1.85695 0.43910 2.02975 0.59750 2.26375 0.63130 1.72295 0.49720 2.04465
11 0.59835 1.96950 0.53525 1.84570 0.58575 1.81470 0.77395 2.06530 0.54995 2.05880
12 1.84495 0.41810 1.97165 0.47160 2.19265 0.67420 1.73335 0.47140 1.98555 0.45600 2.04800
13 0.37195 1.78410 0.57005 1.66470 0.63315 1.71360 0.53125 1.81840 0.45605 1.88450 0.56030 1.87010
14 1.90415 0.42710 2.00675 0.62920 2.33165 0.77530 1.73185 0.45170 2.10725 0.37020 2.14030 0.48950 1.92140
15 0.53320 2.02115 0.63020 1.91555 0.51650 1.91265 0.72660 2.07105 0.47270 2.11985 0.45555 2.10775 0.50905 2.20185
                                                   ...                      ...
```

- Vignette needs biological interpretation. What biological insight did CytoMDS help identify? Currently, it reads as a list of functions. What biological conditions are in OMIP-021 and what significant differences between them did CytoMDS reveal?

**Comment by phauchamps** [comment]
Hi Dario, 

Thank you for the insightful comments, and the time spent on reviewing the package code in details.
I agree with all your code related remarks, and will improve the package code accordingly.

Regarding the lack of biological insight in the vignette and the why of the simulated data, I hope to be able to address both concerns in a common way, i.e. by replacing the simulated data by a more representative public dataset for illustration. 

I expect to work on the corrections in the coming days, and be back to you soon.

Best regards,

Philippe

**Comment by phauchamps** [comment]
Hi Dario, 

I have just pushed a new version (*CytoMDS* 0.99.13) which addresses the issues you mentioned. Here below is my 'point by point' answer:

- Frequent copy and paste for case of single core processing  
=> As suggested, I now use `BiocParallel::SerialParam()` as a default for the `BPPARAM` parameter, avoiding code duplication. I also removed `useBiocParallel` parameter from the calculation methods, since it is now redundant :-)  
```
pairwiseEMDDist <- function(
        x,
        rowRange = c(1, nSamples), 
        colRange = c(min(rowRange), nSamples),
        loadFlowFrameFUN = NULL,
        loadFlowFrameFUNArgs = NULL,
        channels = NULL,
        verbose = FALSE,
        BPPARAM = BiocParallel::SerialParam(),
        BPOPTIONS = BiocParallel::bpoptions(
            packages = c("flowCore")),
        binSize = 0.05,
        minRange = -10,
        maxRange = 10
        ){ ... }
```

- Inefficient unlisting with `for` loop. 
=> As suggested, I now use `unlist(recursive=FALSE)` :
```
        ## reorganize multivariate distributions in a single list
        distrs <- unlist(distribBlockList, recursive = FALSE)
```

- Don't incrementally grow lists. Use vapply or sapply. 
=> I refactored the code at several places to implement that suggestion.

- Objects of class `mdsRes` flood the user's R console with output. Class needs a `show` method to display concisely. 
=> I have replaced `mdsRes` class with a `MDS` S4 class, implementing several getters, and also a more concise `show` method :
```
> mdsObj
MDS object containing MDS projection (using Smacof algorithm)  data:
Nb of dimensions:  4 
Nb of points:  16 
Stress:  0.040668 
Pseudo RSquare:  0.981489 
Goodness of fit:  0.998346 
```
- In order to address the lack of biological interpretation in the vignette, I updated it by including a real public mass cytometry dataset (instead of a synthetic dataset based on two samples only). I introduced the dataset by giving a bit of context to the study, and the experimental design. I also added some plot interpretations, seeking biological insight by identifying markers which are diffentially expressed between the two conditions. In order to help with this user task, I also implemented a new method in the package: `ggplotMarginalDensities` which displays selected marker univariate distributions for selected samples, possibly coloured by condition. This new method is also demonstrated in the vignette.

- `# References {-}`. The references section is empty. Please add content.
=> I did not change anything for this. In fact, upon knitting, the `References` section is populated automatically, using the references in the main text of the vignette, and the .bib file stored in the vignette directory.

Best,

Philippe

**Comment by DarioS** [comment]
CytoMDS has been substantially improved. There is just one outstanding issue, though.

- A large fraction of the unnecessary `for` loops that ought to be one of the apply functions remain. For example,

```r
distances <- rep(0., length(channels))
   ...        ...
for (ch in seq_along(channels)) {
        ...                ...        
  distances[ch] <- wasserstein1d(a = locations, wa = wA, b = locations, wb = wB)
}
```

![image](https://github.com/Bioconductor/Contributions/assets/631218/534f9731-bb36-460d-af11-69a3b30c24c6)

Some loops might not be able to be converted into apply, but the majority of the ones I manually inspected can and must be.

**Comment by phauchamps** [comment]
Hi @DarioS,

I have just pushed version 0.99.14 which addresses most of these `for(...)` loops. 
In this latest version, `for(...)` loops are still used at 3 places in the code, where nested loops implement complex relationships between objects of different dimensions (with indices translations) so I think that converting these nested loops into `apply()` family of functions would be at best awkward, if not impossible, and in any case, at the expense of deteriorating the readability of the code. 

Let me know what you think :-) 

Best,

Philippe

**Comment by DarioS** [comment]
Good.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/phauchamps.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CytoMDS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CytoMDS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
