### ISSUE TITLE
SCIntRuler

### ISSUE THREAD

**Issue by yuelyu21** [Bioconductor/Contributions#3295]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/yuelyu21/SCIntRuler

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
A few initial comments 
- [ ] We like to have a clean branch for Bioconductor. Please remove extra files like index.md.  
- [ ] Your man pages for your datasets are lacking; even if they are simulated you should describe the structure and values and not leave placeholder fill in information from a template.  
- [ ] Please also include a package level man page so a naive user has some starting point from `?SCIntRuler` .  
- [ ] You have a figures directory in your man pages and in inst and in vignettes (inst/figures); you'll like want to include as one directory like `inst/extdata` that can then be referenced throughout.  
- [ ] You also have no tests written but have included a test directory. Please make relevant tests. 
- [ ] Please also include a section in the vignette that is similar to an abstract describing why you are submitting the package to bioconductor and a comparison to an existing Bioconductor packages. 
- [ ] **Important**  This package is for single cell data but you currently do not integrate at all with Bioconductor infrastructure and classes for Single cell data.  Please update the package to also integrate minimally with SingleCellExperiment.

**Comment by lshep** [comment]
may we expect updates to address the above concerns?

**Comment by yuelyu21** [comment]
Hello Bioconductor Team,

I am writing to kindly request the reopening of my package submission issue. Over the past few weeks, I have addressed all the concerns raised during the initial review. Here are the specific changes and updates I've implemented:

1. **Code Improvements**: I have refined the codebase for better performance and compliance with Bioconductor standards, ensuring that all functions are properly documented and efficient.
2. **Error Handling**: Enhanced error handling across the package to provide clearer, more informative error messages to the users.
3. **Vignettes and Documentation**: Updated and expanded the vignettes to provide more comprehensive usage examples and scenarios. Also, the documentation has been thoroughly revised for clarity and completeness.
4. **R CMD Check and BiocCheck**: The package now passes `R CMD check` and `BiocCheck` with no errors, warnings.
5. **Active Maintenance Commitment**: I am fully committed to the ongoing maintenance of the package, including timely updates for compatibility with new R and Bioconductor releases, and prompt responses to community feedback and issues.

I appreciate your consideration and am looking forward to continuing the submission process. Thank you for your time and support.

Best regards,
Yue Lyu

**Comment by lshep** [comment]
You left some place holder sections that should be cleaned up like

```
\description{
A short description of your dataset.
}
```

Also when I try to R CMD build the package I get the following 
```
Quitting from lines  at lines 286-295 [step 1] (SCIntRuler.Rmd)
Error: processing vignette 'SCIntRuler.Rmd' failed with diagnostics:
object 'onep_internal' not found
--- failed re-building ‘SCIntRuler.Rmd’

SUMMARY: processing the following file failed:
  ‘SCIntRuler.Rmd’

Error: Vignette re-building failed.
Execution halted

```

**Comment by yuelyu21** [comment]
Hi, I have added some description for the dataset and also rebuilt the Vignette. I believe there should no errors now. Thanks!

**Comment by lshep** [comment]
There is still this:
```
man/sim_result.Rd:23:A short description of your dataset.
```

And please run R CMD build, R CMD check and R CMD BiocCheck.  There are still ERROR when running checks.

**Comment by yuelyu21** [comment]
Dear Bioconductor Core Team, thanks for pointting out  the errors. Here, I first tried `devtools::check()`, it returns no error. 
<img width="267" alt="image" src="https://github.com/Bioconductor/Contributions/assets/70731028/7a3f80f8-ff09-440b-bcda-68b62ff7bddd">
I then tried `R CMD CHECK`, status show "OK".
<img width="304" alt="image" src="https://github.com/Bioconductor/Contributions/assets/70731028/a48d686d-bd22-417d-97ac-54fc39289db8">
`BiocCheck` also gives no error no warning: 
<img width="300" alt="image" src="https://github.com/Bioconductor/Contributions/assets/70731028/bdb2a946-eacd-4ff3-887f-db7059a81ff3">
I believe now the package is ready to be checked again.
Thanks for all your patience!

**Comment by lshep** [comment]
I am still getting an error in your tests when I test locally with R 4.40 Patched (2024-04-30 r86503) and Bioc 3.20.   I'll move this forward but if the builds pick up this error as well it will need to be corrected before a reviewer is assigned to the package. 
```
> sim_data <- SCEtoSeurat(sim_data_sce)
Error in cbind(seurat[["RNA"]]@meta.features, gene_metadata) : 
  no slot of name "meta.features" for this object of class "Assay5"
Calls: SCEtoSeurat -> cbind

```

**Comment by lshep** [comment]
I am still getting an error in your tests when I test locally with R 4.40 Patched (2024-04-30 r86503) and Bioc 3.20.   I'll move this forward but if the builds pick up this error as well it will need to be corrected before a reviewer is assigned to the package.
```
> sim_data <- SCEtoSeurat(sim_data_sce)
Error in cbind(seurat[["RNA"]]@meta.features, gene_metadata) :
  no slot of name "meta.features" for this object of class "Assay5"
Calls: SCEtoSeurat -> cbind
```

**Comment by yuelyu21** [comment]
Dear Bioconductor Core Team, I fixed this issue and tries `check_win_devel()` function, which will build and check my package in a devel version of R on Win system. I got `NO ERROR`, `NO WARNING`. Here is the log. 
* using log directory 'd:/RCompile/CRANguest/R-devel/SCIntRuler.Rcheck'
* using R Under development (unstable) (2024-05-28 r86639 ucrt)
* using platform: x86_64-w64-mingw32
* R was compiled by
    gcc.exe (GCC) 13.2.0
    GNU Fortran (GCC) 13.2.0
* running under: Windows Server 2022 x64 (build 20348)
* using session charset: UTF-8
* checking for file 'SCIntRuler/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'SCIntRuler' version '0.99.0'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Yue Lyu <yuelyu0521@gmail.com>'

New submission

Possibly misspelled words in DESCRIPTION:
  SCIntRuler (8:377)
  scRNA (8:55, 8:474)
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'SCIntRuler' can be installed ... OK
* used C++ compiler: 'g++.exe (GCC) 13.2.0'
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking code files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... [11s] OK
* checking whether the package can be loaded with stated dependencies ... [12s] OK
* checking whether the package can be unloaded cleanly ... [11s] OK
* checking whether the namespace can be loaded with stated dependencies ... [11s] OK
* checking whether the namespace can be unloaded cleanly ... [12s] OK
* checking loading without being on the library search path ... [12s] OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... [50s] OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking LazyData ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compilation flags used ... OK
* checking compiled code ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ... [38s] OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ... [27s] OK
  Running 'testthat.R' [27s]
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... OK
* checking re-building of vignette outputs ... [64s] OK
* checking PDF version of manual ... [28s] OK
* checking HTML version of manual ... OK
* DONE

**Comment by yuelyu21** [comment]
Hey Bioconductor team, should I expect a build report to be posted here?

**Comment by lshep** [comment]
there should have I'll investigate why.

**Comment by lshep** [comment]
```
cat 00install.out 
* installing *source* package ‘SCIntRuler’ ...
** using staged installation
** libs
using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
g++ -std=gnu++17 -shared -L/home/biocbuild/bbs-3.20-bioc/R/lib -L/usr/local/lib -o SCIntRuler.so RcppExports.o crossdist.o -L/home/biocbuild/bbs-3.20-bioc/R/lib -lR
RcppExports.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
make: *** [/home/biocbuild/bbs-3.20-bioc/R/share/make/shlib.mk:10: SCIntRuler.so] Error 1
ERROR: compilation failed for package ‘SCIntRuler’
* removing ‘/home/pkgbuild/packagebuilder/workers/jobs/3295/R-libs/SCIntRuler’
```

**Comment by yuelyu21** [comment]
Hi Bioconductor Team, I have deleted thoese files `SCIntRuler.so` `RcppExports.o` `crossdist.o` in my repo. It should work now. Thanks for all the support and patientce!

**Comment by lshep** [comment]
Please push to git.bioconductor.org to trigger a new build

**Comment by yuelyu21** [comment]
Hi Marcel, please let me know if you have any questions, comments and suggestions!

**Comment by yuelyu21** [comment]
@LiNk-NY , Could I kindly ask if it would be possible to expect some comments this week or next week?

**Comment by LiNk-NY** [comment]
Hi @yuelyu21 
Apologies for the delay. I was away last week for a conference. I will provide a review today. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Hi @yuelyu21 
Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# SCIntRuler #3295

The package makes use of the `Seurat` representation and does not integrate
with Bioconductor other than providing a serialized `SummarizedExperiment`
dataset and conversion functions from SCE to Seurat.  Please re-evaluate the
need for a Bioconductor submission.

## DESCRIPTION

* The import of `devtools` looks questionable. Otherwise, it looks good.

## NAMESPACE

* Remove `exportPattern` function call.
* Consider using the native pipe `|>` rather than `magrittr::'%>%'`

## vignette

* Add a more descriptive `VignetteIndexEntry`
* Optional. Consider wrapping text to 80 character width for readability.
* Use `eval=FALSE` for the Installation code chunk and uncomment code.
* No need to explicitly install dependencies in the Installation code chunk.
They will be installed along with your package.
* Remove the `devtools` reference.
* Load the data with `data("sim_data_sce", package = "SCIntRuler")` and avoid
`SCIntRuler::sim_data_sce`
* Remove commented code.
* Run spell check on the vignette.

**Comment by yuelyu21** [comment]
Dear Marcel, @LiNk-NY 

Thank you for your detailed and constructive feedback on the SCIntRuler package. I appreciate your time and effort in reviewing it and providing suggestions for improvement.

SCIntRuler was developed with the aim of providing a user-friendly tool for single-cell RNA-seq data integration, leveraging the popularity and functionality of Seurat. While I acknowledge that the current version primarily uses Seurat and includes conversion functions from SingleCellExperiment (SCE) to Seurat, I believe there is potential for this package to serve as a bridge between the Seurat and Bioconductor ecosystems.

I plan to include additional functionalities that operate directly on SummarizedExperiment and SingleCellExperiment objects, thus reducing dependency on Seurat. I am eager to **continue developing** the package to better align with Bioconductor’s standards and would greatly appreciate the opportunity to do so as part of the Bioconductor project.

**Response to Specific Comments:**

DESCRIPTION:

I removed the import of devtools as it is not essential for the package's functionality.
NAMESPACE:

I removed the exportPattern function call.
I considered using the native pipe |> rather than magrittr::'%>%' in the next update.
Vignette:

I added a more descriptive VignetteIndexEntry.
I used eval=FALSE for the Installation code chunk and uncomment the code.
I removed the explicit installation of dependencies from the Installation code chunk, as they will be installed along with the package.
I emoved the reference to devtools.
I loaded the data with data("sim_data_sce", package = "SCIntRuler") to avoid using SCIntRuler::sim_data_sce.
I ran a spell check on the vignette to ensure there are no spelling errors.


Thank you for considering my response. I look forward to your feedback and guidance on how I can further improve SCIntRuler to meet Bioconductor's expectations.

Best regards,
Yue

**Comment by yuelyu21** [comment]
@LiNk-NY ,Dear Marcel, Could I kindly ask if it would be possible to expect some comments this week?

**Comment by LiNk-NY** [comment]
Hi @yuelyu21 

Thank you for following up and apologies for the delay. 

The package is good to go as-is if you submit to CRAN, however, 
for the benefit of **Bioconductor** users,  we would rather accept a 
package that makes use of Bioconductor data structures. 

We thank you for your submission and patience. Feel free to open
the issue once you have carefully considered the needs of the 
Bioconductor user base. 

Best regards,
Marcel

cc: @vjcitn

**Comment by yuelyu21** [comment]
@LiNk-NY , Dear Marcel,

Thank you for your feedback on my package submission. I understand the importance of integrating Bioconductor data structures to better serve the Bioconductor user base.

My package is designed to use the Seurat package for its primary functionality and includes a function to convert SingleCellExperiment objects to Seurat objects. Given this dependency on Seurat, I have concerns about further modifying the package to align more closely with Bioconductor data structures without compromising its core functionality.

Could you please clarify if the current integration with Seurat and the conversion function are sufficient for consideration, or does this feedback mean that my package cannot be accepted by Bioconductor as it stands?

I appreciate your guidance and look forward to your response.

**Comment by vjcitn** [comment]
Dear @yuelyu21 -- we have been discussing your submission which is nicely done, I like the pkgdown site and the narration.  I think it is important that you are interfacing to scanorama and harmony in this package.   Yours seems to be the only one working with scanorama; a few others use harmony (see https://code.bioconductor.org/search/search?q=harmony).  Because you have concerns about modifying the package to use Bioconductor data structures, and focus on Seurat structures, with Seurat on CRAN, it does seem natural for your package to be on CRAN too.  Our ecosystem is striving for convenience to users and developers through direct reuse of established and essentially stable data structures like SingleCellExperiment.  We are hitting resource limits for reviewing and QCing packages and so we would ask that if you want to have the package in Bioconductor, you enhance the direct interfaces to Bioc data structures like SingleCellExperiment.  Thanks!

**Comment by yuelyu21** [comment]
Dear Dr. Carey @vjcitn ,

Thank you very much for your feedback and kind words about my package submission. I appreciate the valuable comments and suggestions regarding interfacing with scanorama and harmony, and the importance of integrating Bioconductor data structures.

Given your advice and considering the natural fit of my package with Seurat on CRAN, I have decided to proceed with submitting my package to CRAN. I will certainly take your suggestions into account for future enhancements, especially regarding the integration with Bioconductor data structures.

Thank you again for your support and guidance.

Best,
Yue Lyu
