### ISSUE TITLE
SpotSweeper

### ISSUE THREAD

**Issue by MicTott** [Bioconductor/Contributions#3310]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MicTott/SpotSweeper

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lazappi** [comment]
Hi @MicTott

Thanks for submitting **SpotSweeper** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: Please review the notes from `BiocCheck::BiocCheck()` in the build report and address as many as possible

## DESCRIPTION file

- [ ] :rotating_light: The `Title` field should be a one line description of the package, not just the package name
- [ ] :green_circle: After you update `Title` you may want to consider expanding`Description` which can be a short paragraph
- [ ] :rotating_light: Bioconductor recommends setting `LazyData: False`
- [ ] :rotating_light: The R dependency for the next release should be `R (>= 4.4.0)`

## NAMESPACE file

- [ ] :warning: The naming of `modified_z` is different to the other functions, I can see why but maybe think about if you can make them consistent
- [ ] :warning: You use `import()` for some packages, please consider if this is necessary or if you can use `importFrom()` instead (especially for **{MASS}**)

## The NEWS file

- [ ] :rotating_light: Please add at least one entry to the `NEWS` file (and ideally keep it up to date as you make changes)

## The CITATION file

- [ ] :warning: Currently you have a TODO for the bioRxiv citation, I would suggest removing this until it is available to avoid confusing users

## Package data

- [ ] :green_circle: The included data file is ok according to the checks but you may be able to reduce the size by using compression (if you haven't already)

## Documentation

### README

- [ ] :green_circle: If you want to include text that is formatted as code but isn't meant to be run you can use ```` ```r ```` without the `{}` instead of setting `eval=FALSE`
- [ ] :green_circle: I think there are some examples here that aren't included in the vignette, you may want to consider adding/moving them there

### Vignette

- [ ] :rotating_light: Please use the `BiocStyle` package for formatting
- [ ] :rotating_light: Please include a table of contents
- [ ] :rotating_light: The vignette should have an *Introduction* section that includes motivation for inclusion in Bioconductor and comparison to similar packages (if applicable)
- [ ] :rotating_light: The vignetted should have an *Installation* section that uses Bioconductor installation instructions (NOT evaluated)
- [ ] :warning: The vignette is quite limited. Please consider expanding it to cover more of the functionality of the package including things like how to set parameters and interpret output.
- [ ] :green_circle: There is no need for `eval = requireNamespace('SpotSweeper')`, the pacakge will always be available when the vignette is being built

### Man pages

- [ ] :green_circle: It is recommended to add a package man page

## Unit tests

- [ ] :rotating_light: Please add some unit tests to cover a large part of the core functionality

## Code

### R

- [ ] :rotating_light: Please use `seq_along()`/`seq_len()` instead of `1:...`
- [ ] :warning: Some code is repeated across the functions (such as selecting features), consider moving this to another function and resuing it
- [ ] :warning: Consider adding for validity checks for function arguments
- [ ] :rotating_light: Please check if any `for` loops can be replaced with `apply()` functions. Where possible, any `for` loops that are kept should pre-allocate space for results rather than growing an object inside the loop.
- [ ] :rotating_light: Rather than an argument for the number of cores you should have a `BPPARAM` argument that accepts a `BiocParallel` object. The default should be `bpparam()` or `SerialParam()`.
- [ ] :green_circle: I think you should be able to just use `"k18"` rather than `paste0("k", 18)`

### Third-party code

- [ ] :rotating_light: Please make sure you have followed the license for code included from other packages

**Comment by MicTott** [comment]
Hi @lazappi 

Thanks so much for the feedback! Please see below where I've made all of the changes, the 🚨 Required and ⚠️ Recommended items with [-] were removed (e.g., `modified_z` replaced with `spatialEco::outliers`, removed `BiocParallel`). 

Please let me know if there is anything to fix before this upcoming BioC release. 

All the best,
Michael

> Hi @MicTott
> 
> Thanks for submitting **SpotSweeper** 🎉! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.
> 
> **What next?**
> 
> Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.
> 
> Luke
> 
> # Review
> **Key:** 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question
> 
> ## General package development
> * [X]  ⚠️ Please review the notes from `BiocCheck::BiocCheck()` in the build report and address as many as possibl
> 
> ## DESCRIPTION file
> * [X]  🚨 The `Title` field should be a one line description of the package, not just the package name
> * [X]  🟢 After you update `Title` you may want to consider expanding`Description` which can be a short paragraph
> * [X]  🚨 Bioconductor recommends setting `LazyData: False`
> * [X]  🚨 The R dependency for the next release should be `R (>= 4.4.0)`
> 
> ## NAMESPACE file
> * [-]  ⚠️ The naming of `modified_z` is different to the other functions, I can see why but maybe think about if you can make them consistent
> * [X]  ⚠️ You use `import()` for some packages, please consider if this is necessary or if you can use `importFrom()` instead (especially for **{MASS}**)
> 
> ## The NEWS file
> * [X]  🚨 Please add at least one entry to the `NEWS` file (and ideally keep it up to date as you make changes)
> 
> ## The CITATION file
> * [X]  ⚠️ Currently you have a TODO for the bioRxiv citation, I would suggest removing this until it is available to avoid confusing users
> 
> ## Package data
> * [-]  🟢 The included data file is ok according to the checks but you may be able to reduce the size by using compression (if you haven't already)
> 
> ## Documentation
> ### README
> * [X]  🟢 If you want to include text that is formatted as code but isn't meant to be run you can use `` ```r `` without the `{}` instead of setting `eval=FALSE`
> * [X]  🟢 I think there are some examples here that aren't included in the vignette, you may want to consider adding/moving them there
> 
> ### Vignette
> * [X]  🚨 Please use the `BiocStyle` package for formatting
> * [X]  🚨 Please include a table of contents
> * [X]  🚨 The vignette should have an _Introduction_ section that includes motivation for inclusion in Bioconductor and comparison to similar packages (if applicable)
> * [X]  🚨 The vignetted should have an _Installation_ section that uses Bioconductor installation instructions (NOT evaluated)
> * [X]  ⚠️ The vignette is quite limited. Please consider expanding it to cover more of the functionality of the package including things like how to set parameters and interpret output.
> * [X]  🟢 There is no need for `eval = requireNamespace('SpotSweeper')`, the pacakge will always be available when the vignette is being built
> 
> ### Man pages
> * [-]  🟢 It is recommended to add a package man page
> 
> ## Unit tests
> * [X]  🚨 Please add some unit tests to cover a large part of the core functionality
> 
> ## Code
> ### R
> * [X]  🚨 Please use `seq_along()`/`seq_len()` instead of `1:...`
> * [-]  ⚠️ Some code is repeated across the functions (such as selecting features), consider moving this to another function and resuing it
> * [X]  ⚠️ Consider adding for validity checks for function arguments
> * [X]  🚨 Please check if any `for` loops can be replaced with `apply()` functions. Where possible, any `for` loops that are kept should pre-allocate space for results rather than growing an object inside the loop.
> * [-]  🚨 Rather than an argument for the number of cores you should have a `BPPARAM` argument that accepts a `BiocParallel` object. The default should be `bpparam()` or `SerialParam()`.
> * [X]  🟢 I think you should be able to just use `"k18"` rather than `paste0("k", 18)`
> 
> ### Third-party code
> * [-]  🚨 Please make sure you have followed the license for code included from other packages

**Comment by lazappi** [comment]
> > * [x]   🚨 The vignetted should have an _Installation_ section that uses Bioconductor installation instructions (NOT evaluated)

You can write this section as though the package has been accepted so you don't need to update it after the package becomes available.

> > * [-]  🚨 Rather than an argument for the number of cores you should have a `BPPARAM` argument that accepts a `BiocParallel` object. The default should be `bpparam()` or `SerialParam()`.

Can you please explain why you decided to remove it? I guess you didn't need to do things in parallel?

> > * [-]  🚨 Please make sure you have followed the license for code included from other packages

Can you please explain your response to this? I'm not sure if you didn't need to make any changes or if you removed the code from other packages?

Otherwise I am happy with the changes so should be able to accept this after you respond to these questions.

**Comment by MicTott** [comment]
Hi @lazappi,

> You can write this section as though the package has been accepted so you don't need to update it after the package
becomes available.

Done.

> Can you please explain why you decided to remove it? I guess you didn't need to do things in parallel?

Yes the method currently is very quick, even on large datasets. And the speed improvement from parallelization was minor, so I've just removed it for now. I may add it back in later if needed.

> Can you please explain your response to this? I'm not sure if you didn't need to make any changes or if you removed the code from other packages?

Sorry for the confusion - the only code I used from a different package was `spatialEco::outliers` where I directly copied it to the function `SpotSweeper::modified_z`. At the time, the package had been taken off CRAN and was unable to be imported. Since then the authors have updated the package so that it's back on CRAN. So I chose to remove the `SpotSweeper::modified_z` and instead just directly use `spatialEco::outliers`. Hopefully that makes sense to you. 

Thanks again for the feedback! Please let me know if there is anything else.

**Comment by lazappi** [comment]
Ok, I'm happy with this. I will mark it as approved.

**Comment by lazappi** [comment]
Congratulations on getting **{SpotSweeper}** accepted into Bioconductor 🎉! It can take a few days to be picked up by the build system but then it will be available in Bioconductor devel and next release.

**Comment by MicTott** [comment]
Thank you for all your careful feedback @lazappi! Have a wonderful day.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MicTott.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SpotSweeper")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SpotSweeper

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
