### ISSUE TITLE
CaMutQC

### ISSUE THREAD

**Issue by Wangxin555** [Bioconductor/Contributions#3312]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/likelet/CaMutQC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Wangxin555** [comment]
Hello,

I just made some modifications and the latest version of CaMutQC should be 0.99.3 now.

**Comment by Wangxin555** [comment]
**Update: Solevd!**
---------------------------------------------------------------------------------------------------------

Hello, @lshep 
I ran into a problem when pushing to upstream, and don't know what to do:

```Administrator@CHINAMI-7A2TBAP MINGW64 /e/GitRepo/CaMutQC (master)
$ git fetch --all
Fetching origin
Fetching upstream
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: could not fetch upstream
```

I am sure that I have added public ssh keys to Github, but I don't know why this problem happens.
Could you provide any help?

**Comment by Wangxin555** [comment]
Hi, @lshep 
I have question about the size limitation of Bioc packages.
Now there is only one ERROR in the build report, saying `Package tarball exceeds the Bioconductor size requirement`. But as it shows in the report, the package size is **4984.42 [KiB]**, which is smaller than 5Mb. So why am I getting this error?
Thank you!

**Comment by DarioS** [comment]
CaMutQC provides a comprehensive set of functions for filtering variants. I noted some coding and documentation issues.

- The package has widespread use of `for` loops. [Bioconductor expects vapply or mapply](https://contributions.bioconductor.org/r-code.html#code-syntax-and-efficiency).
- Inconsistent use of white space around operators. Refer to [Use of Space](https://contributions.bioconductor.org/r-code.html#use-of-space).
```r
TSL=getValue(CSQ_info$TSL),HGVS_OFFSET = getValue(CSQ_info$HGVS_OFFSET),
PHENO = getValue(CSQ_info$PHENO), MINIMISED = '', 
gnomAD_AF = getgnomInfo(CSQ_info, fieldName = "AF"),
```
- User inputs are not checked. Use `is(inputData, "c;lass")` to check user input data is correct class.
- Inconsistent use of `camelCase` and `snake_case` naming. [Bioconductor requires snakeCase](https://contributions.bioconductor.org/r-code.html#variable-names).
- A vignette should have an installation section near the top of it. Also, should have BiocStyle. See [Vignettes](https://contributions.bioconductor.org/docs.html#vignettes). Also, the vignette shows a series of outputs but there is no interpretation sentence after each output. Explain what each output means, don't just show a result and start a new section without interpreting it.
- Panel of Normals filtration only works for human genomes. That seems overly restricted.
```r
else if (!(genomeVersion %in% c('GRCh38', 'GRCh37'))){
        stop('Invaild genome version.')
```
- Duplication of functionality. There is a `readBed` function but Biocoductor already has a function in [rtracklayer](https://bioconductor.org/packages/release/bioc/html/rtracklayer.html) to do that.
```r
# read and validate bed file / bed data frame or bed rds
readBed <- function(bedVar, bedHeader = FALSE) {
    ...        ...
```
Similarly, `readINFO` seems redundant to Bioconductor's [VariantAnnotation](https://bioconductor.org/packages/release/bioc/html/VariantAnnotation.html) package for importing VCF files. Please improve,

**Comment by Wangxin555** [comment]
Hi @DarioS 
Thank you for your suggestions, and we are addressing them.
I have a few confusions so far:
* In the Bioc contribution manual at [here](https://contributions.bioconductor.org/r-code.html#variable-names), it says Bioc prefers camelCase but not snakeCase, so we should use camelCase right? Also, I often use lowerCamelCase (first word in lower case, first letter of proceeding words is an uppercase letter), is that ok?
* Because we now only focus on the quality control of **human** cancer somatic mutations, we only consider human genomes for PON files, and I just added a message to notice users. We may support more species in the future. Hope this addresses the 6th point you mentioned.
* I fail to find a `readBed` function in package `rtracklayer`. But despite we have `readBed` and `readInfo` functions that might be similar to some functions in other packages, they are **inner functions**, which means they are not exported and users are not able to access them directly. I think it is ok to keep them for now, but I might be wrong, so please correct me if I am wrong.

Thank you!

**Comment by DarioS** [comment]
Yes, lowerCamelCase for variables, UpperCamelCase for class definitions. Thanks for clarifying species. See [import](https://rdrr.io/bioc/rtracklayer/man/BEDFile-class.html) e.g. `import("example.bed")`. Avoiding duplication of existing functionality and increasing use of core infrastructure is important.

**Comment by Wangxin555** [comment]
Hi, @DarioS 
I have addressed the issues you mentioned:
1. **for loops**: I replace more than 10 for loops by `apply` or `vapply`, and now there are only about 3 loops in the code of this package.
2. **Inconsistent use of white space around operators**: I did a thorough code review on CaMutQC and fixed all inconsistences I could find. Please notify if you find some that I haven't fixed.
3. **User inputs are not checked**: I added code to check the class of `maf` at the begining of every filtration function.
4. **Inconsistent use of camelCase and snake_case naming**: Now the name of variables and function are all in camelCase.
5. **A vignette should have an installation section near the top of it**: The vignette has been updated and changed to BiocStyle.
6. **Duplication of functionality**: I read the code of `readBed` function in other packages and found that there actually are differences between it and the `readBed` in CaMutQC, for example, the `readBed` in CaMutQC can read `rds` files, or bed files with header, which cannot be achieved by other `readBed` functions. Similar for `readInfo`, `readINFO` in CaMutQC enables the extraction of more information. In addition, due to the special structure of CaMutQC and the functions and features it has, relying on other internal functions may lead to issues in future updates. Therefore, I think it is necessary to implement private inner functions like `readbed` and `readINFO` in CaMutQC. But still, we are open to suggestions and comments.

Thanks!

**Comment by DarioS** [comment]
Well done.

**Comment by Wangxin555** [comment]
Hi, @DarioS 
Thank you so much for your comments and updates.
It is OK now if I update CaMutQC a little by adding some messages for users?

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Wangxin555.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CaMutQC")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CaMutQC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
