### ISSUE TITLE
funomics package

### ISSUE THREAD

**Issue by elisagdelope** [Bioconductor/Contributions#3322]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/elisagdelope/funOmics

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Please make sure R CMD build,  R CMD check, and BiocCheck can run on your package without ERROR.   Your package currently can not be built as it is missing a NAMESPACE file. 

Could you please provide an abstract/intro section in your vignette that provides motivation for inclusion in Bioconductor and when appropriate a review and comparison to existing Bioconductor packages with similar functionality or scope. It will also be important to show interoperability with some of the standard Bioconductor classes for pathway analysis and gene sets like KEGGREST, Gostats, BiocSet/GSEAset, etc.  See also [common classes](http://contributions.bioconductor.org/important-bioconductor-package-development-features.html#reusebioc) or [results of pathway biocview](https://bioconductor.org/packages/release/BiocViews.html#___Pathways)

**Comment by elisagdelope** [comment]
Thanks for the revision. The NAMESPACE was not in the repository because it was mistakenly included in the .gitignore file, I already fixed it. The R CMD build, check and BiocCheck are passed smoothly. I have updated the intro section in the vignette with a motivation and comparison with existing Bioconductor packages. 

As for the interoperability, the inputs for the package are essentially an omics data matrix or dataframe and the molecular sets in the format of a list of lists. This list of lists is a generic format, not tied to any particular package or class and can be obtained by processing the downloads from https://data.broadinstitute.org/gsea-msigdb/msigdb/release/ or https://mips.helmholtz-muenchen.de/corum/#download/ as described in the vignette section "Real data: Where to find molecular sets?".  To better clarify, I added to the vignette both an example of how to read the downloads from those sources to get a list of lists containing pathways and molecules (e.g. genes), and another code snippet for how to retrieve pathway gene sets as a list of lists from KEGGREST, but the idea is that the user uses their preferred source of molecular sets as desired for their analyses and these are just some examples. 

Regarding GOstats or GSEAset, these packages do not align with the current scenario because they are meant to test enrichment and thus require a "universe of genes". Please note that enrichment is not the purpose of funomics package. 

All changes have been uploaded to the repository linked in this issue.

**Comment by vjcitn** [comment]
Thanks for this submission.  I understand that the package code handles data matrices or data frames and lists of lists.  So we have, in the vignette, 
```
X <- matrix(abs(rnorm(g * s)), nrow = g, dimnames = list(paste0("g", 1:g), paste0("s", 1:s)))
pathways <- as.list(sample(10:100, size = 100, replace = TRUE))
pathways <- lapply(pathways, function(s, g) paste0("g", sample(1:g, size = s, replace = FALSE)), g)
names(pathways) <- paste0("pathway", seq_along(pathways))
print(paste("Dimensions of omics matrix X:", dim(X)[1], "*", dim(X)[2], "; Length of molecular sets list:", length(pathways)))
```
The aim of Bioconductor data structure designs is to hide the complexity of code like this.  The
omics data matrix should be part of a SummarizedExperiment in which omic features and sample characteristics
are well-annotated and bound together.  Methods on SummarizedExperiments support high-level expression
of filtering on features or sample characteristics.  If you don't wish to use SummarizedExperiments or interoperate
with other Bioconductor components, please explain further in this issue.

**Comment by elisagdelope** [comment]
Thanks a lot for your revision and comment. This code from the vignette corresponds to the generation of simulated data: A matrix X of omics abundance (e.g., gene counts) is generated, as well as a list of lists containing the genes involved in pathways. I think this code would not be less complex if using a SummarizedExperiment object instead of a matrix and a list of lists. The main value of SummarizedExperiment is to have sample annotations and the counts matrix in the same object, as you mention indeed. However, in the context of this package, the pathway information is independent of sample-specific annotations typically stored in the colData slot of a SummarizedExperiment object (e.g., treatment, diagnosis). The focus in the vignette is on demonstrating the core functionalities of `funomics` for pathway-level aggregation, and sample annotations are not essential for this purpose.

More importantly, the pathway list of lists contains information about the molecular sets and their constituent molecules (e.g., gene IDs), and is typically downloaded or obtained from external sources (as described in the vignette, there is a section on this, and how to integrate programatically with KEGGREST), hence a separate list aligns well with how pathway information is often obtained in practice, beyond the simulated pathway list in the vignette.

Therefore, a data matrix/dataframe and a separate list of molecular sets provides flexibility to work with various data formats, such as for users whose data does not necessarily come from a SummarizedExperiment object. Note that if the actual data is in `SummarizedExperiment` format, the assay matrix can easily be retrieved (`assay(SEobject)`) to be used as input for `funomics`. I added a comment on this in the vignette to cover this case. 

I've also updated the repository with a slight change in the package name (funomics -> funOmics). Please, let me know how i should proceed.

**Comment by vjcitn** [comment]
You are correct on all counts.  But the [contribution guidelines](https://contributions.bioconductor.org/bioconductor-package-submissions.html#subintro) are clear: Interoperate with other Bioconductor packages by re-using common data structures (see [Common Bioconductor Methods and Classes](https://contributions.bioconductor.org/important-bioconductor-package-development-features.html#reusebioc)) and existing infrastructure (e.g., rtracklayer::import() for input of common genomic files).  I get that you are reluctant to do this, and you explain that users who already have SummarizedExperiment or gene set data structures can disassemble them to use your package.  The "ecosystem" and "interoperability" concepts are somewhat vague, but wouldn't your package be appropriate for CRAN?  We have limited review resources and since you are not going to use Bioconductor data structures to any advantage, it would be better if our reviewers could pass on this one.  Close the issue if you agree.  Thanks again.

**Comment by elisagdelope** [comment]
Thank you for your feedback. I understand and appreciate the emphasis on Bioconductor contribution guidelines. While I initially considered CRAN due to the package's flexibility in handling diverse data formats, I've been advised and encouraged that 'funomics' core functionality of aggregating omics data into pathway-level features aligns better with Bioconductor's focus.

The package funomics interoperates with the Bioconductor ecosystem in several ways. It leverages KEGGREST for retrieving pathway information, a common Bioconductor package for accessing KEGG resources. Additionally, funomics potentially complements packages like pathifier by offering alternative functionalities for pathway-level aggregation (e.g., user-defined pooling operators). Indeed, funomics package provides a kind of wrapper for the pathifier function "quantify_pathways_deregulation". I've also realized pathifier package performs somewhat similar operations, and does not require input from SummarizedExperiments object, hence I guess it is not a strict requirement?

Nevertheless I understand the benefits of SummarizedExperiment for data management. Disassembling and reassembling SummarizedExperiment objects within funomics could be technically feasible, and I'm not reluctant to work on this, but it introduces unnecessary complexity (at this stage, this would artificially force the package to use it without real necessity). However, I'm open to exploring ways to integrate SummarizedExperiment or other Bioconductor structures in future versions of the package based on specific use cases and user feedback where using it provides added value to their analyses (this is why I point to the use of github issues to suggest improvements). 

Given funomics' focus on functional-level omics data aggregation and its interoperability with Bioconductor packages, I believe it can still be a valuable addition to the bioconductor repository and community even if at this stage, it does not take SummarizedExperiments objects as input. It operates with other packages, demonstrates utility in the field, and can also interact with the assay slot of SummarizedExperiments objects, so it's compatible with bioconductor structures. 

I'm happy to discuss this further and address any additional questions you might have. If absolutely required, as mentioned I can artifically force funomics to take SummarizedExperiment object as input, disassembling it internally, and assembling a SummarizedExperiment as an output, but I believe doing this just for the sake of using this class is not necessarily a good practice.

**Comment by vjcitn** [comment]
Thank you.  The only "necessity" I am thinking of at this point is fairness.  Many developers of packages in the ecosystem took the time to achieve interoperability and did not get reviewed until this was accomplished.  I think your package has to meet the same standard.  Please revise.

**Comment by elisagdelope** [comment]
Hi, I'm not sure I follow your last comment. I pointed some examples in which funomics package interacts with other packages of the bioconductor ecosystem, hence the intereoperability. I also pointed an example bioconductor package using omics data where SummarizedExperiment in particular is not used. Most importantly, I explained why using SummarizedExperiment input does not add much value at this stage, indeed if only SummarizedExperiment structures are accepted as input, it would limit its flexibility and restrict its use to this specific data format, which is not necessarily the data format all potential users of funomics implement. 

Then, I don't really understand what is the requirement that is missing for the package to move forward. Are there alternative ways funomics can demonstrate interoperability with the Bioconductor ecosystem beyond SummarizedExperiment integration?  or can you elaborate on how this SummarizedExperiment integration could make sense given the functionality and current structure of the package?

**Comment by lshep** [comment]
I would argue then show an example using one of the many available SummarizedExperiment objects rather than a toss away comment in the vignette as a potential extension of the "real work" example in the vignette.  There are many predefined SummarizedExperiments provided in packages and in the ExpeirmentHub.  

 Also, the work around I generally suggest for people that have extensively coded out generalized structures rather than Bioconductor structures, if their documentation and vignette are thorough and code fairly sound and they argue its not as much value,  is to create wrapper function around Bioconductor objects therefore simply adding a secondary function specific for the Bioconductor class structure; or simply check for the input to a function and if its a SummarizedExperiment (`inherits()` or `is()`) parse out what is needed by your functions internally.   Is there a way to do this so both are implemented?  

Similarly you use KEGGREST (which is good)  but then there is a complicated looping section to force it into your structure. 
```
kegg_sets <- list()
for (i in seq(1, length(pathway_ids), by = batch_size)) {
  batch_ids <- pathway_ids[i:(min(i + batch_size - 1, length(pathway_ids)))]
  batch_objs <- keggGet(batch_ids)
  for (obj in batch_objs) {
    if ("GENE" %in% names(obj)) {
      entrez_id_indices <- seq(1, length(obj$GENE), by = 2) # Extract Entrez IDs (odd entries)
      entrez_ids <- obj$GENE[entrez_id_indices]
      kegg_sets[[obj$PATHWAY_MAP[[1]]]] <- entrez_ids
}}}
``` 
As Vince said above, this is the complexity we like to try to minimize for users.  Where we would suggest again, a function that would take care of this formatting for a user.  

We will move this into the next stage of review but would expect some additional work to make it easier for end users.

**Comment by lshep** [comment]
As far as the renaming,  the DESCRIPTION and the repo must match exactly including capitalization.  Please also rename the repo and update the url in the first comment.

**Comment by lshep** [comment]
I think this has to do with the change of capitalization. I thought it would work to just update. I'll look into it more this weekend and get back to you on if we can change it on our end or what steps to take next.

**Comment by lshep** [comment]
I think everything is straightened out. You should receive a new report shortly

**Comment by elisagdelope** [comment]
Thanks both for your comments and understanding: 

- I will show an example using one SummarizedExperiment object from ExpeirmentHub in the vignette. 

- I will wrap the code for getting kegg pathways from KEGGREST in a list of lists format into a function.

- I will revise if/how to better integrate a SummarziedExperiment as input (and then I guess output as well). - this might take some more time tho.

Since there is this "abnormality", just to avoid messing the bioconductor git I will keep updating my personal repo ( https://github.com/elisagdelope/funOmics) until you let me know about next steps.

**Comment by elisagdelope** [comment]
> Thanks both for your comments and understanding:
> 
> * I will show an example using one SummarizedExperiment object from ExpeirmentHub in the vignette.
> * I will wrap the code for getting kegg pathways from KEGGREST in a list of lists format into a function.
> * I will revise if/how to better integrate a SummarziedExperiment as input (and then I guess output as well). - this might take some more time tho.
> 
> Since there is this "abnormality", just to avoid messing the bioconductor git I will keep updating my personal repo ( https://github.com/elisagdelope/funOmics) until you let me know about next steps.

An example using the SummarizedExperiment object from airway data and a new function get_kegg_sets() to retrieve pathway gene sets from KEGG have been implemented. Since SummarizedExperiment assays must be of the same dimensions, and `funOmics` reduces the dimensions (in particular, the number of features) of the omics matrix, the vignette extends the example usage for the airway SummarizedExperiment object to interact with another bioconductor package, `MultiAssayExperiment`, that provides a structure similar to SummarizedExperiment but allowing to include the information in airway as well as the summarized data matrix provided by `funOmics`. 

I think the vignette is now more complete, and shows effectively how `funOmics` can be integrated in different workflows and analyses, while still being flexible for various data formats. 

Re the "abnormal" label, it seems like it still assigns it when I push.

**Comment by lshep** [comment]
I'll check why the abnormal tag is still being added but it looks like it was resolved since you pushed and received a build report so please continue to do so.

**Comment by elisagdelope** [comment]
Thanks, from the report I see this note "License stub is invalid DCF." and I don't really understand what is to be done here, as I do have the MIT license file in the repository, and it is indicated in the DESCRIPTION file. 

Regarding the 'suppressWarnings'/'*Messages' if possible (found 2 times), I have used it on suppressMessages(AnnotationDbi::mapIds function()) that is used internally in get_kegg_sets() function to avoid displaying messages coming from a gene id internal mapping that could confound the user (as those messages are not related to the core purpose of get_kegg_sets(), and are not always shown, only if using homo sapiens samples). I think having them displayed is quite unclear in the context of get_kegg_sets, hence the suppressMessages.

Please let me know about these, and if there's anything else that needs to be addressed.

**Comment by elisagdelope** [comment]
Hi, I addressed the concerns on interoperability and added a function to get KEGG sets as suggested. The package build without warnings/errors. Are there any updates on the package revision?

**Comment by vjcitn** [comment]
There will be.  Feel free to make further improvements.

**Comment by vjcitn** [comment]
Early in the vignette we have
```
# Example usage:
set.seed(1)
g <- 10000
s <- 20
X <- matrix(abs(rnorm(g * s)), nrow = g, dimnames = list(paste0("g", 1:g), paste0("s", 1:s)))
pathways <- as.list(sample(10:100, size = 100, replace = TRUE))
pathways <- lapply(pathways, function(s, g) paste0("g", sample(1:g, size = s, replace = FALSE)), g)
names(pathways) <- paste0("pathway", seq_along(pathways))
print(paste("Dimensions of omics matrix X:", dim(X)[1], "*", dim(X)[2], "; Length of molecular sets list:", length(pathways)))
```

I commented previously that code like this in a vignette is unwelcome.  Later in the vignette you
illustrate with airway dataset.  This should be moved up as it is potentially biologically meaningful;
the example with simulation is not.

The vignette mentions 

> `funOmics` accommodates various omics modalities (e.g., metabolomics, transcriptomics, proteomics), and allows users to define custom molecular sets for aggregation.

Are any of these tasks illustrated in the package or in literature?  Please clarify.

**Comment by vjcitn** [comment]
It seems to me that there are some omissions in the package that the package checking system is missing.
There should be declarations of usage of airway, SummarizedExperiment, and MultiAssayExperiment in DESCRIPTION.
Probably in Suggests field.  Set the environment variable `_R_CHECK_SUGGESTS_ONLY_` to a true value to see
that the absence of these declarations causes CHECK to fail.

**Comment by lshep** [comment]
I do think we are getting closer to acceptance. We appreciate your efforts thus
far. A few additional comments:


**man**

- [ ] Please have a package level man page so if a naive user does `?funOmics`
  something is displayed

**vignette**

- [ ] I would agree with @vjcitn. Switching to have the real world data more prevalent
  over simulated data would be preferred. It should at least be above the
  sessionInfo at minimum.  Thank you for adding the real world data set with
  airways to better show the interaction. 



- [ ] So to clarify on @vjcitn statement a little. You have code displaying useful
  information.  Things like your print statements

```
print(paste("Pathway activity score matrix has dimensions:", nrow(pathway_activity), ",", ncol(pathway_activity)))

```

and your summary statistics

```
length_sets <- sapply(pathways, function(p) length(p))
short_sets <- names(length_sets[length_sets < min])
print(length_sets[short_sets])
print(pathways[short_sets])
```

this is where defining a class structure and having dedicated helper functions
that would do the subsetting and have nice print statements could benefit the
user. Remembering specific code subsets that need to be performed in order to
extract information from your list of lists can be complex and cumbersome for an end user.

**Comment by elisagdelope** [comment]
- A package level man page for ?funOmics has been added. 
- Packages needed for the vignette (but not dependencies of the package) have been added to the suggest of the description file.

Pending restructure of the vignette to highlight the use case on airway data as compared to simulated data.

**Comment by lshep** [comment]
Thank you. Let us know when the vignette is updated and we will take a look again.

**Comment by elisagdelope** [comment]
I'm currently facing an issue with the NMF package. One of the functions in funOmics uses this package. The package is imported both in the NAMESPACE file and in the functions.R file, where the functions are located (in roxygen2 format @import, @importFrom). I have also tried to call the functions as NMF::nmf() and NMF::coef() instead of just nmf() and coef(), however the error persists. 

The error (see below) only gets removed if I explicitly load the library itself, like, if I have library(NMF) before calling the package function that, internally, uses one of its functions. I have explored a range of possible solutions but i have not been successful. What would you recommend? I know it's not ideal but, is it fine if i add library(NMF) in the vignette? Weirdly enough, this issue only happens with this library, not with any other.

Error traceback: 
```
Error in `do.call()`:
! 'what' must be a function or character string
Backtrace:
  1. funOmics::summarize_pathway_level(X, kegg_sets, type = "nmf")
  2. funOmics:::aggby_dimred(ifunmat, type)
  4. NMF::nmf(X, rank = 1)
  6. NMF::nmf(x, rank, NULL, ...)
  7. NMF (local) .local(x, rank, method, ...)
  9. NMF::nmf(x, rank, method, seed = seed, model = model, ...)
 11. NMF::nmf(x, rank, method = strategy, ...)
 12. NMF (local) .local(x, rank, method, ...)
 13. base::do.call(...)

```
When in vignette:   
```
|...........................                        |  54% [unnamed-chunk-18]
Quitting from lines  at lines 182-184 [unnamed-chunk-18] (funomics_vignette.Rmd)
                                                                                                             
Error in `do.call()`:
! 'what' must be a function or character string
Backtrace:
  1. funOmics::summarize_pathway_level(X, kegg_sets, type = "nmf")
  2. funOmics:::aggby_dimred(ifunmat, type)
  4. NMF::nmf(X, rank = 1)
  6. NMF::nmf(x, rank, NULL, ...)
  7. NMF (local) .local(x, rank, method, ...)
  9. NMF::nmf(x, rank, method, seed = seed, model = model, ...)
 11. NMF::nmf(x, rank, method = strategy, ...)
 12. NMF (local) .local(x, rank, method, ...)
 13. base::do.call(...)
Execution halted
```

**Comment by vjcitn** [comment]
feel free to post this at the developer forum on slack

**Comment by elisagdelope** [comment]
- I have restructured the vignette, now almost everything is illustrated through the airway dataset (summarizedExperiment). I have also added examples from all types of aggregations available in funOmics (dimension reduction, summary statistics and test statistics).
- I have added a new function, `short_sets_details` so that some interesting information about molecular sets below an specified `minsize` (minimum size) that I was previously showing through manual inspection of results is now accessible through this helper function without need to extract that information manually from the list of lists.
- The relevant print statements have been incorporated in the package functions so this info is automatically shown without need for further printing, again removing need for manual inspection from the user.
- Re the NMF package issue: I was suggested in the developer forum (slack) to go with the Depends (it appears there is a do.call() somewhere in NMF package that assumes the object is on the search path), and in the meantime i've opened an issue on NMF to see if this can be perhaps solved in their end. 

I think now the vignette is quite illustrative and straightforward to follow. Looking forward to your review.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/elisagdelope.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("funOmics")`. The package 'landing page' will be created at

https://bioconductor.org/packages/funOmics

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
