### ISSUE TITLE
mulea

### ISSUE THREAD

**Issue by stitam** [Bioconductor/Contributions#3328]
Dear Bioconductor Team,

With this issue we would like to submit the `mulea` package. `mulea` is a comprehensive overrepresentation and functional enrichment analyser R package which reads ontologies (gene and protein sets) in a standardised GMT (Gene Matrix Transposed) format.

Kind regards,
Tamás

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ELTEbioinformatics/mulea

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by stitam** [comment]
Some comments:

We have already submitted `muleaData` which is the data package for `mulea`: https://github.com/Bioconductor/Contributions/issues/3291

`mulea` has an upstream which is archived and will not be updated in the future.

`BiocCheck::BiocCheck()` returns the following NOTES:
 
```
NOTE: Update R version dependency from 4.0.0 to 4.3.0.
```
I would rather not do this because then R CMD check will fail on oldrel-1 (https://github.com/ELTEbioinformatics/mulea/pull/24). The package does not require R 4.3.0. (I have turned off GitHub workflows for the Bioconductor submission process)

```
NOTE: Cannot determine whether maintainer is subscribed to the Bioc-Devel mailing list (requires admin
      credentials). Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```
I am registered to both the mailing list and the support forum.

**Comment by lshep** [comment]
Please fix ERROR in build report before the package will more forward in review.

**Comment by stitam** [comment]
Hi @lshep it seems I cannot interact with the upstream (`Permission denied (publickey)`). Can you please check if everything looks fine on your end? Is it possible that because of an earlier submission (which was not done by me) my GitHub account is not on the whitelist? FYI, I'm following this guide: https://contributions.bioconductor.org/git-version-control.html#new-package-workflow. SSH seems fine on my end.

**Comment by lshep** [comment]
everything is fine on our end. Please see about that you should activate your account and then if need be add additional ssh keys

**Comment by stitam** [comment]
Thanks @lshep, my Bioconductor Git Credentials account was not activated.

**Comment by stitam** [comment]
A quick note about the warning: `library()` is necessary for importing cpp stuff into nodes when using multiple threads. I've tried to implement a solution without `library()` but could not find one. We're happy to receive suggestions.

**Comment by DarioS** [comment]
I have trialled the package and noted some issues to be addressed.

- The package lacks sufficient integration with existing Bioconductor infrastructure. It involves enrichment analysis but does not make use of [GSEABase](https://www.bioconductor.org/packages/release/bioc/html/GSEABase.html) data structures. Also, the package depends on data strutures such as `data.frame` which have a Bioconductor equivalent `DataFrame`.
```r
> library(S4Vectors)
> d <- DataFrame(x = 1:5)
> is(d, "data.frame")
  FALSE
```
Also, code uses parallel package instead of BiocParallel. For example, ` cl <- makeCluster(spec=nthread, type="PSOCK")`. Please refer to [Parallel Recommendations](https://contributions.bioconductor.org/r-code.html?q=BiocParallel#parallel-recommendations).
Please greatly improve interoperability with existing Bioconductor conventions.
- The vignette imports an undocumented data set from the `inst` directory and uses `eval = FALSE`. No code chunks are allowed to use `eval = FALSE`. Please see [Package Data](https://contributions.bioconductor.org/data.html) chapter for how to best include data sets.
- Some of the steps in the vignette are long seem like they should be a function. For example,
```r
# if there are duplicated Gene.symbols keep the first one only
geo2r_result_tab_filtered <- geo2r_result_tab %>% 
    # grouping by Gene.symbol to be able to filter
    group_by(Gene.symbol) %>%
    # keeping the first row for each Gene.symbol from rows with the same 
    # Gene.symbol
    filter(row_number()==1) %>% 
    # ungrouping
    ungroup() %>% 
    # arranging by logFC in descending order
    arrange(desc(logFC)) %>%
    select(Gene.symbol, logFC)
```
- Functions and variables need to use camelCase rather than snake_case format. See [R Code](https://contributions.bioconductor.org/r-code.html#r-code-development).
- Namespace file has both selective and complete imports for a particular package.

```r
import(magrittr)
importFrom(magrittr,"%<>%")
importFrom(magrittr,"%>%")
```
- Don't create empty vectors or lists and incrementally grow them. For example,
```r
create_random_db <- function() {
  DB <- list()
  for (cat_i in seq_len(10)) {
    DB_cat_values <- c()
```
Refer to [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize).

**Comment by stitam** [comment]
Many thanks @DarioS for reviewing the package, we'll address these ASAP.

It was unclear to us whether Bioconductor *requires* camel case or snake case is also accepted, we decided to go with snake case and only harmonised this for uer facing functions. Please advise, for a successful review 1. should we moveo to camel case? 2. should we use harmonise for internal functions as well?

Regarding your observation on the namespace file: If there is complete import there is no need to include selective import as well, this is the issue, right?

**Comment by DarioS** [comment]
camelCase for user-facing functions is sufficient. Yes, import either completely or selectively, depending on how many functions.

**Comment by stitam** [comment]
Thank you Bioconductor Team for all your work! It was not feasible for us to implement these changes so we decided to publish the package on CRAN instead of Bioconductor. The package has been released: https://cran.r-project.org/web/packages/mulea/index.html.
