### ISSUE TITLE
basecallQC

### ISSUE THREAD

**Issue by ThomasCarroll** [Bioconductor/Contributions#333]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository:https://github.com/ThomasCarroll/basecallQC

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
The package doesn't look complete, for instance the version number is not of the correct form ('0.99.0') and the 'Description:' field is a template. The package should mention it's central SystemRequirements: bcl2fastq. Its surprising there is not tighter integration with standard Bioconductor packages GenomicRanges, ShortRead, etc. I'll wait to moderate this (so that the package can be built and sent for review) until these issues have been addressed.

**Comment by ThomasCarroll** [comment]
Sorry, i have fixed the missing Description, updated the version number from 0.9.9 to 0.99.0 and added the bcltoFastq version needed in SystemRequirements tag to the description as well as added an additional section at the beginning of vignette for people to get more information on bcl2Fastq program.
This package was aimed at making it easier to work with the input files and commands needed for Illumina's standard basecalling/demultiplexing software, bcl2fastq, and parsing the results generated with bcl2fastq in XML format into something more digestible. I reviewed the Bioconductor objects available and for this package I didn't believe, although i may be wrong, any would fit since it is aimed at working upstream of fastQ and aligned data which could be represented genomic intervals.
I hope these changes can address the issues raised. 
Thank you for your time,
tom

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor. Please see the following comments: 

**GENERAL**
Please fix all notes and warnings in the [build report.](http://bioconductor.org/spb_reports/basecallQC_buildreport_20170328175223.html) which include:
- [ ] Malformed Title field in DESCRIPTION 
- [ ] stringr is listed more than once in Depends, Imports, Suggests, Enhances
- [ ] Packages in Depends field not imported from: BiocStyle prettydoc yaml  These packages need to be imported from (in the NAMESPACE file) for when this namespace is loaded but not attached.
- [ ] There are `:::` that should be `::`
- [ ] partial argument match of 'key' to 'key_col'
- [ ] no visible binding for global variable  see `?globalVariables` in R 

**VIGNETTE**
- [ ] general question: so all these files are generated as output from some experiment?  do the users have to generate any of the files by hand? If so this should be better clarified.

**MAN**
- [ ] for your classes (bcl2fastqparams, basecallQC, etc) describe what information is provided in the output object - what slots are there and formats?  That way we can also verify if there is an existing Bioconductor class that may be better or if your classes are well needed.

**CODE**
allClasses:
- [ ] basecallQC  - why is there a hard coded path? shouldn't this be a variable to be given where the files are located? generally hard coded paths are bad. 

processXMLs_Functions.R:
- [ ] Avoid use of 1:n; use seq_len(n) or seq_along(x) instead. 


Once the above issues are addressed please do a version bump to kick off a new build (please ensure your [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) is properly initialized before version bump) and  comment back here with how they were addressed or any clarification.

**Comment by lawremi** [comment]
At the very least, you could define a method on the `report()` generic from ShortRead, instead of defining `reportBCL()`. Also, `setBCL2FastQparams()` would be better named as a constructor, like `BCL2FastqParams()`.  It seems odd for `basecallQC()` to convert the BCL to Fastq _and_ compute the QC. Why not separate those operations?

**Comment by ThomasCarroll** [comment]
Thank for your comments.
I have addressed the General and Code comments and renamed as a constructor - BCL2FastqParams().
Before I bump the version I am working on your other comments. 
I will clarify in vignette the input files and object slots in the manual, I agree that it would be useful to disentangle the basecalling prep from QC and I am implementing this now. I will clarify in manual how reportBCL() reports information from Illumina's XML output as opposed to QC from the fastQ files generated.

**Comment by lshep** [comment]
Please make sure the webhook [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) is set up and do a version bump to kick off a new build.  If you don't see a new build report the webhook isn't set up correctly.

**Comment by ThomasCarroll** [comment]
I have worked to fix the comments and here I address the points below one at a time.

> GENERAL
> Please fix all notes and warnings in the build report. which include:
> 
>  Malformed Title field in DESCRIPTION
>  stringr is listed more than once in Depends, Imports, Suggests, Enhances
>  Packages in Depends field not imported from: BiocStyle prettydoc yaml These packages need to be imported from (in the NAMESPACE file) for when this namespace is loaded but not attached.
>  There are ::: that should be ::
>  partial argument match of 'key' to 'key_col'
>  no visible binding for global variable see ?globalVariables in R
> 

I have removed all the check notes and warnings from R CMD check and have two notes remaining from BiocCheck (lines too long and indentation being 2 instead of 4)

The warning i incurred seemed to be related to rmarkdown being built on R 3.5.0 on Windows.

> VIGNETTE
> 
>  general question: so all these files are generated as output from some experiment? do the users have to generate any of the files by hand? If so this should be better clarified.

I have added sections to the vignette which I hope clarifies more where these files come from and the relation to bcl2Fastq software.

> MAN
> 
>  for your classes (bcl2fastqparams, basecallQC, etc) describe what information is provided in the output object - what slots are there and formats? That way we can also verify if there is an existing Bioconductor class that may be better or if your classes are well needed.

I have added details tag in the manual explaining the slots and what they represent.

> 
> CODE
> allClasses:
> 
>  basecallQC - why is there a hard coded path? shouldn't this be a variable to be given where the files are located? generally hard coded paths are bad.

Sorry this was for some tests and should have been removed. I have fixed this now.

> processXMLs_Functions.R:
> 
>  Avoid use of 1:n; use seq_len(n) or seq_along(x) instead.

I have changed to use seq_along.

> Also, setBCL2FastQparams() would be better named as a constructor, like BCL2FastqParams()

I have changed this.

> It seems odd for basecallQC() to convert the BCL to Fastq and compute the QC. Why not separate those operations?

I agree and I have split the prep from the QC so people are able to plot or report tables without working through samplesheet and basemasks preparation.

thank you for your time

**Comment by lshep** [comment]
The package looks acceptable.  I will mark as accepted. Please leave the issue open and you will receive svn instructions within a few days.

**Comment by ThomasCarroll** [comment]
Thank you both for the comments and review.
