### ISSUE TITLE
(inactive) D3GB

### ISSUE THREAD

**Issue by BioinfoUSAL** [Bioconductor/Contributions#334]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BioinfoUSAL/D3GB

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
It's really surprising that there are _no_ Bioconductor dependencies, given the extensive facilities for working with standard file formats via [rtracklayer][], [Biostrings][], [ShortRead][], [Rsamtools][] and the highly flexible [GenomicRanges][] infrastructure -- it seems like the main motivation for including a genome browser in R is to enable interoperability.

[rtracklayer]: https://bioconductor.org/packages/rtracklayer
[Biostrings]: https://bioconductor.org/packages/Biostrings
[ShortRead]: https://bioconductor.org/packages/ShortRead
[Rsamtools]: https://bioconductor.org/packages/Rsamtools
[GenomicRanges]: https://bioconductor.org/packages/GenomicRanges

**Comment by lawremi** [comment]
Also: selfish plug for using the genbankr package for reading the genbank files.

**Comment by BioinfoUSAL** [comment]
The main intention of avoiding too many dependencies is to facilitate 
the maintenance. However, I will take into account your suggestions for 
further versions.

**Comment by BioinfoUSAL** [comment]
The main intention of avoiding too many dependencies is to facilitate 
the maintenance. However, I will take into account your suggestions for 
further versions.

**Comment by mtmorgan** [comment]
I am declining this package. Certainly a solid stand-alone browser interacting with R / Biocondudctor would be interesting. But from the vignette and upstream discussion the current package really provides limited interaction (file download and browser launch), and is primarily an R distribution of a javascript browser. A revised package that much more effectively integrated with existing R / Bioconductor data representations might be considered. It would be useful to look at for instance rtracklayer, epivizr, and other existing packages for ideas on integration. The obvious points of contact include GenomicRanges, GenomicAlignments, rtracklayer, and the annotation resources such as TxDb, ensembldb, ...
