### ISSUE TITLE
New package omXplore

### ISSUE THREAD

**Issue by samWieczorek** [Bioconductor/Contributions#3347]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/prostarproteomics/omXplore

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
- [ ] You have many additional non standard directories and listings from a base level
package. Can this be cleaned up and pared down to just package code and
necessities and additional material moved to a different branch? 

- [ ] What are the files in `inst/md` should these be moved to standard
vignettes? 

- [ ] There is a single image file in `inst/www` is it needed or can it be condensed
someplace else?

- [ ] How is the data in `inst/extdata` used? There is no documentation on its
creation.  Please provide relavent informatoni in `inst/script` on how this data
was generated and any source/licensing information.

- [ ] Is the doc directory needed for pkgdown?

- [ ] In the vignette can you please explain and compare how this package differs from
already existing visualiztion packages for omics data that exist in
Bioconductor.

- [ ] Please be advised when I build the package I get the following

```
R CMD build omXplore 
* checking for file 'omXplore/DESCRIPTION' ... OK
* preparing 'omXplore':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a 'data/datalist' file should be added
* building 'omXplore_0.99.1.tar.gz'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk0ZjaVQ.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk5hkWVAexg.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk5hkaVQ.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk8ZkWVAexg.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk8ZkaVQ.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk_RkaVQ.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0RkxhjaVQ.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0RkyFjWVAexg.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0RkyFjaVQ.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsg-1x4gaVQ.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsg-1y4k.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsgH1y4k.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgshZ1y4k.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsiH0B4gaVQ.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsiH0C4k.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjZ0B4gaVQ.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjZ0C4k.woff'
Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  'omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjr0C4k.woff'

```

- [ ]  And `R CMD check`  
```
R CMD check omXplore_0.99.1.tar.gz 
* using log directory '/home/lorikern/PkgReview/PreReview/omXplore.Rcheck'
* using R Under development (unstable) (2023-10-25 r85412)
* using platform: x86_64-pc-linux-gnu
* R was compiled by
    gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
    GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
* running under: Ubuntu 22.04.4 LTS
* using session charset: UTF-8
* checking for file 'omXplore/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'omXplore' version '0.99.1'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .github
These were most likely included in error. See section 'Package
structure' in the 'Writing R Extensions' manual.
* checking for portable file names ... NOTE
Found the following non-portable file paths:
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk0ZjaVQ.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk5hkWVAexg.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk5hkaVQ.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk8ZkWVAexg.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk8ZkaVQ.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk_RkaVQ.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0RkxhjaVQ.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0RkyFjWVAexg.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0RkyFjaVQ.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsg-1x4gaVQ.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsg-1y4k.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsgH1y4k.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgshZ1y4k.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsiH0B4gaVQ.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsiH0C4k.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjZ0B4gaVQ.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjZ0C4k.woff
  omXplore/docs/deps/bootstrap-5.3.1/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjr0C4k.woff

Tarballs are only required to store paths of up to 100 bytes and cannot
store those of more than 256 bytes, with restrictions including to 100
bytes for the final component.
See section 'Package structure' in the 'Writing R Extensions' manual.
* checking for sufficient/correct file permissions ... OK
* checking whether package 'omXplore' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking whether startup messages can be suppressed ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
Build_X_CC: no visible global function definition for ‘metadata’
Build_X_CC: no visible global function definition for ‘metadata<-’
Check_MSnSet_Consistency : <anonymous>: no visible global function
  definition for ‘experimentData’
MAE_Compatibility_with_Prostar_1x : <anonymous>: no visible binding for
  global variable ‘.colData’
SE_Compatibility_with_Prostar_1.x: no visible global function
  definition for ‘experimentData’
SE_Compatibility_with_Prostar_1.x: no visible global function
  definition for ‘metadata’
SE_Compatibility_with_Prostar_1.x: no visible global function
  definition for ‘metadata<-’
Undefined global functions or variables:
  .colData experimentData metadata metadata<-
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking running R code from vignettes ...
  'addingThirdPartyPlots.Rmd' using 'UTF-8'... OK
  'omXplore.Rmd' using 'UTF-8'... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 3 NOTEs
See
  '/home/lorikern/PkgReview/PreReview/omXplore.Rcheck/00check.log'
for details.


```

**Comment by samWieczorek** [comment]
I have cleand and update my package omXplore with your advices

* many additional non standard directories and listings from a base level
package. Can this be cleaned up and pared down to just package code and
necessities and additional material moved to a different branch?
>> unnecessary directories and listings have been deleted

 What are the files in inst/md should these be moved to standard
vignettes?
>> Not necessary => deleted

 There is a single image file in inst/www is it needed or can it be condensed
someplace else?
>> Not necessary => deleted

 How is the data in inst/extdata used? There is no documentation on its
creation. Please provide relavent informatoni in inst/script on how this data
was generated and any source/licensing information.
>> The two *.png files have been moved to inst/images

 Is the doc directory needed for pkgdown?
>> Yes but I moved it in the gh-pages branch of omXplore

 In the vignette can you please explain and compare how this package differs from
already existing visualiztion packages for omics data that exist in
Bioconductor.
>> Done (in Introduction and Features section)

Hope that these updates are sufficient. Please let me know if I have to do anything else

**Comment by lshep** [comment]
I'm still seeing a doc directory and _pkgdown.yml in the main branch rather than in gh-pages as indicated when I do a fresh git clone ?

**Comment by samWieczorek** [comment]
Do not know what happened. Must be ok now.

**Comment by vjcitn** [comment]
Is this really ready to go?  
```
plot_violin.R:#' @param conds xxx
plot_violin.R:#' @param subset xxx
plot_violin.R:#' @param pal.name xxx
Prostar_1x.R:#' @title xxxx
Prostar_1x.R:#' @description xxx
utils.R:#' @title xxx
utils.R:#' @description xxx
utils.R:#' @title xxx
utils.R:#' @description xxx
utils.R:#' @return A `character(1)` with the name of the package or xxx
utils.R:#' @param width xxx
utils.R:#' @param height xxx
utils.R:#' xxxx
utils.R:#' xxxx
```

**Comment by samWieczorek** [comment]
Oupss, sorry. I have forgotten some comments. Fixed

**Comment by vjcitn** [comment]
really sorry for delay on this.  I installed and did ?SE_to_mae and saw
```
Description:

     The resulting object is an instance of the MultiAssayExperiment
     class. F
```
looks like some text is lost?  Furthermore the example for SE_to_mae starts with miniACC which is not an SE but is already an MAE.  What is the intention here?

**Comment by vjcitn** [comment]
In the first paragraph of vignette "Bioconductor" is misspelled.  When I try to follow the app code in the vignette, I see 
```
> listPlotModules()
[1] "omXplore_cc"          "omXplore_corrmatrix"  "omXplore_density"    
[4] "omXplore_heatmap"     "omXplore_intensity"   "omXplore_pca"        
[7] "omXplore_tabExplorer" "omXplore_variance"   
> data(sub_R25)
app <- view_dataset(sub_R25)
shiny::runApp(app)

Listening on http://127.0.0.1:6128
No external module was found
```
and the display is
![image](https://github.com/Bioconductor/Contributions/assets/4624066/6eb570d3-3513-4f9c-9a3a-40524ca03fef)

**Comment by lshep** [comment]
@samWieczorek  may we expect updates based on the above soon?

**Comment by vjcitn** [comment]
@samWieczorek will you be working on this?

**Comment by samWieczorek** [comment]
Sorry, I did not see your previous message. Yes of course I still work on this. I will check all your previous messages today

**Comment by samWieczorek** [comment]
About the comment of [vjcitn](https://github.com/vjcitn) [on Jul 11]
All is normal. The message indicating "No external module found" explains that the interface only shows default plots embedded in the package omXplore ans the user did not load ant supplementary plot

**Comment by samWieczorek** [comment]
Please let me know if there is anything to modify in this package so as to be in th next release

**Comment by samWieczorek** [comment]
Is the package ready to be pushed in the devel branch of the next release ?

**Comment by vjcitn** [comment]
Are you able to do anything about this
```
    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples.
    * NOTE: Usage of dontrun{} / donttest{} tags found in man page
      examples. 35% of man pages use at least one of these tags.
    * NOTE: Use donttest{} instead of dontrun{}.
```
result of BiocCheck?

**Comment by vjcitn** [comment]
I have accepted it because for the most part it seems well-done.  However I think you should do more to ensure that examples are runnable by the user and to avoid the situation I showed on July 11 ... "No external module found" is not helpful, and if you must return a message of this sort, please make it more informative with a reference to relevant documentation.

**Comment by samWieczorek** [comment]
Ok, thank you for the acceptance

I will do my best to make better examples

De : Vince Carey ***@***.***>
Envoyé : jeudi 3 octobre 2024 11:11
À : Bioconductor/Contributions ***@***.***>
Cc : WIECZOREK Samuel ***@***.***>; Mention ***@***.***>
Objet : Re: [Bioconductor/Contributions] New package omXplore (Issue #3347)


I have accepted it because for the most part it seems well-done. However I think you should do more to ensure that examples are runnable by the user and to avoid the situation I showed on July 11 ... "No external module found" is not helpful, and if you must return a message of this sort, please make it more informative with a reference to relevant documentation.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/samWieczorek.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("omXplore")`. The package 'landing page' will be created at

https://bioconductor.org/packages/omXplore

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
