### ISSUE TITLE
GA4GHshiny

### ISSUE THREAD

**Issue by Welliton309** [Bioconductor/Contributions#335]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/labbcb/GA4GHshiny

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Hi,

(1) man pages
The packages listed in Suggests need to be loaded in man pages and vignettes. When GA4AGHshiny is installed, there is no check to confirm packages in Suggests are installed on the user's system - so if they aren't the example will fail. The runApp.Rd example uses an OrgDb and TxDb; both should be loaded before you call the function.

(2) typos in vignette
"...
The package have only one function called `runApp`, wich runs the web application.
..."

'have' should be 'has'
'wich' should be 'which'

(3) 'host' arg in runApp()
From the man page:
```
host: URL of GA4GH API data server.
```
What values can host have ... only the one default? If there can be more than one value how do I discover what these are?

(4) application
When I try to runApp() I get this error:
```
> runApp(host = "http://1kgenomes.ga4gh.org/",
+     serverName = "Hosting Thousand Genomes Project",
+     orgDb = "org.Hs.eg.db",
+     txDb = "TxDb.Hsapiens.UCSC.hg19.knownGene")
Loading required package: org.Hs.eg.db
Loading required package: AnnotationDbi
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: IRanges

Loading required package: TxDb.Hsapiens.UCSC.hg19.knownGene
Loading required package: GenomicFeatures
Loading required package: GenomeInfoDb
Loading required package: GenomicRanges
Error in while (response$nextPageToken != "" && nrow(response$datasets) <  :
  missing value where TRUE/FALSE needed
```
Valerie

**Comment by Welliton309** [comment]
Thank you @vobencha for the suggestions.

The GA4GH API schema changed and broke the GA4GHclient package ([reference](https://github.com/labbcb/GA4GHclient/issues/27)). I updated this package in Bioc-devel. I also had to change the name of `runApp` function because the shiny package has a function with the same name. Now, this function is called `app`.

**Comment by vobencha** [comment]
Has the package been updated? If yes, please explain how items in https://github.com/Bioconductor/Contributions/issues/335#issuecomment-291617634 have been addressed. A version bump will trigger a new SPB build.

Valerie

**Comment by Welliton309** [comment]
I updated the repository right now and changed the package version ([0.99.3](https://github.com/labbcb/GA4GHshiny/blob/master/DESCRIPTION#L4)). Looks like nothing happened at build system.

Answering the comments:

1. I added `library` calls to examples and vignette.
2. Fixed typos.
3. Improved documentation about `host` argument.
4. Fixed GA4GHclient package ([version 0.99.10](http://bioconductor.org/packages/devel/bioc/html/GA4GHclient.html)).

**Comment by llrs** [comment]
The build system of packages maybe is stopped due to shortly new release of Bioconductor.

**Comment by vobencha** [comment]
@lshep can you please kick off a new build?
Thanks.
Val

**Comment by lshep** [comment]
Yes but please @Welliton309 Please ensure you followed the instructions [here](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) for setting up the webhook. If the webhook was not initiated, version bumps will not kick off new builds.

**Comment by Welliton309** [comment]
I am sorry. I forgot to configure the webhook for this repository. Thank you @lshep.

**Comment by lshep** [comment]
No problem.  You might get two reports now as I manually kicked off a build as well.

**Comment by vobencha** [comment]
Thanks for making the changes. The package is approved and you should get an email in a few days with svn instructions and next steps.
Valerie
