### ISSUE TITLE
gINTomics

### ISSUE THREAD

**Issue by angelovelle96** [Bioconductor/Contributions#3352]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/angelovelle96/gINTomics

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Kayla-Morrell** [comment]
@angelovelle96 - Thank you for submitting to _Bioconductor_. Please see the initial review of 
the package below. The required changes must be made while the suggested 
changes do not have to be (though we strongly encourage them). Comment back 
here with updates that have been made and when the package is ready for a 
re-review.

## DESCRIPTION

- [ ] REQUIRED: Update R version dependency from 4.3.0 to 4.4.0.

##  NAMESPACE

- [ ] SUGGESTION: Consider adding 'importFrom("stats", "coef", "cov")' to your NAMESPACE file.

## CITATION

- [ ] SUGGESTION: (Optional) CITATION file not found. Only include a CITATION
      file if there is a preprint or publication for this Bioconductor
      package. Note that Bioconductor packages are not required to have
      a CITATION file but it is useful both for users and for tracking
      Bioconductor project-wide metrics. When including a CITATION
      file, add the publication using the 'doi' argument of
      'bibentry()'.

## Data

- [ ] REQUIRED: Data in the `data/` directory needs to have a man page for documentation. I see the documentation within `inst/scripts` but it should be moved into a `data.Rd` file.

## Vignette

- [ ] REQUIRED: Code blocks should not include `eval = FALSE`. 

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the package and links to the main functions. Users should be able to have a relevant page display with `?gINTomics`.
- [ ] SUGGESTION: Rd file 'dot_poly.Rd' \examples lines wider than 100 characters. These lines will be truncated in the PDF manual.

## R code

- [ ] REQUIRED: There are ':::' calls to the package's namespace in its code. A package almost never needs to use ':::' for its own objects. You can just use `.def_enrich`.
- [ ] SUGGESTION: Checking R code for possible problems. Undefined global functions or variables:
        Freq chr_cov cnv cnv_meet coef cov met mirna_cnv omics pval significance
- [ ] REQUIRED: Use accessors; don't access S4 class slots via '@' in examples/vignettes.
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 48 lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 386 lines that are not.

Best,
Kayla

**Comment by angelovelle96** [comment]
@Kayla-Morrell Thank you for your time and for the comments and suggestions regarding our package. All the required and some of the suggested updates have been implemented, now we are ready for a re-review:

 ## DESCRIPTION
- [x] REQUIRED: Update R version dependency from 4.3.0 to 4.4.0.

**Version updated**

 ## NAMESPACE
 - [ ]  SUGGESTION: Consider adding 'importFrom("stats", "coef", "cov")' to your NAMESPACE file.

**coef and cov are columns of a dataframe used for building a ggplot. I noticed that R check gives NOTES when using the standard ggplot2 workflow (giving a dataframe as input and then calling the variables using column’s names). Anyway I would like to leave it this way, since this should be the correct structure to use with ggplot2.**
 
 
 ## CITATION
 - [x]  SUGGESTION: (Optional) CITATION file not found. Only include a CITATION
       file if there is a preprint or publication for this Bioconductor
       package. Note that Bioconductor packages are not required to have
       a CITATION file but it is useful both for users and for tracking
       Bioconductor project-wide metrics. When including a CITATION
       file, add the publication using the 'doi' argument of
       'bibentry()'.

**We don’t have a publication or preprint yet**
 
 
 ## Data
 - [x]  REQUIRED: Data in the `data/` directory needs to have a man page for documentation. I see the documentation within `inst/scripts` but it should be moved into a `data.Rd` file.

**I noticed that the names of the rda files in `data/` didn’t match the names of their respective R objects and Rd files. Now the two rda files in `data/` are `mmultiassay_ov.rda` and `mirna_hsa.rda`. You can find their documentations in `man/mmultiassay_ov.Rd` and `man/mirna_hsa.Rd`**
 
 ## Vignette
- [x]  REQUIRED: Code blocks should not include `eval = FALSE`.

**I removed the `eval = FALSE`, now the only chunk that has it is the one for the package installation**
 
 
 ## Man pages
- [x]  SUGGESTION: We encourage having a package man page with an overview of the package and links to the main functions. Users should be able to have a relevant page display with `?gINTomics`.

**I added the package man page**

- [x]  SUGGESTION: Rd file 'dot_poly.Rd' \examples lines wider than 100 characters. These lines will be truncated in the PDF manual.

**Now the example lines are shorter**

 ## R code
 - [x]  REQUIRED: There are ':::' calls to the package's namespace in its code. A package almost never needs to use ':::' for its own objects. You can just use `.def_enrich`.

**I removed the  `:::` for  .def_enrich**
 
- [ ]  SUGGESTION: Checking R code for possible problems. Undefined global functions or variables:
       Freq chr_cov cnv cnv_meet coef cov met mirna_cnv omics pval significance

**This is the same ggplot2 issue of the NAMESPACE section**
 
- [x]  REQUIRED: Use accessors; don't access S4 class slots via '@' in examples/vignettes.

**I removed the '@', now the accessors are used**

 - [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 48 lines that are > 80 characters long.

**All the lines exceeding 80 characters are contained in text  sections of manual/vignette**

- [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 386 lines that are not.

**We used the `styler` package for the indentation, almost all the lines are correctly indented. Part of the lines that are not correctly indented are contained in text  sections of manual/vignette**

Best,
Angelo

**Comment by Kayla-Morrell** [comment]
@angelovelle96 - Thank you for making the necessary changes. I have reviewed everything and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/angelovelle96.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gINTomics")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gINTomics

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
