### ISSUE TITLE
HoloFoodR

### ISSUE THREAD

**Issue by TuomasBorman** [Bioconductor/Contributions#3353]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/EBI-Metagenomics/HoloFoodR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
Just wanted to verify that you want this package to be considered a data experiment package and not a software package?

**Comment by TuomasBorman** [comment]
This package is related to MGnifyR that is also in Bioc submission https://github.com/Bioconductor/Contributions/issues/3191 . They should be in same place.

These packages provide linkage between Bioconductor and APIs. They can only search and fetch data. Based on Bioconductor guidelines, software packages can provide access to resources. It also seems that the structure of ExperimentData packages are different: they contain ready datasets stored in ExperimentHub.

Classified as "data package" would be natural (also because the package might be easier to find from there), but I guess this is still "sofware package" based on Bioc guidelines?

**Comment by lshep** [comment]
Yes in what we have done in the past we would consider it more a software package but it can be listed however you like. If you feel data experiment is a better classification that is fine.  Just wanted to check before we add as once it is accepted it will be harder for us to alter.

**Comment by lshep** [comment]
Please confirm before we advance farther

**Comment by TuomasBorman** [comment]
Yes, sorry for delay. We had to discuss about this. It seems that all other packages that create R interface to some database are categorized as software. So it is best to follow this convention (and Bioconductor guide).

--> we want to classify HoloFoodR and MGnifyR as software packages

**Comment by lshep** [comment]
Could you please update your biocViews then to reflect this?

**Comment by TuomasBorman** [comment]
Updated

**Comment by TuomasBorman** [comment]
To note:

Examples on `getMetaboLights` are commented out. The connection fails sometimes which causes build to fail. If I add `\dontrun`, the build also fails --> "At least 80% of man pages documenting exported objects must have runnable examples."

**Comment by TuomasBorman** [comment]
Hello! Has this proceeded?

**Comment by Kayla-Morrell** [comment]
@TuomasBorman - Thank you for submitting to _Bioconductor_. Please see the initial review of 
the package below. The required changes must be made while the suggested 
changes do not have to be (though we strongly encourage them). Comment back 
here with updates that have been made and when the package is ready for a 
re-review.

## DESCRIPTION

- [ ] SUGGESTION: The Description field in the DESCRIPTION is made up by less than 3 sentences. Please consider expanding this field and structure it as a full paragraph.

## NEWS 

- [ ] REQUIRED: It's good practice to include a NEWS file. However, it doesn't seem to be formatted properly. Please see our documentation for proper formatting of news files - https://contributions.bioconductor.org/news.html.

## Data

- [ ] REQUIRED: Data included in the 'inst/extdata/' directory needs corresponding documentation. This documentation should be in an 'inst/script/' directory. The scripts in this directory can vary but most importantly they should clearly state how the data was generated and include source information. There should be source URLs and any key information regarding filtering or processing. It can be executable code, sudo code, or a text description. Users should be able to download and roughly reproduce the file or object that is present as data.

## Vigenttes

- [ ] REQUIRED: All code blocks, except for installation, should be executable and not use 'eval = FALSE'.

## Man pages

- [ ] REQUIRED: Only man pages belong in the 'man/' directory. If the figures are needed they should be moved to an 'inst/figures/' directory and paths should be changed to reflect this.

## R code

- [ ] SUGGESTION: Avoid redundant 'stop' and 'warn*' in signal conditions.
- [ ] SUGGESTION: Avoid 'suppressWarnings'/'*Messages' if possible.

Best,
Kayla

**Comment by TuomasBorman** [comment]
-  [x] SUGGESTION: The Description field in the DESCRIPTION is made up by less than 3 sentences. Please consider expanding this field and structure it as a full paragraph.

- [x] SUGGESTION: Avoid redundant 'stop' and 'warn*' in signal conditions.

- [x] SUGGESTION: Avoid 'suppressWarnings'/'*Messages' if possible.

- [x] REQUIRED: Data included in the 'inst/extdata/' directory needs corresponding documentation. This documentation should be in an 'inst/script/' directory. The scripts in this directory can vary but most importantly they should clearly state how the data was generated and include source information. There should be source URLs and any key information regarding filtering or processing. It can be executable code, sudo code, or a text description. Users should be able to download and roughly reproduce the file or object that is present as data.

- [ ] REQUIRED: It's good practice to include a NEWS file. However, it doesn't seem to be formatted properly. Please see our documentation for proper formatting of news files - https://contributions.bioconductor.org/news.html.
 
 --> It seems that NEWS file is parsed correctly
 
- [ ] REQUIRED: All code blocks, except for installation, should be executable and not use 'eval = FALSE'.

--> They are not evaluated because it will take long time to download the data. Instead of loading it from database, the data is already loaded and stored in inst/extdata.

- [ ] REQUIRED: Only man pages belong in the 'man/' directory. If the figures are needed they should be moved to an 'inst/figures/' directory and paths should be changed to reflect this.

--> They are in man folder because otherwise the figures cannot be included in the manual. (or at least it seems to be the easiest solution). https://ebi-metagenomics.github.io/HoloFoodR/

**Comment by Kayla-Morrell** [comment]
@TuomasBorman - Thank you for making the necessary changes. My apologies for the NEWS file requirement, you are correct it is formatted properly. Your rational for eval = FALSE in vignette is acceptable. If the figures won't render in the manual than you may move the figures back to the man directory. I am more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/TuomasBorman.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HoloFoodR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HoloFoodR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
