### ISSUE TITLE
multistateQTL

### ISSUE THREAD

**Issue by dunstone-a** [Bioconductor/Contributions#3357]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dunstone-a/multistateQTL

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by DarioS** [comment]
The package is well thought-out and has good interoperability with existing Bioconductor infrastructure such as `QTLExperiment`. I have noticed some minor issues to improve upon.

- Don't have separate installations of CRAN and Bioconductor packages in README file. Already listed in DESCRIPTION.
- Avoid sequences such as `1:nStates` and use `seq_along(nStates)`. See [Syntax and Efficiency](https://contributions.bioconductor.org/r-code.html?q=camelCase#code-syntax-and-efficiency).
- Variable naming is inconsistent e.g. `beta_sd`, `nNull`. [camelCase is Bioconductor standard](https://contributions.bioconductor.org/r-code.html?q=camelCase#variable-names).
- Inputs are not type-checked. Use `is(qtle, "QTLExperiment")` or an S4 method which forces type-checking to be done by R.
- Vignette has inconsistent and duplicated section numbering.
![image](https://github.com/Bioconductor/Contributions/assets/631218/9343ef22-8c17-43b6-80f6-93f02a5744a8)
- Plotting section should explain whether graphics are ggplot2 and customisable by `+` or base graphics and not.
- Section "Pairwise sharing": Interpret the two blocks seen in the heatmap in a sentence or two.
- Consistency: `plotCompareStates` seems to use default ggplot2 style but `plotSimulationParams` probably `theme_bw()`.
- Visualizing multi-state QTL: Add interpretation after the plot.

**Comment by dunstone-a** [comment]
Thank you so much for your review @DarioS ! Apologies that it has taken me a while to reply. I have addressed all of your comments:

> Don't have separate installations of CRAN and Bioconductor packages in README file. Already listed in DESCRIPTION.

I have removed these from the README.

> Avoid sequences such as `1:nStates` and use `seq_along(nStates)`. See [Syntax and Efficiency](https://contributions.bioconductor.org/r-code.html?q=camelCase#code-syntax-and-efficiency).

I have replaced all instances of `1:n` and `1:length(x)` with `seq_len()` and `seq_along()`.

> Variable naming is inconsistent e.g. `beta_sd`, `nNull`. [camelCase is Bioconductor standard](https://contributions.bioconductor.org/r-code.html?q=camelCase#variable-names).

I have updated all functions to use only camelCase for inputs, changing the names of arguments which were in snake_case. For example I am now using betaSd, annotateRowsBy, annotateColsBy, assaySig, colRange, distMethod, threshSig, threshNull, colBoth, colDiverging, colNeither, colX, colY, etc.

I have kept `state_id `the way it was because it is similar to `spatial_id `of the SpatialExperiment package.

I retained `row_km `and `column_km `and `show_row_names` as these arguments are passed directly to ComplexHeatmap so users familiar with ComplexHeatmap may already know these arguments.

Retained `FUN `argument as it is similar to the `FUN `argument from base R functions such as tapply. 
Retained `p.adjust.method` as it is similar to the `p.adjust.methods` from the base R stats package. 


> Inputs are not type-checked. Use `is(qtle, "QTLExperiment")` or an S4 method which forces type-checking to be done by R.

I have added type-checking for the main input to the following plotting functions: plotUpSet, plotCompareStates and plotSimulationParams.

I also added type checking for the main inputs in: simPerformance, runTestMetrics, runPairwiseSharing, replaceNAs, qtleSimulate, qtleEstimate, callSignificance, getComplete, getSignificant and getTopHits.

> Vignette has inconsistent and duplicated section numbering.

I've removed the manually typed in numbers for sections that were causing problems.

> Plotting section should explain whether graphics are ggplot2 and customisable by `+` or base graphics and not.
> Consistency: `plotCompareStates` seems to use default ggplot2 style but `plotSimulationParams` probably `theme_bw()`.

I've added a description at the start of the plotting section to explain that all graphics are built using _ggplot2_ or _ComplexHeatmap_. 
I've also updated the plotting functions to all use `theme_classic()`.

> Section "Pairwise sharing": Interpret the two blocks seen in the heatmap in a sentence or two.
> Visualizing multi-state QTL: Add interpretation after the plot.

I've added descriptions for both of these plots in the vignette.

Let me know if you have any further suggestions to improve the package.

Thanks,
Amelia

**Comment by DarioS** [comment]
The issues have been addressed.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dunstone-a.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("multistateQTL")`. The package 'landing page' will be created at

https://bioconductor.org/packages/multistateQTL

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
