### ISSUE TITLE
(inactive) pathwrap

### ISSUE THREAD

**Issue by Elizaddh** [Bioconductor/Contributions#3372]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Kannapolis-Bioinformatics/pathwrap

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
You should not be trying to install system requirements for a user.  Anything
that is needed to should be assumed to be installed by the user.  If a system
dependency is needed please include an INSTALL file for installation
instructions http://contributions.bioconductor.org/sysdep.html and make sure it
is listed in the DESCRIPTION file.

**Comment by Elizaddh** [comment]
Hi,
It looks like some scripts in the readme.md file were trying to install packages.  I commented them out. My packages only prompts/messages user to install the required package when reference directory is not provided as an argument. I updated the DESCRIPTION file with reference and annotation packages for mouse in the Suggests section. Also I updated the code to include proper name of pathways for compound sets analysis without which there was a bug in the result table generation. Please let me know if any other things triggered this issue or other issues. 
Thanks,

**Comment by lshep** [comment]
Is there a reason to change the user's options in mktxdbobj.R `options(cache_size = NULL, synchronous = NULL)` ; it is not advisable to change user options without their permission? 

Why are you looking in the working directory for files when it seems like file paths are specified by the user in plotpathways.R?

**Comment by vjcitn** [comment]
Thanks for this submission.  We've discussed it internally and have some concerns.  First, the vignette includes (I substitute dots for backtick)
```
...r installation, eval = FALSE}
library(pathwrap)
data(anntpkglist, package = "pathwrap")
#replace Homo sapiens with scientific name of mouse, Mus musculus for mouse data
genomepkg <- anntpkglist$genome[which(anntpkglist$species == "Homo sapiens")]
anntpkg <- anntpkglist$annotate[which(anntpkglist$species == "Homo sapiens")]
#BiocManager::install(genomepkg)
#BiocManager::install(anntpkg)
```
So no code is being run or tested.  This is not how vignettes are intended to work ... They really should put mileage on your code so that any bit-rot can be exposed when vignette computations fail.  Is it possible to construct a modest working example with running code in the vignette?  It might be more appropriate to submit this as a workflow package.

**Comment by vjcitn** [comment]
I am setting the flag to "pre-review" changes needed.

**Comment by Elizaddh** [comment]
Hi,
Thank you for the comments and concerns. I plan to rewrite vignettes and get some test codes running moving forward. I will update the package soon in github and let you know. 
Eliza.

**Comment by lshep** [comment]
Just wanted to check in to see if we may expect any updates soon?

**Comment by Elizaddh** [comment]
Hi,
sorry for late response. I got occupied with other issues.I will probably work on this in July. Please expect an update after July 10 on early.
