### ISSUE TITLE
RaggedExperiment

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/Contributions#339]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/RaggedExperiment

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment]
Could the constructor get the default `colData` from the `mcols()` on the provided List (when it is a List)?
Would additional range summaries make sense, like `reduce()`, `union()`, `intersect()`, etc? Seems like the `qreduce` thing would be useful for summarizing Rle coverage and other things.

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor. Please see the comments below: 

**General:**
- [ ] Please response to @lawremi comments above 

**Vignette:**
- [ ] (Optional) I would suggest putting installation instructions in vignette
```
source("https://bioconductor.org/biocLite.R")
biocLite("RaggedExperiment")
```

**Man:**
- [ ] (Optional) In RaggedExperiment-package I would suggest having links to main functions of package so users know where to get started. 

Please respond to or address the issues above.
Thank you

**Comment by lshep** [comment]
rerunning the build for you too so that you can have a better report now that the Biobase ERROR has been resolved

**Comment by LiNk-NY** [comment]
Hi Michael @lawremi, 
Thank you for your feedback. I have implemented a `List` type of input for `RaggedExperiment`. This would best work with `SimpleGenomicRangesList` inputs that have `mcols` data. 

I think additional range summarizes like reduce can be used with the `qreduceAssay` function. For example, `rowRanges(ragexp)` can be `reduce`d and used as the input to the function: 

```
## after running code in the vignette
reducedRanges <- reduce(rowRanges(ragexp))
qreduceAssay(ragexp, query = reducedRanges, simplify = weightedmean)
```

Thank you for your comments Lori @lshep. 
I have added the additional installation instructions in the vignette. I have also added links to the RaggedExperiment documentation in the package help page.

Regards,
Marcel

**Comment by lshep** [comment]
I will mark as accepted. Please leave the issue open and you will receive svn instructions via email shortly (normally within a week).  Thank you for you submission to bioconductor.

**Comment by LiNk-NY** [comment]
Thanks Martin @mtmorgan, Lori @lshep, and Michael @lawremi ! :smile:
