### ISSUE TITLE
KoinaR - R package to interface with Koina web service

### ISSUE THREAD

**Issue by LLautenbacher** [Bioconductor/Contributions#3392]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wilhelm-lab/koinar

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput ~~genomic~~ proteomics data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
**NEWS**

- [ ] Please have at least one news item.  New packages often use something
similar to 
```
Changes in version 0.99.0
- submitted to Bioconductor 
```

**General**

- [ ] I understand that this is establishing interactions with a novel API but
  it would be nice to see some interoperability with current Bioconductor class
  structure.  I see you reference sequences in the vignette. Is it possible to
  show an example utilizing the Biostrings class structures?

**Comment by LLautenbacher** [comment]
HI Ishep, thank you for looking into this. I added an example with OrgMassSpecR. Biostrings is mostly nucleotide sequences and as such not really relevant for our package.

Let me know if I should add anything else!

**Comment by LLautenbacher** [comment]
Hi @lshep is there something still missing for moving this along?

**Comment by lshep** [comment]
OrgMassSpecR is not a Bioconductor package.  Is there any Bioconductor workflows/infrastructure that this can tie into?

**Comment by lshep** [comment]
Any further comments on this?

**Comment by LLautenbacher** [comment]
Hi Ishep, sorry for the long stretch of inactivity. I was at a conference and then on vacation.
I could create another usage example using [rawrr](https://www.bioconductor.org/packages/release/bioc/html/rawrr.html). Would that be sufficient?

**Comment by lshep** [comment]
yes that would be sufficient

**Comment by LLautenbacher** [comment]
Hi Ishep, thank you for your patience! I just pushed a new version to my repo. I pivoted and decided to instead create an example using the [msdata](https://bioconductor.org/packages/release/data/experiment/html/msdata.html) and [Spectra](https://bioconductor.org/packages/release/bioc/html/Spectra.html) Bioconductor packages. I hope that is alright as well.

**Comment by LLautenbacher** [comment]
Hi @lshep, thank you for your help so far! Do you believe it is feasible to be included in this year's Autumn release of Bioconductor?

**Comment by DarioS** [comment]
KoinaR is an R package for submitting queries to a server of models and receiving predictions. The interoperability with Bioconductor is low and the documentation is not clear and very small. The connection to Bioconductor is unclear.

- The Koina class has no `show` method. See [Class Design](https://contributions.bioconductor.org/r-code.html?q=show%20metrho#class-design). It floods the user's R console with a bulk of text.

```r
prosit2019
## Reference class object of class "Koina"
## Field "model_inputs":
## $peptide_sequences
## $peptide_sequences$shape
## $peptide_sequences$shape[[1]]
## [1] -1
## 
## $peptide_sequences$shape[[2]]
## [1] -1
## 
## 
## $peptide_sequences$datatype
## [1] "BYTES"
## 
## 
## $precursor_charges
## $precursor_charges$shape
## $precursor_charges$shape[[1]]
## [1] -1
## 
## $precursor_charges$shape[[2]]
## [1] 1
## 
## 
## $precursor_charges$datatype
## [1] "INT32"
## 
## 
## $collision_energies
## $collision_energies$shape
## $collision_energies$shape[[1]]
## [1] -1
## 
## $collision_energies$shape[[2]]
## [1] 1
## 
## 
## $collision_energies$datatype
## [1] "FP32"
## 
## 
## Field "model_outputs":
## $intensities
## $intensities$datatype
## [1] "FP32"
## 
## 
## $mz
## $mz$datatype
## [1] "FP32"
## 
## 
## $annotation
## $annotation$datatype
## [1] "BYTES"
## 
## 
## Field "batch_size":
## [1] 1000
## Field "response_dict":
## list()
## Field "model_name":
## [1] "Prosit_2019_intensity"
## Field "url":
## [1] "koina.wilhelmlab.org:443"
## Field "ssl":
## [1] TRUE
## Field "type_convert":
## $FP32
## [1] "float32"
## 
## $BYTES
## [1] "character"
## 
## $INT16
## [1] "integer"
## 
## $INT32
## [1] "integer"
## 
## $INT64
## [1] "integer"
```

For interoperability, most Bioconductor packages use S4 object-oriented system. Justify the necessity for using an R6 class.

- Remove package loading clutter by hiding package loading messages in R Markdown using `message = FALSE`.

```r
library(Spectra)
## Loading required package: S4Vectors
## Warning: package 'S4Vectors' was built under R version 4.4.1
## Loading required package: stats4
## Loading required package: BiocGenerics
## 
## Attaching package: 'BiocGenerics'
## The following objects are masked from 'package:stats':
## 
##     IQR, mad, sd, var, xtabs
## The following objects are masked from 'package:base':
## 
##     anyDuplicated, aperm, append, as.data.frame, basename, cbind,
##     colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
##     get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
##     match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
##     Position, rank, rbind, Reduce, rownames, sapply, setdiff, table,
##     tapply, union, unique, unsplit, which.max, which.min
## 
## Attaching package: 'S4Vectors'
## The following object is masked from 'package:utils':
## 
##     findMatches
## The following objects are masked from 'package:base':
## 
##     expand.grid, I, unname
## Loading required package: BiocParallel
## Loading required package: ProtGenerics
## 
## Attaching package: 'ProtGenerics'
## The following object is masked from 'package:stats':
## 
##     smooth
```

- Instead of `data.frame` in base R, Bioconductor has its own `DataFrame` in [S4Vectors](https://bioconductor.org/packages/release/bioc/html/S4Vectors.html). KoinaR lacks interoperability with `DataFrame` objects. Again, the usefulness and relatedness to Bioconductor is unclear.

```r
> input <- DataFrame(peptide_sequences = c("LGGNEQVTR", "GAGSSEPVTGLDAK"),
                     collision_energies = c(25, 25),
                     precursor_charges = c(1, 2))
> prediction_results <- prosit2019$predict(input)
Error in if (max <= min) stop("must have 'max' > 'min'") : 
  argument is of length zero
```

- The package purpose is "AI models for life science research accessible". However, the vignette delves into technical mass spectrometry concepts without explanation. The vigentte is inadequately written as a series of R code chunks without explanatory paragraphs between them. There code is presented sequentially, without motivation of the biological question the example is trying to address. What "life science research" other than mass spectrometry does KoinaR support?

- A package's examples should work without internet access. See [Other Data](https://contributions.bioconductor.org/data.html?q=access#other-data).

- Inconsistent parameter naming style. For example, `pred_prosit`, `top.lab`. For consistency between Bioconductor packages, please use camelCase according to [Function Development](https://contributions.bioconductor.org/r-code.html?q=camelCase#function-development).

- Installation instructions should appear near the beginning of the vignette, after Introduction. See [Installation](https://contributions.bioconductor.org/docs.html#installation).

- Don't use `for` loops. Use vectorised loops such as `vapply` or `lapply`. See [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize).

**Comment by vjcitn** [comment]
I would agree with Dario that more documentation is needed, especially at the highest level.  Koina is a web service that "democratizes machine learning in proteomics".  That's pretty broad.   KoinaR mediates between R users and the web service.  For a Bioconductor user the relevant issues would be relations between the classes used in proteomics and the values returned by the service.  Can a function on an MSnSet push data to the service and return information readily that can be readily combined with the input?  Does the package also simplify the creation of or use of completely de novo DL/ML functions, even written in R?  Improved substantive content in your README and your DESCRIPTION are necessary to help reviewers and users understand the scope and limits of your offering.

**Comment by LLautenbacher** [comment]
Thank you for your valuable feedback! Please excuse the limited adherence of the package to Bioconductor coding style guidelines. I started developing this package with the intention to publish on CRAN not Bioconductor. Only after the package was done and talking with my co-author he motivated me to publish via Bioconductor, to improve visibility ot the proteomics community. 

@DarioS 
**The Koina class has no show method. See [Class Design](https://contributions.bioconductor.org/r-code.html?q=show%20metrho#class-design). It floods the user's R console with a bulk of text.**
Thank you for pointing this out! I implemented a show function.


**For interoperability, most Bioconductor packages use S4 object-oriented system. Justify the necessity for using an R6 class.**
I have only limited familiarity with the R class system. Coming from a background of using mostly python I found the structure enabled by `setRefClass` to be easiest to understand and make work. I could attempt to rewrite this as an S4 class but the benefit of this is not clear to me. The [documentation](https://contributions.bioconductor.org/r-code.html?q=show%20metrho#class-design) only says it is preferred without giving an explanation. I also reached out on the Bioconductor Slack channel, so far the responses encouraged a discussion about this. 
Inline with the suggestions on Slack i added a helper function `predictWithKoinaModel` to give people the option to use pass-by-value or pass-by-reference syntax. In case the lack of this option motivated this comment.


**Remove package loading clutter by hiding package loading messages in R Markdown using message = FALSE.**
Thank you for pointing this out! I implemented your fix for this issue.


**Instead of data.frame in base R, Bioconductor has its own DataFrame in [S4Vectors](https://bioconductor.org/packages/release/bioc/html/S4Vectors.html). KoinaR lacks interoperability with DataFrame objects. Again, the usefulness and relatedness to Bioconductor is unclear.**
I added support for the Bioconductor DataFrame class.


**The package purpose is "AI models for life science research accessible". However, the vignette delves into technical mass spectrometry concepts without explanation. The vigentte is inadequately written as a series of R code chunks without explanatory paragraphs between them. There code is presented sequentially, without motivation of the biological question the example is trying to address. What "life science research" other than mass spectrometry does KoinaR support?**
Thank you for pointing this out! I gave the vignette a major overhaul, attempting to motivate more what the KoinaR package is useful for. I also updated the package title and description to bring it in line with the current capabilities of KoinaR.


**A package's examples should work without internet access. See [Other Data](https://contributions.bioconductor.org/data.html?q=access#other-data).**
I started to use httptest to to enable offline use of the tests and vignette.


**Inconsistent parameter naming style. For example, pred_prosit, top.lab. For consistency between Bioconductor packages, please use camelCase according to [Function Development](https://contributions.bioconductor.org/r-code.html?q=camelCase#function-development).**
Both my package and the vignette use exclusively snake_case (an unfortunate byproduct of my python background) the `top.lab` you mention is part of a package I use as part of the vignette. Since the only interfaces required for a user of my package are the `Koina` class and its `predict` function, both of which would not change in style. The benefit of renaming all internally used variables to camelCase seems disproportionate to the required work. I also added the the function `predictWithKoinaModel` in camelCase according with Bioconductor preferences.


**Installation instructions should appear near the beginning of the vignette, after Introduction. See [Installation](https://contributions.bioconductor.org/docs.html#installation).**
I moved the installation instructions, to the beginning of the vignette.


**Don't use for loops. Use vectorised loops such as vapply or lapply. See [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize).**
I switched to using vectorized loops.

@vjcitn
**For a Bioconductor user the relevant issues would be relations between the classes used in proteomics and the values returned by the service. Can a function on an MSnSet push data to the service and return information readily that can be readily combined with the input?**
Thank you for the suggestion! I am not familiar with MSnSet, as such, it is not supported. The aim of this package is to be a low-level, lightweight interface, and in my eyes, it should only take care of client-server communication. I would like to avoid custom integrations with several packages in favor of a generic easy-to-use interface. Instead of integrating MSnBase into KoinaR, I would prefer to integrate KoinaR into MSnBase. To enable the developers of other packages to also make use of KoinaR. This also allows similar designs with client packages developed in other languages (at the moment, only Python). So users can use similar syntax regardless of language used.


**Does the package also simplify the creation of or use of completely de novo DL/ML functions, even written in R?** 
Koina can host any model that can be compiled into TensorRT, ONNX, TensorFlow, PyTorch, OpenVINO, Python, DALI, FIL, vLLM if the model developed in R can be compiled in any of these, it can be run. But this is unrelated to this package. It is exclusively used to fetch predictions from the server.


**Improved substantive content in your README and your DESCRIPTION are necessary to help reviewers and users understand the scope and limits of your offering.**
I updated both the README, DESCRIPTION, and vignette to give users a better overview of the capabilities and limitations of KoinaR.

**Comment by DarioS** [comment]
> Instead of integrating MSnBase into KoinaR, I would prefer to integrate KoinaR into MSnBase.

Should this review be transferred to Laurent Gatto for his consideration?

**Comment by vjcitn** [comment]
@LLautenbacher What is meant by "integrate KoinaR into MSnBase"?  Please clarify.

**Comment by cpanse** [comment]
As Ludwig mentioned, the package serves as a low-level interface to the prediction service and is not confined to the proteomics domain. Fragment ion and retention time prediction are merely examples of its application. In my opinion, integration into environments such as MSnbase or Spectra, for instance, should be managed through backend packages similar to MsBackendMzR, MsBackendSQL, and others. C

**Comment by cpanse** [comment]
Additionally, I would like to highlight that Wassim presented this work at the [EuroBioC 2023 meeting](https://eurobioc2023.bioconductor.org/schedule/). If there are any concerns, wouldn't addressing them during the developer meetings be more appropriate? That was the primary reason for attending and presenting the work there ahead of time.

**Comment by wolski** [comment]
@DarioS  'setRefClass' is not R6 but an extension of S4 and is widely used in Bioconductor
e.g. https://github.com/search?q=org%3ABioconductor%20setRefClass&type=code

**Comment by LLautenbacher** [comment]
If you are interested and want more background information. We have a [preprint](https://www.biorxiv.org/content/10.1101/2024.06.01.596953v1.full) describing Koina.

**Comment by DarioS** [comment]
Yes, some Bioconductor packages use `setRefClass`, but it is used for internal code that is not seen by a package user. For example, Rsamtools has:
```r
.BamFile <- setRefClass("BamFile", contains="RsamtoolsFile",
.BcfFile <- setRefClass("BcfFile", contains="RsamtoolsFile",
.TabixFile <- setRefClass("TabixFile", contains="RsamtoolsFile")
exportPattern("^[^\\.]")
```
In other words, only those package components not starting with `.` are exported. In contrast, KoinaR's design uses R5 reference classes as user-facing elements. I will defer this to Vincent Carey.

It seems that `min_intensity` is a fixed parameter of the `predict` method. `min_intensity` is specific to mass spectrometry data. Can KoinaR be used for other data sets or must the input data have an `intensities` variable? I wonder if, in the Examples section of the class documentation, adding a simple example of Koina being used on `data(iris)` to predict whether a flower is Setosa, Versicolor or Virginica would help to demonstrate that is a general-purpose machine learning package.
```r
predict = function(input_data, pred_as_df = TRUE, min_intensity = 1e-5)
...    ...
if (pred_as_df) {return(format_predictions(results, data.frame(input_data), min_intensity))
...    ...
format_predictions = function(predictions, input_df, min_intensity = 1e-4)
...    ...
df <- df[df$intensities > min_intensity, ]
```

If a `data.frame` has thousands of rows, it will flood the user's R console with output. Please utilise the [DataFrame](https://www.bioconductor.org/packages/release/bioc/vignettes/S4Vectors/inst/doc/S4VectorsOverview.html#list-like-objects) class.
```r
> class(prediction_results)
  "data.frame"
```
`DataFrame`'s `show` method automatically adapts its output to the number of rows of results.

The vignette needs minor spell-checking. For example, "predicitng", "sampe".

**Comment by LLautenbacher** [comment]
@vjcitn What is your opinion on using `setRefClass`? Is there a reason why I should avoid this?

@DarioS
You are correct `min_intensity` is too specific of a variable. I added a generic `filter`  instead, a list of vectors. The names need to match the output that should be filtered. The first value is the minimum, and the second is the maximum. If there is no prediction that matches the filter, the filter is ignored. The new default value to accommodate the most common use case so far is now `list("intensities" = c(1e-4, 1)))`.

I adjusted the data frame return statement to match the datatype that is used as input. If you use `DataFrame`, you get a `DataFrame`. If you use `data.frame`, you get a `data.frame`.

**Comment by LLautenbacher** [comment]
@vjcitn and @DarioS thank you for your help so far. 
Do you think it's possible to finish the review before October 23rd so the package is part of the Bioconductor 3.20 release?

**Comment by vjcitn** [comment]
I am sorry for delay in commenting on R5.  I would say that if the functions are clearly documented with working examples so that a user knows how to use them, it would be fine.  However, you might gain usability by wrapping the R5-dependent tasks in ordinary functions.

**Comment by LLautenbacher** [comment]
I already added a convenience function `predictWithKoinaModel`, which takes a created model and predicts with it. Do you mean by "R5-dependent tasks" that I adapt this function to create the model instance within the function? If you think that is more user-friendly for people familiar with R, I would be happy to do that!

```R
predictWithKoinaModel <- function(koina_model, input) {
  return(koina_model$predict(input))
}
```

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LLautenbacher.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("koinar")`. The package 'landing page' will be created at

https://bioconductor.org/packages/koinar

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
