### ISSUE TITLE
MS2extract

### ISSUE THREAD

**Issue by DanielQuiroz97** [Bioconductor/Contributions#3398]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CooperstoneLab/MS2extract

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lgatto** [comment]
Thank you for your submission. I have some general comments, before addressing the technical review of the package.

One important aspect we take into account when considering new packages is how they make use of existing data infrastructure. I see that you used `MSnbase::readMsData()` to parse the raw (mzML, mzXML) data using (by default) the in-memory backend.

1. Are you aware of the [R for Mass Spectrometry packages](https://www.rformassspectrometry.org/) (RforMS), and in particular the Bioconductor [Spectra](https://bioconductor.org/packages/release/bioc/html/Spectra.html) package? Spectra, and the other RforMS packages represent are developed by the core MSnbase team, re-using what worked well in MSnbase, and replacing/improving what didn't work that well. MSnbase isn't going to be deprecated any time soon, but I would suggest to use `Spectra::Spectra()` rather than `MSnbase::readMsData()`.

2. I see that you are exporting data to mgf and msp. This functionality is available as part of RforMS, and more specifically the [MsBackendMgf](https://bioconductor.org/packages/release/bioc/html/MsBackendMgf.html) and [MsBackendMsp](https://bioconductor.org/packages/release/bioc/html/MsBackendMsp.html) backends, that integrate directly with `Spectra`.

3. Will you approach scale to larger dataset? Using an in-memory approach and converting the data into a tibble won't work for modern shotgun data. The small example data you provide is only composed of 9 MS2 scans, and generates a tibble with 24249 rows. Have you considered using our dedicated classes that would (1) make it possible to handle larg data and (2) benefit from the existing input and output capabilities (see point 2).

```
  library(Spectra)
  ProcA2_file <-
      system.file("extdata",
                  "ProcyanidinA2_neg_20eV.mzXML",
                  package = "MS2extract")
  ## load the raw data, extract based on retention time and precursor
  ## MZ, ...
  Spectra(ProcA2_file) |>
      filterRt(c(163, 180)) |>
      filterPrecursorMzRange(c(575.119, 575.120)) ## |> ...
```

4. As a side note, using the RforMS infrastructure will provide you with lazy and parallel evaluation for free.

**Comment by lshep** [comment]
@DanielQuiroz97  did you have any responses and updates to the comments above?

**Comment by DanielQuiroz97** [comment]
Dear All,

Thank you so much for taking the time to go over MS2extract.
Please find my comments for the presented topics:

* In contrast with the suggested packages (mzR, MSnbase) that are based on OOP, I am continuing tidy data principles first proposed in the TidyMass project ([link](https://www.tidymass.org)). I am conscious that when dealing with MS data, using tidy data might not be the best choice, but. MS2extract is designed to select only one scan per analyte (reference MS/MS spectra). Therefore reducing redundancy and not keeping everything in memory.

* Yes, exporting *.mgf* files is supported in those files, but MS2extract was designed to be compatible with GNPS for batch upload MS/MS libraries and GNPS requieres the library to have a specific format ([link](https://www.google.com/search?client=safari&rls=en&q=gnps+batch+upload&ie=UTF-8&oe=UTF-8)). Therefore, the suggested functions does not support GNPS compatibility. We would like to have this feature so the mass spectrometry community can use MS2extract to create MS/MS libraries and be able to upload to GNPS, one of the main platforms for compound identification. This feature was extensively tested and one of our databases, which was created with MS2extract (PhenolicsDB),is currently in GNPS libraries repository ([link](https://external.gnps2.org/gnpslibrary)).


Please let me know if these comments provide more clarification about MS2extract implementation decisions. I am more than happy to provide more information.

I hope I was able to provide the novelty and MS2extract and the potential positive impact in data democratization of MS/MS libraries.

Best,
Daniel

**Comment by jorainer** [comment]
just chiming in to clarify - `MsBackendMgf` has full GNPS support. The `spectraVariableMapping()` allows to define how certain *spectra variables* from `Spectra` are translated/renamed to MGF data fields. This allows to create GNPS compliant MGF files.

But yes, *MsBackendMgf* does not support batch upload of data to GNPS.

**Comment by jorainer** [comment]
Talking about "in house library creation" - maybe it would also be worthwhile to have a look at the [CompounDb](https://github.com/RforMassSpectrometry/CompoundDb) Bioconductor package - that package allows creation, managing and use of (in house and/or public) small compound annotation databases. And it has full support for the *Spectra* infrastructure. - including access of the full data as a `Spectra` object and related export of MS2 data as MGF file(s).

I understand that you want to adhere to tidy concepts, but maybe a combination of re-using the (IMHO) powerful *Spectra*-based framework and tidy concepts might be preferable/more powerful? This could reduce the need to re-implement existing functionality.

**Comment by lgatto** [comment]
Thank you, @jorainer, for clarifying the GNPS point.

Regarding:

> In contrast with the suggested packages (mzR, MSnbase) that are based on OOP, I am continuing tidy data principles first proposed in the TidyMass project ([link](https://www.tidymass.org/)). I am conscious that when dealing with MS data, using tidy data might not be the best choice, but. MS2extract is designed to select only one scan per analyte (reference MS/MS spectra). Therefore reducing redundancy and not keeping everything in memory.

The Bioconductor project emphasises the systematic re-use S4 classes, to promote interoperability and data consistency. This is an important request we have for new packages, and is paramount for Bioconductor packages. We feel that packages that prefer not to use these classes are probably a better fit for CRAN or, in your case, the tidymass project.

**Comment by lgatto** [comment]
Hi @DanielQuiroz97 - I will close this issue for now due to inactivity. Feel free to re-open it if needed to continue the discussion and/or if you think a contribution to the Bioconductor project is still relevant.
