### ISSUE TITLE
Differentially Expressed Heterogeneous OverDispersion Gene Test

### ISSUE THREAD

**Issue by ahshen26** [Bioconductor/Contributions#3408]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ahshen26/DEHOGT

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by PeteHaitch** [comment]
This isn't provided as a properly structured R package. 
The only script (https://github.com/arlinashen/DEHOGT/blob/main/DEHOGT_method.R) wraps existing Bioconductor functionality, making the actual analysis opaque.

**Comment by ahshen26** [comment]
Hi sorry, I have updated the code. I included some libraries from already existing Bioconductor packages that I didn't use in the function, I have removed those now. The function uses genomics-specific data structures and analyses, statistical modeling capabilities, which are enhanced with parallel processing to manage the demands of large genomic datasets. This makes the function quite powerful and flexible, suitable for advanced users who need to customize their differential expression analysis workflows beyond standard DESeq2 pipelines.

**Comment by vjcitn** [comment]
The code in your repo does not form an R package.  Please see https://contributions.bioconductor.org/ ... reopen when you have a package that can be installed and that passes R CMD check.  Thank you!

**Comment by ahshen26** [comment]
> The code in your repo does not form an R package. Please see https://contributions.bioconductor.org/ ... reopen when you have a package that can be installed and that passes R CMD check. Thank you!

Hi I have adjusted the package so that it passes R CMD check. Could you reopen this for me? I tried to re-submit my package but it says that it is currently linked to this issue.

**Comment by lshep** [comment]
Please read the the links we have provided now multiple times:  https://contributions.bioconductor.org/  .  And please run not only R CMD check but BiocCheck as you have indicated you have on submission.  The checks would clearly fail.  You are missing key features that are requirements of Bioconductor packages.  Specifically re-using Bioconductor class structures (as none are defined in your DESCRIPTION), including system files that should not be tracked,  and missing a vignette.   https://contributions.bioconductor.org/important-bioconductor-package-development-features.html

**Comment by lshep** [comment]
may we expect updates soon?

**Comment by ahshen26** [comment]
> may we expect updates soon?

Hi, we've decided to publish this package to CRAN instead, thank you!
