### ISSUE TITLE
ATACseqQC

### ISSUE THREAD

**Issue by jianhong** [Bioconductor/Contributions#342]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jianhong/ATACseqQC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by jianhong** [comment]
This package is renamed ATACqc.

**Comment by hpages** [comment]
I'm re-assigning this package to me since this is a re-submission of package ATACqc (https://github.com/Bioconductor/Contributions/issues/332) under a new name ATACseqQC

**Comment by hpages** [comment]
Hi Jianhong Ou,
I get the following error when trying to build the package (I'm on Linux):
```
hpages@latitude:~$ R CMD build ATACseqQC 
* checking for file ‘ATACseqQC/DESCRIPTION’ ... OK
* preparing ‘ATACseqQC’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
See system.file("LICENSE", package="MotifDb") for use restrictions.
Quitting from lines 110-120 (ATACseqQC.Rmd) 
Error: processing vignette 'ATACseqQC.Rmd' failed with diagnostics:
is(conservation, "PhastConsDb") is not TRUE
Execution halted

real	1m44.413s
user	0m53.804s
sys	0m1.366s
```
Can you please look into this?
Thanks,
H.

**Comment by jianhong** [comment]
Hi @hpages ,

I updated the package according the error. PhastConsDb is changed to GScores.

**Comment by hpages** [comment]
Hi Jianhong Ou,

Thanks for reducing the dependencies and the time it takes to build the vignette. However, running the code in the vignette or in some of the examples still uses about 4.5 Gb of RAM. It would be great if you could reduce this a little, ideally to <  2 Gb. Otherwise we'll have to mark the package as unsupported on 32-bit Windows.

Other than that, the package is in good shape. The next Bioconductor release is in 5 days so we don't have much time left. Hopefully you can do something about memory usage. I would need to hear back from you before Saturday night. 

Thanks,
H.

**Comment by jianhong** [comment]
Hi @hpages ,

I tried my best. Hope this time the RAM issue could be fixed. Thank you.

**Comment by hpages** [comment]
Hi Jianhong Ou,

Looks like you managed to reduce memory usage to < 2 Gb. Excellent! Thanks a lot for doing that.
I'm marking the package as accepted.

Best,
H.
