### ISSUE TITLE
(inactive) SpatialDeX

### ISSUE THREAD

**Issue by lchengy1024** [Bioconductor/Contributions#3422]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wang-lab/SpatialDeX

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment]
Thanks for this submission!

Title: What the Package Does (Title Case) should not be used as the Title field in DESCRIPTION

The Import of copykat may be problematic because the package is not in CRAN or bioconductor.  See the last clause of section 1.1 at https://contributions.bioconductor.org/bioconductor-package-submissions.html ... you may wish to encourage the copykat developer to contribute the package to CRAN or Bioconductor, or remove the role of copykat from your package.

**Comment by lshep** [comment]
**General**

- [ ] All packages must be on CRAN or Bioconductor. copykay does not appear to fit this criteria.  You will not be able to list it as a dependency or utilize it in the package until it is on CRAN or Bioconductor 

**License**

- [ ] You include GPL-3 but list GPL-2 in the DESCRIPTION. Please update to 3 in
  the description

**inst**

- [ ] Please include an `inst/script` directory that documents how the data in
  extdata was generated. Include relevant source and licensing information. This
  can be text, psuedo code, or code.

**Comment by lshep** [comment]
May we expect any updates soon?

**Comment by lchengy1024** [comment]
Hello,

Sorry for the delay. We are working on encouraging the copykat developer to
contribute the package to CRAN or Bioconductor. However it may unlikely to
happen. Is there alternative option to solve this issue? Thank you.

Best,
Xinyi

**Comment by lshep** [comment]
Unfortunately all packages must be on CRAN or Bioconductor. If copykat is unwilling to submit you could check on their licensing and include the functionality directly in your package, only if proper credit is given to original authors. Otherwise it must be removed from the package to be included in Bioconductor.

**Comment by lchengy1024** [comment]
Thank you for your advice. We will check the license.

**Comment by lshep** [comment]
Has there been any progress on this?
