### ISSUE TITLE
(inactive) biotidy

### ISSUE THREAD

**Issue by Yunuuuu** [Bioconductor/Contributions#3478]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Yunuuuu/biotidy

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lgatto** [comment]
Chiming in here, as I was browsing recent submissions. We typically ask to describe other relevant packages already in Bioconductor in the vignette introduction. In this particular case, it didn't see any mention of/comparison with the Bioconductor [tidyomics](https://github.com/tidyomics) project.

**Comment by Yunuuuu** [comment]
Thank you for your comment. I have briefly reviewed the `tidyomics` project, which primarily utilizes a pipe-based workflow for managing bioinformatic objects. It is important to note that `biotidy` serves a different purpose compared to `tidyomics`. `biotidy` specifically provides a method for extracting a data frame from bioinformatic objects, similar to how the `broom::tidy` function operates on statistical model objects.

**Comment by lshep** [comment]
If this is not in the vignette I think it would be useful to add this distinction so it is clearly known.

**Comment by Yunuuuu** [comment]
Thanks for your suggestion, I have added it into the `vignette`.

**Comment by Yunuuuu** [comment]
The package utilizes S3 methods and incorporates all dependencies in the Suggests field, leading to a warning. In my opinion, the S3 method is the most suitable approach for this package.

**Comment by PeteHaitch** [comment]
Hi @Yunuuuu ,

Before I go any further with my review, you state in the vignette that "The inspiration for biotidy came from the functionality of the scuttle::makePerCellDF".
When then does `biotidy::makePerCellDF(mocked_sce)` give completely different output to `scuttle::makePerCellDF(mocked_sce)`?

``` r
library(biotidy)
mocked_sce <- mockSCE()
a <- biotidy::makePerCellDF(mocked_sce)
b <- scuttle::makePerCellDF(mocked_sce)
dim(a)
#> [1]  200 2103
dim(b)
#> [1] 200   3
a[1:5, 1:3]
#>         Gene0001 Gene0002 Gene0003
#> Cell001       15        0        0
#> Cell002       23       12       17
#> Cell003        0        0      347
#> Cell004       20       66       26
#> Cell005        2        0       62
b[1:5, 1:3]
#>         Mutation_Status Cell_Cycle Treatment
#> Cell001        positive         G0    treat2
#> Cell002        negative          S    treat1
#> Cell003        negative        G2M    treat1
#> Cell004        positive          S    treat1
#> Cell005        negative         G0    treat1
```

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.4.1 (2024-06-14)
#>  os       macOS Sonoma 14.5
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Australia/Melbourne
#>  date     2024-08-14
#>  pandoc   3.2 @ /usr/local/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package              * version date (UTC) lib source
#>  abind                  1.4-5   2016-07-21 [1] CRAN (R 4.4.0)
#>  beachmat               2.21.5  2024-07-26 [1] Bioconductor 3.20 (R 4.4.1)
#>  Biobase                2.65.0  2024-05-04 [1] Bioconductor 3.20 (R 4.4.0)
#>  BiocGenerics           0.51.0  2024-05-04 [1] Bioconductor 3.20 (R 4.4.0)
#>  BiocParallel           1.39.0  2024-05-04 [1] Bioconductor 3.20 (R 4.4.0)
#>  biotidy              * 0.99.0  2024-08-14 [1] Bioconductor
#>  cli                    3.6.3   2024-06-21 [1] CRAN (R 4.4.0)
#>  codetools              0.2-20  2024-03-31 [1] CRAN (R 4.4.1)
#>  crayon                 1.5.3   2024-06-20 [1] CRAN (R 4.4.0)
#>  DelayedArray           0.31.11 2024-08-04 [1] Bioconductor 3.20 (R 4.4.1)
#>  digest                 0.6.36  2024-06-23 [1] CRAN (R 4.4.0)
#>  evaluate               0.24.0  2024-06-10 [1] CRAN (R 4.4.0)
#>  fastmap                1.2.0   2024-05-15 [1] CRAN (R 4.4.0)
#>  fs                     1.6.4   2024-04-25 [1] CRAN (R 4.4.0)
#>  GenomeInfoDb           1.41.1  2024-05-24 [1] Bioconductor 3.20 (R 4.4.0)
#>  GenomeInfoDbData       1.2.12  2024-03-28 [1] Bioconductor
#>  GenomicRanges          1.57.1  2024-06-12 [1] Bioconductor 3.20 (R 4.4.1)
#>  glue                   1.7.0   2024-01-09 [1] CRAN (R 4.4.0)
#>  htmltools              0.5.8.1 2024-04-04 [1] CRAN (R 4.4.0)
#>  httr                   1.4.7   2023-08-15 [1] CRAN (R 4.4.0)
#>  IRanges                2.39.2  2024-07-17 [1] Bioconductor 3.20 (R 4.4.1)
#>  jsonlite               1.8.8   2023-12-04 [1] CRAN (R 4.4.0)
#>  knitr                  1.48    2024-07-07 [1] CRAN (R 4.4.0)
#>  lattice                0.22-6  2024-03-20 [1] CRAN (R 4.4.1)
#>  lifecycle              1.0.4   2023-11-07 [1] CRAN (R 4.4.0)
#>  Matrix                 1.7-0   2024-04-26 [1] CRAN (R 4.4.1)
#>  MatrixGenerics         1.17.0  2024-05-04 [1] Bioconductor 3.20 (R 4.4.0)
#>  matrixStats            1.3.0   2024-04-11 [1] CRAN (R 4.4.0)
#>  R6                     2.5.1   2021-08-19 [1] CRAN (R 4.4.0)
#>  Rcpp                   1.0.13  2024-07-17 [1] CRAN (R 4.4.0)
#>  reprex                 2.1.1   2024-07-06 [1] CRAN (R 4.4.0)
#>  rlang                  1.1.4   2024-06-04 [1] CRAN (R 4.4.0)
#>  rmarkdown              2.27    2024-05-17 [1] CRAN (R 4.4.0)
#>  rstudioapi             0.16.0  2024-03-24 [1] CRAN (R 4.4.0)
#>  S4Arrays               1.5.7   2024-08-06 [1] Bioconductor 3.20 (R 4.4.1)
#>  S4Vectors              0.43.2  2024-07-17 [1] Bioconductor 3.20 (R 4.4.1)
#>  scuttle                1.15.2  2024-07-17 [1] Bioconductor 3.20 (R 4.4.1)
#>  sessioninfo            1.2.2   2021-12-06 [1] CRAN (R 4.4.0)
#>  SingleCellExperiment   1.27.2  2024-05-24 [1] Bioconductor 3.20 (R 4.4.0)
#>  SparseArray            1.5.31  2024-08-04 [1] Bioconductor 3.20 (R 4.4.1)
#>  SummarizedExperiment   1.35.1  2024-06-28 [1] Bioconductor 3.20 (R 4.4.1)
#>  UCSC.utils             1.1.0   2024-05-04 [1] Bioconductor 3.20 (R 4.4.0)
#>  withr                  3.0.1   2024-07-31 [1] CRAN (R 4.4.0)
#>  xfun                   0.46    2024-07-18 [1] CRAN (R 4.4.0)
#>  XVector                0.45.0  2024-05-04 [1] Bioconductor 3.20 (R 4.4.0)
#>  yaml                   2.3.10  2024-07-26 [1] CRAN (R 4.4.0)
#>  zlibbioc               1.51.1  2024-06-05 [1] Bioconductor 3.20 (R 4.4.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by PeteHaitch** [comment]
Also, the examples produce way too much output. 
``` r
library(biotidy)
# First example from ?biotidy::makePerCellDF
mocked_se <- mockSE()
makePerCellDF(mocked_se)
#>         Gene0001 Gene0002 Gene0003 Gene0004 Gene0005 Gene0006 Gene0007 Gene0008
#> Cell001        0       55       34        0       16      129      310     1266
#> 
#> <thousands of lines of output excluded>
#>  [ reached 'max' / getOption("max.print") -- omitted 151 rows ]
```

This is either causing or masking the cause of the failure when I run `R CMD check biotidy_0.99.0.tar.gz` on my system (macOS):

```
cat /Users/peter/GitHub/biotidy/biotidy.Rcheck/00check.log
* using log directory ‘/Users/peter/GitHub/biotidy/biotidy.Rcheck’
* using R version 4.4.1 (2024-06-14)
* using platform: aarch64-apple-darwin20
* R was compiled by
    Apple clang version 14.0.0 (clang-1400.0.29.202)
    GNU Fortran (GCC) 12.2.0
* running under: macOS Sonoma 14.5
* using session charset: UTF-8
* checking for file ‘biotidy/DESCRIPTION’ ... OK
* this is package ‘biotidy’ version ‘0.99.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘biotidy’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking code files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... ERROR
Running examples in ‘biotidy-Ex.R’ failed
The error most likely occurred in:

> ### Name: makePerCellDF
> ### Title: Create a per-cell data.frame
> ### Aliases: makePerCellDF makePerCellDF.SummarizedExperiment
> ###   makePerCellDF.SingleCellExperiment makePerCellDF.ExpressionSet
> ###   makePerCellDF.Seurat
> 
> ### ** Examples
> 
> # SummarizedExperiment method
> mocked_se <- mockSE()
> makePerCellDF(mocked_se)
        Gene0001 Gene0002 Gene0003 Gene0004 Gene0005 Gene0006 Gene0007 Gene0008
Cell001        0       18        0     1116       17     1572     1146       14
<thousands of lines of output excluded>
> # SingleCellExperiment method
> mocked_sce <- mockSCE()
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE
Status: 1 ERROR

**Comment by Yunuuuu** [comment]
Thank you for taking the time to review my package.

For added convenience, biotidy introduces several enhancements compared to scuttle:

 - By default, `biotidy` uses the first assay in a SummarizedExperiment, the exprs assay in an ExpressionSet, or the Default assay in Seurat objects, whereas `scuttle` defaults to using `logcounts`.
 - The `biotidy` package allows a single boolean value to be used in the `features` argument (the same with `use_altexps` argument). By default, this is set to TRUE, meaning all genes are included in the output. In contrast, scuttle does not include any genes by default.
``` r
library(biotidy)
mocked_sce <- mockSCE()
a <- biotidy::makePerCellDF(mocked_sce, use_altexps = FALSE)
b <- scuttle::makePerCellDF(mocked_sce,
    assay.type = "counts",
    features = rownames(mocked_sce)
)
a[1:5, 1:5]
#>         Gene0001 Gene0002 Gene0003 Gene0004 Gene0005
#> Cell001      376        0        0        0       63
#> Cell002      409       19       27        1      327
#> Cell003      274        0        0        0     1052
#> Cell004      463        0        0        0      814
#> Cell005      785        2       12        0      398
```

``` r
# note: scuttle put column meta data first, then the gene expression value, but `biotidy` put the gene expression value firstly
b[1:5, 1:5]
#>         Mutation_Status Cell_Cycle Treatment Gene0001 Gene0002
#> Cell001        positive         G0    treat2      376        0
#> Cell002        negative         G1    treat1      409       19
#> Cell003        negative         G1    treat2      274        0
#> Cell004        negative        G2M    treat2      463        0
#> Cell005        positive          S    treat2      785        2
```

``` r
setequal(names(a), names(b))
#> [1] TRUE
```

``` r
identical(a, b[names(a)])
#> [1] TRUE
```

<sup>Created on 2024-08-25 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by PeteHaitch** [comment]
My broader point is that since you are inspired by an existing Bioconductor function, and using the same function name, then as a user has a reasonable expectation that the default output of your new function is identical to that of the old function[^1].
A simple alternative is to use different names for your functions (e.g., `SEToDFByCell()` and `SEToDFByFeature()`?) and to acknowledge the inspiration provided by `scuttle::makePerCellDF()` and `scuttle::makerPerFeatureDF()` in the documentation.

I'd also note that what you call "enhancements compared to scuttle" are what I'd call a different choice of defaults because it's not clear to me that one is better than the other.
In fact, I'd argue producing a _data.frame_ with all features is not a good default because it produces so much output and allocates a lot of memory in doing so.

[^1]: This expectation would be stronger if `makePerCellDF()` was a generic function, which it is not, but in general I think if you are 'mimicing' an existing function then it should have the same defaults to avoid this confusion.

**Comment by PeteHaitch** [comment]
Hi @Yunuuuu,

Since we haven't heard back from you for 3 months, we're going to close this issue.
You can post back here if you would like to discuss the issues raised in my pre-review.

Cheers,
Pete
