### ISSUE TITLE
SplineDV

### ISSUE THREAD

**Issue by Xenon8778** [Bioconductor/Contributions#3489]
Hello Bioconductor team,
I am submitting my R package {SplineDV} for consideration for Bioconductor release.

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Xenon8778/SplineDV

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
-  [ ] Please remove `inst/doc` these files should be generated automatically with R CMD build.  Also please remove vignettes/SplineDV.nb.html .    

- [ ] If you are working with Single cell data, your package should utilize SingleCellExperiment objects.  SingleCellExperiment is the main class structure utilized in Bioconductor.

**Comment by Xenon8778** [comment]
Hi, 

Thanks for your suggestions, I have removed the inst/doc directory and the removed vignettes/SplineDV.nb.html.
The package now uses SingleCellExperiment objects instead of Seurat.

Thanks

**Comment by Xenon8778** [comment]
> * [x]  Please remove `inst/doc` these files should be generated automatically with R CMD build.  Also please remove vignettes/SplineDV.nb.html .
> * [x]  If you are working with Single cell data, your package should utilize SingleCellExperiment objects.  SingleCellExperiment is the main class structure utilized in Bioconductor.

**Comment by lshep** [comment]
Please do not read data in that is solely hosted on github. The data (or an acceptable smaller subset if large) should be included in the package to use for examples and vignettes.

**Comment by Xenon8778** [comment]
Hi,

Thanks for the suggestion. The package now reads smaller data subsets ('.rda' files) stored in the data/ directory for vignettes and examples.

Thanks

**Comment by lshep** [comment]
The vignette is still referencing Seurat but we can move it forward to test on the build system.  When a reviewer is assigned they will be looking for documentation updates.

**Comment by DarioS** [comment]
- Vignette needs to have an Installation section. See [Installation](https://contributions.bioconductor.org/docs.html#installation).
- The vignette uses `eval = FALSE`. No code chunks are allowed to use `eval = FALSE`. Please see [Vignettes](https://contributions.bioconductor.org/docs.html?q=eval#vignettes).
- Don't use example data from Seurat. Please consider [scRNAseq](https://www.bioconductor.org/packages/release/data/experiment/html/scRNAseq.html) or [ExperimentHub](https://www.bioconductor.org/packages/release/bioc/html/ExperimentHub.html).
- Vignette defines a plotting function `getdensity`. Should be a documented function in the package.
- Use spaces around binary operators. For example, `CV <- SDs/Means` does not. See [Use of Space](https://contributions.bioconductor.org/r-code.html#use-of-space) in [R Code](https://contributions.bioconductor.org/r-code.html).
- Don't use `for` loops and append to empty lists but vectorise with `mapply`. See [Vectorize](https://contributions.bioconductor.org/r-code.html?q=vapply#vectorize).

```r
    Dist_HVG <- c()
    dvecx <- c()
    dvecy <- c()
    dvecz <- c()
    nearidx <- c()
    df <- as.matrix(xyz1)
    pb <- txtProgressBar(min = 0, max = nrow(xyz), initial = 0, style = 3)
    for (i in 1:nrow(xyz)){
```

- Inconsistent variable naming style. For example, `is.mito`, `qc_df`.  [Bioconductor requires camelCase](https://contributions.bioconductor.org/r-code.html?q=write#variable-names) for consistency.

- Result floods user's R console with output. 

```r
load(system.file("extdata", "WT_count.rda", package = "SplineDV")) # WT Sample
load(system.file("extdata", "KO_count.rda", package = "SplineDV")) # KO Sample
DV_res <- DV_splinefit(X = KO_count, Y = WT_count)
```

![image](https://github.com/user-attachments/assets/cf566dd3-712d-429a-95c5-a474a725eed9)

- Result is claimed to be `DataFrame` type. It is not. It is `data.frame`. Please make it `DataFrame`.

```
\value{
A DataFrame with DV Statistics
}
> class(DV_res)
  "data.frame"
```
- Package lacks unit tests. Please read [Chapter 14: Unit Tests](https://contributions.bioconductor.org/tests.html) and add some meaningful correctness tests.
- Don't stop execution on a warning. You probably meant to write `stop("Sample has too few genes.")`. You wrote:
```r
    warning('Sample has too few genes')
    stop()
```

**Comment by Xenon8778** [comment]
Hi @DarioS ,

Thank you for your review and comments! I had a few questions about the following suggestions - 

1. The vignette already has an installation section. This section is "eval=False" as mentioned in the Package manual. See [Installation (https://contributions.bioconductor.org/docs.html#installation). Do I need to make any changes here?
![image](https://github.com/user-attachments/assets/bce26c05-e800-4d82-bdb4-fac65eb9f09c)

3. No part in the vignette uses example data in the vignette. The file paths in the vignette are just dummy paths, hence these sections were kept eval=False. I just wanted to show users how to load data from Seurat in the vignette. Where should I put that in the vignette?

I am working on the other issue and will soon update the package. Thanks once again.

**Comment by DarioS** [comment]
Yes, should be

````
```
BiocManager::install("Xenon8778/SplineDV")
```
````


See [Data](https://contributions.bioconductor.org/data.html#data)
> When developing a software package, an excellent practice is to give a comprehensive illustration of the methods in the package using an existing [experiment data package](https://bioconductor.org/packages/release/BiocViews.html#___ExperimentData), [annotation data](https://bioconductor.org/packages/release/BiocViews.html#___AnnotationData) or data in the [ExperimentHub](https://bioconductor.org/packages/3.20/ExperimentHub) or [AnnotationHub](https://bioconductor.org/packages/3.20/AnnotationHub), or submitting new data to those resources yourself.

**Comment by Xenon8778** [comment]
Thank you. I'll incorporate the changes.

**Comment by Xenon8778** [comment]
Hi @DarioS,

The issues have been fixed-
- Vignette has an installation section.
![image](https://github.com/user-attachments/assets/9bf4a2b6-6126-4a9e-8d90-9fd11cae3a8c)

- No code chunks use eval=False.
- Examples from Seurat have been removed. The vignette uses only example data within the package.
- The plotting function is documented in the package.
- Spaces fixed.
- lapply is used instead of for loop
- All variable names with "." have been changed to one naming style that uses "_"
- Can't replicate "Result floods user's R console with output." Seems like you were printing the output data.frame instead of assigning it to a variable.
![image](https://github.com/user-attachments/assets/0778ceb1-c64a-44cd-a628-1f50cf684035)
- Unit tests included and Citation included.
- Executions now stop with stop()

Thanks! Hope to hear from you soon.

**Comment by DarioS** [comment]
- You converted the naming style to snake_case, not to camelCase.
- Results in the vignette don't have any explanation. Every plot or table should have a couple of sentences explaining what information the result reveals.
- If you vary parameters from default, explain why they should have a different value. For example,
```r
HVG_res <- HVG_splinefit(WT_count, nHVGs = 20, ncells = 3, ncounts = 200)
```
has no explanation why defaults are not used but different numbers are.
- Any data sets included in the package must have documentation pages in `man` folder. See [Data](https://contributions.bioconductor.org/data.html#raw-data-and-the-instextdata-directory).

**Comment by Xenon8778** [comment]
Hi @DarioS,

The issues have been fixed-

1. Naming style for objects has been converted to camelCase.
2. Results in the vignette describe every column in output data.frame and plot have a description now.
3. Parameter change has been justified in the vignette.
4. Datasets have been added to /data and package and vignette calls it from there.

Thanks for the suggestions! I look forward to hearing from you soon.

**Comment by DarioS** [comment]
- Example data loading needs to be realistic, using R functions a user would use to load their own data set.

```r
WTcount <- SplineDV::WTcount
KOcount <- SplineDV::KOcount
```
is not acceptable. See [LazyData](https://contributions.bioconductor.org/description.html?q=lazy#description-lazydata) section of developer's guide.

- There are plenty of single-cell RNA-seq data sets in Bioconductor already. Justify why you need a new one.

- Function documentation is often too brief and vague. For example,

```r
\value{
A data.frame with DV Statistics
}
\description{
Differential Variability analysis
}
```

Each description section should be at least a couple of sentences long and informative.

- Vignette states what the columns contain. This should be in the Rd files, not the vignette. For example,

> The splineDV result data.frame contains the following data:
> genes - Contains the name of the gene.
> mu1 - log1p(mean) expression of gene in test sample.
> mu2 - log1p(mean) expression of gene in control sample.
> CV1 - log1p(CV) expression of gene in test sample.
> CV2 - log1p(CV) expression of gene in control sample.
> drop1 - Dropout rate of gene in test sample.
> drop2 - Dropout rate of gene in control sample.
> dist1 - Distance of real gene statistics from nearest point on spline in test sample.
> dist2 - Distance of real gene statistics from nearest point on spline in control sample.

Vignette should contain a case study and biological interpretation of the output. It still lacks interpretation. For example,

```r
fig <- DVPlot(dvRes)
fig
# Then no interpretation but simply a new section titled Highly Variable Genes (HVGs) Using Spline-HVG.
```

- Bioconductor has `DataFrame` in [S4Vectors](https://bioconductor.org/packages/release/bioc/html/S4Vectors.html) for tabular data but SplineDV relies on `data.frame`.

```r
> dvRes <- DataFrame(dvRes)
> DVPlot(dvRes)
Error in vapply(all_objects, nrow, integer(1L), USE.NAMES = FALSE) :
  values must be length 1,
 but FUN(X[[2]]) result is length 0
```
Please improve interoperability with standard Bioconductor classes and read [Common Classes](https://contributions.bioconductor.org/important-bioconductor-package-development-features.html?q=interoperability#commonclass) section.

**Comment by Xenon8778** [comment]
Hi @DarioS,

1. The package contains no data now. The example data in Vignette now uses a dataset from the scRNAseq package.
2. Function documentation has been made more detailed wherever needed.
3. Output DataFrame descriptions have been moved from vignette to @return in the description.
4. Output tables are stored and read as DataFrame objects.
5. The vignette has been made more detailed.

I pushed a valid push but didn't receive a build report. Can you help me out with this issue?

**Comment by DarioS** [comment]
Almost there.
- Use `message = FALSE` in R Markdown options to avoid clutter.
![image](https://github.com/user-attachments/assets/280300c6-f642-4880-a349-b98bf18bcc54)
- Data fetching is done twice, unnecessarily, in section 4.1 and 5.1.

**Comment by Xenon8778** [comment]
Hi @DarioS,

Thanks for the suggestions.

- message = FALSE has been used.
- The second data fetching has been removed.

Hoping to hear from you soon!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Xenon8778.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SplineDV")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SplineDV

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
