### ISSUE TITLE
chevreuldata

### ISSUE THREAD

**Issue by whtns** [Bioconductor/Contributions#3491]
This is an experimentHub data package. Also pinging author @Bavanaa. This is a dependency for recently submitted package chevreul #3332

Update the following URL to point to the GitHub repository of
the package you wish to submit to Bioconductor

    Repository: https://github.com/whtns/chevreuldata

Confirm the following by editing each check box to '[x]'

    [ x] I understand that by submitting my package to Bioconductor,
    the package source and all review commentary are visible to the
    general public.

    [x ] I have read the Bioconductor [Package Submission](https://bioconductor.org/developers/package-submission/)
    instructions. My package is consistent with the Bioconductor
    [Package Guidelines](https://contributions.bioconductor.org/).

    [x ] I understand Bioconductor [Package Naming Policy](https://bioconductor.org/developers/package-submission/#naming) and acknowledge
    Bioconductor may retain use of package name.

    [ x] I understand that a minimum requirement for package acceptance
    is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS.
    Passing these checks does not result in automatic acceptance. The
    package will then undergo a formal review and recommendations for
    acceptance regarding other Bioconductor standards will be addressed.

    [ x] My package addresses statistical or bioinformatic issues related
    to the analysis and comprehension of high throughput genomic data.

    [x ] I am committed to the long-term maintenance of my package. This
    includes monitoring the [support site](https://support.bioconductor.org/) for issues that users may
    have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
    of developments in the Bioconductor community, responding promptly
    to requests for updates from the Core team in response to changes in
    R or underlying software.

    [x ] I am familiar with the [Bioconductor code of conduct](https://bioconductor.org/about/code-of-conduct/) and
    agree to abide by it.

I am familiar with the essential aspects of Bioconductor software
management, including:

    [ x] The 'devel' branch for new packages and features.
    [ x] The stable 'release' branch, made available every six
    months, for bug fixes.
    [ x] Bioconductor version control using [Git](http://bioconductor.org/developers/how-to/git/)
    (optionally [via GitHub](http://bioconductor.org/developers/how-to/git/sync-existing-repositories/)).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website](https://bioconductor.org/) to sign up.

**Comment by lshep** [comment]
This should be submitted as an additional package to the chevreul issue so they can be reviewed together.

**Comment by whtns** [comment]
Ok, thanks resubmitting on that issue
