### ISSUE TITLE
(inactive) EnsemblGenomes

### ISSUE THREAD

**Issue by js2264** [Bioconductor/Contributions#3499]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/js2264/EnsemblGenomes

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by js2264** [comment]
The package does not rely on any Bioconductor class per se, but is related to genomics projects. The idea here is (1) not to have to rely on AnnotationHub to recover references/annotations, but instead directly scrape Ensembl FTP servers, and (2) not provide any caching function, but instead directly expose the URL to locally download the file. I think this approach is helpful to people who are not necessarily versed in AnnotationHub or BiocFileCache, but just want to get a pair of files here and now. Do let me know if you think this should not belong to Bioconductor.

**Comment by lshep** [comment]
I still think it might be helpful to cache files when downloaded in some way shape or form.  If the web service is down, which we have experienced before with ensembl API's, the package will fail, and the end user will not be able to work even if they had downloaded a resource previously.   I like the idea of an on demand but would still strongly suggest a caching mechanism.     

It has been also noted that in certain environments, access to external resources via FTP protocol can be blocked by institutions or firewalls. Is that a concern at all? 

The vignette is very minimal.  I run your functions and get down to the last table 
```
> list_ensembl_files('amphiprion_percula', release = 'release-100')
ℹ Scanning taxons [release-100]...
✔ Taxon found: vertebrate [release-100]
# A tibble: 4 × 8
  date             release     taxon   collection species type  url   url_status
  <chr>            <chr>       <chr>   <lgl>      <chr>   <chr> <chr>      <int>
1 2020-03-04 22:28 release-100 verteb… NA         amphip… refe… http…        200
2 2020-03-04 22:28 release-100 verteb… NA         amphip… refe… http…        200
3 2020-03-04 22:28 release-100 verteb… NA         amphip… refe… http…        200
4 2020-03-16 00:31 release-100 verteb… NA         amphip… anno… http…        200

```
now what?   How do I actually download or retrieve the files?   

And while the package itself may not rely on Bioconductor classes per se...  it would be nice to show how to convert the downloaded files into a Bioconductor class structure for those that are familiar and to show how to seamlessly integrate into the Bioconductor ecosystem if desired.

**Comment by js2264** [comment]
Thank for your feedback. I'll add support for caching through BiocFileCache, and add extra information on how to import the downloaded files into Bioconductor workflows. 

Regarding access via FTP protocol, I don't think this should be an issue. All the queries are done through HTTP requests, and the recovered URLs are https://.... 

I'll ping you when I have implemented the mentioned features.

**Comment by lshep** [comment]
excellent. thank you

**Comment by lshep** [comment]
@js2264 just checking back in. Any progress?

**Comment by js2264** [comment]
Hi @lshep sorry I didn't have any time to work on this. Is it a problem to leave the issue open until I have more time to spend on this? I hope to get some time to work on that in ~ a week/10 days...

**Comment by lshep** [comment]
yes. thank you for the update

**Comment by lshep** [comment]
Just want to check in. The release is fast approaching

**Comment by lshep** [comment]
checking in. if this will take more time we can close the issue for now and you can message here to reopen when you have time to work on it
