### ISSUE TITLE
SpectraQL package to support MassQL on Bioconductor's mass spectrometry objects

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/Contributions#3525]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RforMassSpectrometry/SpectraQL

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
we are investigating an SSL issue on our builder;  this is likely on our end to fix.

**Comment by jianhong** [comment]
# Package 'SpectraQL' Review
Thank you for submitting your package to Bioconductor. The package passed check and build. It is in pretty good shape. I am looking for a bone in an egg now. Please try to answer the comments line by line when you are ready for a second review.
Code: Note: please consider; Important: must be addressed.

## R code
- [ ] NOTE: Vectorize: `for` loops present, try to replace them by `*apply` funcitons.
	* In file R/massql-parser.R:
		+ at line 171 found '    for (i in seq_len(l)) {'
- [ ] To avoid the `* NOTE: Avoid redundant 'stop' and 'warn*' in signal conditions` in BioCheck,
        could you please change the word `error` to other word in 
			- R/massql-parser.R (line 63, column 14)
- [ ] NOTE: Functional programming: code repetition.
	* repetition in `.filter`, `.what`, and `.where`
		+ in .filter
			- line 1:{
			- line 2:    res <- sub(".*?filter[[:space:]]*(.*?)[[:space:]]*(where.*|$)", 
			- line 3:        "\\1", x, ignore.case = TRUE)
			- line 4:    res[res == x] <- NA_character_
			- line 5:    res <- unlist(strsplit(res, split = "[[:space:]]*(and|AND)[[:space:]]*"))
			- line 6:    res[nchar(res) > 0 & !is.na(res)]
		+ in .what
			- line 1:{
			- line 2:    res <- sub(".*?query[[:space:]]*(.*?)[[:space:]]*(where.*|filter.*|$)", 
			- line 3:        "\\1", x, ignore.case = TRUE)
			- line 4:    res[res == x] <- NA_character_
			- line 5:    res
		+ in .where
			- line 1:{
			- line 2:    res <- sub(".*?where[[:space:]]*(.*?)[[:space:]]*(filter.*|$)", 
			- line 3:        "\\1", x, ignore.case = TRUE)
			- line 4:    res[res == x] <- NA_character_
			- line 5:    res <- unlist(strsplit(res, split = "[[:space:]]*(and|AND)[[:space:]]*"))
			- line 6:    res[nchar(res) > 0 & !is.na(res)]
	* repetition in `.translate_condition_ms2nl`, `.translate_condition_ms2prec`, `.translate_condition_peak_mz`, and `.translate_filter_mz_value`
		+ in .translate_condition_ms2nl
			- line 1:    function (...) 
			- line 2:    {
			- line 3:        parms <- list(...)[[1L]]
			- line 4:        nl <- numeric(0)
			- line 5:        ppm <- 0
			- line 6:        tolerance <- 0
			- line 7:        if (any(names(parms) == "MS2NL")) 
			- line 8:            nl <- as.numeric(.parse_or(parms["MS2NL"]))
			- line 9:        if (anyNA(nl)) 
			- line 10:            stop("Non-numeric value/s for 'MS2NL'")
			- line 11:        if (any(names(parms) == "TOLERANCEMZ")) 
			- line 12:            tolerance <- as.numeric(parms["TOLERANCEMZ"])
			- line 13:        if (is.na(tolerance)) 
			- line 14:            stop("Non-numeric value for 'TOLERANCEMZ'")
			- line 15:        if (any(names(parms) == "TOLERANCEPPM")) 
			- line 16:            ppm <- as.numeric(parms["TOLERANCEPPM"])
			- line 17:        if (is.na(ppm)) 
			- line 18:            stop("Non-numeric value for 'TOLERANCEPPM'")
			- line 19:        if (length(nl)) {
		+ in .translate_condition_ms2prec
			- line 1:    function (...) 
			- line 2:    {
			- line 3:        parms <- list(...)[[1L]]
			- line 4:        pmz <- numeric()
			- line 5:        ppm <- 0
			- line 6:        tolerance <- 0
			- line 7:        if (any(names(parms) == "MS2PREC")) 
			- line 8:            pmz <- as.numeric(.parse_or(parms["MS2PREC"]))
			- line 9:        if (anyNA(pmz)) 
			- line 10:            stop("Missing or non-numeric value(s) for 'MS2PREC'")
			- line 11:        if (any(names(parms) == "TOLERANCEMZ")) 
			- line 12:            tolerance <- as.numeric(parms["TOLERANCEMZ"])
			- line 13:        if (is.na(tolerance)) 
			- line 14:            stop("Non-numeric value for 'TOLERANCEMZ'")
			- line 15:        if (any(names(parms) == "TOLERANCEPPM")) 
			- line 16:            ppm <- as.numeric(parms["TOLERANCEPPM"])
			- line 17:        if (is.na(ppm)) 
			- line 18:            stop("Non-numeric value for 'TOLERANCEPPM'")
			- line 19:        if (length(pmz)) {
			- line 20:            ProcessingStep(filterPrecursorMzValues, ARGS = list(mz = pmz, 
		+ in .translate_condition_peak_mz
			- line 1:    function (..., msLevel = 2L, value = "MS2PROD") 
			- line 2:    {
			- line 3:        parms <- list(...)[[1L]]
			- line 4:        pmz <- numeric(0)
			- line 5:        ppm <- 0
			- line 6:        tolerance <- 0
			- line 7:        if (any(names(parms) == value)) 
			- line 8:            pmz <- as.numeric(.parse_or(parms[value]))
			- line 9:        if (anyNA(pmz)) 
			- line 10:            stop("Missing or non-numeric value(s) for '", value, 
			- line 11:                "'")
			- line 12:        if (any(names(parms) == "TOLERANCEMZ")) 
			- line 13:            tolerance <- as.numeric(parms["TOLERANCEMZ"])
			- line 14:        if (is.na(tolerance)) 
			- line 15:            stop("Non-numeric value for 'TOLERANCEMZ'")
			- line 16:        if (any(names(parms) == "TOLERANCEPPM")) 
			- line 17:            ppm <- as.numeric(parms["TOLERANCEPPM"])
			- line 18:        if (is.na(ppm)) 
			- line 19:            stop("Non-numeric value for 'TOLERANCEPPM'")
			- line 20:        if (length(pmz)) {
		+ in .translate_filter_mz_value
			- line 1:    function (..., msLevel = 2L, value = "MS2MZ") 
			- line 2:    {
			- line 3:        parms <- list(...)[[1L]]
			- line 4:        mz <- numeric(0)
			- line 5:        ppm <- 0
			- line 6:        tolerance <- 0
			- line 7:        if (any(names(parms) == value)) 
			- line 8:            mz <- as.numeric(.parse_or(parms[value]))
			- line 9:        if (anyNA(mz)) 
			- line 10:            stop("Missing or non-numeric value(s) for '", value, 
			- line 11:                "'")
			- line 12:        if (any(names(parms) == "TOLERANCEMZ")) 
			- line 13:            tolerance <- as.numeric(parms["TOLERANCEMZ"])
			- line 14:        if (is.na(tolerance)) 
			- line 15:            stop("Non-numeric value for 'TOLERANCEMZ'")
			- line 16:        if (any(names(parms) == "TOLERANCEPPM")) 
			- line 17:            ppm <- as.numeric(parms["TOLERANCEPPM"])
			- line 18:        if (is.na(ppm)) 
			- line 19:            stop("Non-numeric value for 'TOLERANCEPPM'")
			- line 20:        if (length(mz)) 
			- line 21:            ProcessingStep(filterMzValues, ARGS = list(mz = mz, 
## Documentation
- [ ] Note: Vignette installation section should be formatted as source code.
    * rmd file vignettes/SpectraQL.Rmd

**Comment by jorainer** [comment]
Thanks for your review @jianhong ! Below I address your points - I will add each point as a separate comment to avoid having a single very long comment.

> [ ] NOTE: Vectorize: for loops present, try to replace them by *apply funcitons. 

I had a look at the mentioned `for` loop at line 171, but could not come up with a (safe) and more efficient way using `*apply`. I'm accessing two different variables `mini` and `maxi` within that loop, so I would anyway to loop over an index - and doing that using e.g. `lapply` (`lapply(seq_len(l), function ...` would IMHO not be more efficient - and also less readable. So, if you agree, I would like to keep the `for` loop in that particular case. Note that I usually use `vapply` whenever possible.

**Comment by jorainer** [comment]
> [ ]  To avoid the * NOTE: Avoid redundant 'stop' and 'warn*' in signal conditions in BioCheck,

Thanks for the comment. It indeed would look *ugly*. I changed the wording from *Syntax error* to *Wrong syntax*.

**Comment by jorainer** [comment]
code repetition:

> repetition in .filter, .what, and .where

Thanks, that's a great suggestion! I've moved the respective code into a new `.parse_query` function (that is called by `.what`, `.where` etc.

The changes are in this commit: https://github.com/rformassspectrometry/SpectraQL/commit/cf1dd9a7b843e34c7797af0cf76278e4cd86d550

**Comment by jorainer** [comment]
code repetition:

> repetition in .translate_condition_ms2nl, .translate_condition_ms2prec, .translate_condition_peak_mz, and .translate_filter_mz_value

Thanks for spotting this! I've created two new helper functions to reduce the repeated code.

The changes are in this commit: https://github.com/rformassspectrometry/SpectraQL/commit/49f4b1e72fc8816db42600696bdfab6c5d3e3a5e

**Comment by jorainer** [comment]
> Note: Vignette installation section should be formatted as source code. 

Also done.

Changes are in this commit: https://github.com/rformassspectrometry/SpectraQL/commit/f4bbe03f7eeb3db99545542940496c9cc53e1f5a

**Comment by jorainer** [comment]
Changes have now all been pushed to BioC too. Thanks again for the review @jianhong ! Looking forward to the second round of review.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jorainer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SpectraQL")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SpectraQL

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
