### ISSUE TITLE
ComSeq: An ensemble method for RNA-Seq differential analysis

### ISSUE THREAD

**Issue by DongmeiLi2017** [Bioconductor/Contributions#353]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DongmeiLi2017/ComSeq

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by DongmeiLi2017** [comment]
I have revised the package and checked the package building in RStudio. The building of the package is OK now. Thanks!

**Comment by LiNk-NY** [comment]
Hi @DongmeiLi2017, 
Can you please bump the package's version so that you can start another build in the SPB? 
Thank you. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Dong Mei,  @DongmeiLi2017, 
Do you intend to work on this package? 
Otherwise, I am forced to close the issue. 

Regards,
Marcel

**Comment by DongmeiLi2017** [comment]
Hi Marcel,

Yes, I have revised the package according to suggestions. Will you reevaluate it? Thanks!

Best,
Dongmei

**Comment by LiNk-NY** [comment]
Hi Dong Mei, @DongmeiLi2017 

Based on the last build of the package, it is having errors. Can you look into that? 
http://bioconductor.org/spb_reports/Combine_buildreport_20170424164732.html#malbec2_buildsrc_anchor

Also, once you have resolved those errors, bump the package version so that the package be built by the SPB. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Dong Mei, @DongmeiLi2017 
Please resolve the warnings and errors in your package and bump the package version. 

Regards,
Marcel

**Comment by DongmeiLi2017** [comment]
Hi Marcel,

Thanks for your information! I have changed the package name from Combine to ComSeq as there are already some packages in R have the same name. Thanks!

Best,
Dongmei

**Comment by LiNk-NY** [comment]
Hi Dong Mei, @DongmeiLi2017

Can you resolve the errors in your package and bump the version?
Please keep doing this until you see no errors.

Thank you,
Marcel

**Comment by LiNk-NY** [comment]
Hi Dong Mei, @DongmeiLi2017
You created a duplicate issue. You could have kept this issue open.
I'm closing it. Nitesh will review your package.
Regards,
Marcel
