### ISSUE TITLE
scrapper

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#3536]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/libscran/scrapper

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LTLA** [comment]
Do we have cmake installed on the build machines?

**Comment by lshep** [comment]
We'll check on the broken cmake on nebbiolo2.  Please make sure to list this system dependency in the DESCRIPTION as a SystemRequirement and provide the accompanied INSTALL file.  See [system requirements](https://contributions.bioconductor.org/sysdep.html).   It will make end user use of this package more tricky having this requirement; is it needed?   Also we are transitioning builders for now please use teran2 as the report to clean up;  it seems to have picked up the cmake there but is failing for other reasons.

**Comment by LTLA** [comment]
> Please make sure to list this system dependency in the DESCRIPTION as a SystemRequirement and provide the accompanied INSTALL file. See [system requirements](https://contributions.bioconductor.org/sysdep.html).

I've never heard of this `INSTALL` file before. Your link provides no information on the expected format. WRE mentions this but does not specify the format.

> It will make end user use of this package more tricky having this requirement; is it needed?

Depends on how seriously we want consistency between languages.

If not, we can ditch the entire CMake dependency and use the existing **igraph** R package.

Otherwise, we need this to guarantee we're using the intended version of the **igraph** C library with the same seed, as the R package doesn't expose the C-level seed setters.

~I suppose I technically don't _need_ CMake, as I could just extract the small parts of the **igraph** C library that I actually do need. This would require some modest reverse engineering.~ **Edit:** just tried and gave up, too difficult.

> Also we are transitioning builders for now please use teran2 as the report to clean up; it seems to have picked up the cmake there but is failing for other reasons.

Forgot to push an update to **assorthead** to BioC-devel, this should resolve soon enough.

**Comment by vjcitn** [comment]
We discussed this part of configure process 
```
trying URL 'https://github.com/igraph/igraph/releases/download/0.10.13/igraph-0.10.13.tar.gz'
```
in core and would prefer that igraph (C) be regarded as a system dependency.  Package installation code depending on retrievals from github are not allowed.

**Comment by vjcitn** [comment]
I had a clean install of scrapper on a linux box only after updating BiocNeighbors and beachmat.  My laptop with ccache would not build it.

**Comment by LTLA** [comment]
Hmm.

I suppose we could create an **Rlibigraph** package in the same vein as **Rhdf5lib**, allowing downstream packages like **scrapper** to link to the static **libigraph** library. I have also begun working on https://github.com/LTLA/biocmake/ that would eliminate the need for a user-managed `SystemRequirements: cmake` in BioC packages. I probably won't have enough time to get this into the upcoming release, though.

In the meantime, I could just switch to relying purely on the **igraph** R package. This would not give consistent results across languages due to differences in seeds/versions, but perhaps that's not so big an issue - yet. My _real_ concern with relying on CRAN packages is that updates could change my package's results outside of the usual release schedule; this is a contributing factor to the fragility of the book builds, for example.

In general, **scrapper**'s development policy - all the way down to the C++ code - has been to eliminate as many dependencies as possible, especially those that cannot guarantee back-compatible results. Hence the vendoring of C++ libraries in **assorthead** that are ostensibly provided by other CRAN packages, or the complete rewrite of **Rtsne**, **uwot** and **irlba** in C++. Using the **igraph** R package would be a (hopefully temporary) exception to this rule.

Anyway, while it might not be relevant in the next push attempt, I'd still like to know why your **ccache** build failed. I semi-regularly use **ccache** and it hasn't been an issue.

**Comment by LTLA** [comment]
Did this end up building?

**Comment by vjcitn** [comment]
probably not   i will try to sign on and diagnose    later tonite

**Comment by LTLA** [comment]
FWIW the **igraph** problem can be solved in the next dev cycle with:

- https://github.com/LTLA/biocmake
- https://github.com/libscran/Rlibigraph

This won't affect the current submission for **scrapper** but just FYI.

**Comment by vjcitn** [comment]
I was able to build scrapper on our provisional SPB (teran2).  My hypothesis on why it seemed to hang on your push: the system had no ExperimentHub cache and hung on the scRNAseq requests.  @lshep is that plausible?  As an isolated user, once I authorized creation of the cache, the vignette code succeeded.  It is important to be using the very latest checkouts of BiocNeighbors and beachmat, otherwise there are header-related errors.  I wonder if you should use >= version specs for those imports.

**Comment by vjcitn** [comment]
CMD check produced
```
── Error ('test-modelGeneVariances.R:10:5'): modelGeneVariances works without blocking ──
Error in `MatrixGenerics:::.load_next_suggested_package_to_search(x)`: Failed to find a rowVars() method for dgCMatrix objects.
  However, the following packages are likely to contain the missing method
  but are not installed: sparseMatrixStats, DelayedMatrixStats.
  Please install them (with 'BiocManager::install(...)') and try again.
  Alternatively, if you know where the missing method is defined, install
  only that package.
Backtrace:
    ▆
 1. ├─testthat::expect_equal(out$variances, rowVars(x)) at test-modelGeneVariances.R:10:5
 2. │ └─testthat::quasi_label(enquo(expected), expected.label, arg = "expected")
 3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
 4. ├─MatrixGenerics::rowVars(x)
 5. └─MatrixGenerics::rowVars(x)
 6.   └─MatrixGenerics:::.load_next_suggested_package_to_search(x)
── Error ('test-modelGeneVariances.R:36:9'): modelGeneVariances works with blocking ──
Error in `MatrixGenerics:::.load_next_suggested_package_to_search(x)`: Failed to find a rowVars() method for dgCMatrix objects.
  However, the following packages are likely to contain the missing method
  but are not installed: sparseMatrixStats, DelayedMatrixStats.
  Please install them (with 'BiocManager::install(...)') and try again.
  Alternatively, if you know where the missing method is defined, install
  only that package.
                                            
```

**Comment by vjcitn** [comment]
Once those were installed it passed with one note.

**Comment by vjcitn** [comment]
@hpages have you had a look?

**Comment by hpages** [comment]
Hi @LTLA,

https://github.com/libscran/scrapper/commit/ca6019cb8d7f8970521329b40784ddbd28b4e850 <-- Thanks for that!

> My _real_ concern with relying on CRAN packages is that updates could change my package's results outside of the usual release schedule; this is a contributing factor to the fragility of the book builds, for example.

Yep, that definitely brings back [bad memories](https://github.com/OSCA-source/OSCA.multisample/issues/8).

Anyways, like @vjcitn, I'm not a big fan of the approach that consists in pulling external GitHub assets during installation. Your [Rlibigraph](https://github.com/libscran/Rlibigraph) proposal sounds like the way to go here.

Taking a look at **scrapper** now...

**Comment by hpages** [comment]
Not sure what's going on here but **scrapper** redefines `aggregateAcrossCells()` which is already defined as a generic function in package **scuttle** and as a regular function in package **epiregulon**. Very confusing given that you are also a co-author or/and maintainer of the latter two packages.

It also redefines `normalizeCounts()` which is already defined as a regular function in packages **epigraHMM**, **tweeDEseq**, **MDTS**, **celda**, **STdeconvolve**, and as a generic function (with various methods) in package **scuttle**. That's a lot of `normalizeCounts()` functions!

Same for `scoreMarkers()`: it's already defined as a generic function in package **scran** but redefined as a regular function in **scrapper**.

Not really satisfying for an ecosystem like Bioconductor where we put such a great emphasis on coordination and harmonization.

What am I missing? Is there a plan to tidy things a little?

Other than that, the package is good to go.

**Comment by LTLA** [comment]
Indeed, the plan is to slowly shift users onto **scrapper**, and then eventually retire some of the older packages. More specifically, the plan with @lgeistlinger was to develop two packages; **scrapper** provides the underlying bare-bones utilities, while a second package would provide all of the user-friendly bells and whistles (e.g., plotting, one-click workflows, integration with other BioC data structures and packages) for actual end users and the book. I'm not sure where that plan is at, given that we didn't get any money to do it, but **scrapper** represents my end of the deal.

**Comment by hpages** [comment]
Thanks for clarifying. Glad to hear there's a plan.

Package accepted.

**Comment by hpages** [comment]
My mistake, I closed this inadvertendly. Reopened now. Sorry for the confusion.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LTLA.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scrapper")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scrapper

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by DarioS** [comment]
Ah, bummer about the funding. It takes a couple of steps for the basics e.g. `t(t(features[["sums"]]) / features[["counts"]])`.

**Comment by LTLA** [comment]
Well, I suppose you could always start putting something together, and see if any of the interested parties (mostly book authors) would be interested in helping out. I don't see any money on the horizon, so if it's going to be a volunteer effort anyway, one might as well start now.
