### ISSUE TITLE
OmicsMLRepoR

### ISSUE THREAD

**Issue by shbrief** [Bioconductor/Contributions#3551]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shbrief/OmicsMLRepoR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by HelenaLC** [comment]
# misc

- [ ] Please update R version dependency from 4.2.0 to 4.4.0.
- [ ] `LazyData:` should be removed or set to `false` (see [here](https://contributions.bioconductor.org/description.html?q=lazy#description-lazydata)).
- [ ] `Date:` field is invalid; see corresponding build report NOTE.
- [ ] Consider adding a NEWS file to keep track of changes, in non-technical language, in the code from one release version to the next.
- [ ] In the README, please add installation instructions using `BiocManager::install()`.

# docs

- [ ] Consider adding a package *.man*/help page (`?OmicsMLRepoR`) with a description of key functionality, links to key functions etc.
- [ ] Source and providence information on `inst/extadata` is currently hidden in `inst/scripts`; please provide a corresponding *.man* page so users can view these.
- [ ] Vignette- please replace `devtools::install_github()` installation instructions by ones using `BiocManager::install()`.
- [ ] Vignette- you can hyperlink external packages using `BiocStyle::Biocpkg()` (or similar, for packages living on CRAN or GitHub).
- [ ] Vignette- please add `sessionInfo()` output, to be placed at the very end.
- [ ] Vignette- typo in line 94 (dadta > data).
- [ ] Vignette- `eval=FALSE` flags or similar are not permitted.
- [ ] Vignette- bug in line 234? There's a `for`-loop iterating through `studies`, but `study <- studies[1]` is fixed.

# code

- [ ] Please address the NOTEs in the build report...
  - [ ] Avoid `sapply()`; use `vapply()` (6 instances).
  - [ ] Avoid `1:n`; use `seq_len/along` (3 instances).
  - [ ] Avoid `cat/print` outside of `show` methods (2 instances); you could, e.g., use `message()` and expose an argument `verbose=TRUE/FALSE` that let's the user control this (some might want to suppress printing to the console). 
- [ ] In `ontoTreePlot()`, you can use `match.arg()` to make valid argument choices visible in the documentation, and validate the users input. Also, here's a more concise alternative of the code: 
```r
ontoTreePlot <- function(..., display=c("Term", "Text")) {
  display <- match.arg(display)
  ...
  foo <- switch(display, Term=map$term, Text=map$text)
  edgelist <- edgelist_base %>%
      mutate(from = plyr::mapvalues(from, map$id, foo, warn_missing = FALSE)) %>%
      mutate(to = plyr::mapvalues(to, map$id, foo, warn_missing = FALSE))
}
```

**Comment by shbrief** [comment]
Hi @HelenaLC, I updated the following review points. Let me know if you need anything else. Thanks!

> # misc
> * [x]  Please update R version dependency from 4.2.0 to 4.4.0.
> * [x]  `LazyData:` should be removed or set to `false` (see [here](https://contributions.bioconductor.org/description.html?q=lazy#description-lazydata)).
> * [x]  `Date:` field is invalid; see corresponding build report NOTE.
> * [x]  Consider adding a NEWS file to keep track of changes, in non-technical language, in the code from one release version to the next.
> * [x]  In the README, please add installation instructions using `BiocManager::install()`.
> 
> # docs
> * [x]  Consider adding a package _.man_/help page (`?OmicsMLRepoR`) with a description of key functionality, links to key functions etc.
> * [ ]  Source and providence information on `inst/extadata` is currently hidden in `inst/scripts`; please provide a corresponding _.man_ page so users can view these.
> * [x]  Vignette- please replace `devtools::install_github()` installation instructions by ones using `BiocManager::install()`.
> * [x]  Vignette- you can hyperlink external packages using `BiocStyle::Biocpkg()` (or similar, for packages living on CRAN or GitHub).
> * [x]  Vignette- please add `sessionInfo()` output, to be placed at the very end.
> * [x]  Vignette- typo in line 94 (dadta > data).
> * [x]  Vignette- `eval=FALSE` flags or similar are not permitted.
> * [x]  Vignette- bug in line 234? There's a `for`-loop iterating through `studies`, but `study <- studies[1]` is fixed.
> 
> # code
> * [x]  Please address the NOTEs in the build report...
>   
>   * [x]  Avoid `sapply()`; use `vapply()` (6 instances).
>   * [x]  Avoid `1:n`; use `seq_len/along` (3 instances).
>   * [x]  Avoid `cat/print` outside of `show` methods (2 instances); you could, e.g., use `message()` and expose an argument `verbose=TRUE/FALSE` that let's the user control this (some might want to suppress printing to the console).
> * [x]  In `ontoTreePlot()`, you can use `match.arg()` to make valid argument choices visible in the documentation, and validate the users input. Also, here's a more concise alternative of the code:
> 
> ```r
> ontoTreePlot <- function(..., display=c("Term", "Text")) {
>   display <- match.arg(display)
>   ...
>   foo <- switch(display, Term=map$term, Text=map$text)
>   edgelist <- edgelist_base %>%
>       mutate(from = plyr::mapvalues(from, map$id, foo, warn_missing = FALSE)) %>%
>       mutate(to = plyr::mapvalues(to, map$id, foo, warn_missing = FALSE))
> }
> ```

**Comment by HelenaLC** [comment]
Hm, I can see updates on your GH, however, you need to push changes (with a version bump in the DESCRIPTION) to the (upstream) Bioc branch, which will trigger a new build (and report) that should show up here. Please see [here](https://contributions.bioconductor.org/bioconductor-package-submissions.html#whattoexpect) for guidance if that's unclear.

**Comment by HelenaLC** [comment]
Super, thanks! Almost there now...

major-ish...

- [ ] example data documentation is still missing (specifically, hidden to the user); please provide corresponding .man pages (see previous comment)
- [ ] similarly, in the vignette, could you please add a comment clarifying where `sampleMetadta` is coming from? It appears in a code chunk without being previously assigned, and it took me a minute to understand that becomes available with `library(curatedMetagenomicData)`

very minor...

- [ ] from the build report: "consider adding `@importFrom graphics text` and `@importFrom stats setNames`" - I can find the 1st, but roxygen syntax requires a hash-dash (i.e., you have `#`, but should be `#'`); can't find the 2nd currently
- [ ] there are still 2 instances of `sapply()` (utils.R and treatment_columns.R, though the latter is only in `inst/`)
- [ ] similarly, a couple `1:n` left in ancestors.R and mini_cmd.R; nothing major, but would be nice to get in the habit of using `seq_len/along()` consistently

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shbrief.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("OmicsMLRepoR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/OmicsMLRepoR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
