### ISSUE TITLE
Submission of ProteinGymR

### ISSUE THREAD

**Issue by tram-nguyen-n** [Bioconductor/Contributions#3575]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ccb-hms/ProteinGymR/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
ignore support site ERROR for now.

**Comment by tram-nguyen-n** [comment]
Hi Bioconductor Team, with the upcoming release schedule I wanted to check on the status of this review and see when we might expect to hear back. Please let me know if I can provide anything else to help the process. Thanks!

**Comment by hpages** [comment]
Thanks @tram-nguyen-n for this submission.

`R CMD check` fails for me (see below). Can you take a look? Also please try to address the NOTEs (2 of them, the 1st and 3rd, should be straightforward to get rid of). 

Thanks,
H.

@lshep The last SPB report is empty but the bioc-issue-bot still reports that "The package built without errors or warnings on all platforms". Any idea what could have caused something like this? 

```
hpages@XPS15:~$ time R CMD check ProteinGymR_0.99.2.tar.gz 
* using log directory ‘/home/hpages/pkgreviews/ProteinGymR.expressreview/ProteinGymR.Rcheck’
* using R version 4.4.0 (2024-04-24)
* using platform: x86_64-pc-linux-gnu
* R was compiled by
    gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0
    GNU Fortran (Ubuntu 13.2.0-4ubuntu3) 13.2.0
* running under: Ubuntu 23.10
* using session charset: UTF-8
* checking for file ‘ProteinGymR/DESCRIPTION’ ... OK
* this is package ‘ProteinGymR’ version ‘0.99.2’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘ProteinGymR’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking code files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  ‘AnnotationHub’ ‘tibble’
  All declared Imports should be used.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
benchmark_models: no visible global function definition for ‘all_of’
benchmark_models: no visible global function definition for
  ‘everything’
benchmark_models: no visible binding for global variable ‘model’
benchmark_models: no visible binding for global variable ‘score’
benchmark_models: no visible binding for global variable ‘model_mean’
dms_corr_plot: no visible binding for global variable ‘uID’
dms_corr_plot: no visible binding for global variable ‘.data’
pg_correlate: no visible global function definition for ‘cor.test’
pg_filter_am_table: no visible binding for global variable ‘Entry Name’
pg_filter_am_table: no visible binding for global variable ‘.data’
pg_match_id: no visible global function definition for ‘na.omit’
pg_match_id: no visible binding for global variable ‘UniProt_id’
pg_match_id: no visible binding for global variable ‘mutant’
pg_match_id: no visible binding for global variable ‘AlphaMissense’
pg_match_id: no visible binding for global variable ‘DMS_score’
Undefined global functions or variables:
  .data AlphaMissense DMS_score Entry Name UniProt_id all_of cor.test
  everything model model_mean mutant na.omit score uID
Consider adding
  importFrom("stats", "cor.test", "na.omit")
to your NAMESPACE file.
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... ERROR
Running examples in ‘ProteinGymR-Ex.R’ failed
The error most likely occurred in:

> ### Name: dms_corr_plot
> ### Title: Integrate ProteinGym DMS and AlphaMissense Pathogenicity Scores
> ### Aliases: dms_corr_plot
> 
> ### ** Examples
> 
> 
> dms_corr_plot(uniprotId = "Q9NV35")
'alphamissense_table' not provided, using default table from `ProteinGymR::am_scores()`
see ?ProteinGymR and browseVignettes('ProteinGymR') for documentation
loading from cache
'dms_table' not provided, using default table from `ProteinGymR::dms_substitutions()`
see ?ProteinGymR and browseVignettes('ProteinGymR') for documentation
loading from cache
Error in `purrr::keep()`:
ℹ In index: 16.
ℹ With name: ANCSZ_Hobbs_2022.
Caused by error:
! `.p()` must return a single `TRUE` or `FALSE`, not `NA`.
Backtrace:
     ▆
  1. └─ProteinGymR::dms_corr_plot(uniprotId = "Q9NV35")
  2.   └─ProteinGymR:::pg_filter_dms_table(pg_table = dms_table, uID = uniprotId)
  3.     └─purrr::keep(pg_table, ~any(.x$UniProt_id == uID))
  4.       └─purrr:::where_if(.x, .p, ...)
  5.         └─purrr:::map_(.x, .p, ..., .type = "logical", .purrr_error_call = .purrr_error_call)
  6.           ├─purrr:::with_indexed_errors(...)
  7.           │ └─base::withCallingHandlers(...)
  8.           ├─purrr:::call_with_cleanup(...)
  9.           └─purrr (local) .f(.x[[i]], ...)
 10.             └─cli::cli_abort(...)
 11.               └─rlang::abort(...)
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... NOTE
'::' or ':::' import not declared from: ‘ComplexHeatmap’
'library' or 'require' calls not declared from:
  ‘ComplexHeatmap’ ‘stringr’
* checking package vignettes ... OK
* checking re-building of vignette outputs ... ERROR
Error(s) in re-building vignettes:
  ...
--- re-building ‘data_import_and_representation.Rmd’ using rmarkdown

Quitting from lines 55-61 [unnamed-chunk-2] (data_import_and_representation.Rmd)
Error: processing vignette 'data_import_and_representation.Rmd' failed with diagnostics:
there is no package called 'ComplexHeatmap'
--- failed re-building ‘data_import_and_representation.Rmd’

SUMMARY: processing the following file failed:
  ‘data_import_and_representation.Rmd’

Error: Vignette re-building failed.
Execution halted

* checking PDF version of manual ... OK
* DONE

Status: 2 ERRORs, 3 NOTEs
See
  ‘/home/hpages/pkgreviews/ProteinGymR.expressreview/ProteinGymR.Rcheck/00check.log’
for details.


real	1m32.465s
user	1m10.535s
sys	0m3.995s
```

**Comment by tram-nguyen-n** [comment]
Thanks @hpages, it should be fixed now. The only error I see now is for the Watched Tags which @lshep and I are working through. Please let me know if I missed something.

**Comment by hpages** [comment]
Thanks @tram-nguyen-n 

Package looks good and will be ready to go after you address the following `R CMD check` WARNING and NOTE (see Single Package Builder report above):

```
* checking DESCRIPTION meta-information ... WARNING
Dependence on R version 4.4.1 not with patchlevel 0
```

```
* checking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  AnnotationHub tibble
  All declared Imports should be used.
```

Thanks again,
H.

**Comment by tram-nguyen-n** [comment]
I think that should do it. Thanks again @hpages!

**Comment by hpages** [comment]
Thanks!

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tram-nguyen-n.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ProteinGymR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ProteinGymR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
