### ISSUE TITLE
IdentifiHR

### ISSUE THREAD

**Issue by ashleyweir1** [Bioconductor/Contributions#3579]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DavidsonGroup/IdentifiHR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by ashleyweir1** [comment]
I have updated the DESCRIPTION file and made necessary changes. The updated version is now available on GitHub with version 0.99.1. Please consider the new version for review. Thank you!

**Comment by lshep** [comment]
Please adapt to also use standard Bioconductor object for gene expression, SummarizedExperiment

**Comment by ashleyweir1** [comment]
Hi, I have updated my main branch so that the package can also use SummarizedExperiment objects. However, I want to double check - do I have access to the Bioconductor git server, to push these changes to the remote branch? Thank you for your help.

**Comment by lshep** [comment]
at this point you do not have git access yet.  We will check your github branch shortly

**Comment by lshep** [comment]
In the description your license is gpl3 + file license but I only see the gpl3
license included in the package.  I think you should remove the `+ file license`
as it does not seem needed

Could you also add a section in the vignette to show the use of the Bioconductor class.  And update the man pages/documentation to indicate as such

**Comment by ashleyweir1** [comment]
Hi, 
Thank you for bringing these needed changes to my attention -  I have updated the license listed in the DESCRIPTION and the vignette to document SummarizedExperiment objects as input, though I believe the man pages/documentation for the functions where this change is relevant have already been updated. 
Kindly,
Ashley

**Comment by lshep** [comment]
Your vignette uses a data.frame of "rawCounts" not a SummarizedExperiment object?  Did you not push to the github repo?  Your man pages mention SummarizedExperiment but again use data.frame. Please add a SummarizedExperiment example in the vignette -- there are lots of available existing SummarizedExperiments in other packages or ExperimentHub if needed.

**Comment by ashleyweir1** [comment]
Hi,
I apologise for the confusion.
I have added examples specifically and pushed to the repo.
Please let me know if anything else is needed - thank you for your help,
Ashley

**Comment by lshep** [comment]
The package and code seems to still not have been updated to directly take a SummarizedExperiment object.  Sub-setting the SummarizedExperiment object to parse out necessary data.frames should be done inside your main functions, if not directly implemented throughout the code so a Bioconductor user can directly use the functions without extra effort and getting the benefit of class validations.
