### ISSUE TITLE
keggseq

### ISSUE THREAD

**Issue by w-korani** [Bioconductor/Contributions#358]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/w-korani/keggseq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by w-korani** [comment]
The package a part of a paper that will be publish a late time this year, 2017.

**Comment by w-korani** [comment]
I handled the problems, would you mind to re-test the package

**Comment by lawremi** [comment]
Recommend rejection (no Bioc integration, vignette is just the readme, it unnecessarily couples analysis with database access, and the code needs a lot of work).

**Comment by nturaga** [comment]
@w-korani Please follow the recommendations of @lawremi , the package is missing many key components which are required for a Bioconductor package. If you are interested in still developing this as per [Bioconductor guidelines][] , please do so. 

[Bioconductor guidelines]: https://www.bioconductor.org/developers/package-guidelines/

**Comment by w-korani** [comment]
Dear Michael,

thanks for your concern about the packages:

1. for vignette, I used just short form because I had a ref. to another manual file. Anyway, I will update it to be in complete form.

2. regarding to data accession, it is mandatory for the package since one of the main advantage that it is run-time, KEGG database is updated very frequently, weekly and sometimes daily so if I create internal data sets, I have to continue update the package with the same rate of KEGG database.

3. I could not under stand; no bioc intergration and code needs a lot of work, the package handle statistical enrichment analysis of biological pathways which is important step in RNA-seq experiment analysis. In addition, the code passed all checks on our university cluster and I fixed the reported errors/warning that you mentioned so the code now can pass RMC check/RMC build/BiocCheck and I followed biocoductor instruction page except for the vignette which I will update


Thanks


________________________________

**Comment by lawremi** [comment]
I'll let @nturaga take this from here.

**Comment by nturaga** [comment]
Hi @w-korani,

 Thanks for submitting this package to be reviewed. We understand that the package does provide some useful functionality.

 However, we are declining this package.

 Some packages you might want to take a look at include [KEGGREST][] for accessing KEGG data, working with existing Bioconductor objects such as those defined in the packages [GenomicRanges][] and                 [SummarizedExperiment][], and [DESeq2][] for an exceptional vignette.

 Some coding practices we encourage you to look at [developer resources][] for use of vectorization, tests, coding style, robust and efficient code, etc.


 [KEGGREST]: https://www.bioconductor.org/packages/KEGGREST
 [DESeq2]: https://www.bioconductor.org/packages/DESeq2
 [GenomicRanges]: https://www.bioconductor.org/packages/GenomicRanges
 [SummarizedExperiment]: https://www.bioconductor.org/packages/SummarizedExperiment
 [developer resources]: https://www.bioconductor.org/developers/
