### ISSUE TITLE
Barbie

### ISSUE THREAD

**Issue by FeiLiyang** [Bioconductor/Contributions#3612]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Oshlack/Barbie

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
You might want to suppressPackageStartupMessages when calling the libraries in
your vignette. And it would be helpful to add more detail to each sections as to
what we are looking at or why its important or useful so it can read more like a
manual.
Could you also expand your intro to compare to some of the existing packages
that are focused on barcodes to indicate how yours differs. 

I'm slightly concerned if the name "Barbie" can be used because of the
registered brand/trademark?

**Comment by FeiLiyang** [comment]
> You might want to suppressPackageStartupMessages when calling the libraries in your vignette. And it would be helpful to add more detail to each sections as to what we are looking at or why its important or useful so it can read more like a manual. Could you also expand your intro to compare to some of the existing packages that are focused on barcodes to indicate how yours differs.
> 
> I'm slightly concerned if the name "Barbie" can be used because of the registered brand/trademark?

Hi @lshep , thank you for the feedback. I'll work on the vignette to address the first two comments. Plus, regarding the name "Babie" and its potential trademark risks, would you strongly recommend changing it? I was wondering where to find the specific rules for the name issues like this, as the [developer's handbook](https://contributions.bioconductor.org/package-name.html) seems a bit vague on this. Thank you!

**Comment by vjcitn** [comment]
https://en.clairfort.nl/the-ip-protection-of-barbie/ says the word "Barbie" is protected by trademark law.  It would be nice for the Bioconductor project not to have to be concerned that it is involved with a trademark violation.  So please do change the name if you wish to have the package in this ecosystem, thanks!

**Comment by FeiLiyang** [comment]
> https://en.clairfort.nl/the-ip-protection-of-barbie/ says the word "Barbie" is protected by trademark law. It would be nice for the Bioconductor project not to have to be concerned that it is involved with a trademark violation. So please do change the name if you wish to have the package in this ecosystem, thanks!

Thank you @vjcitn  for the explanation. I'm considering a name change and have brainstormed a few alternatives: 
**"BarbieQ"**, or **"barbieQ"**, as Q stands for quantification analysis and "barbie" itself is a slang for barbecue in Aussie English. Or, **"BarbeQ"** to avoid direct similarity to the trademarked Barbie doll. The package deals with barcode data, so I’m keen on including "bar" in the name. I'd appreciate hearing your thoughts on these alternative names. Thank you very much!

**Comment by vjcitn** [comment]
BarbeQ sounds good to me

**Comment by lshep** [comment]
To make sure the package gets processed correctly, I'm going to close this issue. Please re-submit with updated name.  FWIW: I would lean towards BarbeQ as well just to make sure.
