### ISSUE TITLE
(inactive) sgnesR

### ISSUE THREAD

**Issue by shaileshtripathi** [Bioconductor/Contributions#362]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shaileshtripathi/sgnesR
Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
The package does not meet basic Bioconductor requirements, e.g., the existence of a vignette. The package does not integrate with other Bioconductor tools, e.g., the use of SummarizedExperiment or GenomicRanges data representations to facilitate interoperability.

**Comment by shaileshtripathi** [comment]
Hi, I have updated the package, can you please look into this for further consideration
https://github.com/shaileshtripathi/sgnesR

**Comment by shaileshtripathi** [comment]
Hi, @mtmorgan

 I have updated the package, can you please look into this for further consideration
https://github.com/shaileshtripathi/sgnesR

**Comment by mtmorgan** [comment]
The vignette and other aspects of the package are not up to Bioconductor standards; we are declining the contribution.

**Comment by shaileshtripathi** [comment]
Hi,

I updated vignette and other documentation related issues yesterday. Can
you please check again.
How can I resubmit package.

Best,
Shailesh

**Comment by mtmorgan** [comment]
We declined your package based on the entirety of my original comments. Also, compare your vignette to other Bioconductor vignettes, including the vignettes of recently accepted packages. Compare also your package to the Bioconductor check list. We did review your changes before once again declining your package.

Please feel free to continue developing your package until you are confident that it meets basic Bioconductor standards. Create or rename your current repository and open a new issue. Do not do this in haste, but instead consider carefully how your package will integrate with other Bioconductor packages, and how your coding and documentation practices compare to basic Bioconductor expectations. You might find it helpful to engage users through other means, and to take their feedback on the utility, interoperability, and robustness of your package into consideration.

**Comment by shaileshtripathi** [comment]
Hi I did go through the checklist and added other required things.
I just want to resubmit it is there any way to resubmit it so that it can
go through check again without changing its name.

Best,
Shailesh

**Comment by mtmorgan** [comment]
I'm sorry, your package has been declined. We will not consider your package further. Consider distributing it through other channels, e.g., CRAN or Github.
