### ISSUE TITLE
G4SNVHunter

### ISSUE THREAD

**Issue by rongxinzh** [Bioconductor/Contributions#3623]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rongxinzh/G4SNVHunter

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by DarioS** [comment]
Overall, a very good submission and only a few minor changes are needed.

- Don't ask the user to install optional packages one-by-one.

![image](https://github.com/user-attachments/assets/f6ce7252-b9c2-4efe-82f1-6d922142fae7)

You should recommend that the user uses `BiocManager::install("G4SNVHunter", dependencies = TRUE)`.

- Section 5.3: Visualize G4Hunter Prediction Results has no biological interpretation of the output. Add a couple of sentences below the plot to help the reader interpret the results. For example, explain why panels B and D are bimodal.

- Section 6: Evaluate SNV Effects. The schematic diagram is too small to read. Make it bigger.

- For variables such as `raw_score_threshold`, specify their valid range. Can they be negative? Can they be more than 1?

- For a particular package, use either `import` or `importFrom`. I see some duplication in the NAMESPACE file.

```r
import(Biostrings)
importFrom(Biostrings,DNAString)
importFrom(Biostrings,DNAStringSet)
importFrom(Biostrings,replaceAt)
```

- No input checking for `strands`. In function defintion, should be strands = c('b', 'p') and inside function should be strands <- match.arg(strands). See [a tutorial](https://www.r-at-work.com/functions/base/match-arg.html).

**Comment by rongxinzh** [comment]
Dear @DarioS, thank you very much for taking the time to review our package and providing the valuable comments.

We have reviewed all of your concerns one by one and addressed nearly all of them, except for the last one, as we already have input checking for strands.

---

**Q:** Don't ask the user to install optional packages one-by-one. 
**A:** _Following your suggestion, we have revised this section, removed the part about manual package installation, and recommended users to install using the command BiocManager::install('G4SNVHunter', dependencies = TRUE)._
_Please see section 2 and 3._
![image](https://github.com/user-attachments/assets/fdf546b5-b907-42d9-9225-5ea116a12a3c)

**Q:** Section 5.3: Visualize G4Hunter Prediction Results has no biological interpretation of the output. Add a couple of sentences below the plot to help the reader interpret the results. For example, explain why panels B and D are bimodal. 
**A:** _We have added an explanation to interpret the biological significance of the figure. Please see section 5.3 for more details._
![image](https://github.com/user-attachments/assets/d612810f-61ec-4bf7-9b28-a9962f863abb)

**Q:** Section 6: Evaluate SNV Effects. The schematic diagram is too small to read. Make it bigger. 
**A:** _We have designed a new schematic diagram. It looks clearer and more user-friendly. Please see it in section 6 of the vignette._
![image](https://github.com/user-attachments/assets/d08a29ae-ec12-4cc1-86e4-c590713fdb40)

**Q:** For variables such as raw_score_threshold, specify their valid range. Can they be negative? Can they be more than 1? 
**A:** _We have provided a more stringent definition for the value ranges of the raw_score_threshold, mut_score_threshold, and score_diff_threshold parameters. We have added explanations in the vignette and also enforced these definitions in the code of the filterSNVImpact function._
![image](https://github.com/user-attachments/assets/743e06fc-7471-41e1-8a4f-680a3d4e4f92)
![image](https://github.com/user-attachments/assets/20ebe71d-4836-405e-8321-3a001b96926c)

**Q:** For a particular package, use either import or importFrom. I see some duplication in the NAMESPACE file. 
**A:** _Have revised them. Thanks!_

**Q:** No input checking for strands. In function defintion, should be strands = c('b', 'p') and inside function should be strands <- match.arg(strands). See a tutorial. 
**A:** _We do have input checking for strands. We perform input validation for the strands parameter by calling the validateG4HunterParams function within G4HunterDetect._
![image](https://github.com/user-attachments/assets/d04a7a3d-d1bb-4e15-a458-265e6ae91ee5)
![image](https://github.com/user-attachments/assets/3c4ad445-fc81-4078-a398-e293e6dbc8ab)

---

Overall, your suggestions have been extremely effective, and we greatly appreciate your contribution as a volunteer to the R open-source community.

Please feel free to let me know if you have any further concerns.

**Comment by DarioS** [comment]
All requests have been addressed.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/rongxinzh.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("G4SNVHunter")`. The package 'landing page' will be created at

https://bioconductor.org/packages/G4SNVHunter

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
