### ISSUE TITLE
RTNsurvival: An R/Bioconductor package for survival analysis using transcriptional networks and regulons

### ISSUE THREAD

**Issue by csgroen** [Bioconductor/Contributions#363]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/csgroen/RTNsurvival/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by nturaga** [comment]
RTNsurvival Review
==================

## Build

R-release CMD build RTNsurvival: Ok

R-release CMD INSTALL RTNsurvival: Ok

## DESCRIPTION

* The DESCRIPTION should follow a paper abstract format. It should provide the reader a overview of what to expect in the package.

* biocViews : Too many biocViews. Emphasize most-specific terms

## NAMESPACE

* Ok.

## Vignette

* Vignette is informative and well done.

* The markdown file in the vignette is not written according to "Rmarkdown" standards. The code section needs to start with  "```{r}". If the code isn't written like this in the vignette then the R code is not evaluated. Bioconductor vignettes must have evaluated code chunks.

* You should not have a "figures" folder in your vignette. This should be generated as the build system runs your vignette. This is solved if you fix your markdown file.

## man

* Good man pages, with examples for each function.

## R

* It seems like the input to key functions could use the [SummarizedExperiment][] package and class to represent data (see DESeq2's vignette). This greatly increases interoperability with other Bioconductor packages.

* Always provide and use (including internally in the package) a constructor (e.g., `TNS(...)` instead of `new("TNS", ...)`) and accessors (e.g., `tni()` instead of `object@tni`) to avoid directly exposing implementation details (e.g,. `new()`, `@`) to the user.

* Consider: Use consistent code formatting and white space, e.g., use the [formatR][]

* Functions like `.survplot` in the "AllSupplements.R" represent a plot, with too many 'magic numbers' that are likely to make the code very fragile, e.g., when the user changes the data set or size of the plotting device. But does make pretty plots

* Use `message()` instead of `cat()` so that diagnostic messages go to stderr rather than stdout.

* Use e.g., `seq_len(nSections)` (AllSupplements.R:135) instead of `1:nSections` for robust code (avoiding problems when `nSections == 0`).

* (AllMethods.R:448) Avoid 'copy-and-append', where `resall` is initialized and then at each iteration appended with `rbind()`. This is extremely inefficient. Either 'pre-allocate and fill' or use an `lapply()` to generate the data and then a single call `do.call("rbind", result)`; some hints are [here][robust].

[robust]: http://bioconductor.org/developers/how-to/efficient-code/
[formatR]: https://cran.r-project.org/package=formatR
[SummarizedExperiment]: https://bioconductor.org/packages/SummarizedExperiment

## General Comments

* Consider adding the existing code to the RTN package.

**Comment by nturaga** [comment]
Hi @csgroen ,

Should we review this package again? If not, please let us know in the comments when you are ready for us to review.

**Comment by csgroen** [comment]
Hi @nturaga,

We only saw your review last week and are still working on your comments. I'll let you know as soon as we address everything that has been remarked upon.

**Comment by nturaga** [comment]
Thanks. Keep me posted.

**Comment by csgroen** [comment]
# RTNsurvival Review

**(1) REVIEWER:** 
The DESCRIPTION should follow a paper abstract format. It should provide the reader a overview of what to expect in the package.

**AUTHORS:** 
We updated the package description with a more informative summary of the package.


**(2) REVIEWER:** 
biocViews : Too many biocViews. Emphasize most-specific terms

**AUTHORS:** 
We cut down on the number of biocViews. We can cut down more if needed.


**(2) REVIEWER:** 
Vignette is informative and well done.

**AUTHORS:** 
Thank you.


**(3) REVIEWER:**
The markdown file in the vignette is not written according to "Rmarkdown" standards. The code section needs to start with "```{r}". If the code isn't written like this in the vignette then the R code is not evaluated. Bioconductor vignettes must have evaluated code chunks.

**AUTHORS:** 
All code sections now work as required and figures are evaluated and generated by the system.


**(4) REVIEWER:**
You should not have a "figures" folder in your vignette. This should be generated as the build system runs your vignette. This is solved if you fix your markdown file.

**AUTHORS:** 
As suggested, we eliminated the figures folder by evaluating the vignette.


**(5) REVIEWER:**
Consider putting .Rhistory in the .gitignore file of your repository

**AUTHORS:**
.Rhistory file was removed

**(6) REVIEWER:**
Good man pages, with examples for each function.

**AUTHORS:**
Thank you.


**(7) REVIEWER:**
It seems like the input to key functions could use the SummarizedExperiment package and class to represent data (see DESeq2's vignette). This greatly increases interoperability with other Bioconductor packages.

**AUTHORS:**
We thank the Reviewer for the suggestion, SummarizedExperiment package is indeed a great tool and can increases interoperability and make data more consistent across different platforms. However, RTNsurivival requires a TNI class object. By the time SummarizedExperiment package was made available for the community, TNI class was 2 years on Bioconductor, so this would require updating an older Bioconductor class. Although it is possible, it requires considering the life cycle of another package. We are going to evaluate the possibility of implementing an alternative input format that includes SummarizedExperiment package. In the meantime, we have simplified the vignette of RTNsurvival in order to make the data type required clearer to run the current package, not exposing the implementations.


**(8) REVIEWER:**
Always provide and use (including internally in the package) a constructor (e.g., TNS(...) instead of new("TNS", ...)) and accessors (e.g., tni() instead of object@tni) to avoid directly exposing implementation details (e.g,. new(), @) to the user.

**AUTHORS:**
The same problem as described above, RTNsurvival requires a TNI class object. For RTNsurvival, there is no exposed implementations, all details hidden. We hope that the new examples in the vignette have clarified the input data format. Therefore, we changed the vignette and manual examples to provide the user with a processed TNI object. This makes the examples simpler and hides any implementation details from the user.


**(9) REVIEWER:**
Consider: Use consistent code formatting and white space, e.g., use the formatR

**AUTHORS:**
All code was cleaned up using formatR.

**(10) REVIEWER:**
Functions like .survplot in the "AllSupplements.R" represent a plot, with too many 'magic numbers' that are likely to make the code very fragile, e.g., when the user changes the data set or size of the plotting device. But does make pretty plots

**AUTHORS:**
Thank you. We now provide more graphical parameters for fine-tuning to functions like .survplot. As most of the 'magic numbers' are graphical parameters, we believe this will offset most plotting issues that users might have had.

**(11) REVIEWER:**
Use `message() `instead of `cat() `so that diagnostic messages go to stderr rather than stdout.

**AUTHORS:**
All `cat()` calls were replaced with `message()` calls.

**(12) REVIEWER:**
Use e.g., seq_len(nSections) (AllSupplements.R:135) instead of 1:nSections for robust code (avoiding problems when nSections == 0).

**AUTHORS:**
`1:nSections` was changed to` seq_len(nSections)`

**(13) REVIEWER:**
(AllMethods.R:448) Avoid 'copy-and-append', where resall is initialized and then at each iteration appended with rbind(). This is extremely inefficient. Either 'pre-allocate and fill' or use an lapply() to generate the data and then a single call do.call("rbind", result); some hints are here.

**AUTHORS:**
The 'copy-and-append' problem has been solved using `lapply() `to generate resall.

**(14) REVIEWER:**
Consider adding the existing code to the RTN package.

**AUTHORS:**
We thank the Reviewer for the suggestion, however, the maintenance cycle of RTN is too complex to include new and not directly related methods as the ones provided by RTNsurvival. This new package provides concepts that cannot be easily integrated into the story around RTN. Therefore, we rather see RTN as a basic infrastructure to build regulatory networks. Whenever possible we want to spin off new methods if we see this opportunity. RTNsurvival brings a new method that we have recently described in our Nature Genetics study (doi: 10.1038/ng.3458), and we believe it can bring great value to the community that studies regulatory networks.
