### ISSUE TITLE
microRNAome

### ISSUE THREAD

**Issue by mccallm** [Bioconductor/Contributions#370]
- Repository: https://github.com/mccallm/microRNAome

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Hi Matthew,

Looks like an experimental data package. A few suggestions below.

1.  Explain the dimensions on the man page
The man page says ...
" New small RNA-seq data from 39 primary cells obtained by culture, flow 
cytometry or centrifugation were augmented with Sequence Read Archive (SRA)
small RNA-seq read data from 496 samples with over 1 million microRNA reads. 
..."

Explain how these numbers become 2131 and 528:
> dim(microRNAome)
[1] 2131  528

2. Add an \examples section that shows how to find the data. Explain that in this object the 'assays' only holds one matrix and the name is "counts" (vs an SE object that holds many matrices).

> names(assays(microRNAome))
[1] "counts"
> assays(microRNAome)$counts[1:3,1:3]
                    SRR2296788 ERR738403 ERR738404
hsa-let-7a-2-3p              0         0         0
hsa-let-7a-3p               73        77        87
hsa-let-7a-5p/7c-5p      71331     41863     43784

3. The URL field in DESCRIPTION usually refers to an external repo, e.g., github or someone's personal web site. I don't think it adds value to refer to the Bioconductor web site so I'd suggest removing this field.

4. Was this data package designed to work with an existing software package? If yes, you may want to mention that in the man page - you don't need an example with the software package, just a heads up to the users.

Valerie

**Comment by mccallm** [comment]
Hi Valerie,

I made the suggested changes to the microRNAome.Rd and DESCRIPTION files.

This data package isn't designed to work with any specific software package. 

Thanks,
Matt

**Comment by vobencha** [comment]
Thanks for making the changes. Marking as approved.
Valerie
