### ISSUE TITLE
cytofWorkflow

### ISSUE THREAD

**Issue by gosianow** [Bioconductor/Contributions#374]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gosianow/cytofWorkflow
- This package is a workflow.

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
The description file does not look current (fields "Title", "Descritpion"). Please update before the package is accepted for moderation.

**Comment by gosianow** [comment]
Done.

**Comment by mtmorgan** [comment]
ABNORMAL usually means a problem with the DESCRIPTION file or otherwise -- R CMD build should work on your local machine. @nturaga this is a workflow rather than a regular package, and will be reassigned.

**Comment by gosianow** [comment]
Hello, 
I get an error on the Windows machine because the captioner package is not available there.
However, a Windows version of this package exists
https://cran.r-project.org/web/packages/captioner/index.html
Could it be that it is not installed on your Windows machine?

**Comment by lshep** [comment]
This is an issue on our end and we are looking into it.  Unless you hear otherwise please ignore this ERROR for now.

**Comment by gosianow** [comment]
I am sorry but this error message "Fatal error: cannot create 'R_TempDir'" does not tell me anything. I can R CMD build the package on my Linux machine. Could you help me with understanding what can be the potential problem, please?

**Comment by lshep** [comment]
This is an ERROR on our build machine please ignore for now.

**Comment by mtmorgan** [comment]
our build system seems to have used up it's temp directory memory allocation... nothing that you can do about it.

**Comment by nturaga** [comment]
# Review cytofWorkflow

## Build and Install

R-release CMD build cytofWorkflow : ok

R-release CMD INSTALL cytofWorkflow_0.99.6.tar.gz : ok

## DESCRIPTION

* Description should follow a paper abstract format. I suggest using the abstract in your vignette.

* URL missing (github link where the workflow is being developed).

* No internal R-code, so just move everything from `Imports`  to `Suggests`. The file NAMESPACE should still be there, but it should be empty..

## Vignette

* You should just connect your vignette to the README.md in github,

    ```
    git rm README.md
    ln -s vignette/cytofWorkflow.md README.md
    git add README
    ```

## Genral Comments

* Good figures and good vignette.

**Comment by gosianow** [comment]
Could I just keep my old README.md file?

**Comment by gosianow** [comment]
I would like that the packages necessary for running the vignette get installed when installing the workflow package. Does that take place when I move all the packages from `Imports` to `Suggests`? Otherwise, users have to do that manually.

**Comment by nturaga** [comment]
@gosianow You can put it back in `Imports` in that case.  

Regarding your README, you should probably change it to include the abstract, and the installation from `biocLite`.  You can leave the rest as is.
