### ISSUE TITLE
retnfit

### ISSUE THREAD

**Issue by hstern2** [Bioconductor/Contributions#376]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hstern2/retnfit

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Before moderating this package so that it can be built for a comprehensive review, please update the vignette to be 'real', i.e., with evaluated code chunks rather than cut-and-paste results. Please also consider how this package fits in with other packages in the Bioconductor ecosystem, and introduces these packages either for data representation (e.g., SummarizedExperiment, GRanges) in the body of the package (via Imports: or perhaps Depends:), manipulation (e.g., BiocParallel, rather than Rmpi) or illustration (in the vignette).

**Comment by hstern2** [comment]
thanks for the response.

1) I am now using BiocParallel  (SummarizedExperiment and GRanges) aren’t applicable to this work however)

2) I have tried to include code to be evaluated in the \examples section of man/parallelFit.Rd but ran into trouble with R CMD check - I think the problem is that because this uses MPI, it requires R to be invoked with mpirun.  is there a way to tell R CMD check to do that?  I wasn’t sure this was possible because the Rmpi library itself seems to bypass the problem with \donttest{  (that’s the “solution” I chose)

thanks for any suggestions!

best - Harry


____________
Harry Stern
Center for Integrated Research Computing
Wegmans Hall 1205, University of Rochester
hstern2@ur.rochester.edu<mailto:hstern2@ur.rochester.edu>
(585) 275-8804


On May 23, 2017, at 12:43 PM, Martin Morgan <notifications@github.com<mailto:notifications@github.com>> wrote:


Before moderating this package so that it can be built for a comprehensive review, please update the vignette to be 'real', i.e., with evaluated code chunks rather than cut-and-paste results. Please also consider how this package fits in with other packages in the Bioconductor ecosystem, and introduces these packages either for data representation (e.g., SummarizedExperiment, GRanges) in the body of the package (via Imports: or perhaps Depends:), manipulation (e.g., BiocParallel, rather than Rmpi) or illustration (in the vignette).

**Comment by hstern2** [comment]
I commited changes to git repo.  the example in man/parallelFit.Rd is no longer commented out with \dontest
so this is a “real” example.

I still have trouble running R CMD check but it works with —no-examples

R CMD BiocCheck passes.

Thanks for your help getting this package submitted to bioconductor.

Harry

On May 25, 2017, at 11:57 AM, Stern, Harry <harry.stern@rochester.edu<mailto:harry.stern@rochester.edu>> wrote:

thanks for the response.

1) I am now using BiocParallel  (SummarizedExperiment and GRanges) aren’t applicable to this work however)

2) I have tried to include code to be evaluated in the \examples section of man/parallelFit.Rd but ran into trouble with R CMD check - I think the problem is that because this uses MPI, it requires R to be invoked with mpirun.  is there a way to tell R CMD check to do that?  I wasn’t sure this was possible because the Rmpi library itself seems to bypass the problem with \donttest{  (that’s the “solution” I chose)

thanks for any suggestions!

best - Harry


____________
Harry Stern
Center for Integrated Research Computing
Wegmans Hall 1205, University of Rochester
hstern2@ur.rochester.edu<mailto:hstern2@ur.rochester.edu>
(585) 275-8804


On May 23, 2017, at 12:43 PM, Martin Morgan <notifications@github.com<mailto:notifications@github.com>> wrote:


Before moderating this package so that it can be built for a comprehensive review, please update the vignette to be 'real', i.e., with evaluated code chunks rather than cut-and-paste results. Please also consider how this package fits in with other packages in the Bioconductor ecosystem, and introduces these packages either for data representation (e.g., SummarizedExperiment, GRanges) in the body of the package (via Imports: or perhaps Depends:), manipulation (e.g., BiocParallel, rather than Rmpi) or illustration (in the vignette).

**Comment by mtmorgan** [comment]
The currently blocking issue is the vignette, where the 'verbatim' commands need to be replaced with code chunks `<<>>= ... @` that are actually evaluated. You'll need to work through the MPI issues on your end -- the build system will not launch your builds under mpi. You should (a) carefully examine the code that uses MPI and confirm that it is written efficiently (poor R code, typically 'iteration' via `for()` or `lapply()` can perform 100x slower than vectorized code) (b) ensure that the 'default' mode of evaluation is serial mode and (c) provide parallel evaluation as a user-configurable option.

**Comment by mtmorgan** [comment]
I am closing this issue. If you develop the vignette further, please update your git repository and let me know; I will then re-open the issue.

**Comment by hstern2** [comment]
hi, I have finally updated this package with a configure script to detect MPI and build serial version if not there, use BiocParallel, have working vignette, etc

____________
Harry Stern
Center for Integrated Research Computing
Wegmans Hall 1205, University of Rochester
hstern2@ur.rochester.edu<mailto:hstern2@ur.rochester.edu>
(585) 275-8804

On Jul 9, 2017, at 6:35 AM, Martin Morgan <notifications@github.com<mailto:notifications@github.com>> wrote:


I am closing this issue. If you develop the vignette further, please update your git repository and let me know; I will then re-open the issue.

**Comment by mtmorgan** [comment]
I didn't see your comment, and am opening this issue and assigning it to a reviewer.

**Comment by hstern2** [comment]
thanks again for your help.  one thing I wanted to check on was that I was subscribed to the bioc-devel mailing list - I am seeing


* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

I tried subscribing at the website a couple times but I am not sure if it took.

Harry Stern
hstern2@ur.rochester.edu<mailto:hstern2@ur.rochester.edu>

On Jan 8, 2018, at 10:46 AM, Martin Morgan <notifications@github.com<mailto:notifications@github.com>> wrote:


I didn't see your comment, and am opening this issue and assigning it to a reviewer.

**Comment by mtmorgan** [comment]
After entering subscription information the mailing list usual sends a confirmation email; this often ends up in people's 'spam' mail box...

**Comment by hstern2** [comment]
yes that is exactly what happened.  sorry for trouble

On Jan 9, 2018, at 5:06 PM, Martin Morgan <notifications@github.com<mailto:notifications@github.com>> wrote:


After entering subscription information the mailing list usual sends a confirmation email; this often ends up in people's 'spam' mail box...

**Comment by mtmorgan** [comment]
@hstern2 Yes ignore the warning; I'll review your package when the VERSION BUMP REQUIRED tag is removed (by a version bump on your end). Thanks!

**Comment by hstern2** [comment]
OK I bumped version to 0.99.8

On Jan 11, 2018, at 10:56 AM, Martin Morgan <notifications@github.com<mailto:notifications@github.com>> wrote:


@hstern2<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hstern2&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=u5vYjhgzTwkkBS1kIx9w6AP8ISqhIMUy3rigf-BuXE4&m=v5CH1EB_hSEkiVi9IwfKj8XLwZMca1FRN-B5TMExuWI&s=P0pTOp2cFuF8mXGfYoDd-oX9f4dvRyu65cbe1Jj8X0Q&e=> Yes ignore the warning; I'll review your package when the VERSION BUMP REQUIRED tag is removed (by a version bump on your end). Thanks!

**Comment by mtmorgan** [comment]
## General

- do not commit 'build' products to git, e.g., remove build/
- the `configure` file looks like (the unmaintainable) output from a much simpler `configure.ac`; provide `configure.ac` instead / as well
- It's pretty unusual to code MPI at the C level, and much more flexible to make decisions like this at the R level via Rmpi, e.g., your package ability is determined by system capabilities at package installation, rather than at run time.
- Make sure NEWS can be parsed by `utils::news()`

## DESCRIPTION, NAMESPACE

- Please provide additional detail in the Deescription: field, e.g., about inputs, and merits relative to alternative approaches.
- Since 

## R

- `stop(paste(...))` can usually be replaced with `stop(...)`
- More carefully validate user-suplied inputs, e.g., using `stopifnot()`
- Use BiocParallel::SerialParam() (and Import: BiocParallel, etc) to avoid extra complexity in the main function, e.g.,

    ```
    if (## MPI is available) {
       ...
        bp_param <- SnowParam(n_proc, type="MPI")
    } else {
        bp_param <- SerialParam()
    }

    bplapply(..., BPPARAM = bp_param)
    ```

## src

- looks like `R_logical()` is just `Rf_ScalarLogical()`; likewise `R_int()` / `Rf_ScalarInteger()`.
- Usual convention is `INTEGER(x)[0]` rather than `INTEGER_VALUE()`, and `INTEGER(x)` rather than `INTEGER_POINTER(x)`, etc. Also `STRING_ELT(x, 0)`
- Is there sufficient care to avoid race conditions in the writes at, e.g., gn.c:653?

## vignette / man

- The vignette is very brief. Consider developing a more extensive example, including visualizing and interpretting the result.
- The vignette and man page are too succinct in their description of `experiment_set` and other inputs. Provide enough description and 'worked example' to remove or explain jargon, e.g, whait are 'experiment' and 'index' nodes, what does an outcome -1, 0, 1 signify? How are 'costs' measured, in what (experimental?) context is a perturbation (and is this really logical `TRUE` / `FALSE`)?

**Comment by hstern2** [comment]
hi Martin thanks for the great feedback.  I am working on these changes now, I have one quick question, now that I have a configure.ac file I am getting a new warning for the tokay2 build


Found the following shell script(s) with CR or CRLF line endings:
  configure.ac

is there an easy fix, should I ignore (like the execute perms thing…??)

thanks - Harry

On Jan 18, 2018, at 4:12 PM, Martin Morgan <notifications@github.com<mailto:notifications@github.com>> wrote:

General

  *   do not commit 'build' products to git, e.g., remove build/
  *   the configure file looks like (the unmaintainable) output from a much simpler configure.ac; provide configure.ac instead / as well
  *   It's pretty unusual to code MPI at the C level, and much more flexible to make decisions like this at the R level via Rmpi, e.g., your package ability is determined by system capabilities at package installation, rather than at run time.
  *   Make sure NEWS can be parsed by utils::news()

DESCRIPTION, NAMESPACE

  *   Please provide additional detail in the Deescription: field, e.g., about inputs, and merits relative to alternative approaches.
  *   Since

R

  *   stop(paste(...)) can usually be replaced with stop(...)

  *   More carefully validate user-suplied inputs, e.g., using stopifnot()

  *   Use BiocParallel::SerialParam() (and Import: BiocParallel, etc) to avoid extra complexity in the main function, e.g.,

if (## MPI is available) {
   ...
    bp_param <- SnowParam(n_proc, type="MPI")
} else {
    bp_param <- SerialParam()
}

bplapply(..., BPPARAM = bp_param)


src

  *   looks like R_logical() is just Rf_ScalarLogical(); likewise R_int() / Rf_ScalarInteger().
  *   Usual convention is INTEGER(x)[0] rather than INTEGER_VALUE(), and INTEGER(x) rather than INTEGER_POINTER(x), etc. Also STRING_ELT(x, 0)
  *   Is there sufficient care to avoid race conditions in the writes at, e.g., gn.c:653?

vignette / man

  *   The vignette is very brief. Consider developing a more extensive example, including visualizing and interpretting the result.
  *   The vignette and man page are too succinct in their description of experiment_set and other inputs. Provide enough description and 'worked example' to remove or explain jargon, e.g, whait are 'experiment' and 'index' nodes, what does an outcome -1, 0, 1 signify? How are 'costs' measured, in what (experimental?) context is a perturbation (and is this really logical TRUE / FALSE)?

**Comment by mtmorgan** [comment]
I think the solution is to save configure.ac with 'linux' (i.e., linefeed only) line endings; probably this (saving with LF line endings) is an option i whatever editor you are using.

**Comment by hstern2** [comment]
OK, the file was created on linux and didn’t have any CR’s but I think git was adding them when it checked out for the windows system.  after looking around a bit and trying a couple things I ended up creating and checking in a .gitattributes file with the line

configure.ac eol=lf

that removed the warning.

On Jan 23, 2018, at 2:39 PM, Martin Morgan <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the solution is to save configure.ac with 'linux' (i.e., linefeed only) line endings; probably this (saving with LF line endings) is an option i whatever editor you are using.

**Comment by hstern2** [comment]
one more question, I have made almost all of the suggested code changes but I had some trouble with replacing INTEGER_VALUE(x) … with INTEGER(x)[0], STRING_ELT, etc  … I got warnings/errors either on our cluster here or on the bioc test builds...  INTEGER_VALUE is just a macro for Rf_asInteger so I am now using that.  here is what I am currrently using to convert SEXP’s to C data types,

static int SEXP_to_int(SEXP x) { return Rf_asInteger(x); }
static int *SEXP_to_intp(SEXP x) { return INTEGER(x); }
static double SEXP_to_double(SEXP x) { return Rf_asReal(x); }
static double *SEXP_to_doublep(SEXP x) { return REAL(x); }
static const char *SEXP_to_const_charp(SEXP x) { return CHAR(Rf_asChar(x)); }

this passes checks and doesn’t give warnings/errors, does that look OK?

On Jan 24, 2018, at 10:40 AM, Stern, Harry <harry.stern@rochester.edu<mailto:harry.stern@rochester.edu>> wrote:

OK, the file was created on linux and didn’t have any CR’s but I think git was adding them when it checked out for the windows system.  after looking around a bit and trying a couple things I ended up creating and checking in a .gitattributes file with the line

configure.ac eol=lf

that removed the warning.

On Jan 23, 2018, at 2:39 PM, Martin Morgan <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the solution is to save configure.ac with 'linux' (i.e., linefeed only) line endings; probably this (saving with LF line endings) is an option i whatever editor you are using.

**Comment by mtmorgan** [comment]
Your C wrappers are fine; is your package ready for final review?

**Comment by hstern2** [comment]
Ok thanks … not yet ready I still need to work on vignette/man.

On Jan 26, 2018, at 8:48 AM, Martin Morgan <notifications@github.com<mailto:notifications@github.com>> wrote:


Your C wrappers are fine; is your package ready for final review?

**Comment by mtmorgan** [comment]
I'll close this issue; when you're ready for review add a comment here mentioning mtmorgan and I'll re-open it.
