### ISSUE TITLE
SCnorm

### ISSUE THREAD

**Issue by rhondabacher** [Bioconductor/Contributions#377]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rhondabacher/SCnorm

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by LiNk-NY** [comment]
Hi Rhonda, @rhondabacher 

Please bump your package's version after you register to the bioc-devel mailing list. 

```
   * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```

Thanks, 
Marcel

**Comment by rhondabacher** [comment]
Do I need to bump the version again ?

**Comment by LiNk-NY** [comment]
Hi Rhonda, @rhondabacher 

Thank you for your submission. I took a quick look at your package and it seems like you are not using any of the Bioconductor infrastructure. It would be good to see you use `SummarizedExperiment` to represent your dataset. This method is preferred because `SummarizedExperiment` is a robust class for your data.

Regards,
Marcel

**Comment by rhondabacher** [comment]
Hi Marcel,

I appreciate your suggestion and have thought about it considerably. Given that most of our users are non-experts in R, I think the accessibility of our SCnorm package would be most successful keeping the classes in S3. Is it possible to move forward with our BioConductor submission without using the SummarizedExperiment classes?

Best,
Rhonda

**Comment by LiNk-NY** [comment]
Hi Rhonda, @rhondabacher

Please keep in mind that we value packages that are inter-operable with the existing Bioconductor infrastructure. This means providing an interface via `SummarizedExperiment` (or any other robust Bioconductor classes). There are many reasons for using S4 classes over S3. One such reason is that S4 allows for a more robust and structured class _with_ validity checks. Variation in user expertise is more easily controlled for by the package's API rather than the class system it uses.

Regards,
Marcel

**Comment by rhondabacher** [comment]
Hi Marcel,

Thanks for your suggestions. I have now included use of Summarized Experiment as well as BiocParallel in the SCnorm package. 

Best,
Rhonda

**Comment by LiNk-NY** [comment]
Hi Rhonda, @rhondabacher
Thank you for making those changes. I have taken a quick look at your package.
Please see the review below.

Feel free to contact me if you have any questions. 
Regards,
Marcel 

---

# SCnorm #377

## DESCRIPTION & NAMESPACE
Looks good.
* Please add relevant URL links to GitHub issues and source code.

## data
* Please rename the dataset provided to a more descriptive name. `ExampleData` can be any type of data. 

## inst & man
Looks good. 

## R
Major:
* Please make sure that you are not saving plots without the user's explicit request. It is best to remove these type of functionalities from functions like `checkCountDepth` as the user can just save the plot independent of the function.
* If the function is a plotting function, it should be indicated by its name. For example, rename `checkCountDepth` to `plotCountDepth` or something to that effect. 
* Please update documentation to indicate `SummarizedExperiment` support in the relevant functions (e.g., `checkCountDepth`) 
* Avoid growing a vector with code such as `Mode <- c(); for (i in 1:10) {Mode[i] <- foo}`. Use the allocate and fill method.
* Separate plotting and computing functions, some functions do both (e.g., `GetK`)
* Vectorize where possible, some functions are using `apply` and `sum`, these can be improved by using `rowSums`. 
* Use helper functions to avoid repetitive coding
* Use camelCase function naming conventions
* `getResults` is not very descriptive, please use a more descriptive name

Minor: 
Please follow Bioconductor's best practices as listed in the [package guidelines](http://bioconductor.org/developers/package-guidelines/). The following are some examples where best practices can be implemented: 
* avoid the use of `1:n` sequences, use the more robust `seq_len` or `seq_along` functions.
* avoid using `sapply`, use `vapply` for more robust outputs
* use `is(object, "SummarizedExperiment")` to test for S4 class membership
* avoid using a function like `c` as an object, e.g., `checkWithinFactor.R` line 74
* the usage section is automatically generated with roxygen2, there is little need to specify it yourself
* avoid the use of while loops where possible
* consider using `verbose = FALSE` arguments in functions that have a lot of message calls

## vignettes

* Nicely done. You showed the use of `SummarizedExperiment` which is helpful
for those looking to integrate their analysis with your method.

**Comment by rhondabacher** [comment]
Hi Marcel,

 I have implemented the major and most minor revisions you suggested. I do have two remaining while loops that are necessary, but I have put conditions and restrictions on them. I think your suggestions have improved the efficiency and usability of SCnorm. Thank you and I look forward to hearing your feedback.

Best,
Rhonda

**Comment by mtmorgan** [comment]
Hi Rhonda -- can you bump the version to 0.99.7 to trigger a final build?

**Comment by LiNk-NY** [comment]
Hi Rhonda, 
Sorry for the late response. 
Thank you for submitting to Bioconductor. Your package has been accepted. 

Regards,
Marcel

**Comment by rhondabacher** [comment]
Thank you Marcel!
