### ISSUE TITLE
Rhdf5lib

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/Contributions#378]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/grimbough/Rhdf5lib

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by dvantwisk** [comment]
Just a friendly reminder, your package still has build errors.  You can look over the build errors by clicking on the link in the message above.  We can only begin reviewing your package once it builds without errors.

~ Thanks! ~

**Comment by grimbough** [comment]
I am really struggling to diagnose the problem with the Windows build.  The error appears to be related to executing Makevars.win 
 
`make: C:/Users/BIOCBU~1/BBS-3~1.6-B/R/etc/x64/Makeconf: Permission denied`

but I'm unable to reproduce the error on any local Windows machines.  Running `Rcmd.exe build Rhdf5lib` simply works for me.  Any suggestions would be much appreciated.

**Comment by grimbough** [comment]
Are the commands reported at the top of the build report complete?  I'm trying to run them in exactly the same fashion to diagnose the problem, but I'm not sure they contain all the information required e.g.

> CheckCommand: C:\Users\biocbuild\bbs-3.6-bioc\R\bin/R CMD INSTALL --build --merge-multiarch --library=Rhdf5lib.buildbin-libdir Rhdf5lib_0.99.4.tar.gz >Rhdf5lib-install.out 2>&1

For me the equivalent just builds the package and doesn't invoke the checking.  Since I still can't replicate these new errors under Windows I just want to make sure I'm running the commands correctly.

**Comment by mtmorgan** [comment]
The wrong commands seem to be echoed; @lshep knows about this. The commands are I believe supposed to be the same as the regular builder, e.g., [zlibbioc][].

[zlibbioc]: http://bioconductor.org/checkResults/3.6/bioc-LATEST/zlibbioc/tokay1-checksrc.html

**Comment by lshep** [comment]
Sorry for the confusion.  The report does not show the right commands that are run during the process.  I will work on getting the right commands displayed on the report in the upcoming weeks. In the meantime, below are the commands that are run during our build and check process for your package: 

R Install Command:
```
C:\Users\biocbuild\bbs-3.6-bioc\R\bin/R CMD INSTALL --build --merge-multiarch -library=Rhdf5lib.buildbin-libdir Rhdf5lib_0.99.4.tar.gz >Rhdf5lib-install.out 2>&1
```
R Check Command:
```
C:\Users\biocbuild\bbs-3.6-bioc\R\bin/R CMD check --library=Rhdf5lib.buildbin-libdir --install='check:Rhdf5lib-install.out' --force-multiarch --no-vignettes --timings Rhdf5lib_0.99.4.tar.gz
```
R BiocCheck Command:
```
C:\Users\biocbuild\bbs-3.6-bioc\R\bin/R CMD BiocCheck --build-output-file=R.out --new-package Rhdf5lib_0.99.4.tar.gz
```

**Comment by grimbough** [comment]
So it sounds like the Windows build failed.  Perhaps you can have a look at the commands I'm running locally which get through R CMD check and let me know what I'm doing differently from the builder.

`rm -rf Rhdf5lib.buildbin-libdir Rhdf5lib.Rcheck && mkdir Rhdf5lib.buildbin-libdir Rhdf5lib.Rcheck && "c:\Program Files\R\R-3.4.0\bin\R.exe" CMD INSTALL --build --merge-multiarch --library=Rhdf5lib.buildbin-libdir Rhdf5lib_0.99.5.tar.gz >Rhdf5lib-install.out 2>&1 && "c:\Program Files\R\R-3.4.0\bin\R.exe" CMD check --library=Rhdf5lib.buildbin-libdir --install="check:Rhdf5lib-install.out" --force-multiarch --no-vignettes --timings Rhdf5lib_0.99.5.tar.gz`

Sorry for the horrible string of commands, I can't figure out multiple lines to the Windows prompt.

**Comment by dvantwisk** [comment]
We've reviewed your package!  Everything looks fine, but be sure that the licensing is consistent with hdf5lib's license.

DESCRIPTION
- Title/Description: Okay!
- Ensure licensing is consistent with hdf5lib license.

NAMESPACE
- Good!

R/zzz.R
- Looks fine!

man/pkgconfig.Rd
- Good!

vignettes/Rhdf5lib.Rmd
- Okay

**Comment by lshep** [comment]
@grimbough I'm working on testing the change to the running script that we had talked about; hopefully will be up later today so you can get a full windows report.

**Comment by grimbough** [comment]
@lshep Great.  I wasn't sure if it had already been implemented since @dvantwisk provided the review.  I merged the separate branch I had been working on to stop it spamming here with failed builds, but I'll hang back from committing any other changes until I hear from you. Cheers.

**Comment by lshep** [comment]
since we don't see this with really any other package, I will probably kick off a manually build of your package once I implement it;  so don't be alarmed if you see a build report or two pop up without you doing a version bump.

**Comment by lshep** [comment]
I made the switch.  Hopefully it should be good now. You should receive a build report momentarily

**Comment by grimbough** [comment]
@lshep Thanks for making the change to the build script, looks like it's handling the multi-arch installation correctly now.

I'm not sure if the remaining WARNING is important.  I've no idea how to change the windows permissions on the `cleanup` and `configure` scripts, and I don't think they're executed on Windows anyway.  There are also many packages in the main repo that report the same messages (e.g. [Rhtslib](http://bioconductor.org/checkResults/3.5/bioc-LATEST/Rhtslib/tokay2-buildsrc.html) or [netReg](http://bioconductor.org/checkResults/3.5/bioc-LATEST/netReg/tokay2-buildsrc.html)) and they don't get the WARNING flag next to the Build status.

Please let me know if I'm missing something obvious.

**Comment by mtmorgan** [comment]
I'd recommend ignoring...

**Comment by grimbough** [comment]
So is this good to be included in the devel branch, or are there more recommendations?

**Comment by grimbough** [comment]
That's great news, many thanks.
