### ISSUE TITLE
oneSENSE

### ISSUE THREAD

**Issue by yongkee** [Bioconductor/Contributions#382]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JinmiaoChenLab/oneSENSE/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by nturaga** [comment]
Hi @yongkee Your package doesn't build on the Linux and the Mac builders. Please check the build report http://bioconductor.org/spb_reports/oneSENSE_buildreport_20170530093551.html

**Comment by yongkee** [comment]
The primary issue with the previous version was the tcltk package. Hence I have removed it and ported GUI capabilities of tcltk to shiny.

Also, I am changing the location of my github directory under an organisation. Do I have to resubmit the package as an issue?

Currently my github repos for oneSENSE is [here](`https://github.com/JinmiaoChenLab/oneSENSE`)

**Comment by nturaga** [comment]
Please bump the version so the build runs.

**Comment by nturaga** [comment]
Please address the Errors

```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```

and warnings,

```
* Checking R Version dependency...
    * WARNING: Update R version dependency from 3.3.0 to 3.4.
```

and the following Note's,

```
* Checking for <<-...
    Found <<- in R/YKOneSmapperFlour.R (line 255, column 7)
    * NOTE: Avoid '<<-' if possible (found in 1 files)

    * NOTE: Consider multiples of 4 spaces for line indents, 242
      lines(24%) are not.
```
(Consider using [formatR](https://yihui.name/formatr/))

**Comment by yongkee** [comment]
@nturaga i have change repos location to https://github.com/JinmiaoChenLab/oneSENSE/

However, when i update the version in description, it is unable to run the checks. How can i remedy this?

**Comment by nturaga** [comment]
# oneSENSE package review

## Build and Install

R-release CMD build oneSENSE: ok

R-release CMD INSTALL oneSENSE_0.99.6.tar.gz: ok

## DESCRIPTION

* `Description` section needs to be like a paper abstract, to make it more informative. Possibly use "Rationale of One-SENSE" as part of this, that will be more informative.

## NAMESPACE

* ok

## man

* Please include runnable examples in the man pages. 

## vignette

* The package focuses on a shiny app, there needs to be some screenshots in the vignette to show users how to go about starting the app, and the steps to use the app.

* Spell check the vignette.

* The Rmd file is not correctly written. There is no vignette generated upon building the package, this is because there are no Rmarkdown components in that file `quickstart.Rmd`. It is merely a markdown file. 

Please use the R-markdown annotation, (http://rmarkdown.rstudio.com/lesson-4.html)
a
eg: 

<pre>
```{r, eval=FALSE}
 source("https://bioconductor.org/biocLite.R")
 biocLite("oneSENSE")
```
</pre>

# R

* Consistently name `oneSENSE` in the same casing. eg: onesense_GUI vs oneSENSE

* Remove commented out code.

* Use formatR for more consistent code styling, use 4 spaces instead of 2 for indentation. (https://cran.r-project.org/web/packages/formatR)

* There is an error in your onesense_GUI().  

```
> onesense_GUI()

Listening on http://127.0.0.1:3564
Warning: Error in do.call: object 'volumes' not found
Stack trace (innermost first):
    45: do.call
    44: shinyDirChoose
    43: server
     2: runApp
     1: onesense_GUI
Error in do.call("dirGetter", list(...)) : object 'volumes' not found
```

## General Comments

* Address and resolve the NOTE  sections in the build report

```
* Checking for <<-...
    Found <<- in R/YKOneSmapperFlour.R (line 251, column 11)
    * NOTE: Avoid '<<-' if possible (found in 1 files)
```

```
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * NOTE: Consider shorter lines; 131 lines (13%) are > 80 characters
      long.
    First 6 lines:
      R/FCStSNE.R:8 #' @param FNnames .csv file generated when markers from e...
      R/FCStSNE.R:18 #' @importFrom flowCore read.flowSet exprs keyword write...
      R/FCStSNE.R:32                      Bins = 250) #it doesnt use the vari...
      R/FCStSNE.R:34   fs <-read.flowSet(path = LoaderPATH, pattern = ".fcs$"...
      R/FCStSNE.R:35   FcsFileNames <- rownames(keyword(fs, "FILENAME")) #key...
      R/FCStSNE.R:40     FFt <- exprs(fs[[FFs]]) # assign matrix (row:events,...
    * NOTE: Consider multiples of 4 spaces for line indents, 242
      lines(24%) are not.
```

**Comment by yongkee** [comment]
updated version to 0.99.3

**Comment by yongkee** [comment]
@nturaga resolved most issues, except for formatting.

**Comment by nturaga** [comment]
Hi @yongkee, See https://github.com/Bioconductor/Contributions#adding-a-web-hook and https://github.com/Bioconductor/Contributions#additional-actions. Is your web hook set up correctly?

**Comment by yongkee** [comment]
@nturaga @mtmorgan thanks for the assistance. I've added the webhook successfully. I've also changed the repository.

**Comment by yongkee** [comment]
Hi,

I was wondering when onesense will be released as non-devel version?

Is there a release schedule of packages?



Yours Sincerely,

Tan Yong Kee
Faculty of Science, Computational Biology Undergraduate
NUS
________________________________

**Comment by nturaga** [comment]
https://www.bioconductor.org/about/release-announcements/ 

It will be in October.
