### ISSUE TITLE
OnassisJavaLibs

### ISSUE THREAD

**Issue by eugeniaeueu** [Bioconductor/Contributions#383]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository:https://github.com/eugeniaeueu/OnassisJavaLibs

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by eugeniaeueu** [comment]
Hi, this package contains libraries to solve the Issues related to the package Onassis (issue package #365).

**Comment by mtmorgan** [comment]
@vobencha -- I'll take over the review of this package.

**Comment by mtmorgan** [comment]
Please provide a short vignette that indicates the purpose of this package.

**Comment by eugeniaeueu** [comment]
Hi, 
I created this package as a data package,  that includes the java source code of the libraries imported by Onassis. I don't know how to solve the issue related to the representation of the long paths when gzipping the package. Can you please give some advice? Thanks,

Eugenia

**Comment by mtmorgan** [comment]
The note about long lengths should be ignored; I believe this is not commonly encountered, and there is little that can be done anyway. The current Windows error looks transient. I will review your package this week.

**Comment by nturaga** [comment]
Hi @eugeniaeueu ,

```
  conflicting biocViews subgraphs:
    OnassisJavaLibs: ExperimentData (ExperimentData), DataImport (Software)
```

This package needs to have biocViews terms only from the ExperimentData hierarchy.
