### ISSUE TITLE
Scale4C

### ISSUE THREAD

**Issue by walter-ca** [Bioconductor/Contributions#384]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/walter-ca/Scale4C

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by walter-ca** [comment]
Thank you for the prompt response. In hindsight, I fully agree on the GRanges part; unless I missed something, most data frames of the package should now have been replaced by GRanges objects. The exception is the export table in the alternative "not onlyPeaks" mode, where I'd like to have a table that contains one central region with two neighbouring regions - putting that into metadata columns for GRanges felt a bit forced. The main/usual output exports a GRanges object, though.

However, I do have slight issues with the SummarizedExperiment objective. As far as I understood the package, it's for matrices of the form genomic-ranges vs samples (like affy array data or whatever), while the two matrices I use contain data of the form scale-factor vs coordinate. Did I understand your criticism wrong, or the package's intention?

Thanks in advance for clarifying.

**Comment by lawremi** [comment]
If it makes sense to store annotations on the rows and/or columns of the matrices, then a SummarizedExperiment structure probably makes sense. The API is more general than features vs. samples. Only use a RangedSummarizedExperiment if the rows correspond to genomic ranges.

**Comment by walter-ca** [comment]
Okay, I do get the difference between SummarizedExperiment and RangedSummarizedExperiment. I also re-read its vignette and I do understand its usefulness for array data.

The annotation part is the part where I am struggling right now for my personal matrices, because in its current form, the proposed package just doesn't use those for both objects. My row data is an index of fragments, running from 1 to nrow(frags), and the column data is a scale factor that increases in steps of "1" to a certain maximum of choice. Of course these fragments do have their coordinates as genomic intervals, but for one matrix, I'm just tracking curves of 1 or -2 from neighbour fragment to neighbour fragment, with no interest at all where this neighbour is located. 
Until now, my matrices therefore literally look like the default,
  V1 V2 V3 V4 V5
1
2
3
because I have not bothered with the row names or column names at all and just access the values I need by [x,y].

I'm sorry if I miss something obvious (like a performance issue with the basic matrix?); I can certainly integrate SummarizedExperiment in place of the matrices next week. But I still fail to see why it is necessary or which advantages it has in this situation.

**Comment by lawremi** [comment]
I'm not familiar with 4C data, but it's typically helpful to have self-contained objects. SummarizedExperiment would attach the data to the fragment ranges (and any other metadata known about the fragments). Otherwise, the user is juggling the data and metadata separately, which is complicated, inconvenient, and error-prone.

**Comment by walter-ca** [comment]
I see, good point. Actually I could have saved myself some trouble for the later functions, come to think of it.
Thanks, I'm going to adapt the code.

**Comment by walter-ca** [comment]
Changes regarding the integration of standard BioC classes:

1. Both matrices should now be combined into one SummarizedExperiment object called "scaleSpace" with two assays; all metadata (fragment coordinates as ranges, scaling factor sigma) is included.
Old "scaleSpace matrix" is now assay 1 of scaleSpace, old "fingerprint matrix" is assay 2.

2. GenomicRanges have replaced data frames. Example data (vp, points of interest) changed accordingly.

Minor changes: 
- Reduced maximum sigma in example from 2500 to 2000 due to size; reduced array sizes of example objects to 0.99.3 version sigma = 50 since it was not sufficient without "resave-data" flag
- some minor edits in vignette
- removed 'importBed' due to triviality of issue when using any import + GenomicRanges constructor or Genomic Ranges functions

**Comment by vobencha** [comment]
@walter-ca thanks for making the changes. General package structure looks good to me. @lawremi , did you have any follow up comments?
Val

**Comment by lawremi** [comment]
Looks good to me.

**Comment by vobencha** [comment]
Approving this package.
