### ISSUE TITLE
zFPKM

### ISSUE THREAD

**Issue by ronammar** [Bioconductor/Contributions#385]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ronammar/zFPKM

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
The vignette isn't really acceptable; it should illustrate how the package integrates into typical Bioconductor work flows. Use of standard Bioconductor data representations facilitates interoperability between packages, reproducibility (e.g., tracking  'metadata' about samples and experiments) and utility. So it's amazing that you don't have any Bioconductor dependencies, e.g., GenomicRanges for representing genomic coordinates, SummarizedExperiment for representing RNASeq count data, rtracklayer and tximport for import / export of standard precursors to the analysis that you enable.

**Comment by ronammar** [comment]
Hi @mtmorgan, thanks for the feedback. Can you point me to a vignette that integrates well so I can use it as an example?

**Comment by mtmorgan** [comment]
[tximport][] for instance.

[tximport]: http://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html

**Comment by ronammar** [comment]
Hi, why am I getting the following error on only 2/3 platforms? I confirmed my subscription to the bioc-devel mailing list.

```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```

**Comment by mtmorgan** [comment]
I don't see your email address (from the DESCRIPTION) file in the bioc-devel mailing list. When you subscribed, the mailman software sends a confirmation that you need to respond to. This often ends up in spam folders.

**Comment by ronammar** [comment]
Apologies - I think the confirmation I received was from BioC support. However, I've now signed up for the bioc-devel mailing list twice today and haven't received a confirmation email in my inbox or junk mail. 

Can my subscription request be confirmed by the list moderator?

**Comment by mtmorgan** [comment]
I now see your subscription on the mailing list. It's tagged as indicating that the user (you) have chosen not to receive email. I'm not sure if this is mailman's way of saying you haven't responded to the acknowledgement or that you have actually configured your account this way?

**Comment by ronammar** [comment]
Corporate mail filtering released "junk" mail it in a weird way. That was my attempt to turn mail on. Anyway, I've confirmed membership.

**Comment by ronammar** [comment]
Ok I've got an error on Linux: `Fatal error: cannot create 'R_TempDir'`
Is this a permissions issue or a full `/tmp` directory issue (as suggested on [SO](https://stackoverflow.com/questions/6307836/fatal-error-cannot-mkdir-r-tempdir))? Advice?

Also, the warnings on OS X and Windows pertain to an existing `inst/doc` path. How should I resolve this?

Thanks!

**Comment by mtmorgan** [comment]
Yeah the linux problem is on our end.The content of your 'inst/doc' directory are actually generated by the R CMD build step, and should not be in your git repository.

**Comment by ronammar** [comment]
The sole error that remains is the Linux system issue with temp directories. How should I proceed?

**Comment by mtmorgan** [comment]
Wait for the formal review from @LiNk-NY

**Comment by LiNk-NY** [comment]
Thank you @mtmorgan for generous input and follow-up on Ron's package. 

Ron, @ronammar
Thank you for submitting to Bioconductor. 
Although you've made changes to the vignette, it does not seem complete since it doesn't make use of the Bioconductor infrastructure already available.

A few preliminary points: 

* Please make sure you are using `SummarizedExperiment` to represent your RNAseq count data. If you are also working with ranged data, strongly consider using the `GenomicRanges` package.
* Once you switch to this infrastructure, the use of `dplyr` will not be required. 
* Please do not output plots passively. This should be done by explicit request from the user and should be separated as its own function rather than your main function. 
* Ideally, your main function should be the same name as the package. 
* Include `R (>= 3.4.0)` in the `Depends` field in the `DESCRIPTION` file.

Regards,
Marcel

**Comment by ronammar** [comment]
Thanks @LiNk-NY for your valuable feedback, and @mtmorgan for all your help so far!

I have done my best to address your points:
- I now make use of `SummarizedExperiment`'s where needed
- I have removed `dplyr` except where group-wise operations are required, and these do not substitute the Bioconductor infrastructure.
- Plots are output by `zFPKMPlot()` and the main function now has the same name as the package, `zFPKM()`.
- Is it ok to include `Depends: R (>= 3.3.3)` instead?

**Comment by ronammar** [comment]
For some reason, the Bioconductor package `GEOquery` periodically and unexpectedly yields errors connecting to NCBI. Aside from this error, the builds appear to be working. I've contacted the package maintainer for help. Thoughts?

**Comment by ronammar** [comment]
Hi- any thoughts on next steps to progress with this submission? I think the package is building correctly, but `GEOquery` is crashing, causing my package build to have errors unexpectedly. Should I bundle .rds with the vignette to circumvent this potential error?

**Comment by LiNk-NY** [comment]
Yes, you can do that. 
Create a subset of the dataset from `GEOquery` and add it to your vignette examples. 

I will have a second look at this soon. Thanks. 

Regards,
Marcel

**Comment by ronammar** [comment]
Thanks @LiNk-NY, I followed your suggestion, and bundled a .rds file with the vignette.

**Comment by ronammar** [comment]
Hi @LiNk-NY, is there anything else that came up during review? Thanks!

**Comment by LiNk-NY** [comment]
Hi Ron, @ronammar 
Sorry for the delay. I will get to your package soon. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Ron, @ronammar

It doesn't seem like you are using `SummarizedExperiment` as you have stated previously. Have you rolled 
back to a previous commit? 

I don't see `SummarizedExperiment` in the `DESCRIPTION` file. 

Regards,
Marcel

**Comment by ronammar** [comment]
Hi @LiNk-NY, thanks for your feedback. I've updated my repository to include `SummarizedExperiment` where appropriate. Please let me know if anything else is required after review.

**Comment by LiNk-NY** [comment]
Hi Ron, @ronammar
Thanks for making that change.

Your package is most of the way there. There are some minor issues that can be addressed.

* Make use of helper functions to avoid repeating yourself in functions like `zFPKMPlot` and `zFPKM`.
* Separate functionality. `PlotGaussianFit` should be two different functions the gaussian fit function and the plotting function. Please separate the two. This will avoid calling a plotting function when you just want to fit the model as in `zFPKMTransform`.

Please consider that most plotting functions output to the device and not to a file. A user wishing to save a file will do so in the format of their choosing. You should just limit the plotting function to returning the figure in the graphics device.

Regards,
Marcel

**Comment by ronammar** [comment]
Hi Marcel (@LiNk-NY),

Thanks again for your review and the suggestions to improve the package.

Note, the recent build report appears to have an error and was run on a single OS. I'm uncertain as to the cause- Is this an error on my end?

Addressing your feedback:
- I am now using a helper function and have removed redundant calls.
- The `PlotGaussianFitDF` function performs plotting-specific scaled fits that are distinct from the zFPKM transformation, but are required for the final plot. This computation is easier to understand within the context of the `PlotGaussianFitDF` function rather than separated. So, the `zFPKMTransform` and plotting fitting are independent and distinct, even though they appear similar.

Thanks!
Ron

**Comment by LiNk-NY** [comment]
Hi Ron, @ronammar
Thanks for looking into it. 

* Please keep a NEWS file in the `inst` folder in your package for updates on the versions.
* If your imports are not central to what your package does, then they should be in suggests. It seems to me like `checkmate` can be an optional package dependency and is not needed.
* Use the more robust double bracket extractor method rather than the `$` (e.g., `d[["m"]]` vs `d$m`)

Minor
* check class membership with `is(object, "SummarizedExperiment")`
* avoid using "this" as object names, it's not descriptive

The package is close to being accepted. Thanks. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Ron, @ronammar 
The package is close to completion and should be accepted as soon as you make those minor changes.
Are you able to make those changes and bump the version?

Thanks,
Marcel

**Comment by ronammar** [comment]
Hi Marcel (@LiNk-NY),

Thanks again for your review and the suggestions to improve the package. I have updated the package accordingly. Please advise.

Regards,
Ron

**Comment by ronammar** [comment]
Excellent! Thanks, Marcel @LiNk-NY!

**Comment by ronammar** [comment]
Hello @mtmorgan @LiNk-NY, I've added a requested biocViews tag and pushed. How do I trigger a new build? Thanks!

**Comment by mtmorgan** [comment]
Since your package has been accepted, changes need to be made to the Bioconductor git repository rather than to your github repository. Resources are available at http://bioconductor.org/developers/how-to/git/ ; be sure to use the bioc-devel mailing list https://stat.ethz.ch/mailman/listinfo/bioc-devel for communication about issues like this.
