### ISSUE TITLE
diffuStats

### ISSUE THREAD

**Issue by SergiPicart** [Bioconductor/Contributions#387]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/b2slab/diffuStats

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by SergiPicart** [comment]
Dear Nitesh, 

I have tried to reproduce the build error on a virtual windows machine, but the building process completed fine. 
The error mentions permission issues - can this be due to the machine configuration? The package contains Rcpp code.

Thank you,

**Comment by nturaga** [comment]
Hi @SergiPicart Before we get into the build error, you'd have to do a couple of things,

1. Change the name of the package, `diffusion` is a very generic package name.

2. Edit the issue name to reflect the change, the issue should contain just your package name. You do not need `Submission....etc`.

**Comment by SergiPicart** [comment]
Hi @nturaga , we have changed the package name and the issue with Windows is gone, the mailing list confirmed it was due to tokay1's configuration. Is there anything else we should do before the review?
Thank you

**Comment by nturaga** [comment]
@SergiPicart I'll review it and get back to you.

**Comment by nturaga** [comment]
# diffuStats Review

## Build

R-release CMD build diffuStats: Ok.

R-release CMD INSTALL diffuStats : ok

## DESCRIPTION

* ok

## NAMESPACE

* ok

## man

* good

## vignette

* Good to see use of Bioconductor colors in vignette. 

* Change name of vignette from `yeast.Rnw` to diffuStats.Rnw. 

## R

* remove commented out code.

* Remove debug statements `browser()` in between code.

* in diffuse.R:117

```
			 mat_complete <- apply(
				 mat,
				 2,
				 function(col) {
					 n_pos <- sum(col)
					 n_neg <- n_bkgd - n_pos

					 col[col == 0] <- -1

					 p <- (n_pos - n_neg)/(n_tot)
					 c(col, rep(p, n_tot - n_bkgd))
				 }
			 )
```

This is a 'nested iteration' (apply inside lapply) so will have poor performance. Try to 'vectorize' instead, typically by 'hoisting' iterative calculations outside the iteration.

```
## vectorized calculations, not iterations
n_pos <- colSums(mat)
n_neg <- n_bkgd - n_pos
p <- (n_pos - n_neg) / n_tot

res = mat    # copy, to avoid modifying mat?
res[res == 0] <- -1
## ?? c(col, rep(p, n_tot-n_bkgd)) seems like it is also vectorizable?
```

* diffuse_mc.R, line 190 and elsewhere, the `gc()` is not needed because R runs a garbage collector when it needs memory. 


## Cpp

* Remove commented out code

**Comment by SergiPicart** [comment]
Thank you for your thorough review. 
All the points have been addressed in the new version (0.99.9), although it seems the bot has not noticed the last push. In particular, the code that you mention has been vectorised. Some references in the vignette have been fixed as well (incorrect URLs)
If this is not a nuisance, I would ask you to consider adding on top some changes to improve the package functionality, which are kept in a separate branch (version 0.99.10):

- Function "diffuse_mc" can work with quantitative inputs as well
- Unit testing have been updated accordingly
- Slight modifications to the compiled code
- Functions that do not use quantitative inputs now throw an exception

Otherwise, you can just take the version 0.99.9 from master. 
Thank you very much

**Comment by nturaga** [comment]
@SergiPicart We'll kick off a build manually tomorrow.

**Comment by SergiPicart** [comment]
@nturaga It seems that the package passes the cheks. 
Have you considered the update I mentioned in my last post? Should I push that version?

Thank you for everything

**Comment by nturaga** [comment]
Hi @SergiPicart , I cannot add functionality to your package. My role is that of a reviewer. Please let me know if you'd like me to check your current version, if you think its ready for a review again.  I would merge everything you want reviewed to the `master` branch

**Comment by SergiPicart** [comment]
Hi @nturaga , I have merged the changes in the master branch, but the bot has not noticed. Can we review that version?
Thank you

**Comment by nturaga** [comment]
Update version for the bot to notice.

**Comment by SergiPicart** [comment]
I already updated the master branch, but still not noticing

**Comment by SergiPicart** [comment]
Hi @nturaga , I have updated again and the bot does not see it. Please, can you trigger a manual build and review the current version? Thank you
