### ISSUE TITLE
RProtoBufLib

### ISSUE THREAD

**Issue by mikejiang** [Bioconductor/Contributions#391]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RGLab/RProtoBufLib
Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Before moderation and review, your package requires a vignette (e.g., covering material like that in the zlibbioc vignette). Also please explain how this package differs from [RProtoBuf][] and verify that you redistribution satisfies the licensing conditions of the underlying library.

[RProtoBuf]: https://cran.r-project.org/package=RProtoBuf

**Comment by mikejiang** [comment]
vignette is added and license is updated. See explanation [here](https://github.com/RGLab/RProtoBufLib/blob/master/vignettes/UsingRProtoBufLib.Rmd)

**Comment by LiNk-NY** [comment]
Hi Mike, @mikejiang 

Did you set up a web hook for the package? 


### RProtoBufLib #391
----

The package looks good. 

I would just suggest that you make sure you are filtering out the compiled files (if any) that should not be uploaded to GitHub and or used for building the package. Make sure you have a `.gitignore` with those files and a proper `.Rbuildignore`. 

Also, you can resolve a build warning by adding a `@return` tag with some text to the function documentation in `zzz.R`. 

Regards,
Marcel

**Comment by mikejiang** [comment]
@LiNk-NY 
Yes, I did. And I pushed the updates as you recommended.
Regarding to complied files, were you referring to `https://github.com/RGLab/RProtoBufLib/tree/master/src/win/lib`? These are prebuilt binary libs for windows ( simply following the same practice as `rhdf5`)

**Comment by LiNk-NY** [comment]
Hi Mike, @mikejiang

I was just noting that for any files in general. Those mentioned are needed for windows support.
Thanks for adding those to the `.gitignore`.

There are still some minor errors to be resolved.
After addressing those, your package will be approved.

Thanks,
Marcel

**Comment by mikejiang** [comment]
How do I see the latest build report?

**Comment by mikejiang** [comment]
@LiNk-NY 
I could not reproduce there two errors, it checks ok for me locally
```bash
* Checking whether vignette is built with 'R CMD build'...
    * ERROR: Vignette must be built by 'R CMD build'. Please see the
      `Vignette Checks` section of the BiocCheck vignette.
 * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
```

**Comment by LiNk-NY** [comment]
Hi Mike, @mikejiang

I just built the package locally and I didn't get them either.
I will mark your package as accepted.

Thanks!

Regards,
Marcel

**Comment by mikejiang** [comment]
Great!Thanks.

**Comment by mikejiang** [comment]
Looks like the package has not been added to devel branch yet, wondering if anything is still wrong with it?

**Comment by mtmorgan** [comment]
patience, sorry
