### ISSUE TITLE
ComSeq: An ensemble method for RNA-Seq differential analysis

### ISSUE THREAD

**Issue by DongmeiLi2017** [Bioconductor/Contributions#398]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DongmeiLi2017/ComSeq

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by DongmeiLi2017** [comment]
This package is renamed from previous submitted package "Combine".

**Comment by nturaga** [comment]
# ComSeq review

## Build

R-release CMD build ComSeq: ok

R-release CMD INSTALL ComSeq: ok

## DESCRIPTION

* `Description` needs to follow a paper abstract format and needs to be more informative.

## NAMESPACE

* ok

## man

* ok

## Vignette

* The vignette needs more information. The way it is represented is not informative to the user.

* The way the result is shown is of no value to the user. The permutations are irrelavent, and the Result should be shown in a more meaningful way in the vignette.

## R

* Use SummarizedExperiment as an input for your `Combined_method` function. See, www.bioconductor.org/packages/SummarizedExperiment

* In, the function, your arguement `label` should be a column in the colData of SummarizedExperiment.

* At the start of your function, your should validate your inputs(label and alpha).

* Use formatR to format your R code to meet the standards. (https://cran.r-project.org/web/packages/formatR)

* Check the following NOTE:

	```
	* Checking package NEWS...
		* NOTE: Consider adding a NEWS file, so your package news will be
		  included in Bioconductor release announcements.
	* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
	  and vignette source...
		* NOTE: Consider shorter lines; 38 lines (16%) are > 80 characters
		  long.
		First 6 lines:
		  R/Combined_method.R:23   group.con <- data.frame(cbind(c(rep("control",...
		  R/Combined_method.R:25   rownames(group.con) <- c(paste("control", 1:su...
		  R/Combined_method.R:27   DESeq2.dds <- DESeqDataSetFromMatrix(countData...
		  R/Combined_method.R:34   DESeq2.sig.gene <- as.numeric(rownames(RNAseqc...
		  R/Combined_method.R:39   EBSeq.out <- EBTest(Data = count.norm, Conditi...
		  R/Combined_method.R:45   EBSeq.sig.gene <- as.numeric(rownames(RNAseqco...
		* NOTE: Consider multiples of 4 spaces for line indents, 58
		  lines(24%) are not.
	```

* Too many magic numbers in parameters for running DESeq2, EBseq2, etc. There has been no logic given for why these parameters were chosen. It will appear to be a black box for users. Expose the parameters as your main functions arguments, use default values but justify them in your vigentte and man pages.

* Please explain why you use certain normalization methods used across each package and other scientific assumptions in the vignette in a detailed manner.

**Comment by nturaga** [comment]
@DongmeiLi2017 Please bump the version

**Comment by nturaga** [comment]
@DongmeiLi2017 Please bump the version. And provide a summary of changes when you are ready for second review.

**Comment by nturaga** [comment]
HI @DongmeiLi2017 Let me know when you have made the changes providing a summary. I'll review your package again.

**Comment by nturaga** [comment]
@DongmeiLi2017 Please provide a summary of the changes you have made as soon as you can.

**Comment by nturaga** [comment]
@DongmeiLi2017 Please fix the build issues and all other issues as per the review previously. We usually give the maintainer about 2 weeks to respond before closing the issue. 

Since you weren't made aware of this before, I will wait till Oct 19th before closing the issue if there is no response. 

Thanks.

**Comment by DongmeiLi2017** [comment]
Hi Nitesh,

Thanks so much for your reminder! Could you please close the current issues for ComSeq? We have decided to integrate another method in ComSeq and will revise the ComSeq package and resubmit in a later time. Thanks so much!

Best,
Dongmei
