### ISSUE TITLE
survBootOutliers

### ISSUE THREAD

**Issue by jonydog** [Bioconductor/Contributions#399]
- Repository: https://github.com/jonydog/survBootOutliers

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by vobencha** [comment]
Hi,
Just fyi, the errors in the Single Package Builder output must be cleaned up before I do a full review.
Valerie

**Comment by jonydog** [comment]
Thank you for the reminder. I have been busy, I will make a fix very shortly.

Joao

**Comment by vobencha** [comment]
FYI I'm out of the office July 26 - Aug 2. If you have not submitted a new version by Aug 7 I'll close the issue. You can resubmit when you have time to work on the package.
Valerie

**Comment by jonydog** [comment]
Hi there.

I was full of work this month, I am pretty sure I will have some spare time to  fix the build this week, is it possible to have this week to fix the build?

Thanks in advance.

João Pinto

________________________________
De: vobencha <notifications@github.com>
Enviado: segunda-feira, 24 de julho de 2017 13:17
Para: Bioconductor/Contributions
Cc: João DIogo Pinto; Mention
Assunto: Re: [Bioconductor/Contributions] survBootOutliers (#399)


FYI I'm out of the office July 26 - Aug 2. If you have not submitted a new version by Aug 7 I'll close the issue. You can resubmit when you have time to work on the package.
Valerie

**Comment by vobencha** [comment]
Yes we can wait another week.
Valerie

**Comment by jonydog** [comment]
Thank you!


________________________________
De: vobencha <notifications@github.com>
Enviado: segunda-feira, 7 de agosto de 2017 13:52
Para: Bioconductor/Contributions
Cc: João DIogo Pinto; Mention
Assunto: Re: [Bioconductor/Contributions] survBootOutliers (#399)


Yes we can wait another week.
Valerie

**Comment by vobencha** [comment]
Closing this issue. Please open a new issue when you have a new version to submit.

**Comment by jonydog** [comment]
Hello Valerie.

Finally I did the necessary fixes and also added some features, can the review process continue ?

Thanks.

Joao

**Comment by jonydog** [comment]
I have two closed issues, one in the first page and this one, is that supposed to happen?

**Comment by vobencha** [comment]
Re-opening this issue to continue the review.

**Comment by vobencha** [comment]
I'm not sure what you mean by 2 closed issues - I see only the one which is now re-opened. Can you provide links?

**Comment by jonydog** [comment]
The other one is this: https://github.com/Bioconductor/Contributions/issues/486 

I filed a new issue first, then I realised i probably just needed to communicate the fix in the same issue.  Sorry.

**Comment by vobencha** [comment]
OK. We'll leave #486 closed. Please move/consolidate all details to this issue.

**Comment by vobencha** [comment]
@lshep This issue was closed and we've reopened it. It still has the (inactive) tag in the title. Does this matter, i.e., will it mess with the webhook? I wasn't sure if I should manually remove it or if it should be done in a different interface or just let it be.

**Comment by jonydog** [comment]
Ok I did not know I had to subscribe to the bioc-devel as a maintainer. I just subscribed, I am just waiting confirmation before doing another commit.

**Comment by vobencha** [comment]
You do not need to subscribe to the list as 'maintainer'. The message is saying that the person in the maintainer field of the DESCRIPTION file needs to subscribe to this list. The point is to be able to send emails to the maintainer when the package is broken.

**Comment by jonydog** [comment]
I am the maintainer and I understand the purpose, I just didn't know ;)

**Comment by vobencha** [comment]
Hi,
I've taken a quick look at the package. It looks like a purely statistical methods package and very useful for the R community in general but it doesn't seem like a fit for Bioconductor.

Bioconductor hosts packages specific to genomics/proteomics/*-omics data. Packages in Bioconductor should build upon existing infrastructure by extending packages and reusing classes and methods. Your package has no such dependencies.

Please consider submitting the package to CRAN. If you want to submit to Biocondcutor the package needs to be rewritten to use existing infrastructure and real data for examples and the vignette, potentially from the experimental data repo here:
http://www.bioconductor.org/packages/release/BiocViews.html#___ExperimentData

For an example of a full featured Bioconductor statistical methods package please see the source code for [edgeR](http://www.bioconductor.org/packages/release/bioc/html/edgeR.html) or [DESeq2](http://www.bioconductor.org/packages/release/bioc/html/DESeq2.html).

Valerie

**Comment by vobencha** [comment]
Any thoughts on https://github.com/Bioconductor/Contributions/issues/399#issuecomment-333720636?

**Comment by jonydog** [comment]
I think what you said makes sense, and I communicated that to my colleagues.

We will move to CRAN I am just waiting for the answer of one of my colleague, then I communicate that the decision is made. Sorry for the delay in my response.

On 25 Oct 2017, at 18:36, vobencha <notifications@github.com<mailto:notifications@github.com>> wrote:


Any thoughts on #399 (comment)<https://github.com/Bioconductor/Contributions/issues/399#issuecomment-333720636>?

**Comment by jonydog** [comment]
OK we are moving to CRAN, thanks a lot for your help.

**Comment by vobencha** [comment]
Sounds good. I'll close this issue.
