### ISSUE TITLE
mfa

### ISSUE THREAD

**Issue by kieranrcampbell** [Bioconductor/Contributions#403]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kieranrcampbell/mfa
Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor. The package looks good and is very close to acceptance. Some minor concerns/clarification points: 

VIGNETTE: 
- [ ] We recommend include an installation section: 
```
source("https://bioconductor.org/biocLite.R")
biocLite("mfa")
library(mfa)
```

R CODE: 
- [ ] Just a clarification question:  lines 240/243 if looks as if you are filling each column with a static column from the previous object; is this correct? 
- [ ] line 292:  please use seq_len() instead of 1:n 

Once these minor points are addressed, please comment back here and also bump the version (e.g. 0.99.1) to kick off a new build.  

Cheers

**Comment by kieranrcampbell** [comment]
Hi @lshep 

Thanks for your review. Points addressed below

> We recommend include an installation section:

Added.

> Just a clarification question: lines 240/243 if looks as if you are filling each column with a static column from the previous object; is this correct?

Yes, this initialises the factor loading matrix, but the intercept and gradient matrices are separate, hence this rather odd bit of code.

> line 292: please use seq_len() instead of 1:n

Added.

> Once these minor points are addressed, please comment back here and also bump the version (e.g. 0.99.1) to kick off a new build.

Great, done.

**Comment by lshep** [comment]
Thank you for the clarification and the updates.  Your package has been accepted. Please leave the issue open and you will receive further instructions via email within the next several days
