### ISSUE TITLE
seqcombo

### ISSUE THREAD

**Issue by GuangchuangYu** [Bioconductor/Contributions#410]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GuangchuangYu/seqcombo

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by LiNk-NY** [comment]
Hi GuangChuang, @GuangchuangYu
My apologies for the delay in getting to your package.
I will review it shortly. 

Best regards,
Marcel

**Comment by GuangchuangYu** [comment]
@LiNk-NY No problem and take your time.

**Comment by LiNk-NY** [comment]
Hi GuangChuang, @GuangchuangYu
Thanks for submitting to Bioconductor.
Can you briefly explain how your package integrates with Bioconductor?

Major: 
* No need to export functions like `%>%`, `plot`

There a few minor points to address: 

* Create accessor functions for extracting data from your object class
* Use consistent naming conventions, `hybridplot` should be `hybrid_plot`
* You can use `anyDuplicated` rather than `which(duplicated(object))`
* Avoid the use of `sapply`
* Avoid sequence generation via `1:n`, use `seq_along` or `seq_len`

**Comment by GuangchuangYu** [comment]
All the Major and Minor issues had been fixed. In my opinion, if Bioconductor has a `phylo` BiocView, there is no problem of integrating this package to Bioconductor. There are already several packages that are phylogenetic-related, such as phyloseq, philr and my ggtree. BTW: I will extend the `hybrid_plot` to work with tempo-spatial data when I have some data on hand.

**Comment by LiNk-NY** [comment]
Hi GuangChuang, @GuangchuangYu
Thank for making those changes. There are still a few minor issues that are unresolved.

* Please test class membership with the `is.*` construction, e.g., `is.character` (`is(object, "S4ClassNameHere")` for S4)
* Please avoid the use of `1:nrow(x)` sequence generation, use the more robust `seq_len` or `seq_along`
* Use an accessor function to access data elements of your class

Regards,
Marcel

**Comment by GuangchuangYu** [comment]
For the first point, I don't get your idea.

Since if the class membership is not match with the class definition, when we constructing the object using `new()`, it will throw error. I think I don't need to test the membership to ensure the validity. 

Point 2 had been fixed.


For point 3,  I only defined `SeqDiff` S4 class in this package and only the `diff` slot is a calculated content that not provided by user and I did provide an accessor function `get_diff` in previous commit. Do I need to provide more accessor to get data that are actually function input?

```r
> fas <- list.files(system.file("examples","GVariation", package="seqcombo"),
+                  pattern="fas", full.names=TRUE)
> x1 <- seqdiff(fas[1], reference=1)
> is(x1, 'SeqDiff')
[1] TRUE
> head(get_diff(x1))
  position difference
1        8          T
2        9          C
3       15          G
4       25          T
5       26          G
6       27          T
```

**Comment by GuangchuangYu** [comment]
For the first point, I don't get your idea.

Since if the class membership is not match with the class definition, when we constructing the object using `new()`, it will throw error. I think I don't need to test the membership to ensure the validity. 

Point 2 had been fixed.


For point 3,  I only defined `SeqDiff` S4 class in this package and only the `diff` slot is a calculated content that not provided by user and I did provide an accessor function `get_diff` in previous commit. Do I need to provide more accessor to get data that are actually function input?

```r
> fas <- list.files(system.file("examples","GVariation", package="seqcombo"),
+                  pattern="fas", full.names=TRUE)
> x1 <- seqdiff(fas[1], reference=1)
> is(x1, 'SeqDiff')
[1] TRUE
> head(get_diff(x1))
  position difference
1        8          T
2        9          C
3       15          G
4       25          T
5       26          G
6       27          T
```

**Comment by GuangchuangYu** [comment]
@LiNk-NY 

BTW: I found that `anyDuplicated` is not equivalence to `which.duplicated`.

**Comment by LiNk-NY** [comment]
Hi GuangChuang, @GuangchuangYu
Good point. The functions are not equivalent.

For the first point, I was talking about mostly base class membership tests. This means that `is.character(layout)` is preferred over `class(layout) == "character"`, for example.

For the accessor, it is preferred that you stay consistent and use all camelCase functions when creating methods for your S4 classes. You can create an accessor such as `diff` to return `x@diff`.

Regards,
Marcel

**Comment by GuangchuangYu** [comment]
I  have changed the `class(layout) == "character"` to `is.character(layout)` and defined a `diff` method to return `x@diff` as suggested.

**Comment by LiNk-NY** [comment]
Hi GuangChuang, @GuangchuangYu
Thanks for making those changes.
It should be good to go soon. I will have a quick look at it and approve.
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Thanks GuangChuang for your submission. 
Minor: 
Please keep in mind that `typeof` can be replaced with `is.language` and `is.character` where appropriate.
Best regards,
Marcel

**Comment by mtmorgan** [comment]
See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build
(check-out from git at about 6 pm Eastern; build completion around 2pm
Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main
landing page are consistent with the addition of your
package). Once the package builds successfully, you package will be
available for download in the 'Devel' version of Bioconductor using
`biocLite("YOUR_PACKAGE_NAME")`. The package 'landing page' will
be created at

https://bioconductor.org/packages/YOUR_PACKAGE_NAME

If you have any questions, please contact the bioc-devel mailing
list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue
will not be monitored further.
