### ISSUE TITLE
M3C package submission

### ISSUE THREAD

**Issue by crj32** [Bioconductor/Contributions#411]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/crj32/M3C

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by crj32** [comment]
Hi, this is my first package. As for the webhook I have followed the instructions and I have the error message: invalid http response 400. My payload URL is: http://issues.bioconductor.org/ and content type is: application/json. I need some help here.

I have realized my vignette images have to be in the vignette source directory - this was the source of the error, I have changed that now and updated the github from terminal. Let me know if this is OK.

Thanks.

**Comment by mtmorgan** [comment]
Looks like the package DESCRIPTION file needs the field Version: to be bumped to 0.99.1 (then 0.99.2, 0.99.3, ... with subsequent commits).

**Comment by crj32** [comment]
Hi, I have applied for the bioc-devel mailing list. The other problem seems to be timeout, what is this referring to? My example code may take quite a while to run because it is computationally intensive, I could put the iterations down if this is the problem? I have found some relevant output below.

**Comment by dvantwisk** [comment]
You are getting the TIMEMOUT tag because your package is taking more than ten minutes to build.  To solve this, consider providing less computationally expensive examples or consider changing your code at places where it might be inefficient.

**Comment by crj32** [comment]
Hi 

I have tried reducing the runtime of the example code in 3 different ways, and there still is a TIMEOUT error. However, on my machine it runs fine and fast on a single core (see below). I have also tested it on my windows virtualmachine and it the example does not take very long compared with your machines. These are the outputs of devtools::check('M3C').......

My machine 1: (no problem, 0 errors)

Examples with CPU or elapsed time > 5s
     user system elapsed
M3C 7.672  0.012   7.684

My machine 2:

* checking examples ... OK
Examples with CPU or elapsed time > 5s
    user system elapsed
M3C 8.96   0.17    9.38

Your machine: (this takes ages……)

* checking examples ...
** running examples for arch 'i386' ... [12m] OK
Examples with CPU or elapsed time > 5s
     user system elapsed
M3C 36.85   0.94  740.24

I just don't understand why we keep reaching timeout on your machines, sorry.

Thanks,

Chris

**Comment by dvantwisk** [comment]
A few things to consider:

- It would be helpful to see your `sessionInfo()`.  Our build machines are running R (3.4.1) and the devel version of BioConductor (3.6.0).  If you are using different versions of either, this might explain the differences in speed.

- Consider building the package on your machine again using `R CMD BUILD M3C` and `R CMD INSTALL M3C`.  It might be the case that you've cached certain things on your end that cause your package to build faster, and a fresh package installation could alleviate this.

- Finally, it would be useful to consider places in your code that are inefficient.  We will do a thorough review once the package builds correctly, but there are places where, at a glance, it appears the code can be vectorized.  Making the code more efficient in certain places now could let your pacakage be built below the ten minute threshold.  For example:
M3C.R:120-126 can be made better with:
```{r}
minv <- matrixStats::rowMins(temp)
maxv <- matrixStats::rowMaxs(temp)
random <- matrix(runif(nrow(temp) * ncol(temp), minv, maxv), ncol=ncol(temp))
```

**Comment by crj32** [comment]
Hi, thanks, firstly I have worked on this code for 2 years and the bit of code that takes 95% of the time (or more) is the ccRun function, the rest we might save a second or two here or there so I haven't optimised that. It also runs in 10 seconds or under on my machines if we disable the monte carlo simulation for the example code as I did before the last build. With

OK have tested in on 3 machines now:

Machine 1: 
Sorry this is the laptop so I haven't saved the output exactly, but this was the (general) output of sessioninfo().
R version 3.4.1 (2017-06-30)
Running under: windows >= 8 x64 (build 9200)

I built the package from source (R CMD build) and installed the current version on a machine that has never had it. I tried running the example code for the M3C function and honestly it took about 4 seconds.

Machine2: 
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

R CMD build M3C
R CMD INSTALL M3C 

(To do a fresh install on the linux machine. The below bit is the example code where we are getting the timeout errors, I have copied and pasted it from above the function in the R script from the directory I created the source from)

> system.time(result <- M3C(mydata, cores=1, iters=100, ref_method = 'reverse-pca', montecarlo = FALSE,printres = FALSE, 
+ maxK = 10, showheatmaps = FALSE, repsreal = 100, repsref = 100,printheatmaps = FALSE, seed = 123, des = desx))
***M3C: Monte Carlo Consensus Clustering***
warning running without monte carlo simulation lowers accuracy
user does give extra annotation for reordering according to clustering results
running without monte carlo simulations...
running consensus cluster algorithm for real data...
finished
   user  system elapsed 
  3.792   0.032   4.211 

Very fast as I would have expected.

Below is the output if I run monte carlo and set the iterations to 10 to save time (instead of 100).

> system.time(result <- M3C(mydata, cores=1, iters=10, ref_method = 'reverse-pca', montecarlo = TRUE,printres = FALSE, 
+ maxK = 10, showheatmaps = FALSE, repsreal = 10, repsref = 10,printheatmaps = FALSE, seed = 123, des = desx))
***M3C: Monte Carlo Consensus Clustering***
user does give extra annotation for reordering according to clustering results
running simulations...
  |======================================================================| 100%
finished generating reference distribution
running consensus cluster algorithm for real data...
finished
we have multiple lowest p values, using pac stat to break the tie
optimal decision: 4
   user  system elapsed 
  1.832   0.040  18.889 

Only 18 seconds. The one before last build including the exact same parameters, but your machines took like 8 minutes or something.

Now the windows virtual machine.

Machine3: 
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

install.packages('M3C_0.99.4.tar.gz', repos = NULL, type="source")

system.time(result <- M3C(mydata, cores=1, iters=100, ref_method = 'reverse-pca', 
                          montecarlo = FALSE,printres = FALSE, 
                          maxK = 10, showheatmaps = FALSE, repsreal = 100, repsref = 100,
                          printheatmaps = FALSE, seed = 123, des = desx))

> system.time(result <- M3C(mydata, cores=1, iters=100, ref_method = 'reverse-pca', 
+                           montecarlo = FALSE,printres = FALSE, 
+                           maxK = 10, showheatmaps = FALSE, repsreal = 100, repsref = 100,
+                           printheatmaps = FALSE, seed = 123, des = desx))
***M3C: Monte Carlo Consensus Clustering***
warning running without monte carlo simulation lowers accuracy
user does give extra annotation for reordering according to clustering results
running without monte carlo simulations...
running consensus cluster algorithm for real data...
finished
   user  system elapsed 
   8.92    0.09   10.44 

Any ideas?

Best,

Chris

**Comment by mtmorgan** [comment]
The examples take a long time on my machine, too. Here's what I've got

```
M3C$ git log --oneline -n 1
3b901bd lets try again, slightly different example
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

and what I'm installing

```
$ R --vanilla CMD build --no-build-vignettes M3C
* checking for file 'M3C/DESCRIPTION' ... OK
* preparing 'M3C':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* looking to see if a 'data/datalist' file should be added
* building 'M3C_0.99.4.tar.gz'

$ R --vanilla CMD INSTALL M3C_0.99.4.tar.gz 
* installing to library '/home/mtmorgan/R/x86_64-pc-linux-gnu-library/3.4-Bioc-3.6'
* installing *source* package 'M3C' ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (M3C)
```

This is close to what the build machine is doing, on my machine

```
$ time R --vanilla -e "library(M3C); example(M3C)"
M3C> res <- M3C(mydata, cores=1, iters=100, ref_method = 'reverse-pca', montecarlo = TRUE,printres = TRUE, 
M3C+ maxK = 10, showheatmaps = FALSE, repsreal = 100, repsref = 100,printheatmaps = TRUE, seed = 123, des = desx)
***M3C: Monte Carlo Consensus Clustering***
user does give extra annotation for reordering according to clustering results
running simulations...
running consensus cluster algorithm for reference data...
finished.
running consensus cluster algorithm for reference data...
finished.
running consensus cluster algorithm for reference data...
finished.
running consensus cluster algorithm for reference data...
finished.
^C
Execution halted

real	1m4.551s
user	1m4.232s
sys	0m0.112s
```

I have the current version of R, which is 3.4.1, and the 'devel' version of Bioconductor.

```
$ R --vanilla -e "sessionInfo()"
> sessionInfo()
R version 3.4.1 Patched (2017-07-04 r72894)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /home/mtmorgan/bin/R-3-4-branch/lib/libRblas.so
LAPACK: /home/mtmorgan/bin/R-3-4-branch/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.27.2

loaded via a namespace (and not attached):
[1] compiler_3.4.1
> 
> 
```

Addressing the low-hanging fruit of missing imports etc makes the build report easier to use and eliminates a number of possible issues.

**Comment by crj32** [comment]
OK I think we have worked it out, I was edited the R script for M3C manually and so the M3C.Rd file has remained the same and so the example has not been changing!

Think we should be OK now. I am going to drop the iterations down to make it run fast.

**Comment by crj32** [comment]
I think we got past the timeout, I need to be subscribed to the mailing list, I did this a week ago and nothing has happened so I guess we will have to wait. Thanks.

**Comment by mtmorgan** [comment]
Mailing list subscription sends a confirmatory email. Did you receive / confirm subscription? It is sometimes classified as 'spam' on the client side.

**Comment by crj32** [comment]
Yeah it was in spam, I'll sort it out.

**Comment by crj32** [comment]
huzzah!

**Comment by crj32** [comment]
Hi

The only warning is related to not evaluating code in the vignette, we have checked the code works in the vignette, but this tool is designed to run on multi core system or people without short time limits. Currently my college has an idea to improve speed, but we have not managed to implement it yet, it may or may not happen.

Could we please continue regardless? The example code runs with 10 iterations fine.

Thanks,
Chris

**Comment by dvantwisk** [comment]
Hello,

Unfortunately, we can't make an exception for your package, it will have to build without warnings.

If you can find any inefficient code that could be replaced with better implementations, this will help.

Other than that, you may need to consider refactoring the examples in your vignette so that they run faster, but still provide a comprehensive overview of what the package can do.  For example, reducing the number of iterations of `iters`, `repsreal`, and `repsref` would appear to improve the run-time; although, you would need to assure that a change like this would still produce an acceptable example.

**Comment by crj32** [comment]
Hi

We do not think further big improvements in speed are likely.

However, the best way to speed this up is to actually reduce the size of the example instead of lowering the iterations, That should be fine. I will have to change the example code and re do the vignette.

Best wishes.

**Comment by crj32** [comment]
Hi - we finally got there, thanks for support.

**Comment by dvantwisk** [comment]
Great!  We'll start our review now.

**Comment by dvantwisk** [comment]
We've reviewed your package!  It looks good, but we have found places were it can be improved:

GENERAL:
- Add unnecessary files such as M3C.Rproj to .gitignore
- Multiple lines have more than 80 characters. When this happens, consider using
	multiple lines to avoid long lines of code that are less than 80 characters.
- place `data` in `inst` directory


DESCRIPTION:
- Consider adding more biocViews, if applicable.
- Consider using `BiocParallel` instead of `parallel`, `doParallel`, and `foreach`.


NAMESPACE
- Looks good!


R/M3C.R
- L3: Add description of functionality of `M3C()` to roxygen2 header.
- L3: In the roxygen2 header, its is best to use `@import()` or `@importFrom()`
	to explicitly declare what symbols from which packages are being used.
	After doing this, remove unnecessary package calls. For example, once
	`@importFrom(doSNOW, registerDoSNOW)` is included in the header,
	its usage later on in the file can simply be called with
	`registerDoSNOW(cl)`.
- L28: Explicitly state which options are available to the user for the
	function and use`match.arg()` to obtain user's input. For example, for the
	parameter `clusteralg='pam'` in the M3C function can be changed to
	`clusteralg = c('pam', 'hc', 'kmeans')`. The user's selection can be
	obtained using `clusteralg <- match.arg(clusteralg)`. (Add More?)
- L88: package `parallel` is not present in the NAMESPACE. Use the roxygen2
	header `@import()` or `@importFrom()` to indicate all outside package and
	symbol usage.  Also include packages in DESCRIPTION file.
- L88: Consider using the package `BiocParallel` instead of `parallel`.
- L105: Use `seq_len()` instead of `seq(1, ...)`.
- L105: replace for-loop with:
```{r}
rnorm_res <- rnorm(nrow(pca1$x), mean=0, sd=pca1$x)
simulated_data <- matrix(rnorm_res, nrow=ncol(mydata), ncol=ncol(mydata))
```
- L156-162: Avoid expensive copy and append pattern and improve p-value
	derivation with:
```{r}
distribution <- as.numeric(ls[,seq_len(real$PAC_REAL)])
pvals <- colSums(distribution < real$PAC_REAL) / (iters + 1)
```
- L169-177: Improve expensive copy and append pattern:
```{r}
pvals2 <- vapply(seq_len(nrow(real)), function(x) {
		mean <- real$PAC_REF[i]
		var <- variance[[i]]
		realpac <- real$PAC_REAL[i]
		params2 <- estBetaParams(mu=mean, var=var)
		pbeta(realpac, params2[[1]], params2[[2]])
	}, numeric(1))
```
- L424: Use `message()` instead of `print()` to communicate with user. (multiple incidents)
- L722-733: Replace for-loop with:
```{r}
value1 <- cdf_res3[seq(2, nrow(cdf_res3), 2), 2]
value2 <- cdf_res3[seq(1, nrow(cdf_res3), 2), 2]
PAC <- value1 - value2
PAC_res <- matrix(PAC, seq(2, nrow(value1)))
```

R/clusterism.R
- L43-48: Replace for-loop with:
```{r}
x2 <- matrix[,1]
y2 <- matrix[,2]
answer <- sqrt(((x2-x1)^2) + ((y2-y1)^2))
matrix <- cbind(matrix, answer)
```
- L59-68: Vectorize code similarly to what we suggested for lines L43-48.
- L98-101: Code can be vectorized similarly to suggestion for lines L43-48.

R/desx.R
- Needs more description about the contents of the file, i.e. structure of the data object.

R/imports.R
- Better to include `roxygen2` import headers in source files in which they are used.

R/mydata.R
- Needs more description about the contents of the file, i.e. structure of the data object.


tests
- Consider adding tests using the `testthat` package.


vignettes
- Looks great!


Please comment back to us once you've addressed these issues so that we can continue our review!

**Comment by dvantwisk** [comment]
Hi, can you perform a version bump?

**Comment by crj32** [comment]
Yes, I have been making the changes you suggest, I can update possibly tommorow or if not the day after. Hope that's OK.

Thanks.

**Comment by dvantwisk** [comment]
That's fine.  I just wanted to be sure that your package was going to be built properly since our build system indicated that a version bump was required.

**Comment by crj32** [comment]
Sorry hit close by accident.

**Comment by crj32** [comment]
OK, thanks for your help. I have made most of the changes suggested and it runs a little faster now. I also made a few updates to the ccRun function and removed a lot of the extra code that was confusing things. Have replaced for loops with vectorization and also used vapply. I tried putting the R data files in a new directory called 'inst' and I couldn't load them, not sure what to do about that... Chris.

**Comment by dvantwisk** [comment]
Everything looks good!  My last recommendation is to add the file M3C.Rproj to your `.gitignore`.

**Comment by crj32** [comment]
Hi Daniel

OK, so, I added the file to my .gitignore file in the M3C directory.

You have been most helpful.

Best,

Chris

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to
Bioconductor's git repository.

To use this repository, we need an 'ssh' key to associate with your github
user name. Please

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build
(check-out from git at about 6 pm Eastern; build completion around 2pm
Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main
landing page are consistent with the addition of your
package). Once the package builds successfully, you package will be
available for download in the 'Devel' version of Bioconductor using
`biocLite("YOUR_PACKAGE_NAME")`. The package 'landing page' will
be created at

https://bioconductor.org/packages/YOUR_PACKAGE_NAME

If you have any questions, please contact the bioc-devel mailing
list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue
will not be monitored further.
