### ISSUE TITLE
beachmat

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#413]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LTLA/beachmat

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by LTLA** [comment]
Hmm... as I expected, I'm missing a few Windows-specific flags in the linking step to make the `libbeachmat.dll` shared library in `Makevars.win`. Any thoughts on how to get them, other than manually writing them into `Makevars.win`? And looking at the build line for `beachmat.dll` reveals a mystery `tmp.def` file, is this important for building `libbeachmat.dll`?

```sh
C:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o beachmat.dll tmp.def HDF5_utils.o any_matrix.o character_matrix.o character_output.o functions.o integer_matrix.o logical_matrix.o numeric_matrix.o repacker.o utils.o -LC:/Users/pkgbuild/packagebuilder/workers/jobs/413/R-libs/Rhdf5lib/lib/i386 -lhdf5_cpp -lhdf5 -lz -lws2_32 -ldl -lm -lpsapi -LC:/local323/lib/i386 -LC:/local323/lib -LC:/Users/BIOCBU~1/BBS-3~1.6-B/R/bin/i386 -lR
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -shared  -s -static-libgcc -o libbeachmat.dll any_matrix.o character_matrix.o character_output.o integer_matrix.o logical_matrix.o numeric_matrix.o utils.o HDF5_utils.o -LC:/Users/pkgbuild/packagebuilder/workers/jobs/413/R-libs/Rhdf5lib/lib/i386 -lhdf5_cpp -lhdf5 -lz -lws2_32 -ldl -lm -lpsapi -LC:/local323/lib/x64 -LC:/local323/lib -LC:/Users/BIOCBU~1/BBS-3~1.6-B/R/bin/x64 -lR 
```

**Comment by grimbough** [comment]
Do you know which header files you need from `C:/local323/lib`?  Could you just ship them with the package? I ended up including including a version of `libdl` with **Rhdf5lib** as it isn't included in the Rtools bundle.

**Comment by LTLA** [comment]
The funny thing is that `beachmat.dll` builds fine; it's `libbeachmat.dll` that fails. So everything that is needed is there, I'm just missing something in the linker line. In the above example, the failure is probably because the -L for `libbeachmat.dll` is for x64 but `beachmat.dll` uses i386.

**Comment by grimbough** [comment]
You can use the environment variable `$R_ARCH` in `Makevars.win` if that's any help.  I've used that to pick the approparite versions of things to link against in the past.

I'm giving it a try on my Windows machine, but so far all I've realised is that **Rhdf5lib** fails to give the correct location of things if there's a space in its path, so I'll patch that and get back to you.

**Comment by LTLA** [comment]
Thanks Mike, that would be a great help. I think I'm just missing some `R CMD config` flags that only show up on Windows; _Writing R extensions_ provides little guidance here.

**Comment by grimbough** [comment]
I've updated **Rhdf5lib** to cope with spaces in the path, but I don't think this would have been an issue for you on the single package builder.

I've also sent a pull request with a change to `Makevars.win` that gets it building on my machine.  It then falls over on the first code example I tried for `rechunkByMargins()`, but at least it builds.

**Comment by LTLA** [comment]
Thanks Mike. I thought it was something like that; on Linux, `--ldflags` just gives an error.

**Comment by LTLA** [comment]
Hm - the Windows-specific error with `rechunkByMargins` is very interesting. At least it's not a segmentation fault, which is what I was most worried about.

**Comment by grimbough** [comment]
Might there be some conflict caused by **rhdf5** and **Rhdf5lib** using different base versions of HDF5 (1.8.7 vs 1.8.18)?

I've been trying to re-engineer **rhdf5** to link against  **Rhdf5lib**, but it's not going too smoothly at the moment.

**Comment by LTLA** [comment]
Okay, based on the diagnostics I'm printing, it seems to be option 1. The file names are definitely different, so it's not _HDF5Array_'s fault. Thus, _rhdf5_ is opening the files in read-only mode on Windows. 

It might be that `h5createFile` is not properly executing `H5Fclose`, which may be leaving the newly created HDF5 file in an inappropriate state for further opening. This raises some immediate questions:

- Is `H5Fclose` getting triggered when `h5createFile` is called (by `getHDF5DumpFile`)?
- If triggered, is the file close operation actually succeeding, i.e., error code of zero?

**Comment by LTLA** [comment]
It seems that `h5createFile` does return `TRUE` on the Windows build machines, which suggests that it is indeed executing `H5Fclose` internally. In light of this, the only other explanation is that `H5Fclose` is not, for some reason, doing its job on Windows - or at least, not in a manner that is compatible with the new HDF5 C++ API. Hard to tell, given that there's no indication of how the Windows DLL was built.

In any case, I'll disable all examples and tests for `rechunkByMargins` on Windows to get _beachmat_ to build. However, this issue also implies that any attempt to write to a HDF5 file from C++ will fail, i.e., _beachmat_'s output capabilities are broken on Windows. I guess that's just too bad.

**Comment by LTLA** [comment]
Ha ha... that "fixed" the problem. But perhaps we can try to narrow down what the cause was. @grimbough, could you try putting this code into _usingRhdf5lib_ and see if it runs properly? Make a `test.cpp` file and put:

```cpp
#include "R.h"
#include "Rinternals.h"
#include "c++/H5Cpp.h"

extern "C" {

SEXP test_me(SEXP input) {
    std::string infile(CHAR(STRING_ELT(input, 0)));
    H5::H5File stuff(H5std_string(infile), H5F_ACC_RDWR);
    return R_NilValue;
}   

}
```

... re-install the package, and then open an R session on a Windows machine and run:

```r
library(rhdf5)
library(usingRhdf5lib)

fname <- "yay.h5"
stopifnot(h5createFile(fname))
.Call("test_me", fname, PACKAGE="usingRhdf5lib")
```

It should just give a `NULL`, but if the bug is present, it will crash and complain that it can't open the file.

**Comment by grimbough** [comment]
I get the `NULL` output from this.  Happy to test anything else.  I can also give you the steps I took to compile the windows dlls if that's useful.  I always intended to distribute that with **Rhdf5lib**, I guess I just haven't done so yet.

**Comment by LTLA** [comment]
Thanks Mike. I've ported the whole `repacker.cpp` function into _usingRhdf5lib_, available at:

https://www.dropbox.com/sh/rfasf3mxjs65ac9/AADNbMGqo4AGPrj1l26D6fU3a?dl=0

Can you try installing it on Windows and running the following code block:

```r
library(HDF5Array); library(usingRhdf5lib)
A <- as(matrix(runif(5000), nrow=100, ncol=50), "HDF5Array")
byrow <- rechunkByMargins(A, byrow=TRUE)
bycol <- rechunkByMargins(A, byrow=FALSE)
```

If this fails, then the problem is isolated to `repacker.cpp` (possibly due to some interaction with _Rcpp_); otherwise, it's something funny with _beachmat_.

**Comment by grimbough** [comment]
This now throws the same error we were seeing before:

`>  byrow <- rechunkByMargins(A, byrow=TRUE)`

> HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
>   #000: ../../src/H5F.c line 604 in H5Fopen(): unable to open file
>     major: File accessibilty
>     minor: Unable to open file
>   #001: ../../src/H5Fint.c line 1028 in H5F_open(): file is already open for read-only
>     major: File accessibilty
>     minor: Unable to open file
> Error in rechunkByMargins(A, byrow = TRUE) : 
>   c++ exception (unknown reason)

**Comment by LTLA** [comment]
Oh good. In that case, I've put up `usingRhdf5lib_0.0.3-2.tar.gz` on Dropbox, where I've completely commented out the repacker class - so only _Rcpp_ and templating are now present in the C++ code. Running the R code block should "work" in the sense that it shouldn't throw a C++ error. (It'll throw an R error - namely, `"HDF5. Dataset. Object not found."` - because the C++ code returns `NULL`, but that's understandable.)

**Comment by grimbough** [comment]
This still throws the same error as before, despite the commenting out.  Interestingly, if I change the two lines in the rechunk template to open files in the same mode e.g.

```c++
H5::H5File ihfile(H5std_string(Rcpp::as<std::string>(ifile[0])), H5F_ACC_RDONLY);
H5::H5File ohfile(H5std_string(Rcpp::as<std::string>(ofile[0])), H5F_ACC_RDONLY);
```
or

```c++
H5::H5File ihfile(H5std_string(Rcpp::as<std::string>(ifile[0])), H5F_ACC_RDWR);
H5::H5File ohfile(H5std_string(Rcpp::as<std::string>(ofile[0])), H5F_ACC_RDWR);
```

it works as you expect, with the `"HDF5. Dataset. Object not found."` message.

**Comment by LTLA** [comment]
Super. Weird. What's going on here? They should be two separate files - I don't understand why the `ihfile` setting would affect the ability of `ohfile` to be opened. 

Well, okay, one more attempt. I've uploaded `usingRhdf5lib_0.0.3-3.tar.gz` with three changes:

- Printing out file names to ensure that the files are indeed different.
- Avoided calling `H5std_string`, just in case that's messing things up.
- Set `ihfile` to open in `RDWR` and `ohfile` to open in `RDONLY`. If the API is somehow opening the same file, this should still "work" as we are allowed to open a RDONLY handle to a file that is already in RDWR mode. If this doesn't work, then it's something strange and mysterious under the hood.

**Comment by grimbough** [comment]
The files are definitely different.  Here's the output of version 3 (slightly modified to print separate lines):

```
Input: C:/Users/Mike Smith/AppData/Local/Temp/RtmpIDGgzF/HDF5Array_dump/auto00001.h5
Output: C:/Users/Mike Smith/AppData/Local/Temp/RtmpIDGgzF/HDF5Array_dump/auto00002.h5
 Error in H5Dopen(g, name) : HDF5. Dataset. Object not found. 
```

However, if I just switch the order the two file handles are declared in the code i.e.

```c++
 H5::H5File ohfile(ofname.c_str(), H5F_ACC_RDONLY);
 H5::H5File ihfile(ifname.c_str(), H5F_ACC_RDWR);
```
it fails as before, despite everything seeming the same. 

```
Input: C:/Users/Mike Smith/AppData/Local/Temp/RtmpE9Ui5f/HDF5Array_dump/auto00001.h5
Output: C:/Users/Mike Smith/AppData/Local/Temp/RtmpE9Ui5f/HDF5Array_dump/auto00002.h5
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: ../../src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../src/H5Fint.c line 1028 in H5F_open(): file is already open for read-only
    major: File accessibilty
    minor: Unable to open file
Error in rechunkByMargins(A, byrow = TRUE) : 
  c++ exception (unknown reason)
```
I'll see if I can find a Windows version of libhdf5 compiled by someone else (or I'll use the recommended toolchain myself) to try and verify if this is something weird in the version distributed with **Rhdf5lib**.

**Comment by LTLA** [comment]
Thanks Mike. For a while, I was wondering whether Windows was messing up the file names (e.g., truncating them to the same name), but I don't think this is possible. I've uploaded `usingRhdf5lib-0.0.3-4.tar.gz` containing a trimmed-back example that should trigger the failure with:

```r
test("yay.h5", "whee.h5")
```

On Dropbox, I've also put in a `compiled/` subdirectory that contains the same C++ code that can be built outside of R, i.e., using the system HDF5 libraries. If this chucks an error, then it's something wrong with the core libraries themselves, rather than something to do with _Rhdf5lib_.

**Comment by grimbough** [comment]
So I think this is a result of some unreported problem in the way I was compiling HDF5 on Windows.  I've managed to build a version using CMake rather than configure, but still using the version of gcc in Rtools.  I can then link **beachmat** to these libraries and `rechunkByMargins` runs without throwing an error.  Is there a way to test that it's actually doing what you'd expect?

There's a few kinks to sort out still, but hopefully I can get a new version in **Rhdf5lib** fairly quickly.

**Comment by LTLA** [comment]
A-maz-ing. The tests in `tests/testthat/test-rechunk.R` will tell you if it's working properly.

**Comment by grimbough** [comment]
**Rhdf5lib** version 0.99.12 should be compatible with **beachmat** now.  I can run the everything in `tests/testthat/test-rechunk.R` without issue when linking against it on 64bit Windows.  I haven't tested 32bit Windows or any other platform yet.

**Comment by LTLA** [comment]
Great. I should mention that there is a battery of actual tests in `inst` that verify that _beachmat_'s core API functionality is working. These are not put into the `tests` subdirectory as they require the installation of a "test" package to check that linking works as it should. You can test it by running:

```sh
R CMD check testpkg/
```

**Comment by hpages** [comment]
Amazing debugging job guys! Thanks for sorting out the nasty Windows issue. I'm taking a look at beachmat right now. We need to get the package into Bioconductor and on the daily build reports ASAP.

**Comment by LTLA** [comment]
Yep, as soon as I see the latest version of _Rhdf5lib_, I'll trigger a version bump.

**Comment by hpages** [comment]
Sounds good. I guess you could also try to re-enable the `rechunkByMargins`'s example.
Almost done with the review. Everything looks good. Still need to run `R CMD check testpkg/` and have a quick look at the vignette.

**Comment by LTLA** [comment]
Oh, that's a good point actually. @grimbough, the tests in `test-rechunk.R` were hidden in an `if` block that prevents their execution on Windows, so if you just `source`d the test file, it will finish without problems because nothing gets run! Perhaps you've already realized this, though.

**Comment by grimbough** [comment]
I took the Windows clause out, so it was running the tests correctly.  I'm having some problems building the `testpkg` inside.  Something isn't found when I try to load the dll, but for the moment I'm not sure if it's related to `Rhdf5lib.dll`, `beachmat.dll` or something else entirely and we're missing a linker flag somewhere.  I'll take a look in more depth tomorrow morning.

**Comment by hpages** [comment]
Everything looks good. I'm marking the package as accepted.

Some minor comments, mostly cosmetic. Note that I'm not a C++ guy so I'm learning a lot by looking at your code. Also that means that my comments below might not make much sense so feel free to
ignore ;-)

I noticed that in the 'Defining the common input interface' section in `LIN_methods.h` (lines 14-36), the following definitions are duplicated:
```
   lin_output<T>::get_col
   lin_output<T>::get_row
```
Is this expected?

   lin_output<T>::fill_col
   lin_output<T>::fill_row

The 'Defining the common output interface' section in `LIN_outfun.h` (lines 14-60) contains similar definitions and duplicated definitions for `fill_col` and `fill_row`.

Overall I wonder if some of the `get_col(size_t, Rcpp::StringVector::iterator)` or `get_row(size_t r, Rcpp::IntegerVector::iterator out)` methods couldn't be avoided. They seem to all do the same thing i.e. they just call `get_col(c, out, 0, get_nrow())` for the former and `get_row(r, out, 0, get_ncol())` for the latter.

Argument naming mismatch between vignette and real code: `X` in the vignette but `out` in the code for several methods e.g. `get_col`, `get_row`, and some of the `fill_*` methods. Also `rstart/rend` or `cstart/cend` in the vignette but `start/end` in the code.

I'm worried that the use of `start`/`end` to specify row or column ranges might be a little bit confusing given that start/end is already widely used in Bioconductor at the R and C level and with a different semantic i.e. 1-based and with bounds included in the range (`start` <= i <= `end`). If I understand correctly, `start`/`end` in beachmat are zero-based and describe range `start` <= i < `end`. What about using something like `from`/`to` or `first`/`last` or `r1`/`r2` and `c1`/`c2` instead? Another option could be to specify the ranges by the offset and nb of rows or cols e.g. something like `offset`/`nrow` or `offset`/`n`. Could also use `r` or `c` instead of `offset` (i.e. `r`/`nrow` and `c`/`ncol`) since you already use this for the `get` methods. Or `roffset`/`nrow`, `coffset`/`ncol`...

The `get*`/`fill*` pairing is a little bit unconventional. What about something like `get*`/`set*` or `read*`/`write*` or `extract*`/`replace*` etc instead?

H.

**Comment by LTLA** [comment]
@grimbough Yes, it's entirely possible that `pkgconfig` isn't written properly for Windows, I just ripped it from _Rhtslib_. Though everything in there is standard C++, so I didn't think much was needed...

@hpages Good points; I'll get onto them tomorrow morning.

**Comment by LTLA** [comment]
Responses to comments by @hpages:

1. Yes, the duplication is intended. This is function overloading in C++ (don't think it exists in C), where the compiler can figure out which function to use based on the number and type of arguments. Here, I've used it to allow for different iterator types (e.g., for implicit conversion from double-precision data in the matrix to integer data in the storage vector) and to allow the start/end of the extraction range to be specified or not.
2. Yes, I too wish that I didn't have to duplicate a lot of the functions. The problem is that the type of iterator needs to be known at compile time. Normally I would handle this by templating the iterator argument so that I only need to write the function once (and the compiler automatically copies it for every iterator type), but I can't have virtual templated methods due to various intricacies of how C++ classes work. So, just duplicating the definition was the easiest option.
3. I'll fix the mismatch. 
4. I can change this to `first` and `last`, which is probably the more appropriate name.
5. I'll change it to `set_*`.

**Comment by LTLA** [comment]
@hpages Code has been updated as suggested in 0.99.8.

@grimbough I guess we should move to the Slack channel to deal with our Windows problem.
