### ISSUE TITLE
TMixClust

### ISSUE THREAD

**Issue by Monica-Golumbeanu** [Bioconductor/Contributions#415]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cbg-ethz/TMixClust

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by Monica-Golumbeanu** [comment]
The error was because I was not a member of the bioc-devel list. I am now subscribed to the list.

**Comment by mtmorgan** [comment]
Make sure that your package interoperates with Bioconductor. Do this by accepting as input Biobase ExpressionSet and / or SummarizedExperiment::SummarizedExperiment()` objects.

Use BiocParallel for parallel evaluation, so that Bioconductor users do not have to master different parallel computing conventions for different packages.

**Comment by Monica-Golumbeanu** [comment]
I added a function, get_time_series_df_bio, which parses a Biobase ExpresionSet into a data frame necessary for the main function of the package. I modified the analyse_stability function such that it uses the BiocParallel environment.

**Comment by nturaga** [comment]
# Review TMixClust

## Build

* R CMD build: ok

* R CMD INSTALL: ok

## DESCRIPTION

* ok.

## NAMESPACE
* ok

* Does BiocStyle need to be imported, if it is just for the vignette it needs to be in "Suggests".

## man

* ok

## vignette

* Ok

## R

* Replace `1:nrow(ts_df)` with `seq_len(nrow(ts_df))` ??

```
    for (j in 1:nrow(ts_df)) {
        plot(time_points, ts_df[j,], ylim=yl, axes = FALSE, xlab="", ylab="",
            main="", col=data_color, type="l", pch=20,lwd=2)
        par(new=TRUE)
    }
```

    Same problem in all other instances of `(1: value)`

    if you need to do `2:nrow(data_table)` use `seq_len(nrow(data_table))[-1]`, do this in all the other places as well.



* internal_spline_functions.R line:10

    ```
         nb_numeric = apply(data_table, MARGIN = 1, function(x) sum(1-is.na(c(x))))
    ```

    can be replaced with 

    ```
    nb_numeric <- rowSums(1-is.na(data_table))
    ```
    vectorize wherever you can. It'll be way more efficient.


* You can make your "create_z" function much faster, by vectorizing
  (internal_spline_function.R )
  
  ```
  create_z = function(data_table) {
    nb_numeric <- rowSums(1-is.na(data_table))
    nb_elements = sum(nb_numeric)

    z = matrix(c(z, 0L), nrow(data_table), nrow(data_table))
    previous = head(c(0, cumsum(nb_numeric)), -1)
    for (i in seq_len(nrow(data_table))) {
        z[ previous[i] + seq_len(nb_numeric[i]), i] <- 1
		}
    return(z)
	}
  ```


	
* Remove `print(w)` and replace with `message` instead (l:85
  internal_spline_function.R"). Make this correction in every place
  `print` was used.

* In `init_kmeans`, try doing preallocate and fill, instead just
  making an object <- NULL. Take a look at the modified function
  below, and see if there are similar changes to be made in other
  places as well.
  
```
 init_kmeans = function(data_table, K, time_points) {
    t = ncol(data_table)
    gss_obj_list = vector("list", K)
    # replace missing values by interpolaiton; only done for kmeans clustering.
    data_p = t(apply(data_table, MARGIN = 1, function(x) zoo::na.spline(c(x))))
    kmeans_clust = kmeans(data_p,K)$cluster

    # for each cluster, estimate the mean curve using gss ssanova function
    for (k in 1:K) {
        cluster_genes = which(kmeans_clust == k)
        if (length(cluster_genes)>0) {
            cluster_data = data_table[cluster_genes,]
            gss_obj_list[[k]] = fit_ssanova(cluster_data, time_points)
        }
    }
    return(list(kmeans_clust = kmeans_clust, gss_obj_list = gss_obj_list))
}
```

* There seems to be a lot of code which is running in the loops, and
  doesn't need to be inside the loop. There is a lot of scope for the
  code to be optimized to run faster. 
  
  Vectorize whenever you can, and please try to follow
  https://www.bioconductor.org/developers/how-to/efficient-code/.
  
  This is an important critique of the code you have written.

* Generally, no need to use `which(<logical>)`, just use `<logical>`.

**Comment by Monica-Golumbeanu** [comment]
Thanks for the review. I have addressed all the issued you raised and updated the code accordingly. Thank you for your code vectorizing suggestions, I have removed a couple of useless for loops. I replaced the which(<logical>) commands where they were not necessary.

**Comment by Monica-Golumbeanu** [comment]
Hi @nturaga,

Here is a more detailed description of the changes I’ve done according to your previous package review:

_**- Replace 1:nrow(ts_df) with seq_len(nrow(ts_df)) ??**_
I replaced this everywhere in the code.

**_- internal_spline_functions.R line:10_**
I used rowSums as you indicated.

**_- You can make your "create_z" function much faster, by vectorizing_**
I modified the “create_z” function as you suggested.

**_- Remove print(w) and replace with message instead_** 
Done, files external_TMixClust.r, internal_em_functions.r and internal_spline_functions.r were changed accordingly.

**_- In init_kmeans, try doing preallocate and fill, instead just making an object <- NULL._** 
I followed your advice and made this modification in relevant functions except in function “do_EM” (internal_em_functions.R), where vectors ll and em_pi_k have a number of elements equal to the number of iterations of the EM algorithm, which is not known in advance.

**_- There seems to be a lot of code which is running in the loops, and doesn't need to be inside the loop._** 
In addition to previous optimizations, I replaced the for loop used to calculate t_wei with a faster matrix multiplication (in “internal_em_functions.R”, line 196). The retrieval of missing values from functions “calc_prob” and “calc_ll” was not necessary inside the for loop, I put it outside.
I also added a unit test that checks whether the clustering on the toy data returns the same number of genes in each cluster as the ground truth solution.

**_- Generally, no need to use which(<logical>), just use <logical>._**
I removed the which in most of the functions, except in a few places where the actual indices were needed.

**_- Remove all commented out lines of code._**
Done.

Please let me know if there are further improvements I could do to the code. Thanks again for your help.

**Comment by nturaga** [comment]
I'll have your second review by mid next week.

**Comment by mtmorgan** [comment]
Your ssh public keys have been added from GitHub; you can access your
Bioconductor repository using the corresponding private key(s); the
command

    ssh git@git.bioconductor.org

should include a line like

    R W    packages/YOUR_PACKAGE_NAME

indicating read / write access is available.

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build
(check-out from git at about 6 pm Eastern; build completion around 2pm
Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main
landing page are consistent with the addition of your
package). Once the package builds successfully, you package will be
available for download in the 'Devel' version of Bioconductor using
`biocLite("YOUR_PACKAGE_NAME")`. The package 'landing page' will
be created at

https://bioconductor.org/packages/YOUR_PACKAGE_NAME

If you have any questions, please contact the bioc-devel mailing
list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue
will not be monitored further.
