### ISSUE TITLE
RVS

### ISSUE THREAD

**Issue by sherman5** [Bioconductor/Contributions#416]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sherman5/RVS

Confirm the following by editing each check box to '[x]'

- [X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X ] The 'devel' branch for new packages and features.
- [ X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Please make your package interoperable with other Bioconductor packages, e.g., by expecting / accepting VariationAnnotation::VCF() input / output.

**Comment by sherman5** [comment]
The functions RVgene and RVgeneAllshare now accept inputs of the type "SnpMatrix" as well as the LINKAGE format that was previously accepted. Is this sufficient?

**Comment by vobencha** [comment]
I'll take a look at this tomorrow.
Valerie

**Comment by vobencha** [comment]
Hi,

Overall an organized and well documented package. Well done. A few comments below.

1) Please clean up the NOTES in single package builder output:
```
* Checking to see if we understand object initialization...
    * NOTE: Consider clarifying how 2 object(s) are initialized. Maybe
      they are part of a data set loaded with data(), or perhaps part
      of an object referenced in with() or within().
    object (function)
      f (exactSharingProb)
      f (monteCarloSharingProb)

* Checking man pages...
* Checking exported objects have runnable examples...
    * NOTE: Consider adding runnable examples to the following man
      pages which document exported objects:
      RVgene_allshare.Rd
```
2) snpStats
Yes, the support of SnpMatrix is sufficient. snpStats should be moved to Imports or Depends and be (partially or fully) imported in the NAMESPACE. Packages in Suggests are not checked during installation so a user that does not have snpStats installed could not use your package even though they could install it.

    When you use an object from another package you should always import or depend on the originating package. You can fully import or partially import calling out only the classes and methods you're using with importClassesFrom() and importMethodsFrom().

3) kinship2
Same situation here. kinship2 should be moved to Imports or Depends and imported in the NAMESPACE.

4) gRain
This package is in the Imports field in DESCRIPTION and should be partially or fully imported in the NAMESPACE.

5) genotypeToSnpMatrix()
This function is mentioned in a couple of places but there is no indication of where it comes from:
```
~/RVS/R >grep genotypeToSnpMatrix *
RVgeneAllshare.R:#'  genotypeToSnpMatrix function, with missing values coded NA
RVgene.R:#'  genotypeToSnpMatrix function, with missing values coded NA
```
If you mean the function from VariantAnnotation you should state that or use VariantAnnotation::genotypeToSnpMatrix to indicate origin.

Let me know if you have questions.

Valerie

**Comment by vobencha** [comment]
fyi I'm out of the office July 26 - Aug 2.
Valerie

**Comment by sherman5** [comment]
Thank you for the feedback,

>> 1. Please clean up the NOTES in single package builder output:

All NOTES have been resolved, except for 12 lines in the man pages to are not indented to a multiple of 4 spaces. This is due to roxygen copying over the function signature to multiple lines.

>>  2. snpStats 3. kinship2 4. gRain

all of these packages have been included in the NAMESPACE and Imports fields, see [commit](https://github.com/sherman5/RVS/commit/29b11d942ac358ff5639b4af431dbc4fbffa3534)

>> 5. genotypeToSnpMatrix()

we clarified the description and this function is no longer referenced

Tom

**Comment by vobencha** [comment]
Thanks for making the changes. Marking this as approved.
Valerie
