### ISSUE TITLE
AnimalGene2QTL:retrieve QTL,SNP and gene

### ISSUE THREAD

**Issue by liuyufong** [Bioconductor/Contributions#427]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/liuyufong/AnimalGene2QTL
AdditionalPackage: https://github.com/liuyufong/AnimalQTLDB

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by liuyufong** [comment]
The AnimalGene2QTL provides functions to retrieve QTL , SNP and gene data

**Comment by mtmorgan** [comment]
Your package will need to integrate much better with Bioconductor, e.g., using GRanges to describe QTL locations.

**Comment by lshep** [comment]
Is AnimalQTLDB an R package on CRAN? Or is this an additional package that you were submitting to Bioconductor?

**Comment by liuyufong** [comment]
Dear Ishep,
 The AnimalQTLDB is an additional package that i am tring to submitting to Bioconductor.
it is a ExperimentData package that provides  sqlite database to AnimalGene2QTL package

**Comment by lshep** [comment]
The ExperimentalData package should have been submitted first as these packages should be submitted under the same issue: 
https://github.com/Bioconductor/Contributions#submitting-related-packages

**Comment by liuyufong** [comment]
@lshep  Thank you for reminding me. I will submit it

**Comment by liuyufong** [comment]
@lshep  I submit the  additional packages AnimalQTLDB:
AdditionalPackage: https://github.com/liuyufong/AnimalQTLDB

**Comment by lshep** [comment]
Thank you.  Please make sure your [webhooks](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) are set up on both of the packages.  
Please debug AnimalQTLDB  completely first.

**Comment by liuyufong** [comment]
[AnimalQTLDB_0.99.6.tar.gz](https://github.com/Bioconductor/Contributions/files/1167189/AnimalQTLDB_0.99.6.tar.gz)
I run build("AnimalQTLDB",vignettes = FALSE)

**Comment by lshep** [comment]
Thank you for you submission to Bioconductor. Please see the following comments: 

Experimental Data Package :  AnimalQTLDB

- [ ] Please provide some information about where the data is coming from? The man page is very brief and just says connect QTL database.  Please provide information on where the data came from and how it was generated (perhaps a creation data or version if applicable., etc... ). Is this a subset of data that is provided? It seems like it connects to a QTL database that is provided locally and not connecting to a remote resource - this should probably be made clear. 
- [ ] Is this separate package necessary? It seems the data is small enough to include directly with your package and still meet the requirement of <4Mb .  The software package size is 17.12KiB and the data package is 8036.13 KiB.
- [ ] perhaps a use example?  the function doesn't return the connection just returns TRUE?


Software Package AnimalGene2QTL

VIGNETTE: 
In the section getAnimalQTL() function: 
```
geneid <- c("ENSBTAG00000009851", "ENSBTAG00000005101", "ENSBTAG00000036262")
qtl <- getAnimalQTL(qtl_attributes=c('QTL_ID'),gene_filters='ensembl_gene_id' ,gene_values=geneid,data_set=1);
head(qtl);
```
It looks like the column names are not in the correct order? 
```
> names(qtl)
[1] "ensembl_gene_id"           "QTL_ID"                   
[3] "length in the region (bp)"
> qtl[1:5,3]
[1] "ALL" "ALL" "ALL" "ALL" "ALL"
```


R CODE and general questions: 
- [ ] Please use formatR to formate your R code to make it easier to read.
- [ ] Why are there only 5 datasets? Is this a limitation of Biomart? Are these specific ones you have chosen and provided in the Experimental Data package? Does QTL provide more than that, is there some way users could import their own data into your function to use? Does the package really connect to the QLT website or only a subset of data that you have provided? 

listQTLAF.R / listQTL.R
- [ ] what are these hard coded values? Is it possible for them to be autogenerated as hard coded value lists like this are easy to get out of date/stale?

getSNPbyQTL.R / getQTLbySNP.R / getAnimalQTL.R / getAnimalGene.R
- [ ] see [efficient code](http://bioconductor.org/developers/how-to/efficient-code/)
don't use 1:n or 1:length(x) use seq_len(n) or seq_along(x)
applys generally can be faster than for loops - might be worth looking into performance differences

Please address the above issues and submit new version of the package.  Please also comment back here when the updates are complete with a summary of changes or comments. 
Thank you

**Comment by liuyufong** [comment]
@lshep Thank you for the advice,  I updated my package.
  About Experimental Data Package : AnimalQTLDB:

-  I have added the information about QTL data in the man page and rmd file.

- package is meet the requirement of <4Mb, The separate package for facilitate updating QTL database without change the AnimalGene2QTL package.

About Software Package AnimalGene2QTL:

- the function getAnimalQTL() retrieval result include input filters, output attributes (such as gene_filters='ensembl_gene_id',qtl_attributes='QTL_ID'),and a column named "length in the region (bp)". it means the length of QTL data in the interval of the corresponding gene in a row，the column value is "ALL" when  a QTL data is all in  the interval of the corresponding gene, in addition to this column is numerical value.

-Five QTL data of  livestock animals in AnimalQTLDB package, include Cattle, Chicken, Horse, Pig, Sheep, so there are five dataset. I localized the QTL data ,that come from the websit (https://www.animalgenome.org/cgi-bin/QTLdb/index), and convert to SQLite database. Now I only converted five QTL data.
Importing user data is not currently supported.

**Comment by lshep** [comment]
Hello

Some additional comments: 

**AnimalQTLDB**
- [ ] Since this is an initialization of the package and data source, we feel like you should include all of the available sources at https://www.animalgenome.org/cgi-bin/QTLdb/index.  Do all 7 of 7 instead of 5 of 7. 

**AnimalGene2QTL**
**Code** 
- [ ] In many functions you check for RSQLite, bioMart and AnimalQTLDB using a  requireNamespace.  This check is not needed since those packages are imported in the NAMESPACE of your package.  Please remove these checks. 
- [ ] You described the following: 

*the function getAnimalQTL() retrieval result include input filters, output attributes (such as gene_filters='ensembl_gene_id',qtl_attributes='QTL_ID'),and a column named "length in the region (bp)". it means the length of QTL data in the interval of the corresponding gene in a row，the column value is "ALL" when a QTL data is all in the interval of the corresponding gene, in addition to this column is numerical value.*

The column name should be changed as there should not be spaces in the column names; this prohibits tab completion and accessing the column.  The type of data stored in the column should also not be a mixture of character and numeric values - it should be one or the other. 

Thank you.  Please comment here when you have made changes and are ready for another review. 

Cheers 
Lori

**Comment by lshep** [comment]
Hello @liuyufong ,  I was just checking in on any progress or comments.  The next Bioconductor release will be the end of October and it would be great to be able to get it approved by then.

**Comment by lshep** [comment]
If there are no updates and no response with intent to continue to work on this package submission within the next week I will close the issue for inactivity.

**Comment by lshep** [comment]
closing do to inactivity.  You may reopen this issue at anytime.
