### ISSUE TITLE
DrugDiseaseNet

### ISSUE THREAD

**Issue by azampvd** [Bioconductor/Contributions#443]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/azampvd/DrugDiseaseNet

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [ ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
No need to include vignette build products in the vignettes/ directory, just the Rnw and bib files.

**Comment by vobencha** [comment]
Hi,

Package looks good. Just a few suggestions.

1) Convert the vignette over to use BiocStyle. There are examples of how to produce html or pdf output in the BiocStyle vignette.

2) Consistent naming of function arguments
I would suggest using either underscores or camelCase but not mixing the two if possible:
```
edgeData_keggPathwaygraphs(edge_from, edge_to, updateKEGG = FALSE)

updateGlobalGraph(globalGraph, edgesToremove = list(c("hsa:6657", "hsa:79923")))
```
3) updateGlabalGraph.Rd needs an /examples section.

4) More descriptive examples on man pages
For example, on keggGlobalGraph.Rd instead of just creating 'gg', show it:
```
> gg<-keggGlobalGraph()
> gg
A graphNEL graph with directed edges
Number of Nodes = 5593
Number of Edges = 28371 
```
Same with nodeData_keggPathwaygraphs.Rd. Show a little of what the result is.
```
> class(pathways)
[1] "character"
> head(pathways)
                path:hsa04010                 path:hsa04012
     "MAPK signaling pathway"      "ErbB signaling pathway"
                path:hsa04062                 path:hsa04066
"Chemokine signaling pathway"     "HIF-1 signaling pathway"
                path:hsa04150                 path:hsa04151
     "mTOR signaling pathway"  "PI3K-Akt signaling pathway" 
```

Valerie

**Comment by vobencha** [comment]
Checking in. Are you planning to submit an updated version?
Valerie

**Comment by azampvd** [comment]
Thank you very much for your message. I am confused about the issue/suggestion 1:
"Convert the vignette over to use BiocStyle. There are examples of how to produce html or pdf output in the BiocStyle vignette." 
Other issues got resolved.

**Comment by vobencha** [comment]
Please use the BiocStyle package to create your vignette. Instructions for using BiocStyle are here:
http://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html

**Comment by vobencha** [comment]
Are you planning to submit a new version or should I close this issue?

**Comment by azampvd** [comment]
Hi,


I am sorry. I am gonna submit it ASAP.


Thanks,

Azam

________________________________

**Comment by vobencha** [comment]
Closing this issue. If you decide to submit a new version we can re-open this.
