### ISSUE TITLE
cytolib 

### ISSUE THREAD

**Issue by mikejiang** [Bioconductor/Contributions#445]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/RGLab/cytolib

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mikejiang** [comment]
This package contains the original `c++` code from `flowWorkspace`, 
`cytolib` consists of the c++ data structure and its APIs as the infrastructural library for the entire `flow cytometry` tool chains. 
`flowWorkspace` mainly contains the R bindings to the `cytolib` and the `xml` parsing.
The separation will make it easier to maintain both packages, so that the frequent enhancements and new features are added to `flowWorkspace` at R level without the unnecessary lengthy `C++` re-compilation against those core c++ files.. 
On other hands, the new extension efforts can also be made directly to `cytolib` without introducing the unwanted heavy dependencies from `flowWorkspace`

**Comment by mikejiang** [comment]
@LiNk-NY , I see this false positive error report again, hope it won' affect the process of review
```r
ERROR: Maintainer must subscribe to the bioc-devel mailing list.
```

**Comment by LiNk-NY** [comment]
Hi Mike, @mikejiang
If you are registered, then I will follow up with Lori (@lshep) about that error because it seems odd.
Thanks for submitting your package to Bioconductor. It has been accepted. 

Best regards,
Marcel

**Comment by mikejiang** [comment]
@LiNk-NY , is the package still in the queue of bioc devel?Just wondering

**Comment by LiNk-NY** [comment]
Hi Mike,
We are still working on adding the recently accepted packages to the git server.
Please stay tuned to the bioc-devel mailing list. 
Regards,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to
Bioconductor's git repository.

Your ssh public keys have been added from GitHub; you can access your
Bioconductor repository using the corresponding private key(s); the
command

    ssh git@git.bioconductor.org

should include a line like

    R W    packages/YOUR_PACKAGE_NAME

indicating read / write access is available.

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build
(check-out from git at about 6 pm Eastern; build completion around 2pm
Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main
landing page are consistent with the addition of your
package). Once the package builds successfully, you package will be
available for download in the 'Devel' version of Bioconductor using
`biocLite("YOUR_PACKAGE_NAME")`. The package 'landing page' will
be created at

https://bioconductor.org/packages/YOUR_PACKAGE_NAME

If you have any questions, please contact the bioc-devel mailing
list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue
will not be monitored further.
