### ISSUE TITLE
(inactive) ClonEvol

### ISSUE THREAD

**Issue by hdng** [Bioconductor/Contributions#450]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hdng/clonevol

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Some preliminary comments: Your packages should interoperate with [standard Bioconductor representations][1] in the appropriate domain, probably accepting as input SummarizedExperiment or SingleCellExpermient. Update your vignette to reflect installation instructions after accepted to Bioconductor. Remove build products (e.g., html, pdf) from your git repository (e.g., store them on a different branch).

[1]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by hdng** [comment]
Hi @hpages, I've fixed a few issues and bumped the version. What else do I need to do to trigger the next build? Thanks.

**Comment by mtmorgan** [comment]
have you [established a web hook][1] ? If not do so and bump again. If so see the 'Additional Actions' section of that page, final items about debugging web hooks; if there are problems fix them and bump the version.

[1]: https://github.com/Bioconductor/Contributions#adding-a-web-hook

**Comment by hpages** [comment]
Hi Ha X,

Thanks for your submission. Please address the `R CMD check` warnings as well as the issues reported by Martin. Thanks!

Best,
H.

**Comment by hdng** [comment]
Hi @hpages , I am addressing the warnings. Couldn't see Martin's comments, where are they? Thanks.

**Comment by mtmorgan** [comment]
My comments are in the github issue

**Comment by hpages** [comment]
Hi Ha X,
After you're done addressing the `R CMD check` warnings as well as the issues reported by Martin (mtmorgan in the issue on github), please make sure to bump the version of the package in order to trigger a new build.
Thanks,
H.

**Comment by hpages** [comment]
Hi Ha X,
Are you planning to follow up on this submission? If we don't hear back from you in the next couple of weeks, we'll close this issue.
Regards,
H.

**Comment by hdng** [comment]
Hi @hpages,

I am implementing several new features, hopefully to roll them out within a few weeks. I'd like to wait until then to bump the version. I am very sorry for the lack of response.

**Comment by hpages** [comment]
Hi Ha X,

That's fine. Thanks for the update and for improving ClonEvol. However please note that, at this point, it won't be realistic to consider ClonEvol for inclusion in the upcoming Bioconductor release (BioC 3.6, scheduled for Oct 31). We will consider it for inclusion in the next version, BioC 3.7.

Don't hesitate to ask on the bioc-devel mailing list if you have any questions or concerns about this.

Regards,
H.

**Comment by hpages** [comment]
Please use cameCase style for the names of your functions. For example, if `plot.clonal.models` is not an S3 `plot` method for `clonal.models` objects, then name it `plotClonalModels`.

You should not be worried to rename things at this point as the package has not been released as part of Bioconductor yet (so probably has a very small number of users). Once the package is added to Bioconductor, you will of course need to be careful to not make changes that break user code. This will be particularly important for the version of the package that will be in the released version of Bioconductor (i.e. for the RELEASE_X_Y branch of the package). For the version of the package that will be in BioC devel (i.e. the master branch of the package), it will still be possible to do some important changes while at the same time maintain backward compatibility with existing code by using appropriate deprecation/defunct cycles.

Regards,
H.

**Comment by hpages** [comment]
Hi @hdng,

Do you intend to follow up on this submission? If I don't hear from you before end of January, I'll close this issue.

Thanks,
H.

**Comment by hdng** [comment]
Hi @hpages,

I will push some major update within a couple of weeks. The package has gained significant traction, thus making it compatible with bioconductor without affecting existing userbase is not trivial. 

Thanks.

**Comment by hpages** [comment]
Hi @hdng, thanks for the update. H.

**Comment by hpages** [comment]
Hi @hdng ,
Just a reminder that you will need to bump the version number of clonevol if you want to trigger a new build/check by our Single Package Builder. Also please let me know when you want me to take a 2nd look at the package (after you've bumped the version number).
Thanks,
H.

**Comment by hpages** [comment]
Hi @hdng,

Sorry but I have to ask again if you intend to follow up on this submission? If yes, please note that at this point it's going to be too late for ClonEvol to make it into the BioC 3.7 release (schedule for May 1st). If I don't hear from you before end of April, I'll close this issue.

Regards,
H.

**Comment by hdng** [comment]
Hi @hpages,

Sorry this has been lagged. There have been numerous updates of the code that I made but I don't think it is ready to comply with bioconductor coding style.

Let's aim for the next release if you don't mind.

Thanks.

**Comment by hpages** [comment]
Hi @hdng: No problem. Thx for the update. --  H.

**Comment by mtmorgan** [comment]
We'll close this for now; it can be opened when @hdng is ready to work on the submission again.
