### ISSUE TITLE
Rbowtie2

### ISSUE THREAD

**Issue by wzthu** [Bioconductor/Contributions#457]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wzthu/Rbowtie2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by wzthu** [comment]
Deer reviewer,


There are two distinct errors from various  OS/arch:


The first error is in R CMD BiocCheck:
"
Checking for bioc-devel mailing list subscription...     * ERROR: Maintainer must subscribe to the bioc-devel mailing list.       Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
"
I subscribed just now and I think I have solved it.


The second error is in R CMD check, 
which is caused by architecture problem.  


Because bowtie2 can only be compiled by 64bit g++ compiler, 
the compiler from mingw_32 etc. will cause errors.
Therefore, Setting the arguments "--arch x64" and "--no-multiarch"  
may be necessary for this package: 
"R --arch x64 CMD check --no-multiarch"
And, I had declared “Arch: x64” in DESCRIPTION before I submmited. 


Thanks!


------------------
Zheng Wei



 




------------------
魏征
 
 

 




------------------ Original ------------------

**Comment by LiNk-NY** [comment]
Hi Zheng, @wzthu
Thank you for your submission.

I apologize for the late response.
I will be reviewing your package shortly.

Best regards,
Marcel

**Comment by wzthu** [comment]
Thank you, @LiNk-NY. I am looking forward to your suggestion.

**Comment by LiNk-NY** [comment]
Hi Zheng, @wzthu
I wasn't able to install the package locally. 
I'm not sure why. The build system installs the package without a problem.

You will get the review shortly. Thanks.

Regards,
Marcel 

> less Rbowtie2.Rcheck/00install.out
```
* installing *source* package ‘Rbowtie2’ ...
** libs
** arch - 
mkdir -p ../inst
(cd	adapterremoval && (make -j8 CXX="g++ -std=gnu++11" -f Makefile))
make[1]: warning: -jN forced in submake: disabling jobserver mode.
make[1]: Entering directory '/home/mramos/Documents/Bioconductor/GitHub/Rbowtie2.Rcheck/00_pkg_src/Rbowtie2/src/adapterremoval'
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c adapterset.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c alignment.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c argparse.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c debug.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c demultiplex.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c fastq.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c fastq_enc.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c fastq_io.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c linereader.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c linereader_joined.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c main_adapter_id.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c main_adapter_rm.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c main_demultiplex.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c scheduler.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c strutils.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c threads.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c timer.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c trimmed_reads.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c userconfig.cc 
g++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c main.cc 
cp AdapterRemoval ../../inst/
cp: cannot stat 'AdapterRemoval': No such file or directory
Makefile:50: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/mramos/Documents/Bioconductor/GitHub/Rbowtie2.Rcheck/00_pkg_src/Rbowtie2/src/adapterremoval'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: compilation failed for package ‘Rbowtie2’
* removing ‘/home/mramos/Documents/Bioconductor/GitHub/Rbowtie2.Rcheck/Rbowtie2’
```

**Comment by LiNk-NY** [comment]
Hi Zheng, @wzthu 
Thank you for submitting to Bioconductor!

Please see your package review below.

Feel free to contact me if you have any questions. 

Best regards,
Marcel

---

# Rbowtie2 #457

The Rbowtie2 does not import any Bioconductor packages.
We can see that an R interface to bowtie2 is valuable but
it does not make an attempt to integrate to the Bioconductor infrastructure.
I will discuss this with the Bioconductor core team and I will get back to you.

## DESCRIPTION

* The `Depends` field is missing. It should be set to `R (>= 3.4.1)`.

## R

* Make sure that your argument names are consistent across functions. 
* Typo in `R/adapterremoval.R#L169` "Argument", also `seq2` is not an
argument in the `remove_adapters` function.
* Avoid using `1:length(x)` sequence generation, use the  more robust
`seq_along(x)` or `seq_len(n)`.
* Avoid growing a vector (`paramArray <- c()`), please use the allocate
and fill strategy

## vignettes

* You can use parentheses to print your result in the same line
(e.g., `(cdmout <- adapterremoveal_version())`)
* Please include your `sessionInfo()` as the last chunk in your vignette.

**Comment by wzthu** [comment]
Thank you for your suggestions, Marcel @LiNk-NY .

You mentioned that you were not able to install the package locally. 

That is because we did not consider multi-core compiling for Makefiles.

We have revised the Makefiles to fix this bug. 

Besides, we have revised the related problem and suggestions mentioned in package review.

**Comment by LiNk-NY** [comment]
Hi Zheng, @wzthu 
Thank you for making those changes! 
Your package has been accepted. 
Thank you for submitting to Bioconductor. 

Best regards,
Marcel

**Comment by wzthu** [comment]
Great! Thanks, Marcel @LiNk-NY !

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (tithub.com/<username>.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"YOUR_PACKAGE_NAME\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/YOUR_PACKAGE_NAME

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
