### ISSUE TITLE
methyvim

### ISSUE THREAD

**Issue by nhejazi** [Bioconductor/Contributions#463]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nhejazi/methyvim

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by nhejazi** [comment]
AdditionalPackage: https://github.com/nhejazi/methyvimData

**Comment by mtmorgan** [comment]
Please remove non-R / Bioconductor from your master branch so that, when your package is accepted, only R package files are added to the Bioconductor git repository.

**Comment by nhejazi** [comment]
@mtmorgan -- Do you just mean to remove the `remotes` section in `DESCRIPTION`?

**Comment by mtmorgan** [comment]
No, the various files CODE_OF_CONDUCT.md etc that are not part of basic R packages structure. Move these to a distinct branch for the duration of the review.

The remotes: field is not supported; your data (package) also needs to be available in CRAN or via Bioconductor. If you're submitting to Bioconductor then the strategy is to submit first the package (usually the experiment data package) that does not depend on the other package, and work through whatever problems cause it not to build. Once building, add the 'AdditionalPackage' field referencing a second package. The workflow is described at https://github.com/Bioconductor/Contributions#submitting-related-packages

Assuming that the data package is the one that can be built independently, I suggest that we close this issue and that you open a new issue with the data package.

**Comment by nhejazi** [comment]
Ok -- got it. Sure -- I'll move those files to a separate branch.

The data package that I added above via the "AdditionalPackage" statement is not strictly necessary for this package to build so I don't think we need to close this issue. I'll remove the data package and the remotes field and we should be able to proceed from there.

**Comment by nhejazi** [comment]
Closing this. Will open a new issue and submit the independent data package first.
