### ISSUE TITLE
loci2path

### ISSUE THREAD

**Issue by StanleyXu** [Bioconductor/Contributions#467]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/StanleyXu/loci2path

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by LiNk-NY** [comment]
Hi TianLei Xu, @StanleyXu
Thank you for submitting to Bioconductor.
`loci2path` provides analysis for eQTL conveniently using `GRanges` objects.
The package can benefit from function outputs with more structure. 

Please find the review below.
If you have any questions, let me know. 
Regards,
Marcel

---

# loci2path #467

Formatting of code and DESCRIPTION should make it readable. Please make sure
you are not going over 80 columns.

## DESCRIPTION

* Please include `URL` and `BugReports` fields and their respective links
* Review the need to include `GenomicRanges`, `BiocParallel` and `GenomeInfoDb`
in the `Depends` field. Are you building on top of these packages or just
using the functions and classes? The former would require you to list them
in the `Depends` field.
* Please use the release version of `roxygen2` unless the devel is required.

## NAMESPACE

* Explicitly export functions in your package, do not use a pattern for
exporting functions, use the `roxygen` `@export` and related tags

## R

* Please use the `<-` assignment operator to avoid confusion with `=` in
argument assignment. 
* Please use accessor functions for your `eqtlSet` and other relevant classes,
avoid the use of `@` in code for slot extraction.
* Avoid the use of `1:nrow(x)` sequence generation, use the more robust
`seq_len` or `seq_along`
* Please include a file argument for functions that save to a file such as
`draw.wordcloud`
* Use a consistent naming convention. For Bioconductor S4 classes, `camelCase`
is preferred.
* Some of these functions can actually be methods so to have shorter
function names, i.e., `query.egset.list` -> `setMethod("query", "eqtlSet")`
* A list structure might not be the best representation for your object.
Consider using an S4 object outputs for functions such as `query.egset.list`
* Why do you need `invisible(NULL)` in the show methods?

**Comment by StanleyXu** [comment]
Hi Marcel,

Thank you very much for the suggestions. I’m working on updating codes for this package. I have a question for your comment:


"Some of these functions can actually be methods so to have shorter
function names, i.e., query.egset.list -> setMethod("query", "eqtlSet")“


The two major query functions require two classes: eqtlSet and geneSet, because we try to utilize two independent data sources to perform enrichment analysis. Thus the function is wrote as taking two classes as argument, rather than a method for one specific class. In this case, is it okay that we leave the function as it was?

I agree that the output can be represented in an S4 object. I’ll work on a new output class and implement methods accordingly.

Thank you!
Tianlei

**Comment by LiNk-NY** [comment]
Hi TianLei, @StanleyXu 

Sorry for the delay in responding. 
There are ways to dispatch to multiple class signatures:

```
setMethod("query", signature = c("query", "eqtlSet", "geneSet"), function(a , b, c) { # code here } )
```

Best regards,
Marcel

**Comment by StanleyXu** [comment]
Thank you very much Marcel! I'll modify this method accordingly. 

I'm at the end stage of implementing the features in your previous comment. I have another question in regard of this issue:
" Please include a file argument for functions that save to a file such as
draw.wordcloud"

I intended to generate plots to the default R active graphics window, such as what function plot.default() does. Is this okay without specifying a file name? Users can specify their output format using pdf(), png(), ... etc.

Thank you!
Tianlei

**Comment by LiNk-NY** [comment]
Hi TianLei, @StanleyXu 

Yes, this method is preferred as the user can save his/her own plots in a
preferred format by calling `pdf`, `png`, etc.

Best regards,
Marcel

**Comment by StanleyXu** [comment]
Hi Marcel,

Thank you for your suggestions and helps. I've finished updating the package. The new version is uploaded and passed the tests. Below is a list of modifications addressing your questions in the previous review. Please let me know if there are further improvements needed.

Best,
Tianlei


----
>Please include URL and BugReports fields and their respective links

- fileds `URL` and `BugReports` are added to the current DESCRIPTION file



>Review the need to include GenomicRanges, BiocParallel and GenomeInfoDb
in the Depends field. Are you building on top of these packages or just
using the functions and classes? The former would require you to list them
in the Depends field.

- Move GenomicRanges, BiocParallel and GenomeInfoDb from Depends; I only need the functions.




>Please use the release version of roxygen2 unless the devel is required.

- `roxygen2` is updated to the release version before generating the current documents.





>Explicitly export functions in your package, do not use a pattern for
exporting functions, use the roxygen @export and related tags

- Roxygen tags are updated for all functions, so the current NAMESPACE is completely generated by roxygen2




>Please use the <- assignment operator to avoid confusion with = in
argument assignment.

- Assignment operator are unified to “ <- “, and argument assignment are unified to “=“ (without space)



>Please use accessor functions for your eqtlSet and other relevant classes,
avoid the use of @ in code for slot extraction.

- All classes are updated with accessors; Slot extraction in the codes are replaced with accessors.


>Avoid the use of 1:nrow(x) sequence generation, use the more robust
seq_len or seq_along

- All sequence generation parts are updated.



>Please include a file argument for functions that save to a file such as
draw.wordcloud

- All the figure generating functions will not write figures to a file and will generate plots in the active graphics window



>Use a consistent naming convention. For Bioconductor S4 classes, camelCase
is preferred.

- Naming convention changed to camelCase for all the S4 classes


>Some of these functions can actually be methods so to have shorter
function names, i.e., query.egset.list -> setMethod("query", "eqtlSet")
>A list structure might not be the best representation for your object.
Consider using an S4 object outputs for functions such as query.egset.list

- New query methods are designed to replace previous function (query.egset, query.egset.list, query.tissue).
- Also a new Class `loci2pathResult` is designed for query output. All the result exploring functions are modified accordingly.



>Why do you need invisible(NULL) in the show methods?

- Remove unnecessary empty returning statement. 

---

**Comment by StanleyXu** [comment]
Dear Marcel,

I just noticed that a new release of Bioconductor today. I'm wondering if this submission process will be affected, since it is still in review. Please let me know if I need to further modify my package. 

Thank you!
Tianlei

**Comment by LiNk-NY** [comment]
Hi StaleyXu, @StanleyXu 
Unfortunately, your package was not able to be included in the release version of Bioconductor 
this time around as the deadline for new release packages has passed.
We can still include it in the development branch of Bioconductor 3.7. 
Thank you for making those changes. I will have another look at your package shortly.

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi TianLei Xu, @StanleyXu
Thank you for contributing to Bioconductor!
Your package has been accepted.

Best regards,
Marcel

**Comment by StanleyXu** [comment]
Hi Marcel @LiNk-NY , Thank you for your suggestions and helps during the development!

Regards,
Tianlei

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/StanleyXu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"loci2path\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/loci2path

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
