### ISSUE TITLE
EpiCluster

### ISSUE THREAD

**Issue by JoshuaTian** [Bioconductor/Contributions#470]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JoshuaTian/EpiCluster

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
@JoshuaTian your vignette contains 'pictures of code' but must contain actual code chunks `<<>>=` please provide a real vignette and post a comment here addressed to me. I will then approve your package to begin the review process.

**Comment by JoshuaTian** [comment]
Hello @mtmorgan  , I have changed vignette into Rmarkdown format, and I have run R CMD build, R CMD check, and BiocCheck, it seems there is no error or warning. Could you please check it?

**Comment by mtmorgan** [comment]
Your code chunks are marked `eval = FALSE`, but they must actually be evaluated, otherwise how will your user have any confidence that the code works?

**Comment by JoshuaTian** [comment]
Oh, sorry, I just know what you mean "picture of code", you actually mean code not running in vignette, which seems acceptable before. I did not run them because I don't want these program output too many messages, thus the vignette would be pretty long... Sorry that I did not know this new rule for Bioconductor. OK I will change it again.

**Comment by mtmorgan** [comment]
It is not actually a new rule, it has been a requirement for many years. Also, if the output is too verbose for the vignette, then maybe it is too verbose for a user; consider adding a 'verbose=FALSE' argument.

**Comment by mtmorgan** [comment]
I haven't seen any change and am closing the issue. Thanks for considering Bioconductor!
