### ISSUE TITLE
TnT: interactive visualization for track-based genomic data

### ISSUE THREAD

**Issue by Marlin-Na** [Bioconductor/Contributions#487]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Marlin-Na/TnT

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Marlin-Na** [comment]
@LiNk-NY 
Hi Marcel, it seems that the package has passed automatic building.
Would you like to have a review on it? Comments would be appreciated! ;-)

Comments from others are also welcome, and I will address them as well !

Sincerely,
Jialin

**Comment by lawremi** [comment]
epivizr is related work

**Comment by Marlin-Na** [comment]
@lawremi 
Hi Michael, I think TnT may not be as that fully functional as epivizr. In fact I did have a look at the epivizr package before I started writing the package, though I did not go into the detail. As what I see from its vignette, it is not possible use it locally, or I missed it?

I see TnT as an interactive version of Gviz, rather than a fully functional genome browser like IGV or epiviz. It can be used to take a quick look at the R objects (i.e. GRanges, GRangesList, TxDb, EnsDb) and embed into Rmarkdown or shiny applications. However, the interaction between the rendered browser and R is currently limited. It is also not possible to use remote source for now, all shown tracks must be in-memory R objects, though in future tracks linking to a remote source (e.g. to a bam file) may be implemented.

**Comment by Marlin-Na** [comment]
@lawremi 
Well, to correct me, it seems that epivizr can be used locally with Epiviz Desktop and epivizrStandalone.

**Comment by LiNk-NY** [comment]
Hi Marlin, @Marlin-Na 
Apologies for the delay. 
I will be reviewing your package soon. 
Thank you. 

Best regards,
Marcel

**Comment by Marlin-Na** [comment]
Hi Marcel @LiNk-NY ,

Thanks for your reviewing comments! I will address them in the following days.

A few questions:

1. I would like to replace `build.sh` with a R script that may help other potential developers for testing purposes, and it contains the script to build the documentation site. I have added it to `.Rbuildignore`, so will it be acceptable?

2. I am not sure about the difference between `is` and `inherits`, is there any advantage for using `is`?

Thanks!
Jialin

**Comment by LiNk-NY** [comment]
Hi JiaLin, @Marlin-Na 
1. Yes, you can add it to the `.Rbuildignore`. 
You may also add it to an `inst/scripts/` folder.

2. The difference is subtle. The `is` function is specifically designed for formal `S4` classes.
Both functions are similar but there are exceptions where `inherits` will return a different output
from `is`. The safer bet is to use `is` all the time for S4 classes, especially when testing classes
with complex inheritance.

Regards,
Marcel

**Comment by Marlin-Na** [comment]
Hi Marcel @LiNk-NY ,

Thanks for your comments! I have made the following changes:

> Please relocate examples enclosed in if (FALSE) {} to inst/scripts/
  These examples may be added to the vignette

I have relocated most of those examples to `inst/vignettes/examples/Notshown*.Rmd`, which will be executed when building documentation site.

> Reduce JSCascade and similar functions to just one argument (with "...") by taking list(...) and subsetting to the first element if it is already a list.

Fixed. I found that I did not really use that extra argument `.listData` in my code, thus I simply removed it.

> Avoid renaming functions within your code (e.g., js, jc, etc.)

Fixed.

> Use methods::is for testing class membership for S4 classes

Fixed, except for three S4 classes used internally (JavaScript, JSCascade, MultiArgs).

The main reasons are:
1. In my code, the three classes are tested together with multiple S3 classes and the function is called recursively. It seems that unlike `is`, `inherits` can once test against multiple classes.
2. The three classes are used internally, and I do not expect user constructing such objects nor extending the classes.

Hope it would be okay.

> There's no apparent need to nest functions in .convertToJSChar

The reason is that the nested function is called recursively by itself and it would be safe to rename the parent function. But I have fixed it using `sys.function()` instead of nested function.

> Avoid using sapply and use the more robust vapply instead

Fixed.

> Avoid assigning variables to function names to avoid name collisions,  i.e., t <- new(class)

Fixed.

> End show outputs in newline \n

Fixed.

> if (!length(x)) is equivalent to if (length(x) == 0L)
    if (length(x)) is equivalent to if (length(x) > 0L)

Fixed.

> Use the semantically better replacement method, setReplaceMethod

Fixed.

> Always provide error messages when calling stop, mark <internal> as necessary

Fixed.

> Functions like .checkBoardSpec can be validity checks for your class

`.checkBoardSpec` is not part of the object validity because missing values (like background color) are in fact allowed in the object but will be filled before the browser is rendered. So I consider it is a sanity check which should not be seen by users.

> Color inputs should also be integer, as in base functions

Fixed, and I have modified some examples in vignettes to use integer input with palette function.

> Add a default value when no background is selected in the show method

Fixed. And I use `par('bg')` as default value in the show method and use it to fill missing values.

Please see if you have any further comments, thanks!

Regards,
Jialin

**Comment by LiNk-NY** [comment]
Hi JiaLin, @Marlin-Na 
Thank you for making those changes. 

Your package has been accepted. As you maintain your package,
please follow the `BiocCheck` recommendations. You can also
look at [MangoTheCat/goodpractice](https://github.com/MangoTheCat/goodpractice).

Thank you for submitting to Bioconductor.

Best regards,
Marcel

**Comment by Marlin-Na** [comment]
@LiNk-NY Hi Marcel, thanks again for reviewing and accepting the package!

Best regards,
Jialin

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Marlin-Na.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"TnT\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TnT

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
