### ISSUE TITLE
bcSeq

### ISSUE THREAD

**Issue by jl354** [Bioconductor/Contributions#495]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jl354/bcSeq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
Needs to integrate with Bioc data structures. Presumably sequences could be passed from as DNAStrings and results returned in GAlignments or GRanges.

Also, if this is a novel algorithm written in C++, why not make it a separate C++ library, with this package as the R interface to it?

**Comment by jl354** [comment]
Hi lawremi
Will try to add returns in GAlignments, however, the package meant to deal with the Phred score. I am not quite sure if the DNAstring can be implemented, do you have some examples.

It is incorporate some nice C++ features for both DNA sequence and phred score, not a quite independent C++ library. Also, it would be handy to add in with Rcpp.

* The windows build of our package has some error that is similar to the post  below:
https://github.com/Bioconductor/packagebuilder/issues/2
I have tried my own window system for building and CRAN windows builder. Both works fine. Can you suggest what we can do with this?

Bests
Jiaxing

**Comment by jl354** [comment]
Hi lawremi @lawremi 
Will try to add returns in GAlignments, however, the package meant to deal with the Phred score. I am not quite sure if the DNAstring can be implemented, do you have some examples.

It is incorporate some nice C++ features for both DNA sequence and phred score, not a quite independent C++ library. Also, it would be handy to add in with Rcpp.

The windows build of our package has some error that is similar to the post below:
Bioconductor/packagebuilder#2
I have tried my own window system for building and CRAN windows builder. Both works fine. Can you suggest what we can do with this?
Bests
Jiaxing

**Comment by lawremi** [comment]
Should be possible to incorporate any additional scores into GAlignments in the metadata columns. I'm not sure what kind of examples you need for DNAString. I think the user would want to pass sequences in a DNAString(Set) to your aligner.

**Comment by jl354** [comment]
@lawremi 
Hi I had update the package per your recommend for add support for the DNAString(Set) as package aligner input.

**Comment by LiNk-NY** [comment]
Hi JianXing, @jl354 

Thank you for your submission to Bioconductor. 
Please find the review below.

If you have any questions, feel free to contact me. 

Best regards,
Marcel 

----

# bcSeq #495

`bcSeq` is a fast aligner for shRNA and CRISPR. 

You've updated the package to support `DNAString(set)`

## DESCRIPTION

* Please include a `Depends` field
* Import additional packages based on @lawremi 's review
* Include a `BugReport` field

## NAMESPACE

* Looks good 

## R

* Please remove "Error!" word from error message. `stop` already labels it as
an error.
* It looks like you're overwriting `tMatSeq[1]` with `tMatSeq[1] <- tMat[1, 1]`,
it doesn't seem necessary
* Avoid `1:nrow(x)`. Use `seq_len(nrow(x))` instead for robustness
* Use `is.character` and related functions to check for S3 class membership

## vignettes

* I wasn't able to pull up the vignette after installation. I used:

```
# R CMD INSTALL bcSeq_* && R
library(bcSeq)
browseVignettes("bcSeq")
vignette(package = "bcSeq")
```
* Other than that, the code runs without issues

**Comment by jl354** [comment]
Hi Marcel, @LiNk-NY

Thanks you so much for the suggestive comments on the package.
We have made modification according to your comments as below:

*DESCRIPTION
 (1) added Depends filed
 (2) imported DNAStrings
 (3) included a BugReport filed

*R
 (1) remove "Error!" word
 (2) Explain: in the beginning we set up a default value for tMatSeq[1]
     and we check if the user supply a vectir fir tMatSeq, if it is true,
     we put the vector to tMatSeq and make tMatseq a vector. Thus, we want
     an over write. However, better solution are welcomed.
 (3) changed 1:nrow(x) to seq_len(nrow(x)) for robustness
 (4) Used is.character() for checking S3 class.

*vignettes
 I try the following code and it can pull up the vignette:
 R CMD INSTALL bcSeq_* && R
 library(bcSeq)
 vignette("bcSeq", package = "bcSeq")

Again, thank you so much for taking time for review our package.
Also, the modified code pass through the build check. Please let us
know if you have other questions.

Bests

Jiaxing

**Comment by LiNk-NY** [comment]
Hi JiaXing, @jl354
Please use `is.character(sampleFile)` and `is(sampleFile, "DNAStringSet")` respectively for S3 and S4 class tests in your code.
It's pretty close. 

Thanks,
Marcel

**Comment by jl354** [comment]
Hi Marcel @LiNk-NY 

Thanks for the careful review, I have update the S3 and S4 test methods according to your suggestion. 

Bests

Jiaxing

**Comment by jl354** [comment]
Dear Marcel @LiNk-NY

I have pushed your proposed changes from 10/26. The revised package builds successfully.

Could you please advise if additional revisions are needed to get our package approved?

Sincerely,
Jiaxing @jl354

**Comment by LiNk-NY** [comment]
Hi JiaXing, @jl354 
Sorry for the delay. Package reviews were put on the back burner for a bit.
I will have a quick look at the package and likely approve of it shortly.
Best regards,
Marcel

**Comment by jl354** [comment]
Dear Marcel @LiNk-NY

May I please ask when our package is expected to be added to the Bioconductor git repository?

Happy Thanksgiving.

Sincerely,
Jiaxing @jl354

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jl354.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"bcSeq\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/bcSeq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
