### ISSUE TITLE
GAprediction

### ISSUE THREAD

**Issue by JonBohlin** [Bioconductor/Contributions#50]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JonBohlin/GAprediction

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by JonBohlin** [comment]
I think I know what the problem is. I originally called the package predictGA, but had to change the name because I hadn't uploaded the R files properly the first time. The case was closed and I had to use a new name. Is it possible to open the old predictGA repository?

**Comment by mtmorgan** [comment]
Sorry for my slow response. You could close this issue, rename your github repository, revert the DESCRIPTION file and other changes with the new package name,, and open another issue. I'll assign myself to it. Alternatively, you could update your current code (e.g., in the vignette, where you say require(predictGA) to match the new package name.

**Comment by JonBohlin** [comment]
OK -thanks! The package is called "GAprediction" and all files have been updated. I have now tested the package multiple times with both windows and linux and it seems to (R CMD) run, build and check(BiocCheck) fine now, so please try again!

**Comment by mtmorgan** [comment]
To trigger a build, make a commit to the master branch where the version number in the DESCRIPTION file is changed from 0.99.0 to 0.99.1

**Comment by JonBohlin** [comment]
OK, it's done,

**Comment by dtenenba** [comment]
Have you [set up a webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook)?

It seems that our system did not detect your commit and push.

Please add a web hook and then bump the version again, to 0.99.2, and commit and push that change.

**Comment by mtmorgan** [comment]
Looks like the remaining issue is because the package lists your address @fhi.no whereas you are subscribed to biocDevel as @gmail.com

**Comment by JonBohlin** [comment]
OK -thanks, I was starting to wonder...

**Comment by mtmorgan** [comment]
Thanks for your package.

- Since the central function of the package processes
  HumanMethylation450k arrays, it seems like predictGA should accept
  the output of common upstream software for processing this data,
  e.g., minfi(??). Likely this can be accomplished by writing a
  one-line test / coercion inside predictGA that extracts the relevant
  matrix if the argument is of the appropriate type. Likely this also
  requires at least adding the relevant package where the class and
  accessor are defined to the Suggests: field of the DESCRIPTION file,
  or better Import:'ing the relevant package and functions.
- A LICENSCE file is not needed for GPL-2; please remove it
- use `message()`  rather than `cat()`  to communicate with  the user;
  messages can be suppressed via `suppressMessages()`
- include context in error messages, rather than printing the error
  message to the screen and stopping uninformatively, e.g., at
  predictGA.R:32 write
  
        stop("Missing essential CpGs needed for prediction\n"
              predictorSites[temp], "\n")

- vectorize rather than iterate, for instance at predictGA.R:53

		for(i in predictorSites)
			predMatr[,i]<-mldat[,i]

  is I think just `predMatr[, predictorSites] <- mldat[, predictorSites]`
  
- explicitly invoking the garbage collector, e.g., at predictGA.R:68
  is seldom necessary; these objects will be available for garbage
  collection as soon as the function ends, i.e., after the next line.
- It seems like the UL.mod.cv data is a central component of the
  model, and its derivation should be described explicitly (e.g., as a
  script in `inst/script/`.
- consider adding spaces around `<-` in the man pages; this makes the
  code more readable.

**Comment by JonBohlin** [comment]
Thank you very much for you comments! I am now on vacation but will look into this and get bet back to you!

**Comment by JonBohlin** [comment]
Thank you very much for taking the time to review my code and for your excelent comments. I have included a point-to-point response to them below. Your comments start with a bulletpoint, my responses are in _italic_

•	Since the central function of the package processes HumanMethylation450k arrays, it seems like predictGA should accept the output of common upstream software for processing this data, e.g., minfi(??). Likely this can be accomplished by writing a one-line test / coercion inside predictGA that extracts the relevant matrix if the argument is of the appropriate type. Likely this also requires at least adding the relevant package where the class and accessor are defined to the Suggests: field of the DESCRIPTION file, or better Import:'ing the relevant package and functions.

_Yes, this is a good idea. However, there are many different packages used for treating HumanMethylation450k data having myself used Minfi, WateRmellon and Methylumi. Unfortunately, there is no standard method (yet?) for extracting the beta-matrix which is required by the GA predictor. All the packages mentioned above are quite comprehensive and I’d like to keep this program as small and independent as possible._

•	A LICENSCE file is not needed for GPL-2; please remove it

_Removed_

•	use message() rather than cat() to communicate with the user; messages can be suppressed via suppressMessages()

_OK, thanks!_

•  include context in error messages, rather than printing the error
message to the screen and stopping uninformatively, e.g., at
predictGA.R:32 write
  stop("Missing essential CpGs needed for prediction\n"
        predictorSites[temp], "\n")

_OK_

•  vectorize rather than iterate, for instance at predictGA.R:53
for(i in predictorSites)
    predMatr[,i]<-mldat[,i]
is I think just predMatr[, predictorSites] <- mldat[, predictorSites]

_Thanks!_

•	explicitly invoking the garbage collector, e.g., at predictGA.R:68
is seldom necessary; these objects will be available for garbage
collection as soon as the function ends, i.e., after the next line.

_Thanks!_

•	 It seems like the UL.mod.cv data is a central component of the model, and its derivation should be described explicitly (e.g., as a script in inst/script/.

_An accompanying paper is under review and there everything is explained in detail. One of the reviewers wanted us to write a package to do GA prediction and so I did. Hopefully, the paper will be accepted soon._

•	consider adding spaces around <- in the man pages; this makes the code more readable.

_OK_

**Comment by mtmorgan** [comment]
I'm sorry for my slow response. The changes look great and I'm marking this as 'accepted'. It'll be added to the nightly builds and the Bioc svn repository, with further instructions via email in the next several days.

**Comment by JonBohlin** [comment]
Great thanks!

Jon
