### ISSUE TITLE
Guitar2

### ISSUE THREAD

**Issue by laureniezhang** [Bioconductor/Contributions#500]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/laureniezhang/Guitar2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
The level of integration with Bioconductor is commendable. Nice work.

A few recommendations:

I noticed that this contains a custom BED12 parser. I'm pretty sure you could use `import.bed()` instead and call `blocks()` on the result to get the GRangesList corresponding to `exonsBy()` on a TxDb.

It's also weird to have an argument for saving to PDF in a plotting function. The graphics output is orthogonal to the plot itself. The user should be able to save to a file using existing mechanisms.

There's some code that constructs R code as a string, parses it and evaluates it. Whenever you find yourself in a situation where you think you need to do that, please ask for help. There is almost always a better way. Even when code generation is necessary, construct the language objects directly; don't parse a string. In this particular case, I think you're looking for `do.call()`.

To generate the `landmark` object in the vignette, I think you want something like `split(GuitarCoords, ~ comp + category)`.

**Comment by nturaga** [comment]
Hi @laureniezhang 

This seems like a copy of the Guitar (http://bioconductor.org/packages/release/bioc/html/Guitar.html) package by a different author. 

Please explain why you are contributing a new package rather than arranging with the original author to update their package.

**Comment by nturaga** [comment]
Hi @laureniezhang 

You have 2 weeks to reply to the review comments before we close the issue. If there is no response by Oct 31st, the issue will be closed. 

Thanks

**Comment by nturaga** [comment]
@laureniezhang There was no response from you. This issue is being closed.
