### ISSUE TITLE
pcxn

### ISSUE THREAD

**Issue by BioSok** [Bioconductor/Contributions#501]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hidelab/pcxn

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by BioSok** [comment]
Dear @vobencha , I believe the ERROR concerns the turned-off Tcl/Tk (and X11?) during compilation on Linux and OSX. I believe they are TRUE by default on the Windows server where the package builds fine.

**Comment by vobencha** [comment]
Hi,

It looks like we have a mixture of a software and experimental data package.

* In general, experimental data packages do not contain R code. Functions that manipulate the data object belong in a software package that defines the class of the data object.
* I would not recommend setting so many global variables. This usually means the existing functions don't have the proper input arguments to create the desired outcome. Please explain why you feel you need these:
utils::globalVariables(c("pathprint.Hs.gs","pheatmap",
                            "pathCor_pathprint_v1.2.3_dframe",
                            "pathCor_CPv5.1_dframe", "gobp_gs_v5.1",
                            "PathCor", "p.value", "Pathway.A", "Pathway.B"))
* The name of the vignette file is inconsistent with the name of the package (PCxN vs pcxn).
* I don't see the need to create the pxcn object. It is a matrix with a list. Why not reuse objects from Biobase, GSEABase, or SummarizedExperiment? Please consider re-packaging the data in an existing class and using the getters/setters already in place for that class. 

Please explain a little more about what you want to accomplish with this package. Once that's cleared up I can give better guidance on how to restructure.

Valerie

**Comment by BioSok** [comment]
Dear @vobencha ,

This package is meant to carry the functionality (mostly as queries) of the included functions using the present data. In the future this package will be extended and we want to build around the pcxn object and that is the reason we want to differentiate it. The specific fields of this object also coincide with other forms of existing pcxn (like a web-tool). This object should be plugged in future R packages which are part of a pipeline along with pcxn. 

The global variables were used as it was the only successful way to gain access to those data from within the functions. After your comment I will try to find the proper way to do this.

Thank you for your time and help!

With regards,
Sokratis

**Comment by vobencha** [comment]
Hi,

The data should be separate from the software functions unless you can pair it down to the required size which is <=4MB on disk: http://www.bioconductor.org/developers/package-guidelines/#correctness

Can you reduce the size and should we go ahead with pcxn as a software package?

Valerie

**Comment by BioSok** [comment]
Hi,

Unfortunately all included data are necessary and cannot be loaded from another place, so I cant remove them. I will split the current package to a software (named pcxn) and a data package (named pcxnData). If I do the split (within few days) will both packages be included in the coming release? Thanks!

-Sokratis

**Comment by vobencha** [comment]
We'll do our best but there are no guarantees. Both packages must meet the guidelines and go through the full review process.

The process is described in detail here: https://github.com/Bioconductor/Contributions. The key steps are,
- close this issue
- open a new issue for the data package; once the data package passes build/check then
- submit the software package to the same issue

Valerie
