### ISSUE TITLE
transcriptogramer

### ISSUE THREAD

**Issue by arthurvinx** [Bioconductor/Contributions#504]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/arthurvinx/transcriptogramer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by arthurvinx** [comment]
Hello Daniel, I'm wondering the reason of the build failure on Windows, it is a server problem?

> 'BiocCheck' is not recognized as an internal or external command, operable program or batch file.

**Comment by arthurvinx** [comment]
Hello @dvantwisk, I made some minor changes in the last commits:
[x] Avoid 1:n style iterations
[x] Some methods now have an argument to set the number of processing cores
[x] Minor fixes (documentation and vignette)

I'm sorry for these changes, I will not make any other change until your review is done.

**Comment by arthurvinx** [comment]
Hello, @dvantwisk, I saw one of the @lshep posts...

> The deadline for new packages to be included in the Oct 31 release is next Tue 17.

Any news about the review? I'm worried about the deadline.

**Comment by dvantwisk** [comment]
I am review it now, I will try to have something for you shortly.

**Comment by lshep** [comment]
Also please note that even if it is not accepted by tomorrow to be included in Bioc 3.6, it can still be accepted into the devel version of Bioconductor and will be released under Bioc 3.7.

**Comment by dvantwisk** [comment]
I am just finishing up looking through you R files. I am just checking off on a few more things in your R code, and am awaiting a few email from my supervisors about it. The review below is for everything aside from the R code, I'll give you this first so you can correct these issues:

DESCRIPTION:
- LICENSE: Choose specific version of GPL license to use.
- [CONSIDER] using `BiocParallel` in place of `parallel`.  Also make appropriate changes to R code to reflect this.

**Comment by arthurvinx** [comment]
Hello @dvantwisk, here is a quote from the [GNU.org](https://www.gnu.org/licenses/license-recommendations.html):

> Please give permission to use future license versions as well—in other words, make the license notice say that your program is covered by GPL version 3 or later.

And some of the bioconductor's packages use 'GPL (>= 2)' as license.
[RedeR](https://github.com/Bioconductor-mirror/RedeR/blob/master/DESCRIPTION), [geneplast](https://github.com/Bioconductor-mirror/geneplast/blob/master/DESCRIPTION).

**Comment by dvantwisk** [comment]
Thank you for pointing this out.  I actually wasn't aware of this with the GPL License.

**Comment by dvantwisk** [comment]
I apologize for the delay, I had to clarify some things with a supervisor before I could review your R code, here is out review of your R code:

- First argument of all getters and setters should be `x` or
   `object`, not `.Object`.

- The getSlot() generic and method make no sense. They need
   to provide individual getters e.g. association(), ordering(),
   radius(), etc... instead. But only for the slots that they
   actually want to expose to the user.

- `setRadius()` should be replaced with a `radius()` *setter* i.e.
```
     setGeneric("radius<-", signature="x",
         function(x, value) standardGeneric("radius<-")
     )
     setReplaceMethod("radius", "Transcriptogram",
         function(x, value) {
             ....
         }
     )
```
   The purpose of all this is to allow the user to use the radius()
   on the *left* side of the assignment e.g.:

     `radius(x) <- some_value`

   This is the typical syntax for modifying the content of an object.
   A very R-ish one!

- This kind of verbosity provides no useful information and should
   be avoided:
```
     > x <- setRadius(x, 80)
     done!
```
- Transcriptogram objects need a "show" method.

- And yes, the big monolithic transcriptogramer.check() function
   for checking any user input value seems poor coding practice.
   Separate functions, one for each input, would make more sense e.g.

     `check_ordering()`, `check_association()`, `check_expression()`, etc...

- You shouldn't include dots in their function names (except if the
   function is an S3 method). This is particularly important for
   exported functions.

Once you address these issues, I'll do a quick look through your code.  I'll be here all day and we should be able to get your package in as long as it's finished by 5:00pm.

**Comment by dvantwisk** [comment]
How are the updates with this coming along?

**Comment by arthurvinx** [comment]
Hi @dvantwisk, I will not be able to do the updates today, hence, I will miss the Bioc 3.6 release.

But I will update the package as soon as possible, thank you for the feedback.

**Comment by arthurvinx** [comment]
Thank you for your patience @dvantwisk, I'm ready for another review.

**Comment by arthurvinx** [comment]
I'm ready for another review @dvantwisk.

**Comment by dvantwisk** [comment]
Okay, I'll have a look at it soon.

**Comment by dvantwisk** [comment]
Apologies for the delay.  All the changes look good!  I'll go ahead and accept it.

**Comment by dvantwisk** [comment]
Btw, the timeout on tokay1 was an issue on our part.  And your package appears to build fine on all systems.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/arthurvinx.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"transcriptogramer\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/transcriptogramer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
