### ISSUE TITLE
dmrseq

### ISSUE THREAD

**Issue by kdkorthauer** [Bioconductor/Contributions#513]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kdkorthauer/dmrseq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by kdkorthauer** [comment]
Hi,

There were two issues with my build report: 

- WARNING in CHECK on tokay1: used R version 3.4.1 (2017-06-30), but package 'matrixStats' was built under R version 3.4.2. Seems like either R version 3.4.2 should be used on this system, or the 'matrixStats' package should be reverted on tokay1 to the version built on 3.4.1. 

- ERROR in CHECK on tokay1: 'BiocCheck' is not recognized as an internal or external command,
operable program or batch file. Seems like BiocCheck is not being called correctly on this system. 

I'm not sure what I can do on my end to solve these issues. Any suggestions would be greatly appreciated. No warnings or errors on OS X or Linux.

Best,
Keegan

**Comment by kdkorthauer** [comment]
I kicked off a new build; now the error on tokay1 is resolved, and just the warning about versions of the `MatrixStats` package remains.

**Comment by kdkorthauer** [comment]
Hi @lawremi,

I noticed that another recently submitted package has the same issue (`DelayedMatrixStats`, issue https://github.com/Bioconductor/Contributions/issues/514#issuecomment-334852343), which pertains to another package and not `dmrseq`. 

Best,
Keegan

**Comment by lawremi** [comment]
I'm not going to be able to help with the build issues. But I will have a review for you soon.

**Comment by lawremi** [comment]
Here is the review:

# Overall<a id="orgheadline1"></a>

# `DESCRIPTION`<a id="orgheadline2"></a>

-   Authors: totally up to you, but you might consider including
    others involved in the work (e.g., the paper authors)

# Vignette<a id="orgheadline3"></a>

-   There is a code comment that mentions hg19 but the code uses hg18.

# API<a id="orgheadline8"></a>

## `dmrseq()`<a id="orgheadline4"></a>

-   Does the `BPPARAM` argument really only accept a *SnowParam* or
    *MulticoreParam*? Ideally, it wouldn't care about the specific
    implementation.
-   Why not drop the `parallel` argument and instead expect the user
    to pass a SerialParam to disable parallelization? By default I
    think BiocParallel just uses 2 cores, so it's probably safe to
    parallelize by default.
-   What is the difference between passing `sampleIndex` or just
    subsetting the input object for the samples of interest? It seems
    like the latter would be more clear.
-   It seems like the return value should be a GRanges, with
    `indexStart` and `indexEnd` folded into an IRanges and attached
    as a metadata column, along with the other outputs.

## `filterLoci()`<a id="orgheadline5"></a>

-   Function needs a more specific name, if you want to keep it
-   It ignores its `minCoverage` argument
-   Not sure this function is really needed, as it should be easy
    enough for the user to filter by coverage directly

## `plotEmpiricalDistribution()`<a id="orgheadline6"></a>

-   The user should probably be responsible for saving graphics
    device output to a file, e.g., using `dev.copy()`, so this
    function does not need to save any files.

## `simDMRs()`<a id="orgheadline7"></a>

-   Similar to above, avoid having functions that both generate a
    value, and cause side effects. The idea is to isolate side
    effects, because they do not blend well with the functional
    nature of R, but also there is a general desire for *cohesion* (a
    module should have a single responsibility, at some level of
    abstraction, deciding on the level is the hard part). More
    cohesive modules are easier to reuse. They are also easier to
    understand, because it forces the user to express themselves
    (again, at the "right" level). Consider:
    
        simDMRs(file, bs=BS.chr21, num.dmrs=300)
    
    It is not at all obvious what `file` means: is it an input or an
    output? Instead, this is more obvious:
    
        save(simDRS(bs=BS.chr21, num.dmrs=300), file=file)

# Code<a id="orgheadline19"></a>

## `filterLoci()`<a id="orgheadline9"></a>

-   It is almost never necessary to call `rm()` and `gc()`. If
    memory is a problem, it is best to iterate. There are many
    other places where this happens in the code.
-   Could be simplified by using logical subscript instead of
    calling `which()`.

## `getAnnot()`<a id="orgheadline10"></a>

-   The user should not have to call `library(annotatr)`, as
    mentioned in the example
-   The implementation relies on about 1000 lines of code copied and
    modified from the annotatr package. Please work with the authors
    to support hg18. If they are not responsive, you are probably
    better off making use of or something AnnotationHub
    directly. Dropping this code would remove the direct dependency
    on readr and maybe other packages.
-   Is there a more reliable way to download files, so that there is
    no need to try 5 times? Maybe a data package, or AnnotationHub?

## `refineEdges()`<a id="orgheadline11"></a>

-   It looks like the body of this loop should just be wrapped into a
    function (potentially enclosed within `refineEdges()`) that takes
    `sig` as an argument. That affords the opportunity to make the
    intent of the code more obvious. This occurs in other functions,
    as well.
    ```
    for (ii in 1:2) {
         if (ii == 1) {
             sig <- 1
         } else {
             sig <- -1
         }
         ...
    }
    ```
-   Use `vapply()` over `sapply()`, and `lengths()` over `sapply(x,
         length)`; these recommendations apply throughout the code
-   The loops could probably be vectorized using (for example)
    compressed lists and IRanges, but that is optional if the current
    performance is OK

## `meanDiff()`<a id="orgheadline12"></a>

-   Here is an example of how you could vectorize these types of
    summary calculations. Here is some code from this function:
    
        meanDiff <- sapply(1:nrow(dmrs), function(x) {
            return(mean(rowMeans(prop.mat[(dmrs$indexStart[x]:dmrs$indexEnd[x]),
                                          which(design[, coeff] == levs[2])]) -
                        rowMeans(prop.mat[(dmrs$indexStart[x]:dmrs$indexEnd[x]), 
                                          which(design[, coeff] == levs[1])]),
                        na.rm = TRUE))
        })
    
    If the `indexStart` and `indexEnd` were folded into an IRanges
    called `indexRanges`, then you could do:
    
        prop.mat.dmr <- extractROWS(prop.mat, indexRanges)
        prop.mat1.means <- rowMeans(prop.mat.dmr[,design[, coeff] == levs[1]])
        prop.mat2.means <- rowMeans(prop.mat.dmr[,design[, coeff] == levs[2]])
        meanDiff <- mean(relist(prop.mat2.means - prop.mat1.means, indexRanges),
                         na.rm=TRUE)

## `regionScanner()`<a id="orgheadline13"></a>

-   This code:
    
        sapply(1:(sampleSize * 2),
               function(x) rep(x, length(ix)))
    
    Could become:
    
        rep(seq_len(sampleSize * 2), each=length(ix))
    
    And there is a similar example nearby. But since it looks like
    there is a matrix being converted to a long form data.frame, you
    could use `row()` and `col()` to generate those subscripts even
    more succinctly. Another option would be to convert to a
    data.frame and use `utils::stack()`.
-   I could be wrong, but I think, e.g.:
    
        melt(meth.mat[ix, ])$value
    
    is the same as:
    
        as.vector(meth.mat[ix, ])
-   The S4Vectors package defines useful `aggregate()` functionality,
    so you could convert this code:
    
        res <- data.frame(chr = sapply(Indexes, function(Index) chr[ind[Index[1]]]),
                          start = sapply(Indexes, function(Index) min(pos[ind[Index]])),
                          end = sapply(Indexes, 
                                       function(Index) max(pos[ind[Index]])), 
                          indexStart = sapply(Indexes, function(Index) min(ind[Index])), 
                          indexEnd = sapply(Indexes, function(Index) max(ind[Index])),
                          L = sapply(Indexes, 
                                     length),
                          area = sapply(Indexes, function(Index) abs(sum(x[ind[Index]]))), 
                          stringsAsFactors = FALSE)
    
    Into something like:
    
        df <- DataFrame(ind, chr = chr[ind], pos = pos[ind], x = x[ind])
        res <- aggregate(df, List(Indexes), chr = unlist(phead(chr, 1L)),
                         start = min(pos), end = max(pos),
                         indexStart = min(ind), indexEnd = max(ind),
                         L = lengths(chr), area = abs(sum(x)))

## `bumphunter.reduceIt()`<a id="orgheadline14"></a>

This is copy/pasted from bumphunter, which is not ideal, but
luckily none of the code seems to use it, so you could probably
delete it.

## `dmrPlotAnnotations()`<a id="orgheadline15"></a>

-   It should suffice to check that `annoTrack` is a
    *GenomicRangesList*, rather than checking each element. In
    general, I think you want a *SimpleGenomicRangesList* here, not a
    *GRangesList*, which has semantics particular to ranges with
    gaps.

## `.dmrPlotSmoothData()`<a id="orgheadline16"></a>

-   I'd recommend using `for()` instead of `sapply()` or any other
    functional iteration when the body causes side effects, like
    changes to the graphics device. Remember to use `seq_len(n)` not
    `1:n`.

## `plotDMRs()`<a id="orgheadline17"></a>

-   Condition throwing functions like `stop()`, `message()`, etc,
    already concatenate their arguments, so there is no need for
    `paste0()` in that context. This probably happens elsewhere.

## `plotEmpiricalDistribution()`<a id="orgheadline18"></a>

-   This code seems odd:
    
        if (!exists("time")) {
            time <- NULL
        } else if (is.null(time)) {
            time <- time
        }
    
    In what context might "time" not exist? The argument already
    defaults to `NULL`. The `else` argument does not any sense at
    all.
-   Use `is.function()` instead of comparing the `class()` to
    "function"
-   When could `time` and `time2` be functions anyway? Btw, it looks
    like the check for `time2` has a copy/paste error.
-   `c1` and `c2` are never used after being defined
-   Always use the scalar-wise, short-circuiting `&&()` instead of
    `&()` when testing conditions, such as the first arg to `if()`,
    as it is more explicit about the intent, and can be faster
-   Do not use `exist()` to determine whether a previous `if()` call
    did something or not. For example,
    
        if (length(grep("_", time)) < 0) {
            t1 <- strsplit(time, "_")[[1]][[2]]
            ...
        }
        if (exists("t1") & exists("t2")) {
            ...
        }
    
    Should instead be something like:
    
        t1_has_underscore <- any(grepl("_", time))
        if (t1_has_underscore) {
            t1 <- strsplit(time, "_")[[1]][[2]]
            ...
        }
        if (t1_has_underscore && t2_has_underscore) {
            ...
        }
-   This could probably use `utils::stack()` instead of `melt()`

**Comment by kdkorthauer** [comment]
Thank you for the review, @lawremi. This is extremely helpful and I will work on addressing all of these points. I'll let you know once I have done so.

Best,
Keegan

**Comment by kdkorthauer** [comment]
Hi @lawremi, 

Thanks again for your review. I have addressed each of the points you raised - see below for fully explanation (my responses are given in bold).

I'm working on fixing the Timeout issue in Windows. I'm not running into timeout
issues on OS X or Linux, but I'll try and reduce the examples. I'm also not familiar
with the PostProcessing checks, so if you have any suggestions on tracking down
those errors, I'd be grateful.

Best,
Keegan

# Overall

## DESCRIPTION

- Authors: totally up to you, but you might consider including
others involved in the work (e.g., the paper authors)

**Thanks for the suggestion; I have added the paper authors to the 
description file.**
  
  ## Vignette
  
  - There is a code comment that mentions hg19 but the code uses hg18.

**I have corrected the code comment to refer to the correct hg version.**
  
  ## API
  
  ### dmrseq()
  
  - Does the BPPARAM argument really only accept a SnowParam or
MulticoreParam? Ideally, it wouldn't care about the specific
implementation.

**No, you are correct. I have fixed the wording.**

- Why not drop the parallel argument and instead expect the user
to pass a SerialParam to disable parallelization? By default I
think BiocParallel just uses 2 cores, so it's probably safe to
parallelize by default.

**Agreed. I have dropped the parallel argument so that parallel is the 
default and serial implementation can be carried out through the BPPARAM
argument or by changing the default backend.**
  
  - What is the difference between passing sampleIndex or just
subsetting the input object for the samples of interest? It seems
like the latter would be more clear.

**Good point. I have removed the the argument sampleIndex.**
  
  - It seems like the return value should be a GRanges, with
indexStart and indexEnd folded into an IRanges and attached
as a metadata column, along with the other outputs.

**Great idea. I have changed the output format to be a GRanges object,
with the metadata columns containing an IRanges with the start and end
indices as well as the other inference outputs.**
  
  ### filterLoci()
  
  - Not sure this function is really needed, as it should be easy
enough for the user to filter by coverage directly

**I agree. I have decided to remove this function.**
  
  ### plotEmpiricalDistribution()
  
  - The user should probably be responsible for saving graphics
device output to a file, e.g., using dev.copy(), so this
function does not need to save any files.

**This function has been revamped to be more user friendly. Instead of plotting
a pdf with multiple pages, the user can specify which type of plot they would 
like and the function returns a single ggplot object with the plot. No 
graphics are saved.**
  
  ### simDMRs()
  
  - Similar to above, avoid having functions that both generate a
value, and cause side effects. The idea is to isolate side
effects, because they do not blend well with the functional
nature of R, but also there is a general desire for cohesion (a
                                                              module should have a single responsibility, at some level of
                                                              abstraction, deciding on the level is the hard part). More
cohesive modules are easier to reuse. They are also easier to
understand, because it forces the user to express themselves
(again, at the "right" level). Consider:
  
  simDMRs(file, bs=BS.chr21, num.dmrs=300)
It is not at all obvious what file means: is it an input or an
output? Instead, this is more obvious:
  
  save(simDRS(bs=BS.chr21, num.dmrs=300), file=file)

**The 'simfile' argument has been removed from the `simDMRs` function, so that
the function no longer produces side effects. The user can save the object
themself as you point out.**
  
  ## Code
  
  ### filterLoci()
  
  - It is almost never necessary to call rm() and gc(). If
memory is a problem, it is best to iterate. There are many
other places where this happens in the code.

**the rm() and gc() calls have been removed throughout the package code.**
  
  - Could be simplified by using logical subscript instead of
calling which().

**This function was removed since it was deemed unnecessary.**
  
  ### getAnnot()
  
  - The user should not have to call library(annotatr), as
mentioned in the example

**This is correct. I have removed the library call from the example.**
  
  - The implementation relies on about 1000 lines of code copied and
modified from the annotatr package. Please work with the authors
to support hg18. If they are not responsive, you are probably
better off making use of or something AnnotationHub
directly. Dropping this code would remove the direct dependency
on readr and maybe other packages.

**I reached out to the annotatr package authors regarding support of hg18, but
they do not wish to add this support.** **Instead of re-implementing everything
in annotatr just for the hg18 genome, I have greatly simplified the code by 
getting hg19 annotations from annotatr and lifting them over to hg18 using 
AnnotationHub.**
  
  - Is there a more reliable way to download files, so that there is
no need to try 5 times? Maybe a data package, or AnnotationHub?
  
  **The download retries are because annotatr directly downloads files for 
genome builds that aren't natively supported in AnnotationHub. 
They aren't necessary if using one of the supported genomes (the most 
                                                             common situation). I could get around this by doing something similar as for 
the hg18 situation and using AnnotationHub
and rtracklayer to liftOver to the unsupported genomes. If you think that is 
preferable, I'm happy to implement it.**

### refineEdges()

- It looks like the body of this loop should just be wrapped into a
function (potentially enclosed within refineEdges()) that takes
sig as an argument. That affords the opportunity to make the
intent of the code more obvious. This occurs in other functions,
as well.
for (ii in 1:2) {
if (ii == 1) {
sig <- 1
} else {
sig <- -1
}
...
}

**I have re-written this function to include functions instead of the
cryptic looping over ii and sig; the intention of the code is hopefully
much more obvious. The same issue was present with trimEdges, which I have
also remedied.**

- Use vapply() over sapply(), and lengths() over sapply(x, length); 
these recommendations apply throughout the code

**Throughout the package code, I have replaced all instances of 
sapply(x, length) with lengths().** **In addition, I have replaced all instances 
of sapply() with vapply() in the package code where possible.** **Where not possible
(i.e. variable-length returns), I have instead used lapply to avoid unexpected
surprises due to simplification.**

- The loops could probably be vectorized using (for example)
compressed lists and IRanges, but that is optional if the current
performance is OK

**Good to know. I tried thinking about how to vectorize it, using the example
you provided with meanDiff() below. Essentially the function looks within each
subset of indices (that define a region) and if it is longer and has edges with 
lower values than a certain cutoff, it will return a subset from the first 
index to the last index above the threshold. Since the subsetting is performed
on each region and not each individual index, I'm not sure how to vectorize 
it. This step doesn't present a bottleneck, so I'm not too
concerned about speeding it up, but at the same time I'd like my code to be
as fast as possible, so I'm happy to hear additional suggestions.**
  
  ### meanDiff()
  
  Here is an example of how you could vectorize these types of
summary calculations. Here is some code from this function:
  
  meanDiff <- sapply(1:nrow(dmrs), function(x) {
    return(mean(rowMeans(prop.mat[(dmrs$indexStart[x]:dmrs$indexEnd[x]),
                                  which(design[, coeff] == levs[2])]) -
                  rowMeans(prop.mat[(dmrs$indexStart[x]:dmrs$indexEnd[x]), 
                                    which(design[, coeff] == levs[1])]),
                na.rm = TRUE))
  })

If the indexStart and indexEnd were folded into an IRanges
called indexRanges, then you could do:
  
  prop.mat.dmr <- extractROWS(prop.mat, indexRanges)
prop.mat1.means <- rowMeans(prop.mat.dmr[,design[, coeff] == levs[1]])
prop.mat2.means <- rowMeans(prop.mat.dmr[,design[, coeff] == levs[2]])
meanDiff <- mean(relist(prop.mat2.means - prop.mat1.means, indexRanges),
                 na.rm=TRUE)

**Wow; on a simple example, the IRanges approach is 6x faster for this 
calculation. I have made this change to the meanDiff() function.**
  
  ### regionScanner()
  
  - This code:
  
  sapply(1:(sampleSize * 2),
         function(x) rep(x, length(ix)))
Could become:
  
  rep(seq_len(sampleSize * 2), each=length(ix))
And there is a similar example nearby. But since it looks like
there is a matrix being converted to a long form data.frame, you
could use row() and col() to generate those subscripts even
more succinctly. Another option would be to convert to a
data.frame and use utils::stack().

**I have replaced the sapply() calls with the rep() call as you suggest.**
  
  - I could be wrong, but I think, e.g.:
  
  melt(meth.mat[ix, ])$value
is the same as:
  
  as.vector(meth.mat[ix, ])

**You are correct; I have simplified the code.**
  
  - The S4Vectors package defines useful aggregate() functionality,
so you could convert this code:
  
  res <- data.frame(chr = sapply(Indexes, function(Index) chr[ind[Index[1]]]),
                    start = sapply(Indexes, function(Index) min(pos[ind[Index]])),
                    end = sapply(Indexes, 
                                 function(Index) max(pos[ind[Index]])), 
                    indexStart = sapply(Indexes, function(Index) min(ind[Index])), 
                    indexEnd = sapply(Indexes, function(Index) max(ind[Index])),
                    L = sapply(Indexes, 
                               length),
                    area = sapply(Indexes, function(Index) abs(sum(x[ind[Index]]))), 
                    stringsAsFactors = FALSE)
Into something like:
  
  df <- DataFrame(ind, chr = chr[ind], pos = pos[ind], x = x[ind])
res <- aggregate(df, List(Indexes), chr = unlist(phead(chr, 1L)),
                 start = min(pos), end = max(pos),
                 indexStart = min(ind), indexEnd = max(ind),
                 L = lengths(chr), area = abs(sum(x)))

**Nifty! I have replaced these lines with the more efficient S4Vectors code
you suggested.**
  
  ### bumphunter.reduceIt()
  
  This is copy/pasted from bumphunter, which is not ideal, but
luckily none of the code seems to use it, so you could probably
delete it.

**Good catch. I've removed this function since it's no longer needed.**
  
  ### dmrPlotAnnotations()
  
  It should suffice to check that annoTrack is a
GenomicRangesList, rather than checking each element. In
general, I think you want a SimpleGenomicRangesList here, not a
GRangesList, which has semantics particular to ranges with
gaps.

**I have changed from using a GRangesList to a SimpleGenomicRangesList 
for the annoTrack annotation element throughout.**
  
  ### .dmrPlotSmoothData()
  
  I'd recommend using for() instead of sapply() or any other
functional iteration when the body causes side effects, like
changes to the graphics device. Remember to use seq_len(n) not
1:n.

**I have changed the sapply() calls that cause a change to the graphics
device to use for() instead. I have also changed the indexing style to use
seq_len(n) instead of 1:n throughout the package.**

### plotDMRs()

- Condition throwing functions like stop(), message(), etc,
already concatenate their arguments, so there is no need for
paste0() in that context. This probably happens elsewhere.
plotEmpiricalDistribution()

**This is good to know! Saves a lot of typing! I've removed the 
unnecessary paste0() commands throughout the package code.**
  
  - This code seems odd:
  
  if (!exists("time")) {
    time <- NULL
  } else if (is.null(time)) {
    time <- time
  }
In what context might "time" not exist? The argument already
defaults to NULL. The else argument does not any sense at
all. Use is.function() instead of comparing the class() to
"function". When could time and time2 be functions anyway? Btw, it looks
like the check for time2 has a copy/paste error.
c1 and c2 are never used after being defined.

**These code chunks have all been removed as part of making the function
more user-friendly.**
  
  - Always use the scalar-wise, short-circuiting &&() instead of
&() when testing conditions, such as the first arg to if(),
as it is more explicit about the intent, and can be faster

**Good point; I have replaced & and | with && and || when testing conditions.**
  
  - Do not use exist() to determine whether a previous if() call
did something or not. For example,

if (length(grep("_", time)) < 0) {
  t1 <- strsplit(time, "_")[[1]][[2]]
  ...
}
if (exists("t1") & exists("t2")) {
  ...
}
Should instead be something like:
  
  t1_has_underscore <- any(grepl("_", time))
if (t1_has_underscore) {
  t1 <- strsplit(time, "_")[[1]][[2]]
  ...
}
if (t1_has_underscore && t2_has_underscore) {
  ...
}

**These code chunks have all been removed as part of making the function
more user-friendly.**
  
  - This could probably use utils::stack() instead of melt()

**I have replaced usages of melt() with utils::stack().**

**Comment by kdkorthauer** [comment]
Hi @lawremi,

Update: I resolved the issues with timeout and postprocessing; build is now passing. For a detailed explanations of changes made in response to review, see my previous comment (2/20/18). Thanks again!

Best,
Keegan

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kdkorthauer.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"dmrseq\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/dmrseq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
