### ISSUE TITLE
DelayedMatrixStats

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/Contributions#514]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PeteHaitch/DelayedMatrixStats

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by PeteHaitch** [comment]
Ah, bugger. I just remembered I'm depending on a version of **matrixStats** that isn't yet available on CRAN. I'll take another look at this tonight to see if I can get it working with the released version of **matrixStats**

**Comment by PeteHaitch** [comment]
Since this package interacts so closely with the **DelayedArray** package, I have some issues I would appreciate some advice on. See https://github.com/PeteHaitch/DelayedMatrixStats/labels/initial_release for the ones I think are pertinent for the initial release.
Thanks!

**Comment by lawremi** [comment]
I wonder if some or all of these could just be folded into the DelayedArray package itself? Seems problematic to have a `colSums()` and `colSums2()`.

**Comment by PeteHaitch** [comment]
I appreciate that concern. `matrixStats::colSums2()` has extra functionality over `base::colSums()`, behaviour which I'm (planning) to mimic with `colSums2()` in **DelayedMatrixStats`

``` r
library(matrixStats)

args(colSums)
#> function (x, na.rm = FALSE, dims = 1L) 
#> NULL

args(colSums2)
#> function (x, rows = NULL, cols = NULL, na.rm = FALSE, dim. = dim(x), 
#>     ...) 
#> NULL
```

**Comment by lawremi** [comment]
But what's the point of those arguments when you can just lazily subset the object?

**Comment by PeteHaitch** [comment]
> But what's the point of those arguments when you can just lazily subset the object?

Yes, that's what I mean by "this behaviour may not be achievable for all types of DelayedMatrix objects". However, by at least _offering_ `colSums2()` the same code will work for _matrix_ and _DelayedMatrix_ objects.

**Comment by lawremi** [comment]
I can sort of see the desire for compatibility with matrixStats. But why not give `colSums()` the same treatment as `colSums2()`? I think we really want people calling the standard function.

**Comment by PeteHaitch** [comment]
> But why not give colSums() the same treatment as colSums2()? I think we really want people calling the standard function.

So from my perspective the ultimate would be to have `base::colSums()` have the capabilities of `matrixStats::colSums2()`, but I suspect that's not what you mean :) And to clarify, `colSums()` does already exist in **DelayedArray** (and uses the block-processing strategy), but some of the tricks used in `colSums2()` could be brought over (e.g., 'seed-aware' methods).

Re your earlier comment, 

> I wonder if some or all of these could just be folded into the DelayedArray package itself?

Again, ultimately, that may be the right thing to do. Right now, at least for me, decoupling the two makes development a little easier

**Comment by lawremi** [comment]
Ok, cool, it would be great if DelayedArray could be optimized for the seeds that it knows about, and use whatever general tricks DelayedMatrixStats is using.

Totally agree that matrixStats should be folded into base R.

**Comment by PeteHaitch** [comment]
- Passing on veracruz1
- Error on tokay1 is `'BiocCheck' is not recognized as an internal or external command,
operable program or batch file.`
- Error on malbec1 is because R was not configured with memory-profiling enabled (this is used in vignette, I can disable or perhaps there is a clean way to skip this

**Comment by PeteHaitch** [comment]
- the remaining warning on tokay1, `package 'matrixStats' was built under R version 3.4.2`, concerns a dependency and not **DelayedMatrixStats**

**Comment by dvantwisk** [comment]
You're right.  We'll have a review to you soon.

**Comment by PeteHaitch** [comment]
Any updates on this, @dvantwisk ? I appreciate that there were many packages submitted just before the deadline and that you are all swamped with reviews.

My main question is probably for @hpages and/or @mtmorgan - would you be interested in folding this package directly into **DelayedArray**? I'm of course willing to do the grunt work and write up a pull request. Obviously, this now won't happen in time for the next BioC release, but I'd rather get this right, making it broadly useful to developers, than rushing it. Please let me know what you think of this idea or whether you think it is better to contribute + maintain as a separate package. Thanks!

**Comment by dvantwisk** [comment]
I am review it now, I will try to have something for you shortly.

**Comment by dvantwisk** [comment]
I am just finishing up looking through you R files.  The package looks expertly written and am just checking off on a few more things in your R code, to see if I have any issues with it at all.  The review below is for everything aside from the R code, I'll give you this first so you can correct these issues:

GENERAL:
- [REQUIRED] many files that don't appear to be needed are included
in the git repository.  The following files and directories in the main
directory of the package should be added to the `.gitignore` file:
  - `DelayedMatrixStats.Rproj`
  - `.travis.yml`
  - `buggy`
  - `codecov.yml`
  - `man-roxygen` appears to be unnecessary.  It seems all relevant man pages
are included in the `man` directory.

DESCRIPTION:
- [CONSIDER] License: just `MIT` is fine.

**Comment by PeteHaitch** [comment]
Thanks, @dvantwisk! 

Regarding those extra files:

1. `buggy` contains old code, which I have removed in be31f4e
2. `DelayedMatrixStats.Rproj`, `.travis.yml`, `codecov.yml` are files I use to integrate with RStudio, Travis CI, and CodeCov, respectively
3. `man-roxygen` is necessary to generate the `.Rd` files (it is used for 'templates' with **roxygen2**). It's not necessary to build the package on BioC servers, but is necessary for my local development of the package.

So I have deleted (1). However, if I add (2) and (3) to .gitignore then when I (or anyone else) clone the package from the BioC git server the package code will be incomplete for development purposes. What I would like is for these to be part of the git repository but not part of the R package, so my solution was to put them in `.Rbuildignore` but not in `.gitignore`. Is there a better way?

Regarding the license, I was following the advice from http://r-pkgs.had.co.nz/description.html . This seems to be used by other BioC packages with an MIT license (e.g., http://bioconductor.org/packages/ccrepe/ http://bioconductor.org/packages/LedPred/,  http://bioconductor.org/packages/isomiRs/)

Thanks,
Pete

**Comment by dvantwisk** [comment]
Okay, I see the rational so those files can stay out of `.gitignore`.  Aside from that, I can't find any issues with the R code.  I'm waiting for a supervisor to answer a question, but aside from that, I'm going to move to accept the package at the end of the day

**Comment by PeteHaitch** [comment]
Thanks for your review, @dvantwisk!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/PeteHaitch.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"DelayedMatrixStats\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DelayedMatrixStats

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
