### ISSUE TITLE
curatedTCGAData

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/Contributions#522]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/waldronlab/curatedTCGAData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Please fix the ERRORS and WARNINGS. 

When I try to run the code in the vignette with dry.run=FALSE I get the following ERROR: 
```
> temp = curatedTCGAData(diseaseCode = "COAD", assays = "RPPA*", dry.run = FALSE)
snapshotDate(): 2017-10-10
snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/639'
retrieving 1 resource
  |======================================================================| 100%

snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/628'
retrieving 1 resource
  |======================================================================| 100%

snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/631'
retrieving 1 resource
  |======================================================================| 100%

snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/640'
retrieving 1 resource
  |======================================================================| 100%

Error in (function (experiments = ExperimentList(), colData = S4Vectors::DataFrame(),  : 
  unused arguments (buildDate = 1506474096.88579, cancerCode = "COAD", runDate = "20160128", analyzeDate = "20160128", session_info.platform.version = "R Under development (unstable) (2017-04-12 r72509)", session_info.platform.system = "x86_64, linux-gnu", session_info.platform.ui = "X11", session_info.platform.language = "(EN)", session_info.platform.collate = "en_US.UTF-8", session_info.platform.tz = "posixrules", session_info.platform.date = "2017-09-26", session_info.packages.package1 = "AnnotationDbi", session_info.packages.package2 = "AnnotationForge", session_info.packages.package3 = "AnnotationHub", session_info.packages.package4 = "AnnotationHubData", session_info.packages.package5 = "assertthat", session_info.packages.package6 = "base", session_info.packages.package7 = "bindr", session_info.packages.package8 = "bindrcpp", session_info.packages.package9 = "Biobase", session_info.packages.package10 = "BiocGenerics", session_info.packages.package11 = "BiocInstaller", ses
```

And when I try to run the example call with dry.run=FALSE I get the following ERROR: 

```
> curatedTCGAData(diseaseCode = c("GBM", "ACC"), assays = "CNASNP", dry.run=FALSE)
snapshotDate(): 2017-10-10
snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/558'
retrieving 1 resource
  |======================================================================| 100%

snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/669'
retrieving 1 resource
  |======================================================================| 100%

Loading required package: RaggedExperiment
in method for 'coerce' with signature '"RangedRaggedAssay","RaggedExperiment"': no definition for class "RaggedExperiment"
snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/560'
retrieving 1 resource
  |======================================================================| 100%

snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/563'
retrieving 1 resource
  |======================================================================| 100%

snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/569'
retrieving 1 resource
  |======================================================================| 100%

snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/671'
retrieving 1 resource
  |======================================================================| 100%

snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/674'
retrieving 1 resource
  |======================================================================| 100%

snapshotDate(): 2017-10-10
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
downloading from 'https://experimenthub.bioconductor.org/fetch/685'
retrieving 1 resource
  |======================================================================| 100%

Error in data.frame(..., check.names = FALSE) : 
  row names contain missing values
```

Please investigate.

**Comment by lshep** [comment]
Hello 
- [ ] There are still ERROR and WARNING in the build report that should be taken care of.  
- [ ] I can run the example code in the man file. But I did notice a message that should be looked into when doing dry.run=FALSE: 
```
> temp = curatedTCGAData(diseaseCode = c("GBM", "ACC"), assays = "CNASNP", dry.run=FALSE)

loading from cache '/home/lori//.ExperimentHub/669'
Loading required package: RaggedExperiment
in method for 'coerce' with signature '"RangedRaggedAssay","RaggedExperiment"': no definition for class "RaggedExperiment"
```
- [ ] I still can't run the vignette code with dry.run=FALSE
```

> temp = curatedTCGAData(diseaseCode = "COAD", assays = "RPPA*", dry.run = FALSE)
snapshotDate(): 2017-10-12
snapshotDate(): 2017-10-12
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
loading from cache '/home/lori//.ExperimentHub/639'
snapshotDate(): 2017-10-12
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
loading from cache '/home/lori//.ExperimentHub/628'
snapshotDate(): 2017-10-12
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
loading from cache '/home/lori//.ExperimentHub/631'
snapshotDate(): 2017-10-12
see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
loading from cache '/home/lori//.ExperimentHub/640'
Error in (function (experiments = ExperimentList(), colData = S4Vectors::DataFrame(),  : 
  unused arguments (`COAD_colData-20160128` = <S4 object of class "DataFrame">, `COAD_metadata-20160128` = list(buildDate = 1506474096.88579, cancerCode = "COAD", runDate = "20160128", analyzeDate = "20160128", session_info = list(platform = list(version = "R Under development (unstable) (2017-04-12 r72509)", system = "x86_64, linux-gnu", ui = "X11", language = "(EN)", collate = "en_US.UTF-8", tz = "posixrules", date = "2017-09-26"), packages = list(package = c("AnnotationDbi", "AnnotationForge", "AnnotationHub", 
"AnnotationHubData", "assertthat", "base", "bindr", "bindrcpp", "Biobase", "BiocGenerics", "BiocInstaller", "BiocParallel", "biocViews", "biomaRt", "Biostrings", "bit", "bit64", "bitops", "blob", "cellranger", "compiler", "data.table", "datasets", "DBI", "DelayedArray", "devtools", "digest", "dplyr", "futile.logger", "futile.options", "GenomeInfoDb", "GenomeInfoDbData", "GenomicAlignments", "GenomicFeatures", "GenomicRanges", "GEOquery", "glue", "graph", "graphics", "
```

Please look into these and let me know when I should test again.

**Comment by lshep** [comment]
When I run the example in the man page with dry.run=FALSE I still get a message about
```
 Loading required package: RaggedExperiment
in method for 'coerce' with signature '"RangedRaggedAssay","RaggedExperiment"': no definition for class "RaggedExperiment"
```
This probably has more to do with RaggedExperiment than curatedTCGAData but wanted you to be aware. 

Also please be aware of the WARNING on malbec1 and veracruz1 concerning the manual generation - once the landing page is created you might want to check this to see if properly generated.

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 
Yes, this is a `RaggedExperiment` issue and it will be removed after the upcoming release
as a bug fix since `RaggedExperiment` will be removed.
Thanks,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LiNk-NY.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"curatedTCGAData\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/curatedTCGAData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
