### ISSUE TITLE
(inactive) biothings

### ISSUE THREAD

**Issue by thomascjohnson** [Bioconductor/Contributions#540]
@newgene :)

Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/biothings/biothings_client.R

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by newgene** [comment]
@bioc-issue-bot Will it work if we change our package name to "biothings_client" and the repo name is "biothings_client.R"? The reason we cannot just rename our repo as "biothings_client" is because we also have other "biothings_clients" in other languages, e.g. our "biothings_client.py" and "biothings_client.js" repos. Just naming the R client as "biothings_client" is not ideal for us. This is basically the same pattern for our other existing BioC package "mygene", whose repo is called "mygene.R".

**Comment by mtmorgan** [comment]
yes, that sounds fine.

**Comment by newgene** [comment]
@mtmorgan thanks! 

@thomascjohnson shall we update the DESCRIPTION and resubmit here? 

Also if we change the package name to "biothings_client", do we need to change "BioThings" function to "BioThingsClient", or have to be the same as the package name "biothings_client"? We should just follow whatever the BioC package conventions.

```
   library(biothings_client)
   mg = BioThingsClient('gene')
   btGet(mg, '1017')
```

**Comment by thomascjohnson** [comment]
This thread got buried under a bunch of others. I'll change the name to biothings_client for now but I'll hold off on renaming the class pending feedback from @mtmorgan

**Comment by thomascjohnson** [comment]
Update here: https://github.com/biothings/biothings_client.R/commit/67fa4916fceb54b30ac82d4a056a9e38873569aa

**Comment by mtmorgan** [comment]
I read this as six of one and half a dozen of the others. The Bioc naming convention would have package and class as CapitalCamelCase; your existing packages would suggest biothings_client.R / biocthings_client(), so you can either be consistent with Bioc or with biothings, really up to you.

**Comment by thomascjohnson** [comment]
Thanks for the feedback! @newgene How do you feel about renaming the repo biothings.R?

**Comment by newgene** [comment]
I'm certain we don't want to call the repo just "biothings.R". Since it's a BioC package, I like to follow the BioC convention. How about this:

```
   library(BioThingsClient)
   mg = BioThingsClient('gene')
   btGet(mg, '1017')
```

And I can rename repo to "BioThingsClient.R".

**Comment by thomascjohnson** [comment]
https://github.com/biothings/biothings_client.R/commit/7bb03a7d49a62cdad05b70c8013db66dfb525d79

**Comment by newgene** [comment]
Thanks @thomascjohnson , I have renamed the repo as "BioThingsClient.R":

https://github.com/biothings/BioThingsClient.R

I think we are ready to submit this package as a new issue now. (Cc'ing @mtmorgan @bioc-issue-bot to be sure)

**Comment by mtmorgan** [comment]
yes resubmit as new issue; the app that handles the build might fail (diff. repo / package name) but we'll work to override that.
