### ISSUE TITLE
drawProteins

### ISSUE THREAD

**Issue by brennanpincardiff** [Bioconductor/Contributions#541]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/brennanpincardiff/drawProteins

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
Probably should define a formal S4 class for the data returned from UniProt. Not clear there is a need for the "features" and data.frame representation, at least not exposed to the user. There is no reason to depend on magrittr. The user is free to use the pipe independent of the package implementation. To use it in an example, just put it in Suggests.

**Comment by brennanpincardiff** [comment]
Thanks Michael for your comments. 
In response to your comments, errors and warnings the following changes have been made:

1. Bioc-devel Subscription made although may require some admin to complete. 
2. Updated R version dependency from 3.3.2 to 3.4.
3. Removed magrittr from package - as you say not necessary. 

About the suggestion for a formal S4 class prevent exposure of the features to the user, I'm not sure about this at this point. The following reasons occur to me:
1. I think users may want to be able to see the features. The drawing functions don't and probably cannot cover all the possible features in Uniprot. As such, users would have the possibility of creating additional draw function or using ggplot to add extra details to the object. 
2. I'm planning a argument that would color the changes by expression values. This could be achieved by altering the dataframe structure, I believe. 
3. Some users may want to customise the order of the proteins. My thought is that a way to do this would be to alter the order within the dataframe. 

All that in mind, if you really think an S4 object is the best way forward, I can do it. 
As I said, thanks for your comment. It's really great to have feedback and you've made me think about the code in a very positive and productive way. 

Version bumped up to 0.99.1 so hopefully it will prompt a new build. 
Thanks, 
Paul

**Comment by brennanpincardiff** [comment]
Hi, 
   Only problem is: ERROR: Maintainer must subscribe to the bioc-devel mailing list.
   I have registered but awaiting approval from list maintainer. 
Best wishes, 
Paul

**Comment by mtmorgan** [comment]
Registration usually triggers an email verification; maybe it ended up in your spam folder?

**Comment by brennanpincardiff** [comment]
Registered brennanpincardiff@gmail.com at Bioc-devel so hopefully it will permit build.

**Comment by vobencha** [comment]
Before I do a full review, why aren't you using the UniProt.ws package to retrieve the data? Much of this seems to be reinventing the wheel ... ?

**Comment by brennanpincardiff** [comment]
That's a reasonable question. 
I chose to use the new API which returns the data in JSON format because I could understand it better and use it to create an R object that worked well with ggplot2 commands and facilitate the protein visualisation. 
Accessing UniProt is not the key advance of this package. The visualisation is the key advance.
If you prefer I can adapt the code in a way that works with UniProt.ws as well.  
Best wishes, Paul

**Comment by vobencha** [comment]
Yes, please do adapt the code to use UniProt.ws. I believe calls to select() return a data.frame which should be straightforward to move down the line to ggplot2. Thanks.

**Comment by brennanpincardiff** [comment]
Hi, so I have been looking at UniProt.ws and I really don't think it will return the protein features in a way that will allow them to be drawn. 

Here is a script that shows this:

```R
library(UniProt.ws)
## Make a UniProt.ws object
up <- UniProt.ws(taxId=9606)

# example keys as UniProt accession number
# columns will be "FEATURES"

# let's test for Rel A and p50

rel_prot <- c("Q04206", "P19838")
# this will be the keys

res <- select(up, keys = rel_prot,
  columns = c("FEATURES", "PHOSSITE",
    "UNIPROTKB", "DOMAIN", "DOMAINS"))

# features - all in one box with no mapping
res[1,2]
res[2,2]
# PHOSSITE returns a NA for Q04206 for both as well?
res[1,3]
# DOMAIN AND DOMAINS also blank...
```

This seems to reflect other peoples experiences and questions on [Bioconductor support](https://support.bioconductor.org/p/56824/)
and on [Biostars] (https://www.biostars.org/p/172085/#283814).

Thus using the UniProt API and writing new functions seems to be a good option but I welcome advice...
Best wishes, Paul

**Comment by vobencha** [comment]
Sorry for the delay - I'm looking into the shortcomings of UniProt and will get back to you.

**Comment by vobencha** [comment]
We're going to reassess UniProt.ws over the next few weeks. It may get a substantial rewrite so for the time being let's just continue this review without it.

You package currently has errors on R CMD check. When those are cleared up I'll do a full review.

**Comment by vobencha** [comment]
Looks like we still have this error:
```
* checking tests ...
  Running testthat.R [2s/3s]
 [2s/3s] ERROR
Running the tests in tests/testthat.R failed.
Last 13 lines of output:
  > 
  > test_check("drawProteins")
  1. Error: extract_transcripts (@test-extract_multiple_transcripts.R#16) --------
  object 'begin' not found
  1: drawProteins::extract_transcripts(five_rel_data) at testthat/test-extract_multiple_transcripts.R:16
  2: filter(data_s, begin < data_s[1, 4])
  
  [1] "Download has worked"
  [1] "An error has occured. Code: 400"
  testthat results ================================================================
  OK: 98 SKIPPED: 0 FAILED: 1
  1. Error: extract_transcripts (@test-extract_multiple_transcripts.R#16) 
  
  Error: testthat unit tests failed
```

**Comment by vobencha** [comment]
@brennanpincardiff , just to clarify, it looks like this error is in your court. Are you planing to fix or ... ?

**Comment by brennanpincardiff** [comment]
@vobencha 
Thanks for the message.
I introduced a change that caused the failed to build. 
However, I have now reverted to a version that should pass (passes Travis CI). The test seems very slow for some reason. I have created a devel branch on Github to introduce new functionality. 
For that reason, I would be grateful if we can continue with review. I would welcome feedback. 
Best wishes, 
Paul

**Comment by brennanpincardiff** [comment]
@vobencha Should be good to go for review now :-)
Best wishes, Paul

**Comment by vobencha** [comment]
Looks good. Just a couple of comments - 

1) LazyData: true 
Any particular reason why you're setting this to 'true'? I ask because we've seen this cause problems (long delays) when loading packages with substantial data. My recommendation would be to leave this as 'False'.

2)  Both httr and ggplot2 are imported in DESCRIPTION. They should be selectively or fully imported in the NAMESPACE.

Valerie

**Comment by brennanpincardiff** [comment]
@vobencha 
Happy New Year and thanks for your comments. 
I've addressed both of them, created a new version and it's been built with no errors or warnings. 
What's the next step?
Best wishes, 
Paul

**Comment by vobencha** [comment]
Looks good, thanks. Package is approved.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/brennanpincardiff.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"drawProteins\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/drawProteins

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
