### ISSUE TITLE
Key2Enrich

### ISSUE THREAD

**Issue by ppdragondw** [Bioconductor/Contributions#544]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ppdragondw/Key2Enrich

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please review the check boxes in the issue; your package fails to meet basic criteria such as appropriate version number (0.99.0) and active vignette (vignettes/*.Rmd, no processed files, no inst/doc). Also please write your vignette as though the package were available in Bioconductor -- devtools::load_all() is not appropriate.

Please consider whether packages belong in Depends: (essential for end-users to see these packages to use your package), Imports: (essential for your package to function, but not needed by the end user), and Suggests: (useful for your package under some circumstances, e.g., to process vignettes or examples).

There are many established gene set enrichment methods available in Bioconductor, please clarify in your Description: how yours differs from these. Consider also re-using existing infrastructure, in particular accepting SummarizedExperiment for expression values and GSEABase for gene set representation.

Once your package has been revised to meet the minimal requirements for Bioconductor, please post a short comment here; it will then be added to the review queue for formal technical review.

**Comment by ppdragondw** [comment]
Thanks so much for your reviewing.
1. We changed the version number and uploaded vignette file.
2. We corrected the package calling method in Description file.
3.  Key2Enrich is an all-in-one R package for gene set enrichment analysis. It combines the whole pipeline of enrichment analysis in one package, provides enrichment function and visualization methods, while it also maps and renders input sample data on relevant KEGG pathway graphs.  Currently, it support KEGG/Reactome/GO. We will support GO slim and biocarta shortly. And more databases and gene sets will be supported.  We provided Wiki on github for introduction.  The input data for enrichment analysis is gene ID list. So, our package does support SummarizedExperiment and GSEABase.

**Comment by Liubuntu** [comment]
Dear @ppdragondw, 

I am doing a quick review of you package now. 

## Please fix all `errors` and `WARNINGS` returned by the building report, these are the minimum requirement for the package acceptance. These include: 

### Add test functions. 
```  
Error: No tests found for Key2Enrich
  Execution halted
```
### Add `BiocView` terms, refer to the link in the report. 
```
* Checking biocViews...
* Checking that biocViews are present...
    * ERROR: No biocViews terms found.
See http://bioconductor.org/developers/how-to/biocViews/
```

### Please register the `bioc-devel` mailing list and support site, using the links below. These are the minimum requirement for the acceptance of your package. 

```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
    * ERROR: Maintainer must register at the support site; visit
      https://support.bioconductor.org/accounts/signup/ .
```
###. recheck your vignettes. 
```
Quitting from lines 20-26 (my-vignette.Rmd) 
Error: processing vignette 'my-vignette.Rmd' failed with diagnostics:
The given dataset:  mmusculus_gene_ensembl , is not valid.  Correct dataset names can be obtained with the listDatasets() function.
Execution halted
```

## Pay attention to the NOTE messages also, they are most probably goes to the formal review. For example:    

### please recheck your packages in `depends`, `Imports` again. You may want to import most of them, and only depend on `R (>= 3.4.2)`, some basic infrastructure packages like `S4Vectors (>= 0.15.3)`, `BiocGenerics` or any packages with functions that are exposed to end-users. Please keep them better to be 1-3, not exceeding 5. 
  
```
* checking package dependencies ... NOTE
  Depends: includes the non-default packages:
  'biomaRt' 'KEGGREST' 'png' 'XML' 'ggplot2' 'grid' 'colorspace'
  'gtable' 'clusterProfiler' 'ReactomePA' 'DOSE'
Adding so many packages to the search path is excessive and importing
selectively is preferable.
```
### check the undocumented arguments or any documented arguments that are not in \usage. 
```
* checking Rd \usage sections ... WARNING
Documented arguments not in \usage in documentation object 'Key2KEGGEnrich':
  'mapping'
Undocumented arguments in documentation object 'getAllTypesID'
  'inputIDType'
```

Please fix all the errors and warnings first, and seek to fix the NOTE messages. Once the build went through with no error, a formal review will be given. 

Thank you for your contribution to Bioconductor. 

Best, 
Qian

**Comment by lawremi** [comment]
Please explain how your package supports SummarizedExperiment and GSEABase.

**Comment by ppdragondw** [comment]
Thank you so much for your reviewing and suggestion.
1. We fix all errors and warning when running R CMD check.
2. For SummarizedExperiment and GSEABase support, our package is used for gene list enrichment analysis and pathway mapping. The input data is differentially expressed gene list with or without fold change value. As my understanding,  SummarizedExperiment and GSEABase are used to store matrices of experimental results, which are commonly produced by sequencing and microarray experiments. People need generate differential expressed gene (DEG) list from SummarizedExperiment and GSEABase class data and then they can perform gene enrichment analysis by KeyEnrich. People need tools to generate DEG list, such as DESeq2, limma.  Please let us know if it is fine or do we need integrate DEG generation steps into our package?

**Comment by lawremi** [comment]
GSEABase is all about representing gene lists. It might be that SE is not relevant; I haven't looked closely.

**Comment by Liubuntu** [comment]
Please fix this error following the links. 
```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```

**Comment by ppdragondw** [comment]
1. We fixed all errors and warning during check process.
2. I subscribe here: ”https://stat.ethz.ch/mailman/listinfo/bioc-devel“ several times with my email donny.dw@gmail.com. I did not receive any confirmation email. Is that OK?
3. The package supports GSEAbase now. We wrote a sample in vignette file.

Thanks.

**Comment by mtmorgan** [comment]
The confirming email seems to end up in spam mail boxes; can you check there?

**Comment by ppdragondw** [comment]
I found the confirmation letter and subscribed bioc-devel successfully. Thanks.

**Comment by ppdragondw** [comment]
Hi, could you please give us suggestion how to fix this warning?

Checking R Version dependency...
    * WARNING: Update R version dependency from 3.4 to 3.5.

 DESCRIPTION file:

```
Depends:
    KEGGREST,
    biomaRt,
    R (>= 3.4)
```

**Comment by Liubuntu** [comment]
Hi @ppdragondw, 

Thanks for fixing the building errors. An official review will be given before Wednesday EST. 
Qian

**Comment by Liubuntu** [comment]
Hi @ppdragondw ,

You package is generally very well written and the visualization looks nice. I may need a closer look at your vignette, but for now, please address the following issues:

## DESCRIPTION
- please mention the `LICENSE` file in your top folder in the License field of DESCRIPTION, and also stick with 1 specific version of GPL only. e.g., `License: GPL-3 | file LI\
CENSE`.
The following are suggested:
- Consider adding the relevant links to the Github repository, in DESCRIPTION field of `url:`, and `Bug Report:` which links to the package github folder and the issue under t\
he folder. Here is an example: https://github.com/zhengxwen/SeqArray/blob/master/DESCRIPTION
- Consider adding these biocViews when appropriate: Pathways, KEGG, ThirdPartyClient.
See http://bioconductor.org/developers/how-to/biocViews/

## NEWS file. 
Please consider adding a NEWS file in your top level folder, by including new features of your package for each version bump, so your package news will be included in Biocondu\
ctor release announcements.

## NAMESPACE
- looks good.

## Vignette
- Write code as you are the user who is using your package the first time in a non-preset environment. So please add the following in beginning of the vignette before library \
the package.  
```{r setup, eval=FALSE}
source("https://bioconductor.org/biocLite.R")
biocLite("Key2Enrich")
```
- The assigning symbol "<-" should have white space before and after it.
```                                                                                                                                                                             
inputSample<-as.data.frame(inputSample)  ## yours                   
inputSample <- as.data.frame(inputSample) ## correct                                                                           
```                                                                                                                                                                             

## man
The manuals look good!

## R
The R code generally looks really good, written in a tidy way. Just several minor issues:
- Use `seq_len()` instead of `1:length()` in for loops, e.g., In the function of `parseList2Dataframe`, `1:length(nodeList)`. Generalize to other for loops.
- Rewrite all assigning symbol "<-" to have white space before and after it (" <- ").
- Remove commented code in your scripts.

Remember to make a version bump before any valid push to trigger the build. Thanks!

Cheers, 
Qian

**Comment by Liubuntu** [comment]
HI, 

It has been almost 3 weeks since the last review. We usually have a rule of 2 weeks notice. Please make efforts to address all/some of the issues above. If no response before this Friday, this issue will be closed. 

Most of the issues are just cosmetics and the package is close to acceptance. Please address them ASAP. 

Qian

**Comment by Liubuntu** [comment]
HI @ppdragondw ,

Since there was no response or showing effort in addressing the review issues, I will close this issue for now. You can submit it again by creating a new issue when you are ready with it. Thanks again for your contribution. 

Best, 
Qian
