### ISSUE TITLE
Numero

### ISSUE THREAD

**Issue by smm52** [Bioconductor/Contributions#546]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sahmri-molar/Numero

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by smm52** [comment]
Hi,

the only error was that the maintainer was not subscribed to the bioc-devel mailing list. This has now been fixed. 

As this wasn't a source code error, do I still need to bump the version number in the repository or is it possible for you to re-run the automated single package builder without the version number bump?

Thanks for your help,
Stefan

**Comment by lawremi** [comment]
The vignette says:

> there is nothing in the R package that is specifically aimed at biology

So why submit it to Bioconductor?

**Comment by smm52** [comment]
Hi Michael,

Thank you for your feedback. 

We have amended the statement in the vignette into “Although we have previously used the framework for metabolomics and biomedical data analysis, the functionality is not restricted to biological applications but the method can also be applied to any complex dataset.” Please note that just because we made the extra effort to make the package generally applicable does not in any way diminish its usefulness in biological applications.

I have updated the vignette and the version number on master branch. Thus, my previous comment regarding rebuilding the package without a version bump is no longer applicable.

Cheers,
Stefan

**Comment by lawremi** [comment]
Bioconductor is not just a repository for biology-related packages. It's a platform of interoperating packages, all based on standard data structures, mostly oriented around high-throughput data. It doesn't look like this package extends that platform in any way. Would it make sense for this to accept a SummarizedExperiment?

**Comment by smm52** [comment]
Hi Michael,

Thanks for your suggestion. 

We had an extensive discussion on including a package such as SummarizedExperiment. The aim of our software package is to provide a sleek, easy to use solution to biomedical subgrouping. Therefore, the input data is read in from a spreadsheet into a standard R matrix. We do not see that adding support for SummarizedExperiment fits well with the above aim.

It will be unfortunate if this prevents our package from being part of Bioconductor, but we do understand your goal of standardising data formats and apologise for the inconvenience from an unsuccessful submission.

Cheers,
Stefan

**Comment by mtmorgan** [comment]
I enjoyed your talk today at BiocAsia and really appreciate the extensive vignette and amount of work that went into this well-crafted package. I agree with Michael's general point that the fit with Bioconductor's emphasis on high-throughput genomic data is not that strong. I think this also contributes to the challenges of integrating with existing Bioconductor infrastructure. I'll close this issue, but read this as by mutual consent; if you feel strongly otherwise then please let me know.

**Comment by smm52** [comment]
Thanks Martin for your comments and feedback regarding the package and the presentation at BiocAsia today. 

We agree with your comments regarding the closure of this issue. Software development and publication is a journey and we are learning along the way where our software package best fits in. 

Unfortunately, due to international travel, I missed the meeting today, but I enjoyed the masterclass yesterday.

Cheers,
Stefan
