### ISSUE TITLE
pace

### ISSUE THREAD

**Issue by MalgorzataOles** [Bioconductor/Contributions#551]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MalgorzataOles/pace

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

**Comment by MalgorzataOles** [comment]
Package build fails because SPB does not run [R 3.5 recommended](http://bioconductor.org/developers/package-guidelines/#version) for new package submissions.

**Comment by lshep** [comment]
I'm sorry for the confusion. The single package builders have not been updated for the release yet - they will be updated within the next few days.

**Comment by aoles** [comment]
Seems that the "maximal number of DLLs reached" error is haunting us again. This should be [resolved after the update to R-devel](https://stat.ethz.ch/pipermail/bioc-devel/2017-October/011949.html), though.

**Comment by mtmorgan** [comment]
I think for a single package to trigger this is very disconcerting, it implies a very large number of dependencies hence exposure to changes or bugs in each; this seems like a very fragile situation. I'd encourage the package contributor to carefully evaluate each dependency for the functionality it provides, choosing to limit marginally relevant features or finding alternative implementations of necessary functionality in a smaller subset of packages.

**Comment by MalgorzataOles** [comment]
This is an ExperimentData package as indicated in the biocViews DESCRIPTION field. It contains a complete analysis for the associated paper, therefore the vignette build time is long (> 1 hour). The package contributor kindly asks Bioconductor to grant it more time to complete.

**Comment by lshep** [comment]
Packages are generally expected to meet the [package guidelines](http://bioconductor.org/developers/package-guidelines/) which require a check time in < 5 min so 10 is already double this allotted amount;  there are exceptions in the case of workflows and some experiment packages but this is decided on a per package basis.  I will let your assigned reviewer @hpages respond further on his thoughts concerning this.

**Comment by wolfganghuber** [comment]
Gosia, since this is a data package, I wonder whether we shouldn't use a more specific name than "pace". Perhaps something like
                         **CLLDrugResponses2017** ?

**Comment by MalgorzataOles** [comment]
The package has been renamed to BloodCancerMultiOmics2017 and resubmitted as a new issue.
