### ISSUE TITLE
ChIPSeqSpike: ChIP-Seq data scaling according to spike-in control

### ISSUE THREAD

**Issue by descostesn** [Bioconductor/Contributions#555]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/descostesn/ChIPSeqSpike

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
# ChipSeqSpike Review

## Build and Install

R CMD build: ok

R CMD INSTALL: ok

## DESCRIPTION

* Needs more Description. Think of the Description section as an "abstract" for a paper.

## NAMESPACE

* ok (hand written)

## man

* ok.

## vignettes

* Good vignette.

## R

* Use `seq_len` instead of `1:length`, `1:nrow()` or `1:ncol()`

        constructors.R: 78:

        names(list_dataset) <- paste0("dataset", 1:length(list_dataset));

  Do this everywhere if you have used the same code.

* Make these, `stop` instead of being `warning` and `return`.
  constructor.R (mutiple locations)

        warning("Scaling factors and counts should be numeric.");
        return(NA);


* Use `lapply` instead of `sapply` that way, you don't have to worry about
  allocating a empty list `setArray_list`. 


		.retrieveAverageValuesList <- function(files_vec, gff_vec, genome, binsize, 
			before, after, mean_or_median, interpolation_average, verbose){

		location_type_vec <- c("pf", "mf", "ef", "af");

		lapply(location_type_vec, function(location_name, files, gff_vec,
						genome_version, bin_size, profile_length_before, 
						profile_length_after, mean_or_median){
						
                
                if(verbose)
                    message("Extraction at ", location_name)
                getPlotSetArray(tracks = files, 
                                features = gff_vec, 
                                refgenome = genome_version, 
                                bin = bin_size, 
                                xmin = profile_length_before, 
                                xmax = profile_length_after, 
                                xanchored = interpolation_average,
                                type = location_name, 
                                add_heatmap = TRUE, 
                                stat = mean_or_median)
              
            }, files_vec, gff_vec, genome, binsize, before, after, 
            mean_or_median))
		}



  Do the same thing for `mat_list` on line 43. Remove `invisible`, it doesn't seem necessary.


*  You seem to use `<<-` in your lapply statement in `inputSubtraction-methods.R: l 39`. You can avoid using `<<-` if you just use a for loop there instead.

		score(exp_bigWig_file[which(chrom_exp == chrom)]
			)[which(scores_exp >= 0)]<<- result_scores;

   It is bad practice to update an object outside the scope using `<<-`.

* You don't need `stop` and `paste0`. `stop` will concatenate as well.

		stop(paste0("Input subtraction should be performed before ",
                            "reverting RPM normalization"));


* In `sapply(..., simplify=TRUE)` simplify=TRUE is the default. Instead, just use `vapply`. It improves your code.

`vapply` does two things:

Slight speed improvement

Improves consistency by providing limited return type checks.


	 AllClasses.R
	 47:            else if(!all(sapply(object@datasetList, function(x)
	 72:            else if(!all(sapply(object@experimentList, function(x)
	 96:            else if(!all(sapply(object@datasetList, function(x)
	 123:            else if(!all(sapply(object@experimentListLoaded, function(x)
	 198:        if(!all(sapply(value, function(x)inherits(x, "PlotSetArray"))))
	 206:        if(!all(sapply(value, function(x) inherits(x, "matrix"))))

	 extractBinding-methods.R
	 7:    invisible(sapply(location_type_vec, function(location_name, files, gff_vec,
	 173:            if(!unique(sapply(files_vec, file.exists, simplify = TRUE)))

	 plot-methods.R
	 321:                                            return(unlist(sapply(ind,
	 390:                                                             sapply(1:exp_nb,
	 685:                                return(unlist(sapply(ind,
	 755:                                                sapply(1:exp_nb,




* Use the accessor methods or functions already written, to access `theObject@datasetList` in
  extractBinding-methods.R: l199. Try not to use `@` in functions and methods and class definitions. If the accessor doesn't exisit you might want to consider implementing them.

Correct these issues in the following files as well.


	 estimateScalingFactors-methods.R
	 88:                    theObject@experimentList <-
	 89:                            lapply(theObject@experimentList,
	 125:            theObject@experimentListLoaded <-
	 126:                    lapply(theObject@experimentListLoaded,
	 144:    object@datasetList <- lapply(object@datasetList,


	 extractBinding-methods.R
	 136:            files_vec <- .retrieveAllFiles(theObject@experimentList);
	 170:            files_vec <- unlist(lapply(theObject@experimentListLoaded,
	 199:    theObject@datasetList <- lapply(theObject@datasetList,


	 inputSubtraction-methods.R
	 61:            theObject@experimentListLoaded <- lapply(
	 62:                    theObject@experimentListLoaded, function(exp, input){
	 105:   theObject@experimentList <- lapply(
	 106:           theObject@experimentList, function(exp, input){
	 139:    theObject@datasetList <- lapply(theObject@datasetList,

	 plot-methods.R
	 39:            mat_mean_list <- lapply(theObject@experimentList, function(exp){
	 114:            mat_mean_list <- lapply(theObject@experimentListLoaded,
	 244:            experiment_number <- length(theObject@experimentListLoaded);
	 245:            expNamesVec <- unlist(lapply(theObject@experimentListLoaded,
	 268:            expNamesVec <- unlist(lapply(theObject@experimentList, getExpName),
	 290:            list_arrayList <- lapply(theObject@datasetList, function(object){
	 294:            expNamesVec <- as.character(unlist(lapply(theObject@datasetList,
	 368:            list_arrayList <- lapply(theObject@datasetList, function(object){
	 372:            expNamesVec <- as.character(unlist(lapply(theObject@datasetList,
	 449:            expNamesVec <- unlist(lapply(theObject@experimentList, getExpName),
	 493:            nb_element <- length(theObject@datasetList);
	 496:            invisible(lapply(theObject@datasetList, function(dataset){
	 577:            expNames_vec <- unlist(lapply(theObject@experimentList,
	 632:            expNames_vec <- unlist(lapply(theObject@experimentListLoaded,
	 671:            list_arrayList <- lapply(theObject@datasetList, function(object){
	 691:            expNames_vec <- as.character(unlist(lapply(theObject@datasetList,
	 743:            list_arrayList <- lapply(theObject@datasetList, function(object){
	 761:            expNames_vec <- as.character(unlist(lapply(theObject@datasetList,
	 959:            input_mat_list <- lapply(theObject@datasetList,
	 995:            list_matBindingValues_list <- lapply(theObject@datasetList,
	 1225:            input_mat_list <- lapply(theObject@datasetList,
	 1264:            input_mat_list <- lapply(theObject@datasetList,

This is not a complete list. Do this everywhere.

* You have ";" (semi-colons) in your code. R does not need semi-colons.

* In AllGenerics.R:

		setGeneric(
        
        name = "boxplotSpike",
        
        def = function(theObject, col = NULL, rawFile = FALSE, rpmFile = FALSE,
                bgsubFile = FALSE, revFile = FALSE, spiked = TRUE, ylab = NULL,
                outline = TRUE, violinPlot = FALSE, notch = TRUE, 
                mean_with_sd = FALSE, mean = FALSE, median = FALSE, 
                boxplot = FALSE, jitter = FALSE, plot = TRUE, verbose = FALSE){
            
            standardGeneric("boxplotSpike");
        });
		
 
  instead ,
  
		setGeneric(
        name = "boxplotSpike",
        def = function(theObject, col = NULL, rawFile = FALSE,
			           rpmFile = FALSE, bgsubFile = FALSE, revFile = FALSE,
			           spiked = TRUE, ylab = NULL,
                       outline = TRUE, violinPlot = FALSE, notch = TRUE, 
                       mean_with_sd = FALSE, mean = FALSE, median = FALSE, 
                       boxplot = FALSE, jitter = FALSE, plot = TRUE,
					   verbose = FALSE){
             standardGeneric("boxplotSpike")
        },
		signature = "theObject"
		)

* I recommend re-formatting your code. Try to use "formatR" package, to check how to format it.

**Comment by descostesn** [comment]
Thank you so much for your nice work! I am starting addressing your comments asap.

**Comment by descostesn** [comment]
# Reply to review

>ChipSeqSpike Review
>Build and Install
>R CMD build: ok
>R CMD INSTALL: ok
>DESCRIPTION
>Needs more Description. Think of the Description section as an "abstract" for a paper.

**A more exhaustive description of the package is now provided.**

> NAMESPACE: ok
> man: ok.
> vignettes: Good vignette.

>R
>Use seq_len instead of 1:length, 1:nrow() or 1:ncol()
>constructors.R: 78:
>names(list_dataset) <- paste0("dataset", 1:length(list_dataset));
>Do this everywhere if you have used the same code.

**Corrected:**

-  constructors.R line 78: names(list_dataset) <- paste0("dataset", seq_len(length(list_dataset)))
- plot-methods.R line 390: sapply(seq_len(exp_nb),
- plot-methods.R line 446: list_indexes <- split(seq_len(arrayList[[1]]$ntracks()),
- plot-methods.R line 447: rep(seq_len(experiment_number), each = 5))
- plot-methods.R line 755: sapply(seq_len(exp_nb),
- plot-methods.R line 1069: mat_comb <- combn(seq_len(ncol(input_mat)), 2)
- matBindingValues.Rd line 62: new_list <- list(matrix(seq_len(10)), matrix(2:18))

> Make these, stop instead of being warning and return.
> constructor.R (mutiple locations)
> warning("Scaling factors and counts should be numeric.");
>return(NA);

**Done**

- constructors.R line 248: stop("endogenousBamFilePath should be a string.");
- constructors.R line 252: stop("exogenousBamFilePath should be a string.");
- constructors.R line 256: stop("bigWigFilePath should be a string.");
- constructors.R line 261: stop("name should be an alphanumeric.");
- constructors.R line 266: stop("Scaling factors and counts should be numeric.");

>Use lapply instead of sapply that way, you don't have to worry about
>        allocating a empty list setArray_list.
>        .retrieveAverageValuesList <- function(files_vec, gff_vec, genome, binsize, 
>        before, after, mean_or_median, interpolation_average, verbose){
>        
>        location_type_vec <- c("pf", "mf", "ef", "af");
>        
>        lapply(location_type_vec, function(location_name, files, gff_vec,
>        genome_version, bin_size, profile_length_before, 
>        profile_length_after, mean_or_median){
>        
>        
>        if(verbose)
>        message("Extraction at ", location_name)
>        getPlotSetArray(tracks = files, 
>        features = gff_vec, 
>        refgenome = genome_version, 
>        bin = bin_size, 
>        xmin = profile_length_before, 
>        xmax = profile_length_after, 
>        xanchored = interpolation_average,
>        type = location_name, 
>        add_heatmap = TRUE, 
>        stat = mean_or_median)
>        
>        }, files_vec, gff_vec, genome, binsize, before, after, 
>        mean_or_median))
>        }

**Done.** I kept the line returning the setArray_list to be able to attributes the location names to each element. I also removed 'invisible'

> Do the same thing for mat_list on line 43. Remove invisible, it doesn't seem necessary.

**Done.**

> You seem to use <<- in your lapply statement in inputSubtraction-methods.R: l 39. You can avoid using <<- if you just use a for loop there instead.
>score(exp_bigWig_file[which(chrom_exp == chrom)]
>)[which(scores_exp >= 0)]<<- result_scores;
>It is bad practice to update an object outside the scope using <<-.

**Done.**

>Also change <<- and the declaration of empty list in the following parts:

**Done: see details within functions.**

- plot-methods.R line 147: .plotAverageProfiles <- function(legends, arrayList, indexes_track, title_vec, colVec)
- plot-methods.R line 281: setMethod(f = "plotProfile", signature = "ChIPSeqSpikeDatasetList",
- plot-methods.R line 357: setMethod(f = "plotProfile", signature = "ChIPSeqSpikeDatasetListBoost",
- plot-methods.R line 425: setMethod(f = "plotTransform", signature = "ChIPSeqSpikeDataset",
- plot-methods.R line 476: setMethod(f = "plotTransform", signature = "ChIPSeqSpikeDatasetList",
- plot-methods.R line 804-816: .perform_boxplot_violinplot <- function(input_matrix, [...], plot){
- plot-methods.R 1088-1123: .perform_heatscatterplot <- function(input_mat, [...], color_contour, ...)



>You don't need stop and paste0. stop will concatenate as well.
>stop(paste0("Input subtraction should be performed before ",
>"reverting RPM normalization"));

**Done.** Line 27 and 32 of scaling-methods.R

>In sapply(..., simplify=TRUE) simplify=TRUE is the default.

**Done.** extractBinding-methods.R line 172

>  Instead, just use vapply. It improves your code.
>vapply does two things:
>Slight speed improvement
>Improves consistency by providing limited return type checks.
AllClasses.R
>        47:            else if(!all(sapply(object@datasetList, function(x)

**Done.** else if(!all(vapply(object@datasetList, function(x) inherits(x, "ChIPSeqSpikeDataset"), logical(1))

>        72:            else if(!all(sapply(object@experimentList, function(x)

**Done.**  

`else if(!all(vapply(object@experimentList, function(x) inherits(x, "Experiment"), logical(1))))`

>        96:            else if(!all(sapply(object@datasetList, function(x)

**Done.**

`else if(!all(vapply(object@datasetList, function(x) inherits(x, "ChIPSeqSpikeDatasetBoost"), logical(1))))`

>        123:            else if(!all(sapply(object@experimentListLoaded, function(x)

**Done.**

`else if(!all(vapply(object@experimentListLoaded, function(x) inherits(x, "ExperimentLoaded"), logical(1))))`

>        198:        if(!all(sapply(value, function(x)inherits(x, "PlotSetArray"))))

**Done.**

`if(!all(vapply(value, function(x)inherits(x, "PlotSetArray"), logical(1))))`

>        206:        if(!all(sapply(value, function(x) inherits(x, "matrix"))))

**Done.**

`if(!all(vapply(value, function(x) inherits(x, "matrix"), logical(1))))`
        
>extractBinding-methods.R
>        7:    invisible(sapply(location_type_vec, function(location_name, files, gff_vec,

**Replaced by lapply accordingly to previous suggestion.**

>        173:            if(!unique(sapply(files_vec, file.exists, simplify = TRUE)))

**Done.**

` if(!unique(vapply(files_vec, file.exists, logical(1))))`
        
>plot-methods.R
>        321:                                            return(unlist(sapply(ind,

**Done.**

`unlist(vapply(ind, function(x) list(dataset[[x]]), c(new("PlotSetPair")))`

>        390:                                                             sapply(1:exp_nb,

**Done.**

`unlist(vapply(seq_len(exp_nb), function(x) list(dataset[[x]]), c(new("PlotSetPair"))))`

>        685:                                return(unlist(sapply(ind,

**Done.**

`return(unlist(vapply(ind, function(x) list(dataset[[x]]),c(new("PlotSetPair")))))`

>        755:                                                sapply(1:exp_nb,

**Done.**

`return(unlist( vapply(seq_len(exp_nb), function(x) list(dataset[[x]]), c(new("PlotSetPair")))))`

       
>Use the accessor methods or functions already written, to access theObject@datasetList in
>extractBinding-methods.R: l199. Try not to use @ in functions and methods and class definitions. If the accessor doesn't exisit you might want to consider implementing them.

**Done.**

- AllGenerics.R line 147: add setGeneric(name = "getDatasetList", def = function(theObject){standardGeneric("getDatasetList");});
- accesssor-methods.R line 508-529: add accessor getDatasetList for signature ChIPSeqSpikeDatasetList and ChIPSeqSpikeDatasetListBoost
- NAMESPACE line 28: add getDatasetList
- add a getDatasetList.Rd file to man
- AllGenerics.R line 242: add setter datasetList<-
- replace-methods.R line 349-380: add setter datasetList for signatures ChIPSeqSpikeDatasetList and ChIPSeqSpikeDatasetListBoost
- NAMESPACE line 31: add "datasetList<-"
- add a datasetList.Rd file to man
- extractBinding-methods.R line 198: theObject@datasetList <- lapply(theObject@datasetList to datasetList(theObject) <- lapply(getDatasetList(theObject)  

> Correct these issues in the following files as well.
>estimateScalingFactors-methods.R
>        88:                    theObject@experimentList <-
>        89:                            lapply(theObject@experimentList,

**Done.**

- rename getExperimentList to getExperimentListBigWigs: 

               * accessor-methods.R line 164 and 179
               * AllGenerics.R line 39 and 43
               * ChIPSeqSpikeDataset-class.Rd line 66
               * ChIPSeqSpikeDatasetBoost-class.Rd line 69
               * rename getExperimentList.Rd to getExperimentListBigWigs.Rd and change documentation accordingly
               * test-getters.R line 77 and 90
               * NAMESPACE line 24 
               
- AllGenerics.R line 157: declare new generic getExperimentList
- accessor-methods line 532-553: declare getExperimentList method for signatures ChIPSeqSpikeDataset and ChIPSeqSpikeDatasetBoost
- NAMESPACE line 28: add getExperimentList
- add a getExperimentList.Rd file to man
- AllGenerics.R line 262: add "experimentList<-" generic
- replace-methods line 258 and 363: add setter experimentList for signatures ChIPSeqSpikeDataset and ChIPSeqSpikeDatasetBoost
- NAMESPACE line 31: add "experimentList<-"
- add a experimentList.Rd file to man
- estimateScalingFactors-methods.R line 88: experimentList(theObject) <- lapply(getExperimentList(theObject)



>              125:            theObject@experimentListLoaded <-
>              126:                    lapply(theObject@experimentListLoaded,

**Done.**

`experimentList(theObject) <- lapply(getExperimentList(theObject)`

>              144:    object@datasetList <- lapply(object@datasetList,

**Done.** 

`datasetList(object) <- lapply(getDatasetList(object)`
                                        
> extractBinding-methods.R
> 136:            files_vec <- .retrieveAllFiles(theObject@experimentList);

**Done.**
`files_vec <- .retrieveAllFiles(getExperimentList(theObject));`

> 170:            files_vec <- unlist(lapply(theObject@experimentListLoaded,

**Done.**
`files_vec <- unlist(lapply(getExperimentList(theObject),`

>                199:    theObject@datasetList <- lapply(theObject@datasetList,

**Done.**
`datasetList(theObject) <- lapply(getDatasetList(theObject)`
                        
> inputSubtraction-methods.R
> 61:            theObject@experimentListLoaded <- lapply(
> 62:                    theObject@experimentListLoaded, function(exp, input){

**Done.** 
`experimentList(theObject) <- lapply(getExperimentList(theObject), function(exp, input)`

>            105:   theObject@experimentList <- lapply(
>                    106:           theObject@experimentList, function(exp, input){

**Done.**
`experimentList(theObject) <- lapply(getExperimentList(theObject)`

>            139:    theObject@datasetList <- lapply(theObject@datasetList,

**Done.**
`datasetList(theObject) <- lapply(getDatasetList(theObject),`
                                
> plot-methods.R
>            39:            mat_mean_list <- lapply(theObject@experimentList, function(exp){

**Done.**
`mat_mean_list <- lapply(getExperimentList(theObject),`

>        114:            mat_mean_list <- lapply(theObject@experimentListLoaded,

**Done.**
`mat_mean_list <- lapply(getExperimentList(theObject),`

>        244:            experiment_number <- length(theObject@experimentListLoaded);
>        245:            expNamesVec <- unlist(lapply(theObject@experimentListLoaded,

**Done.**
`experiment_number <- length(getExperimentList(theObject));
            expNamesVec <- unlist(lapply(getExperimentList(theObject), `

>        268:            expNamesVec <- unlist(lapply(theObject@experimentList, getExpName),

**Done.**
`expNamesVec <- unlist(lapply(getExperimentList(theObject),`

>        290:            list_arrayList <- lapply(theObject@datasetList, function(object){

**Done.**
`list_arrayList <- lapply(getDatasetList(theObject),`

>        294:            expNamesVec <- as.character(unlist(lapply(theObject@datasetList,

**Done.**
`expNamesVec <- as.character(unlist(lapply(getDatasetList(theObject),`

>        368:            list_arrayList <- lapply(theObject@datasetList, function(object){

**Done.**
`list_arrayList <- lapply(getDatasetList(theObject),`

>        372:            expNamesVec <- as.character(unlist(lapply(theObject@datasetList,

**Done.**
`expNamesVec <- as.character(unlist(lapply(getDatasetList(theObject), getExpName)));`

>        449:            expNamesVec <- unlist(lapply(theObject@experimentList, getExpName),

**Done.**
`expNamesVec <- unlist(lapply(getExperimentList(theObject),`

>        493:            nb_element <- length(theObject@datasetList);

**Done.**
`nb_element <- length(getDatasetList(theObject));`

ADD: 494: count_vec <- seq_len(length(theObject@datasetList));
Done. count_vec <- seq_len(length(getDatasetList(theObject)));

>        496:            invisible(lapply(theObject@datasetList, function(dataset){

**Done**
`. }, getDatasetList(theObject), count_vec));`

>        577:            expNames_vec <- unlist(lapply(theObject@experimentList,

**Done**
` expNames_vec <- unlist(lapply(getExperimentList(theObject),`

>        632:            expNames_vec <- unlist(lapply(theObject@experimentListLoaded,

**Done**
`expNames_vec <- unlist(lapply(getExperimentList(theObject),`

>        671:            list_arrayList <- lapply(theObject@datasetList, function(object){

**Done**
`list_arrayList <- lapply(getDatasetList(theObject),`

>        691:            expNames_vec <- as.character(unlist(lapply(theObject@datasetList,

**Done**
`expNames_vec <- as.character(unlist(lapply(getDatasetList(theObject), getExpName)));`

>        743:            list_arrayList <- lapply(theObject@datasetList, function(object){

**Done**
`list_arrayList <- lapply(getDatasetList(theObject),`

>        761:            expNames_vec <- as.character(unlist(lapply(theObject@datasetList,

**Done**
`expNames_vec <- as.character(unlist(lapply(getDatasetList(theObject), getExpName)));`

>        959:            input_mat_list <- lapply(theObject@datasetList,

**Done**
`input_mat_list <- lapply(getDatasetList(theObject),`

>        995:            list_matBindingValues_list <- lapply(theObject@datasetList,

**Done**
`list_matBindingValues_list <- lapply(getDatasetList(theObject),`

>       1225:            input_mat_list <- lapply(theObject@datasetList,

**Done**
` input_mat_list <- lapply(getDatasetList(theObject),`

>       1264:            input_mat_list <- lapply(theObject@datasetList,

**Done**
` input_mat_list <- lapply(getDatasetList(theObject),`

>This is not a complete list. Do this everywhere.

- scaling-methods.R
137: theObject@experimentList <-  
Done. experimentList(theObject) <-
138: lapply(theObject@experimentList, function(experiment){
Done. lapply(getExperimentList(theObject), function(experiment){ 
177: theObject@experimentListLoaded <-
Done. experimentList(theObject) <-  
178: lapply(theObject@experimentListLoaded, function(experiment){
Done. lapply(getExperimentList(theObject), function(experiment){ 
208: theObject@datasetList <- lapply(theObject@datasetList,  
Done. datasetList(theObject) <- lapply(getDatasetList(theObject),


If doing a search for '@' the remaining symbols should be allowed to my 
understanding, if not please let me know:
- R > accessor-methods.R (35 matches).
- R > AllClasses.R (23 matches)
- R > AllGenerics.R (5 matches)
- R > replace-methods.R (18 matches)
- tests > all @ are in messages
- vignettes > @ of the references to the litterature
- DESCRIPTION > @ of email address



> You have ";" (semi-colons) in your code. R does not need semi-colons.

**Removed from package**



>In AllGenerics.R:
>setGeneric(
>name = "boxplotSpike",
>def = function(theObject, col = NULL, rawFile = FALSE, rpmFile = FALSE,
>bgsubFile = FALSE, revFile = FALSE, spiked = TRUE, ylab = NULL,
>outline = TRUE, violinPlot = FALSE, notch = TRUE, 
>mean_with_sd = FALSE, mean = FALSE, median = FALSE, 
>boxplot = FALSE, jitter = FALSE, plot = TRUE, verbose = FALSE){
>standardGeneric("boxplotSpike");
>});
                                                                                                                                                                                                                
>instead ,
                                                                                                                                                                                                                
>setGeneric(
>name = "boxplotSpike",
>def = function(theObject, col = NULL, rawFile = FALSE,
>rpmFile = FALSE, bgsubFile = FALSE, revFile = FALSE,
>spiked = TRUE, ylab = NULL,
>outline = TRUE, violinPlot = FALSE, notch = TRUE, 
>mean_with_sd = FALSE, mean = FALSE, median = FALSE, 
>boxplot = FALSE, jitter = FALSE, plot = TRUE,
>verbose = FALSE){
>standardGeneric("boxplotSpike")
>},
>signature = "theObject"
>)

**Done for all generics**
                                                                                                                                                                                                                
>  I recommend re-formatting your code. Try to use "formatR" package, to check how to format it.

**I have tried the package, I really do not like the formating, it makes it more difficult to read. if that's ok I would like to keep the code as it is.**

**Comment by nturaga** [comment]
Hi @descostesn 

Please bump the version number if you are ready. I'll wait for the build to complete and review your package again.

**Comment by nturaga** [comment]
@descostesn 

Thank you for your detailed response to the initial review.

Please check the latest build report and address the ERROR.

**Comment by descostesn** [comment]
@nturaga 

This is coming from system.file which does not find the extdata files anymore. This is weird because I did not get the error in December... I am looking into it.

Thanks!

**Comment by descostesn** [comment]
@nturaga 

Hi again,

So it turns out that rtracklayer does not support importing bigwig files on windows. However using the package with fixed steps wiggle file does not seem to be a good solution to me. Looking around it seems that the only alternative would be to use something like:

`if(.Platform$OS.type == 'windows') {
    stop('As of rtracklayer 1.25.16, BigWig is not supported on
Windows. Thus loading data from BigWig files will most likely fail!')
}else{......
}`

Would it be ok ?

By the way, do you know why this error did not show up during my previous commits?

**Comment by nturaga** [comment]
Hi @descostesn,

That fix seems fine. Please be sure to inform your users that this feature doesn't work on windows, through the vignette and man pages as well. 

The reason it didn't show up before was because the windows builder wasn't active at that point.

**Comment by descostesn** [comment]
Hi @nturaga ,

I have addressed the issue that we talked about by adding a warning message where needed. Please see below the details of the modifications.

Thanks,

Nicolas




`if(.Platform$OS.type == 'windows') {
        warning("As of rtracklayer >= 1.37.6, BigWig is not supported on ",
                "Windows. Thus loading data from BigWig files will most ",
                "likely fail.", immediate. = TRUE)
    }`

Added to:
constructors.R: at line 220 and 297.
inputSubtraction-method.R: at line 101 and 120.
scaling-methods.R: line 73.

----------------------------------------------

	"On Windows operating system, reading of BigWig files may fail due to the 
	Bioconductor package rtracklayer >= 1.37.6 that does not support this file format.".

Added to the details section: 
ChIPSeqSpikeDatasetBoost-class.Rd: line 134.
ExperimentLoaded-class.Rd: line 118.
inputSubtraction.Rd: line 60.
scaling.Rd: line 82.

-------------------------------------------------

Added a section 2.1 "Note for Windows users" in the vignette

**Comment by descostesn** [comment]
Hi @nturaga ,

I wanted to make sure that my last post is ok to pursue the review. Can you confirm that it is fine?

Thanks.

Nicolas

**Comment by nturaga** [comment]
The error seems to persist. Can you try another version bump? I'll take a look at it after.

**Comment by descostesn** [comment]
@nturaga 

The error will not disappear on the system as I added warning messages for the fact that rtracklayer does not handle bigwigs on windows. And if you look at the [report](http://bioconductor.org/spb_reports/ChIPSeqSpike_buildreport_20180119155612.html), the error is only on windows.
I think it is better to add warning messages rather than preventing to run the code on windows (+ note in the vignette, see post from 5 days ago).

The reason to put warnings instead of not running the code is that some users, for whatever reason, can use rtracklayer on windows. see [here](http://bioc-devel.r-project.narkive.com/TWAGEPoh/rtracklayer-bigwigfile-on-windows) the discussion with Michael Lawrence.

**Comment by nturaga** [comment]
Hi, 

I guess instead of throwing an error or a warning, you should just `return` to avoid getting an error if its on the windows machine. 

I might have misunderstood your earlier message.

**Comment by descostesn** [comment]
Hi @nturaga,

So now the package is building on the 3 platforms without errors.

Concerning the remaining warnings on windows, I do not get it. For instance:

              missing file link 'PlotSetArray'  in  ChIPSeqSpikeDataset-class
 
but I wrote:

               \code{\link[seqplots]{PlotSetArray}}

From what I found [here](http://r-pkgs.had.co.nz/man.html), this code seems to be correct:

                allows you to point to other useful resources, either on the web, 
                \url{http://www.r-project.org}, in your package \code{\link{functioname}}, 
                or another package \code{\link[packagename]
                {functioname}}.

**Comment by descostesn** [comment]
Hi @nturaga 

I removed the warnings and errors on the three platforms. Can I ask what will be the next step? next round of revisions?

thanks

**Comment by mtmorgan** [comment]
Sorry to chime in late here. The `warning()` should be `stop()`, and the code chunks / examples that generate the error about BigWig not available on Windows should be conditionally evaluated, e.g., in examples, 

```
if (.Platform$OS.type != "windows") {
   ...
}
```

**Comment by descostesn** [comment]
Dear @mtmorgan  and @nturaga,

This is done.

Nicolas

**Comment by descostesn** [comment]
@nturaga 

Thank you very much!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/descostesn.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"ChIPSeqSpike\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ChIPSeqSpike

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
