### ISSUE TITLE
TTMap

### ISSUE THREAD

**Issue by jeitziner** [Bioconductor/Contributions#559]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jeitziner/TTMap

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jeitziner** [comment]
Dear Bioconductor,

I changed the package to a newer version.

Thanks!

**Comment by jeitziner** [comment]
Dear Bioconductor, Dear @mtmorgan,

The last warning I get are independent of my package (it concerns RGL which whenever you don't have X11 on your PC can't be working: Warning : RGL: unable to open X11 display
Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE). Any suggestions on what I can do ?  

Thanks!

**Comment by mtmorgan** [comment]
ignore the rgl warning.

**Comment by jeitziner** [comment]
Dear Bioconductor, Dear @mtmorgan,

I changed the package to a newer version, with only warning the warning from rgl. Hence, I have a version ready for review.

Thanks a lot,

Regards

**Comment by vobencha** [comment]
- rgl is at version 0.98.1. Why the dependency on rgl (>= 0.95.1456)?

- function names:

  -- Re-name all of TTMap_part1, TTMap_part2, TTMap_part3 and TTMap_part4 to more descriptive names.

  -- Re-name read.pcl and write.pcl to have underscores so they are consistent with the other function names.
- Name functions consistently. The names in the vignette are capatilized (TTMap_part1) but the function name is ttmap_part1.

- All man pages need running examples.

- Instead of constructing data by hand in the examples and man pages, please use a dataset available in the experimental data repository or one of the 'Hubs':

  https://bioconductor.org/packages/release/BiocViews.html#___ExperimentData

  https://bioconductor.org/packages/release/bioc/html/AnnotationHub.html

  https://bioconductor.org/packages/release/bioc/html/ExperimentHub.html

- Inputs / Outputs

  The methods in this package operate on RNA seq data. The standard Bioconductor classes for organizing and manipulating such data are SummarizedExperiment::SummarizedExperiment, DESeq2::DESeqDataSet and edgeR::DGEList classes. Please use (or extend) one of these classes. For example, arguments normal.pcl and tumor.pcl in TTMap_part1 could both be SummarizedExperiment objects.

  By using these pre-existing classes you get accessros and validity methods for free.

- vignettes/

  This directory should only have a .Rnw, bib and graphics. Do not include static files such as pdf and html. If you want to have such files in your github repo, add a .gitignore file to omit these files when comitting to git.
```
~/repos/github/packageReview/TTMap/vignettes >ls
biblio2.bib  natbib  TTMap.pdf  TTMap.Rnw  TTMap.tex
```
- Please use the BiocStyle package for your vignette.

Let me know if you have questions.

Valerie

**Comment by jeitziner** [comment]
Dear Valerie, 
Thanks for your first review. I addressed all the points. See below I answered specifically for those were I did something special 

	•	rgl is at version 0.98.1. Why the dependency on rgl (>= 0.95.1456)?
Stackexchange said it might put away the warning for X11. But It does not, so I removed the dependency, thank you.

	•	Name functions consistently. The names in the vignette are capatilized (TTMap_part1) but the function name is ttmap_part1.

I tried to name all the function with small letters and all the variables with capital letters, I changed the vignettes sections.

	•	Instead of constructing data by hand in the examples and man pages, please use a dataset available in the experimental data repository or one of the 'Hubs': https://bioconductor.org/packages/release/BiocViews.html#___ExperimentData https://bioconductor.org/packages/release/bioc/html/AnnotationHub.html https://bioconductor.org/packages/release/bioc/html/ExperimentHub.html

Done, I took the breastCancerNKI.

	•	Inputs / Outputs The methods in this package operate on RNA seq data. The standard Bioconductor classes for organizing and manipulating such data are SummarizedExperiment::SummarizedExperiment, DESeq2::DESeqDataSet and edgeR::DGEList classes. Please use (or extend) one of these classes. For example, arguments normal.pcl and tumor.pcl in TTMap_part1 could both be SummarizedExperiment objects. By using these pre-existing classes you get accessros and validity methods for free.

The TTMap method is written in a general way because it can be used more generally (I used it for instance on brain spike data, or on proteomics data), to put there a restriction on only SummarizedExperiment data is not a good idea. 
However, I created a new function (SumExp2pcl) that should enable to pass from SummarizedExperiment to pcl. 

	•	vignettes/ This directory should only have a .Rnw, bib and graphics. Do not include static files such as pdf and html. If you want to have such files in your github repo, add a .gitignore file to omit these files when comitting to git.
~/repos/github/packageReview/TTMap/vignettes >ls
biblio2.bib  natbib  TTMap.pdf  TTMap.Rnw  TTMap.tex

done

	•	Please use the BiocStyle package for your vignette.

done

Have a nice day!

**Comment by vobencha** [comment]
Thanks for making the chagnes.

* Supporting existing infrastructure

The SummarizedExpepriment class is very general. The assays() matrices can hold count, expression or other types of data. rowRanges() holds genomic position data and rowData() holds a DataFrame of metadata on the rows. It's quite flexible and non restrictive.

If your methods can be used on a vector, matrix or data.frame, they can work on a SummarizedExperiment. If you feel a distinction needs to be made for proteomics data, your methods can support the data in one of the existing classes in these packages:

  https://bioconductor.org/packages/release/BiocViews.html#___Proteomics

* man page examples
    - Data used in man pages and vignettes (i.e., not essential for package function) should be in the 'Suggests' field of DESCRIPTION. Please move breastCancerNKI to 'Suggests'.

    - The data package needs to be loaded, i.e., library(breastCancerNKI), when used in man pages or the vignette.

    - Do no use unexported functions in your man page examples. These are for internal business only. The idea is that you give the user access (and documentation) to all functions they need. If the user needs SumExp2pcl() then you need to export it. If it remains internal, do not use it in the man page examples.
```
\examples{
##--
data(nki)
ALPHA <- 1
junk <- TTMap:::SumExp2pcl(nki,1:10,50:60,
rownames(nki),rownames(nki))
TTMAP_part1prime <-TTMap::ttmap_part1_ctrl_adj(
normal.pcl = junk$CTRL,
tumor.pcl = junk$TEST, 
normalname = "Hi", dataname = "Hello", 
org.directory = getwd(),e=0,P=1.1,B=0);
}
```

Valerie

**Comment by jeitziner** [comment]
Dear Valerie, @vobencha 
Thanks for the update.
	•	Supporting existing infrastructure
The SummarizedExpepriment class is very general. The assays() matrices can hold count, expression or other types of data. rowRanges() holds genomic position data and rowData() holds a DataFrame of metadata on the rows. It's quite flexible and non restrictive.
If your methods can be used on a vector, matrix or data.frame, they can work on a SummarizedExperiment. If you feel a distinction needs to be made for proteomics data, your methods can support the data in one of the existing classes in these packages:
https://bioconductor.org/packages/release/BiocViews.html#___Proteomics

You are right actually! No, no distinction needs to be made for proteomics, one can simply use make_matrices if one has a matrix or SumExp2pcl if one has a Summarized experiment.  

	•	man page examples
	◦	Data used in man pages and vignettes (i.e., not essential for package function) should be in the 'Suggests' field of DESCRIPTION. Please move breastCancerNKI to ‘Suggests'.
Done
	◦	The data package needs to be loaded, i.e., library(breastCancerNKI), when used in man pages or the vignette.
Done
	◦	Do no use unexported functions in your man page examples. These are for internal business only. The idea is that you give the user access (and documentation) to all functions they need. If the user needs SumExp2pcl() then you need to export it. If it remains internal, do not use it in the man page examples.
Done, I removed a lot of function, I did not really get (until now) that it should be like that ! Thanks! 
Also, I forgot to include SumExp2pcl into the exports, but yes it needs to be there, because users need to tell the computer what (or which columns/samples) to consider in their SummarizedExperiment as a control or as a test group, so they need the man-docs attached to it.

Thanks, Have a nice start in the week,

Rachel

**Comment by jeitziner** [comment]
Dear Valerie, @vobencha ,

Did you have a chance to get a new glance at the package ?

Thanks, Have a nice start in the week

Rachel

**Comment by vobencha** [comment]
If the method supports multiple objects, e.g., SummarizedExperiment, matrix, data.frame etc. it should be an S4 generic. See GenomicRanges, GenomicAlignments, VariantAnnotation, DESeq2 etc. for examples of the setGeneric and setMethod statements. 

The man pages should describe each type of possible input the method supports. If SummarizedExperiment is a possible input this must be stated on the man page. See the man pages of the above packages above for examples. Specifically, here is an example of how to document the S4 generic and methods for readGAlignments():
```
library(GenomicAlignments)
?readGAlignments
```

Valerie

**Comment by jeitziner** [comment]
Dear Valerie, @vobencha,

I am not sure to understand why it would be helpful to create a S4 generic object. Would that be so that the format is clearer ? Up to now, I optimized the parameter selection of the method mainly for gene expression data, so I guess the fact that I wrote functions for matrices, data.frame and Summarized experiment covers it all no ? 

Sorry for asking a naive question.

Thanks,

Rachel

**Comment by vobencha** [comment]
Hi,
I don't see where you've written methods for data.frame, SummarizeExperiment and matrix. For example, ttmap_part1_ctrl_adj() takes matrix as the first 2 arguments. It does not take data.frame or SummarizedExperiment.

You would be using S4 method dispatch, not creating a new S4 class. S4 method dispatch has several advantages but the most relevant are probably these:
- Allows you to skip a great deal of checking that must be done to ensure the input is valid.
- Compatibility with other Bioconductor infrastructure classes. By supporting other classes, your method becomes more accessible to users across the board. They don't have to manipulate or change their data to use your methods.

My original comment asked you to support SummarizedExperiment inputs for the 'normal.pcl' and 'turmor.pcl' arguments to ttmap_part1_ctrl_adj(). To do this you would need to
- Create a ttmap_part1_ctrl_adj generic function (not class)
- Create a ttmap_part1_ctrl_adj method that dispatches on matrix,matrix and another method that dispatches on SummarizedExperiment,SummarizedExperiment
- The first portions of the 2 methods would differ in that you'd use assays() to extract the data matrices from the SummarizedExperiment object. After that point, the 2 methods would be the same.

These comments apply to several man pages but I'm using ttmap_part1_ctrl_adj() an example.

* The name of this function is cumbersome and not intuitive. I don't think many users would know what ttmap_part1_ctrl_adj() stands for or what the function might do. Please consider renaming this (and the other ttmap_part* functions) to something that make intuitive sense. At least something that is easier for the user to remember and type to find the man page with question mark ... ?functionName, etc.

* Avoid using names like 'junk' in your examples. I'm not sure what this is supposed to mean and it doesn't give a good impression to the user.
```
junk <- TTMap:::SumExp2pcl(nki,1:10,50:60,rownames(nki),rownames(nki))
```

* The names 'Hi' and 'Hello' are not biologically relevant terms. How should the user interpret these values in application to their own data? Your examples are supposed to 'set the stage' so to speak, for the user to modify their own data to the analysis offered in your package.
```
TTMAP_part1prime <-TTMap::ttmap_part1_ctrl_adj(
normal.pcl = junk$CTRL,
tumor.pcl = junk$TEST,
normalname = "Hi", dataname = "Hello",
org.directory = getwd(),e=0,P=1.1,B=0)
```

* On the ?SumExp2pcl man page we see this:
```
"SumExp2pcl generates the test matrix and the control matrix in
the format accepted by ttmap_part1_ctrl_adj from a
SummarizedExperiment object"
```
Yet that is not what the function does in the examples. The 'niki' argument is supposed to be a SummarizedExperiment but it is an ExpressionSet:
```
> library(breastCancerNKI)
> data(nki)
> class(nki)
[1] "ExpressionSet"
attr(,"package")
[1] "Biobase"
```
AFAICT, SumExp2pcl prepares data for the ttmap_part1_ctrl_adj function. These steps would be wrapped in the method for SummarizedExperiment,SummarizedExperiment. In this way the user will not need to call this function themselves - you'd do it as part of the method behind the scenes.

* Remove the triple colon for functions that are exported. You do not need a triple colon to call SumExp2pcl() if it's exported. This applies to the write* and read* functions as well.

* Please use some level of indenting in your code, e.g., 4 spaces. It is very difficult to read as you have it all left justified. Look at GenomicAlignments/R source code for formatting examples.

* Do not write to the users local system in the man pages or vignette. The build machines (windows) will not allow it. Use tempfile() and tempdir() instead.
```
TTMap:::write_pcl(to_be_saved,"/the_file",getwd())
d <- TTMap:::read_pcl("the_file",na.type = "",Nrows= -1)
```

**Comment by vobencha** [comment]
Are you planning to resubmit or should I close this issue?

**Comment by jeitziner** [comment]
Dear Valerie,

I am almost done ! I am just changing the remaining .Rd files. New version very soon!

**Comment by jeitziner** [comment]
Hi @vobencha,

Happy new year, sorry I was on holidays so I did not work on this project during that time.

My method called TTMap (two-tier Mapper) is made out of two major parts that are independent. So I thought that if a person only wants to use the first part, (s)he will look for ttmap_part1. 

Now, to be more precise, there are two subparts in the first part, that is why I thought to write ttmap_part1_ctrl_adj as it adjust the control group (ctrl_adj) and ttmap_part1_hda as it does a deviation assessement from a hyperrectangle (hda). The second part ttmap_part2 has only one function, but I made it more precise, it actually does use the mathematical algorithm « Mapper » but with a global-to-local covering, hence it is called ttmap_part2_gtlmap for global to local Mapper. 

I don’t quite know now how to make these names more precise than that. Maybe it would just be clearer with a scheme in the text (which I added in the vignettes!) so that a person sees the different parts visually. 

If it is the ttmap_part1 and part2 that I should remove, I can. I just thought it is more intuitive for a person only seeking for one or the other part to know what they should look for in terms of functions. What do you think ? Any suggestions on how to write it ?

-I used indenting in my code now, removed triple colons, no more names like « hi » « hello » « test » and « junk », sorry for that.
-I changed to tempdir(), tempfile(). 

As you correctly noticed, Sum2pcl and make-matrices are functions that prepare for ttmap_part1_ctrl_adj. I now used the S4 methods on the make-matrices which is the very first function the user has to use (because (s)he needs to indicate to the computer which are the groups he wants to compare afterwards, whence he can not skip that step and just go to ttmap_part1_ctrl_adj directly). In that way no more need for Sum2pcl. 

After make-matrices, I have the formats I need for the rest to work. 

Have a nice day and I am looking forward to hearing from you. 

Rachel

**Comment by vobencha** [comment]
You could rename the functions:
```
ttmap_part1_ctrl_adj() --> TTCorrectedControl()
ttmap_part1_hda() --> TTHyperrectangleDeviation()
ttmap_part_gtlmap() --> TTMap()
```
Please don't forget to support SummarizedExperiment and doucment that in the man pages.

Thanks.
Valerie

**Comment by jeitziner** [comment]
Dear Valerie, @vobencha,

I changed the names of the functions, and the SummarizedExperiment is supported in the make_matrices and I changed the man accordingly. 

I did not find in the webpage you suggested any SummarizedExperiment that is why I took the NKI dataset which is an ExpressionSet. If you'd rather have also an example with SummarizedExperiment can you suggest a dataset? thanks

Have a nice day,
Rachel

**Comment by jeitziner** [comment]
Dear Valerie, @vobencha ,

Sorry I wanted to add links in all my mans, but somehow it gave me problems on Windows, while working on Mac and linux. Now I solved it and it is working. 

Thanks for your further comments,

Rachel

**Comment by vobencha** [comment]
To find example data in a SummarizedExperiment object go to the BiocViews page
  https://bioconductor.org/packages/release/BiocViews.html#___ExperimentData
and click on 'Experiment Data' on the left. Then enter the search term 'SummarizedExperiment' on the top right. The packages that show up are 
airway
fission
GSE62944
microRNAome
parathyroidSE

**Comment by jeitziner** [comment]
Dear @vobencha 
Tried it on the two first packages ! Works fine by me. 
Have a nice day

**Comment by vobencha** [comment]
Thank you for making the changes. Unfortunately not all of the comments in https://github.com/Bioconductor/Contributions/issues/559#issuecomment-352297571 have been addressed. Code is not formatted, triple colon is still used etc.

In addition to those issues, please -

1) Remove breastCancerNKI. The point is to use a dataset that has a SummarizedExperiment, not ExpressionSet. Replace breastCancerNKI with one of the other packages I suggested in https://github.com/Bioconductor/Contributions/issues/559#issuecomment-359909271

2) Name functions consistently. This may be my fault for suggesting camelCase when re-naming a few functions. You can use underscores or camelCase but please just use one style. For example, you can use control_adjustment instead of ControlAdjustment.

Thanks.
Valerie

**Comment by vobencha** [comment]
@jeitziner 

It is very time consuming for me to re-review your code with each submission only to find that you have not addressed problems raised previously.

Please explain (create an itemized list) how all issues raised in these comments have been addressed:
https://github.com/Bioconductor/Contributions/issues/559#issuecomment-347320967
https://github.com/Bioconductor/Contributions/issues/559#issuecomment-359909271
https://github.com/Bioconductor/Contributions/issues/559#issuecomment-360476149

Valerie

**Comment by jeitziner** [comment]
•	rgl is at version 0.98.1. Why the dependency on rgl (>= 0.95.1456)?
Stackexchange said it might put away the warning for X11. But It does not, so I removed the dependency.
	•	function names: -- Re-name all of TTMap_part1, TTMap_part2, TTMap_part3 and TTMap_part4 to more descriptive names. -- Re-name read.pcl and write.pcl to have underscores so they are consistent with the other function names.

TTMap_part1 is called control_adjustement as it adjust the control group
TTMap_part2 is called hyperrectangle_deviation_assessment as it calculates a deviation from a hyperrectangle
TTMap_part3 is called ttmap as it is the main function calculating the Mapper output using a two-tier cover 

All the exported functions are with small letters and are separated by underscores.

	•	Name functions consistently. The names in the vignette are capatilized (TTMap_part1) but the function name is ttmap_part1.

Names are consistent

	•	All man pages need running examples.

They do.

	•	Instead of constructing data by hand in the examples and man pages, please use a dataset available in the experimental data repository or one of the 'Hubs': https://bioconductor.org/packages/release/BiocViews.html#___ExperimentData https://bioconductor.org/packages/release/bioc/html/AnnotationHub.html https://bioconductor.org/packages/release/bioc/html/ExperimentHub.html

I took the airway data set which is a Summarized Experiment data set.

	•	Inputs / Outputs The methods in this package operate on RNA seq data. The standard Bioconductor classes for organizing and manipulating such data are SummarizedExperiment::SummarizedExperiment, DESeq2::DESeqDataSet and edgeR::DGEList classes. Please use (or extend) one of these classes. For example, arguments normal.pcl and tumor.pcl in TTMap_part1 could both be SummarizedExperiment objects. By using these pre-existing classes you get accessros and validity methods for free.

Now the method allows the input to be a Summarized experiment/ExpressionSet/data.frame or matrix. One starts with « make_matrices » this function creates the right format for the rest of the functions

	•	vignettes/ This directory should only have a .Rnw, bib and graphics. Do not include static files such as pdf and html. If you want to have such files in your github repo, add a .gitignore file to omit these files when comitting to git.
~/repos/github/packageReview/TTMap/vignettes >ls
biblio2.bib  natbib  TTMap.pdf  TTMap.Rnw  TTMap.tex

Only .Rnw, bib and one .png left.
	•	Please use the BiocStyle package for your vignette.
I do.
#############################################################
Hi,
I don't see where you've written methods for data.frame, SummarizeExperiment and matrix. For example, ttmap_part1_ctrl_adj() takes matrix as the first 2 arguments. It does not take data.frame or SummarizedExperiment.

I need the user to use first make_matrices so that he/she tells me what are the samples he wants to use as controls and what are the samples he wants to use as a test, from a dataset. So that is why since anyway he/she has to use the make_matrices, it does not matter what inputs ttmap_part1_ctrl_adj needs.

You would be using S4 method dispatch, not creating a new S4 class. S4 method dispatch has several advantages but the most relevant are probably these:
	•	Allows you to skip a great deal of checking that must be done to ensure the input is valid.
	•	Compatibility with other Bioconductor infrastructure classes. By supporting other classes, your method becomes more accessible to users across the board. They don't have to manipulate or change their data to use your methods.

make_matrices uses S4 methods

My original comment asked you to support SummarizedExperiment inputs for the 'normal.pcl' and 'turmor.pcl' arguments to ttmap_part1_ctrl_adj(). To do this you would need to
	•	Create a ttmap_part1_ctrl_adj generic function (not class)
	•	Create a ttmap_part1_ctrl_adj method that dispatches on matrix,matrix and another method that dispatches on SummarizedExperiment,SummarizedExperiment
	•	The first portions of the 2 methods would differ in that you'd use assays() to extract the data matrices from the SummarizedExperiment object. After that point, the 2 methods would be the same.

So I think there is no need because make_matrices does the job. However if you still would rather have me doing this please tell me ! 

These are a few new comments:
	•	man pages
	•	These comments apply to several man pages but I'm using ttmap_part1_ctrl_adj() an example.
-- The name of this function is cumbersome and not intuitive. I don't think many users would know what ttmap_part1_ctrl_adj() stands for or what the function might do. Please consider renaming this (and the other ttmap_part* functions) to something that make intuitive sense. At least something that is easier for the user to remember and type to find the man page with question mark ... ?functionName, etc.

Understood: it was changed with your advices. 

-- Avoid using names like 'junk' in your examples. I'm not sure what this is supposed to mean and it doesn't give a good impression to the user.
junk <- TTMap:::SumExp2pcl(nki,1:10,50:60,rownames(nki),rownames(nki))

There are none anymore.

-- The names 'Hi' and 'Hello' are not biologically relevant terms. How should the user interpret these values in application to their own data? Your examples are supposed to 'set the stage' so to speak, for the user to modify their own data to the analysis offered in your package.
TTMAP_part1prime <-TTMap::ttmap_part1_ctrl_adj(
normal.pcl = junk$CTRL,
tumor.pcl = junk$TEST,
normalname = "Hi", dataname = "Hello",
org.directory = getwd(),e=0,P=1.1,B=0)

I made them more clear in the method. 

-- On the ?SumExp2pcl man page we see this:
"SumExp2pcl generates the test matrix and the control matrix in
the format accepted by ttmap_part1_ctrl_adj from a
SummarizedExperiment object"
Yet that is not what the function does in the examples. The 'niki' argument is supposed to be a SummarizedExperiment but it is an ExpressionSet:
> library(breastCancerNKI)
> data(nki)
> class(nki)
[1] "ExpressionSet"
attr(,"package")
[1] « Biobase"

This has been changed and is replaced by the S4 generic method make_matrices

AFAICT, SumExp2pcl prepares data for the ttmap_part1_ctrl_adj function. These steps would be wrapped in the method for SummarizedExperiment,SummarizedExperiment. In this way the user will not need to call this function themselves - you'd do it as part of the method behind the scenes.

Yes you understood correctly, but this has now changed into make_matrices

	•	In all code, please remove the triple colon for functions that are exported. You do not need a triple colon to call SumExp2pcl() if it's exported. This applies to the write* and read* functions as well.

This was corrected. No more triple colon neither in man nor in vignettes.

	•	Please use some level of indenting in your code, e.g., 4 spaces. It is very difficult to read as you have it all left justified. Look at GenomicAlignments/R source code for formatting examples.

In all .R files and in .man files I added indenting

	•	Do not write to the users local system in the man pages or vignette. The build machines (windows) will not allow it. Use tempfile() and tempdir() instead.
TTMap:::write_pcl(to_be_saved,"/the_file",getwd())
d <- TTMap:::read_pcl("the_file",na.type = "",Nrows= -1)

I used tempdir(), it was corrected. 

#################################################################

	1	Remove breastCancerNKI. The point is to use a dataset that has a SummarizedExperiment, not ExpressionSet. Replace breastCancerNKI with one of the other packages I suggested in #559 (comment)

The dataset is now airway and breastCancerNKI was removed.
	2	Name functions consistently. This may be my fault for suggesting camelCase when re-naming a few functions. You can use underscores or camelCase but please just use one style. For example, you can use control_adjustment instead of ControlAdjustment.

This I changed also so all the exported functions are now with small letters and with underscore when needed.

Hope that this report is as you wanted. If more precisions are needed please tell me. 

Rachel

**Comment by jeitziner** [comment]
Dear Valerie, @vobencha
I forgot to mark you in the last e-mail. 
Have a nice day,
Rachel

**Comment by vobencha** [comment]
Thank you for describing the changes. The package looks good but it looks like we need a version bump. Please bump the version and hopefully we'll get a clean build report. Once that's done I'll mark as accepted.

**Comment by jeitziner** [comment]
Dear Valerie, @vobencha,
I had a timeout error message (only on Mac, which was actually strange since I have a Mac and it only took 2 minutes on my computer) and I realized it is because the "airway" dataset was not filtered for 0 expressed genes. I had to therefore change all the .Rd files (I mean all the examples) to just add that they have to be filtered and log transformed. I added a note on that in the "vignettes" as well. 

The last error message I had was quite strange (on windows only!), I checked online and people said that if you re-run the code the error disappears, which it did. So I don't know what it was due to...

Sorry for all these pushes and builds.

Now everything should be fine. I wanted to thank you, I saw the package improving a lot. 

Have a nice day,

Rachel

**Comment by vobencha** [comment]
OK, it looks like the remaining warnings are on our side. The package is approved.

Valerie

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jeitziner.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"TTMap\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TTMap

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
