### ISSUE TITLE
enrichplot

### ISSUE THREAD

**Issue by GuangchuangYu** [Bioconductor/Contributions#567]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GuangchuangYu/enrichplot

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by GuangchuangYu** [comment]
```
* checking for file enrichplot/DESCRIPTION ... OK
* preparing enrichplot:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
ERROR: dependency ggraph is not available for package enrichplot
```
That's the problem of the build system.

**Comment by hpages** [comment]
Hi @GuangchuangYu,

For some reason the graph package was missing on Mac builder merida2. It should be installed by now. Can you please bump the version of enrichplot in order to trigger a new build? I'll start reviewing the package right after that.

Thanks,
H.

**Comment by GuangchuangYu** [comment]
Thanks, @hpages. It seems the issue is still exists.

**Comment by hpages** [comment]
Hi @GuangchuangYu,

My bad: It's **ggraph** that's causing problems, not **graph**. I misread the name sorry. CRAN doesn't provide Mac binary packages for R 3.5 yet. Problem is that ggraph depends (indirectly) on udunits2 which is one of those packages that the build system fails to install from source. This is a known issue, let's ignore it for know.

I'll take a first look at enrichplot in the next few days. Thanks for your patience!

Best,
H.

**Comment by hpages** [comment]
Hi @GuangchuangYu,

Here is some feedback:

- The `cnetplot()`, `dotplot()`, `gseaplot()`, and `ridgeplot()` functions are already defined as generic functions in the DOSE package. Why would you redefine them as regular functions in the enrichplot package? The fact that enrichplot depends on DOSE and that you are also an author of DOSE makes this choice even more surprising/confusing.

- The vignette is plot gallery i.e. a collection of plots with no text. Would be nice to make it look like a real vignette e.g. by adding an introduction that provides some context and by providing some short explanation and/or comment about each plot.

- The man pages are also too minimalist. For example the title and description in `?mapplot` are
  ```
    mapplot
  ```
  and
  ```
    Enrichment Map
  ```
  Having a title that is just the name of the function doesn't really help, especially when the user is navigating the man pages via the HTML browser interface. The description needs to be a full sentence (i.e. with a verb).

- Use of capitalization could be more consistent. For example the description and author in `?mapplot` are
  ```
    Enrichment Map
  ```
  and
  ```
    Guangchuang Yu
  ```
  But in `?cnetplot` they are
  ```
    gene-concept network
  ```
  and
  ```
    guangchuang yu
  ```

Please address at your earliest convenience, thanks!

H.

**Comment by GuangchuangYu** [comment]
Thanks @hpages for your feedback.


>    The cnetplot(), dotplot(), gseaplot(), and ridgeplot() functions are already defined as generic functions in the DOSE package. Why would you redefine them as regular functions in the enrichplot package? The fact that enrichplot depends on DOSE and that you are also an author of DOSE makes this choice even more surprising/confusing.

I have defined all of the visualization functions as generic functions in enrichplot and removed the dependency of DOSE.  I will update DOSE to use methods implemented in enrichplot.

The reasons I split the visualization methods from DOSE to enrichplot are that some of the methods are re-implemented using ggplot2 (now all of them are ggplot2-based) and new methods were added.

>    The vignette is plot gallery i.e. a collection of plots with no text. Would be nice to make it look like a real vignette e.g. by adding an introduction that provides some context and by providing some short explanation and/or comment about each plot.

I have updated the vignette with explanation of each plot.


>The man pages are also too minimalist. For example the title and description in ?mapplot are
>
>   mapplot
>
>and
>
>   Enrichment Map
>
>Having a title that is just the name of the function doesn't really help, especially when the user is navigating the man pages via the HTML browser interface. The description needs to be a full sentence (i.e. with a verb).

I have updated the man pages.

>Use of capitalization could be more consistent. For example the description and author in ?mapplot are
>
>  Enrichment Map
>
>and
>
> Guangchuang Yu
>
>But in ?cnetplot they are
>
>  gene-concept network
>
>and
>
>  guangchuang yu

All man pages were updated and consistent now.

**Comment by GuangchuangYu** [comment]
any progress?

**Comment by hpages** [comment]
Hi @GuangchuangYu,
Thanks for the update. Note that it is not a good idea to define S3 generics and methods to dispatch on S4 objects. Please define `cnetplot()`, `dotplot()`, `gseaplot()`, and `ridgeplot()` as **S4** generics. The rest of your changes look good, especially the improvements to the vignette. Thanks!
H.

**Comment by GuangchuangYu** [comment]
the error looks like another issue of the build server.

**Comment by GuangchuangYu** [comment]
@hpages do you have any further comments? It took more than 2 months and I think it hanged up too much for the build system issue.

**Comment by GuangchuangYu** [comment]
> Error : package udunits2 was installed by an R version with different internals; it needs to be reinstalled for use with this R version

the build system issue is still not fixed.

**Comment by hpages** [comment]
Thanks @GuangchuangYu for the updated package.

Let's ignore the error on the Mac builder for now (which is a problem on our side).

Note that you shouldn't put curly braces around the call to `standardGeneric()` in the definition of your generic functions:
```
> heatplot
nonstandardGenericFunction for "heatplot" defined from package "enrichplot"

function (x, showCategory = 30, foldChange = NULL) 
{
    standardGeneric("heatplot")
}
```
This makes them look as non-standard generic functions and I don't think that's what you want.

Other than that everything looks fine and I'm labeling the package as "accepted".

Cheers,
H.

PS: Yes, "the entire review process **typically** takes between 2 and 5 weeks". But please note that we don't promise anything. Sometimes it takes longer... That's just the way it is.

**Comment by GuangchuangYu** [comment]
Thanks @hpages.

I will update the generic function definition directly to the bioconductor git repo.

However, I don't have the permission:

```
FATAL: R any packages/enrichplot g.yu DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch upstream
```

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GuangchuangYu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"enrichplot\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/enrichplot

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
