### ISSUE TITLE
r2cytoscape

### ISSUE THREAD

**Issue by AlexanderPico** [Bioconductor/Contributions#570]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cytoscape/r2cytoscape

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Bioconductor requires that each package have a vignette outlining overall package use and integration with other Bioconductor work flows. The vignette should included code chunks that illustrate this use, and the code chunks should be evaluated (not static 'pictures of code'). See http://bioconductor.org/developers/package-guidelines/#vignettes

**Comment by AlexanderPico** [comment]
Thanks for the quick response. I've added a couple vignettes to the package.

**Comment by mtmorgan** [comment]
Sorry to be stickler but the 'pictures of code' vignettes with `eval = FALSE` are not acceptable; these too quickly become out-of-date, and simultaneously remove an important source of tests for your package code. Also, please use the Bioconductor idiom for installing packages, assuming yours is accepted, i.e., `source("https://bioconductor.org/biocLite.R"); biocLite("r2cytoscape")` -- the vignette is about using your package, not about strategies for version management. I am also not confident (though I have no reason to suspect otherwise) that pacman respect the Bioconductor approaches to version management.

**Comment by AlexanderPico** [comment]
I appreciate the feedback!  I think I understand about using biocLite instead of pacman, writing the vignette assuming it's a package (change committed).

But, I'm not sure how to fix the ```eval=FALSE``` situation. The r2cytoscape package is all about communicating with a software package called Cytoscape. None of the functions work unless Cytoscape is installed and running. So, my tests and vignettes have to be skipped for automated evaluation, right?  If you have any suggestions, I'd be happy to implement another approach.

**Comment by mtmorgan** [comment]
Right, this is a problem. Before trying to tackle, can you tell me the relationship between your package and [RCy3][1] (especially) and [RCyjs][2], especially the novelty your package provides and why these features cannot be included in RCy3? Another point of reference is the recently defunct package [RCytoscape][3], removed in favore of RCy3.

[1]: https://bioconductor.org/packages/devel/RCy3
[2]: https://bioconductor.org/packages/devel/RCyjs
[3]: https://bioconductor.org/packages/RCytoscape

**Comment by AlexanderPico** [comment]
Certainly. In fact, I started this particular journey by preparing a workshop on Cytoscape automation using RCy3.  I'm a core developer for the [Cytoscape](http://www.cytoscape.org) project and one of our goals this past year was to facilitate automation, e.g., via R, by improving documentation, providing demos and giving workshops.  RCy3 does a lot of great things and has many years of development even predating the REST interface for Cytoscape (i.e., RCytoscape). In preparing the workshop, however, I ran into a long list of issues. The RCy3 developers were very responsive and pushed out bug fixes for most of these. In the end, there remained "show-stoppers" that could not be resolved. I believe these are due to fundamental design decisions that reflect subtly different use cases. RCy3 is excellent when starting with a network model in R and wanting to push it to Cytoscape and then tweak visualization styles. However, if you are starting with a network in Cytoscape (e.g., retrieved from numerous public repositories), then the process of pulling it into R for analysis and continued visualization tweaks is more problematic. For example, the import of a small network with lots of attributes (from the STRING database) takes ~5 minutes in RCy3, but less than a second in r2cytoscape. I believe this has to do with the CytoscapeWindow approach in RCy3. This approach is also brittle to errors and can leave you in the middle of an analysis without a handle on your network. I could not reliably get through the workshop I was preparing with RCy3, so I wrote r2cytoscape as an alternative.

In r2cytoscape, I'm taking a much simpler, light-weight approach. I'm basically providing wrapper functions around the available CyREST calls and Commands in Cytoscape, making the URL construction and result parsing easier and tailored for R. This approach is easy to develop and maintain; it results in fast execution; and it doesn't depend on an object handle, so it's resilient to errors. You can even restart R and then pick up where you left off.  

In terms of development and maintenance, I'm on weekly conference calls with the developers of CyREST and Cytoscape Commands, and have worked out a protocol for coordinated issue tracking so that new CyREST features turn into r2cytoscape feature request and vice versa. 

At this point, I've personally seen r2cytoscape work through diverse use cases for >100 individuals across 4 different workshop events with a good sampling of platforms and environments. We've worked out all the major kinks and are quite pleased with the package. The major remaining pain point is the installation of the package (currently via github), which we are hoping to resolve with this submission.

**Comment by mtmorgan** [comment]
OK thanks for the explanation. I think it's silly for two R / Cytoscape packages, plus RCyjs, but will initiate the review process. It would be great if there were a meeting of minds between relevant contributors, but I will not insist on it.

As with RCy, you're right it's very difficult to test functionality without a running web server. I think the corollary of this is that the unit tests need to be extensive and robust. One strategy might be to generate small mock objects that represent return values for REST queries from supported versions of Cytoscape, and validate that the mock objects are parsed correctly by r2cytoscape. I'll leave the implementation of this to you.

I'll approve the package for building. It will then build across platforms, and a reviewer will be assigned; I'll take over review of this package and will provide written comments once the package builds across platforms; if there are problems that seem 'build system' related, then I'll try to step in and correct them.

**Comment by AlexanderPico** [comment]
Thanks for moving this forward. I've reviewed the platform build results and have addressed 2 or 3 errors:  
* added biocViews
* subscribed to bioc-devel

The third error is related to the issue of automated testing previously discussed (if I understood it correctly): 

> ERROR: At least 80% of man pages documenting exported objects
>       must have runnable examples.

I've included examples as @section docs in place of auto-run @examples since the functions in this package all require that Cytoscape is running.

Let me know if there is anything else I should respond to.

**Comment by mtmorgan** [comment]
The usual thing to do is to write the examples as
```
#' @examples
#' \dontrun{
#'    ....
#' }
```

or `\donttest{}`(so that the user with a running Cytoscape could still say `example(foo)` and run the examples on the help page, but the examples would not be run when the package was checked).

BiocCheck might complain anyway, but feel free to ignore.

**Comment by AlexanderPico** [comment]
I'll do just that!

The "warnings" from the report were quite helpful as well. Fixes committed.

**Comment by AlexanderPico** [comment]
All errors and warnings should be clear now. Ready for another round of the automated single package builder.

**Comment by mtmorgan** [comment]
Commit version 0.99.1 and it'll trigger another build.

**Comment by mtmorgan** [comment]
Probably the 'must subscribe to bioc-devel' is because you didn't respond to a verification email (probably ended in your spam box). I'll take a look at the package and get back to you with a review in a few days.

**Comment by AlexanderPico** [comment]
Sure enough. Found it in "junk" and replied. Thanks for your tips and for your time!

**Comment by paul-shannon** [comment]
Hi Alex,   

Paul Shannon here.  May I admit to having mixed feelings about your new package?  On balance, it makes some good sense for a core Cytoscape developer of long standing and high skills to be involved.  And no package lasts forever.  So good luck to you - that is my primary message.

I am saddened, however, upon reading this in your message above: " I could not reliably get through the workshop I was preparing with RCy3, so I wrote r2cytoscape as an alternative." 

 Not invented here, I'll write my own: this approach is all too common in scientific software.  It leads to lots of duplicated effort.   Another strategy, perhaps equally useful would be:  "I found a serious bug in package X.  I will report it, engage the package maintainers, maybe contribute a patch, start a collaboration."    

To repeat myself, however, and to emphasize my main point: I wish you good luck and wide adoption with your new package!

- Paul

**Comment by AlexanderPico** [comment]
Hi Paul. I appreciate your message. I share your perspective on the evils of duplicate effort and work pretty hard to avoid it myself.  I did in fact follow the strategy of getting in contact, reporting bugs in a helpful way and trying to make it work. I've got a long thread with your co-author where we both put in a lot of effort (I think you were only cc'd at the start). I'll contact you directly and share more of that history and where we got stuck.  Stuck enough that I felt it was worthwhile taking an alternate approach even at the cost of duplicate effort (a very personal cost, in fact).

**Comment by AlexanderPico** [comment]
@mtmorgan Can I press pause on this process?  I want a bit of time to digest an ongoing discussion with Paul and I don't want to waste your time.

**Comment by mtmorgan** [comment]
Sure, no problem. I'll leave the issue open for a bit; let me know when / how you'd like to resume.

**Comment by mtmorgan** [comment]
I'll close the issue for now; let me @mtmorgan know when you're ready to resume and I'll re-open.
