### ISSUE TITLE
ddPCRclust

### ISSUE THREAD

**Issue by bgbrink** [Bioconductor/Contributions#575]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bgbrink/ddPCRclust

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
before adding your package to the review queue, please update the vignette to have fully evaluated code chunks `<<>>=` rather than verbatim 'pictures of code'. Remember the package guidelines about time and space limitations.

**Comment by bgbrink** [comment]
I pushed the requested changes to the repo 5 days ago. Do you get notified directly via the webhook, or should I adress this and future comments throughout the review process here?

**Comment by mtmorgan** [comment]
The issue hadn't been accepted to the moderation queue so the web hook was not active; thanks for your initial change, a reviewer has been assigned.

**Comment by bgbrink** [comment]
The build command says "ERROR: dependency flowDensity is not available for package ddPCRclust" on Mac OSX. Is this a problem with the build system?

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink 
This is a problem with the available Mac binaries for OSX. 
Please ignore the error. It should go away once the R-development binaries are posted by CRAN.

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink

Please remove the `Remotes` field from your `DESCRIPTION` file. 
It is not necessary. All of these Bioconductor packages are included in the BBS.
You may even be installing out of date packages that way.

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink

I took a quick look at the package and I had a few issues with its implementation.

* Please remove all `library` calls from `.R` files. These can only be present in vignettes or examples.
* Remove any `source` calls in any `.R` file.
* Avoid the use of `@`. Please see the [essential S4 interface](http://www.bioconductor.org/developers/how-to/efficient-code/#essential-s4-interface).
* Avoid using `1:n` sequence generation, use the more robust `seq_len` and `seq_along`. 
* Please review the [package guidelines](http://www.bioconductor.org/developers/package-guidelines/) for more on writing efficient code.

Best regards,
Marcel

**Comment by bgbrink** [comment]
Der Marcel,

thank you for your input. I adressed all your points except the third one. May I ask what the reasoning behind avoiding `@` is? 

I am using the `@exprs` tag to override the expression data of a flowFrame with data from a ddPCR experiment. Simply using the designated function `flowCore::exprs()` produces an error, because the data don't match. Thus, avoiding these checks is intentional and crucial to our ddPCRclust package, since we want to apply some methods from flow cytometry to ddPCR. I would be very grateful for any advice on how to keep the core functionality of our package intact and comply with Bioconductors coding standards at the same time.

Best regards,
Benedikt

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink 

As in the link provided, it separates the implementation from the interface.
Our coding standards require that you provide a clean user interface in the package. 

But based on your description, it seems like it is an issue for the `flowCore` maintainers.
I would create a GitHub issue about it if it is not giving you what you expect.

Regards, 
Marcel

**Comment by bgbrink** [comment]
Hi Marcel, @LiNk-NY 

thank you for your response. To be honest, I do not think this is an issue for the `flowCore` maintainers, because their data structure is intented for flow cytometry data and probably fulfills those needs perfectly. However, we developed a package for ddPCR data, which is outside the scope of `flowCore`, but aims to employ some of the methods of the packages `flowDensity`, `flowPeaks`, and `SamSPECTRAL`. Because these packages were developed for flow cytometry data, we are sometimes forced to mimic a flowFrame even though we actually work with ddPCR data. The only way I was able to do it was directly override it with `flowFrame@exprs <- as.matrix(ddPCRdata)`.

**Comment by bgbrink** [comment]
Hi Marcel, @LiNk-NY 

I was finally able to follow all your previous suggestions, thank you. However, moving `BiocStyle` to the `Suggests` field now produces an error when running `R CMD check`. The `NAMESPACE` was generated automatically by `roxygen2`.

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink 

You have a stray import directive in your files. See: `R/ddPCRclust.R:27`.

Regards,
Marcel

**Comment by bgbrink** [comment]
Hi Marcel, @LiNk-NY 

...yes, sorry. Can I keep the import directives for the functions that make heavy use of the respective packages (namely `flowDensity`, `SamSPECTRAL`, `flowPeaks`, and `clue`) or should all imports be removed regardless?

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink 

In general, you want to import packages whose functions you are using within your own functions.
In this case, you're not using any of the `BiocStyle` functions within your functions so it should
be removed from the imports.

[Line 27](https://github.com/bgbrink/ddPCRclust/blob/master/R/ddPCRclust.R#L27) should read:
```
@import plotrix
``` 

Preferably, you want to selectively import functions rather than whole packages to avoid name
collisions. For example, `@importFrom plotrix clplot`. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink 
Thank you for submitting to Bioconductor. 
`ddPCRclust` provides an algorithm for identifying clusters in ddPCR reaction data.

Although it uses other Bioconductor packages, `ddPCRclust` does not seem to use existing
data structures already available. Please find a data structure that fits the data, namely from
`flow*` packages. 

Please see the review below. 

Best regards,
Marcel

---

# ddPCRclust #575

## DESCRIPTION

* Please format the `DESCRIPTION` for readability with a max width of 80
columns. 
* `Date` field can be omitted
* Remove mention of `GitHub`. You can direct the users to the vignette.
* Consider adding a `BugReports` field to the description pointing to the
`GitHub` issues page.

## NAMESPACE

* It looks like some functions such as `export*` are not needed.
These options should be left up to the user.
* You may just want a plot method for your data structure.

## R

* Avoid overwriting functions with objects such as `t <- ...`
* Fix the formating in the files, it is recommended that files
not exceed 80 columns
* Please use a data structure that will be an input to ddPCRclust, using
files is not very extendable.
* No need to use `ids <- annotations <- vector()`. `lapply` will
take care of memory management internally. 
* Consider using a more appropriate structure for your algorithm with
validity checks. A `list` output will be prone to errors.
* Where possible, avoid using numeric indices for subsetting as they can be
prone to errors when the data changes, it is recommended that you use names
(e.g., `dataset[, "var"]`)
* Create helper functions for repeated operations


Minor: 
* Logical to Index switching is not necessary in most cases
(e.g., `which(result == 8)` can be `result == 8`)
* Length evaluates to `TRUE` when positive (e.g., `if (length(var))`)

## vignettes

* Vignette should not exceed 80-column width 

## LICENSE

* Does it have to be an academic only license? 
* Perhaps @mtmorgan can comment on this.

**Comment by bgbrink** [comment]
Hi Marcel, @LiNk-NY 
thank you for your feedback, it is much appreciated. I am working my way through your comments and a few questions came up. 

> Please use a data structure that will be an input to ddPCRclust, using
files is not very extendable.

I have seen some packages that take a string representing the location of a file as in input before and I always found that very practical for the end user. Thus, I implemented ddPCRclust the same way. If I move the file-reading part of the main function into a different function, that may or may not be used by the end user, while the main function takes the resulting data frame as an input, would that work for you?

> Consider using a more appropriate structure for your algorithm with
validity checks. A list output will be prone to errors.

I do not understand this to be honest. Could you give me an example for a more appropriate structure?

> Does it have to be an academic only license?

We have reasons to leave the licence how it is now, is this going to be a problem with making ddPCRclust available on Bioconductor?

Best regards,
Benedikt

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink 
Functions should perform a single task and not try to do too much.
When you introduce a `file` argument, you limit the way the data can be read in. 
In cases where different file types arise for similar data, the function would suffer in portability. 

When using a data structure such as `data.frame` as input, the user can read in and manipulate the
data before passing it on to the algorithm.

My point about the data structure is that you may want to use a tried and tested data class such
as `SummarizedExperiment` to represent your data. This class would come with validity checks
and is more robust than a simple `list`. 

With regards to the license, I'm not sure but I will ask @mtmorgan about this. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink 
After consulting with Martin @mtmorgan, I was informed that we are unable
to accept a package with an academic only license.
If you are unable to change the license restriction, we will be forced to close the
issue.
Thank you for your attention.
Regards,
Marcel

**Comment by bgbrink** [comment]
Hi Marcel, @LiNk-NY 

we will change the license to artistic-2.0.

I have been implementing most of your suggested changes over the weekend, however I still have a question regarding the previously discussed list output. Changing the output to different data class will require extensive changes not only to ddPCRclust, but also to the accompanying shiny app ddPCRvis (https://github.com/bgbrink/ddPCRvis). I estimate that a significant amount of time would be necessary to implement and test these changes. Since I am only able to work on this project in my free time, I am not sure that I can provide what you ask at the moment. However, I would be happy to keep it in mind for possible future versions of ddPCRclust and ddPCRvis. Alternatively, maybe you can point me in a different direction whith faster to implement changes. I really hope we can find a solution to make ddPCRclust available on Bioconductor while meeting the high standard of Bioconductor packages.

**Comment by bgbrink** [comment]
Hi Marcel, @LiNk-NY

in the new Version most of your requests have been implemented. However, I did not remove the `export*` functions, since I use them in the shiny app and I think some users might find them useful. Furthermore, as aforementioned, I did not (yet) change the output of the functions. 

I did not get an error on my Linux machine when building and checking the package. I will look into that on the weekend.

Lastly, I tried using the `formatR` package to format the code in order to comply with the 80 columns limit. It seems this did not work very well, since `BiocCheck` sill reports about 20% of lines exceeding this limit. Is it really expected to manually go through thousands of lines of code and apply this limit by hand? May I ask what the motivation behind this is?

Best regards,
Benedikt

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink 
Thank you for making those changes.
It would be good for your package to be able to benefit from the
established classes in Bioconductor. 

List outputs are not very structured and can be prone to errors. 
They also don't have established data validity methods. Please consider
using a Bioconductor class for your results.

It seems to me like these functions should go with the shiny app rather than
here. 

Readable code is easier to review and maintain. We don't strictly enforce the
80 column width limit but it reflects on the quality of the coding to some extent.

Best regards,
Marcel

**Comment by bgbrink** [comment]
Hi Marcel, @LiNk-NY 
I cannot reproduce the timeout issue on the machines that are available to me. Do you have any idea what might be the cause here?

Regarding the requested changes, I understand and agree that it would be good to benefit from established Bioconductor classes. However, I would like to ask you to consider that the package is working perfectly fine as it is and the requested changes would require a significant amount of time. I am finalising the revision for the manuscript about ddPCRclust, which has been submitted to Bioinformatics, and I would very much like to be able to include the link to Bioconductor in the final version of the paper. Could you point out to me which changes absolutely have to be done before the package can be accepted on Bioconductor, so I can prioritise appropriately in order to have a chance to make it in time?

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink

Thanks for making those changes. 

It is understandable that making the requested changes will take a significant amount of
time. In the time being, your package will be accepted. Hopefully, you consider making
these changes as you continue to maintain and develop your package. 

Thank you for submitting to Bioconductor.

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Please fix the errors and I will accept your package. Thanks.

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink 

We prefer that the package be supported on both Windows architectures.
You can try using [appveyor](https://www.appveyor.com/) to check your package on the Windows platforms if it is easier.

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Please disregard the `martini` issue reference. It was a typo. 
Best,
Marcel

**Comment by bgbrink** [comment]
Hi Marcel, @LiNk-NY 

I set up a VM with Windows 10 and also followed your advice and built the package with appveyor (https://ci.appveyor.com/project/bgbrink/ddpcrclust). I can not reproduce the error in any case, all test run though just fine on both i386 and x64.

**Comment by LiNk-NY** [comment]
Hi Benedikt, @bgbrink 

Thanks for looking into it and providing the link!
I will mark your package as accepted. Thank you for your submission!

Best regards,
Marcel

**Comment by bgbrink** [comment]
Hi Marcel, @LiNk-NY

thank you for this constructive review process. As promised, I just changed the license to Artistic-2.0. Thank you for your patience!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bgbrink.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"ddPCRclust\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ddPCRclust

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
