### ISSUE TITLE
tidytree: A Tidy Tool for Phylogenetic Tree Data Manipulation

### ISSUE THREAD

**Issue by GuangchuangYu** [Bioconductor/Contributions#578]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GuangchuangYu/tidytree

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by GuangchuangYu** [comment]
Here is the online vignette, <https://guangchuangyu.github.io/tidytree/>, for your reference.

This package fill the gap between existing Bioconductor packages [treeio](https://bioconductor.org/packages/treeio/) and [ggtree](https://bioconductor.org/packages/ggtree/). 

+ treeio: parsing data
+ tidytree: manipulating data
+ ggtree: visualization

**Comment by lawremi** [comment]
The tbl_tree class lacks an explicit definition and contract for what data it contains.  It would probably be best to define it as an S4 class but in a "tidy" tabular shape, like a GRanges.  Verbs from the tidyverse could then be defined as methods with that class in the signature. It could even derive from the S3 tibble class. The tidygraph approach is also relevant, where it stores the data internally as a formal graph object, to take advantage of the efficiency and abstraction that it might provide.

**Comment by GuangchuangYu** [comment]
@lawremi Thanks for your suggestion. 

I have added a `valid.tbl_tree` function for checking `tbl_tree` object contains, and all the methods for `tbl_tree` object will check the object before processing it.

Defining S4 method seems not a good idea, as it introduces inconsistent and set barrier for new users. Simplicity is the first priority IMO.

**Comment by lawremi** [comment]
No one said you'd have to define S4 methods. Just an S4 class.

**Comment by GuangchuangYu** [comment]
Sorry for the typo, I mean 'defining S4 class'. 

The object is just a `tibble` with *parent*, *node* and *label* columns required.

The `tbl_tree` object class attribute is to make sure that methods designed to work with `tbl_tree` will not be called by using ordinary `tibble` object. Now the `valid.tbl_tree` function will make sure that calling `tbl_tree` methods using ordinary `tibble` object with `tbl_tree` class attribute will throw friendly error message.

Since no extra slot is needed, I don't think define S4 class is good idea, and users can directly using dplyr verbs to summarize evolutionary evidences e.g. of different clades/trunks.

**Comment by lawremi** [comment]
S4 classes are almost? always a good idea. For example, how would we even know that the tbl_tree is supposed to derive from tibble, when that is not defined in a single place, but is instead implicit in the code, in many different places? How would we know to call this newly invented `valid()` function, when S4 already gives us `validObject()`? There is no guarantee that the validity is checked when creating a new tbl_tree. By containing the tibble class, all of the dplyr stuff should just work.

**Comment by GuangchuangYu** [comment]
> By containing the tibble class, all of the dplyr stuff should just work.

This is exactly what I intend to do in this pkg.

>How would we know to call this newly invented valid() function, when S4 already gives us validObject()? There is no guarantee that the validity is checked when creating a new tbl_tree.

[Phylogenetic tools in R](https://cran.r-project.org/web/views/Phylogenetics.html) rely extensively on `phylo` object defined in the important core phylogenetics package `ape`. The`tbl_tree` should be created by `as_data_frame` method defined in `tidytree` pkg.

All the other classes including S4 classes (such `phylo4d` defined in `phylobase` and `treedata` defined in `treeio`) are derived from `phylo`. I also provides converter `as.treedata` to convert `phylo4d` to `treedata` and `as_data_frame` method to convert `treedata` to `tbl_tree`. Of course using my methods will guarantee the validity of the object.

Creating `tbl_tree` without using my converters is possible, if the users have expertise to manipulate tree structure. Even using S4, you can't guarantee users to create invalid object that pass validity check.

**Comment by lawremi** [comment]
What is your objection to using an S4 class here? Just make an S4 class, and we can move forward.

**Comment by lawremi** [comment]
Here is the code

```
setClass("tbl_tree", contains="tbl", validity=valid.tbl_tree)
```

**Comment by GuangchuangYu** [comment]
The reason is I only need 1 component, a tibble. If I need more slots, I will definitely use S4 class.

**Comment by lawremi** [comment]
An S4 class is not just about slots, as I said before. You can just put that `setClass()` into your package and then define a constructor like:
```
tbl_tree <- function(tbl_df) new("tbl_tree", tbl_df)
```
And call that instead of `class<-()`.

**Comment by GuangchuangYu** [comment]
I know and I want to keep things simple as possible. As I said before, all I need is a data frame, and hiding it in S4 introduces inconsistent and set barrier for users.

This pkg is intend to use tibble and introduces users to use verbs of tidyverse to manipulate tree data. After their manipulation, the tibble may not necessarily be a valid tree object. In this case, if I defined `tbl_tree` S4 class and allow users to perform such manipulation, the output should also be a simple ordinary data frame but not a `tbl_tree` object. There is no guarantee as you expected and only introduce inconsistent. 

If the output object is still a valid tree object, *e.g.* linking external data to phylogeny as I presented in the vignette, users can convert it back to `phylo` or `treedata` and employ other comparative methods or models that implemented in other packages to analyze the tree with data. 

I have created enough tree classes in my `treeio` package, and don't want to create a new one in tidytree. Validity of tree structure is not guaranteed after data manipulation, since I don't want to restrict the possibility of what users can do or can not. 

The validity of tree structure will be guaranteed only when converting the object to `phylo` or `treedata`, which can be further analyzed, exported to newick/nexus file, *etc.*.

**Comment by GuangchuangYu** [comment]
The ecosystem of this field rely heavily on `phylo` object. Manipulating `phylo` or derivative objects are frustrated as the components are fragmented. 

The tidytree pkg is not to introduce new tree object but open the door for users to manipulate tree data, to map their own data to phylogeny, *etc.*.

If user want to analyze the tree, they still need to convert it back to `phylo` object as almost all R packages in phylogenetics support it.

**Comment by lawremi** [comment]
I think you're misunderstanding my proposal. All you need to do is define the inheritance relationship and validity contract within the S4 system. There is no need to represent the data outside of the tibble structure, although you could do that internally like tidygraph does.

**Comment by GuangchuangYu** [comment]
sorry, I decided to withdraw this submission.
