### ISSUE TITLE
TarMet

### ISSUE THREAD

**Issue by hcji** [Bioconductor/Contributions#591]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hcji/TarMet

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Before this package is added to our moderation and review queue, it requires a vignette that fully describes its use. I realize that this is primarily a shiny application, but I anticipated that you can illustrate the steps and outcomes through screen shots and especially FULLY EVALUATED code chunks.

When you have revised your package, please make a comment including @mtmorgan indicating that it is now ready for review.

**Comment by hcji** [comment]
@mtmorgan  I have already add test of all exposed functions to the vignette.

**Comment by LiNk-NY** [comment]
Hi Ji, @hcji

Please see the build report. There appears to be some errors in the vignette.
Can you have a look at this?

Thanks,
Marcel

**Comment by hcji** [comment]
Hi Marcel, @LiNk-NY 

This is because I pushed some new funtions, which was not completed yet. I thought only the release would be reviewed. So, I roll back to the previous version for review. The remained warning comes from over-size of the built help document, may be it can be ignore ?
By the way, is there any way to push the new functions and not be considered ? Do I have to create a new repository for this ?

Ji

**Comment by LiNk-NY** [comment]
Hi Ji, @hcji

Is the package ready for submission? 
Perhaps the submission to the issue tracker is too soon.
If you'd like, you can re-submit the package once you're finished development.

Regards,
Marcel

**Comment by hcji** [comment]
Hi Marcel, @LiNk-NY 

Yes, it is ready. Maybe some other functions will be added, but they are totally independent ones.
The reason why the submission to the issue tracker is soon is that this is my first contributation, and there are many more demands of bio-conductor check than  R CMD check, so I have to fix them one by one. Anyhow, I think it is ready.
Thank you,

Ji

**Comment by LiNk-NY** [comment]
Hi Ji, @hcji 

What do you mean by "totally independent ones"? 
I'm not sure why you can't add them now since it seems you have those functions ready.

You can run `BiocCheck` locally and fix the package that way.

The issue tracker is not meant to support ongoing development of a package.
We expect complete packages.

I can give you more time to add those functions and address any major issues
that arise from running `BiocCheck` such as using `vapply` instead of `sapply` etc.

Regards,
Marcel

**Comment by hcji** [comment]
thank you. i deside to develop some more functions. when i finish, i will reopen this issue.

**Comment by hcji** [comment]
Can I withdraw the submission ? @LiNk-NY
