### ISSUE TITLE
switchde

### ISSUE THREAD

**Issue by kieranrcampbell** [Bioconductor/Contributions#60]
- Repository: https://github.com/kieranrcampbell/switchde/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Hello, 
I have reviewed your package and have a few comments to address: 

NAMESPACE: 
1. you shouldn't need importFrom(dplyr,filter) when you already import the entire dplyr package with import(dplyr)
2. Please consider adding the imports and imports from suggested in the package build report to remove the "no visible global function definition" notes: 
Consider adding
  importFrom("methods", "is")
  importFrom("stats", "coef", "dnorm", "lm", "median", "optim",
             "p.adjust", "pchisq", "var")
  importFrom("Biobase", pData")
  importFrom("numDeriv", "grad")
3.  We would appreciate if you could also correct the package build report notes on "no visible binding for global variable".   See  `?globalVariables`

R CODE: 
You shouldn't need "::"  when calling functions from the package "dplyr" as it should be imported from the specification in the namespace. 

VIGNETTE:
1. If the directories switchde_vignette_cache and switchde_vignette_files are not necessary please remove. 
2. Please add a section utilizing Bioconductor object. According to the man page, it seems like these functions can utilize a SCESet of scater but there is no example.  Please add in this example to the vignette in a separate section. 
3. Add an installation section including: 
 ```
source("https://bioconductor.org/biocLite.R")
biocLite("switchde")

```


MAN
If sanitise_inputs and sigmoid can be run by user, please provide an example.  

README
Should also contain the instructions for installing using `biocLite()` as demonstrated above in addition to the devtools method.

**Comment by kieranrcampbell** [comment]
Hello,

Thanks very much for your help and feedback. I think I've addressed all the above issues with the exception of the following:

> importFrom("numDeriv", "grad")

Since grad is only used in the `test_that` functions then `library(numDeriv)` there should be sufficient?

> Please add a section utilizing Bioconductor object. 

This has been added but inline with the current example, since except for the initial function call `switchde(...)` the rest of the examples would be identical.

> If sanitise_inputs and sigmoid can be run by user, please provide an example.

These are meant for internal use only but documented using roxygen2 for consistency.

Thanks

Kieran

**Comment by lshep** [comment]
Thank you for clarification. 
Could you add @keyword internal to the man pages for sanitise_inputs and sigmoid

**Comment by kieranrcampbell** [comment]
> Could you add @keyword internal to the man pages for sanitise_inputs and sigmoid

This has been fixed in the latest commit.

**Comment by lshep** [comment]
Thank you for making these changes. The package looks okay now and I will recommend be accepted. You should get svn instructions via email in the next couple of days.

**Comment by kieranrcampbell** [comment]
Thanks very much.

Kieran

**Comment by kieranrcampbell** [comment]
Hello,

I still haven't received any email, just wondering if I should have?

Kieran

**Comment by lshep** [comment]
Sorry for the delay. It is in the list to get sent out, you should get it soon.
