### ISSUE TITLE
Submission of "srnadiff" to BioConductor

### ISSUE THREAD

**Issue by mzytnicki** [Bioconductor/Contributions#601]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mzytnicki/srnadiff

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Before this package can be added to the review queue, it needs to have a 'real' vignette with evaluated code chunks (using `\```{r}...` rather than indenting code chunks). Please update your repository, bump the version (to 0.99.1), confirm that the package build and check steps conform to Bioconductor guidelines, and post a short comment here indicating that your package is ready for review.

**Comment by mzytnicki** [comment]
I updated the vignette with code chunks.  Sorry for the mistake.
CRAN checks and BioC checks give no error nor warning.
Version is now 0.99.1.
Thank you!

**Comment by mzytnicki** [comment]
It seems that the only warning/error so far comes from the Windows build, with

    ERROR: dependency 'Rsubread' is not available for package 'srnadiff'

because Rsubread is not available on this OS (something that I did not know).

**Comment by lshep** [comment]
Please continue to debug the package. When the package has a clean build/check I will review further.  If you are having troubles feel free to ask on the devel mailing list.

**Comment by lshep** [comment]
I believe this has to do with a dependency package -  I will rebuild your package manually when we think it is resolved on our end.

**Comment by mzytnicki** [comment]
Thank you very much for your support.  Actually, it seems that I found a bug recently introduced (i.e. the day before yesterday) in the devel distribution.  I sent a message [here](https://support.bioconductor.org/p/104759/), and the follow-up is [there](https://support.bioconductor.org/p/104764/).  I am waiting for their answer and their fix, hoping that it will be solved soon.

**Comment by lshep** [comment]
I think this has been correct.  I am kicking off a manual build to hopefully get a build report for us both to look at. Cheers

**Comment by mzytnicki** [comment]
Cool!  Glad the problem was solved, thanks!
Just let me know how/when to proceed.

**Comment by lshep** [comment]
I'm having trouble trying to build your package locally. When I run I get the following: 

```
lori@lori-HP-ZBook-15-G2:~/pkgReview$ R CMD build srnadiff/
Bioconductor version 3.7 (BiocInstaller 1.29.3), ?biocLite for help
* checking for file 'srnadiff/DESCRIPTION' ... OK
* preparing 'srnadiff':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... ERROR
... 164 elements found...
... Annotation step done.
Constructing object...
... done.
Starting Naive step...
  ... 32 regions found.
... Naive step done.
Starting HMM step...
  Building data...
  ... data built
  Computing p-values...
  ... values computed
  Running HMM...
  ... HMM run.
  ... 4 regions found.
... HMM step done.
Starting slice step...
  ... 37 regions found.
... slice step done.
Quitting from lines 56-65 (srnadiff.Rmd) 
Error: processing vignette 'srnadiff.Rmd' failed with diagnostics:
could not find symbol ".Object" in environment of the generic function
Execution halted
```

**Comment by mzytnicki** [comment]
Thanks for your feedback.
That is strange.  Could you please give me your session info if possible?

**Comment by lshep** [comment]
It looks like it actually was coming from a dependency that was fixed in yesterdays build.  I will have a review for you soon.

**Comment by mzytnicki** [comment]
Relieved...

**Comment by lshep** [comment]
Hello, 

The package looks very good some minor comments and clarification below: 

**Build Report** 

- [ ] Please add unit tests 

**R Code**

- [ ] Some functions might benefit from checking the input of arguments to make sure that the correct format is being passed in.  For instance, sRNADiffExp, checking if annotation is not NULL that is was given a GRanges object,  if replicates and conditions have to be the same length checking for that unless this won't cause issues?,  etc ... Evaluate functions and see if some argument checks are appropriate. 

- [ ] The defaults chosen for 
readWhoeGenomeAnnotation/readMiRBasePreAnnotation/readMiRBaseMatureAnnotation -
are these standard based on a particular instrument output or standard to the
file format? 

Else the package looks good.  Please address or comment on the issues above.  If there are any changes in code remember to do a version bump to kick off a new build and let me know when it is ready for me to take a second look.  Thank you for your submission to Bioconductor

**Comment by mzytnicki** [comment]
Thanks for your feedback.  I will try to implement the suggestions ASAP.

**Comment by mzytnicki** [comment]
Hello!

Here is what I did:

- Added unit tests on almost all functions/methods.
- Checked the user inputs.  Actually, there are few inputs.  I also added validators.
- I also tried to describe my choices concerning the annotation imports in the vignette.

Did I answer your requests?

Thanks again for your support.

**Comment by lshep** [comment]
Thank you.  Yes .

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mzytnicki.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"srnadiff\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/srnadiff

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
