### ISSUE TITLE
(inactive) BioDataome

### ISSUE THREAD

**Issue by kliolak** [Bioconductor/Contributions#606]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mensxmachina/BioDataome

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Before this package can be added to the review queue, please review the package guidelines and submission instructions. There are basic problems with the current version, including no License: field and an incorrect version number. Remember that you should run your package through R CMD build, R CMD check (on the build product) and R CMD BiocCheck (after installing the BiocCheck package) using the 'devel' version of R and Bioconductor.

When your update is complete please post a comment here including the tag @mtmorgan

**Comment by kliolak** [comment]
Update completed @mtmorgan

**Comment by dvantwisk** [comment]
Hello,

It looks like this package still has a few errors.  Are you still working to correct them?

**Comment by dvantwisk** [comment]
Hello,

Are you still working on this package?  Please respond to let us know or I will close this issue two weeks from now.

**Comment by kliolak** [comment]
Hello,
yes we are still working on this package. We had some unplanned tasks to
sort out but on Monday BioDataome will become a priority.
Please accept my apologies for this inconvenience.
Kind Regards,
Klio

**Comment by dvantwisk** [comment]
It's no trouble to us!  We just want to make sure the packages we are reviewing are active.

**Comment by dvantwisk** [comment]
Hello,

It's been a few weeks and I just want to message you again to check if this issue is still active.  If you won't be able to work on this package for a long period of time, it may be best to close the issue and reopen it once you have more time.  We plan to have a new Bioconductor release in early May, so If you want your package to be included in that release, it will need to be accepted by mid-April.  Please message me back and feel free to ask for any help if it is needed.

**Comment by kliolak** [comment]
Hello, we will do our best to complete any changes before mid-Arpil. We are
currently working on it. Thank you very much for your help and patience.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Απαλλαγμένο
από ιούς. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dvantwisk** [comment]
Just messaging you back to check in on your progress.  This is another two week notice.  Do you want to keep this issue open?

**Comment by kliolak** [comment]
Yes, please

On Mon, Mar 26, 2018 at 10:18 PM, Daniel Van Twisk <notifications@github.com

**Comment by kliolak** [comment]
@dvantwisk, I just pushed to github the new version of BioDataome.

**Comment by dvantwisk** [comment]
Please perform a version bump on your package to initiate the build.

**Comment by kliolak** [comment]
@dvantwisk, I have already pushed to github a new version of BioDataome (v. 0.99.2). Why version bump is still required ?The previous one was v. 0.99.1
Many thanks

**Comment by dvantwisk** [comment]
Try performing a version bump now.

**Comment by dvantwisk** [comment]
Hello,

I'm just sending out this message to those who are still working on their packages.  The package needs to be accepted by April 16th to be included in the upcoming Bioconductor 3.7 release.  Please have your package ready soon to allow time for the review and subsequent changes that may need to be made.

**Comment by dvantwisk** [comment]
Hello,

It's been a while since any updates were made on this issue.  Are you still working on this package?  If not, I'm going to mark this issue as intactive within the next two weeks.

**Comment by dvantwisk** [comment]
I haven't heard back about this project in two weeks, so I'm going to close the issue for now.  You can reopen the issue when you are prepared for further work on the package.
