### ISSUE TITLE
tRNAscan2GRanges

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/Contributions#607]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/FelixErnst/tRNAscan2GRanges

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
There is a lot of low-hanging fruit for optimization and cleanup. The vignette needs to be developed: what is the tRNA-SE format, where is it encountered, what are some typical things people do with the data once they've imported it? The vignette section on the "Literature" seems to contain the wrong content.

**Comment by FelixErnst** [comment]
I added some more detailed information in the vignette. Could you specify, what you mean with cleanup?

Apart from the little example case scenario, which is now part of the vignette, a typical usage case will be part of a follow up package, but I wanted to split this functionality since it is straight forward and contained.

**Comment by lawremi** [comment]
By cleanup I mean the parser code. It should be vectorized, rather than looping over rows and blocks in R.

**Comment by FelixErnst** [comment]
Thanks for insisting. I previously didn't come up with a vectorized solution. Learned something :)

**Comment by FelixErnst** [comment]
I added some visualization to the vignette and removed some clashes with gff3 naming conventions. Currently I don't have anything more to add.

**Comment by FelixErnst** [comment]
@hpages @lawremi 
Hi. just wanted to ask if you have any additional points I should take care of? Thanks

**Comment by hpages** [comment]
Hi @FelixErnst ,
I started to look at tRNAscan2GRanges and will provide some feedback here today.
H.

**Comment by FelixErnst** [comment]
Hi @hpages, any news?

**Comment by FelixErnst** [comment]
Hi @hpages 
I am sorry to bother you again. Is there any feedback you can provide? Thanks!
Felix

**Comment by FelixErnst** [comment]
@hpages Thanks for the feedback.

In any case: After renaming the package, the github URL would change. Would I need to resubmit it under the new name?

**Comment by FelixErnst** [comment]
First things first: Thanks again for the feedback. First submissions are always tricky and the feedback is so important to learn from ones "mistakes".

1. I renamed the package to tRNAscanImport and the main function `import.tRNAscanAsGRanges` analogous to `import.gff3` from the rtracklayer package . As suggested a direct conversion to a gff3 compatible GRanges object can be triggered by setting `as.gff3 = TRUE` and `tRNAscan2GFF` expects a _GRanges_ as input, so it can be converted from compatible input independently of the origin of the _GRanges_ object.

2. Do you mean the _ID_ column? That is a bit of functionality, which one has to have, since tRNA have sometimes multiple copies per chromosome. I followed the naming convention SGD uses. In my opinion, that is the most robust naming scheme, to ensure unique IDs.

3. Done on the types. Apart from the numeric/integer values, the export.gff3/import.gff3 looks much alike the output of `tRNAscan2GFF`.

4. Done

5. Done

6. Regarding the width issue: I will open an issue one the BiocStyle repo. The reason for the wrapping probably is, that the character vector in tRNA_str does not have a space in in it. So I don't know, how that can be resolved in BiocStyle. It could be solved by extending the XStringSet for something like DotBStringSet (dot bracket annotation of nucleotide secondary structure), which would than behave like DNAStringSet masking longer sequences.

Since the build broke because of some path not found, I assume it was because of the renaming. The Webhook also does not work anymore, since the BioC build system does not know about the package with the new name. ("Sorry, you haven't told us about this repository, please go to https://github.com/Bioconductor/Contributions/issues/new .")

I opened another issue with renamed package: https://github.com/Bioconductor/Contributions/issues/645
Is that the right procedure or should/can I do something else?

**Comment by hpages** [comment]
Yes, opening a new issue is the right procedure. I'll close this one and follow-up on the new one. Thanks!
