### ISSUE TITLE
fsgor

### ISSUE THREAD

**Issue by DanWiebe** [Bioconductor/Contributions#623]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/DanWiebe/fsgor

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Before your package can be added to the review queue, it must be modified to contain vignette(s) with evaluated code chunks (e.g., .Rmd format, `{r}` code chunk annotations). Your package should also be modified to use core Bioconductor infrastructure to represent common data objects, and should not 'reinvent the wheel' by implementing functionality that already exists, e.g., use `GSEABase::getOBOCollection()` to parse obo files.

It is surprising that your package does not make use of, e.g., in the vignette, Bioconductor's extensive annotation resources, e.g., the [GO.db][1] package.

[1]: https://bioconductor.org/packages/GO.db

**Comment by mtmorgan** [comment]
Sorry, the package was added to the review queue prematurely; it must still be updated as outlined in an earlier comment.

**Comment by lshep** [comment]
Please see the above comments and modifications that will need to take place before an official review. Thank you.

**Comment by lshep** [comment]
Could you please respond with your intention to work on this package to form to Bioconductor standards.  If there is no response, in another week we will decline the package and close the issue.  You can reopen or start a new issue at a later time if you so wish.

**Comment by DanWiebe** [comment]
Yes, I will continue my work on the package.
All the best, Daniil Wiebe

**Comment by lshep** [comment]
There has still be no updates and no commits to your github repository - If there is no progress I will close the issue.  You can reopen when you are ready to push changes and continue working.

**Comment by lshep** [comment]
You can reopen the issue when you are ready for a review.
