### ISSUE TITLE
NADDA (non-alignment domain detection algorithm for protein sequences)

### ISSUE THREAD

**Issue by armenabnousi** [Bioconductor/Contributions#626]
https://github.com/armenabnousi/naddaR

**Comment by nturaga** [comment]
naddaR review
===============

This is an **initial** review, once you have made these changes I will follow up with a secondary review of the package.

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

* Description section needs more, think of it like a paper abstract.

## Vignette

* Doesn't use BiocStyle

* Looks incomplete and references are not filled out.

## man

* Man pages missing for functions which are exported. Please make sure
  to use document all your functions.

## R

* Do not use sapply and 1:len for iteration.
  Correct the following NOTEs in your build report,

```
* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply() found in files:
    nadda_functionized.R (line 76, column 30)
    nadda_functionized.R (line 379, column 30)
    nadda_functionized.R (line 702, column 31)
    nadda_functionized.R (line 707, column 20)
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
    nadda_functionized.R (line 76, column 37)
    nadda_functionized.R (line 379, column 37)
    nadda_functionized.R (line 388, column 58)
    nadda_functionized.R (line 684, column 45)
    nadda_functionized.R (line 690, column 45)
    nadda_functionized.R (line 769, column 57)
    nadda_functionized.R (line 776, column 57)
```


* Remove commented out code in your files, you should only keep
  comments which document functions, or additional helper
  documentation. No dead code.

* Replace `print` statements with `message` to print to stdout. Do
  this everywhere you use "print".

* Use
  formatR(https://cran.r-project.org/web/packages/formatR/index.html),
  to format your code to be more readable.

* Your function names contain both `_` (underscore) and `.` and
  `camelCase`.  This makes it very hard for a user to know what your
  function names are. Follow a specific style guide,
  http://adv-r.had.co.nz/Style.html.

* There is no need to remove `rm(rank, share, l, nproc)` objects at
  the end of the function, or anywhere in between as well. R does
  garbage collection automatically. Do this everywhere.

* Just make the parallel package you use a dependency in the
  DESCRIPTION file in Enchaces field. It avoids the usage of this "if"
  statement.

    ```
    if ("pbdMPI" %in% installed.packages()[,1]) {
                        seqs <- parallel_read_AA(obj, nproc)
                        distributed <- TRUE
    ```

	You should just make a utility function and reuse this code chunk,
	
	```
	if (!requireNamespace("pdbMPI")) {
		stop("Install package if you want to use parallel ......")
	}
	```

* In your functions , you can vectorize a lot. Example:

```
extract_seqs_lengths <- function(d) {
        #print("inextract_seqs_lengths")
        lengths <- sapply(d, function(seq) {
                seq <- toString(seq)
                len <- nchar(seq)
                len
        })
        lengths <- data.frame(seqs=names(lengths), lens=lengths)
        lengths <- setorder(as.data.table(lengths))
        setkey(lengths, "seqs")
        return(lengths)
}
```

The whole sapply to get the lengths is not needed, you can replace that with this:

```
lengths <- nchar(toString(d))
```

Do this everywhere and check which functions are vectorized before using them with sapply or vapply or lapply.

**Comment by nturaga** [comment]
Hi @armenabnousi 

Please reply within 2 weeks with the corrections. If not we can always close the issue, and reopen when you have time to work on the package.
