### ISSUE TITLE
CCPROMISE: Integrating Two Forms of Molecular Data with Multiple Biologically Related Endpoints

### ISSUE THREAD

**Issue by xueyuancao** [Bioconductor/Contributions#63]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/xueyuancao/CCPROMISE

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by xueyuancao** [comment]
I have pushed the new commit to github. I have fixed all the requirements and recommendations. I have checked the CCPROMISE package using BiocCheck in windows system without any requirements and recommendations, but with 5 considerations. 

Thanks,

**Comment by dtenenba** [comment]
Looks like you did not [set up a webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) to let us know about your pushes. Please follow those instructions, then bump the version again (to 0.99.1; 0.99.z is the appropriate version number for a package in devel), then commit and push.

**Comment by xueyuancao** [comment]
I set up the webhook and push the changes. Thanks,

**Comment by vobencha** [comment]
Hi,

Please see comments and suggestions below.

(1) Please break up your R code and rename the files to something like

CANN.R

CCPROMISE.R

etc.

(2) Remove commented out code chunks in all R code.

(3) Reformat all R code (R/, man/, vignettes/)  be max 80 characters wide.

(4) NAMESPACE exports

If you want to export every function defined in your package you should use this in the NAMESPACE:

exportPattern("^([^.]|\\..+\\.)")

If you want to choose which functions you export use the export(), exportMethods() directives. As an fyi, remember that each function you export should have a corresponding man page.

You currently "export all functions" with the above pattern and use export(). Please choose one or the other and make sure you have man pages for all exported functions.

(5) data/

Please add more information to the man page for the datasets. State where the data came from, what type of data, what samples are included if any etc.

(6) man pages

These issues need to be fixed on all function man pages - CANN, CCPROMISE, PROMISE2, etc.

i) silence functions

When I run the examples, a large amount of data is output to the screen. This should not be the default behavior. If you want the option to see all of this add a 'verbose' argument. Even in that case, 'verbose' usually only prints limited information as the function is progressing. Please silence your functions or add a 'verbose' argument.

ii) put the correct class for \value

Most functions out put a list. The \value should say the function outputs a lists, say how long it is and what the names are. For example, after running the CANN.Rd example I see the out put is a list:

> class(test1)
[1] "list"

of length 3 with these names:

> names(test1)
[1] "res"    "gen"    "candtl"

I would recommend more descriptive names. It's not clear what 'candtl' is supposed to stand for. Becuase this name is exposed to the user it should be something more intuitive.

(7) datSet.Rd

If this function is used internally by CANN() maybe the user doesn't need it ... ? If there is no need to export it you don't need a man page. If you do export it the man page needs to be cleaned up.

i) Please rename 'thisPrb' to a more appropriate (descriptive) name.

ii) The output class is matrix, not data.frame as stated:

> class(seldata)
[1] "matrix"

iii) Explain the output dimensions and why they are what they are:

> dim(seldata)
[1] 151  89

iv) Explain the column names:

> head(colnames(seldata))
[1] "cg00466425" "cg00934322" "cg01386080" "cg01598675" "cg01936707"
[6] "cg02313535"

(8) vignette

This sentence does not make sense:

The PROMISE package depends on {\em Biobase}, {\em CCP}and {\em PROMISE}  ...

If I understand correctly, you've built upon what is available in the PROMISE package and extended it for a) two data sets and b) canonical correlation. Please clearly state that in the vignette. It's important to give credit where credit is due. If I've misunderstood, please explain how your package is different from what is offered in PROMISE.

Let me know if you have questions.

Valerie

**Comment by vobencha** [comment]
Are you planning to submit a new version or should I close this issue? You can open another one when you are ready to resubmit.
Valerie

**Comment by xueyuancao** [comment]
Please keep the issue open. I am planning to submit a new version. I am kind of missing the communication. Thanks,

**Comment by xueyuancao** [comment]
I am a kind of confused by the version number. I use 0.99.2. Do I need increase the the version number?

**Comment by xueyuancao** [comment]
I shorten most lines to 80 characters. But, I have to leave some lines to be more than 80 characters to make the code readable.

**Comment by vobencha** [comment]
Have you addressed the issues raised in https://github.com/Bioconductor/Contributions/issues/63#issuecomment-236465244? If yes, please explain what was fixed and how.

Valerie

**Comment by xueyuancao** [comment]
I have addressed most of the issues raised in #63 (comment) as below:
1) Break the R file into individual R files:
CANN.R
CCPROMISE.R
datSel.R
PrbCor.R
PrbPROMISE.R
PROMISE2.R
2) Removed all comments in all R files.
3) Reformated most  R code (R/, man/, vignettes/) be max 80 characters wide. Some are still more than 80 characters due to readability.

4)NAMESPACE 
export("CCPROMISE", "PrbPROMISE", "CANN", "PROMISE2", "PrbCor")
removed exportPattern("^([^.]|\..+\.)") 

(5) data/
Add more information to the man page for the datasets. 

(6) man pages
i) The running output has been silenced. 
ii) I have put the correct class for \value 'list' with names renamed to be more meaningful.

(7) datSet.Rd
Removed from export in NAMESPACE and removed from \man

(8) vignette
The PROMISE package depends on {\em Biobase}, {\em CCP}and {\em PROMISE} ...
has been changed to "The CCPROMISE package extends our former PROMISE package to integrate two forms of molecular data with multiple biologically related endpoints in gene level or probe set level." 

I think I have addressed most points of your suggestions in last comment. 
Thank you very much for your help and patience in the process.

Bests,

Xueyuan

**Comment by vobencha** [comment]
Thank you for making the changes. The package is looking much better. A few last things to clean up.

- Is the datSel() function necessary? It isn't used by any internal function. Can it be removed?
- Remove CCPROMISE.pdf from the vignettes/ directory. Vignette products are built automatically when R CMD build is run; we don't want static pdf, html files etc. in svn.
- Man pages for the data files in data/ should state where the data came from. Are the data simulated? Were they downloaded from a web site and processed?

Valerie

**Comment by xueyuancao** [comment]
I have made following changes without change Version number:

    1) datSel() function is definition necessary. It is used by other function and can be removed.
    2) Removed CCPROMISE.pdf from the vignettes/ directory.
    3) Man pages for the data files in data/ stated that there are conceptional data sets. 
The package involves complex data structure. We include example data sets so that the software can be demonstrated.

Thanks,

Xueyuan

**Comment by vobencha** [comment]
Thanks for making the changes, I'm marking the package as approved. You will get an email in the next week with svn credentials and next steps.
Valerie

**Comment by xueyuancao** [comment]
Thank you very much for your kindly help and quick response.

Bests,

Xueyuan
