### ISSUE TITLE
(inactive) SEQprocess

### ISSUE THREAD

**Issue by hgwoo** [Bioconductor/Contributions#634]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SYSMED/SEQprocess

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your package does not have a vignette with evaluated code chunks, and does not (re) use standard and well-established Bioconductor representations for NGS analysis (e.g., GenomicRanges, SummarizedExperiment, rtracklayer::import()). Use of these data structures enables interoperability between packages and facilitates robust software developement. With a vignette or use of Bioconductor objects, your package is not appropriate for Bioconductor.

If you revise your package around these concerns, and follow the Bioconductor guidelines in the new submission form, then please post a comment including @mtmorgan and indicating that your  package ready for reconsideration.

**Comment by hgwoo** [comment]
@mtmorgan

**Comment by hgwoo** [comment]
@bioc-issue-bot #669

**Comment by mtmorgan** [comment]
Is your package now ready for moderation and review?

**Comment by hgwoo** [comment]
Hi @mtmorgan  , 

SEQprocess provides pipelines that perform quality control, sequence alignment, variant calling, and annotation of sequence variations. Processing of NGS data are carried out by multiple methods according to the data types to be analyzed. These multiple processes can be run sequentially as a single and customized pipeline. (using fastQC, tophat2, bwa, cufflinks, gatk, picard, annovar.....)

I would like to submit the SEQprocess package to bioconductor, please let me know what you need to modify or add.
Thank you!

**Comment by mtmorgan** [comment]
My original comment was here https://github.com/Bioconductor/Contributions/issues/634#issuecomment-362240916

Looking again, I do not think your package fits well with Bioconductor -- it relies heavily on external tools that our build system will not have available. The vignette cannot be evaluated and the software tested in an automated way. Bioconductor users expect to work with well-defined objects and perform in-memory, interactive computation whereas your package provides a way of orchestrating a work flow of third-party tools. I am going to decline this package for these reasons.
