### ISSUE TITLE
powerTCR

### ISSUE THREAD

**Issue by hillarykoch** [Bioconductor/Contributions#635]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hillarykoch/powerTCR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please avoid checking in .Rhistory, .Rdata, and other files that are not part of the source code of your package. See [these instructions][1].

[1]: https://help.github.com/articles/ignoring-files/

**Comment by hillarykoch** [comment]
@lshep @mtmorgan My only error is for not being subscribed to the bioc-devel mailing list, but I am subscribed (hillary.koch01@gmail.com) I have double-checked by logging in and looking for my email

**Comment by lshep** [comment]
Hello, 

Thank you for your interest in Bioconductor.  Please see initial comments below:

**BUILD REPORT** 
- [ ] Add unit tests
- [ ] Checking coding practice about sapply and 1:n structures
- [ ] Add runnable example to Parse.Rd

**README**
- [ ] I'm not exactly sure why you took this out but update to include
Bioconductor installation instructions as originally had - you can include
both github instructions and Bioconductor instructions. 

**VIGNETTE/CODING:**
- [ ] clarification question - can there be infiniate number of samples? In your example data
you show 2 - can this be any number? 
- [ ] Vignette and sample code should also use coding practice advice of build report
- [ ] For future reference there does exists AtomicList structures in IRanges, like IntegerList or NumericList for lists of a consistent type 
- [ ] It might be nice to have a specific show method and accessors for the "most important" or each value of output (ie.  nllh(fits) would give the nllh output)
- [ ] Density, distribution, and quantile functions, plus simulating data section: you said you have to specify each modle parameter but it looks like you use default arguments from running your functions - and the original vector is stored in your function output so realistically couldn't the argument to
qdiscgammagpd be 'fits' with a designated sample - if the user specifies an argument than use specified argument but else calculate based on default from 'fits' 
- [ ] Doing comparative analysis section: The code in this section again appears like it could be better hidden within a function and the user only need to specifiy the object,  then a selection of
defaults could be used to do the calculation.  It seems like distance, grid calucation and argument defaults all could be within this wrapper function. 

**NOTE**
I'm not going to insist on this, given that a class designed for this seems slightly overkill and its reuse would be unlikely,  but for future reference you may consider designing packages with a designated class structure (S4 class) for output and input to other functions/methods (reusing any Bioconductor infastructure is most ideal).  This is a more formalized way to define output/input and we strongly suggest it. This also allows for easier customized accessor methods, show methods, etc .... Given that the output is more list like and variable with statistical output, again I won't insist on it but just something to keep in mind for future Bioconductor submissions.   

 Please address the above issues and/or comment with clarification or justification.  When you are ready for another review ensure that a new build is generated with a version bump and comment back here in some way addressing the above concerns for a second review. Thank you. 

Cheers.

**Comment by hillarykoch** [comment]
Thank you @lshep for your helpful comments. I have made several changes to the package in response to your recommendations.

**Build Report**

- Added unit tests
- Changed instances of sapply to vapply and 1:n to seq_along(n)
- Concerning Parse.Rd, unfortunately I don't have runnable examples. The function is a wrapper for functions in the tcR package that are convenient for getting data into the form used by powerTCR (although powerTCR only requires a very simple vector). While I have used the tcR package before, I have not used the functions parse.file and parse.folder. This is simply because I have not worked with files in the format supported by parse.file and parse.folder (though I'm sure others do) -- I added the wrapper at the end of development in case others might find it helpful. Actually, although the tcR package has a very nice vignette, it also provides no runnable examples for parse.file and parse.folder in the vignette of help files. The takeaway here is that I simply don't have shareable data that is in the format needed by the file parser.

**README**
I took the Bioconductor installation instructions out because I thought maybe I was being a little bit premature. I put it back, however.

**Vignette/Coding**
- You can use any number of samples (in comparative analysis I use 3). I keep it small just for computational purposes. I added a line of clarification in the vignette.
- It appears the all of my code is compliant with expectations. There are some warnings about lines being too long, but these appear to be in .Rd files that automatically wrap in the help file.
- I added accessor functions for the important output values and updated the vignette to describe them.
- For density, distribution, quantile functions and simulation, I added the ability to pass a model fit. However, I also kept the ability to specify all parameters. This feels very natural as all of R's standard tools for density, distribution function, etc are like this. This is now in the vignette as well.
- I totally agree with the remarks about JS_desponds and JS_spliced. I added a wrapper called JS_dist, and described it in the vignette. I do believe the user should specify their own grid, so now the user only needs to pass model fits, a grid, and the type of model they are passing. Of course, the function stops if they pass fits from different models to JS_dist.

**NOTE**
I thought about S4 classes much after I started this project, but decided against it because I thought it might be a lot of trouble for such simple data types. Definitely for future development I need to (and am) familiarize myself with the selection of classes out there and make sure that code is in line with relevant S4 classes for given assays.

**Comment by lshep** [comment]
Thank you for your updates a few more comments below: 

**Vignette**
- [ ] Please update the code in the vignette to also not use 1:n and use seq_along or seq_len where appropriate. 
- [ ] The *my paper* is bold and with no link? Is there a reference somewhere? 

Cheers

**Comment by hillarykoch** [comment]
Hi @lshep 

Thanks, I changed the vignette. The __my paper__ thing was just a placeholder for me so that I could go back and drop the paper reference in there, when available. Our paper is in its final stages before submitting to a journal, and we wanted to be able to point to a package available when submitting. Currently there is no pre-print as one of the data sets we analyzed is unpublished and the data generators are not ready to publish it yet. However, we could possibly have a preprint in the near future. Of course I am happy to change the "__my paper__ " to whatever you think is appropriate.

Cheers-

**Comment by lshep** [comment]
Maybe add a **my paper(pending)** so that users aren't confused.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hillarykoch.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"powerTCR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/powerTCR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
