### ISSUE TITLE
Geneplastdata submission

### ISSUE THREAD

**Issue by sheylatrefflich** [Bioconductor/Contributions#640]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sheylatrefflich/geneplast.data.string.v91

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by sheylatrefflich** [comment]
Dear Bioc Reviewer,
Thank you for assigning our data package for review. We have updated the package according to the automatic checks and we believe the package is ready for reviewing.
Sincerely,
Sheyla

**Comment by nturaga** [comment]
geneplast.data.string.v91 review
================================

##  R CMD build

ok

## R CMD Check

ok

## DESCRIPTION

ok

## Vignette

* missing.

* Take the vignette as an opportunity to describe how to load and use
  your data, and document where the data came from.


## data

* Consider converting cogdata to a RSQLite database since it's larger. (427Mb)

## NEWS

* Consider adding a NEWS file which can be parsed by utils::news().

**Comment by mtmorgan** [comment]
Thanks for your email. It's appropriate to continue reviewing this annotation package here. 

One possibility is to make this an 'AnnotationHub' package. The big data would be stored as resources on AnnotationHub, your package would have a few light-weight functions that made it easy for users to download the resources they want. This seems particularly  appealing because of the size of the data, and because the version number at the end of your package implies that you might have in mind additional versions in the future. See the [vignette for creating AnnotationHub resources][1] for more information. At any rate the first step is to address the relatively minor points raised by Nitesh.

[1]: http://bioconductor.org/packages/devel/bioc/vignettes/AnnotationHub/inst/doc/CreateAnAnnotationPackage.html

**Comment by mtmorgan** [comment]
I'm checking in on the progress on this package. It looks like there are some review comments outstanding. Do you wish to continue revising your package?

**Comment by sheylatrefflich** [comment]
Dear Bioc Reviewers,

Thank you for all suggestions. We have improved our data package and the new version is now available at our git repository. Please see below our point-by-point reply for the Reviewer suggestions. 
Please let us know any other questions or suggestions.

We look forward to contributing with Bioc and our community. 

Sincerely,

Sheyla Trefflich



#---------------------------------------------------
# Bioc Reviewer1 (Nitesh Turaga)

(1) Bioc Reviewer1: 
Vignette missing. Take the vignette as an opportunity to describe how to load and use your data, and document where the data came from.

Authors: Thank you for this suggestion. We totally agree, the Vignette is the best way to provide examples to users on how to use our packages, and Bioc provides a robust framework to make sure all packages are accompanied by this documentation. The point here is that we are submitting a data package that is built to work with the Geneplast software (http://bioconductor.org/packages/devel/bioc/html/geneplast.html), which provides the Vignette with all relevant examples. We have now improved the Geneplast Vignette, including a new case study that shows how "geneplast.data.string.v91" is used in the workflow. Please see section 3 (Case studies, at 3.1. High-throughput rooting inference).

(2) Bioc Reviewer1: 
Data. Consider converting cogdata to a RSQLite database since it's larger. (427Mb)

Authors: The size of the data package is actually much smaller, it is only 19,1 MB. We have further compacted the R objects within the package. Giving this small size and how the package is used in the Geneplast software, we think a data matrix would be the simplest solution. For example, in order to compute Geneplast statistics we need to provide the universe size (i.e. all information in the Geneplast.data), so the full data table would be required for all analyses (please see the new "case study" section at Geneplast Vignette).

(3) Bioc Reviewer1:
NEWS. Consider adding a NEWS file which can be parsed by utils::news().

Authors: Thank you, we have included a NEWS file.

#---------------------------------------------------
# Bioc Reviewer2 (Martin Morgan)

(1) Bioc Reviewer2:
Thanks for your email. It's appropriate to continue reviewing this annotation package here.
One possibility is to make this an 'AnnotationHub' package. The big data would be stored as resources on AnnotationHub, your package would have a few light-weight functions that made it easy for users to download the resources they want. This seems particularly appealing because of the size of the data, and because the version number at the end of your package implies that you might have in mind additional versions in the future. See the vignette for creating AnnotationHub resources for more information. At any rate the first step is to address the relatively minor points raised by Nitesh.

Authors: Thank you Martin. We've considered this suggestion. Please see our responses to Nitesh's suggestions, we believe both are aligned to this issue.
