### ISSUE TITLE
RSeqAn

### ISSUE THREAD

**Issue by aguang** [Bioconductor/Contributions#652]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/compbiocore/RSeqAn

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Can you clarify your relationship to the SeqAn development team, and the reason for wrapping the original BSD license in MIT?

**Comment by aguang** [comment]
@mtmorgan There is no relationship, I wanted to package the SeqAn headers for easy use in a different R package. I wasn't sure how to write the license. Originally I was just going to include their LICENSE file and use the BSD 3-clause. Some of the license sites said the MIT license was essentially the same as the BSD. I can change the license back to BSD and include their file instead if that makes more sense.

**Comment by mtmorgan** [comment]
Can I ask you to communicate with the SeqAn people to confirm that they are aware of your effort and approve? Of course the license allows that to happen but this is a courtesy. And yes, the license should reflect the license of the underlying code, so BSD-3.

**Comment by aguang** [comment]
I've emailed them, waiting to hear back for a response. Updated the license to BSD-3. The SeqAn library has support for Visual C++, clang and ICC on Windows, but doesn't have support for mingw. I've attempted a few changes but haven't been able to get it to pass the checks. Will this be a problem?

**Comment by LiNk-NY** [comment]
Hi @aguang, 

Sorry for the delay. 
I am CC'ing Martin @mtmorgan about your question here. 

Regards,
Marcel

**Comment by mtmorgan** [comment]
Generally Bioconductor discourages submission of packages that are not supported on all platforms. An exception can be made in this case.

**Comment by aguang** [comment]
Thanks. I am also getting some help from the SeqAn development team to build in mingw-w64 support so if I am able to get it to build and pass checks I will definitely update.

**Comment by LiNk-NY** [comment]
Hi August, @aguang 
Please see the short review below. 
Keep us updated about supporting all platforms. 

Regards,
Marcel

---

# RSeqAn #652

A header files package for R from SeqAn. 

* Please make sure that it is compatible in all supported platforms.

## DESCRIPTION

* No need for the `Date` field.
* You can optionally combine `Author` and `Maintainer` fields with the
`Authors@R` field.
* I don't think you need a `RoxygenNote` field.

## vignettes

* Looks good.

## NAMESPACE

* I don't think you need a `NAMESPACE` file

## ../RSeqAn pkg folder

* You can get rid of the `*.Rproj` file as there is no R code in the package.

**Comment by aguang** [comment]
@LiNk-NY thanks for your comments. I've made all the changes except for the `NAMESPACE` file (the package won't build if it's not included...?) and it now is supported on Windows as well.

**Comment by LiNk-NY** [comment]
Hi August @aguang 
It builds for me locally without the `NAMESPACE`. What kind of error are you getting? 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
You may also want to include a more descriptive title to your vignette. 
Other than that. It looks ready to do go. 
Thanks!

**Comment by aguang** [comment]
I get the following from running `R CMD build RSeqan`:

`* checking for file ‘RSeqAn/DESCRIPTION’ ... OK
* preparing ‘RSeqAn’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘RSeqAn’ ...
ERROR: a 'NAMESPACE' file is required
* removing ‘/private/var/folders/xk/1630rnpd1_9fzr8vlhxjrx_w0000gn/T/RtmpC3NFX8/Rinst7101da79ac6/RSeqAn’
      -----------------------------------
ERROR: package installation failed`

**Comment by LiNk-NY** [comment]
Hi August, @aguang 
It works for me. I'm using R 3.5 and Linux. 

```
platform       x86_64-pc-linux-gnu                               
arch           x86_64                                            
os             linux-gnu                                         
system         x86_64, linux-gnu                                 
status         Under development (unstable)                      
major          3                                                 
minor          5.0                                               
year           2017                                              
month          11                                                
day            21                                                
svn rev        73765                                             
language       R                                                 
version.string R Under development (unstable) (2017-11-21 r73765)
nickname       Unsuffered Consequences                           
```

R automatically creates a `NAMESPACE` for you with `exportPattern(".")` in it. 
You can just add that line in your `NAMESPACE` and it should be fine.

Regards,
Marcel

**Comment by PeteHaitch** [comment]
Re need for NAMESPACE
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Found out today.  Minimum req for <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> package to install: DESCRIPTION file.  Min req for <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> package to pass R CMD check --as-cran: DESC + NAMESPACE file.</p>&mdash; John Muschelli (@StrictlyStat) <a href="https://twitter.com/StrictlyStat/status/984105693551702017?ref_src=twsrc%5Etfw">April 11, 2018</a></blockquote>

**Comment by aguang** [comment]
I changed NAMESPACE to just `exportPattern(".")`, will that be ok? I am not sure why it will not build without a NAMESPACE for me. I am running R/3.4 and macOS.

**Comment by LiNk-NY** [comment]
Hi August, @aguang 

Yes, that's okay. 
BTW, you should be developing with bioc-devel and thus `R >= 3.5.0`.

Regards,
Marcel

**Comment by LiNk-NY** [comment]
I will mark your package as accepted.
Thank you for contributing to Bioconductor!

Best,
Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/aguang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"RSeqAn\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RSeqAn

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
