### ISSUE TITLE
CAGEfightR

### ISSUE THREAD

**Issue by MalteThodberg** [Bioconductor/Contributions#659]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MalteThodberg/CAGEfightR

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by MalteThodberg** [comment]
The package now passes checks, except the warning for having too low an R-version.

I would greatly prefer to keep the R-version at 3.4, as we are currently several people using the package by installing from GitHub via devtools. I would be super inconvenient to have to force all these users to use the development version of R. When the release date approaches, I will be happy to bump up the R-version.

**Comment by MalteThodberg** [comment]
Dear @nturaga,

Please do let me know if there's anything I need before the review process to move along. I'm more than happy to implement changes and suggestions.

**Comment by pkimes** [comment]
Just a quick comment from a fellow R developer (not affiliated with Bioconductor) regarding the R versions. 

Why not just create a separate branch that uses R version 3.4 (maybe called `R-3.4`) and update your `master` branch to meet the Bioconductor requirements? Collaborators can still install the package using `devtools` with the `ref =` argument:
```
devtools::install_github("MalteThodberg/CAGEfightR", ref = "R-3.4")
```

Alternatively, if you don't think you'll be updating the R-3.4 version of the package (and therefore don't need a separate branch), you can just use the current commit hash (or create a tag) as the value to `ref =`:
```
devtools::install_github("MalteThodberg/CAGEfightR", ref = "96d5650")
```

**Comment by nturaga** [comment]
@MalteThodberg I will review your package in the next week.

**Comment by nturaga** [comment]
Hi @MalteThodberg Please remove the .html and the .R files from your `vignettes` directory.

**Comment by nturaga** [comment]
@MalteThodberg Make sure to check all the NOTE messages you get in the build report and correct as many as possible. Most of them are pretty easy to fix.

**Comment by MalteThodberg** [comment]
I've tested the package under Rdevel 3.6 now, with the following notes:

- I am not planning on implementing unit tests at this stage.
- The functions lacking documentation are deliberately commented out, since they take too long to run
- There are a few lines longer than 80 left in the man pages, I cannot fix these as they are generated using roxygen2
- I have used tabs instead of 4 spaces consistently, so I would prefer not to change between these.

**Comment by nturaga** [comment]
Hi @MalteThodberg 

Please fix the indentation in your code. An easy fix is to use `formatR`. 

```
formatR::tidy_dir(path = "CAGEfightR/R")
```

As a reviewer it's very hard for me to review your code as it renders like this, 

![screen shot 2018-04-05 at 9 42 27 am](https://user-images.githubusercontent.com/2746443/38369522-e37a2cde-38b5-11e8-8bfa-5ac73f519cd1.png)

Consistent coding style and indentation make it a lot easier for me to review the code.  This is a Bioconductor recommended format, http://bioconductor.org/developers/how-to/coding-style/. I suggest you follow it.

**Comment by MalteThodberg** [comment]
I've reformatted the entire package with formatR as you specified.

**Comment by nturaga** [comment]
# CAGEfightR review

## R CMD BUILD

ok

## R CMD INSTALL

ok

## DESCRIPTION

* Description is insufficient, it should be like the abstract of a
  paper.


## NAMESPACE

* ok

## Vignettes

* ok

## R

* There is no need to remove objects from R using `rm`, R does this
  automatically. Please remove `rm` calls throughout your code.
  
```
R/assign.R
184:	rm(antisense)
278:	rm(TSSs, extendedGeneModels)

R/cluster.R
54:	rm(coverage_stranded)

R/combine.R
67:	rm(os)
74:	rm(shared_assays)
81:	rm(shared_cols)
94:	rm(new_meta)

R/enhancers.R
25:	rm(pooled)
33:	rm(P)
41:	rm(covByStrand, M)
137:	rm(cw)
171:	rm(A, B)
183:	rm(scores, peaks, balance, viewsA, viewsB)
194:	rm(o_ids)
278:	rm(mat_plus, mat_minus)

R/quantify.R
173:	rm(plus_strand, minus_strand)

R/shape.R
66:	rm(covByStrand)
72:	# rm(coverage_plus, coverage_minus)
88:	rm(TCsByStrand)
94:	rm(stat_plus, stat_minus)

R/track.R
58:	rm(by_strand)
153:	rm(object)

R/trimTo.R
101:	rm(coverage_stranded)
108:	rm(tcs_stranded)
126:	rm(views_plus, views_minus)
138:	rm(left_plus, right_plus, left_minus, right_minus)
144:	rm(coverage_plus, coverage_minus, irl_plus, irl_minus)
231:	rm(coverage_stranded, peaks)
238:	rm(tcs_stranded)
244:	rm(coverage_plus, coverage_minus, irl_plus, irl_minus)

R/tune.R
59:		rm(steps_series)
72:	rm(by_strand)
```

**Comment by MalteThodberg** [comment]
I have updated the Description, so it's ready for next review.

As explained above, the use of rm() is intentional in the few functions that do the heavy lifting. It greatly improves memory usage by removing very large RleLists, IRanges and GRanges when they are no longer needed.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MalteThodberg.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"CAGEfightR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CAGEfightR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
