### ISSUE TITLE
Rmmquant

### ISSUE THREAD

**Issue by mzytnicki** [Bioconductor/Contributions#684]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mzytnicki/Rmmquant

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
nturaga will review your package; for interoperability and reproducibility, the main output of your function should be a [SummarizedExperiment][1] rather than simple count matrix.

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by mzytnicki** [comment]
Thank you.
I will change the count matrix to a SummarizedExperiment, and fix the bugs ASAP.

**Comment by mzytnicki** [comment]
Done!
The output matrix is now a SummarizedExperiment, and there is no warning.
Awaiting your comments now.

**Comment by nturaga** [comment]
# Rmmquant package review

## R CMD build

ok

## R CMD check

ok

## DESCRIPTION

* Description not enough, think of it as a Abstract for a paper.
* Maintainer is not needed, if you have Authors@R

## NAMESPACE

* ok

## man

* ok

## vignette

* The most important part of the vignette is not being run, the chunk
  `deseq2` should be run, where you use the `RmmquantRun` function.

## R

* Format code using formatR for your RcppExports.R.

**Comment by mzytnicki** [comment]
Thank you very much for the comments.  I am currently working on it.

Finding a good example working with `DESeq2` will not be easy, because the quantification step takes time, especially with more than 100 genes, and at least 4 samples (required by `DESeq2`).  Yet, I hope I will make it.

However, I am afraid I cannot format `RcppExport.R` with `formatR`.  `RcppExport.R` is generated automatically by `Rcpp`, and `formatR` seems to alter the computer-generated format.
For instance, the first lines of the file:

    # Generated by using Rcpp::compileAttributes() -> do not edit by hand
    # Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

are transformed into:

    # Generated by using Rcpp::compileAttributes() -> do not edit by hand Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

which will interfere with `Rcpp`.  Actually, a (somewhat) similar comment has been addressed in this [thread](https://github.com/r-lib/styler/issues/215), and it has been suggested to exclude this file.

Yet, I would be glad to take any suggestion about correcting the format of  `RcppExport.R`.

**Comment by nturaga** [comment]
Hi, You can keep the formatting of `RcppExport.R` as is.

**Comment by mzytnicki** [comment]
Hello.
The previous build report was not very informative, but I managed to add a small example with `DESeq2` in the vignette.
Is it what you expected?

**Comment by nturaga** [comment]
Hi @mzytnicki Please issue a new build by bumping the version number.

**Comment by nturaga** [comment]
Hi @mzytnicki 

The warning is related to the size of your package. Software packages have to be under the 5MB limit. Your package exceeds that size.

These files in particular which you are using for the example,

```
1.8M	./inst/extdata/Homo_sapiens.gtf
3.1M	./inst/extdata/SRR1047863.bam
2.0M	./inst/extdata/SRR1047864.bam
2.2M	./inst/extdata/SRR1047865.bam
2.4M	./inst/extdata/SRR1047866.bam
2.6M	./inst/extdata/SRR1047867.bam
3.0M	./inst/extdata/SRR1047868.bam
2.7M	./inst/extdata/SRR1047869.bam
3.4M	./inst/extdata/SRR1047870.bam
2.9M	./inst/extdata/SRR1047871.bam
2.8M	./inst/extdata/SRR1047872.bam
2.6M	./inst/extdata/SRR1047873.bam
2.6M	./inst/extdata/SRR1047874.bam
```

I'm not totally sure if you need them for your example case. Maybe @mtmorgan can chip in and advice you on how to make the example smaller and fit the software package requirements. 

Best,

Nitesh

**Comment by mzytnicki** [comment]
Thank you very much for your feedback.

This what I realized when the WARNING were issued, and what I expected when I added an example compatible with DESeq2.
I will try to fix it soon, by reducing the files even more.

Matthias.

**Comment by mtmorgan** [comment]
consider also re-using existing Bioconductor resources, e.g., 
```
library(AnnotationHub)
hub = AnnotationHub()
query(hub, c("Homo", "gtf", "ensembl", "92"))
cache(hub["AH61126"])  # make a local copy; once only
fileName(hub["AH61126"])
```
and an ExperimentData package http://bioconductor.org/packages/release/BiocViews.html#___ExperimentData containing BAM files (search for 'bam').

**Comment by mzytnicki** [comment]
Excellent!
I will try that.  Thanks!

**Comment by mzytnicki** [comment]
@nturaga I implemented the suggestions, and corrected another bug.
The build issues warnings, but the "WARNING count" on the three platforms are "0"...
Strange.

Please let me know if everything looks fine for you.

Matthias.

**Comment by mzytnicki** [comment]
I decided to restart a build (without changing the code).
It seems to build without problem.

**Comment by nturaga** [comment]
@mzytnicki Ok, I will review your package once more.

**Comment by mzytnicki** [comment]
@nturaga Thanks a lot!
Actually, I just implemented your suggestions, as well as @mtmorgan's.
And a few more tests, too.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mzytnicki.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"Rmmquant\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Rmmquant

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
