### ISSUE TITLE
alpineData

### ISSUE THREAD

**Issue by mikelove** [Bioconductor/Contributions#69]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mikelove/alpineData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mikelove** [comment]
AdditionalPackage: https://github.com/mikelove/alpine

**Comment by vobencha** [comment]
Looks good. Approving alpineData.

**Comment by mikelove** [comment]
Any update on alpineData and alpine getting in devel?

**Comment by vobencha** [comment]
Martin is a little behind. He's going to work on these over the next couple of days ... sorry for the delay.

**Comment by mikelove** [comment]
Sorry if this is unnecessary noise, but I just wanted to check and see if the software package `alpine` that is attached to this issue will also be showing up in devel soon. I just got the "alpineData has been added to Bioconductor" email.

**Comment by vobencha** [comment]
Hi Mike,
Completely my fault. With this new tracker additional packages get buried in the issue. 
This 6 month cycle we're using R 3.3. for both release and devel; please change DESCRIPTION to R>=3.3 and resubmit. 
Thanks.
Val

**Comment by mikelove** [comment]
I believe alpine already has R >= 3.3:

https://github.com/mikelove/alpine/blob/master/DESCRIPTION#L10

**Comment by vobencha** [comment]
Ah yes it does. I was looking at the older SPB report. I'll let Martin know there is an accompanying software to go with the data and we'll get it in asap.
Val
