### ISSUE TITLE
IGV

### ISSUE THREAD

**Issue by paul-shannon** [Bioconductor/Contributions#704]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/paul-shannon/IGV

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by paul-shannon** [comment]
The dependency on BrowserViz (>= 2.0) should work tomorrow:  I checked in that update to BrowserViz mid-day today.

**Comment by lawremi** [comment]
A little surprised by the naming choice being exactly the same as the underlying library. Why not rigv or something? Makes it easier to google and talk about. Also IGV stands for _integrative_ genomics view, not _integrated_.

**Comment by paul-shannon** [comment]
Thanks for the correction on integrative - will fix.

The underlying library is formally and colloquially "igv.js".  I don't see a euphonious place to add an "R" to that.  I figure - reasonable people may differ!- that, in context, in actual use, the R-ness of the software will be well known; that what is wrapped will be instantly recognized.  

The vignette is incomplete and, as of late last night, broken.  Temporary files seem to get lost, but only with knitr in the mix.  I think.  Will tacke that today.

 - Paul

**Comment by paul-shannon** [comment]
Michael - I consulted with Jim Robinson.  He agreed with you regarding the utility of a distinctive name, and suggested igvR as the least awkward of the possibilities we could came up with.

**Comment by paul-shannon** [comment]
The build reports (except for Windows, where BrowserViz 2.0 is not available - a separate problem) all report that R CMD build, with vignettes, takes more than 10 minutes.  On my old lap top, they take < 3 minutes.   The vignette will likely hang if no browser opens on the build machine.  Maybe that's the problem?  I recall that Dan Tenenbaum engineered a way for this to work.

With regards to Windows: "Error : package 'BrowserViz' 1.11.0 was found, but >= 2.0 is required by 'IGV'"  I cannot see the build report for the latest BrowserViz.  Any suggestions?

**Comment by paul-shannon** [comment]
Just removed BrowserViz/.BBSoptions which had this one line - an artifact of early httpuv versions, in which asynchronous communications had not been ported to Windows

  UnsupportedPlatforms: win

IGV should now build as well on Windows as on linux and macos -  or as poorly, if a build system web browser is not available for IGV to connect to.

**Comment by paul-shannon** [comment]
sent to bioc-devel just now, copying here to keep the record complete.

> Once your package builds and checks without errors or (avoidable) warnings, a Bioconductor team member will provide a technical review of your package. Other Bioconductor developers and users with domain expertise are encouraged to provide additional community commentary. Reviewers will add comments to the issue you created.

I don’t believe my submission, IGV, quite fits the mold.  As best I can tell, no web browser can be summoned on any of the architectures by IGV during build or check.  So the package build always times out.  And so, according to the guideline quoted above, it will never be reviewed!

IGV is a BrowserViz version >=2 subclass; BrowserViz was recently uprev’d in devel.  Like RCyjs, IGV's raison d’être is the provision of R access to interactive graphics in your web browser, in this case to Jim Robinson’s igv.js.  

My analysis may be incorrect.  Can this matter receive a little attention, despite the bioc submission guideline quoted above, in hopes that the package can move forward?

Thank you,

- Paul

**Comment by hpages** [comment]
Hi Paul,

What about the renaming to igvR? If that is indeed the plan, please submit again in a new issue. Thx!

H.

**Comment by paul-shannon** [comment]
Thanks, Herve’.  I will do that right now.  It might take an hour or two before you see it.

Will you be doing the review?   I’d be delighted!

 - Paul

**Comment by hpages** [comment]
Someone else will probably do it. I'll be on vacation for the next 9 days. Hopefully the review will be quick and smooth.

H.

**Comment by hpages** [comment]
Closing this issue then.
