### ISSUE TITLE
contributing TxRegInfra

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/Contributions#708]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/vjcitn/TxRegInfra

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment]
On the face of it, it's not clear why a package that interfaces with mongo would also need to make plots, like via Gviz. Seems like there should be some abstraction layer in between.

**Comment by vjcitn** [comment]
The plots are there to give a concrete view of what kinds of information
can be handled in this setup.  What's the motivation for a RaggedMongoExpt?
One motivation is that epigenetic findings that are managed irregularly in
a tissue-specific way can be used to direct interest to one or another
transcripts of a gene.  The plot used in the vignette aims to illustrate
this
motivation.  We could stop with RaggedMongoExpt but it seemed worthwhile
to go a bit further.  I do get the point that there might be a concern with
scope creep, but data visualization should be pretty natural in a vignette.
I would like to do some more work to minimize the imports and perhaps Gviz
could go to Suggests.

**Comment by lawremi** [comment]
Sure, Suggests makes sense.

**Comment by vjcitn** [comment]
On Thu, Apr 5, 2018 at 12:21 PM, Nitesh Turaga <notifications@github.com>
wrote:

> TxRegInfra review R CMD build
>
> ok
> R CMD check
>
> ok
> DESCRIPTION
>
>    -
>
>    The title could be changed to something more informative
>
> done

>
>    -
>    -
>
>    The Description section gives the users very little information. Needs
>    to be more elaborate.
>
> done

Title: Metadata management for multiomic specification of transcriptional
regulatory networks

Description: This package provides interfaces to genomic metadata

        employed in regulatory network creation, with a focus on noSQL

        solutions.  Currently quantitative representations of eQTLs,

        DnaseI hypersensitivity sites and digital genomic footprints

        are assembled using an out-of-memory extension of the

        RaggedExperiment API.



>
>    -
>
> NAMESPACE
>
>    - ok
>
> data
>
>    -
>
>    ok
>    -
>
>    Are these data files needed?
>
>
I will check and remove if possible but I think at least some are used.

>
>    -
>
> inst
>
>    - The legacy folder seems to be not doing anything as all the code is
>    commented out.
>
> Why do these files have to get installed along with the package? I
> don't understand how they are adding value.
>

Gone

> vignettes
>
>    - demo.R doesn't work. You can incorporate it in your vignette if its
>    important, and make sure it's evaluated.
>
> gone

>
>
> > library(TxRegQuery)
> Error in library(TxRegQuery) : there is no package called 'TxRegQuery'
>
>
>    - The vignette could use a little more biological context around line
>    83.
>
> man
>
>    - ok
>
> R
>
>    - Some NOTE's from the build report need to be fixed,
>
>

> Avoid 1:length() and use seq_len and seq_along instead.
>
> done

> Use vapply instead of sapply to return to return the type you expect.
>
> * Checking coding practice...
>     * NOTE: Avoid sapply(); use vapply() found in files:
>     lite.R (line 54, column 9)
>     lite.R (line 55, column 9)
>     lite.R (line 56, column 8)
>     * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
>     lite.R (line 13, column 36)
>     lite.R (line 166, column 39)
>     mongolite.R (line 39, column 35)
>
> done

>  Use getters and setters methods instead of direct slot access with @.
>
> * Checking for direct slot access...
>     Found @ in vignettes/TxRegInfra.Rmd
>     * NOTE: Use accessors; don't access S4 class slots via '@' in
>       examples/vignettes.
>
> done

>
>    - Reformat R code, using formatR, limit lines to 80 chars and wrap as
>    neeed.
>
> formatR::tidy_dir(path="TxRegInfra/R")
>
> this led to some errors ... bad handling of single quotes it seems.  but
repaired.

>
>    - Use system2 instead of system for commands
>
> (system2 is a more portable and flexible interface than system. It
> allows redirection of output without needing to invoke a shell on
> Windows, a portable way to set environment variables for the execution
> of command, and finer control over the redirection of stdout and
> stderr. Conversely, system (and shell on Windows) allows the
> invocation of arbitrary command lines.)
>
> eg:
>
> lis = system(sprintf("mongo %s/%s --eval 'db.getCollectionNames()'", url, db),
>         intern = TRUE)
>
> fullurl = file.path(url, db)
> lis = system2("mongo", args = c(fullurl, "--eval", "'db.getCollectionNames()'"),
> 	          stdout=TRUE)
>
> Why is there use of both system and system2?
>
system2 fully adopted

**Comment by vjcitn** [comment]
Hi What is the fate of this submission?  Thanks

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vjcitn.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"TxRegInfra\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TxRegInfra

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
