### ISSUE TITLE
YAPSA

### ISSUE THREAD

**Issue by huebschm** [Bioconductor/Contributions#71]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/huebschm/YAPSA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by huebschm** [comment]
@hpages 
Dear Bioconductor team,
after submission of my package, building and testing works well on zin1 (Linux) and morelia (Mac OS), but building fails on moscato (Windows):

moscato1 CHECK output:

* installing *source* package 'YAPSA' ...
** R
** data
** inst
** preparing package for lazy loading
Warning: replacing previous import 'ggplot2::Position' by 'BiocGenerics::Position' when loading 'ggbio'
Error in library.dynam(lib, package, package.lib) : 
  DLL 'limSolve' not found: maybe not installed for this architecture?
ERROR: lazy loading failed for package 'YAPSA'
* removing 'D:/packagebuilder/workers/jobs/YAPSA_20160727145534/YAPSA.buildbin-libdir/YAPSA'
Warning: running command 'D:/packagebuilder/R/bin/i386/Rcmd.exe INSTALL --library=YAPSA.buildbin-libdir YAPSA_0.99.4.tar.gz --no-multiarch' had status 1

Looking at the output of the build of other packages, e.g.
http://bioconductor.org/checkResults/release/bioc-LATEST/moscato2-R-instpkgs.html
reveals that the package limSolve, which my package depends on, is installed under R-3.3.0:
limSolve                                          1.5.5.1 3.3.0

Is there anything that can be done to overcome this?
Thank you very much in advance for your help, best Daniel.

**Comment by vobencha** [comment]
Hi Daniel,

YASPA has been transferred to me and I'll be doing the review. I wanted to make sure you saw Martin's response to your questions here

https://stat.ethz.ch/pipermail/bioc-devel/2016-July/009570.html

Valerie

**Comment by huebschm** [comment]
Dear Valeria,
thank you very much for reviewing YAPSA. Indeed I saw Martin's response (thank you very much Martin). I tried out the following:
- install.packages("limSolve") in R-3.3.1 on Windows 10
This worked out, so comparing to the report under 
https://www.r-project.org/nosvn/R.check/r-release-windows-ix86+x86_64/limSolve-00check.html
it seems like it is only an example of limSolve which throws the error.
Of course I can still try to contact the authors of limSolve.
Best Daniel.

**Comment by vobencha** [comment]
I don't understand what you mean by 'this worked out'.

You have 2 choices:
1) use a different dependency (something other than limsolve)
2) contact the author of limSolve to fix the error
Until one of these two is done YASPA will not pass check on windows and cannot be approved.

Valerie

**Comment by huebschm** [comment]
Dear Valerie,
by 'this worked out' I mean that install.packages("limSolve") in R-3.3.1 on Windows 10 doesn't throw an error, and the package limSolve can be loaded and used with e.g. library(limSolve).
But of course, I will try to solve the build problem and am contacting the maintainer of limSolve.
Best, Daniel.

**Comment by vobencha** [comment]
Hi,
Just checking in. Have you found a solution to the limSolve problem ... are you ready for me to do a full review?
Valerie

**Comment by huebschm** [comment]
Hi, the maintainer of limSolve didn't reply. Therefore we were looking for an alternative. It seems like limSolve uses the package lsei, and for the functions we need lsei might be sufficient. What I don't know yet is if lsei builds on windows, but we will try that out.
Best Daniel

**Comment by huebschm** [comment]
Dear Valerie,
I replaced the dependency limSolve by lsei and not there is no more build errer on windows.
Is this a state in which you could start your review?
Thank you very much, best regards Daniel.

**Comment by vobencha** [comment]
Yes, that's good, thanks. I'm looking at it now and should have comments for you by tomorrow.
Valerie

**Comment by vobencha** [comment]
Great job with the vignette and code organization. Comments and suggestions below.

(1) number of exported functions
My biggest concern is that you're exporting 79 objects
~/YAPSA >grep "export" NAMESPACE | wc -l
79

and have over 100 man pages:
~/proj/git/software/YAPSA/man >ls -l | wc -l
108

In general, the number of exported objects should be >= the number of man pages. Everything that is exported needs a man page but if a function is not exported it does not need a man page.

Is it essential the user have access to all these functions? If some (many?) are for internal use only it would be a much cleaner design to not export (and not document) these functions. Please explain.

(2) support VRAnges

Several functions take as input a data.frame of chromosome name, position, alt, ref etc. which is a natural representation for VRanges. As you probably know, VRanges is a commonly used class for variants and supporting this would make it easy for users with data already in VRanges to use your functions.

For functions that operate on this type of data.frame please add support for VRanges. For example, in trellis_rainfall_plot.Rd the 'in_rainfall_dat' argument can be either a data.frame or VRanges.

I'm sure I've missed a few but it looks like these functions support this type of data.frame and should also support VRanges:
trellis_rainfall_plot.Rd
translate_to_hg19.Rd
translate_to_1kG.Rd
annotate_intermut_dist_cohort.Rd
annotate_intermut_dist_PID.Rd
attribute_nucleotide_exchanges.Rd

(3) Please format your code to max 80 characters wide.

(4) non-evaluated man pages

Please explain why these are wrapped in \dontrun:

~/proj/git/software/YAPSA/man >grep dont *
build_gene_list_for_pathway.Rd: \dontrun{
create_mutation_catalogue_from_df.Rd:\dontrun{
create_mutation_catalogue_from_VR.Rd:\dontrun{
cut_breaks_as_intervals.Rd: \dontrun{
run_SMC.Rd:\dontrun{
stratify_and_create_mutational_catalogue.Rd:\dontrun{
stratify_vcf_like_df.Rd:\dontrun{
trellis_rainfall_plot.Rd:\dontrun{

(5) vignette

- Please download and save this figure as a file instead of trying to retrieve it from the web site:
https://upload.wikimedia.org/wikipedia/commons/f/f9/NMF.png

- Add a sentence or two in this introduction paragraph that states what YAPSA offers beyond SomaticSignatures:
"Another package to perform analyses of mutational signatures is available (Gehring et al. 2015) ..."

Let me know if you have questions.

Valerie

**Comment by huebschm** [comment]
Dear Valerie,
thank you very much for your review and your comments. I am almost done with the changes and will post an explanation of the changes once ready.
Best Daniel.

**Comment by huebschm** [comment]
Dear Valerie,
thank you very much for your review and your comments. I am almost done with the changes and will post an explanation of the changes once ready.
Best Daniel.

**Comment by huebschm** [comment]
Dear Valerie,
thank you very much for your review and your comments. I am almost done with the changes and will post an explanation of the changes once ready.
Best Daniel.

**Comment by huebschm** [comment]
Dear Valerie,
I submitted a new version which complies with all of your comments and suggestions:

(1) number of exported functions: The number of exported functions was reduced:
~/software/huebschm/R/yapsa> grep export NAMESPACE | wc -l
69
Technically, it could be reduced further (there are e.g. a few wrapper functions and the functions they call are still exported), but as I use YAPSA in the data evaluation for a few projects, I get the feeling that usability decreases if I reduce the namespace further.

The number of man pages was also reduced:
~/software/huebschm/R/yapsa> ls -al man/ | wc -l
68
Initially there were many separate man pages for the data, but these (as well as some man pages for functions) are now grouped into more comprehensive man pages describing several objects at once.


(2) support VRAnges
trellis_rainfall_plot.Rd: now supports data frames and VRanges as input
translate_to_hg19.Rd: now supports data frames and VRanges as input
translate_to_1kG.Rd: now supports data frames and VRanges as input
annotate_intermut_dist_cohort.Rd: now supports data frames and VRanges as input
annotate_intermut_dist_PID.Rd: now supports data frames and VRanges as input
attribute_nucleotide_exchanges.Rd: now supports VRanges, VRangesList, data frames or lists of data frames as input
make_subgroups_df.Rd: now supports data frames and VRanges as input

(3) Please format your code to max 80 characters wide.
I reformatted all lines which are accessible to me. There are a few exceptions which still are longer than 80 characters:
- some lines in the documentation paragraphs include urls which are longer and cannot be broken
- the lines defining chunk names and chunk options in Rmd in the vignette
- the Rd files (automatically generated by roxygenize(), therefore I haven't edited these manually) 

(4) non-evaluated man pages
- build_gene_list_for_pathway.Rd: \dontrun{: only example left with dontrun. This is a wrapper function for keggFind keggLink from the KEGGREST package. In the example a query is sent to KEGG and the time needed for the evaluation of this example depends on connectivity of the user. Therefore I would suggest to leave this in dontrun{}.
- create_mutation_catalogue_from_df.Rd:\dontrun{: dontrun removed
- create_mutation_catalogue_from_VR.Rd:\dontrun{: dontrun removed
- cut_breaks_as_intervals.Rd: \dontrun{: dontrun removed
- run_SMC.Rd:\dontrun{: dontrun removed
- stratify_and_create_mutational_catalogue.Rd:\dontrun{: function not exported any more
- stratify_vcf_like_df.Rd:\dontrun{: function not exported any more
- trellis_rainfall_plot.Rd:\dontrun{: dontrun removed

(5) vignette
- Please download and save this figure as a file instead of trying to retrieve it from the web site: https://upload.wikimedia.org/wikipedia/commons/f/f9/NMF.png: done
- Add a sentence or two in this introduction paragraph that states what YAPSA offers beyond SomaticSignatures: "Another package to perform analyses of mutational signatures is available (Gehring et al. 2015) ...": done

Thank you very much for your comments and suggestions, best Daniel.

**Comment by huebschm** [comment]
Dear Valerie,
I have the impression that since my last commit, no build has been finished, even though the message 

Received a valid push; starting a build. Commits are:

197fe57 last changes for code review

was sent out. Could this be related to the fact that by increasing the version number I reached 0.99.10 by now, i.e. two digits after the last separator?

Thank you for your help, best Daniel.

**Comment by vobencha** [comment]
Thanks for making the changes and documenting what you did. I'm not sure why the SPB didn't complete - I'll check with Lori. The 'z' portion of the 'x.y.z' version can go as high as you want; there is no restriction on that. More than likely it was related to the closing of the issue. Once we get a clean build/check I'll approve the package.

Valerie

**Comment by huebschm** [comment]
Dear Valerie,
the package has now been built. Thank you for triggering the process. Is the current state sufficient for approval?
Thank you very much again, best regards Daniel.

**Comment by vobencha** [comment]
Yes, looks good. You'll get an email from Martin within the next week with svn credentials and next steps. Thanks again for putting in the extra work to improve the package.
Valerie
