### ISSUE TITLE
eegc

### ISSUE THREAD

**Issue by Sharonxiaoyuan** [Bioconductor/Contributions#73]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Sharonxiaoyuan/eegc
Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by Sharonxiaoyuan** [comment]
Dear Bioconductor team,

I have fixed all errors and warnings of the package, thanks!

Best, Xiaoyuan

**Comment by mtmorgan** [comment]
If you'd like me to review your package now, please bump the version (to 0.99.2) and, if the current version builds without problem, I'll review it.

**Comment by Sharonxiaoyuan** [comment]
Dear Martin,

Sorry for the modifications of package without updating the version, I have updated to 0.99.2 and wait for the build information, if it goes well, please go ahead to review it, thanks very much!

Best, Xiaoyuan

-----原始邮件-----
发件人: "Martin Morgan" <notifications@github.com>
发送时间: 2016年8月19日 星期五
收件人: Bioconductor/Contributions <Contributions@noreply.github.com>
抄送: Sharonxiaoyuan <zhouxiaoyuan@picb.ac.cn>, Mention <mention@noreply.github.com>
主题: Re: [Bioconductor/Contributions] eegc (#73)



If you'd like me to review your package now, please bump the version (to 0.99.2) and, if the current version builds without problem, I'll review it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


Save

**Comment by mtmorgan** [comment]
Your package looks really good, congratulations! I have the following
minor suggestion

DESCRIPTION, NAMESPACE, NEWS

- good

vignettes

- this looks really great!

R. The following are general comments, please review your code for
other examples that adopt the same strategy.

- [1][] uses a 'copy-and-append' strategy, which is very
  inefficient. Also, creating an index using `1:n` instead of
  `seq_len(n)` or something like `seq_along(cate.gene)` causes
  problems when `n` is zero. See [2][]
  
man

- good

[1]: https://github.com/Sharonxiaoyuan/eegc/blob/master/R/enrichment.R#L79-L85
[2]: http://bioconductor.org/developers/how-to/efficient-code/

**Comment by Sharonxiaoyuan** [comment]
Dear Martin,

Thanks very much for the review, I will revise the codes accordingly to adopt the strategy. By the way, do I need to update the version every time when I modify the codes?

Best, Xiaoyuan Zhou

-----原始邮件-----
发件人: "Martin Morgan" <notifications@github.com>
发送时间: 2016年8月24日 星期三
收件人: Bioconductor/Contributions <Contributions@noreply.github.com>
抄送: Sharonxiaoyuan <zhouxiaoyuan@picb.ac.cn>, Mention <mention@noreply.github.com>
主题: Re: [Bioconductor/Contributions] eegc (#73)



Your package looks really good, congratulations! I have the following
minor suggestion

DESCRIPTION, NAMESPACE, NEWS

good

vignettes

this looks really great!

R. The following are general comments, please review your code for
other examples that adopt the same strategy.

1 uses a 'copy-and-append' strategy, which is very inefficient. Also, creating an index using 1:n instead of seq_len(n) or something like seq_along(cate.gene) causes problems when n is zero. See 2

man

good

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


Save

**Comment by mtmorgan** [comment]
Yes, a version bump for each time you update the code, otherwise there are two variations of the package available to the user but with the same version number.

**Comment by Sharonxiaoyuan** [comment]
OK, got it, thanks!

**Comment by mtmorgan** [comment]
Thanks I'll mark the package as accepted. It will be added to the bioc svn repository and nightly builds. More information will be sent in the next several days.
