### ISSUE TITLE
BPRMeth package submission

### ISSUE THREAD

**Issue by andreaskapou** [Bioconductor/Contributions#74]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/andreaskapou/BPRMeth

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by andreaskapou** [comment]
Hi,

This package was written as a support for a paper accepted
(arXiv:1603.08386) at the ECCB 2016 which will be held from 3-7 of
September, and is also accepted for publication in the Bioinformatics
journal.

I will be giving a presentation of my work at the main conference, and it
would be great if I could inform them that my method is available through
Bioconductor.

I would appreciate it if the review process would be quick enough so as to
know about the inclusion of my package before the conference.

Kind Regards,
Andreas

----------------------------------------------------------
Chantriolnt - Andreas Kapourani
PhD Candidate in Data Science,
School of Informatics,
University of Edinburgh

e-mail  : C.A.Kapourani.ed.ac.uk
            : kapouranis.andreas@gmail.com

**Comment by hpages** [comment]
Hi Andreas,

I'm sorry for my slow response. The package looks great and I'm marking it as 'accepted'. It'll be added to the BioC svn repository and to the nightly builds, with further instructions sent to you via email in the next several days.

Congratulations and thanks for your contribution to the project.

Cheers,
H.

**Comment by andreaskapou** [comment]
Hi,

Thanks for the acceptance of the package.

Glad to contribute to Bioconductor!

Kind Regards,
Andreas

**Comment by andreaskapou** [comment]
Hi, 

I saw that Bioconductor 3.4 is released, but I cannot find my package there?

I thought that when a package is accepted it is automatically added to the next release of Bioconductor. May I ask you what is wrong here?

I am looking forward to hearing from you!

Regards,
Andreas

**Comment by andreaskapou** [comment]
Hi,

I still cannot find my package on Bioconductor. Is there anything that I should do in order this to happen?

Thanks!
