### ISSUE TITLE
MetID

### ISSUE THREAD

**Issue by ressomlab** [Bioconductor/Contributions#752]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ressomlab/MetID

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
@dvantwisk will review your package; please remove stray files (e.g., vignettes/.DS_store) from your github repository.

**Comment by ressomlab** [comment]
Dear Reviewer,

MetID package has been updated over a week. Is there any additional step needed before publishing this bioconductor package?

**Comment by dvantwisk** [comment]
I apologize for the delay.  I'm almost finished reviewing your package and should have a review up early next week.

**Comment by dvantwisk** [comment]
Apologies for the delay.  Here is the review.  The [REQUIRED] tags must either be addressed, or the changes made.  The [CONSIDER] tags indicate things that do not need to be changed, but are advisable.  I don't run the code that I right for the packages, so they may not be entirely correct.  Please message me back when you are finished making changes.
```
DESCRIPTION:
- [REQUIRED] L9: This line seems uneeded; please remove it.

R/GENERAL
- [CONSIDER] In documenation for using facing symbols, it is advisible to be as
specific as possible for the user.  For example, in `R/GetScores.R`:L3 it asks
for a `name of a file` as input for a parameter. I am assume it is asking for a
`character` but some packages in Bioconductor include classes for filetypes such
as `rtracklayer` so this may cause confusion for the user. In the same file,
L16-17 specifiy "hyper-parameters" as input for these two parameters. Maybe a
`numeric` or `interger` is meant here, but again, it is not clear.
- [REQUIRED] Use `message()` instead of `print()` for diagnostic messages meant
for users. This is because `message()`s may be toggled easily by the user.
- [CONSIDER] Use `seq_len()` or `seq_along()` instead of `1:...`. Doing this is
slighly more efficient and also catches the unexpected case where `1:0` is
`1 0`.

R/BuildNetworks.R
- [CONSIDER] L9: Since `c` tends to commonly be used with `c()` in R, it may be
best not to use it as a variable here since it may cause confusion. 
- [REQUIRED] L13-27: Much of the conditional complexity seems unnecessary. The
for-loop is also inefficient. `ids` and `indexes` are created in a
copy-and-append pattern which is very ineffienct in R.  Change to:
```
kegg_id <- strsplit(kegg_id, ' ')
kegg_id <- lapply(kegg_id, unique)
ids <- unlist(kegg_id)
indexes <- rep(seq_along(kegg_id), lengths(kegg_id))
```
- [CONSIDER] L80-101: There is a triple for-loop here. Places like this in your
code can dramatically increase the run-time of a function, especially using R.
It's not trivial to me how to improve the run-time, so please look into this
block of code and consider how it could be improved.

R/GetScores.R
- [REQUIRED] L18,129: It doesn't appear that a file is being returned, rather a
`data.frame`. The file seems to be written though, however, I need to ask if it
is necessary to write to the file `scores.csv`? If only the `data.frame` is
returned, the used can choose whether or not they want to write the file
themselves.
- [REQUIRED] L84: Is there a reason `500` is being used? Perhaps the user should
be given the option to input the number of iterations.

R/PreprocessData.R
- [REQUIRED] L45-49: Replace for-loop with:
```
mass_set <- qmass[!duplicated(qmass)]
metid <- match(qmass, mass_set, nomatch=0)
```
- [REQUIRED] L110-121: Since you are already using `stringr`, this entire
function can be replaced with `stringr`'s `word` function such that:
```
response <- word(id, 1)
```
- [REQUIRED] L126-137: Use `vapply()` in place of defining `reponse` and then
iteratively creating `response`:
```
  response <- vapply(id, function(i) {
    if (is.na(i) || !i %in% InchiKey$CID)
      as.character(i)
    else
      substr(InchiKey$InchiKey[which(InchiKey$CID %in% i)],1,14)
  })
```

tests
- [CONSIDER] Add tests to the package using the `testthat` pacakge.
```

**Comment by ressomlab** [comment]
I updated bioc-devel and Bioconductor subscription, can you re-do the report

**Comment by lshep** [comment]
You will need to do a version bump in your DESCRIPTION file to have the report regenerated.

**Comment by ressomlab** [comment]
Hi Package Reviewer,

Do you have any additional feedback for MetID package?

**Comment by dvantwisk** [comment]
The changes so far look good.  I have just a few more things I'd like you to address:

- Line 9 in `DESCRIPTION` is still there.  I'd like to see this removed as it seems irrelevant.
- In `GetScores.R:L130`, I'm not certain the `write.csv()` is necessary.  The user gets the written object as output so the user should just be able to write that object themselves if they want to .  I would recommend removing line.
- In `PreprocessData.R:L119-120`, this seems to be a work in progress.  Are there any more changes to be made here?

**Comment by dvantwisk** [comment]
Hello, have you been making changes to this package?

**Comment by ressomlab** [comment]
This package is been updated yesterday

**Comment by ressomlab** [comment]
There is a webhook issue
Connection: close
Content-Length: 30
Content-Type: text/html;charset=utf-8
Date: Tue, 17 Jul 2018 17:42:24 GMT
Server: Apache/2.4.18 (Ubuntu)
Status: 500 Internal Server Error
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger 5.3.3
X-XSS-Protection: 1; mode=block

**Comment by dvantwisk** [comment]
I do need to ask about this.  When I tried pulling your changes, I got an unrelated history warning.  Your package seemed to have been re-initiated such that there are only two commits now.  Did you mean to do this?

**Comment by dvantwisk** [comment]
Other than the issue above think everything looks fine now and I'm willing to move to accept the package.

**Comment by ressomlab** [comment]
I did not intend to re-initiate the package, what should I do to fix this?

**Comment by ressomlab** [comment]
No, I don't. The package was transferred to me to handle so I did not have the package with all the commits. The local version is the same as the one I uploaded

**Comment by dvantwisk** [comment]
If that is the case, there's not really a way to rebuild the various commits if they are no longer available somewhere.  The package is fine as it is.  The various commits are only useful for tracking who contributed to the package, as well as making it possible to role back any change if they were made at a certain point in the package.  You may consider asking others in the group if they have an older version of the package with the commits, but the package is fine as it is.  Message me back telling me whether you plan on trying to recover the commits are just want me to accept the package as is.

**Comment by ressomlab** [comment]
Hi dvantwisk
Our group member uses this same account to contribute to the project. If you have no problem with this, please go ahead with the approval process, let me know if anything is needed

**Comment by dvantwisk** [comment]
Okay, I will move to accept the package now.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ressomlab.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"MetID\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MetID

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
