### ISSUE TITLE
Anaquin

### ISSUE THREAD

**Issue by student-t** [Bioconductor/Contributions#78]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/student-t/Anaquin

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
In moderating this package, I noticed that sequin.xyz is not accessible (chrome says "www.sequin.xyz’s server DNS address could not be found"); can you please address this?

**Comment by student-t** [comment]
@mtmorgan The URL was probably down for a brief maintenance, it's definitely working now. Please visit "http://www.sequin.xyz".

**Comment by student-t** [comment]
I can't seem to download the log. Can somebody help?

**Comment by student-t** [comment]
R CMD check works for me on Mac OS-X and Linux. I need to access the log to work out why it failed on Bioconductor.

**Comment by student-t** [comment]
The builder is complaining the vignette couldn't be built, but it was just just working in Anaquin_buildreport_20160809024336.html. Then, it stopped working in my next commit. That commit 9b39865 only changed the MAN pages and updated R (>= 3.2) to R (>= 3.3). Does the builder able to build on R 3.3? Otherwise, I don't know why it gave me error message 43.

I was able to build the source on Unix and RStudio.

![screen shot 2016-08-09 at 5 55 55 pm](https://cloud.githubusercontent.com/assets/7627987/17508887/9dc494ea-5e5a-11e6-9ee7-0aa0456298cb.png)

**Comment by student-t** [comment]
I'm talking about "moscato1 BUILD SRC output".

**Comment by vobencha** [comment]
Hi,
Probably an SPB hiccup. I also was able to build locally. I'll go ahead with the review - don't worry about troubleshooting that issue for now.
Valerie

**Comment by student-t** [comment]
Hi,

I fixed English grammar in my latest commit but the builder is reporting errors again. The error message is the same as before (error message 43 in generate a PDF report). Can you please restart the build for me? I will not update anything until further notice.

**Comment by vobencha** [comment]
I don't think another SPB is necessary.  I'll just do the review and we can go from there.

**Comment by vobencha** [comment]
Nice job with the documentation and package in general. A few comments and suggestions below.

(1) sample data

From the man pages it's not clear what the difference is between mixtureA and mixtureB. Please briefly re-explain what an RnaQuin sequin is here so someone who has not read the vignette but comes across the man page can still put this in context

(2) Anaquin class

The old S3 class system of assigning an attribute is no longer encouraged:

  class(r) <- 'Anaquin'

Instead we've moved to the S4 class system which involves setClass() statement, getters and setters.

Anaquin is a very simple structure, a list of length 1 with a data.frame. If this list never has more than one element it doesn't need to be a list. Was there a reason you didn't want to return just a data frame? I realize the plot*() functions require certain columns in the data.frame. Those functions could do some checking to make sure the correct columns are present. If you want this to be a class it needs to be S4 and should have getters to extract data from slots.

(3) createAnaquinData()

i)  I would suggest listing all possible arguments in the function definition so users know what they can control. The arguments should be the 'keys' or metrics the function supports, e.g.,

    keys <- c('sd', 'pval', 'qval', 'ratio', 'mean', 'expected', 'input', 'measured', 'sensitivity', 'label', 'score')

'names' is required so no default for that one. You could use NA, NULL or empty data types.
```
createAnaquinData <- function(names,
  sd=numeric, pval=numeric(), qval=numeric,
  ratio=numeric(), mean=numeric(), expected=numeric(),
  input=numeric(), measured=numeric(), sensitivity=numeric(),
  label=character(), score=numeric()) {
                                                  
...
...
}

```
ii) update the \usage section in the man page to reflect the new arguments

(4) plot function data checks

Each plot functions requires certain fields in 'data'. The first few lines of each plot function should check for these fields and return a sensible error. For example, I prepared 'anaquin' from the plotSensitivity man page and gave it to plotScatter. It's not clear from the error message what's wrong with the data or how it can be fixed.

> plotScatter(anaquin, title=title, xlab=xlab, ylab=ylab, showLOQ=TRUE)
Error: !is.null(data$y) is not TRUE
In addition: Warning message:
In is.na(data$measured) :
  is.na() applied to non-(list or vector) of type 'NULL'

Let me know if you have questions.

Valerie

**Comment by student-t** [comment]
@vobencha 

I've submitted a new update that should address your comments.

1. I've updated the man pages for mixtureA and mixtureB.

2. I prefer S4 class representation because I will expand the project and add new complexity and statistical methods. My new code now uses the S4 class representation to represent an input data set. There are also getters to extract data from slots. The S4 class name is _AnaquinData_.

3. _createAnaquinData()_ is now removed. I have a validation function (_.validate()_ in the code) that checks inputs for each analysis. It should not be possible for a user to create invalid input data. \usage also updated.

4.  Each plot function now checks type of the analysis. For example:

> plotLinear <- function(data, title=NULL, xlab=NULL, ylab=NULL, showSD=FALSE, showLOQ=TRUE, showAxis=FALSE, ...)
> {
>     stopifnot(class(data) == 'AnaquinData')
>     if (analysis(data) != 'PlotLinear') { stop('plotLinear requires PlotLinear analysis') }
>     stopifnot(!is.null(seqs(data)))
>     stopifnot(!is.null(input(data)))
>     stopifnot(!is.null(measured(data)))
>     ......

If we now try to give an invalid analysis, for example:

    data('seqDESeq2')      
    data <- AnaquinData(analysis='PlotLODR',
                            seqs=row.names(seqDESeq2),
                        measured=seqDESeq2$Mean,
                           ratio=seqDESeq2$ExpLFC,
                            pval=seqDESeq2$Pval)  

    # This is invalid because we can't give PlotLODR analysis to plotLinear
    checkException(plotLinear(data, unitTest=TRUE))

we will get an error message: **plotLinear requires PlotLinear analysis**

I have also added some unit tests for input validation.

**Comment by vobencha** [comment]
1) Thanks.

2) Sounds good.

3) Good.

4) Good.

5) Other:

a) Please format code to max 80 characters wide.

b) constructor

Calling the constructor with no args throws an error:

```
> AnaquinData()

Anaquin data for  analysis
Number of sequins: 0

- Use sequins(x) to get sequins
Error in if (aly == "PlotLODR") { : argument is of length zero
```

'analysis' is a required argument. The constructor should either list 'analysis' with no default

```
AnaquinData <- function(analysis, ...) {
...
}
```

or provide the vector of options and choose the first by default with match.arg():

```
AnaquinData <- function(analysis = c('PlotLODR', 'PlotROC', 'PlotLinear', 'PlotLogistic'), ...) {
  analysis <- match.arg(analysis)
  ...
}
```

For example, here's how match.arg() is used in GenomicFeatures::transcriptsBy(). 'gene' is chosen by default.

```
setMethod("transcriptsBy", "TxDb",
    function(x, by=c("gene", "exon", "cds"), use.names=FALSE)
    {
        by <- match.arg(by)
        .extract_features_by(x, "transcript", by, use.names=use.names)
    }
)
```

**Comment by student-t** [comment]
1: All source files are now under 80 characters width
2: I've updated the _AnaquinData_ function. It now does that:

> AnaquinData()
  Error in initialize(value, ...) : 
  argument "analysis" is missing, with no default

**Comment by student-t** [comment]
@vobencha 

1: All source files are now under 80 characters width
2: I've updated the AnaquinData function. It now does that:

> AnaquinData()
Error in initialize(value, ...) : 
argument "analysis" is missing, with no default

**Comment by student-t** [comment]
@vobencha 

I'm not so sure how to address the error message in the build, so I'll just leave it:

    /bin/sh: ../../build-universal.sh: No such file or directory

**Comment by lshep** [comment]
That was a problem with our builder. I will manually kick off a new build for you; it should be corrected.

**Comment by vobencha** [comment]
Thanks for making the changes. I'm marking the package as accepted and you should get an email from Martin in the next week with svn credentials and next steps.
Valerie
