### ISSUE TITLE
BUScorrect

### ISSUE THREAD

**Issue by XiangyuLuo** [Bioconductor/Contributions#781]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/XiangyuLuo/BUScorrect

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by XiangyuLuo** [comment]
Thank you for the information. I am looking forward to your further message.

**Comment by mtmorgan** [comment]
@nturaga will review this package; to enhance interoperability with Bioconductor, please implement an interface that accepts a [SummarizedExperiment][1] as input / output, with a colData() column indicating which batch samples are from.

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by XiangyuLuo** [comment]
@mtmorgan Thank you very much for the great suggestion! After reading through the SummarizedExperiment instruction, I will add "SummarizedExperiment" as an acceptable input to the main R function "BUSgibbs". Users can input an R list (my current input class) or the "SummarizedExperiment" class based on their preferences. 

Regarding the output, it is very difficult to describe the returned values by our main R function "BUSgibbs" as a matrix-like object because the output gives posterior samples as well as posterior estimates for each type of model parameters. Different types of parameters have different dimensions, so I think using an R list for output might be more appropriate. To better clarify the output items, I also provide users with detailed instructions: what each component of the output list means.    

Anyway, I really appreciate your suggestion and will add the "SummarizedExperiment" class as an input to enhance Bioconductor interoperability.

**Comment by XiangyuLuo** [comment]
Hi @nturaga 

Thank you very much for agreeing to review our R package! The package was built with no error or warning two weeks ago. Could you kindly let me know the status of the reviewing process?

Thanks a lot for your precious time on our package!  

Xiangyu

**Comment by nturaga** [comment]
# BUScorrect Review

## R CMD buld

ok

## R CMD check

ok 

## NEWS

* Please include a NEWS file.

## DESCRIPTION

* Description not enough to give a full picture of what the package is
  doing. Please think of this section like the abstract of a paper.

## NAMESPACE

* ok

## man

* ok

## vignette

* Consider using BiocStyle for you vignette.

https://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html

## R 

* [REQUIRED] Make sure your build report is clean. Address all the
  NOTEs before a further review. I'm only pasting one from your build
  report below, but please address all the NOTE sections in
  http://bioconductor.org/spb_reports/BUScorrect_buildreport_20180627000843.html.
  
* [REQUIRED] We are particular about coding standards, follow
  https://bioconductor.org/developers/how-to/coding-style/ . It also
  makes your code easier to read for the reviewer.

```
* Checking coding practice...
	* NOTE: Avoid sapply(); use vapply() found in files:
      BUS_Rfunctions.R (line 17, column 22)
      BUS_Rfunctions.R (line 44, column 25)
      BUS_Rfunctions.R (line 398, column 24)
      BUS_Rfunctions.R (line 484, column 25)
      BUS_Rfunctions.R (line 529, column 33)
      BUS_Rfunctions.R (line 566, column 25)
      BUS_Rfunctions.R (line 769, column 41)
      BUS_Rfunctions.R (line 811, column 42)
      BUS_Rfunctions.R (line 856, column 42)
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
      BUS_Rfunctions.R (line 17, column 29)
      BUS_Rfunctions.R (line 43, column 18)
      BUS_Rfunctions.R (line 44, column 32)
      BUS_Rfunctions.R (line 88, column 18)
      BUS_Rfunctions.R (line 89, column 26)
      BUS_Rfunctions.R (line 91, column 44)
      BUS_Rfunctions.R (line 209, column 10)
      BUS_Rfunctions.R (line 218, column 10)
      BUS_Rfunctions.R (line 223, column 10)
      BUS_Rfunctions.R (line 266, column 10)
      BUS_Rfunctions.R (line 268, column 36)
      BUS_Rfunctions.R (line 281, column 10)
      BUS_Rfunctions.R (line 282, column 18)
      BUS_Rfunctions.R (line 334, column 10)
      BUS_Rfunctions.R (line 350, column 10)
      BUS_Rfunctions.R (line 375, column 26)
      BUS_Rfunctions.R (line 397, column 10)
      BUS_Rfunctions.R (line 398, column 31)
      BUS_Rfunctions.R (line 422, column 10)
      BUS_Rfunctions.R (line 423, column 47)
      BUS_Rfunctions.R (line 424, column 53)
      BUS_Rfunctions.R (line 425, column 59)
      BUS_Rfunctions.R (line 429, column 10)
      BUS_Rfunctions.R (line 431, column 47)
      BUS_Rfunctions.R (line 483, column 18)
      BUS_Rfunctions.R (line 484, column 32)
      BUS_Rfunctions.R (line 528, column 26)
      BUS_Rfunctions.R (line 529, column 40)
      BUS_Rfunctions.R (line 565, column 18)
      BUS_Rfunctions.R (line 566, column 32)
      BUS_Rfunctions.R (line 599, column 18)
      BUS_Rfunctions.R (line 603, column 18)
      BUS_Rfunctions.R (line 612, column 26)
      BUS_Rfunctions.R (line 613, column 34)
      BUS_Rfunctions.R (line 635, column 18)
      BUS_Rfunctions.R (line 698, column 18)
      BUS_Rfunctions.R (line 704, column 18)
      BUS_Rfunctions.R (line 710, column 18)
      BUS_Rfunctions.R (line 768, column 34)
      BUS_Rfunctions.R (line 769, column 48)
      BUS_Rfunctions.R (line 770, column 80)
      BUS_Rfunctions.R (line 772, column 85)
      BUS_Rfunctions.R (line 810, column 34)
      BUS_Rfunctions.R (line 811, column 49)
      BUS_Rfunctions.R (line 812, column 81)
      BUS_Rfunctions.R (line 814, column 80)
      BUS_Rfunctions.R (line 854, column 26)
      BUS_Rfunctions.R (line 855, column 34)
      BUS_Rfunctions.R (line 856, column 49)
      BUS_Rfunctions.R (line 857, column 84)
      BUS_Rfunctions.R (line 859, column 83)
      BUS_Rfunctions.R (line 887, column 18)
      BUS_Rfunctions.R (line 897, column 18)
      BUS_Rfunctions.R (line 901, column 18)
```

Please let me know once your done fixing the issues, I will do a secondary review of your code.

**Comment by XiangyuLuo** [comment]
Hi @nturaga Thank you very much for the great comments and suggestion! I have updated the R packages as follows:

1. News file. I have added a NEWS file in my R package.
2. DESCRIPTION file. I have provided a detailed description about the background and the aim of this R package.
3. Vignette. I have adopted the standard documentation style in Bioconductor by using the BiocStyle package.
4. R. I have tried my best to deal with the note number in the build report as few as possible: 
       a) replaced all "sapply" with "vapply"
       b) replaced all "1:..." with "seq_len( )"
       c) added examples to each R function
       d) deleted canned comments in man pages
       e) adjusted the indentation of the R code to be easier to read 
5. In the main R function "BUSgibbs", I added the "SummarizedExperiment" as an acceptable input.  

Please accept my deepest gratitude for your time on my R package!

Best regards with many thanks,

Xiangyu

**Comment by nturaga** [comment]
##  Update 

* I should have been clear in my previous review, please add a NEWS
  file parsable by utils::news()

* Vignette looks great! The section on `Data Preparation` could use a
  little more description for the naive user.

### R

* Just as good practice, it's helpful to declare your internal
  functions outside your `BUSgibbs` with a `.Dirchlet`, `.Inv_Gamma`
  etc, and use them within the function. This makes it easier to
  debug, and also read the code.
  
* Try to optimize your loops, and only compute something within a loop
  if it's really needed. Try to vectorize as much as possible. Eg: the
  `sum` function in the if statement is not needed.
  

		for(b in seq_len(B)){
			for(k in seq_len(K)){
				if(sum(Z_t[[b]] == k) > 1){
					raw_Means[b,k,] <- colMeans(Y[[b]][Z_t[[b]]==k,])
				}else   raw_Means[b,k,] <- Y[[b]][Z_t[[b]]==k,]
			}
		}


vs

	for(b in seq_len(B)){
		sumzt <- sum(Z_t[[b]]
		for(k in seq_len(K)){
			if(sumzt == k) > 1){
				raw_Means[b,k,] <- colMeans(Y[[b]][Z_t[[b]]==k,])
			} else {
				raw_Means[b,k,] <- Y[[b]][Z_t[[b]]==k,]
			}
		}
	}
	

Look for patterns like this throughout your codebase. Your usage of `for` loops in general requires more scrutiny. (also look at nested for loops, and `apply` functions)

* There hasn't been a change on how your format your code base, plenty of code exceeds the 80 char limit. This makes it hard to read and it easy formattbale. 


* As far as end user messages go, please pay attention to which function you use,


`message()` communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.

`warning()` communicates unusual situations handled by your code.

`stop()` indicates an error condition.

`cat()` or `print()` are used only when displaying an object to the user, e.g., in a show method.

You seem to be using `cat` but you really want to use `message` in some places.

**Comment by XiangyuLuo** [comment]
Hi @nturaga Thank you very much for the valuable and constructive comments! I have carried out the following updates based on your comments.

1. Added a NEWS.Rd file in the folder "inst". The NEWS.Rd file is parsable by utils::news() now;
2. Added more naive-user-friendly details for preparing input data in the vignette.
3. Declared all internal functions outside the main function.    
4. Optimized the for loops and reduced the usage of ```apply``` function as few as possible.
5. Changed the code format such that each line in R code does not exceed 80 characters. 
6. Replaced ```cat``` by ```message``` for all R functions except the S3 methods ```summary``` and ```print```.

Once again, please accept my deepest thanks for your time on evaluating my code.

Xiangyu

**Comment by XiangyuLuo** [comment]
Hi @nturaga , I updated the code according to your requirements two weeks ago. Could you please let me know the current status of reviewing. Thank you very much for your great help! 

Xiangyu

**Comment by XiangyuLuo** [comment]
Hi @nturaga , my R package was installed with green OK two weeks ago. Today, I just modified the README file, but the system always gave me "ABNORMAL". Is it due to the build system itself? 

Many thanks!

Xiangyu

**Comment by lshep** [comment]
This ABNORMAL was likely do to an issue on our end.  I am rerunning your package now for a complete build report.

**Comment by XiangyuLuo** [comment]
Hi @lshep Thank you very much! It became OK now.

**Comment by XiangyuLuo** [comment]
Hi @nturaga Sorry for disturbing you again. Is it possible for me to know the current reviewing status? Thank you very much for your precious time spent on the review. 
Many thanks!
Xiangyu

**Comment by nturaga** [comment]
Hi @XiangyuLuo 

Your package looks in good shape. It has been accepted.

**Comment by XiangyuLuo** [comment]
@nturaga Thank you so much!!!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/XiangyuLuo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"BUScorrect\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BUScorrect

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
