### ISSUE TITLE
SAFEclustering

### ISSUE THREAD

**Issue by yycunc** [Bioconductor/Contributions#810]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/yycunc/SAFEclustering

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment]
Hi @yycunc 

Please make sure that your package build report is **clean**. That means, no *errors*, no *warnings*, and as few *notes* as possible

**Comment by yycunc** [comment]
Hi Nitesh,

Sorry for the inconvenience. However, there is no error or warning in my code, when I did check and BiocCheck. I think the problem is that, my code requires two compiled C codes for computing. And these two programs need to be put into the working directory or define the exact directory where they are. So, there may be an error when you run the example without these two programs.

Do you have any ideas how to deal with such a case?

Thanks for your help!

Bests,

Yuchen

Yuchen Yang, Ph.D.
Postdoctoral Fellow, Department of Genetics
5100 Genetic Medicine Building
University of North Carolina at Chapel Hill
120 Mason Farm Road
Chapel Hill, NC, 27599

**Comment by nturaga** [comment]
Hi @yycunc 

I have to point out,  that by including third-party code the package maintainer assumes responsibility for maintenance of that code. Part of the maintenance responsibility includes keeping the code up to date as bug fixes and updates are released for the mainline third-party project.

Have you taken a look at the following two links?

https://cran.r-project.org/doc/manuals/R-exts.html#System-and-foreign-language-interfaces

http://bioconductor.org/developers/package-guidelines/#ccode

It's not common to populate your package directory with the two folders(`gpmetis_and_shmetis_for_Linux` etc..) you have. C code usually lives in the `src` directory. The other issue is it seems like your package is supported on only two platforms.

@mtmorgan Do you have any more comments regarding this issue @yycunc is having?

Best,

Nitesh

**Comment by yycunc** [comment]
Hi Nitesh,

I have tried to compile the C code by command MAKEFLAGS="CFLAGS=-O3" R CMD SHLIB gpmetis.c, however, I met the error that the library used in gpmetis.c can not be found. Actually, there are many library required by this program.

#include <GKlib.h>
#include <stddef.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdio.h>
#include <ctype.h>
#include <math.h>
#include <time.h>
#include <string.h>
#include <limits.h>
#include <signal.h>
#include <setjmp.h>
#include <assert.h>

I don’t know how to deal with this problem.

Thanks for your kindly help!

Bests,

Yuchen

Yuchen Yang, Ph.D.
Postdoctoral Fellow, Department of Genetics
5100 Genetic Medicine Building
University of North Carolina at Chapel Hill
120 Mason Farm Road
Chapel Hill, NC, 27599

**Comment by mtmorgan** [comment]
Let me interject here and say also that there seem to be two R packages (SAVER, cidr) that are not on CRAN or Bioconductor; these cannot be dependencies of your package. My feeling is that there is significant technical work that needs to be done before the package can be reviewed, and that the level of support you're asking of Nitesh is too much for the review process. I'd encourage you to close this issue and to work on the package further, perhaps through questions on the bioc-devel mailing list but  also through independent effort at incorporating the library code and modifying your package to only use CRAN or Bioconductor functionality.
