### ISSUE TITLE
SmCCNet

### ISSUE THREAD

**Issue by wjshi** [Bioconductor/Contributions#828]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/KechrisLab/SmCCNet

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please use the standard bioinformatics / Bioconductor representation of data as feature (row) x sample (column) matrices. Please use as inputs and outputs to your functions where possible [standard Bioconductor data representations][2] such as [SummarizedExperiment][1]. Please clean up your repository so that the 'master' branch contains only the files that form the source of your package, e.g., no 'package' directory or vignettes/*pdf files.

[1]: https://bioconductor.org/packages/SummarizedExperiment
[2]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by LiNk-NY** [comment]
Hi Jenny, @wjshi 
Can you please fix the errors in the package? Please see the [build report](http://bioconductor.org/spb_reports/SmCCNet_buildreport_20180806165657.html). 
Thank you.
-Marcel

**Comment by wjshi** [comment]
Hi Marcel,

Thanks for the reminder! My apologies for not responding to the previous
email. I’m just had a baby and I’m currently on maternity leave. I will
make fix the package as soon as possible.

Best,
Jenny

**Comment by LiNk-NY** [comment]
Hi Jenny, 
Congratulations! 

We can close the issue and you can re-submit/re-open when you
have time to work on the package. How's that? 

Thanks!
-Marcel

**Comment by wjshi** [comment]
Ok. Thank you.

Jenny
