### ISSUE TITLE
breakpointRdata

### ISSUE THREAD

**Issue by daewoooo** [Bioconductor/Contributions#835]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/daewoooo/breakpointRdata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by daewoooo** [comment]
AdditionalPackage: https://github.com/daewoooo/breakpointR

**Comment by dvantwisk** [comment]
Here is the review for this package.  It's a data package, so there's not much to say but there are a few small things. The [REQUIRED] tags indicate changes that must be made or require an explanation. The [CONSIDER] tags indicate changes that are advisable but not required. Please message me back when you are done making changes.

DESCRIPTION:
- [REQUIRED] I'm not sure what the license is and the `LICENESE` file doesn't
seem to indicate which license it is using. It may be correct but I haven't seen
it like this before. Is it a custom license? If it isn't, it may be useful to change the `License:` tag in the `DESCRIPTION` file to `LICENSE: <name_of_license> + LICENSE` just to make it clear to the user.

R/documented_data.R
- [CONSIDER] It may be worth it to add a little about the structure of the data
e.g. the dimensions.

**Comment by daewoooo** [comment]
Hi Daniel,

Thank you very much for your comments to improve the quality of this package.
Please find my response to your comments below.
[REQUIRED] 
I have modified the LICENSE file to comply with the standard MIT LICENSE.

[CONSIDER]
I have modified R/documented_data.R to provide more details on the data objects presented with this data package.

For example_bams I have added the reference genome the data were aligned to and also what modifications have been made to the data in order to reduce the file size.

For example_results I have a added a description of the overall structure of the RData object. Also I have added a description of each element of this RData object.

Best regards,

David

**Comment by dvantwisk** [comment]
Hi,
The changes you made to the package look fine. I am ready to accept if you are.

**Comment by daewoooo** [comment]
Hi Daniel,

Sounds good to me. Thanks again for your review. I assume that the review of the main package (breakpointR) will follow.

David

**Comment by dvantwisk** [comment]
I'll accept the package then.
As for the `breakpointR` package. I'm not seeing it as an open issue. Do you have a link to that issue?

**Comment by daewoooo** [comment]
Nice thanks. breakpointR package was added as an additional package to this issue 14days ago. See the link.
https://github.com/Bioconductor/Contributions/issues/835#issuecomment-412973692
I hope I did right. Let me know if you have any trouble to find it.

**Comment by dvantwisk** [comment]
I suppose I didn't see it! I will get a review of this to you.

**Comment by lshep** [comment]
Hi @daewoooo   For the record: Yes you did do this correctly by submitting the data package first and the software package as an additional package.  Please see the following review of the software package:

**General:**
- [ ] Please clean up NOTES in the build report
```
* Checking coding practice...
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
      confidenceInterval.R (line 43, column 28)
      confidenceInterval.R (line 125, column 28)
      exportRegions.R (line 33, column 23)
      GenotypeBreaks.R (line 49, column 26)
      hotspotter.R (line 34, column 24)
      plotting.R (line 32, column 15)
      plotting.R (line 242, column 15)
      plotting.R (line 294, column 16)
      plotting.R (line 392, column 19)
      syncReads.R (line 51, column 15)
Warning in readLines(infile) :
* Checking exported objects have runnable examples...
    * NOTE: Consider adding runnable examples to the following man
      pages which document exported objects:
      breakpointr.Rd, runBreakpointr.Rd
```

**README**
- [ ] Please use BiocManager::install  for installing from bioconductor and not Biocinstaller::biocLite 
```
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
install("GenomicRanges") 

etc... 

``` 

**NEWS**
- [ ] Thank you for including the NEWS file but it is formatted incorrectly. Please have headers in the form of "Changes in version x.y.z"  and the items below will have to be identified with either a -, +, or o ... so for instance the NEWS file would become 
```
Changes in version 0.99.0
----------------------------------

- This package implements various functions to find template strand changepoints
in Strand-seq data.

``` 

**LICENSE**
- [ ] I see you included your own license - it doesn't restrict distribution or use so its fine but I was just curious why a standard open source license like those already include with R couldn't be used? I see that you distributed the data package under MIT - was there a reason it couldn't be the same?

**test/testthat**
- [ ] You included RData files in your testthat so the tests are really not interactively testing the functions in your package.  The point of the tests is so the files are generated and run on freshly generated data to indicate any problems. The way its implemented is really tricking the testing process

**vignette* 
- [ ] I suggest removing the -knit from the vignette title.  Generally the vignettes are the name of the package or something meaniful as within R the user will call vignette("vignetteTitle")  it is not very intuitive to be vignette("breakpointR-knitr")  

- [ ] your main function breakpointr is never run as in the man/example file it is in a dontrun{} and in the vignette is in included in code chunks that are eval=FALSE.  We require that all functions are evaluated at least once for testing. 

- [ ] Actually most of the code chunks in your vignette are eval=FALSE; This is unacceptable as the vignette needs a working example.  If you are including a data package you can and should be including files to allow your package to have a working example (unless using already existing Experiment Data from other packages which is strongly encouraged).  There are BAM files available through existing Bicondcutor Experiment Data packages like [pasillaBamSubset](https://www.bioconductor.org/packages/release/data/experiment/html/pasillaBamSubset.html) 
There are also newly submitted BAM files on ExperimentHub, althoughth that package is also going throught the submission process they can be accessed with the devel experimenthub 
```
> eh = ExperimentHub()
qusnapshotDate(): 2018-09-05
> query(eh, "MMAPPR2data")
ExperimentHub with 4 records
# snapshotDate(): 2018-09-05 
# $dataprovider: Bench to Bassinet GnomEx CvDC
# $species: Danio rerio
# $rdataclass: character
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH1657"]]' 

           title     
  EH1657 | zy13mut   
  EH1658 | zy13mutIdx
  EH1659 | zy13wt    
  EH1660 | zy13wtIdx 

```
Please update the vignette to have a working example of your functions.  


**R code**
- [ ] In all files - you nest internal helper functions inside other functions which make it very hard to read. I suggest making an internal.R or utils.R that contains all these internal helper functions to allow the function calls to only include the relevant code. 

- [ ] writeBed.R -  is this really needed?  Why could you not use the export function provided by rtracklayer? rtracklayer has an export method that will write BED files. 

- [ ] importReads.R - similar to above.  There are already existing methods for reading BAM files. 

breakpoint.R 
- [ ] Don't repeat code - example in the section commmented #binning#  The code is essentially repeated with few changes between whether createCompositFile, numCPU >1 and else - have a function that defines the main section of this code and these sections become wrappers around it. 


Please start with these suggested changes.  Please comment back here addressing the above issues and when you would like a re-review of the package. 

Thank you and Thank you for your efforts and interest in Bioconductor.

**Comment by daewoooo** [comment]
Dear reviewer,

Thank you very much for the review of breakpointR package. I appreciate your effort and time to make this package better. I have addressed your comments one-by-one below (text in italics). Updated version of the package have pushed to git.

General:
Please clean up NOTES in the build report
* Checking coding practice… 
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
      confidenceInterval.R (line 43, column 28)
      confidenceInterval.R (line 125, column 28)
      exportRegions.R (line 33, column 23)
      GenotypeBreaks.R (line 49, column 26)
      hotspotter.R (line 34, column 24)
      plotting.R (line 32, column 15)
      plotting.R (line 242, column 15)
      plotting.R (line 294, column 16)
      plotting.R (line 392, column 19)
      syncReads.R (line 51, column 15)
_All above mentioned functions have been modified as required._

Warning in readLines(infile) :
* Checking exported objects have runnable examples...
    * NOTE: Consider adding runnable examples to the following man
      pages which document exported objects:
      breakpointr.Rd, runBreakpointr.Rd
_To address above reported NOTE, we have added runnable example for runBreakpointr function. In order to meet package build times we have included runnable example of the main breakpointr function as a part of vignettes._


README
Please use BiocManager::install for installing from bioconductor and not Biocinstaller::biocLite
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
install("GenomicRanges") 

etc... 
_We have modified the README file to meet the above mentioned requirements._

NEWS
Thank you for including the NEWS file but it is formatted incorrectly. Please have headers in the form of "Changes in version x.y.z" and the items below will have to be identified with either a -, +, or o ... so for instance the NEWS file would become
Changes in version 0.99.0
----------------------------------

- This package implements various functions to find template strand changepoints
in Strand-seq data.
_We have changed the NEWS to match required format._

LICENSE
I see you included your own license - it doesn't restrict distribution or use so its fine but I was just curious why a standard open source license like those already include with R couldn't be used? I see that you distributed the data package under MIT - was there a reason it couldn't be the same?
_We have changed the license in order to comply with MIT standards._

test/testthat
You included RData files in your testthat so the tests are really not interactively testing the functions in your package. The point of the tests is so the files are generated and run on freshly generated data to indicate any problems. The way its implemented is really tricking the testing process
_In order to save space we have stored raw Strand-seq data (raw sequecning reads) as a GRanges object and saved it in RData file. Such raw reads are then processed using runBreakpoinr function to test all main functionalities of breakpointR package to detect breakpoints in Strand-seq data. Running this function we rigorously test if the whole breakpoint detection procedure will give us an expected number of breakpoints and as such uncover any bugs in our code._


*vignette
I suggest removing the -knit from the vignette title. Generally the vignettes are the name of the package or something meaningful as within R the user will call vignette("vignetteTitle") it is not very intuitive to be vignette("breakpointR-knitr")
_As suggested, we have changed the name of vignettes to breakpointR.Rnw ._

your main function breakpointr is never run as in the man/example file it is in a dontrun{} and in the vignette is in included in code chunks that are eval=FALSE. We require that all functions are evaluated at least once for testing.
_As mentioned before, the main breakpointr function is now fully run as a vignette example._

Actually most of the code chunks in your vignette are eval=FALSE; This is unacceptable as the vignette needs a working example. If you are including a data package you can and should be including files to allow your package to have a working example (unless using already existing Experiment Data from other packages which is strongly encouraged). There are BAM files available through existing Bioconductor Experiment Data packages like pasillaBamSubset
_We have added full runnable example of the main breakpointR function that runs whole breakpoint detection pipeline. Vignettes also contain explanations of recommended setting for the main breakpointr function. These explanations are eval=FALSE as we think it’s unnecessary to run the same function over and over again._

There are also newly submitted BAM files on ExperimentHub, althoughth that package is also going throught the submission process they can be accessed with the devel experimenthub
Unfortunately, none of the above mentioned examples can be used to test functionalities of breakpointR package. breakpointR is specifically designed to process single-cell Strand-seq data.
> eh = ExperimentHub()
qusnapshotDate(): 2018-09-05
> query(eh, "MMAPPR2data")
ExperimentHub with 4 records
# snapshotDate(): 2018-09-05 
# $dataprovider: Bench to Bassinet GnomEx CvDC
# $species: Danio rerio
# $rdataclass: character
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH1657"]]' 

           title     
  EH1657 | zy13mut   
  EH1658 | zy13mutIdx
  EH1659 | zy13wt    
  EH1660 | zy13wtIdx 

Please update the vignette to have a working example of your functions.
_We changed the vignettes to contain runnable examples of the main function to ensure that the whole breakpoint analysis can be run. Other parameter explanations for the main function are not runnable since they only point user how to use those parameters._

R code
In all files - you nest internal helper functions inside other functions which make it very hard to read. I suggest making an internal.R or utils.R that contains all these internal helper functions to allow the function calls to only include the relevant code.
_We made sure there are no undefined internal function within other functions. Also we have created new utils.R file for any helper function used throughout the package._

writeBed.R - is this really needed? Why could you not use the export function provided by rtracklayer? rtracklayer has an export method that will write BED files.
_As suggested we have further explored the possibility to utilize rtracklayer functionalities. However, we concluded that for our purposes implementation of rtracklayer would not bring much improvement in readability of our bed export function. Therefore we opt for splitting our main export function in two function to make our code more concise and easy to understand._

importReads.R - similar to above. There are already existing methods for reading BAM files.
_Unfortunately, existing methods are not applicable for specifics of Strand-seq data. In our function we have to make sure that the read directionality in every single library is preserved regardless of single or paired-end data being loaded. Moreover, we offer user additional options, such as merging paired-end reads into a single fragment while preserving read directionality as well as optional filtering of alternative alignments._

breakpoint.R
Don't repeat code - example in the section commented #binning# The code is essentially repeated with few changes between whether createCompositFile, numCPU >1 and else - have a function that defines the main section of this code and these sections become wrappers around it.
_We added a helper function into the main breakpointr wrapper in order to decrease unnecessary code repetition and to improve readability of the code._

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/daewoooo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"breakpointRdata\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/breakpointRdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/daewoooo.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"breakpointR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/breakpointR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
