### ISSUE TITLE
QSutils

### ISSUE THREAD

**Issue by VHIRHepatiques** [Bioconductor/Contributions#868]
- Repository: https://github.com/VHIRHepatiques/QSutils

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

**Comment by nturaga** [comment]
Hi @VHIRHepatiques 

Please fix the NOTEs in your build report before we continue reviewing the package,

http://bioconductor.org/spb_reports/QSutils_buildreport_20180920061754.html

```
* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply() found in files:
      CorrectGapsAndNs.R (line 15, column 12)
      Diverge.R (line 20, column 15)
      GenerateVars.R (line 25, column 19)
      HCqProfile.R (line 8, column 11)
      HillProfile.R (line 8, column 11)
      RaoPowProfile.R (line 11, column 11)
      ReadAmplSeqs.R (line 6, column 11)
      RenyiProfile.R (line 8, column 11)
      ReportVariants.R (line 12, column 18)
      SortByMutations.R (line 15, column 19)
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
      Collapse.R (line 6, column 20)
      CorrectGapsAndNs.R (line 15, column 20)
      DBrule.R (line 13, column 33)
      DBrule.R (line 16, column 14)
      Diverge.R (line 22, column 14)
      Diverge.R (line 24, column 19)
      Diverge.R (line 24, column 39)
      fn.ab.1.R (line 5, column 22)
      fn.ab.2.R (line 5, column 21)
      fn.ab.3.R (line 5, column 21)
      FreqMat.R (line 13, column 22)
      GenerateVars.R (line 23, column 14)
      geom.series.R (line 5, column 10)
      MutsTbl.R (line 7, column 21)
      RaoPowProfile.R (line 11, column 18)
      Recollapse.R (line 6, column 20)
      ReportVariants.R (line 12, column 25)
      ReportVariants.R (line 19, column 19)
      SortByMutations.R (line 15, column 26)
      SortByMutations.R (line 15, column 52)
* Checking package NEWS...
    * NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * NOTE: Consider shorter lines; 1 lines (0%) are > 80 characters
      long.
    First 1 lines:
      man/DBrule.Rd:53 filepath_geno<-system.file("extdata","GenotypeStandard...
```

See http://bioconductor.org/developers/how-to/coding-style/

**Comment by Merguerrero** [comment]
Dear @nturaga ,

the sapply() in SortByMutations.R (line 15, column 19), can't be removed because the output of the function inside has variable length.

Thank you!

**Comment by VHIRHepatiques** [comment]
Dear @nturaga,

The sapply() in SortByMutations.R (line 15, column 19), can't be removed because the output of the function inside has a variable length. 

Thank you!

**Comment by nturaga** [comment]
# QSutils review

## R CMD build

ok

## R CMD INSTALL 

ok

## DESCRIPTION

Reformat your DESCRIPTION file without and blank lines. 

## NAMESPACE

* ok

* Why do you need to import devtools? 

* `utils` comes with every installation of R, you don't have to import
  it in your namespace.

## NEWS

* The NEWS file is usually more informative, it descripes what changes
  have been made / fixed.

## man

ok

## vignette

* Replace "devtools" install of QSutils with
  `BiocManager::install("QSutils")`.

* Remove all files which are ".html". These will be autogenerated when
  your package builds, if your vignetter formatting is correct.

* Named "chunks" in the Rmd file allow users to know exactly where the
  vignette fails. 

## R

* Do not use `class(X) == "DNAStringSet`, instead use 

		> is("X", "character")
		[1] TRUE

  Make the change everywhere you use `class`
  
```
    Collapse.R
3:    cls <- class(seqs)

Recollapse.R
3:    cls <- class(seqs)
```

* There is no documentation in the code. Please document your code,
  your future self will thank you. (Also the reviewers)

* Declare your helper functions outside the function, eg:
  CorrectGapsAndNs.R,

	    CorrPos <- function(v,nt){ 
        fl <- v %in% c("-","N")
        v[fl] <- nt
        return (v)
		}

  There is no reason this function needs to be within the main
  function. If you wan to make sure users cannot access this function,
  just don't export it, and call it with a "." in front the function
  name `.foo <- function(x, y) {}`.
  
  
* You also seem to have extrememly short functions within each file in
  you R directory. It is easy to just group a few functions which fall
  in the same bracket in one single file, like `GiniSimpson.R`,
  `GiniSimpsonMVUE.R` ...etc...can go into `Gini.R`.
  
  You can do this for multiple functions of yours.
  
* What is the reasoning behind saving the `.Random.seed`? Is it really
  random if you've saved it?
  
  
* Some of the `apply` calls can be removed and vectorized from the
  package `matrixStats`. Like

		flags <- apply(mut.tbl,2,sum)>0

	this can be replaced with,
	
		flags <- colSum(mut.tbl) > 0
		
  Change similar apply functions through out your code.
  
  
* The functions `fn.ab.1()` looks very similar to fn.ab.2, and
  fn.ab.3. This is a bad coding style. The code is repeated, and can
  be easily contained in a single function.

  The only line that changes in all three functions is,
  
	      a <- floor(h*1/(seq_len(n))^r)
		  
              a <- floor(h^(1/seq_len(n)))
	 
	      a <- floor(h*r^((seq_len(n))-1))

  Please fix this and similar instances.
  

Once you have fixed your package, please make sure you follow http://bioconductor.org/developers/how-to/efficient-code/ in all your coding practices. Also follow http://bioconductor.org/developers/how-to/coding-style/. 

Please update the version number once you have made the changes. Reply, point by point to each issue in this review.

**Comment by VHIRHepatiques** [comment]
Hi @nturaga, 

### **QSutils review**

**DESCRIPTION**
- Reformat your DESCRIPTION file without and blank lines. -> DONE

**NAMESPACE**
- Why do you need to import devtools? -> To install the package in the vignettes. But now this is removed. 

**NEWS**
- The NEWS file is usually more informative, it descripes what changes have been made / fixed. -> DONE

**vignette**
- Replace "devtools" install of QSutils with BiocManager::install("QSutils"). -> DONE

- Remove all files which are ".html". These will be autogenerated when your package builds, if your vignetter formatting is correct. -> DONE

- Named "chunks" in the Rmd file allow users to know exactly where the vignette fails. -> DONE

**R**
- Do not use class(X) == "DNAStringSet, instead use  is("X", "character") ->DONE

- There is no documentation in the code. Please document your code, your future self will thank you. (Also the reviewers) -> DONE

- Declare your helper functions outside the function. -> DONE

- You also seem to have extrememly short functions within each file inyou R directory. It is easy to just group a few functions which fall in the same bracket in one single file. -> DONE

- What is the reasoning behind saving the .Random.seed? Is it really random if you've saved it? -> Now is removed, it was automatically generated and we didn't notice. 

- Some of the apply calls can be removed and vectorized from the package matrixStats. -> DONE

- The functions fn.ab.1() looks very similar to fn.ab.2, and fn.ab.3. This is a bad coding style. The code is repeated, and can be easily contained in a single function. -> DONE

Do not hesitate to contact us if there is any problem or error.

**Comment by nturaga** [comment]
Hello @VHIRHepatiques 

Thanks for implementing the changes. The package looks better. 

* Consider explicitly adding `export(<function name>)` to your NAMESPACE. This clarifies how many functions you are exposing to the user. I

* Please check the following NOTE.

```
* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply() found in files:
      SortByMutations.R (line 21, column 19)
```

* Please clarify what exactly is in the `build` folder? And why you need it. 

Package looks good otherwise. A few small changes to go and it looks good to be accepted.

Best,

Nitesh

**Comment by VHIRHepatiques** [comment]
Hi @nturaga 

- Consider explicitly adding export(<function name>) -> DONE

- SortByMutations NOTE:

`isq <- unlist(sapply(seq_len(length(tnm)), function(i) seq_len(tnm[i])))`

As it was mentioned before we are not able to remove sapply in this case, as the result of the intern function is a numeric vector of variable length. 

- Please clarify what exactly is in the build folder?
 It is an error, it must have appeared in a unfinished build of the tarball of the pagacke. It is now deleted. -> DONE

Thaks for your time, we are looking forward for your reply.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/VHIRHepatiques.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install(\"QSutils\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/QSutils

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
