### ISSUE TITLE
(inactive) ceRNAmiRNAfun

### ISSUE THREAD

**Issue by JohnMengChun** [Bioconductor/Contributions#875]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JohnMengChun/ceRNAmiRNAfun

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
There is no vignette with evaluated code chunks. This is required for all Bioconductor packages.

**Comment by JohnMengChun** [comment]
@mtmorgan  Dear Mr.Morgan: Thank you for your comment, I will soon add the vignette to the package.
How can I let you know when I finish new updating for your new checking?

thanks

**Comment by mtmorgan** [comment]
To let me know, post a comment just like the one above.

**Comment by JohnMengChun** [comment]
@mtmorgan  Dear Mr.Morgan: Sorry for letting you wait so long. I have updated the vignette of my package, please give me any comments if there is a problem of that, thank you

**Comment by mtmorgan** [comment]
Hmm, most of the chunks are eval=FALSE, which defeats the purpose of the vignette; you reference paths on your own disk so obviously not portable.

**Comment by JohnMengChun** [comment]
@I see.  But I have no idea  how I can get the data reading protable? To assign the link to the github? Is it possible to give me the examples because I couldn't find it in the R packages file.  thank you.

**Comment by mtmorgan** [comment]
Usually vignettes use small sample data sets that are distributed with the package in a folder <pkg>/inst/extdata/... and the files are referenced in the vignette with `system.file(package="<pkg>", "extdata", "...")`. If the files are large (this is usually not necessary, the vignette is demonstrating functionality not performing a full analysis) then they can be included via a separate 'experiment data' package or in experiment hub. Try the first solution (data included in the package) first.

**Comment by JohnMengChun** [comment]
@mtmorgan thank you for the reply, I will give it a try.

**Comment by mtmorgan** [comment]
@Kayla-Morrell I'll review this package...

**Comment by JohnMengChun** [comment]
@mtmorgan I renamed my vignette, hope it would work, can you check my package again?

**Comment by mtmorgan** [comment]
Do you have the 'web hook' [active][1]? Did you bump the version of your package (to 0.99.1) to trigger an automatic build?

[1]: https://github.com/Bioconductor/Contributions#adding-a-web-hook

**Comment by JohnMengChun** [comment]
@mtmorgan I think I  bumped the version of your package to 0.99.1 to trigger an automatic build
And oncemore, how can I deal with the problem of invalid UTF-8 encoding ?  It is pretty annoying  since my laptop is under window10 system.

**Comment by mtmorgan** [comment]
The version needs to be bumped (0.99.2, 0.99.3, ...) each time a change is pushed to the repository.

The problem in your vignette is that you have used non-ASCII characters to represent special symbols. I did
```
> tools::showNonASCIIfile("introduction_to_ceRNAmiRNAfun.Rmd")
87: pairinformation<e3><80><80><e3><80><80>miRNA<e3><80><80><e3><80><80>genelist
88: Row1<e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80>A      <e3><80><80>geneA1,geneA2<e2><80><a6>
89: Row2<e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80>B      <e3><80><80>geneB1,geneB2<e2><80><a6>
90: Row3<e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80><e3><80><80>C      <e3><80><80>geneC1,geneC2
97: <e3><80><80>	    miRNA
98: Row1<e3><80><80><e3><80><80><e3><80><80>A
99: Row2<e3><80><80><e3><80><80><e3><80><80>B
100: Row3<e3><80><80><e3><80><80><e3><80><80>C
110: To demonstrate the usage of the ceRNAmiRNAfun package, the package contains 475 paired miRNA and gene lung cancer samples. As for dictionary data, there are 137 paired miRNA and corresponding gene data in a list form, and miRNA_total data has the first column of the dictionary data of the miRNA<e2><80><99>s names.
```
all of those `<e2><80><99>` and similar are problematic. I see: '...' printed as a single character, maybe you want to use three separate '.'; use of a 'fancy' apostrophe, rather than a plain apostrophe in miRNA's, use of a M-width space ' ' rather than a plain space. I guess each of these are examples of whatever editor you are using trying to be 'helpful' and make your text look 'pretty' or 'smart'; the solution is to turn off these features of your editor, or to use an editor that does not try to be helpful in this way, or to override the suggestions that the editor makes.

**Comment by mtmorgan** [comment]
Oops, pressed the wrong button...

**Comment by mtmorgan** [comment]
The current problem in the DESCRIPTION file is that the field is called `Authors@R`, not `Author@R`. With the `Authors@R` field set, you do not need the `Maintainer:` field.

Also remember that the 'best practice' is to build and check your package locally, before pushing the commit and waiting to see errors in our build system

```
R CMD build ceRNAmiRNAfun
R CMD check ceRNAmiRNAfun_0.99.2.tar.gz
```

or similar, e.g., within R, `devtools::check("ceRNAmiRNAfun")`

**Comment by JohnMengChun** [comment]
@mtmorgan I think I have already uploaded the new file, please check it.
 And furthermore, I have some questions I don't understand in my R CMD check
1.I would like to know where are the "codoc" and "documentation" that I can check my data.
The warnings are as followed: 

checking for code/documentation mismatches ... WARNING
Data codoc mismatches from documentation object 'gene_sam':
Variables in data frame 'gene_sam'

2.Are we necessary to use the Rtools to build a package?
Because I followed the website installation, but I still got the same warnings.

The warning is as followed:
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/

Please give me some hints, thank you

**Comment by mtmorgan** [comment]
The 'VERSION BUMP REQUIRED' tag indicates that you pushed changes, but did not increment the version of your package in the DESCRIPTION file, to 0.99.3. If you want to build your package before checking (recommended), then yes, you need Rtools installed. You can also check the package without building, but that will result in misleading warnings. 

'codoc' is trying to say that your code defines a function or object in one way, but the documentation is different, i.e., a 'code / documentation' mismatch. When the warning mentions documentation object 'gene_sam', it means that the problem is in the man/gene_sam.Rd file. Instructions for documenting data objects are found in Writing R Extensions https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Documenting-data-sets .

**Comment by JohnMengChun** [comment]
@mtmorgan 
Sorry I was a little busy last two weeks and still had some error message I didn't know how to solve in my package check.
I already bumped a new version of my description, please check it.
But there are still some warnings in my check, I will do that within this week.
Sorry to bother you so far.

**Comment by mtmorgan** [comment]
Will you be updating your package to pass the checks, or shall we mark this issue as 'inactive'?

**Comment by JohnMengChun** [comment]
@mtmorgan 
Sorry for the late update
I want to update the package, but I was stuck by  the errors I had
The one of them was the Rtools installation.

I used install.packages("Rtools") in R version 3.5.1
but it didn't work as the following error occurred:
Warning in install.packages :
  package ‘Rtools’ is not available (for R version 3.5.1)

How can I fix it to finish my procedure of building packages

Thank you

**Comment by JohnMengChun** [comment]
＠mtmorgan
1.Thank you for your reply, I installed Rtools from the website for several times before, and also check it really exists in my R directory, but still cannot work
The following message still exists:
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:
https://cran.rstudio.com/bin/windows/Rtools/

Is it possible for another problem to occur even if Rtools indeed in the directory?


2. another similar problem is I exactly put 2 of my png files under the folder inst
but the following message still exists:
Files in the 'vignettes' directory but no files in 'inst/doc':
     'pics/plotp.png', 'pics/workflow_ceRNAmiRNAfun.png'

I tried some solutions on the website, but it didn't work  :https://stackoverflow.com/questions/42670800/r-check-warning-files-in-the-vignettes-directory-but-no-files-in-inst-doc

Can you give me some hints?  

I used Win10, version3.5.1 Rstudio to compile
I was stuck here and couldn't find the solutions for a while.

Thank you so much for the reply.

**Comment by mtmorgan** [comment]
Rtools needs to be installed on the system PATH, so your Rtools is not installed correctly. But to back up, why are you trying to install Rtools, which is typically required to only to install packages that have compiled (C or Fortran) code?

**Comment by JohnMengChun** [comment]
@mtmorgan you mean Rtools is not necessary? because the error message below shows up every time when I test the package

**Comment by mtmorgan** [comment]
I see, I reviewed the comment history here. Yes you want to install Rtools to build and check your package. So the problem is that Rtools is not installed correctly. You should install Rtools in a path WITHOUT spaces. When you install Rtools it asks you if you want to add the tools to your system PATH. You should answer Yes, but then also confirm after installation that the PATH (it is a Windows system environment variable) is set correctly; one way to do this is to ensure that in a new DOS or PowerShell terminal the command `gcc --version` returns correctly.

**Comment by JohnMengChun** [comment]
@mtmorgan
Thank you for you comments, but it still failed
I did what you said(in a no-spaced path and answer yes) and tried installing different combinations of Rtools installation, but it still couldn't find my path 

And one more thing , I hope to know how to deal with the problem as well, also the problem I cannot figure out where the problem is.

I exactly put 2 of my png files under the folder inst
but the following message still exists:
Files in the 'vignettes' directory but no files in 'inst/doc':
'pics/plotp.png', 'pics/workflow_ceRNAmiRNAfun.png'
I tried some solutions on the website, but it didn't work :https://stackoverflow.com/questions/42670800/r-check-warning-files-in-the-vignettes-directory-but-no-files-in-inst-doc

**Comment by mtmorgan** [comment]
Build and install packages from the command line rather than using devtools. In this way problems with devtools are avoided.

Commit your most recent changes and trigger a build; I will provide detailed comments from that.

**Comment by JohnMengChun** [comment]
@mtmorgan ok, I am doing my best and will  upload a new version in these two days

**Comment by JohnMengChun** [comment]
@mtmorgan 
Dear mtmorgan:
I want to reupload my package here, what should I do to eliminate the inactive label?

Please let me know, thanks

**Comment by JohnMengChun** [comment]
Ok, thank you, I will upload it in recent days
By the way, is that any quick way to delete some of the folders of old version folder?
what I know so far is only delete file by file, which takes some time

**Comment by mtmorgan** [comment]
I don't understand your question, maybe you could show what you are doing now that takes some time.

**Comment by JohnMengChun** [comment]
Uh..It's a little difficult to show..
Roughly speaking, in my package ceRNAmiRNAfun, I have 8 folders, but when I want to delete the whole folder, I should go into the folder and delete the file,  rather than the whole folder. Is it possible to accelerate the procedure?

**Comment by mtmorgan** [comment]
what do you do to delete the file? are you talking about git, or your operating system, or a script in R or ???

**Comment by JohnMengChun** [comment]
@mtmorgan sorry that I didn't explain it in detailed 
I was talking about git itself, I wanted to replace the old package with new one, so far I know is to move out the old file, and then upload the new one, I am trying to get a faster way.

But it is still ok with me if there is nothing to do with this one problem 
I will soon sort my files and upload it 
Thanks anyway

**Comment by mtmorgan** [comment]
OK I'll let you sort your problem out. Remeber to version bump your package (to 0.99.6) when ready.

**Comment by JohnMengChun** [comment]
@mtmorgan I have updated some of my commands , please check it.
I was stuck in a very weird problem that if I put the r file "data_miRhubgeneoutput" in my R folder, the  error would occur when I  devtools::check()
![error1](https://user-images.githubusercontent.com/40553123/56951629-ea1d3980-6b6a-11e9-9bdb-f19d0dfc5d04.PNG)
And if I removed this file to do devtools::check(), the object 'miRhubgeneoutput' not found 
[00check.log](https://github.com/Bioconductor/Contributions/files/3130578/00check.log)
However, I could read the object miRhubgeneoutput in my rstudio.

Please give some comments on it, thanks anyway

**Comment by JohnMengChun** [comment]
And oncemore, one of my bioc-check error message is about my package size, but the data is all I need to put...
 I have no idea how to deal with such problem, please give me some instructions
Thanks again

**Comment by mtmorgan** [comment]
I'm sorry for my extreme delay.

Please address simple errors, warnings, and notes, rather than waiting for my response to more complicated questions. 

```
* Checking valid files...
    * ERROR: System Files found that should not be git tracked:
        ceRNAmiRNAfun.Rproj
```

```
* checking package subdirectories ... NOTE
Found the following CITATION file in a non-standard place:
  inst/CITATION.txt
Most likely inst/CITATION should be used instead.
```

The following means that you mention Rcpp in the Imports: field, but do not either `import()` or use, e.g., `Rcpp::...` in your code -- do you use these packages in your code? If not, remove them. If so, import the packages.
```
* checking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  Rcpp clusterGeneration gridExtra mvtnorm stats xts
  All declared Imports should be used.

```

At least some of the following functions(e.g., `clusterEvalQ`) indicate that you should `Import:` or `Suggest:` other packages (e.g., parallel), and `importFrom(parallel, clusterEvalQ)` and similar in the NAMESPACE. Clarify other symbols and in particular avoid uning programming language idioms (e.g., `subset()` that do not fully qualify variable names.

```
Undefined global functions or variables:
  Count clusterEvalQ combn cor fisherz makeCluster mir na.omit p pnorm
  w x1 x2 y1 y2
Consider adding
  importFrom("stats", "cor", "na.omit", "pnorm")
  importFrom("utils", "combn")
```

wrap long lines like this
```
* checking Rd line widths ... NOTE
Rd file 'miRhubgeneplot.Rd':
  \examples lines wider than 100 characters:
     ## use miRhubgeneplot to merge out the bridging miRNA and hub genes and then make the plot of the top miRNA expression level of modulat ... [TRUNCATED]

These lines will be truncated in the PDF manual.
```

'output' is a very bad name for a data object, provide it with a more meaningful name and provide documentation (what class it is, what sorts of data it contains, e.g., if a data.frame then describe each column so that someone other than you can understand it).

```
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  output
Undocumented data sets:
  output
All user-level objects in a package should have documentation entries.
See chapter Writing R documentation files in the Writing R
Extensions manual.
```

Your package will be added to the Bioconductor 'devel' branch, where it will be built and checked nightly against R version 3.6. Specifying an R version dependency equal to R-3.6 truthfully advertises the checked functionality.
```
* Checking R Version dependency...
    * WARNING: Update R version dependency from 3.5.0 to 3.6.
```

```
* Checking biocViews validity...
    * WARNING: 'VariantDection' is an invalid BiocViews term. Did you
      mean: 'VariantDetection'
```

```
 Checking coding practice...
    * NOTE: Avoid sapply(); use vapply()
    ...
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
    ...
    * WARNING: Use TRUE/FALSE instead of T/F
    ...
    * WARNING: Avoid class() == or class() != ; use is() or !is()
```

```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
    * ERROR: Maintainer must register at the support site; visit
      https://support.bioconductor.org/accounts/signup/ .
```

Package size

```
* Checking package size...
    * ERROR: Package Source tarball exceeds Bioconductor size
      requirement.
        Package Size: 22.3529 MB
        Size Requirement: 5.0000 MB
* Checking individual file sizes...
    * WARNING: The following files are over 5MB in size:
      'inst/extdata/TCGA-LUSC_MirnaTarget_dictionaryuse.rds'
```

- This 'rds' file should be in the `/data` directory. 
- If the full dataset is required for your package, replace the use here with an ExperimentHub-based data resource

Please address these issues. When done, post a brief comment. I will then look, promptly, at the remainder of the package.

**Comment by mtmorgan** [comment]
Please let me know when you will be able to address the issues above.

**Comment by JohnMengChun** [comment]
@mtmorgan thank you for your reply, I will fix the problems step by step and then let you know.

Thank you

**Comment by mtmorgan** [comment]
I'll mark this issue as inactive; post a comment here when you wish to continue with the review process.
