### ISSUE TITLE
RNASeqR

### ISSUE THREAD

**Issue by HowardChao** [Bioconductor/Contributions#881]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/HowardChao/RNASeqR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Looks like this is the package mentioned at https://support.bioconductor.org/p/113080 where the external system dependencies make it not suitable for Bioconductor. I can tell that you have put a lot of work into the package, and that this must be disappointing to you.

FWIW, when I tried to run
```
> RNASeqQualityAssessment_CMD(exp)
> 
nohup: appending output to 'nohup.out'
```
The code does not  generate an error, but looking at the log I see
```
> library(RNASeqR)
Error: This is R 3.4.1, package 'RNASeqR' needs >= 3.5.0
```
because your code invokes the R that is found on the search path
```
            args = paste0("R CMD BATCH ", path.prefix,
```
whereas I used my own R

**Comment by HowardChao** [comment]
Thank you for answering my questions on Bioconductor support site.

In each analysis step, this package provide two kinds of functions. Take quality assessment step for example, `RNASeqQualityAssessment()` can be run in R shell and `RNASeqQualityAssessment_CMD()` can be run in background (create an Rscript, and invoke nohup command)

To run `XXX.CMD` function, R on search path also need `R >= 3.5.0`

Because some steps in RNA-Seq need a lot of time, so running in background is the solution that I came up with.

I am curious whether `RNASeqQualityAssessment()` can bun run correctly?

**Comment by mtmorgan** [comment]
Your _CMD scripts should use the same R as the command is invoked from; this would be easy to construct using `R.home()` when you form the system command.

`RNASeqQualityAssessment()` runs, but the next command fails

```
> RNASeqQualityTrimming(exp@path.prefix,
+                         exp@sample.pattern)
⚜♜♜♜ 'RNASeqQualityTrimming()' environment pre-check ...

(✔) : RNASeqQualityTrimming() pre-check is valid


************** Quality Trimming **************

● "SRR3396381XV" quality trimming

     ● Moving "SRR3396381_XV_1.fastq.gz" to "/tmp/yeast_example/gene_data/raw_fastq.gz/original_untrimmed_fastq.gz/"

     ● Moving "SRR3396381_XV_2.fastq.gz" to "/tmp/yeast_example/gene_data/raw_fastq.gz/original_untrimmed_fastq.gz/"

     ● Start trimming ...

Error: Input/Output
  no input files found
  dirPath: /tmp/yeast_example/gene_data/raw_fastq.gz/original_untrimmed_fastq.gz/SRR3396381_XV_1.fastq.gz
  pattern: character(0)
In addition: Warning messages:
1: In file.rename(from = file1, to = file1.untrimmed) :
  cannot rename file '/tmp/yeast_example/gene_data/raw_fastq.gz/SRR3396381_XV_1.fastq.gz' to '/tmp/yeast_example/gene_data/raw_fastq.gz/original_untrimmed_fastq.gz/SRR3396381_XV_1.fastq.gz', reason 'No such file or directory'
2: In file.rename(from = file2, to = file2.untrimmed) :
  cannot rename file '/tmp/yeast_example/gene_data/raw_fastq.gz/SRR3396381_XV_2.fastq.gz' to '/tmp/yeast_example/gene_data/raw_fastq.gz/original_untrimmed_fastq.gz/SRR3396381_XV_2.fastq.gz', reason 'No such file or directory'
```
This seems to show the hazard of non-evaluated chunks in the vignette.

It's also not really clear why the `_CMD()` versions get to use the object, but the plain versions violate the API / implementation interface and require the user to access slots.

**Comment by HowardChao** [comment]
@mtmorgan  Dear Mr.Morgan: 
Thank you for your comments, I was wondering whether my vignette code would work. Thanks!

**Comment by HowardChao** [comment]
AdditionalPackage: https://github.com/HowardChao/RNASeqRData

**Comment by HowardChao** [comment]
@mtmorgan Dear Mr.Morgan:
This package is not designed for window,  I would like to skip window os version.
My package has successfully been built on OSX and Linux with code chunks on (running toy RNA-Seq data while building vignette) But the problem that I faced is that the package source tarball exceeds Bioconductor size. (size issue)
Is this error tolerable?
Thanks you very much!

**Comment by mtmorgan** [comment]
Only linux / mac is ok; any idea why the tarball is large? Is it because the images in the vignette are stored at a higher resolution than necessary?

**Comment by HowardChao** [comment]
@mtmorgan Dear Mr.Morgan:
I have resaved images in a lower resolution (300 -> 100 dpi), but the  tarball  issue is still there. 
I think the problem is about images. I put about 30 images in my vignette.
Anything I could do with the image size?
Thanks~

**Comment by HowardChao** [comment]
@mtmorgan Dear Mr.Morgan:
I have resaved images in a lower resolution (300 -> 100 dpi), but the tarball issue is still there.
I think the problem is about images. I put about 30 images in my vignette.
Anything I could do with the image size?
Thanks~

**Comment by HowardChao** [comment]
@mtmorgan Dear Mr.Morgan:
## RNASeqRData
* the package should have a vignette tihat describes the data and pre-processing steps taken to arrive at the files
> Done. I have added vignette in the package with data pre-processing steps.

* ideally, the data should be presented as an 'ExperimentHub' package where the files are stored in the ExperimentHub and retrieved / managed in the light-weight package; see
http://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html
* some of the data are available from AnnotationHub, and should be retrieved from there.
> * I am not sure whether 'ExperimentHub' package is suitable for my experiment data package. To reduce the size, I aligned true `fastq` files beforehands and extracted only reads on 'XV:0-100000' regions only. Detailed informations are in vignette.
> * Besides, the `fa` sequence file is also extracted. 
> * The 'input_files/' directory which contains all the raw data inside is the directory that user have to prepare before running this workflow. This directory must contains all these **raw files(not R object)** for running this workflow.


## RNASeqR
vignettes

* please remove .html and .R files from version control; these are generated during R CMD build
> Done

* the introduction starts with several undefined [ref]erences
> Done

* use BiocManager::install() when suggesting installation instructions
> Done

* use tempfile() and tmpdir() rather than hard-coded /tmp/yeast_example
> Done

### cmd_batch_rnaseq_environment_set.R  ~~ Next from here
* provide a 'show' method for RNASeqRParam and provide slot accessors (if required for user manipulation) rather than requiring direct slot access
> 'show' method is added. RNASeqRParam does not require direct slot access, so I do not provide slot accessors.


* review message() and paste0() (e.g., DE_DESeq2_analysis.R:190) for unnecessary use of paste0().
> Done

* remove unsed DE_TPM.R -- it is in version control anyway, and serves only to confuse the code 
> Done

* avoid cat() in code, other than to print output; e.g., DE_edgeR_analysis.R this seems to be a message() or warning() destined for diagnostic output (stderr, message, warning, error) rather than output from the program(stdout, cat).
> Changed to message. Done

Misc.

* if the NEWS file is not going to be maintained, then please remove it
> Done. Start to maintain.

* remove Rplots.pdf
> Done

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/HowardChao.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"RNASeqR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RNASeqR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
