### ISSUE TITLE
cicero

### ISSUE THREAD

**Issue by hpliner** [Bioconductor/Contributions#886]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cole-trapnell-lab/cicero

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by hpliner** [comment]
Hi @Liubuntu, Is the 5 min check time a hard limit? I'm having a hard time cutting the time without violating other rules (not enough vignette sections eval=TRUE, not enough runnable examples, etc)

**Comment by hpliner** [comment]
@Liubuntu 
I have removed basically all testing, minimized the vignette and minimized all examples and the windows check still takes more than 5 minutes (5:20ish). The other two builds are below 5 (3:30 and 4:09) .  Any ideas of what else I might do?

**Comment by lshep** [comment]
@Liubuntu will have a full technical review for you soon but in generally removing tests is not the way to achieve a better time limit -  if you have minimized the examples and vignettes (but have kept them functional)  as long as the other platforms are within the time constraint it should be ok.  I do recommend adding at least some of your testing back in.

**Comment by Liubuntu** [comment]
Hi @hpliner , 

I just came back from a vacation and will start reviewing your package. Thank you @lshep for your help when I was out. As Lori said, can you add at least some of the testing back in and the timeout on just one platform (especially Windows which usually takes longer time building on both 32 and 64 than the other two platforms) would be fine. 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @hpliner , 

Here is an initial review of your package with some major issues to fix (especially in vignette). The remaining parts for R/, man/, and tests will be reviewed soon. 

## DESCRIPTION

- remove the "Date" field.
- “LazyData:” field: For packages that include data, we recommend not including LazyData: TRUE. This rarely proves to be a good thing. In our experience it only slows down the loading of packages with large data.

## NAMESPACE

- Looks good.

## vignette 

- Introduction

Add a short Introduction section in the beginning (functioning as an abstract).

- Installation

Add a section of "Installation" to show how to download/install and load the package.

Include the following contents.

```

1. Download the package from Bioconductor.
{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
 BiocManager::install("pkgName")

Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)

 2. Load the package into R session.
 {r Load, message=FALSE}
 library(pkgName)
 ```

- TOC: Add TOC for the vignette header, with a hierarchical structure for the usage of this package.

- Add "sessionInfo" as the last section. Include runnable "sessionInfo()" and let it print the details about session information.

- Add more descriptive contents for each section. All big code chunks now.

**Comment by hpliner** [comment]
@Liubuntu Great, I'll get working on this and revert the tests as well.

**Comment by Liubuntu** [comment]
Hi @hpliner , 

Here is the review for the rest parts. Please comment back with any question, answers or ready for a 2nd look. Thanks!

## R/

Generaly looks good!

Major:
- Need runnable examples for most of the export functions.
- Remove the "utils::globalVariables()" which might cause incorrect
  usage of variables. If the warning/note raises from the report, and
  they are actually from usage of piping language, it would be just
  fine until Bioconductor have a general rule for that later.
- Add a NEWS file, so your package news will be included in
  Bioconductor release announcements. The initial version could be
  blank. Later updated please refer
  [here](https://github.com/Bioconductor/BiocManager/blob/master/NEWS)
  for new features / bug fixes...

Coding:
- use "<- " for assignment.
- Avoid using "sapply", use "vapply" which is more robust. Refer to
  the building report.
- Avoid 1:...; use `seq_len()` or `seq_along` instead. refer to the
  building report.

## man/

- Looks good!

## vignette

- Not sure if that's my problem with the internet connection, I could
  not be able to open the link you have for section "Website
  Vignette".
- To avoid the messages by running "library(cicero)" which doesn't
  make any sense inside a vignette, you may have a section with the
  following setting, which will load in the package in the background,
  and then load it again by not really evaluating. Taking BiocManager
  as an example here.

```
{r, library, echo=FALSE, message=FALSE}
library(BiocManager)
```
and then:
```
{r, eval=FALSE}
library(BiocManager)
```

- Put the visualization and advanced visualization into one section?
  With more contents and descriptions for each arguments that are
  either needed or advanced?

- Again, add more descriptive sentences for all sections, explaining
  why the step is needed, and how it is different from other methods,
  OR how each argument is supposed to be used with normal / advanced
  functions.
## tests
- Can you explain why you would have
  "tests/testthat/figs/plotting/*.svg" in this directory and why they
  are needed?

**Comment by hpliner** [comment]
@Liubuntu I believe I've made the changes you requested. The .svg files in test are for using the vdiffr package for testing, which lets you test for changes in plotting functions. Please let me know if there are any other changes that need to be made!

**Comment by Liubuntu** [comment]
Thanks for the quick reply. I'm glad that you have also changed the link for the Cicero website. Will look at the changes and get back to you soon.

**Comment by Liubuntu** [comment]
Hi @hpliner , 

Here are some minor issues on vignette. All other modifications look good!

## Vignette
- Can you take "Installation" and "sessionInfo" as a header section in same level as "Introduction". 

Cheers,
Qian

**Comment by hpliner** [comment]
Thanks Qian! This last push should do it!

**Comment by Liubuntu** [comment]
Hi @hpliner , 

Thanks for the changes. The package looks good now. Althrough by reenabling the examples, and having all the tests, there are warnings for all 3 platforms (R CMD check exceeded 5 min requirement)... but I think it's fine. I'll pass it! 

Cheers, 
Qian

**Comment by hpliner** [comment]
Thanks!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hpliner.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"cicero\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cicero

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
