### ISSUE TITLE
cTRAP

### ISSUE THREAD

**Issue by nuno-agostinho** [Bioconductor/Contributions#906]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/nuno-agostinho/cTRAP

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nuno-agostinho** [comment]
Hello @vobencha, I have now fixed all issues with the package, but I am having trouble with running R CMD check within 5 minutes. The problem is that many examples/tests make use of data that is downloaded on demand. 

I asked the question at bioc-devel, to which Lori Shepherd replied to check BiocFileCache. Still, wouldn't this make the build fail since it has to download everything the first time to create the cache?

**Comment by vobencha** [comment]
Hi @nuno-agostinho ,

I'd recommend creating small sample data files for the man pages and vignette. Put them in cTRAP/data/ or cTRAP/inst/extdata. Documentation on what type of file goes where is here:
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Data-in-packages

Once this is done you can load the file with system.file() or data() - there is no need to create your own function, loadInternalData().

This solution assumes you're downloading data in man pages or vignette, not internally with your package functions. The package functions should avoid downloading on the fly - they will be broken when the user has no internet access.

Valerie

**Comment by vobencha** [comment]
If the package is ready for re-review please articulate what changes were made wrt 
https://github.com/Bioconductor/Contributions/issues/906#issuecomment-428606791

**Comment by nuno-agostinho** [comment]
Hey @vobencha, as per [the comparison between commit 5c8c972 and the current master (commit 6257e75)](https://github.com/nuno-agostinho/cTRAP/compare/5c8c972...6257e75), the following changes were made:

- Data files are now stored in `cTRAP/data` (for external use) instead of `cTRAP/R/sysdata.rda` (for internal use)
- As you suggested, small sample data files were created for the man pages and vignette; they are stored in the `cTRAP/data` folder and their respective documentation (including code on how to obtain the same sample data) is in the `cTRAP/R/cTRAP-package.r` file
- As you suggested, internal data is loaded using the built-in `data()`function instead of the `loadInternalData()` function that was created for a redundant purpose
- Code to download and filter/process data was isolated into new functions (`downloadENCODEsamples()`, `downloadL1000data()`, `filterL1000metadata()` and `prepareENCODEgeneExpression()`), so users are able to explicitly use the output of those functions as input for downstream functions
- Changes were made to function examples, test units and vignette to reflect and leverage the new small data samples and functions, among the other changes reported here

## Bug fixes, copy-editing and minor changes
- The file `cTRAP/R/l1000-package.r` was renamed to `cTRAP/R/cTRAP-package.r` as the name of the package was changed cTRAP (I apologise for this as I forgot to rename this file before sending this for review)
- `performDifferentialExpression()` returned a single mean-aggregate result of differential gene expression statistic for all genes whose ENSEMBL identifier did not match any gene symbol; the mean-aggregate value of such genes is now removed before returning the results
- Function/variable names with `L1000` were uniformed: any letter in a function/variable after `L1000` is now lowercase for consistency purposes (e.g. `getL1000Conditions()` is now `getL1000conditions()`)
- Expanded the examples for the `plotL1000comparison()` function

**Comment by vobencha** [comment]
Excellent. Thanks for making the changes.

Just a few things left:
- All man pages need running examples if possible; if there are exceptions please explain.
- Remove vignettes/tutorial.R; only the vignette and graphic files should be in there.
- Consider renaming the vignette to something more descriptive related to the package name.

We have until COB Oct 24 to get this in Bioc 3.8. These last issues shouldn't take much time - we should be able to make it.

Thanks.
Valerie

**Comment by nuno-agostinho** [comment]
Hey @vobencha, thank you for the quick reply. I would like to make the following comments on your points:

> All man pages need running examples if possible; if there are exceptions please explain.

Do man pages for internal functions also need examples?

Regarding exported functions with no runnable examples, there are 3: `downloadENCODEsamples()` and `downloadL1000data()` have no runnable examples as they take time to download the data; `loadL1000perturbations()` requires the data downloaded from those functions and I thought it would be more useful to the user to have a non-runnable example with the code to download the needed files and running the function in question.

> Consider renaming the vignette to something more descriptive related to the package name.

The vignette (previously named  *CTRAP: tutorial*) will be renamed to **cTRAP: differential expression comparison with cellular perturbations**.

**Comment by nuno-agostinho** [comment]
> You could put a code chunk there and wrap in interactive()

I will replace the `\dontrun{` with `if (interactive() ) {` in the examples of the functions `downloadENCODEsamples()`, `downloadL1000data()` and `loadL1000perturbations()`.

> Re: vignette name, I was specifically thinking of the R code file name. Currently the filename is tutorial.Rmd.

I will rename the vignette to `comparing_DGE_with_perturbations.Rmd`.

As you suggested in your previous comment, I will also remove the `vignettes/tutorial.R` file. Do you agree with these changes?

**Comment by vobencha** [comment]
Looks good! Thanks.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/nuno-agostinho.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install(\"cTRAP\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cTRAP

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
