### ISSUE TITLE
(inactive) methyLImp

### ISSUE THREAD

**Issue by pdilena** [Bioconductor/Contributions#924]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pdilena/methyLImp

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your functions should use data representations such as SummarizedExperiment as inputs / outputs, to enhance interoperability with other Bioconductor packages; see [[1][]]

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by pdilena** [comment]
thank you for the suggestion, I was not aware of the SummarizedExperiment package, 
as it appears to be released just three weeks ago.

I will look into it and certainly consider it for integration in the next release of the mehtyLImp package.

The current implementation of methyLImp does not depend on a particular data container.

**Comment by mtmorgan** [comment]
FWIW the SummarizedExperiment package has been available for more than three years, as you can see from the 'in bioc' tag at the top of the '[landing page][1]'

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by hpages** [comment]
Hi @pdilena 

Thanks for submitting the methyLImp package. The package doesn't seem to be ready for review yet. In particular the current vignette would need to be significantly improved. Keep in mind that a vignette should be a user-friendly document that shows a typical workflow with the package. Right now 90% of the document is filled with the output of 4 commands. This should be avoided. Besides that, the vignette contains very little useful information.

Some other problems with the vignette:
- It has empty subsections:

    0.0.1 The methyLImp Package
    0.1 Pietro Di Lena
    0.5 Suggested analysis workflow

- The structure of the document and the numbering of the sections/subsections make no sense.

- The installation subsection should show the proper way to install a Bioconductor package (see https://bioconductor.org/install/)

Please make sure the package satisfies our guidelines here https://bioconductor.org/developers/package-guidelines/ before we can start the review process.

Thanks,
H.

**Comment by pdilena** [comment]
Hi H.,

we're finalizing the updated version of the vignette. it will be pushed 
shortly.

Thanks,

pdilena


Il 2019-01-24 16:58 hpages ha scritto:
