### ISSUE TITLE
GAPGOM (novel Gene Annotation Prediction and other GO Metrics)

### ISSUE THREAD

**Issue by Berghopper** [Bioconductor/Contributions#947]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Berghopper/GAPGOM

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Berghopper** [comment]
I also wanted to note that, while I understand how the branches work, I haven't implemented these yet on my repository.

**Comment by Berghopper** [comment]
Ok so I fixed a few errors/notes but some I have some questions for;

I fixed;

Version error (bumped the version in latest commit).
Some other smaller notes.

Problems;

```
 * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples. The following pages do not:
      fantom_download.Rd, fantom_load_raw.Rd, fantom_to_expset.Rd
```

This happens because I am using the `\dontrun{}` clause in some of my function as they are dependent on FANTOM5 data being downloaded. This can take very long and takes up a lot of space so I want to skip it in the `R CMD check`. Any tips?

The timeout happens probably because the algorithms themselves are pretty intensive/take long to complete. I could do less rigorous testing/change the examples in my package to compensate if necessary.

Besides this I don't know how much sense it makes to add a bunch of parsing functions for FANTOM5 specifically. It helps, but is not necessary and maybe not very atomic seeing the package description. I'd like some input on that if this should be removed/changed.

Thanks in advance!

**Comment by mtmorgan** [comment]
I'll review the package as-is in the next day or so. You should anticipate revising your examples to use less time-consuming examples / vingette / tests; I'll have specific recommendations about FANTOM5 when I review the package.

**Comment by mtmorgan** [comment]
DESCRIPTION

- consider using AnnotationHub for access to annotation resources, rather than packages. This reduces the dependnecies in your package and opens the possibliity for access to more organisms. (The result of `[[` is cached, so the download occurs only once...

    ```
    > library(AnnotationHub)
    > hub = AnnotationHub()
    snapshotDate(): 2018-11-01
    > query(hub, "OrgDb")
    AnnotationHub with 2002 records
    # snapshotDate(): 2018-11-01 
    # $dataprovider: ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/, FungiDB, TriTrypDB, ...
    # $species: Toxoplasma gondii, Fusarium oxysporum, Entamoeba histolytica, Hi...
    # $rdataclass: OrgDb
    # additional mcols(): taxonomyid, genome, description,
    #   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
    #   rdatapath, sourceurl, sourcetype 
    # retrieve records with, e.g., 'object[["AH65001"]]' 
    
                title                                                              
      AH65001 | Edhazardia aedis USNM 41457 genome wide annotations                
      AH65002 | Aspergillus versicolor CBS 583.65 genome wide annotations          
      AH65003 | Aspergillus sydowii CBS 593.65 genome wide annotations             
      AH65004 | Phytophthora cinnamomi var. cinnamomi CBS 144.22 genome wide ann...
      AH65005 | Trypanosoma vivax Y486 genome wide annotations                     
      ...       ...                                                                
      AH67895 | org.Vibrio_vulnificus.eg.sqlite                                    
      AH67896 | org.Achromobacter_group_B.eg.sqlite                                
      AH67897 | org.Achromobacter_group_E.eg.sqlite                                
      AH67898 | org.Pannonibacter_phragmitetus.eg.sqlite                           
      AH67899 | org.Salinispora_arenicola_CNS-205.eg.sqlite                        
    > query(hub, "org.EcK12")
    AnnotationHub with 1 record
    # snapshotDate(): 2018-11-01 
    # names(): AH66153
    # $dataprovider: ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/
    # $species: Escherichia coli
    # $rdataclass: OrgDb
    # $rdatadateadded: 2018-10-22
    # $title: org.EcK12.eg.db.sqlite
    # $description: NCBI gene ID based annotations about Escherichia coli
    # $taxonomyid: 511145
    # $genome: NCBI genomes
    # $sourcetype: NCBI/ensembl
    # $sourceurl: ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/, ftp://ftp.ensembl.org/p...
    # $sourcesize: NA
    # $tags: c("NCBI", "Gene", "Annotation") 
    # retrieve record with 'object[["AH66153"]]' 
    > db = hub[["AH66153"]]
    downloading 1 resources
    retrieving 1 resource
      |======================================================================| 100%
    
    loading from cache 
        '/Users/ma38727//.AnnotationHub/72899'
    ```

- Capitalize Title:
- Provide a 'Description:' field that reads more like an abstract guiding the user to the specific functionality your pacakge provides.
- No need to provide Author: or Maintainer: when Authors@R is used

NAMESPACE

- this entry `importFrom(plyr,.)` looks incorrect

vignettes

- GAPGOM.Rmd:57 no need to separately install dependencies or to invoke BiocManager with no argument
    ```
    if (!requireNamespace("BiocManager"))
        install.packages("BiocManager")
    BiocManager::install("GAPGOM")
    ```

  add argument `dependencies = TRUE` to install Suggests: as well; see `?install.packages`, which is what `BiocManager::install()` uses.

- please evaluate more chunks, e.g., those at lines 130 and 149; use `head(expressions)` rather than `View()` for vignettes.

- the problem with eval=FALSE code chunks is that they quickly become broken, for instance I see

    ```
    > fantom_file <- fantom_download("./", organism = "mouse", 
                               noprompt = TRUE) # saves filename
    # load the file (use fantom_file variable if doing all at once)
    ft5 <- fantom_load_raw("./mm9.cage_peak_phase1and2combined_tpm_ann.osc.txt", 
    verbose = TRUE)
    + > 
    trying URL 'http://fantom.gsc.riken.jp/5/datafiles/latest/extra/CAGE_peaks/mm9.cage_peak_phase1and2combined_tpm_ann.osc.txt.gz'
    Content type 'text/html' length 442 bytes
    ==================================================
    downloaded 442 bytes
    
    > > + > 
    [1] "reading header variables..."
    [1] "DONE"
    [1] "loading dataframe..."
    [1] "DONE"
    [1] "formatting column names..."
    Error in setnames(x, value) : 
      Passed a vector of type 'list'. Needs to be type 'character'.
    ```

- GAPGOM.Rmd:256 never use direct slot access, instead use accessors `fData()` and `fData(GAPGOM::expset)$GeneType` in this case

- GAPGOM.Rmd:331 this code chunk is not useful to the end user; place it instead in, e.g., inst/script/.

R

- reconsider the need for a startup message; if all packages did this then the user is simply overwhelmed and ignores it.
- argument_checks.R:87 and many other places: `message()`, `stop()`, `warning()` etc do not generally need to have `paste()` inside them; the arguments are paste'd together internally.
- e.g., argument_checks.R:127 and elsewhere consider adopting an identation style (e.g., by 2 or 4 spaces each indentation level, rather than to the same level as the closing parenthesis) that allows for longer lines and more consistent formatting. Nested 'message()` statements are unlikely to be needed; single and double quotes can be used interchangeably at the outer level to create relatively more clean messages. e.g.,

    ```
    message(
        "Incorrectly specific method! Must be one of the following: '",
        paste0(methods, collapse="', '"),
        "'"
    )
    ```

- data_preparation.R:64 no need to call `cmpfun` explicitly; functions are compiled when the package is installed.
- data_preparation.R:290 `eval(parse())` is seldom necessary, and is not needed here.
- data_preparation.R:337 this looks very inefficient, likely making a copy o fthe entire matrix each time a single element is updated. Also, this seems to be fully vectorizeable (no explicit iteration required).
- data_preparation.R:362 this also looks like it can be vectorized, eg., 
  ```
  idx <- cbind(matched_by_row, matched_by_row)
  score_matrix[idx] <- 1.0
  ```
- topoicsim_algorithms.R:224 this vapply (and similar elsewhere) might be replaced by `matrixStats::rowMax()`.
- For FANTOM download, consider using BiocFileCache as outlined in http://bioconductor.org/packages/devel/bioc/vignettes/BiocFileCache/inst/doc/BiocFileCache.html#local-cache-of-an-internet-resource

man, tests

- OK

OTHER

- make sure your NEWS.md file can be parsed by `utils::news()`.

**Comment by Berghopper** [comment]
> DESCRIPTION
> 
>     * consider using AnnotationHub for access to annotation resources, rather than packages. This reduces the dependnecies in your package and opens the possibliity for access to more organisms. (The result of `[[` is cached, so the download occurs only once...
>       ```
>       > library(AnnotationHub)
>       > hub = AnnotationHub()
>       snapshotDate(): 2018-11-01
>       > query(hub, "OrgDb")
>       AnnotationHub with 2002 records
>       # snapshotDate(): 2018-11-01 
>       # $dataprovider: ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/, FungiDB, TriTrypDB, ...
>       # $species: Toxoplasma gondii, Fusarium oxysporum, Entamoeba histolytica, Hi...
>       # $rdataclass: OrgDb
>       # additional mcols(): taxonomyid, genome, description,
>       #   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
>       #   rdatapath, sourceurl, sourcetype 
>       # retrieve records with, e.g., 'object[["AH65001"]]' 
>       
>                   title                                                              
>         AH65001 | Edhazardia aedis USNM 41457 genome wide annotations                
>         AH65002 | Aspergillus versicolor CBS 583.65 genome wide annotations          
>         AH65003 | Aspergillus sydowii CBS 593.65 genome wide annotations             
>         AH65004 | Phytophthora cinnamomi var. cinnamomi CBS 144.22 genome wide ann...
>         AH65005 | Trypanosoma vivax Y486 genome wide annotations                     
>         ...       ...                                                                
>         AH67895 | org.Vibrio_vulnificus.eg.sqlite                                    
>         AH67896 | org.Achromobacter_group_B.eg.sqlite                                
>         AH67897 | org.Achromobacter_group_E.eg.sqlite                                
>         AH67898 | org.Pannonibacter_phragmitetus.eg.sqlite                           
>         AH67899 | org.Salinispora_arenicola_CNS-205.eg.sqlite                        
>       > query(hub, "org.EcK12")
>       AnnotationHub with 1 record
>       # snapshotDate(): 2018-11-01 
>       # names(): AH66153
>       # $dataprovider: ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/
>       # $species: Escherichia coli
>       # $rdataclass: OrgDb
>       # $rdatadateadded: 2018-10-22
>       # $title: org.EcK12.eg.db.sqlite
>       # $description: NCBI gene ID based annotations about Escherichia coli
>       # $taxonomyid: 511145
>       # $genome: NCBI genomes
>       # $sourcetype: NCBI/ensembl
>       # $sourceurl: ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/, ftp://ftp.ensembl.org/p...
>       # $sourcesize: NA
>       # $tags: c("NCBI", "Gene", "Annotation") 
>       # retrieve record with 'object[["AH66153"]]' 
>       > db = hub[["AH66153"]]
>       downloading 1 resources
>       retrieving 1 resource
>         |======================================================================| 100%
>       
>       loading from cache 
>           '/Users/ma38727//.AnnotationHub/72899'
>       ```
> 
>     * Capitalize Title:
> 
>     * Provide a 'Description:' field that reads more like an abstract guiding the user to the specific functionality your pacakge provides.
> 
>     * No need to provide Author: or Maintainer: when Authors@R is used
> 
> 
> NAMESPACE
> 
>     * this entry `importFrom(plyr,.)` looks incorrect
> 
> 
> vignettes
> 
>     * GAPGOM.Rmd:57 no need to separately install dependencies or to invoke BiocManager with no argument
>       ```
>       if (!requireNamespace("BiocManager"))
>           install.packages("BiocManager")
>       BiocManager::install("GAPGOM")
>       ```
>       add argument `dependencies = TRUE` to install Suggests: as well; see `?install.packages`, which is what `BiocManager::install()` uses.
> 
>     * please evaluate more chunks, e.g., those at lines 130 and 149; use `head(expressions)` rather than `View()` for vignettes.
> 
>     * the problem with eval=FALSE code chunks is that they quickly become broken, for instance I see
>       ```
>       > fantom_file <- fantom_download("./", organism = "mouse", 
>                                  noprompt = TRUE) # saves filename
>       # load the file (use fantom_file variable if doing all at once)
>       ft5 <- fantom_load_raw("./mm9.cage_peak_phase1and2combined_tpm_ann.osc.txt", 
>       verbose = TRUE)
>       + > 
>       trying URL 'http://fantom.gsc.riken.jp/5/datafiles/latest/extra/CAGE_peaks/mm9.cage_peak_phase1and2combined_tpm_ann.osc.txt.gz'
>       Content type 'text/html' length 442 bytes
>       ==================================================
>       downloaded 442 bytes
>       
>       > > + > 
>       [1] "reading header variables..."
>       [1] "DONE"
>       [1] "loading dataframe..."
>       [1] "DONE"
>       [1] "formatting column names..."
>       Error in setnames(x, value) : 
>         Passed a vector of type 'list'. Needs to be type 'character'.
>       ```
> 
>     * GAPGOM.Rmd:256 never use direct slot access, instead use accessors `fData()` and `fData(GAPGOM::expset)$GeneType` in this case
> 
>     * GAPGOM.Rmd:331 this code chunk is not useful to the end user; place it instead in, e.g., inst/script/.
> 
> 
> R
> 
>     * reconsider the need for a startup message; if all packages did this then the user is simply overwhelmed and ignores it.
> 
>     * argument_checks.R:87 and many other places: `message()`, `stop()`, `warning()` etc do not generally need to have `paste()` inside them; the arguments are paste'd together internally.
> 
>     * e.g., argument_checks.R:127 and elsewhere consider adopting an identation style (e.g., by 2 or 4 spaces each indentation level, rather than to the same level as the closing parenthesis) that allows for longer lines and more consistent formatting. Nested 'message()` statements are unlikely to be needed; single and double quotes can be used interchangeably at the outer level to create relatively more clean messages. e.g.,
>       ```
>       message(
>           "Incorrectly specific method! Must be one of the following: '",
>           paste0(methods, collapse="', '"),
>           "'"
>       )
>       ```
> 
>     * data_preparation.R:64 no need to call `cmpfun` explicitly; functions are compiled when the package is installed.
> 
>     * data_preparation.R:290 `eval(parse())` is seldom necessary, and is not needed here.
> 
>     * data_preparation.R:337 this looks very inefficient, likely making a copy o fthe entire matrix each time a single element is updated. Also, this seems to be fully vectorizeable (no explicit iteration required).
> 
>     * data_preparation.R:362 this also looks like it can be vectorized, eg.,
>       ```
>       idx <- cbind(matched_by_row, matched_by_row)
>       score_matrix[idx] <- 1.0
>       ```
> 
>     * topoicsim_algorithms.R:224 this vapply (and similar elsewhere) might be replaced by `matrixStats::rowMax()`.
> 
>     * For FANTOM download, consider using BiocFileCache as outlined in http://bioconductor.org/packages/devel/bioc/vignettes/BiocFileCache/inst/doc/BiocFileCache.html#local-cache-of-an-internet-resource
> 
> 
> man, tests
> 
>     * OK
> 
> 
> OTHER
> 
>     * make sure your NEWS.md file can be parsed by `utils::news()`.

Dear Morgan,

I added most of your suggested edits, I however still had some comments on some of them. Please consider reading my concerns below on some of them.

# DESCRIPTION

- consider using AnnotationHub

I will leave this out for now as the package is hugely dependent on GOSemSim as it is right now. Mainly the Information Content (IC) calculations and the `GOSemSimDATA` object are very handy and would take quite some more time to implement myself. As this project is part of an internship that is soon ending, I don't think I can change this in time. I'll still add it to the readme/news as a possible new feature.

[x] Capitalize Title

[x] Provide a 'Description:' field that reads more like an abstract guiding the user to the specific functionality your pacakge provides.

[x] No need to provide Author: or Maintainer: when Authors@R is used

# NAMESPACE

- this entry `importFrom(plyr,.)` looks incorrect

This is actually not the case and caused me a lot of frustration in the beginning of my project;

`plyr` uses the `.` function to make it able to use a variable as an abstraction in code. Even though it might look odd, I'm 99% sure this import is correct.

# vignettes

[x] GAPGOM.Rmd:57 no need to separately install dependencies or to invoke BiocManager with no argument

[x] please evaluate more chunks, e.g., those at lines 130 and 149; use head(expressions) rather than View() for vignettes.

(I only did this for the main vignette, because I wanted to keep the benchmarks as-is and running time would take too long otherwise).

- the problem with `eval=FALSE` code chunks is that they quickly become broken, for instance I see

Very true, and I agree. However the example you gave, only broke because the fantom website seems to be offline right now because of security issues? Just a funny coincidence with timing I suppose. 

I will still do a double check on the benchmarks at the last minute before release, and just not touch it afterwards (if that's ok). Like mentioned earlier, I'm afraid this vignette would take too long to build otherwise.

[x] GAPGOM.Rmd:256 never use direct slot access, instead use accessors fData() and fData(GAPGOM::expset)$GeneType in this case

Yep, missed this one, thanks :).

[x] GAPGOM.Rmd:331 this code chunk is not useful to the end user; place it instead in, e.g., inst/script/.

Moved to `inst/script/` and added the original scripts the package is based on.

# R

- reconsider the need for a startup message; if all packages did this then the user is simply overwhelmed and ignores it.

In what case should one add or leave out a startup message? I could not find a good example on this. Besides this, people still use `suppressPackageStartupMessages()` to ignore it.

[x] argument_checks.R:87 and many other places: `message()`, `stop()`, `warning()` etc do not generally need to have `paste()` inside them; the arguments are paste'd together internally.

[x] e.g., argument_checks.R:127 and elsewhere consider adopting an identation style (e.g., by 2 or 4 spaces each indentation level, rather than to the same level as the closing parenthesis) that allows for longer lines and more consistent formatting. Nested `message()` statements are unlikely to be needed; single and double quotes can be used interchangeably at the outer level to create relatively more clean messages. e.g.,

[x] data_preparation.R:64 no need to call `cmpfun` explicitly; functions are compiled when the package is installed.

- data_preparation.R:290 `eval(parse())` is seldom necessary, and is not needed here.

Sadly, `keytypes()` does not evaluate if you give it strings, it wants you to give it the `org.db` **object**. I think I might be able to change the `switch` clause and make it so the actual library object is in there. I am worried though, that in that case I'd need to call `library()` as well; I don't think it'd be handy to add ALL the database libraries as a necessary import either. GOSemSim itself actually calls `library()` because of this.

[x] data_preparation.R:337 this looks very inefficient, likely making a copy o fthe entire matrix each time a single element is updated. Also, this seems to be fully vectorizeable (no explicit iteration required).

- data_preparation.R:362 this also looks like it can be vectorized, eg.,

Since the matrix is actually not always mirrored and positions of identical items can differ, this may not be solved by using `cbind`. I could still take a second look to see if I can make it vectorized. In my experience it tends to be hard to vectorize these kinds of assignments (with specific indices)

[x] topoicsim_algorithms.R:224 this vapply (and similar elsewhere) might be replaced by `matrixStats::rowMax()`.

- For FANTOM download, consider using BiocFileCache as outlined in http://bioconductor.org/packages/devel/bioc/vignettes/BiocFileCache/inst/doc/BiocFileCache.html#local-cache-of-an-internet-resource

I will still add this as it does seem really nice and handy for the end-users;

However, does it also resolve the timing issue on the testing servers (with my examples etc)? I'd imagine it'd still need to download on there.

# man, tests

OK

# OTHER

[x] make sure your NEWS.md file can be parsed by utils::news().

The .md should be able to be parsed. I specifically asked this to Lori Shepherd on the mailing list a while back. With the latest R-devel you should be able to parse it with `tools:::.build_news_db_from_package_NEWS_md("NEWS.md")`. This is not properly updated yet on the website according to her, and she said she'd update it. I could also make the "legacy" news file if you so desire and make it parsable that way.

Thanks in advance for considering my comments!

Version as of writing this comment; 0.99.6

**Comment by Berghopper** [comment]
Dear @mtmorgan 

I seem to be having trouble reproducing the errors from the build report, and I do not fully understand why it's giving me the errors that it is.

For me the cmd check finishes correctly with 1 note;

```
* checking examples ... OK
Examples with CPU or elapsed time > 5s
                    user system elapsed
topo_ic_sim_genes 38.525  0.229  38.690
set_go_data        5.215  0.063   5.286
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ... SKIPPED
* checking re-building of vignette outputs ... SKIPPED
* checking PDF version of manual ... OK
* DONE

Status: 1 NOTE
See
  ‘/home/casper/GAPGOM.Rcheck/00check.log’
for details.
```

I used the same parameters as in the build report, yet on the servers, it seems to be crashing:

```
* checking examples ... ERROR
Running examples in GAPGOM-Ex.R failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: topo_ic_sim_genes
> ### Title: GAPGOM - topo_ic_sim_genes()
> ### Aliases: topo_ic_sim_genes
> 
> ### ** Examples
> 
> # single gene mode
> result <- GAPGOM::topo_ic_sim_genes("human", "MF", "218", "501")

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |===                                                                   |   4%Error in length(common_ancestors) != 0 && !is.na(common_ancestors) : 
  'length(x) = 6 > 1' in coercion to 'logical(1)'
Calls: <Anonymous> ... withCallingHandlers -> .topo_ic_sim_g1g2 -> .topo_ic_sim_titj
Execution halted
* checking for unstated dependencies in tests ... OK
* checking tests ...
  Running testthat.R [29s/29s]
 [30s/30s] ERROR
Running the tests in tests/testthat.R failed.
Last 20 lines of output:
   3. Error: topoicsim geneset level (@test_topo.R#29)  
  'length(x) = 5 > 1' in coercion to 'logical(1)'
  1: expect_equal(testgenesettopo(), gapgom_tests$maintopo_baseresult) at testthat/test_topo.R:29
  2: quasi_label(enquo(object), label)
  3: eval_bare(get_expr(quo), get_env(quo))
  4: testgenesettopo()
  5: GAPGOM::topo_ic_sim_genes("human", "MF", list1[1:5], list1[1:5], use_precalculation = TRUE, 
         progress_bar = FALSE) at testthat/test_topo.R:21
  6: suppressMessages(.topo_ic_sim_geneset(genes1, genes2, topoargs))
  7: withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
  8: .topo_ic_sim_geneset(genes1, genes2, topoargs)
  9: .topo_ic_sim_g1g2(gene1, gene2, topoargs_gen)
  10: .topo_ic_sim_titj(go1, go2, topoargs)
  
   testthat results  
  OK: 9 SKIPPED: 0 FAILED: 3
  1. Error: topoicsim term level (@test_topo.R#5) 
  2. Error: topoicsim gene level (@test_topo.R#11) 
  3. Error: topoicsim geneset level (@test_topo.R#29) 
  
  Error: testthat unit tests failed
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in inst/doc ... OK
* checking running R code from vignettes ... SKIPPED
* checking re-building of vignette outputs ... SKIPPED
* checking PDF version of manual ... OK
* DONE

Status: 2 ERRORs, 1 NOTE
See
  /home/pkgbuild/packagebuilder/workers/jobs/947/6306f3d/GAPGOM.Rcheck/00check.log
for details.


```

I've never seen this line of code fail in the lifetime of the project, and I cannot reproduce this exact error on my machine. My environment is as follows;

```
> sessionInfo()
R Under development (unstable) (2019-01-07 r75958)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS: /usr/local/lib64/R/lib/libRblas.so
LAPACK: /usr/local/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=nl_NL.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=nl_NL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] GAPGOM_0.99.10

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0           plyr_1.8.4           compiler_3.6.0       pillar_1.3.1         dbplyr_1.2.2        
 [6] bindr_0.1.1          tools_3.6.0          digest_0.6.18        bit_1.1-14           lattice_0.20-38     
[11] BiocFileCache_1.7.0  RSQLite_2.1.1        memoise_1.1.0        tibble_2.0.0         pkgconfig_2.0.2     
[16] rlang_0.3.0.1        graph_1.61.0         Matrix_1.2-15        igraph_1.2.2         GEOquery_2.51.5     
[21] DBI_1.0.0            rstudioapi_0.8       curl_3.2             yaml_2.2.0           parallel_3.6.0      
[26] bindrcpp_0.2.2       xml2_1.2.0           org.Mm.eg.db_3.7.0   dplyr_0.7.8          httr_1.4.0          
[31] hms_0.4.2            S4Vectors_0.21.9     IRanges_2.17.4       rappdirs_0.3.1       grid_3.6.0          
[36] stats4_3.6.0         bit64_0.9-7          tidyselect_0.2.5     glue_1.3.0           data.table_1.11.8   
[41] Biobase_2.43.0       R6_2.3.0             AnnotationDbi_1.45.0 RBGL_1.59.1          GOSemSim_2.9.0      
[46] limma_3.39.3         GO.db_3.7.0          tidyr_0.8.2          readr_1.3.1          purrr_0.2.5         
[51] blob_1.1.1           org.Hs.eg.db_3.7.0   magrittr_1.5         matrixStats_0.54.0   BiocGenerics_0.29.1 
[56] assertthat_0.2.0     crayon_1.3.4  
```

Any tips? Or should I try post on the mailing list?

**Comment by lshep** [comment]
See [R Check Environment](http://bioconductor.org/developers/package-guidelines/#checkingenv) .  This might be the cause and how you could reproduce on your system.

**Comment by Berghopper** [comment]
Thanks @lshep !

The build more or less finishes now as expected, with the expected error that too much code isn't being ran (dontrun clause).

**Comment by mtmorgan** [comment]
The problem with dontrun examples is that they hide broken code. For instance the example on fantom_download() returns
```
>     fantom_file <- fantom_download("./", organism = "mouse", noprompt = TRUE)
adding rname 'http://fantom.gsc.riken.jp/5/datafiles/latest/extra/CAGE_peaks/mm9.cage_peak_phase1and2combined_tpm_ann.osc.txt.gz'
  |======================================================================| 100%

Error in if (unpack) { : argument is not interpretable as logical
```
Now that this function uses BiocFileCache the 'downloads' will be fast and reliable and the function can be evaluated in the example. The unpack operation could use a file location returned by 
```
rname = basename(tools::file_path_sans_ext(full_filename))
if (!nrow(bfcquery(bfc, query = rname, field = rname))
   ## unpack to bfcnew(bfc, rname)
```

At least some of
```
Undefined global functions or variables:
  V1 V2 nei to
```
(e.g., `nei`) seem to be true positives; please investigate.

Thanks for your other changes

**Comment by Berghopper** [comment]
Dear @mtmorgan 

I have fixed the Error (at least locally) and there should be no Errors or Warnings.
However; Sadly because the server still needs to download the file, it takes too long and throws the warning that it exceeds the time limit. Do you want me to reverse this by adding the dontrun clauses again? Or do we just ignore the error?

On the R CMD check note about the global variables;

So technically R CMD check isn't wrong, but this is hard to prevent. It is an artifact of the libraries `igraph` and `data.table`. An example of a similar problem with [ggplot2](https://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when).

The `V1` and `V2` are occuring in the `.unique_combos()` function, the other two occur in `.longest_path()`.

`nei` and `to` are internal indexing functions of igraph, hence why check doesn't like it; they aren't defined in the package's namespace.

`V1` and `V2` are also index abstractions, this happens internally somewhere in `magrittr` package.

Now, I can set these variables to NULL in the beginning of both functions kind of as a work around, or we keep the note. For now I'll add the NULL definitions as a work around.

Thanks :)

P.S. before package release I will do 1 last commit to ensure that the benchmarks still run properly and update them if necessary.

**Comment by mtmorgan** [comment]
Where do we stand with this package? Is it ready for final review?

**Comment by Berghopper** [comment]
@mtmorgan I would say so, I tried fixing everything I could.
The only thing that is still really annoying to fix, mainly because the build server has time constrictions, is the fantom download functions. It DOES work with local testing, but the server cannot allocate the data properly/things it takes too long to download.

Is there still anything that needs changing before it could get accepted?

**Comment by Berghopper** [comment]
@mtmorgan @lshep bump, how far along is the review process? :)

**Comment by mtmorgan** [comment]
Sorry for the delay. The windows error is because the example is too large. The Mac warning is because the example(s) run too long. Both can be addressed by a carefully chosen example that uses less memory in a shorter period of time.

**Comment by Berghopper** [comment]
@mtmorgan I fixed the delays by skipping some non-critical tests and introducing only a part of the fantom file during the example. Everything should be ok now :)

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Berghopper.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GAPGOM")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GAPGOM

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by Berghopper** [comment]
@mtmorgan 
Thanks for accepting the package!

I still had a few questions regarding the git servers:

Will my package (now 0.99.23) be automatically bumped to 1.0.0 and 1.1.0 in devel when Bioconductor 3.9 releases?

A more specific question, and maybe a little more important: I will be the lead developer for the package for at least the next ~3 months, after this, I will probably hand off my package to my supervisors. How would this work/how should I change the repos to accommodate their user?

**Comment by mtmorgan** [comment]
Bioconductor will manage release-based version bumps.

If you were going to continue to be involve, the recommendation would be to add collaborators to your github repository, with you continuing to push to bioc http://bioconductor.org/developers/how-to/git/add-collaborators/

If you're really changing maintainers, follow http://bioconductor.org/developers/how-to/git/change-maintainer/

**Comment by Berghopper** [comment]
@mtmorgan Alright thanks! One last question: for some reason the build server is still throwing errors (invalid description file?: https://bioconductor.org/checkResults/3.9/bioc-LATEST/GAPGOM/) and I was wondering if there's a more descriptive build output. Could have maybe messed up the versioning accidentally as I was messing around with that, hence my previous question.

**Comment by mtmorgan** [comment]
you should be asking these questions on the bioc-devel mailing list rather than on this issue, so that others in a similar boat (and those better able to answer than the people on this issue) can benefit / contribute.

The error is somehow 'catastrophic' in the build system; I believe it comes from the poorly formed Maintainer: field where there is no author name. When using `Authors@R:` it is not necessary to use `Maintainer:`.

**Comment by Berghopper** [comment]
@mtmorgan Alright, thanks, I'll be sure to post it next time. I think I've fixed the issue now :)
