### ISSUE TITLE
pram

### ISSUE THREAD

**Issue by pliu55** [Bioconductor/Contributions#948]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pliu55/pram

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by pliu55** [comment]
Hi @nturaga 

My submitted package was labeled as 'OK' by @bioc-issue-bot . According to the 'Package Submission' instruction, the next step would be waiting for you to review my package.  I am wondering if there is anything I should do to trigger this process?  Do I need to bump version or just simply wait for your review?  This is my first to submit a package to Bioconductor.  Your suggestion will be highly appreciated.  Thank you.

Best,
Peng

**Comment by pliu55** [comment]
Hi @nturaga 

Thanks for your prompt reply.  I appreciate it.

Best,
Peng

**Comment by pliu55** [comment]
Hi @nturaga 

When possible, could you please review my package and post a review?  Thank you.

Best,
Peng

**Comment by nturaga** [comment]
Hi,

I'll get back to you today. Thanks.

Nitesh

**Comment by pliu55** [comment]
Thanks @nturaga.  I appreciate your help.

Best,
Peng

**Comment by pliu55** [comment]
> Hi, I'll get back to you today. Thanks. Nitesh
> […](#)

Hi @nturaga ,

Just checking in to make sure I didn't miss your note.  You said that you will get back to me the day before yesterday, but I haven't seen any of your messages so far. Thanks.

Best,
Peng

**Comment by nturaga** [comment]
# pram review

## R CMD build

* ok

## R CMD INSTALL

* ok

## DESCRIPTION

* 'Description' section is not enough, think of the this like the
  abstract of a paper. Please elaborate.

## NAMESPACE

* ok

## man

* ok

## NEWS

* This file should be parsable by `utils::news()`. Please make sure to
  add content to the NEWS file.

## vignette

* The vignette is informative. But it doesn't run when I try to run
  it, because the format is not in Rmd. Your R-chunk tags are not
  accurate. When a user runs the vignette, there needs to be some work
  done by the package to demonstrate it's usage. Currently nothing
  happens.


## R

* Why not just make a `TxDb` object from GTF files? Is there a reason you'd need to write a separate class for this? You could take a look at https://bioconductor.org/packages/release/bioc/vignettes/GenomicFeatures/inst/doc/GenomicFeatures.pdf.  Why do you need to use a `data.table` here? Does a TxDb object not provide sufficient functionality? 


```
library(GenomicFeatures)
> gff_file <- path("a.gtf")
> txdb <- makeTxDbFromGFF(gtf_file, format="gtf")
```

* I'm not sure why you are hardcoding the links, in `param.R`. You
  shouldn't be downloading files like this from the internet, without
  explicitly telling the user. This is a bad practice, if your tool is
  based on cufflinks, stringtie and other tools, what you should be
  doing is, adding a 'SystemsRequirements' section in your DESCRIPTION
  file.

	And letting users point the `/bin/program` files in a
    function. But the installation should be left to them.

```
prototype = list(
    OS2CUFFLINKS_URL = list(
        'LINUX' = paste0('http://cole-trapnell-lab.github.io/cufflinks/',
            'assets/downloads/cufflinks-2.2.1.Linux_x86_64.tar.gz'),

        'OSX' = paste0('http://cole-trapnell-lab.github.io/cufflinks/',
            'assets/downloads/cufflinks-2.1.1.OSX_x86_64.tar.gz')
    ),

    OS2STRINGTIE_URL = list(
        'LINUX' = paste0('http://ccb.jhu.edu/software/stringtie/dl/',
            'stringtie-1.3.3b.Linux_x86_64.tar.gz'),

        'OSX' = paste0('http://ccb.jhu.edu/software/stringtie/dl/',
            'stringtie-1.3.3b.OSX_x86_64.tar.gz')
    ),

    OS2TACO_URL = list(
        'LINUX' = paste0('https://github.com/tacorna/taco/releases/',
            'download/v0.7.0/taco-v0.7.0.Linux_x86_64.tar.gz'),

        'OSX' = paste0('https://github.com/tacorna/taco/releases/',
            'download/v0.7.0/taco-v0.7.0.OSX_x86_64.tar.gz')
    ),
```

* In utils.R, the function name `isFileExisted` doesn't convey the
  right meaning, please change the name of the function to accurately 

Please correct these issues/ answer the questions posted before I come back to you with another review. This will be an iterative process.

**Comment by nturaga** [comment]
> > Hi, I'll get back to you today. Thanks. Nitesh
> > […](#)
> 
> Hi @nturaga ,
> 
> Just checking in to make sure I didn't miss your note. You said that you will get back to me the day before yesterday, but I haven't seen any of your messages so far. Thanks.
> 
> Best,
> Peng

Please understand we

**Comment by pliu55** [comment]
Hi @nturaga,

Thanks for the review.  I will work on the issues you brought up. 

Best,
Peng

**Comment by nturaga** [comment]
Update:

* Add the way the package is installed in the vignette through Bioconductor. as well.  Installation instructions need to be given using the package `BiocManager`.

**Comment by nturaga** [comment]
Hi,

Try to issue another version bump and see if the same issue persists.

Best

Nitesh

**Comment by pliu55** [comment]
Hi @nturaga,

Sorry to bug you again.  I have been receiving WARNINGS from build reports as 

>  WARNING: R CMD check exceeded 5 min requirement

The issue confused me is that one time the warning was from bioc-issue-bot's OSX server and no warning from Windows server (please see the [build report for v0.99.10](http://bioconductor.org/spb_reports/pram_buildreport_20190117220211.html)), whereas another time it was from Windows server and no warning from OSX server (please see the [build report for v0.99.12](http://bioconductor.org/spb_reports/pram_buildreport_20190117224010.html)).  My code is identical between the two versions except different version numbers in DESCRIPTION and NEWS files.  If possible, could you please give me some suggestions on how to proceed regarding this issue?  I would be appreciated.  Thank you.

Best,
Peng

**Comment by pliu55** [comment]
Hi @nturaga,

Thanks again for your review.  It definitely helped improving my package and my skills in software development.  I made a point-by-point response below. Please feel free to let me know if any response is unclear or any part needs further improvement.

Best,
Peng


> # pram review
> ## R CMD build
> * ok
>
> ## R CMD INSTALL
> * ok
>
> ## DESCRIPTION
> * 'Description' section is not enough, think of the this like the abstract of a paper. Please elaborate.
>

I have the 'Description' section elaborated by adding biological background, software development motivation, and package functions.

>
> ## NAMESPACE
> * ok
>
> ## man
> * ok
>
> ## NEWS
> * This file should be parsable by `utils::news()`. Please make sure to add content to the NEWS file.
>

I have added content to the __NEWS__ file.  I have tested that it can be parsed by `utils::news()` on my Mac laptop.

>
> ## vignette
> * The vignette is informative. But it doesn't run when I try to run it, because the format is not in Rmd. Your R-chunk tags are not accurate. When a user runs the vignette, there needs to be some work done by the package to demonstrate it's usage. Currently nothing happens.
>

I have corrected the R-chunk tags.  Sorry about this mistake. Now, a user can run functions in the vignette and see output in the PDF file.  Please note that two functions, `runPRAM()` and `buildModel()`, did not run when building the vignette, because they depend on external software (which related to another issue you raised and I addressed below). Also, since examples presented in 
this vignette for `defIgRanges()`, `evalModel()`, `prepIgBam()`, and `selModel()` are identical to the ones listed in the man page documentation.  I marked `donttest{}` in the corresponding man page examples.  That is what the only NOTE from `R CMD BiocCheck` is about. I feel it would be redundant to run the same examples twice. Please let me know if you think it would be better to run them in man pages instead of in this vignette.

>
> ## R
> * Why not just make a `TxDb` object from GTF files? Is there a reason you'd need to write a separate class for this? You could take a look at https://bioconductor.org/packages/release/bioc/vignettes/GenomicFeatures/inst/doc/GenomicFeatures.pdf.  Why do you need to use a `data.table` here? Does a TxDb object not provide sufficient functionality?
>

Yes, there is a reason that I have to create a separate GTF class with a `data.table` object for transcript.  I need to evaluate a transcript's prediction accuracy by `data.table`.  This was implemented in `evalModel()` and associated functions (please see `evalModel(character, character)`, `calTpFn4Jnc()`, and `calFp4Jnc()` for details).  When users have predicted transcript models by my package, it would be of interest to know how accurate these models are. The `evalModel()` was implemented for this purpose.  By this function, users can compare their models with true transcripts, i.e., positive controls, to get precision and recall rates for their predictions on transcript splice junctions.  I did not find any similar function from TxDb object or `GenomicFeatures` that can calculate precision or recall rates for this feature. Therefore, I created a separate GTF class with a `data.table` object.

As a side node, I want to thank you for bringing this issue up, because it made me realize that I did not mention anything about `evalModel()` in the vignette.  I have added description for this important function in the vignette. Your suggestion also made me realized that the `ModelGTF` class is no longer in use.  I have removed this class and its associated test files.


>
> * I'm not sure why you are hardcoding the links, in `param.R`. You shouldn't be downloading files like this from the internet, without explicitly telling the user. This is a bad practice, if your tool is based on cufflinks, stringtie and other tools, what you should be doing is, adding a 'SystemsRequirements' section in your DESCRIPTION file. And letting users point the `/bin/program` files in a function. But the installation should be left to them.
>

I have added this dependency in the 'SystemsRequirements' section in DESCRIPTION.  I stopped automatically downloading external software by removing the `downloadAndUntar()` in __util.R__.  Instead, I kept the links and used them in error message to remind users where to download these softwares in __Param.R__'s `checkCufflinksBin()`, `checkCuffmergeRequiredBins()`, `checkStringTieBin()`, and `checkTacoBin()` functions.

>
> * In utils.R, the function name `isFileExisted` doesn't convey the right meaning, please change the name of the function to accurately
>

I changed the function name to `fileExists`.  It is an extension of the R function `file.exists()`. I hope that the new name conveys the right meaning.


>
> Please correct these issues/ answer the questions posted before I come back to you with another review. This will be an iterative process.

> Update:
> 
> * Add the way the package is installed in the vignette through Bioconductor. as well.  Installation instructions need to be given using the package `BiocManager`.
>

I have added Bioconductor installation instruction via using the package `BiocManager` in the vignette.

**Comment by nturaga** [comment]
@pliu55 I will go through your package in the next week and all the changes your made.

**Comment by nturaga** [comment]
@mtmorgan Regarding the setting of the new class `GTF`, I was wondering if you had any comments about this? Mainly because `TxDb` can be used.

**Comment by mtmorgan** [comment]
It seems like the basic uses are
```
txdb = GenomicFeatures::makeTxDbFromGFF("inst/extdata/gtf/gnc_v24_minus_chr18.gtf")
GenomicFeatures::transcripts(txdb)
GenomicFeatures::exons(txdb)
GenomicFeatures::intronsByTranscript(txdb)
...
```
There is also more specific functionality available via `select()`.

So a lot of functionality, especially in parsing the GTF file, has been duplicated. Of course it would be appropriate or expected to add additional functionality within pram, for instance coercing to a data table `as.data.table(exons(txdb))` and performing additional computation. But reusing existing infrastructure is much preferred to re-implementing new infrastructure.

**Comment by pliu55** [comment]
Hi @mtmorgan and @nturaga, thanks for your comments and suggestions on the `GTF` class and `txdb`. 

@nturaga, could you please let me know if there is any other aspect of this package you would like me to improve?  Thanks.

Best,
Peng

**Comment by nturaga** [comment]
# Review update

* Why do you still need `mclapply`? 

```
modelByMethod <- function(method, prm) {
    dt = managerdt(prm)
    nthr = nthreads(prm)
    if ( nthr == 1 ) {
        lapply(dt$fmdlbam, modelByChromOriBam, method, prm)
    } else if ( nthr > 1 ) {
        if ( Sys.info()[["sysname"]] == "Windows" ){
            snow = SnowParam(workers = nthr, type = "SOCK")
            bplapply(dt$fmdlbam, modelByChromOriBam, method, prm, BPPARAM=snow)
        } else {
            mclapply(dt$fmdlbam, modelByChromOriBam, method, prm, mc.cores=nthr)
        }
    }
}
```

I would rather you don't use mclapply at all, and replace that with a function taken from BiocParallel.

Otherwise, your package looks good to me.

**Comment by pliu55** [comment]
Hi @nturaga,  

Thanks for your feedback.  I will replace `mclapply` by `bplapply`.  

Regarding the `GTF` class, I understand Martin and your suggestions that it would be good not to introduce additional class unless necessary.  I will to think of a way to remove `GTF` class without affect the `evalModel()` and related functions.  At the moment, I am not sure how much time it may take.  Is there any time restraint on package revision? 

Best,
Peng

**Comment by lshep** [comment]
There is no set time frame.  We like to see updates within 2-3 weeks of leaving feedback.  We like to keep packages in the queue that are immediately ready for review and if the feedback was significant and you think the changes will take significant time we can temporarily close the issue and you can request the issue be reopened when the changes are ready.

**Comment by pliu55** [comment]
Hi @lshep, 

Thanks for your reply.  I will try to have an update that addresses the review within 2-3 weeks. 

Best,
Peng

**Comment by pliu55** [comment]
Hi @nturaga,

I have removed the `GTF` class and replaced `mclapply` by `bplapply`.  Could you please take a look of my package to see if there is anything I should improve? Thanks.

The __WARNINGS__ I received from the build results on Linux, Mac, and Windows are all due to 
```
* checking for future file timestamps ...Warning in file(con, "r") :
  cannot open URL 'http://worldclockapi.com/api/json/utc/now': HTTP status was '403 Site Disabled'
 WARNING
unable to verify current time
```

I think this __WARNINGS__ is because of connection issue from the build servers, not from my package.  Please let me know if I mis-understood or if you would like me to bump version of my package and re-do the build. Thanks

Best,
Peng

**Comment by nturaga** [comment]
Hi,

Thanks for removing the mclapply commands. The package looks much better. I will accept it.

One last suggestion, please remove the commented out lines.

**Comment by pliu55** [comment]
Hi @nturaga,

Thanks for your suggestions.   I have removed commented out lines from my package.  

The `timestamps` warning is gone this time, but the `WARNING: R CMD check exceeded 5 min requirement` warnings came back.  I guess it most likely because the testing servers were crowded with other jobs, because I didn't experience such warning before I removed commented out lines (please see [build report for version 0.99.15 here](
http://bioconductor.org/spb_reports/pram_buildreport_20190305222028.html)) and I don't think removing the commented out code will result in a longer R CMD check.  

In addition, I tried two version 0.99.16 ([build report](
http://bioconductor.org/spb_reports/pram_buildreport_20190319210127.html)) and 0.99.17 ([build report](
http://bioconductor.org/spb_reports/pram_buildreport_20190319220115.html)), which only differ in the version number and nothing else.  The Windows server was running fine for v0.99.16, but had a `5 min` warning for v0.99.17.  All the evidence made me suspect that the `5 min` warning is due to the server load, not my code.  I cc'ed @lshep here to see if any suggestion could be given.  Please let me know if you would like me to do another version bump and let the servers test my built again.  Thank you.

Best,
Peng

**Comment by nturaga** [comment]
I'm accepting the package because this doesn't show up on my end. Thanks

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pliu55.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pram")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pram

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
