### ISSUE TITLE
(inactive) PhosMap

### ISSUE THREAD

**Issue by ecnuzdd** [Bioconductor/Contributions#954]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ecnuzdd/PhosMap

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ecnuzdd** [comment]
Could you teach me how to solve this? Or give me an email of Bioconductor Core Member?




Best regards!
Dongdong Zhan
The Institute of Biomedical Sciences
East China Normal University
500 Dongchuan Road
Shanghai 200241, China
On 12/13/2018 21:21，bioc-issue-bot<notifications@github.com> wrote：

Dear @ecnuzdd ,

You (or someone) has already posted that repository to our tracker.

See #935

You cannot post the same repository more than once.

If you would like this repository to be linked to issue number: 954,
Please contact a Bioconductor Core Member.
I am closing this issue.

**Comment by mtmorgan** [comment]
Visit the original issue #935 and add a comment asking for it to be reopened because you have addressed the problems that were present with the original submission.

**Comment by ecnuzdd** [comment]
Many thanks for your reply!




Best regards!
Dongdong Zhan
The Institute of Biomedical Sciences
East China Normal University
500 Dongchuan Road
Shanghai 200241, China
On 12/13/2018 21:54，Martin Morgan<notifications@github.com> wrote：

Visit the original issue #935 and add a comment asking for it to be reopened because you have addressed the problems that were present with the original submission.

**Comment by ecnuzdd** [comment]
Dear Martin,

I have completely updated PhosMap R package, please help me active the issue #954 for test.

Many thanks!
