### ISSUE TITLE
BiocWorkflowTools

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/Contributions#96]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/grimbough/BiocWorkflowTools

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment]
Thank you for your submission.  Everything looks great; nice and straightforward.  

I'm not sure if it has to do with the F1000 formatting but it seems like if the Rmd file does not contain a table markdownTolatex fails. Is there a way to remedy this? 
If I copy your inst/example/f1000_software_example.Rmd  and remove the Table section and try to run the function, I get the following: 
`markdownToLatex("f1000_software_example.Rmd")`
Error in x[1]:x[2] : NA/NaN argument

**Comment by grimbough** [comment]
Hi lshep, 

Thanks for the comments.  I've added a patch that stops the code failing if no tables are present in the input document.

I'm not sure why it is currently failing to build on the Linux build machine, it passes fine on my test machines.  It looks like the error may be with a function in the rmarkdown package, is there anyway to see what versions are installed on the build machines?

**Comment by lshep** [comment]
I'll look into this today to see if I can get any insight on to why its failing on our linux build.

**Comment by lshep** [comment]
May I suggest importing the full rmarkdown library in the NAMESPACE,  or at least add the importFrom(rmarkdown, discover_rmd_resources).  My guess is that since this other rmarkdown function is called but not imported it cannot find it.

**Comment by grimbough** [comment]
I tried importing the whole `rmarkdown` package, but that didn't have any effect, which I guess is to be expected since `discover_rmd_resources()` isn't exported by it.

I also tried reverting everything back to the v.0.99.3 state since that was building fine, but it now produces the same error on the linux build machine.  Perhaps something has subtly changed in the last week on the build machine?

A closer look at the error message suggests the problem lies in [rmarkdown/html_resources.R](https://github.com/rstudio/rmarkdown/blob/f452167d5828d569597754aa33f559d9b1a9b510/R/html_resources.R#L332) with the statement `if (chunk_line < 0)` is returning `NA`, but that code hasn't changed recently.

I will keep digging, so I apologise for the Github spam since I can't reproduce this on any of my own machines for testing purposes.

**Comment by lshep** [comment]
Yes I have been following and investigating on our end as well.  There were some changes made last week so I am going through them now to see if I can track anything down.

**Comment by lshep** [comment]
I am so sorry for the inconvenience.  I have tracked down and fixed the issues. There was a missing application installation on our end.  Please try implementing your patch again.

**Comment by lshep** [comment]
Looks good. Sorry again for the confusion.  I am recommending the package be accepted.  You should get svn instructions within the next week.

**Comment by grimbough** [comment]
That's great.  Many thanks.
