### ISSUE TITLE
BioMM: Biological-informed Multi-stage Machine learning framework for phenotype prediction using omics data

### ISSUE THREAD

**Issue by Junfang** [Bioconductor/Contributions#963]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/transbioZI/BioMM

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Remember to increment the version number (to 0.99.1, 0.99.2, ...) to trigger automatic builds.

**Comment by nturaga** [comment]
#Update

## R

* Not all `print` statements are removed. Please check `resultReport.R`. There are still a few `print` statements left behind.

  Another piece of code which is unusual, what is the functionality of `print(plot(...))`. This is unnecessary.

* There are still some `which` statements you don't need. `which` creates a numeric index, which is not needed when subsetting a vector. 

* Please use a smaller example in the vignette using some mock data or example data, to showcase the functionality. The vignette should comprise of test use-cases which the user can successfully run and evaluate. 

You may also include the examples you have in a section, which say that these examples require significant compute resources. 

* As far as `bplapply` goes, you can consider also giving the user the choice of BPPARAM to use, if the function can be parallelized. `BIocParallel` also does the platform type checking for you already, you do not need to check `if(.Platform$OS.type` to choose between `windows` and Linux based platforms. 

The function should be ideally implemented with this interface in mind (from a user stand point).

```
param <- MulticoreParam(workers = 2)
pred_test <- predByCV(data, repeats, ....., BPPARAM = param)
```

The function could look like,

```
predByCV <- function(data, repeats, nfolds, FSmethod, cutP, fdr, FScore,
                     classifier, predMode, paramlist,
                     BPPPARAM = MulticoreParam())
{
    cvMat <- c()
    replist <- seq_len(repeats)
    for (reps in replist) {
        foldlists <- split(sample(nrow(data)), rep(seq_len(nfolds),
            length = nrow(data)))
        cvY <- rep(NA, nrow(data))
        cvEstimate <- bplapply(foldlists, function(fold) {
            trainData <- data[-fold, ]
            testData <- data[fold, ]
            predTest <- predByFS(trainData, testData, FSmethod, cutP, fdr,
                FScore, classifier, predMode, paramlist)
        }, BPPARAM = BPPARAM)
        cvY[unlist(foldlists)] <- unlist(cvEstimate)
        cvMat <- cbind(cvMat, cvY)
    }
```

Please make similar changes wherever applicable in other places you've used BiocParallel.

* If you are worried about efficiency of the package, then you can try to eliminate `return` calls at the end of your functions. R automatically returns as long as you declare the variable at the end of the function.

```
foo <- function(x = 2) {
    x* 2
}
```

**Comment by Junfang** [comment]
Dear @nturaga Thanks a lot for your review. I just have a question regarding the usage of 'MulticoreParam' on different platforms. Do I have to indicate the platform type in the examples of the documentation (.Rd files), also in the vignette? so that my package could pass all three Bioconductor platforms. As far as I have tested on windows,  'MulticoreParam' could not dispatch to 'Serial'.

**Comment by Junfang** [comment]
**Dear @nturaga Many thanks again, please see my reply below.**

> # Update
> ## R
> * Not all `print` statements are removed. Please check `resultReport.R`. There are still a few `print` statements left behind.
>   Another piece of code which is unusual, what is the functionality of `print(plot(...))`. This is unnecessary.

**Now 'print' statements are removed, except that print(plot(...)) is still used. The reason is that I have to call print() explicitly to draw a plot inside a function when using ggplot2 plot. See also https://www.rdocumentation.org/packages/ggplot2/versions/3.1.0/topics/print.ggplot**

> * There are still some `which` statements you do not need. `which` creates a numeric index, which is not needed when subsetting a vector.

**Unnecessary 'which' statements were now removed. However, 'which' statements in `exploreStat.R` are not removed since its derived numeric index will be used for computing the overlapping numeric index from another vector. e.g. See line 126, line 142 in `exploreStat.R`.**

> * Please use a smaller example in the vignette using some mock data or example data, to showcase the functionality. The vignette should comprise of test use-cases which the user can successfully run and evaluate.
>
> You may also include the examples you have in a section, which say that these examples require significant compute resources.

**Thank you for your suggestion. The vignette is now updated using smaller datasets and models. In addition, a subsection was included to describe the computational consideration.**
 
> * As far as `bplapply` goes, you can consider also giving the user the choice of BPPARAM to use, if the function can be parallelized. `BIocParallel` also does the platform type checking for you already, you do not need to check `if(.Platform$OS.type` to choose between `windows` and Linux based platforms.
> 
> The function should be ideally implemented with this interface in mind (from a user stand point).
> 
> ```
> param <- MulticoreParam(workers = 2)
> pred_test <- predByCV(data, repeats, ....., BPPARAM = param)
> ```
> The function could look like,
> 
> ```
> predByCV <- function(data, repeats, nfolds, FSmethod, cutP, fdr, FScore,
>                      classifier, predMode, paramlist,
>                      BPPPARAM = MulticoreParam())
> {
>     cvMat <- c()
>     replist <- seq_len(repeats)
>     for (reps in replist) {
>         foldlists <- split(sample(nrow(data)), rep(seq_len(nfolds),
>             length = nrow(data)))
>         cvY <- rep(NA, nrow(data))
>         cvEstimate <- bplapply(foldlists, function(fold) {
>             trainData <- data[-fold, ]
>             testData <- data[fold, ]
>             predTest <- predByFS(trainData, testData, FSmethod, cutP, fdr,
>                 FScore, classifier, predMode, paramlist)
>         }, BPPARAM = BPPARAM)
>         cvY[unlist(foldlists)] <- unlist(cvEstimate)
>         cvMat <- cbind(cvMat, cvY)
>     }
> ```
> Please make similar changes wherever applicable in other places you have used BiocParallel.

**I have now adapted the usage of MulticoreParam() in all related functions.**

> * If you are worried about efficiency of the package, then you can try to eliminate `return` calls at the end of your functions. R automatically returns as long as you declare the variable at the end of the function.
> 
> ```
> foo <- function(x = 2) {
>     x* 2
> }
> ```

**Many thanks for the hint. I updated some functions accordingly.**

**Comment by nturaga** [comment]
# Update

* Please fix the issue in the vignette,

```
> result <- BioMM(trainData=studyDataSub, testData=NULL,
+                 stratify="chromosome", pathlistDB, featureAnno,
+                 restrictUp=10, restrictDown=200, minPathSize=10,
+                 supervisedStage1, typePCA="regular",
+                 resample1="BS", resample2="CV", dataMode="allTrain",
+                 repeatA1=20, repeatA2=1, repeatB1=20, repeatB2=1,
+                 nfolds=10, FSmethod1=NULL, FSmethod2=NULL,
+                 cutP1=0.1, cutP2=0.1, fdr1=NULL, fdr2=NULL, FScore=param1,
+                 classifier1, classifier2, predMode1, predMode2,
+                 paramlist1, paramlist2, innerCore=param2,
+                 outFileA2=NULL, outFileB2=NULL)
[1] "Chromosomes: "
 [1] "1"  "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "2"  "20" "21" "22" "3"  "4"  "5"  "6"
[20] "7"  "8"  "9"
[1] "Summary stat of # probes in each Chr: "
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  27.00   64.00   86.00   90.86  118.00  216.00
Error in as.integer(mc.cores) :
  cannot coerce type 'S4' to vector of type 'integer'
```

Another way of looking at this,

```

Quitting from lines 163-184 (BioMMtutorial.Rmd)
Error in as.integer(mc.cores) :
  cannot coerce type 'S4' to vector of type 'integer'
```

Update the version number so that the build runs after you fix the error.

**Comment by Junfang** [comment]
Dear @nturaga Thanks for your quick update. I tried to replicate this issue on several different machines (windows, linux and mac) but I did not get any error. I was wondering if you would have any problem when running the following example?

```
## Load data  
methylfile <- system.file('extdata', 'methylData.rds', package='BioMM')  
methylData <- readRDS(methylfile)  
dataY <- methylData[,1]
## select a subset of genome-wide methylation data at random
methylSub <- data.frame(label=dataY, methylData[,c(2:2001)])  
trainIndex <- sample(nrow(methylSub), 30)
trainData = methylSub[trainIndex,]
testData = methylSub[-trainIndex,]
library(ranger) 
library(BiocParallel)
param1 <- MulticoreParam(workers = 1)
param2 <- MulticoreParam(workers = 20)
predY <- predByBS(trainData, testData, 
                  dataMode='allTrain', repeats=50,
                  FSmethod=NULL, cutP=0.1, 
                  fdr=NULL, FScore=param1, 
                  classifier='randForest',
                  predMode='classification', 
                  paramlist=list(ntree=300, nthreads=10),
                  innerCore=param2)  
testY <- testData[,1]
accuracy <- classifiACC(dataY=testY, predY=predY)
print(accuracy)  
```

**Comment by Junfang** [comment]
Great,  thank you so much for the time and effort taken to review our package!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Junfang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BioMM")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BioMM

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
