### ISSUE TITLE
philr

### ISSUE THREAD

**Issue by jsilve24** [Bioconductor/Contributions#97]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jsilve24/philr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
This package seems to be in great shape with well-documented and
organized code. I have only limited comments.

1. For standard licenses, e.g., GPL-3, a LICENSE.txt file is not
   required
   
2. Please clarify the role of the 'docs' folder -- this will not be
   installed on user systems, and seems to be extraneous to the R
   package?

3. Tight `for` loops such as at weighted_ILR.R:116 make one nervous
   that the code is not fully vectorized. Is that the case here, or
   can distp.pari be implemented as a matrix operation rather than
   iteration over rows & columns?

**Comment by jsilve24** [comment]
Regarding your points in order:

1.  I removed the license file
2.  docs folder currently holds the [github.io site](http://jsilve24.github.io/philr/) for my package (same format as the [ggtree package](https://github.com/GuangchuangYu/ggtree) and [ggtree site](https://guangchuangyu.github.io/ggtree/), note ggtree is on bioconductor). As you mention, this folder is specified to be ignored by the .Rbuildignore file. I could also move these files to a gh-pages branch but I felt this approach was easier for me. Let me know if this is acceptable or if not I can change it. 
3. Very true, thank you for catching that. the function disp.pair and distp where hold outs from earlier version of the code. I just went ahead and completely removed these functions. 

Please let me know what else is needed to get philr included in the next bioconductor release.
