### ISSUE TITLE
doseR submission

### ISSUE THREAD

**Issue by avastermark19** [Bioconductor/Contributions#992]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/WaltersLab/doseR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please make sure that the inputs / outputs of your package accept [standard Bioconductor objects][1], including [SummarizedExperiment][2].

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/
[2]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by lshep** [comment]
Please fix the ERROR/WARNING/NOTES from the above build report,  and address the issue as pointed out by @mtmorgan above that the package should work with standard Bioconductor objects, namely SummarizedExperiment for sequencing data.  
Once these are corrected,  ensure your [webhook is intialized](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook), kick off a new build with a version bump in the DESCRIPTION,  and I will proceed with a more formal review of the package. 
Thank you and I look forward to working with you on getting your package accepted into Bioconductor.

**Comment by lshep** [comment]
**GENERAL:**
- [ ] As @mtmorgan pointed out - The package should be updated for all inputs
and outputs to work with [standard Bioconductor objects][1], including [SummarizedExperiment][2].

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/
[2]: https://bioconductor.org/packages/SummarizedExperiment


**BUILD REPORT:**
Clean! Okay! 



**DESCRIPTION:**
- [ ] Need full name in Author field not shorthand
- [ ] Expand on Description. It should be more informative, almost like a mini
abstract to describe the functionality of the package. 
- [ ] Remove `lazyData: true` we rarely find this useful and can actually slow
down a package installation.



**NAMESPACE:**
- [ ] Don't use `exportPattern("^[[:alpha:]]+")` which exports everything. Be
selective about what you are exposing to the user interface. 


**index.md**
- [ ] For what its worth - if you change the name to README.md it will show as a
top level page in your github. Bioconductor ignores this file but just wanted to
make mention. 


**NEWS:**
- [ ] Not formatted correctly. See `?news` and [news][3]

[3]: https://bioconductor.org/developers/package-guidelines/#news



**Vignette:**
- [ ] Remove the `.R` and `.html` files in the vignette directory. The are not
needed and regenerated on the build.  Remember that this should be a `git rm` 
- [ ] Also optional but for what its worth - The name of the vignette is what
you would type in the `vignette()` in R - It is more intuitive to have just the
package name `doseR` rather `doseR_vingnette` - again entirely optional 
- [ ] Please include full name 
- [ ] We encourage the use of BiocStyle but this is also optional
- [ ] We encourage a table of contents
- [ ] Please include reference information for the example data utilized. 
- [ ] See general comment about updating to be able to use common Bioconductor
input/output.  You can additional support your current implementation but we
will require it to also work with the standard RNA-seq objects popularly used in
Bioconductor.  
- [ ] Remove the installing from local file sections - This should not be
needed. 
- [ ] Are mclust and edgeR required for using your package? If the
imports/depends are specified right in the NAMESPACE/DESCRIPTION you should not
have to load these in addition to your package. 


**data:**
 - [ ] Update to use a Bioconductor formated object.



I'm going to wait to review the code and the man pages until the package has been updated to use SummarizedExperiment.   Please work on updates and kick off a version bump to generate new build reports.  When the above has been addressed please comment back here for a re-review.

**Comment by avastermark19** [comment]
Could you (`or the applicable reviewer) go ahead with a formal in depth
review of doseR package?
The only error  is:
```
WARNING: check time exceeded 5 min.
```
Could we ignore this point for now?

**Comment by lshep** [comment]
Yes I will review the package.  I will advise on the warning in the review.  You can expect in within the next week.

**Comment by avastermark19** [comment]
Hello Bioconductor/Contributions
i fixed something and now it builds without any problems again, pleae
reviev 0.99.7, not any older
Thanks!! Ake

**Comment by avastermark19** [comment]
Hi Lori Shepherd / current reviewer
I was hoping to get some feedback by the end of this week. But if you need
more time, that's fine too. Let me know if there are any questions.
Aake
KCMO

**Comment by lshep** [comment]
I'm sorry for the delay - We try to get to reviews within 2 weeks of a clean build/request for a review and I did mention I should have something by the end of this week - I got tied up with some other pressing issues but I will work on the review over the weekend and have something posted at latest Monday.

**Comment by avastermark19** [comment]
That's fantastic news.
Take the time you need.
Ake

**Comment by lshep** [comment]
Thank you for updating to use a SummarizedExperiment object.   A few minor points below:

misc:
- [ ] There are two .R files in the top level directory - these should be moved
or removed? 


Namespace:
- [ ] You shouldn't need to export SummarizedExperiment or colData unless you
created your own unique functions for these.  If the package is specified as an
import which it is, the functions will be available for use. 


Man page:

- [ ] Don't use shorthand - for example the se arugment of the simpleFilter -
  `An se object` - Please say `summarizedExperiment` as naive users may not make
  the connection.  Just one example please fix thoroughout. 

For What its worth for future packages  -  its very hard to read your code with no indenting for functions, or indicating loops/clauses/brackets -  it would be worth looking at https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Tidying-and-profiling-R-code  or the formatR package.  There is no need to convert this package but it would be really helpful in the future. So for example just a dummy example with some sudo code
```
MyFun <-  function(argument1, argument2=FALSE){
     stopifnot(is.character(argument1))
     n <- 3
     while(n > 0){
            #do some code in the loops
             n <- n - 1
      }
}
```
So you can see in the above where the functions begin and end -  and where the loops begin and end - etc....  


Please clean up the above issues and comment back here when done.

**Comment by avastermark19** [comment]
Hi Lori
1. I removed the 2 .R files.
2. On my computer, removing the export('SummarizedExperiment','colData')
from NAMESPACE file causes problem in the vignette.
3. I replaced SE by SummarizedExperiment.
4. I'm keeping the 80x50 char formatting to avoid bioccheck error, (it's
not the original formatting.)
Hope this (0.99.14) is ready for preliminary acceptance now.!
Thanks!
Aake

**Comment by avastermark19** [comment]
Hi Lori
1. I removed the 2 .R files.
2. On my computer, removing the export('SummarizedExperiment','colData')
from NAMESPACE file causes problem in the vignette.
3. I replaced SE by SummarizedExperiment.
4. I'm keeping the 80x50 char formatting to avoid bioccheck error, (it's
not the original formatting.)
Hope this (0.99.14) is ready for preliminary acceptance now.!
Thanks!
Aake

**Comment by lshep** [comment]
Since the `SummarizedExperiment`  comes from the `SummarizedExperiment` package,  it would be better to remove `export SummarizedExperiment colData` from the NAMESPACE as these are not your functions. To fix the vignette include `library(SummarizedExperiment)` when you do `library(doseR)`.   Please make this change and then I will accept.

**Comment by avastermark19** [comment]
done...
0.99.15
Aake

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/avastermark19.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("doseR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/doseR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
